### ISSUE TITLE
配置文件的 `"vectorMaxProcess": 15,` 不起作用.

### ISSUE THREAD

**Issue by xrkk** [labring/FastGPT#1001]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**

配置文件的 `"vectorMaxProcess": 15,` 不起作用.

**复现步骤**

修改配置 `vectorMaxProcess` 的值为 `16`.

在本地部署最新代码，在 [generateVector.ts](https://github.com/labring/FastGPT/blob/main/projects/app/src/service/events/generateVector.ts) 的 `generateVector()` 中添加日志, 在 `// get training data` 前面添加如下日志: 
```ts
import * as process from 'process';

const pid = process.pid;
console.log(`=== queue: ${pid}: ${global.vectorQueueLen}/${max}`)
``` 

用 `pnpm dev` 启动, 部分运行日志如下:
```
=== queue: 2910: 2/16
mongo start connect
mongo connected
pg connected
init pg successful
=== queue: 3021: 1/10
=== queue: 3021: 2/10
=== queue: 3021: 3/10
=== queue: 3021: 4/10
=== queue: 3021: 5/10
=== queue: 3021: 6/10
=== queue: 3021: 7/10
=== queue: 3021: 8/10
=== queue: 3021: 9/10
=== queue: 3021: 10/10
System Version: 4.7
{...系统配置...}
[INFO] 2024-03-15 02:33:36 [QA Queue] Done
default team exist new ObjectId("65d5a6904f18d376249c7209")
root user init: { username: 'root', password: '12345678' }
[INFO] 2024-03-15 02:33:38 [Vector Queue] Start
=== queue: 3021: 4/16
[INFO] 2024-03-15 02:33:38 [Vector Queue] Finish {"time":2421}
[INFO] 2024-03-15 02:33:40 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:40 [Vector Queue] Finish {"time":1669}
[INFO] 2024-03-15 02:33:42 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:42 [Vector Queue] Finish {"time":1994}
[INFO] 2024-03-15 02:33:44 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:44 [Vector Queue] Finish {"time":1727}
[INFO] 2024-03-15 02:33:45 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:45 [Vector Queue] Finish {"time":1594}
[INFO] 2024-03-15 02:33:47 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:47 [Vector Queue] Finish {"time":1363}
[INFO] 2024-03-15 02:33:48 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:48 [Vector Queue] Finish {"time":1422}
[INFO] 2024-03-15 02:33:49 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:49 [Vector Queue] Finish {"time":1166}
[INFO] 2024-03-15 02:33:51 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:51 [Vector Queue] Finish {"time":1299}
[INFO] 2024-03-15 02:33:52 [Vector Queue] Start
=== queue: 3021: 1/16
[INFO] 2024-03-15 02:33:52 [Vector Queue] Finish {"time":1165}
```

日志中可以看到, 队列中所有进程都是同一个. 而在服务器端 (通过 xinference 的本地部署) 的 create_embedding() 接口也是 **挨个** 调用的.

> xinference 本地部署没问题. 自己用脚本调用 xinference 本地部署的 create_embedding() 接口, 单进程调用时 xinference 的处理频率比 FastGPT 调用时要快很多，多进程调用时更是快到飞起。

**预期结果**

预期：FastGPT 应该启动 16 个进程，所有进程同时向 xinference 发起 create_embedding() 请求。

**相关截图**

日志添加截图如下：
![image](https://github.com/labring/FastGPT/assets/46306065/efc43773-53fb-464d-b3b7-548a554070a6)

**Comment by c121914yu** [comment]
=== queue: 3021: 10/10 不是10个了么

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/6e983476-192f-45a1-a41f-e44e0a37b224)
不知道你怎么测的，我导入一个文件，就已经同时进行了15组请求。

**Comment by xrkk** [comment]
@c121914yu 感谢您的回复。我找到原因了。

因为我之前一次性上传了超多文档，导致 dataset.trainings 条目超过 100万, 服务器在 data = MongoDatasetTraining.findOneAndUpdate() 的时间就超过了1秒钟. 

通过以下方式解决了此问题: 修改文件 `packages\service\core\dataset\training\schema.ts`，添加以下索引
```
    TrainingDataSchema.index({ weight: -1 });
    TrainingDataSchema.index({ lockTime: 1, mode: 1 });
```

**Comment by 704572066** [comment]
> dataset.trainings

为什么我的mongodb中的dataset.trainings表一直是空的，dataset.datas是有数据的
