### ISSUE TITLE
已配置向量模型，但是处理知识库的时候，还是使用默认的text-embedding-ada-002，然后报错显示不可用

### ISSUE THREAD

**Issue by gubinjie** [labring/FastGPT#1002]
配置文件中已配置：
![image](https://github.com/labring/FastGPT/assets/37869445/4020bfb2-aaa7-4d69-84a2-fa762df705b0)
并在页面索引模型也是配置的，
![image](https://github.com/labring/FastGPT/assets/37869445/c3068256-1ad4-4388-a449-cdda93cda9f3)
但是最终再上传文本知识库的时候，后台报错。
![Uploading image.png…]()
请问还需要修改什么地方吗？

**Comment by gubinjie** [comment]
![image](https://github.com/labring/FastGPT/assets/37869445/ea2b30eb-1a4b-46af-945d-9d7cc2d3e3db)

**Comment by 0x5c0f** [comment]
知识库需要在你修改模型后重新创建，不然还是会使用原来的

**Comment by gubinjie** [comment]
他循环报错：
![image](https://github.com/labring/FastGPT/assets/37869445/ff67e3cf-0fbd-49f8-9812-3653086553fb)

**Comment by c121914yu** [comment]
> 他循环报错： ![image](https://private-user-images.githubusercontent.com/37869445/313054302-ff67e3cf-0fbd-49f8-9812-3653086553fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzgzNzYsIm5iZiI6MTcxMDczODA3NiwicGF0aCI6Ii8zNzg2OTQ0NS8zMTMwNTQzMDItZmY2N2UzY2YtMGZiZC00OWY4LTk4MTItMzY1MzA4NjU1M2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA1MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwOGUzMzk5MDg5NjY0OWM5Mjc1NTQ4ZWRmZDg0MWQ5YzhiMjEyNDkzMjVhMGNkZjQwM2IxNDg3MjRmMjhjM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DumAXnc-iOmf-8mQkYjOB3-4VQNyv_MJxSBP1aKjBks)

模型api地址不对

**Comment by gubinjie** [comment]
@c121914yu 这个保存是在我知识库做文件上传，上传文件完成之后他就一直循环报这个问题。
我也单独调用向量模型是没有问题的。
![image](https://github.com/labring/FastGPT/assets/37869445/48c1ae03-d682-4eb2-9eb8-5791ce971423)

我在上传完成之后，PG库里面modeldata是空。

**Comment by c121914yu** [comment]
> @c121914yu 这个保存是在我知识库做文件上传，上传文件完成之后他就一直循环报这个问题。 我也单独调用向量模型是没有问题的。 ![image](https://private-user-images.githubusercontent.com/37869445/313573616-48c1ae03-d682-4eb2-9eb8-5791ce971423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTM5ODksIm5iZiI6MTcxMDgxMzY4OSwicGF0aCI6Ii8zNzg2OTQ0NS8zMTM1NzM2MTYtNDhjMWFlMDMtZDY4Mi00ZWIyLTllYjgtNTc5MWNlOTcxNDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAyMDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YWQxM2ZjZDFkNDcwZjEyMTA3ZjFhZTkxZGFjMDI0ZTgzN2NhNjJmNzMyYmY3MzlhNDdlYTU2ZTg0OGY5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXjgvgn1Zmd8SOIMQ4jDMNKFDHECCo7J53j-AzxjCbA)
> 
> 我在上传完成之后，PG库里面modeldata是空。

你api地址填错了吧

**Comment by cloudtuotuo** [comment]
知识库建库的时候用的是 ada-002，这个向量配置会一直生效，无法修改，除非重新建库

可以在配置文件里再增加一个 ada-002 的配置，这样可以保证两种向量库都不再报错
