### ISSUE TITLE
[ERROR] 2024-03-15 11:14:06 sse error: 404 <!DOCTYPE html><html lang="zh"><head

### ISSUE THREAD

**Issue by gubinjie** [labring/FastGPT#1004]
你好，这个他一直循环跑出来咋办哟？
![image](https://github.com/labring/FastGPT/assets/37869445/55d0a35b-76ea-415a-a1cc-9ec586f222db)

**Comment by c121914yu** [comment]
解决404问题

**Comment by SuiKevin** [comment]
出现同样的问题，不知道是什么报错的404

**Comment by c121914yu** [comment]
> 出现同样的问题，不知道是什么报错的404 是在知识库使用问题拆分模式上传文件时出现的

向量模型404
