### ISSUE TITLE
分享链接加上可点击查看原始文件

### ISSUE THREAD

**Issue by weijy008** [labring/FastGPT#1005]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

发布应用采用免登录窗口方式进行分享给内部使用时，回答的问题引用没有可点击查看原始文件的按钮，请求在发布应用时加上可选项：是否允许查看原始文件。

**应用场景**

我了解在分享链接时是为了考虑内部知识库数据安全性的问题，但我们如果都是在内部使用时，应可以查看到引用中点击查看原始文件，所以在发布应用时，可以加上一个选项：是否允许查看原始文件，这样可以选择分享出去的链接是否允许查看到原始文件，即保留了数据安全性的考虑，又能满足有些内部使用时确实需要查看原始文件的问题

**相关示例**

目前默认是不允许查看原始文件，图示如下：
![image](https://github.com/labring/FastGPT/assets/40796961/b15e47cd-a4f4-4a52-9c98-be9ece00e1b0)

而通过应用立即对话进行的问题回答中引用是可以点击查看原始文件的，如下：
![image](https://github.com/labring/FastGPT/assets/40796961/7c61e1ba-6b6d-465a-a61c-a1c89339a30d)

**Comment by JinCheng666** [comment]
#974 与我的问题一致。暂时还没得到回复

**Comment by c121914yu** [comment]
> #974 与我的问题一致。暂时还没得到回复

已回复，后续在974讨论

**Comment by zhapi1780** [comment]
我也有类似需求，不知道现在有没有解决

**Comment by sdytzjp** [comment]
同问
