### ISSUE TITLE
api key功能无法使用

### ISSUE THREAD

**Issue by Riofd** [labring/FastGPT#1007]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
我按照docker-compose 的部署教程成功在自己服务器上搭建了fastGPT，在网页中能够正常添加数据库和使用ai对话，但是无法使用fastGPT的api访问功能，同时我也测试了作者提供的在线版本的fasgGPT，发现其提供的api是能够正常使用的。
**复现步骤**

**预期结果**

**相关截图**
这是在自己搭建的fastgpt下使用ai对话功能表现正常的截图：
![image](https://github.com/labring/FastGPT/assets/42333296/b2d4c927-27cb-4725-82a8-860afb8f0ba9)
这是在chatgpt-next-web中使用自己搭建的fastGPT接口的结果：
![image](https://github.com/labring/FastGPT/assets/42333296/67246a96-a59a-4d19-9ddc-32846b32980c)
这是使用在线版本的fastgpt[fastgpt.in](https://api.fastgpt.in/api)提供的接口能够正常访问的截图：
![image](https://github.com/labring/FastGPT/assets/42333296/10f65743-ed73-4501-8967-62b56205936c)

**Comment by c121914yu** [comment]
这个是你部署问题吧，都是一套代码~

**Comment by Riofd** [comment]
谢谢您的回复，我部署的时候完全按照教程来的呀，只是改了fastgpt容器映射到主机的端口。我想知道本地部署的fastgpt想使用api功能对于服务器端口或者其他配置有要求吗，会不会是这个影响了

**Comment by c121914yu** [comment]
> 谢谢您的回复，我部署的时候完全按照教程来的呀，只是改了fastgpt容器映射到主机的端口。我想知道本地部署的fastgpt想使用api功能对于服务器端口或者其他配置有要求吗，会不会是这个影响了

可能是你访问路径问题。可以看看日志。

**Comment by Riofd** [comment]
谢谢，我看了一下fastGPT的日志没有任何报错，我又试了一下用通用key是可以正常访问到知识库的，现在我怀疑是不是对话应用配置有什么需要注意的地方，目前来看只有用应用特定key会出现访问不了的情况

**Comment by Riofd** [comment]
我后来发现在api地址后面加上 /v1/chat/completions，例如"http://xx.xx.xx.xx:3000/api/v1/chat/completions"就能通过curl正常获取对话结果了

**Comment by c121914yu** [comment]
> 我后来发现在api地址后面加上 /v1/chat/completions，例如"http://xx.xx.xx.xx:3000/api/v1/chat/completions". 就能通过curl正常获取对话结果了

这个就是接口地址。

**Comment by Riofd** [comment]
不好意思，我再请教一下，我现在改了上面的那个api地址过后还是没办法在chatgpt-next-web中正常对话，报错还是跟上面的截图一样，我想请问一下这是什么原因呢？

**Comment by Riofd** [comment]
我发现问题了，界面中给出的是base url，文档中有详细的说明，再次谢谢作者的工作和回复。

**Comment by GGSCHWEIN** [comment]
请问chatgpt-next-web的接口地址应该用哪个呢
