### ISSUE TITLE
HTTP 模块请求地址只支持全局变量，外部参数输入的变量不识别。

### ISSUE THREAD

**Issue by zhaobingxu19** [labring/FastGPT#1010]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
HTTP 模块请求路径填写外部参数输入的参数时不识别；
目前在具体使用中发现只有全局变量可以使用；
**复现步骤**
![image](https://github.com/labring/FastGPT/assets/82586081/1bb81b6e-c86f-4b0b-971e-cf30d13a6176)

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
4.7支持下
