### ISSUE TITLE
本地安装的环境，能否不用docker的方式打包和运行？

### ISSUE THREAD

**Issue by maomao-bj** [labring/FastGPT#1015]
请问，因为环境原因，无法使用docker。能否不用docker的方式，改为直接运行。

**Comment by huluohu** [comment]
那不就是直接源码跑吗？源码就在这里。

**Comment by c121914yu** [comment]
得熟悉下nextjs，需要修改下next.config.json文件。暂时无教程~

**Comment by huluohu** [comment]
其实参考dockerfile就差不多啦
