### ISSUE TITLE
API 请求里面的 variables: 模块变量，怎么在http 模块里面使用类

### ISSUE THREAD

**Issue by shan-vvv** [labring/FastGPT#1016]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
![5296efc23dee8cbbed14e94d9966210](https://github.com/labring/FastGPT/assets/66903931/800f652c-cb74-4530-baaa-26a6dc9fd4c3)
这里传入的这个模块变量，怎么在http 模块里使用？
![5cf828bc266be10c2e07e7049975302](https://github.com/labring/FastGPT/assets/66903931/36c0a56b-7c65-4d9b-b999-f7da1c23175e)
我在这里直接写这个变量，
![企业微信截图_17108147406684](https://github.com/labring/FastGPT/assets/66903931/390f2bb8-4daf-4c9d-a85e-cfa11080c86b)
这个变量并没有被替换
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
传 variables 里的 key
