### ISSUE TITLE
缺少文件时报错导致进程退出

### ISSUE THREAD

**Issue by LinuxSuRen** [labring/FastGPT#1017]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**

**复现步骤**
* 采用 Helm 的方式安装，地址为：docker.io/surenpi/fastgpt:0.1.0
  * 缺少 pluginTemplates 目录
* 使用默认用户登录
* 主容器退出

**预期结果**
有缺少文件时，主进程不退出

**相关截图**
![image](https://github.com/labring/FastGPT/assets/1450685/038837b5-1b3c-4913-b189-69622d9c88ed)

**Comment by c121914yu** [comment]
没启用 mongodb 副本集
