### ISSUE TITLE
与gemma:2b对接，相应非常慢

### ISSUE THREAD

**Issue by taoshanghu** [labring/FastGPT#1018]
环境：
系统：rocky:9
物理主机：40核  128G  400G ssd磁盘 独占

fastgpt: v4.6.8
one-api : 0.6.1
ollama: 0.1.27
m3e: registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest
LLM: gemma-2b

部署后 每次通过AI 提问 要50秒以上才能回复， 这还是我一个人操作，这个速度有没有优化的空间？或者是LLM不符

**Comment by c121914yu** [comment]
这个和 fastgpt 没关系呢。。模型问题得找模型本身。
