### ISSUE TITLE
接口报错后，页面无法中断，后台日志一直重复发送请求，刷新页面依旧

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#1021]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
V4.6.9

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
如题：
<img width="757" alt="Screenshot 2024-03-20 at 00 02 27" src="https://github.com/labring/FastGPT/assets/36452456/9dc272e3-7310-4462-b656-34e750084c6b">

只有第一条消息是我发送的，下面的四条在我刷新页面后自己出现了
<img width="1251" alt="Screenshot 2024-03-20 at 00 06 24" src="https://github.com/labring/FastGPT/assets/36452456/f87f1801-e7bd-407d-8c18-dea83cba1061">

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
有录屏操作么

**Comment by bincooo** [comment]
https://www.1micro.top/alist/d/Screen%20Recording%202024-03-26%20at%2011.01.30%202.mov

**Comment by bincooo** [comment]
[video](https://www.1micro.top/alist/d/1.mov)
<video width="320" height="240">
   <source src="https://www.1micro.top/alist/d/1.mov"></source>
</video>

**Comment by c121914yu** [comment]
不知道要怎么才能复现，能提供例子么
