### ISSUE TITLE
如何用nginx代理发布后的应用，如代理此地址http://172.10.0.xxx:3020/chat/share?shareId=a0rqbwmvzo7p41a0rlpetmyl

### ISSUE THREAD

**Issue by Andy1018** [labring/FastGPT#1024]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
如何用nginx代理发布后的应用，如代理此地址http://172.10.0.xxx:3020/chat/share?shareId=a0rqbwmvzo7p41a0rlpetmyl
**复现步骤**

**预期结果**
可用nginx代理，发布的应用
**相关截图**

**Comment by c121914yu** [comment]
不行的，只能代理到host。 否则会无法加载资源。

**Comment by cloudtuotuo** [comment]
可以
![image](https://github.com/labring/FastGPT/assets/37918843/24647cd4-8a8a-4b06-b2a9-68f8fc0f7b61)

**Comment by Andy1018** [comment]
@cloudtuotuo 谢谢。不用 location 匹配 /  ,匹配 /chat/share有解决方案吗？

**Comment by cloudtuotuo** [comment]
> @cloudtuotuo 谢谢。不用 location 匹配 / ,匹配 /chat/share有解决方案吗？

这个只能问AI了。。。

**Comment by sdytzjp** [comment]
> 可以 ![image](https://private-user-images.githubusercontent.com/37918843/314394314-24647cd4-8a8a-4b06-b2a9-68f8fc0f7b61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTA4OTksIm5iZiI6MTcxOTk5MDU5OSwicGF0aCI6Ii8zNzkxODg0My8zMTQzOTQzMTQtMjQ2NDdjZDQtOGE4YS00YjA2LWIyYTktNjhmOGZjMGY3YjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3MDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NWJlYjViYTcwY2M5ODEyODM4NDEwYWQ2M2ExMDQ2MjE1MmViNjEyOWY2YmE0YWZiNGVkZDgzMzIxYjA5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2PWqnJaikZSeWyDRX7Q7b72UCrZj35l8RnuMBFX-0iQ)

你好，请教下：
1、你这个nginx配置为什么我不生效，输入http://ip:80后直接打开nginx报错界面
2、你做这个反向代理的目的是什么？这种方式仍然无法解决登陆问题，仍然会造成非法用户访问

**Comment by sdytzjp** [comment]
> 可以 ![image](https://private-user-images.githubusercontent.com/37918843/314394314-24647cd4-8a8a-4b06-b2a9-68f8fc0f7b61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTA4OTksIm5iZiI6MTcxOTk5MDU5OSwicGF0aCI6Ii8zNzkxODg0My8zMTQzOTQzMTQtMjQ2NDdjZDQtOGE4YS00YjA2LWIyYTktNjhmOGZjMGY3YjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3MDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NWJlYjViYTcwY2M5ODEyODM4NDEwYWQ2M2ExMDQ2MjE1MmViNjEyOWY2YmE0YWZiNGVkZDgzMzIxYjA5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2PWqnJaikZSeWyDRX7Q7b72UCrZj35l8RnuMBFX-0iQ)

你好，请教下：
1、你这个nginx配置为什么我不生效，输入http://ip:80后直接打开nginx报错界面
2、你做这个反向代理的目的是什么？这种方式仍然无法解决登陆问题，仍然会造成非法用户访问

**Comment by Timerunning** [comment]
> @cloudtuotuo 谢谢。不用 location 匹配 / ,匹配 /chat/share有解决方案吗？

你好，这个问题你找到解决办法了吗
