### ISSUE TITLE
私有镜像打包部署运行后报错

### ISSUE THREAD

**Issue by aqzwy** [labring/FastGPT#1026]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
修改了一些逻辑后本地docker build后，启动镜像时报错
【fastGPT版本】
4.6.8
【打包命令】
docker build -t 镜像名称 --build-arg name=app --build-arg proxy=taobao .
【启动】
使用docker-compose启动 yml文件后报错

**复现步骤**

**预期结果**

**相关截图**
<img width="644" alt="image" src="https://github.com/labring/FastGPT/assets/18528119/b96b928d-c09e-447a-8360-a5c1f080d884">

**Comment by c121914yu** [comment]
emmm，那是你把打包的内容改坏了吧
