### ISSUE TITLE
升级4.6.9版本后Fastgpt的AI应用配置使用之前的config.json 不显示任何模型选项

### ISSUE THREAD

**Issue by zyy543370785** [labring/FastGPT#1028]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
根据升级步骤完成4.6.9脚本的升级工作，创建AI应用无法选择AI模型，AI配置那为空，在之前的v4.6.7版本使用相同config.json 正常，是使用docker部署的

**Comment by zyy543370785** [comment]
![Uploading 企业微信20240320-150229.png…]()

**Comment by c121914yu** [comment]
没改成新的config.json
