### ISSUE TITLE
开启重排但实际响应重排为关闭

### ISSUE THREAD

**Issue by jixishi** [labring/FastGPT#1029]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**docker latest**
![image](https://github.com/labring/FastGPT/assets/57534147/db57444b-4335-43bb-b9dc-7697266090ca)

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
开启重排但实际响应重排为关闭并且reranker没请求日志，已测试fastgpt容器可以访问到reranker 
**复现步骤**

**预期结果**
应响应带有重排的输出
**相关截图**
![image](https://github.com/labring/FastGPT/assets/57534147/23aaa342-d5f1-4815-b34d-346fd7309131)
![image](https://github.com/labring/FastGPT/assets/57534147/d4f1db5a-81a6-41f4-a4c6-7c0355fa3028)
![image](https://github.com/labring/FastGPT/assets/57534147/662773f1-d29c-42c9-8c75-79d01e0562a3)
![image](https://github.com/labring/FastGPT/assets/57534147/94de0506-8f5a-496c-9768-d3e647e3237c)
![image](https://github.com/labring/FastGPT/assets/57534147/f0452622-7f27-48c6-b80a-7b4fc4514f15)

**Comment by Andy1018** [comment]
requestUrl换成http://xxx试试

**Comment by jixishi** [comment]
OK了
