### ISSUE TITLE
私有化运行报错

### ISSUE THREAD

**Issue by ykmail9** [labring/FastGPT#1030]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
node -v
v21.7.1
pnpm -v
8.15.5

- [x] 私有部署版本

**问题描述**
根据私有化部署，完成后执行pnpm dev报错，报错内容如截图。
安装部署步骤都已按照正常步骤执行，未报错。

**复现步骤**

**预期结果**

**相关截图**
erver Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
detect
file:///home/legion/fastgpt/node_modules/.pnpm/echarts@5.4.1/node_modules/echarts/dist/echarts.js (123:54)
<unknown>
file:///home/legion/fastgpt/node_modules/.pnpm/echarts@5.4.1/node_modules/echarts/dist/echarts.js (97:9)
<unknown>
file:///home/legion/fastgpt/node_modules/.pnpm/echarts@5.4.1/node_modules/echarts/dist/echarts.js (22:68)
Object.<anonymous>
file:///home/legion/fastgpt/node_modules/.pnpm/echarts@5.4.1/node_modules/echarts/dist/echarts.js (25:2)
Module._compile
node:internal/modules/cjs/loader (1368:14)
Module._extensions..js
node:internal/modules/cjs/loader (1426:10)
Module.load
node:internal/modules/cjs/loader (1205:32)
Module._load
node:internal/modules/cjs/loader (1021:12)
Module.require
node:internal/modules/cjs/loader (1230:19)
mod.require
file:///home/legion/fastgpt/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/require-hook.js (64:28)
require
node:internal/modules/helpers (179:18)
Object.echarts
file:///home/legion/fastgpt/projects/app/.next/server/pages/login.js (691:18)
__webpack_require__
file:///home/legion/fastgpt/projects/app/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./src/components/Markdown/img/EChartsCodeBlock.tsx (10:65)
__webpack_require__.a
file:///home/legion/fastgpt/projects/app/.next/server/webpack-runtime.js (97:13)

**Comment by ykmail9** [comment]
今天可以启动了，但是没法进系统   1234和123456两个默认密码都试了 Operation `users.findOne()` buffering timed out after 10000ms

**Comment by c121914yu** [comment]
数据库问题查其他issue或文档 https://doc.fastai.site/docs/development/faq/#operation-auth_codesfindone-buffering-timed-out-after-10000ms

**Comment by princeGoo** [comment]
请问这个问题有人解决了吗？Operation users.findOne() buffering timed out after 10000ms

**Comment by yiwaixiao** [comment]
> 请问这个问题有人解决了吗？Operation users.findOne() buffering timed out after 10000ms

问题解决了吗 ？
