### ISSUE TITLE
源代码部署无法连接mongo

### ISSUE THREAD

**Issue by Hao-star123** [labring/FastGPT#1031]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在fastgpt目录下，删除了docker-compose.yml文件中的fastgpt部分以及mongo和pg的`network-fastgpt`,docker-compose部署了mongo和pg，初始化副本集为ip:27017。
fork源代码，克隆仓库按照文档进行了依赖安装，修改了`.env.local`文件，执行`pnpm dev`命令，出现报错`error-> mongo connect error MongoServerError: Authentication failed.`

**预期结果**
正确登录

**相关截图**
1. 初始化副本集
![QQ图片20240320193534](https://github.com/labring/FastGPT/assets/69717586/6a5477bb-cf18-4de8-8856-b52c6f16c2d8)

2. docker-compose.yml文件
![QQ图片20240320193855](https://github.com/labring/FastGPT/assets/69717586/430c02fc-6b51-4c34-9055-49224d9534e3)

3. `.env.local`文件
![QQ图片20240320194249](https://github.com/labring/FastGPT/assets/69717586/77e7539a-86de-41ef-9f11-6d5e3784f43b)

4. `pnpm dev`报错问题
![QQ图片20240320194659](https://github.com/labring/FastGPT/assets/69717586/5f746d55-b063-4cfc-a8b0-27ad67f624e8)

**Comment by c121914yu** [comment]
Auth failed，不是密码错了么

**Comment by shmily91** [comment]
+1

**Comment by jamesdanner** [comment]
@c121914yu 不是密码错误，我也遇到同样的问题，想在本地通过docker启动mongodb 服务在 本地 dev开发调试一下 一直就是 mongodb连接不上

**Comment by c121914yu** [comment]
问题是，你给的图片里，mongo的密码就不一样。

> > Auth failed，不是密码错了么
> 
> @c121914yu 但是`.env.local`文件中默认密码是123456，我试过123456和1234都是有报错。`error->mongo connect error MongoServerError: Authentication failed.·`

**Comment by wbext** [comment]
> @c121914yu 不是密码错误，我也遇到同样的问题，想在本地通过docker启动mongodb 服务在 本地 dev开发调试一下 一直就是 mongodb连接不上

我也是遇到同样的问题，想初始化副本集，执行了进入数据库的命令，但是死活连不上去。连接使用的账户和密码都没用改动，和docker-compose配置文件中一致。

**Comment by c121914yu** [comment]
> > @c121914yu 不是密码错误，我也遇到同样的问题，想在本地通过docker启动mongodb 服务在 本地 dev开发调试一下 一直就是 mongodb连接不上
> 
> 我也是遇到同样的问题，想初始化副本集，执行了进入数据库的命令，但是死活连不上去。连接使用的账户和密码都没用改动，和docker-compose配置文件中一致。

有没有可能，你把mongo环境变量里密码改过了，已经不是初始化的密码。

**Comment by wbext** [comment]
<img width="960" alt="2bd83a606bcca402e9a23a768b751fa" src="https://github.com/labring/FastGPT/assets/134917942/d9dd8fde-9d14-4f9e-88f2-62746e9aae84">
<img width="960" alt="fe43484575f6e8e3a1aa0882407ef3f" src="https://github.com/labring/FastGPT/assets/134917942/ad882638-6016-4fcb-b119-94a3783027ec">
mongo环境变量密码是这里看吗？好像也没改过啊

**Comment by c121914yu** [comment]
> <img alt="2bd83a606bcca402e9a23a768b751fa" width="960" src="https://private-user-images.githubusercontent.com/134917942/316381183-d9dd8fde-9d14-4f9e-88f2-62746e9aae84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzkxMTcsIm5iZiI6MTcxMTMzODgxNywicGF0aCI6Ii8xMzQ5MTc5NDIvMzE2MzgxMTgzLWQ5ZGQ4ZmRlLTlkMTQtNGY5ZS04OGYyLTYyNzQ2ZTlhYWU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDEwNTQ3MWYyZTQ5ZjhiODQzNjkyMGFiMThhNjVhOTA3OWFmODc2NTVhMzBiNjQwMGM2ZDk4OTVhMzBiYWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dVBTpbKvw9lbOnZ58m3ctqdxFNyrG58VTellr1NvAS8"> <img alt="fe43484575f6e8e3a1aa0882407ef3f" width="960" src="https://private-user-images.githubusercontent.com/134917942/316381200-ad882638-6016-4fcb-b119-94a3783027ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzkxMTcsIm5iZiI6MTcxMTMzODgxNywicGF0aCI6Ii8xMzQ5MTc5NDIvMzE2MzgxMjAwLWFkODgyNjM4LTYwMTYtNGZjYi1iMTE5LTk0YTM3ODMwMjdlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDYxZTU1NmVmYmE5YmY1MmM3ZWQ3YjFmNjEyZjYxZjc0MDRlOWVhMWQ0MmZjYmQ1YWY0ZjIzOWEwMjYwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mQCThhC8-J8wD9i25kLWr-2CzMsnR2nTnyZ_b_t_OLo"> mongo环境变量密码是这里看吗？好像也没改过啊

你是不是直接把新的文件覆盖你以前的了，以前是 username 和 password

**Comment by wbext** [comment]
> > <img alt="2bd83a606bcca402e9a23a768b751fa" width="960" src="https://private-user-images.githubusercontent.com/134917942/316381183-d9dd8fde-9d14-4f9e-88f2-62746e9aae84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzkxMTcsIm5iZiI6MTcxMTMzODgxNywicGF0aCI6Ii8xMzQ5MTc5NDIvMzE2MzgxMTgzLWQ5ZGQ4ZmRlLTlkMTQtNGY5ZS04OGYyLTYyNzQ2ZTlhYWU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDEwNTQ3MWYyZTQ5ZjhiODQzNjkyMGFiMThhNjVhOTA3OWFmODc2NTVhMzBiNjQwMGM2ZDk4OTVhMzBiYWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dVBTpbKvw9lbOnZ58m3ctqdxFNyrG58VTellr1NvAS8"> <img alt="fe43484575f6e8e3a1aa0882407ef3f" width="960" src="https://private-user-images.githubusercontent.com/134917942/316381200-ad882638-6016-4fcb-b119-94a3783027ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzkxMTcsIm5iZiI6MTcxMTMzODgxNywicGF0aCI6Ii8xMzQ5MTc5NDIvMzE2MzgxMjAwLWFkODgyNjM4LTYwMTYtNGZjYi1iMTE5LTk0YTM3ODMwMjdlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDYxZTU1NmVmYmE5YmY1MmM3ZWQ3YjFmNjEyZjYxZjc0MDRlOWVhMWQ0MmZjYmQ1YWY0ZjIzOWEwMjYwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mQCThhC8-J8wD9i25kLWr-2CzMsnR2nTnyZ_b_t_OLo"> mongo环境变量密码是这里看吗？好像也没改过啊
> 
> 你是不是直接把新的文件覆盖你以前的了，以前是 username 和 password

没有覆盖，这个是我重新拉取的docker-compose文件，以前的文件被我移到别的目录去了，而且以前的文件也是myusername的呀
<img width="960" alt="1711345891425" src="https://github.com/labring/FastGPT/assets/134917942/42e81c08-c87b-4a8f-a8bf-05fa52507018">

**Comment by wbext** [comment]
> > > <img alt="2bd83a606bcca402e9a23a768b751fa" width="960" src="https://private-user-images.githubusercontent.com/134917942/316381183-d9dd8fde-9d14-4f9e-88f2-62746e9aae84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzkxMTcsIm5iZiI6MTcxMTMzODgxNywicGF0aCI6Ii8xMzQ5MTc5NDIvMzE2MzgxMTgzLWQ5ZGQ4ZmRlLTlkMTQtNGY5ZS04OGYyLTYyNzQ2ZTlhYWU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDEwNTQ3MWYyZTQ5ZjhiODQzNjkyMGFiMThhNjVhOTA3OWFmODc2NTVhMzBiNjQwMGM2ZDk4OTVhMzBiYWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dVBTpbKvw9lbOnZ58m3ctqdxFNyrG58VTellr1NvAS8"> <img alt="fe43484575f6e8e3a1aa0882407ef3f" width="960" src="https://private-user-images.githubusercontent.com/134917942/316381200-ad882638-6016-4fcb-b119-94a3783027ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzkxMTcsIm5iZiI6MTcxMTMzODgxNywicGF0aCI6Ii8xMzQ5MTc5NDIvMzE2MzgxMjAwLWFkODgyNjM4LTYwMTYtNGZjYi1iMTE5LTk0YTM3ODMwMjdlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDYxZTU1NmVmYmE5YmY1MmM3ZWQ3YjFmNjEyZjYxZjc0MDRlOWVhMWQ0MmZjYmQ1YWY0ZjIzOWEwMjYwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mQCThhC8-J8wD9i25kLWr-2CzMsnR2nTnyZ_b_t_OLo"> mongo环境变量密码是这里看吗？好像也没改过啊
> > 
> > 
> > 你是不是直接把新的文件覆盖你以前的了，以前是 username 和 password
> 
> 没有覆盖，这个是我重新拉取的docker-compose文件，以前的文件被我移到别的目录去了，而且以前的文件也是myusername的呀 <img alt="1711345891425" width="960" src="https://private-user-images.githubusercontent.com/134917942/316400013-42e81c08-c87b-4a8f-a8bf-05fa52507018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDcwMjYsIm5iZiI6MTcxMTM0NjcyNiwicGF0aCI6Ii8xMzQ5MTc5NDIvMzE2NDAwMDEzLTQyZTgxYzA4LWM4N2ItNGE4Zi1hOGJmLTA1ZmE1MjUwNzAxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwNjA1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzcxZTA3Zjg5ZDZkYzI0MzUzYjZkZDRkYjA0ZWE4NmVjM2I4MDQ2M2FjZDk1Y2Q1ODNiZDY3MTU5MWUwOGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xcL1h_nIT1tvfnOyH2MCUByhdlV5FnJkzNVMMmnc1a4">

而且无论我用myusername的账户密码还是username的账户密码来登录，都连接不上

**Comment by wbext** [comment]
ok是我傻逼了，账户密码确实改了。兄弟们，一般遇到auth failed的可能是账户密码不对的问题

**Comment by QichangZheng** [comment]
请问在哪里看账户和密码呢？不是myusername和mypassword吗？

**Comment by QichangZheng** [comment]
> > 请问在哪里看账户和密码呢？不是myusername和mypassword吗？
> 
> 我用docker部署的数据库，clone的fastgpt。mongo数据库默认是myusername，fastgpt文件写的默认是username。有冲突所以连接不上

我解决了，确实是用户名和密码的问题，谢谢谢谢！！
