### ISSUE TITLE
问题分类应用报错，代码307

### ISSUE THREAD

**Issue by phoenixdna** [labring/FastGPT#1032]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在创建分类问题的应用时候，用了默认的模板还是报错
**复现步骤**
我的应用-》新建-》问题分类+知识库
**预期结果**
系统做出正确符合分类的回答
**相关截图**
![image](https://github.com/labring/FastGPT/assets/31263323/a41d144b-e3a7-4ccf-a1cb-7aea8fa0cf58)

容器中的fastgpt日志如下：
[ERROR] 2024-03-20 16:51:16 sse error: bad_response_status_code (request id: 2024032100511589425293781505320)
{
message: '307 (request id: 2024032100511589425293781505320)',
stack: 'Error: 307 (request id: 2024032100511589425293781505320)\n' +
' at eL.generate (/app/projects/app/.next/server/chunks/53204.js:21:70226)\n' +
' at ax.makeStatusError (/app/projects/app/.next/server/chunks/53204.js:21:81454)\n' +
' at ax.makeRequest (/app/projects/app/.next/server/chunks/53204.js:21:82188)\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async g (/app/projects/app/.next/server/chunks/1492.js:75:422)\n' +
' at async Object.T [as classifyQuestion] (/app/projects/app/.next/server/chunks/1492.js:70:903)\n' +
' at async I (/app/projects/app/.next/server/chunks/1492.js:85:7124)\n' +
' at async Promise.all (index 0)\n' +
' at async Promise.all (index 0)\n' +
' at async O (/app/projects/app/.next/server/chunks/1492.js:85:8194)'
}

我的config.json内容：
{
  "systemEnv": {
    "openapiPrefix": "fastgpt",
    "vectorMaxProcess": 15,
    "qaMaxProcess": 15,
    "pgHNSWEfSearch": 100
  },
  "llmModels": [

     {
      "model": "gpt-3.5-turbo",
      "name": "gpt3.5",
      "maxContext": 16000,
      "maxResponse": 4000,
      "quoteMaxToken": 13000,
      "maxTemperature": 1.2,
      "charsPointsPrice": 0,
      "censor": false,
      "vision": false,
      "datasetProcess": true,
      "usedInClassify": true,
      "usedInExtractFields": true,
      "usedInToolCall": true,
      "usedInQueryExtension": true,
      "toolChoice": true,
      "functionCall": false,
      "customCQPrompt": "",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig": {}
    },
more...

**Comment by c121914yu** [comment]
key问题吧，没遇到过

**Comment by phoenixdna** [comment]
作者您好，key是好使的；4种应用里面只有最后的创建分类问题+知识库的应用报错了。
是不是应该重装好点。

**Comment by phoenixdna** [comment]
我后来实验发现，在做问题分类中选用的大模型，如果config.json中的toolChoice改成false，functioCall改为true就可以正常跑；但是只针对qwen-max和国内的模型，gpt3.5怎么改都没法用作问题分类中的大模型。
我可能还是不太理解这些开关的含义。谢谢作者回复。

**Comment by c121914yu** [comment]
> 我后来实验发现，在做问题分类中选用的大模型，如果config.json中的toolChoice改成false，functioCall改为true就可以正常跑；但是只针对qwen-max和国内的模型，gpt3.5怎么改都没法用作问题分类中的大模型。
> 我可能还是不太理解这些开关的含义。谢谢作者回复。

文档里有每个字段的注释。
gpt35 用不了，估计是你买的是些逆转 key，不支持函数调用。

**Comment by huawuhen** [comment]
> 我后来实验发现，在做问题分类中选用的大模型，如果config.json中的toolChoice改成false，functioCall改为true就可以正常跑；但是只针对qwen-max和国内的模型，gpt3.5怎么改都没法用作问题分类中的大模型。 我可能还是不太理解这些开关的含义。谢谢作者回复。

我要遇到这个问题，我用的是oneapi的key。toolChoice改成false，functioCall改为true ，这个步骤对我没用

**Comment by 1600858489** [comment]
我也遇到了该问题，连续两天连续聊天超过50条就会出现该问题，我用的是gpt4.0的中转key，没有使用问题分类的功能。部署方式是通过docekr部署，问题只会在fastgpt聊天页面会出现，通过接口接入chatgpt-on-wechat时没有该问题
