### ISSUE TITLE
知识库存量达到百万条时，知识库导入速度下降严重

### ISSUE THREAD

**Issue by yanjian1978** [labring/FastGPT#1033]
-  [x] 我已确认目前没有类似 issue
-  [x]我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
-  [x]我使用了自己的 key，并确认我的 key 是可正常使用的
-  [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [x] 私有部署版本：V4.6.9     ,docker-compose 部署

**问题描述**
知识库存量达到百万条时，知识库导入速度下降严重

**复现步骤**
知识库导入功能：
正常情况下：当知识库存量小时
m3e-base 向量算法，用3090显卡启动m3e-base 接口
当知识库存量小时，1万条知识几分钟内导完，3090 上m3e-base 基本上跑50%功耗
异常变慢：当知识库已导入量达到百万时
当知识库已导入量达到百万时， 1万条知识一个小时也导不完，
fastgpt 应用mongo的CPU利用率非常高，3090上m3e-base 非常空

分析mongo:
  "findAndModify" : "dataset.trainings",
  "keysExamined" : 1261763,
  "docsExamined" : 0,
感觉索引还是生效的，但就是慢

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
数据库阻塞了吧，是不是数据库规格太小

**Comment by yanjian1978** [comment]
如果单文件行数达到百万级时，速度极慢，但和一共多少个知识库无关

**Comment by Arshjzhu** [comment]
同样的问题

**Comment by wufxgtihub123** [comment]
> 数据库阻塞了吧，是不是数据库规格太小

大佬，请问这种卡住的问题该怎么解决呢？需要增加数据库规格吗？

**Comment by c121914yu** [comment]
> > 数据库阻塞了吧，是不是数据库规格太小
> 
> 大佬，请问这种卡住的问题该怎么解决呢？需要增加数据库规格吗？

一百万数据，还是并发竞争查改。
这种改进一般就是，索引优化（代码里已经有了，可以看看有没有生效）
代码逻辑优化或者增加规格。
另外就是优化部署，一般 docker 的数据库都比较慢，要么是 kubeblock 集群库，要么可以裸机装。
