### ISSUE TITLE
[QA Queue] Finish {"time":89057,"splitLength":30,"usage":{"prompt_tokens":3239,"total_tokens":4379,"completion_tokens":1140}} error => Collection is not exist

### ISSUE THREAD

**Issue by zyy543370785** [labring/FastGPT#1034]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

导入知识库后，发现向量模型和索引一直没变化，显示为[QA Queue] Finish {"time":89057,"splitLength":30,"usage":{"prompt_tokens":3239,"total_tokens":4379,"completion_tokens":1140}}
error => Collection is not exist

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/4c7f7006-c0dc-4670-a571-067089f3e7db)
检查你的数据库里数据是否一致，是否有删除数据操作。

dataset.trainigns 表里的 collectionId 数据，是否都能在 dataset.collections 里找到。
