### ISSUE TITLE
按照教程安装docker compose版本的fastGPT在新建AI应用时提示 timeout of 60000ms exceeded

### ISSUE THREAD

**Issue by 4741301** [labring/FastGPT#1039]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
按照教程安装docker compose版本的fastGPT在新建应用时提示 timeout of 60000ms exceeded，查看日志docker logs fastgpt里面无错误提示，可正在登录平台。
**复现步骤**
新安装后立即出现。
**预期结果**

**相关截图**
![1711010428030](https://github.com/labring/FastGPT/assets/94953379/2f830ae8-b98b-4427-89b7-8d0ffa2d273a)
启动时有两个报错，但我不知道这是否有影响。
![1711010682456](https://github.com/labring/FastGPT/assets/94953379/c91cf532-2cbf-4ba7-b706-e68556c89981)

**Comment by c121914yu** [comment]
看着是数据库没正常
