### ISSUE TITLE
知识库查询慢

### ISSUE THREAD

**Issue by JerryMoon** [labring/FastGPT#1042]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.6.9

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
知识库数据不到1000条，但是每次请求查询知识库速度非常慢。看pg log实际的查询好像并没有很耗时，但是多条查询之间间隔的时间比较长。请教下可能是哪里出现了问题。

**复现步骤**
如下面两张图，会话开始请求时间是在19分28秒，但直到19分35秒才完成知识库查询。
pg log中相邻两次查询间隔时间比较长，不清楚在做什么耗时的事情。

<img width="1083" alt="VC20240321-173248" src="https://github.com/labring/FastGPT/assets/10956374/bd1bc452-3526-4bd6-ab8e-ecf228ee70ff">

<img width="1057" alt="VC20240321-174500" src="https://github.com/labring/FastGPT/assets/10956374/79c7024f-83e0-4e94-a5d0-bd9523d1c0de">

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
用了问题补全？

**Comment by JerryMoon** [comment]
> 用了问题补全？

用了。是问题补全导致的吗？关了问题补全在4秒左右，这个是正常的吗，感觉也有点慢。

<img width="1059" alt="VC20240322-100635" src="https://github.com/labring/FastGPT/assets/10956374/c7ff2826-05cc-4007-ac14-f4ffad2042e8">

**Comment by c121914yu** [comment]
> > 用了问题补全？
> 
> 用了。是问题补全导致的吗？关了问题补全在4秒左右，这个是正常的吗，感觉也有点慢。
> 
> <img alt="VC20240322-100635" width="1059" src="https://private-user-images.githubusercontent.com/10956374/315862055-c7ff2826-05cc-4007-ac14-f4ffad2042e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODg2OTUsIm5iZiI6MTcxMTI4ODM5NSwicGF0aCI6Ii8xMDk1NjM3NC8zMTU4NjIwNTUtYzdmZjI4MjYtMDVjYy00MDA3LWFjMTQtZjRmZmFkMjA0MmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDEzNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNTg4YTcwNWVkYjE3OGUwOTJlOGQ4NzdiMmVjNDNkNzRmMTdmOGMxNTVmZWRjMjhiMTM1NmZhNmIyYTc4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xd_JlYLI76osfA0_UbEewqX2vFIfCai86iCOQykg4T8">

知识库搜索中可能包含的流程：
1. 请求向量化API （可以手动插入数据，看看速度）
2. 向量搜索 （数据库里直接测试sql）
3. 全文检索 （搜索测试直接选择它来测）
4. 问题补全 （可以单独测试问题补全模块的速度）
5. 重排 （成功的时候，日志里会提示具体时间）

都可能导致慢

**Comment by yangkl-ui** [comment]
我的加了知识库之后响应要十多秒，检索知识库要7、8秒，好慢啊，怎么调

**Comment by yoohhwz** [comment]
> > > 用了问题补全？
> > 
> > 
> > 用了。是问题补全导致的吗？关了问题补全在4秒左右，这个是正常的吗，感觉也有点慢。
> > <img alt="VC20240322-100635" width="1059" src="https://private-user-images.githubusercontent.com/10956374/315862055-c7ff2826-05cc-4007-ac14-f4ffad2042e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODg2OTUsIm5iZiI6MTcxMTI4ODM5NSwicGF0aCI6Ii8xMDk1NjM3NC8zMTU4NjIwNTUtYzdmZjI4MjYtMDVjYy00MDA3LWFjMTQtZjRmZmFkMjA0MmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDEzNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNTg4YTcwNWVkYjE3OGUwOTJlOGQ4NzdiMmVjNDNkNzRmMTdmOGMxNTVmZWRjMjhiMTM1NmZhNmIyYTc4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xd_JlYLI76osfA0_UbEewqX2vFIfCai86iCOQykg4T8">
> 
> 知识库搜索中可能包含的流程：
> 
> 1. 请求向量化API （可以手动插入数据，看看速度）
> 2. 向量搜索 （数据库里直接测试sql）
> 3. 全文检索 （搜索测试直接选择它来测）
> 4. 问题补全 （可以单独测试问题补全模块的速度）
> 5. 重排 （成功的时候，日志里会提示具体时间）
> 
> 都可能导致慢

那这些有解决手段吗？ 因为感觉每个环节都是必不可少的优化

**Comment by yoohhwz** [comment]
> 我的加了知识库之后响应要十多秒，检索知识库要7、8秒，好慢啊，怎么调

怎么说  有解决眉目了吗

**Comment by yangkl-ui** [comment]
我换了向量模型m3e快很多了












略略略你略得有我快吗
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月28日(周二) 中午1:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 知识库查询慢 (Issue #1042)




  
我的加了知识库之后响应要十多秒，检索知识库要7、8秒，好慢啊，怎么调
  
怎么说  有解决眉目了吗

**Comment by dockersky** [comment]
确实慢，大家有解决方案吗？
