### ISSUE TITLE
mongo docker源有问题

### ISSUE THREAD

**Issue by xsser** [labring/FastGPT#1044]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本

**问题描述**
 无法启动docker compose ,我的docker compose文件内如下：

```version: '3.3'
  4 services:
  5   pg:
  6     image: ankane/pgvector:v0.5.0 # git
  7     # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # 阿里云
  8     container_name: pg
  9     restart: always
 10     ports: # 生产环境建议不要暴露
 11       - 5432:5432
 12     networks:
 13       - fastgpt
 14     environment:
 15       # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
 16       - POSTGRES_USER=username
 17       - POSTGRES_PASSWORD=password
 18       - POSTGRES_DB=postgres
 19     volumes:
 20       - ./pg/data:/var/lib/postgresql/data
 21   mongo:
 22     image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:4.4.24
 23     container_name: mongo
 24     restart: always
 25     ports:
 26       - 27017:27017
 27     networks:
 28       - fastgpt
 29     command: mongod --keyFile /data/mongodb.key --replSet rs0
 30     environment:
 31       - MONGO_INITDB_ROOT_USERNAME=myusername
 32       - MONGO_INITDB_ROOT_PASSWORD=mypassword
 33     volumes:
 34       - ./mongo/data:/data/db
 35     entrypoint:
 36       - bash
 37       - -c
 38       - |
 39         openssl rand -base64 128 > /data/mongodb.key
 40         chmod 400 /data/mongodb.key
 41         chown 999:999 /data/mongodb.key
 42         exec docker-entrypoint.sh $$@

```

结果是：
Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:4 not found: manifest unknown: manifest unknown

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
4.x 版本没做备份，可以自行到 docker hub 下载。

**Comment by xsser** [comment]
> 4.x 版本没做阿里云备份，可以自行到 docker hub 下载。

<img width="1100" alt="图片" src="https://github.com/labring/FastGPT/assets/1850771/0acf76b5-2361-4d76-b256-e4fde867a01a">
 
OK 主要是我阅读了文档发现需要改 就改了

**Comment by c121914yu** [comment]
> > 4.x 版本没做阿里云备份，可以自行到 docker hub 下载。
> 
> <img width="1100" alt="图片" src="https://github.com/labring/FastGPT/assets/1850771/0acf76b5-2361-4d76-b256-e4fde867a01a">
>  
> OK 主要是我阅读了文档发现需要改 就改了

嗯，下次改改说明。
