### ISSUE TITLE
知识库，选择pdf进行增强处理，一直未处理成功

### ISSUE THREAD

**Issue by linth2005** [labring/FastGPT#1045]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本
4.6.9
**问题描述**
1个小时了，一直卡着，部署本服务的cpu和内存都正常，数据库负载也正常。fastgpt控制台日志也正常
![image](https://github.com/labring/FastGPT/assets/13826754/5ef94d57-aedd-4ee0-bc41-9be0bd2580e7)
**复现步骤**
选择任意pdf进行增强处理
**预期结果**
能正确完成数据训练
**相关截图**
![image](https://github.com/labring/FastGPT/assets/13826754/1248d729-3ee1-4bb9-9b01-dd15ca39a6f7)
![image](https://github.com/labring/FastGPT/assets/13826754/4edd7850-8c82-4ac7-9beb-0a86f3100b0f)

**Comment by linth2005** [comment]
一直展示 QA训练排队(预计5分钟)

**Comment by c121914yu** [comment]
之前 issue 有。商业版才支持。

**Comment by FVCSAV** [comment]
请问解决这个问题了吗？
