### ISSUE TITLE
v4.7版本挂载知识库或工具报错误：sse error: bad_response_status_code bad response status code 400

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#1046]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
 OneAPI-v0.6.3-alpha.1，FastGPT-v4.7版本。
在应用中一旦挂上知识库或工具，chat的时候会报以下错误（如果把知识库或工具拿掉，那可以正常chat）：
```
[ERROR] 2024-03-21 16:51:24 sse error: bad_response_status_code bad response status code 400 (request id: 2024032200512459019245161442518) 
{
  message: '400 bad response status code 400 (request id: 2024032200512459019245161442518)',
  stack: 'Error: 400 bad response status code 400 (request id: 2024032200512459019245161442518)\n' +
    '    at eL.generate (/app/projects/app/.next/server/chunks/80555.js:21:70043)\n' +
    '    at af.makeStatusError (/app/projects/app/.next/server/chunks/80555.js:21:81687)\n' +
    '    at af.makeRequest (/app/projects/app/.next/server/chunks/80555.js:21:82610)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async g (/app/projects/app/.next/server/chunks/94900.js:121:1884)\n' +
    '    at async Object.w [as tools] (/app/projects/app/.next/server/chunks/94900.js:119:4647)\n' +
    '    at async N (/app/projects/app/.next/server/chunks/94900.js:125:2787)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async S (/app/projects/app/.next/server/chunks/94900.js:125:4092)\n' +
    '    at async h (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2771)'
}
```

**相关截图**
![image](https://github.com/labring/FastGPT/assets/18339429/04608bff-8ff5-4708-8232-788ee103514d)
![image](https://github.com/labring/FastGPT/assets/18339429/f6c44781-9a02-45d5-81eb-0bdaaccd5a86)

**Comment by zhanghx0905** [comment]
遇到了相同的错误。我使用one-api连接本地部署的xinference

**Comment by leoterry-ulrica** [comment]
@c121914yu 是不是跟v4.7-alpha3这个修复有关：简易模式中，单纯选择知识库，仍保持旧逻辑，不调用工具。

**Comment by leoterry-ulrica** [comment]
> 遇到了相同的错误。我使用one-api连接本地部署的xinference

你解决了吗？

**Comment by zhanghx0905** [comment]
> > 遇到了相同的错误。我使用one-api连接本地部署的xinference
> 
> 你解决了吗？

未解决，我正在等待正式版镜像，等正式版发布了我再测试

**Comment by zhanghx0905** [comment]
根据我的测试，这个错误与packages\service\core\workflow\dispatch\agent\runTool\toolChoice.ts中第110行左右调用模型时，设置stream=True有关，我使用的Xinference不支持在设置Tools的同时设置stream=True

**Comment by leoterry-ulrica** [comment]
@c121914yu 请问如何修改？

**Comment by qinxuye** [comment]
Xinference 目前使用 tools 的时候不能支持 stream。

**Comment by leoterry-ulrica** [comment]
> Xinference 目前使用 tools 的时候不能支持 stream。

那有什么解决方案吗？

**Comment by zhanghx0905** [comment]
我使用的是xinference v0.9.3，fastgpt 当前的最新main分支
让fastgpt兼容xinference的tools call的方法是设置stream=False，并且在工具调用返回的请求体中设置一个空的content。参见https://github.com/zhanghx0905/FastGPT/commit/2d21659be106cb56877fd7e646d3652f080071c6

![07208a72dfa923abb97dfa093ee0a2a](https://github.com/labring/FastGPT/assets/50790281/ab51985a-09f9-4890-9a3c-60e29f033981)

不知道为什么，虽然模型结果正确返回了，fastgpt的对话框里没有显示出结果。

![9a696f38211ba1591f4ec5662fcb29e](https://github.com/labring/FastGPT/assets/50790281/53940fbe-9460-40fd-a074-e652bbf00381)

**Comment by c121914yu** [comment]
> 虽然模型结果正确返回了，fastgpt的对话框里没有显示出结果。

那必然是改得模型。直接做一个伪流接口。

**Comment by leoterry-ulrica** [comment]
> > 虽然模型结果正确返回了，fastgpt的对话框里没有显示出结果。
> 
> 那必然是改得模型。直接做一个伪流接口。

@qinxuye 这个能处理的吗？

**Comment by jjssjdhhd** [comment]
我也是这个问题，有谁解决了吗

**Comment by studying-llama** [comment]
有人解决了吗

**Comment by cwateryuan** [comment]
同样遇到了这个问题。

**Comment by c121914yu** [comment]
Xinference support: https://github.com/xorbitsai/inference/issues/1208
