### ISSUE TITLE
AI提示词框中莫名多出许多换行

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#1047]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
RT，多出的空行导致AI的回复里格式不对齐

**复现步骤**
<img width="654" alt="Screenshot 2024-03-22 at 05 30 58" src="https://github.com/labring/FastGPT/assets/36452456/15673438-01be-41c9-b120-8951f93bf6b5">

**预期结果**

**相关截图**

**Comment by AlanLee1996** [comment]
遇到了同样的问题

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.7 拉下这个版本试试

**Comment by bincooo** [comment]
感谢作者，这就试试

**Comment by bincooo** [comment]
更新后没有出现空行了

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/1120 忘了是哪个pr修复了
