### ISSUE TITLE
HTTP 模块中增加超时时间设置

### ISSUE THREAD

**Issue by pfchai** [labring/FastGPT#1048]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
HTTP 模块中增加超时时间设置，支持自定义设置超时时间。

**应用场景**
控制应用中，HTTP模块调用接口，接口响应时间太慢对体验造成影响。

**相关示例**

**Comment by c121914yu** [comment]
默认加了120秒，不想增加更多配置内容。尽量由服务端解决。
