### ISSUE TITLE
接口问题

### ISSUE THREAD

**Issue by KnSun99** [labring/FastGPT#105]
进行docker-compose 部署后，运行并对话时，会显示  接口连接异常  是什么原因啊？

![nnn](https://github.com/c121914yu/FastGPT/assets/123467428/08dade71-1d10-4c6b-b8bf-2e4dfad02ceb)

**Comment by SunJackson** [comment]
配置中的代理配置没有删除

**Comment by KnSun99** [comment]
是这个问题，已经解决了，但又出现了   request failed with status code 403  这个问题

**Comment by c121914yu** [comment]
> 是这个问题，已经解决了，但又出现了 request failed with status code 403 这个问题

403 凭证问题了，具体哪个凭证看看日志

**Comment by KnSun99** [comment]
日志是这个吗？

![image](https://github.com/c121914yu/FastGPT/assets/123467428/446d60a9-ccbe-4402-a346-19fe7918972f)

**Comment by KnSun99** [comment]
sealos代理的log

![image](https://github.com/c121914yu/FastGPT/assets/123467428/ed880f5a-eb63-4e62-b8e4-2f923d077175)

**Comment by c121914yu** [comment]
> Reference in

这个是正常的，你不能直接访问，需要访问 地址/openai/v1。
给的 nginx 配置里，请求需要有一个 header.auth 进行凭证校验。具体是多少看 nginx 的配置，否则会 403，确保 fastgpt 中填写了 OPENAI_BASE_URL_AUTH 这个参数。

**Comment by c121914yu** [comment]
![image](https://github.com/c121914yu/FastGPT/assets/50446880/056fddde-6e51-41e5-a544-00b8840b8c57)
这里已经说明了

**Comment by KnSun99** [comment]
在这个位置添加了，docker-compose.yml 里面也添加了

![image](https://github.com/c121914yu/FastGPT/assets/123467428/e9c3e007-00bf-458c-9197-3224d31fa897)

**Comment by c121914yu** [comment]
那可能不是 nginx 问题了~ 你可以 postman 手动验证下

**Comment by KnSun99** [comment]
不过又变成 429 错误了

![image](https://github.com/c121914yu/FastGPT/assets/123467428/6fa7f52f-4505-4ce0-86a3-0fe89a053050)

**Comment by KnSun99** [comment]
现在提问时变成 429 报错了，请问右边这个 fetch 有个错误标识，这个正常吗？

我是docker-compose 部署，部署在本机分别在 admin文件夹 和 client文件夹 运行了 pnpm i、pnpm dev，然后打开的 http://localhost:3003

![image](https://github.com/labring/FastGPT/assets/123467428/f6e35c0d-ec48-4b76-a0f1-4986c1f493b0)

![image](https://github.com/labring/FastGPT/assets/123467428/84b1bc58-37f4-44b3-bffb-757ff007229b)

**Comment by c121914yu** [comment]
key问题

**Comment by KnSun99** [comment]
根据那个文档链接查询过，这样key是不能用吗？

![image](https://github.com/labring/FastGPT/assets/123467428/6fc540e5-ee2a-4093-8f04-ae713896482e)

![image](https://github.com/labring/FastGPT/assets/123467428/b1e3abd2-f0ae-4842-83a7-6bdfec3e25ed)

**Comment by c121914yu** [comment]
5刀经常用不了。具体错误看后台日志

**Comment by KnSun99** [comment]
120的也不行，报出 key不合法

![image](https://github.com/labring/FastGPT/assets/123467428/1ce94e7a-309c-4e00-96de-1e756f9eef44)

![image](https://github.com/labring/FastGPT/assets/123467428/c00f9eea-d546-4e62-90cc-4091057a8cfd)

![image](https://github.com/labring/FastGPT/assets/123467428/bff5bac0-2078-4ef6-a3b5-8776385bfd1b)

**Comment by c121914yu** [comment]
> 120的也不行，报出 key不合法
> 
> ![image](https://github.com/labring/FastGPT/assets/123467428/1ce94e7a-309c-4e00-96de-1e756f9eef44)
> 
> ![image](https://github.com/labring/FastGPT/assets/123467428/c00f9eea-d546-4e62-90cc-4091057a8cfd)
> 
> ![image](https://github.com/labring/FastGPT/assets/123467428/bff5bac0-2078-4ef6-a3b5-8776385bfd1b)
> 
> 

那就看日志，实际发出的内容

**Comment by KnSun99** [comment]
日志是在哪里啊？一直没找到

**Comment by c121914yu** [comment]
> 日志是在哪里啊？一直没找到

docker log 容器

**Comment by KnSun99** [comment]
这个log是吗？

![image](https://github.com/labring/FastGPT/assets/123467428/8752aaac-ee7c-495f-ac11-18a2003dacc9)

这个镜像下面的
![image](https://github.com/labring/FastGPT/assets/123467428/4d425e1e-69fb-4305-a581-b0671b5c903d)

**Comment by c121914yu** [comment]
这是nginx的，，要看fastgpt的

**Comment by bigfoot88** [comment]
[Error]: 429 status code (no body)
    at eL.generate (/app/projects/app/.next/server/chunks/43326.js:21:67784)
    at tx.makeStatusError (/app/projects/app/.next/server/chunks/43326.js:21:79051)
    at tx.makeRequest (/app/projects/app/.next/server/chunks/43326.js:21:79785)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async b (/app/projects/app/.next/server/chunks/62522.js:31:828)
    at async v (/app/projects/app/.next/server/chunks/62522.js:23:447)
    at async Promise.all (index 0)
    at async a (/app/projects/app/.next/server/chunks/62522.js:79:161)
    at async h (/app/projects/app/.next/server/chunks/62522.js:83:2526) {
  status: 429,
  headers: {
    'content-encoding': 'gzip',
    'content-length': '23',
    date: 'Fri, 01 Mar 2024 01:44:03 GMT',
    vary: 'Accept-Encoding',
    'x-oneapi-request-id': '2024030109440351220634357075125'
  },
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
error => 429 status code (no body)
使用one-api基于通义千问生成的api-key，出现上述报错429，请问是什么原因？
