### ISSUE TITLE
用了一段时间出现 “insufficient_user_quota user quota is not enough”问题，已查看文档，但未提及如何“手动修改”root用户余额。

### ISSUE THREAD

**Issue by BUJIDAOVS** [labring/FastGPT#1054]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

fastgpt是docker部署的4.6.9

模型是本地部署的，oneapi令牌设置的是永不过期。

已查看faq文档，但未提及具体如何“手动修改”root用户余额。

请问应该如何修改root用户额度，或新建用户？

![image](https://github.com/labring/FastGPT/assets/98118374/90ad51b4-441e-4343-a13c-a40669baaf62)

文档只写了可以手动修改，但不清楚具体如何修改啊？？

**Comment by BUJIDAOVS** [comment]
找到了，是oneapi上余额的问题，用户剩余额度和无限制令牌是两个概念，修改用户余额就好了。
![image](https://github.com/labring/FastGPT/assets/98118374/e962da02-e63b-4400-8411-2b0aab15aac2)

**Comment by sun-timer** [comment]
用户信息这里更新了剩余额度，再去调用工作流时还是报了user quota is not enough，请问有遇到这种情况吗
![image](https://github.com/user-attachments/assets/ef876a34-ce15-4bcd-8862-d746a93e3bd0)
