### ISSUE TITLE
对话后报错 insufficient_quota 当前分组上游负载已饱和，请稍后再试 

### ISSUE THREAD

**Issue by ManitosuperToken** [labring/FastGPT#1056]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
![Snipaste_2024-03-25_11-29-57](https://github.com/labring/FastGPT/assets/40332205/2bb63e00-a110-4eae-b5c8-4c5c18d3a578)

**Comment by qinde025** [comment]
![image](https://github.com/user-attachments/assets/57793daa-2372-434f-b004-42cc0ac4f80b)

**Comment by pll8754** [comment]
这个问题是如何解决的

**Comment by pll8754** [comment]
> key 上限了

是哪个key上线了，私有部署是在哪里替换
