### ISSUE TITLE
支持 kimi

### ISSUE THREAD

**Issue by mofadeyunduo** [labring/FastGPT#1059]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

支持 kimi

**应用场景**

目前直接导入 Kimi 的 key 提示，not found the model or permission denied，是不是模型类型限制了

**相关示例**

**Comment by c121914yu** [comment]
没遇到，moonshot 已经正常用着了
