### ISSUE TITLE
获取对话日志文件

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1060]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
现有在前端界面中可以以多种格式(html,md,pdf)导出对话日志,如果想导出数据库(pg/mongo)中的对话日志文件呢
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
得去数据库导出。

**Comment by xiaoToby** [comment]
是啊，是得去数据库导出，我还没找出是在数据库得哪个路径下去找

**Comment by bruceye777** [comment]
目前情况下只能通过数据库导出，参考命令如下：
mongoexport   -u "xxxx" -p "xxxx" --authenticationDatabase admin --db=fastgpt --collection=chatitems --type=csv --fields=chatId,appId,title,obj,value,time --out=/data/db/chatitems.csv
聊天记录放在chatitems里面，fields定义需要的字段，导出到chatitems.csv
