### ISSUE TITLE
docker-compose启动后，log显示：【pg       | popen failure: Cannot allocate memory】

### ISSUE THREAD

**Issue by ZDF64** [labring/FastGPT#1061]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
按照docker-compose部署方法启动后，打印日志发现后台报错
pg       | popen failure: Cannot allocate memory
pg       | initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/15/bin/initdb"

这个问题导致ankane/pgvector:v0.5.0反复重启，无法正常运作
![image](https://github.com/labring/FastGPT/assets/15723054/b87c4b8f-c8dd-4404-956d-a69802f31502)

但同样，我在windows环境中部署则没有发生问题
FastGPT功能正常，log中也没有报错信息
**复现步骤**
环境：CentOS 7.9
![image](https://github.com/labring/FastGPT/assets/15723054/181e37a9-a9e7-4ad3-8d53-bb4386482f2b)

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/15723054/996a6856-7dca-4920-87ae-652b6f52b6ae)

**Comment by c121914yu** [comment]
内核太低了

**Comment by ZDF64** [comment]
> 内核太低了

您的意思，就是系统版本太久了，是么

**Comment by ZDF64** [comment]
折腾了一晚上，查阅到了相关一个资料
https://qiita.com/Y__Mori/items/51090da0fe13520ac14a
需要特殊的postgres版本，也就是postgres:15-bullseye
于是我下载了git@github.com:pgvector/pgvector.git
更改了Dockerfile
------------Dockerfile--------------

`ARG PG_MAJOR=15-bullseye`
`FROM postgres:$PG_MAJOR`
`ARG PG_MAJOR`
`COPY . /tmp/pgvector`
`RUN apt-get update && \`
`    apt-mark hold locales && \`
`    apt-get install -y --no-install-recommends build-essential postgresql-server-dev-$PG_MAJOR && \`
`    cd /tmp/pgvector && \`
`    make clean && \`
`    make OPTFLAGS="" && \`
`    make install && \`
`    mkdir /usr/share/doc/pgvector && \`
`    cp LICENSE README.md /usr/share/doc/pgvector && \`
`    rm -r /tmp/pgvector && \`
`    apt-get remove -y build-essential postgresql-server-dev-$PG_MAJOR && \`
`    apt-get autoremove -y && \`
`    apt-mark unhold locales && \`
`    rm -rf /var/lib/apt/lists/*`
------------Dockerfile--------------
重新制作镜像放到本地库
![image](https://github.com/labring/FastGPT/assets/15723054/3b5b7fe2-fd5c-4574-950b-fc7f3713438f)
![image](https://github.com/labring/FastGPT/assets/15723054/64cabc34-3901-42b6-bfc7-c16f4c5f8b05)
然后在修改docker-compose.yml引入刚才做好的image
![image](https://github.com/labring/FastGPT/assets/15723054/ed9b1d2c-f727-4976-882a-08b8efe8d4f4)
之后再启动就不报错了，FastGPT也能正常登陆了
![image](https://github.com/labring/FastGPT/assets/15723054/57ae04b4-9179-405e-90e4-34884b6d9736)

**Comment by c121914yu** [comment]
> 折腾了一晚上，查阅到了相关一个资料
> https://qiita.com/Y__Mori/items/51090da0fe13520ac14a
> 需要特殊的postgres版本，也就是postgres:15-bullseye
> 于是我下载了git@github.com:pgvector/pgvector.git
> 更改了Dockerfile
> ------------Dockerfile--------------
> 
> `ARG PG_MAJOR=15-bullseye`
> `FROM postgres:$PG_MAJOR`
> `ARG PG_MAJOR`
> `COPY . /tmp/pgvector`
> `RUN apt-get update && \`
> `    apt-mark hold locales && \`
> `    apt-get install -y --no-install-recommends build-essential postgresql-server-dev-$PG_MAJOR && \`
> `    cd /tmp/pgvector && \`
> `    make clean && \`
> `    make OPTFLAGS="" && \`
> `    make install && \`
> `    mkdir /usr/share/doc/pgvector && \`
> `    cp LICENSE README.md /usr/share/doc/pgvector && \`
> `    rm -r /tmp/pgvector && \`
> `    apt-get remove -y build-essential postgresql-server-dev-$PG_MAJOR && \`
> `    apt-get autoremove -y && \`
> `    apt-mark unhold locales && \`
> `    rm -rf /var/lib/apt/lists/*`
> ------------Dockerfile--------------
> 重新制作镜像放到本地库
> ![image](https://github.com/labring/FastGPT/assets/15723054/3b5b7fe2-fd5c-4574-950b-fc7f3713438f)
> ![image](https://github.com/labring/FastGPT/assets/15723054/64cabc34-3901-42b6-bfc7-c16f4c5f8b05)
> 然后在修改docker-compose.yml引入刚才做好的image
> ![image](https://github.com/labring/FastGPT/assets/15723054/ed9b1d2c-f727-4976-882a-08b8efe8d4f4)
> 之后再启动就不报错了，FastGPT也能正常登陆了
> ![image](https://github.com/labring/FastGPT/assets/15723054/57ae04b4-9179-405e-90e4-34884b6d9736)
> 

大佬牛逼。
这个确实挺坑的，我之前 centos7 也初始化不了。
后面是找了个 unbuntu 运行后，直接把 data 目录拷贝回去，这样就不用初始化了。

**Comment by c121914yu** [comment]
引用之前 issue https://github.com/labring/FastGPT/issues/784

据说增加 privileged=true 也可以解决

**Comment by atzq1234** [comment]
> 引用之前 issue #784
> 
> 据说增加 privileged=true 也可以解决

nb，解决不了，试试这个，有时候就是万能救命方案

**Comment by abxxxi** [comment]
> > 引用之前 issue [#784](https://github.com/labring/FastGPT/issues/784)
> > 据说增加 privileged=true 也可以解决
> 
> nb，解决不了，试试这个，有时候就是万能救命方案

绝！搞了1个多小时，privileged=true解决了

**Comment by six-double-seven** [comment]
> 引用之前 issue [#784](https://github.com/labring/FastGPT/issues/784)
> 
> 据说增加 privileged=true 也可以解决

牛 好用

**Comment by abxxxi** [comment]
您好，已收到你的邮件，我会尽快处理。————————————这是来自QQ邮箱的自动回复邮件。
