### ISSUE TITLE
调用oneapi报错，请问怎么解决

### ISSUE THREAD

**Issue by lixingxing1231** [labring/FastGPT#1063]
[ERROR] 2024-03-26 00:37:22 sse error: bad_response_status_code  (request id: 2024032600371937190689128646579) 
{
  message: '500  (request id: 2024032600371937190689128646579)',
  stack: 'Error: 500  (request id: 2024032600371937190689128646579)\n' +
    '    at eL.generate (/app/projects/app/.next/server/chunks/53204.js:21:70210)\n' +
    '    at ax.makeStatusError (/app/projects/app/.next/server/chunks/53204.js:21:81454)\n' +
    '    at ax.makeRequest (/app/projects/app/.next/server/chunks/53204.js:21:82188)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async u (/app/projects/app/.next/server/chunks/31119.js:85:200)\n' +
    '    at async /app/projects/app/.next/server/chunks/31119.js:87:255\n' +
    '    at async i (/app/projects/app/.next/server/chunks/31119.js:87:216)\n' +
    '    at async Object.d [as datasetSearchNode] (/app/projects/app/.next/server/chunks/1492.js:85:3561)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/1492.js:85:7125)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/1492.js:85:8195)\n' +
    '    at async l (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2751)'

**Comment by xiaoToby** [comment]
还有其他的报错日志吗，这个日志看不出什么问题

**Comment by c121914yu** [comment]
看不出，这个是上游报错。。基本上是一些自己部署的模型，报错信息不清楚。

**Comment by lixingxing1231** [comment]
![image](https://github.com/labring/FastGPT/assets/22806545/bd8a4433-c26f-4c48-9066-5ff93864af03)
![image](https://github.com/labring/FastGPT/assets/22806545/a5e6b36a-570f-4d07-ae6d-ea643ee3786a)
就是我请求fastgpt的接口传参stream为false时返回报错，为true时有能正常返回，不知道是什么原因

**Comment by c121914yu** [comment]
模型问题，你这个肯定是自己部署的模型吧？ 有些接口都不适配非stream

**Comment by lixingxing1231** [comment]
![image](https://github.com/labring/FastGPT/assets/22806545/5d5aee41-3543-4e09-ae20-bdc6fca89255)
测试过接口是支持非stream模式的

**Comment by Yuuchuin** [comment]
我在遇到了跟你一模一样的问题，我是改了yml里面oneapi的baseUrl后，没有更新。docker-compose up -d 更新一下就解了

**Comment by lixingxing1231** [comment]
那我这个不一样，我都重启n遍了

**Comment by c121914yu** [comment]
> ![image](https://private-user-images.githubusercontent.com/22806545/317203607-5d5aee41-3543-4e09-ae20-bdc6fca89255.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzM4NjgsIm5iZiI6MTcxMTk3MzU2OCwicGF0aCI6Ii8yMjgwNjU0NS8zMTcyMDM2MDctNWQ1YWVlNDEtMzU0My00ZTA5LWFlMjAtYmRjNmZjYTg5MjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyMTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1Y2MyZmFiOTY2ODBiYmYzNDkxNzNlZGMyOTA2MWYwZDQyYzUwMzVmOTk4NDFlMTM4ZmIzYTE2NTA1ZTZkZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9l-640nHyXDUmXS2BDvMj_bM0FLCodSCJygfLvhcLGI) 测试过接口是支持非stream模式的

你这个不是oneapi地址把

**Comment by lixingxing1231** [comment]
![Uploading image.png…]()
我这是oneapi的地址

**Comment by haibincoder** [comment]
我遇到过和你一样的问题，非stream没问题，stream模式报500

当时解决流程如下：
每个模块都加日志，抓到日志后用curl或postman直接调用接口，一层一层看是哪个模块的接口问题，fastgpt->oneapi->本地模型

后面发现问题如下：
本地模型处理参数的方式不对，改了一下模型入参

**Comment by xiaoToby** [comment]
@haibincoder 
How to "每个模块都加日志"?
