### ISSUE TITLE
通过api接口访问对话，流失返回数据有问题

### ISSUE THREAD

**Issue by zhangshuo687686** [labring/FastGPT#1064]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
对话接口,请求参数中配置  detail=false,stream=true ，结果是流失返回。问题是返回的结果是在fastGPT生成结果后以流失返回，每条返回的数据时间间隔极端，造成在页面展示的时候感觉不到流失展示，像是一次展示结果。
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
这是要你客户端处理。。服务器肯定要第一时间返回。
