### ISSUE TITLE
添加一个js编辑器模块

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#1065]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
可否添加一个可以在AI编排页面中使用的js执行模块？
可以处理一些自定义的判断，字符处理，随机数等

还有一个
我通过webdis将redis接入来管理状态，能不能添加一个clear（删除会话）功能的回调呢？

**应用场景**

**相关示例**

**Comment by AlanLee1996** [comment]
很需要这个功能，比如字符串编辑，能用js就太方便了，python也行

**Comment by bincooo** [comment]
这是我做的折中处理... 😂😂😂
<img width="516" alt="Screenshot 2024-03-29 at 08 31 10" src="https://github.com/labring/FastGPT/assets/36452456/6b6ac1a3-7ca5-4a9a-8aa2-1511a13f73b8">

**Comment by AlanLee1996** [comment]
> 这是我做的折中处理... 😂😂😂 <img alt="Screenshot 2024-03-29 at 08 31 10" width="516" src="https://private-user-images.githubusercontent.com/36452456/317920375-6b6ac1a3-7ca5-4a9a-8aa2-1511a13f73b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NzUwNjUsIm5iZiI6MTcxMTY3NDc2NSwicGF0aCI6Ii8zNjQ1MjQ1Ni8zMTc5MjAzNzUtNmI2YWMxYTMtN2NhNS00YTlhLThhYTItMTUxMWExM2Y3M2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAxMTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjVlOWQ1YWZmNDU5YjZkYzAyY2M3MDk0MGZhOTdhZjg5NTA1ODYyMTYwZDJlZmM5NWJjMjE2ZjMxMjkxYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3wMLW28hihhdxX5r-lGgJ334OhmRS6pPrN57pyRMyEk">
> 
> 希望作者能改一下，body也不要限制为json了吧

你能玩成这样也是牛逼，但是太麻烦了还不如写个api，这也说明fastgpt完全可以做这种模块
@c121914yu

**Comment by AlanLee1996** [comment]
我自己实现了下，起一个node服务，使用eval执行代码并返回
![image](https://github.com/labring/FastGPT/assets/20987229/c2897c48-5085-4961-a4e4-e9fcff3b6fcc)
fastgpt里这么写
![image](https://github.com/labring/FastGPT/assets/20987229/f67781aa-900f-46c7-8cca-1b8fc161e9dc)
很好实现的功能哈哈，官方完全可以做个，前端带代码编辑器和变量传入。
@c121914yu

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/1120 已增加laf

**Comment by bincooo** [comment]
这种脚本执行不放沙箱环境嘛？
