### ISSUE TITLE
搜索测试里的“全文检索”展示的搜索结果不全

### ISSUE THREAD

**Issue by buctllx** [labring/FastGPT#1066]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  v4.6.9

**问题描述**
搜索测试里的“全文检索”展示的搜索结果不全；目前测试发现和知识库-数据集 里的搜索框的搜索结果不一样；
搜索测试里的“全文检索”只有一个搜索结果；而知识库-数据集 里的搜索框的搜索 有两个结果
具体截图如下：
![企业微信截图_17114434632208](https://github.com/labring/FastGPT/assets/12623648/d0e13d49-cbbf-4bc6-b8d2-d60ab0126ba4)

![image](https://github.com/labring/FastGPT/assets/12623648/f64c5d1b-3a7a-47c1-a8e9-26a5939da1c0)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
分数低于一定值，全文检索不会返回

**Comment by buctllx** [comment]
> 分数低于一定值，全文检索不会返回

全文检索的这个召回分数在哪里设置？有修改的入口吗？

**Comment by c121914yu** [comment]
> > 分数低于一定值，全文检索不会返回
> 
> 全文检索的这个召回分数在哪里设置？有修改的入口吗？

数据库决定，估计得翻 mongo 源码
