### ISSUE TITLE
关于对话过程中，依据的上下文数量的问题

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1067]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
![image](https://github.com/labring/FastGPT/assets/40045458/e5f3a8de-6bf5-4955-91ea-4ae70b8e7d0c)
如图所示，现在fastgpt对话功能中支持的依据**8**条上下文，这个数量是否可以更改？
@c121914yu 
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
高级编排
