### ISSUE TITLE
fastGPT容器不能起动

### ISSUE THREAD

**Issue by zhi42live** [labring/FastGPT#1069]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**2.6.9**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述**
fastGPT容器不能启动，不断尝试，关键是没有任何日志。我修改为2.6.4版本一切正常。

**复现步骤**

**预期结果**

**相关截图**
![be00539b95b8fa9e15992b5780a0a85](https://github.com/labring/FastGPT/assets/33366192/a376b079-8cf7-4fa6-b94e-4d367d92cb97)

![ec2a976b091224018602c2816c29b6a](https://github.com/labring/FastGPT/assets/33366192/b49ccbd5-6174-4171-aedc-d8ae84a33f1d)

**Comment by c121914yu** [comment]
暂时没遇到过
