### ISSUE TITLE
希望知识库的网络地址能支持微软的confluence登录，并下载页面内容

### ISSUE THREAD

**Issue by warlockedward** [labring/FastGPT#1070]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
目前的知识库针对网络页面的下载无法支持有登入情况的页面下载内容方式
**应用场景**
企业大量的文档或者知识库都保存在特定的网络空间内，如使用微软认证的confluence，对于下载相关页面信息失败，希望能有接口可以处理类似的任务
**相关示例**

**Comment by c121914yu** [comment]
最近设计外部文件库，这种鉴权问题不好解决，每家鉴权不一样，不打算做单独适配。这种建议通过 api 导入。
页面导入主要是可直接访问的外部资源或临时可访问的链接。
