### ISSUE TITLE
ERROR: Invalid interpolation format for "entrypoint" option in service "mongo": "openssl rand -base64 128 > /data/mongodb.key

### ISSUE THREAD

**Issue by zhseasm** [labring/FastGPT#1073]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X ] 我已确认目前没有类似 issue
- [X ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [X ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [X ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X ] 私有部署版本, 具体版本号: 

**问题描述**
ERROR: Invalid interpolation format for "entrypoint" option in service "mongo": "openssl rand -base64 128 > /data/mongodb.key
**复现步骤**
docker-compose up -d 
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/34650924/31360754-9d6f-4e14-97dc-1967da3594b2)

**Comment by zhseasm** [comment]
解决办法：
![image](https://github.com/labring/FastGPT/assets/34650924/23d48258-fb1c-4635-841d-9f25cb6fcb33)
改成

**Comment by nongmo677** [comment]
> 解决办法： ![image](https://private-user-images.githubusercontent.com/34650924/317100972-23d48258-fb1c-4635-841d-9f25cb6fcb33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDg0NjIsIm5iZiI6MTcxMTUwODE2MiwicGF0aCI6Ii8zNDY1MDkyNC8zMTcxMDA5NzItMjNkNDgyNTgtZmIxYy00NjM1LTg0MWQtOWYyNWNiNmZjYjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAyNTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYTZkMTZjNzM3ZGUyNjZhNzI3OThmZDNjOTEyMTNmZmY4NGZjOWI1NDZhN2EyOWMwMGZhN2M4Zjc5ZTk2NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7giRiWnujUOIt3Z818MzueeIDAcP9hKjd0pcry8TvAk) 改成 ![image](https://private-user-images.githubusercontent.com/34650924/317101226-85fd2daf-2694-469c-8747-761198cfadba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDg0NjIsIm5iZiI6MTcxMTUwODE2MiwicGF0aCI6Ii8zNDY1MDkyNC8zMTcxMDEyMjYtODVmZDJkYWYtMjY5NC00NjljLTg3NDctNzYxMTk4Y2ZhZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAyNTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YzBhZGEyZGI4OGI3M2I0MzJiY2JmY2MxMGQ0N2FiNTI3OGYzZGQ1Zjk4MTJmZDBmN2Y4YTc3YjQ1NmZjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Egz4ofTH-czxmc4r3az6qx0xmHSfEe-SEi5Y8rgZ3sY)

没看懂这个解决方案欸，有`$$`@和`$$!`这种表示形式吗

**Comment by c121914yu** [comment]
docker-compose版本太低

**Comment by zhseasm** [comment]
> > 解决办法： ![image](https://private-user-images.githubusercontent.com/34650924/317100972-23d48258-fb1c-4635-841d-9f25cb6fcb33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDg0NjIsIm5iZiI6MTcxMTUwODE2MiwicGF0aCI6Ii8zNDY1MDkyNC8zMTcxMDA5NzItMjNkNDgyNTgtZmIxYy00NjM1LTg0MWQtOWYyNWNiNmZjYjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAyNTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYTZkMTZjNzM3ZGUyNjZhNzI3OThmZDNjOTEyMTNmZmY4NGZjOWI1NDZhN2EyOWMwMGZhN2M4Zjc5ZTk2NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7giRiWnujUOIt3Z818MzueeIDAcP9hKjd0pcry8TvAk) 改成 ![image](https://private-user-images.githubusercontent.com/34650924/317101226-85fd2daf-2694-469c-8747-761198cfadba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDg0NjIsIm5iZiI6MTcxMTUwODE2MiwicGF0aCI6Ii8zNDY1MDkyNC8zMTcxMDEyMjYtODVmZDJkYWYtMjY5NC00NjljLTg3NDctNzYxMTk4Y2ZhZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAyNTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YzBhZGEyZGI4OGI3M2I0MzJiY2JmY2MxMGQ0N2FiNTI3OGYzZGQ1Zjk4MTJmZDBmN2Y4YTc3YjQ1NmZjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Egz4ofTH-czxmc4r3az6qx0xmHSfEe-SEi5Y8rgZ3sY)
> 
> 没看懂这个解决方案欸，有`$$@`和`$$!`这种表示形式吗

就是把docker-compose里的这两个部分改成下面这个图片这样，就可以启动了，我是这么操作的

**Comment by zhseasm** [comment]
> docker-compose版本太低。最好用2.17+
谢谢解答
