### ISSUE TITLE
Failed to release the helm chart

### ISSUE THREAD

**Issue by LinuxSuRen** [labring/FastGPT#1081]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
The version is invalid.

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/1450685/0d158440-f0de-4a00-9a36-d7d18dd3a6f7)

**Comment by LinuxSuRen** [comment]
Caused by https://github.com/labring/FastGPT/pull/1023

**Comment by LinuxSuRen** [comment]
hi @c121914yu ，一个简单的办法就是不在 `main` 分支变更时发布 helm chart。你觉得如何？

**Comment by c121914yu** [comment]
> hi @c121914yu ，一个简单的办法就是不在 `main` 分支变更时发布 helm chart。你觉得如何？

可以考虑改成手动触发？

**Comment by LinuxSuRen** [comment]
个人建议是在发布 release tag 时触发，并支持手动处罚。

**Comment by c121914yu** [comment]
> 个人建议是在发布 release tag 时触发，并支持手动处罚。

可以。我们现在其他action也不是更新触发，tag触发，latest的话是手动
