### ISSUE TITLE
http插件可否不限制json requestBody

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#1084]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
有许多公开的api不是通过application/json传输的
https://github.com/labring/FastGPT/blob/00ace0b69cf63aa6407778dcd0d1622cc67a7e61/packages/service/core/workflow/dispatch/tools/http468.ts#L91

还有一个是问题分类中的聊天记录，我填了1但是貌似无法控制上下文

**复现步骤**

**预期结果**

**相关截图**
<img width="1281" alt="Screenshot 2024-03-28 at 03 47 49" src="https://github.com/labring/FastGPT/assets/36452456/7102fc1c-4d3f-4224-9b1b-cd045b4155e1">
<img width="1382" alt="Screenshot 2024-03-28 at 03 48 22" src="https://github.com/labring/FastGPT/assets/36452456/8c6e294c-f939-43ec-aff9-b3485dd1b096">

**Comment by bincooo** [comment]
@c121914yu 
https://github.com/labring/FastGPT/blob/00ace0b69cf63aa6407778dcd0d1622cc67a7e61/packages/service/core/workflow/dispatch/tools/http468.ts#L64

请教一下这个位置，最新记录是在左边吗？感觉新对话在右边插入的？
这样是不是会没满30条时，左边10条固定了。。。

**Comment by c121914yu** [comment]
> @c121914yu 
> https://github.com/labring/FastGPT/blob/00ace0b69cf63aa6407778dcd0d1622cc67a7e61/packages/service/core/workflow/dispatch/tools/http468.ts#L64
> 
> 请教一下这个位置，最新记录是在左边吗？感觉新对话在右边插入的？
> 这样是不是会没满30条时，左边10条固定了。。。

确实应该是取后，可以提个pr修复下。

**Comment by bincooo** [comment]
好的谢谢 @c121914yu

**Comment by c121914yu** [comment]
不限制 body 这个，目前可以通过外挂代码实现。后面有时间再看看要不要做进去。

**Comment by bincooo** [comment]
已经通过补丁改了
<img width="625" alt="Screenshot 2024-04-01 at 23 55 47" src="https://github.com/labring/FastGPT/assets/36452456/7c987ab8-19b9-46e6-bbd3-5419914b7c23">

后面还是幸苦一下大佬
