### ISSUE TITLE
升级4.7，重排更新luanshaotong/reranker:v0.2，调用重排时报错

### ISSUE THREAD

**Issue by 2277419213** [labring/FastGPT#1085]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述**
根据步骤升级luanshaotong/reranker:v0.2
![image](https://github.com/labring/FastGPT/assets/37398336/d67f9f13-5292-442c-8c74-c8ec60e99ddb)
启动正常，调用时报错
![image](https://github.com/labring/FastGPT/assets/37398336/c2c031f2-776b-45d0-a23b-7668173d3bcd)
**复现步骤**
如上
采用这个命令部署docker run -d --gpus all --name reranker -p 7222:6006 -e ACCESS_TOKEN=sk-3BiEXXXXXXXXXXXXXX(脱敏一下)b7781 luanshaotong/reranker:v0.2
**预期结果**
不报错，正常执行重排
**相关截图**

**Comment by hd19820806** [comment]
同样报错，172.18.0.1:53330 - "POST /api/v1/rerank HTTP/1.1" 404 Not Found

**Comment by c121914yu** [comment]
> 同样报错，172.18.0.1:53330 - "POST /api/v1/rerank HTTP/1.1" 404 Not Found

没有api

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/1111 看看是不是一个

**Comment by 2277419213** [comment]
> #1111 看看是不是一个

大佬，你终于回来看我了，是同一个问题吧，但是别人是改的fastgpt的源码解决的，我的是容器部署，只能等官方更新了，据说是多了一层data？

**Comment by jzhu888666** [comment]
刚重新拉了registry.cn-hangzhou.aliyuncs.com/fastgpt/rerank:v0.2 
还是报INFO:     172.26.0.3:49654 - "POST /api/v1/rerank HTTP/1.1" 404 Not Found

**Comment by 2277419213** [comment]
> 刚重新拉了registry.cn-hangzhou.aliyuncs.com/fastgpt/rerank:v0.2 还是报INFO: 172.26.0.3:49654 - "POST /api/v1/rerank HTTP/1.1" 404 Not Found

你这个报错要去看一下，你的config.js文件里面配置的rerank地址，和我的错不是同一个

**Comment by 2277419213** [comment]
> 同样报错，172.18.0.1:53330 - "POST /api/v1/rerank HTTP/1.1" 404 Not Found

你这个报错要去看一下，你的config.js文件里面配置的rerank地址，和我的错不是同一个

**Comment by c121914yu** [comment]
> 刚重新拉了registry.cn-hangzhou.aliyuncs.com/fastgpt/rerank:v0.2 还是报INFO: 172.26.0.3:49654 - "POST /api/v1/rerank HTTP/1.1" 404 Not Found

为啥要个api

**Comment by jzhu888666** [comment]
回馈非常慢，在fastgpt里面reranker的提示还是false。 不清楚回答是不是重拍后的结果。看日志后面有把检索出来的信息发给reranker

rerank error: AxiosError: timeout of 30000ms exceeded
    at RedirectableRequest.handleRequestTimeout (file:///app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/adapters/http.js:647:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
    at Axios.request (file:///app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/core/Axios.js:45:41)
    at async q (/app/projects/app/.next/server/chunks/59120.js:85:3465)
    at async g (/app/projects/app/.next/server/chunks/59120.js:86:957)
    at async Object.d [as datasetSearchNode] (/app/projects/app/.next/server/chunks/94900.js:129:3586)
    at async N (/app/projects/app/.next/server/chunks/94900.js:130:2805)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async S (/app/projects/app/.next/server/chunks/94900.js:130:4134)
    at async h (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2771) {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 30000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'Cache-Control': 'no-cache',
      Authorization: 'Bearer shanghai123',
      'User-Agent': 'axios/1.6.8',
      'Content-Length': '26588',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://c7cdc4e82b6a:3000',
    url: 'http://reranker:6006/v1/rerank',
    method: 'post',

**Comment by jzhu888666** [comment]
reranker 这里看提示已经连接成功

INFO:     172.26.0.3:35878 - "POST /v1/rerank HTTP/1.1" 200 OK
INFO:     Started server process [6]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6006 (Press CTRL+C to quit)
/opt/conda/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

**Comment by jzhu888666** [comment]
换了台配置高点的机器，看上去是重排成功了，看提示也是重排成功，但是所有经过重排的回答都说找不到相应答案，关了重排一切正常。

[INFO] 2024-04-03 05:32:00 [QA Queue] Done 
[INFO] 2024-04-03 05:32:00 [Vector Queue] Done 
rerank time: 15061

**Comment by MusicOfWind** [comment]
> > #1111 看看是不是一个
> 
> 大佬，你终于回来看我了，是同一个问题吧，但是别人是改的fastgpt的源码解决的，我的是容器部署，只能等官方更新了，据说是多了一层data？

老哥，你之前 v4.6.x 版本有成功接入的 rerank 版本吗

**Comment by MusicOfWind** [comment]
> 换了台配置高点的机器，看上去是重排成功了，看提示也是重排成功，但是所有经过重排的回答都说找不到相应答案，关了重排一切正常。
> 
> [INFO] 2024-04-03 05:32:00 [QA Queue] Done [INFO] 2024-04-03 05:32:00 [Vector Queue] Done rerank time: 15061

老哥，你换个机器就可以重排了是吧？

**Comment by hd19820806** [comment]
> > 换了台配置高点的机器，看上去是重排成功了，看提示也是重排成功，但是所有经过重排的回答都说找不到相应答案，关了重排一切正常。
> > [INFO] 2024-04-03 05:32:00 [QA Queue] Done [INFO] 2024-04-03 05:32:00 [Vector Queue] Done rerank time: 15061
> 
> 老哥，你换个机器就可以重排了是吧？

还在折腾自己重排啊？调用 硅基流动 的免费重排api不香吗？
