### ISSUE TITLE
tts 试听报 “凭证错误”

### ISSUE THREAD

**Issue by MaricoHan** [labring/FastGPT#1088]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:v4.6.9 

**问题描述**

docker-compose 部署的最新版， tts 试听没反应，检查发现返回凭证错误（使用的 https://api.openai.com/v1 ，llm 聊天都是正常输出的），不知道 tts 试听为啥报错：

```json
{"code":403,"statusText":"unAuthorization","message":"凭证错误","data":null}
```

**复现步骤**
本地部署，必现
**预期结果**
试听成功
**相关截图**
![image](https://github.com/labring/FastGPT/assets/92877246/f9f8354e-6a4a-4573-8743-0b43ad1ef805)

**Comment by MaricoHan** [comment]
发现使用 https 访问 fastgpt 就可以试听成功了，但是原因未知，感觉是个 bug

**Comment by c121914yu** [comment]
不是https不支持cookie，流接口需要cookie校验。
