### ISSUE TITLE
【参数配置】调用reRank模型接口时，timeout属性可配置

### ISSUE THREAD

**Issue by guobinkim** [labring/FastGPT#1090]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
类路径：packages\service\core\ai\rerank\index.ts
function：reRankRecall
期望37行的timeout属性可配置，目前是固定30秒。
**应用场景**
升级到V4.7版本后发现重排序特性不起作用，看错误日志是调用rerank接口超时了，上一版本该值设置的较大，所以没有问题，现在只有30秒，在条数多的情况下有可能超时，导致重排序不起作用。希望能够配置在config.json中reRankModels下。
**相关示例**

**Comment by 2277419213** [comment]
你看看你的reRank的日志，是不是和我一样报错了，我感觉不是超时问题
https://github.com/labring/FastGPT/issues/1085

**Comment by guobinkim** [comment]
我看日志是超时的，提示超过30000，之后看了下代码，参数是30000，上一个版本好像是120000。

**Comment by c121914yu** [comment]
> 我看日志是超时的，提示超过30000，之后看了下代码，参数是30000，上一个版本好像是120000。

一个重排超过 30s 还有意义么

**Comment by guobinkim** [comment]
有没有意义是另一个话题，只是提供下优化建议。

**Comment by 2277419213** [comment]
> 我看日志是超时的，提示超过30000，之后看了下代码，参数是30000，上一个版本好像是120000。

看fastgpt的日志，是重排超时，你的reRank日志是不是报错了，重排超时是因为reRank报错没有返回，正常的话，重排应该是很快的

**Comment by 2277419213** [comment]
> > 我看日志是超时的，提示超过30000，之后看了下代码，参数是30000，上一个版本好像是120000。
> 
> 一个重排超过 30s 还有意义么，甚至超过 10s 应该中断了。

大佬，看看这个https://github.com/labring/FastGPT/issues/1085

**Comment by guobinkim** [comment]
嗯嗯，问题和你发的那个不太一样哈，确定是因为超时：

1、4.7后rerank接口有变化，我也按照提供的样例调整了，测试是OK的。
2、可能是因为我查出来的数据有点多，加上我是在自己的电脑上跑的，性能不好，所以rerank超过30多秒。
3、我把召回的token限制了下，就正常了。

正常情况下30秒应该没问题的，如果能做个参数配置，那就更好了哈。

**Comment by c121914yu** [comment]
> 嗯嗯，问题和你发的那个不太一样哈，确定是因为超时：
> 
> 1、4.7后rerank接口有变化，我也按照提供的样例调整了，测试是OK的。
> 2、可能是因为我查出来的数据有点多，加上我是在自己的电脑上跑的，性能不好，所以rerank超过30多秒。
> 3、我把召回的token限制了下，就正常了。
> 
> 正常情况下30秒应该没问题的，如果能做个参数配置，那就更好了哈。

变量太多管理不方便，配置起来还得李姐，大部分参数以正常使用的设置就好。
可能你是纯 cpu 运行，加个显卡好很多，搞个 2080ti 这种性价比的跑比较香。

**Comment by c121914yu** [comment]
> > > 我看日志是超时的，提示超过30000，之后看了下代码，参数是30000，上一个版本好像是120000。
> > 
> > 一个重排超过 30s 还有意义么，甚至超过 10s 应该中断了。
> 
> 大佬，看看这个https://github.com/labring/FastGPT/issues/1085

得等搞这个模型的人看看👀

**Comment by 2277419213** [comment]
> > 嗯嗯，问题和你发的那个不太一样哈，确定是因为超时：
> > 1、4.7后rerank接口有变化，我也按照提供的样例调整了，测试是OK的。
> > 2、可能是因为我查出来的数据有点多，加上我是在自己的电脑上跑的，性能不好，所以rerank超过30多秒。
> > 3、我把召回的token限制了下，就正常了。
> > 正常情况下30秒应该没问题的，如果能做个参数配置，那就更好了哈。
> 
> 变量太多管理不方便，配置起来还得李姐，大部分参数以正常使用的设置就好。 可能你是纯 cpu 运行，加个显卡好很多，搞个 2080ti 这种性价比的跑比较香。



> > > > 我看日志是超时的，提示超过30000，之后看了下代码，参数是30000，上一个版本好像是120000。
> > > 
> > > 
> > > 一个重排超过 30s 还有意义么，甚至超过 10s 应该中断了。
> > 
> > 
> > 大佬，看看这个#1085
> 
> 得等搞这个模型的人看看👀

帮我艾特他一下大佬
