### ISSUE TITLE
问题分类无法正常实现

### ISSUE THREAD

**Issue by Lands-1203** [labring/FastGPT#1093]
尝试了很多模型，问题分类都无法正常实现，我怀疑是不是fastGpt没有对接好？

**Comment by nongmo677** [comment]
请确保你模型支持function calling，本质上在做的是结构化数据的提取
说白了，fastgpt这个功能一开始对接的是gpt的能力，其他的模型请确保模型的官方说支持工具调用，在这个前提下调整提示词使得模型理解和解析给定的指令

**Comment by c121914yu** [comment]
😂我试了国内商业的基本都行，就是准确率只有 60 70

**Comment by c121914yu** [comment]
> 请确保你模型支持function calling，本质上在做的是结构化数据的提取
> 说白了，fastgpt这个功能一开始对接的是gpt的能力，其他的模型请确保模型的官方说支持工具调用，在这个前提下调整提示词使得模型理解和解析给定的指令

提示词模式也可以，用 few shot 没太大区别。

**Comment by nongmo677** [comment]
> > 请确保你模型支持function calling，本质上在做的是结构化数据的提取
> > 说白了，fastgpt这个功能一开始对接的是gpt的能力，其他的模型请确保模型的官方说支持工具调用，在这个前提下调整提示词使得模型理解和解析给定的指令
> 
> 提示词模式也可以，用 few shot 没太大区别。
> 大概率是，楼主配置有问题，不支持 fc 的向量模型也设置 fc 模式。

哈哈，我还是旧版本，没看到有提示词模式，不过确实始终是调提示词的问题
