### ISSUE TITLE
知识库上传word文档里面带有截图，进行问答时候，同样的问题，有时候回答带着截图多数不带截图，什么原因？

### ISSUE THREAD

**Issue by Andy1018** [labring/FastGPT#1097]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
知识库上传word文档里面带有截图，进行问答时候，同样的问题，有时候回答带着截图多数不带截图，什么原因？
**复现步骤**

**预期结果**
答案中应该带着截图
**相关截图**

**Comment by lijiajun1997** [comment]
我理解应该都不会出现图片来着

**Comment by WestCraneLi** [comment]
代码中有支持图片
![image](https://github.com/labring/FastGPT/assets/76116480/6b9a91f8-8262-42f3-be99-e755040a0ba6)
估计是代码问题了

**Comment by c121914yu** [comment]
那不是模型问题么

**Comment by jackieZhouQQ** [comment]
我也遇到了，用的gpt3.5接口，有啥模型会回复图片吗
