### ISSUE TITLE
知识库导入文件训练报错Incorrect API key provided: sk-zm7FU***************************************16Cc. You can find your API key at https://xxx (request id: 2024032918120050192168135107491)"

### ISSUE THREAD

**Issue by hlovingness** [labring/FastGPT#1098]
这是什么问题，我没有这个 sk，我配置的sk 是另外一个
![image](https://github.com/labring/FastGPT/assets/16331459/e1327a6d-7d01-4678-9be1-1bc41ae02d64)

**Comment by hlovingness** [comment]
我传过去的模型是 文心，但是这里走的还是 openai 的
![image](https://github.com/labring/FastGPT/assets/16331459/8e31b84e-88d8-4de5-b6b3-6b53cb84a2e7)
还有一个问题是，这里选择处理模型无用，默认是第一个，但是选择其他也是传的第一个

**Comment by c121914yu** [comment]
> 我传过去的模型是 文心，但是这里走的还是 openai 的
> ![image](https://github.com/labring/FastGPT/assets/16331459/8e31b84e-88d8-4de5-b6b3-6b53cb84a2e7)
> 还有一个问题是，这里选择处理模型无用，默认是第一个，但是选择其他也是传的第一个

没遇到，我这可以自由选择处理模型。有更多信息？
你截图那个是问题补全，和知识库没啥关系。

**Comment by hlovingness** [comment]
我选择处理模型后，但是在测试时候传的都是第一个模型，我这里文心一言我是在配置文件里面把 文心一言放到了第一个，然后我传过去的是 NRNIE-Bot,但是响应的都是 openai 的
![image](https://github.com/labring/FastGPT/assets/16331459/2f07667e-e3ec-4b6f-b02f-a46f195c0b63)

**Comment by c121914yu** [comment]
> 我选择处理模型后，但是在测试时候传的都是第一个模型，我这里文心一言我是在配置文件里面把 文心一言放到了第一个，然后我传过去的是 NRNIE-Bot,但是响应的都是 openai 的
> ![image](https://github.com/labring/FastGPT/assets/16331459/2f07667e-e3ec-4b6f-b02f-a46f195c0b63)
> 

图片看不出啥问题，而且你也用了 openai 的向量模型
