### ISSUE TITLE
自动完成文档

### ISSUE THREAD

**Issue by sunth888** [labring/FastGPT#1101]
**例行检查**

[//]: # '方框内填 x 表示打钩'

-[x] 我已确认目前没有类似 features
- [x]我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
   回答问题输出到word文档，可以直接下载。
**应用场景**
   我写一些说明文档，一次问题后，可以根据知识库&&事先准备的目录，一次次问答AI，将问答内容逐步插入word中，直接下载。
**相关示例**

**Comment by lijiajun1997** [comment]
建议用gpt写一个python，多次请求fastgpt的api  估计作者暂时没有这个计划

**Comment by c121914yu** [comment]
这个不会有，建议通过api自己实现~
