### ISSUE TITLE
更新私有部署版本初始化脚本时出错

### ISSUE THREAD

**Issue by LinhanXu3928** [labring/FastGPT#1102]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述**
更新4.7版本时，初始化脚本的步骤，报错
**复现步骤**
执行完docker-compose pull
docker-compose up -d后
sudo curl --location --request POST 'https://10.122.92.2/api/admin/initv47' --header 'rootkey: root_key' --header 'Content-Type: application/json'
报错：curl: (7) Failed to connect to 10.122.92.2 port 443 after 0 ms: 连接被拒绝
**预期结果**
成功更新
**相关截图**
![image](https://github.com/labring/FastGPT/assets/86815251/ec81624e-da62-48f8-8a2a-84210f5fa5fd)

**Comment by c121914yu** [comment]
老哥，，你是ip，哪里有https~
