### ISSUE TITLE
v4.7没有重排问题

### ISSUE THREAD

**Issue by xiaohaiqing** [labring/FastGPT#1111]
![image](https://github.com/labring/FastGPT/assets/28615061/1321a66c-d7fa-480b-863c-562d396a24c7)
![image](https://github.com/labring/FastGPT/assets/28615061/8ac9ae04-6df3-4827-8b2a-ffa7cca522f6)
升级到4.7版本后，设置中已经开启了结果重排，结果实际进行对话时却没有，请问这是什么原因呢？

**Comment by xiaohaiqing** [comment]
reranker版本已经根据升级说明升级到了v0.2版本

**Comment by Andy1018** [comment]
@c121914yu 我也遇到，同样的问题。reranker可以调用成功，但是前端显示false，如何排查此问题啊？

**Comment by Andy1018** [comment]
reranker v2.0打印日志
[root@adsl-172-10-0-187 fastgpt]# docker logs -f 37fa8c360ee8
INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6006 (Press CTRL+C to quit)
/opt/conda/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
INFO:     172.10.0.197:59754 - "POST /v1/rerank HTTP/1.1" 200 OK

**Comment by c121914yu** [comment]
更新个经验 ethandai4869/bge:v0.2 
文档迟点改

**Comment by Kaiwen6** [comment]
本地部署已按要求更改配置文件和代码，能调用成功且不报错，但实际没有重排，请问是咋回事
![Snipaste_2024-04-01_17-26-00](https://github.com/labring/FastGPT/assets/71768682/1ae0d777-9d6e-4aec-bb3d-9be0f6874738)
![Snipaste_2024-04-01_17-25-23](https://github.com/labring/FastGPT/assets/71768682/f74ecef6-69a0-4496-9f92-cb16942da82e)

**Comment by c121914yu** [comment]
> 已找到问题，代码中rerank0.2返回数据的结构有变化

ethandai4869/bge:v0.2 试试这个镜像。

**Comment by c121914yu** [comment]
确实是多了一层数据，之前一直用负载均衡器，没注意这个。。明天让搞模型的老哥看看。

**Comment by 2277419213** [comment]
> UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly. To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
> return self.fget.**get**(instance, owner)()

解决了么

**Comment by c121914yu** [comment]
registry.cn-hangzhou.aliyuncs.com/fastgpt/rerank:v0.2 更新镜像

**Comment by sunlin-xiaonai** [comment]
我解决了重排问题做了视频记录，需要的可以看我的
YouTube：https://www.youtube.com/watch?v=M4DQhA_D8TU
b站：https://www.bilibili.com/video/BV1Lp42197yg/?spm_id_from=333.1365.list.card_archive.click

**Comment by MusicOfWind** [comment]
> reranker版本已经根据升级说明升级到了v0.2版本

我的 fastgpt 版本是 v4.6.7，请问老哥前面 reranker 用的是什么版本？

**Comment by MusicOfWind** [comment]
> 已找到问题，代码中rerank0.2返回数据的结构有变化

怎么查看 rerank 返回的数据结构，fastgpt 需要什么样的数据结构

**Comment by MusicOfWind** [comment]
> > > > > UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly. To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
> > > > > return self.fget.**get**(instance, owner)()
> > > > 
> > > > 
> > > > 解决了么
> > > 
> > > 
> > > 我是改的源码，可以了
> > 
> > 
> > 大哥，你改了哪个的源码，fastgpt的还是重排的，教教我
> 
> <img alt="F732F3F3-2606-468e-8F80-626FCBC6905F" width="895" src="https://private-user-images.githubusercontent.com/16043789/318697008-1f96f4d3-a203-40c4-a0dc-38baf6432a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTk3NTksIm5iZiI6MTcyODcxOTQ1OSwicGF0aCI6Ii8xNjA0Mzc4OS8zMTg2OTcwMDgtMWY5NmY0ZDMtYTIwMy00MGM0LWEwZGMtMzhiYWY2NDMyYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3NTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MGYxN2M1MGVhNjA5MTU5N2FjNDJjNjhkYTlhMzA3OGY0MTI0YmVhNTZmZTU2YTVjNDU4YjNkMjE2MDViMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Bgrmsr_AhrA1d429y9dS19dIlIQUNfEtMu50fqo83B8"> <img alt="86F83487-A115-464c-911E-D229C0EB93B6" width="799" src="https://private-user-images.githubusercontent.com/16043789/318697063-2553185d-6f60-4d78-8364-a61561e50f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTk3NTksIm5iZiI6MTcyODcxOTQ1OSwicGF0aCI6Ii8xNjA0Mzc4OS8zMTg2OTcwNjMtMjU1MzE4NWQtNmY2MC00ZDc4LTgzNjQtYTYxNTYxZTUwZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3NTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyM2VjZWE4YmMyODhiN2E0OGQ4MDgyYWQxM2E5YjE0YThkZjA0MDBlODRjOGZmMGZiYjcyNWJkNTI5YWE2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tMnpOSv9VSPs2hphcdmQVMgTn4u9mlBgWzArsMkl-2A">

版本没有如图 rerank 的文件夹代码部分是不是说明版本不支持 rerank
