### ISSUE TITLE
访问子应用请求地址chat/share?shareId=a0rqbwmvzo7p41a0rlpetmyl，特别慢需要10s，有哪个地方可以优化吗？

### ISSUE THREAD

**Issue by Andy1018** [labring/FastGPT#1112]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
<img width="1295" alt="D6F01048-9357-4e29-97E9-36317F45F47D" src="https://github.com/labring/FastGPT/assets/16043789/74699277-0a9e-42b1-b84e-f67ee64d89ee">

**Comment by Andy1018** [comment]
问题补充：源码方式启动，访问速度不慢。换成镜像启动速度就慢

**Comment by Andy1018** [comment]
@hkutangyu 没有。很奇怪的是偶尔重启一次访问速度又快了，这种情况只是偶尔会发生。绝不是硬件问题，无论是cpu、内存还是gpu都有很大空闲。

**Comment by hkutangyu** [comment]
> @hkutangyu 没有。很奇怪的是偶尔重启一次访问速度又快了，这种情况只是偶尔会发生。绝不是硬件问题，无论是cpu、内存还是gpu都有很大空闲。

嗯，我们硬件都是128核，128GB的服务器，8卡3090。确实，我重启一下，就好了。

**Comment by Andy1018** [comment]
@c121914yu 能提供下解决思路吗，比如在某几个请求页面加上日志信息

**Comment by Andy1018** [comment]
> > @c121914yu 能提供下解决思路吗，比如在某几个请求页面加上日志信息
> 
> 可以试试，share 页去掉 ssr，重新打包看看。或者给 ssr 的数据库查询加上时间日志。

是这个页面吗？share.tsx debug好像不走这个页面呢。。。

**Comment by c121914yu** [comment]
> > > @c121914yu 能提供下解决思路吗，比如在某几个请求页面加上日志信息
> > 
> > 可以试试，share 页去掉 ssr，重新打包看看。或者给 ssr 的数据库查询加上时间日志。
> 
> 是这个页面吗？share.tsx debug好像不走这个页面呢。。。

是这个。chat/share

**Comment by Andy1018** [comment]
> > > > @c121914yu 能提供下解决思路吗，比如在某几个请求页面加上日志信息
> > > 
> > > 
> > > 可以试试，share 页去掉 ssr，重新打包看看。或者给 ssr 的数据库查询加上时间日志。
> > 
> > 
> > 是这个页面吗？share.tsx debug好像不走这个页面呢。。。
> 
> 就是这个。 完整点: chat/share.tsx

已测试，并不是share.tsx页面问题，问下在进入_app.tsx前，后台走的是那一部分逻辑？

**Comment by Andy1018** [comment]
> > > > > @c121914yu 能提供下解决思路吗，比如在某几个请求页面加上日志信息
> > > > 
> > > > 
> > > > 可以试试，share 页去掉 ssr，重新打包看看。或者给 ssr 的数据库查询加上时间日志。
> > > 
> > > 
> > > 是这个页面吗？share.tsx debug好像不走这个页面呢。。。
> > 
> > 
> > 就是这个。 完整点: chat/share.tsx
> 
> 已测试，并不是share.tsx页面问题，问下在进入_app.tsx前，后台走的是那一部分逻辑？

进入程序入口页面_app.tsx就很慢，测试方法在_app.tsx function App({ Component, pageProps }: AppProps) {方法加日志，需要10s才会打印

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/1173我在这个Pr中临时修复了这个问题。
关键问题在于，SSR渲染时候，没有使用已连接的数据库实例，目前是临时加了个强制连接操作，但是从日志看，也没看到MongoDB连接的日志（不过解决了数据库查询超时问题）。
具体原因后续继续排查。
