### ISSUE TITLE
status code 403

### ISSUE THREAD

**Issue by 13386420250** [labring/FastGPT#1115]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
填写本地LLM的 Base URL后提示403错误 不知道该如何解决
**复现步骤**

**预期结果**

**相关截图**
<img width="1163" alt="image" src="https://github.com/labring/FastGPT/assets/57855531/8090679c-55de-42fc-860a-9355efb58afe">
<img width="1135" alt="image" src="https://github.com/labring/FastGPT/assets/57855531/35e92f23-a22c-46bb-a765-2b04d40bcf9c">

**Comment by c121914yu** [comment]
大概率鉴权问题

**Comment by hang925** [comment]
你好 请问你解决这个问题了吗
