### ISSUE TITLE
私有部署之后，请求对话接口提示http url is empty

### ISSUE THREAD

**Issue by Romanlink** [labring/FastGPT#1116]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: latest

**问题描述**
私有化部署之后，请求对话接口
curl --location --request POST 'http://ip:3000/api/v1/chat/completions' \
--header 'Authorization: Bearer fastgpt-7kv9zrWbthNnYiPUdWgV0trkym25ArlqBfbxgSElhByTgILbYYW2xLoJnmT5mM' \
--header 'Content-Type: application/json' \
--data-raw '{
    "chatId": "111",
    "stream": false,
    "detail": false,
    "messages": [
        {
            "content": "导演是谁",
            "role": "user"
        }
    ]
}'
----------------------------------------以下是返回结果----------------------------------
{
    "code": 500,
    "statusText": "",
    "message": "Http url is empty",
    "data": null
}

fastgpt容器内日志内容如下：
[INFO] 2024-04-01 10:03:00 [Vector Queue] Done 
[INFO] 2024-04-01 10:04:00 [Vector Queue] Done 
[INFO] 2024-04-01 10:04:00 [QA Queue] Done 
[ERROR] 2024-04-01 10:04:18 response error: Http url is empty 
{ message: 'Http url is empty', stack: undefined }
[ERROR] 2024-04-01 10:04:26 response error: Http url is empty 
{ message: 'Http url is empty', stack: undefined }
[ERROR] 2024-04-01 10:04:27 response error: Http url is empty 
{ message: 'Http url is empty', stack: undefined }

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
编排问题把，没填http模块地址

**Comment by Romanlink** [comment]
@c121914yu 小白求教，要怎么操作，

**Comment by c121914yu** [comment]
> @c121914yu 小白求教，要怎么操作，

看高级编排
