### ISSUE TITLE
有新的微信群吗？有问题，急，求大佬解决。有偿

### ISSUE THREAD

**Issue by Star-cre** [labring/FastGPT#1119]
目前的需求是需要根据数据库导出的表格来进行问答，并且进一步优化，在第一步数据导入的时候就卡住了，csv格式要求的是index和content格式的，但是数据库导出的表格是很杂乱的，该怎么构建？后续如何优化？

**Comment by c121914yu** [comment]
已有，，扫码可进。
必须两列，因为数据存储也是两列。这个是和导出配合用的，其他文件直接导入就行。

**Comment by Star-cre** [comment]
进不去啊哥，那个二维码还是满人的状态。麻烦哥有空看一下
