### ISSUE TITLE
从4.6.8升级到4.6.9后，访问MongoDB出现报错Transaction numbers are only allowed on a replica set member or mongos

### ISSUE THREAD

**Issue by shikaiwei1** [labring/FastGPT#1124]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.6.9

**问题描述**
从4.6.8升级到4.6.9后，在“聊天”模块提问时，对话无法保存。
控制台提示如下报错：
```
{
  message: 'Transaction numbers are only allowed on a replica set member or mongos',
  stack: 'MongoBulkWriteError: Transaction numbers are only allowed on a replica set member or mongos\n' +
    '    at h (/app/projects/app/.next/server/chunks/75165.js:6:74632)\n' +
    '    at /app/projects/app/.next/server/chunks/75165.js:6:359597\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
```

回退到4.6.8版本后，可以正常使用

**部署环境**
- fastgpt:docker
- mongoDB:阿里云-云数据库MongoDB
  - 4.0
  - 单节点版

**Comment by c121914yu** [comment]
没用副本集

**Comment by Toketec** [comment]
简单开发运行，不想浪费精力安装多节点，偏要设置副本集？

**Comment by Leif160519** [comment]
> 简单开发运行，不想浪费精力安装多节点，偏要设置副本集？

我也遇到了这个问题，感觉比较坑，非要副本集

**Comment by xunmenglt** [comment]
有解决的办法吗
