### ISSUE TITLE
增加知识库信息报错

### ISSUE THREAD

**Issue by fairychao** [labring/FastGPT#1126]
**问题描述**
重新部署最新的4.7版本后，新增知识库信息报错，详见如下截图

**复现步骤**

![image](https://github.com/labring/FastGPT/assets/20513651/e722c9a1-006f-4cee-a1e6-4f5e07324201)

![image](https://github.com/labring/FastGPT/assets/20513651/a51630e2-d729-42e1-ae38-1d9eae6caece)

![image](https://github.com/labring/FastGPT/assets/20513651/cc796363-472a-4776-9811-1fbbc5223fb0)

**Comment by jjssjdhhd** [comment]
我也是，知识库老是出错

**Comment by fairychao** [comment]
升级了4.7.1-alpha，仍然报错，具体如下：
1）部署情况
![image](https://github.com/labring/FastGPT/assets/20513651/f715133a-a567-4c02-817c-cf7270e456ed)

2）报错情况
![image](https://github.com/labring/FastGPT/assets/20513651/673af145-3762-4af0-8d7c-b6a5476679cd)

![image](https://github.com/labring/FastGPT/assets/20513651/1342e227-79a6-41c5-a285-7e98873c83ba)

**Comment by c121914yu** [comment]
看着和知识库没啥关系，而且好像代码还没合并把？怎么升级的。

**Comment by fairychao** [comment]
直接修改 docker-compose.yml  image

**Comment by c121914yu** [comment]
401 是 key 报错了，和知识库没啥关系

**Comment by fairychao** [comment]
升级时重新部署oneapi，没有重新部署m3e导致，重新运行m3e容器，设置 sk-key环境变量解决。

**Comment by tony-wuhongtao** [comment]
设置 sk-key环境变量解决
具体怎么设置？
