### ISSUE TITLE
one api  联动问题

### ISSUE THREAD

**Issue by aiastia** [labring/FastGPT#113]
我设置了 ONEAPI_URL=https://xxxxx.cloud.sealos.io/v1
      - ONEAPI_KEY=sk-xxxxxx   
      - 
      为 oneapi的地址 然后运行正常  但是在账户信息页面 openaiKey: 没办法填写 ONEAPI_URL   
提示 Incorrect API key provided: sk- ***************************************D75e. You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by c121914yu** [comment]
oneapi属于系统的，账号页是用户自己的key。 用户的key不走oneapi

**Comment by aiastia** [comment]
我以为是 都走 oneapi
