### ISSUE TITLE
使用one-api ,搭建通义前问api服务，为啥配置的工具调用不生效？

### ISSUE THREAD

**Issue by taishan666** [labring/FastGPT#1130]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by linqinguang** [comment]
同问，kimi也不生效，但是用dify却能正常调工具

**Comment by c121914yu** [comment]
配置文件写不对吧，线上都能用。

**Comment by nEvErMoReaken** [comment]
![image](https://github.com/labring/FastGPT/assets/39018437/23347d9c-b842-4a7e-b6cf-e726feca80f4)

![image](https://github.com/labring/FastGPT/assets/39018437/51117ac0-1673-44cf-9b0f-2221dac62fa9)

这是kimi的配置，其他配置和kimi基本相同。
使用讯飞星火，kimi和qwen都不能正常调用预设的时间工具。
我自己写的工具也不能调用，请问是哪里配置出问题了吗？

**Comment by c121914yu** [comment]
因为他们不支持函数调用

**Comment by c121914yu** [comment]
![Screenshot_20240413_001315_com.android.chrome.jpg](https://github.com/labring/FastGPT/assets/50446880/19d983b3-5d11-4908-bd4f-dd08d3ee0c5f)

moonshot 再提示词模式下就成功调用。

**Comment by nEvErMoReaken** [comment]
好的 谢谢

**Comment by JinCheng666** [comment]
> ![Screenshot_20240413_001315_com.android.chrome.jpg](https://private-user-images.githubusercontent.com/50446880/322050357-19d983b3-5d11-4908-bd4f-dd08d3ee0c5f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3Mzg5NTcsIm5iZiI6MTcxNTczODY1NywicGF0aCI6Ii81MDQ0Njg4MC8zMjIwNTAzNTctMTlkOTgzYjMtNWQxMS00OTA4LWJkNGYtZGQwOGQzZWUwYzVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAyMDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYTQxN2Y3MjJmMGYyOGI2MzI0ZjNmMTlmYjE3MmY5ZTNiZDQ0MGY5MjUyNDQ3ZGE4NGEzM2MzZThhMDg2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MtQ93xscDYrFuhIMi39VKzdIAo8RULYB9RxBA05PMj0)
> 
> moonshot 再提示词模式下就成功调用。

请问如何配置提示词模式调用工具？
