### ISSUE TITLE
更新到最新版后内容提取模块和问题分类模块无法选择模型，AI模块正常

### ISSUE THREAD

**Issue by echoopen** [labring/FastGPT#1132]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1-alpha

**问题描述**
更新到最新版后内容提取模块和问题分类模块无法选择模型，AI模块正常
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/62507651/ae087147-0d3c-47e8-85f8-a816e51e3b59)

**Comment by nongmo677** [comment]
配置文件里的llmModels对应的模型设置下面的属性了吗？
      "usedInClassify": true,
      "usedInExtractFields": true,

**Comment by bingxueyinlian** [comment]
请问一下，在哪设置呢。我也遇到同样的问题。 @nongmo677 

> 配置文件里的llmModels对应的模型设置下面的属性了吗？ "usedInClassify": true, "usedInExtractFields": true,

**Comment by bingxueyinlian** [comment]
知道了，“模型配置”页面上有个“配置文件”的按钮。或者直接点编辑，打开“用于问题分类”和“用于文本提取”的开关就可以了。
> 请问一下，在哪设置呢。我也遇到同样的问题。 [@nongmo677](https://github.com/nongmo677)
> 
> > 配置文件里的llmModels对应的模型设置下面的属性了吗？ "usedInClassify": true, "usedInExtractFields": true,
