### ISSUE TITLE
对话日志不记录API的对话

### ISSUE THREAD

**Issue by HelloEveryonehh** [labring/FastGPT#1137]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
我把fastgpt的应用生成了一个apikey放到nextweb上面了，然后可以正常对话，但是fastgpt的对话日志不显示，只显示在线使用的记录
**预期结果**
在对话日志中可以看的api的调用记录
**相关截图**
![image](https://github.com/labring/FastGPT/assets/110333012/a49f6649-0361-4ab1-b8b5-8ec383f17950)

**Comment by c121914yu** [comment]
看文档。
没传 chatid

**Comment by mwnu** [comment]
> chatid

API对话接口兼容GPT的接口，但是openai的api接口上没有 `chatId` 这个参数，相关客户端自然也不会传，也就是说在支持openai 接口的应用上虽然也能把fastgpt的应用当gpt 代理来用，但是不会在应用日志中显示记录？
