### ISSUE TITLE
core.chat.Chat API is error or undefined&&问题稍微变动存在上述报错

### ISSUE THREAD

**Issue by ejie2** [labring/FastGPT#1138]
**例行检查**

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
模型在nextweb正常使用，但是使用自己的代码调用会存在如下问题：
![%W7BQE ~B5CPO07IUL9OLGT](https://github.com/labring/FastGPT/assets/130576603/e17b6bd0-ef49-4133-9bf7-614b42e49383)
检查了调用模型获得的对话数据，第一个问题得到的回答第一条event为空消息，第二条报错如下：
![R8}0T(DN7PK`~SE26XK8D)8](https://github.com/labring/FastGPT/assets/130576603/d19d5046-df70-4763-9862-33f1a4864048)
而第二个问题得到了正确的回答，下面是调用模型的代码：
![图片](https://github.com/labring/FastGPT/assets/130576603/9da97b00-6eca-4433-96c5-551118a2ed0f)
![图片](https://github.com/labring/FastGPT/assets/130576603/9ac869b6-2a2a-4d0c-883f-60955b520d7d)

**Comment by c121914yu** [comment]
看文档 faq

**Comment by bulexu** [comment]
@ejie2 请问你的问题解决了吗
