### ISSUE TITLE
error: [errno 2] no such file or directory: 'config'

### ISSUE THREAD

**Issue by flyice8** [labring/FastGPT#1141]
error: [errno 2] no such file or directory: 'config'
最新版本

运行sudo npm run dev出现如下错误[
![屏幕截图 2024-04-07 165441](https://github.com/labring/FastGPT/assets/164740348/327cf34d-8a3f-4145-9cc9-522e38fccea5)
](url)

**Comment by flyice8** [comment]
web access get below error
![屏幕截图 2024-04-07 165736](https://github.com/labring/FastGPT/assets/164740348/4df96185-5570-4051-a1ae-1ffcbadf897c)

**Comment by c121914yu** [comment]
没有复制配置文件：config.local.json
没有 pnpm install
