### ISSUE TITLE
QueryExtension 拼接历史记录的逻辑不正确

### ISSUE THREAD

**Issue by zhanghx0905** [labring/FastGPT#1142]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1-alpha

**问题描述**

在 QueryExtension 中，拼接历史记录的逻辑不正确：

https://github.com/labring/FastGPT/blob/5cfa43287f16b441f24ae5435e374fdf92c52153/packages/service/core/ai/functions/queryExtension.ts#L120

item.value 是一个对象，最后模型得到的提示词中历史记录变成了`\nQ: [object Object]\nA: [object Object]\n`。
因为此问题，模型无法依据历史记录进行查询重写。

**Comment by c121914yu** [comment]
噢！麻烦可以提个PR？我发布个修复版本，这个应该4.7也有问题了

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/1012 参考这个PR
