### ISSUE TITLE
知识库导出报错 unAuthorization

### ISSUE THREAD

**Issue by jevonsnotes** [labring/FastGPT#1146]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.6
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
知识库导出报错，本地直接用的http访问。有发现类似问题说使用ssl正常，请问有相关部署指引吗？
`
[ERROR] 2024-04-08 08:49:30 export dataset error 
{ message: 'unAuthorization', stack: undefined }`
**复现步骤**
知识库→导出
![image](https://github.com/labring/FastGPT/assets/24319663/23ab860d-6214-43e6-807b-a79c0296e930)

**预期结果**
正常导出csv
**相关截图**

**Comment by jevonsnotes** [comment]
用nginx https反向代理 http能解决，只能通过这种方式吗，有没有办法从应用层面解决呢？
```
 server {

       listen       6443 ssl;
       server_name  fastgpt.test.com;
       ssl_certificate      certs/server.crt;
       ssl_certificate_key  certs/server.key;

       ssl_session_cache    shared:SSL:1m;
       #ssl_session_timeout  5m;

       location / {
           proxy_pass http://192.168.10.30:3000/;
       }
  }
```

**Comment by lijiajun1997** [comment]
我是用花生壳内网穿透映射到https域名解决的
