### ISSUE TITLE
无法跳转到大模型

### ISSUE THREAD

**Issue by jin-cheng-87** [labring/FastGPT#1147]
我的需求是：知识库里面有的按照知识库回答，知识库搜不到的，走大模型本身的能力，以前是可以，但最近无法做到；

比如问天气，它现在一直在知识库里转，无法跳转到大模型；
将知识库全删，就能跳到大模型，并出正确答案；请看图片；

![微信图片_20240408132851](https://github.com/labring/FastGPT/assets/143367519/186b76bd-722f-4ced-9a1d-9de585ecc4d2)

![微信图片_20240408133032](https://github.com/labring/FastGPT/assets/143367519/894ca511-0d0c-44d2-afd0-a06a10d253d8)

**Comment by lijiajun1997** [comment]
这种情况是因为知识库给你匹配到了知识 但是给到AI的时候，AI觉得这个知识不相关。
解决办法：
1、对问题进行分类，把你投喂的数据的领域走知识库，其他的走AI，
2、知识库对相关度的要求调高到0.85以上

**Comment by jin-cheng-87** [comment]
感谢你的回复，请问上面说的，应该在哪个位置调？

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/f36dddb7-b811-4623-8bb1-8ffe29c185e1)
![image](https://github.com/labring/FastGPT/assets/156336589/7989bfa1-7663-4589-a176-a89873e21400)

> 感谢你的回复，请问上面说的，应该在哪个位置调？
