### ISSUE TITLE
部署好后构建知识库后台报错The expanded size of the tensor (513) must match the existing size (512) at non-singleton dimension 1

### ISSUE THREAD

**Issue by ccly1996** [labring/FastGPT#1149]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.6.8

**问题描述**
构建知识库时中途索引会卡住，查看后台日志发现报错
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/39228103/24679861-753e-4cc7-b9c4-0b216c140831)

**Comment by c121914yu** [comment]
key报错

**Comment by ccly1996** [comment]
> key报错

是api的key吗，但是绕过oneapi的话也会报这个错误

**Comment by c121914yu** [comment]
> > key报错
> 
> 是api的key吗，但是绕过oneapi的话也会报这个错误

你key的模型就有问题，饶不饶没区别

**Comment by npllyq** [comment]
我这边也遇到了这个问题：我这边是用fastchat来部署embedding模型，最后将fastchat版本改成0.2.33后，问题解决了。

**Comment by MusicOfWind** [comment]
> **例行检查**
> 
> * * [ x] 我已确认目前没有类似 issue* [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)* [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的* [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈* [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本**
> 
> * * [ ]  公有云版本* [x ] 私有部署版本, 具体版本号: 4.6.8
> 
> **问题描述** 构建知识库时中途索引会卡住，查看后台日志发现报错 **复现步骤**
> 
> **预期结果**
> 
> **相关截图** ![image](https://github.com/labring/FastGPT/assets/39228103/24679861-753e-4cc7-b9c4-0b216c140831)

请问你这个问题是咋解决的

**Comment by MusicOfWind** [comment]
> 我这边也遇到了这个问题：我这边是用fastchat来部署embedding模型，最后将fastchat版本改成0.2.33后，问题解决了。

哥，能发一下部署过程不

**Comment by MusicOfWind** [comment]
> 我这边也遇到了这个问题：我这边是用fastchat来部署embedding模型，最后将fastchat版本改成0.2.33后，问题解决了。

哥，你们python包fschat部署的嘛

**Comment by MusicOfWind** [comment]
> 我这边也遇到了这个问题：我这边是用fastchat来部署embedding模型，最后将fastchat版本改成0.2.33后，问题解决了。

问一下你们的python版本是多少

**Comment by MusicOfWind** [comment]
> 我这边也遇到了这个问题：我这边是用fastchat来部署embedding模型，最后将fastchat版本改成0.2.33后，问题解决了。

有效，感谢老哥
