### ISSUE TITLE
聊天界面显示接口异常（未在docker-compose.yml中部署代理）

### ISSUE THREAD

**Issue by xxs980** [labring/FastGPT#115]
部署的fastgpt，在聊天界面输入文字发送后没有结果，卡一会儿报 接口异常，请问如何解决呢？是openai的API key的问题吗
![image](https://github.com/labring/FastGPT/assets/75365118/02c48be2-1f3d-4e74-a581-24902041c8a9)

**Comment by c121914yu** [comment]
不是。
看日志

**Comment by ShenYang222** [comment]
api response time: 0.363s
2023-07-28T14:14:42.950790551Z chat generate success. text len: 52. token len: 146. pay:true
2023-07-28T14:15:11.433249825Z api response time: 0.356s
2023-07-28T14:15:11.462388928Z chat generate success. text len: 54. token len: 159. pay:true

**Comment by ShenYang222** [comment]
这个啥意思

**Comment by c121914yu** [comment]
> api response time: 0.363s
> 2023-07-28T14:14:42.950790551Z chat generate success. text len: 52. token len: 146. pay:true
> 2023-07-28T14:15:11.433249825Z api response time: 0.356s
> 2023-07-28T14:15:11.462388928Z chat generate success. text len: 54. token len: 159. pay:true
> 

响应结束
