### ISSUE TITLE
请求接口报凭证错误

### ISSUE THREAD

**Issue by m5314** [labring/FastGPT#1150]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.7

**问题描述**
通过看网页请求得到获取问题建议是调用这个接口/api/v1/core/ai/agent/createQuestionGuide，但无论使用应用key还是root_key都报凭证错误，我想问问获取问题建议是调用哪个接口？

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
该接口没有openapi，需要用token

**Comment by 1234faker** [comment]
> 该接口没有openapi，需要用token

细说兄弟
