### ISSUE TITLE
高级编排，Http模块无法请求成功，请求报protocol mismatch错误

### ISSUE THREAD

**Issue by denghaichao** [labring/FastGPT#1151]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述**
创建了一个AI知识库回答助手，使用高级编排。
通过知识库搜索知识，搜索有结果喂给大模型进行输出；搜索没有结果，调用自定义的HTTP请求输出内容。
发现HTTP请求一直无法调用成功，一直报protocol mistach错误。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/40666618/fa7fe714-a418-4c4f-b47f-3139630df6cc)
![image](https://github.com/labring/FastGPT/assets/40666618/1c492a2b-83ec-413f-b64b-d045db5ac540)

**Comment by c121914yu** [comment]
看着是你接口的协议不支持
