### ISSUE TITLE
如何传入通义千问的一个参数

### ISSUE THREAD

**Issue by luyouli** [labring/FastGPT#1152]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述**
我接入通义千问的qwen-max，提问华为mate60，返回的信息是华为mate60尚未发布。
经过与客户沟通，把通义千问的一个参数传进去就行，这个参数是个布尔类型，enable_search（是否参考搜索的结果，默认false），我想把True传进去

**复现步骤**
我把 "enable_search": "True", 写进config.json里面，执行 docker-compose down && docker-compose up -d 重启无效

**预期结果**
将enable_search=True传进去，这样就可以答复我最新的信息，比如华为mate60

**相关截图**

**Comment by c121914yu** [comment]
https://doc.fastai.site/docs/development/configuration/ 配置文件配置模型时，允许传入自定义参数

**Comment by luyouli** [comment]
牛批

**Comment by luyouli** [comment]
"datasetProcess": true, // 是否设置为知识库处理模型（QA），务必保证至少有一个为true，否则知识库会报错
      "usedInClassify": true, // 是否用于问题分类（务必保证至少有一个为true）
      "usedInExtractFields": true, // 是否用于内容提取（务必保证至少有一个为true）
      "usedInToolCall": true, // 是否用于工具调用（务必保证至少有一个为true）
      "usedInQueryExtension": true, // 是否用于问题优化（务必保证至少有一个为true）
      "toolChoice": true, // 是否支持工具选择（分类，内容提取，工具调用会用到。目前只有gpt支持）
      "functionCall": false, // 是否支持函数调用（分类，内容提取，工具调用会用到。会优先使用 toolChoice，如果为false，则使用 functionCall，如果仍为 false，则使用提示词模式）
      "customCQPrompt": "", // 自定义文本分类提示词（不支持工具和函数调用的模型
      "customExtractPrompt": "", // 自定义内容提取提示词
      "defaultSystemChatPrompt": "", // 对话默认携带的系统提示词
      "defaultConfig":{}  // 请求API时，挟带一些默认配置（比如 GLM4 的 top_p）

这里面，那个是允许传入自定义参数？

**Comment by xkkjiayou** [comment]
我在这里配置了，好像并不生效
![828ba0f573608d9224e9fbe5d04ecb2](https://github.com/labring/FastGPT/assets/38376865/1b0a0b71-60d3-4d45-a7b5-fd44be5d0d7e)

**Comment by luyouli** [comment]
我也是这样配置的，并不生效，我还改了好几次，甚至重启了宿主机，均不生效

**Comment by xkkjiayou** [comment]
咋办兄弟，我很想要这个

**Comment by luyouli** [comment]
巧了，我也是，而且我还不知道到底哪个是：允许传入自定义参数

**Comment by luyouli** [comment]
我又开了一个 https://github.com/labring/FastGPT/issues/1164  来这里回复吧
