### ISSUE TITLE
重排 rereank，我测试了4.6.9 到4.7.1-alpha个版本的fastgpt ，重排始终不成功。

### ISSUE THREAD

**Issue by sunlin-xiaonai** [labring/FastGPT#1155]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 私有部署版本, 具体版本号: 
- [ ] **问题描述**
私有部署，的rerank 模型，从容器中拷贝出来的所有代码和模型，在本地启动的服务，测试了4.6.9， 4.7， 4.7.1-alpha 版本的fastgpt 全部调用重排模型成功，但是在前端界面显示是失败。

**复现步骤**

**预期结果**

**相关截图**

<img width="327" alt="image" src="https://github.com/labring/FastGPT/assets/129371884/8a4cd2ef-bdb2-4bee-9b77-e17e83b70d95">

<img width="339" alt="image" src="https://github.com/labring/FastGPT/assets/129371884/5db853cb-5ab1-4d29-83ab-9bdfdb9a93a9">
<img width="316" alt="image" src="https://github.com/labring/FastGPT/assets/129371884/12475ef0-d5ed-4fda-8b37-a51beccd70b9">
<img width="610" alt="image" src="https://github.com/labring/FastGPT/assets/129371884/6467c70b-371e-493a-93fc-0da5524601f3">

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/1111 问题重复，自行修改评论镜像。或文档最新镜像。

**Comment by sunlin-xiaonai** [comment]
文档最新镜像是多少呀

> #1111 问题重复，自行修改评论镜像。或文档最新镜像。

我尝试了更新到了最新版本的镜像问题依然存在

**Comment by yibohub** [comment]
前端界面显示false的问题好像没有解决。rerank的日志好像显示成功了，但是fastgpt日志报错。fastgpt是4.7.1-fix版本，reranker模型：image: registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1
![image](https://github.com/labring/FastGPT/assets/161293070/e8fcdc88-665b-4e1e-85cb-0105f517a702)
![image](https://github.com/labring/FastGPT/assets/161293070/c501c2c9-a033-4dd2-b29c-26cd9551b189)
![image](https://github.com/labring/FastGPT/assets/161293070/6a3e3dc1-ee24-4296-b87a-963a2034b0f5)
![image](https://github.com/labring/FastGPT/assets/161293070/f3e3f821-3eb1-49a6-80a6-a4bf924746f0)
![image](https://github.com/labring/FastGPT/assets/161293070/bc497d76-31bd-4bb4-a64c-362da879ed25)

**Comment by password36** [comment]
> 前端界面显示false的问题好像没有解决。rerank的日志好像显示成功了，但是fastgpt日志报错。fastgpt是4.7.1-fix版本，reranker模型：image: registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1 ![image](https://private-user-images.githubusercontent.com/161293070/321076520-e8fcdc88-665b-4e1e-85cb-0105f517a702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2NTIwLWU4ZmNkYzg4LTY2NWItNGUxZS04NWNiLTAxMDVmNTE3YTcwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGY0NzIyMzk1MWI2NTRiYzRiNmJjNTY3NjU0YWZiOGI3MzY4NGRlZjI3NWM0MTU2OTU5MDdkNDFiYTdjYTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.moogtBgvGQdAUX7iuEtZL-uZIRlZZFvXEyKszoYYpsk) ![image](https://private-user-images.githubusercontent.com/161293070/321076551-c501c2c9-a033-4dd2-b29c-26cd9551b189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2NTUxLWM1MDFjMmM5LWEwMzMtNGRkMi1iMjljLTI2Y2Q5NTUxYjE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWMwMThiNWJmNGY2NmU2YjJjNzE0NjBhYjI5MTY3MmQxYWE4MTZlNGEwNzUwNjI1Nzc5OTlmMjQ5MTVlNTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SQKtrZ-sfRZTSOKbdbn7xr6vPtDcISdGkjdhrZ_XINY) ![image](https://private-user-images.githubusercontent.com/161293070/321076623-6a3e3dc1-ee24-4296-b87a-963a2034b0f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2NjIzLTZhM2UzZGMxLWVlMjQtNDI5Ni1iODdhLTk2M2EyMDM0YjBmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWIzYzAxMzczODZiNmUyZjAyY2NlNGNmMmQ4Y2Y0OTNjYzcyZjZiMGExZTE0NjBiYmQ4NTJjZDZiNDUwNjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X1UMoSsUtV4Mh56NvozVw7ZB2Hs9K-YEw3FtrzaY0HY) ![image](https://private-user-images.githubusercontent.com/161293070/321076695-f3e3f821-3eb1-49a6-80a6-a4bf924746f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2Njk1LWYzZTNmODIxLTNlYjEtNDlhNi04MGE2LWE0YmY5MjQ3NDZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTNiZWI2YjNmNjdkN2M0MGQ2ODc1MGM1ZThkNTdkMGI5ZjUxYzFjOTc1ZjE1MmY1NjNmNjVhNTk5OTBmNDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.roV-k2besWt1l2XOzJKnSQwU5cboFLyrdcYEDGOo7fc) ![image](https://private-user-images.githubusercontent.com/161293070/321076788-bc497d76-31bd-4bb4-a64c-362da879ed25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2Nzg4LWJjNDk3ZDc2LTMxYmQtNGJiNC1hNjRjLTM2MmRhODc5ZWQyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTE4ZTFlMTRkNTE3NjM1YWVkMjc4MWUzNmJhYTUzOTdkNmMxNzYxYmE5MWQ1NTcyYTNiYTY4MWFkN2VkMjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D9Qe52gjmlL6bYnK6bGr8xHjR0t90MCakpUpKeiXsi8)

同样遇到这个问题，这个只是前端显示问题么？现在无论在测试还是对话里rerank虽然调用但都是显示false，我的版本4.7.1的镜像

**Comment by sunlin-xiaonai** [comment]
> > 前端界面显示false的问题好像没有解决。rerank的日志好像显示成功了，但是fastgpt日志报错。fastgpt是4.7.1-fix版本，reranker模型：image: registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1 ![image](https://private-user-images.githubusercontent.com/161293070/321076520-e8fcdc88-665b-4e1e-85cb-0105f517a702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2NTIwLWU4ZmNkYzg4LTY2NWItNGUxZS04NWNiLTAxMDVmNTE3YTcwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGY0NzIyMzk1MWI2NTRiYzRiNmJjNTY3NjU0YWZiOGI3MzY4NGRlZjI3NWM0MTU2OTU5MDdkNDFiYTdjYTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.moogtBgvGQdAUX7iuEtZL-uZIRlZZFvXEyKszoYYpsk) ![image](https://private-user-images.githubusercontent.com/161293070/321076551-c501c2c9-a033-4dd2-b29c-26cd9551b189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2NTUxLWM1MDFjMmM5LWEwMzMtNGRkMi1iMjljLTI2Y2Q5NTUxYjE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWMwMThiNWJmNGY2NmU2YjJjNzE0NjBhYjI5MTY3MmQxYWE4MTZlNGEwNzUwNjI1Nzc5OTlmMjQ5MTVlNTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SQKtrZ-sfRZTSOKbdbn7xr6vPtDcISdGkjdhrZ_XINY) ![image](https://private-user-images.githubusercontent.com/161293070/321076623-6a3e3dc1-ee24-4296-b87a-963a2034b0f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2NjIzLTZhM2UzZGMxLWVlMjQtNDI5Ni1iODdhLTk2M2EyMDM0YjBmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWIzYzAxMzczODZiNmUyZjAyY2NlNGNmMmQ4Y2Y0OTNjYzcyZjZiMGExZTE0NjBiYmQ4NTJjZDZiNDUwNjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X1UMoSsUtV4Mh56NvozVw7ZB2Hs9K-YEw3FtrzaY0HY) ![image](https://private-user-images.githubusercontent.com/161293070/321076695-f3e3f821-3eb1-49a6-80a6-a4bf924746f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2Njk1LWYzZTNmODIxLTNlYjEtNDlhNi04MGE2LWE0YmY5MjQ3NDZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTNiZWI2YjNmNjdkN2M0MGQ2ODc1MGM1ZThkNTdkMGI5ZjUxYzFjOTc1ZjE1MmY1NjNmNjVhNTk5OTBmNDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.roV-k2besWt1l2XOzJKnSQwU5cboFLyrdcYEDGOo7fc) ![image](https://private-user-images.githubusercontent.com/161293070/321076788-bc497d76-31bd-4bb4-a64c-362da879ed25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTg3MTUsIm5iZiI6MTcxMzQxODQxNSwicGF0aCI6Ii8xNjEyOTMwNzAvMzIxMDc2Nzg4LWJjNDk3ZDc2LTMxYmQtNGJiNC1hNjRjLTM2MmRhODc5ZWQyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNTMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTE4ZTFlMTRkNTE3NjM1YWVkMjc4MWUzNmJhYTUzOTdkNmMxNzYxYmE5MWQ1NTcyYTNiYTY4MWFkN2VkMjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D9Qe52gjmlL6bYnK6bGr8xHjR0t90MCakpUpKeiXsi8)
> 
> 同样遇到这个问题，这个只是前端显示问题么？现在无论在测试还是对话里rerank虽然调用但都是显示false，我的版本4.7.1的镜像

可以看我的视频我解决了这个问题：https://www.bilibili.com/video/BV1Lp42197yg/?spm_id_from=333.1007.top_right_bar_window_dynamic.content.click

**Comment by MusicOfWind** [comment]
> 文档最新镜像是多少呀
> 
> > #1111 问题重复，自行修改评论镜像。或文档最新镜像。
> 
> 我尝试了更新到了最新版本的镜像问题依然存在

老哥，fastgpt v 4.6.x 版本有成功的 rerank 版本吗

**Comment by MusicOfWind** [comment]
> 文档最新镜像是多少呀
> 
> > #1111 问题重复，自行修改评论镜像。或文档最新镜像。
> 
> 我尝试了更新到了最新版本的镜像问题依然存在

你这个当时用的是什么 rerank 版本
