### ISSUE TITLE
语音输入模块只在简单模式有设置按钮 高级编排无按钮

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#1157]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.7.1 alpha2

**问题描述**
![image](https://github.com/labring/FastGPT/assets/156336589/c0d0fa1e-574b-411f-a09d-57f7e1e1c21c)
![image](https://github.com/labring/FastGPT/assets/156336589/e72fba57-fbae-4faf-a1fd-3c054c356912)

**复现步骤**
1.应用设置
2.简单编排有设置语音输入的按钮
3.高级编排无输入设置按钮
4.简单编排修改设置会覆盖高级编排

**预期结果**
高级编排有打开语音输入按钮
**相关截图**

**Comment by lijiajun1997** [comment]
另外发布的免登录链接使用语音输入提示无权操作
![image](https://github.com/labring/FastGPT/assets/156336589/a54c0aa2-8de9-4fe7-a988-5331f1ad7e87)

**Comment by c121914yu** [comment]
ok 待会看看

**Comment by lijiajun1997** [comment]
> ok 待会看看

升级alpha 3 高级编排有按钮了 但是点不开

**Comment by lijiajun1997** [comment]
貌似旧的应用不行 无法打开按钮
