### ISSUE TITLE
config一旦给了defaultSystemChatPrompt，如果是有prompt的应用，就会报错

### ISSUE THREAD

**Issue by xkkjiayou** [labring/FastGPT#1158]
{
  message: 'core.chat.Chat API is error or undefined',
  stack: undefined
}

如果是没有prompt的应用（prompt为空），就不会报错

**Comment by c121914yu** [comment]
按文档教程 debug

**Comment by dreamsnail** [comment]
解决了吗，看文档说是key的问题，curl测试没问题呀

**Comment by xkkjiayou** [comment]
> 解决了吗，看文档说是key的问题，curl测试没问题呀

我是模型配置问题，重新配一下模型就好了

**Comment by dreamsnail** [comment]
> > 解决了吗，看文档说是key的问题，curl测试没问题呀
> 
> 我是模型配置问题，重新配一下模型就好了

请问你是怎么配置的，是json文件里面的配置，还是本地模型项目配置
