### ISSUE TITLE
HTTP功能如何提取想要的json部分

### ISSUE THREAD

**Issue by skstudying** [labring/FastGPT#1159]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
HTTP功能中如何提取想要的json部分？
使用HTTP调用bing-search api进行新闻查询。现在需要 webPages.value
value是一个数组，难道必须 webPages.value[0], webPages.value[1]这样一个个调用吗，请问有什么方法可以一次性把此数组的内容传出？
更深入的，如果我只想要value数组中每个元素的snippet和url，又该如何设置字段key呢？

如果用此方法不行，FastGPT的高级编排中，有没有其他方法可以替代达到这个效果？

**复现步骤**

**预期结果**

**相关截图**
![微信截图_20240409121604](https://github.com/labring/FastGPT/assets/62501789/4ec06485-72ef-4e17-8081-1d06f8168309)

**Comment by nongmo677** [comment]
1. 理论上，目前确实只能一条一条取出来，如果只是存粹的传数组也是ok的，直接用字符串类型传也可以
2. 对于http组件输出你可以webPages.value[0].snippet和webPages.value[0].url，只要格式是正确的，输出的key就可以这么写，http下游组件的key不受影响

**Comment by skstudying** [comment]
> 1. 理论上，目前确实只能一条一条取出来，如果只是存粹的传数组也是ok的，直接用字符串类型传也可以
> 2. 对于http组件输出你可以webPages.value[0].snippet和webPages.value[0].url，只要格式是正确的，输出的key就可以这么写，http下游组件的key不受影响

感谢回复。目前用这种方式粗略完成了，希望能有更丰富的插件，比如支持python代码json数据做清洗。不然把json原数据丢给LLM烧tokens不说，速度还很慢。

**Comment by nongmo677** [comment]
> > 1. 理论上，目前确实只能一条一条取出来，如果只是存粹的传数组也是ok的，直接用字符串类型传也可以
> > 2. 对于http组件输出你可以webPages.value[0].snippet和webPages.value[0].url，只要格式是正确的，输出的key就可以这么写，http下游组件的key不受影响
> 
> 感谢回复。目前用这种方式粗略完成了，希望能有更丰富的插件，比如支持python代码json数据做清洗。不然把json原数据丢给LLM烧tokens不说，速度还很慢。

等官方接入laf，似乎就可以自己写js函数了，用python的话你自己起一个python web服务处理一下，相当于中转接口，然后http组件接入也算吧
官方接入python的话还得另起一个环境或者用个沙箱给你做插件运行处理，成本感觉也很高
烧token这件事目前没法避免了

**Comment by c121914yu** [comment]
4.7.1 接了 laf，自己写代码处理即可。
