### ISSUE TITLE
Incorrect API key provided: 123. You can find your API key at https://xxx (request id: 2024040906333984869695562985922)

### ISSUE THREAD

**Issue by qq378488249** [labring/FastGPT#1162]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 私有部署版本, 具体版本号: 4.7

**问题描述**
我新建了知识库，选择了智普的语言模型，但是无法新增数据集（图1，图2）。已确认智普可正常对话（图3），请问是我哪里配置不对吗？

**复现步骤**

**预期结果**

**相关截图**
![微信截图_20240409143334](https://github.com/labring/FastGPT/assets/13046994/0c641dae-964c-425d-b3cc-cd1c4fe07050)
![微信截图_20240409143324](https://github.com/labring/FastGPT/assets/13046994/deb9e975-73a2-43a4-aef3-447e51374e8d)
![微信截图_20240409143652](https://github.com/labring/FastGPT/assets/13046994/71ed20be-9896-4cb2-a86d-c687028af28f)

**Comment by nongmo677** [comment]
知识库最主要的是向量模型（Embedding模型）
请正确配置向量模型，在config文件里的`vectorModels`
    "model": "text-embedding-ada-002",
    "name": "Embedding-2",
智谱应该是没有这个模型的

**Comment by qq378488249** [comment]
咱们目前支持哪些向量模型呢？

**Comment by c121914yu** [comment]
看着就是 key 不对。向量模型配置的是 openai 的，需要有 openai 的号，
