### ISSUE TITLE
语义检索得分超过1

### ISSUE THREAD

**Issue by igangang** [labring/FastGPT#1163]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.7

**问题描述**
使用ollama的Embedding模型nomic-embed-text:v1.5进行语义检索时，得分超过了1，导致无法按0-1的分数进行过滤
**复现步骤**

**预期结果**

**相关截图**
<img width="370" alt="image" src="https://github.com/labring/FastGPT/assets/18605969/6481cfd6-93dd-4a49-8d27-b96d89e2c9da">

**Comment by 13829386012** [comment]
> **例行检查**
> 
> * [ ]  我已确认目前没有类似 issue
> * [ ]  我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
> * [ ]  我使用了自己的 key，并确认我的 key 是可正常使用的
> * [ ]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本**
> 
> * [ ]  公有云版本
> * [x]  私有部署版本, 具体版本号: v4.7
> 
> **问题描述** 使用ollama的Embedding模型nomic-embed-text:v1.5进行语义检索时，得分超过了1，导致无法按0-1的分数进行过滤 **复现步骤**
> 
> **预期结果**
> 
> **相关截图** <img alt="image" width="370" src="https://private-user-images.githubusercontent.com/18605969/320749005-6481cfd6-93dd-4a49-8d27-b96d89e2c9da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzI0NTgsIm5iZiI6MTcxNjk3MjE1OCwicGF0aCI6Ii8xODYwNTk2OS8zMjA3NDkwMDUtNjQ4MWNmZDYtOTNkZC00YTQ5LThkMjctYjk2ZDg5ZTJjOWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA4NDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlOTg4OTI4OTY1MjliYTNhZTQ0OTQ5ZWNlNTA0ZTg0NWIwMTVlNTU0MmI4MzlkYzQ5Y2ZiODMyYTYxNmE1OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LWTvzOjlRQEvBjiKY9TxNYCI_PQvhYIvYOj5T7poaCA">

问题解决了吗,遇到同样的问题
