### ISSUE TITLE
配置文件配置模型时，允许传入自定义参数指的是那个？

### ISSUE THREAD

**Issue by luyouli** [labring/FastGPT#1164]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述**
昨天提问：https://github.com/labring/FastGPT/issues/1152
答复我配置上“允许传入自定义参数”即可
我修改了很多次的配置，都不行
"defaultConfig": {"enable_search": "True"}
"defaultConfig": {"enable_search": "true"}
"defaultConfig": {"enable_search": True}
"defaultConfig": {"enable_search": true}

另外，这些那个配置项是：“允许传入自定义参数”
 "vision": false, // 是否支持图片输入
      "datasetProcess": true, // 是否设置为知识库处理模型（QA），务必保证至少有一个为true，否则知识库会报错
      "usedInClassify": true, // 是否用于问题分类（务必保证至少有一个为true）
      "usedInExtractFields": true, // 是否用于内容提取（务必保证至少有一个为true）
      "usedInToolCall": true, // 是否用于工具调用（务必保证至少有一个为true）
      "usedInQueryExtension": true, // 是否用于问题优化（务必保证至少有一个为true）
      "toolChoice": true, // 是否支持工具选择（分类，内容提取，工具调用会用到。目前只有gpt支持）
      "functionCall": false, // 是否支持函数调用（分类，内容提取，工具调用会用到。会优先使用 toolChoice，如果为false，则使用 functionCall，如果仍为 false，则使用提示词模式）
      "customCQPrompt": "", // 自定义文本分类提示词（不支持工具和函数调用的模型
      "customExtractPrompt": "", // 自定义内容提取提示词
      "defaultSystemChatPrompt": "", // 对话默认携带的系统提示词
      "defaultConfig":{}  // 请求API时，挟带一些默认配置（比如 GLM4 的 top_p）

**复现步骤**

**预期结果**

**相关截图**

**Comment by luyouli** [comment]
![4706](https://github.com/labring/FastGPT/assets/28440272/a892da31-7b45-46ad-9944-491147fc3abe)
我已经这样配置了，还是不行

**Comment by c121914yu** [comment]
oneapi 支持？

**Comment by luyouli** [comment]
> oneapi 有支持这个参数了么

这个是需要oneapi支持之后，才能使用吗

**Comment by luyouli** [comment]
通义千问是支持这个参数的
oneapi里只有插件参数可以配置，是要在“插件参数”里面把enable_search=true配置上吗？
![5697](https://github.com/labring/FastGPT/assets/28440272/8d5e70c3-8a5a-45b8-9fde-a3befff60aba)
![3823](https://github.com/labring/FastGPT/assets/28440272/a16ff5e8-7b6f-4288-a032-67fee8b6672d)

**Comment by c121914yu** [comment]
> > oneapi 有支持这个参数了么
> 
> 这个是需要oneapi支持之后，才能使用吗

可以通过直接 curl 请求 oneapi 进行测试。不确定它是否忽略该参数。

**Comment by c121914yu** [comment]
> 不仅重启了docker，还把宿主机重启了
> 
> 请问如何curl请求测试？有具体的参考吗？

emmm，curl 是基本操作，，百度下吧。

**Comment by luyouli** [comment]
> > 不仅重启了docker，还把宿主机重启了
> > 
> > 请问如何curl请求测试？有具体的参考吗？
> 
> emmm，curl 是基本操作，，百度下吧。

我问的不是如何curl，而是curl oneapi地址后面的URL

**Comment by c121914yu** [comment]
> > > 不仅重启了docker，还把宿主机重启了
> > > 请问如何curl请求测试？有具体的参考吗？
> > 
> > 
> > emmm，curl 是基本操作，，百度下吧。
> 
> 我问的不是如何curl，而是curl oneapi地址后面的URL

不就是和 openai 的一样的接口么？直接看 openai 文档就行了。

**Comment by luyouli** [comment]
> > > > 不仅重启了docker，还把宿主机重启了
> > > > 请问如何curl请求测试？有具体的参考吗？
> > > 
> > > 
> > > emmm，curl 是基本操作，，百度下吧。
> > 
> > 我问的不是如何curl，而是curl oneapi地址后面的URL
> 
> 不就是和 openai 的一样的接口么？直接看 openai 文档就行了。

明天上午研究下

**Comment by luyouli** [comment]
获取的models信息，如下
{"id":"qwen-max","object":"model","created":1626777600,"owned_by":"ali","permission":[{"id":"modelperm-LwHkVFn8AcMItP432fKKDIKJ","object":"model_permission","created":1626777600,"allow_create_engine":true,"allow_sampling":true,"allow_logprobs":true,"allow_search_indices":false,"allow_view":true,"allow_fine_tuning":false,"organization":"*","group":null,"is_blocking":false}],"root":"qwen-max","parent":null}

**Comment by c121914yu** [comment]
> 加了enable_search=true参数后，获取的信息，如下 {"id":"qwen-max","object":"model","created":1626777600,"owned_by":"ali","permission":[{"id":"modelperm-LwHkVFn8AcMItP432fKKDIKJ","object":"model_permission","created":1626777600,"allow_create_engine":true,"allow_sampling":true,"allow_logprobs":true,"allow_search_indices":false,"allow_view":true,"allow_fine_tuning":false,"organization":"*","group":null,"is_blocking":false}],"root":"qwen-max","parent":null}

这是可以还是不可以呢

**Comment by luyouli** [comment]
> 我也遇到了同样的问题，请问你解决了吗？

没有

**Comment by Yshayu** [comment]
> > 我也遇到了同样的问题，请问您解决了吗？
> 
> 没有

我也是没有解决，各种方法都尝试过了，在问题群问了也没有得到回复

**Comment by luyouli** [comment]
> > > 我也遇到了同样的问题，请问您解决了吗？
> > 
> > 
> > 没有
> 
> 我也是没有解决，各种方法都尝试过了，在问题群问了也没有得到回复

所以···我暂时弃用了

**Comment by Yshayu** [comment]
> > > > 我也遇到了同样的问题，请问您解决了吗？
> > > 
> > > 
> > > 没有
> > 
> > 
> > 我也是没有解决，各种方法都尝试过了，在问题群问了也没有得到回复
> 
> 所以···我暂时弃用了

那你现在是用的什么解决方案？

**Comment by luyouli** [comment]
> > > > > 我也遇到了同样的问题，请问您解决了吗？
> > > > 
> > > > 
> > > > 没有
> > > 
> > > 
> > > 我也是没有解决，各种方法都尝试过了，在问题群问了也没有得到回复
> > 
> > 
> > 所以···我暂时弃用了
> 
> 那你现在是用的什么解决方案？

没解决···

**Comment by SDAIer** [comment]
到oneapi那边问问是否支持这个参数
