### ISSUE TITLE
知识库上次csv文件报错

### ISSUE THREAD

**Issue by fairychao** [labring/FastGPT#1166]
**问题描述**

知识库上次csv文件报错（下载模板直接导入可以成功，打开文件后直接保存再导入失败）

![image](https://github.com/labring/FastGPT/assets/20513651/c300d606-6d43-40db-a8ba-737a552b2a7e)

**Comment by nongmo677** [comment]
Unknown encoding: GB2312 
尝试修改编码重新上传

**Comment by fairychao** [comment]
修改为UTF-8解决。谢谢。
