### ISSUE TITLE
请问如何用sk-key环境变量配置m3e-large-api的密钥呢？

### ISSUE THREAD

**Issue by ocpinfo** [labring/FastGPT#1168]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [] 公有云版本
- [x] 私有部署版本, 具体版本号: Fastgpt v4.6.8

**问题描述**
配置后显示的环境变量如下：
ubuntu@VM-4-5-ubuntu:~$ sudo docker exec m3e env
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=cf5ba0f9bcb4
SK-KEY=sk-123456
LANG=C.UTF-8
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
PYTHON_VERSION=3.10.12
PYTHON_PIP_VERSION=23.0.1
PYTHON_SETUPTOOLS_VERSION=65.5.1
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py
PYTHON_GET_PIP_SHA256=96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207
NAME=World
HOME=/root
**复现步骤**
sudo docker run -d -p 6008:6008 -e SK-KEY=sk-123456 --name=m3e stawky/m3e-large-api:latest
**预期结果**
在oneapi中配置好之后用这个自己定义的密钥总是连接不上m3e。如果直接用sk-aaabbbcccdddeeefffggghhhiiijjjkkk这个是可以的。
**相关截图**

**Comment by ocpinfo** [comment]
好的，谢谢。我再试试

**Comment by qingfeng95** [comment]
请问楼主我正想解决这个问题，自己本地部署这个 m3e-large-api 或者 别的向量模型后，怎么配置，可以和别的大模型一起提供给fastgpt呀，fastgpt使用的大模型和向量模型允许分开吗

**Comment by ocpinfo** [comment]
> 请问楼主我正想解决这个问题，自己本地部署这个 m3e-large-api 或者 别的向量模型后，怎么配置，可以和别的大模型一起提供给fastgpt呀，fastgpt使用的大模型和向量模型允许分开吗

当然可以分开
