### ISSUE TITLE
语音播报功能失效

### ISSUE THREAD

**Issue by Tooroplo** [labring/FastGPT#1170]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
我使用OpenRouter的key，可以正常文本内容输出。但是，出现无法播报语音（除了浏览器自带可以播报以外）。请将如何处理?
并且出现以下代码：
404 <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" href="/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2" as="font" crossorigin="" type="font/woff2"/><link rel="stylesheet" href="/_next/static/css/d051a93bfc40db14.css" data-precedence="next"/><link rel="preload" as="script" fetchPriority="low" href="/_next/static/chunks/webpack-8c4cd80487809124.js"/><script src="/_next/static/chunks/c2a6b034-c8b5116ba8756f36.js" async=""></script><script src="/_next/static/chunks/8e63e258-e3dd4db029f30086.js" async=""></script><script src="/_next/static/chunks/4908-11183f6bc6c83df3.js" async=""></script><script src="/_next/static/chunks/main-app-396281177860873a.js" async=""></script><script src="/_next/static/chunks/app/global-error-721e5e1dde63237b.js" async=""></script><script src="/_next/static/chunks/3637-a97af8420bc1c451.js" async=""></script><script src="/_next/static/chunks/6611-dec0e3c5ef2b6e25.js" async=""></script><script src="/_next/static/chunks/5750-e90c24942153546f.js" async=""></script><script src="/_next/static/chunks/8580-71c1cc442f663872.js" async=""></script><script src="/_next/static/chunks/6872-752d16c999cd82e3.js" async=""></script><script src="/_next/static/chunks/950-73aafcafc78fcb68.js" async=""></script><script src="/_next/static/chunks/9414-9ccee108a0aa98e4.js" async=""></script><script src="/_next/static/chunks/4651-6cc0ff2c67798319.js" async=""></script><script src="/_next/static/chunks/8070-40f5386c3e0744ec.js" async=""></script><script src="/_next/static/chunks/5051-b7447dad266111c5.js" async=""></script><script src="/_next/static/chunks/8818-f2520482d7ef2eef.js" async=""></script><script src="/_next/static/chunks/1161-d08103102f3193b1.js" async=""></script><script src="/_next/static/chunks/3247-ce7ffd03a7127ba8.js" async=""></script><script src="/_next/static/chunks/5320-5d60fb1b03c8123c.js" async=""></script><script src="/_next/static/chunks/app/layout-e5ae2dcbb706f3ec.js" async=""></script><script src="/_next/static/chunks/app/(internal)/layout-aa1543b3a6f99194.js" async=""></script><link rel="preload" href="https://xxx as="script"/><meta name="robots" content="noindex"/><title>OpenRouter</title><meta name="description" content="A router for LLMs and other AI models"/><meta name="robots" content="follow, index"/><meta property="og:title" content="OpenRouter"/><meta
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
404 代表没这个 api
