### ISSUE TITLE
使用docker部署bge-rerank-v2-m3镜像，启动出错

### ISSUE THREAD

**Issue by zidanereal5** [labring/FastGPT#1175]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.6.9

**问题描述**
使用docker部署bge-rerank-v2-m3镜像，启动出错
**复现步骤**
运行命令：
docker run -d --name reranker -p 6006:6006 -e ACCESS_TOKEN=mytoken --gpus all registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-v2-m3:v0.1
错误信息：
Error response from daemon: could not select device driver "" with capabilities: [[gpu]]
**预期结果**
本地有GPU，本地CUDA 版本12.2， 是否可能的原因是，镜像bge-rerank-v2-m3:v0.1需要CUDA版本 11.7。
请问问题原因，我该如何调整，谢谢？
**相关截图**
![image](https://github.com/labring/FastGPT/assets/123045775/f49b961d-c06c-4b1d-a1ee-ab42445e6363)

**Comment by c121914yu** [comment]
看着是你运行命令就错了

**Comment by c121914yu** [comment]
gpt 随便就能回答出来了
