### ISSUE TITLE
调用chatglm3本地模型，回复较短时报错“对话接口报错或返回为空”

### ISSUE THREAD

**Issue by 23357** [labring/FastGPT#1178]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.6.8

**问题描述**
使用本地部署的chatglm3模型对话时，引导回复两三个字的时候，结果会报错，普通正问题可以正常回复，使用api直接调用oneapi得到的回复也是正常的
**复现步骤**
先问一个正常问题，再问一个可能回复较短的问题
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/33109715/5443b085-f9bb-4f40-9f2a-b634703e488f)

api调用:
![image](https://github.com/labring/FastGPT/assets/33109715/70b49001-9517-48a1-9f4f-c4a84c6ee06a)

**Comment by c121914yu** [comment]
用 stream 模式测试

**Comment by 23357** [comment]
> 用 stream 模式测试，并且保证相同上下文。
![image](https://github.com/labring/FastGPT/assets/33109715/a89f4462-700d-4f35-b33d-2858ef9bddd4)

奇怪了，strem模式确实没输出，那是模型部署有问题？长对话可以，短对话不行......之前都是用非流式看结果没发现
