### ISSUE TITLE
使用高级编排中的文本加工功能，编辑和保存后内容不一样

### ISSUE THREAD

**Issue by WestCraneLi** [labring/FastGPT#1179]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: lateset 

**问题描述**
使用高级编排中的文本加工功能，编辑和保存后内容不一样，在编辑中测试可以引用知识库内容，但是保存后就不行了

**复现步骤**

编辑添加文本加工功能
![image](https://github.com/labring/FastGPT/assets/76116480/8aa801a1-dadf-4ebb-81e9-be74cebf7300)

保存后
![image](https://github.com/labring/FastGPT/assets/76116480/e83aace9-6756-4530-880e-092972a7aedf)

**预期结果**
保存后和编辑是一致

**Comment by c121914yu** [comment]
你用简易模式保存的吧？

**Comment by WestCraneLi** [comment]
> 你用简易模式保存的吧？

是的
![image](https://github.com/labring/FastGPT/assets/76116480/8e73db7e-d3a4-4152-a2f2-525afea3185c)
![image](https://github.com/labring/FastGPT/assets/76116480/b37c830c-9746-425f-84d7-33c98469934f)

**Comment by WestCraneLi** [comment]
那不点击保存就能应用了高级编排的能力了是吗

> > > 你用简易模式保存的吧？
> > 
> > 
> > 是的
> > ![image](https://private-user-images.githubusercontent.com/76116480/321308716-8e73db7e-d3a4-4152-a2f2-525afea3185c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjU2MjYsIm5iZiI6MTcxMjc2NTMyNiwicGF0aCI6Ii83NjExNjQ4MC8zMjEzMDg3MTYtOGU3M2RiN2UtZDNhNC00MTUyLWEyZjItNTI1YWZlYTMxODVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2MDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlODY5ZWRjNTM0ODgwMjlkOWRjYjY3MWNiODIwZjE0NTllZTVkOGZlM2Y5M2MyMmRiYjY0ODk4Mjk2ODg2YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BdWDUPEkm-FUuapUK2Fatd37mc6472iH8CpGW-iHclA)
> > ![image](https://private-user-images.githubusercontent.com/76116480/321308851-b37c830c-9746-425f-84d7-33c98469934f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjU2MjYsIm5iZiI6MTcxMjc2NTMyNiwicGF0aCI6Ii83NjExNjQ4MC8zMjEzMDg4NTEtYjM3YzgzMGMtOTc0Ni00MjVmLTg0ZDctMzNjOTg0Njk5MzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2MDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZjY1YzIzZDc4NTM4YTI5NmI5ZjQzNjE0NDE2OGI2ZGU5YzBhZjlkMzU5OGFkOTc0ZjMxZWMwYjY3MDE2MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Ln7GzsyjFrhxa3cq_PPQrdAGIcrH7AkWtnjlWeGcCY)
> 
> 你注意看提示。。
