### ISSUE TITLE
高级编排里, 对话入口如何调用聊天记录

### ISSUE THREAD

**Issue by zihjiang** [labring/FastGPT#1181]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  前天部署最新版,v4.7

**问题描述**
分体分类的 "聊天记录是必选项", 我找了一圈没找到这个聊天记录是从那个模块里拖出来的, 直到我找到了一个官方的配置导进来后发现可能是从对话入口来的, 所以我就把官方的配置导进来了, 在官方的基础上把对话入口的这个配置加进来, 这才可以完成这个流程, 我下问下这个是不是bug
**复现步骤**

**预期结果**

**相关截图**
<img width="1096" alt="image" src="https://github.com/labring/FastGPT/assets/21021327/f7389f94-8f2d-4ced-813c-4aec1633e866">

**Comment by lijiajun1997** [comment]
默认会自动调取对话记录上下文 这个模块是隐藏的 我也没见过

**Comment by c121914yu** [comment]
每个模块都有历史记录选项，直接选多少条就可以了。
