### ISSUE TITLE
新reranker版本优化支持cpu运行

### ISSUE THREAD

**Issue by yibohub** [labring/FastGPT#1183]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1-fix

**问题描述**
fastgpt是4.7.1-fix版本，reranker模型：image: registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1
在这个reranker模型下，cpu运行耗时过长，导致重排失败，以前的reranker版本是可以正常运行和调用的。请优化。
B站上都有老哥针对这个问题自己修改代码录了视频，但是仅限针对alpha2版本。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/161293070/f3e3f821-3eb1-49a6-80a6-a4bf924746f0)
![image](https://github.com/labring/FastGPT/assets/161293070/bc497d76-31bd-4bb4-a64c-362da879ed25)

**Comment by yibohub** [comment]
4.6.8版本时，把rerank模型和M3E模型一起部署在一个4V8G的服务器上还可以跑。现在在4V8G上根本内存不够。换了4V16G的服务器，可以跑，但是延时严重，用不了。

**Comment by Lzzycola** [comment]
我打了个日志，4.7.1的镜像在rerank的时候会将知识库所有的内容全部送进模型里跑，而不是先根据第一遍搜索过滤后的数据进行rerank。我因为数据太多直接把rerank打死了，哈哈哈哈。

**Comment by c121914yu** [comment]
> 我打了个日志，4.7.1的镜像在rerank的时候会将知识库所有的内容全部送进模型里跑，而不是先根据第一遍搜索过滤后的数据进行rerank。我因为数据太多直接把rerank打死了，哈哈哈哈。

rerank 数量应该是 100 条。

**Comment by c121914yu** [comment]
> 4.6.8版本时，把rerank模型和M3E模型一起部署在一个4V8G的服务器上还可以跑。现在在4V8G上根本内存不够。换了4V16G的服务器，可以跑，但是延时严重，用不了。

cpu 跑没意义

**Comment by lxl80** [comment]
> > 4.6.8版本时，把rerank模型和M3E模型一起部署在一个4V8G的服务器上还可以跑。现在在4V8G上根本内存不够。换了4V16G的服务器，可以跑，但是延时严重，用不了。
> 
> cpu 跑没意义

可以支持Mac芯片的GPU来跑吗？

**Comment by Linnnkkk** [comment]
请问这个问题解决了吗

**Comment by Linnnkkk** [comment]
> 我打了个日志，4.7.1的镜像在rerank的时候会将知识库所有的内容全部送进模型里跑，而不是先根据第一遍搜索过滤后的数据进行rerank。我因为数据太多直接把rerank打死了，哈哈哈哈。

这个解决了吗？

**Comment by yibohub** [comment]
基本不支持cpu运行。
