### ISSUE TITLE
知识库导入，优化含表格文件分块功能

### ISSUE THREAD

**Issue by yibohub** [labring/FastGPT#1184]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
现有的知识库导入在自动分块时，直接按字数分块，对表格文件如PDF含表格，EXCEL表格文件分块时直接按字数截断，同一行的信息位于不同的块中。建议优化为在满足字数要求的情况下按行截断，保证信息的完整性。
**应用场景**

**相关示例**

**Comment by lijiajun1997** [comment]
同意 另外如果按行分块的话 建议补全表头

**Comment by c121914yu** [comment]
excel 已经按行补全表头了呢。

**Comment by sdytzjp** [comment]
> excel 已经按行补全表头了呢。

的确已经按行补全表头了，这个就很好。
请问4.8.9，是在满足字数要求的情况下按行截断的吗？

**Comment by c121914yu** [comment]
> > excel 已经按行补全表头了呢。
> 
> 
> 
> 的确已经按行补全表头了，这个就很好。
> 
> 请问4.8.9，是在满足字数要求的情况下按行截断的吗？

对，
