### ISSUE TITLE
本地部署FastGPT有注册入口吗或者如何添加新的账号

### ISSUE THREAD

**Issue by WestCraneLi** [labring/FastGPT#1186]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  lateset

**问题描述**
我想创建多个用户账号，给其他人使用，所以需要FastGPT的注册功能
![image](https://github.com/labring/FastGPT/assets/76116480/f67af661-836b-4d62-b998-69181778018f)

**Comment by mxr612** [comment]
这个貌似是商业版功能
