### ISSUE TITLE
本地部署回复上限不能超过2000

### ISSUE THREAD

**Issue by HelloEveryonehh** [labring/FastGPT#1188]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.7

**问题描述**
本地部署fastgpt，通过one-api对接qwen-max和qwen-turbo，然后发现当回复**上限设置超过2000时**，会报错，2000以内则不会报错，报错如下
我已经自行确认qwen-max和qwen-turbo的可接受上下文比我设置的要大，**在faq中的对应原因与我的情况不符合**。请作者看一下，非常感谢！
**预期结果**
回复超过2000不报错
**相关截图**
报错截图:
![image](https://github.com/labring/FastGPT/assets/110333012/80838983-44f3-4777-863a-d908d01aa28c)
docker logs fastgpt截图:
![image](https://github.com/labring/FastGPT/assets/110333012/0d31e4e3-1d59-48f3-b01f-e0e688f01ded)
config.json：
![image](https://github.com/labring/FastGPT/assets/110333012/8d3e196f-04d0-40ba-bde8-3f80f0642963)
![image](https://github.com/labring/FastGPT/assets/110333012/7b19a6c3-1dd7-41b6-bdfe-f7febe5d96e6)
下面是one-api里面的截图，当发送报错的时候会出现如下情况:
![image](https://github.com/labring/FastGPT/assets/110333012/747975b7-01a2-4589-94dd-a8b2f6895a18)

**Comment by HelloEveryonehh** [comment]
> 官方支持多少？

![image](https://github.com/labring/FastGPT/assets/110333012/d4f75937-8069-43fd-b1eb-7728cdf9b312)
我测试发现，在正式的对话界面回答的内容要比在高级编排界面回答的内容要多，即使我都是设置的2000

**Comment by HelloEveryonehh** [comment]
@c121914yu 所以这是一个bug吗

**Comment by c121914yu** [comment]
> @c121914yu 所以这是一个bug吗

不懂，没用过本地模型。本地模型，先自己测试通过再接入。

**Comment by HelloEveryonehh** [comment]
> > @c121914yu 所以这是一个bug吗
> 
> 不懂，没用过本地模型。本地模型，先自己测试通过再接入。 本地模型能不能用，除了取决于模型参数，很大程度还取决于接口是否适配，有些接口写的很垃圾，参数鲁棒性很差，那也没啥用。

这个是阿里的api服务，应该不算本地模型，国内还挺常见的，问题是在高级编排里面回答的内容很少，但是在正式的对话可以回答很多内容，看起来是个bug

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/8936d8d4-569d-4726-b373-5fb673b974d9)
直接测试就知道了，官方提示就最大2000
