### ISSUE TITLE
求助：docker 部署："modeldata"错误

### ISSUE THREAD

**Issue by justincnn** [labring/FastGPT#119]
![](https://s2.loli.net/2023/07/08/swjnO7utmk2dS4e.png)

docker部署，可以进系统，注册账号都没有问题，但是无法新建知识库，

使用的是最新的docker-compose镜像

进入PG容器，链接数据库之后，输入init.sql没有任何输出

![](https://s2.loli.net/2023/07/08/Kx2m3VM8aR9y7i5.png)

**Comment by c121914yu** [comment]
init.sql是首次部署自动执行的。没法自动执行的话，手动复制sql语句执行。

**Comment by billsking** [comment]
> init.sql是首次部署自动执行的。没法自动执行的话，手动复制sql语句执行。

请问sql语句在哪儿？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> init.sql is automatically executed for the first deployment. If it cannot be executed automatically, manually copy the SQL statement and execute it.

Where is the sql statement?
