### ISSUE TITLE
登录fastgpt时出现network error

### ISSUE THREAD

**Issue by wnnnnh007** [labring/FastGPT#1192]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ x] 公有云版本
- [ √] 私有部署版本, 具体版本号: 

**问题描述**
  第一次登陆的时候并没有可以正常跑通所有流程，重新拉起容器后就无法使用fastgpt，在获取创建模型的时候就已经显示network error
**复现步骤**

**预期结果**

**相关截图**
![微信图片_20240412101955](https://github.com/labring/FastGPT/assets/95423496/c6b69ec5-3b18-4767-8d06-99dc9f9e6696)

![微信图片_20240412102030](https://github.com/labring/FastGPT/assets/95423496/bb606a20-a321-43ca-97c3-962964204766)

**Comment by newboy111** [comment]
你好 我也遇到了这个错误 想请问一下如何解决的

**Comment by tiamohf** [comment]
遇到同样的问题
![image](https://github.com/labring/FastGPT/assets/33214450/9f8ce46a-6200-4d00-93e4-fe3dadfd0888)

**Comment by thegenway** [comment]
我遇到了相同的问题，请问作者解决了吗？下面是我的报错信息
`2024-04-30 10:35:26 Load init config error SyntaxError: Unexpected token / in JSON at position 2194
2024-04-30 10:35:26     at JSON.parse (<anonymous>)
2024-04-30 10:35:26     at p (/app/projects/app/.next/server/chunks/16378.js:54:24110)
2024-04-30 10:35:26     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-30 10:35:26     at async Promise.all (index 0)
2024-04-30 10:35:26     at async g (/app/projects/app/.next/server/chunks/16378.js:54:23441)
2024-04-30 10:35:26     at async y (/app/projects/app/.next/server/chunks/16378.js:54:22571)`

**Comment by RyanHM123** [comment]
这个问题解决了吗？

**Comment by c121914yu** [comment]
> 我遇到了相同的问题，请问作者解决了吗？下面是我的报错信息
> `2024-04-30 10:35:26 Load init config error SyntaxError: Unexpected token / in JSON at position 2194
> 2024-04-30 10:35:26     at JSON.parse (<anonymous>)
> 2024-04-30 10:35:26     at p (/app/projects/app/.next/server/chunks/16378.js:54:24110)
> 2024-04-30 10:35:26     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-04-30 10:35:26     at async Promise.all (index 0)
> 2024-04-30 10:35:26     at async g (/app/projects/app/.next/server/chunks/16378.js:54:23441)
> 2024-04-30 10:35:26     at async y (/app/projects/app/.next/server/chunks/16378.js:54:22571)`

配置文件写错了哇

**Comment by lvouran** [comment]
> 遇到同样的问题 ![image](https://private-user-images.githubusercontent.com/33214450/326340312-9f8ce46a-6200-4d00-93e4-fe3dadfd0888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MjY3OTAsIm5iZiI6MTczMDQyNjQ5MCwicGF0aCI6Ii8zMzIxNDQ1MC8zMjYzNDAzMTItOWY4Y2U0NmEtNjIwMC00ZDAwLTkzZTQtZmUzZGFkZmQwODg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAyMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmM2E4OTY2ZmY2N2IyZDBlZmNlOWI2OWU5N2MyZDliZDc4NDBiM2JiZGEwZWNiNGYzMGEyMWYwZjQ5YzFkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SyPlCER4OP-Ks_rXxV9XA-13jhVQOqkw0A-JehIGzrc) ![image](https://private-user-images.githubusercontent.com/33214450/326340600-1e57ef2c-d4dd-40ec-a812-0b4d833056d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MjY3OTAsIm5iZiI6MTczMDQyNjQ5MCwicGF0aCI6Ii8zMzIxNDQ1MC8zMjYzNDA2MDAtMWU1N2VmMmMtZDRkZC00MGVjLWE4MTItMGI0ZDgzMzA1NmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAyMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NmZhYzIyZTQ3M2EyZTJjMzVhODBiY2I2ZjVkOGJjN2YwNTcxNzc0Y2I3YWQ0MzZlY2UxZWM3YTU0YzJiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zPS4HIwTYZrQ3WV9mZ_jThViYG0xOzKcYH_RBUzDxlY)

你好，这个报错解决了嘛，我看并不是下面说的配置文件报错
