### ISSUE TITLE
BUG：高级编排语音输入配置 无法开启语音输入

### ISSUE THREAD

**Issue by zhanghx0905** [labring/FastGPT#1195]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.7.1

**问题描述**

高级编排中，点击语音输入配置，在弹出的配置框中，无法启用语音输入选项。点击启动按键没有响应。

但是在简单编排中是能正确启用语音输入的。

![](https://github.com/labring/FastGPT/assets/50790281/d8435b84-c993-41ef-bb4f-5ecf9b1e3dc6)

**Comment by zhanghx0905** [comment]
我发现通过导出配置在导入配置，通过手动加入语音输入的相关配置，可以解决这个问题

**Comment by ifkd111** [comment]
> 我发现通过导出配置在导入配置，通过手动加入语音输入的相关配置，可以解决这个问题

求教程，小白完全不会

**Comment by c121914yu** [comment]
> 我发现通过导出配置在导入配置，通过手动加入语音输入的相关配置，可以解决这个问题

fix 修复了这个问题
