### ISSUE TITLE
bad_response_status_code bad response status code 400 (request id: 2024041206471277477749259854448)

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1196]
**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述**
对话第三轮，就会出现这个报错
**复现步骤**
[ERROR] 2024-04-12 06:47:12 sse error: bad_response_status_code bad response status code 400 (request id: 2024041206471277477749259854448)
{
  message: '400 bad response status code 400 (request id: 2024041206471277477749259854448)',
  stack: 'Error: 400 bad response status code 400 (request id: 2024041206471277477749259854448)\n' +
    '    at eL.generate (/app/projects/app/.next/server/chunks/80555.js:21:70043)\n' +
    '    at af.makeStatusError (/app/projects/app/.next/server/chunks/80555.js:21:81687)\n' +
    '    at af.makeRequest (/app/projects/app/.next/server/chunks/80555.js:21:82610)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Object.x [as chatNode] (/app/projects/app/.next/server/chunks/94900.js:129:1124)\n' +
    '    at async N (/app/projects/app/.next/server/chunks/94900.js:130:2805)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async S (/app/projects/app/.next/server/chunks/94900.js:130:4134)\n' +
    '    at async /app/projects/app/.next/server/pages/api/v1/chat/completions.js:1:4535'
}

**Comment by Essence9999** [comment]
![image](https://github.com/labring/FastGPT/assets/66725845/a1cb295f-1dd4-4741-ad3c-44098657be83)
高级编排中，将聊天记录由3改为默认的6，测试多轮，问题没出现

**Comment by c121914yu** [comment]
参考另一个讨论。国内模型不支持奇数。
