### ISSUE TITLE
知识库机器人回答所引用文件列表的top1检索到的文本内容，并没有作为结果回答出来，而是选择了top2的文本内容

### ISSUE THREAD

**Issue by WestCraneLi** [labring/FastGPT#1197]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: lateset

**问题描述**
知识库机器人回答的内容，并不是所引用文件列表中的top1文本内容，而是选择了top2的文本内容，1和2内容具有一定差异性，这是为什么呢，因为上下文吗
![image](https://github.com/labring/FastGPT/assets/76116480/5e5719aa-df92-4fba-b069-e701cac72a30)

**Comment by WestCraneLi** [comment]
> 排序是看向量匹配度 回答是AI自己看哪个知识与答案更相关

如何让AI回答往排序第一个靠呢，毕竟有时候回答救护出现这种情况

**Comment by c121914yu** [comment]
尝试在引用提示词增加 index 变量，这是一个排序变量。
并在提示词对模型进行要求。。

**Comment by WestCraneLi** [comment]
看起来有一定效果
