### ISSUE TITLE
判断器无法判断空字符串

### ISSUE THREAD

**Issue by jevonsnotes** [labring/FastGPT#1199]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
4.7
**问题描述**
判断器无法判断输入的空串
**复现步骤**
![image](https://github.com/labring/FastGPT/assets/24319663/ae736ef2-08f1-40dc-b23b-b793f4c902bb)

![e0f1ea5054a95cdacf16e83e9730d9d](https://github.com/labring/FastGPT/assets/24319663/220b1296-497a-43fe-96a6-bca4a9d0f016)
![d0ed4c9ddf17c353a3d22764ab3cc4f](https://github.com/labring/FastGPT/assets/24319663/df9f49dc-a451-4154-b27f-bc9b3aaf6c78)

**预期结果**
应该输出false
**相关截图**

**Comment by c121914yu** [comment]
试试正则 ^$

**Comment by jevonsnotes** [comment]
试过了，截图里有的

| |
张浩文（Jevons）
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月12日 22:12 |
| 收件人 | labring/FastGPT ***@***.***> |
| 抄送人 | jevonsnotes ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [labring/FastGPT] 判断器无法判断空字符串 (Issue #1199) |

试试正则 ^$

**Comment by c121914yu** [comment]
新工作流中会解决这个问题

**Comment by jevonsnotes** [comment]
> 新工作流中会解决这个问题

好的，谢谢

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8-preview 新的判断器可以实现
