### ISSUE TITLE
提取内容的提示词有问题，<对话记录>标签导致千问Qwen模型查不到真的<对话记录>

### ISSUE THREAD

**Issue by mxdlzg** [labring/FastGPT#1200]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1

**问题描述**
使用目前的提示词生成的请求如下：
`{
  "model": "qwen-1.8b-chat",
  "temperature": 0.01,
  "messages": [
    {
      "role": "user",
      "content": "你可以从 **<对话记录></对话记录>**中提取指定 JSON 信息，你仅需返回 JSON 字符串，无需回答问题。<提取要求>你是谷歌搜索机器人，根据当前问题和对话记录生成搜索词。 你需要自行判断是否需要进行网络实时查询： - 如果需查询则生成搜索词。 - 如果不需要查询则不返回该字段。      </提取要求>      <字段说明>      1. 下面的 JSON 字符串均按照 JSON Schema 的规则描述。      2. key 代表字段名；description 代表字段的描述；enum 是可选值，代表可选的 value。      3. 如果没有可提取的内容，忽略该字段。      4. 本次需提取的JSON Schema：{\"key\":\"searchKey\", \"description\":\"搜索词\"}      </字段说明>      <对话记录>Human: 查询今日的股票信息</对话记录>"
    }
  ],
  "stream": false
}`
结果：
`{
    "id": "090fd4b9-65c6-9807-a905-18ebed6bf9b1",
    "model": "qwen",
    "object": "chat.completion",
    "created": 1712932297,
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                **"content": "根据您的要求，我将从对话记录中提取“searchKey”字段的信息，并将其转换为 JSON 字符串。\n```json\n{\n    \"key\": \"searchKey\",\n    \"description\": \"搜索词\"\n}\n```\n\n因此，今天的股票信息是：“今日的股票信息”。"**
            },
            "finish_reason": "stop"
        }
    ],
    "usage": {
        "prompt_tokens": 194,
        "completion_tokens": 61,
        "total_tokens": 255
    }
}`

修改提示词的请求如下：
`{
  "model": "qwen-1.8b-chat",
  "temperature": 0.01,
  "messages": [
    {
      "role": "user",
      "content": "你可以从**对话记录**中提取指定 JSON 信息，你仅需返回 JSON 字符串，无需回答问题。<提取要求>你是谷歌搜索机器人，根据当前问题和对话记录生成搜索词。 你需要自行判断是否需要进行网络实时查询： - 如果需查询则生成搜索词。 - 如果不需要查询则不返回该字段。      </提取要求>      <字段说明>      1. 下面的 JSON 字符串均按照 JSON Schema 的规则描述。      2. key 代表字段名；description 代表字段的描述；enum 是可选值，代表可选的 value。      3. 如果没有可提取的内容，忽略该字段。      4. 本次需提取的JSON Schema：{\"key\":\"searchKey\", \"description\":\"搜索词\"}      </字段说明>      <对话记录>Human: 查询今日的股票信息</对话记录>"
    }
  ],
  "stream": false
}`
结果：
`{
    "id": "300f49b8-be5c-9994-bdbd-bfb37e0fa151",
    "model": "qwen",
    "object": "chat.completion",
    "created": 1712932229,
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                **"content": "{'searchKey': '今日股票', 'description': '查询今日的股票信息'}"**
            },
            "finish_reason": "stop"
        }
    ],
    "usage": {
        "prompt_tokens": 189,
        "completion_tokens": 18,
        "total_tokens": 207
    }
}`

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/18144577/2d5e7ba5-5cee-4f69-ab8f-c9332685f11b)

**Comment by c121914yu** [comment]
根据不同模型调整即可，配置文件可以配置。
