### ISSUE TITLE
gpt-4-turbo发布后请求对话接口支持图片上传

### ISSUE THREAD

**Issue by vary** [labring/FastGPT#1201]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [ x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
OpenAPI 对话接口请求支持文件上传图片上传，现在gpt-4-turbo发布后图片成为了标配，希望能够在接口上对接OpenAI支持图片上传
**应用场景**
立即对话页面早已支持图片上传，接口支持可以更方便的扩展使用场景
**相关示例**

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/7e4063f6-d9cf-4579-bc0c-2494894d7fb8)
打开就可以了

**Comment by dimsky** [comment]
#1217

**Comment by dimsky** [comment]
> > #1217 已修复
> 
> 不是的，页面上支持我知道支持，我说的是通过API调用fastgpt

你仔细看看这个  issue ，刚修复的，v4.7.2 版本应该会修复这个问题。

**Comment by vary** [comment]
> > > #1217 已修复
> > 
> > 
> > 不是的，页面上支持我知道支持，我说的是通过API调用fastgpt
> 
> 你仔细看看这个 issue ，刚修复的，v4.7.2 版本应该会修复这个问题。

好的，感谢！
