### ISSUE TITLE
AI模型配置中，聊天记录数量设置为奇数时对话出现接口报错或返回为空的报错

### ISSUE THREAD

**Issue by duskcouple** [labring/FastGPT#1202]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1

**问题描述**
通过docker镜像升级至4.7.1后发现一个问题，目前不确认是否是共性问题，问题现象是，当在应用的AI模型配置那里，将聊天记录数量设置为奇数的时候，正常对话没几条，然后就出现无法对话，出现对话接口报错或者返回为空的提示框，docker logs 也看到有相关的报错，不管是单纯的AI对话应用，还是带知识库的应用，都有此问题。但如果将聊天记录数量设置为偶数的时候，就不会出现这种错误。挺诡异的，提供给官方测试排查下，不知道是否是共性普遍问题，还是我个人环境问题。
**复现步骤**
在AI模型配置那里，将聊天记录数量设置为奇数  1  ，3   ，5  ....
**预期结果**

**相关截图**
![搜狗截图20240413111926](https://github.com/labring/FastGPT/assets/26564245/23e88ce2-abfe-4c80-babd-081518c0884a)
![搜狗截图20240413112122](https://github.com/labring/FastGPT/assets/26564245/fc4a6336-0727-46c9-a2a8-5d0878f56f92)
![搜狗截图20240413112154](https://github.com/labring/FastGPT/assets/26564245/32771bac-2239-407f-9d40-9596e523fc02)

**Comment by c121914yu** [comment]
除了 gpt，国内模型都不支持奇数吧

**Comment by duskcouple** [comment]
哭死！我还真不知道国内模型还有这癖好，偶数行，奇数不行，就这，各家还遍地吹遥遥领先。
不过，还是建议那里能给个提示，我觉得肯定不光是我一个人不知道国内模型的这癖好，从界面交互上来说，既然能调节设置数量，没人会考虑什么奇数偶数。

**Comment by Essence9999** [comment]
> 哭死！我还真不知道国内模型还有这癖好，偶数行，奇数不行，就这，各家还遍地吹遥遥领先。 不过，还是建议那里能给个提示，我觉得肯定不光是我一个人不知道国内模型的这癖好，从界面交互上来说，既然能调节设置数量，没人会考虑什么奇数偶数。

我之前设置一个3，也是同样的情况，以为是多轮对话轮数~

**Comment by c121914yu** [comment]
> 哭死！我还真不知道国内模型还有这癖好，偶数行，奇数不行，就这，各家还遍地吹遥遥领先。
> 不过，还是建议那里能给个提示，我觉得肯定不光是我一个人不知道国内模型的这癖好，从界面交互上来说，既然能调节设置数量，没人会考虑什么奇数偶数。

嗯呢。
