### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Dmeng1996** [labring/FastGPT#1203]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述**
fastgpt连接不上oneapi
**复现步骤**

**预期结果**

**相关截图**
![error](https://github.com/labring/FastGPT/assets/37871138/c42666d3-b229-412d-b0ad-35411fb15000)

**Comment by lijiajun1997** [comment]
看上去不是oneapi的问题？是fastgpt应用本身没有启动好？删掉部署重来试试

**Comment by c121914yu** [comment]
地址填不对，网络不通
