### ISSUE TITLE
语音输入功能不能正常使用

### ISSUE THREAD

**Issue by boboyunz** [labring/FastGPT#1205]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.7.1

**问题描述**
启用了语音输入的功能，但是页面上不起作用。无法接收语音输入

**复现步骤**
![image](https://github.com/labring/FastGPT/assets/45583988/2afa2832-f93f-48c1-b043-cdfcb8e31e06)
![image](https://github.com/labring/FastGPT/assets/45583988/7ad44803-20a8-41f4-862c-8a425659a165)

**预期结果**
系统能够正常使用语音输入功能
**相关截图**

**Comment by lijiajun1997** [comment]
需要api里有whisper-1模型

**Comment by boboyunz** [comment]
怎么配置  请详细说明一下

**Comment by lijiajun1997** [comment]
> 怎么配置 请详细说明一下

whisper-1是openai的语音识别模型，你找个openai的中转api就带着，没试过本地部署语音识别或者用其他模型，我理解需要改下config里的模型名称然后接入oneapi

**Comment by boboyunz** [comment]
谢谢   我试试看  有结果在这里反馈

**Comment by c121914yu** [comment]
不能用有很多种，你是哪种？请详细描述下。比如
点了没反应。
一直转圈，
接口报错等等

**Comment by ifkd111** [comment]
> 不能用有很多种，你是哪种？请详细描述下。比如 点了没反应。 一直转圈， 接口报错等等

点了没反应，我不知道早呢恶魔接入模型什么的，就是更新了4.7.1之后，看到有语音这个选项，就选了，但是并没有反应，求问怎么设置？纯小白

**Comment by ifkd111** [comment]
> 谢谢 我试试看 有结果在这里反馈

有结果了嘛？求带带，小白不会弄，我本地部署的

**Comment by nightzjp** [comment]
> > 谢谢 我试试看 有结果在这里反馈
> 
> 有结果了嘛？求带带，小白不会弄，我本地部署的

语音输入输出好像必须要https协议

**Comment by boleyn** [comment]
苹果手机识别效果很差，初步判断是录音文件的问题，有时候甚至录音文件丢失，安卓手机就没有这个问题

**Comment by ifkd111** [comment]
> > > 谢谢 我试试看 有结果在这里反馈
> > 
> > 
> > 有结果了嘛？求带带，小白不会弄，我本地部署的
> 
> 语音输入输出好像必须要https协议

所以该怎么操作呢

**Comment by sdytzjp** [comment]
怎么处理的

**Comment by jjjasd7764** [comment]
我也用了语音功能，但是没有任何反应
