### ISSUE TITLE
应用分享的免登录窗口是否可以控制让回答的“引用”模块不展示

### ISSUE THREAD

**Issue by WestCraneLi** [labring/FastGPT#1208]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
应用分享的免登录窗口不展示回答的“引用”模块不展示。以下是2个考虑点
* 考虑到应用分享的免登录窗口大概率情况下是给非开发人员所使用的，不展示“引用”模块对用户体验更好，毕竟如果“引用”模块中的文件内容过多，对用户体验也不好
* “引用”模块里的文件内容均为markdown格式，非开发用户看了也看不懂，所以不展示也没有问题
![image](https://github.com/labring/FastGPT/assets/76116480/88ca2d53-8daa-47ac-a890-31217c5c8a5f)

**Comment by nongmo677** [comment]
![image](https://github.com/labring/FastGPT/assets/31816449/19d172e7-2851-479e-96f4-7eb19af23f01)

发布里面不是有这个功能吗

**Comment by WestCraneLi** [comment]
> ![image](https://private-user-images.githubusercontent.com/31816449/322332143-19d172e7-2851-479e-96f4-7eb19af23f01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDcyMTMsIm5iZiI6MTcxMzE0NjkxMywicGF0aCI6Ii8zMTgxNjQ0OS8zMjIzMzIxNDMtMTlkMTcyZTctMjg1MS00NzllLTk2ZjQtN2ViMTlhZjIzZjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAyMDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYmZkNTM5MmEwNWE0MDMxNzdiYzdkMTAyZTAwMDdhYWUyNzJiZWUxZmI0MGQ0M2Y5YTBjNjJhYjZiZjMwZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8WaN_ex3uB6eQgepFvF-Iqp6ivuhsU6of-wtTF2HItE)
> 
> 发布里面不是有这个功能吗

好的没看清楚😂
