### ISSUE TITLE
请问本地部署如何修改title

### ISSUE THREAD

**Issue by WangDongWei515** [labring/FastGPT#1209]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
通过替换icon文件修改默认图标，重新部署后失效。
之前有一个版本可以通过config.json设置title，现在好像不行了？
**复现步骤**

**预期结果**

**相关截图**
![629fd2af15b0d777bc6b55760a4aecb](https://github.com/labring/FastGPT/assets/56469810/3a7c43a1-397e-4ea1-acf1-552d8eaff436)
上图为之前版本
下图为最新版本

![微信图片_20240415095219](https://github.com/labring/FastGPT/assets/56469810/fe127056-42e3-4e4d-a2ab-83653fea1be4)

**Comment by boleyn** [comment]
直接在代码里面修改  projects/app/src/pages/api/common/system/getInitData.ts 这里面直接修改，目前版本通过配置文件修改好像不生效

**Comment by sdytzjp** [comment]
> 直接在代码里面修改 projects/app/src/pages/api/common/system/getInitData.ts 这里面直接修改，目前版本通过配置文件修改好像不生效

请问这么目录在那个docker下，fastgpt下没有
![image](https://github.com/labring/FastGPT/assets/174102361/818402d7-702e-46bb-b0fa-2e172197b946)
