### ISSUE TITLE
高级编排中的引用提示词中的引用内容模版的完整案例，包含source，sourceId，index

### ISSUE THREAD

**Issue by WestCraneLi** [labring/FastGPT#1211]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: lateset

**问题描述**
高级编排中的引用提示词中的引用内容模版的完整案例，除了模版中展示QA，我还想知道，其他的如何描述，比如source，sourceId，index
![image](https://github.com/labring/FastGPT/assets/76116480/a33836ab-2003-4bf9-9899-b5a994dbd9bf)

以下是我写的内容，不知道是否正确
![image](https://github.com/labring/FastGPT/assets/76116480/3b167bc9-2884-4a20-88b8-85d0dfe3238e)

**Comment by c121914yu** [comment]
是的

**Comment by WestCraneLi** [comment]
好的，那没有问题了
