### ISSUE TITLE
手动录入的数据集删除后还会被检索到

### ISSUE THREAD

**Issue by jackieZhouQQ** [labring/FastGPT#1212]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号:  4.7.1

**问题描述**
手动录入的数据集删除后，有时会删除不成功，还是会被检索到，但是数据集页面已经无法找到该数据集

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/108133430/58ac76ca-feeb-4636-bc25-7d30342a2f38)
![image](https://github.com/labring/FastGPT/assets/108133430/f3516602-b6b3-411c-92ba-9451cf768faa)

**Comment by c121914yu** [comment]
这个问题会在 4.8.1 进一步优化。
之前设置了定时器清理，但是发现时间写错了。
可以尝试执行 4.8.1 的 clearInvalid api 清理全部脏数据。
后续，它会每小时检测一遍 2-6 小时内的数据，并清理脏数据。
