### ISSUE TITLE
oneapi 容器启动不起来 

### ISSUE THREAD

**Issue by lonngxiang** [labring/FastGPT#1218]
报错：

2024/04/16 02:10:07 /build/model/main.go:79
[error] failed to initialize database, got error dial tcp 172.118.0.5:33066: connect: connection refused
[SYS] 2024/04/16 - 02:10:39 | One API v0.6.5-alpha.18 started 
[SYS] 2024/04/16 - 02:10:39 | using MySQL as database 
[FATAL] 2024/04/16 - 02:10:39 | [dial tcp 172.118.0.5:33066: connect: connection refused] 

2024/04/16 02:10:39 /build/model/main.go:79
[error] failed to initialize database, got error dial tcp 172.118.0.5:33066: connect: connection refused

**Comment by xiaoToby** [comment]
应该在oneapi项目中询问。。。。。

**Comment by nongmo677** [comment]
Linux 还是wsl? 看错误是oneapi 对应的mysql 容器的问题
建议docker-compose down && docker-compose up -d 重启项目从头查看日志

**Comment by Jiang-Wan** [comment]
![截图](https://github.com/labring/FastGPT/assets/57851281/77b6344e-98ea-47b0-9b95-9f5193d9e4a2)
试试把截图中的MySql改成实际的IP地址，当然，要确保你的MySql外部能访问

**Comment by lonngxiang** [comment]
确实主要就是ip问题，容器内ip或者主机ip测试

**Comment by Thinking80s** [comment]
+1

**Comment by Dhaizei** [comment]
解决了吗

**Comment by open8eye** [comment]
确实是ip地址的问题，我wsl运行的，用虚拟机内部的ip地址就可以了

**Comment by fozzmarc** [comment]
我是通过把 MEMORY_CACHE_ENABLE 功能关掉，便可以顺利启动了。
