### ISSUE TITLE
chatgpt-on-wechat使用GLM-4 模型后字段改变问题

### ISSUE THREAD

**Issue by AiLiMeN** [labring/FastGPT#1219]
chatgpt-on-wechat  1.5.7版本后支持GLM4模型，但是配置文件中字段有改动，
原：
"model": "gpt-3.5-turbo",
"zhipu_ai_api_key": "YOUR_API_KEY",
"zhipu_ai_api_base": "http://xx.xx.xx.xx:3000/api/v1"

现在：
"model": "glm-4",
"zhipu_ai_api_key": "YOUR_API_KEY",
"zhipu_ai_api_base": "https://open.bigmodel.cn/api/paas/v4"
导致如果chatgpt-on-wechat接glm4模型就不能使用fastgpt，接fastgpt就无法使用glm4模型，可否与chatgpt-on-wechat沟通，统一下字段

**Comment by nongmo677** [comment]
接入oneapi做中转

**Comment by AiLiMeN** [comment]
> 接入oneapi做中转

"zhipu_ai_api_key": "YOUR_API_KEY", 这里填oneapi的令牌吗？
"zhipu_ai_api_base": "https://open.bigmodel.cn/api/paas/v4"，这里填oneapi部署的地址及端口吗？

**Comment by nongmo677** [comment]
冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？

**Comment by AiLiMeN** [comment]
> 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？

部署的开源版本，chatgpt-on-wechat调fastgpt发布的api

**Comment by nongmo677** [comment]
> > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> 
> 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api

那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的

**Comment by AiLiMeN** [comment]
> > > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> > 
> > 
> > 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api
> 
> 那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的
是这样配置的，但是他不能用glm4

**Comment by AiLiMeN** [comment]
> > > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> > 
> > 
> > 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api
> 
> 那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的

是这样配置的，但是他不能用glm4

**Comment by AiLiMeN** [comment]
> > > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> > 
> > 
> > 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api
> 
> 那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的

OPEN_AI_API_KEY: 'fastgpt-xxxxxx'
OPEN_AI_API_BASE: 'http://xxx:3000/api/v1'
用这个配置文件接入fastgpt后只能调用它默认的gpt3.5

**Comment by AiLiMeN** [comment]
> > > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> > 
> > 
> > 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api
> 
> 那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的

因为我fastgpt是接的glm4，在PC上的回答比较好，但是用chatgpt-on-wechat微信回答的就有点差强人意，看了日志有一个警告，默认走gpt3.5了

**Comment by nongmo677** [comment]
> > > > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> > > 
> > > 
> > > 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api
> > 
> > 
> > 那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的
> 
> OPEN_AI_API_KEY: 'fastgpt-xxxxxx' OPEN_AI_API_BASE: 'http://xxx:3000/api/v1' 用这个配置文件接入fastgpt后只能调用它默认的gpt3.5

oneapi里面支持模型重定向，就是说接收到gpt3.5，但是你可以重定向到你定义的glm4，这个功能你探索一下

**Comment by AiLiMeN** [comment]
> > > > > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> > > > 
> > > > 
> > > > 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api
> > > 
> > > 
> > > 那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的
> > 
> > 
> > OPEN_AI_API_KEY: 'fastgpt-xxxxxx' OPEN_AI_API_BASE: 'http://xxx:3000/api/v1' 用这个配置文件接入fastgpt后只能调用它默认的gpt3.5
> 
> oneapi里面支持模型重定向，就是说接收到gpt3.5，但是你可以重定向到你定义的glm4，这个功能你探索一下

oneapi里面里面我就配了两个模型，一个m3e一个glm4，按道理它用不了gpt3.5的

**Comment by nongmo677** [comment]
实际上不需要你的渠道里面真的能用这个模型...例如我配的智普的渠道，我在里面写gpt-3.5-turbo也可以的
然后在下面重定向就好了
![image](https://github.com/labring/FastGPT/assets/31816449/4bb6519d-2d26-4e98-a582-c51e26479084)

测试结果如下
![image](https://github.com/labring/FastGPT/assets/31816449/c732c956-0a97-4f8b-85d5-c9ebfb45c511)

**Comment by nongmo677** [comment]
> > > > > > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> > > > > 
> > > > > 
> > > > > 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api
> > > > 
> > > > 
> > > > 那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的
> > > 
> > > 
> > > OPEN_AI_API_KEY: 'fastgpt-xxxxxx' OPEN_AI_API_BASE: 'http://xxx:3000/api/v1' 用这个配置文件接入fastgpt后只能调用它默认的gpt3.5
> > 
> > 
> > oneapi里面支持模型重定向，就是说接收到gpt3.5，但是你可以重定向到你定义的glm4，这个功能你探索一下
> 
> oneapi里面里面我就配了两个模型，一个m3e一个glm4，按道理它用不了gpt3.5的

因为你说是默认走gpt3.5，那你就在glm4渠道里配一个gpt3.5的名字，然后重定向，理论上没问题

**Comment by AiLiMeN** [comment]
> > > > > > > 冒昧问一下，你是直接买FastGPT官网给的api-key吗...还是部署开源版本，然后chatgpt-on-wechat调fastgpt发布的api？
> > > > > > 
> > > > > > 
> > > > > > 部署的开源版本，chatgpt-on-wechat调fastgpt发布的api
> > > > > 
> > > > > 
> > > > > 那就部署一个oneapi，fastgpt的配置里接入oneapi 的地址和令牌，chatgpt-on-wechat正常调fastgpt发布的api，这个思路理论上是没问题的
> > > > 
> > > > 
> > > > OPEN_AI_API_KEY: 'fastgpt-xxxxxx' OPEN_AI_API_BASE: 'http://xxx:3000/api/v1' 用这个配置文件接入fastgpt后只能调用它默认的gpt3.5
> > > 
> > > 
> > > oneapi里面支持模型重定向，就是说接收到gpt3.5，但是你可以重定向到你定义的glm4，这个功能你探索一下
> > 
> > 
> > oneapi里面里面我就配了两个模型，一个m3e一个glm4，按道理它用不了gpt3.5的
> 
> 因为你说是默认走gpt3.5，那你就在glm4渠道里配一个gpt3.5的名字，然后重定向，理论上没问题

但是我chatgpt-on-wechat没有连oneapi，连的是fastgpt，fastpgt连的是oneapi,其实我希望是chatgpt-on-wechat是个通道，把微信里的信息传递给fastgpt并把fastgpt的结果返回给chatgpt-on-wechat即可，不需要它单独再调用语言模型

**Comment by c121914yu** [comment]
走什么模型没关系，fastgpt不会关注传入的模型是什么，而是关注你配置了什么模型。
