### ISSUE TITLE
开放一种展示html的方式或者展示图表的方式

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [labring/FastGPT#1220]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X] 我已确认目前没有类似 features
- [X] 我已确认我已升级到最新版本
- [X] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [X] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我们在做一些基于LLM模型转图表展示的应用，基于现在的4.7.1版本，分析用户意图，结合库表结构生成sql我们都有思路，就是最后一步，有了sql怎么展示不知道如何实现，我们在想，如果我们有个外部组件，可以执行sql生成图表，也需要fastgpt可以展示图表，或者可以展示html内容才行。能否提供一个html展示的能力？

**应用场景**
基于fastgpt进行图表分析交互。

**相关示例**

**Comment by boleyn** [comment]
已经具备，只要你输出的内容是以~~~echarts \n echatsJson的就可以生成图表

**Comment by nongmo677** [comment]
携带Markdown的echarts代码块，代码块内写 eCharts 配置数据

![image](https://github.com/labring/FastGPT/assets/31816449/6c81a8eb-78b3-4694-ac2f-8e62ace5847b)

**Comment by WholeWorld-Timothy** [comment]
收到，已经按照格式配置出来了。

**Comment by sdytzjp** [comment]
> 收到，已经按照格式配置出来了。


你好  能否给个具体的参考如何实现

**Comment by sdytzjp** [comment]
> 收到，已经按照格式配置出来了。


你好  能否给个具体的参考如何实现

**Comment by sdytzjp** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 features
> * [x]  我已确认我已升级到最新版本
> * [x]  我已完整查看过项目 README，已确定现有版本无法满足需求
> * [x]  我理解并愿意跟进此 features，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**
> 
> **功能描述** 我们在做一些基于LLM模型转图表展示的应用，基于现在的4.7.1版本，分析用户意图，结合库表结构生成sql我们都有思路，就是最后一步，有了sql怎么展示不知道如何实现，我们在想，如果我们有个外部组件，可以执行sql生成图表，也需要fastgpt可以展示图表，或者可以展示html内容才行。能否提供一个html展示的能力？
> 
> **应用场景** 基于fastgpt进行图表分析交互。
> 
> **相关示例**

请问你是如何实现的分析用户意图转换为sql
