### ISSUE TITLE
fastgpt聊天回复没有引用知识库

### ISSUE THREAD

**Issue by lonngxiang** [labring/FastGPT#1224]
![91df15db1488f716271d1c35a41e173](https://github.com/labring/FastGPT/assets/40717349/d4d261cf-f0be-47ce-8bb9-b7f3e0ea6b04)
一条引用都没收到？
![eea9ef692a027c35d2050e46f939098](https://github.com/labring/FastGPT/assets/40717349/ba52906f-f00e-4c8f-bd75-0f0bc93209d4)
用的m3e召回向量相似度这么低吗？是不是这个相似度值影响的

**Comment by c121914yu** [comment]
是的。而且你的问题看着确实没啥关联

**Comment by JevenZhu** [comment]
我也是这样

**Comment by JevenZhu** [comment]
你什么版本？

**Comment by JevenZhu** [comment]
> ![91df15db1488f716271d1c35a41e173](https://private-user-images.githubusercontent.com/40717349/322757620-d4d261cf-f0be-47ce-8bb9-b7f3e0ea6b04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzE5NjIsIm5iZiI6MTcxMzM3MTY2MiwicGF0aCI6Ii80MDcxNzM0OS8zMjI3NTc2MjAtZDRkMjYxY2YtZjBiZS00N2NlLThiYjktYjdmM2UwZWE2YjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE2MzQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMWRhMDQ0MmQ1NzE0Yzc3ZWU5OGY2MzMyMjAzZTBlNGU3ZDVmNWY2NmMxM2VkYjk1ZGFlZTdhMTZiYTU2OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D8R3sIl_Y8-LNVn11fqG5cxDMpH2IwFJX2kGiGaoad4) 一条引用都没收到？ ![eea9ef692a027c35d2050e46f939098](https://private-user-images.githubusercontent.com/40717349/322757721-ba52906f-f00e-4c8f-bd75-0f0bc93209d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzE5NjIsIm5iZiI6MTcxMzM3MTY2MiwicGF0aCI6Ii80MDcxNzM0OS8zMjI3NTc3MjEtYmE1MjkwNmYtZjAwZS00YzhmLWJkNzUtMGYwYmM5MzIwOWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE2MzQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTdmMDBkNGU1YTFhMTE1Y2JmYmViMGJjNzdhN2U0OTgxOGIyMjNiZGY2YTFjZDg3MWE2MjdiMTAzOWRkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ggWeyGTvsyZrm6Nd2HTL2m9BSAU60jG0eMGFZMUuTls) 用的m3e召回向量相似度这么低吗？是不是这个相似度值影响的

相关度太低了导致的
