### ISSUE TITLE
对话日志删除功能

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1227]
希望支持对话日志删除

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/3339e4e1-8db0-4712-bf81-5ebf628aaab4)
@Essence9999

**Comment by Essence9999** [comment]
![image](https://github.com/labring/FastGPT/assets/66725845/99599861-0684-4018-8362-1bbee8571967)
这种在线对话，能删除。
![image](https://github.com/labring/FastGPT/assets/66725845/0dd7fdf4-af2c-4d18-ba42-554084f85685)
像这种外部分享的，如何删除呢？

**Comment by xiaoToby** [comment]
去数据库删？

**Comment by c121914yu** [comment]
> ![image](https://github.com/labring/FastGPT/assets/66725845/99599861-0684-4018-8362-1bbee8571967)
> 这种在线对话，能删除。
> ![image](https://github.com/labring/FastGPT/assets/66725845/0dd7fdf4-af2c-4d18-ba42-554084f85685)
> 像这种外部分享的，如何删除呢？

目前只有所有者才能删

**Comment by Essence9999** [comment]
> > ![image](https://private-user-images.githubusercontent.com/66725845/323805764-99599861-0684-4018-8362-1bbee8571967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTY2MjMsIm5iZiI6MTcxMzc1NjMyMywicGF0aCI6Ii82NjcyNTg0NS8zMjM4MDU3NjQtOTk1OTk4NjEtMDY4NC00MDE4LTgzNjItMWJiZWU4NTcxOTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzMjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NjAwMmYyZDljZDFjMTA4ZGQ4MTI0YTE2MGVmNmE4YzVjMzIxNGNmN2FiZDhiMDc5YjBjNmM3Y2NmNmE3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ero7bzwikxOK7KzLZIrgwfUHHQzdOTLscNyS5zyDw6k)
> > 这种在线对话，能删除。
> > ![image](https://private-user-images.githubusercontent.com/66725845/323805845-0dd7fdf4-af2c-4d18-ba42-554084f85685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTY2MjMsIm5iZiI6MTcxMzc1NjMyMywicGF0aCI6Ii82NjcyNTg0NS8zMjM4MDU4NDUtMGRkN2ZkZjQtYWYyYy00ZDE4LWJhNDItNTU0MDg0Zjg1Njg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzMjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyODYxMzk4NzFiZjFjZDA5NTQ5ZjBkNTBlODZhNDE1ODkyODZmNWJjN2VlYmY1YjQwYzA5NTA4MTg2YTA0NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJe9RWf7J6rKBNAlzyKaw2dGVihBNplXeIExzMDK52E)
> > 像这种外部分享的，如何删除呢？
> 
> 目前只有所有者才能删

嗯嗯，好的，明白了，外部链接只能通过在外部链接的对话中，删除，感谢
