### ISSUE TITLE
如何更换logo

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1228]
**例行检查**

![image](https://github.com/labring/FastGPT/assets/40045458/11001411-77b2-4417-b4fb-ddf5f5b469b0)

如图所说，在docker容器中没有找到相关目录
还想问问，能不能更换如下图红框所示的头像

![image](https://github.com/labring/FastGPT/assets/40045458/82dfc841-1dc0-4b76-95f7-7a843d214ede)

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by zhanghxiao** [comment]
在改应用名字的时候，点一下就能改
![image](https://github.com/labring/FastGPT/assets/137479165/5dde04dc-e83b-4c58-9620-86dbf88ef37d)

**Comment by zanderjiang** [comment]
> 在改应用名字的时候，点一下就能改 ![image](https://private-user-images.githubusercontent.com/137479165/323151437-5dde04dc-e83b-4c58-9620-86dbf88ef37d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTU5MDksIm5iZiI6MTcyMjQ5NTYwOSwicGF0aCI6Ii8xMzc0NzkxNjUvMzIzMTUxNDM3LTVkZGUwNGRjLWU4M2ItNGM1OC05NjIwLTg2ZGJmODhlZjM3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwNzAwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDViZDQ4MjQyZGQyODFmNmFhY2IyN2IzZDA3MjhiOTFhYWUwNTBlZGQzZmM1YmM0N2EwNGYwNGM1YmJmODEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ROMe8EXHgxL7m4U4DSmgncgYrjvrAPm7Gv-mO09HhBY)

请问有限制的格式吗？上传了一个PNG没有反应

**Comment by doraqiqi** [comment]
请问问题解决了吗，我也是点击上传了没反应

**Comment by ste0815** [comment]
对图片格式有要求吗？我也尝试点击上传了没反应。
