### ISSUE TITLE
本地代码运行，登录，创建应用，编排都正常，发起提问报错404

### ISSUE THREAD

**Issue by Ambitionon** [labring/FastGPT#1229]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.7

**问题描述**
本地代码运行，登录，创建应用，编排都正常，发起提问报错404
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/24786037/1871190f-5936-4659-80fa-b5dd4f4ecb83)

**Comment by c121914yu** [comment]
api key 问题

**Comment by hang925** [comment]
你好 问题解决了吗 我也遇到这个问题

**Comment by MarkYangGit** [comment]
我也遇到了

**Comment by mstestlp** [comment]
我也遇到了,有人解决吗

**Comment by MarkYangGit** [comment]
那个 docker-compose.yml
里 apibase 配置地址端口改成 3001
