### ISSUE TITLE
请问有计划接入ChatGLM2

### ISSUE THREAD

**Issue by 0x12woo** [labring/FastGPT#123]
请问有计划接入ChatGLM2

**Comment by pepsigold** [comment]
需求+1 感谢分享这么好的应用！
最好是支持GLM2本地模型，谢谢。

**Comment by c121914yu** [comment]
可以通过oneapi简介接入

**Comment by sunk926** [comment]
刚刚看了  可以接入了,就是不知道能不能像 openai那样训练了...

**Comment by pepsigold** [comment]
> 可以通过oneapi间接接入

那真是好消息

**Comment by pepsigold** [comment]
> 刚刚看了  可以接入了,就是不知道能不能像 openai那样训练了...

微调啊？

**Comment by 0x12woo** [comment]
可以完全不用chatGPT吗,全部使用ChatGLM2方式,包括问答对的生成和回复问题?

**Comment by c121914yu** [comment]
> 可以完全不用chatGPT吗,全部使用ChatGLM2方式,包括问答对的生成和回复问题? @c121914yu 

新版的可以。已经把qa生成模型和向量模型抽出来配置，大概会在4.1版本实现

**Comment by forcemeter** [comment]
>  新版的可以。已经把qa生成模型和向量模型抽出来配置，大概会在4.1版本实现

@c121914yu  这个可以早点释放出来吗
