### ISSUE TITLE
pptx文件无法正常解析

### ISSUE THREAD

**Issue by zhangwei8607** [labring/FastGPT#1234]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1

**问题描述**
上传ppt文件报错
**复现步骤**
随便上传一个ppt文件
**预期结果**
可以正常解析成功ppt文件
**相关截图**
![image](https://github.com/labring/FastGPT/assets/3302139/957db6b6-8e5b-44f0-8a0a-dcfcd51e5c56)

**Comment by c121914yu** [comment]
编码不支持，得改下编码。通用编码: utf8

**Comment by c121914yu** [comment]
新版增加了 utf8 兜底，一定程度上减少报错。
