### ISSUE TITLE
上传知识知识库，第一次没报错，后续超过一定大小都报错

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1235]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7.1
私有部署版本, 具体版本号: 4.7.1

**问题描述**
上传知识知识库，第一次没报错，后续超过一定大小都报错，看着是mongo的问题
**复现步骤**

**预期结果**
希望可以正常上传20M以上的文件内容
**相关截图**
![image](https://github.com/labring/FastGPT/assets/50564015/e2799b94-b0c8-48c8-903e-fbf4884305b5)
![Uploading image.png…]()

**Comment by lxb0425** [comment]
那不是一千多万行 是17M左右，  几百kb或者几M的都可以

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/0bc99d21-77b8-43da-8128-ebed44a0cf6d)
27M csvmei没遇到问题？
![image](https://github.com/labring/FastGPT/assets/50446880/a2e9bfa5-2ee5-4061-936f-a0c5914b0e48)

**Comment by lxb0425** [comment]
那我这个真是见鬼了啊 之前也传上去过一个200多M和20几M的 现在就不行了
![image](https://github.com/labring/FastGPT/assets/50564015/1f18665e-4be4-4e6d-b85d-6c269ebadf49)
![image](https://github.com/labring/FastGPT/assets/50564015/a9131427-3f33-45ae-9f01-5c6030d610e3)

**Comment by c121914yu** [comment]
> 那我这个真是见鬼了啊 之前也传上去过一个200多M和20几M的 现在就不行了
> ![image](https://github.com/labring/FastGPT/assets/50564015/1f18665e-4be4-4e6d-b85d-6c269ebadf49)
> ![image](https://github.com/labring/FastGPT/assets/50564015/a9131427-3f33-45ae-9f01-5c6030d610e3)
> 

可能得 debug 或者看看日志，具体是哪个语句。

**Comment by lxb0425** [comment]
fastgpt 报的的错误 mongo没报错 感觉看不出啥
![image](https://github.com/labring/FastGPT/assets/50564015/409474ba-049d-482e-8ca1-87d896ab8722)

**Comment by c121914yu** [comment]
> fastgpt 报的的错误 mongo没报错 感觉看不出啥
> ![image](https://github.com/labring/FastGPT/assets/50564015/409474ba-049d-482e-8ca1-87d896ab8722)
> 

能发下数据集？迟点本地试试

**Comment by lxb0425** [comment]
可以的 而且我刚试了下 txt也是这个错  感觉都没到mongo
[Uploading drug的副本.csv…]()

限制上传25M 我删掉了几条

**Comment by c121914yu** [comment]
> 可以的 而且我刚试了下 txt也是这个错 感觉都没到mongo 在上传阶段就报了这个错 [drug的副本.csv](https://github.com/labring/FastGPT/files/15023861/drug.csv)
> 
> 限制上传25M 我删掉了几条 问的gpt ![image](https://private-user-images.githubusercontent.com/50564015/323577079-3873ede8-b30a-4712-bfdc-e0bbe67e935a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDIxMTMsIm5iZiI6MTcxMzQ0MTgxMywicGF0aCI6Ii81MDU2NDAxNS8zMjM1NzcwNzktMzg3M2VkZTgtYjMwYS00NzEyLWJmZGMtZTBiYmU2N2U5MzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEyMDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYzNhZTNiMWM4MmUwZjA2MTIyYWRhMmM0YWVmMzJhMGNmZjMxMmNmZTQzM2I4ZTE0Njc1MjcwNDJjNDIzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YNhcy5FqzWsJUCLuidDTMyOXaJ72zhNU00OLl0ScSik)

csv 表格导入的方式？还是分段导入

**Comment by lxb0425** [comment]
![image](https://github.com/labring/FastGPT/assets/50564015/e8a93d85-d0e5-4dd1-89d8-c55c201f1f58)
![image](https://github.com/labring/FastGPT/assets/50564015/a3b306e2-c82c-4add-bae7-27979f645716)
这lian两种都试过 然后看了下mongo数据库 文件已经传上去了 好像是解析的问题
![image](https://github.com/labring/FastGPT/assets/50564015/ba552fe6-bcec-425d-bcce-fca0caeff6d3)

**Comment by lxb0425** [comment]
第一步是完成的吧
![image](https://github.com/labring/FastGPT/assets/50564015/9468faaf-363d-493f-bdd8-18b26439b7c9)
