### ISSUE TITLE
应用调用之后返回的字符串希望能够流失输出

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1237]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [xx] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本** 4.7.1

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
编排HTTP请求后返回的字符串，全部瞬间出来了，尝试加了AI对话，但是字符串内容会发生变化
**复现步骤**

**预期结果**
希望按照流式输出
**相关截图**
![image](https://github.com/labring/FastGPT/assets/50564015/981a84b7-91c6-4891-9efc-d106d32309a5)

**Comment by c121914yu** [comment]
指定回复会用于回复图片等内容，流的话会很丑。
