### ISSUE TITLE
本地docker部署fastgpt，如果修改docker compose.yml文件配置，保证数据卷能在wsl环境下被正确加载

### ISSUE THREAD

**Issue by Austinlyon-ops** [labring/FastGPT#1238]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.7.1

**问题描述**
安装wsl和docker的时候，教程里有提到这一步，启动docker默认用的是wsl，为了更好的兼容性。但是我发现每次docker默认用wsl启动的时候，数据卷都不会正常加载，也就是出现了知识库和应用设置丢失的情况。如果我改成powershell的命令行来启动docker，这个数据卷就可以正常加载了，配置就会被保留。出现这个问题的原因可能是docker compose.yml文件里面的容器（比如fastgpt容器）的volume的路径配置可能跟wsl不兼容，但是我不知道怎么改这个文件配置。如果我不改变默认设置，也就是默认每次docker自己启动的时候都是用wsl来启动，那就会导致我每次都要用powershell重新加载一次docker compose.yml文件才能正常。显然这是不科学的方式。合理的方式应该是要改docker compose.yml文件配置去适应兼容wsl环境。
**复现步骤**

**预期结果**

**相关截图**
<img width="1280" alt="67d49596049ccb4ac90636bc3eed9be" src="https://github.com/labring/FastGPT/assets/135449931/2c11f499-bb7f-44e6-b2ad-27953f68ebd2">

**Comment by c121914yu** [comment]
没听说过 yml 适配 docker
