### ISSUE TITLE
知识库问答相关问题

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1240]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
![image](https://github.com/labring/FastGPT/assets/40045458/4678cbe6-08f6-4238-8bfd-438253c5a8f5)
如图所示，不想要红框内的内容。是需要怎么调整配置
**复现步骤**

**预期结果**

**相关截图**

**Comment by nongmo677** [comment]
把AI对话的`触发器`连接到知识库搜索的`搜索结果不为空`上

**Comment by xiaoToby** [comment]
> 把AI对话的`触发器`连接到知识库搜索的`搜索结果不为空`上

Yes!

**Comment by xiaoToby** [comment]
还有一个问题。就是关于搜索模式的选择
例如我选择了混合检索+结果重排，这是效果截图
![image](https://github.com/labring/FastGPT/assets/40045458/fc227131-a249-4345-b8fd-49a8f28a014a)
我选择语义检索+结果重排，这是效果截图
![image](https://github.com/labring/FastGPT/assets/40045458/10cf952c-ad6c-41ec-b4bf-5c930092ae2c)
选择全文检索+结果重排，效果截图：
![image](https://github.com/labring/FastGPT/assets/40045458/08f251c0-899e-49fe-a730-16387ffa4733)
选择全文检索，不选结果重排，效果截图：
![image](https://github.com/labring/FastGPT/assets/40045458/0ebb7e29-82f9-403c-82e2-faea82ea0b05)
只有选择语义检索，不选结果重排。才能得到自己想要的效果
![image](https://github.com/labring/FastGPT/assets/40045458/6e75d2aa-e8a2-4542-8df0-8c3d02369267)

我的认知是：搜索效果来说： 混合》全文》语义 ； 而结果重排是一种加持，提高搜索效果。
但如何设定，才能是如果知识库中没有回答问题(例如：介绍库里)的知识，那么回复固定的回复；如果有能回答问题(例如什么是线程)的知识，知识库搜索效果是最优的
@nongmo677 @c121914yu

**Comment by c121914yu** [comment]
> 还有一个问题。就是关于搜索模式的选择
> **例如我选择了混合检索+结果重排，这是效果截图**
> ![image](https://github.com/labring/FastGPT/assets/40045458/fc227131-a249-4345-b8fd-49a8f28a014a)
> **我选择语义检索+结果重排，这是效果截图**
> ![image](https://github.com/labring/FastGPT/assets/40045458/10cf952c-ad6c-41ec-b4bf-5c930092ae2c)
> **选择全文检索+结果重排，效果截图：**
> ![image](https://github.com/labring/FastGPT/assets/40045458/08f251c0-899e-49fe-a730-16387ffa4733)
> **选择全文检索，不选结果重排，效果截图：**
> ![image](https://github.com/labring/FastGPT/assets/40045458/0ebb7e29-82f9-403c-82e2-faea82ea0b05)
> **只有选择语义检索，不选结果重排。才能得到自己想要的效果**
> ![image](https://github.com/labring/FastGPT/assets/40045458/6e75d2aa-e8a2-4542-8df0-8c3d02369267)
> 
> 我的认知是：搜索效果来说： 混合》全文》语义 ； 而结果重排是一种加持，提高搜索效果。
> 但如何设定，才能是如果知识库中没有回答问题(例如：介绍库里)的知识，那么回复固定的回复；如果有能回答问题(例如什么是线程)的知识，知识库搜索效果是最优的
> @nongmo677 @c121914yu 
> 

没有最优。整个链路都会影响最终结果，你只能一个个调，选择合适的数据格式，索引结构以及检索方式
