### ISSUE TITLE
api调用，同样的问题，答案被截断

### ISSUE THREAD

**Issue by HelloEveryonehh** [labring/FastGPT#1242]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
调用fastgpt的api进行对话，在对话日志中查询，同样的问题，第一次回答被截断，第二次正常
请问可能问题出在哪里了？
**相关截图**
![image](https://github.com/labring/FastGPT/assets/110333012/bf66c393-fa67-418b-9e77-1056cb81c14b)

**Comment by c121914yu** [comment]
api 问题吧，看到响应说明接口正常结束了。

**Comment by HelloEveryonehh** [comment]
> api 问题吧，看到响应说明接口正常结束了。

您好，您的意思是对话模型的API的问题吗，我确实在公有云版本配置了我自己的one-api。

**Comment by c121914yu** [comment]
> > api 问题吧，看到响应说明接口正常结束了。
> 
> 您好，您的意思是对话模型的API的问题吗，我确实在公有云版本配置了我自己的one-api。

能看到下面的标签，说明接口正常结束了，没有任何报错。。
被截断估计是接口直接就断了。
