### ISSUE TITLE
调用ollama嵌入模型报404

### ISSUE THREAD

**Issue by ns500** [labring/FastGPT#1244]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**：v4.7

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: v4.7

**问题描述**
调用ollama支持的3个嵌入模型，上传的文件一直在索引中，ollama日志报404找不到模型，不知道模型名称是不是写错了，调用chat qwen模型没有任何问题。
**复现步骤**
知识库使用ollama嵌入模型，chat模型使用ollama qwen，单独使用聊天应用调用qwen模型没有问题。
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/16814164/b64faa9d-bc4e-49e6-993f-c4b61ef00cfe)

![image](https://github.com/labring/FastGPT/assets/16814164/0dbeb404-e301-4384-910b-04d16a16be72)

![image](https://github.com/labring/FastGPT/assets/16814164/1faba9f2-70d7-4c39-8f73-fbf03102c373)
![image](https://github.com/labring/FastGPT/assets/16814164/90352e09-5f6f-4707-9bc6-8bc8aa3ccd04)
![image](https://github.com/labring/FastGPT/assets/16814164/f47fbd93-dd42-4a6d-92c2-b7ea19aeb08f)
![image](https://github.com/labring/FastGPT/assets/16814164/833206f7-346e-4d16-8143-5e861165f67c)
![image](https://github.com/labring/FastGPT/assets/16814164/146bd715-6d61-489d-898f-2f1dcea48337)

**Comment by nongmo677** [comment]
我这边测试没有问题

![image](https://github.com/labring/FastGPT/assets/31816449/8477095c-4218-4744-9010-c0434c6e69f4)

![image](https://github.com/labring/FastGPT/assets/31816449/8473f00a-f502-4b6b-ac67-31fc2ff67ebb)

![image](https://github.com/labring/FastGPT/assets/31816449/64e70727-5c54-42a1-9d73-6d717b573969)

建议请更新oneapi至最新版本，oneapi有个过渡版本是只包含ollama /api/chat路由而没用实现embeddings路由的，有可能导致没用转发至/v1/embeddings

oneapi最新版本已加入

https://github.com/songquanpeng/one-api/blob/3d149fedf45472eff92910324974c762fc37dad6/relay/adaptor/ollama/adaptor.go#L27
