### ISSUE TITLE
用DOCKER-ReRank 接入(私有部署) 不能用

### ISSUE THREAD

**Issue by cq134cq** [labring/FastGPT#1248]
![541AFC90-237F-4028-8E6C-FA7F229F5BE0](https://github.com/labring/FastGPT/assets/95132993/60542fcc-a084-4d84-a9eb-81e2bfb0a719)
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 
docker
**问题描述**
不能用ReRank，说出错，请问那里问题
**复现步骤**

**预期结果**

**相关截图**
![D7B0C2DB-86ED-48c2-85D6-5A47AA0AC46F](https://github.com/labring/FastGPT/assets/95132993/62742eba-d268-43d6-bc16-4d186adba88c)
![27755FE2-CBCE-4803-BF2A-639F211021B7](https://github.com/labring/FastGPT/assets/95132993/5aa0b2e1-105b-4ab0-ac97-8197b7ebe74f)
![6402C21E-9501-4885-A9E4-9C120D8CB39E](https://github.com/labring/FastGPT/assets/95132993/41257e44-c161-4229-a900-daf8338566ef)

**Comment by boleyn** [comment]
确定不是你自己的key不对？我这边就可以用啊，最新版本的

**Comment by c121914yu** [comment]
看着 key 不对

**Comment by cq134cq** [comment]
> 确定不是你自己的key不对？我这边就可以用啊，最新版本的

"requestAuth": "安全凭证，已自动补 Bearer"这个在那里找？

**Comment by c121914yu** [comment]
> > 确定不是你自己的key不对？我这边就可以用啊，最新版本的
> 
> "requestAuth": "安全凭证，已自动补 Bearer"这个在那里找？

部署时候自己填的。

**Comment by cq134cq** [comment]
> > > 确定不是你自己的key不对？我这边就可以用啊，最新版本的
> > 
> > 
> > "requestAuth": "安全凭证，已自动补 Bearer"这个在那里找？
> 
> 部署时候自己填的。
部署时没有KEY
docker run -d --name reranker -p 6006:6006 -e ACCESS_TOKEN=mytoken --gpus all registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1

**Comment by c121914yu** [comment]
> > > > 确定不是你自己的key不对？我这边就可以用啊，最新版本的
> > > 
> > > 
> > > "requestAuth": "安全凭证，已自动补 Bearer"这个在那里找？
> > 
> > 部署时候自己填的。
> 部署时没有KEY
> docker run -d --name reranker -p 6006:6006 -e ACCESS_TOKEN=mytoken --gpus all registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1
> 

😅你自己都列出来了，mytoken，建议仔细看文档

**Comment by cq134cq** [comment]
> > > > > 确定不是你自己的key不对？我这边就可以用啊，最新版本的
> > > > 
> > > > 
> > > > "requestAuth": "安全凭证，已自动补 Bearer"这个在那里找？
> > > 
> > > 
> > > 部署时候自己填的。
> > > 部署时没有KEY
> > > docker run -d --name reranker -p 6006:6006 -e ACCESS_TOKEN=mytoken --gpus all registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1
> 
> 😅你自己都列出来了，mytoken，建议仔细看文档

谢谢

**Comment by cq134cq** [comment]
> > > > > 确定不是你自己的key不对？我这边就可以用啊，最新版本的
> > > > 
> > > > 
> > > > "requestAuth": "安全凭证，已自动补 Bearer"这个在那里找？
> > > 
> > > 
> > > 部署时候自己填的。
> > > 部署时没有KEY
> > > docker run -d --name reranker -p 6006:6006 -e ACCESS_TOKEN=mytoken --gpus all registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1
> 
> 😅你自己都列出来了，mytoken，建议仔细看文档

rerank error: AxiosError: timeout of 30000ms exceeded
    at RedirectableRequest.handleRequestTimeout (file:///app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/adapters/http.js:647:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
    at Axios.request (file:///app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/core/Axios.js:45:41)
    at async q (/app/projects/app/.next/server/chunks/59120.js:85:3465)
    at async g (/app/projects/app/.next/server/chunks/59120.js:86:957)
    at async /app/projects/app/.next/server/pages/api/core/dataset/searchTest.js:1:2983 {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 30000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'Cache-Control': 'no-cache',
      Authorization: 'Bearer mytoken',
      'User-Agent': 'axios/1.6.8',
      'Content-Length': '61742',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://2a1826918fd7:3000',
    url: 'http://10.0.100.190:6006/v1/rerank',
    method: 'post',
请问这个是时间太短？

**Comment by xiaoToby** [comment]
> > > > > > 确定不是你自己的key不对？我这边就可以用啊，最新版本的
> > > > > 
> > > > > 
> > > > > "requestAuth": "安全凭证，已自动补 Bearer"这个在那里找？
> > > > 
> > > > 
> > > > 部署时候自己填的。
> > > > 部署时没有KEY
> > > > docker run -d --name reranker -p 6006:6006 -e ACCESS_TOKEN=mytoken --gpus all registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.1
> > 
> > 
> > 😅你自己都列出来了，mytoken，建议仔细看文档
> 
> rerank error: AxiosError: timeout of 30000ms exceeded at RedirectableRequest.handleRequestTimeout (file:///app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/adapters/http.js:647:16) at RedirectableRequest.emit (node:events:514:28) at Timeout. (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:210:12) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7) at Axios.request (file:///app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/core/Axios.js:45:41) at async q (/app/projects/app/.next/server/chunks/59120.js:85:3465) at async g (/app/projects/app/.next/server/chunks/59120.js:86:957) at async /app/projects/app/.next/server/pages/api/core/dataset/searchTest.js:1:2983 { code: 'ECONNABORTED', config: { transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }, adapter: [ 'xhr', 'http' ], transformRequest: [ [Function: transformRequest] ], transformResponse: [ [Function: transformResponse] ], timeout: 30000, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, env: { FormData: [Function], Blob: [class Blob] }, validateStatus: [Function: validateStatus], headers: Object [AxiosHeaders] { Accept: 'application/json, text/plain, _/_', 'Content-Type': 'application/json', 'Cache-Control': 'no-cache', Authorization: 'Bearer mytoken', 'User-Agent': 'axios/1.6.8', 'Content-Length': '61742', 'Accept-Encoding': 'gzip, compress, deflate, br' }, baseURL: 'http://2a1826918fd7:3000', url: 'http://10.0.100.190:6006/v1/rerank', method: 'post', 请问这个是时间太短？

@c121914yu 也是报的rerank error: AxiosError: timeout of 30000ms exceeded
