### ISSUE TITLE
工具调用报错：unknown_parameter Unknown parameter: 'messages[2].tool_calls[0].index'.

### ISSUE THREAD

**Issue by vary** [labring/FastGPT#1253]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1

**问题描述**
使用工具调用时报错：unknown_parameter Unknown parameter: 'messages[2].tool_calls[0].index'.看起来是OpenAI的接口在tool_calls中不支持index字段
**复现步骤**
使用工具调用连接获取当前时间，如图所示，然后问几点了，就会报错，刚开始使用oneapi报错，切换成OpenAI官方的地址后也报同样的错误
**预期结果**
能够正常使用工具调用
**相关截图**
<img width="1290" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/b34b97e0-ed0b-4c3a-b36b-0bf2038ca80c">

**Comment by hd19820806** [comment]
mark 同样问题  而且发现3.5的api比4.0的更不容易报错，但是回复质量太堪忧

**Comment by vary** [comment]
是的，最新的gpt-4-turbo出问题的概率最大

**Comment by c121914yu** [comment]
> 是的，最新的gpt-4-turbo出问题的概率最大

gpt4，直接用官方接口也报错，不知道为啥。

**Comment by vary** [comment]
<img width="615" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/a9c42211-ac4f-4f13-9798-2cc4a9781741">
tool_calls返回里有index，但是根据报错提示感觉是在请求的时候不让带index

> > 是的，最新的gpt-4-turbo出问题的概率最大
> 
> gpt4，直接用官方接口也报错，不知道为啥。

**Comment by vary** [comment]
https://community.openai.com/t/gpt-4-turbo-model-function-call-doesnt-work/712218
<img width="788" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/402fc4f8-271f-4d5c-9153-1aaec072bced">
看起来是OpenAI修改了校验的逻辑

**Comment by c121914yu** [comment]
> <img width="615" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/a9c42211-ac4f-4f13-9798-2cc4a9781741">
> tool_calls返回里有index，但是根据报错提示感觉是在请求的时候不让带index
> 
> > > 是的，最新的gpt-4-turbo出问题的概率最大
> > 
> > gpt4，直接用官方接口也报错，不知道为啥。
> 
> 

收到，后面做个优化😂这文档没更新头大
