### ISSUE TITLE
能否在url中填写填写参数转化为全局变量

### ISSUE THREAD

**Issue by Byelliot** [labring/FastGPT#1255]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
- 在url中填写填写参数转化为全局变量

**应用场景**
- 如网站客服等需要知道账号的前提下才能提供服务

**相关示例**
![微信截图_20240420012444](https://github.com/labring/FastGPT/assets/39994633/92cd2506-cb74-49dd-b3b5-334d575f9a02)

**Comment by c121914yu** [comment]
已经支持了。
全局变量有外部传入类型
