### ISSUE TITLE
undefined 当前分组 default 下对于模型 gpt-3.5-turbo 无可用渠道

### ISSUE THREAD

**Issue by aiyouwoqudi** [labring/FastGPT#1256]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的(账号密码是正确且可使用的)
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
使用知识库问答时，提示：undefined 当前分组 default 下对于模型 gpt-3.5-turbo 无可用渠道 
**复现步骤**
按照操作手册完成部署之后，新建知识库、新建应用，并在应用内关联知识库，在对话中使用知识库后，出现该问题
**预期结果**
可以正常使用
**相关截图**
<img width="295" alt="c6eb861826768c29ae2a96a1b4a9936" src="https://github.com/labring/FastGPT/assets/53113729/be0c24c9-cc82-4a24-ae4d-7455255341f5">

**Comment by Thinking80s** [comment]
同样错误提示：undefined 当前分组 default 下对于模型 gpt-3.5-turbo 无可用渠道

**Comment by Cartride** [comment]
现在加入知识库，勾选模型没用，只会自动用模型列表第一个

**Comment by c121914yu** [comment]
> 对于

实测都有用

**Comment by ygai002** [comment]
> > 对于
> 
> 实测都有用。自己没改对应问题优化模型而已。
@c121914yu   可否分享一下这个模型的配置文件？  是从config.json改吗 ？

**Comment by c121914yu** [comment]
> > > 对于
> > 
> > 
> > 实测都有用。自己没改对应问题优化模型而已。
> > @c121914yu   可否分享一下这个模型的配置文件？  是从config.json改吗 ？

页面上有选，而且没有的模型就别放配置文件，找不到模型会默认用第一个，然后你第一个模型又用不了~

**Comment by ygai002** [comment]
> > > > 对于
> > > 
> > > 
> > > 实测都有用。自己没改对应问题优化模型而已。
> > > @c121914yu   可否分享一下这个模型的配置文件？  是从config.json改吗 ？
> 
> 页面上有选，而且没有的模型就别放配置文件，找不到模型会默认用第一个，然后你第一个模型又用不了~

![image](https://github.com/labring/FastGPT/assets/144642992/0e86c2e4-e9e6-4e96-8e8a-37c4da35cc5a)
这部分的内容可否替换使用 one api中的内容呢 ？ 有点不太明白这个调用机制

**Comment by c121914yu** [comment]
> > > > > 对于
> > > > 
> > > > 
> > > > 实测都有用。自己没改对应问题优化模型而已。
> > > > @c121914yu   可否分享一下这个模型的配置文件？  是从config.json改吗 ？
> > 
> > 
> > 页面上有选，而且没有的模型就别放配置文件，找不到模型会默认用第一个，然后你第一个模型又用不了~
> 
> ![image](https://private-user-images.githubusercontent.com/144642992/342595631-0e86c2e4-e9e6-4e96-8e8a-37c4da35cc5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTQ3MDMsIm5iZiI6MTcxOTI5NDQwMywicGF0aCI6Ii8xNDQ2NDI5OTIvMzQyNTk1NjMxLTBlODZjMmU0LWU5ZTYtNGU5Ni04ZThhLTM3YzRkYTM1Y2M1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwNTQ2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDU4MzdjMDYxMDU2ODFkMWMyZTQ2ZWVlMzBkMzllOTU1NWFiOTJiN2I5OGU1OTI1ZDA1ZTVlNDgwMzQ0OWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9L-6VOIeM3Onk5px11zK4Q6sojqfS_2qZs5tys1tYE4) 这部分的内容可否替换使用 one api中的内容呢 ？ 有点不太明白这个调用机制

文档有说明

**Comment by kid20210528** [comment]
![1719471162450](https://github.com/labring/FastGPT/assets/84962923/99a382c8-90ab-44f6-9b21-34b0be78245f)
![1719471128591](https://github.com/labring/FastGPT/assets/84962923/1f493422-97f3-407a-afd2-a1df630a1d35)
![1719471106571](https://github.com/labring/FastGPT/assets/84962923/4d145cc3-0ae4-4e05-9bcb-82771db7070e)
![1719471242352](https://github.com/labring/FastGPT/assets/84962923/8bcee3b0-163a-42de-8ebc-ca893ee13644)
这问题出在哪里呢？没搞懂，该有的配置都有了，有大神指导一下吗

**Comment by cmdhh** [comment]
> ![1719471162450](https://private-user-images.githubusercontent.com/84962923/343662176-99a382c8-90ab-44f6-9b21-34b0be78245f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDQwODcsIm5iZiI6MTcyNDIwMzc4NywicGF0aCI6Ii84NDk2MjkyMy8zNDM2NjIxNzYtOTlhMzgyYzgtOTBhYi00NGY2LTliMjEtMzRiMGJlNzgyNDVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAxMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMDU2OGE0NmZiYzU5ZDJmNGIyYzc5Mzk3OGUyN2YwNWY5NGVkNjkyYTZmNzA5NWViYjMxMjA0NjJjZjk5NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rPDGK5TLNz7pB4JaVNtCl7vpBf4SvxJmidJEdv6eDI) ![1719471128591](https://private-user-images.githubusercontent.com/84962923/343662189-1f493422-97f3-407a-afd2-a1df630a1d35.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDQwODcsIm5iZiI6MTcyNDIwMzc4NywicGF0aCI6Ii84NDk2MjkyMy8zNDM2NjIxODktMWY0OTM0MjItOTdmMy00MDdhLWFmZDItYTFkZjYzMGExZDM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAxMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMjY2N2M4MTI4MWZjZWEzM2EzMzg5YWU2ZjkzODhhMDNkNWYzZDhmY2VkZmU2NmE0ZTFkMmMzZDZjYWFjZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwJN3wI18ZNoz_AJzgEqcB3FaxEmPqX2kqh1yIgDQbI) ![1719471106571](https://private-user-images.githubusercontent.com/84962923/343662198-4d145cc3-0ae4-4e05-9bcb-82771db7070e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDQwODcsIm5iZiI6MTcyNDIwMzc4NywicGF0aCI6Ii84NDk2MjkyMy8zNDM2NjIxOTgtNGQxNDVjYzMtMGFlNC00ZTA1LTliY2ItODI3NzFkYjcwNzBlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAxMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNmE2MzdhNTVmMjBmNzBmNjM4M2Q1Y2U0OTg1NDQxZTI2NzdlMmY0MWI4MjcyNmY4NDU4N2Q0MGIzNTE4OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vnNsKe3cmJ1grsyb_WU3ClcZBZ2W1prR4zwaNpf2tNc) ![1719471242352](https://private-user-images.githubusercontent.com/84962923/343662441-8bcee3b0-163a-42de-8ebc-ca893ee13644.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDQwODcsIm5iZiI6MTcyNDIwMzc4NywicGF0aCI6Ii84NDk2MjkyMy8zNDM2NjI0NDEtOGJjZWUzYjAtMTYzYS00MmRlLThlYmMtY2E4OTNlZTEzNjQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAxMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYTNmMjUxN2ExZDI3ZjM4ZjlmMjZhNTI4MTU4Zjg2MDA2ZjI1MzFmODc3ZWI4MTQzYmJjMDRiNjlkNDdhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tzs6RpMssZLfYLHbcGb1p9Vj5IHF-tLDTkV1N5A8zpM) 这问题出在哪里呢？没搞懂，该有的配置都有了，有大神指导一下吗

解决了吗，我也是这样

**Comment by 17643130087** [comment]
在你的应用里--选择数据库 ,然后右上角有个 小字选项叫参数, 点进去 ,  上面三个框,选问题优化, 关掉就行了
