### ISSUE TITLE
403 该令牌无权使用模型：m3e

### ISSUE THREAD

**Issue by hhhhhx2020** [labring/FastGPT#1258]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X ] 私有部署版本, 具体版本号: 

**问题描述**
本机IP情况：
![图片](https://github.com/labring/FastGPT/assets/159286704/206273f3-245b-4456-bbcc-246e0ea7cde9)
M3E部署情况：
![图片](https://github.com/labring/FastGPT/assets/159286704/29ddce21-22f2-4b15-8536-b878c428e6b9)
oneapi信息情况：
![图片](https://github.com/labring/FastGPT/assets/159286704/cfa01c5a-27bc-44c3-bbb1-fbe1527fca6c)
使用知识库出现报错：
![图片](https://github.com/labring/FastGPT/assets/159286704/58994f0a-bf92-42cf-ac48-e5aaa890a6d6)
查看日志发现：oneapi报错
![图片](https://github.com/labring/FastGPT/assets/159286704/cf004fbd-60d7-47f7-a6cc-6194559f42e5)
fastgpt报错：
![图片](https://github.com/labring/FastGPT/assets/159286704/f0ceeabc-3f04-4b8d-b739-d7af17e56af0)
请问是啥原因

**Comment by nigo81** [comment]
oneapi更新到v0.6.5版本，我安装时也出现这个问题。使用之前版本问题解决：image: ghcr.io/songquanpeng/one-api:v0.6.4

**Comment by Songzimeng** [comment]
我现在的版本是v0.6.8-alpha 还是有这个问题

**Comment by c121914yu** [comment]
> oneapi更新到v0.6.5版本，我安装时也出现这个问题。使用之前版本问题解决：image: ghcr.io/songquanpeng/one-api:v0.6.4

因为你设置了令牌模型范围，不设置就好了

**Comment by ahajacky** [comment]
> oneapi更新到v0.6.5版本，我安装时也出现这个问题。使用之前版本问题解决：image: ghcr.io/songquanpeng/one-api:v0.6.4

换了版本还是一样的问题

**Comment by rizi960** [comment]
> > oneapi更新到v0.6.5版本，我安装时也出现这个问题。使用之前版本问题解决：image: ghcr.io/songquanpeng/one-api:v0.6.4
> 
> 因为你设置了令牌模型范围，不设置就好了

这个是对的

**Comment by c20liu** [comment]
fastgpt4.8.5 + oneapi 0.6.6 版本，oneapi 配置了1个令牌（没有限制模型），2个渠道（qwen2, m3e）, oneapi测试m3e，日志返回 "POST /v1/chat/completions HTTP/1.1" 404 Not Found

fastgpt可以正确使用qwen模型进行问答，但是配置了知识库，搜索测试返回  该令牌无权使用模型：m3e (request id: 2024072108205231713643448078500)

搞了好久，不知道哪里出了问题

**Comment by mofeiyanma** [comment]
> > oneapi更新到v0.6.5版本，我安装时也出现这个问题。使用之前版本问题解决：image: ghcr.io/songquanpeng/one-api:v0.6.4
> 
> 因为你设置了令牌模型范围，不设置就好了

试过了，还是该令牌无权使用模型的错误

**Comment by sunroad** [comment]
可能是使用那边的model名称和oneapi里面的model名称没有一直导致的。我用fastgpt的时候遇到过。

**Comment by bxrjmfh** [comment]
> 可能是使用那边的model名称和oneapi里面的model名称没有一直导致的。我用fastgpt的时候遇到过。

可以检查是否是模型名称后有多余的空格
