### ISSUE TITLE
v4.7.1聊天的语音输入转文本好像点击按钮没反应，不能将语音输入正常转换成文本

### ISSUE THREAD

**Issue by sulian2018** [labring/FastGPT#1259]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
v4.7.1聊天的语音输入转文本好像点击按钮没反应，不能将语音输入正常转换成文本
**复现步骤**
1.v4.7.1版本源码，部署后
2.进入聊天页面，点语音输入按钮，点击没反应
**预期结果**
将语音输入正常转换成文本
**相关截图**

**Comment by lijiajun1997** [comment]
需要你的api里有这个模型whisper-1，或者你部署其他语音识别模型然后接入oneapi
![image](https://github.com/labring/FastGPT/assets/156336589/d7a12c24-e2b0-4f73-9d97-b6a19beed7a1)

**Comment by c121914yu** [comment]
首先要支持 https

**Comment by boleyn** [comment]
苹果手机识别效果很差，初步判断是录音文件的问题，有时候甚至录音文件丢失，安卓手机就没有这个问题

**Comment by ifkd111** [comment]
> 首先要支持 https

请问https怎么弄，我模型都弄好了，但是还是不行

**Comment by wufxgtihub123** [comment]
> > 首先要支持 https
> 
> 请问https怎么弄，我模型都弄好了，但是还是不行

老哥，请问这个语音输入的问题你解决了吗？是咋解决的

**Comment by boleyn** [comment]
自己弄个域名，然后弄一下https 就可以了，具体网上都有教程
或者浏览器强制开启某个ip的安全模式

**Comment by ifkd111** [comment]
> 自己弄个域名，然后弄一下https 就可以了，具体网上都有教程 或者浏览器强制开启某个ip的安全模式

我是http开启了语音输入，反正就是chrome://flags/里设置下就好了，但是语音这个按键亮了，能点击了，可还是没有输入，应该输入的时候会有波形的嘛，到底是哪里不对呢？求大哥指导下，谢谢了

**Comment by sdytzjp** [comment]
> > 首先要支持 https
> 
> 请问https怎么弄，我模型都弄好了，但是还是不行

https用nginx反向代理处理即可

请问你语音模型怎么接入oneapi的，跟文本模型的方法一样吗 我搞不定这个
