### ISSUE TITLE
fastgpt中的聊天记录，可以提取相关信息标识进行处理，未解决相关问题推送给后台人员通知，或者生成工单记录；

### ISSUE THREAD

**Issue by sulian2018** [labring/FastGPT#1260]
fastgpt中的聊天记录，可以提取相关信息标识进行处理，未解决相关问题推送给后台人员通知，或者生成工单记录；

**Comment by lijiajun1997** [comment]
可以在每轮对话后加一个分类，是否解决用户问题，然后加一个判断器，执行http,推送工单
