### ISSUE TITLE
无法使用\n回车进行分段

### ISSUE THREAD

**Issue by LSXNN** [labring/FastGPT#1261]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
上传知识库时，通过【直接分段】——【自定义规则】——使用\n回车进行分段，无法正常分段；
在其他电脑上部署同样的项目后，做相同的测试，同样无法使用回车分段，具有普遍性。
**复现步骤**

**预期结果**
可以依据\n分段

**相关截图**
![image](https://github.com/labring/FastGPT/assets/42612227/712df61f-d8b8-42f4-bfaa-2cde54a24193)

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/5c7fcf26-d93f-4a4b-9654-c9f4820c4afc)
没有问题啊
是不是应该要查一下你的模型，是否支持文件处理
![image](https://github.com/labring/FastGPT/assets/40045458/f2e7243b-f14a-40ab-a7fd-da8e715d5c5e)
@LSXNN

**Comment by c121914yu** [comment]
感觉是你文件问题，它不是\n，可能是 \r\n啥的
