### ISSUE TITLE
高级流程编排中，“应用调用”插件，应提供直接无条件直接调用功能 

### ISSUE THREAD

**Issue by sulian2018** [labring/FastGPT#1262]
在高级流程编排中，那个“应用调用”插件，“用户问题"输入参数可以为空，作为一个指令，直接调用“应用调用”的对话入口，然后在新的应用调用节点输入问题，继续流程。这样更符合实际应用场景，而现有的流程编排，把“用户问题"输入参数作为必输项，不能直接保存，实际应用场景大多只是通过前面流程节点条件触发这个“应用调用”，“用户问题"可以忽略，这样改进一下会更好提升应用需求。

**Comment by lijiajun1997** [comment]
没理解你的意思 能不能流程图

**Comment by c121914yu** [comment]
确实没懂。。

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8-alpha
新版工作流触发时机优化，可以再尝试
