### ISSUE TITLE
知识库csv文件分段，如何将一行数据分割为单独的一段

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1267]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
在知识库中导入csv文档，如何设置“自定义分隔符“，到达每一行的内容分割在单独的一段中

例如：如图所示的csv文档
![image](https://github.com/labring/FastGPT/assets/40045458/3c740a67-f0b3-48ec-8c17-6c5f463b0a6d)
如何设置自定义分隔符，可以分为3段，到达如下的效果：

第一段：
A:1
C:1
E:1

第二段：
B:2
D:2

第三段：
A:3
B:3
C:3
D:3
E:3

谢谢！
@lolocoo @c121914yu  @nongmo677 
**复现步骤**

**预期结果**

**相关截图**

**Comment by nongmo677** [comment]
把csv转成txt，保证编码为`utf-8`重新上传，然后用`\r\n`或者`\n`自定义分割

**Comment by xiaoToby** [comment]
> 把csv转成txt，保证编码为`utf-8`重新上传，然后用`\r\n`或者`\n`自定义分割

原本是json文件，我好不容易转换成csv，为什么还要转成txt

**Comment by nongmo677** [comment]
> > 把csv转成txt，保证编码为`utf-8`重新上传，然后用`\r\n`或者`\n`自定义分割
> 
> 原本是json文件，我好不容易转换成csv，为什么还要转成txt @nongmo677

不同文件的解析的结果不一样

**Comment by xiaoToby** [comment]
> > > 把csv转成txt，保证编码为`utf-8`重新上传，然后用`\r\n`或者`\n`自定义分割
> > 
> > 
> > 原本是json文件，我好不容易转换成csv，为什么还要转成txt @nongmo677
> 
> 不同文件的解析的结果不一样

这是靠经验判断的，还是有相应的理论支撑？

**Comment by xiaoToby** [comment]
> 把csv转成txt，保证编码为`utf-8`重新上传，然后用`\r\n`或者`\n`自定义分割

感觉还是没有达到理想的分段效果。

例如：如图所示的csv文档
![image](https://github.com/labring/FastGPT/assets/40045458/8cdd7ccc-9378-4138-97a5-778f75c01173)

如何设置自定义分隔符，可以分为3段，到达如下的效果：

第一段：
A:1
C:1
E:1

第二段：
B:2
D:2

第三段：
A:3
B:3
C:3
D:3
E:3

**Comment by xiaoToby** [comment]
> > 把csv转成txt，保证编码为`utf-8`重新上传，然后用`\r\n`或者`\n`自定义分割
> 
> 感觉还是没有达到理想的分段效果。
> 
> 例如：如图所示的csv文档 ![image](https://private-user-images.githubusercontent.com/40045458/324675453-8cdd7ccc-9378-4138-97a5-778f75c01173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDMwODcsIm5iZiI6MTcxMzg0Mjc4NywicGF0aCI6Ii80MDA0NTQ1OC8zMjQ2NzU0NTMtOGNkZDdjY2MtOTM3OC00MTM4LTk3YTUtNzc4Zjc1YzAxMTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAzMjYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMDg1MzYzYTQ0NWU0NWM2ZDk5YWJmNWQyYWU1ZWM3ZjhhMzlhNjIzZGViMDU3Y2E1ZjgzMmVjMmE3NWYzMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Citsw7NbCAwpA9UYB2JbmmEljER0GoiVagZKcpeY1p8)
> 
> 如何设置自定义分隔符，可以分为3段，到达如下的效果：
> 
> 第一段： A:1 C:1 E:1
> 
> 第二段： B:2 D:2
> 
> 第三段： A:3 B:3 C:3 D:3 E:3

**Comment by nongmo677** [comment]
这种自由度太高了...从源码出发自己开发一套逻辑

**Comment by nongmo677** [comment]
> 这种自由度太高了...从源码出发自己开发一套逻辑

太累了...你这种还得分组，这已经不是一个正则表达式就能做的事情了

如果你只是为了获取有数值的内容尝试用零宽断言的形式匹配吧`\w:\s+(?!\d)`，已经想不出更合适的正则了

![image](https://github.com/labring/FastGPT/assets/31816449/0759e276-37fb-4c0b-b20f-ee57b02569c6)

**Comment by xiaoToby** [comment]
> 分隔符这个功能压根不能用，怎么分都不行

也没有呢，还是能用的，先好好调整一下自己的文本内容。
我是这样做的我对每一个类目都写在了一个段落内，分隔符使用"\n"，也成功的把每个类目都分开了

**Comment by zx874561** [comment]
> 分隔符这个功能压根不能用，怎么分都不行

解决了吗
