### ISSUE TITLE
本地开发，无法正常启动项目

### ISSUE THREAD

**Issue by hqh546020152** [labring/FastGPT#1268]
**你的版本**
V4.7.1-fix

- 私有部署版本

**问题描述**
本地开发，无法正常启动项目，报“Load init config error SyntaxError: Unexpected token A in JSON at position 921” 报错情况无法定位问题。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/33022391/0dfc1dfe-bddd-4f43-a5fb-e590cbe1ccc9)

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/fefd915a-e827-4a56-99f4-5d0ba6aa8e14)
全局搜搜就知道了
