### ISSUE TITLE
docker-compose.yml 配置问题，导致fastgpt应用无法连接mongodb

### ISSUE THREAD

**Issue by fairychao** [labring/FastGPT#1269]
**问题描述**
当docker-compose.yml  中 mongo 的密码配置特殊字符时，mongo正常启动和配置，但是fastgpt应用无法连接到mongo。
返回  findone()，timeout。

如密码配置为mongo#1234，登录时报上面错误，删除“#”后，正常。

**Comment by c121914yu** [comment]
自行转义
