### ISSUE TITLE
知识库问答同一个问题回答内容不一样

### ISSUE THREAD

**Issue by jipfqf** [labring/FastGPT#127]
![image](https://github.com/labring/FastGPT/assets/22951659/fc06f61d-467f-4766-b328-b8870bba2976)

这种是不是不太正常

![image](https://github.com/labring/FastGPT/assets/22951659/ffad4a24-6b51-4317-a214-b54da694fcb3)
这个是原文件
该怎么调整

**Comment by sunk926** [comment]
用gpt4吧,3.5是比较弱智,我之前那个也是这样

**Comment by c121914yu** [comment]
限定词影响了。而且因为有上下文。你从语文角度去思考就知道为什么了。
