### ISSUE TITLE
对话框上传文件

### ISSUE THREAD

**Issue by adogcode** [labring/FastGPT#1270]
1、问答框支持文件上传，类似chatpdf效果，以及多文档管理和问答
2、还有个需求是：针对大文件的摘要生成，有没有什么标准化的配置方案，现在向量数据库解决不了这个需求
3、问答时候内置url链接抓取插件，可以自动抓取问题中的url链接内容

**Comment by boleyn** [comment]
同求，文档框支持文档上传，流程编排希望增加支持文档入口，自己做了，但是效果不是很好啊，求大大原生支持
![img_v3_02a7_77686036-fd95-4f4f-85c3-c0bfb8df74fg](https://github.com/labring/FastGPT/assets/24293664/7b9d6b78-ef44-4a7b-a1a7-2ac28c8bdc1c)

**Comment by gallonyin** [comment]
+1，希望支持文件上传，类似chatfile插件能力

**Comment by SimpleYoung423** [comment]
+1，希望支持文件上传，类似chatfile插件能力

**Comment by MrFanco** [comment]
Yes, I also need  this too, please!

**Comment by lijiajun1997** [comment]
+1，希望支持文件上传，类似chatfile插件能力

**Comment by xiaoToby** [comment]
+1，希望支持文件上传，类似chatfile插件能力

**Comment by adogcode** [comment]
另外有个需求就是，想能查看每天的用户访问量和对话次数，不知道哪个表里能查到这些数据

**Comment by dumengnan** [comment]
This is a very useful function. In some scenarios, we hope to support it.

**Comment by zhanghx0905** [comment]
希望能支持OCR读图，这样即使是不支持多模态的模型，可以通过读取图片上的文字响应图片输入

**Comment by zenwan** [comment]
+1，希望在聊天框支持文件上传

**Comment by PittYao** [comment]
> 同求，问答档框支持文档上传，流程编排希望增加支持文档入口，自己做了，但是效果不是很好啊，求大大原生支持 ![img_v3_02a7_77686036-fd95-4f4f-85c3-c0bfb8df74fg](https://private-user-images.githubusercontent.com/24293664/324710936-7b9d6b78-ef44-4a7b-a1a7-2ac28c8bdc1c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDQ5MTksIm5iZiI6MTcyNDMwNDYxOSwicGF0aCI6Ii8yNDI5MzY2NC8zMjQ3MTA5MzYtN2I5ZDZiNzgtZWY0NC00YTdiLWExYTctMmFjMjhjOGJkYzFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA1MzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYTUxY2EzMzI2OTA4MDFkYWVkYjkzNDkwOTY3YmMzY2UwYmZjYTY4Y2QwYzQwN2IxODBiYjNhYTNlMGFiOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ufziwE2epbVj6XYixXNfkLdGsVxquG-Bm3EiCANh1t8)

有仓库地址吗 想学习下怎么做的

**Comment by c121914yu** [comment]
4.8.9 已有
