### ISSUE TITLE
/app/data/config.json，配置文件挂载

### ISSUE THREAD

**Issue by swallowMuzi** [labring/FastGPT#1273]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
在执行docker compose up -d时出现报错，提示配置文件config.json挂载不成功，该怎么解决呀

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/127709056/0093a4f0-d4f2-4fd2-accf-ddd361927834)

**Comment by swallowMuzi** [comment]
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/nxydsl/fastgpt/config.json" to rootfs at "/app/data/config.json": mount /data/nxydsl/fastgpt/config.json:/app/data/config.json (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by leamiko-eich** [comment]
![image](https://github.com/labring/FastGPT/assets/131839210/42eb7e32-4732-446f-be29-1038cd5e9d4a)
 一样的问题

**Comment by leamiko-eich** [comment]
删掉config.json这个目录

手动复制  https://github.com/labring/FastGPT/blob/main/projects/app/data/config.json 

![image](https://github.com/labring/FastGPT/assets/131839210/9e196595-b581-4746-9578-d24cac44202a)

然后docker compose up -d 就可以了

**Comment by swallowMuzi** [comment]
> 删掉config.json这个目录
> 
> 手动复制 https://github.com/labring/FastGPT/blob/main/projects/app/data/config.json
> 
> ![image](https://private-user-images.githubusercontent.com/131839210/325066928-9e196595-b581-4746-9578-d24cac44202a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDIwOTgsIm5iZiI6MTcxMzk0MTc5OCwicGF0aCI6Ii8xMzE4MzkyMTAvMzI1MDY2OTI4LTllMTk2NTk1LWI1ODEtNDc0Ni05NTc4LWQyNGNhYzQ0MjAyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNjU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjgzYzA4YzRhZGQ2ZTk3MjRkMzNlN2M4YzMzZDQ0M2RlZDY5NDk0NDdmZjZhZDE5OTk4ODgzMTU5YjgxNDMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QjHT2k80BJLHRnJW-kH-nT-ec1mQ-xu2KgoMiDODJhg)
> 
> 然后docker compose up -d 就可以了

大佬，我把config.json这个文件删掉了，新建了一个空的config.json文件，复制了最新的配置代码进去，但还是挂载不成功，主要问题是出在哪里呀

**Comment by swallowMuzi** [comment]
@leamiko-eich

**Comment by c121914yu** [comment]
你要先有文件才能挂载，，你这先运行再下文件有啥用~

**Comment by leamiko-eich** [comment]
@swallowMuzi  第一次 docker compose  up -d 的时候，它生成了config.json的目录， 你要删掉它，新建一个config.json的文件，然后复制配置进去，重新 `docker compose up -d `

**Comment by gcm42659** [comment]
> 你要先有文件才能挂载，，你这先运行再下载文件有啥用~ 问题在于，你没config.json文件，就去运行docker compose，他会给你创建一个叫config.json 的目录。 并且修改挂载文件，需要 down 了再 up

大佬，我还是没明白，能在解释一下吗，我删掉文件后，重新建立一个config.json夹，里面有一个config.json文件，然后我再去运行docker compose up，他还是显示挂载

**Comment by c121914yu** [comment]
> > 你要先有文件才能挂载，，你这先运行再下载文件有啥用~ 问题在于，你没config.json文件，就去运行docker compose，他会给你创建一个叫config.json 的目录。 并且修改挂载文件，需要 down 了再 up
> 
> 大佬，我还是没明白，能在解释一下吗，我删掉文件后，重新建立一个config.json夹，里面有一个config.json文件，然后我再去运行docker compose up，他还是显示挂载

config.json 是个文件不是文件夹

**Comment by c121914yu** [comment]
> > 你要先有文件才能挂载，，你这先运行再下载文件有啥用~ 问题在于，你没config.json文件，就去运行docker compose，他会给你创建一个叫config.json 的目录。 并且修改挂载文件，需要 down 了再 up
> 
> 大佬，我还是没明白，能在解释一下吗，我删掉文件后，重新建立一个config.json夹，里面有一个config.json文件，然后我再去运行docker compose up，他还是显示挂载

config.json 是个文件不是文件夹

**Comment by liudonghua123** [comment]
same problem, `cp ../../projects/app/data/config.json .` fixed.

**Comment by PairZhu** [comment]
我也遇到了这个问题，这是什么原因导致的？运行容器前我并没有这个目录，是挂载的时候自动创建的，按理说应该是从容器内复制出来才对，但是我进入容器内查看发现确实是文件。这就很莫名其妙。难道是我docker版本太老的问题？我服务器上的docker容器确实很老
