### ISSUE TITLE
新建的聊天中发送任何问题就会出现报错

### ISSUE THREAD

**Issue by wyk0930** [labring/FastGPT#1275]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述**
容器启动后并登录页面后，在新建的聊天中发送任何问题就会出现报错。

**复现步骤**
1. 选择[新对话]
2. 发送问题

**预期结果**
响应正常回答内容

**相关截图**
![Snipaste_2024-04-23_23-14-11](https://github.com/labring/FastGPT/assets/95577729/90d9cd9b-9061-4f3d-9909-8aa369de57ee)

**Comment by c121914yu** [comment]
key填不对

**Comment by c121914yu** [comment]
> key填不对

**Comment by pan-common** [comment]
啥key不对?我也遇到这个问题了
