### ISSUE TITLE
功能需求-判断器多个分支简化

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#1277]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
如果需要使用判断器生成多个分支，需要叠很多个判断器反复if else，对于流程编排会增加很多工作。
能否简化逻辑，在判断器中直接进行多个分支设定，形成类似于分类器的功能。
**应用场景**
例如我需要在全局变量中由用户选择功能选项，然后对于这个变量进行不同的编排路径，需要设置多个判断器去进行分类。
**相关示例**
类似于分类器

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8-alpha 支持if elseif else组合
