### ISSUE TITLE
错误消息“ECONNREFUSED”

### ISSUE THREAD

**Issue by zwzypmmlc** [labring/FastGPT#1281]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
在使用高级编排的HTTP请求时，配置了api地址以及出参和入参，提示接口返回ECONNREFUSED
**复现步骤**
用postman试了接口是没问题的，不清楚为什么这里的功能接口返回报错

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/153880050/c45b32b5-0bee-4d84-8295-8c06bf9fa092)
![image](https://github.com/labring/FastGPT/assets/153880050/0ca1d686-3c6d-49a0-b94e-040d688b3f25)

**Comment by c121914yu** [comment]
看着是没法请求你这个地址~检查你的网络。
