### ISSUE TITLE
为什么我用阿里的文本向量接口，语义搜索匹配的值都在几千，不是再0-1之间呢

### ISSUE THREAD

**Issue by taishan666** [labring/FastGPT#1282]
为什么我用阿里的文本向量接口，语义搜索匹配的值都在几千，不是再0-1之间呢

**Comment by boleyn** [comment]
没做归一化处理

**Comment by lijiajun1997** [comment]
之前有人提过，目前对于其他的向量匹配度兼容性还没优化，估计后面会修复

**Comment by c121914yu** [comment]
> 没做归一化处理

正解

**Comment by taishan666** [comment]
> 目前对于其他的向量匹配度兼容性还没优化，估计后面会修复



> 没做归一化处理
如何做归一化处理，再fastgpt上改，还是oneapi
