### ISSUE TITLE
v4.7版本 系统自定义prompt不生效？

### ISSUE THREAD

**Issue by cikiChe** [labring/FastGPT#1283]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ √] 私有部署版本, 具体版本号: v4.7

**问题描述**
系统自定义prompt不生效？

**复现步骤**
![image](https://github.com/labring/FastGPT/assets/13810025/3d99797f-39c9-48d0-a953-d7688e06a58b)
![image](https://github.com/labring/FastGPT/assets/13810025/93ea8aac-aee5-4993-9867-c25682951998)
![image](https://github.com/labring/FastGPT/assets/13810025/13cfb9fd-35b7-4a82-8500-9d1c13d291ba)

**预期结果**
可能是我理解有误，我希望的是让它直接回复知识库设定内容。

我的场景是：学生和老师，学生提问，老师回答。但是因为分类过多，导致学生也不方便看，所以我想让fastgpt在用户输入某个分类的问题后，自动回复知识库的内容

**相关截图**

**Comment by c121914yu** [comment]
直接看完整记录就知道了，有引用内容，回答不了，要么模型太烂，要么提示词太烂。

**Comment by cikiChe** [comment]
> 直接看完整记录就知道了，有引用内容，回答不了，要么模型太烂，要么提示词太烂。

感谢，使用了14b后就正常了，确实是模型问题
