### ISSUE TITLE
高级编排中，能否调用本地api函数或python脚本

### ISSUE THREAD

**Issue by zhjygit** [labring/FastGPT#1284]
例如，我本地部署了kiwix离线维基知识库，kiwix是zim格式，在网页中集合了文字、图片、音视频等内容，资源非常丰富，比纯文字版的本地知识库好很多。在kiwix离线知识库基础上，可编写python脚本去查找kiwix里面的内容，再将内容返回到fastGPT中，这个调用过程是怎么实现的呢？
看到了laf和http貌似都需要联网使用，如果是离线本地不连互联网，如何高级编排中调用第三方功能呢？

当然，实现我的需求，还有一个方法是，在kiwix框架中集成llm模型的接口。

**Comment by lijiajun1997** [comment]
写一个接口，用http模块post请求，返回的信息用markdown形式。
