### ISSUE TITLE
“知识库搜索引用合并”对于存在空引用就无法执行的问题

### ISSUE THREAD

**Issue by pharaohnie** [labring/FastGPT#1286]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

利用“工具调用”和配合“知识库搜索引用合并”自动的根据问题选择一个或多个知识库进行回答。
当问题只关联到一个知识库的时候，由于“知识库搜索引用合并”的逻辑要求，必须所有的引用都不为空才会继续向下执行。
因此执行到这一步的时候，流程就停止了。

**应用场景**
自动根据问题选择一个或多个知识库进行回答。

**相关示例**

<img width="1603" alt="image" src="https://github.com/labring/FastGPT/assets/880867/6308c680-9c3b-4183-8c79-ece4123177c2">
一共两个库，语文课标和信息科技课标。提问“语文和信息科技课标主要内容，100字总结”，可以关联到两个，引用1和引用2都有内容，
“知识库搜索引用合并”会继续向下运行，直到回答完毕。

但是，当我提问“信息科技课标主要内容，100字总结”的时候，引用1的内容是空的。此时，就不会在调用“AI对话”了。

**建议**
调整“知识库搜索引用合并”的逻辑。当有引用为空的时候，流程仍然能继续运行。

**Comment by c121914yu** [comment]
不合理的编排

**Comment by c121914yu** [comment]
有点抽象，用了工具调用，直接让模型回复就可以了把？

**Comment by pharaohnie** [comment]
> 有点抽象，用了工具调用，直接让模型回复就可以了把？

这样解释吧。比如，我有A和B两个知识库，我问同一个问题，以下两种问题召回方式的答案肯定是有区别的。
1）从“A+B”混合的知识库召回内容回答。
2）同样的问题从A知识库召回内容，同样的问题再从B知识库召回内容，之后混合召回内容在回答。

所以我才去尝试用工具调用去选择知识库，然后合并引用来回答问题。尤其在知识库多的时候，这种方式肯定效果更好。

结果发现合并引用的时候，如果某个引用内容是空，就停止继续运行了。

**Comment by lijiajun1997** [comment]
你直接在工具连接两个知识库，然后在提示词里告诉工具请先从两个知识库里查找答案，如果没有，则自己组织回答。
不要接后面一堆乱七八糟的。

**Comment by pharaohnie** [comment]
各位，我找到解决办法了，还是编排设置的问题。不是合并引用的问题。合并引用中如果某一个引用是空的仍然会继续下一步的。
重点是“工具调用终止”的摆放位置。如下：

<img width="1490" alt="image" src="https://github.com/labring/FastGPT/assets/880867/ab7dcff0-dd1b-4438-989d-c3608cbd45d4">

**Comment by lijiajun1997** [comment]
不懂你为啥使用工具，还再接一次模型，直接知识库返给工具就可以输出答案了。




李嘉俊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月25日(星期四) 晚上9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] “知识库搜索引用合并”对于存在空引用就无法执行的问题 (Issue #1286)





 
各位，我找到解决办法了，还是编排设置的问题。不是合并引用的问题。合并引用中如果某一个引用是空的仍然会继续下一步的。
 重点是“工具调用终止”的摆放位置。如下：
 image.png (view on web)

**Comment by c121914yu** [comment]
可以尝试新工作流~ 旧版的close掉了
