### ISSUE TITLE
对项目进行npm build编译报错

### ISSUE THREAD

**Issue by zukxu** [labring/FastGPT#1287]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
系统版本：Windows11 / CentOS Linux release 8.1.1911 (Core)
node：v18.20.2
npm：10.5.0
pnpm：9.0.5
项目为最新开源版【截至20240424】
- Windows环境：
![image](https://github.com/labring/FastGPT/assets/63381545/a5a07967-831d-45ca-b50f-cddfb520b1e9)
- 服务器环境
![image](https://github.com/labring/FastGPT/assets/63381545/4d928ec3-899a-4ae2-a5d7-7056b82d6316)

**问题描述**
在本机Windows上执行`npm run build`命令能正常编译打包，但是在服务器上执行`npm run build`就会报编译错误

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/63381545/2ded3c05-9ca3-499f-a623-fd1b041fa627)

**Comment by c121914yu** [comment]
这是pnpm项目

**Comment by zukxu** [comment]
> 首先这是pnpm项目。 其次，你这个是ts报错，type error

但是哪怕执行了`pnpm run build`，依然报错，而且代码都是没有任何改动的源码，为什么还会报这个错误

![image](https://github.com/labring/FastGPT/assets/63381545/ec39c7ec-f18f-4696-9712-2ac1175c451b)
