### ISSUE TITLE
http请求模块流转异常

### ISSUE THREAD

**Issue by fevolq** [labring/FastGPT#1290]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.7

**问题描述**
http请求失败后，流程直接终止了，无法进行下一个流程。
**复现步骤**
1. 使用一个无法访问的链接
2. http请求后续再连接其他流程
**预期结果**
无论http是否响应200，都应在结束后走到下一个流程，而且把内容传过去
**相关截图**
![image](https://github.com/labring/FastGPT/assets/49370176/8ffcba86-2450-4e67-b144-19992de7eb4d)
![image](https://github.com/labring/FastGPT/assets/49370176/900f5431-1878-46f3-8f17-dd1c36e04fc9)

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8-alpha
新版做了优化

**Comment by LuKing4DB** [comment]
感觉是一个负优化。导致流程进行必须依赖于插件的正常运行？

**Comment by c121914yu** [comment]
> 感觉是一个负优化。导致流程进行必须依赖于插件的正常运行？

不正常运行意义在哪里

**Comment by LuKing4DB** [comment]
这个优化的结果是剥夺了用户对于流程的错误处理。插件报错程序关闭了，好比我现在用的chrome一个插件不能用，整个浏览器都关掉一样。

> > 感觉是一个负优化。导致流程进行必须依赖于插件的正常运行？
> 
> 不正常运行意义在哪里

**Comment by c121914yu** [comment]
> 这个优化的结果是剥夺了用户对于流程的错误处理。插件报错程序关闭了，好比我现在用的chrome一个插件不能用，整个浏览器都关掉一样。
> 
> > > 感觉是一个负优化。导致流程进行必须依赖于插件的正常运行？
> > 
> > 不正常运行意义在哪里
> 
> 

这个比喻不好，浏览器和插件独立的。节点直接是有流程的。
如果谷歌搜索接口报错了，还要继续展示搜索结果，非常奇怪。
正常程序，如果希望错误了继续，肯定是捕获错误单独处理，而不是让它直接继续。

**Comment by fevolq** [comment]
> > 这个优化的结果是剥夺了用户对于流程的错误处理。插件报错程序关闭了，好比我现在用的chrome一个插件不能用，整个浏览器都关掉一样。
> > > > 感觉是一个负优化。导致流程进行必须依赖于插件的正常运行？
> > > 
> > > 
> > > 不正常运行意义在哪里
> 
> 这个比喻不好，浏览器和插件独立的。节点直接是有相互关系的。 如果谷歌搜索接口报错了，还要继续展示搜索结果，非常奇怪。 正常程序，如果希望错误了继续，肯定是捕获错误单独处理，而不是让它直接继续。

但是请求的url不一定是自己写的服务，如果请求的是别人的链接呢，怎么捕获异常

**Comment by c121914yu** [comment]
> > > 这个优化的结果是剥夺了用户对于流程的错误处理。插件报错程序关闭了，好比我现在用的chrome一个插件不能用，整个浏览器都关掉一样。
> > > > > 感觉是一个负优化。导致流程进行必须依赖于插件的正常运行？
> > > > 
> > > > 
> > > > 不正常运行意义在哪里
> > 
> > 
> > 这个比喻不好，浏览器和插件独立的。节点直接是有相互关系的。 如果谷歌搜索接口报错了，还要继续展示搜索结果，非常奇怪。 正常程序，如果希望错误了继续，肯定是捕获错误单独处理，而不是让它直接继续。
> 
> 但是请求的url不一定是自己写的服务，如果请求的是别人的链接呢，怎么捕获异常

单独写一个服务去捕获。

**Comment by fevolq** [comment]
> > > > 这个优化的结果是剥夺了用户对于流程的错误处理。插件报错程序关闭了，好比我现在用的chrome一个插件不能用，整个浏览器都关掉一样。
> > > > > > 感觉是一个负优化。导致流程进行必须依赖于插件的正常运行？
> > > > > 
> > > > > 
> > > > > 不正常运行意义在哪里
> > > 
> > > 
> > > 这个比喻不好，浏览器和插件独立的。节点直接是有相互关系的。 如果谷歌搜索接口报错了，还要继续展示搜索结果，非常奇怪。 正常程序，如果希望错误了继续，肯定是捕获错误单独处理，而不是让它直接继续。
> > 
> > 
> > 但是请求的url不一定是自己写的服务，如果请求的是别人的链接呢，怎么捕获异常
> 
> 单独写一个服务去捕获。

这样的话，内置的http模块就没意义了，我为什么不直接自己封装一个插件，用来请求外部链接

**Comment by c121914yu** [comment]
> > > > > 这个优化的结果是剥夺了用户对于流程的错误处理。插件报错程序关闭了，好比我现在用的chrome一个插件不能用，整个浏览器都关掉一样。
> > > > > > > 感觉是一个负优化。导致流程进行必须依赖于插件的正常运行？
> > > > > > 
> > > > > > 
> > > > > > 不正常运行意义在哪里
> > > > 
> > > > 
> > > > 这个比喻不好，浏览器和插件独立的。节点直接是有相互关系的。 如果谷歌搜索接口报错了，还要继续展示搜索结果，非常奇怪。 正常程序，如果希望错误了继续，肯定是捕获错误单独处理，而不是让它直接继续。
> > > 
> > > 
> > > 但是请求的url不一定是自己写的服务，如果请求的是别人的链接呢，怎么捕获异常
> > 
> > 
> > 单独写一个服务去捕获。
> 
> 这样的话，内置的http模块就没意义了，我为什么不直接自己封装一个插件，用来请求外部链接

因为封装插件也需要HTTP

**Comment by LuKing4DB** [comment]
> > > 不正常运行意义在哪里
> 
> 这个比喻不好，浏览器和插件独立的。节点直接是有相互关系的。 如果谷歌搜索接口报错了，还要继续展示搜索结果，非常奇怪。 正常程序，如果希望错误了继续，肯定是捕获错误单独处理，而不是让它直接继续。

那你这不是承认了4.8版本不是正常程序，因为他不能捕获错误且单独处理。多的也不想争。看来提issue没啥用，fork自己改吧。

**Comment by c121914yu** [comment]
> > > > 不正常运行意义在哪里
> > 
> > 这个比喻不好，浏览器和插件独立的。节点直接是有相互关系的。 如果谷歌搜索接口报错了，还要继续展示搜索结果，非常奇怪。 正常程序，如果希望错误了继续，肯定是捕获错误单独处理，而不是让它直接继续。
> 
> 那你这不是承认了4.8版本不是正常程序，因为他不能捕获错误且单独处理。多的也不想争。看来提issue没啥用，fork自己改吧。

那是你接口不能不过错误处理，和哪个版本有啥关系

**Comment by c121914yu** [comment]
一个常见的例子：
我有两个HTTP，第一个HTTP会请求用户信息，然后是调用模型分析用户信息，最后是调用HTTP存储用户信息。
那么，假设我的第一个接口报错了，模型还继续分析（虽然不会得到任何结果，但是会费token），然后再进行HTTP存储，此时肯定不会存储到内容。
最终，我需要给用户一段反馈，那么他最终得到的，依然是一个报错，并且是存储的报错，而不是获取信息的报错。

**Comment by c121914yu** [comment]
> 一个常见的例子： 我有两个HTTP，第一个HTTP会请求用户信息，然后是调用模型分析用户信息，最后是调用HTTP存储用户信息。 那么，假设我的第一个接口报错了，模型还继续分析（虽然不会得到任何结果，但是会费token），然后再进行HTTP存储，此时肯定不会存储到内容。 最终，我需要给用户一段反馈，那么他最终得到的，依然是一个报错，并且是存储的报错，而不是获取信息的报错。

![image](https://github.com/labring/FastGPT/assets/50446880/8bb54b41-1c50-4df1-8e3e-ec71a7032723)
我给他做了优化

**Comment by fevolq** [comment]
> > 一个常见的例子： 我有两个HTTP，第一个HTTP会请求用户信息，然后是调用模型分析用户信息，最后是调用HTTP存储用户信息。 那么，假设我的第一个接口报错了，模型还继续分析（虽然不会得到任何结果，但是会费token），然后再进行HTTP存储，此时肯定不会存储到内容。 最终，我需要给用户一段反馈，那么他最终得到的，依然是一个报错，并且是存储的报错，而不是获取信息的报错。
> 
> ![image](https://private-user-images.githubusercontent.com/50446880/332680980-8bb54b41-1c50-4df1-8e3e-ec71a7032723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTk1MTAsIm5iZiI6MTcxNjM1OTIxMCwicGF0aCI6Ii81MDQ0Njg4MC8zMzI2ODA5ODAtOGJiNTRiNDEtMWM1MC00ZGYxLThlM2UtZWM3MWE3MDMyNzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA2MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmZhNzMyOTZjNzk4YTE5NDA1Y2ZjZjNmM2ExMGM5MWQxMTQ5OGYzYzlhMWM1ZGJjZTE0ZWI2YWZlZTU3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vi8ioyLr7B1L0QeDRMys6FlnyqCvCnOv52VsXZz2Lys) 我给他做了优化

你自己都写了，在http后面对这个请求结果进行判断，成功会怎么进行，失败会怎么进行。主要是流程不能被http来中断

**Comment by c121914yu** [comment]
> > > 一个常见的例子： 我有两个HTTP，第一个HTTP会请求用户信息，然后是调用模型分析用户信息，最后是调用HTTP存储用户信息。 那么，假设我的第一个接口报错了，模型还继续分析（虽然不会得到任何结果，但是会费token），然后再进行HTTP存储，此时肯定不会存储到内容。 最终，我需要给用户一段反馈，那么他最终得到的，依然是一个报错，并且是存储的报错，而不是获取信息的报错。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/50446880/332680980-8bb54b41-1c50-4df1-8e3e-ec71a7032723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTk1MTAsIm5iZiI6MTcxNjM1OTIxMCwicGF0aCI6Ii81MDQ0Njg4MC8zMzI2ODA5ODAtOGJiNTRiNDEtMWM1MC00ZGYxLThlM2UtZWM3MWE3MDMyNzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA2MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmZhNzMyOTZjNzk4YTE5NDA1Y2ZjZjNmM2ExMGM5MWQxMTQ5OGYzYzlhMWM1ZGJjZTE0ZWI2YWZlZTU3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vi8ioyLr7B1L0QeDRMys6FlnyqCvCnOv52VsXZz2Lys) 我给他做了优化
> 
> 你自己都写了，在http后面对这个请求结果进行判断，成功会怎么进行，失败会怎么进行。主要是流程不能被http来中断

重点是~ 没能提出解决方案。

**Comment by fevolq** [comment]
可以考虑给http多增加一个状态码的输出

![image](https://github.com/labring/FastGPT/assets/49370176/18057e48-e4dc-4e6c-bb75-fddbc24453ee)
