### ISSUE TITLE
本地开发后，部署打包构建镜像docker build -t dockername/fastgpt:tag --build-arg name=app .最后报错

### ISSUE THREAD

**Issue by jy-githup** [labring/FastGPT#1292]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by jy-githup** [comment]
<img width="1160" alt="Snipaste_2024-04-25_21-11-00" src="https://github.com/labring/FastGPT/assets/66984015/46dc52db-c181-4d3d-9af8-79a08fcb7fbb">
<img width="1352" alt="Snipaste_2024-04-25_21-11-41" src="https://github.com/labring/FastGPT/assets/66984015/d3c66c99-e2ad-4cd9-8ca1-40534ccb5b76">

**Comment by swallowMuzi** [comment]
蹲解决方法，我也遇到类似的问题

**Comment by c121914yu** [comment]
> <img width="1160" alt="Snipaste_2024-04-25_21-11-00" src="https://github.com/labring/FastGPT/assets/66984015/46dc52db-c181-4d3d-9af8-79a08fcb7fbb">
> <img width="1352" alt="Snipaste_2024-04-25_21-11-41" src="https://github.com/labring/FastGPT/assets/66984015/d3c66c99-e2ad-4cd9-8ca1-40534ccb5b76">
> 

用新的 lock 文件

**Comment by jy-githup** [comment]
OK，已重新构建成功，感谢
