### ISSUE TITLE
我希望能够有鉴权功能

### ISSUE THREAD

**Issue by ifkd111** [labring/FastGPT#1296]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**相关示例**

**Comment by ifkd111** [comment]
我希望分发后有完整鉴权

**Comment by c121914yu** [comment]
抱歉，开源版不会有额外鉴权功能~
