### ISSUE TITLE
猜你想问无法回显

### ISSUE THREAD

**Issue by chuanSir123** [labring/FastGPT#1301]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√] 我已确认目前没有类似 issue
- [√] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [√] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [√ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
猜你想问无法回显。是因为返回格式错了么，正确的格式是怎么样的，能否自定义猜你想问的prompt？

api/core/ai/agent/createQuestionGuide接口返回如下，：
{
    "code": 200,
    "statusText": "",
    "message": "",
    "data": [
        {
            "问题1": "如何提高学员的课程参与度？",
            "问题2": "如何通过优惠吸引新学员？",
            "问题3": "如何利用学员社群增加出勤率？"
        }
    ]
}

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
看着是模型不听话。
正确格式是 string［］

**Comment by Snownamida** [comment]
请问一下这个接口有文档吗? 它的实现代码在哪里呀
