### ISSUE TITLE
node版本为18 本地启动报错 ==> ReferenceError: window is not defined

### ISSUE THREAD

**Issue by perfume6** [labring/FastGPT#1303]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X] 我已确认目前没有类似 issue
- [√] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [√] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [√] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
node版本为18.18.2

启动后报错：
ReferenceError: window is not defined
**复现步骤**
克隆代码下来，启动后访问报错
**预期结果**
不报错
**相关截图**
![image](https://github.com/labring/FastGPT/assets/104194350/5bbbc44a-18d2-436c-9889-183ee07cd05a)
![image](https://github.com/labring/FastGPT/assets/104194350/4a0f6905-48ff-4b70-befb-59499114b4e9)

**Comment by c121914yu** [comment]
不影响正常运行吧？
