### ISSUE TITLE
是否有支持其他向量数据库的计划？现有的pgvector镜像已经不更新了

### ISSUE THREAD

**Issue by mwnu** [labring/FastGPT#1304]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
[ankane/pgvector](https://registry.hub.docker.com/r/ankane/pgvector/tags)这个镜像最后一版是v0.5.1，上次更新还在7个月前。
而[pgvector](https://github.com/pgvector/pgvector)已升级到[v0.6.2](https://github.com/pgvector/pgvector/releases/tag/v0.6.2)版，[这个](https://registry.hub.docker.com/r/pgvector/pgvector)应该是它官方的库。
除此之外，向量数据库还有[qdrant](https://github.com/qdrant/qdrant),[weaviate](https://github.com/weaviate/weaviate)等更流行的选择。
**应用场景**
希望在其他应用中直接调用向量数据库，但相比qdrant、weaviate等，更少工具支持pgvector。

**相关示例**

Flowise 是一款热门的langchain工具，但是不支持pgvector。

**Comment by c121914yu** [comment]
下次更新下。忘记改镜像里的了。
向量库后续会支持 milvus

**Comment by xcpuma** [comment]
milvus不错

**Comment by HelloEveryonehh** [comment]
> 下次更新下。忘记改镜像里的了。或者手动改 vector 新的官方镜像即可。 向量库后续会支持 milvus

什么时候可以支持milvus数据库， Zilliz 能否一并支持，他们两是一家公司的，一个开源一个闭源，sdk是一模一样的操作
