### ISSUE TITLE
开源版不支持laf吗？

### ISSUE THREAD

**Issue by mwnu** [labring/FastGPT#1306]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

我看到文档里面有laf模块，配置中的lafEnv我填了，但是在开源部署的服务里面没找到，这部分是商业版才有的功能吗？
**应用场景**
想要做一些文本处理，目前的文本加工模块不够用，需要支持JavaScript或Python脚本的模块进行数据清洗，http模块可以调用外部工具，但是比较麻烦。

**相关示例**
用正则表达式提取用户输入字符串中的字段。

**Comment by c121914yu** [comment]
配置文件加入后，就会有。

**Comment by mwnu** [comment]
> 配置文件加入后，就会有。

需要填自己部署的laf后端地址吗？
我填的是示例配置中默认的"lafEnv": "https://laf.dev"，没出现这个模块。

**Comment by c121914yu** [comment]
> > 配置文件加入后，就会有。
> 
> 需要填自己部署的laf后端地址吗？ 我填的是示例配置中默认的"lafEnv": "[https://laf.dev"，没出现这个模块。](https://laf.dev%22%EF%BC%8C%E6%B2%A1%E5%87%BA%E7%8E%B0%E8%BF%99%E4%B8%AA%E6%A8%A1%E5%9D%97%E3%80%82)

设计上，配置了就会出来，没涉及商业版，可以看看是不是配置没加载成功。

**Comment by mwnu** [comment]
> > > 配置文件加入后，就会有。
> > 
> > 
> > 需要填自己部署的laf后端地址吗？ 我填的是示例配置中默认的"lafEnv": "[https://laf.dev"，没出现这个模块。](https://laf.dev%22%EF%BC%8C%E6%B2%A1%E5%87%BA%E7%8E%B0%E8%BF%99%E4%B8%AA%E6%A8%A1%E5%9D%97%E3%80%82)
> 
> 设计上，配置了就会出来，没涉及商业版，可以看看是不是配置没加载成功。

确实没有，哪里看啊？也没有相关日志

**Comment by mwnu** [comment]
> 配置文件加入后，就会有。

抱歉，`feConfigs` 字段漏写了一个“s”🤦‍，补上就有了。
