### ISSUE TITLE
无法获取http模块中的响应字段

### ISSUE THREAD

**Issue by mwnu** [labring/FastGPT#1307]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X] 私有部署版本, 具体版本号: [V4.8-preview2](https://github.com/labring/FastGPT/releases/tag/v4.8-preview2)

**问题描述**

例如，我问一个问题：`-ty 最近AI有什么大事件`，其中`-ty` 是我自定义的一个指令，该字符串经过http外部脚本的处理，去除指令保留用户的提示，响应的json是：
```json
{
  "message": "最近AI有什么大事件"
}
```
然后我希望在AI模块中用户问题经过处理的字段： `最近AI有什么大事件` 而不是用户输入原始文本：`-ty 最近AI有什么大事件`，因此，在http模块中添加自定义输出"message"，格式为字符串，它应该能够提取到响应体中的message的值，但我在后续模块引用，无论是手动选的模式还是用`{{message}}`，获取的都是用户原始输入，而非处理后的字符串。

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/45463732/2711791e-c7c7-442e-a83e-0e311995e887)
![image](https://github.com/labring/FastGPT/assets/45463732/087b3382-c0b8-4a98-bdd5-9dc6e70d66b4)
![image](https://github.com/labring/FastGPT/assets/45463732/e4a0b992-8087-42b5-95a6-8ab8eb322203)

**其他例子**
![image](https://github.com/labring/FastGPT/assets/45463732/648cbe4c-6f65-4e2d-9db9-828d84021717)

**Comment by mwnu** [comment]
我知道了，后面的节点要使用前面的变量作为参数需要改类型为引用内容。

**Comment by rodchen-king** [comment]
能分享一下高级编排配置嘛，想做一个 ai可以根据内容分析是否查询接口 以及 ai能力处理结果的。但是没有成功

**Comment by mwnu** [comment]
> 能分享一下高级编排配置嘛，想做一个 ai可以根据内容分析是否查询接口 以及 ai能力处理结果的。但是没有成功

看我在另一个issues中的回复：https://github.com/labring/FastGPT/issues/1388#issuecomment-2098463751

**Comment by Zhenyi-Wang** [comment]
4.8.2升级多了个代码模块，可以直接用js处理字符串，应该不需要专门搞个http接口了。建议可以试试
