### ISSUE TITLE
无法使用本地视觉模型

### ISSUE THREAD

**Issue by QichangZheng** [labring/FastGPT#1308]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
docker部署，已经确认所有镜像都是最新版

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
问题和https://github.com/labring/FastGPT/issues/639 类似，但是我已经是最新版(4.7), oneapi也是最新版
API模型可以正常解析图片，例如gpt4-vision
ollama部署的llava模型在webui调试，可以解析图片，所以模型没问题
在fastgpt可以和llava对话，说明模型正常加载，但是解析图片报错，如截图所示

**复现步骤**

**预期结果**

**相关截图**
<img width="1920" alt="cc1dfc2d3d9055f12c25d8c91afd466" src="https://github.com/labring/FastGPT/assets/82627111/143210d6-6ad3-478c-b20f-827e3c8b1134">

**Comment by nongmo677** [comment]
V4.7.1 测试无误

![image](https://github.com/labring/FastGPT/assets/31816449/c70b3b1e-1ffb-4271-b4ee-917adb62cd29)

**Comment by c121914yu** [comment]
接口没对齐 gpt4v 把

**Comment by QichangZheng** [comment]
> V4.7.1 测试无误
> 
> ![image](https://private-user-images.githubusercontent.com/31816449/326181058-c70b3b1e-1ffb-4271-b4ee-917adb62cd29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjYyOTQsIm5iZiI6MTcxNDIyNTk5NCwicGF0aCI6Ii8zMTgxNjQ0OS8zMjYxODEwNTgtYzcwYjNiMWUtMWZmYi00MjcxLWI0ZWUtOTE3YWRiNjJjZDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEzNTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YWE4MzIwMjRjNjhlNWExZGU4YzU5OTYzNWFjZDQ1ZDljMGI4ODA0OTA2NzhhNTlkMzRmN2IyODg0YWVkZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZboonBPcbE1D33CLjClB60T4HR0eXUH-Yrv42s9mnUY)

请问可以看一下你的配置信息吗？有可能是我配置错了

**Comment by QichangZheng** [comment]
> 接口没对齐 gpt4v 把

我不确定有没有对其，但是gpt4-v和Claude3在我的fastgpt是可以正常解析图片的。

**Comment by nongmo677** [comment]
oneapi渠道选择 ollama渠道

**Comment by QichangZheng** [comment]
已解决：
fastgpt需要指定v4.71版本，我默认latest是v4.7
oneapi的ollama渠道需要设置为ollama，而不是OpenAI
