### ISSUE TITLE
OpenAPI Schema导入integer 类型不能自动转为数字

### ISSUE THREAD

**Issue by mwnu** [labring/FastGPT#1310]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: [V4.8-preview2](https://github.com/labring/FastGPT/releases/tag/v4.8-preview2)

**问题描述**
在[OpenAPI 规范](https://openapi.apifox.cn/)中整数类型的参数一般表示为integer，但导入到fastgpt后并不会被标识为数字
另外数组也没有标识
**复现步骤**

**预期结果**

**相关截图**

**Comment by mwnu** [comment]
另外，http插件如果从Schema导入的，编辑其中action的模块参数是不会同步更新到schema上的，因此如果不幸修改的插件（例如改名），手动编辑的模块会被覆盖掉。
为了避免这一点，只能在action中手动导出备份，一个http插件里面可能会友多个action，这样略显麻烦。

**Comment by c121914yu** [comment]
schema导入是单向的，肯定不会有同步操作，而且schema导入的插件不应该进行编辑。
整数类型 @newfish-cmyk 看看
