### ISSUE TITLE
fastgpt4.8-preview3版本镜像更新之后登录错误

### ISSUE THREAD

**Issue by nightzjp** [labring/FastGPT#1312]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [4.8-preview3 ] 私有部署版本, 具体版本号: 

**问题描述**
更新至4.8-preview3版本之后登录报错；

**复现步骤**
现在我的镜像是4.8-preview，我升级至preview2没问题，当我升级至preview3之后登录500异常

**预期结果**

**相关截图**
<img width="1375" alt="image" src="https://github.com/labring/FastGPT/assets/73635091/b1cd9e70-ac56-4513-b26d-42cdc683dd6f">

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/1311 repeat

**Comment by c121914yu** [comment]
action完成后重新拉取
