### ISSUE TITLE
fastgpt 请求xinference 的rerank模型接口报错

### ISSUE THREAD

**Issue by liangpn** [labring/FastGPT#1316]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
fastgpt 调用 xinference rerank接口报错
fastgpt的配置
![image](https://github.com/xorbitsai/inference/assets/52708183/1dd40a46-cf08-42bb-95cf-f9993b4d2dd3)

使用bce的reank会有下面的错误
![69cb08bb59c01b9eea328d3d2a898f6](https://github.com/xorbitsai/inference/assets/52708183/3fe04377-17cc-49b4-9943-45022f9af2c7)
![61622e47e94db52755c596b9f40dac0](https://github.com/xorbitsai/inference/assets/52708183/833cdfd9-4ae1-4955-9b37-357e1efbb827)
使用bge的reank则是正常
![f2a56b93a0dba4f31eaad604966129f](https://github.com/xorbitsai/inference/assets/52708183/cb5a52e2-322f-4252-b6e6-23b0ee9c74cd)
![cc0b1ab03cd32142d7743ba5e109f8f](https://github.com/xorbitsai/inference/assets/52708183/44b3d3d3-dbf4-4bbc-a35d-52fad557e265)

但是直接curl 调用xinference 的rerank 接口是返回正常
![image](https://github.com/xorbitsai/inference/assets/52708183/a25a292d-d008-4f4c-a0c5-5bbb545cbf01)

**复现步骤**

**预期结果**

**相关截图**

**Comment by cq134cq** [comment]
同问

**Comment by KanoSang** [comment]
可以自己docker部署一个rerank

**Comment by c121914yu** [comment]
数据越界了吧。看着 xinference 问题，可以给他们提，你测试数据太小了。
