### ISSUE TITLE
希望对话接口增加语音&图片输入输出功能

### ISSUE THREAD

**Issue by nightzjp** [labring/FastGPT#1318]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
目前语音&图片输入输出功能可以通过网页分享链接正常使用；但是api接口目前只支持文本问答；希望增加语音的输入输出；图片的输入；感谢fastgpt

**应用场景**

**相关示例**

**Comment by nightzjp** [comment]
网页版么得问题哈。通过api 调用如果能支持就更好了🤪🤪

| |
seven_nighter
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月28日 22:29 |
| 收件人 | labring/FastGPT ***@***.***> |
| 抄送人 | ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [labring/FastGPT] 希望对话接口增加语音&图片输入输出功能 (Issue #1318) |

语音转文字再输入~
网页版也是分开。
图片，存储后发送图片链接。
图片响应是markdown链接。

**Comment by c121914yu** [comment]
> 网页版么得问题哈。通过api 调用如果能支持就更好了🤪🤪 | | seven_nighter | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年04月28日 22:29 | | 收件人 | labring/FastGPT ***@***.***> | | 抄送人 | ***@***.***>, Author ***@***.***> | | 主题 | Re: [labring/FastGPT] 希望对话接口增加语音&图片输入输出功能 (Issue #1318) | 语音转文字再输入~ 网页版也是分开。 图片，存储后发送图片链接。 图片响应是markdown链接。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

不现实，不可能重复做接口，只会组合接口。

**Comment by ifkd111** [comment]
> 

网页版我也起不来语音和图片输入，求大神指导下好么，焦头烂额

**Comment by sdytzjp** [comment]
网页版怎么实现图片和语音

**Comment by sdytzjp** [comment]
网页版怎么实现图片和语音输入和输出，请指教

**Comment by sdytzjp** [comment]
网页版怎么实现图片和语音

**Comment by JiXia830** [comment]
解决了吗？各位佬
