### ISSUE TITLE
llm-embedding是否支持？

### ISSUE THREAD

**Issue by chenbe1990** [labring/FastGPT#132]
请问FastGPT项目是否支持使用使用开源LLM作为embeddings，进行知识库生成

**Comment by c121914yu** [comment]
都支持，写个接口，挂载到oneapi就行了

**Comment by taurusduan** [comment]
> 询问FastGPT项目是否支持使用开源LLM作为嵌入，进行知识库生成

可以询问一下你是如何添加的，我添加embeddings后，录入文件时就卡住了。除了不能生成知识库，其他的都能正常使用
