### ISSUE TITLE
在文本加工中对知识库引用进行加工

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [labring/FastGPT#1320]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X] 我已确认目前没有类似 features
- [X] 我已确认我已升级到最新版本
- [X] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [X] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在知识库搜索之后，对接知识库引用到文本加工中，能否像在AI对话中应用知识库引用时，可以自定义格式，我们想只是把Q或者A拿出来，其他的内容不要。
**应用场景**
在文本加工中对知识库引用进行加工。
**相关示例**

**Comment by lijiajun1997** [comment]
啥应用场景只需要Q不需要A。。。。
如果只需要A的话，你上传文本就好，不要用问答拆分。

**Comment by WholeWorld-Timothy** [comment]
我是要Q或A里面的字，不是要这个结构，我的问题描述的挺清楚的。

**Comment by lijiajun1997** [comment]
> 我是要Q或A里面的字，不是要这个结构，我的问题描述的挺清楚的。

你需要把你这个需求的共性（应用场景）写清楚，如果只是特殊需求的话，作者没有动力去帮你修改这个需求。。
如果你只需要QA里的字，可以在问答拆分后导出csv，把Q列或者A列删掉，再导入csv。

**Comment by WholeWorld-Timothy** [comment]
现有的版本处理可以用http处理，引用内容传给外部api，外部api处理后，可以返回需要的字段。我们在开发中发现，这种场景的需求挺多的，而且也不复杂，在fastgpt中适合实现这一需求。这是我们实际开发中遇到问题，我们写的内容对于熟悉fastgpt的人应该不难理解。

**Comment by Ocean22** [comment]
> 啥应用场景只需要Q不需要A。。。。 如果只需要A的话，你上传文本就好，不要用问答拆分。

需求场景：检索出来的知识相关度只达到20%-50%时，我只想把Q拿出来返回给用户，作为猜你想问的问题列表

**Comment by c121914yu** [comment]
可以通过代码运行实现

**Comment by sanpatricky** [comment]
> 啥应用场景只需要Q不需要A。。。。 如果只需要A的话，你上传文本就好，不要用问答拆分。

知识查重，非常朴素的需求
