### ISSUE TITLE
在yml文件mongo command 里添加--bind_ip_all之后仍然无法外部连接mongo

### ISSUE THREAD

**Issue by zyc1128** [labring/FastGPT#1323]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述**

![1714299790029](https://github.com/labring/FastGPT/assets/68692461/8174eb0d-6fb8-49cc-9f91-ad1f9bc7c557)
files 中的 mongod.comf.orig里bindIp参数仍然是127.0.0.1，改成0.0.0.0也没用

**复现步骤**

**预期结果**

**相关截图**
![1714299984198](https://github.com/labring/FastGPT/assets/68692461/180afb6b-873d-4c5c-854f-3bdf9dac4dc1)

**Comment by c121914yu** [comment]
建议看文档说明
