### ISSUE TITLE
AI市场知识库应用，其他用户无法查看回答的引用

### ISSUE THREAD

**Issue by he-bowen** [labring/FastGPT#133]
问题描述：

A账户在AI市场共享知识库应用，B账户使用该应用，提问后可以看到引用数量，但无法看到引用内容
![image](https://github.com/labring/FastGPT/assets/69750910/296b6906-bf7c-4d5c-a823-9700a58ce2a6)

问题需求：
1. 个人认为，引用的意义为参考，如果只有回答，没有引用，那无法判断问题的准确性。
2. 建议可以将市场应用的引用做到所有账户均可读取。

**Comment by he-bowen** [comment]
@c121914yu

**Comment by he-bowen** [comment]
请问有人可以帮忙看看这个问题嘛？

**Comment by c121914yu** [comment]
设计就是不能看的

**Comment by he-bowen** [comment]
> 设计就是不能看的

好的，谢谢回复，请问有办法可以微调代码来实现该功能嘛~

**Comment by c121914yu** [comment]
改代码，响应时候设置了非owner不返回模型参数
