### ISSUE TITLE
文本内容提取无结果，尝试多种也无效

### ISSUE THREAD

**Issue by siboweng** [labring/FastGPT#1330]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7

- [ ] 私有部署版本, 具体版本号: 4.7

**问题描述**
通过文本内容提取无法提取到具体参数，导致无法进行下一步。

**复现步骤**
![image](https://github.com/labring/FastGPT/assets/167409493/f8618975-5962-4814-bc54-b73cbd6860f9)

![image](https://github.com/labring/FastGPT/assets/167409493/1dcd947b-ecc3-4deb-a283-12b65db34310)

![image](https://github.com/labring/FastGPT/assets/167409493/c0d00cb1-91fc-41d2-964b-6704768ab520)

**预期结果**

**相关截图**

**Comment by nongmo677** [comment]
请把config里对应模型的`toolChoice`和`functionCall`设置为false，变为使用提示词模式

测试在线阿里灵积qwen-max模型，可以提取

![image](https://github.com/labring/FastGPT/assets/31816449/4a636bbc-82a7-483c-9aa6-8d43a98992b2)

**Comment by c121914yu** [comment]
日志会有报错，看文档faq

**Comment by yangkl-ui** [comment]
我本地部署且用本地的模型，换了多个模型都提取不到，日志也没报错，toolChoice和functionCall都调过了也没用，求帮助
