### ISSUE TITLE
llama3:70b关联知识库搜索特别慢

### ISSUE THREAD

**Issue by zhaoyuchen1128** [labring/FastGPT#1335]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
单独聊天速度正常，用很小的模型关联知识库搜索速度也快，但大模型也太慢了
**复现步骤**

**预期结果**

**相关截图**
![ee2c3c6e52dea055abb3744d255f2cf](https://github.com/labring/FastGPT/assets/167266669/e48fd3a5-5d99-4a5c-93bc-17f730a04301)

**Comment by nongmo677** [comment]
开了知识库的`问题优化`?

**Comment by zhaoyuchen1128** [comment]
问题分类模块也要10多秒怎么办

**Comment by zhaoyuchen1128** [comment]
> 开了知识库的`问题优化`?
问题分类模块也要10多秒怎么办

**Comment by c121914yu** [comment]
加卡

**Comment by nongmo677** [comment]
我用ollama部署的正常3秒多回复

![image](https://github.com/labring/FastGPT/assets/31816449/053a814a-57a1-4ccd-a32e-1ea34a3ba7eb)

这种回复问题，一般只跟你部署的模型服务和框架有关，和项目没有直接关系
