### ISSUE TITLE
建议改进文件导入QA拆分

### ISSUE THREAD

**Issue by anguslilei** [labring/FastGPT#134]
看了下代码，是将导入的文本让GPT生成25个问答对，然后就生成索引了。有两个问题

- 1、文本信息可能很短，根本无需25个问答对（或者文本很长，25个可能太少）
- 2、生成的问答对，未必准确，需要调整或者确认

因此提出以下建议：

- 1、可以设置生成问答对数量
- 2、生成问答对后，让用户确认，或者可以修改、删除或者可以重新生成，确认后再导入

当然，现在可以用其它模型（GPT4等）生成更高质量的问答对后，导入CSV，也是一个解决办法，以上只是建议

**Comment by c121914yu** [comment]
csv导入已经有了呀。
1. 大部分文件都会到8k，除了最后一段
2. 这个比较困难，时间不确定，排队的话可能得更久。
选择模型确实是个方法，但是4太贵了，而且长度也不够16k大。感觉改进提示词，或者用function之类的更好。

文件导入后续会持续优化。感谢你的建议

**Comment by c121914yu** [comment]
已经可以单独配置知识库的处理模型。
