### ISSUE TITLE
聊天没问题，但是在知识库里操作就会报错Panic detected, error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thegenway** [labring/FastGPT#1340]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [4.7] 私有部署版本, 具体版本号: 

**问题描述**
正常聊天没问题，但是在知识库里操作（包括手动插入数据，或者是文件上传）就会报错，试了零一万物和讯飞星火，都是这种问题

**相关截图**

![微信截图_20240430154036](https://github.com/labring/FastGPT/assets/12321764/4954eef0-96ee-4029-b167-fa43668fedbb)
![微信截图_20240430154100](https://github.com/labring/FastGPT/assets/12321764/84507f0a-7786-4ded-b878-289e30be0d55)

**Comment by thegenway** [comment]
又变这个错了....【400 Unsupported model: text-embedding-ada-002】

**Comment by c121914yu** [comment]
先自行检查下oneapi 的向量模型是否正常，对话不用向量模型~

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/1379
类似问题。模型问题。
