### ISSUE TITLE
高级编排中的问题分类模块返回的结果与AI大模型返回的结果不一致

### ISSUE THREAD

**Issue by chenlei0913** [labring/FastGPT#1342]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x ] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x ] 私有部署版本, 具体版本号: v4.8-preview2

**问题描述**
高级编排配置了问题分类，配置是正确的。测试时发的问题看命中分类与从log里看到的结果不一致
**复现步骤**
问题分类列表填写：账单查询、业务办理、便民服务、其他问题
发送内容：你是谁
**预期结果**
其他问题
**相关截图**
<img width="433" alt="图片1" src="https://github.com/labring/FastGPT/assets/8358994/be2ad12e-60bc-4d8f-8350-1c1a3f3fe30b">
<img width="867" alt="图片2" src="https://github.com/labring/FastGPT/assets/8358994/06f4f452-330b-4e98-bbd9-bcdbe2ae7406">

**Comment by c121914yu** [comment]
看着是模型没有直接回答id，而是废话了一堆，并且包含了账单查询这个关键词，所以按顺序会找到账单查询。
