### ISSUE TITLE
我在oneapi中配置m3e出现了问题，是中提示404

### ISSUE THREAD

**Issue by wxc-learn** [labring/FastGPT#1343]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
fastgpt:v4.7
one-api:latest
m3e-large-api:latest
**问题描述**
我使用的docker compose进行部署，期间增加了m3e oneapi，当我使用oneapi配置m3e的时候，点击测试提示404，oneapi配置的m3e路径如下：http://host.docker.internal:6008，期间也使用了m3e.fastgpt.orb.local 这个地址，也是一样的404
**相关截图**
<img width="791" alt="image" src="https://github.com/labring/FastGPT/assets/23518701/55b0c189-e2be-4432-9bc9-0a657f300814">
<img width="1331" alt="image" src="https://github.com/labring/FastGPT/assets/23518701/5fc4b581-e12c-4b1b-b849-27d7b7aeabbf">
<img width="1205" alt="image" src="https://github.com/labring/FastGPT/assets/23518701/0b2368f3-da84-4cf8-876d-b4da740135f1">
<img width="1351" alt="image" src="https://github.com/labring/FastGPT/assets/23518701/b5ee7a5c-6bee-47b3-806e-2615a0740e3f">

**Comment by wxc-learn** [comment]
我是使用的mac m1 进行的搭建

**Comment by nongmo677** [comment]
目前oneapi的测试按钮仅只支持聊天模型，不支持embedding模型
如果要测试embedding模型，建议请使用代码测试，或者使用别的软件手动发送请求进行测试
```python
from openai import OpenAI

client = OpenAI(
    api_key="oneapi的令牌",
    base_url="oneapi的地址/v1/",  # 例如http://192.168.20.59:7891/v1/
)


# compute the embedding of the text
embedding = client.embeddings.create(
    input="你好",
    model="模型名称" # 注意，不是渠道名称
)
print(embedding)
```

**Comment by lonrencn** [comment]
换个镜像，推荐的镜像版本有问题，我换了一个，就好了

**Comment by leoncool23** [comment]
> 换个镜像，推荐的镜像版本有问题，我换了一个，就好了
我也遇到同样问题，请发下你用的镜像版本 谢谢

**Comment by lonrencn** [comment]
> > 换个镜像，推荐的镜像版本有问题，我换了一个，就好了
> > 我也遇到同样问题，请发下你用的镜像版本 谢谢
stawky/m3e-large-api:latest

**Comment by aiyouwoqudi** [comment]
> > > 换个镜像，推荐的镜像版本有问题，我换了一个，就好了
> > > 我也遇到同样问题，请发下你用的镜像版本 谢谢
> > > stawky/m3e-large-api:latest

我用了这个镜像问题依然存在

**Comment by lonrencn** [comment]
> > > > 换个镜像，推荐的镜像版本有问题，我换了一个，就好了
> > > > 我也遇到同样问题，请发下你用的镜像版本 谢谢
> > > > stawky/m3e-large-api:latest
> 
> 我用了这个镜像问题依然存在

404 是正常的，就用官网给的地址，在fast中能用。
