### ISSUE TITLE
tool Missing "tool call id"

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#1347]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1和4.8 preview4

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/156336589/124bdbd9-f9df-4ba9-ae46-4c4e4cf32d70)
![image](https://github.com/labring/FastGPT/assets/156336589/b70e1435-8ce0-4d52-a3e1-2de7d0fdc620)
![image](https://github.com/labring/FastGPT/assets/156336589/dfb43694-e28d-4ae5-b71d-1318d4a7edef)公有云版

**复现步骤**
1.创建tool
2.创建http插件。
3.进行提问，调用插件。

**预期结果**
正常调用插件
**相关截图**

**Comment by c121914yu** [comment]
哪个模型

**Comment by lijiajun1997** [comment]
> 哪个模型

gpt3.5 用公有云版本也是一样

**Comment by c121914yu** [comment]
> > 哪个模型
> 
> gpt3.5 用公有云版本也是一样

公有云是 4.7.1

**Comment by c121914yu** [comment]
![Screenshot_20240501_174403_com.android.chrome.jpg](https://github.com/labring/FastGPT/assets/50446880/be7a36a5-795a-495d-8943-78a315474d53)

![Screenshot_20240501_174550_com.android.chrome.jpg](https://github.com/labring/FastGPT/assets/50446880/585a459a-525a-4848-81bd-30b2cba441a4)

![Screenshot_20240501_174505_com.android.chrome.jpg](https://github.com/labring/FastGPT/assets/50446880/2abcdcac-88f1-44fa-afde-6fbc4b2f3886)

看着是渠道问题，有时候会报错，切微软的就没问题。

**Comment by lijiajun1997** [comment]
解决了 是渠道的问题

**Comment by Aloee1** [comment]
您好，请问是怎么解决的？
我现在使用的是azure openai，在one api的渠道测试里是没问题的，创建知识库搜索测试也没问题，但是创建应用的时候就会报错。
