### ISSUE TITLE
QNAP部署提示

### ISSUE THREAD

**Issue by samqin123** [labring/FastGPT#1349]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
Waiting for MongoDB to start...

WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

部署后，Mongodb会报错，mongo版本和QNAP硬件不适配。也有一批用户使用NAS部署和提供服务，所以请适配qnap和群晖

**复现步骤**
docker-compose yaml文件中修改mongodb版本为4.2.2， 原来版本为5.0.8（aliyun默认），会报错。
mongod: line 19:    10 Illegal instruction     exec docker-entrypoint.sh "$@"
mongod: line 19:    31 Illegal instruction     mongo -u username -p password --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1
Waiting for MongoDB to start...
Waiting for MongoDB to start...
mongod: line 19:    33 Illegal instruction     mongo -u username -p password --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1
mongod: line 19:    35 Illegal instruction     mongo -u username -p password --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1
Waiting for MongoDB to start...
mongod: line 19:    37 Illegal instruction     mongo -u username -p password --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1

**预期结果**
mongodb无法连接，启动应用ok，登陆会报错

**相关截图**

**Comment by c121914yu** [comment]
你用的不是新的 docker compose 吧

**Comment by samqin123** [comment]
是的，我看到了，更新了$$，有效。版本要降到4.4，就可以了
