### ISSUE TITLE
和零一万物的api适配故障

### ISSUE THREAD

**Issue by samqin123** [labring/FastGPT#1350]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 features
- [ x] 我已确认我已升级到最新版本
- [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
调用0-1万物(zero-one)LLM的api接口时，如果通过cow项目进行问答，则会报错。注意：网页版正常。
COW是使用fastgpt标准配置api服务接口，cow的模型是无效的，所以大概率应该是fastgpt的接口和0-1 LLM的response不适配造成的。

换用其它多个模型，均正常。

还有yi-200k和yi-8k的反馈也不正常，可能是prompt的问题，但是也请一并测试。

[ERROR] 2024-05-02 01:10:34 response error: The first message should be user or system (request id: 2024050209103352531655615917164) (request id: 2024050209103343983063481479080) (request id: 2024050209103339028163104224767): {"stack":"Error: 400 The first message should be user or system (request id: 2024050209103352531655615917164) (request id: 2024050209103343983063481479080) (request id: 2024050209103339028163104224767)\n    at eL.generate (/app/projects/app/.next/server/chunks/5092.js:23:67640)\n    at tx.makeStatusError (/app/projects/app/.next/server/chunks/5092.js:23:79051)\n    at tx.makeRequest (/app/projects/app/.next/server/chunks/5092.js:23:79785)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.k [as chatNode] (/app/projects/app/.next/server/chunks/7050.js:90:1025)\n    at async M (/app/projects/app/.next/server/chunks/7050.js:90:5284)\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)\n    at async Promise.all (index 0)\n    at async b (/app/projects/app/.next/server/chunks/7050.js:90:6369)\n    at async /app/projects/app/.next/server/chunks/1282.js:1:3122"}

[ERROR] 2024-05-02 01:10:45 response error: The first message should be user or system (request id: 2024050209104483869359960050175) (request id: 2024050209104476596336813839732) (request id: 2024050209104471358750169580378): {"stack":"Error: 400 The first message should be user or system (request id: 2024050209104483869359960050175) (request id: 2024050209104476596336813839732) (request id: 2024050209104471358750169580378)\n    at eL.generate (/app/projects/app/.next/server/chunks/5092.js:23:67640)\n    at tx.makeStatusError (/app/projects/app/.next/server/chunks/5092.js:23:79051)\n    at tx.makeRequest (/app/projects/app/.next/server/chunks/5092.js:23:79785)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.k [as chatNode] (/app/projects/app/.next/server/chunks/7050.js:90:1025)\n    at async M (/app/projects/app/.next/server/chunks/7050.js:90:5284)\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)\n    at async Promise.all (index 0)\n    at async b (/app/projects/app/.next/server/chunks/7050.js:90:6369)\n    at async /app/projects/app/.next/server/chunks/1282.js:1:3122"}

**应用场景**
fastgpt提供微信自动服务和对话

**相关示例**
微信中提问 “hi”
微信中回复：”你好，我是fastgpt助手”

**Comment by c121914yu** [comment]
印象中wx回复了
