### ISSUE TITLE
Fastgpt Ai对话测试报connection error

### ISSUE THREAD

**Issue by fashaoyou888** [labring/FastGPT#1351]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√ ] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**{
  message: 'Connection error.',
  stack: 'Error: Connection error.\n' +
    '    at af.makeRequest (/app/projects/app/.next/server/chunks/80555.js:21:82237)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Object.x [as chatNode] (/app/projects/app/.next/server/chunks/94900.js:129:1124)\n' +
    '    at async N (/app/projects/app/.next/server/chunks/94900.js:130:2805)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async S (/app/projects/app/.next/server/chunks/94900.js:130:4134)\n' +
    '    at async h (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2771)'
}

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
https://doc.fastai.site/docs/development/faq/#connection-error
文档有
