### ISSUE TITLE
Laf绑定出现Invalid URL

### ISSUE THREAD

**Issue by Cheyenne1025** [labring/FastGPT#1352]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ☑️] 私有部署版本, 具体版本号:  V4.8-preview4

**问题描述, 日志截图**
env: https://laf.run
Laf账户绑定后最后一步确认操作错误:  Invalid URL
主机Clash等代理均已关闭。

同时还尝试更换env依然无效，包括：
“https://laf.run/” -> PAT验证成功，绑定应用失败
“https://laf.run/v1” -> PAT验证成功，绑定应用失败
“https://laf.run/v1/“ -> PAT验证成功，绑定应用失败

**复现步骤**
1. 创建Laf( laf.run ) PAT
2. 在FastGPT上对此进行绑定
3. 选择当前应用
4. 点击更新按钮

**预期结果**
应绑定成功。

**相关截图**
<img width="378" alt="299b1761dc692de76b635c6e72268c8a" src="https://github.com/labring/FastGPT/assets/95136511/d138f16f-cde0-4213-9f48-aa132ee8391a">

**Comment by newfish-cmyk** [comment]
再试试重启下对应laf应用，然后绑定

laf.run 之前不支持

**Comment by bluryar** [comment]
同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定

**Comment by bluryar** [comment]
> 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定

换成 laf.run 也是一样

**Comment by c121914yu** [comment]
> > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> 
> 换成 laf.run 也是一样

laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效

**Comment by bluryar** [comment]
> > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > 
> > 
> > 换成 laf.run 也是一样
> 
> laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效

那 self host 的 laf 能集成到fastgpt吗？

我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。

FastGPTProUrl 是商业版的意思吗？

**Comment by c121914yu** [comment]
> > > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > > 
> > > 
> > > 换成 laf.run 也是一样
> > 
> > laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效
> 
> 那 self host 的 laf 能集成到fastgpt吗？
> 
> 我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。
> 
> FastGPTProUrl 是商业版的意思吗？

新版就可以

**Comment by bluryar** [comment]
> > > > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > > > 
> > > > 
> > > > 换成 laf.run 也是一样
> > > 
> > > 
> > > laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效
> > 
> > 
> > 那 self host 的 laf 能集成到fastgpt吗？
> > 我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。
> > FastGPTProUrl 是商业版的意思吗？
> 
> 新版就可以

感谢回复。

我是从 https://github.com/labring/laf/tree/main/build 进行构建的。构建步骤就是 sealos build -t mylaf/laf . 。我修改了其中几个配置，开启了TLS。

这个构建出来的是新版吗？

**Comment by c121914yu** [comment]
> > > > > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > > > > 
> > > > > 
> > > > > 换成 laf.run 也是一样
> > > > 
> > > > 
> > > > laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效
> > > 
> > > 
> > > 那 self host 的 laf 能集成到fastgpt吗？
> > > 我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。
> > > FastGPTProUrl 是商业版的意思吗？
> > 
> > 新版就可以
> 
> 感谢回复。
> 
> 我是从 https://github.com/labring/laf/tree/main/build 进行构建的。构建步骤就是 sealos build -t mylaf/laf . 。我修改了其中几个配置，开启了TLS。
> 
> 这个构建出来的是新版吗？

🧐这个可能得艾特一下laf，之前测试环境也是额外部署的。
@newfish-cmyk 这个跟进下

**Comment by newfish-cmyk** [comment]
> > > > > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > > > > 
> > > > > 
> > > > > 换成 laf.run 也是一样
> > > > 
> > > > 
> > > > laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效
> > > 
> > > 
> > > 那 self host 的 laf 能集成到fastgpt吗？
> > > 我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。
> > > FastGPTProUrl 是商业版的意思吗？
> > 
> > 
> > 新版就可以
> 
> 感谢回复。
> 
> 我是从 https://github.com/labring/laf/tree/main/build 进行构建的。构建步骤就是 sealos build -t mylaf/laf . 。我修改了其中几个配置，开启了TLS。
> 
> 这个构建出来的是新版吗？

自己构建出来的应该是最新版，https://github.com/labring/laf/pkgs/container/laf 这里是构建好的

**Comment by bluryar** [comment]
> > > > > > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > > > > > 
> > > > > > 
> > > > > > 换成 laf.run 也是一样
> > > > > 
> > > > > 
> > > > > laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效
> > > > 
> > > > 
> > > > 那 self host 的 laf 能集成到fastgpt吗？
> > > > 我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。
> > > > FastGPTProUrl 是商业版的意思吗？
> > > 
> > > 
> > > 新版就可以
> > 
> > 
> > 感谢回复。
> > 我是从 https://github.com/labring/laf/tree/main/build 进行构建的。构建步骤就是 sealos build -t mylaf/laf . 。我修改了其中几个配置，开启了TLS。
> > 这个构建出来的是新版吗？
> 
> 自己构建出来的应该是最新版，https://github.com/labring/laf/pkgs/container/laf 这里是构建好的

这个是我 [folk 的代码](https://github.com/bluryar/laf)，我添加了TLS的相关支持，尽管可以使创建的应用以https访问，但还是连不上fastgpt。

如果有人成功把laf和fastgpt了， 请一定踢我 🤣

**Comment by bluryar** [comment]
> > > > > > > > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 换成 laf.run 也是一样
> > > > > > > 
> > > > > > > 
> > > > > > > laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效
> > > > > > 
> > > > > > 
> > > > > > 那 self host 的 laf 能集成到fastgpt吗？
> > > > > > 我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。
> > > > > > FastGPTProUrl 是商业版的意思吗？
> > > > > 
> > > > > 
> > > > > 新版就可以
> > > > 
> > > > 
> > > > 感谢回复。
> > > > 我是从 https://github.com/labring/laf/tree/main/build 进行构建的。构建步骤就是 sealos build -t mylaf/laf . 。我修改了其中几个配置，开启了TLS。
> > > > 这个构建出来的是新版吗？
> > > 
> > > 
> > > 自己构建出来的应该是最新版，https://github.com/labring/laf/pkgs/container/laf 这里是构建好的
> > 
> > 
> > 这个是我 [folk 的代码](https://github.com/bluryar/laf)，我添加了TLS的相关支持，尽管可以使创建的应用以https访问，但还是连不上fastgpt。
> > 如果有人成功把laf和fastgpt了， 请一定踢我 🤣
> 
> 你的laf应用的openapi文档可以正常访问么

![企业微信截图_17158192275804](https://github.com/labring/FastGPT/assets/48168490/7125e0a7-6780-4658-ae37-3ab0c24e2307)

可以的

**Comment by newfish-cmyk** [comment]
> > > > > > > > > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 换成 laf.run 也是一样
> > > > > > > > 
> > > > > > > > 
> > > > > > > > laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效
> > > > > > > 
> > > > > > > 
> > > > > > > 那 self host 的 laf 能集成到fastgpt吗？
> > > > > > > 我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。
> > > > > > > FastGPTProUrl 是商业版的意思吗？
> > > > > > 
> > > > > > 
> > > > > > 新版就可以
> > > > > 
> > > > > 
> > > > > 感谢回复。
> > > > > 我是从 https://github.com/labring/laf/tree/main/build 进行构建的。构建步骤就是 sealos build -t mylaf/laf . 。我修改了其中几个配置，开启了TLS。
> > > > > 这个构建出来的是新版吗？
> > > > 
> > > > 
> > > > 自己构建出来的应该是最新版，https://github.com/labring/laf/pkgs/container/laf 这里是构建好的
> > > 
> > > 
> > > 这个是我 [folk 的代码](https://github.com/bluryar/laf)，我添加了TLS的相关支持，尽管可以使创建的应用以https访问，但还是连不上fastgpt。
> > > 如果有人成功把laf和fastgpt了， 请一定踢我 🤣
> > 
> > 
> > 你的laf应用的openapi文档可以正常访问么
> 
> ![企业微信截图_17158192275804](https://private-user-images.githubusercontent.com/48168490/330993898-7125e0a7-6780-4658-ae37-3ab0c24e2307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjcyMDAsIm5iZiI6MTcxNTgyNjkwMCwicGF0aCI6Ii80ODE2ODQ5MC8zMzA5OTM4OTgtNzEyNWUwYTctNjc4MC00NjU4LWFlMzctM2FiMGMyNGUyMzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NGFjNTAxZTlkZTJhZjA2YmU0YTU0OTMwNGU5YzcxOTllM2Q0MWU0Y2IzZmY5NDUxNmFmOGEyNzQ2NzFmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yu1ERjfjxZx7pjtXtVpf61_wIsl5YI6UXOICW0Vee8g)
> 
> 可以的
> 
> 我将内网ip解析到这个域名上了，并且我是用tailscale组的内网

<img width="326" alt="image" src="https://github.com/labring/FastGPT/assets/71265218/badfd580-a91a-4726-84fa-0d000ea59e93">
这个链接有效吗

**Comment by c121914yu** [comment]
> > > > > > > > > > 同样的问题，我是self host的laf，PAT也验证通过了，但是没法绑定
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 换成 laf.run 也是一样
> > > > > > > > 
> > > > > > > > 
> > > > > > > > laf.dev才用这个功能，laf应该要最新1个版本，并且重启了runtime才有效
> > > > > > > 
> > > > > > > 
> > > > > > > 那 self host 的 laf 能集成到fastgpt吗？
> > > > > > > 我看是[这段代码导致的异常](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/api/proApi/%5B...path%5D.ts#L17C11-L17C21)。
> > > > > > > FastGPTProUrl 是商业版的意思吗？
> > > > > > 
> > > > > > 
> > > > > > 新版就可以
> > > > > 
> > > > > 
> > > > > 感谢回复。
> > > > > 我是从 https://github.com/labring/laf/tree/main/build 进行构建的。构建步骤就是 sealos build -t mylaf/laf . 。我修改了其中几个配置，开启了TLS。
> > > > > 这个构建出来的是新版吗？
> > > > 
> > > > 
> > > > 自己构建出来的应该是最新版，https://github.com/labring/laf/pkgs/container/laf 这里是构建好的
> > > 
> > > 
> > > 这个是我 [folk 的代码](https://github.com/bluryar/laf)，我添加了TLS的相关支持，尽管可以使创建的应用以https访问，但还是连不上fastgpt。
> > > 如果有人成功把laf和fastgpt了， 请一定踢我 🤣
> > 
> > 你的laf应用的openapi文档可以正常访问么
> 
> ![企业微信截图_17158192275804](https://github.com/labring/FastGPT/assets/48168490/7125e0a7-6780-4658-ae37-3ab0c24e2307)
> 
> 可以的
> 
> 我将内网ip解析到这个域名上了，并且我是用tailscale组的内网

是指laf应用的openapi文档，而不是laf的。如楼上

**Comment by winxin** [comment]
同样的问题，有人解决了么。
[ERROR] 2024-05-23 08:30:13 Api response error: undefined, Invalid URL 
{
  message: 'Invalid URL',
  stack: 'TypeError [ERR_INVALID_URL]: Invalid URL\n' +
    '    at new NodeError (node:internal/errors:405:5)\n' +
    '    at new URL (node:internal/url:611:13)\n' +
    '    at d (/app/projects/app/.next/server/pages/api/proApi/[...path].js:1:2365)'
}

**Comment by nextwa** [comment]
同样问题，试了laf.run和laf.dev 都提示 Invalid URL
