### ISSUE TITLE
使用知识库测试，没几下就宕机

### ISSUE THREAD

**Issue by lonrencn** [labring/FastGPT#1358]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本** --v4.8

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: --v4.8

虚拟机 e3 2685 v3 4c8g  一台虚拟机dev，调用另一台的同样配置的数据库docker
**问题描述, 日志截图**
使用知识库测试，没几下就宕机
![image](https://github.com/labring/FastGPT/assets/158190203/35ff8880-dfc5-4b38-915d-21e302d77550)

**复现步骤**
用知识库测试功能，切换  语义检索  到  全文检索
**预期结果**

**相关截图**

确实是，可以复现，只要用知识库测试，就宕机。

**Comment by c121914yu** [comment]
暂时没遇到，看看有没有人碰到
