### ISSUE TITLE
是否支持将mysql替换成国产达梦数据库

### ISSUE THREAD

**Issue by linerbackers** [labring/FastGPT#1364]
当前很多国企央企在推行国产化，包括服务器国产化，cpu国产化，数据库国产化等。
fastgpt涉及mysql，postgres 两种关系型数据库，特别是mysql，是否fastgpt支持通过修改数据源能够切换到达梦，实现这块的改变？

**Comment by boleyn** [comment]
fastgpt 涉及的是mongo 和pg ，这两个暂时没有比较好的国产替代哦，另外mysql是oneapi 中使用到的，可以注释掉，使用自带的sqllite

**Comment by c121914yu** [comment]
确实莫得，oneapi 的mysql可以取代，mongo没法。
