### ISSUE TITLE
容器重启后，fastgpt登录提示network error

### ISSUE THREAD

**Issue by geminizyz** [labring/FastGPT#1368]
之前一切正常，重启容器后，fastgpt无法登录 提示  network error
![微信截图_20240506140708](https://github.com/labring/FastGPT/assets/167763677/144fb84c-9113-4c90-bd4e-796f5d234202)
docker logs fastgpt 提示：
![微信截图_20240506140905](https://github.com/labring/FastGPT/assets/167763677/1920be37-42e7-40ed-9364-413c74af200b)
rm掉了mongo 重新docker compose 依旧不行

**Comment by geminizyz** [comment]
config.json么？  没问题   之前还好好的

**Comment by MusicOfWind** [comment]
> 之前一切正常，重启容器后，fastgpt无法登录 提示 network error ![微信截图_20240506140708](https://private-user-images.githubusercontent.com/167763677/328092500-144fb84c-9113-4c90-bd4e-796f5d234202.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTI5MDIsIm5iZiI6MTczMTU1MjYwMiwicGF0aCI6Ii8xNjc3NjM2NzcvMzI4MDkyNTAwLTE0NGZiODRjLTkxMTMtNGM5MC1iZDRlLTc5NmY1ZDIzNDIwMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMjUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWJjYWYyNThiMDQ3ZDlkMzM0NjQxYWI1NjcyYmZhYmI4NzJmY2E2YTNjZGE1MWI1M2I2MTAzNjEyYjEyODUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.plh1xbTSTyDtJd5ztWdtAu6vZ_0hA4XlUG1vpe2DIy0) docker logs fastgpt 提示： ![微信截图_20240506140905](https://private-user-images.githubusercontent.com/167763677/328092560-1920be37-42e7-40ed-9364-413c74af200b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTI5MDIsIm5iZiI6MTczMTU1MjYwMiwicGF0aCI6Ii8xNjc3NjM2NzcvMzI4MDkyNTYwLTE5MjBiZTM3LTQyZTctNDBlZC05MzY0LTQxM2M3NGFmMjAwYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMjUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDQzMjI3MDdlZmZkYzM5MmI1NDYwMDRlNTlhMGE0ZjQ2NjFlOTM5OTBhZmZiMjMyODA2NjViYzQ0Mjc4NzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RvvJ730v4hnzeJ7KQY2VXY9rrpY61JIaScl7OIN4dYM) rm掉了mongo 重新docker compose 依旧不行

你好，这个你是怎么解决的？
