### ISSUE TITLE
官网的高级编排例子配置 复制导入进去一片空白

### ISSUE THREAD

**Issue by xingxi521** [labring/FastGPT#1373]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/68280961/9a01a338-104c-4ca8-bc7b-32919f184d0b)
我复制这里高级编排配置，然后导入一片空白
![image](https://github.com/labring/FastGPT/assets/68280961/4d4a36bc-fb90-481e-9ee8-bb47ca587477)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
文档是4.8的

**Comment by xingxi521** [comment]
> 文档是4.8的。公有云还是4.7.1

那就是在线的fastGPT还不支持导入是吧？

**Comment by xingxi521** [comment]
那有没有4.7.1的配置啊？发一个呗，想参考下

**Comment by c121914yu** [comment]
> 那有没有4.7.1的配置啊？发一个呗，想参考下

得翻提交记录~ 找到对应markdown文件。。

**Comment by xingxi521** [comment]
能告诉一下是哪个markdown文件吗 我去翻一下

**Comment by c121914yu** [comment]
> 能告诉一下是哪个markdown文件吗 我去翻一下

在docSite/content目录下的。
直接全文搜下对应标题最快。

**Comment by xingxi521** [comment]
找到了，谢谢
