### ISSUE TITLE
工具调用使用 llama3 70b模型时，调用http请求报错

### ISSUE THREAD

**Issue by romejiang** [labring/FastGPT#1374]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

使用  llama3 70b 模型时报错，显示是返回值不完整。其他的分支是正常的，比如获取时间，说明llama3 模型是通的。
![WechatIMG1703](https://github.com/labring/FastGPT/assets/1053325/a1c0602b-381b-4cf1-a430-0b832dd2909e)
![WechatIMG1704](https://github.com/labring/FastGPT/assets/1053325/2742d227-9b93-4275-866a-82134b9c1b0f)

fastgpt日志报错
![WX20240506-231432@2x](https://github.com/labring/FastGPT/assets/1053325/b89dbbfd-4f04-4daf-82aa-89c2d4e05ac1)

**复现步骤**

docker 私有化部署 ，fastgpt 版本 fastgpt:v4.7.1-alpha2 其他配置都是默认。
具体这篇文章都有描述。
https://romejiang.top/posts/2024/05/fastgpt/

**预期结果**

应该和 ChatGPT 3.5 一样，可以发起HTTP请求。

**相关截图**

其他配置不变，改成 ChatGPT 3.5 接口就正常了。
![WechatIMG1707](https://github.com/labring/FastGPT/assets/1053325/f16925a1-1542-4396-835d-07f347de9d27)

在我电脑上用相同的提示词，llama3 是可以返回正常结果的。
![WechatIMG1705](https://github.com/labring/FastGPT/assets/1053325/32fc6f38-1a38-476c-993e-7b846094f23a)
![WechatIMG1706](https://github.com/labring/FastGPT/assets/1053325/d9191fc2-3679-4138-bc7f-8be64849e0dd)

llama3 70b模型配置 "toolChoice": false,  "functionCall": false,
![WX20240506-230955@2x](https://github.com/labring/FastGPT/assets/1053325/f593c5c3-607e-4755-9faa-683ab0486e94)

**Comment by c121914yu** [comment]
带有requestId，看着是模型接口报错了。
可以log下面的的参数，单独拿出去测试下。

![image](https://github.com/labring/FastGPT/assets/50446880/b82269d2-ddeb-42c5-a94a-5853040e5022)

**Comment by romejiang** [comment]
问题解决了，是因为 llama3 70b默认的max_tokens太小，导致返回的信息不足。但也产生了两个新的疑问。

解决方案，在配置文件中给 llama3 模型默认参数。
![WX20240507-220348@2x](https://github.com/labring/FastGPT/assets/1053325/25269005-cc75-435f-912b-df21a0b2043c)

第一个疑问，在什么环节导致默认的max_tokens如此小？是模型本身？oneapi？还是fastgpt某个地方。

第二个疑问，调用工具的配置界面有 temperature 和 回复上限的参数。但从代码看就没有用到。这是bug还是？

![WX20240507-220422@2x](https://github.com/labring/FastGPT/assets/1053325/85ae744e-afe3-48e5-b601-721928a76741)

![WX20240507-220237@2x](https://github.com/labring/FastGPT/assets/1053325/0c21f5f5-fd23-4a17-b7bf-8e7c369ba012)

**Comment by c121914yu** [comment]
> bug

context=8000，
如果上下文占用了7500，那么max_token只有500.

温度和max_token是页面配置的，default肯定不会生效。
