### ISSUE TITLE
上传图片时出现connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by shitou103** [labring/FastGPT#1377]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/158791771/8263b469-a605-432c-9add-5071cfc77447)

**复现步骤**

**预期结果**
可以正常上传图片并问答
**相关截图**

**Comment by c121914yu** [comment]
看着是你服务挂了。我这都正常使用

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/dfbab145-4fa6-47d7-94af-e6ed00e94187)
确认没问题，请检查自己服务器以及服务是否有重启（OOM之类的）

**Comment by xiafeng111** [comment]
我也是一样的问题，版本号是4.6.9
![微信截图_20240510160033](https://github.com/labring/FastGPT/assets/33710913/eb51207f-1d87-4c77-91e9-6a2dcb183d19)

**Comment by xiafeng111** [comment]
> ![image](https://private-user-images.githubusercontent.com/50446880/329440522-dfbab145-4fa6-47d7-94af-e6ed00e94187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjgyNjUsIm5iZiI6MTcxNTMyNzk2NSwicGF0aCI6Ii81MDQ0Njg4MC8zMjk0NDA1MjItZGZiYWIxNDUtNGZhNi00N2Q3LTk0YWYtZTZlZDAwZTk0MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA3NTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3M2NkZTk1NWYxYTllNzBkNWY0MDllYzI5YTA3ZTM5N2NiZmY1NjEzYzc1ZjZlNzBiOWNlZjgxZTFhYmI3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJJOvOlqkMIckMTVXCvLCIRQQ7G3uTDbYB4ba_NWF94) 确认没问题，请检查自己服务器以及服务是否有重启（OOM之类的）

![Uploading 微信截图_20240510160033.png…]()

**Comment by xiafeng111** [comment]
> ![image](https://private-user-images.githubusercontent.com/50446880/329440522-dfbab145-4fa6-47d7-94af-e6ed00e94187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjgyNjUsIm5iZiI6MTcxNTMyNzk2NSwicGF0aCI6Ii81MDQ0Njg4MC8zMjk0NDA1MjItZGZiYWIxNDUtNGZhNi00N2Q3LTk0YWYtZTZlZDAwZTk0MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA3NTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3M2NkZTk1NWYxYTllNzBkNWY0MDllYzI5YTA3ZTM5N2NiZmY1NjEzYzc1ZjZlNzBiOWNlZjgxZTFhYmI3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJJOvOlqkMIckMTVXCvLCIRQQ7G3uTDbYB4ba_NWF94) 确认没问题，请检查自己服务器以及服务是否有重启（OOM之类的）

我也是一样的问题，版本号4.6.9
![微信截图_20240510160033](https://github.com/labring/FastGPT/assets/33710913/a9fe6dee-71f1-4bb6-9a5b-4ba11a7015f2)
