### ISSUE TITLE
希望增强知识库文章分片

### ISSUE THREAD

**Issue by boleyn** [labring/FastGPT#1390]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
目前的知识库分片对知识的完整性有破坏
希望参考这个 项目 https://github.com/FullStackRetrieval-com/RetrievalTutorials.git
对知识库文章分片进行增强
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
这个项目没啥参考意义呢
