### ISSUE TITLE
聊天对话苹果手机 语音输入效果很差语音文件不全，安卓手机就没有问题

### ISSUE THREAD

**Issue by boleyn** [labring/FastGPT#1392]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7.1
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**
苹果手机 语音输入效果很差语音文件不全，安卓手机就没有问题
**预期结果**

**相关截图**

**Comment by boleyn** [comment]
开启了hhtps ，也配置了whisper 电脑端和安卓都测试了，只有苹果手机不行

**Comment by boleyn** [comment]
![image](https://github.com/labring/FastGPT/assets/24293664/c97a375e-e8eb-4f2d-b2c6-775366b20a9e)
录音抓下来也试听也不缺少东西，就是识别不了

**Comment by boleyn** [comment]
https://github.com/kbumsik/opus-media-recorder 参考这个

**Comment by CloverZhou** [comment]
请问大佬是怎么实现语音输入的？

**Comment by c121914yu** [comment]
> https://github.com/kbumsik/opus-media-recorder 参考这个

这个也不支持ios~

**Comment by sdytzjp** [comment]
> 开启了hhtps ，也配置了whisper 电脑端和安卓都测试了，mac 端谷歌浏览器可以 safari 就不行。初步判断是 Safari浏览器不兼容

请问你测试安卓和电脑端语音识别效果如何？我本地的whisper，效果很差，识别的大部分是繁体字，而且准确率很差

**Comment by c121914yu** [comment]
> > 开启了hhtps ，也配置了whisper 电脑端和安卓都测试了，mac 端谷歌浏览器可以 safari 就不行。初步判断是 Safari浏览器不兼容
> 
> 请问你测试安卓和电脑端语音识别效果如何？我本地的whisper，效果很差，识别的大部分是繁体字，而且准确率很差

用阿里的新模型。效果好，性能好

**Comment by sdytzjp** [comment]
请问阿里具体模型名称是什么


对接方式跟对接llm一样吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月24日(周三) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 聊天对话苹果手机 语音输入效果很差语音文件不全，安卓手机就没有问题 (Issue #1392)




   
开启了hhtps ，也配置了whisper 电脑端和安卓都测试了，mac 端谷歌浏览器可以 safari 就不行。初步判断是 Safari浏览器不兼容
  
请问你测试安卓和电脑端语音识别效果如何？我本地的whisper，效果很差，识别的大部分是繁体字，而且准确率很差
  
用阿里的新模型。效果好，性能好

**Comment by Charmnut** [comment]
> 请问阿里具体模型名称是什么 对接方式跟对接llm一样吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月24日(周三) 晚上9:23 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [labring/FastGPT] 聊天对话苹果手机 语音输入效果很差语音文件不全，安卓手机就没有问题 (Issue #1392) 开启了hhtps ，也配置了whisper 电脑端和安卓都测试了，mac 端谷歌浏览器可以 safari 就不行。初步判断是 Safari浏览器不兼容 请问你测试安卓和电脑端语音识别效果如何？我本地的whisper，效果很差，识别的大部分是繁体字，而且准确率很差 用阿里的新模型。效果好，性能好 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

可以用Belle-whisper-large-v3-zh，显存只占4-5G，效果还可以，兼容oneapi只定向whisper-1的神奇特性，oneapi接入之后fastgpt什么都不用配置就能用了

**Comment by Charmnut** [comment]
> > 开启了hhtps ，也配置了whisper 电脑端和安卓都测试了，mac 端谷歌浏览器可以 safari 就不行。初步判断是 Safari浏览器不兼容
> 
> 请问你测试安卓和电脑端语音识别效果如何？我本地的whisper，效果很差，识别的大部分是繁体字，而且准确率很差

可以用Belle-whisper-large-v3-zh，显存只占4-5G，效果还可以，也兼容oneapi只定向whisper-1的特性

**Comment by sdytzjp** [comment]
繁体问题我用openCC解决了




JP
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月12日(星期四) 上午9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] 聊天对话苹果手机 语音输入效果很差语音文件不全，安卓手机就没有问题 (Issue #1392)





   
开启了hhtps ，也配置了whisper 电脑端和安卓都测试了，mac 端谷歌浏览器可以 safari 就不行。初步判断是 Safari浏览器不兼容
  
请问你测试安卓和电脑端语音识别效果如何？我本地的whisper，效果很差，识别的大部分是繁体字，而且准确率很差
  
可以用Belle-whisper-large-v3-zh，显存只占4-5G，效果还可以，也兼容oneapi只定向whisper-1的特性

**Comment by nightzjp** [comment]
ios生成的音频文件可以直接手机播放，whisper模型不能识别；mac生成的音频文件手机不能播放，whisper模型可以正常识别。。好奇怪
