### ISSUE TITLE
如何修改默认的提示词

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1395]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/40045458/3850f238-0e15-4311-b981-5b7496dcaca3)

一直都是返回为空
我打印了request以及自己用curl方法实现同样的功能
![image](https://github.com/labring/FastGPT/assets/40045458/0f317318-41ea-44df-a490-b1f96bdb0b2b)

我的问题/疑问是：
1. 内容提取的模板中，没有使用输入的用户问题，导致的输出为空？
2. 如何修改默认的内容提取的模板
**复现步骤**

**预期结果**

**相关截图**

**Comment by xiaoToby** [comment]
@c121914yu @nongmo677

**Comment by nongmo677** [comment]
1. 你先学会用一些简单的例子提取看是否成功吧
2. 你做测试要看组件运行过程的话，点击查看详情就好了
3. 你想用提示词触发，建议先把llama3模型配置中的这部分设为 "toolChoice": false, "functionCall": false

这部分受限于模型本身的能力
想测试模型是否能实现这个功能，建议先请直接构建你的指令直接和模型进行对话看返回值，能够正确返回结构化数据说明模型能力还行，提示词的部分请自己探索，或者查看fastgpt提供的模板进行改造
![image](https://github.com/labring/FastGPT/assets/31816449/f7bfa44a-e8a6-4ec4-a0bb-30d052138d1f)

然后再根据内容提取的一些特性组装起来就得到结果了，请自行探索
![image](https://github.com/labring/FastGPT/assets/31816449/dcce2e20-024c-4c85-b9d8-29ad2c64a64f)

**Comment by xiaoToby** [comment]
> 3\. 你想用提示词触发，建议先把llama3模型配置中的这部分设为 "toolChoice": false, "functionCall": false

好的，感谢你的指导

还有一个疑问，关于config.json文档中的这些字段，能否说明以下具体的意义吗？
![image](https://github.com/labring/FastGPT/assets/40045458/3b4a365b-b650-4c31-8ef8-4f986bf0341a)

还有在defaultConfig中是否能配置图中的这些配置项
![image](https://github.com/labring/FastGPT/assets/40045458/405f98a3-3cfe-4217-a38d-c13dfa1d89e5)

**Comment by 23357** [comment]
https://doc.fastai.site/docs/development/configuration/

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/ad0c353d-52b1-4c80-affd-207073ed976f)
方便分享一下完整提取提示词的内容吗？

@nongmo677

**Comment by c121914yu** [comment]
默认提示词：
![image](https://github.com/labring/FastGPT/assets/50446880/7cd27b70-9929-4eed-8b62-e3612e08c1d1)


自定义提示词：
![image](https://github.com/labring/FastGPT/assets/50446880/097d141c-2ca9-4fee-96a5-f37b991d5d65)
![image](https://github.com/labring/FastGPT/assets/50446880/14ece03c-6516-462a-9303-90f3face3435)

**Comment by nongmo677** [comment]
> ![image](https://private-user-images.githubusercontent.com/40045458/329438030-ad0c353d-52b1-4c80-affd-207073ed976f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDkwOTUsIm5iZiI6MTcxNTMwODc5NSwicGF0aCI6Ii80MDA0NTQ1OC8zMjk0MzgwMzAtYWQwYzM1M2QtNTJiMS00YzgwLWFmZmQtMjA3MDczZWQ5NzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAyMzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZTViYjcxMGVjOTAyNzQ2MzdkODIxNTI4OGEyYWMzNWUzYjg2ZGMyYjM3ZmM0NWM5ZGY5MDYzMTFhMWM1MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1R0zoEWgh9MtvxhBd9gW9eGGapvUR8UvvG9Df42mJs4) 方便分享一下完整提取提示词的内容吗？
> 
> @nongmo677

你直接搜fastgpt内部设置的就好了
```
你可以从 <对话记录></对话记录> 中提取指定 JSON 信息，你仅需返回 JSON 字符串，无需回答问题。
<提取要求>
{{description}}
</提取要求>
<字段说明>
1. 下面的 JSON 字符串均按照 JSON Schema 的规则描述。
2. key 代表字段名；description 代表字段的描述；enum 是可选值，代表可选的 value。
3. 如果没有可提取的内容，忽略该字段。
4. 本次需提取的JSON Schema：{{json}}
</字段说明>
<对话记录>
{{text}}
</对话记录>
```

**Comment by xiaoToby** [comment]
> > ![image](https://private-user-images.githubusercontent.com/40045458/329438030-ad0c353d-52b1-4c80-affd-207073ed976f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDkwOTUsIm5iZiI6MTcxNTMwODc5NSwicGF0aCI6Ii80MDA0NTQ1OC8zMjk0MzgwMzAtYWQwYzM1M2QtNTJiMS00YzgwLWFmZmQtMjA3MDczZWQ5NzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAyMzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZTViYjcxMGVjOTAyNzQ2MzdkODIxNTI4OGEyYWMzNWUzYjg2ZGMyYjM3ZmM0NWM5ZGY5MDYzMTFhMWM1MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1R0zoEWgh9MtvxhBd9gW9eGGapvUR8UvvG9Df42mJs4) 方便分享一下完整提取提示词的内容吗？
> > @nongmo677
> 
> 你直接搜fastgpt内部设置的就好了
> 
> ```
> 你可以从 <对话记录></对话记录> 中提取指定 JSON 信息，你仅需返回 JSON 字符串，无需回答问题。
> <提取要求>
> {{description}}
> </提取要求>
> <字段说明>
> 1. 下面的 JSON 字符串均按照 JSON Schema 的规则描述。
> 2. key 代表字段名；description 代表字段的描述；enum 是可选值，代表可选的 value。
> 3. 如果没有可提取的内容，忽略该字段。
> 4. 本次需提取的JSON Schema：{{json}}
> </字段说明>
> <对话记录>
> {{text}}
> </对话记录>
> ```

![image](https://github.com/labring/FastGPT/assets/40045458/76e1d7cf-49ff-4bae-acb8-de15eea226d1)
我就是觉得默认的提取提示词模板，好像不好用，在测试llama3时，没有用到<用户问题>, 返回的一直时{},而我自己在命令行中用curl方法测试api接口，就能提取出来

**Comment by xiaoToby** [comment]
关于如何提取多个关键字的值
同样的内容和提示词，
在高级编排中的文本内容提取工具中的效果如下图所示：
![image](https://github.com/labring/FastGPT/assets/40045458/b0943187-f688-4146-88a4-a124cffdff68)

在对话框中的效果如下图所示：
![image](https://github.com/labring/FastGPT/assets/40045458/20a9282d-4472-47db-81f1-b98323a2d7cc)

1. 是否是因为我图中的内容还不够好？,如果是，有什么好的意见或提示词版本？
![image](https://github.com/labring/FastGPT/assets/40045458/54af627f-330a-4fdf-aafc-98ea06b168f3)
2.还是因为fastgpt内置的内容提取的提示词需要修改
![image](https://github.com/labring/FastGPT/assets/40045458/cab61a66-e0c1-4446-a72c-f98844c590e1)


@nongmo677 @c121914yu

**Comment by SDAIer** [comment]
咋解决的
