### ISSUE TITLE
自定义反馈结果报错

### ISSUE THREAD

**Issue by colinyyj** [labring/FastGPT#1396]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ ✔] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.0-preview4
- [ ] 公有云版本
- [ ✔] 私有部署版本, 具体版本号:  4.8.0-preview4

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/5284443/d3b70e54-1c17-4088-976e-7099b00903af)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
中间加一层文本加工试试？

**Comment by c121914yu** [comment]
用 alpha 版本测试

**Comment by colinyyj** [comment]
是用的alpha版本

**Comment by c121914yu** [comment]
似乎就debug报错，正常用不会

**Comment by colinyyj** [comment]
> 似乎就debug报错，正常用不会

嗯，但是还是没有任何返回
![image](https://github.com/labring/FastGPT/assets/5284443/0c6bad18-4904-474b-926b-45b2ebb41021)

明天我再去看看代码

**Comment by c121914yu** [comment]
> > 似乎就debug报错，正常用不会
> 
> 嗯，但是还是没有任何返回 ![image](https://private-user-images.githubusercontent.com/5284443/328906968-0c6bad18-4904-474b-926b-45b2ebb41021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzU1MzksIm5iZiI6MTcxNTE3NTIzOSwicGF0aCI6Ii81Mjg0NDQzLzMyODkwNjk2OC0wYzZiYWQxOC00OTA0LTQ3NGItOTI2Yi00NWIyZWJiNDEwMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTMzMzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI4MjkzZDg5MmNlZjMzMzA1YWU4OWE5NTRiZmYyYWYyZDI4YjczNzhlNGU1MmRhOTljM2M5YzFiODVjM2QxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._LCG7x5yIf5KqOBflL9_erJNDMyb6oVlxoZxzVeKjwA)
> 
> 明天我再去看看代码

我本地测测。返回这个就是正常了。
这个插件确实是没返回值的，测试的话会打印一个文案，发布后使用会直接给数据库插入记录。

**Comment by c121914yu** [comment]
我找到了，是因为HTTP模块给它打印了内容~ debug 模式应该是非 stream 的，这里输出后，http响应体就不是JSON了。
![image](https://github.com/labring/FastGPT/assets/50446880/98012eaa-65f6-403b-9f4b-9154eee2a725)
