### ISSUE TITLE
调用DeepSeek报400错误，非流正常

### ISSUE THREAD

**Issue by zhiqing0205** [labring/FastGPT#1400]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本 [V4.8-alpha2](https://github.com/labring/FastGPT/releases/tag/v4.8-alpha2)
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
bad_response_status_code bad response status code 400
DeepSeek API能够正常调用且支持流式，在高级编排调试非流是正常的
**复现步骤**

**预期结果**

**相关截图**

**Comment by zhiqing0205** [comment]
可以自定义流式/非流吗

**Comment by buaajjg** [comment]
高级编排在哪能改成非流式的呀

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/ed457c9a-8809-465f-874e-c05735b2cfc6)
没遇到，正常使用~

**Comment by buaajjg** [comment]
> ![image](https://private-user-images.githubusercontent.com/50446880/329120963-ed457c9a-8809-465f-874e-c05735b2cfc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjczMTYsIm5iZiI6MTcxNTIyNzAxNiwicGF0aCI6Ii81MDQ0Njg4MC8zMjkxMjA5NjMtZWQ0NTdjOWEtODgwOS00NjVmLTg3NGUtYzA1NzM1YjJjZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjI5MzhkYzE5YTRkOWIxOGU2YTQ1NzA3YWQ2MjMyZTExNGU1NzcwMmQ0MzMyMjQ4N2MxNzA2ZTY3MzNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LzMOd6KU_7QCNJJFNsrXJALjU1zDeJT7Y-nWZfxF08A) 没遇到，正常使用~

你加上知识库， 再问问 你是谁   马云是谁之类的问题 看看  我这样是报400 的   单独问也没问题

**Comment by c121914yu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/50446880/329120963-ed457c9a-8809-465f-874e-c05735b2cfc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjczMTYsIm5iZiI6MTcxNTIyNzAxNiwicGF0aCI6Ii81MDQ0Njg4MC8zMjkxMjA5NjMtZWQ0NTdjOWEtODgwOS00NjVmLTg3NGUtYzA1NzM1YjJjZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjI5MzhkYzE5YTRkOWIxOGU2YTQ1NzA3YWQ2MjMyZTExNGU1NzcwMmQ0MzMyMjQ4N2MxNzA2ZTY3MzNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LzMOd6KU_7QCNJJFNsrXJALjU1zDeJT7Y-nWZfxF08A) 没遇到，正常使用~
> 
> 你加上知识库， 再问问 你是谁   马云是谁之类的问题 看看  我这样是报400 的   单独问也没问题

知识库有敏感内容吧？

**Comment by zhiqing0205** [comment]
> > > <img alt="image" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/50446880/329120963-ed457c9a-8809-465f-874e-c05735b2cfc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjczMTYsIm5iZiI6MTcxNTIyNzAxNiwicGF0aCI6Ii81MDQ0Njg4MC8zMjkxMjA5NjMtZWQ0NTdjOWEtODgwOS00NjVmLTg3NGUtYzA1NzM1YjJjZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjI5MzhkYzE5YTRkOWIxOGU2YTQ1NzA3YWQ2MjMyZTExNGU1NzcwMmQ0MzMyMjQ4N2MxNzA2ZTY3MzNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LzMOd6KU_7QCNJJFNsrXJALjU1zDeJT7Y-nWZfxF08A"> 没遇到，正常使用~
> > 
> > 
> > 你加上知识库， 再问问 你是谁   马云是谁之类的问题 看看  我这样是报400 的   单独问也没问题
> 
> 知识库有敏感内容吧？

真有可能，这个审查好像很敏感，我把引用上限调小就可以了(可能是少引用了敏感内容)

**Comment by c121914yu** [comment]
> > > > <img alt="image" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/50446880/329120963-ed457c9a-8809-465f-874e-c05735b2cfc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjczMTYsIm5iZiI6MTcxNTIyNzAxNiwicGF0aCI6Ii81MDQ0Njg4MC8zMjkxMjA5NjMtZWQ0NTdjOWEtODgwOS00NjVmLTg3NGUtYzA1NzM1YjJjZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjI5MzhkYzE5YTRkOWIxOGU2YTQ1NzA3YWQ2MjMyZTExNGU1NzcwMmQ0MzMyMjQ4N2MxNzA2ZTY3MzNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LzMOd6KU_7QCNJJFNsrXJALjU1zDeJT7Y-nWZfxF08A"> 没遇到，正常使用~
> > > 
> > > 
> > > 你加上知识库， 再问问 你是谁   马云是谁之类的问题 看看  我这样是报400 的   单独问也没问题
> > 
> > 知识库有敏感内容吧？
> 
> 真有可能，这个审查好像很敏感，我把引用上限调小就可以了(可能是少引用了敏感内容)

如果是偶尔不能用，估计是这个问题了。

**Comment by buaajjg** [comment]
> > > > > <img alt="image" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/50446880/329120963-ed457c9a-8809-465f-874e-c05735b2cfc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjczMTYsIm5iZiI6MTcxNTIyNzAxNiwicGF0aCI6Ii81MDQ0Njg4MC8zMjkxMjA5NjMtZWQ0NTdjOWEtODgwOS00NjVmLTg3NGUtYzA1NzM1YjJjZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjI5MzhkYzE5YTRkOWIxOGU2YTQ1NzA3YWQ2MjMyZTExNGU1NzcwMmQ0MzMyMjQ4N2MxNzA2ZTY3MzNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LzMOd6KU_7QCNJJFNsrXJALjU1zDeJT7Y-nWZfxF08A"> 没遇到，正常使用~
> > > > 
> > > > 
> > > > 你加上知识库， 再问问 你是谁   马云是谁之类的问题 看看  我这样是报400 的   单独问也没问题
> > > 
> > > 
> > > 知识库有敏感内容吧？
> > 
> > 
> > 真有可能，这个审查好像很敏感，我把引用上限调小就可以了(可能是少引用了敏感内容)
> 
> 如果是偶尔不能用，估计是这个问题了。
![企业微信截图_1715233545647](https://github.com/labring/FastGPT/assets/14844277/bc457a40-d591-4fe3-b98e-b1d98a48c9d3)

敏感词是中共党员   老板的履历违规  哈哈哈

**Comment by c121914yu** [comment]
> > > > > > <img alt="image" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/50446880/329120963-ed457c9a-8809-465f-874e-c05735b2cfc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjczMTYsIm5iZiI6MTcxNTIyNzAxNiwicGF0aCI6Ii81MDQ0Njg4MC8zMjkxMjA5NjMtZWQ0NTdjOWEtODgwOS00NjVmLTg3NGUtYzA1NzM1YjJjZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjI5MzhkYzE5YTRkOWIxOGU2YTQ1NzA3YWQ2MjMyZTExNGU1NzcwMmQ0MzMyMjQ4N2MxNzA2ZTY3MzNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LzMOd6KU_7QCNJJFNsrXJALjU1zDeJT7Y-nWZfxF08A"> 没遇到，正常使用~
> > > > > 
> > > > > 
> > > > > 你加上知识库， 再问问 你是谁   马云是谁之类的问题 看看  我这样是报400 的   单独问也没问题
> > > > 
> > > > 
> > > > 知识库有敏感内容吧？
> > > 
> > > 
> > > 真有可能，这个审查好像很敏感，我把引用上限调小就可以了(可能是少引用了敏感内容)
> > 
> > 
> > 如果是偶尔不能用，估计是这个问题了。
> > ![企业微信截图_1715233545647](https://private-user-images.githubusercontent.com/14844277/329139433-bc457a40-d591-4fe3-b98e-b1d98a48c9d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzM5NTgsIm5iZiI6MTcxNTIzMzY1OCwicGF0aCI6Ii8xNDg0NDI3Ny8zMjkxMzk0MzMtYmM0NTdhNDAtZDU5MS00ZmUzLWI5OGUtYjFkOThhNDhjOWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA1NDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMDkzMTY4ZTc3Y2NhZTAxOWNjNjgwZTA2MTFhNDUzODVhNGI0ZTQ4ZjhhNzQyNWQ3MjZlMWUyYWZiYmU3MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2yBP7G-A3NZ2ZF6Ks-BGpuml40-3a3R1v-zqKwnXVW0)
> 
> 敏感词是中共党员 老板的履历违规 哈哈哈

乐hh

**Comment by cubxxw** [comment]
+ 1 me too ~

![img_v3_02cb_675ef0a9-2a3b-46ba-8085-5b26a24038fg](https://github.com/labring/FastGPT/assets/86140903/efa09037-a7db-41c8-aa9f-4da01d4dc99b)
