### ISSUE TITLE
docker mysql 镜像拉取失败

### ISSUE THREAD

**Issue by xianyu110** [labring/FastGPT#1401]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
version：3.3
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"

docker compose pull 拉取mysql镜像超时失败
**复现步骤**
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/53889513/8d4e7136-f66b-4586-85ff-c0f4e28761b2)
![image](https://github.com/labring/FastGPT/assets/53889513/0463578c-8d69-445a-a37d-c6bac9a59544)

**Comment by xianyu110** [comment]
后面我注释了mysql 的docker镜像

**Comment by c121914yu** [comment]
网络不行吧？
