### ISSUE TITLE
调用Searxng结果无效

### ISSUE THREAD

**Issue by utopeadia** [labring/FastGPT#1405]
我自行设计了一套流程作为工具引入，但是编排后发现并没有成功调用，请求得到帮助。
逻辑如下：首先通过一个AI提取关键词，将关键词使用searxng进行搜索同时返回json，因为没有找到json配置所以我直接再次调用ai进行分析，这套流程尽管会消耗token但是分支单独调试是能够完美跑通的。但是我不太清楚如何将最终AI回复的结果作为工具引入，请求得到帮助
![image](https://github.com/labring/FastGPT/assets/98788152/d8b51e8f-67df-4026-8c0a-320cca9bea48)

**Comment by lijiajun1997** [comment]
加一层文本加工 把问题和查询结果都引用上 然后AI对话的问题从文本加工中取

**Comment by utopeadia** [comment]
> 加一层文本加工 把问题和查询结果都引用上 然后AI对话的问题从文本加工中取

您的意思是使用指定回复吗？有一点不太明白，能详细解释下吗

**Comment by lijiajun1997** [comment]
> > 加一层文本加工 把问题和查询结果都引用上 然后AI对话的问题从文本加工中取
> 
> 您的意思是使用指定回复吗？有一点不太明白，能详细解释下吗

![image](https://github.com/labring/FastGPT/assets/156336589/938764de-131d-4946-b462-c2d6d8f862a1)

**Comment by utopeadia** [comment]
> > > 加一层文本加工 把问题和查询结果都引用上 然后AI对话的问题从文本加工中取
> > 
> > 
> > 您的意思是使用指定回复吗？有一点不太明白，能详细解释下吗
> 
> ![image](https://private-user-images.githubusercontent.com/156336589/329209849-938764de-131d-4946-b462-c2d6d8f862a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTAxMzUsIm5iZiI6MTcxNTI0OTgzNSwicGF0aCI6Ii8xNTYzMzY1ODkvMzI5MjA5ODQ5LTkzODc2NGRlLTEzMWQtNDk0Ni1iNDYyLWMyZDZkOGY4NjJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMDE3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTA4MTMwZWMyYWZkMWFkODc0NzNhZGNjOGY4Njk2ZDg0ODc5NDRjM2JmNGI5OTFjYTMxYjRhODRkODhiZWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eA01N5NWpLW44kL5gU1jV1w4CacJRiqG6ynawYhkG00)

我的想法是引用数据库同时进行网络搜索，对数据库和网络内容都作为数据库的内容。如果只是单独搜索的话倒是没啥问题
<img width="864" alt="image" src="https://github.com/labring/FastGPT/assets/98788152/ab3675de-331e-4d54-8257-d2d79f4094d0">

**Comment by lijiajun1997** [comment]
> > > > 加一层文本加工 把问题和查询结果都引用上 然后AI对话的问题从文本加工中取
> > > 
> > > 
> > > 您的意思是使用指定回复吗？有一点不太明白，能详细解释下吗
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/156336589/329209849-938764de-131d-4946-b462-c2d6d8f862a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTAxMzUsIm5iZiI6MTcxNTI0OTgzNSwicGF0aCI6Ii8xNTYzMzY1ODkvMzI5MjA5ODQ5LTkzODc2NGRlLTEzMWQtNDk0Ni1iNDYyLWMyZDZkOGY4NjJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMDE3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTA4MTMwZWMyYWZkMWFkODc0NzNhZGNjOGY4Njk2ZDg0ODc5NDRjM2JmNGI5OTFjYTMxYjRhODRkODhiZWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eA01N5NWpLW44kL5gU1jV1w4CacJRiqG6ynawYhkG00)
> 
> 我的想法是引用数据库同时进行网络搜索，对数据库和网络内容都作为数据库的内容。如果只是单独搜索的话倒是没啥问题 <img alt="image" width="864" src="https://private-user-images.githubusercontent.com/98788152/329211786-ab3675de-331e-4d54-8257-d2d79f4094d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTA5MTYsIm5iZiI6MTcxNTI1MDYxNiwicGF0aCI6Ii85ODc4ODE1Mi8zMjkyMTE3ODYtYWIzNjc1ZGUtMzMxZS00ZDU0LTgyNTctZDJkNzlmNDA5NGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEwMzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MTA5ZDIzOGU2YjZmZWNkOTAzYWJlNDMzYjY1OTVjZDRkMTY3NDk2NmMwODJiNTEwYjU2MTQ1NjJmNGY5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IqG47BekIf_RJMzgBEvRxHh_B_-qqSO1hBEutZYNfgA">

知识库正常接到AI模型，联网搜索的结果用我上图的模式插到问题前面，这样两部分都会被参考
![image](https://github.com/labring/FastGPT/assets/156336589/44d3c439-2097-4907-98fb-8e883ad6ab9a)

**Comment by utopeadia** [comment]
> > > > > 加一层文本加工 把问题和查询结果都引用上 然后AI对话的问题从文本加工中取
> > > > 
> > > > 
> > > > 您的意思是使用指定回复吗？有一点不太明白，能详细解释下吗
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/156336589/329209849-938764de-131d-4946-b462-c2d6d8f862a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTAxMzUsIm5iZiI6MTcxNTI0OTgzNSwicGF0aCI6Ii8xNTYzMzY1ODkvMzI5MjA5ODQ5LTkzODc2NGRlLTEzMWQtNDk0Ni1iNDYyLWMyZDZkOGY4NjJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMDE3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTA4MTMwZWMyYWZkMWFkODc0NzNhZGNjOGY4Njk2ZDg0ODc5NDRjM2JmNGI5OTFjYTMxYjRhODRkODhiZWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eA01N5NWpLW44kL5gU1jV1w4CacJRiqG6ynawYhkG00)
> > 
> > 
> > 我的想法是引用数据库同时进行网络搜索，对数据库和网络内容都作为数据库的内容。如果只是单独搜索的话倒是没啥问题 <img alt="image" width="864" src="https://private-user-images.githubusercontent.com/98788152/329211786-ab3675de-331e-4d54-8257-d2d79f4094d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTA5MTYsIm5iZiI6MTcxNTI1MDYxNiwicGF0aCI6Ii85ODc4ODE1Mi8zMjkyMTE3ODYtYWIzNjc1ZGUtMzMxZS00ZDU0LTgyNTctZDJkNzlmNDA5NGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEwMzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MTA5ZDIzOGU2YjZmZWNkOTAzYWJlNDMzYjY1OTVjZDRkMTY3NDk2NmMwODJiNTEwYjU2MTQ1NjJmNGY5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IqG47BekIf_RJMzgBEvRxHh_B_-qqSO1hBEutZYNfgA">
> 
> 知识库正常接到AI模型，联网搜索的结果用我上图的模式插到问题前面，这样两部分都会被参考 ![image](https://private-user-images.githubusercontent.com/156336589/329215527-44d3c439-2097-4907-98fb-8e883ad6ab9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTI0OTgsIm5iZiI6MTcxNTI1MjE5OCwicGF0aCI6Ii8xNTYzMzY1ODkvMzI5MjE1NTI3LTQ0ZDNjNDM5LTIwOTctNDkwNy05OGZiLThlODgzYWQ2YWI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMDU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzM4OWJmNmYzNGFmMDAyMDI1MWRjMmUyN2NkNGQyYmY1MDZlZjE3ZDQ3ZDBiMmE0YjFmZmU4Yzg5YjUzMjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0G2tmLlP0XSkE-4Vz2E5ntb7nKWhsPGowJVhwH7S1Hc)

成功跑通，十分感谢！
