### ISSUE TITLE
支持知识库回答后的超链接功能吗

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1407]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
知识库回答后能支持【智能导诊】的超链接吗
而不是加个网址的那种
![image](https://github.com/labring/FastGPT/assets/50564015/a763c42c-fd4c-428e-989d-5f3b393c71ff)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
可以在知识库中用markdown的格式设置链接 
![image](https://github.com/labring/FastGPT/assets/156336589/511f2d53-011e-4f4d-9714-3d27f7cc67f0)

**Comment by sdytzjp** [comment]
请问图片格式如何处理。例如以下markdown格式就不生效
![图片](http://www.xxxx.com/1.png)
