### ISSUE TITLE
如何修改上传知识库中的分段数据

### ISSUE THREAD

**Issue by zhaoyuchen1128** [labring/FastGPT#1408]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我上传PDF以后，分段的数据由于本身PDF格式等原因不是很规范导致问答效果一般，如何通过代码交互形式或者得到这些数据并修改？
**应用场景**

**相关示例**

**Comment by xiaoToby** [comment]
建议：优化数据结构，采用合适的分段规则

**Comment by lijiajun1997** [comment]
可以自己用python切割分段，然后用csv导入
