### ISSUE TITLE
FastGPT本地部署最好使用Linux系统吗

### ISSUE THREAD

**Issue by zixiaotan21** [labring/FastGPT#1409]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x]私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我想在本地部署FastGPT，最好使用Linux系统吗？我的电脑是Windoxs系统，是否需要用 WSL 2 后端在 Windows 中安装 Docker Desktop呢？

**Comment by lijiajun1997** [comment]
WSL 2 后端在 Windows 中安装 Docker Desktop就可以

**Comment by lijiajun1997** [comment]
最简单的还是在sealos里部署

**Comment by c121914yu** [comment]
都行。。但是服务器一般目前都是unbuntu好点~没这么多坑，，window不适合做云服务器部署。
本地开发无所谓，啥都可以。

**Comment by zixiaotan21** [comment]
> WSL 2 后端在 Windows 中安装 Docker Desktop就可以

好滴好滴，我试试看，感谢感谢！
