### ISSUE TITLE
FastGPT接入企业微信失败

### ISSUE THREAD

**Issue by zixiaotan21** [labring/FastGPT#1412]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x]我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x]公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

按照说明文档的详细步骤，尝试将FastGPT接入企业微信。遇到的问题如下：
1. 企业微信中提问没有回答
<img width="507" alt="image" src="https://github.com/labring/FastGPT/assets/142043181/e24a4fda-0140-4b62-8972-3ada7c5a92af">

2. Laf运行结果显示“签名验证失败"
<img width="745" alt="image" src="https://github.com/labring/FastGPT/assets/142043181/f857bbcd-7c90-42a6-a15b-138f040222d1">

**预期结果**
我猜测失败的原因如下：
1. 文档提供的那几个需要企业微信可信的 IP 地址不对？
2. FastGPT 的 API 接口网址不对，需要根据 FastGPT 提供的网址进行修改吗？

**Comment by c121914yu** [comment]
@zuoFeng59556 这个看看？

**Comment by KanoSang** [comment]
可以用别的项目接入

**Comment by KanoSang** [comment]
> > 可以用别的项目接入
> 
> 别的项目指的是什么项目呀？

chatgpt on wechat

**Comment by zixiaotan21** [comment]
噢噢好的！我看看试试，谢谢啦！

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
