### ISSUE TITLE
docker部署fastgpt到线上服务器时，打开网页显示连接失败

### ISSUE THREAD

**Issue by xiaomingcimy** [labring/FastGPT#1413]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
<img width="641" alt="b8b68a767165d45fb54158f3274c5ce" src="https://github.com/labring/FastGPT/assets/82130409/d4c7706c-881a-4080-8c40-30c6bd2e627e">

**复现步骤**

**预期结果**

**相关截图**

**Comment by dooonabe** [comment]
看一下mysql容器启动成功了吗

**Comment by xiaomingcimy** [comment]
> 看一下mysql容器启动成功了吗

<img width="644" alt="1715240894166" src="https://github.com/labring/FastGPT/assets/82130409/fc41e0e5-8f0d-42ed-be58-bf041baf6ecf">

**Comment by xiaomingcimy** [comment]
解决了，是3000端口没有放行
