### ISSUE TITLE
“发布应用”-“免登录窗口”，代码包含 http 链接，插入 https 页面后提示 This request has been blocked; the content must be served over HTTPS

### ISSUE THREAD

**Issue by michael-xgw** [labring/FastGPT#1417]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: v4.7.1-fix2

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
![cfc6f346d7c56dd75076cf1f6a89fbe](https://github.com/labring/FastGPT/assets/51981994/f0db46f4-d866-47fc-930e-d764827d7f55)

**Comment by lijiajun1997** [comment]
用http的网页确实无法用iframe嵌入的，可以做跳转。

**Comment by michael-xgw** [comment]
> 用http的网页确实无法用iframe嵌入的，可以做跳转。

如何跳转，方便详细说一下吗？

**Comment by lijiajun1997** [comment]
> > 用http的网页确实无法用iframe嵌入的，可以做跳转。
> 
> 如何跳转，方便详细说一下吗？
`<!DOCTYPE html>
<html>
<head>
<meta http-equiv="refresh" content="0; URL=http://xxx">
</head>
<body>
</body>
</html>
`

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/c488cd27-f2c7-4f7d-9067-8304e51fffb3)

**Comment by michael-xgw** [comment]
> > > 用http的网页确实无法用iframe嵌入的，可以做跳转。
> > 
> > 
> > 如何跳转，方便详细说一下吗？
> 
> 就把https的域名直接放一个跳转的网页代码就行

误解了，就是因为在Fastgpt 的docker 部署中无法实现 https 域名，所以后面应用发布后需插入的代码中才只有 http 链接，无法获得 https 链接
![image](https://github.com/labring/FastGPT/assets/51981994/79cdba5d-ac7b-4201-bfee-91c4a2250bbb)

**Comment by lijiajun1997** [comment]
我在docker部署，用花生壳做的穿透有https域名，也可以用iframe。




李嘉俊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] “发布应用”-“免登录窗口”，代码包含 http 链接，插入 https 页面后提示 This request has been blocked; the content must be served over HTTPS (Issue #1417)





    
用http的网页确实无法用iframe嵌入的，可以做跳转。
  
如何跳转，方便详细说一下吗？
  
就把https的域名直接放一个跳转的网页代码就行
  
误解了，就是因为在Fastgpt 的docker 部署中无法实现 https 域名，所以后面应用发布后需插入的代码中才只有 http 链接，无法获得 https 链接
 image.png (view on web)

**Comment by c121914yu** [comment]
地址是根据你访问的fastgpt地址生成的

**Comment by sdytzjp** [comment]
请问怎么实现发布免登录的url是https

**Comment by michael-xgw** [comment]
> 请问怎么实现发布免登录的url是https
我在 docker-compose.yml 中添加了一个 nginx 服务
![image](https://github.com/labring/FastGPT/assets/51981994/caf58d3f-7318-4701-af8b-6a947f65d8ac)

**Comment by JiXia830** [comment]
> > 请问怎么实现发布免登录的url是https
> > 我在 docker-compose.yml 中添加了一个 nginx 服务
> > ![image](https://private-user-images.githubusercontent.com/51981994/346404852-caf58d3f-7318-4701-af8b-6a947f65d8ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTI2NjgsIm5iZiI6MTczNjE1MjM2OCwicGF0aCI6Ii81MTk4MTk5NC8zNDY0MDQ4NTItY2FmNThkM2YtNzMxOC00NzAxLWFmOGItNmE5NDdmNjVkOGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDA4MzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWY2MTcxMGVhZmQ1M2ExNjQyYWI3Yjc1YjAzZmE3ZDQxYWU1NDAwYWMzNjg0MzBlY2U4NzczOGYzMDc1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mFfkqPK97X8431L9W7Ms8SAFHcI2M4pcmvxKvJzHgWQ)

配置前需要申请域名的证书吗？请问佬输入的fastgpt域名是啥呢，是API根地址吗？

**Comment by michael-xgw** [comment]
当初不懂走的弯路，不值得参考了。简单的做法，在 bt面板中部署，然后添加反代，端口3002，为该站点免费申请ssl即可。
