### ISSUE TITLE
急急急！无法创建应用，提示异常！

### ISSUE THREAD

**Issue by loveyxh** [labring/FastGPT#1418]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
V4.7.1

- [ ] 公有云版本
- [ ●] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**
1 。点击“”应用“” -->点击 “新建” -->出现创建应用提示框
2.  填写应用名称  ，确认创建，出行异常。

**预期结果**

希望能正常创建应用

**相关截图**

![41e583643afbc46edb239b1c3f4ce8c](https://github.com/labring/FastGPT/assets/9854836/7e8b4db3-9aec-4230-9bd9-c0dab27a897f)

**Comment by lijiajun1997** [comment]
没遇到过。。。换个浏览器试一下，或者更新一下版本

**Comment by c121914yu** [comment]
看着是你网关设置太小了

**Comment by loveyxh** [comment]
> 没遇到过。。。换个浏览器试一下，或者更新一下版本

换浏览器试了，没用
