### ISSUE TITLE
excel导入，表头问题咨询

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1422]
第一个块，是有表头的
![image](https://github.com/labring/FastGPT/assets/66725845/f5630e6e-425f-49ee-b286-3e4d3f34dbed)
从第二个块开始，没有表头
![image](https://github.com/labring/FastGPT/assets/66725845/b01f85a3-612d-4675-865b-24ad1612eae9)

这种检索某一个块（非第一个块），数据能准备映射相应的表头吗？

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/1424
这个Pr会做一点优化，csv和excel这种表格数据，会往markdown table去转换。
![image](https://github.com/labring/FastGPT/assets/50446880/2de40725-d8bd-4745-add0-c6c30e1894a9)

**Comment by Essence9999** [comment]
> #1424 这个Pr会做一点优化，csv和excel这种表格数据，会往markdown table去转换。 ![image](https://private-user-images.githubusercontent.com/50446880/329224410-2de40725-d8bd-4745-add0-c6c30e1894a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDQ1NzQsIm5iZiI6MTcxNTMwNDI3NCwicGF0aCI6Ii81MDQ0Njg4MC8zMjkyMjQ0MTAtMmRlNDA3MjUtZDhiZC00NzQ1LWFkZDAtYzZjMzBlMTg5NGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAxMjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMTEyNWY3MDMzMDEzYjZjNGI0OThmYmU0OTYwNDk2OTRjZmRhZWZkYmMxYWFmMDk3NTJmNTBmMGIwM2NjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igDjowHav8X72g_bqKjXR1AsDR_XkRjsTq1hQEJWbPY)

如果是这种的话，感觉就没有csv和excel之分了，只是底层判断一下，统一称为表格数据，转markdown多列（csv也不用特许两列，两列只是多列的一个特例）

**Comment by c121914yu** [comment]
> > #1424 这个Pr会做一点优化，csv和excel这种表格数据，会往markdown table去转换。 ![image](https://private-user-images.githubusercontent.com/50446880/329224410-2de40725-d8bd-4745-add0-c6c30e1894a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDQ1NzQsIm5iZiI6MTcxNTMwNDI3NCwicGF0aCI6Ii81MDQ0Njg4MC8zMjkyMjQ0MTAtMmRlNDA3MjUtZDhiZC00NzQ1LWFkZDAtYzZjMzBlMTg5NGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAxMjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMTEyNWY3MDMzMDEzYjZjNGI0OThmYmU0OTYwNDk2OTRjZmRhZWZkYmMxYWFmMDk3NTJmNTBmMGIwM2NjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igDjowHav8X72g_bqKjXR1AsDR_XkRjsTq1hQEJWbPY)
> 
> 如果是这种的话，感觉就没有csv和excel之分了，只是底层判断一下，统一称为表格数据，转markdown多列（csv也不用特许两列，两列只是多列的一个特例）

嗯，excel也是转成类似csv格式。
csv也是多列。
