### ISSUE TITLE
怎么完全按照知识库回答

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1423]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
添加了知识库后，总是有一些模型的逻辑，怎么让完全按照知识库的内容响应呢 
尝试使用编排 把AI对话换成了指定回复，回复的内容就有问题了
![image](https://github.com/labring/FastGPT/assets/50564015/54cfa964-fe2a-4a13-8e23-c98821103fcf)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/99cb2a8d-ff20-40ae-b4ff-771db3bdd1f3)
在这里设置，以及在提示词中强调一下。 这个内容需要AI加工，不能直接把知识库链接到指定回复。

**Comment by lxb0425** [comment]
那这个是完全基于知识库吧 不会联想到知识库材料没有提供的内容吧？

**Comment by lijiajun1997** [comment]
> 好的好的 再问下。回答是完全基于知识库吧 不会联想到知识库材料没有提供的内容吧？

通过提示词可以强调

**Comment by lxb0425** [comment]
额 这也行吗 这给客户用的 万一问到内容 回答到知识库以外的 那不坑惨了 /捂脸

**Comment by lijiajun1997** [comment]
> 额 这也行吗 这给客户用的 万一问到内容 回答到知识库以外的 那不坑惨了 /捂脸

提示词里可以限制“如果问到的问题不在提供的知识里，你应该拒绝回答”

**Comment by lxb0425** [comment]
嗯额  也可以通过知识库搜索结果为空走指定回复输出固定回复的内容吧
