### ISSUE TITLE
文本加工BUG

### ISSUE THREAD

**Issue by zyxingsky** [labring/FastGPT#1427]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
使用“http请求” 调用  stable diffusion 接口，返回的是base64编码的图片。再使用“文本加工”，拼接markdown展示图片，拼接内容如图。如果图片是512*512大小，则会报错，大概意思是body超过了1M的限制。如果图片改小点，则能正常拼接。
**复现步骤**

**预期结果**

**相关截图**
![screenshot-20240509-194701](https://github.com/labring/FastGPT/assets/167400273/ad3b9752-54e1-45db-9ea5-b1df88e78ac4)

**Comment by c121914yu** [comment]
最新版是productionhttps://github.com/labring/FastGPT/pull/1485 更新下，，上次只加了响应，没加请求限制。
