### ISSUE TITLE
接入DALL·E中的dall-e-3模型输出用户需要的图片

### ISSUE THREAD

**Issue by weifengzyl** [labring/FastGPT#1432]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
V4.6.8
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.6.8

**问题描述, 日志截图**
![Uploading image.png…]()

**复现步骤**

**预期结果**
希望能够引入dall-e-3模型进行输出图片操作
**相关截图**

**Comment by weifengzyl** [comment]
![image](https://github.com/labring/FastGPT/assets/114549102/d062fa20-8277-49b4-b395-0dd317531d77)

**Comment by HaishengLiang** [comment]
你直接在工具里面建立一个api接口 然后 返回图片url
最后以markdown方式展示即可
