### ISSUE TITLE
语音输入配置在简易配置无法正常配置

### ISSUE THREAD

**Issue by Strong-Gavin** [labring/FastGPT#1433]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**
1、新建应用
2、应用简易配置-语音输入
![image](https://github.com/labring/FastGPT/assets/17334234/a32e22e0-e3c7-4c0c-90cf-66800a70b52f)
![image](https://github.com/labring/FastGPT/assets/17334234/685a00eb-e61f-429e-806e-6a06bfeb3a27)

3、进行语音相关配置，按钮失效
4、高级编排中按钮正常
**预期结果**
在应用简易配置中语音也需要正常点击配置

**相关截图**

**Comment by c121914yu** [comment]
啥版本？4.8没遇到
