### ISSUE TITLE
是否一定要联网才能部署

### ISSUE THREAD

**Issue by zhuangjiayue** [labring/FastGPT#1434]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.7

**问题描述, 日志截图**

这个版本是否一定要联网才能部署，离线部署新建应用时，发现会请求https://api-github.com/repos/labring/FastGPT ，导致新建应用访问不成功

**复现步骤**

**预期结果**

**相关截图**

**Comment by nongmo677** [comment]
emm.. 可能你在config里加上设置show_git为false就不会请求了

```
  "feConfigs": {
    "show_git": false
  },
...其他部分不变
```
  
  可以试试

**Comment by c121914yu** [comment]
这个接口报错和应用没任何关系

**Comment by zhuangjiayue** [comment]
> emm.. 可能你在config里加上设置show_git为false就不会请求了
> 
> ```
>   "feConfigs": {
>     "show_git": false
>   },
> ...其他部分不变
> ```
> 
> 可以试试
试了不行，看了下源代码：
\projects\app\src\web\common\system\useSystemStore.ts
```
gitStar: 9300,
        async loadGitStar() {
          try {
            const { data: git } = await axios.get('https://api.github.com/repos/labring/FastGPT');

            set((state) => {
              state.gitStar = git.stargazers_count;
            });
          } catch (error) {}
        },
```
这个造成的，一定要请求公网

**Comment by zhuangjiayue** [comment]
> emm.. 可能你在config里加上设置show_git为false就不会请求了
> 
> ```
>   "feConfigs": {
>     "show_git": false
>   },
> ...其他部分不变
> ```
> 
> 可以试试

看console应该是配置问题，WeakRef is not defined

**Comment by nongmo677** [comment]
Nodejs版本呢？

**Comment by zhuangjiayue** [comment]
> Nodejs版本呢？

18.17.1版本。

**Comment by jeffreychen567** [comment]
我也是这个问题，要部署到内网，用本地的大模型，无法联网，页面各种出不来，一但联网就可以，是个灾难性问题，私有化部署就是不想联网啊

**Comment by c121914yu** [comment]
> 我也是这个问题，要部署到内网，用本地的大模型，无法联网，页面各种出不来，一但联网就可以，是个灾难性问题，私有化部署就是不想联网啊

我们也是内网。都能正常用。

**Comment by jeffreychen567** [comment]
＠c121914yu 你是怎么解决的呢

**Comment by eric20100106** [comment]
我也是一样的问题，私有化部署后，可以正常使用fastgptV4.8.3的所有功能，但断网后，本机访问localhost:3000就界面没响应了，通过浏览器devtool查看到界面访问时的资源情况，发现访问fastgpt首页时，看到系统会去连接“https://api.github.com/repos/labring/FastGPT"!会不会是因为要连接这个地址，断网后访问不到，界面就不正常了？

**Comment by c121914yu** [comment]
> ＠c121914yu 你是怎么解决的呢
> 

不用解决啥，正常部署就可以了。然后 oneapi 把缓存编排挂载进去就好了。

**Comment by eric20100106** [comment]
不太理解， 如何才能够让oneapi 把缓存编排挂载进去？-------- 原始邮件 --------发件人： Archer ***@***.***>日期： 2024年6月15日周六 半夜12:54收件人： labring/FastGPT ***@***.***>抄送： eric20100106 ***@***.***>, Comment ***@***.***>主    题： Re: [labring/FastGPT] 是否一定要联网才能部署 (Issue #1434)

＠c121914yu 你是怎么解决的呢

不用解决啥，正常部署就可以了。然后 oneapi 把缓存编排挂载进去就好了。

**Comment by c121914yu** [comment]
> 不太理解， 如何才能够让oneapi 把缓存编排挂载进去？-------- 原始邮件 --------发件人： Archer ***@***.***>日期： 2024年6月15日周六 半夜12:54收件人： labring/FastGPT ***@***.***>抄送： eric20100106 ***@***.***>, Comment ***@***.***>主    题： Re: [labring/FastGPT] 是否一定要联网才能部署 (Issue #1434)
> 
> ＠c121914yu 你是怎么解决的呢
> 
> 不用解决啥，正常部署就可以了。然后 oneapi 把缓存编排挂载进去就好了。
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

他的官网有

**Comment by ShuangxiNie** [comment]
> 我也是一样的问题，私有化部署后，可以正常使用fastgptV4.8.3的所有功能，但断网后，本机访问localhost:3000就界面没响应了，通过浏览器devtool查看到界面访问时的资源情况，发现访问fastgpt首页时，看到系统会去连接“[https://api.github.com/repos/labring/FastGPT"!会不会是因为要连接这个地址，断网后访问不到，界面就不正常了？](https://api.github.com/repos/labring/FastGPT%22!%E4%BC%9A%E4%B8%8D%E4%BC%9A%E6%98%AF%E5%9B%A0%E4%B8%BA%E8%A6%81%E8%BF%9E%E6%8E%A5%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%EF%BC%8C%E6%96%AD%E7%BD%91%E5%90%8E%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%88%B0%EF%BC%8C%E7%95%8C%E9%9D%A2%E5%B0%B1%E4%B8%8D%E6%AD%A3%E5%B8%B8%E4%BA%86%EF%BC%9F)

有人解决这个问题了吗？

**Comment by eric20100106** [comment]
> emm.. 可能你在config里加上设置show_git为false就不会请求了
> 
> ```
>   "feConfigs": {
>     "show_git": false
>   },
> ...其他部分不变
> ```
> 
> 可以试试

在config.json中设置了，也是没用的。在重新docker compose up后，看到终端显示的还是show_git true,设置并未生效。

**Comment by eric20100106** [comment]
> > 不太理解， 如何才能够让oneapi 把缓存编排挂载进去？-------- 原始邮件 --------发件人： Archer _**@**_._**>日期： 2024年6月15日周六 半夜12:54收件人： labring/FastGPT _**@**_.**_>抄送： eric20100106 _**@**_._**>, Comment _**@**_.**_>主    题： Re: [labring/FastGPT] 是否一定要联网才能部署 (Issue #1434)
> > ＠c121914yu 你是怎么解决的呢
> > 不用解决啥，正常部署就可以了。然后 oneapi 把缓存编排挂载进去就好了。
> > —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 他的官网有

能不能给个链接，到底如何设置才能编排进去？或者把你的配置发出来看看，学习下。

**Comment by tuean** [comment]
> > emm.. 可能你在config里加上设置show_git为false就不会请求了
> > ```
> >   "feConfigs": {
> >     "show_git": false
> >   },
> > ...其他部分不变
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以试试
> 
> 看console应该是配置问题，WeakRef is not defined

查了下这是浏览器版本问题，升级下就成https://caniuse.com/?search=WeakRef

**Comment by passwhl** [comment]
> > 我也是这个问题，要部署到内网，用本地的大模型，无法联网，页面各种出不来，一但联网就可以，是个灾难性问题，私有化部署就是不想联网啊
> 
> 我们也有内网，都能正常用。

你把网断了试试  简直是个灾难

**Comment by dotaofll** [comment]
请问你解决这个bug了么

**Comment by dotaofll** [comment]
> > > emm.. 可能你在config里加上设置show_git为false就不会请求了
> > > ```
> > >   "feConfigs": {
> > >     "show_git": false
> > >   },
> > > ...其他部分不变
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 可以试试
> > 
> > 
> > 看console应该是配置问题，WeakRef is not defined
> 
> 查了下这是浏览器版本问题，升级下就成https://caniuse.com/?search=WeakRef

你在config里设置show_git = false之后，V4.8.30 在新建应用时，会请求/api/common/initData这个接口，会重新设置feConfigs，把show_git = true，然后去请求gitstar，导致应用崩溃。
