### ISSUE TITLE
关于config.json中配置项对应不同模型该如何正确填写

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1437]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
在config.json文件中如图所示的配置项，对应不同的模型，该如何正确填写？
![image](https://github.com/labring/FastGPT/assets/40045458/d04a6bcb-bd79-4ced-bd18-48f5126dec7f)

例如在Meta-Llama-3-8B-Instruct中，
![image](https://github.com/labring/FastGPT/assets/40045458/5516f5f7-5b92-4868-af21-38528857816f)
![image](https://github.com/labring/FastGPT/assets/40045458/834bdaf7-0a3e-4986-9d28-b697ba5efb9e)
该怎么和config.json中配置项对应上？

因为我在用Meta-Llama-3-8B-Instruct进行对话时，出现了如图所示的现象：
![image](https://github.com/labring/FastGPT/assets/40045458/103b92e5-85f9-4360-bb5f-64b81f7e8630)

**复现步骤**

**预期结果**

**相关截图**

**Comment by xiaoToby** [comment]
@c121914yu @nongmo677

**Comment by c121914yu** [comment]
这不是模型问题么

**Comment by xiaoToby** [comment]
我的意思是
![image](https://github.com/labring/FastGPT/assets/40045458/5de0e37f-6ce6-49e1-ad57-36be590a7241)
和
![image](https://github.com/labring/FastGPT/assets/40045458/2b6ba32c-fc13-4ffd-aa9b-b849a58c416f)
的对应关系

@c121914yu @nongmo677

**Comment by c121914yu** [comment]
> 我的意思是
> ![image](https://github.com/labring/FastGPT/assets/40045458/5de0e37f-6ce6-49e1-ad57-36be590a7241)
> 和
> ![image](https://github.com/labring/FastGPT/assets/40045458/2b6ba32c-fc13-4ffd-aa9b-b849a58c416f)
> 的对应关系
> 
> @c121914yu @nongmo677 

不懂这是啥版本～只知道 llama3 官方是 8k 最大上下文
