### ISSUE TITLE
对话框发送图片报错connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by xiafeng111** [labring/FastGPT#1438]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本：4.6.9 通过Windows Docker Desktop部署
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

![微信截图_20240510161424](https://github.com/labring/FastGPT/assets/33710913/4ab1d515-6ced-431b-81a5-d5e029ce29af)
![微信截图_20240510160033](https://github.com/labring/FastGPT/assets/33710913/bfee59c9-39ba-49cd-a5d7-197457b863b4)

**Comment by xiafeng111** [comment]
用IP地址访问fastgpt并发送图片会报422错误
![微信截图_20240510163345](https://github.com/labring/FastGPT/assets/33710913/56cb9e9f-f516-414b-a8ca-9467dd898297)
![微信截图_20240510163254](https://github.com/labring/FastGPT/assets/33710913/38c80064-42ca-40f4-ba4a-dff852e885a3)

**Comment by c121914yu** [comment]
看着是模型报错了，，你这地址模型访问得到？

**Comment by xiafeng111** [comment]
> 看着是模型报错了，，你这地址模型访问得到？

正常的文字对话没有问题

**Comment by c121914yu** [comment]
> > 看着是模型报错了，，你这地址模型访问得到？
> 
> 正常的文字对话没有问题

文字肯定没问题呀，图片是给一个地址过去

**Comment by xiafeng111** [comment]
> > > 看着是模型报错了，，你这地址模型访问得到？
> > 
> > 
> > 正常的文字对话没有问题
> 
> 文字肯定没问题呀，图片是给一个地址过去。对方访问不到你图片地址，那不就报错了

如果是模型问题，对话框内应该是可以正常发送图片但是收不到返回内容吧。但目前是无法发送图片，对话内容里没有我发送的图片。

**Comment by junjie635** [comment]
> > > 看着是模型报错了，，你这地址模型访问得到？
> > 
> > 
> > 正常的文字对话没有问题
> 
> 文字肯定没问题呀，图片是给一个地址过去。对方访问不到你图片地址，那不就报错了
你好，我目前也遇到了这个问题，之前通过源码部署没问题，现在通过docker-compose部署就出现这种情况，图片可以上传，但是发送就会出现楼主的这个错误，我看了下日志，错误发生在请求模型之前，通过axios请求时将图片转换成base64的过程中，而且进入容器内也是无法请求到3000端口的，请问该如何解决
![image](https://github.com/labring/FastGPT/assets/63136443/ffda6b5d-6325-4021-8eaf-90e84ebacd77)

![image](https://github.com/labring/FastGPT/assets/63136443/550bc481-2d8d-406f-9d4a-bffb56c799ec)

![image](https://github.com/labring/FastGPT/assets/63136443/7c52953e-8553-497f-9e35-dd7781312ed9)

**Comment by junjie635** [comment]
> > > > 看着是模型报错了，，你这地址模型访问得到？
> > > 
> > > 
> > > 正常的文字对话没有问题
> > 
> > 
> > 文字肯定没问题呀，图片是给一个地址过去。对方访问不到你图片地址，那不就报错了
> > 你好，我目前也遇到了这个问题，之前通过源码部署没问题，现在通过docker-compose部署就出现这种情况，图片可以上传，但是发送就会出现楼主的这个错误，我看了下日志，错误发生在请求模型之前，通过axios请求时将图片转换成base64的过程中，而且进入容器内也是无法请求到3000端口的，请问该如何解决
> > ![image](https://private-user-images.githubusercontent.com/63136443/333981187-ffda6b5d-6325-4021-8eaf-90e84ebacd77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODk2MDUsIm5iZiI6MTcxNjc4OTMwNSwicGF0aCI6Ii82MzEzNjQ0My8zMzM5ODExODctZmZkYTZiNWQtNjMyNS00MDIxLThlYWYtOTBlODRlYmFjZDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA1NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYWZkOWVjN2JjMDI5YzMwMzM3MzdlY2U2M2Q5YjNkOTE3Y2ZmMDcxNWE1NmM5YzQxYTAzNTI5YWRhZDdiN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0oJj2ulaOznRLtZWqa1lZI_AfJu6-E6ug2n3EiOCAQ4)
> 
> ![image](https://private-user-images.githubusercontent.com/63136443/333980610-550bc481-2d8d-406f-9d4a-bffb56c799ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODk2MDUsIm5iZiI6MTcxNjc4OTMwNSwicGF0aCI6Ii82MzEzNjQ0My8zMzM5ODA2MTAtNTUwYmM0ODEtMmQ4ZC00MDZmLTlkNGEtYmZmYjU2Yzc5OWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA1NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTk2OGVmMjczMjc2OTdmYTA2ZTVkZDY3M2NlZmUwNjFlZDU4NTA1MmQ3ZTQzNjI3Y2I5ODVhMDdkMzg1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cIr450uTjcArMJzQ4pypYrWQlK_gDq3voMROmp8TaCo)
> 
> ![image](https://private-user-images.githubusercontent.com/63136443/333981521-7c52953e-8553-497f-9e35-dd7781312ed9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODk2MDUsIm5iZiI6MTcxNjc4OTMwNSwicGF0aCI6Ii82MzEzNjQ0My8zMzM5ODE1MjEtN2M1Mjk1M2UtODU1My00OTdmLTllMzUtZGQ3NzgxMzEyZWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA1NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZDZhM2Y2ZTc0NTdlM2RiYTk1YzZkOWNhZjczYmM4Yzk0YTgyZDcyMTRmNjliYTg2ZWNhZDcwNjUwOGU3ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6C9hj0wAVgpNizZVPEUZDx376d9cDb34jzlGVx1EOnU)

![image](https://github.com/labring/FastGPT/assets/63136443/bcecd653-d258-4d2a-b5fa-edce4782ae39)

**Comment by stephenlzc** [comment]
同样的问题，在Mac M1 Pro中，使用OrbStack部署了fastgpt和Open WebUI，使用Open WebUI上传给gpt-4o是可以正常返回的，但是在fastgpt中，出现以下错误：

<img width="1400" alt="image" src="https://github.com/labring/FastGPT/assets/52523593/9852a183-58f6-4875-a605-603bf184eaa3">
运行日志：
> [Error] 2024-06-20 11:14:46 sse error: connect ECONNREFUSED ::1:3000 
{
  message: 'connect ECONNREFUSED ::1:3000',
  stack: 'Error: connect ECONNREFUSED ::1:3000\n' +
    '    at AxiosError.from (file:///app/node_modules/.pnpm/axios@1.5.1/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (file:///app/node_modules/.pnpm/axios@1.5.1/node_modules/axios/lib/adapters/http.js:593:25)\n' +
    '    at RedirectableRequest.emit (node:events:514:28)\n' +
    '    at eventHandlers.<computed> (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:38:24)\n' +
    '    at ClientRequest.emit (node:events:514:28)\n' +
    '    at Socket.socketErrorListener (node:_http_client:501:9)\n' +
    '    at Socket.emit (node:events:514:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)',
  config: {
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.5.1',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'http://localhost:3000/api/system/img/66740ed30798ad1e1b630a96',
    data: undefined
  }
}

这是在open webui中的返回结果
<img width="1470" alt="image" src="https://github.com/labring/FastGPT/assets/52523593/cdb200ce-f887-48e9-a1e2-f465d9db8f88">
运行日志：
> INFO:apps.ollama.main:get_all_models()
INFO:     192.168.215.1:52744 - "GET /api/models HTTP/1.1" 200 OK
INFO:     192.168.215.1:52744 - "GET /ollama/api/version HTTP/1.1" 200 OK
INFO:     192.168.215.1:52752 - "GET /api/v1/users/user/settings HTTP/1.1" 200 OK
INFO:     192.168.215.1:52744 - "GET /api/v1/users/user/settings HTTP/1.1" 200 OK
INFO:     127.0.0.1:46606 - "GET /health HTTP/1.1" 200 OK
INFO:     192.168.215.1:57834 - "POST /api/v1/chats/new HTTP/1.1" 200 OK
INFO:     192.168.215.1:57834 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
INFO:     192.168.215.1:57834 - "POST /openai/chat/completions HTTP/1.1" 200 OK
gpt-4o
INFO:     192.168.215.1:57834 - "POST /api/chat/completed HTTP/1.1" 200 OK
INFO:     192.168.215.1:57834 - "POST /api/v1/chats/a6bdb19d-cc7d-4228-9885-927f419ef5b5 HTTP/1.1" 200 OK
INFO:     192.168.215.1:57834 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
generate_title
gpt-4o
INFO:     192.168.215.1:57834 - "POST /api/task/title/completions HTTP/1.1" 200 OK
INFO:     192.168.215.1:57834 - "POST /api/v1/chats/a6bdb19d-cc7d-4228-9885-927f419ef5b5 HTTP/1.1" 200 OK
INFO:     192.168.215.1:57834 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
INFO:     192.168.215.1:57834 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
['HAh6m316YvvqAE9AAAAD']
INFO:     127.0.0.1:48030 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:46064 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:33206 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:41288 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:46538 - "GET /health HTTP/1.1" 200 OK

请确认，谢谢！

**Comment by yw-2020** [comment]
同样的错误，docker部署的，4o和claude-3.5-sonnet都报错

**Comment by c121914yu** [comment]
CLose 未关联 Issue.
可升级新版，旧版的如果用 localhost docker部署无法使用，需IP 或域名模式，新版已兼容。
