### ISSUE TITLE
你好，cloud sealos部署one api问题

### ISSUE THREAD

**Issue by kxkxpack** [labring/FastGPT#144]
[one-api](https://github.com/labring/FastGPT/tree/main/docs/deploy/one-api)

你好，cloud sealos部署one api问题，部署的域名貌似不能通过cloudflare DNS来隐藏域名IP，这样被攻击的话，是不是流量也会飞上去

**Comment by c121914yu** [comment]
mark下，，我问问他们

**Comment by kxkxpack** [comment]
> mark下，，我问他们
好的，谢谢您

**Comment by kxkxpack** [comment]
好的，谢谢您

**Comment by c121914yu** [comment]
"你不需要关心攻击问题，这个应该是 sealos解决的"

**Comment by c121914yu** [comment]
cf套不了确实是个神奇问题，得研究下
