### ISSUE TITLE
关于http组件返回值无法自定义输出第二级数据

### ISSUE THREAD

**Issue by colinyyj** [labring/FastGPT#1440]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ✔] 我已确认目前没有类似 issue
- [✔ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [✔ ] 私有部署版本, 具体版本号:  4.8.0-alpha2

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/5284443/94476779-5a63-498a-a743-98036f2292a3)

**复现步骤**

**预期结果**
能正常返回
**相关截图**

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/b0cd929c-c94b-440b-9f48-12b05cbc2a10)

入参不支持.吧

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/81030afe-aa1f-49f1-b57e-519fa66c5230)
也没问题呢

**Comment by c121914yu** [comment]
哦我直到了。
你有一个 data，还有一个 data.data， 解析时候会报错的，因为对象只有唯一健。

**Comment by colinyyj** [comment]
> 哦我知道了。 你有一个 data，还有一个 data.data， 解析时候会报错的，因为对象只有唯一健。

哦， 明白了，我已经取出来了，
谢谢

**Comment by c121914yu** [comment]
后续再跟进下这个兼容问题
