### ISSUE TITLE
上传知识库里的文档包含图片，如何在回答的时候也引用图片呢

### ISSUE THREAD

**Issue by Jiang-Wan** [labring/FastGPT#1445]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我上传到知识库里的Word文档里包含图片，如何能在AI回答的时候也包含图片答案呢？是否上传word文档并不只是图片的展示，只能用Markdown格式的图片链接呢？
**应用场景**

**相关示例**
![截图1](https://github.com/labring/FastGPT/assets/57851281/60b4ecb5-311f-4b91-8eba-ca6db7a53f54)
这是文档中的问题和答案截图
![image](https://github.com/labring/FastGPT/assets/57851281/3703b61d-60b9-4469-be53-b87117537b6c)
这是回答的答案截图

**Comment by nightzjp** [comment]
默认是不会显示的，除非你问问题的时候要求显示，或者知识库提示词里面说明一下才会显示图片

**Comment by Jiang-Wan** [comment]
> 默认是不会显示的，除非你问问题的时候要求显示，或者知识库提示词里面说明一下才会显示图片

感谢老哥，我试了下，的确可以显示图片

**Comment by gongjl123** [comment]
> > 默认是不会显示的，除非你问问题的时候要求显示，或者知识库提示词里面说明一下才会显示图片
> 
> 感谢老哥，我试了下，的确可以显示图片

老哥这个怎么做的呢 我还是不显示

**Comment by Jiang-Wan** [comment]
> > > 默认是不会显示的，除非你问问题的时候要求显示，或者知识库提示词里面说明一下才会显示图片
> > 
> > 
> > 感谢老哥，我试了下，的确可以显示图片
> 
> 老哥这个怎么做的呢 我还是不显示

问的时候，主动要求显示图片，如：渠道资源系统查询所需资源信息并展示示意图
