### ISSUE TITLE
docker build 报错 failed to compute cache key: "/app/projects/app/.next/standalone" not found: not found

### ISSUE THREAD

**Issue by jingzl** [labring/FastGPT#1457]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1-fix，20240512 下载的版本

**问题描述, 日志截图**
[+] Building 1.3s (32/36)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:18.17-alpine                                               1.0s
 => [internal] load build context                                                                                  0.2s
 => => transferring context: 241.33kB                                                                              0.2s
 => [builder  1/10] FROM docker.io/library/node:18.17-alpine@sha256:3482a20c97e401b56ac50ba8920cc7b5b2022bfc6aa7d  0.0s
 => CACHED [builder  2/10] WORKDIR /app                                                                            0.0s
 => CACHED [runner  3/15] RUN addgroup --system --gid 1001 nodejs                                                  0.0s
 => CACHED [runner  4/15] RUN adduser --system --uid 1001 nextjs                                                   0.0s
 => CACHED [runner  5/15] RUN [ -z "taobao" ] || sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk  0.0s
 => CACHED [runner  6/15] RUN apk add --no-cache curl ca-certificates   && update-ca-certificates                  0.0s
 => CACHED [builder  3/10] COPY package.json pnpm-workspace.yaml ./                                                0.0s
 => CACHED [maindeps  3/11] RUN [ -z "taobao" ] || sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/a  0.0s
 => CACHED [maindeps  4/11] RUN echo -e http://mirrors.ustc.edu.cn/alpine/v3.15/main/ > /etc/apk/repositories      0.0s
 => CACHED [maindeps  5/11] RUN apk add --no-cache libc6-compat && npm install -g pnpm@8.6.0                       0.0s
 => CACHED [maindeps  6/11] RUN [ -z "taobao" ] || pnpm config set registry https://registry.npmmirror.com         0.0s
 => CACHED [maindeps  7/11] COPY pnpm-lock.yaml pnpm-workspace.yaml ./                                             0.0s
 => CACHED [maindeps  8/11] COPY ./packages ./packages                                                             0.0s
 => CACHED [maindeps  9/11] COPY ./projects/app/package.json ./projects/app/package.json                           0.0s
 => CACHED [maindeps 10/11] RUN [ -f pnpm-lock.yaml ] || (echo "Lockfile not found." && exit 1)                    0.0s
 => CACHED [maindeps 11/11] RUN pnpm i                                                                             0.0s
 => CACHED [builder  4/10] COPY --from=mainDeps /app/node_modules ./node_modules                                   0.0s
 => CACHED [builder  5/10] COPY --from=mainDeps /app/packages ./packages                                           0.0s
 => CACHED [builder  6/10] COPY ./projects/app ./projects/app                                                      0.0s
 => CACHED [builder  7/10] COPY --from=mainDeps /app/projects/app/node_modules ./projects/app/node_modules         0.0s
 => CACHED [builder  8/10] RUN [ -z "taobao" ] || sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/ap  0.0s
 => CACHED [builder  9/10] RUN apk add --no-cache libc6-compat && npm install -g pnpm@8.6.0                        0.0s
 => CACHED [builder 10/10] RUN pnpm --filter=app build                                                             0.0s
 => CACHED [runner  7/15] COPY --from=builder /app/projects/app/public /app/projects/app/public                    0.0s
 => CACHED [runner  8/15] COPY --from=builder /app/projects/app/next.config.js /app/projects/app/next.config.js    0.0s
 => ERROR [runner  9/15] COPY --from=builder --chown=nextjs:nodejs /app/projects/app/.next/standalone /app/        0.0s
 => CACHED [runner 10/15] COPY --from=builder --chown=nextjs:nodejs /app/projects/app/.next/static /app/projects/  0.0s
 => ERROR [runner 11/15] COPY --from=builder --chown=nextjs:nodejs /app/projects/app/.next/server/chunks /app/pro  0.0s
------
 > [runner  9/15] COPY --from=builder --chown=nextjs:nodejs /app/projects/app/.next/standalone /app/:
------
------
 > [runner 11/15] COPY --from=builder --chown=nextjs:nodejs /app/projects/app/.next/server/chunks /app/projects/app/.next/server/chunks:
------
failed to compute cache key: "/app/projects/app/.next/standalone" not found: not found

**复现步骤**
1）下载版本后，替换了 ico，修改了systemTitle
2）docker build -t xxxx/fastgpt:4.7.1 --build-arg name=app .

**预期结果**

**相关截图**

**Comment by jingzl** [comment]
日志截图：
![image](https://github.com/labring/FastGPT/assets/2803602/c60d36b2-a98c-4af5-9f74-57730ed5fcc5)

**Comment by c121914yu** [comment]
未遇到，检查下本地环境~
看着都没开始build

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/1468 可以尝试
