### ISSUE TITLE
添加代码执行模块，增加流程的灵活性

### ISSUE THREAD

**Issue by jonathan714** [labring/FastGPT#1461]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在很多复杂逻辑处理的时候，没有直接代码模块能力，灵活性不足
**应用场景**
字符串处理，基于http模块后对返回数据引用的处理，可以基于一个通用的http模块，对返回数据进行读取和处理
**相关示例**

**Comment by jonathan714** [comment]
不基于laf的方式

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8.2 js sandbox
