### ISSUE TITLE
当我将最大上下文设置为3或者3以下时，最大响应tokens变成了默认值200，而不是配置文件的值

### ISSUE THREAD

**Issue by cuisws** [labring/FastGPT#1462]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8-preview
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我希望会话不记录上下文对话，每次对话都是新的对话。进而就把配置文件最大上下文maxContext设置为了3(也试过0，1)，但是最大回复maxResponse还是4000，然后进行对话。此时对话，页面上显示最大最大响应 Tokens为200，造成回答内容只有200Tokens。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/119495121/74e1776e-6fa5-4d36-bfc4-5300e1558c4e)
![image](https://github.com/labring/FastGPT/assets/119495121/403f1c74-76cc-48f7-bcae-20c139ec61d1)

**Comment by cuisws** [comment]
当我将最大上下文maxContext调整为和最大回复maxResponse一样为4000，貌似是好了，不记录上下文了。

**Comment by lijiajun1997** [comment]
上下文在编排里改 不要再config里改

**Comment by c121914yu** [comment]
这是编排里改的~配置文件是配置模型的
