### ISSUE TITLE
高级编排问题分类永远都是走最后一个分类

### ISSUE THREAD

**Issue by thegenway** [labring/FastGPT#1465]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/12321764/44c1215e-939b-47f0-aad0-f2bfa2ba5402)

测试过好多中情况，永远都是走最后一个分类...

**Comment by lijiajun1997** [comment]
模型的问题，如果不是gpt3.5/4 ，在config里把function call和tool call都改成false.

**Comment by thegenway** [comment]
> 模型的问题，如果不是gpt3.5/4 ，在config里把function call和tool call都改成false.

![image](https://github.com/labring/FastGPT/assets/12321764/2de55ddf-6b63-47ac-9045-75b07377b233)
![image](https://github.com/labring/FastGPT/assets/12321764/f82f8863-31eb-43ee-92a1-18d627eebe46)
我看ChatGLM-6B介绍不是也支持Function Call吗，我这个试了也不行

**Comment by c121914yu** [comment]
你要还看oneapi支不支持，以及是函数调用还是工具调用

**Comment by Yue-Lyu123** [comment]
> 模型的问题，如果不是gpt3.5/4 ，在config里把function call和tool call都改成false.

qwen1.5模型把function call和tool call都改成false，就能工具调用了

**Comment by alvinwee07** [comment]
> 你要还看oneapi支不支持，以及是函数调用还是工具调用

这个还涉及oneapi吗？现在私有化版本的工具调用和问题分类（也是只走最后一个）都不生效，config也改了，模型是chatglm3-6b

**Comment by sdytzjp** [comment]
跟进下
