### ISSUE TITLE
更新v4.8版本，http模块报错

### ISSUE THREAD

**Issue by nightzjp** [labring/FastGPT#1467]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8最新版

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
从4.8.alpha3升级到4.8，老的http模块报错，更新http模块，还是报错

**复现步骤**

**预期结果**

**相关截图**
![92f9462a4328e3d9767e7e400445ecd](https://github.com/labring/FastGPT/assets/73635091/46f11b41-d2fd-4dc2-9a58-d944a2ba9128)

**Comment by c121914yu** [comment]
看着网络问题

**Comment by nightzjp** [comment]
> 看着网络问题

4.8.preview3是没问题的；我试试请求其他api有木有问题；

**Comment by c121914yu** [comment]
不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。

**Comment by nightzjp** [comment]
可以的。容器应该是没问题的。我待会试试

| |
seven_nighter
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月14日 10:16 |
| 收件人 | labring/FastGPT ***@***.***> |
| 抄送人 | ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [labring/FastGPT] 更新v4.8版本，http模块报错 (Issue #1467) |

不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。

**Comment by nightzjp** [comment]
> 不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。

刚刚试了下，通过http://web:9999/chat这样的方式访问是没问题的，通过http://192.168.x.x:9999/chat这种方式访问不行

**Comment by c121914yu** [comment]
> > 不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。
> 
> 刚刚试了下，通过[http://web:9999/chat这样的方式访问是没问题的，通过http://192.168.x.x:9999/chat这种方式访问不行](http://web:9999/chat%E8%BF%99%E6%A0%B7%E7%9A%84%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E6%98%AF%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E9%80%9A%E8%BF%87http://192.168.x.x:9999/chat%E8%BF%99%E7%A7%8D%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E8%A1%8C)

你这个是同一个网络不同服务？

**Comment by nightzjp** [comment]
> > > 不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。
> > 
> > 
> > 刚刚试了下，通过[http://web:9999/chat这样的方式访问是没问题的，通过http://192.168.x.x:9999/chat这种方式访问不行](http://web:9999/chat%E8%BF%99%E6%A0%B7%E7%9A%84%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E6%98%AF%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E9%80%9A%E8%BF%87http://192.168.x.x:9999/chat%E8%BF%99%E7%A7%8D%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E8%A1%8C)
> 
> 你这个是同一个网络不同服务？

本地开发测试，fastgpt一个服务，还单独起了一个web服务；
线上部署的时候web服务也加入了fastgpt的网络。
之前是没问题的，更新到4.8之后就出现了。好奇怪

**Comment by c121914yu** [comment]
> > > > 不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。
> > > 
> > > 
> > > 刚刚试了下，通过[http://web:9999/chat这样的方式访问是没问题的，通过http://192.168.x.x:9999/chat这种方式访问不行](http://web:9999/chat%E8%BF%99%E6%A0%B7%E7%9A%84%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E6%98%AF%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E9%80%9A%E8%BF%87http://192.168.x.x:9999/chat%E8%BF%99%E7%A7%8D%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E8%A1%8C)
> > 
> > 
> > 你这个是同一个网络不同服务？
> 
> 本地开发测试，fastgpt一个服务，还单独起了一个web服务； 线上部署的时候web服务也加入了fastgpt的网络。 之前是没问题的，更新到4.8之后就出现了。好奇怪

你的ip变了把

**Comment by nightzjp** [comment]
> > > > > 不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。
> > > > 
> > > > 
> > > > 刚刚试了下，通过[http://web:9999/chat这样的方式访问是没问题的，通过http://192.168.x.x:9999/chat这种方式访问不行](http://web:9999/chat%E8%BF%99%E6%A0%B7%E7%9A%84%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E6%98%AF%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E9%80%9A%E8%BF%87http://192.168.x.x:9999/chat%E8%BF%99%E7%A7%8D%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E8%A1%8C)
> > > 
> > > 
> > > 你这个是同一个网络不同服务？
> > 
> > 
> > 本地开发测试，fastgpt一个服务，还单独起了一个web服务； 线上部署的时候web服务也加入了fastgpt的网络。 之前是没问题的，更新到4.8之后就出现了。好奇怪
> 
> 你的ip变了把

ip地址没有变的，我的网络以及代码没做任何修改，4.8-alpha3正常，升级之后就会出现我描述的这个问题

**Comment by c121914yu** [comment]
> > > > > > 不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。
> > > > > 
> > > > > 
> > > > > 刚刚试了下，通过[http://web:9999/chat这样的方式访问是没问题的，通过http://192.168.x.x:9999/chat这种方式访问不行](http://web:9999/chat%E8%BF%99%E6%A0%B7%E7%9A%84%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E6%98%AF%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E9%80%9A%E8%BF%87http://192.168.x.x:9999/chat%E8%BF%99%E7%A7%8D%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E8%A1%8C)
> > > > 
> > > > 
> > > > 你这个是同一个网络不同服务？
> > > 
> > > 
> > > 本地开发测试，fastgpt一个服务，还单独起了一个web服务； 线上部署的时候web服务也加入了fastgpt的网络。 之前是没问题的，更新到4.8之后就出现了。好奇怪
> > 
> > 你的ip变了把
> 
> ip地址没有变的，我的网络以及代码没做任何修改，4.8-alpha3正常，升级之后就会出现我描述的这个问题

这是内网 ip 我不确定。那你回退后还能正常？

**Comment by nightzjp** [comment]
> > > > > > > 不确定，你可以试试容器里是否正常访问。我这边没有可以复现的方式。
> > > > > > 
> > > > > > 
> > > > > > 刚刚试了下，通过[http://web:9999/chat这样的方式访问是没问题的，通过http://192.168.x.x:9999/chat这种方式访问不行](http://web:9999/chat%E8%BF%99%E6%A0%B7%E7%9A%84%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E6%98%AF%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E9%80%9A%E8%BF%87http://192.168.x.x:9999/chat%E8%BF%99%E7%A7%8D%E6%96%B9%E5%BC%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E8%A1%8C)
> > > > > 
> > > > > 
> > > > > 你这个是同一个网络不同服务？
> > > > 
> > > > 
> > > > 本地开发测试，fastgpt一个服务，还单独起了一个web服务； 线上部署的时候web服务也加入了fastgpt的网络。 之前是没问题的，更新到4.8之后就出现了。好奇怪
> > > 
> > > 
> > > 你的ip变了把
> > 
> > 
> > ip地址没有变的，我的网络以及代码没做任何修改，4.8-alpha3正常，升级之后就会出现我描述的这个问题
> 
> 这是内网 ip 我不确定。那你回退后还能正常？

确实是网络问题，我们公司网络不稳定导致的。刚好被我碰到了。。。
