### ISSUE TITLE
4.8发布版下载源码后docker build出错

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [labring/FastGPT#1468]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X] 我已确认目前没有类似 issue
- [X] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [X] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [X] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X] 私有部署版本, 具体版本号:  V4.8.0

**问题描述, 日志截图**
我在使用
~~~
docker build -t dockername/fastgpt:tag --build-arg name=app --build-arg proxy=taobao .
~~~
编译时发现报错：
~~~
 => ERROR [runner  9/15] COPY --from=builder --chown=nextjs:nodejs /app/projects/app/.next/standalone /app/                                                                                                                    0.0s                                                                                        0.0s 
 => ERROR [runner 11/15] COPY --from=builder --chown=nextjs:nodejs /app/projects/app/.next/server/chunks /app/projects/app/.next/server/chunks   
~~~

~~~
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref af7ffbb5-f2ee-4fdb-adf3-27574f238098::lfycfn5r7ejy83qdq62o22hdz: "/app/projects/app/.next/server/chunks": not found
~~~

**复现步骤**

1.下载v4.8.0项目源码
2.在根目录下执行pnpm i
3.在projects/app目录下执行pnpm dev调试代码
4.在根目录下执行docker build -t dockername/fastgpt:tag --build-arg name=app --build-arg proxy=taobao .

**预期结果**

编译通过

**相关截图**

**Comment by c121914yu** [comment]
没遇到哎，我看action都正常运行成功了。。看看检查下本地环境和网络把，清缓存啥的。

**Comment by boleyn** [comment]
我这也是打包不成功一模一样的问题

**Comment by jfy3d** [comment]
先到 projects/app 下  pnpm  build   然后再docker 制作

**Comment by c121914yu** [comment]
> 这个我也发现了，但是必须对应平台build才行，就比如我mac 这样打出来的包就不行（制定了架构和系统，里面有个jieba这个依赖就很烦）服务器有没有外网很多东西下不下来

arm确实比较难受。。而且还很慢。。如果是打x86镜像，加个 platform 或者配置下 github secret key，到main分支打包

**Comment by boleyn** [comment]
![image](https://github.com/labring/FastGPT/assets/24293664/1ce7f49b-5021-446c-a7a2-9caf6d8e815c)
在build前加一下node的内存大小就可以了，

**Comment by WholeWorld-Timothy** [comment]
膜拜大佬！

**Comment by c121914yu** [comment]
> bui

可以麻烦提个pr去增加这个语句？

**Comment by vary** [comment]
同样的问题，完美解决
