### ISSUE TITLE
新版更新预告

### ISSUE THREAD

**Issue by c121914yu** [labring/FastGPT#147]
经过1个多月的开发，v4版本已经接近尾声，我们预计会在8.14-8.25期间发布新的开源版本。

线上环境已经同步到v4版本，可提前体验。

v4社区版更偏向个人学习使用，我们简化了部署流程，仅需配置 openai 参数和对应root密码即可。

**Comment by forcemeter** [comment]
坐等

**Comment by lipanpan-hub** [comment]
牛的 超期待

**Comment by av8dtop** [comment]
不知是否可用gmail發信，謝謝

**Comment by c121914yu** [comment]
> 不知是否可用gmail發信，謝謝

不再内置发送邮件了

**Comment by c121914yu** [comment]
新版代码已更新
