### ISSUE TITLE
开启猜你想问后回答的很慢

### ISSUE THREAD

**Issue by Forevery1** [labring/FastGPT#1473]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
<img width="1030" alt="image" src="https://github.com/labring/FastGPT/assets/19872771/09a74056-6934-41e8-95f4-65cd29f86d39">
<img width="527" alt="image" src="https://github.com/labring/FastGPT/assets/19872771/4dba6400-1002-4f1d-92dd-2594d374a2ae">

**复现步骤**
如果选择一个模型不是在config.json中的第一个、这时候开启猜你想问就会调config.json中的第一个、不是同一个模型。比如我本地用的ollama、慢的很。如果把选择的模型在config.json中移动到第一个、那就快的很。
**预期结果**
能不能改成选择那个模型、猜你想问就用那个模型、或者是猜你想问可以自己选一个模型
**相关截图**

**Comment by c121914yu** [comment]
后期再增加，短期这个功能暂时不优化

**Comment by wxy545812093** [comment]
尝试自己改啊，不是已经 clone 到本地了么

**Comment by sdytzjp** [comment]
没看懂问题什么意思
