### ISSUE TITLE
使用时间插件时报错

### ISSUE THREAD

**Issue by Jie2GG** [labring/FastGPT#1476]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8

**问题描述, 日志截图**
在工具调用中获取系统时间报错，日志如图所示：
<img width="1269" alt="image" src="https://github.com/labring/FastGPT/assets/39112172/e354e77e-b1b0-4b6d-97c8-589d33975753">

**复现步骤**
1. 创建应用选择 **建议模板**
2. 在工具调用中选择 **获取系统当前时间**
3. 在右侧对话触发错误

**预期结果**
对话后报错

**相关截图**
<img width="1022" alt="image" src="https://github.com/labring/FastGPT/assets/39112172/d221b7eb-0348-4c8f-84d4-bbc1ae185655">

**Comment by lijiajun1997** [comment]
模型的问题不兼容tool choice，你在config里把tool choice和function call都改成false，这样会通过提示词调用工具。或者不通过工具形式，直接在提示词里添加变量“当前时间是：{{time}}”
![image](https://github.com/labring/FastGPT/assets/156336589/f0083015-1783-40fc-bf7e-67de77be53db)
