### ISSUE TITLE
我比较菜，如何使用API创建应用？

### ISSUE THREAD

**Issue by zyc1128** [labring/FastGPT#1477]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我对着mongodb里apps里的参数一个一个试效率很低，返回来的有些也不是完全搞的懂，请大神解惑
**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
没法理解你的需求是什么，使用LLM的api通过fastgpt搭建应用，还是把fastgpt当作中台，提供API给其他的应用。 正常操作也不涉及去mongodb里修改数据。

**Comment by zyc1128** [comment]
> 没法理解你的需求是什么，使用LLM的api通过fastgpt搭建应用，还是把fastgpt当作中台，提供API给其他的应用。 正常操作也不涉及去mongodb里修改数据。

提供API给其他的应用，我的意思是official里没有创建应用的API文档，我不知道咋办

**Comment by lijiajun1997** [comment]
> > 没法理解你的需求是什么，使用LLM的api通过fastgpt搭建应用，还是把fastgpt当作中台，提供API给其他的应用。 正常操作也不涉及去mongodb里修改数据。
> 
> 提供API给其他的应用，我的意思是official里没有创建应用的API文档，我不知道咋办

https://doc.fastai.site/docs/use-cases/openapi/

**Comment by lijiajun1997** [comment]
https://doc.fastai.site/docs/development/openapi/chat/

**Comment by zyc1128** [comment]
> https://doc.fastai.site/docs/development/openapi/chat/

这里面没有教我如何创建应用啊，我说的是fastgpt里的应用，就是外部如何通过post我的服务器来对fastgpt进行一系列操作，文档里只有聊天和知识库等

**Comment by zyc1128** [comment]
> https://doc.fastai.site/docs/development/openapi/chat/

我只能找到mongo里记录了的apps的字段来尝试post,但效果甚微

**Comment by lijiajun1997** [comment]
> 对fastgpt进行一系列操作

你要进行啥操作，出了对话和知识库，难道通过http请求来创建应用？能不能把你的需求 应用场景描述清楚

**Comment by lijiajun1997** [comment]
肯定没法通过http请求进行相关操作，代码里都没有这部分api，你这个需求太奇怪了。

**Comment by lijiajun1997** [comment]
> > 肯定没法通过http请求进行相关操作，代码里都没有这部分api，你这个需求太奇怪了。
> 
> 就是我现在用一台服务器在跑fastgpt等，想测试一下AI知识库应用的落地可能性。另外的人要通过内网调用接口来实现尽可能多的功能，因为能搞的话这些功能会接入他们写的前后端。但我也不太清楚怎么实现，请问怎么办

你在fastgpt创建应用，生成应用的api，然后让其他前后端通过api请求对应的应用。你可以在fastgpt创建不同的应用对接不同的后端需求，比如是否接入知识库，是否联网，是否调用tools，接入不同的LLM

**Comment by zyc1128** [comment]
> > > 肯定没法通过http请求进行相关操作，代码里都没有这部分api，你这个需求太奇怪了。
> > 
> > 
> > 就是我现在用一台服务器在跑fastgpt等，想测试一下AI知识库应用的落地可能性。另外的人要通过内网调用接口来实现尽可能多的功能，因为能搞的话这些功能会接入他们写的前后端。但我也不太清楚怎么实现，请问怎么办
> 
> 你在fastgpt创建应用，生成应用的api，然后让其他前后端通过api请求对应的应用。你可以在fastgpt创建不同的应用对接不同的后端需求，比如是否接入知识库，是否联网，是否调用tools，接入不同的LLM

这些我都知道，我的意思是能不能把比如你说的创建不同的应用这个功能让他们也可以自由使用，现在只能通过修改源码的方式达成这一步？

**Comment by lijiajun1997** [comment]
> > > > 肯定没法通过http请求进行相关操作，代码里都没有这部分api，你这个需求太奇怪了。
> > > 
> > > 
> > > 就是我现在用一台服务器在跑fastgpt等，想测试一下AI知识库应用的落地可能性。另外的人要通过内网调用接口来实现尽可能多的功能，因为能搞的话这些功能会接入他们写的前后端。但我也不太清楚怎么实现，请问怎么办
> > 
> > 
> > 你在fastgpt创建应用，生成应用的api，然后让其他前后端通过api请求对应的应用。你可以在fastgpt创建不同的应用对接不同的后端需求，比如是否接入知识库，是否联网，是否调用tools，接入不同的LLM
> 
> 这些我都知道，我的意思是能不能把比如你说的创建不同的应用这个功能让他们也可以自由使用，现在只能通过修改源码的方式达成这一步？

那就需要该代码增加注册功能和用户管理功能，或者购买商业版fastgpt。

**Comment by nongmo677** [comment]
如果只是想创应用也是ok的
通过`/api/core/app/create`这个接口，比较麻烦的是token生成的问题，这部分你可以查看源码和逻辑，并且创建应用需要的一些body参数也比较多，主要是涉及编排组件的内容
效果如下：

![image](https://github.com/labring/FastGPT/assets/31816449/4bed99d1-583b-423f-a108-dadc3df4d2ab)

![image](https://github.com/labring/FastGPT/assets/31816449/b13addae-eea6-4b20-a091-67be79081e77)

![image](https://github.com/labring/FastGPT/assets/31816449/c839ef9c-45b9-4aad-9488-83e1121c1d01)

**Comment by yuuki798** [comment]
I finally solved this problem by using a single workflow to pass in variables so that I can call various resources directly
