### ISSUE TITLE
想通过高级编排实现提问后先检索知识库，如果知识库没有检索到关键词再进行百度搜索

### ISSUE THREAD

**Issue by zhangshuo687686** [labring/FastGPT#1478]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我现在流程到“文本内容提取”这一步，在上一步“AI 对话”处理中，如果知识库没有问题的答案会返回类似“我不清楚xxx”等格式的内容，想据此判断发送HTTP 请求百度搜索获取问题的答案。能否给一些建议，我当前使用的版本中对“文本内容提取”模块的运行没有达到预期，能否给一些建议

**复现步骤**

**预期结果**

**相关截图**
目前构思的效果
![12](https://github.com/labring/FastGPT/assets/49425161/d5da859f-adf3-4d70-9957-5cae058c4ad6)

文本内容提取运行结果如下
![11](https://github.com/labring/FastGPT/assets/49425161/8618aaac-e211-4a05-a6f1-ae45f3366a09)

**Comment by zhangshuo687686** [comment]
我感觉是在判断器这里配置不对，比如我提问知识库北京今天的天气？ 知识库回答：对不起，我不能直接访问实时的天气数据。如果您需要查询某个具体地址的实时天气，建议您使用手机APP或者搜索引擎查询。 这种情况下在“判断器”中如何继续判断？

**Comment by zhangshuo687686** [comment]
我感觉是在判断器这里配置不对，比如我提问知识库北京今天的天气？ 知识库回答：对不起，我不能直接访问实时的天气数据。如果您需要查询某个具体地址的实时天气，建议您使用手机APP或者搜索引擎查询。 这种情况下在“判断器”中如何继续判断？
如果“判断器”无法判断，是不是需要通过“文本内容提取”打到让“判断器”能够进行判断

**Comment by c121914yu** [comment]
可以尝试直接调用ai对话，生成一些特殊的回答。
判断到特殊回答，则说明知识库不满足。

**Comment by c121914yu** [comment]
例如（我简单写了提示词，没有细调整。）：
![image](https://github.com/labring/FastGPT/assets/50446880/31dea839-8a63-4c5e-a21b-e7533c51fde5)
![image](https://github.com/labring/FastGPT/assets/50446880/c3950bda-a4de-469d-9fd3-60cdafcf1c16)

**Comment by zhangshuo687686** [comment]
好的，多谢，我看了一下，我用的版本是2个月以前的版本，判断器跟跟最新版的使用不一样。我升级到最新版试一下

**Comment by zhangshuo687686** [comment]
我参考了您的建议，在最新版的试了一下。“HTTP请求”模块报错“e.slice is not a function”

**Comment by sdytzjp** [comment]
同问

**Comment by Songzimeng** [comment]
楼主，我有个问题，就是我这样给他设置后，他回复两段回答，一段是ai的回答，一段是我定义的回答或者还是ai的回答，这个问题应该怎么去解决哇。
