### ISSUE TITLE
代码的知识库怎么构建，直接把相应代码放入文档上传就可以吗

### ISSUE THREAD

**Issue by fanfanyaya** [labring/FastGPT#1479]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by wxy545812093** [comment]
理论上确实可以这样子的。但代码片段对格式有强要求的吧？ 所以似乎不适合 “分段拆分” 和 “模型拆分“ ，保险起见建议还是手动添加吧。我的目前理解就是这样子，因为我还没有部署成功~ :) :)

**Comment by lijiajun1997** [comment]
如果一定要上传代码，建议用csv导入。
第一列描述代码实现的功能，第二列放代码。

**Comment by fanfanyaya** [comment]
> 不通过建议知识库的形式，感觉预训练的代码已经覆盖面很广了，RAG代码只能限制AI的发挥。如果有必要，建议提示词+上下文。

我们用的大模型代码生成太差了，答非所问，感觉按您这样分两列太麻烦了，我现在就是从网上爬了点代码块

**Comment by fanfanyaya** [comment]
> 理论上确实可以这样子的。但是代码片段对格式有强要求的吧？好像不适合“分割分割”和“模型分割”，保险起见建议还是手动添加吧。我的目前理解就是这样子，因为我还没配置成功~ :) :)

谢谢，我是刚接触大模型，以前就搞过点cv

**Comment by fanfanyaya** [comment]
> 如果一定要上传代码，建议用csv导入。 第一列描述代码实现的功能，列放代码。

那这知识库的作用是不是对大模型本身的生成效果提升不大，作用是查询资料的感觉

**Comment by lijiajun1997** [comment]
> > 不通过建议知识库的形式，感觉预训练的代码已经覆盖面很广了，RAG代码只能限制AI的发挥。如果有必要，建议提示词+上下文。
> 
> 我们用的大模型代码生成太差了，答非所问，感觉按您这样分两列太麻烦了，我现在就是从网上爬了点代码块

换个大模型，deepseek coder试试，以及提示词优化一下。一般你能找到的代码都已经被大模型训练过了。

**Comment by fanfanyaya** [comment]
> > > 不通过建议知识库的形式，感觉预训练的代码已经覆盖面很广了，RAG代码只能限制AI的发挥。如果有必要，建议提示词+上下文。
> > 
> > 
> > 我们用的大模型代码生成太差了，答非所问，感觉按你这样分两列太麻烦了，我现在就是从网上爬了点代码块
> 
> 换个大模型，deepseek coder 尝试，以及提示词优化一下。一般你能找到的代码都已经被大模型训练过了。

换不了，要用公司的大模型加知识库构建应用体，唉

**Comment by c121914yu** [comment]
可以考虑手动标注。
index 是代码描述，content 是代码
