### ISSUE TITLE
求助部署成功了，但是报错 self-signed certificate

### ISSUE THREAD

**Issue by stone009** [labring/FastGPT#148]
如题，开始对话会弹出：self-signed certificate

我检查了SSL证书，也是没问题的~~

![image](https://github.com/labring/FastGPT/assets/25975586/200cd5a1-cd88-4c67-8571-c70b65980bf7)

**Comment by c121914yu** [comment]
em目前遇到都是证书问题，可以部署新版，我把默认nginx干掉了
