### ISSUE TITLE
菜鸟求助前端破法：Error: NextRouter was not mounted. 

### ISSUE THREAD

**Issue by wxy545812093** [labring/FastGPT#1481]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: app@4.8, nextjs@13.5.2 node@v20.12.0 pnpm@9.1.1 git@2.38.0.windows.1

**问题描述, 日志截图**
one-api部分已成功编译且启动，但FastGPT前端 "run dev" 部分卡主了。无奈对nextjs不懂，搞了很久没效果啊，魂力都耗尽了，没办法只能求助了。会的老铁指点一下：此阵何以破之？

**复现步骤**

**预期结果**

**相关截图**
![000](https://github.com/labring/FastGPT/assets/4502958/22184ad3-44e9-40d5-a3b9-14eb5039b73a)

**Comment by LIKEGAKKI** [comment]
你是想源码运行吗？如果你有前端项目的基础，可以参考官方的文档。[开发与部署指南](https://doc.fastai.site/docs/development/intro/#4-%e5%88%9d%e5%a7%8b%e9%85%8d%e7%bd%ae)
