### ISSUE TITLE
判断器输入文本会重复并自动打断，无法用判断器的结果进行分支选取，各种bug

### ISSUE THREAD

**Issue by BUJIDAOVS** [labring/FastGPT#1483]
判断器输入文本会重复并自动打断
无法用判断器的结果进行分支选定，其他分支的部件莫名奇妙的也在运行
能不能恢复原来的布尔触发器，四向连接看似多了两项，实则少了一堆连线的节点，根本没法控制复杂流程的启停。
每个变量都得手动选取，还不能重复使用
自动保存也有问题，测试着测试着报个错全没了，难用死了

**Comment by c121914yu** [comment]
1235都没遇到
![image](https://github.com/labring/FastGPT/assets/50446880/b232003a-25c4-429b-998c-37d01a6b217f)

**Comment by BUJIDAOVS** [comment]
太简单了你这结构，多个else连多个文本加工再连多个ai回复和指定回复试试，没有原来的触发结构，复杂逻辑根本没法实现，太多歧义了

> 1235都没遇到 ![image](https://private-user-images.githubusercontent.com/50446880/330366574-b232003a-25c4-429b-998c-37d01a6b217f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Nzg4NDQsIm5iZiI6MTcxNTY3ODU0NCwicGF0aCI6Ii81MDQ0Njg4MC8zMzAzNjY1NzQtYjIzMjAwM2EtMjVjNC00MjliLTk5OGMtMzdkMDFhNmIyMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA5MjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZWRiNjhlODRkYWI0OWI3NGNlZWI1ZjVhZDZkMDcxNzRhMTkyNTA5Y2E2NmIwNTY2MGJiMTFmZmViMjZjMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I42luB5kh4e8kHqBC2fuEpkfaIRCikd95DvC3RuzQDc)

**Comment by BUJIDAOVS** [comment]
依然很简单，你这判断完之后只有一步。。。我已经回退471了

**Comment by c121914yu** [comment]
无所谓，反正都能实现，看你心情

**Comment by xiaoToby** [comment]
> ![image](https://private-user-images.githubusercontent.com/50446880/330369816-c88f0d1f-3d9a-41bb-a46d-17b5e3acfac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjYxNTcsIm5iZiI6MTcxNTc2NTg1NywicGF0aCI6Ii81MDQ0Njg4MC8zMzAzNjk4MTYtYzg4ZjBkMWYtM2Q5YS00MWJiLWE0NmQtMTdiNWUzYWNmYWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5MzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMjYzYjYyYzE1MDU5YzFlZmUxNTMxNzE3YjkxOTY5OGRhMmQyMjgzNDA4OGRmZmZlMzY5YzMxNjM3MmQ1ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OVvTqE1tSlf3X473Dhfe0f8UXCjsOC1xIcDhyEmu9Ak) 没看到啥问题。有bug和能不能做两码事，你要是觉得它执行不符合预期就说不符合，没搞明白你是想说实现不了还是不符合预期

这个是商用版吗，为什么我的判断器是这样的。。。
![image](https://github.com/labring/FastGPT/assets/40045458/5b6b40c7-446d-46b5-a64b-34dd9b4cd573)
@c121914yu

**Comment by c121914yu** [comment]
> > 无所谓，反正都能实现，看你心情
> 
> 4.8歧义比4.7多多了，我觉得这种复杂度的4.8是没法实现了。4.7也有很多功能我是另外写api的。 ![image](https://private-user-images.githubusercontent.com/98118374/330750993-41316a91-405e-43ee-80a2-75d643fc271b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjcxOTYsIm5iZiI6MTcxNTc2Njg5NiwicGF0aCI6Ii85ODExODM3NC8zMzA3NTA5OTMtNDEzMTZhOTEtNDA1ZS00M2VlLTgwYTItNzVkNjQzZmMyNzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNDA5OWExYjAzNmMyMWMxMzJjMzNlMzYxODZhNjE2OWQwYmQ2OWU0NDkxZjNlMzhiM2NjYjY0MDdjNjAzNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mao86l-oJErQ0Tli1Fch6-yJyZqrTDCTwwh3L5Tabic) ![image](https://private-user-images.githubusercontent.com/98118374/330751032-69626780-50bb-46e8-a003-e613a49ba35f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjcxOTYsIm5iZiI6MTcxNTc2Njg5NiwicGF0aCI6Ii85ODExODM3NC8zMzA3NTEwMzItNjk2MjY3ODAtNTBiYi00NmU4LWEwMDMtZTYxM2E0OWJhMzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzQ2YjFmOWQ2YjM1MGVlZmUxZjExMDVkOGM2NDI3MDBlZmMxYzhmZWEyNzBjYTUxODhlZWRjZTZlYmY5MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9-Z6XKajMd5yPXNGmEWfIO5RRNFsiSb7SEfeHO1ABOg)

看起来并不复杂，就是一堆判断

**Comment by BUJIDAOVS** [comment]
> > > 无所谓，反正都能实现，看你心情
> > 
> > 
> > 4.8歧义比4.7多多了，我觉得这种复杂度的4.8是没法实现了。4.7也有很多功能我是另外写api的。 ![image](https://private-user-images.githubusercontent.com/98118374/330750993-41316a91-405e-43ee-80a2-75d643fc271b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjcxOTYsIm5iZiI6MTcxNTc2Njg5NiwicGF0aCI6Ii85ODExODM3NC8zMzA3NTA5OTMtNDEzMTZhOTEtNDA1ZS00M2VlLTgwYTItNzVkNjQzZmMyNzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNDA5OWExYjAzNmMyMWMxMzJjMzNlMzYxODZhNjE2OWQwYmQ2OWU0NDkxZjNlMzhiM2NjYjY0MDdjNjAzNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mao86l-oJErQ0Tli1Fch6-yJyZqrTDCTwwh3L5Tabic) ![image](https://private-user-images.githubusercontent.com/98118374/330751032-69626780-50bb-46e8-a003-e613a49ba35f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjcxOTYsIm5iZiI6MTcxNTc2Njg5NiwicGF0aCI6Ii85ODExODM3NC8zMzA3NTEwMzItNjk2MjY3ODAtNTBiYi00NmU4LWEwMDMtZTYxM2E0OWJhMzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzQ2YjFmOWQ2YjM1MGVlZmUxZjExMDVkOGM2NDI3MDBlZmMxYzhmZWEyNzBjYTUxODhlZWRjZTZlYmY5MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9-Z6XKajMd5yPXNGmEWfIO5RRNFsiSb7SEfeHO1ABOg)
> 
> 看起来并不复杂，就是一堆判断

真在4.8重做一个就会发现，心态爆炸了。无所谓，fastgpt是个好项目，但我选择停在4.7

**Comment by c121914yu** [comment]
> > > > 无所谓，反正都能实现，看你心情
> > > 
> > > 
> > > 4.8歧义比4.7多多了，我觉得这种复杂度的4.8是没法实现了。4.7也有很多功能我是另外写api的。 ![image](https://private-user-images.githubusercontent.com/98118374/330750993-41316a91-405e-43ee-80a2-75d643fc271b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjcxOTYsIm5iZiI6MTcxNTc2Njg5NiwicGF0aCI6Ii85ODExODM3NC8zMzA3NTA5OTMtNDEzMTZhOTEtNDA1ZS00M2VlLTgwYTItNzVkNjQzZmMyNzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNDA5OWExYjAzNmMyMWMxMzJjMzNlMzYxODZhNjE2OWQwYmQ2OWU0NDkxZjNlMzhiM2NjYjY0MDdjNjAzNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mao86l-oJErQ0Tli1Fch6-yJyZqrTDCTwwh3L5Tabic) ![image](https://private-user-images.githubusercontent.com/98118374/330751032-69626780-50bb-46e8-a003-e613a49ba35f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjcxOTYsIm5iZiI6MTcxNTc2Njg5NiwicGF0aCI6Ii85ODExODM3NC8zMzA3NTEwMzItNjk2MjY3ODAtNTBiYi00NmU4LWEwMDMtZTYxM2E0OWJhMzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzQ2YjFmOWQ2YjM1MGVlZmUxZjExMDVkOGM2NDI3MDBlZmMxYzhmZWEyNzBjYTUxODhlZWRjZTZlYmY5MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9-Z6XKajMd5yPXNGmEWfIO5RRNFsiSb7SEfeHO1ABOg)
> > 
> > 
> > 看起来并不复杂，就是一堆判断
> 
> 真在4.8重做一个就会发现，心态爆炸了。无所谓，fastgpt是个好项目，但我选择停在4.7

那我感觉这关键是自动适配转化问题？

**Comment by mxdlzg** [comment]
触发器还是很有必要保留的，只有if else这类逻辑控制完全是不够的

**Comment by c121914yu** [comment]
> 触发器还是很有必要保留的，只有if else这类逻辑控制完全是不够的

会用就够
