### ISSUE TITLE
一直生成引导性问题

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1487]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
配置了“猜你想问”功能 如下图 怎么确保每次都能生成三个问题啊 
现在的效果是有时候有 有时候没有
![image](https://github.com/labring/FastGPT/assets/50564015/47e9d296-77f2-4c99-b470-81a2086e6b4f)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lxb0425** [comment]
很多时候都没生成 /捂脸
![image](https://github.com/labring/FastGPT/assets/50564015/194383d1-235d-40d4-ab70-d26799113526)

**Comment by c121914yu** [comment]
> 很多时候都没生成 /捂脸
> ![image](https://github.com/labring/FastGPT/assets/50564015/194383d1-235d-40d4-ab70-d26799113526)
> 

你可以看看请求有没有成功。
也可能是模型问题，没返回 json 格式

**Comment by lxb0425** [comment]
好的 谢谢
