### ISSUE TITLE
提示“Quote type error”

### ISSUE THREAD

**Issue by guanyouhui** [labring/FastGPT#1490]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
我用高级编排想实现一个功能，用户问题如果是@某一个关键词，就回复已经设置为某个知识库，同时设置全局变量为“测试”（知识库名称），同理可以设置其他知识库名称，如果没有@关键词，这个时候判断，如果全局变量不是空的，说明设置过全局变量，就走知识库搜索，知识库搜索这边“选择知识库”用了全局变量，比如之前设置的知识库名称为“测试”
<img width="878" alt="8f5705ff40136a0adf70e1bcb4e9d7d" src="https://github.com/labring/FastGPT/assets/6219471/410bacf9-bfa9-4714-88fa-e0ab6cd4644a">
图如上是这样的，但是实际调试发现比如@流程，回复了“已切换到知识库”，再发送随便内容，这个时候会报错提示"Quote type error"
<img width="721" alt="d93eb83c15705ba8f979a4d875ea585" src="https://github.com/labring/FastGPT/assets/6219471/77bc52c2-8f1a-4900-8e69-28c8697981e1">
想问一下，是不是全局变量设置成知识库的名称是不行的，需要其他什么参数呢？
<img width="700" alt="b833132ee95de3292df226b82c3aba4" src="https://github.com/labring/FastGPT/assets/6219471/c3c112d1-b732-42b9-a793-71f2f569663f">
看使用帮助里面这个，显示“404 Not Found”，烦请能提供相关帮助
**复现步骤**

**预期结果**
提供能正确设置全局变量的参数，使得“知识库搜索”功能，使用全局变量时，可以正常使用，或者有渠道能查询到相关需要的参数信息
**相关截图**

**Comment by nongmo677** [comment]
你这个功能吧，最关键的点在于怎么传入知识库信息，实际上你并不能简单传入知识库名称或者知识库id
这里后台的逻辑是需要你传入的是一个列表，传入的类型参考以下代码
https://github.com/labring/FastGPT/blob/cd876251b70deb2ccd6171f6de82e33a036ab948/packages/global/core/workflow/api.d.ts#L4
类似于要传入这么多内容
```json
[
    {
        "datasetId": "66444f9542fabe3144830033",
        "vectorModel": {
            "model": "text-embedding-ada-002",
            "name": "text-embedding-ada-002",
            "avatar": "/imgs/model/openai.svg",
            "defaultToken": 512,
            "maxToken": 3000,
            "weight": 100,
            "charsPointsPrice": 0.1
        }
    }
]
```

直接使用全局变量这件事可能不是那么好实现，建议换成http组件
![image](https://github.com/labring/FastGPT/assets/31816449/f224ceed-3d42-4f57-98bc-f0bbe57f37c2)

**Comment by CloverZhou** [comment]
> 你这个功能吧，最关键的点在于怎么传入知识库信息，实际上你并不能简单传入知识库名称或者知识库id 这里后台的逻辑是需要你传入的是一个列表，传入的类型参考以下代码
> 
> https://github.com/labring/FastGPT/blob/cd876251b70deb2ccd6171f6de82e33a036ab948/packages/global/core/workflow/api.d.ts#L4
> 
> 
> 类似于要传入这么多内容
> ```json
> [
>     {
>         "datasetId": "66444f9542fabe3144830033",
>         "vectorModel": {
>             "model": "text-embedding-ada-002",
>             "name": "text-embedding-ada-002",
>             "avatar": "/imgs/model/openai.svg",
>             "defaultToken": 512,
>             "maxToken": 3000,
>             "weight": 100,
>             "charsPointsPrice": 0.1
>         }
>     }
> ]
> ```
> 
> 直接使用全局变量这件事可能不是那么好实现，建议换成http组件 ![image](https://private-user-images.githubusercontent.com/31816449/330692102-f224ceed-3d42-4f57-98bc-f0bbe57f37c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjk1ODgsIm5iZiI6MTcyMTAyOTI4OCwicGF0aCI6Ii8zMTgxNjQ0OS8zMzA2OTIxMDItZjIyNGNlZWQtM2Q0Mi00ZjU3LTk4YmMtZjBiYmU1N2YzN2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA3NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDBjNTlhM2RjOWQ4OWMzMjgzYzdmYmEwMjNlOWE3N2UyMjBkOTZhNzFlZWRjYTdlNmQ0ODg1YjViMzJkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YSy9u3NnZJggEfTfnas9JFJM8lqwwc0BkEbVOQ7f1rU)

请问具体该怎么做呀？

**Comment by sumingcheng** [comment]
你只要让他返回的内容格式符合这个即可，

> > 你这个功能吧，最关键的点在于怎么传入知识库信息，实际上你并不能简单传入知识库名称或者知识库id 这里后台的逻辑是需要你传入的是一个列表，传入的类型参考以下代码
> > https://github.com/labring/FastGPT/blob/cd876251b70deb2ccd6171f6de82e33a036ab948/packages/global/core/workflow/api.d.ts#L4
> > 
> > 类似于要传入这么多内容
> > ```json
> > [
> >     {
> >         "datasetId": "66444f9542fabe3144830033",
> >         "vectorModel": {
> >             "model": "text-embedding-ada-002",
> >             "name": "text-embedding-ada-002",
> >             "avatar": "/imgs/model/openai.svg",
> >             "defaultToken": 512,
> >             "maxToken": 3000,
> >             "weight": 100,
> >             "charsPointsPrice": 0.1
> >         }
> >     }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 直接使用全局变量这件事可能不是那么好实现，建议换成http组件 ![image](https://private-user-images.githubusercontent.com/31816449/330692102-f224ceed-3d42-4f57-98bc-f0bbe57f37c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjk1ODgsIm5iZiI6MTcyMTAyOTI4OCwicGF0aCI6Ii8zMTgxNjQ0OS8zMzA2OTIxMDItZjIyNGNlZWQtM2Q0Mi00ZjU3LTk4YmMtZjBiYmU1N2YzN2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA3NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDBjNTlhM2RjOWQ4OWMzMjgzYzdmYmEwMjNlOWE3N2UyMjBkOTZhNzFlZWRjYTdlNmQ0ODg1YjViMzJkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YSy9u3NnZJggEfTfnas9JFJM8lqwwc0BkEbVOQ7f1rU)
> 
> 请问具体该怎么做呀？

我这样成功了，符合他的格式传过去就行
![image](https://github.com/user-attachments/assets/b0e5331f-b61d-4c27-a938-9630ecf708cb)
![image](https://github.com/user-attachments/assets/a137465e-9b39-452e-a0b9-38766d70c951)
