### ISSUE TITLE
重排使用的reRankQuery变量处理有误导致带有历史对话的场景下数据召回失败

### ISSUE THREAD

**Issue by mn325** [labring/FastGPT#1495]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/23238057/1abc8b6b-2fa5-4fea-b21c-997232e13827)
同样的问题在第一次问的时候能召回数据，第二次却无法召回数据

**复现步骤**

**预期结果**
无论第几次询问都应召回数据

**相关截图**
查看源码rewriteQuery变量处理有问题，拼接的字符串是个js对象如下图，导致rerank后的分数很低
![image](https://github.com/labring/FastGPT/assets/23238057/4fbc07e7-27ad-42dc-8041-8ec9321bf3af)
![image](https://github.com/labring/FastGPT/assets/23238057/4ac6e552-348c-4a30-b0e5-cdfd5dd367e4)

**Comment by c121914yu** [comment]
同一个对话，给模型发相同内容本身就是严重错误。

**Comment by mn325** [comment]
> 同一个对话，给模型发相同内容本身就是严重错误。
> 没有问题优化情况下，需要通过上下文进行重排，不然连续对话重排就没用了。

但是拼接的上下文信息不对，如图二，item.value是object，应该取item.value下面的text.content

**Comment by c121914yu** [comment]
> > 同一个对话，给模型发相同内容本身就是严重错误。
> > 没有问题优化情况下，需要通过上下文进行重排，不然连续对话重排就没用了。
> 
> 但是拼接的上下文信息不对，如图二，item.value是object，应该取item.value下面的text.content

你的版本问题把

**Comment by mn325** [comment]
> > > 同一个对话，给模型发相同内容本身就是严重错误。
> > > 没有问题优化情况下，需要通过上下文进行重排，不然连续对话重排就没用了。
> > 
> > 但是拼接的上下文信息不对，如图二，item.value是object，应该取item.value下面的text.content
> 
> 你的版本问题把。这个我记得一个来月前已经有人提修复了

4.8的版本

**Comment by c121914yu** [comment]
> > > > 同一个对话，给模型发相同内容本身就是严重错误。
> > > > 没有问题优化情况下，需要通过上下文进行重排，不然连续对话重排就没用了。
> > > 
> > > 但是拼接的上下文信息不对，如图二，item.value是object，应该取item.value下面的text.content
> > 
> > 你的版本问题把。这个我记得一个来月前已经有人提修复了
> 
> 4.8的版本

确实是，他只修改了问题补全的地方，你可以参考 https://github.com/labring/FastGPT/blob/main/packages/service/core/ai/functions/createQuestionGuide.ts 进行修改，增加一个 value 解析函数。
