### ISSUE TITLE
feConfigs初始化配置，下载镜像后启动没有效果

### ISSUE THREAD

**Issue by jingzl** [labring/FastGPT#1496]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/2803602/8bc6ac87-8320-4d21-9d9b-ac482ee87a09)
发现没有效果后，进去容器内，查看 /app/data 下的config.json 文件，发现是更新后。
但就是启动的页面上，没有任何效果，比如 SystemTitle 没有修改成功。

**复现步骤**
1）下载4.8版本的 docker-compose.yml 和 config.json 文件
2）修改config.json 的 feconfigs信息
3）docker-compose up -d

**预期结果**
feconfig的配置有效

**相关截图**

**Comment by c121914yu** [comment]
不会生效

**Comment by jingzl** [comment]
@c121914yu 这样的配置，在现在的版本里，已经不起作用了，对吧。

**Comment by c121914yu** [comment]
> @c121914yu 这样的配置，在现在的版本里，已经不起作用了，对吧。

是的，fecong 不会生效

**Comment by c121914yu** [comment]
但是我发现，他在4.7.1时候改动成效了
![image](https://github.com/labring/FastGPT/assets/50446880/eea1b21f-84b1-4b39-a6d6-6f14efa1d0ef)
