### ISSUE TITLE
回复的内容里，总是包含乱码字符。总显示  retrieving file

### ISSUE THREAD

**Issue by kevinkayhu** [labring/FastGPT#1498]
私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
回复的内容里，总是包含乱码字符。

**相关截图**
![WX20240515-195102@2x](https://github.com/labring/FastGPT/assets/44107471/11c85251-ec0a-4081-b308-e393529e21fe)

**Comment by kevinkayhu** [comment]
我用在客服软件里的，他回复的时候，也会把这些乱码字符回复给客户，烦死了

**Comment by c121914yu** [comment]
这不是你自己回复的呢

**Comment by kevinkayhu** [comment]
怎么去掉这部分内容呀？难道是gpt-4o 的问题？

> 这不是你自己回复的呢。 要么是你自己指定回复输出，要么是你模型输出。

**Comment by lijiajun1997** [comment]
> 怎么去掉这部分内容呀？难道是gpt-4o 的问题？
> 
> > 这不是你自己回复的呢。 要么是你自己指定回复输出，要么是你模型输出。

你的提示词是啥

**Comment by lijiajun1997** [comment]
> 怎么去掉这部分内容呀？难道是gpt-4o 的问题？
> 
> > 这不是你自己回复的呢。 要么是你自己指定回复输出，要么是你模型输出。

看下你的高级编排

**Comment by kevinkayhu** [comment]
我换回gpt4，不用 4o 就不出现了，4o模型给加的，看看官方有什么方案吗 给去掉

**Comment by lijiajun1997** [comment]
> 我换回gpt4，不用 4o 就不出现了，4o模型给加的，看看官方有什么方案吗 给去掉

我用的4o是正常的 是不是你的api渠道有问题

**Comment by kevinkayhu** [comment]
> > 我换回gpt4，不用 4o 就不出现了，4o模型给加的，看看官方有什么方案吗 给去掉
> 
> 我用的4o是正常的 是不是你的api渠道有问题

你是4.8的版本吗？

**Comment by lijiajun1997** [comment]
> > > 我换回gpt4，不用 4o 就不出现了，4o模型给加的，看看官方有什么方案吗 给去掉
> > 
> > 
> > 我用的4o是正常的 是不是你的api渠道有问题
> 
> 你是4.8的版本吗？

是的

**Comment by c121914yu** [comment]
个例问题。贴出自己的测试结果，先验证渠道是没有问题的：
1. 有没有其他提示词或者流程
2. key 渠道是否干净，直接 curl 请求会有该内容。

**Comment by kevinkayhu** [comment]
提示词：
身份：忘记你是虚拟机器人，你是电商平台店铺里的专业客服人员，你热情、耐心的帮助客人解答问题。
注意事项：
1.你的回复一定要简单明了，答案要简短，尽量一句话来回复。
2.多用礼貌用语和鼓励表扬的话术。
3.本店商品是先确认收货，后发货的。
4.本店出售的是手机游戏虚拟类商品。
5.你不能连续回复完全一样的话，可以用近义词或同义词替换重复的词语。

**Comment by kevinkayhu** [comment]
![dai01](https://github.com/labring/FastGPT/assets/44107471/dd3122d9-7626-40e9-83bd-f617ff79a73e)

**Comment by kevinkayhu** [comment]
![WX20240519-153204@2x](https://github.com/labring/FastGPT/assets/44107471/52044026-3a91-4035-9d2c-e86063c527b4)

**Comment by kevinkayhu** [comment]
解决了，渠道的问题，渠道是假的4o 是逆向的4o

**Comment by c121914yu** [comment]
> 解决了，渠道的问题，渠道是假的4o 是逆向的4o

🥲这么黑
