### ISSUE TITLE
docker build出错-20240515更新的版本

### ISSUE THREAD

**Issue by jingzl** [labring/FastGPT#1499]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8，20240515，更新下来的主线版本

**问题描述, 日志截图**
Scope: all 7 workspace projects
Downloading pdfjs-dist@4.0.269: 9.23 MB/9.23 MB, done
Downloading echarts@5.4.1: 8.37 MB/8.37 MB, done
Downloading next@13.5.2: 13.70 MB/13.70 MB, done
Downloading typescript@4.9.5: 11.62 MB/11.62 MB, done
Downloading @node-rs/jieba-linux-x64-gnu@1.10.0: 5.47 MB/5.47 MB, done
Downloading cytoscape-fcose@2.2.0: 7.60 MB/7.60 MB, done
 WARN  4 deprecated subdependencies found: @types/mime@4.0.0, path2d-polyfill@2.1.1, stable@0.1.8, trim@0.0.1
Packages: +1466
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading @next/swc-linux-x64-gnu@13.5.2: 38.52 MB/38.52 MB, done
Downloading monaco-editor@0.47.0: 17.39 MB/17.39 MB, done
Progress: resolved 1534, reused 0, downloaded 1470, added 1466, done
node_modules/.pnpm/core-js@3.36.1/node_modules/core-js: Running postinstall script, done in 494ms
node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild: Running postinstall script, done in 469ms
node_modules/.pnpm/esbuild@0.15.18/node_modules/esbuild: Running postinstall script, done in 470ms
node_modules/.pnpm/canvas@2.11.2_encoding@0.1.13/node_modules/canvas: Running install script, done in 17m 49.3s
. postinstall$ sh ./scripts/postinstall.sh
│  ERR_PNPM_NO_SCRIPT  Missing script: gen:theme-typings
│ Command "gen:theme-typings
│ " not found. Did you mean "pnpm run gen:theme-typings"?

**复现步骤**
1）下载最新版本
2）在根目录下执行 pnpm i

**预期结果**
执行完毕

**相关截图**
拷贝日志见以上

**Comment by tonny-zhang** [comment]
可以使用v4.8的版本，但这个版本在构建docker镜像时会异常退出，今天我也遇到了类似的问题，经过长时间排查可以定位到是 `pnpm build` 编译源码时node内存达溢出，这时可以参考 v4.8.1 里 Dockerfile 文件里增加 `ENV NODE_OPTIONS="--max-old-space-size=4096"` 然后完美解决

由于docker 构建镜像过程会把内部运行的日志隐藏，可以通过直接文件源码里运行 `pnpm build` 复现内存溢出的问题，以下是部分异常日志
```
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb83f50 node::Abort() [/home/ubuntu/.nvm/versions/node/v18.17.0/bin/node]
 2: 0xa94834  [/home/ubuntu/.nvm/versions/node/v18.17.0/bin/node]
 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/ubuntu/.nvm/versions/node/v18.17.0/bin/node]
 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/ubuntu/.nvm/versions/node/v18.17.0/bin/node]
 5: 0xf42265  [/home/ubuntu/.nvm/versions/node/v18.17.0/bin/node]
```

**Comment by jingzl** [comment]
#1572
