### ISSUE TITLE
文档接入、向量搜索、问题优化的源码在哪里

### ISSUE THREAD

**Issue by zixiaotan21** [labring/FastGPT#1500]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

有点好奇csvQA对文档接入、向量搜索、问题优化， 这几部分的源码在哪里? 我在github 的code部分似乎没有找到相应的.py文件。

**Comment by lijiajun1997** [comment]
用的是TypeScript当然找不到py

**Comment by zixiaotan21** [comment]
谢谢！原来是这样。那如果我私有化部署，要修改代码要怎么修改呀~

> 用的是TypeScript当然找不到py

**Comment by c121914yu** [comment]
> 谢谢！原来是这样。那如果我私有化部署，要修改代码要怎么修改呀~
> 
> > 用的是TypeScript当然找不到py

啊哈？源码不是都在github~ 下载下来不就能改了

**Comment by zixiaotan21** [comment]
> > 谢谢！原来是这样。那如果我私有化部署，要修改代码要怎么修改呀~
> > > 用的是TypeScript当然找不到py
> 
> 啊哈？源码不是都在github~ 下载下来不就能改了

噢噢可我糊涂了，现在明白啦！谢谢！还想请教一下，我现在想私有化部署，是用sealos还是docker compose部署方便呀？

**Comment by c121914yu** [comment]
> > > 谢谢！原来是这样。那如果我私有化部署，要修改代码要怎么修改呀~
> > > > 用的是TypeScript当然找不到py
> > 
> > 
> > 啊哈？源码不是都在github~ 下载下来不就能改了
> 
> 噢噢可我糊涂了，现在明白啦！谢谢！还想请教一下，我现在想私有化部署，是用sealos还是docker compose部署方便呀？

sealos不需要自己维护云资源。docker compose需要自己维护云资源，备份和监控等工作。

**Comment by zixiaotan21** [comment]
> > > > 谢谢！原来是这样。那如果我私有化部署，要修改代码要怎么修改呀~
> > > > > 用的是TypeScript当然找不到py
> > > 
> > > 
> > > 啊哈？源码不是都在github~ 下载下来不就能改了
> > 
> > 
> > 噢噢可我糊涂了，现在明白啦！谢谢！还想请教一下，我现在想私有化部署，是用sealos还是docker compose部署方便呀？
> 
> sealos不需要自己维护云资源。docker compose需要自己维护云资源，备份和监控等工作。

好的好的！那我自己再看看哪个好上手做，感谢回复！
