### ISSUE TITLE
本地部署的Fastgpt接入企业微信作为智能客服问题

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1501]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
现在部署本地fastgpt，如何接入企业微信或者微信，我看到有几种方式
1 是这种 如下图
![image](https://github.com/labring/FastGPT/assets/50564015/3059d715-2912-4157-813f-bab4bb372984)

2 是文档上https://doc.fastai.site/docs/use-cases/wechat/的方式 使用了智能微秘书的方式

这两种有什么区别吗 智能微秘书可以部署本地并且结合本地部署的fastgpt使用吗
都是针对企业微信或者微信吗
是否支持接入多个啊
**复现步骤**

**预期结果**

**相关截图**

**Comment by KanoSang** [comment]
我会

**Comment by c121914yu** [comment]
没区别，不同项目而已，微秘书用的多一点。

**Comment by sdytzjp** [comment]
> 我会

请教下如何实现接入企业微信
