### ISSUE TITLE
刚接入的bge reranker 测试正常，运行日志总是提示"重排结果"为false

### ISSUE THREAD

**Issue by lonrencn** [labring/FastGPT#1502]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本** 

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号:   v4.8

**问题描述, 日志截图**
刚接入的bge reranker 测试正常，运行日志提示"重排结果"为false
**复现步骤**
调用知识库
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/158190203/87db5c2c-a01f-4739-93cf-344730aa52ab)
![image](https://github.com/labring/FastGPT/assets/158190203/fd92ca84-9bde-44d0-8651-6ee6549bc713)
![image](https://github.com/labring/FastGPT/assets/158190203/6bd1cd15-89a9-4d92-b909-897a97ce82a5)

**Comment by Linnnkkk** [comment]
请问解决了吗？

**Comment by Linnnkkk** [comment]
请问解决了吗？

**Comment by lonrencn** [comment]
解决了，用的xinference做的，没问题
