### ISSUE TITLE
升级4.8版本后由于没有了触发器，自定义插件可以添加多输出节点功能

### ISSUE THREAD

**Issue by yjzzcao** [labring/FastGPT#1505]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
升级 4.8 版本后，我需要在主应用添加多个判断器，以实现不同状态下的流程设计。
希望在自定义插件的设计中，可以支持类似判断器的多点输出，避免在主应用中额外添加判断器。

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
是的，这个应该会在4.8.2推出

**Comment by yjzzcao** [comment]
> 是的，这个应该会在4.8.2推出

感谢，另外多问一句，目前有明确的升级时间吗？

**Comment by c121914yu** [comment]
> > 是的，这个应该会在4.8.2推出
> 
> 感谢，另外多问一句，目前有明确的升级时间吗？

估计在5月底

**Comment by yjzzcao** [comment]
谢谢 ，那这个问题我就关闭了。
