### ISSUE TITLE
输出echarts图表只有一片空白

### ISSUE THREAD

**Issue by thegenway** [labring/FastGPT#1506]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
按照 https://github.com/labring/FastGPT/issues/1220 的方式，在指定回复里写markdown里面写echarts的json，结果输出是一片空白

![image](https://github.com/labring/FastGPT/assets/12321764/25746301-7032-44c6-b2ca-0fd7bac90f75)

**复现步骤**

**预期结果**

**相关截图**

**Comment by nongmo677** [comment]
![image](https://github.com/labring/FastGPT/assets/31816449/e8400a61-95f0-4a85-8d4d-067442fb997a)

你的网络不行吧

**Comment by nongmo677** [comment]
![image](https://github.com/labring/FastGPT/assets/31816449/6787fde3-0481-4557-b0d7-52322b650852)

源码部署版也没问题

**Comment by thegenway** [comment]
会不会和控制台的这个错误有关，这个错是进入进入fastgpt主页面就出现了，另外我在4.7是没有这个错的，更新到4.8后就有了
![image](https://github.com/labring/FastGPT/assets/12321764/15470dc0-6973-46ce-bccf-a8a205971dee)

**Comment by thegenway** [comment]
但是这些错不影响正常使用，除了echarts图表是空白的
![image](https://github.com/labring/FastGPT/assets/12321764/73164b13-4c00-47eb-b7eb-364636ac6f0e)

**Comment by thegenway** [comment]
啊啊。我在公有云版本里测试也是这样...
![image](https://github.com/labring/FastGPT/assets/12321764/e02ffbdc-352a-4699-bc6c-646cf5e51159)

**Comment by thegenway** [comment]
好吧我知道了，直接从echarts官网例子里复制过来的json不能用，需要把每个字段都加上双引号，我上面第二幅图加上双引号了但加的是中文双引号😵，现在没问题了。
（控制台里的报错还是一直有存在的）

**Comment by sdytzjp** [comment]
跟进下

**Comment by sdytzjp** [comment]
> 好吧我知道了，直接从echarts官网例子里复制过来的json不能用，需要把每个字段都加上双引号，我上面第二幅图加上双引号了但加的是中文双引号😵，现在没问题了。 （控制台里的报错还是一直有存在的）

你好 能否给个具体的参考 没接触过这部分
