### ISSUE TITLE
指定回复后上下文就被截断

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#1512]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.7.0

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/106878712/3374b4d2-474c-4926-add5-4561f6067d40)

**复现步骤**

**预期结果**
希望在满足知识库搜索为空和上下文中没有提到的问题，才进行指定回复分支！  如果只指定搜索为空回复，便无法关联上下文
**相关截图**
![image](https://github.com/labring/FastGPT/assets/106878712/ed3c9267-e7f7-4ae4-b8f6-f815a5501124)

**Comment by heart18z** [comment]
已经确认4.8的编排也无法实现这个功能

**Comment by heart18z** [comment]
类似这种条件的判断
![image](https://github.com/labring/FastGPT/assets/106878712/ec8d5d05-5b4a-4bc2-a80f-70b11a12af08)

**Comment by c121914yu** [comment]
没看懂你想干啥

**Comment by heart18z** [comment]
我希望走指定回复的判断条件是，1.知识库检索不到和2.上下文没有匹配到问题信息
目前的流程来看，似乎无法同时满足这两个条件

**Comment by c121914yu** [comment]
> 我希望走指定回复的判断条件是，1.知识库检索不到和2.上下文没有匹配到问题信息 目前的流程来看，似乎无法同时满足这两个条件

上下文是一个对象，不是字符串

**Comment by lijiajun1997** [comment]
向量相关度0.45， 那不相关的也会被匹配上，基本不太可能在知识库判定为空了。你得在AI提示词里加，如过提供的<data>与问题不相关，你应该拒绝回答并回复：“xxx”
