### ISSUE TITLE
改进自动保存功能

### ISSUE THREAD

**Issue by cloudtuotuo** [labring/FastGPT#1517]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本：4.8
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
4.8新版，当我们编辑了高级编排后，很多时候是不希望保存配置的，只是一种调试；但退出时，却会被【自动保存】配置，导致覆盖了原有配置

建议优化这个功能，当退出时，提示有自动保存的配置可以保存，由用户选择是否保存

**Comment by c121914yu** [comment]
这种感觉复制一份更合适

**Comment by cloudtuotuo** [comment]
一些模块需要不断调整提示词，以获得更好的效果，但不是每次的调试都会达到效果
如果每一个应用都复制出来一个应用来做测试，会比较麻烦，还是在原应用做测试比较好

所以建议结合一下老版本和新版本

**Comment by bincooo** [comment]
我也郁闷咋弄个自动保存。。。
修改完点一下也不是很麻烦

**Comment by sdytzjp** [comment]
严重同意，模型提示词改来改去，忘记了初衷，又回不去了

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8.10-alpha
