### ISSUE TITLE
配置引用提示词不生效问题

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#1521]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

如何在知识库检索不到相关引用数据时，让AI拒绝本次回答。
![image](https://github.com/labring/FastGPT/assets/106878712/a3cb8848-d913-4174-8ecc-e7f0efc973c1)
![image](https://github.com/labring/FastGPT/assets/106878712/14f000fa-a539-494f-8e12-99aef9740588)

**复现步骤**

**预期结果**

**相关截图**

**Comment by nongmo677** [comment]
高级编排中，加入一个判断器

**Comment by c121914yu** [comment]
😂提示词对模型不一定有用，用 gpt4 试试

**Comment by c121914yu** [comment]
😂提示词对模型不一定有用，用 gpt4 试试

**Comment by xiaoToby** [comment]
> 😂提示词对模型不一定有用，用 gpt4 试试

非常赞同，并且相同的提示词用在不同的模型时，效果也不相同和稳定

**Comment by xiaoToby** [comment]
> 高级编排中，加入一个判断器

判断器真不知道该怎么使用，能提供一个案例吗？@nongmo677

**Comment by xiaoToby** [comment]
@heart18z  
可以参考一下这个https://github.com/labring/FastGPT/issues/1545#issuecomment-2121646595
