### ISSUE TITLE
API 秘钥管理，无论删除哪个秘钥，实际删除的是列表最后一条

### ISSUE THREAD

**Issue by huangyunxin** [labring/FastGPT#1523]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
API 秘钥管理，无论删除哪个秘钥，实际删除的是列表最后一条
在私有部署的4.7版本发现的这个问题；后来到线上的4.8版本测试，也有这个问题
![image](https://github.com/labring/FastGPT/assets/26621931/d766c44e-772f-4912-ae86-1436b9a46a2d)

**Comment by c121914yu** [comment]
感谢。
这个PR会修复它。是由于这个函数调用的问题。
![image](https://github.com/labring/FastGPT/assets/50446880/42371827-5d80-4150-b461-ffbcec26731a)
