### ISSUE TITLE
 retrieving file (file-rDAjDuHwl7fCW3elUS0V7gir) ok   end-searching

### ISSUE THREAD

**Issue by kevinkayhu** [labring/FastGPT#1526]
有没有人帮帮我，用的4.8的版本，gpt-4o，回答问题 一直包含这段信息。
![WX20240517-231528@2x](https://github.com/labring/FastGPT/assets/44107471/fa9bdae8-5308-4147-82d4-0fd276d342b2)
![WX20240517-234620@2x](https://github.com/labring/FastGPT/assets/44107471/c4903dfa-e37d-47a2-8b2e-77c2f6c660e1)

**Comment by kevinkayhu** [comment]
有技术大佬吗？给指点下，可以发个红包，

**Comment by c121914yu** [comment]
> 有技术大佬吗？给指点下，可以发个红包，

有其他提示词或者流程么？
key 渠道干净么？

**Comment by kevinkayhu** [comment]
> > 有技术大佬吗？给指点下，可以发个红包，
> 
> 有其他提示词或者流程么？ key 渠道干净么？直接 curl 请求会有这个内容么？

有微信吗 ？我加你请教

**Comment by c121914yu** [comment]
不加。有问题issue解决即可。把对应测试结果贴出来

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues 重复issue，旧issue回复。
