### ISSUE TITLE
文本内容提取无法正确解析结果

### ISSUE THREAD

**Issue by chenlei0913** [labring/FastGPT#1532]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x ] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8

- [ ] 公有云版本
- [ x ] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
问题截图：
<img width="1077" alt="问题" src="https://github.com/labring/FastGPT/assets/8358994/7dc80239-8bc9-4ee9-adb5-66715ccf2a45">
答复截图：
<img width="1395" alt="答案" src="https://github.com/labring/FastGPT/assets/8358994/bb7977ba-4e5c-475b-a28b-e5d875ab2b43">
日志位置：
<img width="957" alt="加日志位置" src="https://github.com/labring/FastGPT/assets/8358994/524785c4-9f69-412b-bbde-70643bd1b0f6">

**复现步骤**

**预期结果**
从返回结果中获取到真正的json并解析出提取的内容。

**相关截图**

**Comment by c121914yu** [comment]
无法解析 json 的

**Comment by c121914yu** [comment]
返回值不正确呢

**Comment by chenlei0913** [comment]
> 返回值不正确呢

AI返回内容只能是 JSON 字符串，不能带这种巴拉巴拉解释一大堆的这种回复，并且不能是 Markdown 形式的，是吗？

**Comment by c121914yu** [comment]
> > 返回值不正确呢
> 
> AI返回内容只能是 JSON 字符串，不能带这种巴拉巴拉解释一大堆的这种回复，并且不能是 Markdown 形式的，是吗？

印象中，是有一点兼容处理的，会截取括号之间的内容，待会去看看。

**Comment by nongmo677** [comment]
你的日志里面都明显看到 function=> undefined 了，你这个模型不支持functionCall 或者toolChoice，没有返回指定的结果

但是你的模型给你返回了带有json格式的结果，你应该用提示词模式尝试提取，配置提示词模式的文本提取具体请参照官方config.json配置参数

提示词模式文本提取代码如下：
https://github.com/labring/FastGPT/blob/e35ce2caa04034bf0337d8c5b39c9d384ba0779e/packages/service/core/workflow/dispatchV1/agent/extract.ts#L365

**Comment by chenlei0913** [comment]
> 应该

测试有效。已改为使用提示词模式。非常感谢。
