### ISSUE TITLE
请教，如何让fastgpt可以识别图片链接？

### ISSUE THREAD

**Issue by kevinkayhu** [labring/FastGPT#1534]
本地上传的图片可以识别，但是我的场景无法上传，是发送图片链接给gpt。

现在发送链接，他说他无法访问外部链接。头大

![WX20240520-105728@2x](https://github.com/labring/FastGPT/assets/44107471/8f0d8d0d-e16b-4443-be34-4148799ef53d)

**Comment by nongmo677** [comment]
实际上你可以点击查看详情，你就知道上传图片的转过程了

参考下面例子的格式

https://github.com/labring/FastGPT/blob/8e8ceb74396c4333e63d4a5ef209eb7af928e9b7/packages/service/core/chat/utils.ts#L124

把格式输入会被转换成相应的api参数发送给模型服务

例如
![image](https://github.com/labring/FastGPT/assets/31816449/1fe0f00a-b83d-4e87-9356-9c142b2cd6e1)

**Comment by kevinkayhu** [comment]
> 实际上你可以点击查看详情，你就知道上传图片的转过程了
> 
> 参考下面例子的格式
> 
> https://github.com/labring/FastGPT/blob/8e8ceb74396c4333e63d4a5ef209eb7af928e9b7/packages/service/core/chat/utils.ts#L124
> 
> 把格式输入会被转换成相应的api参数发送给模型服务
> 
> 例如 ![image](https://private-user-images.githubusercontent.com/31816449/331938695-1fe0f00a-b83d-4e87-9356-9c142b2cd6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzgzNDksIm5iZiI6MTcxNjE3ODA0OSwicGF0aCI6Ii8zMTgxNjQ0OS8zMzE5Mzg2OTUtMWZlMGYwMGEtYjgzZC00ZTg3LTkzNTYtOWMxNDJiMmNkNmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA0MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMDVkZjFhZGY4NTBkNmJlNDMzMTkyYjcyZDIxNGFiY2I3MWZhYmFmNzQ1ZDVhYWExNTJkNGVjOWNhYzNjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCTV5pLWpVY2HoACU5cmNuVpV-Sr3DdFvleZzfZbjxs)

我是代码小白，请问可以定制吗？

**Comment by kevinkayhu** [comment]
我还有别的需求，方便加你吗？

**Comment by ifkd111** [comment]
> 我还有别的需求，方便加你吗？



> 实际上你可以点击查看详情，你就知道上传图片的转过程了
> 
> 参考下面例子的格式
> 
> https://github.com/labring/FastGPT/blob/8e8ceb74396c4333e63d4a5ef209eb7af928e9b7/packages/service/core/chat/utils.ts#L124
> 
> 把格式输入会被转换成相应的api参数发送给模型服务
> 
> 例如 ![image](https://private-user-images.githubusercontent.com/31816449/331938695-1fe0f00a-b83d-4e87-9356-9c142b2cd6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODA0NzQsIm5iZiI6MTcxNjE4MDE3NCwicGF0aCI6Ii8zMTgxNjQ0OS8zMzE5Mzg2OTUtMWZlMGYwMGEtYjgzZC00ZTg3LTkzNTYtOWMxNDJiMmNkNmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA0NDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNmQzNTYxNWY3MTJjODk1ZTNmMDBhZjFjNGI2NmM4NTg5YmQ1NDZlMDBkNTQ4ZWQ2YzBkMmUwNzBlYzY1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTla3H1VAMHaTcrXu9aGLm6o-0xJ-sy0YSmKDkV4utE)

你好大佬，能加你吗，求救

**Comment by ifkd111** [comment]
> 实际上你可以点击查看详情，你就知道上传图片的转过程了
> 
> 参考下面例子的格式
> 
> https://github.com/labring/FastGPT/blob/8e8ceb74396c4333e63d4a5ef209eb7af928e9b7/packages/service/core/chat/utils.ts#L124
> 
> 把格式输入会被转换成相应的api参数发送给模型服务
> 
> 例如 ![image](https://private-user-images.githubusercontent.com/31816449/331938695-1fe0f00a-b83d-4e87-9356-9c142b2cd6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODE1MDMsIm5iZiI6MTcxNjE4MTIwMywicGF0aCI6Ii8zMTgxNjQ0OS8zMzE5Mzg2OTUtMWZlMGYwMGEtYjgzZC00ZTg3LTkzNTYtOWMxNDJiMmNkNmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA1MDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MDI3MDgxZjQ2OTI3NzdjNGE5ZGEzYzAzYTcwOTFlNmY3YzFmYzRhMTIwYzE4OGFmNDA1ZGJmYjllODkyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pntn-8ueQjhBcZf1CFfW5h6pi8XqQjyBauN9fj7lrQ)
123123123123123
求救，大佬加加

**Comment by nongmo677** [comment]
> 我还有别的需求，方便加你吗？

建议加群，大家一起讨论，或者遇到问题可以提issue

**Comment by kevinkayhu** [comment]
> > 我还有别的需求，方便加你吗？
> 
> 建议加群，大家一起讨论，或者遇到问题可以提issue
我在第28群啊，我们不在一个群吧。没法一起讨论

**Comment by swallowMuzi** [comment]
> > > 我还有别的需求，方便加你吗？
> > 
> > 
> > 建议加群，大家一起讨论，或者遇到问题可以提issue
> > 我在第28群啊，我们不在一个群吧。没法一起讨论

你好，我有个问题想请教你，可以加个联系方式一起学习讨论吗

**Comment by swallowMuzi** [comment]
> > > 我还有别的需求，方便加你吗？
> > 
> > 
> > 建议加群，大家一起讨论，或者遇到问题可以提issue
> > 我在第28群啊，我们不在一个群吧。没法一起讨论

你好，我有个问题想请教你，可以加个联系方式一起学习讨论吗，我的微信号是wxid_dikdogpmpzpm22

**Comment by slot181** [comment]
> > 实际上你可以点击查看详情，你就知道上传图片的转过程了
> > 参考下面例子的格式
> > https://github.com/labring/FastGPT/blob/8e8ceb74396c4333e63d4a5ef209eb7af928e9b7/packages/service/core/chat/utils.ts#L124
> > 
> > 把格式输入会被转换成相应的api参数发送给模型服务
> > 例如 ![image](https://private-user-images.githubusercontent.com/31816449/331938695-1fe0f00a-b83d-4e87-9356-9c142b2cd6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzgzNDksIm5iZiI6MTcxNjE3ODA0OSwicGF0aCI6Ii8zMTgxNjQ0OS8zMzE5Mzg2OTUtMWZlMGYwMGEtYjgzZC00ZTg3LTkzNTYtOWMxNDJiMmNkNmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA0MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMDVkZjFhZGY4NTBkNmJlNDMzMTkyYjcyZDIxNGFiY2I3MWZhYmFmNzQ1ZDVhYWExNTJkNGVjOWNhYzNjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCTV5pLWpVY2HoACU5cmNuVpV-Sr3DdFvleZzfZbjxs)
> 
> 我是代码小白，请问可以定制吗？

试了一下你这个格式还是不行……完全没有效果

**Comment by nongmo677** [comment]
@slot181 

属实是硬控了我几分钟，方法原理给了，而且源码引用也给出来了

首先声明这个回答已经很久之前的了，我部署的版本也一直没有更新，保持稳定状态，我起一个容器给你试一下

image:  fastgpt:v4.6.9

![image](https://github.com/labring/FastGPT/assets/31816449/b453a35c-402d-475f-b166-057a01206c2e)

![image](https://github.com/labring/FastGPT/assets/31816449/34038626-7210-4431-b404-18cf4d3ec821)

如果不行那就是版本更新了，机制改变了
像我的版本手动输入那样格式的内容，是会自动转成图片显示在界面上的，就和图1一样
我在线上新版试了一下，直接输入会被当作文本，不进行转换
这个是一个输入框文本转成api参数的问题，从源码上找规则逻辑然后更改一下也应该能达到目的，可以自己尝试

**Comment by c121914yu** [comment]
4.8.9 可直接读取链接
