### ISSUE TITLE
AI对话中的返回AI内容开关无效

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1538]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
打开“返回AI内容”：
![image](https://github.com/labring/FastGPT/assets/40045458/b40def90-69b7-4831-b7f1-9ba97a6f023e)
![image](https://github.com/labring/FastGPT/assets/40045458/1d0fe89c-f51b-4bc2-b6f7-191921a0fcfb)

关闭“返回AI内容”：
![image](https://github.com/labring/FastGPT/assets/40045458/44f51d87-10c6-4895-921d-992d38d5fbba)
![image](https://github.com/labring/FastGPT/assets/40045458/5feea3d2-36ed-44c4-ba65-b73d6d25b1d9)
![image](https://github.com/labring/FastGPT/assets/40045458/c94caa7a-5fda-4afe-b4f3-ee9f12054855)

@nongmo677 @c121914yu @lijiajun1997
**复现步骤**

**预期结果**

**相关截图**

**Comment by xiaoToby** [comment]
我测试了qwen,chatglm3,llama3，发现只有llama3会出现，关闭了“AI回复内容”之后，输出到下一个组件的内容是当前组件中的提示词

**Comment by c121914yu** [comment]
没看到你的流程~ 而且还有问题优化，你确定不是问题优化时候，模型乱输出了？

**Comment by xiaoToby** [comment]
可能还真是模型不稳定吧，测试了一下又正常了
