### ISSUE TITLE
可以支持本地部署的模型吗比如llama

### ISSUE THREAD

**Issue by lifeofbow** [labring/FastGPT#154]
可以支持本地部署的模型吗

**Comment by c121914yu** [comment]
支持通过 oneapi 接入其他模型，

**Comment by SaraiQX** [comment]
请问如果用llama2， 可以修改 FastGPT/files/models/ChatGLM2/openai_api.py 的代码么？不胜感激！
```

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_name", default="16", type=str, help="Model name")
    args = parser.parse_args()

    model_dict = {
        "4": "THUDM/chatglm2-6b-int4",
        "8": "THUDM/chatglm2-6b-int8",
        "16": "THUDM/chatglm2-6b"
    }

    model_name = model_dict.get(args.model_name, "THUDM/chatglm2-6b")
```

**Comment by winnie1228** [comment]
请问接入本地模型成功了吗

**Comment by bruceye777** [comment]
> 支持通过 oneapi 接入其他模型，

问题是oneapi，我看了他们的文档，并没有说怎么接入自己本地部署的大模型，支持的模型都是非本地的，商业化的大模型。

**Comment by c121914yu** [comment]
> > 支持通过 oneapi 接入其他模型，
> 
> 问题是oneapi，我看了他们的文档，并没有说怎么接入自己本地部署的大模型，支持的模型都是非本地的，商业化的大模型。

@songquanpeng oneapi也补充些本地模型说明？

本地模型可以通过填表自定义模型，请求到自己服务器。可以参考https://doc.fastgpt.run/docs/other/ChatGLM2/

**Comment by songquanpeng** [comment]
本地的模型需要其支持 OpenAI 的 API 格式，One API 目前能做的就是自定义渠道 + 自定义模型名称。

**Comment by winnie1228** [comment]
> 本地的模型需要其支持 OpenAI 的 API 格式，One API 目前能做的就是自定义渠道 + 自定义模型名称。
![image](https://github.com/labring/FastGPT/assets/78136057/160e1773-c17c-48e6-a2d2-35a324267ac4)
你好，我这边本地模型是OpenAI的API格式，请问1.图片中的秘钥是openai的api_key值吗？2.访问本地模型是内网，代理应该怎么填？
