### ISSUE TITLE
知识库添加内容一直报错 404 page not found

### ISSUE THREAD

**Issue by JiaXuanZheng** [labring/FastGPT#1540]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/30172745/5e9a4068-5fbb-48c2-9fe1-30a0ccadc37b)

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/30172745/0183a63b-7136-40cb-a298-3dbc911557cf)

![image](https://github.com/labring/FastGPT/assets/30172745/6d294fb8-1ee6-4c9a-a846-9dbe8ec58155)

![image](https://github.com/labring/FastGPT/assets/30172745/c8a1f82f-9bda-429f-b4c9-048f2951383f)
![image](https://github.com/labring/FastGPT/assets/30172745/faf5ff46-216c-415d-96c2-cb9f3733011d)
![image](https://github.com/labring/FastGPT/assets/30172745/f8f511ac-f58a-4f95-898e-c47c209b1886)
![image](https://github.com/labring/FastGPT/assets/30172745/155f646f-17ca-4c87-9dc6-273b515f80ef)
![image](https://github.com/labring/FastGPT/assets/30172745/4679bfdb-ed17-4e2b-ab70-0f6de5f54195)

**Comment by xiaohei999** [comment]
我的也是这样 蹲一个结果

**Comment by c121914yu** [comment]
m3e能 curl 通？

**Comment by xiaohei999** [comment]
已收到你的来信

**Comment by wuquegongzi** [comment]
<img width="422" alt="截屏2024-05-21 16 56 19" src="https://github.com/labring/FastGPT/assets/29697202/1ffff13f-13e5-4b38-a78e-013869f81e0e">
我也遇到了同样的问题，curl  m3e是通的

**Comment by wuquegongzi** [comment]
> <img alt="截屏2024-05-21 16 56 19" width="422" src="https://private-user-images.githubusercontent.com/29697202/332355608-1ffff13f-13e5-4b38-a78e-013869f81e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODIyNzMsIm5iZiI6MTcxNjI4MTk3MywicGF0aCI6Ii8yOTY5NzIwMi8zMzIzNTU2MDgtMWZmZmYxM2YtMTNlNS00YjM4LWE3OGUtMDEzODY5ZjgxZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA4NTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZjVlOWY2NWQ5YTZlYmIwMmQ2NGM4NWI0MjE3YzZlODcxMjBkMWY1NWMxZTU5MTY0ODVjZjQ0NTI1NWNkOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJZfFUB2F6jlwlwdmdJ8DT00CbxQ45LDzFLdgdJZMm4"> 我也遇到了同样的问题，curl m3e是通的



> <img alt="截屏2024-05-21 16 56 19" width="422" src="https://private-user-images.githubusercontent.com/29697202/332355608-1ffff13f-13e5-4b38-a78e-013869f81e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODI2NzEsIm5iZiI6MTcxNjI4MjM3MSwicGF0aCI6Ii8yOTY5NzIwMi8zMzIzNTU2MDgtMWZmZmYxM2YtMTNlNS00YjM4LWE3OGUtMDEzODY5ZjgxZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjN2ZhZjBhMGNhZjgzMDAyYTM5OTI1NjE2NzNlYjRlYWQyNTFjODNiY2NiN2FjM2MyOWZiOTZiMzZhMGVjNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RQAI4DNnhtEyX2aDOVMTK9_E-vuUsG07F1yfBYY7pL4"> 我也遇到了同样的问题，curl m3e是通的

解决了，使用one-api,配置http://xxxxxx:3001,使用 one-api的秘钥
![image](https://github.com/labring/FastGPT/assets/29697202/19154a4d-5a3b-4342-91ce-9cbd5f9c3d98)
<img width="816" alt="截屏2024-05-21 17 09 12" src="https://github.com/labring/FastGPT/assets/29697202/88ee87b9-b669-4999-a6f1-55424b884f91">

它会直接调用本地6008端口m3e模型，如果对接外部，估计是要在config.json配置里配置vectorModels时指定远程调用地址
