### ISSUE TITLE
高级编排的提示模块定义的全局变量用api调用的python不能赋值

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#1542]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ X] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
高级编排定义了一个全局变量aaa.然后用python代码在post调用时在Data中给aaa赋值。后续流程拿到这个变量为空。尝试在代码中给自带的全局变量赋值，如chatid,赋值能够成功，他们的唯一区别是aaa是any类型，chatid是string类型。但如果直接在高级编排中给aaa赋值一个字符串又是可以成功的。看上去只有自定义的全局变量通过api无法赋值。

**复现步骤**

**预期结果**
调用api可以给自定义的全局变量赋值
**相关截图**

**Comment by c121914yu** [comment]
给 variables 对象传值就可以

**Comment by ppkitty** [comment]
传值不成功。一样的传值方法---“key：value”，chatId就能拿到值，但自定义的变量就是空的。

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/ef05f3d5-a988-4097-9217-3baaf315ecdc)
![image](https://github.com/labring/FastGPT/assets/50446880/735d7a98-523b-4030-8f47-cd19e3340b72)

我测试了是ok的，请检查下你请求内容，有问题在reopen

**Comment by ppkitty** [comment]
可以了，感谢！
