### ISSUE TITLE
使用API接入应用，“对话日志”中无记录

### ISSUE THREAD

**Issue by shikaiwei1** [labring/FastGPT#1544]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8

**问题描述, 日志截图**
使用应用的API KEY访问应用，并使用feishu-openai框架接入飞书。正常对话后，在“对话日志”中看不到对话相关日志

**复现步骤**
1. 在“发布应用”中创建API KEY
2. 使用feishu-openai框架进行流式对话（正常对话）
3. 在“对话日志”中查看日志
**预期结果**
1. 应当有对话日志

**相关截图**
![image](https://github.com/labring/FastGPT/assets/24493077/f3d04f00-aae7-420d-801b-b32f37017557)

**Comment by phplaoyao** [comment]
对话接口 chatId 必须有值才会记录到对话日志里面

**Comment by nongmo677** [comment]
建议结合mongo数据库chats这张表和代码里的查表语句进行排查

https://github.com/labring/FastGPT/blob/8e8ceb74396c4333e63d4a5ef209eb7af928e9b7/projects/app/src/pages/api/core/app/getChatLogs.ts#L41

**Comment by SMSshuai** [comment]
> 对话接口 chatId 必须有值才会记录到对话日志里面

![image](https://github.com/labring/FastGPT/assets/66891829/38c98899-b34c-4122-952e-d66d303a40fe)
在api请求时传递了chatId也遇到了一样的情况，版本为4.8。在线访问是正常的
