### ISSUE TITLE
添加知识库后到问题

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1545]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
添加知识库后，如果输入的问题知识库没有查到 想让大模型回答 怎么做啊 
开了问题优化，有时候有效果，有时候没效果
**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/7c709421-bbc6-48bc-8ae1-08a52d0b06eb)
提示词里加上

**Comment by lxb0425** [comment]
这是啥原因
![image](https://github.com/labring/FastGPT/assets/50564015/e0be728b-7759-42d5-8357-d4fcb47668b8)
![image](https://github.com/labring/FastGPT/assets/50564015/06e62568-ef49-4d8e-8d84-3dd8e4f83b6d)

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/f31760bb-27e5-4faf-8854-43bd9d9e9831)
![image](https://github.com/labring/FastGPT/assets/40045458/898045a9-5854-4cea-acf5-826512086ab6)
@lxb0425
