### ISSUE TITLE
FastGPT不用docker能部署吗？

### ISSUE THREAD

**Issue by KevinFanng** [labring/FastGPT#1546]
阿里云PAI平台
![image](https://github.com/labring/FastGPT/assets/85269058/03330604-a576-4447-a66c-49d0d9ef0002)
不用docker，能部署吗？

**Comment by lijiajun1997** [comment]
FastGPT是前端应用，本身不是大模型，你为啥要用PAI部署。

**Comment by KevinFanng** [comment]
PAI上跑大模型啊

**Comment by lijiajun1997** [comment]
> PAI上跑大模型啊

你把大模型当作API，接入fastgpt就好，fastgpt 用docker或者sealos部署。

**Comment by KevinFanng** [comment]
PAI不连外网

**Comment by lijiajun1997** [comment]
> PAI不连外网

不连外网你fastgpt部署怎么用 不太了解PAI但是我印象里是可以作为api提供对外服务的才是

**Comment by KevinFanng** [comment]
PAI平台的限制。不连外网，这个不大严谨，是PAI不能向外提供API，PAI可以访问互联网，也就是说，别人不能访问PAI的服务，但PAI可以访问别人的服务。

**Comment by nianshengmei** [comment]
不使用docker部署成功了吗，求教程

**Comment by azhe1234** [comment]
> 阿里云PAI平台 ![image](https://private-user-images.githubusercontent.com/85269058/332266388-03330604-a576-4447-a66c-49d0d9ef0002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTExNjYsIm5iZiI6MTcyNDIxMDg2NiwicGF0aCI6Ii84NTI2OTA1OC8zMzIyNjYzODgtMDMzMzA2MDQtYTU3Ni00NDQ3LWE2NmMtNDlkMGQ5ZWYwMDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiY2ZlMTEyYTYwMWQwZDUzZDQ1YThkMzIwYjE0NzI2NDA3ZTZmNTgyMjFkZWNkNjAwZDEyMGY4N2NlYmUxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LEHLOBHiqYgTbiwjSbsbovockvwdSGsEkeI7v-bmcGU) 不用docker，能部署吗？

请问你部署成功了吗，我也是使用的PAI，一直想用docker部署，发现部署不上去。

**Comment by azhe1234** [comment]
> 不使用docker部署成功了吗，求教程

请问你部署成功了吗
