### ISSUE TITLE
知识库是上传到云端吗，有资料泄漏风险吗

### ISSUE THREAD

**Issue by fanfanyaya** [labring/FastGPT#1548]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
知识库的存储方式取决于部署模式，主要有两种：公有云（fastgpt在线版）和本地部署。

1. **公有云部署**：
   - **存储位置**：在公有云部署模式下，您的知识库数据将被存储在FastGPT的云服务器上。
   - **安全性**：有隐私协议，但是仍然存在一定风险。

2. **本地部署**：
   - **存储位置**：在本地部署模式下，知识库数据将被存储在您自己的服务器或数据中心内。
   - **安全性**：本地部署可以显著降低资料泄漏的风险，因为数据完全由您自己掌控。您可以根据自身需求实施严格的安全策略，如防火墙、入侵检测系统和数据加密等。

此外，向量化处理步骤也需要特别注意。向量化是将文本数据转换为向量表示的过程，这一步骤同样可能导致资料泄露。因此，为了确保数据的绝对安全，建议在本地部署环境中也部署本地向量模型。这样，所有数据处理都在您的内部网络中进行，进一步降低了泄露风险。

**Comment by fanfanyaya** [comment]
> 知识库的存储方式取决于部署模式，主要有两种：公有云（fastgpt在线版）和本地部署。
> 
> 1. **公有云部署**：
>    
>    * **存储位置**：在公有云部署模式下，您的知识库数据将被存储在FastGPT的云服务器上。
>    * **安全性**：有隐私协议，但是仍然存在一定风险。
> 2. **本地部署**：
>    
>    * **存储位置**：在本地部署模式下，知识库数据将被存储在您自己的服务器或数据中心内。
>    * **安全性**：本地部署可以显著降低资料泄漏的风险，因为数据完全由您自己掌控。您可以根据自身需求实施严格的安全策略，如防火墙、入侵检测系统和数据加密等。
> 
> 此外，向量化处理步骤也需要特别注意。向量化是将文本数据转换为向量表示的过程，这一步骤同样可能导致资料泄露。因此，为了确保数据的绝对安全，建议在本地部署环境中也部署本地向量模型。这样，所有数据处理都在您的内部网络中进行，进一步降低了泄露风险。

也就是可以直接在内网环境下进行本地部署是吗
