### ISSUE TITLE
移动端拍照识别响应慢

### ISSUE THREAD

**Issue by Purseccc** [labring/FastGPT#1549]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
目前遇到的问题是在移动端访问，用户手机拍照提问的时候响应特别慢，请问如何解决呢？

**复现步骤**

**预期结果**

**相关截图**

**Comment by Purseccc** [comment]
![image](https://github.com/labring/FastGPT/assets/77132374/c7ce32cc-5049-41a1-ba22-58a27205d289)
或许有人知道怎么在微信浏览器里先压缩一遍图像的方式呢？

**Comment by c121914yu** [comment]
加带宽

**Comment by Purseccc** [comment]
二开压缩了图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月26日(星期天) 晚上11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] 移动端拍照识别响应慢 (Issue #1549)





 
加带宽
