### ISSUE TITLE
知识库里的数据集可不可以开放类似于应用的 API 功能

### ISSUE THREAD

**Issue by TangSY** [labring/FastGPT#155]
希望可以支持通过API调用来管理数据集（添加、删除、查询）。同时支持通过API动态关联和解除每个应用对应的数据集

**Comment by bruceye777** [comment]
数据集API确实有较大帮助，因为业务的数据生成可能是动态的，比如和用户交互生成的历史对话，如果只能通过网页手工操作会比较繁琐，同步速度也得不到满足。

**Comment by bruceye777** [comment]
@TangSY  已经有数据集添加接口，大体上满足需求了。
https://kjqvjse66l.feishu.cn/docx/DmLedTWtUoNGX8xui9ocdUEjnNh#GZTedrBslobhQQxDDJjckcrEnJc

**Comment by c121914yu** [comment]
https://doc.fastgpt.in/docs/development/openapi/dataset/
