### ISSUE TITLE
私有化部署版本【系统插件】全都不生效

### ISSUE THREAD

**Issue by alvinwee07** [labring/FastGPT#1554]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [  ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
私有化部署版本系统插件中【文本加工】、【获取当前时间】、【判断器】、【自定义反馈】都不生效

**复现步骤**
流程编排
**预期结果**
生效
**相关截图**
<img width="1267" alt="image" src="https://github.com/labring/FastGPT/assets/149651121/4abddfd6-975e-409b-80dc-209536191258">
<img width="1049" alt="image" src="https://github.com/labring/FastGPT/assets/149651121/8d8283d4-d1c7-482e-abb0-130e3c6660f4">

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/28779ccc-a1d8-474f-bcc2-05aae9092317)
![image](https://github.com/labring/FastGPT/assets/40045458/fcfff2f7-f7cc-4747-8135-8611edfee363)
![image](https://github.com/labring/FastGPT/assets/40045458/f393645b-e18f-47f6-bbcd-33e3dff565c7)

**Comment by lijiajun1997** [comment]
版本更新到4.8试试

**Comment by alvinwee07** [comment]
> ![image](https://private-user-images.githubusercontent.com/40045458/332322851-28779ccc-a1d8-474f-bcc2-05aae9092317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODMyMzMsIm5iZiI6MTcxNjI4MjkzMywicGF0aCI6Ii80MDA0NTQ1OC8zMzIzMjI4NTEtMjg3NzljY2MtYTFkOC00NzRmLWJjYzItMDVhYWU5MDkyMzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzN2IyZDQxNjVmODAxN2MwZTIwODkxZTYyMTgyOTAyYmFmYWZlMjRmMWUwNTNhZDI0NDMyZWQ5M2U2NmI1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3zFFbLGTkHApvvuhe8vrvXpaQT4Y47DcSF_BwE-K9f8) ![image](https://private-user-images.githubusercontent.com/40045458/332322886-fcfff2f7-f7cc-4747-8135-8611edfee363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODMyMzMsIm5iZiI6MTcxNjI4MjkzMywicGF0aCI6Ii80MDA0NTQ1OC8zMzIzMjI4ODYtZmNmZmYyZjctZjdjYy00NzQ3LTgxMzUtODYxMWVkZmVlMzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZGE0NjQ3NmE1MjIxYjlmODI2Yzk2ZTQzNzQwZjViYzUxYTk3ZWUxYjUxYWZkMWNiMTQ0ODlkZWJhZGRmYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_lNWtV49xlaqbOfiWBBHVI-Woy66u3jRfXZiiaAOqc) ![image](https://private-user-images.githubusercontent.com/40045458/332322992-f393645b-e18f-47f6-bbcd-33e3dff565c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODMyMzMsIm5iZiI6MTcxNjI4MjkzMywicGF0aCI6Ii80MDA0NTQ1OC8zMzIzMjI5OTItZjM5MzY0NWItZTE4Zi00N2Y2LWJiY2QtMzNlM2RmZjU2NWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNzM1YTljOGFjMWZhODk5M2FiOTZhODNhMjZiNGE4ODJkMTJmNzdhYzA3YzExMTFmY2E4NDVhZDQ3ODQ3MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6t-8XhmftQJ272dq1P2hZlkWrf4w_eZ2RYX33rbxJik)

直接部署完就可用吗，有做过啥修改不？

**Comment by c121914yu** [comment]
感觉是你自定义挂载了某些东西？其他人都是有头像的

**Comment by alvinwee07** [comment]
> 感觉是你自定义挂载了某些东西？其他人都是有头像的

系统使用了二级目录所以头像没显示，二级目录对系统插件这里也会有影响？

**Comment by c121914yu** [comment]
> > 感觉是你自定义挂载了某些东西？其他人都是有头像的
> 
> 系统使用了二级目录所以头像没显示，二级目录对系统插件这里也会有影响？

那你可能也没读取到插件。可以看日志有没有读取到。

**Comment by alvinwee07** [comment]
> > > 感觉是你自定义挂载了某些东西？其他人都是有头像的
> > 
> > 
> > 系统使用了二级目录所以头像没显示，二级目录对系统插件这里也会有影响？
> 
> 那你可能也没读取到插件。可以看日志有没有读取到。

http request error。调系统插件就报http request error  二级目录导致的吗 还是说插件会用到oneapi？

![image](https://github.com/labring/FastGPT/assets/149651121/b9753a0b-d036-4533-8698-32d621184bf4)

**Comment by c121914yu** [comment]
> > > > 感觉是你自定义挂载了某些东西？其他人都是有头像的
> > > 
> > > 
> > > 系统使用了二级目录所以头像没显示，二级目录对系统插件这里也会有影响？
> > 
> > 那你可能也没读取到插件。可以看日志有没有读取到。
> 
> http request error。调系统插件就报http request error  二级目录导致的吗 还是说插件会用到oneapi？
> 
> ![image](https://github.com/labring/FastGPT/assets/149651121/b9753a0b-d036-4533-8698-32d621184bf4)
> 

会内网进行内部请求

**Comment by alvinwee07** [comment]
> > > > > 感觉是你自定义挂载了某些东西？其他人都是有头像的
> > > > 
> > > > 
> > > > 系统使用了二级目录所以头像没显示，二级目录对系统插件这里也会有影响？
> > > 
> > > 
> > > 那你可能也没读取到插件。可以看日志有没有读取到。
> > 
> > 
> > http request error。调系统插件就报http request error  二级目录导致的吗 还是说插件会用到oneapi？

> 
> 会内网进行内部请求

大佬明示，这个得修改或者排查哪里

**Comment by c121914yu** [comment]
> > > > > > 感觉是你自定义挂载了某些东西？其他人都是有头像的
> > > > > 
> > > > > 
> > > > > 系统使用了二级目录所以头像没显示，二级目录对系统插件这里也会有影响？
> > > > 
> > > > 
> > > > 那你可能也没读取到插件。可以看日志有没有读取到。
> > > 
> > > 
> > > http request error。调系统插件就报http request error  二级目录导致的吗 还是说插件会用到oneapi？
> 
> > 
> > 会内网进行内部请求
> 
> 大佬明示，这个得修改或者排查哪里

我也不懂，你得拉源码 debug 试试。。大概率是因为内部请求不到，比如本来请求 /api/plugin 地址，但是你加了二级目录，实际上需要请求:  /二级目录/api/plugin

**Comment by alvinwee07** [comment]
> > > > > > > 感觉是你自定义挂载了某些东西？其他人都是有头像的
> > > > > > 
> > > > > > 
> > > > > > 系统使用了二级目录所以头像没显示，二级目录对系统插件这里也会有影响？
> > > > > 
> > > > > 
> > > > > 那你可能也没读取到插件。可以看日志有没有读取到。
> > > > 
> > > > 
> > > > http request error。调系统插件就报http request error  二级目录导致的吗 还是说插件会用到oneapi？
> > 
> > 
> > > 会内网进行内部请求
> > 
> > 
> > 大佬明示，这个得修改或者排查哪里
> 
> 我也不懂，你得拉源码 debug 试试。。大概率是因为内部请求不到，比如本来请求 /api/plugin 地址，但是你加了二级目录，实际上需要请求: /二级目录/api/plugin

修改了路径，问题已解决，谢谢大佬

**Comment by GitChenfan** [comment]
单独调试时间插件是有正常输出的，但是放到选择工具后，就不被调用了
