### ISSUE TITLE
本地佈署後無法使用[创建一个文件集合]api

### ISSUE THREAD

**Issue by j205073** [labring/FastGPT#1559]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X] 我已确认目前没有类似 issue
- [X] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [X] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [X] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X ] 私有部署版本, 具体版本号: image: ghcr.io/labring/fastgpt:v4.8 # git

**问题描述, 日志截图**
請問我佈署好fastGPT後，想要透過"**创建一个文件集合**"但是始終回傳一個html。無法正常響應?
其他api都正常，唯獨這一支，能否請問如何排除呢?謝謝。
![image](https://github.com/labring/FastGPT/assets/17948436/1a42214e-7ca7-45b4-87ab-f3777cb65cfe)

**Comment by c121914yu** [comment]
4.8.1 feature. Please upgrade to version 4.8.1-alpha
