### ISSUE TITLE
多模态模型发文字可以正常使用，但是发图片就报错。

### ISSUE THREAD

**Issue by mrguo6221** [labring/FastGPT#1560]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
config设置：
![config设置](https://github.com/labring/FastGPT/assets/128030399/495d1303-fdff-48c0-9849-0af5e4181bc6)

fastgpt错误日志
![fastgpt错误提示](https://github.com/labring/FastGPT/assets/128030399/7c469a47-fb04-4f29-8baa-d9db318f884b)

oneapi渠道测试：
![fastgpt渠道测试](https://github.com/labring/FastGPT/assets/128030399/12809303-1f1d-4b8d-ab8e-b3bec697694c)

oneapi渠道设置：
![fastgpt渠道设置](https://github.com/labring/FastGPT/assets/128030399/96f603c4-8769-4351-81ff-19255e4f5fdf)

oneapi错误日志：
![oneapi错误提示](https://github.com/labring/FastGPT/assets/128030399/8b957c54-2f39-4665-9af3-04c2f429dedf)

fastgpt中发送文字正常聊天和发送图片错误提示：
![错误提示](https://github.com/labring/FastGPT/assets/128030399/8d4a870f-febc-437c-afed-22b241085adf)

**复现步骤**
1.用ollama运行llava-llama3:8b
2.在oneapi添加llava-llama3:8b的使用渠道并测试 成功
3.在fastgpt的config里面添加oneapi中的llava-llama3:8b渠道，并且重启fastgpt
4.在fastgpt新建任务，使用刚刚在config中 添加的 oneapi中的llava-llama3:8b渠道
5.可以使用此渠道进行 正常 的文本聊天
6.一旦发送图片报错如图所示，fastgpt oneapi 的日志如图所示

**预期结果**
正常使用通用的多模态模型不报错 
**相关截图**

**Comment by lijiajun1997** [comment]
llama3不是多模态吧  另外多模态的bug多半在oneapi那边

**Comment by mrguo6221** [comment]
> llama3不是多模态吧 另外多模态的bug多半在oneapi那边

这是一个用llama3结合起来 的多模态模型，使用 openwebui可以正常调用 ollama运行的这个模型，发图片问答啥的都正常。

**Comment by lijiajun1997** [comment]
> > llama3不是多模态吧 另外多模态的bug多半在oneapi那边
> 
> 这是一个用llama3结合起来 的多模态模型，使用 openwebui可以正常调用 ollama运行的这个模型，发图片问答啥的都正常。

你得看格式是否和openai兼容，可以去oneapi那边问问

**Comment by xiaoToby** [comment]
对话框中可以放入图片了？@lijiajun1997

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/a037ad0b-0b63-469f-b021-760de3ddb178)
你z这个图片怎么进去的？@mrguo6221

**Comment by lijiajun1997** [comment]
> ![image](https://private-user-images.githubusercontent.com/40045458/332673351-a037ad0b-0b63-469f-b021-760de3ddb178.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTkyODMsIm5iZiI6MTcxNjM1ODk4MywicGF0aCI6Ii80MDA0NTQ1OC8zMzI2NzMzNTEtYTAzN2FkMGItMGI2My00NjlmLWIwMjEtNzYwZGUzZGRiMTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA2MjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNmQwYWRlNjlhZjA4YjNhNmJiMTYxN2IwNDYyYmJiYTEyZDEzOGEzNTIwNWJlYWYzMjVjOWFkNzExNTUwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ab8dnKKQMpFu1x0qAI_rQspgbFymNQJPgHEAWIN-vJ8) 你z这个图片怎么进去的？@mrguo6221

支持多模态的模型，在config里打开vision就可以

**Comment by i-square** [comment]
你这个问题是因为ollama不支持openai的vision接口，参考 [Ollama OpenAI compatibility docs](https://github.com/ollama/ollama/blob/main/docs/openai.md)

而one-api添加的渠道是用openai的接口格式请求的，自然就报错了

**Comment by 13829386012** [comment]
> 你这个问题是因为ollama不支持openai的vision接口，参考 [Ollama OpenAI compatibility docs](https://github.com/ollama/ollama/blob/main/docs/openai.md)
> 
> 而one-api添加的渠道是用openai的接口格式请求的，自然就报错了

请问您我要上传图片使用多模态模型，需要做哪些设置，我非常需要

**Comment by 13829386012** [comment]
@mrguo6221 请问一下您解决这个问题了吗？

**Comment by 13829386012** [comment]
> > @mrguo6221 请问一下您解决这个问题了吗？
> 
> 解决不了，感觉ollama也是通过这种方式保留自己的生态圈。你用openwebui 可以正常使用ollama的多模态模型，但是他就不开放api通用接口的某些功能。

我看ollama api文件里是有支持图片的
![image](https://github.com/labring/FastGPT/assets/40138671/c3727ec2-143c-410c-8b41-28a45a3bff58)

**Comment by mrguo6221** [comment]
> > > @mrguo6221 请问一下您解决这个问题了吗？
> > 
> > 
> > 解决不了，感觉ollama也是通过这种方式保留自己的生态圈。你用openwebui 可以正常使用ollama的多模态模型，但是他就不开放api通用接口的某些功能。
> 
> 我看ollama api文件里是有支持图片的 ![image](https://private-user-images.githubusercontent.com/40138671/334303261-c3727ec2-143c-410c-8b41-28a45a3bff58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODYzOTYsIm5iZiI6MTcxNjg4NjA5NiwicGF0aCI6Ii80MDEzODY3MS8zMzQzMDMyNjEtYzM3MjdlYzItMTQzYy00MTBjLThiNDEtMjhhNDVhM2JmZjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA4NDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlODczYTdjZDk3YzA3MWM0MjIyZGQzMWRiNDA4N2UxYWNiYWI5NTQ1NGU0MDdiZmJjZWY5NDkwMzk2ZDNjZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H8R40IYNHmAWAVQmcUB1V4iBEZGjk43gDK7fUE0DYik)

没错 是有图片支持的，但是他这种支持不是openapi的通用格式。你明白区别么？就是如 oneapi等程序 都是直接拿openai的 api格式连接模型的，这些程序就不能调用ollama运行的模型的图片功能，挺麻烦的。
