### ISSUE TITLE
对话时输入框回车发送内容后，刷新导致全局参数丢失

### ISSUE THREAD

**Issue by colinyyj** [labring/FastGPT#1562]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号:  4.8.0

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/5284443/3f6e8b1c-a1a8-402d-b502-e57d488814f8)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
这个之前一个issue有提到（我也翻不到了）。分享链接如果不返回详情会存在这个问题
