### ISSUE TITLE
同时上传多个MD文件，报错

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1563]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/66725845/b3bf876b-5bd1-43f6-ba72-7c0173015431)

**复现步骤**
同时上传多个markdown文件

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/4ec60fe4-7158-4bef-bcc9-248a0162294c)
没遇到问题

**Comment by NanasakiX** [comment]
拖放.md文件时出现相同报错。文件上传则可以。
![image](https://github.com/labring/FastGPT/assets/47423266/32869f3a-e06f-4a5e-92d7-28445e150a72)
