### ISSUE TITLE
本地部署FastGPT，无法连接docker上的pg

### ISSUE THREAD

**Issue by EP-TigerAce** [labring/FastGPT#1564]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8

**问题描述, 日志截图**
首先在docker上按照文档成功部署了FastGPT，一切正常。后来根据领导要求，想要换成本地的，于是按照本地部署文档操作，启动后无法连接上pg
![image](https://github.com/labring/FastGPT/assets/116326628/4f965186-a814-43ff-b4ac-350191e9cb63)
有关pg的功能也就无法使用
![image](https://github.com/labring/FastGPT/assets/116326628/55ba9bb7-736e-408d-9882-90ebc43335c1)
但日志中，pg没有报错异常
![image](https://github.com/labring/FastGPT/assets/116326628/aaac5fe6-e704-4de1-b83d-ece41827b2a9)

**复现步骤**
按照文档进行部署，仅修改了config.json以使用本地模型
![image](https://github.com/labring/FastGPT/assets/116326628/324a17a6-7336-45c4-8fde-2ecd5cc30b34)

**预期结果**
部署在docker上时，一切都可以正常使用，部署到本地后就出问题了。
**相关截图**

**Comment by EP-TigerAce** [comment]
已尝试过将ip更换为host、localhost、127.0.0.1等，依然如此

**Comment by FinleyGe** [comment]
可能是本地 pg 部署的问题。从报错来看，可能是 pg 没有配置这个用户的访问，密钥加密方法等等。具体应该修改 pg_hba.conf 这个文件 请参考：http://www.postgres.cn/docs/9.4/auth-pg-hba-conf.html （中文）

**Comment by c121914yu** [comment]
数据库连接问题~ 自己先通过工具校验成功
