### ISSUE TITLE
问题分类后AI对话，用户问题不传入到AI对话中

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1565]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
如图所示：
![image](https://github.com/labring/FastGPT/assets/40045458/19b88687-d3ae-4613-8627-061c1125de29)
![image](https://github.com/labring/FastGPT/assets/40045458/f45bfa17-2e17-432b-b90a-7a0ee80bba69)
![image](https://github.com/labring/FastGPT/assets/40045458/d74190c2-06df-4b4d-97d5-e9ded8af9c0f)
![image](https://github.com/labring/FastGPT/assets/40045458/da2935ad-46ce-4f19-9c6b-94d48a5b90f9)
能够成功进行问题分类，可是有时能把用户问题传入到AI对话中，有时又不行

@nongmo677 @c121914yu @lijiajun1997
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
为什么历史记录是空的

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/82dbd60a-9db0-4f16-91f5-c21ff734cf74)
聊天记录设置为6

**Comment by c121914yu** [comment]
啥版本

**Comment by xiaoToby** [comment]
4.8 @c121914yu

**Comment by xiaoToby** [comment]
问题分类和AI对话都是用的qwen
同种类型的问题，一次能不能流转到AI对话中，一次不能流转到AI对话中
![image](https://github.com/labring/FastGPT/assets/40045458/5f675b14-10c7-4353-a786-bff713c8ea7e)
![image](https://github.com/labring/FastGPT/assets/40045458/b1b58f9b-74fc-4f02-a337-a50c54c5a815)
![image](https://github.com/labring/FastGPT/assets/40045458/56c4b8a3-9443-4d6e-b414-8bf9647cf997)

会不会是因为用的同个模型，两个模块运行的间隙时间太短

**Comment by xiaoToby** [comment]
每次在“问题分类”模块中，都能成功运行，且输出结果。
在“AI对话”中，如图配置的
![image](https://github.com/labring/FastGPT/assets/40045458/f174a265-3123-46e1-b13d-7fe8db7d9c38)
所以不管怎么样，用户问题都应该要传入到"AI对话"中去的呀。。。

现出现一个更奇怪的现象，同样的“用户问题”，一次可以传入到“AI对话”，一次不可以。。。
![image](https://github.com/labring/FastGPT/assets/40045458/2ae19cb6-e9f8-4418-aa73-46c5d96d0d31)
![image](https://github.com/labring/FastGPT/assets/40045458/200f857f-3d5f-4d58-a725-c14f65b4a8d8)

**Comment by xiaoToby** [comment]
每次在“问题分类”模块中，都能成功运行，且输出结果。
在“AI对话”中，如图配置的
![image](https://github.com/labring/FastGPT/assets/40045458/3df8eb16-74bd-4283-b298-d35f9ebfda24)

所以不管怎么样，用户问题都应该要传入到"AI对话"中去的呀。。。

现出现一个更奇怪的现象，同样的“用户问题”，一次可以传入到“AI对话”，一次不可以。。。
![image](https://github.com/labring/FastGPT/assets/40045458/384fb438-cea2-4d42-98b3-0f95c366f27c)
![image](https://github.com/labring/FastGPT/assets/40045458/db607b73-3dd5-41a4-8704-7cd9b8e882f6)

唯一的差别就是“运行时长”

**Comment by xiaoToby** [comment]
上个回复中猜想了会不会是因为“运行时长”

但又一次刷新了我的见解。。。
如图所述：
![image](https://github.com/labring/FastGPT/assets/40045458/d36ec573-91f9-45d5-bf85-1b58f91a9c2a)
![image](https://github.com/labring/FastGPT/assets/40045458/95e3cd0c-b76f-413e-b6fe-875dd912b0d6)

**Comment by xiaoToby** [comment]
@c121914yu @nongmo677 @lijiajun1997

**Comment by c121914yu** [comment]
> 同种类型的问题，一次能不能流转到AI对话中，一次不能流转到AI对话中

目前没遇到

**Comment by nongmo677** [comment]
问就是模型部署的问题

**Comment by xiaoToby** [comment]
> 问就是模型部署的问题

哈哈哈哈哈，真的吗？

**Comment by xiaoToby** [comment]
奇怪了，现在又都正常了。。。

**Comment by c121914yu** [comment]
> 奇怪了，现在又都正常了。。。

有版本更新操作么？

**Comment by xiaoToby** [comment]
没有版本更新，都是v4.8
