### ISSUE TITLE
支持多模态数据的向量数据库

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1567]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
LanceDB (https://github.com/lancedb/lancedb)
优点：
LanceDB采用无服务器架构,这意味着存储和计算被分成两个不同的单元。这种设计使其在RAG用例中非常快,确保快速获取和检索。此外,它还有一些显著的优势——开源、利用其基于Apache Arrow构建的用于高效的Lance柱状数据格式、持久存储能力,以及结合自己的磁盘近似最近邻搜索。所有这些因素共同使LanceDB成为访问和处理多模态数据的理想解决方案。
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
你可能误解了这个库，他和多模态没啥关系。
