### ISSUE TITLE
二维码失效了

### ISSUE THREAD

**Issue by zilong-ding** [labring/FastGPT#157]

**Comment by c121914yu** [comment]
加下右边那个个人号

**Comment by zilong-ding** [comment]
小助手的二维码也是有问题的

**Comment by c121914yu** [comment]
> 小助手的二维码也是有问题的

嗯哼，wx扫噢，，我这可以正常出来，o(╥﹏╥)o

**Comment by zilong-ding** [comment]
![image](https://github.com/labring/FastGPT/assets/71497754/a048f291-dc51-4daa-b2af-053a9b0c5dc0)
我就是微信扫的啊，右边这个识别不出来的

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/b9306982-1c54-4bf3-b4be-6697fad927f5)
你的都没加载完成呢~ 像卡了一样，加载了一半

**Comment by zilong-ding** [comment]
我的界面点开也是缺了下半部分，我们的居然不一样（笑哭）

**Comment by c121914yu** [comment]
神奇，， 邀请你了
