### ISSUE TITLE
执行pnpm i 报错

### ISSUE THREAD

**Issue by jingzl** [labring/FastGPT#1572]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.1-a，20240522 下载的master分支版本

**问题描述, 日志截图**
下载完代码，执行 pnpm i，报错：

. postinstall$ sh ./scripts/postinstall.sh
│  ERR_PNPM_NO_SCRIPT  Missing script: gen:theme-typings
│ Command "gen:theme-typings
│ " not found. Did you mean "pnpm run gen:theme-typings"?

查看 package.json 和 postinstall.sh 文件，里面已包含了 pnpm run gen:theme-typings，感觉这个问题好诡异。

系统：ubuntu22.04  64位
node：18.16.1
pnpm：9.1.1

**复现步骤**
可直接复现。

**预期结果**
能完成依赖安装。

**相关截图**

**Comment by jingzl** [comment]
这个问题，在4.8.0 和 4.8.1-alpha 中都存在，没有人碰到吗？

**Comment by ckbabby** [comment]
我也遇到你这个问题，我用编辑器另存一下这个文件 ./scripts/postinstall.sh 就过了

**Comment by jingzl** [comment]
@ckbabby 你用啥编辑器另存？我用 vi 测试，没有解决。

在 package.json 中 scripts 里包含：
"gen:theme-typings": "chakra-cli tokens packages/web/styles/theme.ts --out node_modules/.pnpm/node_modules/@chakra-ui/styled-system/dist/theming.types.d.ts",
    "postinstall": "sh ./scripts/postinstall.sh",

在 postinstall.sh 中，有语句 pnpm run gen:theme-typings 

似乎该写的都写了。但问题依旧

**Comment by c121914yu** [comment]
暂时没遇到。不过nextjs14，要求最低node是18.17，可能有影响。
![image](https://github.com/labring/FastGPT/assets/50446880/3aa4f935-bf55-40ba-bec2-aae029dd767f)

**Comment by jingzl** [comment]
@c121914yu @ckbabby 
今天又拉取最新版本，同时也更新了node 和 pnpm，修改script目录权限后，直接 pnpm i，很干脆的报错，无语了。
![image](https://github.com/labring/FastGPT/assets/2803602/48655a1b-4272-4e17-96f3-8b9795ae731f)

完全没有头绪了。。。。
难道要重装系统？

**Comment by c121914yu** [comment]
> @c121914yu @ckbabby 今天又拉取最新版本，同时也更新了node 和 pnpm，修改script目录权限后，直接 pnpm i，很干脆的报错，无语了。 ![image](https://private-user-images.githubusercontent.com/2803602/335091491-48655a1b-4272-4e17-96f3-8b9795ae731f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTU5MDAsIm5iZiI6MTcxNzA1NTYwMCwicGF0aCI6Ii8yODAzNjAyLzMzNTA5MTQ5MS00ODY1NWExYi00MjcyLTRlMTctOTZmMy04Yjk3OTVhZTczMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDc1MzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI4YzEzMDNmY2E1ZmM3Y2RiOTI3NjgwYWE4YTA5NGE0YzA2NDRmNGQ1ZmUzNDNiMzEzZjVjYjY0ZTU1MDk3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lxXIRISw2_Xik5VmG0UqGxAIpjQYP6UO3dB96kRnyNM)
> 
> 完全没有头绪了。。。。 难道要重装系统？

确实没啥头绪。建议把pnpm装8.x版本试试

**Comment by jingzl** [comment]
@c121914yu 
参考 https://doc.fastgpt.in/docs/development/intro/ 的说明，清理了缓存及原有版本
node 18.17.0，  pnpm 8.6.0
执行pnpm i 后，跑的多了一些，但最后仍然报错：
![image](https://github.com/labring/FastGPT/assets/2803602/1668986d-f5da-4d85-bfd5-c1ce0c520dd1)
并且在 projects/app 目录下，生成了一个乱字符的tmp文件夹：'tmp'$'\r'

**Comment by jingzl** [comment]
对于这个 postinstall 脚本文件，我根据提示直接 pnpm  run  gen：theme-typings 安装完毕，然后把脚本部分注释掉了。
然后再执行这个 pnpm i，可以执行完。
继续打包试试。
这个地方有点奇怪，这个依赖包，为啥不直接放在 package.json中处理？

**Comment by c121914yu** [comment]
> @c121914yu 参考 https://doc.fastgpt.in/docs/development/intro/ 的说明，清理了缓存及原有版本 node 18.17.0， pnpm 8.6.0 执行pnpm i 后，跑的多了一些，但最后仍然报错： ![55fac3ec1c057b95a9a371773786c42](https://private-user-images.githubusercontent.com/2803602/335123182-2f4c3625-503f-4a18-83fd-cf88c1e0a748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjMzNjksIm5iZiI6MTcxNzA2MzA2OSwicGF0aCI6Ii8yODAzNjAyLzMzNTEyMzE4Mi0yZjRjMzYyNS01MDNmLTRhMTgtODNmZC1jZjg4YzFlMGE3NDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDk1NzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBmNTZhMjI1MDcxYWVmZjhlMmNiZjk3ZWJkYTk4OWU4ZGFhMzdmMGYzZDMwNmY3ZWIyOTY3YzVlNDBiZTRmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mAU8ku3KFTqAiXNTRTZVVCvtAFzw1NHf_6vS1lEX_y8)
> 
> 并且在 projects/app 目录下，生成了一个乱字符的tmp文件夹：'tmp'$'\r'

那看来就是编码有问题，导致脚本无法执行。
这是一个pnpm i 后的脚本，本来有更多东西的，不过删掉了，只剩 pnpm run gen：theme-typings 用到。

**Comment by jingzl** [comment]
谢谢
