### ISSUE TITLE
api每次发送对话请求，全局变量重置为空

### ISSUE THREAD

**Issue by bookwoods** [labring/FastGPT#1573]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我在高级编排中添加了一个全局变量A，并在流程开始时通过判断A是否为空进入两个分支流程。我在用api调用这个应用时，发现每次发送对话请求后全局变量A都会重置为空，除非发送对话请求时，在变量中直接设置全局变量A的值，不然流程始终走向第一个分支。
chatid设置为“abcd”不变
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
请完善一下相关描述。变量 a 的 key，变量 a 如何取值， 编排是什么。

**Comment by bookwoods** [comment]
高级编排如下图，实现功能是对输入文本进行总结描述，并将结果赋值给全局变量description，如果description不为空则直接输出description，但是在chatid不变的前提下，每次输入时都会判断全局变量description为空，然后给description赋新的值，全局变量无法在对话中继承
![image](https://github.com/labring/FastGPT/assets/106570410/dbc80c22-7f3a-4457-bbc2-10c5848b902f)
python调用api的对话
![image](https://github.com/labring/FastGPT/assets/106570410/6c381be7-b41b-4e6a-8b41-596859a1034c)
![image](https://github.com/labring/FastGPT/assets/106570410/2a39ce6e-c6d5-4eb5-813f-c2f1794b3dd5)

**Comment by bookwoods** [comment]
> 请完善一下相关描述。变量 a 的 key，变量 a 如何取值， 编排是什么。

高级编排如下图，实现功能是对输入文本进行总结描述，并将结果赋值给全局变量description，如果description不为空则直接输出description，但是在chatid不变的前提下，每次输入时都会判断全局变量description为空，然后给description赋新的值，全局变量无法在对话中继承
![image](https://github.com/labring/FastGPT/assets/106570410/dbfe2c30-1dfc-4c65-b14f-34d4eb2cb9f6)
python调用api的对话
![image](https://github.com/labring/FastGPT/assets/106570410/347c3c1c-9615-4f88-be69-b04fe8547418)
![image](https://github.com/labring/FastGPT/assets/106570410/a1dd3301-f323-4d62-8aba-41e208e8f2a3)

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/2544 fix
