### ISSUE TITLE
M1 MAC部分容器启动不了，求大佬帮忙，新手

### ISSUE THREAD

**Issue by fanfanyaya** [labring/FastGPT#1577]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
<img width="987" alt="截屏2024-05-23 13 51 10" src="https://github.com/labring/FastGPT/assets/50243914/6e7f9f91-968f-4656-a5ec-db30549a3536">
<img width="739" alt="截屏2024-05-23 13 50 55" src="https://github.com/labring/FastGPT/assets/50243914/210aa220-aa2f-49af-8cc3-fc814368f2e3">
<img width="1009" alt="截屏2024-05-23 13 51 31" src="https://github.com/labring/FastGPT/assets/50243914/2baa0639-275e-47d1-9154-951de319cb9b">

**Comment by FinleyGe** [comment]
用特权模式，启动命令后面加上 --privileged 参数。
