### ISSUE TITLE
关于rerank在oneapi部署，然后fastgpt调oneapi的问题

### ISSUE THREAD

**Issue by peanutpaste** [labring/FastGPT#1578]
我用docker启动了bge-rerank-v2-m3)，然后向配置embedding模型一样，在oneapi中配置，但是rerank模型一直返回404结果。
请问oneapi中不支持配置rerank模型吗还是我的流程有问题？望解答
![image](https://github.com/labring/FastGPT/assets/62008312/769af77a-7848-497e-a44a-6db0e0d0206e)
![image](https://github.com/labring/FastGPT/assets/62008312/376d7973-40fe-4473-b8c0-3bcf69e1d3b6)

**Comment by c121914yu** [comment]
rerank不能介入oneapi~
