### ISSUE TITLE
发起对话请求后，AI模型正在回复过程中，点击新对话，正在执行回复的过程会被中断

### ISSUE THREAD

**Issue by z13260641200** [labring/FastGPT#1579]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8

**问题描述, 日志截图**

**复现步骤**
在一轮对话过程中，AI正在回答问题，用户点击新对话，刚刚AI回答会被中断
**预期结果**
新的对话不影响原来的对话过程
**相关截图**

**Comment by z13260641200** [comment]
![image](https://github.com/labring/FastGPT/assets/88540729/1218ee34-3214-4ea0-9e05-93c627581695)

**Comment by c121914yu** [comment]
这不是正常的么

**Comment by z13260641200** [comment]
新的对话，正常不应该是不影响原来的吗

**Comment by c121914yu** [comment]
> 新的对话，正常不应该是不影响原来的吗

怎么可能呢，都跳出对话了，肯定终止了
