### ISSUE TITLE
应用导入配置时可以选择不覆盖原配置，而是增加一段配置

### ISSUE THREAD

**Issue by KanoSang** [labring/FastGPT#1581]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
希望应用导入高级编排配置时可以选择不覆盖原配置，而是增加一段配置到原配置上
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
不合理。导入就是类似template，而且绝对会有节点冲突

**Comment by KanoSang** [comment]
> 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？

我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连

**Comment by KanoSang** [comment]
> > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > 
> > 
> > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> 
> 有点奇怪，只复制节点不复制边？

是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了

**Comment by c121914yu** [comment]
> > > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > > 
> > > 
> > > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> > 
> > 有点奇怪，只复制节点不复制边？
> 
> 是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了

你可以直接试一试CTRLC+CTRLV粘贴过去

**Comment by KanoSang** [comment]
> > > > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > > > 
> > > > 
> > > > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> > > 
> > > 
> > > 有点奇怪，只复制节点不复制边？
> > 
> > 
> > 是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了
> 
> 你可以直接试一试CTRLC+CTRLV粘贴过去

试了下不行啊 没这个功能吧

**Comment by c121914yu** [comment]
> > > > > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > > > > 
> > > > > 
> > > > > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> > > > 
> > > > 
> > > > 有点奇怪，只复制节点不复制边？
> > > 
> > > 
> > > 是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了
> > 
> > 你可以直接试一试CTRLC+CTRLV粘贴过去
> 
> 试了下不行啊 没这个功能吧

有的，选中节点可以直接复制。

**Comment by KanoSang** [comment]
> > > > > > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > > > > > 
> > > > > > 
> > > > > > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> > > > > 
> > > > > 
> > > > > 有点奇怪，只复制节点不复制边？
> > > > 
> > > > 
> > > > 是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了
> > > 
> > > 
> > > 你可以直接试一试CTRLC+CTRLV粘贴过去
> > 
> > 
> > 试了下不行啊 没这个功能吧
> 
> 有的，选中节点可以直接复制。

对的，选中模块是有个复制选项，但是我想复制到别的应用里，好像只能导出导入配置才行了

**Comment by c121914yu** [comment]
> > > > > > > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > > > > > > 
> > > > > > > 
> > > > > > > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> > > > > > 
> > > > > > 
> > > > > > 有点奇怪，只复制节点不复制边？
> > > > > 
> > > > > 
> > > > > 是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了
> > > > 
> > > > 
> > > > 你可以直接试一试CTRLC+CTRLV粘贴过去
> > > 
> > > 
> > > 试了下不行啊 没这个功能吧
> > 
> > 有的，选中节点可以直接复制。
> 
> 对的，选中模块是有个复制选项，但是我想复制到别的应用里，好像只能导出导入配置才行了

选中模块按 ctrl c 哇😅

**Comment by KanoSang** [comment]
> > > > > > > > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> > > > > > > 
> > > > > > > 
> > > > > > > 有点奇怪，只复制节点不复制边？
> > > > > > 
> > > > > > 
> > > > > > 是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了
> > > > > 
> > > > > 
> > > > > 你可以直接试一试CTRLC+CTRLV粘贴过去
> > > > 
> > > > 
> > > > 试了下不行啊 没这个功能吧
> > > 
> > > 
> > > 有的，选中节点可以直接复制。
> > 
> > 
> > 对的，选中模块是有个复制选项，但是我想复制到别的应用里，好像只能导出导入配置才行了
> 
> 选中模块按 ctrl c 哇😅

谢谢，我应该知道问题在哪了，我试的是我本地的，刚刚也确实CtrlC复制试了显示复制成功，但是V粘贴没有用，然后我去官网试了下是可以的，请问可能是我没加证书的原因吗

**Comment by c121914yu** [comment]
> > > > > > > > > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 有点奇怪，只复制节点不复制边？
> > > > > > > 
> > > > > > > 
> > > > > > > 是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了
> > > > > > 
> > > > > > 
> > > > > > 你可以直接试一试CTRLC+CTRLV粘贴过去
> > > > > 
> > > > > 
> > > > > 试了下不行啊 没这个功能吧
> > > > 
> > > > 
> > > > 有的，选中节点可以直接复制。
> > > 
> > > 
> > > 对的，选中模块是有个复制选项，但是我想复制到别的应用里，好像只能导出导入配置才行了
> > 
> > 选中模块按 ctrl c 哇😅
> 
> 谢谢，我应该知道问题在哪了，我试的是我本地的，刚刚也确实CtrlC复制试了显示复制成功，但是V粘贴没有用，然后我去官网试了下是可以的，请问可能是我没加证书的原因吗

噢噢，那确实。没 ssl 证书不能触发复制（提示不对）

**Comment by KanoSang** [comment]
> > > > > > > > > > > 不合理。导入就是类似template，而且绝对会有节点冲突，最简单，2个AI对话节点，你配置加到哪里？
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我的意思就是配置先临时加到新的高级编排里面，然后再自己连一下就好了，有点像高级编排里的模块复制出来这样，然后再自己连一连
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 有点奇怪，只复制节点不复制边？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 是这样的，比如我有些应用有api调用之类的模块，我别的应用还需要这个模块，那我就把配置新增过去，然后删改一下就好，不用自己再写一个api模块了
> > > > > > > 
> > > > > > > 
> > > > > > > 你可以直接试一试CTRLC+CTRLV粘贴过去
> > > > > > 
> > > > > > 
> > > > > > 试了下不行啊 没这个功能吧
> > > > > 
> > > > > 
> > > > > 有的，选中节点可以直接复制。
> > > > 
> > > > 
> > > > 对的，选中模块是有个复制选项，但是我想复制到别的应用里，好像只能导出导入配置才行了
> > > 
> > > 
> > > 选中模块按 ctrl c 哇😅
> > 
> > 
> > 谢谢，我应该知道问题在哪了，我试的是我本地的，刚刚也确实CtrlC复制试了显示复制成功，但是V粘贴没有用，然后我去官网试了下是可以的，请问可能是我没加证书的原因吗
> 
> 噢噢，那确实。没 ssl 证书不能触发复制（提示不对）

嗯嗯，回头我加一个试试，谢谢
