### ISSUE TITLE
主动终止会话时，全局变量仍然会被清空

### ISSUE THREAD

**Issue by z13260641200** [labring/FastGPT#1582]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8.1

**问题描述, 日志截图**

**复现步骤**

进行AI对话，点击终止，全局变量会被清空，需要重新设置

**预期结果**
不会被清空

**相关截图**

**Comment by c121914yu** [comment]
@newfish-cmyk 看来这块得改个方案了，不能直接从流里取，得新增一个request去获取最新的内容。

**Comment by z13260641200** [comment]
更新为该版本后，无全局变量选择提示框

**Comment by c121914yu** [comment]
> 更新为该版本后，无全局变量选择提示框

没看懂

**Comment by z13260641200** [comment]
原来的：
<img width="690" alt="企业微信截图_17167803198833" src="https://github.com/labring/FastGPT/assets/88540729/735508b0-33a3-4db7-872f-a3c0b30d1383">
更新后的：
![Uploading 企业微信截图_17167803333363.png…]()

**Comment by z13260641200** [comment]
<img width="718" alt="企业微信截图_17167803333363" src="https://github.com/labring/FastGPT/assets/88540729/3eb8eee9-c2b7-42df-9db7-5d0f39cfbce2">

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/2e350b65-ac5b-42ed-b66d-5a1b27c1db40)
我这都有噢
