### ISSUE TITLE
nginx代理https之后，使用语音输入报错：unexpected field

### ISSUE THREAD

**Issue by wufxgtihub123** [labring/FastGPT#1585]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ √] 我已确认目前没有类似 issue
- [ √] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [√ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√ ] 私有部署版本, 具体版本号: 
v4.6.7
**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/74227869/bb9d5549-1111-41c8-950d-ae3934aea701)
![image](https://github.com/labring/FastGPT/assets/74227869/8e4ddc49-86f4-458b-ab4d-a58edcbb1671)
![image](https://github.com/labring/FastGPT/assets/74227869/cd6dc36c-9d3c-4411-8369-b4bfb9f865d9)

**复现步骤**

**预期结果**
希望语音输入能正常访问
**相关截图**

**Comment by c121914yu** [comment]
没遇到过，可以看看是不是有字段没转发，语音转需要传文件。

**Comment by sdytzjp** [comment]
请问下使用nginx代理的目的是什么
