### ISSUE TITLE
用nodejs的http-proxy-middleware做转发服务代理后，报这个错误

### ISSUE THREAD

**Issue by shijianzhong** [labring/FastGPT#1586]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
unmarshal_response_body_failed invalid character 'd' looking for beginning of value (request id: 2024052405395798676421232244012)
**复现步骤**
我们公司的openai是封装过的，所以我需要自己单独写个nodejs服务把我们公司的openai的接口朝标准化掰过来，但是遇到了这个问题
**预期结果**

**相关截图**
![Uploading image.png…]()

**Comment by shijianzhong** [comment]
![20240524134914](https://github.com/labring/FastGPT/assets/15205387/5c611156-27a2-46a8-9563-646db127cd8a)

**Comment by shijianzhong** [comment]
![88888](https://github.com/labring/FastGPT/assets/15205387/9cff6fb8-242b-44cb-b4e8-20ce84447366)
![9999999](https://github.com/labring/FastGPT/assets/15205387/8e160270-a34f-40a4-b74a-0027644dfd11)

**Comment by c121914yu** [comment]
这是你的接口没完全一致把？你能再oneapi或者nextweb之类测试过么

**Comment by shijianzhong** [comment]
> 这是你的接口没完全一致把？你能再oneapi或者nextweb之类测试过么

我一般的问答是可以的，没有复杂联路的可以，就是这种有好几个节点的有问题，不知道接口不完全一致怎么去比对呢

**Comment by c121914yu** [comment]
curl 测试，然后结果跟 GPT 文档比对
