### ISSUE TITLE
不是说知识库导入开放商业版的站点同步等功能吗？

### ISSUE THREAD

**Issue by boleyn** [labring/FastGPT#1587]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
如题，找不到该功能，修改代码放开后，还是不能用
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/24293664/e5e21404-fe1d-4cf9-be55-7fc8a6d259e1)

**Comment by c121914yu** [comment]
哪里说的

**Comment by boleyn** [comment]
新增 - 开放文件导入知识库接口到开源版: [点击查看文档](https://doc.fastai.site/docs/development/openapi/dataset/#%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6%E9%9B%86%E5%90%88)
新增 - 外部文件源知识库: [点击查看文档](https://doc.fastai.site/docs/course/externalfile/)

**Comment by boleyn** [comment]
这个两个不是这个意思吗

**Comment by c121914yu** [comment]
> 这个两个不是这个意思吗
> 

哪里写着站点同步了
