### ISSUE TITLE
使用docker pull fastgpt重新更新后，数据丢失，并且无法使导入就得配置

### ISSUE THREAD

**Issue by Lands-1203** [labring/FastGPT#1588]
![image](https://github.com/labring/FastGPT/assets/61341868/b692f36a-9cf5-4021-9b9b-ce8249e13a79)
![image](https://github.com/labring/FastGPT/assets/61341868/2449c5fd-863c-46fa-91f7-f240f563c629)

**Comment by Essence9999** [comment]
大佬，你数据咋恢复的？
