### ISSUE TITLE
好像Sealos得版本比docker的版本要新好多docker啥时候能和Sealos一起更新啊

### ISSUE THREAD

**Issue by mpuazxc2** [labring/FastGPT#159]
好像Sealos得版本比docker的版本要新好多docker啥时候能和Sealos一起更新啊

**Comment by c121914yu** [comment]
昨天已经同步了，都是latest

**Comment by mpuazxc2** [comment]
https://github.com/labring/FastGPT/tree/main/files/deploy/fastgpt
我根据这个改docker-compose.yml文件
通过run.sh部署的
好像还是老版本啊，依然需要发邮件注册啥的，新版直接root登录就行
难道存在缓存咩

**Comment by mpuazxc2** [comment]
刚刚又部署了一遍，还是老版本
主要 想用高级编排功能

**Comment by c121914yu** [comment]
看文档，，别看文件

**Comment by mpuazxc2** [comment]
终于可以了，谢谢

**Comment by c121914yu** [comment]
好的

**Comment by land007** [comment]
按照这个打包成docker镜像 RUN pnpm --filter=app run build  的时候报错了
执行命令
docker build --build-arg name=app -t fastgpt:latest .
错误如下，这是怎么回事啊。
 [+] Building 717.8s (27/32)                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                  0.0s
 => => transferring dockerfile: 37B                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                     0.0s
 => => transferring context: 34B                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/node:current-alpine                                                                                                3.1s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                           0.0s
 => [internal] load build context                                                                                                                                     8.4s
 => => transferring context: 299.53MB                                                                                                                                 8.3s
 => [builder  1/10] FROM docker.io/library/node:current-alpine@sha256:37750e51d61bef92165b2e29a77da4277ba0777258446b7a9c99511f119db096                                0.0s
 => CACHED [builder  2/10] WORKDIR /app                                                                                                                               0.0s
 => CACHED [runner  3/11] RUN addgroup --system --gid 1001 nodejs                                                                                                     0.0s
 => CACHED [runner  4/11] RUN adduser --system --uid 1001 nextjs                                                                                                      0.0s
 => CACHED [runner  5/11] RUN sed -i 's/https/http/' /etc/apk/repositories                                                                                            0.0s
 => CACHED [runner  6/11] RUN apk add curl   && apk add ca-certificates   && update-ca-certificates                                                                   0.0s
 => CACHED [deps 2/9] RUN apk add --no-cache libc6-compat && npm install -g pnpm                                                                                      0.0s
 => CACHED [deps 3/9] WORKDIR /app                                                                                                                                    0.0s
 => CACHED [deps 4/9] COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./                                                                                         0.0s
 => [deps 5/9] COPY ./packages ./packages                                                                                                                             0.1s
 => [deps 6/9] COPY ./projects/app/package.json ./projects/app/package.json                                                                                           0.0s
 => [deps 7/9] COPY ./projects/app/pnpm-lock.yaml ./projects/app/pnpm-lock.yaml                                                                                       0.0s
 => [deps 8/9] RUN   [ -f pnpm-lock.yaml ] && pnpm install ||   (echo "Lockfile not found." && exit 1)                                                              546.4s
 => [deps 9/9] RUN pnpm prune                                                                                                                                         1.7s
 => [builder  3/10] COPY --from=deps /app/node_modules ./node_modules                                                                                                 8.9s 
 => [builder  4/10] COPY --from=deps /app/packages ./packages                                                                                                         0.0s 
 => [builder  5/10] COPY ./projects/app ./projects/app                                                                                                                0.9s 
 => [builder  6/10] COPY --from=deps /app/projects/app/node_modules ./projects/app/node_modules                                                                       0.0s 
 => [builder  7/10] COPY pnpm-lock.yaml pnpm-workspace.yaml ./                                                                                                        0.0s 
 => [builder  8/10] COPY ./packages ./packages                                                                                                                        0.0s
 => [builder  9/10] RUN npm install -g pnpm                                                                                                                          74.8s
 => ERROR [builder 10/10] RUN pnpm --filter=app run build                                                                                                            65.1s
------                                                                                                                                                                     
 > [builder 10/10] RUN pnpm --filter=app run build:                                                                                                                        
#27 0.665 No projects matched the filters "/app" in "/app"                                                                                                                 
#27 0.671                                                                                                                                                                  
#27 0.671 > app@4.4.6 build /app/projects/app                                                                                                                              
#27 0.671 > next build                                                                                                                                                     
#27 0.671 
#27 1.156    Linting and checking validity of types...
#27 6.493 
#27 6.493 ./src/components/ChatBox/index.tsx
#27 6.493 202:28  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/hooks/usePagination.tsx
#27 6.493 176:6  Warning: React Hook useEffect has missing dependencies: 'defaultRequest' and 'mutate'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/_app.tsx
#27 6.493 87:6  Warning: React Hook useEffect has missing dependencies: 'i18n' and 'setLastRoute'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/_error.tsx
#27 6.493 26:6  Warning: React Hook useEffect has missing dependencies: 'lastRoute' and 'router'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/app/detail/components/AdEdit/index.tsx
#27 6.493 256:6  Warning: React Hook useEffect has a missing dependency: 'initData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/app/detail/components/BasicEdit/index.tsx
#27 6.493 130:6  Warning: React Hook useMemo has an unnecessary dependency: 'refresh'. Either exclude it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 136:6  Warning: React Hook useMemo has an unnecessary dependency: 'refresh'. Either exclude it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/app/detail/components/Charts/TotalUsage.tsx
#27 6.493 180:6  Warning: React Hook useEffect has a missing dependency: 'option'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/app/detail/index.tsx
#27 6.493 77:6  Warning: React Hook useEffect has a missing dependency: 'clearAppModules'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/components/Footer.tsx
#27 6.493 73:5  Warning: React Hook useMemo has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/index.tsx
#27 6.493 25:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/kb/detail/components/DataCard.tsx
#27 6.493 64:24  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/kb/detail/components/FileCard.tsx
#27 6.493 71:27  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/login/index.tsx
#27 6.493 58:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 ./src/pages/login/provider.tsx
#27 6.493 93:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#27 6.493 
#27 6.493 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
#27 19.87    Creating an optimized production build...
#27 65.08 /app/projects/app:
#27 65.08  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  app@4.4.6 build: `next build`
#27 65.08 Command failed with signal "SIGKILL"
------
executor failed running [/bin/sh -c pnpm --filter=$name run build]: exit code: 1

**Comment by suwubee** [comment]
> 按照这个打包成docker镜像 RUN pnpm --filter=app run build 的时候报错了 执行命令 docker build --build-arg name=app -t fastgpt:latest . 错误如下，这是怎么回事啊。
> 
> ```
>  [+] Building 717.8s (27/32)                                                                                                                                                
>  => [internal] load build definition from Dockerfile                                                                                                                  0.0s
>  => => transferring dockerfile: 37B                                                                                                                                   0.0s
>  => [internal] load .dockerignore                                                                                                                                     0.0s
>  => => transferring context: 34B                                                                                                                                      0.0s
>  => [internal] load metadata for docker.io/library/node:current-alpine                                                                                                3.1s
>  => [auth] library/node:pull token for registry-1.docker.io                                                                                                           0.0s
>  => [internal] load build context                                                                                                                                     8.4s
>  => => transferring context: 299.53MB                                                                                                                                 8.3s
>  => [builder  1/10] FROM docker.io/library/node:current-alpine@sha256:37750e51d61bef92165b2e29a77da4277ba0777258446b7a9c99511f119db096                                0.0s
>  => CACHED [builder  2/10] WORKDIR /app                                                                                                                               0.0s
>  => CACHED [runner  3/11] RUN addgroup --system --gid 1001 nodejs                                                                                                     0.0s
>  => CACHED [runner  4/11] RUN adduser --system --uid 1001 nextjs                                                                                                      0.0s
>  => CACHED [runner  5/11] RUN sed -i 's/https/http/' /etc/apk/repositories                                                                                            0.0s
>  => CACHED [runner  6/11] RUN apk add curl   && apk add ca-certificates   && update-ca-certificates                                                                   0.0s
>  => CACHED [deps 2/9] RUN apk add --no-cache libc6-compat && npm install -g pnpm                                                                                      0.0s
>  => CACHED [deps 3/9] WORKDIR /app                                                                                                                                    0.0s
>  => CACHED [deps 4/9] COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./                                                                                         0.0s
>  => [deps 5/9] COPY ./packages ./packages                                                                                                                             0.1s
>  => [deps 6/9] COPY ./projects/app/package.json ./projects/app/package.json                                                                                           0.0s
>  => [deps 7/9] COPY ./projects/app/pnpm-lock.yaml ./projects/app/pnpm-lock.yaml                                                                                       0.0s
>  => [deps 8/9] RUN   [ -f pnpm-lock.yaml ] && pnpm install ||   (echo "Lockfile not found." && exit 1)                                                              546.4s
>  => [deps 9/9] RUN pnpm prune                                                                                                                                         1.7s
>  => [builder  3/10] COPY --from=deps /app/node_modules ./node_modules                                                                                                 8.9s 
>  => [builder  4/10] COPY --from=deps /app/packages ./packages                                                                                                         0.0s 
>  => [builder  5/10] COPY ./projects/app ./projects/app                                                                                                                0.9s 
>  => [builder  6/10] COPY --from=deps /app/projects/app/node_modules ./projects/app/node_modules                                                                       0.0s 
>  => [builder  7/10] COPY pnpm-lock.yaml pnpm-workspace.yaml ./                                                                                                        0.0s 
>  => [builder  8/10] COPY ./packages ./packages                                                                                                                        0.0s
>  => [builder  9/10] RUN npm install -g pnpm                                                                                                                          74.8s
>  => ERROR [builder 10/10] RUN pnpm --filter=app run build                                                                                                            65.1s
> ------                                                                                                                                                                     
>  > [builder 10/10] RUN pnpm --filter=app run build:                                                                                                                        
> #27 0.665 No projects matched the filters "/app" in "/app"                                                                                                                 
> #27 0.671                                                                                                                                                                  
> #27 0.671 > app@4.4.6 build /app/projects/app                                                                                                                              
> #27 0.671 > next build                                                                                                                                                     
> #27 0.671 
> #27 1.156    Linting and checking validity of types...
> #27 6.493 
> #27 6.493 ./src/components/ChatBox/index.tsx
> #27 6.493 202:28  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/hooks/usePagination.tsx
> #27 6.493 176:6  Warning: React Hook useEffect has missing dependencies: 'defaultRequest' and 'mutate'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/_app.tsx
> #27 6.493 87:6  Warning: React Hook useEffect has missing dependencies: 'i18n' and 'setLastRoute'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/_error.tsx
> #27 6.493 26:6  Warning: React Hook useEffect has missing dependencies: 'lastRoute' and 'router'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/app/detail/components/AdEdit/index.tsx
> #27 6.493 256:6  Warning: React Hook useEffect has a missing dependency: 'initData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/app/detail/components/BasicEdit/index.tsx
> #27 6.493 130:6  Warning: React Hook useMemo has an unnecessary dependency: 'refresh'. Either exclude it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 136:6  Warning: React Hook useMemo has an unnecessary dependency: 'refresh'. Either exclude it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/app/detail/components/Charts/TotalUsage.tsx
> #27 6.493 180:6  Warning: React Hook useEffect has a missing dependency: 'option'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/app/detail/index.tsx
> #27 6.493 77:6  Warning: React Hook useEffect has a missing dependency: 'clearAppModules'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/components/Footer.tsx
> #27 6.493 73:5  Warning: React Hook useMemo has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/index.tsx
> #27 6.493 25:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/kb/detail/components/DataCard.tsx
> #27 6.493 64:24  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/kb/detail/components/FileCard.tsx
> #27 6.493 71:27  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/login/index.tsx
> #27 6.493 58:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 ./src/pages/login/provider.tsx
> #27 6.493 93:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> #27 6.493 
> #27 6.493 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
> #27 19.87    Creating an optimized production build...
> #27 65.08 /app/projects/app:
> #27 65.08  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  app@4.4.6 build: `next build`
> #27 65.08 Command failed with signal "SIGKILL"
> ------
> executor failed running [/bin/sh -c pnpm --filter=$name run build]: exit code: 1
> ```

你搞定了嘛，一直编译不了
