### ISSUE TITLE
API需求：为集合批量添加数据返回QA对的id

### ISSUE THREAD

**Issue by winwindg** [labring/FastGPT#1590]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
为集合批量添加数据接口，添加成功后，并没有返回QA的id
API文档：https://doc.fastgpt.in/docs/development/openapi/dataset/#%E4%B8%BA%E9%9B%86%E5%90%88%E6%89%B9%E9%87%8F%E6%B7%BB%E5%8A%A0%E6%B7%BB%E5%8A%A0%E6%95%B0%E6%8D%AE
返回样例：
{"code":200,"statusText":"","message":"","data":{"insertLen":1,"overToken":[],"repeat":[],"error":[]}}

**应用场景**
添加知识完成后，需要对知识进行更新操作

**相关示例**

**Comment by c121914yu** [comment]
不会有这个计划（至少未来2,3个大版本内）
异步任务无法获取id

**Comment by winwindg** [comment]
自主解决了，其实有一个insertData的单条添加API，支持同步返回知识id，只不过需要用登录态进行api调用。
