### ISSUE TITLE
http模块 无法请求本地接口 help~

### ISSUE THREAD

**Issue by 13829386012** [labring/FastGPT#1591]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![http](https://github.com/labring/FastGPT/assets/40138671/e5d49ab6-b724-4d8e-a41c-baf691f8b2aa)
无法请求本地接口，要怎么设置吗？
在postman下测试正常
![image](https://github.com/labring/FastGPT/assets/40138671/43c1a400-9ac7-4df3-861f-1d57104f184c)

日志报错如图：
![image](https://github.com/labring/FastGPT/assets/40138671/0957b52d-9fb2-42df-91f3-c43dea996ced)

**复现步骤**

**预期结果**

**相关截图**

**Comment by 13829386012** [comment]
> 你知道容器里 localhost 指向哪里么

我是用源码部署的，不是docker，改成127.0.0.1和本机ip也是一样的错误

**Comment by c121914yu** [comment]
> > 你知道容器里 localhost 指向哪里么
> 
> 我是用源码部署的，不是docker，改成127.0.0.1和本机ip也是一样的错误

看看有没有其他人遇到吧，我试了试本地开发，localhost 能请求到其他端口服务。
你这个看着，是提示服务挂了

**Comment by 13829386012** [comment]
> > > 你知道容器里 localhost 指向哪里么
> > 
> > 
> > 我是用源码部署的，不是docker，改成127.0.0.1和本机ip也是一样的错误
> 
> 看看有没有其他人遇到吧，我试了试本地开发，localhost 能请求到其他端口服务。 你这个看着，是提示服务挂了



> > > 你知道容器里 localhost 指向哪里么
> > 
> > 
> > 我是用源码部署的，不是docker，改成127.0.0.1和本机ip也是一样的错误
> 
> 看看有没有其他人遇到吧，我试了试本地开发，localhost 能请求到其他端口服务。 你这个看着，是提示服务挂了

我换了其他不是本地的接口，又可以正常调用，就本地接口不行☹️
