### ISSUE TITLE
容器正常运行，但登录界面和创建应用界面总出现网络异常，不知道啥原因，多次删除镜像重新下载也没用

### ISSUE THREAD

**Issue by fanfanyaya** [labring/FastGPT#1594]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
mac M1 os14.5 利用Orbstack部署

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
<img width="1440" alt="截屏2024-05-24 22 51 54" src="https://github.com/labring/FastGPT/assets/50243914/e3e7c522-1e07-4fdb-a603-f37f249e013f">

**Comment by lijiajun1997** [comment]
看下docker日志吧

**Comment by c121914yu** [comment]
大概率配置文件写的有问题，看日志就知道了
