### ISSUE TITLE
当前上游负载已饱和，请稍后再试。

### ISSUE THREAD

**Issue by guodongbin1981** [labring/FastGPT#1595]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
最新版本
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
创建知识库，上传文件一段时间部分文件索引完成后出现卡滞，查看日志发现有报错。

**oneapi的报错：**
[INFO] 2024/05/25 - 02:20:27 | 2024052502202733673623654963543 | user 1 has enough quota 499999999437192, trusted and no need to pre-consume  [INFO] 2024/05/25 - 02:20:27 | 2024052502202739980431347533765 | user 1 has enough quota 499999999437192, trusted and no need to pre-consume  [INFO] 2024/05/25 - 02:20:27 | 2024052502202739933106745127615 | user 1 has enough quota 499999999437192, trusted and no need to pre-consume  [INFO] 2024/05/25 - 02:20:27 | 2024052502202740050221842551812 | user 1 has enough quota 499999999437192, trusted and no need to pre-consume  [GIN] 2024/05/25 - 02:20:27 | 2024052502202733503658994402104 | 429 |   94.358928ms |    192.168.96.6 |    POST /v1/embeddings [ERR] 2024/05/25 - 02:20:27 | 2024052502202733503658994402104 | relay error (channel #5): 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502202733503658994402104)  [GIN] 2024/05/25 - 02:20:27 | 2024052502202733673623654963543 | 429 |   98.693105ms |    192.168.96.6 |    POST /v1/embeddings [ERR] 2024/05/25 - 02:20:27 | 2024052502202733673623654963543 | relay error (channel #5): 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502202733673623654963543)  [GIN] 2024/05/25 - 02:20:27 | 2024052502202740050221842551812 | 429 |   94.280178ms |    192.168.96.6 |    POST /v1/embeddings [ERR] 2024/05/25 - 02:20:27 | 2024052502202740050221842551812 | relay error (channel #5): 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502202740050221842551812)  [ERR] 2024/05/25 - 02:20:27 | 2024052502202739933106745127615 | relay error (channel #5): 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502202739933106745127615)  [ERR] 2024/05/25 - 02:20:27 | 2024052502202739980431347533765 | relay error (channel #5): 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502202739980431347533765)  [GIN] 2024/05/25 - 02:20:27 | 2024052502202739933106745127615 | 429 |  100.251404ms |    192.168.96.6 |    POST /v1/embeddings [GIN] 2024/05/25 - 02:20:27 | 2024052502202739980431347533765 | 429 |  100.005986ms |    192.168.96.6 |    POST /v1/embeddings [INFO] 2024/05/25 - 02:20:27 | 2024052502202757108942680377852 | user 1 has enough quota 499999999437192, trusted and no need to pre-consume  [INFO] 2024/05/25 - 02:20:27 | 2024052502202757628593872201875 | user 1 has enough quota 499999999437192, trusted and no need to pre-consume  [INFO] 2024/05/25 - 02:20:27 | 2024052502202759666825923268810 | user 1 has enough quota 499999999437192, trusted and no need to pre-consume  [INFO] 2024/05/25 - 02:20:27 | 2024052502202761775415423855588 | user 1 has enough quota 499999999437192, trusted and no need to pre-consume  [ERR] 2024/05/25 - 02:20:27 | 2024052502202757108942680377852 | relay error (channel #5): 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502202757108942680377852)  [GIN] 2024/05/25 - 02:20:27 | 2024052502202757108942680377852 | 429 |   99.341161ms |    192.168.96.6 |    POST /v1/embeddings [GIN] 2024/05/25 - 02:20:27 | 2024052502202759666825923268810 | 429 |   86.952642ms |    192.168.96.6 |    POST /v1/embeddings [ERR] 2024/05/25 - 02:20:27 | 2024052502202759666825923268810 | relay error (channel #5): 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502202759666825923268810)  [ERR] 2024/05/25 - 02:20:27 | 2024052502202757628593872201875 | relay error (channel #5): 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502202757628593872201875)  [GIN] 2024/05/25 - 02:20:27 | 2024052502202757628593872201875 | 429 |  141.115694ms |    192.168.96.6 |    POST /v1/embeddings

fastgpt的报错日志：
error => 429 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502260358492959268687883) [ERROR] 2024-05-25 02:26:03 429 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502260358492959268687883)  [INFO] 2024-05-25 02:26:03 [Vector Queue] Start  Embedding Error eK [Error]: 429 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502260362809543897967652)     at eI.generate (/app/projects/app/.next/server/chunks/15428.js:15:67738)     at av.makeStatusError (/app/projects/app/.next/server/chunks/15428.js:15:79337)     at av.makeRequest (/app/projects/app/.next/server/chunks/15428.js:15:80260)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async c (/app/projects/app/.next/server/chunks/75612.js:162:1395)     at async p (/app/projects/app/.next/server/chunks/75612.js:133:14840)     at async Promise.all (index 0)     at async u (/app/projects/app/.next/server/chunks/75612.js:310:29496)     at async /app/projects/app/.next/server/chunks/75612.js:312:3333     at async r (/app/projects/app/.next/server/chunks/75612.js:130:20236) {   status: 429,      'content-length': '156',     'content-type': 'application/json; charset=utf-8',     date: 'Sat, 25 May 2024 02:26:03 GMT',     'x-oneapi-request-id': '2024052502260362809543897967652'   },   error: {     message: '当前分组上游负载已饱和，请稍后再试 (request id: 2024052502260362809543897967652)', {     type: '',   message: '429 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502260362809543897967652)',     param: '',     code: '1113'   stack: 'Error: 429 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502260362809543897967652)\n' +   },     '    at eI.generate (/app/projects/app/.next/server/chunks/15428.js:15:67738)\n' +   code: '1113',     '    at av.makeStatusError (/app/projects/app/.next/server/chunks/15428.js:15:79337)\n' +      '    at av.makeRequest (/app/projects/app/.next/server/chunks/15428.js:15:80260)\n' +   type: ''     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' + }     '    at async c (/app/projects/app/.next/server/chunks/75612.js:162:1395)\n' + error => 429 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502260362809543897967652)     '    at async p (/app/projects/app/.next/server/chunks/75612.js:133:14840)\n' + [ERROR] 2024-05-25 02:26:03 429 当前分组上游负载已饱和，请稍后再试 (request id: 2024052502260362809543897967652)      '    at async Promise.all (index 0)\n' +     '    at async u (/app/projects/app/.next/server/chunks/75612.js:310:29496)\n' +     '    at async /app/projects/app/.next/server/chunks/75612.js:312:3333\n' +     '    at async r (/app/projects/app/.next/server/chunks/75612.js:130:20236)' }

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
key调用频率满了
