### ISSUE TITLE
使用gpt-4-vision报错

### ISSUE THREAD

**Issue by mpuazxc2** [labring/FastGPT#1598]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
当使用工具->获取当前时间时，在模型 gpt-4-vision下报错
null 2 validation errors for Request body -> tool_choice extra fields not permitted (type=value_error.extra) body -> tools extra fields not permitted (type=value_error.extra) (request id: 20240526085448656385903tdrUIF3q) (request id: 20240526085448646995733epv5WhS4) (request id: 2024052608544790244303641471841)

使用gpt-3.5-turbo或者gpt-4-turbo时就正常返回，不会报错
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
4v 不支持工具调用，直接用 4o 就可以了
