### ISSUE TITLE
将知识库搜索结果和http请求结果合并给大模型

### ISSUE THREAD

**Issue by stevensy123** [labring/FastGPT#1599]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: v4.8

**问题描述, 日志截图**
在AI对话框中，知识库引用只能选择知识库或者http请求其中的一个源，无法添加多个
**复现步骤**

**预期结果**
知识库引用可增加多个来源
**相关截图**

**Comment by masktone** [comment]
![0525](https://github.com/labring/FastGPT/assets/124564913/db760748-5fbc-4622-b103-6ce0569aa765)

**Comment by c121914yu** [comment]
很多方法，最简单的就是工具调用，准确好用，就是费点token。
其次可以是HTTP请求，返回的引用格式和知识库完全一致，然后通过知识库引用合并。
最后就是，把知识库搜索结果也发到HTTP中，代码里进行合并。
