### ISSUE TITLE
配置多个模型问题

### ISSUE THREAD

**Issue by xuwtgx** [labring/FastGPT#1600]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本** 
4.8.1

- [ ] 公有云版本
- [ √] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![cdb8fa9986057c127a41e1331130caa](https://github.com/labring/FastGPT/assets/60810823/30c48e62-7cbf-4d2f-820d-5a0e513d9d3d)
图1
![image](https://github.com/labring/FastGPT/assets/60810823/d84266f7-1481-41cc-b53c-564877eb0000)
图2
1.图1报错是调用到图2的ip
2.图1使用ollama
3.图1在使用不适用知识库的时候正常使用，添加知识库就会报错图1

**复现步骤**
1.配置ollma模型启动，配置chatglm模型（两台主机）
2.配置oneapi
3.模型顺序config中配置第一个为chatglm（可不启动这台服务器和服务），第二个为ollama中的模型
4.使用fastgpt，配置ollama中的模型，链接本地知识库提问会出现这样的报错
![image](https://github.com/labring/FastGPT/assets/60810823/b1176555-12ed-49c4-9f68-9a5a3706d8a7)

**预期结果**
配置模型以后，即使选择其它模型，也会被调用到config文件中第一个模型回答问题
**相关截图**

**Comment by lijiajun1997** [comment]
#3.图1在使用不适用知识库的时候正常使用，添加知识库就会报错图1

是不是知识库里没有关掉问题优化？
以及是否正确配置向量模型？

**Comment by c121914yu** [comment]
楼上正解，肯定是没改问题优化模型
