### ISSUE TITLE
私有部署版本4.8，上传文件集合报错404

### ISSUE THREAD

**Issue by zmm1996** [labring/FastGPT#1602]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: V4.8

**问题描述, 日志截图**

**复现步骤**

**预期结果**
上传成功，返回200

**相关截图**
上传到本地部署Fastgpt服务接口,返回404
http://192.168.80.120:3000/api/core/dataset/collection/create/localFile

![image](https://github.com/labring/FastGPT/assets/40532959/7ce649cb-4ea6-43b8-8e5f-b4cd33c9dc9e)

上传到本地部署Fastgpt服务接口，返回200
https://api.fastgpt.in/api/core/dataset/collection/create/localFile

![image](https://github.com/labring/FastGPT/assets/40532959/e7bc909e-1907-4187-b85e-e2a05ffbca2f)

**Comment by nongmo677** [comment]
翻了一下代码，这个是4.8.1才有的路由
