### ISSUE TITLE
fastgpt:v4.8.1的docker版本/login?lastRoute=xxxx无限重定向

### ISSUE THREAD

**Issue by Pandolar** [labring/FastGPT#1604]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: fastgpt:v4.8.1的docker版本

**问题描述, 日志截图**
fastgpt:v4.8.1的docker版本中登录无限重定向
回退到4.8版本就没有该问题
**复现步骤**
直接使用docker部署fastgpt:v4.8.1
**预期结果**
点击登录会无限弹出
**相关截图**

https://github.com/labring/FastGPT/assets/54896726/768bd7d8-6e34-4fd0-86fc-b23e479e11a9

**Comment by c121914yu** [comment]
未发现该情况，可以看看日志和network

**Comment by Pandolar** [comment]
![afb355223d0416e9b063bf8920aefe3](https://github.com/labring/FastGPT/assets/54896726/1420456e-6a23-4f25-a544-324181f2b063)
docker的日志

**Comment by c121914yu** [comment]
> ![afb355223d0416e9b063bf8920aefe3](https://private-user-images.githubusercontent.com/54896726/333998724-1420456e-6a23-4f25-a544-324181f2b063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTEzNTksIm5iZiI6MTcxNjkxMTA1OSwicGF0aCI6Ii81NDg5NjcyNi8zMzM5OTg3MjQtMTQyMDQ1NmUtNmEyMy00ZjI1LWE1NDQtMzI0MTgxZjJiMDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE1NDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ODA2YWZjYzU2YjNmZjE2NzI5ODlmMTg0MjQ3NzlmYTYwY2FjMzQwZjllYjU0NGE5YzI0NzVjMTQ4YTQyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.euMJtTmIWopFesKnhTHA5xgZdnJ_GjRawsr3deFSxk8) docker的日志

networkf的日志，看看有没有错误接口

**Comment by HotelEnglish** [comment]
我也遇到了，但已经解决了。试试删除旧的容器，修改.yml里的版本为v4.8.1，再重新down, pull, 和-d

**Comment by Pandolar** [comment]
> 我也遇到了，但已经解决了。试试删除旧的容器，修改.yml里的版本为v4.8.1，再重新down, pull, 和-d

好的谢谢  我现在先用旧版本 等官方修复了再说

**Comment by c121914yu** [comment]
可以看看是不是你浏览器禁用了 cookie

**Comment by Pandolar** [comment]
> 可以看看是不是你浏览器禁用了 cookie

你好，浏览器并没有禁用cookie，换了两三个浏览器都是这样，包括火狐谷歌等；
但使用谷歌浏览器的隐私模式时，?lastRoute=xxxx参数会被去除，这样就可以访问。

**Comment by Pandolar** [comment]
你好，关于该问题我这边找到无限重定向的原因了。

fastgpt该私有化部署的域名为https://fastgpt.xxxxx.com/
但在xxxxx.com我们有一个统一认证平台，认证后会在cookie中set一个token。

从4.8.1开始，应该是fastgpt代码做了一些更改，在登陆的时候也会set一个key为token的cookie值（此处本人并未看源码无法验证），这会与我主域名的cookie**冲突**，导致无法**写入fastgpt的token**

所以虽然提示登陆成功从http请求中拿到了token的值，但无法写入浏览器，就会出现无限重定向的现象。

建议：
**把fastgpt的token改个名字如fastgpt_token，即可解决冲突。**

该使用场景还是很常见的，很多主域名下也会set token值，所以建议fastgpt这边更改比较合适，或者参考**4.8.0**以之前的**前端权限验证方式**，感谢。

![image](https://github.com/labring/FastGPT/assets/54896726/4bd2ddeb-ff99-46d1-93b1-1700627648b8)

**Comment by c121914yu** [comment]
> 你好，关于该问题我这边找到无限重定向的原因了。
> 
> fastgpt该私有化部署的域名为https://fastgpt.xxxxx.com/
> 但在xxxxx.com我们有一个统一认证平台，认证后会在cookie中set一个token。
> 
> 从4.8.1开始，应该是fastgpt代码做了一些更改，在登陆的时候也会set一个key为token的cookie值（此处本人并未看源码无法验证），这会与我主域名的cookie**冲突**，导致无法**写入fastgpt的token**
> 
> 所以虽然提示登陆成功从http请求中拿到了token的值，但无法写入浏览器，就会出现无限重定向的现象。
> 
> 建议：
> **把fastgpt的token改个名字如fastgpt_token，即可解决冲突。**
> 
> 该使用场景还是很常见的，很多主域名下也会set token值，所以建议fastgpt这边更改比较合适，或者参考**4.8.0**以之前的**前端权限验证方式**，感谢。
> 
> ![image](https://github.com/labring/FastGPT/assets/54896726/3e6d1868-867c-4b34-a6f1-d6ddf0a336a4)
> 
> 

是的，感谢你的提醒。cookie name 确实是 token，后边改个名。

**Comment by c121914yu** [comment]
忘记关联，4.8.5 已修改

**Comment by Almostlover0608** [comment]
当前最新版本，仍有重定向问题。在微信内置浏览器可以打开，edge浏览器、星愿浏览器（chrome内核）都重定向
