### ISSUE TITLE
如何通过免登陆窗口传递全局变量？

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#1606]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
程序通过调用API可以给全局变量赋值，但是免登陆窗口没找到地方给APP内部的全局变量赋值。
**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/c54c1ca0-b2c7-433e-b06f-372dd6fccbb4)

**Comment by boleyn** [comment]
url 上可以加？param=xxx 的方式传递

**Comment by c121914yu** [comment]
如楼上说的。
添加全局变量，然后在url上增加三方参数。

**Comment by ppkitty** [comment]
测试成功，谢谢
