### ISSUE TITLE
多轮问答后，容易乱码

### ISSUE THREAD

**Issue by stevenchen0018** [labring/FastGPT#1614]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

FastGPT V4.8.1 
gpt-4o-2024-05-13

**问题描述, 日志截图**
主要问题就是gpt-4o 多轮对话后，回复容易出现大量中文乱码，所以想问下这事什么原因？

**复现步骤**

**预期结果**

**相关截图**
<img width="896" alt="image" src="https://github.com/labring/FastGPT/assets/7030371/81690e8e-71e1-4283-bf28-03801cb42608">

**Comment by lijiajun1997** [comment]
api渠道问题，以及建议把模型token上限限制在32k,我几百轮对话没有遇到类似的问题。

**Comment by stevenchen0018** [comment]
> api渠道问题，以及建议把模型token上限限制在32k,我几百轮对话没有遇到类似的问题。

api 都是官方openai和这个渠道有什么关系？不是很理解这个意思？前几轮对话都没问题，多几轮就开始出现乱码，而且就是gpt-4o 这个版本会现

**Comment by c121914yu** [comment]
模型问题或者渠道问题。
不是官方直连渠道，可能有浑水摸鱼。
或者温度设置太高。
