### ISSUE TITLE
help!调用多模态模型MiniCPM-Llama3-V-2_5异常

### ISSUE THREAD

**Issue by 13829386012** [labring/FastGPT#1616]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.81

**问题描述, 日志截图**
在调用多模态模型MiniCPM-Llama3-V-2_5时，文字聊天正常，打开vision后上传图片时,报错：Service Unavailable503，
请问要如何设置才能正确使用，这个问题困扰我好几日，非常需要帮助
![image](https://github.com/labring/FastGPT/assets/40138671/94c09c87-5cf7-47fd-81b2-8d9db2ddf118)
config设置如下：
![image](https://github.com/labring/FastGPT/assets/40138671/54693928-ff09-4124-abb9-c287495d69ed)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
需要模型按openai的api标准才行

**Comment by ifkd111** [comment]
> 需要模型按openai的api标准才行

额用oneapi接的，所以应该怎么操作呢？

**Comment by 13829386012** [comment]
> 需要模型按openAI的API標準才行



> 需要模型按openai的api标准才行

请问需要怎么操作呢

**Comment by c121914yu** [comment]
> > 需要模型按openAI的API標準才行
> 
> > 需要模型按openai的api标准才行
> 
> 请问需要怎么操作呢

改模型接口兼容openai，或者改oneapi，让它兼容你的模型。

**Comment by ifkd111** [comment]
> 的

怎么改模型接口匹配openai
