### ISSUE TITLE
接入chatgpt-on-wechat后，聊天记录不会在后台产生希望能修复此功能

### ISSUE THREAD

**Issue by Lands-1203** [labring/FastGPT#1617]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
 通过chatgpt-on-wechat接入微信服务号，聊天记录不会在后台产生
**应用场景**
接入微信服务号
**相关示例**
在对话日志中找不到还日志，是否是因为没有 chatId的原因，如果该需要需要去chatgpt-on-wechat提交issues希望能给答复
![image](https://github.com/labring/FastGPT/assets/61341868/90a965c0-e97c-432d-ae97-5f52d908cb42)

![image](https://github.com/labring/FastGPT/assets/61341868/21dfcfa4-85bd-4a29-b914-58c36be3c35e)

**Comment by c121914yu** [comment]
需要给 cow 提修改

**Comment by c121914yu** [comment]
需要给 cow 提修改

**Comment by handsome-owner** [comment]
+1

**Comment by justdavid-y** [comment]
可以参考这个配置https://github.com/zhayujie/chatgpt-on-wechat/issues/2031
