### ISSUE TITLE
接入通义千问大模型Qwen1.5-110B-Chat，会报错，显示模型不存在

### ISSUE THREAD

**Issue by xiaomingcimy** [labring/FastGPT#1618]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
接入通义千问大模型Qwen1.5-110B-Chat，会报错
bad_response_status_code Model not exist. (request id: 2024052809001967802006448504393)

**Comment by c121914yu** [comment]
错误挺明显吧，模型不存在

**Comment by xiaomingcimy** [comment]
要换成小写
