### ISSUE TITLE
当流程中配置{{cTime}}参数时，通过图形界面请求和通过API请求时，该参数取值不一样

### ISSUE THREAD

**Issue by shikaiwei1** [labring/FastGPT#1621]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.1

**问题描述, 日志截图**
当流程中配置{{cTime}}参数时，通过图形界面请求和通过API请求时，该参数取值不一样；在图形界面中，赋值了当前时间；在API中，赋值了当前时间+8小时；
![image](https://github.com/labring/FastGPT/assets/24493077/6bc61a98-fa3d-4e2d-8d4e-3346dc31874a)
![image](https://github.com/labring/FastGPT/assets/24493077/223db5fe-ada6-4a60-8657-2274021913b5)

**复现步骤**
1. 配置一个简单流程，流程开始后使用“指定回复”：当前时间:{{cTime}}
![image](https://github.com/labring/FastGPT/assets/24493077/c65acb1d-d976-45bc-9a14-1495ce182b47)
2. 使用图形界面进行调试（输出的时间是正确的）
![image](https://github.com/labring/FastGPT/assets/24493077/6bc61a98-fa3d-4e2d-8d4e-3346dc31874a)
3. 使用API调用该流程（输出的时间是错误的）
![image](https://github.com/labring/FastGPT/assets/24493077/223db5fe-ada6-4a60-8657-2274021913b5)

 > 当前系统存在环境变量：TZ=Asia/Shanghai

**预期结果**
应当输出下图中的时间（忽略分钟差异）
![image](https://github.com/labring/FastGPT/assets/24493077/6bc61a98-fa3d-4e2d-8d4e-3346dc31874a)

**相关截图**

**Comment by c121914yu** [comment]
你如果系统设置了时区，那用户就是+0，而不是+8

**Comment by leavegee** [comment]
我也遇到了这个问题。 怎么解决呢？4.8.9版本。 页面调试时间是对的， 用api获取的时间是+8的。 怎么修改？
