### ISSUE TITLE
发布的应用在窄屏模式下点击顶部应用名称会跳转到主站

### ISSUE THREAD

**Issue by Mrkk1** [labring/FastGPT#1623]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

将应用使用脚本注入网页
<img width="699" alt="图片" src="https://github.com/labring/FastGPT/assets/60224145/fcfa5bf2-994e-4e14-8f30-48fe2e3facb2">
或者任意应用采用直接打开的方式
<img width="680" alt="图片" src="https://github.com/labring/FastGPT/assets/60224145/af52cae8-f85e-4ba2-bd68-48472fe05b47">
会出现当响应式触发为手机模式时,点击顶部名称会跳转到首页
**复现步骤**
<img width="834" alt="图片" src="https://github.com/labring/FastGPT/assets/60224145/82575861-36bc-44fd-af7e-3ac5d92f0210">
<img width="660" alt="图片" src="https://github.com/labring/FastGPT/assets/60224145/66105ea0-c10e-4340-a935-91a89d19c70e">

如图点击,会跳转回首页,在对外发布的应用情况下不太合理.
**预期结果**
不触发任何行为
**相关截图**
<img width="699" alt="图片" src="https://github.com/labring/FastGPT/assets/60224145/fcfa5bf2-994e-4e14-8f30-48fe2e3facb2">
<img width="680" alt="图片" src="https://github.com/labring/FastGPT/assets/60224145/af52cae8-f85e-4ba2-bd68-48472fe05b47">
<img width="834" alt="图片" src="https://github.com/labring/FastGPT/assets/60224145/82575861-36bc-44fd-af7e-3ac5d92f0210">
<img width="660" alt="图片" src="https://github.com/labring/FastGPT/assets/60224145/66105ea0-c10e-4340-a935-91a89d19c70e">

**Comment by 13829386012** [comment]
看了你的issue,我去试了一下我的，在触发不是手机模式时，同样存在点击标题直接可以访问后台的问题
![image](https://github.com/labring/FastGPT/assets/40138671/03800f08-c40a-48e0-b640-9dd31a0c7443)

**Comment by AndrewAan** [comment]
是有这个情况，希望修复！

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8.3 之前已经修复
