### ISSUE TITLE
知识库引用合并不能合并全局变量

### ISSUE THREAD

**Issue by yp94** [labring/FastGPT#1624]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.1

**问题描述, 日志截图**
![bug1](https://github.com/labring/FastGPT/assets/28262260/5ba3a9ca-e18d-4e31-8a7d-e84aafb72a6c)
![bug2](https://github.com/labring/FastGPT/assets/28262260/c190d818-1753-474e-b212-35140c2208a9)
知识库搜索引用合并输出的内容不会带上全局变量的内容
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
全局变量为什么会是知识库引用类型？

**Comment by yp94** [comment]
> 全局变量为什么会是知识库引用类型？

我的需求是这样的，我创建的时候生成了一份dsl，这份dsl存我本地了。现在我要编辑dsl，我的想法是创建一个全局变量，然后调接口的时候把我本地的dsl带上，赋值给全局变量，再把这个变量当知识库的一部分让llm去修改它

**Comment by c121914yu** [comment]
> > 全局变量为什么会是知识库引用类型？
> 
> 我的需求是这样的，我创建的时候生成了一份dsl，这份dsl存我本地了。现在我要编辑dsl，我的想法是创建一个全局变量，然后调接口的时候把我本地的dsl带上，赋值给全局变量，再把这个变量当知识库的一部分让llm去修改它

字符串走文本加工。引用合并是给知识库搜索结果类型的。
要混用的话，写脚本代码进行合并。

**Comment by yp94** [comment]
> > > 全局变量为什么会是知识库引用类型？
> > 
> > 
> > 我的需求是这样的，我创建的时候生成了一份dsl，这份dsl存我本地了。现在我要编辑dsl，我的想法是创建一个全局变量，然后调接口的时候把我本地的dsl带上，赋值给全局变量，再把这个变量当知识库的一部分让llm去修改它
> 
> 字符串走文本加工。引用合并是给知识库搜索结果类型的。 要混用的话，写脚本代码进行合并。

好吧，希望后面引用合并能加上非知识库的内容

**Comment by c121914yu** [comment]
> > > > 全局变量为什么会是知识库引用类型？
> > > 
> > > 
> > > 我的需求是这样的，我创建的时候生成了一份dsl，这份dsl存我本地了。现在我要编辑dsl，我的想法是创建一个全局变量，然后调接口的时候把我本地的dsl带上，赋值给全局变量，再把这个变量当知识库的一部分让llm去修改它
> > 
> > 
> > 字符串走文本加工。引用合并是给知识库搜索结果类型的。 要混用的话，写脚本代码进行合并。
> 
> 好吧，希望后面引用合并能加上非知识库的内容

文本加个不就是么

**Comment by yp94** [comment]
> > > > > 全局变量为什么会是知识库引用类型？
> > > > 
> > > > 
> > > > 我的需求是这样的，我创建的时候生成了一份dsl，这份dsl存我本地了。现在我要编辑dsl，我的想法是创建一个全局变量，然后调接口的时候把我本地的dsl带上，赋值给全局变量，再把这个变量当知识库的一部分让llm去修改它
> > > 
> > > 
> > > 字符串走文本加工。引用合并是给知识库搜索结果类型的。 要混用的话，写脚本代码进行合并。
> > 
> > 
> > 好吧，希望后面引用合并能加上非知识库的内容
> 
> 文本加个不就是么

文本好像不能添加知识库内容吧？我最终输入llm的知识库相当于是一部分知识库+全局变量的内容

**Comment by yp94** [comment]
> > > > > 全局变量为什么会是知识库引用类型？
> > > > 
> > > > 
> > > > 我的需求是这样的，我创建的时候生成了一份dsl，这份dsl存我本地了。现在我要编辑dsl，我的想法是创建一个全局变量，然后调接口的时候把我本地的dsl带上，赋值给全局变量，再把这个变量当知识库的一部分让llm去修改它
> > > 
> > > 
> > > 字符串走文本加工。引用合并是给知识库搜索结果类型的。 要混用的话，写脚本代码进行合并。
> > 
> > 
> > 好吧，希望后面引用合并能加上非知识库的内容
> 
> 文本加个不就是么

大佬，能给个解决方案吗？求求啦
