### ISSUE TITLE
高级编排流程走不到http请求

### ISSUE THREAD

**Issue by mj31** [labring/FastGPT#1625]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我这边在测试高级编排的http请求，我自己写了接口，然后按照官方给的例子，我这边调试，只能走到 工具调用
![图片](https://github.com/labring/FastGPT/assets/20577126/fbdf6dd9-b242-4e5e-9136-a06bf55af33a)

下面是我的配置：
![图片](https://github.com/labring/FastGPT/assets/20577126/3901adda-eab7-4cb2-b0a1-d5694527e5d5)

**应用场景**

**相关示例**

**Comment by mj31** [comment]
版本是 v4.8.1

**Comment by mj31** [comment]
已解决 关闭吧

**Comment by sdytzjp** [comment]
请问如何解决的？

**Comment by mj31** [comment]
修改 config.json里的大模型参数
 "toolChoice": false
"functionCall": false,
