### ISSUE TITLE
API调用方式，如何修改stream为true

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1627]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.1

**问题描述, 日志截图**
API请求时， stream默认为false，有没有办法或者在哪里可以修改stream为true
![image](https://github.com/labring/FastGPT/assets/66725845/57d681ca-181c-49c5-a1ef-a156f6704dd3)

**复现步骤**

**预期结果**

**相关截图**

**Comment by Essence9999** [comment]
场景补充：使用智能微秘书，连接微信

**Comment by AuYuHui** [comment]
在请求体 把 stream 改为 true

**Comment by Essence9999** [comment]
> 在请求体 把 stream 改为 true

这个api的请求体在哪里修改啊？

**Comment by c121914yu** [comment]
微信 stream 也没啥用
