### ISSUE TITLE
本地部署导入文本数据集，问答拆分未起作用。

### ISSUE THREAD

**Issue by blackdwarf-star** [labring/FastGPT#1628]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.1

**问题描述, 日志截图**
本地部署的fastgpt，知识库导入文本数据集，选择问答拆分的结果并没有问答对而只是文本分段。索引模型是m3e，文件处理模型是qwen-7b-chat-q4_0。

<img width="829" alt="image" src="https://github.com/labring/FastGPT/assets/85542399/17a79a52-d907-4287-a909-1866fdc97cf8">

**复现步骤**

**预期结果**

**相关截图**
<img width="1037" alt="image" src="https://github.com/labring/FastGPT/assets/85542399/d1a49c54-e352-4e10-8839-3dfce9d67ee0">

**Comment by blackdwarf-star** [comment]
> 不应该啊，感觉是你操作问题，oneapi都没收到QA的请求

可能是我配置的问题，因为我发现刚开始问题拆分后日志就报告说2024-05-29 17:42:35 oneapi    | [SYS] 2024/05/29 - 09:42:35 | model ratio not found: llama3:latest。但是聊天那里llama3:latest是可以用的。请问配置文件或者别的地方应该怎么改呢？

**Comment by blackdwarf-star** [comment]
> > 不应该啊，感觉是你操作问题，oneapi都没收到QA的请求
> 
> 可能是我配置的问题，因为我发现刚开始问题拆分后日志就报告说2024-05-29 17:42:35 oneapi | [SYS] 2024/05/29 - 09:42:35 | model ratio not found: llama3:latest。但是聊天那里llama3:latest是可以用的。请问配置文件或者别的地方应该怎么改呢？
这是我config.json文件中llama3的设置
{
      "model":"llama3:latest",
      "name":"llama3",
      "maxContext": 128000,
      "avatar": "/imgs/model/llama3.svg",
      "maxResponse": 4000,
      "quoteMaxToken": 100000,
      "maxTemperature": 1.2,
      "charsPointsPrice": 0,
      "censor": false,
      "vision": false,
      "datasetProcess": true,
      "usedInClassify": true,
      "usedInExtractFields": true,
      "usedInToolCall": true,
      "usedInQueryExtension": true,
      "toolChoice": true,
      "functionCall": true,
      "customCQPrompt": "",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig": {}
    },

**Comment by lijiajun1997** [comment]
"maxContext": 128000,
"avatar": "/imgs/model/llama3.svg",
"maxResponse": 4000,
"quoteMaxToken": 100000,    这里都改成4k试试, QA拆分的时候会按上限走，但是llama3没这么大的上下文吧？

**Comment by blackdwarf-star** [comment]
> "maxContext": 128000, "avatar": "/imgs/model/llama3.svg", "maxResponse": 4000, "quoteMaxToken": 100000, 这里都改成4k试试, QA拆分的时候会按上限走，但是llama3没这么大的上下文吧？

我对LLM非常不了解，所以想了解一下，像这些比较小的LLM，这里一般设置多少比较合适？

**Comment by lijiajun1997** [comment]
> > "maxContext": 128000, "avatar": "/imgs/model/llama3.svg", "maxResponse": 4000, "quoteMaxToken": 100000, 这里都改成4k试试, QA拆分的时候会按上限走，但是llama3没这么大的上下文吧？
> 
> 我对LLM非常不了解，所以想了解一下，像这些比较小的LLM，这里一般设置多少比较合适？

一般是8k的上下文

**Comment by xiusidunhuren** [comment]
请问你qwen 1.5 7B模型可以qa拆分了吗，我改把参数都改4000也不行

**Comment by xiusidunhuren** [comment]
![260001da4c2f0f5762c472a8fdbd215](https://github.com/labring/FastGPT/assets/86663794/437ecf96-0b3c-47d3-9d7e-6b01fbfc33d0)

**Comment by blackdwarf-star** [comment]
> 请问你qwen 1.5 7B模型可以qa拆分了吗，我改把参数都改4000也不行

可以了。不过可能模型太小了这个问答拆分也不是很好用，并且有一些数据并没有产生问答对还是文本拆分。

**Comment by sgwsgw** [comment]
> > 请问你qwen 1.5 7B模型可以qa拆分了吗，我改把参数都改4000也不行
> 
> 可以了。不过可能模型太小了这个问答拆分也不是很好用，并且有一些数据并没有产生问答对还是文本拆分。

请问一下，你们上传的文件 模板是什么样子的？问答拆分的
