### ISSUE TITLE
知识库语义检索结果异常,向量没有归一化要如何解决？

### ISSUE THREAD

**Issue by 13829386012** [labring/FastGPT#1633]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
V4.81
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/40138671/dd1c8b7d-0656-4ed7-9f00-627b2cc0584b)
在知识库搜索测试时，向量相似性得分是好几百，超过1，导致无法使用最低相关度来过滤
翻看issue时，有提到向量没有归一，想请教一下具体要如何做？

我用的embedding模型是M3E和nomic-embed-text-v1.5

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
归一化是模型服务处理的，有多种算法，可以去对应模型社区找。

**Comment by zha0jf** [comment]
修改 packages/service/core/ai/embedding/index.ts 文件，

在文档最后，增加如下函数：
// Define the normalize_embedding function
export function normalizeEmbedding(vector: number[]): number[] {
// Calculate L2 norm
const norm = Math.sqrt(vector.reduce((acc, value) => acc + (value * value), 0));

// Handle zero norm to avoid division by zero
if (norm === 0) {
return vector;
}

// Create a new array for the normalized vector
const normalizedVector = new Array(vector.length).fill(0);
for (let i = 0; i < vector.length; i++) {
normalizedVector[i] = vector[i] / norm;
}

return normalizedVector;
}

然后，将此文件中的 getVectorsByText函数中的 如下代码，
const [tokens, vectors] = await Promise.all([
countPromptTokens(input),
Promise.all(res.data.map((item) =>unityDimensional(item.embedding)))
]);

替换为
const [tokens, vectors] = await Promise.all([
countPromptTokens(input),
Promise.all(res.data.map((item) => {
// Apply normalization before returning
return normalizeEmbedding(unityDimensional(item.embedding));
})),
]);
即可。

上述修改的作用是：对于api返回的vectors进行归一化操作，如果api返回的结果已经是归一化过的，则内容不变。

**Comment by 13829386012** [comment]
> 修改 packages/service/core/ai/embedding/index.ts 文件，
> 
> 在文档最后，增加如下函数： // Define the normalize_embedding function export function normalizeEmbedding(vector: number[]): number[] { // Calculate L2 norm const norm = Math.sqrt(vector.reduce((acc, value) => acc + (value * value), 0));
> 
> // Handle zero norm to avoid division by zero if (norm === 0) { return vector; }
> 
> // Create a new array for the normalized vector const normalizedVector = new Array(vector.length).fill(0); for (let i = 0; i < vector.length; i++) { normalizedVector[i] = vector[i] / norm; }
> 
> return normalizedVector; }
> 
> 然后，将此文件中的 getVectorsByText函数中的 如下代码， const [tokens, vectors] = await Promise.all([ countPromptTokens(input), Promise.all(res.data.map((item) =>unityDimensional(item.embedding))) ]);
> 
> 替换为 const [tokens, vectors] = await Promise.all([ countPromptTokens(input), Promise.all(res.data.map((item) => { // Apply normalization before returning return normalizeEmbedding(unityDimensional(item.embedding)); })), ]); 即可。
> 
> 上述修改的作用是：对于api返回的vectors进行归一化操作，如果api返回的结果已经是归一化过的，则内容不变。

实测可以了,解决了这个问题，非常非常感谢您，祝你生活愉快

**Comment by chenmonster** [comment]
> 修改 packages/service/core/ai/embedding/index.ts 文件，
> 
> 在文档最后，增加如下函数： // Define the normalize_embedding function export function normalizeEmbedding(vector: number[]): number[] { // Calculate L2 norm const norm = Math.sqrt(vector.reduce((acc, value) => acc + (value * value), 0));
> 
> // Handle zero norm to avoid division by zero if (norm === 0) { return vector; }
> 
> // Create a new array for the normalized vector const normalizedVector = new Array(vector.length).fill(0); for (let i = 0; i < vector.length; i++) { normalizedVector[i] = vector[i] / norm; }
> 
> return normalizedVector; }
> 
> 然后，将此文件中的 getVectorsByText函数中的 如下代码， const [tokens, vectors] = await Promise.all([ countPromptTokens(input), Promise.all(res.data.map((item) =>unityDimensional(item.embedding))) ]);
> 
> 替换为 const [tokens, vectors] = await Promise.all([ countPromptTokens(input), Promise.all(res.data.map((item) => { // Apply normalization before returning return normalizeEmbedding(unityDimensional(item.embedding)); })), ]); 即可。
> 
> 上述修改的作用是：对于api返回的vectors进行归一化操作，如果api返回的结果已经是归一化过的，则内容不变。

我用的是 `Docker Compose` 部署的，进入容器发下 `/app/packages/service` 目录下，发现只有一个 `package.json` 文件，没有这些文件，该怎么改呢？

**Comment by zha0jf** [comment]
> > 修改 packages/service/core/ai/embedding/index.ts 文件，
> > 在文档最后，增加如下函数： // Define the normalize_embedding function export function normalizeEmbedding(vector: number[]): number[] { // Calculate L2 norm const norm = Math.sqrt(vector.reduce((acc, value) => acc + (value * value), 0));
> > // Handle zero norm to avoid division by zero if (norm === 0) { return vector; }
> > // Create a new array for the normalized vector const normalizedVector = new Array(vector.length).fill(0); for (let i = 0; i < vector.length; i++) { normalizedVector[i] = vector[i] / norm; }
> > return normalizedVector; }
> > 然后，将此文件中的 getVectorsByText函数中的 如下代码， const [tokens, vectors] = await Promise.all([ countPromptTokens(input), Promise.all(res.data.map((item) =>unityDimensional(item.embedding))) ]);
> > 替换为 const [tokens, vectors] = await Promise.all([ countPromptTokens(input), Promise.all(res.data.map((item) => { // Apply normalization before returning return normalizeEmbedding(unityDimensional(item.embedding)); })), ]); 即可。
> > 上述修改的作用是：对于api返回的vectors进行归一化操作，如果api返回的结果已经是归一化过的，则内容不变。
> 
> 我用的是 `Docker Compose` 部署的，进入容器发下 `/app/packages/service` 目录下，发现只有一个 `package.json` 文件，没有这些文件，该怎么改呢？

需要修改源码，然后重新docker build 映像。构建好的映像里面的代码好像是做过混淆，没找到可修改的位置。
