### ISSUE TITLE
无效的令牌

### ISSUE THREAD

**Issue by Pnut-GGG** [labring/FastGPT#164]
在升级到4.0之后 直接进行使用 提示无效的令牌
不能查看之前创建的所有应用
但是可以创建应用 在对话的时候 提示无效令牌
并且 能查看到之前创建的知识库
可能的原因：
知识库模块存在鉴权错误
创建应用存在鉴权问题

**Comment by c121914yu** [comment]
没走初始化数据库，看文档

**Comment by zhangzhanhui** [comment]
> 

在fastgpt.run上面遇到同样问题，也是没初始化数据库吗？他们升级也忽视了这一步？

**Comment by c121914yu** [comment]
> > 
> 
> 在fastgpt.run上面遇到同样问题，也是没初始化数据库吗？他们升级也忽视了这一步？

不是，那个是因为oneapi项目的问题

**Comment by c121914yu** [comment]
> > > 
> > 
> > 在fastgpt.run上面遇到同样问题，也是没初始化数据库吗？他们升级也忽视了这一步？
> 
> 不是，那个是因为oneapi项目的问题

mysql导致，每小时同步时候会有几分钟异常

**Comment by Pnut-GGG** [comment]
生成向量错误: unAuthorization 是什么问题啊 能正常对话 但是导入数据库不行

**Comment by zhangzhanhui** [comment]
> > > > 
> > > 
> > > 
> > > 在fastgpt.run上面遇到同样问题，也是没初始化数据库吗？他们升级也忽视了这一步？
> > 
> > 
> > 不是，那个是因为oneapi项目的问题
> 
> mysql导致，每小时同步时候会有几分钟异常

好像是你说的那样，后来用就好了。但是选了文心一言的模型又不行了。
顺便请教一下，如何把chatgpt添加进fastgpt，目测现在只有fastAI和文心一言的模型？

**Comment by azoth07** [comment]
环境变量变动了，OPENAIKEY现在变成了CHAT_API_KEY

**Comment by azoth07** [comment]
OPENAI_TRAINING_KEY和GPT4KEY貌似也不单独部署，url和key直接用openapi去集中管理，大概这个思路。
