### ISSUE TITLE
❇️ 知识库支持图片内容作为ltem

### ISSUE THREAD

**Issue by Dr-xiaoming** [labring/FastGPT#1640]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
 知识库支持图片内容作为ltem
**应用场景**

**相关示例**

**Comment by lijiajun1997** [comment]
知识库本身是可以插入markdown链接作为图片的，只是图片对于LLM来说只是一行代码，他不确定的情况下不太愿意出牌，实际效果不好，需要在图片前面加很多描述，以及在提示词里强调让LLM出知识库里相关的图片。实际应用起来效果不稳定。

**Comment by zhoux0130** [comment]
基于4o也没法实现吗？
应用场景就是saas产品的智能客服，给用户回复的时候需要带出来软件的截图
