### ISSUE TITLE
高级编排内容提取使用

### ISSUE THREAD

**Issue by handsome-owner** [labring/FastGPT#1641]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本** 

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号:  V 4.8.2

**问题描述, 日志截图**
关于高级编排中的内容提取使用。
我在使用过程中切换了多个模型。使用百川模型时，一直报错JSON解析异常
![image](https://github.com/labring/FastGPT/assets/55938848/e3785e09-60fd-40a5-a60a-05978bd3da4b)
使用GLM-3时 无法提取到文本内容
![image](https://github.com/labring/FastGPT/assets/55938848/b3bdf35a-fd4f-4717-8eb7-51290b9d0f13)
这个是配置问题吗? 通过对应模型的官方API 通过HTTP请求是可以提取出来的，
FastGPT config.json 相关模型的配置如下：
![image](https://github.com/labring/FastGPT/assets/55938848/b6074037-3a8f-488c-abac-fb7dc816a200)
请各位大佬帮帮忙吧

**Comment by c121914yu** [comment]
这两个模型都不支持工具调用。

**Comment by huluohu** [comment]
> 这两个模型都不支持工具调用，不能设置工具调用模式。

你好，toolChoice不支持的，functionCall支持可以吗？
我看文档上写会优先toolChoice，若为false，则会functionCall，若也false才会走提示词模式。但是我设置支持functionCall的模型为true，也是提取不到内容。
