### ISSUE TITLE
代码运行， 不支持 promise 

### ISSUE THREAD

**Issue by AuYuHui** [labring/FastGPT#1643]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.2

**问题描述, 日志截图**

**复现步骤**
![image](https://github.com/labring/FastGPT/assets/38815121/2de8ecd8-1db1-4b5f-916d-078071fd36ed)

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/38815121/356a3cbd-16a1-486c-8394-d65db7e720c7)

**Comment by Louis9966** [comment]
我遇到了同样的报错，请问楼主只有在处理promise的时候有报错，还是所有的代码运行都会有报错？
我查了一下，貌似是连接到sanbox的请求被拒绝了
sealos集群部署也有同样的问题
![image](https://github.com/labring/FastGPT/assets/163971929/c228768a-2d2d-4e32-83d2-8f31b042e5cd)

**Comment by sunk926** [comment]
好像函数输入必须是一个 {} 才行

**Comment by c121914yu** [comment]
沙盒不支持promise，也没有啥可用的promise函数（settimeout这类都不会支持）。复杂代码建议用serverless，沙盒主要是用来数据处理。

**Comment by ouyanmei** [comment]
> 我遇到了同样的报错，请问楼主只有在处理promise的时候有报错，还是所有的代码运行都会有报错？ 我查了一下，貌似是连接到sanbox的请求被拒绝了 sealos集群部署也有同样的问题 ![image](https://private-user-images.githubusercontent.com/163971929/335540465-c228768a-2d2d-4e32-83d2-8f31b042e5cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTQ5ODMsIm5iZiI6MTcyMDQ5NDY4MywicGF0aCI6Ii8xNjM5NzE5MjkvMzM1NTQwNDY1LWMyMjg3NjhhLTJkMmQtNGUzMi04M2QyLThmMzFiMDQyZTVjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMzExMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGEzN2YzZGZlZjJjZmJlMjM0YTY5ZjdmOGY2Mjg2NTYxYmUwMTcxMTVkNGRlYzY5NGY1MDE1YjU3MzczODgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pjTc2xh5LsRg1-zooSH4424ehiZMlZRvEgegQm2WD2o)

请问你解决了吗
