### ISSUE TITLE
【safari兼容】iPhone打开网页链接不显示发送按钮

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1646]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.1

**问题描述, 日志截图**
使用iPhone手机打开分享链接，问题发送按钮不显示
**复现步骤**
iPhone微信打开分享链接，都显示正常；在输入框输入内容，右边的发送键消失了，点击iPhone键盘发送，也发送不了。

经过查看过往issue，猜测可能是safari安全问题，我的链接是http开头，苹果浏览器是不是只识别https协议？如何将默认的http分享链接改为https
**预期结果**?

**相关截图**
![mmexport1717073638258](https://github.com/labring/FastGPT/assets/66725845/88c67c59-697e-4013-910c-dc1ddc974c7a)

**Comment by c121914yu** [comment]
嗯，是个已知问题

**Comment by Essence9999** [comment]
> 嗯，是个已知问题

大佬，有什么解决办法吗？

**Comment by c121914yu** [comment]
> > 嗯，是个已知问题
> 
> 大佬，有什么解决办法吗？

上面已经关联修复pr了

**Comment by Essence9999** [comment]
> > > 嗯，是个已知问题
> > 
> > 
> > 大佬，有什么解决办法吗？
> 
> 上面已经关联修复pr了

好的，非常感谢，大佬您辛苦~
