### ISSUE TITLE
猜你想问功能开启后未显示

### ISSUE THREAD

**Issue by Le-Onde** [labring/FastGPT#1649]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.1

**问题描述, 日志截图**
在调试知识库界面开启‘猜你想问’功能并保存后，对话仍然未显示猜你想问的问题，是需要提前在config文件里配置相关内容吗
**复现步骤**

**预期结果**

**相关截图**
![went](https://github.com/labring/FastGPT/assets/80252815/fb28988b-e6dc-4f5b-8574-b10f8454a1d1)

**Comment by c121914yu** [comment]
模型没生成或者接口报错了

**Comment by Le-Onde** [comment]
> 模型没生成或者接口报错了

目前看是因为默认模型走的是gpt-3.5，但是我没配置gpt3.5模型，这个具体是要在配置文件中更改吗，我看简易配置中并没有猜你想问这里有可选择模型的地方
![1717145656660](https://github.com/labring/FastGPT/assets/80252815/a470ea65-05d4-4cec-aff5-f7d726038b81)

**Comment by c121914yu** [comment]
> > 模型没生成或者接口报错了
> 
> 目前看是因为默认模型走的是gpt-3.5，但是我没配置gpt3.5模型，这个具体是要在配置文件中更改吗，我看简易配置中并没有猜你想问这里有可选择模型的地方 ![1717145656660](https://private-user-images.githubusercontent.com/80252815/335509296-a470ea65-05d4-4cec-aff5-f7d726038b81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjY4MDgsIm5iZiI6MTcxNzIyNjUwOCwicGF0aCI6Ii84MDI1MjgxNS8zMzU1MDkyOTYtYTQ3MGVhNjUtMDVkNC00Y2VjLWFmZjUtZjdkNzI2MDM4YjgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA3MjE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNTc2ZmQ0ODFlOTY4Njk0ZDczNTk3NzljMzRlODMzY2FhYzVkZjZhZDE5YTUzZjdmMGUxMzUzYzMxOTgzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8ov-2lLLM25Cl4Q4Jw7-Y8k68p98beyqrth5RsvnL4)

默认第一个模型，没有3.5为啥不删掉呢~
