### ISSUE TITLE
docker更新后所有资料全部不显示

### ISSUE THREAD

**Issue by infoBrainSys** [labring/FastGPT#1651]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
docker V4.7升级 V4.8.1
### 升级前
![image](https://github.com/labring/FastGPT/assets/40877623/e503f729-46cd-47a5-a314-59f0f78a90a9)

### 升级后
![image](https://github.com/labring/FastGPT/assets/40877623/759ef23a-64f2-4aed-9863-7b47d45e6fe3)

**问题描述, 日志截图**
资料都存在
![image](https://github.com/labring/FastGPT/assets/40877623/ecb9e827-67a2-43af-84e8-fdc3f51597b4)

**复现步骤**
### 升级步骤：
- `docker pull ghcr.io/labring/fastgpt:latest`
- `docker compose down && docker compose up -d`
圈起来的为V4.7
![image](https://github.com/labring/FastGPT/assets/40877623/3cfee67e-a978-45fd-be69-2f0dc5e94156)

**预期结果**
结果是：应用、插件、知识库所有信息均不展示
**相关截图**

**Comment by c121914yu** [comment]
看文档，看issue~
