### ISSUE TITLE
升级后所有知识库索引全部失效了

### ISSUE THREAD

**Issue by sunk926** [labring/FastGPT#1656]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
升级最新版本后使用了 初始化脚本和脏数据清理,但是发现所有知识库搜索测试 匹配不到任何内容,必须要每个数据集内容一条一条的手动更新才能正常,数据太多了,一条一条的点击容易点漏掉.有什么方法可以索引整个知识库吗

**Comment by c121914yu** [comment]
目前没遇到。
切换索引模型最容易。

**Comment by sunk926** [comment]
切换成全文检索 可以用,估计是那个向量数据出问题了.

**Comment by sunk926** [comment]
> 目前没遇到。 切换索引模型最容易。

弄错docker-compose-pgvector.yml 文件了,用成docker-compose-milvus.yml 了
之前一直是 pgvector

**Comment by c121914yu** [comment]
> > 目前没遇到。 切换索引模型最容易。
> 
> 弄错docker-compose-pgvector.yml 文件了,用成docker-compose-milvus.yml 了 之前一直是 pgvector

en ,发现doc写错了，我改改

**Comment by sunk926** [comment]
> milvus

那可以继续使用 docker-compose-milvus.yml  吗, milvus 看上去性能更好些.
