### ISSUE TITLE
代码执行无法获取到结果，上一版本还是可以的

### ISSUE THREAD

**Issue by lifei1102** [labring/FastGPT#1657]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本

**问题描述, 日志截图**
如下图简单配置，无法输出代码运行的结果
![image](https://github.com/labring/FastGPT/assets/18553680/2a2fe27a-71e6-42f0-abca-5239ba7cc8e2)

查看详情代码运行节点是正常执行的
![image](https://github.com/labring/FastGPT/assets/18553680/f74bec33-fc26-400f-bdd7-130193b697c9)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
仔细看文档

**Comment by lifei1102** [comment]
> 仔细看文档

翻了文档没找到相关规则修改的描述，大佬可以提示一下吗，是我编排的有问题吗，同样的编排V4.8.2是可以正常运行的呀

**Comment by c121914yu** [comment]
> > 仔细看文档
> 
> 翻了文档没找到相关规则修改的描述，大佬可以提示一下吗，是我编排的有问题吗，同样的编排V4.8.2是可以正常运行的呀

看升级文档，别漏东西

**Comment by lifei1102** [comment]
> > > 仔细看文档
> > 
> > 翻了文档没找到相关规则修改的描述，大佬可以提示一下吗，是我编排的有问题吗，同样的编排V4.8.2是可以正常运行的呀
> 
> 看升级文档，别漏东西

这个执行是在公有云saas版本上运行的效果，应该不涉及到版本升级呀

第一个截图里面可以在地址栏看到saas版本的访问地址的

所以更新后不支持这样去获取代码执行结果了吗，完整响应数据输出我看是可以的，自定义输出就不行

**Comment by c121914yu** [comment]
> > > > 仔细看文档
> > > 
> > > 翻了文档没找到相关规则修改的描述，大佬可以提示一下吗，是我编排的有问题吗，同样的编排V4.8.2是可以正常运行的呀
> > 
> > 看升级文档，别漏东西
> 
> 这个执行是在公有云saas版本上运行的效果，应该不涉及到版本升级呀
> 
> 第一个截图里面可以在地址栏看到saas版本的访问地址的
> 
> 所以更新后不支持这样去获取代码执行结果了吗，完整响应数据输出我看是可以的，自定义输出就不行

噢，😂居然这里看到 saas 问题，迟点看看。

**Comment by lifei1102** [comment]
> > > > > 仔细看文档
> > > > 
> > > > 翻了文档没找到相关规则修改的描述，大佬可以提示一下吗，是我编排的有问题吗，同样的编排V4.8.2是可以正常运行的呀
> > > 
> > > 看升级文档，别漏东西
> > 
> > 这个执行是在公有云saas版本上运行的效果，应该不涉及到版本升级呀
> > 
> > 第一个截图里面可以在地址栏看到saas版本的访问地址的
> > 
> > 所以更新后不支持这样去获取代码执行结果了吗，完整响应数据输出我看是可以的，自定义输出就不行
> 
> 噢，😂居然这里看到 saas 问题，迟点看看。

辛苦辛苦，我是今天本地更新到了4.8.3发现不成功了，然后特意去saas版本试了下先排除一下是不是我们更新造成的问题，结果发现saas版本也不行😂

昨天刚把之前自己用远程请求执行code全换成新增的代码运行组件了，今天更新全都失效了，慌得一批🤣

**Comment by c121914yu** [comment]
> > > > > > 仔细看文档
> > > > > 
> > > > > 翻了文档没找到相关规则修改的描述，大佬可以提示一下吗，是我编排的有问题吗，同样的编排V4.8.2是可以正常运行的呀
> > > > 
> > > > 看升级文档，别漏东西
> > > 
> > > 这个执行是在公有云saas版本上运行的效果，应该不涉及到版本升级呀
> > > 
> > > 第一个截图里面可以在地址栏看到saas版本的访问地址的
> > > 
> > > 所以更新后不支持这样去获取代码执行结果了吗，完整响应数据输出我看是可以的，自定义输出就不行
> > 
> > 噢，😂居然这里看到 saas 问题，迟点看看。
> 
> 辛苦辛苦，我是今天本地更新到了4.8.3发现不成功了，然后特意去saas版本试了下先排除一下是不是我们更新造成的问题，结果发现saas版本也不行😂
> 
> 昨天刚把之前自己用远程请求执行code全换成新增的代码运行组件了，今天更新全都失效了，慌得一批🤣

等 action 好了，😂手机加了行代码
