### ISSUE TITLE
不知到为什么发送图片提问会显示sse error: connect ECONNREFUSED ::1:端口号

### ISSUE THREAD

**Issue by xiye77** [labring/FastGPT#1658]
是什么地方需要配置吗，用的视觉模型，发送文字可以，发送图片会提示上面这个问题。端口号没有屏蔽
dify可以 fastgpt不能

**Comment by swallowMuzi** [comment]
> 是什么地方需要配置吗，用的视觉模型，发送文字可以，发送图片会提示上面这个问题。端口号没有屏蔽 dify可以 fastgpt不能

请问一下你用的是什么视觉模型呀

**Comment by c121914yu** [comment]
看着是不允许内部自身请求，导致转 base64 失败。

**Comment by 13829386012** [comment]
> 是什么地方需要配置吗，用的视觉模型，发送文字可以，发送图片会提示上面这个问题。端口号没有屏蔽 dify可以 fastgpt不能

+1,请问一下你用的是什么视觉模型呀

**Comment by xiye77** [comment]
> > 是什么地方需要配置吗，用的视觉模型，发送文字可以，发送图片会提示上面这个问题。端口号没有屏蔽 dify可以 fastgpt不能
> 
> 请问一下你用的是什么视觉模型呀

Llama3-V 2.5和internvl

**Comment by xiye77** [comment]
> > 是什么地方需要配置吗，用的视觉模型，发送文字可以，发送图片会提示上面这个问题。端口号没有屏蔽 dify可以 fastgpt不能
> 
> +1,请问一下你用的是什么视觉模型呀

可以看看这个MiniCPM-V

**Comment by 13829386012** [comment]
> > > 是什么地方需要配置吗，用的视觉模型，发送文字可以，发送图片会提示上面这个问题。端口号没有屏蔽 dify可以 fastgpt不能
> > 
> > 
> > +1,请问一下你用的是什么视觉模型呀
> 
> 可以看看这个MiniCPM-V

我用的就是这个，但是一发送图片就报503

**Comment by yw-2020** [comment]
我用的3.5-sonnet也报这个错

**Comment by c121914yu** [comment]
CLose 未关联 Issue.
可升级新版，旧版的如果用 localhost docker部署无法使用，需IP 或域名模式，新版已兼容。
