### ISSUE TITLE
配置了one-api后，在知识库管理数据导入的时候尝试使用百度文心千帆，再embeddings的时候异常

### ISSUE THREAD

**Issue by radioend** [labring/FastGPT#166]
配置了one-api后，在知识库管理数据导入的时候尝试使用百度文心千帆，再embeddings的时候异常
如下：
esponse:{"error":{"message":"embeddings max batch size is 16, and can not be 0","type":"baidu_error","param":"","code":336003}}

**Comment by radioend** [comment]
one-api的bug， 他们已经修复了。

**Comment by radioend** [comment]
> 4.2还有这个问题吗

one-api的bug， 他们已经修复了。

**Comment by c121914yu** [comment]
好的
