### ISSUE TITLE
docker-compose快速部署mysql容器无法启动解决办法

### ISSUE THREAD

**Issue by YaJee666** [labring/FastGPT#1662]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
docker-compose.yaml版本号为3.3
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
WSL Ubuntu22.04.3 docker compose快速部署部分启动容器环节遇到mysql无法启动的情况，错误如下所示
![image](https://github.com/labring/FastGPT/assets/55324668/393dd0cb-bc1f-46fb-b9c5-26e4adec9549)
**已验证解决办法**
可以通过修改docker-compose.yaml文件中mysql版本为8.0.37解决
![image](https://github.com/labring/FastGPT/assets/55324668/e6ffe2a3-1833-4bc6-9cca-4b07f0dd0dcb)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
好的，非常感谢。
如果可以的话，可以给文档提个PR，[docker部署常见问题](https://github.com/labring/FastGPT/blob/main/docSite/content/zh-cn/docs/development/docker.md)
