### ISSUE TITLE
更推荐哪种数据库

### ISSUE THREAD

**Issue by mpuazxc2** [labring/FastGPT#1663]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我看你们现在有milvus/pgvector/zilliz
3种数据库版本了，更加推荐哪种数据库啊，实测哪个效率最高，未来3种数据库版本都会同时维护吗

**复现步骤**

**预期结果**

**相关截图**

**Comment by sunk926** [comment]
帮助文档里面不是有 milvus/pgvector/zilliz 介绍对比么

**Comment by mpuazxc2** [comment]
> 帮助文档里面不是有 milvus/pgvector/zilliz 介绍对比么

那未来milvus/pgvector/zilliz都会更新支持吗，还是会注重更新某个数据库

**Comment by c121914yu** [comment]
> > 帮助文档里面不是有 milvus/pgvector/zilliz 介绍对比么
> 
> 那未来milvus/pgvector/zilliz都会更新支持吗，还是会注重更新某个数据库

都一样维护
