### ISSUE TITLE
指定回复，回复json

### ISSUE THREAD

**Issue by yp94** [labring/FastGPT#1664]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
指定回复，回复json
**应用场景**
多个ai对话的结果串联在一起返回，现在是一长串字符串，我通过特殊字符分隔，希望可以返回json
**相关示例**

**Comment by yp94** [comment]
或者支持把代码运行的结果直接返回也行

**Comment by c121914yu** [comment]
> 或者支持把代码运行的结果直接返回也行

不是有代码节点么

**Comment by yp94** [comment]
> > 或者支持把代码运行的结果直接返回也行
> 
> 不是有代码节点么

<img width="1461" alt="image" src="https://github.com/labring/FastGPT/assets/28262260/f67a1b26-8734-4b0e-950a-d77f361f48f4">
代码节点的结果没返回呀

**Comment by c121914yu** [comment]
> > > 或者支持把代码运行的结果直接返回也行
> > 
> > 不是有代码节点么
> 
> <img width="1461" alt="image" src="https://github.com/labring/FastGPT/assets/28262260/f67a1b26-8734-4b0e-950a-d77f361f48f4">
> 代码节点的结果没返回呀

你不输出怎么返回

**Comment by c121914yu** [comment]
> > > > > 或者支持把代码运行的结果直接返回也行
> > > > 
> > > > 
> > > > 不是有代码节点么
> > > 
> > > 
> > > <img alt="image" width="1461" src="https://private-user-images.githubusercontent.com/28262260/335910803-f67a1b26-8734-4b0e-950a-d77f361f48f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNzY5NjYsIm5iZiI6MTcxNzM3NjY2NiwicGF0aCI6Ii8yODI2MjI2MC8zMzU5MTA4MDMtZjY3YTFiMjYtODczNC00YjBlLTk1MGEtZDc3ZjM2MWY0OGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAxMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNzRjNGVjMDcyYzk2YmVlZWEyMWQ5OTRjNzM1MmMzYTBmMjYyYTA1Y2NiZDZkZjZjMjZmYzVlYWNiNzkzMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_A186I_MTDt67JqLoCuEc1SaG5fmxWmSTAEYPQNC4M">
> > > 代码节点的结果没返回呀
> > 
> > 你不输出怎么返回
> 
> 我输出了不就被强制转成字符串了

你看到的不都是字符串？

**Comment by yp94** [comment]
> > > > > > 或者支持把代码运行的结果直接返回也行
> > > > > 
> > > > > 
> > > > > 不是有代码节点么
> > > > 
> > > > 
> > > > <img alt="image" width="1461" src="https://private-user-images.githubusercontent.com/28262260/335910803-f67a1b26-8734-4b0e-950a-d77f361f48f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNzY5NjYsIm5iZiI6MTcxNzM3NjY2NiwicGF0aCI6Ii8yODI2MjI2MC8zMzU5MTA4MDMtZjY3YTFiMjYtODczNC00YjBlLTk1MGEtZDc3ZjM2MWY0OGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAxMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNzRjNGVjMDcyYzk2YmVlZWEyMWQ5OTRjNzM1MmMzYTBmMjYyYTA1Y2NiZDZkZjZjMjZmYzVlYWNiNzkzMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_A186I_MTDt67JqLoCuEc1SaG5fmxWmSTAEYPQNC4M">
> > > > 代码节点的结果没返回呀
> > > 
> > > 
> > > 你不输出怎么返回
> > 
> > 
> > 我输出了不就被强制转成字符串了
> 
> 不是字符串怎么打印

好吧，我自己stringify再输出也行
