### ISSUE TITLE
kimi 不能回复

### ISSUE THREAD

**Issue by kynow2** [labring/FastGPT#1665]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

我通过“渠道”功能增加了moonshotAI，在密钥处输入了我自己的kimi一个sk开头的key，这个key我自己调用是没问题的。但在fastgpt上却不能用，现在在测试时可以，但调用知识库运用时有问题，可能是base—url没有设置，请问是否是这个问题，另外在哪设置？

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/102887016/0436c5df-cebc-4cab-acca-9ba24794a349)

![image](https://github.com/labring/FastGPT/assets/102887016/2b0a2315-5784-40a1-a345-f6a18dc42352)

**Comment by c121914yu** [comment]
建议先看看 oneapi 教程，搞懂几个名词的关系
