### ISSUE TITLE
希望知识库查询的内容能放到system prompt里

### ISSUE THREAD

**Issue by Zhenyi-Wang** [labring/FastGPT#1666]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
希望知识库查询的结果可以放到system prompot里，或者至少有一个选项可以选择。

目前是放在最后一个user的message里，通过参数把用户的问题拼接进来，造成知识和问题的混合。

**应用场景**
我的场景中，用户可以用多种语言问答，而 ChatGPT 原生能够跟随用户语言（就是用什么语言提问，就用什么语言回复），但是在插入知识库之后，即使用户用英文提问，AI 也有很大概率中文回复。

以前用 LangChain-ChatChat 时遇到过相同的问题，后来移到 system prompt 里就解决了，效果应该是没问题的。

**相关示例**
无

**Comment by lijiajun1997** [comment]
https://github.com/labring/FastGPT/discussions/1121?sort=old

**Comment by bincooo** [comment]
我为了能让在指定位置插入上下文自己搞了个<@-n>标签解析

**Comment by ReverseSystem001** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 features
> * [x]  我已确认我已升级到最新版本
> * [x]  我已完整查看过项目 README，已确定现有版本无法满足需求
> * [x]  我理解并愿意跟进此 features，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**
> 
> **功能描述** 希望知识库查询的结果可以放到system prompot里，或者至少有一个选项可以选择。
> 
> 目前是放在最后一个user的message里，通过参数把用户的问题拼接进来，造成知识和问题的混合。
> 
> **应用场景** 我的场景中，用户可以用多种语言问答，而 ChatGPT 原生能够跟随用户语言（就是用什么语言提问，就用什么语言回复），但是在插入知识库之后，即使用户用英文提问，AI 也有很大概率中文回复。
> 
> 以前用 LangChain-ChatChat 时遇到过相同的问题，后来移到 system prompt 里就解决了，效果应该是没问题的。
> 
> **相关示例** 无

我使用langchain-chatchat 的知识库，一致报 “未检索到，此答案是大模型回复”，明明知识库已经创建了，上传个pdf，构建一个知识库，然后对话的时候选择这个知识库，但没啥用，你的可以用？

**Comment by Zhenyi-Wang** [comment]
> 我使用langchain-chatchat 的知识库，一致报 “未检索到，此答案是大模型回复”，明明知识库已经创建了，上传个pdf，构建一个知识库，然后对话的时候选择这个知识库，但没啥用，你的可以用？

其他配置没错的话，可能是问题的匹配度太低，也可能是pdf压根没导入进去。这是langchain-chatchat的问题了，到相应项目里提issue吧，或者加他们的微信群。

**Comment by ReverseSystem001** [comment]
嗯，你用的是可以匹配到的是吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月4日(周二) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 希望知识库查询的内容能放到system prompt里 (Issue #1666)




  
我使用langchain-chatchat 的知识库，一致报 “未检索到，此答案是大模型回复”，明明知识库已经创建了，上传个pdf，构建一个知识库，然后对话的时候选择这个知识库，但没啥用，你的可以用？
  
其他配置没错的话，可能是问题的匹配度太低，也可能是pdf压根没导入进去。这是langchain-chatchat的问题了，到相应项目里提issue吧，或者加他们的微信群。

**Comment by Zhenyi-Wang** [comment]
对






-------- 原始邮件 --------
发件人： reverseSystem ***@***.***>
日期： 2024年6月4日周二 傍晚5:06
收件人： labring/FastGPT ***@***.***>
抄送： Zhenyi-Wang ***@***.***>, Author ***@***.***>
主 题： Re: [labring/FastGPT] 希望知识库查询的内容能放到system prompt里 (Issue #1666)

嗯，你用的是可以匹配到的是吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月4日(周二) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 希望知识库查询的内容能放到system prompt里 (Issue #1666)





我使用langchain-chatchat 的知识库，一致报 “未检索到，此答案是大模型回复”，明明知识库已经创建了，上传个pdf，构建一个知识库，然后对话的时候选择这个知识库，但没啥用，你的可以用？

其他配置没错的话，可能是问题的匹配度太低，也可能是pdf压根没导入进去。这是langchain-chatchat的问题了，到相应项目里提issue吧，或者加他们的微信群。

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

―

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/2733
