### ISSUE TITLE
用kimi，如果引用上限设置超过2000，就会报错

### ISSUE THREAD

**Issue by kynow2** [labring/FastGPT#1667]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7

用kimi，如果引用上限设置超过2000，就会报错。低于就可以输出。
而且不能设置混合搜索，也会报错。
想问下这个能够提高？谢谢

**Comment by c121914yu** [comment]
模型问题，api 不叫 kimi，叫 moonshot，8k 32k 128k 都能正常用，不知道你用的是啥

**Comment by kynow2** [comment]
是我自己用oneapi连接的moonshot，并在设置文档中，加载了对应的“sk-***”，问题是moonshot其实能接收至少上万的token，但在fastgpt的参数设置中，如果我将引用参数调到2000以上，会直接报错，2000以下有的时候没问题，可以正常解析知识库，有的时候也会出错。
似乎是如果输入的提示词，会要求调用更多的知识库内容，超过一定额度，就会报错。但2000以上，是直接报错，没有悬念。
![image](https://github.com/labring/FastGPT/assets/102887016/6a49f98a-62ff-4297-8017-1e3d90b99f37)

**Comment by c121914yu** [comment]
> 是我自己用oneapi连接的moonshot，并在设置文档中，加载了对应的“sk-***”，问题是moonshot其实能接收至少上万的token，但在fastgpt的参数设置中，如果我将引用参数调到2000以上，会直接报错，2000以下有的时候没问题，可以正常解析知识库，有的时候也会出错。
> 似乎是如果输入的提示词，会要求调用更多的知识库内容，超过一定额度，就会报错。但2000以上，是直接报错，没有悬念。
> ![image](https://github.com/labring/FastGPT/assets/102887016/6a49f98a-62ff-4297-8017-1e3d90b99f37)
> 

命中风控了？

**Comment by kynow2** [comment]
因为原本我调试了一天都是在oneapi可以测试通过，但到fastgpt就失败。
然后偶然间，我看到之前issue说谁max_token设置超过2000，所以失败，一看果然是这个原因。但也不稳定。
其实我是想用moonshot的大上下文文本的能力，增加在知识库中一次遍历的内容，使得输出的内容更准确，但现在这样，就无法实现了

**Comment by kynow2** [comment]
> > 是我自己用oneapi连接的moonshot，并在设置文档中，加载了对应的“sk-***”，问题是moonshot其实能接收至少上万的token，但在fastgpt的参数设置中，如果我将引用参数调到2000以上，会直接报错，2000以下有的时候没问题，可以正常解析知识库，有的时候也会出错。
> > 似乎是如果输入的提示词，会要求调用更多的知识库内容，超过一定额度，就会报错。但2000以上，是直接报错，没有悬念。
> > ![image](https://private-user-images.githubusercontent.com/102887016/336262812-6a49f98a-62ff-4297-8017-1e3d90b99f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjQwMjIsIm5iZiI6MTcxNzQ2MzcyMiwicGF0aCI6Ii8xMDI4ODcwMTYvMzM2MjYyODEyLTZhNDlmOThhLTYyZmYtNDI5Ny04MDE3LTFlM2Q5MGI5OWYzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwMTE1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWViZDYyZTlkNjBjZmZkYjJlZjYwNzIwNmI5ZjE3NTU5YWJjNjMxMzIyMTQ4YmU4ZTA2OWZjM2QzYWY2NDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CQGTLW_1rs3_UOGZKz9CsGHf18rcNoN6ygjQXjXI03Y)
> 
> 命中风控了？

应该不是违禁词类似的，都是非常简单的内容总结。比如我说“总结3条”，他能过；如果改成“总结10条”，他就报response的错误了

**Comment by c121914yu** [comment]
> > > 是我自己用oneapi连接的moonshot，并在设置文档中，加载了对应的“sk-***”，问题是moonshot其实能接收至少上万的token，但在fastgpt的参数设置中，如果我将引用参数调到2000以上，会直接报错，2000以下有的时候没问题，可以正常解析知识库，有的时候也会出错。
> > > 似乎是如果输入的提示词，会要求调用更多的知识库内容，超过一定额度，就会报错。但2000以上，是直接报错，没有悬念。
> > > ![image](https://private-user-images.githubusercontent.com/102887016/336262812-6a49f98a-62ff-4297-8017-1e3d90b99f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjQwMjIsIm5iZiI6MTcxNzQ2MzcyMiwicGF0aCI6Ii8xMDI4ODcwMTYvMzM2MjYyODEyLTZhNDlmOThhLTYyZmYtNDI5Ny04MDE3LTFlM2Q5MGI5OWYzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwMTE1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWViZDYyZTlkNjBjZmZkYjJlZjYwNzIwNmI5ZjE3NTU5YWJjNjMxMzIyMTQ4YmU4ZTA2OWZjM2QzYWY2NDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CQGTLW_1rs3_UOGZKz9CsGHf18rcNoN6ygjQXjXI03Y)
> > 
> > 命中风控了？
> 
> 应该不是违禁词类似的，都是非常简单的内容总结。比如我说“总结3条”，他能过；如果改成“总结10条”，他就报response的错误了

你用非 stream 模式测测会有结果（debug 模式），oneapi  stream 模式无法捕获这些错误。
