### ISSUE TITLE
http模块有使用例子啊

### ISSUE THREAD

**Issue by mpuazxc2** [labring/FastGPT#167]
当前分组负载已饱和，请稍后再试，或升级账户以提升服务质量。
这个是是系统限制，还是KEY不行啊
--------
还有
http模块有使用例子啊
是取json某个字段返回还是全部返回，参数最终链接到哪个类型啊

**Comment by c121914yu** [comment]
还没写文档。
key问题，

**Comment by c121914yu** [comment]
http模块输入输出字段是自己填的，没填的字段会忽略

**Comment by mpuazxc2** [comment]
1.出入参数是json还是啥东西啊
2.最终出参内容->因该链接到“指定回复”还是其他什么模块里才能显示啊
3.啥类型可以让他显示php的全部内容啊，不需要取参数

**Comment by c121914yu** [comment]
json。指定回复可以输出，也可以连到其他内容，。

**Comment by mpuazxc2** [comment]
不知道哪里出问题了
---
http地址:http://api.m.taobao.com/rest/h5ApiUpdate.do?&api=test
出参参数：
字段类型：字符串
字段名:出参1
字段key:api
---
出参1->链接到->“指定回复”模块的“回复的内容”选项
---
理论上调用应该返回“test”
实际上返回 空
不知道哪里出问题了

**Comment by superlbr** [comment]
如何判定是来自fastgpt的请求，而不是别人拿到了接口。。。

**Comment by c121914yu** [comment]
文档已经补充。

**Comment by c121914yu** [comment]
> 如何判定是来自fastgpt的请求，而不是别人拿到了接口。。。

1. 不要暴露地址。
2. 通过query增加凭证
3. 验证ip

**Comment by superlbr** [comment]
ip地址留下呗

**Comment by c121914yu** [comment]
> ip地址留下呗

34.87.110.152
34.87.44.74
35.247.163.68
34.142.157.52
34.87.20.189
34.87.180.104
34.87.152.33
34.87.79.202
34.87.51.146
34.87.102.86
34.143.240.160
35.197.149.75
35.247.161.35
35.240.227.100
34.124.237.188
后面可能还会加机子

**Comment by c121914yu** [comment]
> ip地址留下呗

你应该是自己调ip查询接口去更新。。不过95%情况直接用凭证就好了
