### ISSUE TITLE
docker打包部署会报failed to compute cache key: failed to calculate checksum of ref bd3c0c78-c861-41d1-8681-b0934d365568::va3mexylg14xxrm6ixsihipx9: "/.npmrc": not found

### ISSUE THREAD

**Issue by xiaomingcimy** [labring/FastGPT#1670]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
<img width="733" alt="image" src="https://github.com/labring/FastGPT/assets/82130409/489ad9b7-0ff3-45dc-88cf-9c67ee915d04">
![image](https://github.com/labring/FastGPT/assets/82130409/e623826b-e6ad-47dd-8390-a1e907176b2d)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
不是官方代码，或者合并合丢了

**Comment by xiaomingcimy** [comment]
> 不是官方代码，或者合并合丢了

自己建仓库不能打包吗，必须fork出来的仓库才能打包吗

**Comment by c121914yu** [comment]
> > 不是官方代码，或者合并合丢了
> 
> 自己建仓库不能打包吗，必须fork出来的仓库才能打包吗

都行。别漏了代码就行
