### ISSUE TITLE
无法语音输入和输出

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#1672]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: FastGPT:4.7.1

**问题描述, 日志截图**

前提：已在oenAPI接入openAI的模型和tts-1和whisper-1 并能成功测试渠道
![image](https://github.com/labring/FastGPT/assets/106878712/3a594952-81b0-47c8-9b7c-44f94e46fbcd)
![image](https://github.com/labring/FastGPT/assets/106878712/098ea53b-bafc-48ad-8176-f1e8e642066d)

1. 无法开启语音输入，dian'ji点击无反应
![image](https://github.com/labring/FastGPT/assets/106878712/cc82e2bc-dd48-4978-b562-5fefb4c8cdde)
2. 语音播报无法试听
![image](https://github.com/labring/FastGPT/assets/106878712/e063ffcb-f672-41a9-b769-2008121e8b06)

**Comment by heart18z** [comment]
注：是内网环境
oneAPI和FastGPT分别在两台服务器
oneAPI内网服务器可访外网

请问是否调用该功能一定需要HTTPS的SLL证书，配置域名才可使用

**Comment by c121914yu** [comment]
> 注：是内网环境
> oneAPI和FastGPT分别在两台服务器
> oneAPI内网服务器可访外网
> 
> 请问是否调用该功能一定需要HTTPS的SLL证书，配置域名才可使用

是的，浏览器要求必须 ssl 证书

**Comment by sdytzjp** [comment]
https在哪里配置
