### ISSUE TITLE
应用分享删除链接，每次都是删除最后一个！

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#1673]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x ] 公有云版本
- [x] 私有部署版本, 具体版本号: 似乎每个版本都有这个问题

**问题描述, 日志截图**
官方fastgpt.in和本地部署的fastGPT都会出现这个情况
应用管理创建分享链接，然后选择指定分享的链接删除，每次都会默认删除最后一个
![image](https://github.com/labring/FastGPT/assets/106878712/ce5ec715-75cb-49d5-886b-b0d8bfff612c)
![image](https://github.com/labring/FastGPT/assets/106878712/9342424e-7d14-4b37-be8f-c8510fa58436)
![image](https://github.com/labring/FastGPT/assets/106878712/43f8359f-529b-4bea-bc77-61f2f6969bc5)
![image](https://github.com/labring/FastGPT/assets/106878712/b11cf78c-99d0-42de-b541-70f3f510ac80)

**Comment by Essence9999** [comment]
确实存在这个问题，刚我都不小心删除了一个发布链接~
还有这个链接复制键，好像没用，点了复制，却复制不了链接
![image](https://github.com/labring/FastGPT/assets/66725845/49d76aaf-0387-4af7-a55f-048e9d1c7566)

**Comment by c121914yu** [comment]
> 确实存在这个问题，刚我都不小心删除了一个发布链接~
> 还有这个链接复制键，好像没用，点了复制，却复制不了链接
> ![image](https://github.com/labring/FastGPT/assets/66725845/49d76aaf-0387-4af7-a55f-048e9d1c7566)
> 

https 才有用
