### ISSUE TITLE
升级后mongo日志Waiting for MongoDB to start...，应用都消失了

### ISSUE THREAD

**Issue by Code-Bai** [labring/FastGPT#1674]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
升级后mongo日志Waiting for MongoDB to start...，应用都消失了
![image](https://github.com/labring/FastGPT/assets/62536222/f91c596e-e2bc-4ad9-8617-7a0f882c5f42)
![image](https://github.com/labring/FastGPT/assets/62536222/3ba12a00-f394-4207-bd86-0d9bbd3e53bb)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没执行初始化？

**Comment by Code-Bai** [comment]
从4.7版本跨版本升级至4.8.3，发现有问题后，回退至4.7，并执行初始化命名，返回200。
```
curl --location --request POST '{host}:13000/api/admin/initv47' \
--header 'rootkey: root_key' \
--header 'Content-Type: application/json'
```
docker logs mongo 日志如下
![image](https://github.com/labring/FastGPT/assets/62536222/e4d47b77-d721-49bb-96d8-b6074632fb3f)

**Comment by c121914yu** [comment]
> 从4.7版本跨版本升级至4.8.3，发现有问题后，回退至4.7，并执行初始化命名，返回200。
> ```
> curl --location --request POST '{host}:13000/api/admin/initv47' \
> --header 'rootkey: root_key' \
> --header 'Content-Type: application/json'
> ```
> docker logs mongo 日志如下
> ![image](https://github.com/labring/FastGPT/assets/62536222/e4d47b77-d721-49bb-96d8-b6074632fb3f)
> 

回滚得回滚数据库，回滚初始化没用的。

**Comment by Code-Bai** [comment]
请问一下如何进行数据库回滚呢？有没有操作手册呢

**Comment by dandanjunzi** [comment]
我是从v4.8顺序升级到v4.8.1，升级后也是出现之前创建的所有应用、知识库不见了。执行v4.8.1的初始化命令后，恢复正常。curl --location --request POST 'https://{{host}}/api/admin/initv481' \
--header 'rootkey: {{rootkey}}' \
--header 'Content-Type: application/json'。或许你可以顺序升级，但是现在不清楚是否可行。

**Comment by c121914yu** [comment]
> 请问一下如何进行数据库回滚呢？有没有操作手册呢

从数据库备份导出，如果没有，则无法回滚。
