### ISSUE TITLE
请问【结果反馈中的关闭反馈】在哪里可以关掉或隐藏掉

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1676]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
想要关掉或隐藏结果反馈中的”关闭反馈“按钮
**应用场景**
用户在提交反馈后，后台从对话日志查看反馈内容，不小心点击了”关闭反馈“，导致反馈内容消失；而点击右上角”X“，反馈内容依然保持存在。
**相关示例**
![image](https://github.com/labring/FastGPT/assets/66725845/2c59d374-cf11-4f98-82b1-b041c03d96ba)

请问，相应的代码文件是哪个？想注释或隐藏掉

**Comment by c121914yu** [comment]
可以根据文本进行全文搜索，定位到对应组件。
