### ISSUE TITLE
知识库导出遇到下载失败问题_403

### ISSUE THREAD

**Issue by bdugsj** [labring/FastGPT#1677]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/107917926/cd2ef01a-8350-4957-ad6c-40afa8bbc6e3)
![image](https://github.com/labring/FastGPT/assets/107917926/6c0a65cd-b3df-4f4e-a234-cea4dd3e3fc8)

**Comment by c121914yu** [comment]
4.7 需要用 https

**Comment by stephenlzc** [comment]
> 4.7 需要用 https

在本地部署，怎么使用https?

@c121914yu
