### ISSUE TITLE
希望可以正确在fastgpt前端渲染数学公式和化学式

### ISSUE THREAD

**Issue by wongdi** [labring/FastGPT#1680]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

在fastgpt前端页面增加对应的支持，方便正确解析和渲染llm返回的数学公式和化学式。
 

**应用场景**

相关知识解答。

**相关示例**

**Comment by c121914yu** [comment]
一直支持

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/2df505e6-6871-4731-a32f-a8ad2b7e90c9)
在提示词里加上：对于数学公式、表达式前后需要加上“$$”
![image](https://github.com/labring/FastGPT/assets/156336589/0e82c365-f62d-4791-8b24-beeefcea96f2)

**Comment by wongdi** [comment]
> ![image](https://private-user-images.githubusercontent.com/156336589/336277849-2df505e6-6871-4731-a32f-a8ad2b7e90c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjY4NjMsIm5iZiI6MTcxNzQ2NjU2MywicGF0aCI6Ii8xNTYzMzY1ODkvMzM2Mjc3ODQ5LTJkZjUwNWU2LTY4NzEtNDczMS1hMzJmLWE4YWQyYjdlOTBjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwMjAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTdhOTk5MjYxZGE3MDQ3OTVjMDBmYmQ4MTY0YTE1YmNkOTYzYjE1MTVhNGRiY2Y0NjUxY2IyNzNmMDAyMjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w33f1zPUK4vISb_zBBcRwAXn6LUKb5Ztw88cY9vgNpY) 在提示词里加上：对于数学公式、表达式前后需要加上“$$” ![image](https://private-user-images.githubusercontent.com/156336589/336278006-0e82c365-f62d-4791-8b24-beeefcea96f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjY4NjMsIm5iZiI6MTcxNzQ2NjU2MywicGF0aCI6Ii8xNTYzMzY1ODkvMzM2Mjc4MDA2LTBlODJjMzY1LWY2MmQtNDc5MS04YjI0LWJlZWVmY2VhOTZmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwMjAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTczYTdiYjJmZjlhZDBiZmU2Zjc3MzQwZjQ5YTAyOGIzMTAwZmFlNDgyNGI5NGEwOTQ1NDIzZTAzYmIyYzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IgX3ZqBQs9AgXF50LO5tQBwVfV2sKZeVHqreQ6K8r7k)

我不知道我这样操作是否正确，但行为并不固定。
![0](https://github.com/labring/FastGPT/assets/61398882/494b806a-e0a0-49f9-a40f-5a9effc786bc)

**Comment by lijiajun1997** [comment]
> > 在提示词里加上：对于数学公式、表达式前后需要加上“$$” !
> 
> 我不知道我这样操作是否正确，但行为并不固定。 
行为不固定是模型本身对提示词的注意力和理解力问题，我用gpt4是没问题的。
可以多试一些提示词，让LLM知道哪些情况需要加，以及给出举例，这样效果会好点。

**Comment by wongdi** [comment]
> > > 在提示词里加上：对于数学公式、表达式前后需要加上“$$” !
> > 
> > 
> > 我不知道我这样操作是否正确，但行为并不固定。
> > 行为不固定是模型本身对提示词的注意力和理解力问题，我用gpt4是没问题的。
> > 可以多试一些提示词，让LLM知道哪些情况需要加，以及给出举例，这样效果会好点。

数学公式我发现问题在哪里了，少复制了个叹号，现在行为正常了，还有请问这种增加“$$”!是有什么书写规范吗，放不方便提供下相关的具体内容，我也研究一下化学式相关的提示词

**Comment by wongdi** [comment]
> > > 在提示词里加上：对于数学公式、表达式前后需要加上“$$” !
> > 
> > 
> > 我不知道我这样操作是否正确，但行为并不固定。
> > 行为不固定是模型本身对提示词的注意力和理解力问题，我用gpt4是没问题的。
> > 可以多试一些提示词，让LLM知道哪些情况需要加，以及给出举例，这样效果会好点。

我去，你知道这玩意问题出在哪吗，出在知识检索上，问题分类后不检索，直接进llm，一点问题没有。化学公式都正常了。

**Comment by lijiajun1997** [comment]
> > > > 在提示词里加上：对于数学公式、表达式前后需要加上“$$” !
> > > 
> > > 
> > > 我不知道我这样操作是否正确，但行为并不固定。
> > > 行为不固定是模型本身对提示词的注意力和理解力问题，我用gpt4是没问题的。
> > > 可以多试一些提示词，让LLM知道哪些情况需要加，以及给出举例，这样效果会好点。
> 
> 我去，你知道这玩意问题出在哪吗，出在知识检索上，问题分类后不检索，直接进llm，一点问题没有。化学公式都正常了。

知识库的内容太多，会把提示词稀释，如果模型注意力不够会忽略提示词
