### ISSUE TITLE
记录下知识库中没有相关知识的用户提问

### ISSUE THREAD

**Issue by Timerunning** [labring/FastGPT#1683]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
目前，当用户提出的问题在知识库中没有相关知识的时候，通常在提示词中设定拒绝回答。如果想要将这种无法回答的问题全部记录下来。然后人工的去编写这些问题的答案，并将问答手动插入到知识库中，以完善知识库。目前是否可以基于当前V4.8.3版本的能力实现这个功能？

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/a3ebaa97-fb78-435c-95ea-38cbb22157ea)
这样在日志里会看到哪些问题被标记了，用户看不到

**Comment by Timerunning** [comment]
日志是指什么日志？在哪里查看

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/41b9be3e-2a6f-41e5-b23d-88d2077df3d5)

**Comment by c121914yu** [comment]
> 好的，感谢您的解答。这个对话日志是存储在哪个文件里的？我是否可以通过扫描该日志文件来提取出被标记的问题。

mongo表里，chat和chatitems
