### ISSUE TITLE
提供接受json格式的API请求作为输入并返回JSON

### ISSUE THREAD

**Issue by travisgu** [labring/FastGPT#1684]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
为了方便和系统的集成，能否提供一个开始组件，接受一个json的数据作为输入，而不是对话的方式开始，同时将返回结果以JSON的格式返回给调用方（仅包括需要的内容）。目前提供的completion API是对话的场景，还不太适合作为系统间的调用。

**应用场景**
利用RAG功能做一个推荐的功能，以非对话的方式接受一个查询调用输入，返回最接近的三个结果。

**相关示例**
例如：
输入是：
{
"param1":"查询属性1",
"param1":"查询属性1"
}
返回：
{
"recommended items":["item id1","item id2","item id3"]
}

**Comment by yongxingMa** [comment]
+1

**Comment by yongxingMa** [comment]
在请求参数里添加    
"stream": false

**Comment by c121914yu** [comment]
4.8.7 支持插件独立运行，非对话模式。
