### ISSUE TITLE
[强烈建议] “指定回复”模块改进

### ISSUE THREAD

**Issue by B3nDan** [labring/FastGPT#169]
1.为什么
因为我现在有个场景
比如我最后的输出会是 2 个指定内容 + 1个ai回复
这两个指定内容的顺序不好确定

2.怎么做
很简单，给指定回复增加一个“回复结束”的bool输出口
这样，一个指定回复结束可以激活下一个指定回复的触发器

3.配图
现在的指定回复
![Screenshot_20230813_013352](https://github.com/labring/FastGPT/assets/129975925/85a26a06-a8a2-4105-a958-f32c95eb5220)

**Comment by c121914yu** [comment]
是个不错的改进

**Comment by c121914yu** [comment]
但是有个问题，为什么不写在一起？

**Comment by B3nDan** [comment]
> 但是有个问题，为什么不写在一起？

我原本打算补充说明的，忘了

是这样的
这两个 指定回复 的 内容
我是在前面根据 问题分类、ai回复
会在不同问题下有不同结果
所以这俩内容是会变动的

如果说写在一起
除非指定内容的传入参数支持自定义多个
然后每个参数给一个key关键词
在回复里根据规则 进行拼接

直接加个bool输出更容易做
如果您能考虑多参数输入的指定回复
那自由度也会更高一些

**Comment by c121914yu** [comment]
4.1已增加
