### ISSUE TITLE
奇怪的BUG，跳转一下页面原有的一些聊天内容会从聊天页面消失

### ISSUE THREAD

**Issue by mwnu** [labring/FastGPT#1694]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**

而是是丢失，找不回来了了

**相关截图**
![PixPin_2024-06-05_06-38-42](https://github.com/labring/FastGPT/assets/45463732/a3e5c031-fff1-48e9-9472-81da9762418c)

转发到http上发现，AI的历史记录都丢失了，v4.8.3 多了很多奇奇怪怪的BUG

![image](https://github.com/labring/FastGPT/assets/45463732/e1af5cc9-882a-4aee-9d8c-2b3b42c4784b)

目前只在高级编排的应用中发现

**Comment by c121914yu** [comment]
没看懂

**Comment by mwnu** [comment]
> 没看懂



api上的历史记录丢失是我代码的问题，但是fastgpt客户端上记录丢失就不知道是怎么回事了，注意看机器人回复的内容丢失了，这里原来是有内容的，刷新一下页面就没有了：
![image](https://github.com/labring/FastGPT/assets/45463732/6c76662c-7464-4e72-8f0c-230fa5131cc7)

**Comment by mwnu** [comment]
> 没看懂

我明白了，插件要有输出，如果调用应用的话会产生新的历史记录，需要更新到当前应用的全局变量里面，要不然重新进到页面AI的历史回复就丢失了。
之前的版本没有这样的问题，这个逻辑有点迷，因为只有AI的历史回复丢失了，自己提记录还在，而且调用别的应用，别的应用生成的内容就直接在当前应用窗口输出了，都想不到还需要手动把别的应用的历史记录再更新到当前应用会话上来。

**Comment by mwnu** [comment]
另外还发现一个在调试中的BUG，在调试中跳出，但是非调试运行的时候又正常
<img width="1267" alt="PixPin_2024-06-06_02-16-17" src="https://github.com/labring/FastGPT/assets/45463732/bd0d4ba1-d3af-429b-8ee7-82a9247231e0">
<img width="942" alt="PixPin_2024-06-06_02-17-15" src="https://github.com/labring/FastGPT/assets/45463732/5f980009-32df-40a4-91db-56e375b4ac2b">

**Comment by c121914yu** [comment]
先 close，新版本中应该没这个问题了。
