### ISSUE TITLE
指定回复提供链接调用的其他高级编排的功能

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#1695]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
为了更好地引导对话，需要指定回复内容包含链接，用户能通过直接点回复的链接返回一个参数调用后续逻辑功能

**应用场景**
对话引导

**相关示例**
比如回答问题，回答完后显示“1”表示满意并关闭咨询，“2”联系人工

**Comment by lijiajun1997** [comment]
关闭貌似不行，联系人工可以用markdown跳转链接
![image](https://github.com/labring/FastGPT/assets/156336589/d38e0248-b2a7-4adc-a82a-cea3b2bdc124)

**Comment by ppkitty** [comment]
谢谢，我主要是想通过回复，直接点链接调用其他模块

**Comment by lijiajun1997** [comment]
> 谢谢，我主要是想通过回复，直接点链接调用其他模块

你要调用什么模块

**Comment by ppkitty** [comment]
其他app或者插件都可以

**Comment by lijiajun1997** [comment]
> 其他app或者插件都可以

把其他app作为免密链接跳转过去

**Comment by ppkitty** [comment]
可以只显示我想显示的文字，而不是URL吗？比如：上面那个baidu的，不想显示www.baidu.com这个URL，而是只显示[点击这里访问百度]，点这段文字跳转到背后设置的链接

**Comment by Ewanjune** [comment]
我现在也遇到这个问题，请问有什么好办法解决吗
