### ISSUE TITLE
开源版本支持简单修改后端代码吗 

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1696]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
请问下后端代码是哪个 支持本地开发吗
**复现步骤**

**预期结果**

**相关截图**

**Comment by heart18z** [comment]
可以，主要看个人，代码都放出来了

**Comment by lxb0425** [comment]
后端代码没找到啊 操作数据库那一块的

**Comment by Purseccc** [comment]
同问

**Comment by c121914yu** [comment]
没找到是你没学习过 nextjs，，本地开发文档有说明结构。
