### ISSUE TITLE
Invalid image URL. The URL must be a valid HTTP or HTTPS URL, or a data URL with base64 encoding.

### ISSUE THREAD

**Issue by zpcr7** [labring/FastGPT#1697]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: V4.8

**问题描述, 日志截图**
![Uploading image.png…]()
![image](https://github.com/labring/FastGPT/assets/171773052/1b135e80-87cb-4306-85dd-f828537cb729)
本地部署的FastGpt，采用的模型是微软的GPT-4o，在对话中可以进行图片分析；在发布应通过api进行图片分析时，一直报Invalid image URL. The URL must be a valid HTTP or HTTPS URL, or a data URL with base64 encoding.这个错误，在服务器上用crul格式进行调用，crul格式时openAi提供的格式，发现采用阿里云的图片地址是访问不通，采用微软提供的图片地址是可以的，阿里云上传的图片地址在浏览器中都是正常可以打开的，

**Comment by zpcr7** [comment]
![1717567902346](https://github.com/labring/FastGPT/assets/171773052/b842880c-f4a7-475b-9b7e-f26fb9b8b11d)
在对话中可以进行图片分析

**Comment by sdytzjp** [comment]
请问分析图用哪个模型可以

**Comment by sdytzjp** [comment]
同问，为什么有的图片需要base64有的不需要
