### ISSUE TITLE
海外IP使用我的免登录窗口链接，却出现了登录界面

### ISSUE THREAD

**Issue by wbext** [labring/FastGPT#1699]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号:4.7.1 

**问题描述, 日志截图**
![lQLPKHJR8C2079XNAd_NAmawJh3L3srrmj0GS2ULWQDaAA_614_479](https://github.com/labring/FastGPT/assets/134917942/fd04e5a6-42f5-4ed4-b029-2fb93768582b)

**复现步骤**

**预期结果**

**相关截图**

**Comment by wbext** [comment]
刷新几次页面还是依然出现这个登录界面

**Comment by c121914yu** [comment]
旧版问题不排查，可以升到新版或自己看错误接口。
