### ISSUE TITLE
调用通义千问的视觉模型qwen-vl-max报错，提示参数temperature异常

### ISSUE THREAD

**Issue by Jiang-Wan** [labring/FastGPT#1700]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
我在oneapi配置了通义千问的视觉模型qwen-vl-max，并且可以通过代码正常调用（调用时不添加参数temperature或设置temperature=0），结果如下图：
![image](https://github.com/labring/FastGPT/assets/57851281/bb201d54-f975-4bf0-b094-ca7ee0e1e3fd)
在FastGPT中使用该模型的时候，就会报错，具体错误截图如下：
![image](https://github.com/labring/FastGPT/assets/57851281/4a8ca802-1bef-4258-90cb-f1350a193b2c)
关于这个模型的config.json配置如下图：
![image](https://github.com/labring/FastGPT/assets/57851281/f804ca0d-a9c3-4445-8d48-dc2c2696055a)
我知道这个问题是FastGPT后台调用oneapi接口的时候，添加了temperature这个参数导致，我想问的是，能否通过配置，让FastGPT调用的时候，不添加temperature这个参数或者temperature这个参数的值传为0
**复现步骤**

**预期结果**
能正常调用qwen-vl-max模型
**相关截图**

**Comment by swallowMuzi** [comment]
@Jiang-Wan 你好，我最近也在接qwen-vl，能加你联系方式请教一下你是怎么接的吗，我的报另外一种错，我的wx是swallowMuzi

**Comment by Jiang-Wan** [comment]
> @Jiang-Wan 你好，我最近也在接qwen-vl，能加你联系方式请教一下你是怎么接的吗，我的报另外一种错，我的wx是swallowMuzi

你在这个把问题写出来，截图贴出来呗，可能你的问题我也不知道，写在这里，让大家都看看，集思广益嘛！

**Comment by c121914yu** [comment]
最低默认了0.01~ 可以试试maxTem设置1，任何页面上选1（实际就是0.1）试试

**Comment by Jiang-Wan** [comment]
> 最低默认了0.01~ 可以试试maxTem设置1，任何页面上选1（实际就是0.1）试试

看样子应该不行，我在页面上是如下图这样设置的：
![image](https://github.com/labring/FastGPT/assets/57851281/dfaf393c-3e29-4ce0-92f5-d2d7fac7e388)
配置文件也改成了下图这个样子：
![image](https://github.com/labring/FastGPT/assets/57851281/41f7baf9-a187-42dc-aaa4-39168ec9402f)
依然会报一样的错误，如下图：
![image](https://github.com/labring/FastGPT/assets/57851281/5d55658a-dd68-4a0e-a861-246a3de8ba65)
目前来看，只通过配置，是否应该无法完成这个功能了，只能修改后台的代码逻辑了？

**Comment by c121914yu** [comment]
> > 最低默认了0.01~ 可以试试maxTem设置1，任何页面上选1（实际就是0.1）试试
> 
> 看样子应该不行，我在页面上是如下图这样设置的：
> ![image](https://github.com/labring/FastGPT/assets/57851281/dfaf393c-3e29-4ce0-92f5-d2d7fac7e388)
> 配置文件也改成了下图这个样子：
> ![image](https://github.com/labring/FastGPT/assets/57851281/41f7baf9-a187-42dc-aaa4-39168ec9402f)
> 依然会报一样的错误，如下图：
> ![image](https://github.com/labring/FastGPT/assets/57851281/5d55658a-dd68-4a0e-a861-246a3de8ba65)
> 目前来看，只通过配置，是否应该无法完成这个功能了，只能修改后台的代码逻辑了？

看来是的，模型不支持这个参数😂只能改模型接口，过滤对应参数

**Comment by PannyHuang** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue
> * [x]  我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
> * [x]  我使用了自己的 key，并确认我的 key 是可正常使用的
> * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本**
> 
> * [ ]  公有云版本
> * [x]  私有部署版本, 具体版本号: 4.8.3
> 
> **问题描述, 日志截图** 我在oneapi配置了通义千问的视觉模型qwen-vl-max，并且可以通过代码正常调用（调用时不添加参数temperature或设置temperature=0），结果如下图： ![image](https://private-user-images.githubusercontent.com/57851281/336729027-bb201d54-f975-4bf0-b094-ca7ee0e1e3fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjcwMDAsIm5iZiI6MTcyNTQyNjcwMCwicGF0aCI6Ii81Nzg1MTI4MS8zMzY3MjkwMjctYmIyMDFkNTQtZjk3NS00YmYwLWIwOTQtY2E3ZWUwZTFlM2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA1MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOGI1MjBlZDU2NDk0YmJiYjQzOTdlNjRlMzFmNDJhOTFiOTRmNDg2Y2E1ZWY0YWYwNTljZjc2ZDg2NDExZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.inm9uBM5UqE0ZSEMj-hutYx_3EhrRM4yO1-_XFm6-OI) 在FastGPT中使用该模型的时候，就会报错，具体错误截图如下： ![image](https://private-user-images.githubusercontent.com/57851281/336729217-4a8ca802-1bef-4258-90cb-f1350a193b2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjcwMDAsIm5iZiI6MTcyNTQyNjcwMCwicGF0aCI6Ii81Nzg1MTI4MS8zMzY3MjkyMTctNGE4Y2E4MDItMWJlZi00MjU4LTkwY2ItZjEzNTBhMTkzYjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA1MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZjgzNTIxZjg0NTQyYjcwYjU2NTZlZGZmYTQxZDI3MDJjYThjOTc4MDcyODYyMjZhODU5ZTMwZGYxZjk4YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sa5AkNJyCldw4MJLZp11b1mJzGcgWEkBzkMZpmylCYo) 关于这个模型的config.json配置如下图： ![image](https://private-user-images.githubusercontent.com/57851281/336729369-f804ca0d-a9c3-4445-8d48-dc2c2696055a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjcwMDAsIm5iZiI6MTcyNTQyNjcwMCwicGF0aCI6Ii81Nzg1MTI4MS8zMzY3MjkzNjktZjgwNGNhMGQtYTljMy00NDQ1LThkNDgtZGMyYzI2OTYwNTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA1MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZjI2ZWY3ZmQ3OGY3MDQ1ZGVmNjEzZGMyZDI4OWQ1MjZhMDVhY2Y0MmM0NDQ5MDAzOGM1NTU2YjMyNGNlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.asWwuARsv_QWNOlLDSCl45Hs0X0kpO0np_yfKs93lbo) 我知道这个问题是FastGPT后台调用oneapi接口的时候，添加了temperature这个参数导致，我想问的是，能否通过配置，让FastGPT调用的时候，不添加temperature这个参数或者temperature这个参数的值传为0 **复现步骤**
> 
> **预期结果** 能正常调用qwen-vl-max模型 **相关截图**

请问你是如何在oneapi后台给qwen-vl-max配置渠道的？

**Comment by Jiang-Wan** [comment]
![image](https://github.com/user-attachments/assets/82881e93-ea6b-4dda-9f64-02a7caa993fb)
手动填入的，填写后记得docker重启一下oneapi，你要是按fastgpt默认的配置，oneapi会走缓存

**Comment by Jiang-Wan** [comment]
![image](https://github.com/user-attachments/assets/42ccaad6-86cb-4e8d-b083-b951a7fa3ca0)
手动填入的，填入后记得重启下oneapi,你要是按fastgpt默认的方式配置oneapi，那oneapi会有缓存

**Comment by ChjxL** [comment]
你好，请问你有没有试过模型返回内容报错为空呢，我看本地调用是有返回的内容的，fastgpt聊天没有成功解析出来。
