### ISSUE TITLE
调用智谱AI模型返回[1214][history参数非法。请检查文档。]

### ISSUE THREAD

**Issue by zhangshf** [labring/FastGPT#1702]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.8.3
- One-API版本v0.6.6

**问题描述, 日志截图**

**复现步骤**
简单对话
配置使用智谱AI模型
在调试区提问
返回[1214][history参数非法。请检查文档。]

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/6993937/183ce29c-a4db-40a6-96e5-3929b4782aaa)

**Comment by c121914yu** [comment]
oneapi 0.6.5，选智谱渠道，未发现问题。

**Comment by zkstudio** [comment]
把提示词去掉就可以了
