### ISSUE TITLE
工具调用除string类型的输入参数无法被HTTP组件引用

### ISSUE THREAD

**Issue by sun-huafeng** [labring/FastGPT#1703]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ √] 我已确认目前没有类似 issue
- [√ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ √] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√ ] 私有部署版本, 具体版本号: 
V4.8.3
**问题描述, 日志截图**
新建工具自定义输入类型为array[string]时HTTP请求输入无法引用工具除了string类型以外的自定义输入，
![image](https://github.com/labring/FastGPT/assets/32211182/98c41d0d-c268-42eb-b3dc-75839d9b548f)

**复现步骤**
新建工具->自定义输入设置成array[string]数据类型->新增HTTP组件->引入工具array[string]数据类型的参数
**预期结果**
期望可以引用所有数据类型的参数
**相关截图**

**Comment by c121914yu** [comment]
string类型为什么能引用array<string>?
