### ISSUE TITLE
是否能够增加上下文根的配置项

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [labring/FastGPT#1706]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X] 我已确认目前没有类似 features
- [X] 我已确认我已升级到最新版本
- [X] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [X] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
是否能够增加上下文根的配置项，访问fastgpt时需要按照http://XXX.XXX/fastgpt这样的方式访问
**应用场景**
我们想要把fastgpt作为一个后台服务使用，为了避免页面挂载inframe时的跨域问题，我们把fastgpt需要跟主网站挂载到一个域名下，并且需要为fastgpt增加的上下文根，例如访问fastgpt时需要按照http://XXX.XXX/fastgpt这样的方式访问，请问能否增加这样的能力？
**相关示例**
访问fastgpt时需要按照http://XXX.XXX/fastgpt这样的方式访问
**我们的探索**
我们尝试使用nginx代理解决这个问题，一直没有找到合适的配置，后来我们改代码，增加basePath这样的配置，但是发现代码中有大量的相对路径引起的图片，例如/images/logo.svg，改代码改的太多了，而且有一些也找不到是哪引用的，还有报错。

**Comment by bincooo** [comment]
nginx 路径分发

**Comment by WholeWorld-Timothy** [comment]
能否具体点？我们试了反向代理，也试了rewrite的配置都有问题。
