### ISSUE TITLE
docker build 报错 ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref df29319f-8f71-4fd9-8b27-3d9ab7ddc334::837hjyprk382m76ti8egpuhq6: "/app/node_modules/tiktoken": not found

### ISSUE THREAD

**Issue by shikeqiang** [labring/FastGPT#1707]
自己本地修改master分支后构建镜像 docker build -t  . --build-arg name=app --build-arg proxy=taobao 报错

 => ERROR [runner 13/17] COPY --from=mainDeps /app/node_modules/tiktoken ./node_modules/tiktoken                                                   0.0s
------
 > [runner 13/17] COPY --from=mainDeps /app/node_modules/tiktoken ./node_modules/tiktoken:
------
Dockerfile:69
--------------------
  67 |
  68 |     # copy tiktoken but not copy ./node_modules/tiktoken/encoders
  69 | >>> COPY --from=mainDeps /app/node_modules/tiktoken ./node_modules/tiktoken
  70 |     RUN rm -rf ./node_modules/tiktoken/encoders
  71 |
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref df29319f-8f71-4fd9-8b27-3d9ab7ddc334::837hjyprk382m76ti8egpuhq6: "/app/node_modules/tiktoken": not found

**Comment by c121914yu** [comment]
看着是你代码和官方不一致
