### ISSUE TITLE
关于API没有对话日志的反馈，chatid究竟是拥有第三方应用代码权限的作者才能使用吗？

### ISSUE THREAD

**Issue by shuker2024** [labring/FastGPT#1709]
看到有很多反映对话日志中没有返回API应用的对话内容，很多回复都是说没有填写chatid，那么这个chatid究竟应该填写在哪里呢？在其他第三方应用中，只有填写API地址和key的地方，并没有填写chatid的地方，请问这个chatid应该填写在API地址的后面吗？例如：http://zd.XXXX.cc/api/v1=chatid,这样吗？

**Comment by c121914yu** [comment]
接口文档里写的很清楚～
没有填写的地方说明就不支持，gpt 接口本来就不支持纪录
