### ISSUE TITLE
知识库里的 分段文本 导入，有没有例子啊

### ISSUE THREAD

**Issue by mpuazxc2** [labring/FastGPT#171]
我想导入一个类似这样的文本
------
客户：在吗？
客服：在的，请问您需要咨询什么产品？
客户：防盗螺栓有吗？
客服：有的，我们提供全品类的紧固件产品，请告诉我具体的型号和用途。
客户：用在铁塔机器上的，2040304不锈钢
------
大概有个10M的用户对话文本，包括绝大部分可能问题，格式是啥啊
我直接拖入文本一直提示解析错误，手工导入又太慢了，每次只能3000字

**Comment by c121914yu** [comment]
直接分段的挂，按道理大部分文本文件都能直接导入。请给出具体操作，并确保文件可以通过浏览器打开
