### ISSUE TITLE
GLM-4-9B-CHAT模型调用API时常出现中断告错，提示1210API调用参数错误

### ISSUE THREAD

**Issue by warlockedward** [labring/FastGPT#1710]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/18415055/f082b4ba-0d1f-46db-b045-97da442238d5)

**复现步骤**

**预期结果**
![image](https://github.com/labring/FastGPT/assets/18415055/d292805e-744f-4353-a625-0eb46086e12c)

**相关截图**
![image](https://github.com/labring/FastGPT/assets/18415055/43c9be0d-e083-4fbf-adb1-387a450cebd0)

大模型为glm-4-9b-chat，使用VLLM方式加载运行，通过oneapi方式提供网关访问。
时常出现API错误，但又不是完全不能用，调用中断似乎也没有什么规律

源代码使用的是官方地址为：https://github.com/THUDM/GLM-4/blob/main/basic_demo/openai_api_server.py

**Comment by warlockedward** [comment]
![image](https://github.com/labring/FastGPT/assets/18415055/1ee7fd82-c02e-499e-bc98-25c7f73e71a1)

**Comment by lijiajun1997** [comment]
大概率VLLM那边的问题吧，等过几个版本再说

**Comment by warlockedward** [comment]
额~~~~最终发现是我的锅，我在大模型tokenizer_config.json文件里去定义了chat_template导致，返回到原来的方式好像这个问题的概率就降低了很多。现在基本上算能用了
