### ISSUE TITLE
考虑支持图片和文件的上传

### ISSUE THREAD

**Issue by 962694266** [labring/FastGPT#1714]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在聊天框支持文件的上传（图片和pdf、txt），上传后支持不需要fastgpt自己处理，可以通过接口的方式调用外部的ocr之类的工具进行处理

**应用场景**
文档对话，用户上传文档进行对话

**相关示例**
![image](https://github.com/labring/FastGPT/assets/105183985/fd202e9d-8130-4962-83c5-f596ee791909)

**Comment by lifei1102** [comment]
+1

最近遇到了挺多这样的场景，期望对话框支持上传，上传后的在线链接返回可以在高级编排中引用到，例如是个url数组，这样可以在编排中自行选择组件处理


目前是在别的文档管理系统中上传，然后把url复制过来迂回实现的，用户体验不好

**Comment by XingZL** [comment]
图片上传是支持的，但是好像的确没有文件上传功能

**Comment by 962694266** [comment]
> 图片上传是支持的，但是好像的确没有文件上传功能

图片怎么上传，我好像没看到？

**Comment by alexcry** [comment]
文件上传+1

**Comment by bulexu** [comment]
+  1

**Comment by Essence9999** [comment]
+1

**Comment by sdytzjp** [comment]
config里有

**Comment by c121914yu** [comment]
4.8.9 done
