### ISSUE TITLE
是否支持创建知识库地时候自己选择向量库

### ISSUE THREAD

**Issue by HelloEveryonehh** [labring/FastGPT#1716]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
希望可以在创建知识库地时候可以自己选择使用pg还是zilliz
**应用场景**
不同的知识库里面的数据量不同，对于数据量小的就选择使用pg，对于数据量大的知识库就选择使用zilliz
**相关示例**
在创建一个城市的知识库的时候，如果对于学校信息，完全可以放到pg里面，对于整个城市的景区信息就需要放到zilliz或者milvus里面，避免了资源的浪费

**Comment by c121914yu** [comment]
不支持

**Comment by goodstudy12** [comment]
自己部署个中转映射吧。
