### ISSUE TITLE
调试发现基于milvus对单挑数据删除操作,向量库中仍然存在值,但删除集合操作向量库清除有效

### ISSUE THREAD

**Issue by Buliqioqiolibusdo** [labring/FastGPT#1717]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.3
- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**
1. 新增数据并删除这条chunk
2. 查看向量库中是否有数据变化

**预期结果**
mongo与milvus同增同减

**相关截图**

免了

**Comment by c121914yu** [comment]
测试未发现该问题
