### ISSUE TITLE
使用docker私有化部署的fastgpt，执行【代码运行】功能时报错无法连接到80端口

### ISSUE THREAD

**Issue by ShawniLee** [labring/FastGPT#1718]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.3

**问题描述, 日志截图**
在本地使用docker-compose部署fastgpt，无法执行“代码运行”模块，提示"connect ECONNREFUSED 127.0.0.1:80".
![image](https://github.com/labring/FastGPT/assets/28498646/01d4407e-e170-4b02-96c8-32fb93b8c3c7)

**复现步骤**
使用默认docker-compse.yaml部署，fastgpt应该在3000端口，80端口无服务。

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没部署代码运行服务
