### ISSUE TITLE
调用glm4-9b-chat 报json 格式错误

### ISSUE THREAD

**Issue by swingsun888** [labring/FastGPT#1719]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.1 
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
调用glm4-9b-chat  通过oneapi接入模型，提问ai回复时候发现，只要回复问题有分段的情况时候，就会报错“Unexpected end of JSON input”

后台日志显示：
[INFO] 2024-06-08 05:03:45 [dispatchWorkFlow] nodeRunWithActive: 系统配置 
[INFO] 2024-06-08 05:03:45 [dispatchWorkFlow] nodeRunWithActive: 流程开始 
197 new ObjectId("65a37e2de910d7d6da91eadc")
[INFO] 2024-06-08 05:03:45 [dispatchWorkFlow] nodeRunWithActive: AI 对话 
[INFO] 2024-06-08 05:03:45 Count token time: 3, token: 15 
Could not parse message into JSON: 
From chunk: [ 'data: ' ]
[ERROR] 2024-06-08 05:04:00 sse error: Unexpected end of JSON input 
{
  message: 'Unexpected end of JSON input',
  stack: 'SyntaxError: Unexpected end of JSON input\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at eZ.iterator (/app/projects/app/.next/server/chunks/15428.js:15:69289)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async k (/app/projects/app/.next/server/chunks/75612.js:308:2339)\n' +
    '    at async /app/projects/app/.next/server/chunks/75612.js:308:885\n' +
    '    at async Object.A [as chatNode] (/app/projects/app/.next/server/chunks/75612.js:308:787)\n' +
    '    at async k (/app/projects/app/.next/server/chunks/75612.js:309:2194)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async D (/app/projects/app/.next/server/chunks/75612.js:309:2735)\n' +
    '    at async C (/app/projects/app/.next/server/pages/api/v1/chat/completions.js:63:13076)'
}
[INFO] 2024-06-08 05:04:00 Request finish /api/v1/chat/completions, time: 15386ms 
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
api 格式不是 gpt 格式，自行适配。

**Comment by gq2010** [comment]
本地部署的glm4-9b-chat模型，官网提供的代码里没有/v1/embeddings这个API怎么解决呢？
