### ISSUE TITLE
生成向量错误: error: expected 1536 dimensions, not 4096

### ISSUE THREAD

**Issue by winnie1228** [labring/FastGPT#172]
您好！我在对接本地模型过程中，修改了OPENAI_BASE_URL和OPENAIKEY值，可以成功进行简单的对话。但是在做知识库+对话引导时，上传知识库报错如图片所示，在进行这一过程之前我调整了config.json文件中VectorModels为本地模型，目前所知道的是图片中的4096是调用本地模型/v1/embeddings接口返回的数据长度。请问我还需要做什么修改才能顺利进行下去？急🙏
![image](https://github.com/labring/FastGPT/assets/78136057/08b90da0-4892-44b6-b057-ebb8789fc56a)

**Comment by winnie1228** [comment]
> 我也刚好碰到这个问题，这个主要原因是fastgpt的向量维度定义是openai的，而你自己的模型生成的向量维度跟openai的不一致，如文心千帆模型是384也会出现问题，就看作者咋处理， 目前我的临时处理方案是：到PG向量库中将向量的维度改为对应模型的维度，重启 `ALTER TABLE modeldata alter COLUMN vector type vector(384);`

哇，太感谢你能回复我，请问你连接pg的时候打开数据库有这个报错吗？
![image](https://github.com/labring/FastGPT/assets/78136057/e38324c6-9413-4361-8ba6-b5e6211fdbe3)

**Comment by winnie1228** [comment]
> 我也刚好碰到这个问题，这个主要原因是fastgpt的向量维度定义是openai的，而你自己的模型生成的向量维度跟openai的不一致，如文心千帆模型是384也会出现问题，就看作者咋处理， 目前我的临时处理方案是：到PG向量库中将向量的维度改为对应模型的维度，重启 `ALTER TABLE modeldata alter COLUMN vector type vector(384);`

按照你的方法解决了，谢谢你~

**Comment by c121914yu** [comment]
建议归一化成1536

**Comment by muzibaby** [comment]
3.X 的不支持文心一言，这个我也找 oneapi的验证过，不知道 4.0 的是否支持了

**Comment by c121914yu** [comment]
> 3.X 的不支持文心一言，这个我也找 oneapi的验证过，不知道 4.0 的是否支持了

已经支持了
