### ISSUE TITLE
插件中的变量为数字，实际请求是字符串，导致HTTP请求失败

### ISSUE THREAD

**Issue by Code-Bai** [labring/FastGPT#1720]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/62536222/919f25cc-fc78-4b7d-8f18-fdd9760ca73c)
![image](https://github.com/labring/FastGPT/assets/62536222/725f342f-3f2d-44a7-ab03-456c397b2e77)
![image](https://github.com/labring/FastGPT/assets/62536222/faf9173c-2cac-4b6b-b144-19ec96f982b9)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
插件参数不等于 http 参数
