### ISSUE TITLE
免登录链接，允许用户反馈时，上传文件

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1721]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
分享免登录链接，用户访问；回答不正确或引用文件中不存在所需文件时，支持用户反馈并上传相关文件。
**应用场景**
基于知识库检索时，有时问题检索出的引用文件不对，或者库中不存在，这时候允许用户反馈并上传相关文档。
**相关示例**

**Comment by Purseccc** [comment]
大佬，可否留个联系方式。感觉我们的需求很接近，希望有个一起探讨的机会

**Comment by Essence9999** [comment]
重复提

**Comment by Essence9999** [comment]
重复提

**Comment by Essence9999** [comment]
issue重复

**Comment by Essence9999** [comment]
> 大佬，可否留个联系方式。感觉我们的需求很接近，希望有个一起探讨的机会

大佬，我比较菜；相关问题都是提issue，靠本项目大佬[c121914yu](https://github.com/c121914yu)来解决~

**Comment by c121914yu** [comment]
先留着 open 好了，方便后续规划。

**Comment by Essence9999** [comment]
> 先留着 open 好了，方便后续规划。

感谢感谢，翻遍了所有issue，发现涉及文件上传（非知识库）都没啥好的解决方案，项目逻辑太强大，还是等大佬解决比较好
