### ISSUE TITLE
内容提取没有正确获取

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#1722]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.3

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
插件工作流里

流数据：
<img width="1289" alt="Screenshot 2024-06-09 at 18 34 59" src="https://github.com/labring/FastGPT/assets/36452456/04a333dd-2c99-4248-8407-4738989079be">

插件：
<img width="855" alt="Screenshot 2024-06-09 at 18 35 37" src="https://github.com/labring/FastGPT/assets/36452456/7ef8bd3a-9275-430b-977f-64fcb81c98f9">

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
内容提取不走流请求

**Comment by bincooo** [comment]
啊？

**Comment by bincooo** [comment]
我指的是数据返回，
<img width="1581" alt="Screenshot 2024-06-09 at 21 32 55" src="https://github.com/labring/FastGPT/assets/36452456/1472b7cb-ada0-4247-83bb-4cbe66328296">
<img width="914" alt="Screenshot 2024-06-09 at 21 33 19" src="https://github.com/labring/FastGPT/assets/36452456/7b6d07ef-dbf1-425f-9c37-4c91a859bb00">

**Comment by c121914yu** [comment]
> 我指的是数据返回， <img alt="Screenshot 2024-06-09 at 21 32 55" width="1581" src="https://private-user-images.githubusercontent.com/36452456/337977331-1472b7cb-ada0-4247-83bb-4cbe66328296.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDAzNzQsIm5iZiI6MTcxNzk0MDA3NCwicGF0aCI6Ii8zNjQ1MjQ1Ni8zMzc5NzczMzEtMTQ3MmI3Y2ItYWRhMC00MjQ3LTgzYmItNGNiZTY2MzI4Mjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEzMzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NjQyYmVlZDg3M2JjYWIzMzVjYzk3Mjg4MTU4MTY1YjY0MDBjNjAyM2M5MDkwYmU3NjE3NzVhYjU2Yjk1MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vO3xWqMEfODS4mU3vjRIVwZi4SfJ8lpuOfSILnTCYDQ"> <img alt="Screenshot 2024-06-09 at 21 33 19" width="914" src="https://private-user-images.githubusercontent.com/36452456/337977347-7b6d07ef-dbf1-425f-9c37-4c91a859bb00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDAzNzQsIm5iZiI6MTcxNzk0MDA3NCwicGF0aCI6Ii8zNjQ1MjQ1Ni8zMzc5NzczNDctN2I2ZDA3ZWYtZGJmMS00MjVmLTljMzctNGM5MWE4NTliYjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEzMzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTdkMGM3NGVkYTc4NzE0MGM3OTk0ODQ1NTlhNGM0MGE2ZDNkYmM4YjJiYWM0NWQyOGE3MGI5MWQ0Mjc5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hIwe_YT9JD1S1lDLs0afJs9Fpn4-7UI6CJqU6pjStBQ">

你这个能支持tool调用？

**Comment by bincooo** [comment]
额，没注意看。原来如此🤦

**Comment by bincooo** [comment]
试了一下，是我马大哈了。不好意思
