### ISSUE TITLE
应用调用传参BUG：主体调用S应用，设置用户问题的参数是AI回复内容。但实测发现S应用接受不到，只能拿到用户的提问。

### ISSUE THREAD

**Issue by Jonathanfdy** [labring/FastGPT#1728]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/1726 这个 pr 有修复。

**Comment by Jonathanfdy** [comment]
辛苦！是新版本已经修复了么？我用的是4.8

**Comment by c121914yu** [comment]
> 辛苦！是新版本已经修复了么？我用的是4.8

是的
