### ISSUE TITLE
message: '401 无效的令牌

### ISSUE THREAD

**Issue by zrmzack** [labring/FastGPT#1730]
我在管理渠道上已经测通了本地的ollama模型，也对应配置了令牌，但是还是出现了无效令牌，有大佬帮忙看看么
![image](https://github.com/labring/FastGPT/assets/39054457/202838af-4ba6-4340-91ac-e352969f1eb2)
![image](https://github.com/labring/FastGPT/assets/39054457/df07b65f-7c02-45a4-ac1e-69b49b98957c)
![image](https://github.com/labring/FastGPT/assets/39054457/8e6bf46d-aa5c-424d-a140-6349416f97cd)
求大佬bang帮忙看看 ！！！多谢

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/91ef714e-a1be-4995-9af7-fa4446ef2ceb)
这个要用oneapi令牌值

**Comment by zrmzack** [comment]
> ![image](https://private-user-images.githubusercontent.com/40045458/338422103-91ef714e-a1be-4995-9af7-fa4446ef2ceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzY0NDQsIm5iZiI6MTcxODA3NjE0NCwicGF0aCI6Ii80MDA0NTQ1OC8zMzg0MjIxMDMtOTFlZjcxNGUtYTFiZS00OTk1LTlhZjctZmE0NDQ2ZWYyY2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAzMjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYmNiZDJjN2M4ZGE3Y2M0ZmQxYzVkMjY3Y2ZiYTIzNjE0MTk2NjZjYWM2NzE2YmYxOGM4NjI4NGY5OTQ2ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tWZtrDvXqs9tmuWsbn6rqCKBcHhtwDjjbgoae34TWsw) 这个要用oneapi令牌值

您好，我是在这复制的令牌
![image](https://github.com/labring/FastGPT/assets/39054457/9c3d8eef-3503-4fd8-8fcc-55306f91d808)
但是没有生效

**Comment by zrmzack** [comment]
已经解决了 多谢

**Comment by xiaoToby** [comment]
是不是因为是没有填的是的oneapi上的令牌导致的？

**Comment by sslzhou948** [comment]
> 已经解决了 多谢

请问是怎么解决的呢？我也卡在这里了

**Comment by kasaizad** [comment]
如何解决的，能分享下吗

**Comment by hamiduan** [comment]
多谢分享已解决。

1.  在Oneapi 申请令牌后，复制key到fastgpt docker-compose.yml 下CHAT_API_KEY=key
2.  重启fastgpt oneapi（在fastgpt docker-compose.yml 目录下 docker compose down, docker compose up -d)
3.  *注意，令牌界面 「模型范围」不要填写，会限制embedding模型（未测试填写所有所用模型）
4.  复制令牌的sk-key，在渠道所用的llm和embedding模型中粘贴。
5. FastGpt 知识库测试可行。

注释：
1.  *Oneapi不支持测试Embedding，因为请求的是/completion接口，所以会报错response 404。
2. 可通过curl --location --request POST 'http://<此处填Embedding模型IP：端口>/v1/embeddings' \
--header 'Authorization: Bearer <此处填你的令牌sk-key>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "model": "m3e",
    "input": ["laf是什么"]
}'

**Comment by antanxia** [comment]
> 已经解决了 多谢

我也遇上这问题了，你是怎么解决的？

**Comment by izeroidea** [comment]
> 已经解决了 多谢
我也遇这个问题，有请如何解决的?
