### ISSUE TITLE
使用cogvlm2模型出现报错object has no attribute '{name}‘ 

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1732]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/40045458/73fbb211-96d5-430d-8f3c-1077b6693c5a)
![image](https://github.com/labring/FastGPT/assets/40045458/a95a8c5a-49f4-408c-b439-b98ebf773e69)

使用oneapi测试这个接口，也是出现同样的问题
感觉问题是出现在，fastgpt给接口传的数据中，TextContent中的name=None
@c121914yu @nongmo677 @lijiajun1997
**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
vision功能需要转成openai api的格式

**Comment by xiaoToby** [comment]
我使用的cogvlm给的openai api（https://github.com/THUDM/CogVLM2/blob/main/basic_demo/openai_api_demo.py）

**Comment by c121914yu** [comment]
> 我使用的cogvlm给的openai api（https://github.com/THUDM/CogVLM2/blob/main/basic_demo/openai_api_demo.py）

并不是一个标准格式，简易手动改造它。

**Comment by c121914yu** [comment]
> 我使用的cogvlm给的openai api（https://github.com/THUDM/CogVLM2/blob/main/basic_demo/openai_api_demo.py）

oneapi 不行，fastgpt 肯定也不行。。少发的话，其他模型肯定也不通～不用怀疑，肯定是这个接口有问题。

**Comment by xiaoToby** [comment]
> > 我使用的cogvlm给的openai api（[https://github.com/THUDM/CogVLM2/blob/main/basic_demo/openai_api_demo.py）](https://github.com/THUDM/CogVLM2/blob/main/basic_demo/openai_api_demo.py%EF%BC%89)
> 
> oneapi 不行，fastgpt 肯定也不行。。少发的话，其他模型肯定也不通～不用怀疑，肯定是这个接口有问题。

是这个openai_api_demo.py它支持的是cogvlm2-llama3-chinese-chat-19B模型，没有支持他们新发布的glm-4v-9b
后面能在fastgpt中使用这个多模态模型
