### ISSUE TITLE
语义检索 数值大、应用问答，没有引用显示

### ISSUE THREAD

**Issue by nangongchengfeng** [labring/FastGPT#1733]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  v4.8.3

**问题描述, 日志截图**

- 调用一切正常，感觉检索方面 异常
- 回答感觉没有调用知识库的内容，全部走的模型返回的

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/46562911/6bba664d-07ef-41c4-aa26-de39bed964da)
![image](https://github.com/labring/FastGPT/assets/46562911/f6fe6ac0-4377-4af9-8b1f-7bf72b9fc180)
![image](https://github.com/labring/FastGPT/assets/46562911/d9cb0a3a-7fa1-4835-806a-ad5448f6451b)

**Comment by nangongchengfeng** [comment]
目前我使用一键安装正常的，使用docker-compose 有问题。
在上传数据拆分的时候，使用 的 是 qwen-long。然后就会出现这个问题（使用ChatGPT3.5 自带的模型正常）

![image](https://github.com/labring/FastGPT/assets/46562911/54fbafc6-1c10-4ae1-a15f-4636726a7e35)

**Comment by c121914yu** [comment]
qwen 不是向量模型，
