### ISSUE TITLE
pnpm start后报错“no such file or directory”错误

### ISSUE THREAD

**Issue by adamwuyu** [labring/FastGPT#1739]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: "version": "4.8.3",

**问题描述, 日志截图**
运行pnpm dev时出现警告：
<img width="908" alt="截屏2024-06-12 01 17 21" src="https://github.com/labring/FastGPT/assets/2903328/1c88cc96-3f29-4d8d-8a51-cd0680feb718">

接着运行“pnpm start”，然后打开网站url就会报错：
<img width="1629" alt="截屏2024-06-12 01 05 42" src="https://github.com/labring/FastGPT/assets/2903328/fb3dd63c-709f-415e-ac3a-feabe4ecf856">

**复现步骤**
pnpm build
pnpm start

**预期结果**
不报错，且像pnpm dev一样，正常运行网站。

**相关截图**
无

**Comment by c121914yu** [comment]
要手动 build，你需要手动执行 docker file 里 run 阶段所有内容。

**Comment by adamwuyu** [comment]
> 要手动 build，你需要手动执行 docker file 里 run 阶段所有内容。

大佬，DockerFile里的代码手动执行，确实不会呀，您看看我这么操作有什么问题，万分感谢🙏：
1. 删除DockerFile中“# --------- runner -----------”之后的部分，见下方图片；
2. 在根目录执行“sudo docker build -f ./projects/app/Dockerfile -t registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:v4.8.1 . --build-arg name=app”
![DockerFile_adam](https://github.com/labring/FastGPT/assets/2903328/03af8373-9eb6-4765-b648-eb4c89fd845c)

**Comment by c121914yu** [comment]
> > 要手动 build，你需要手动执行 docker file 里 run 阶段所有内容。
> 
> 大佬，DockerFile里的代码手动执行，确实不会呀，您看看我这么操作有什么问题，万分感谢🙏：
> 
> 1. 删除DockerFile中“# --------- runner -----------”之后的部分，见下方图片；
> 2. 在根目录执行“sudo docker build -f ./projects/app/Dockerfile -t registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:v4.8.1 . --build-arg name=app”
>    ![DockerFile_adam](https://private-user-images.githubusercontent.com/2903328/339276751-03af8373-9eb6-4765-b648-eb4c89fd845c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjY4MzAsIm5iZiI6MTcxODI2NjUzMCwicGF0aCI6Ii8yOTAzMzI4LzMzOTI3Njc1MS0wM2FmODM3My05ZWI2LTQ3NjUtYjY0OC1lYjRjODlmZDg0NWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDgxNTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDEwYWEyMWY0OTk1Y2YzZDQwZjk2ZWJlNzJlMDFiYmVjZGJiZmVhMDg2NDVlZmI0OGE4NTlmNjU4YmRmNTkwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tlNEM3AIVfFNGsE4g7DvMC-facU-TKB9TRGF31vZUBM)

不会，，那就老实用docker~

**Comment by adamwuyu** [comment]
> 不会，，那就老实用docker~

好的，之前是因为网络问题，没法使用docker打包。我先解决这个问题。。。谢谢啦
