### ISSUE TITLE
编排模式下，应用A调用应用B，B的对话日志中没有记录

### ISSUE THREAD

**Issue by bulexu** [labring/FastGPT#1742]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.3

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/20762228/54e7dfc8-7b97-4c87-adf6-5b089d67e62a)
<img width="972" alt="image" src="https://github.com/labring/FastGPT/assets/20762228/eda2fa2d-641e-48f3-9bf7-1c312efcf51c">
如图，在第一个应用中查看调用情况，可见调用了应用，但是在对应的第二张截图中，没有任何日志记录

**复现步骤**
通过api调用应用a，编排中配置调用应用b
**预期结果**
b中需要看到对话日志
**相关截图**
无

**Comment by bulexu** [comment]
不清楚是我配置不正确还是当前功能就是这么设计的，请求解答，辛苦

**Comment by c121914yu** [comment]
确实是没有，因为目前对话记录是和顶层 chat 绑定。后续再单独抽一两个版本优化日志。

**Comment by bulexu** [comment]
copy
