### ISSUE TITLE
通过api调用fastgpt应用的流式响应是不是实时转发的

### ISSUE THREAD

**Issue by bulexu** [labring/FastGPT#1744]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.3

**问题描述, 日志截图**
- 使用通义千问api提供大模型能力
- 通过api对接本地部署的fastgpt应用，响应速度比较慢

通过对比对话日志，看着像是fastgpt接收了千问的流式响应的全部内容之后，再通过流式响应给api，这里可否支持实时转发，或者应该如何配置实时转发
**复现步骤**
无
**预期结果**
可以实时转发大模型的响应内容
**相关截图**
无

**Comment by c121914yu** [comment]
你调用问题
