### ISSUE TITLE
遇到了oneapi容器启动失败问题，日志提示panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by helloyangy** [labring/FastGPT#1747]
- [x]  公有云版本Ubuntu22.04

**问题描述, 日志截图**
**复现步骤**
使用文档命令部署
![image](https://github.com/labring/FastGPT/assets/102957628/d088d4b5-8fe9-4ea1-9023-16b189f87f50)

**openapi容器日志**
[SYS] 2024/06/12 - 08:03:38 | One API v0.6.7-alpha.4 started 
[SYS] 2024/06/12 - 08:03:38 | using MySQL as database 
[SYS] 2024/06/12 - 08:03:38 | database migration started 
[SYS] 2024/06/12 - 08:03:38 | database migrated 
[SYS] 2024/06/12 - 08:03:38 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/06/12 - 08:03:38 | using theme default 
[SYS] 2024/06/12 - 08:03:38 | memory cache enabled 
[SYS] 2024/06/12 - 08:03:38 | sync frequency: 600 seconds 
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/songquanpeng/one-api/model.InitChannelCache()
        /build/model/cache.go:196 +0x78e
main.main()
        /build/main.go:76 +0x556

**相关截图**
![image](https://github.com/labring/FastGPT/assets/102957628/1fc216c5-5a80-4b44-9de1-45628c76a293)

**Comment by c121914yu** [comment]
得去oneapi看看，目前还是用0.6.5版本

**Comment by seramat** [comment]
同样的问题，请问怎么解决的？

**Comment by c121914yu** [comment]
> 同样的问题，请问怎么解决的？

置顶 issue 有提
