### ISSUE TITLE
【咨询】FastGPT项目是否支持使用使用开源LLM作为embeddings，进行知识库生成

### ISSUE THREAD

**Issue by taurusduan** [labring/FastGPT#175]
FastGPT项目是否支持使用使用开源LLM作为embeddings，进行知识库生成。

**Comment by c121914yu** [comment]
支持，都是api，换个接口就可以了

**Comment by lifeofbow** [comment]
在哪配置呢

**Comment by c121914yu** [comment]
参考文档：https://doc.fastgpt.run/docs/installation/reference/configuration/
替换向量模型，并在 oneapi 增加对应向量模型

**Comment by c121914yu** [comment]
已支持，参考最新发行版说明：https://github.com/labring/FastGPT/releases/tag/v4.2.1
