### ISSUE TITLE
【建议】能否考虑增加对话历史和内容标注功能

### ISSUE THREAD

**Issue by LivingXu** [labring/FastGPT#176]
能否考虑增加每个应用的对话历史和用户对生成内容的标注功能，以便于收集用于进一步调整模型的数据，谢谢。

**Comment by c121914yu** [comment]
数据已经存储了。后面会增加一个专门查阅记录和快速标椎的页面

**Comment by LivingXu** [comment]
感谢回复，FastGPT是很有价值的工作。

**Comment by c121914yu** [comment]
v4.2.2已经增加反馈与标注。
