### ISSUE TITLE
4.8.3 Docker-compose部署后 Fastgpt启动失败

### ISSUE THREAD

**Issue by DenisZheng** [labring/FastGPT#1760]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
腾讯云服务器，使用docker-compose部署，json文件和yml文件全部只下载没修改
docker启动后，fastgpt显示错误信息：Load init config error SyntaxError: Unexpected token / in JSON at position 0
**复现步骤**
将Docker镜像全部清空后，配置文件重新下载后，重新部署还是一样的问题
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/3062447/7a57b9c0-9aa5-4c48-ad2b-353831aa5130)

**Comment by ENg-122** [comment]
我也遇到了 有没有大佬知道咋解决啊

**Comment by AlphaWu** [comment]
关注，同样的错误。

**Comment by c121914yu** [comment]
最新是4.8.4，你4.8.3用4.8.4配置肯定报错呢~

**Comment by AlphaWu** [comment]
把注释全部删除掉，可以运行了。

**Comment by ENg-122** [comment]
换了4.8.4 也可以了
