### ISSUE TITLE
JS运行失败

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#1761]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
运行JS模块出错
{
  "message": "connect ECONNREFUSED ::1:80",
  "name": "Error",
  "method": "post",
  "url": "undefined/sandbox/js",
  "code": "ECONNREFUSED"
}
不知道要怎么准备运行环境，谢谢
**复现步骤**

**预期结果**
JS能正常运行
**相关截图**

**Comment by c121914yu** [comment]
看 4.8.2 升级说明

**Comment by ppkitty** [comment]
升级说明就一句话，是我找错地方了吗？
https://doc.fastgpt.in/docs/development/upgrading/482/#v482-%E6%9B%B4%E6%96%B0%E8%AF%B4%E6%98%8E
V4.8.2 更新说明 
新增 - js代码运行节点（更完整的type提醒，后续继续完善）
新增 - 内容提取节点支持数据类型选择
修复 - 新增的站点同步无法使用
修复 - 定时任务无法输入内容

**Comment by c121914yu** [comment]
> 升级说明就一句话，是我找错地方了吗？ https://doc.fastgpt.in/docs/development/upgrading/482/#v482-%E6%9B%B4%E6%96%B0%E8%AF%B4%E6%98%8E V4.8.2 更新说明 新增 - js代码运行节点（更完整的type提醒，后续继续完善） 新增 - 内容提取节点支持数据类型选择 修复 - 新增的站点同步无法使用 修复 - 定时任务无法输入内容

里面很明确了呀，要部署啥，改啥变量

**Comment by ppkitty** [comment]
还是报错呢：
[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [NestFactory] Starting Nest application...
2[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [InstanceLoader] AppModule dependencies initialized +11ms
3[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [RoutesResolver] SandboxController {/sandbox}: +41ms
4[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [RouterExplorer] Mapped {/sandbox/js, POST} route +2ms
5[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [NestApplication] Nest application successfully started +2ms
6Application is running on: http://127.0.0.1:3000/
7error => Cannot GET /sandbox/js
8error => main is not defined

**Comment by c121914yu** [comment]
> 还是报错呢： [Nest] 1 - 06/24/2024, 9:11:41 AM LOG [NestFactory] Starting Nest application... 2[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [InstanceLoader] AppModule dependencies initialized +11ms 3[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [RoutesResolver] SandboxController {/sandbox}: +41ms 4[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [RouterExplorer] Mapped {/sandbox/js, POST} route +2ms 5[Nest] 1 - 06/24/2024, 9:11:41 AM LOG [NestApplication] Nest application successfully started +2ms 6Application is running on: http://127.0.0.1:3000/ 7error => Cannot GET /sandbox/js 8error => main is not defined

没按模板代码执行，模板代码是有main函数的
