### ISSUE TITLE
增加一个直接对接OpenAI Assistant的Node

### ISSUE THREAD

**Issue by RandyZ** [labring/FastGPT#1762]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
针对OpenAI的Assistant API做了一层包装
如果需要我愿意整理代码，提供PR
![image](https://github.com/labring/FastGPT/assets/9149366/dea48f2e-546a-40a8-9780-8c56e060f9a7)

**应用场景**
初衷是为了借用OpenAI提供的一些默认Code interpreter处理表格类的数据
**相关示例**

**Comment by c121914yu** [comment]
可以做成插件形式，后续加入模板市场

**Comment by RandyZ** [comment]
好，那我直接关闭了
