### ISSUE TITLE
代码执行增加python的支持

### ISSUE THREAD

**Issue by 962694266** [labring/FastGPT#1763]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
代码执行增加python的支持

**应用场景**

**相关示例**
目前是javascript，在增加了javascript可用性感觉已经提升非常多，太有用了，要是可以用python就更无敌了

**Comment by c121914yu** [comment]
重复 https://github.com/labring/FastGPT/issues/1675
