### ISSUE TITLE
我将原fastgpt docker容器停止并删除后，然后升级最新版重新启动了一个容器，之前容器的配置的数据（应用，知识库等）就不见了

### ISSUE THREAD

**Issue by CytFree** [labring/FastGPT#1768]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
原 4..4.7 版本， 升级到最新版 4.8.4

**问题描述, 日志截图**
这是我的docker启动命令，mongo和pg没有重启
docker run -d --name fastgpt -p 3000:3000 -e DEFAULT_ROOT_PSW=1234 -e OPENAI_BASE_URL=http://192.168.33.8:5050/v1 -e CHAT_API_KEY=sk-fastgpt -e DB_MAX_LINK=30 -e TOKEN_KEY=any -e ROOT_KEY=root_key -e FILE_TOKEN_KEY=filetoken -e MONGODB_URI=mongodb://myusername:mypassword@mongo:27017/fastgpt?authSource=admin -e PG_URL=postgresql://username:password@pg:5432/postgres -e SANDBOX_URL=http://sandbox:3000 -e LOG_LEVEL=info -v /hsdata/docker-lv/fastgpt/tmp:/app/tmp --network fastgpt --restart always fastgpt:v4.8.4

**复现步骤**

**预期结果**

**相关截图**

**Comment by Essence9999** [comment]
对照https://doc.fastgpt.in/docs/development/upgrading/481/
进行初始化，表名变了；
查看fastgpt日志成功后，再登录即可
