### ISSUE TITLE
【功能咨询】请问目前四种方式同时使用，叠加使用，会进一步提升准确度吗？感觉单独使用效果达不到预期。

### ISSUE THREAD

**Issue by lemon-simple** [labring/FastGPT#177]
![image](https://github.com/labring/FastGPT/assets/28141497/75624e55-379a-4874-94d3-412d76f64173)

比如我同时使用 QA拆分+直接分段+CSV导入 会提升本地向量检索的准确度吗？这几种是否会叠加生效？

**Comment by lemon-simple** [comment]
那面向用户来说，比如可以选QA拆分、和直接分段两种功能， 我为了提高准确性，应该选择哪种方式呢？这个用户无法评判

**Comment by lemon-simple** [comment]
@c121914yu 麻烦请教下。

**Comment by c121914yu** [comment]
直接分段，简单粗暴，细节保留。但是如果最后分了几万chunk，效果会很差。

qa拆分，可以支持更多数据，因为匹配内容长度小，相似度容易区分，且可以比直接分段选择更多的搜索数量。缺点是容易丢失细节。
