### ISSUE TITLE
断网后，不能正常访问

### ISSUE THREAD

**Issue by eric20100106** [labring/FastGPT#1770]
私有化部署后，可以正常使用fastgptV4.8.3的所有功能，但断网后，本机访问localhost:3000就界面没响应了，通过浏览器devtool查看到界面访问时的资源情况，发现访问fastgpt首页时，看到系统会去连接“https://api.github.com/repos/labring/FastGPT"!会不会是因为要连接这个地址，断网后访问不到，界面就不正常了？

**Comment by chery589** [comment]
老哥问题解决了嘛，我也遇到一样的问题，断网就报错系统会去连接“https://api.github.com/repos/labring/FastGPT"

**Comment by HugoSun** [comment]
老哥问题解决了吗，同样遇到这个问题

**Comment by c121914yu** [comment]
忘记关联，之前调整了，没网卡情况下也可以用。之前需要开局域网。
