### ISSUE TITLE
新的权限系统(读、写、管理员)和原先的角色(admin, visitor)是怎么一个对应关系

### ISSUE THREAD

**Issue by 704572066** [labring/FastGPT#1773]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没关系

**Comment by 704572066** [comment]
> 没关系

那现在团队成员权限的值好像在数据库中没有保存的字段么，role字段看起来还是admin owner,visitor这几个值，有点搞混了。

**Comment by c121914yu** [comment]
> > 没关系
> 
> 那现在团队成员权限的值好像在数据库中没有保存的字段么，role字段看起来还是admin owner,visitor这几个值，有点搞混了。

开源版没权限的表。
