### ISSUE TITLE
最新版使用文件夹上传知识库每次最多100个文件

### ISSUE THREAD

**Issue by Mgrsc** [labring/FastGPT#1774]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
V4.8.4
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  docker

**问题描述, 日志截图**
在知识库中使用文本数据集上传文件，拖动文件夹进去每次只能拖入100个文件
<img width="303" alt="image" src="https://github.com/labring/FastGPT/assets/118801216/4cce5fd8-6afb-40c5-9e13-8e5222b89acf">
<img width="505" alt="image" src="https://github.com/labring/FastGPT/assets/118801216/74f7bdd6-e961-4152-a949-c5077af66f7f">
重启fastgpt所有组件后恢复正常，并且重启之前还出现了知识库训练卡住不动的情况，同样重启后恢复。
**复现步骤**

**预期结果**
文件夹内所有的格式正确的文件都应该导入，而不是限制100个
**相关截图**

**Comment by c121914yu** [comment]
没有支持文件夹拖动，不知道你是怎么拖进去的

**Comment by Mgrsc** [comment]
这不是支持拖动吗
![image](https://github.com/labring/FastGPT/assets/118801216/84651aae-ea16-47d4-b0ea-5492f87dee27)
![image](https://github.com/labring/FastGPT/assets/118801216/e9371c10-392e-4f08-a662-d4893cf60194)
