### ISSUE TITLE
Markdown 图片解析渲染问题

### ISSUE THREAD

**Issue by zaite** [labring/FastGPT#1775]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
目前知识库录入或者通过文档导入的知识库，支持Markdown 格式，但是在问答输出上很不稳定，比如知识库里包含很多图片，但是在问答环节无法输出，折腾过好多提示词都没效果，比如通过发送，xxx图片，xxx截图或者在知识库markdown 格式前后各种注释描述，这样倒是会出现图片输出渲染的概率，但是这样很不友好！
**应用场景**
知识库，文档操作指引，图文介绍
**相关示例**
![IMG_20240616_184639](https://github.com/labring/FastGPT/assets/22079456/83e9f301-154a-47bb-8c48-12b89f730186)

**Comment by duskcouple** [comment]
和fastgpt应该没啥关系，是大模型比较智障，指令服从性比较拉胯，没什么好办法。甭说图片给你省略了，就是检索出来的知识库的好多核心内容，经过大模型一过滤，就残缺七八了，那些文字看起来头头是道，挺通顺，但实际上知识库检索出来的好多核心有用的知识块都被省略了。

**Comment by c121914yu** [comment]
😅已经返回链接了，但是不是 md 的链接，感觉只能调下模型提示词了

**Comment by zaite** [comment]
> 😅已经返回链接了，但是不是 md 的链接，感觉只能调下模型提示词了。试试强制给他 md 图片格式作为参考。

升级到最新版试了下，图片比前面的版本渲染成功的概率大一点了，而且也和模型有很大关系，gpt和文心可以通过各种提示词提高概率，而通义不管用啥提示词和方法都不行，都不能理解，最后在问题后面附加“最好以图文形式回复”，则能渲染出一些图片，但是，出不出片也很随机，看它模型的心情😅

**Comment by c121914yu** [comment]
> > 😅已经返回链接了，但是不是 md 的链接，感觉只能调下模型提示词了。试试强制给他 md 图片格式作为参考。
> 
> 升级到最新版试了下，图片比前面的版本渲染成功的概率大一点了，而且也和模型有很大关系，gpt和文心可以通过各种提示词提高概率，而通义不管用啥提示词和方法都不行，都不能理解，最后在问题后面附加“最好以图文形式回复”，则能渲染出一些图片，但是，出不出片也很随机，看它模型的心情，几个大模型对比可能gpt相对好用一点😅

我突然想到是不是后缀问题，没有图片后缀导致它觉得这不是图片。下次我试试加个后缀。

**Comment by zaite** [comment]
> > > 😅已经返回链接了，但是不是 md 的链接，感觉只能调下模型提示词了。试试强制给他 md 图片格式作为参考。
> > 
> > 
> > 升级到最新版试了下，图片比前面的版本渲染成功的概率大一点了，而且也和模型有很大关系，gpt和文心可以通过各种提示词提高概率，而通义不管用啥提示词和方法都不行，都不能理解，最后在问题后面附加“最好以图文形式回复”，则能渲染出一些图片，但是，出不出片也很随机，看它模型的心情，几个大模型对比可能gpt相对好用一点😅
> 
> 我突然想到是不是后缀问题，没有图片后缀导致它觉得这不是图片。下次我试试加个后缀。

ok，那回头更新了再试试

**Comment by sdytzjp** [comment]
跟进，同样的需求

**Comment by c121914yu** [comment]
> > > 😅已经返回链接了，但是不是 md 的链接，感觉只能调下模型提示词了。试试强制给他 md 图片格式作为参考。
> > 
> > 
> > 升级到最新版试了下，图片比前面的版本渲染成功的概率大一点了，而且也和模型有很大关系，gpt和文心可以通过各种提示词提高概率，而通义不管用啥提示词和方法都不行，都不能理解，最后在问题后面附加“最好以图文形式回复”，则能渲染出一些图片，但是，出不出片也很随机，看它模型的心情，几个大模型对比可能gpt相对好用一点😅
> 
> 我突然想到是不是后缀问题，没有图片后缀导致它觉得这不是图片。下次我试试加个后缀。

该后缀功能已增加。

**Comment by ifkd111** [comment]
> > > > 😅已经返回链接了，但是不是 md 的链接，感觉只能调下模型提示词了。试试强制给他 md 图片格式作为参考。
> > > 
> > > 
> > > 升级到最新版试了下，图片比前面的版本渲染成功的概率大一点了，而且也和模型有很大关系，gpt和文心可以通过各种提示词提高概率，而通义不管用啥提示词和方法都不行，都不能理解，最后在问题后面附加“最好以图文形式回复”，则能渲染出一些图片，但是，出不出片也很随机，看它模型的心情，几个大模型对比可能gpt相对好用一点😅
> > 
> > 
> > 我突然想到是不是后缀问题，没有图片后缀导致它觉得这不是图片。下次我试试加个后缀。
> 
> 该后缀功能已增加。

为什么现在我的4.8.10输出的是图片地址，而不是之前的markdown格式图片，是因为更新取消了什么功能吗？我没有调整过知识库内容，为什么前后会有差别，之前用的4.8.7就是正常的
然后这个后缀怎么使用
