### ISSUE TITLE
对话中，用户引导增加用户名变量，mongo导出chatitems csv中却没有姓名这个字段

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1778]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:v4.8.3 

**问题描述, 日志截图**
对话中，用户引导增加用户名变量，点开前端对话日志能显示使用者姓名，但mongo导出chatitems csv中却没有姓名这个字段，只有chatID，请问这个用户名变量数据保存在哪？方便与chatid做个映射。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/66725845/432a5fde-4259-48bd-9e1d-3a9b0b410865)

**Comment by Purseccc** [comment]
插眼

**Comment by c121914yu** [comment]
chats表，variables里
