### ISSUE TITLE
系统正常运行2天后，就会出现异常错误：14 UNAVAILABLE: Name resolution failed for target dns:milvusStandalone:19530

### ISSUE THREAD

**Issue by danielxvcg** [labring/FastGPT#1781]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.3

**问题描述, 日志截图**
我在一台虚拟机（配置是CentOS7, 4C16G, 硬盘500G）通过docker-comose部署了一套fastgpt系统，向量数据库采用的是milvus，LLM接入的是通义千问。在创建知识库和聊天应用后，系统正常运行2天后，当我继续编辑知识库或者进入聊天应用时，系统就会出现错误提示：14 UNAVAILABLE: Name resolution failed for target dns:milvusStandalone:19530
![错误提示1](https://github.com/labring/FastGPT/assets/728678/feaa73b3-3b0a-48a4-8ef7-4d141bc708eb)

我在服务器上检查容器状态，发现milvusStandalone状态是Exited，如下图所示：
![错误提示2](https://github.com/labring/FastGPT/assets/728678/6bde2b6f-a192-4fb4-98c6-c9ca2a3b7060)

在日志里，我查到最后异常退出的日志截图如下：
![错误提示3](https://github.com/labring/FastGPT/assets/728678/b55620a5-d1cc-4b49-a149-3998e7b3694c)

我初步怀疑是不是和系统配置有关系。我在网上查了一些资料，milvus对磁盘的速度还是有比较高的要求。当我关闭容器，并重启之后，系统就能正常使用了。但这种状态仍然是维持2天之后，系统又会继续报同样的错误。我试了几次，基本上都是如此。

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
可以milvus问问

**Comment by danielxvcg** [comment]
> 同样的问题

我将硬盘迁移到SSD硬盘上后，这个问题目前就没有再出现了。我查询了Milvus官网，上面要求硬盘是SSD，目前来看应该是硬盘速度不够引起的。

**Comment by liuzj288** [comment]
> > 同样的问题
> 
> 我将硬盘迁移到SSD硬盘上后，这个问题目前就没有再出现了。我查询了Milvus官网，上面要求硬盘是SSD，目前来看应该是硬盘速度不够引起的。

同样的问题，所以得换ssd是吧
