### ISSUE TITLE
插件添加知识库变量，直接崩溃

### ISSUE THREAD

**Issue by lktsuer** [labring/FastGPT#1784]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/37295257/1d813ab0-7c60-4f95-a639-47f4df40cea0)

![image](https://github.com/labring/FastGPT/assets/37295257/cc19ef69-15a9-4615-9cb7-d00cc3137957)

**复现步骤**
直接插件添加知识库变量即可
**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/c2483eed-49d9-4aa1-9dac-016d086a1137)
似乎没遇到~ 看下日志

**Comment by c121914yu** [comment]
fix https://github.com/labring/FastGPT/pull/1835
