### ISSUE TITLE
知识库接口-创建一个文件集合调用失败

### ISSUE THREAD

**Issue by huijinshizhe2017** [labring/FastGPT#1785]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
通过http://localhost:3000/api/core/dataset/collection/create/localFile调用接口，报404错误。
**应用场景**
二次开发创建本地文件集合，调用接口报错。
**相关示例**
curl --location --request POST 'http://localhost:3000/api/core/dataset/collection/create/localFile' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Authorization: Bearer xxx' \
--header 'Accept: */*' \
--header 'Host: localhost:3000' \
--header 'Connection: keep-alive' \
--header 'Content-Type: multipart/form-data; boundary=--------------------------507277619813907857944372' \
--form 'file=@"C:\\Users\\admin\\Desktop\防治条例_1703576498649.docx"' \
--form 'data="{}"'

**Comment by c121914yu** [comment]
自己把最新代码合并~
