### ISSUE TITLE
iPhone聊天页面移位严重影响用户使用

### ISSUE THREAD

**Issue by Purseccc** [labring/FastGPT#1787]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.1 

**问题描述, 日志截图**
![e11bf482138e41fa583789385520761](https://github.com/labring/FastGPT/assets/77132374/18f09b9b-14df-41ad-8662-162741f39fca)
可以看到右侧的按钮都被挡掉了。

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
看版本纪录
