### ISSUE TITLE
查看引用-知识库引用（Markdown格式显示引用内容）

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1788]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
点击查看引用，引用内容以markdown格式呈现
![image](https://github.com/labring/FastGPT/assets/66725845/193ddbd2-e972-42e0-98d9-e39881f445cf)

**应用场景**
LLM 对话问答展示图片不稳定，可通过在引用中直接显示出来，便于查看使用

请问大佬，有没有相关解法；或者修改哪部分代码，添加markdown格式化展示

**Comment by Purseccc** [comment]
projects/app/src/components/core/dataset/QuoteItem.tsx
加MarkDown组件

**Comment by Purseccc** [comment]
参考ChatItem.tsx

**Comment by ChanLicher** [comment]
> projects/app/src/components/core/dataset/QuoteItem.tsx 加MarkDown组件

请问有相关教程吗？这个数据库导入的东西别说图片了，连正常的数学公式都无法显示

![PixPin_2024-06-19_15-27-06](https://github.com/labring/FastGPT/assets/55681496/3f455d40-d1f9-486e-b607-9df67ac4cb54)

**Comment by zenwan** [comment]
数学公式展示混乱，

**Comment by sdytzjp** [comment]
> 参考ChatItem.tsx

能具体介绍下吗

**Comment by c121914yu** [comment]
> > projects/app/src/components/core/dataset/QuoteItem.tsx 加MarkDown组件
> 
> 请问有相关教程吗？这个数据库导入的东西别说图片了，连正常的数学公式都无法显示
> 
> ![PixPin_2024-06-19_15-27-06](https://github.com/labring/FastGPT/assets/55681496/3f455d40-d1f9-486e-b607-9df67ac4cb54)
> 

建议了解下数学公式在 md 如何展示

**Comment by ChanLicher** [comment]
> > > projects/app/src/components/core/dataset/QuoteItem.tsx 加MarkDown组件
> > 
> > 
> > 请问有相关教程吗？这个数据库导入的东西别说图片了，连正常的数学公式都无法显示
> > ![PixPin_2024-06-19_15-27-06](https://private-user-images.githubusercontent.com/55681496/341185493-3f455d40-d1f9-486e-b607-9df67ac4cb54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzUwNjAsIm5iZiI6MTcyMDM3NDc2MCwicGF0aCI6Ii81NTY4MTQ5Ni8zNDExODU0OTMtM2Y0NTVkNDAtZDFmOS00ODZlLWI2MDctOWRmNjdhYzRjYjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3NTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MGVlYWE0MzFiNmNlZTg0M2VmNTg4ZjE2ZGU0MDQ4NmU1ZDhiNzRiNWMzMzQ3MTQ2ODIwODliMjdlNGYzZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ag2UrNFDS_fhdjc6bhiRErEj8U3jy2GTNp62k7DmrgU)
> 
> 建议了解下数学公式在 md 如何展示

我的公式是用 LaTeX 语法写的，而且在我的 md 文档中完美显示，所以是不是 FastGPT 不支持 LeTeX ？如果到头来我还得从头编辑所有公式，那实在是不值得花这份功夫。

**Comment by c121914yu** [comment]
> > > > projects/app/src/components/core/dataset/QuoteItem.tsx 加MarkDown组件
> > > 
> > > 
> > > 请问有相关教程吗？这个数据库导入的东西别说图片了，连正常的数学公式都无法显示
> > > ![PixPin_2024-06-19_15-27-06](https://private-user-images.githubusercontent.com/55681496/341185493-3f455d40-d1f9-486e-b607-9df67ac4cb54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzUwNjAsIm5iZiI6MTcyMDM3NDc2MCwicGF0aCI6Ii81NTY4MTQ5Ni8zNDExODU0OTMtM2Y0NTVkNDAtZDFmOS00ODZlLWI2MDctOWRmNjdhYzRjYjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3NTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MGVlYWE0MzFiNmNlZTg0M2VmNTg4ZjE2ZGU0MDQ4NmU1ZDhiNzRiNWMzMzQ3MTQ2ODIwODliMjdlNGYzZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ag2UrNFDS_fhdjc6bhiRErEj8U3jy2GTNp62k7DmrgU)
> > 
> > 建议了解下数学公式在 md 如何展示
> 
> 我的公式是用 LaTeX 语法写的，而且在我的 md 文档中完美显示，所以是不是 FastGPT 不支持 LeTeX ？如果到头来我还得从头编辑所有公式，那实在是不值得花这份功夫。

这就和问，为什么代码块不高亮一样。
