### ISSUE TITLE
知识库创建时选择文件处理模型没有生效，总是默认选择第一个config.json中的第一个模型

### ISSUE THREAD

**Issue by chenhb-zte** [labring/FastGPT#1792]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
ghcr.io/labring/fastgpt                                     v4.8.2  
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
创建知识库时选择了文件处理模型，但是在知识库搜索时默认选择config.json中的第一个模型

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
知识库搜索用的是向量模型不是LLM，知识库配置的LLM是用来把导入文件转成QA的

**Comment by chenhb-zte** [comment]
> 知识库搜索用的是向量模型不是LLM，知识库配置的LLM是用来把导入文件转成QA的

在问答时，知识库搜索前会先调用config.json中配置的第一个模型，而不是选择的LLM，从one-api日志里可以看到访问记录，这是什么步骤？如果第一个模型是不可用模型，会直接失败。

**Comment by lijiajun1997** [comment]
> > 知识库搜索用的是向量模型不是LLM，知识库配置的LLM是用来把导入文件转成QA的
> 
> 在问答时，知识库搜索前会先调用config.json中配置的第一个模型，而不是选择的LLM，从one-api日志里可以看到访问记录，这是什么步骤？如果第一个模型是不可用模型，会直接失败。

你说的是问题优化，把编排的知识库优化关掉就行

**Comment by sdytzjp** [comment]
我也碰到同样的问题

**Comment by chong1210** [comment]
此项问题如何处理呢
