### ISSUE TITLE
本地部署fastgpt使用chatglm3-6b大模型，在高级编排中使用文本内容提取模块，一直都无法提取内容

### ISSUE THREAD

**Issue by caijx168** [labring/FastGPT#1794]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
本地部署fastgpt使用chatglm3-6b大模型，在高级编排中使用文本内容提前模块，一直都无法提取内容。 自己测试不经过fastgpt，chatglm3是有内容提取能力的。
**复现步骤**

**预期结果**
帮助解决，高级编排中内容提取模块，能正确提取内容
**相关截图**
![image](https://github.com/labring/FastGPT/assets/54843188/44928f47-1045-4cf3-a5fc-65a3222e3b68)

**Comment by lijiajun1997** [comment]
把toolchoice和functioncall改成false试一下

**Comment by caijx168** [comment]
> 把toolchoice和functioncall改成false试一下

这两个都改为false了，有时候可以提取内容，有时候也提取不出来

**Comment by lijiajun1997** [comment]
> > 把toolchoice和functioncall改成false试一下
> 
> 这两个都改为false了，有时候可以提取内容，有时候也提取不出来

原生兼容的只有openai的toolcall，对于其他模型的function call貌似oneapi那边没有兼容，所以只能都关掉 用提示词去提取，但是效果不好

**Comment by caijx168** [comment]
> 原生兼容的只有openai的toolcall，对于其他模型的function call貌似oneapi那边没有兼容，所以只能都关掉 用提示词去提取，但是效果不好

那这个是你们后续会优化嘛，还是只能让我们自己优化提示词去提取呢？

**Comment by c121914yu** [comment]
优先换模型，其次是考虑支持 function call，最后是调提示词。
