### ISSUE TITLE
文本提取模块无法提取到想要的内容，输出为空，但是在线上版一样的条件能够提取成功

### ISSUE THREAD

**Issue by YFSakura** [labring/FastGPT#1796]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
如图，无法提取到想要的内容，输出为空，但是在官网线上版一样的条件能够提取

**复现步骤**

**预期结果**

**相关截图**
![d085bf21e34b9a35b5217ebc1539a02](https://github.com/labring/FastGPT/assets/115632796/e65f4632-a55d-478d-9965-49bd83202d4c)

**Comment by huluohu** [comment]
请问你解决了吗，我用国内包括谷歌的模型都不行，是只能用openai的模型吗？

**Comment by swl632** [comment]
这个问题解决了吗？我也遇到这个问题，用AI对话，是能够给出结果的，但是用文本提取就不行，用同样的模型（我用的是百度模型ERNIE-4.0-8k）
