### ISSUE TITLE
docker-compose up -d报错 timeout

### ISSUE THREAD

**Issue by rocmxp** [labring/FastGPT#1797]
使用Docker Compose 快速部署。到“docker-compose up -d”这一步 报错
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/6e/6e0cb183450e70e379cc6133339f795e9dbfe9a7e31534891797a8352f3ba910/data?verify=1718698193-qkdL3eh1xUGTWbY4QMcdFMedwgg%3D: dial tcp 157.240.1.50:443: i/o timeout

**Comment by c121914yu** [comment]
没挂梯子，或者用阿里云的镜像

**Comment by zzlTim** [comment]
咋设置阿里云镜像啊
