### ISSUE TITLE
HTTP 模块目前还不支持自定义请求头吧

### ISSUE THREAD

**Issue by sunk926** [labring/FastGPT#180]
主要现在很多api都需要授权Authorization,必须要自定义header请求头.

**Comment by sunk926** [comment]
还有建议增加一个简单的markdown编辑器,用于快速知识库编辑或导入.
比如 
标题1Q
段落1A
很容易拆分的,而且更方便管理知识库.

**Comment by c121914yu** [comment]
接口是自己写的，可以选择不带

**Comment by sunk926** [comment]
> 接口是自己写的，可以选择不带

我目前需要调用我的 思源笔记本的api,用来提取笔记内容,但是这个是需要 Authorization鉴权的.刚刚试了一段时间,确实不行.

**Comment by sunk926** [comment]
> > > 接口是自己写的，可以选择不带
> > 
> > 
> > 我目前需要调用我的 思源笔记本的api,用来提取笔记内容,但是这个是需要 Authorization鉴权的.刚刚试了一段时间,确实不行.
> 
> 你自己写个api去掉用思源就好了

好吧~也只有这样了,辛苦了

**Comment by c121914yu** [comment]
嗯。可以用 laf 快速对接，不需要单独部署服务。
