### ISSUE TITLE
网页转Markdown前执行JavaScript处理

### ISSUE THREAD

**Issue by Zhenyi-Wang** [labring/FastGPT#1801]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
当导入网页链接时，使用 puppeteer 或类似库先行处理网页源代码，确保执行JavaScript以渲染内容，之后再将渲染后的结果转换为Markdown格式。

**应用场景**
针对那些依赖纯前端渲染（其中数据通常包含在script标签中）的网站，例如 <https://tenancy.dev>，目前的抓取逻辑无法有效提取内容。此功能将允许用户从这些动态生成的页面中捕获并保存完整的文章或文档内容。

**相关示例**

**Comment by c121914yu** [comment]
开源版不会增加无头爬虫
