### ISSUE TITLE
只要加上 - MILVUS_ADDRESS 的环境变量,就会报错

### ISSUE THREAD

**Issue by jqlts1** [labring/FastGPT#1802]
报错内容如下
Client must be connected before running operations

我只要在 docker-compose 里面设置了  MILVUS_ADDRESS 的链接就会报错,这个MILVUS_ADDRESS是我自己提前部署的地址,是可以正常使用的

**Comment by c121914yu** [comment]
日志会提示，连接miilvus失败。大概率连接地址就不对或者不通。

**Comment by jqlts1** [comment]
> 日志会提示，连接miilvus失败。大概率连接地址就不对或者不通。

是不是我设置了密码的原因? 地址链接应该是没问题的,因为是本地部署的,只是设置了密码,但是按照文档设置好像也不行,你们有测过链接到需要密码的 milvus

**Comment by c121914yu** [comment]
> > 日志会提示，连接miilvus失败。大概率连接地址就不对或者不通。
> 
> 是不是我设置了密码的原因? 地址链接应该是没问题的,因为是本地部署的,只是设置了密码,但是按照文档设置好像也不行,你们有测过链接到需要密码的 milvus

测过，加到 token 就好了。
