### ISSUE TITLE
重排调用成功页面上显示却不成功

### ISSUE THREAD

**Issue by slajdfk** [labring/FastGPT#1803]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [✅] 我已确认目前没有类似 issue
- [✅ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [✅] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [✅] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [✅] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8.4-alpha
- [ ] 公有云版本
- [✅] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
fastgpt调用了本地的rerank。本地显示调用成功且正常返回。但是在fastgpt的页面上显示红色的❌并且没有重排的信息。
![image](https://github.com/labring/FastGPT/assets/157799272/e5d77ca0-baea-4a29-aba6-355074374ca8)
下面是本地rerank调用的信息
<img width="672" alt="image" src="https://github.com/labring/FastGPT/assets/157799272/16b987f8-0a56-4a7d-9ae1-97b9c8e09ef7">

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
估计模型响应接口不一致，参考cohere的接口。

**Comment by slajdfk** [comment]
@c121914yu 不行

**Comment by Linnnkkk** [comment]
我和你一样，解决了吗

**Comment by slajdfk** [comment]
> 我和你一样，解决了吗

模型响应接口和cohere的接口不一致。
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/54e3a6fe-d831-464c-816e-93cd8cc43a84">

**Comment by Linnnkkk** [comment]
> > 我和你一样，解决了吗
> 
> 模型响应接口和cohere的接口不一致。 <img alt="image" width="1377" src="https://private-user-images.githubusercontent.com/157799272/358460977-54e3a6fe-d831-464c-816e-93cd8cc43a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTQ5NzgsIm5iZiI6MTcyMzgxNDY3OCwicGF0aCI6Ii8xNTc3OTkyNzIvMzU4NDYwOTc3LTU0ZTNhNmZlLWQ4MzEtNDY0Yy04MTZlLTkzY2Q4Y2M0M2E4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMzI0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2Y0YzE4M2Y2NzI3YzRkZWY0YWQyMzVjZjkyMDFmMDcxNGNmMzZiNzQ4NjE4MTJmNTMxYTA4YzI2Y2FiZDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4KLd3xBOXcZPRucTJeDcoa9Qa8fv2IlTbKdy2jE6qa8">

求教如何解决啊，
我是部署的官方推荐的bge-reranker-base，部署后，fstgpt的重排显示总是false，但是我在bge-reranker-base的log显示的确实200，ok

**Comment by Linnnkkk** [comment]
> > 我和你一样，解决了吗
> 
> 模型响应接口和cohere的接口不一致。 <img alt="image" width="1377" src="https://private-user-images.githubusercontent.com/157799272/358460977-54e3a6fe-d831-464c-816e-93cd8cc43a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTQ5NzgsIm5iZiI6MTcyMzgxNDY3OCwicGF0aCI6Ii8xNTc3OTkyNzIvMzU4NDYwOTc3LTU0ZTNhNmZlLWQ4MzEtNDY0Yy04MTZlLTkzY2Q4Y2M0M2E4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMzI0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2Y0YzE4M2Y2NzI3YzRkZWY0YWQyMzVjZjkyMDFmMDcxNGNmMzZiNzQ4NjE4MTJmNTMxYTA4YzI2Y2FiZDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4KLd3xBOXcZPRucTJeDcoa9Qa8fv2IlTbKdy2jE6qa8">

求教如何解决啊，
我是部署的官方推荐的bge-reranker-base，部署后，fstgpt的重排显示总是false，但是我在bge-reranker-base的log显示的确实200，ok
