### ISSUE TITLE
请推荐就一个文档校对的大模型，或者告诉我用哪个数据集可以在较小的模型上训练出高质量的ai模型

### ISSUE THREAD

**Issue by xfghvgnfyjssjgte** [labring/FastGPT#1804]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.4
- [x ] 私有部署版本, 具体版本号: 
我现在ollama挂载了qwen2 7b,ollama 8b,经过测试，对文档进行校对，结果质量都是很差
比如我在语句中故意多输入标点符号或者词语，2个模型进行审查校对出来的结果都不行，但是如果用chatgpt4o，出来的质量出奇的高，我的prompt写的是
我将你定义为 kim，一位文书处理专家，以后当我说kim，帮我对上面的文档进行检查时，你就会对我提供的文本信息进行全面的文档审核，主要审查标准为：
	1. 检查错别字。
	2. 检查语句漏字，多字，重复字，造成语句的不通顺
	3. 错误的标点符号，或者缺少、重复的标点符号
	4. 关注内容的一致性。
	5. 确保逻辑连贯性。
	6. 检查格式规范。
	7. 验证数据的准确性。
检查结果中详细列出共性修改项的具体数量和所有修改的具体地方。

所以我在考虑会不会是因为模型的量比较的小，而无法达到校对文档的目的，请都fastgpt老师，这种情况该如何解决或者能自己训练一个专门用于校对文字内容的语言模型。

**Comment by c121914yu** [comment]
模型至少32b以上

**Comment by lijiajun1997** [comment]
70b的模型才能有商业应用的价值，7b只是聊天的玩具，知识能力还行，推理或者指令服从性较差

**Comment by xfghvgnfyjssjgte** [comment]
谢谢，已经明白

**Comment by XhHello** [comment]
> * 我将你定义为 kim，一位文书处理专家，以后当我说kim，帮我对上面的文档进行检查时，你就会对我提供的文本信息进行全面的文档审核，主要审查标准为：

请问你现在做的咋样啦，我需要做个和你类似的任务，审查文档内容的一致性
