### ISSUE TITLE
输出bug

### ISSUE THREAD

**Issue by shuker2024** [labring/FastGPT#1806]
fastgpt特有的bug，经常会出现这样的情况，特别是存在公式的时候会出现乱码，和模型无关，经过测试用什么大模型都会出现这种情况。
类似这样：
[
\text{基础养老金} = \left(\text{养老金计发基数} + \text{养老金计发基数} \times \text{缴费指数}\right) \div 2 \times \text{缴费年限} \times 1%
]
![微信截图_20240619221759](https://github.com/labring/FastGPT/assets/156998643/2e97800b-c2dd-4e59-804a-b57ac1151f84)

**Comment by shuker2024** [comment]
正常显示的时候是这样：
![微信截图_20240619221759](https://github.com/labring/FastGPT/assets/156998643/705ab105-37dc-4942-8cd5-8f3d76c50f4a)

**Comment by c121914yu** [comment]
没加math提示词，看一起issue

**Comment by shuker2024** [comment]
兄弟，math提示词是啥？看一起issue又是啥，有链接嘛

**Comment by shuker2024** [comment]
> 没加math提示词，看一起issue

兄弟，math提示词是啥？看一起issue又是啥，有链接嘛

**Comment by c121914yu** [comment]
> > 没加math提示词，看一起issue
> 
> 兄弟，math提示词是啥？看一起issue又是啥，有链接嘛

![image](https://github.com/labring/FastGPT/assets/50446880/913cd38d-31ba-4ace-8235-2b1909fc2d77)

你搜搜以前别人提的~
math ≈ 公式
