### ISSUE TITLE
调用js代码块功能无法运行，出现以下报错

### ISSUE THREAD

**Issue by YFSakura** [labring/FastGPT#1807]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
调用js代码块功能无法运行，出现以下报错。我的代码好像没有进行网络请求，但是一直说我什么80端口错误
**复现步骤**

**预期结果**

**相关截图**
![5dec1d54d9c12b4a33e69b982b2b010](https://github.com/labring/FastGPT/assets/115632796/238cf5f7-acc6-41e7-ba86-098f97b065f9)

**Comment by c121914yu** [comment]
没部署 sandbox
