### ISSUE TITLE
v4.8.3 docker编译报错：ERROR: failed to solve: process "/bin/sh -c pnpm --filter=app build" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1808]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
node:current-alpine3.20
pnpm@9.4.0

# 对比测试：v4.8.1正常编译，没有问题

node、pnpm试了好几个版本，包括项目自带的，编译到后面，都报：
![image](https://github.com/labring/FastGPT/assets/66725845/3fd05cac-5de4-4ba0-b6fa-bcc061106705)

**复现步骤**
sudo docker build -f ./projects/app/Dockerfile -t rag:dev . --build-arg name=app --build-arg proxy=taobao
**预期结果**

**相关截图**
 => [builder  6/10] COPY ./projects/app ./projects/app                                                                                                                                                                       0.3s
 => [builder  7/10] COPY --from=mainDeps /app/projects/app/node_modules ./projects/app/node_modules                                                                                                                          0.0s
 => [builder  8/10] RUN [ -z "taobao" ] || sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories                                                                                                     0.2s
 => [builder  9/10] RUN apk add --no-cache libc6-compat && npm install -g pnpm@9.4.0                                                                                                                                         4.6s
 => **ERROR [builder 10/10] RUN pnpm --filter=app build**                                                                                                                                                                       16.6s
------
 > [builder 10/10] RUN pnpm --filter=app build:
2.446
2.446 > app@4.8.3 build /app/projects/app
2.446 > next build
2.446
4.800 Attention: Next.js now collects completely anonymous telemetry regarding usage.
4.801 This information is used to shape Next.js' roadmap and prioritize features.
4.801 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
4.801 https://nextjs.org/telemetry
4.801
4.917   ▲ Next.js 14.2.3
4.917   - Experiments (use with caution):
4.917     · outputFileTracingRoot
4.917
4.918    Linting and checking validity of types ...
16.33
16.33 Failed to compile.
16.33
16.33 ./src/components/ChatBox/index.tsx
16.33 190:28  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/ai/SettingLLMModel/index.tsx
16.33 47:6  Warning: React Hook useEffect has missing dependencies: 'defaultData', 'model', 'modelList', and 'onChange'. Either include them or remove the dependency array. If 'onChange' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/app/ScheduledTriggerConfig.tsx
16.33 239:6  Warning: React Hook useEffect has missing dependencies: 'onUpdate' and 'value?.timezone'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/dataset/QuoteItem.tsx
16.33 199:29  Error: Comments inside children section of tag should be placed inside braces  react/jsx-no-comment-textnodes
16.33 200:53  Error: Comments inside children section of tag should be placed inside braces  react/jsx-no-comment-textnodes
16.33
16.33 ./src/components/core/workflow/Flow/NodeTemplatesModal.tsx
16.33 424:6  Warning: React Hook useMemo has a missing dependency: 'appT'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/workflow/Flow/nodes/NodeVariableUpdate.tsx
16.33 252:6  Warning: React Hook useMemo has a missing dependency: 'appDetail.chatConfig'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/workflow/Flow/nodes/render/RenderInput/templates/Reference.tsx
16.33 147:6  Warning: React Hook useMemo has a missing dependency: 'appDetail.chatConfig'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/workflow/Flow/nodes/render/RenderInput/templates/SelectDataset.tsx
16.33 54:6  Warning: React Hook useEffect has a missing dependency: 'data'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/workflow/Flow/nodes/render/RenderInput/templates/SelectDatasetParams.tsx
16.33 61:6  Warning: React Hook useEffect has a missing dependency: 'data'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/workflow/Flow/nodes/render/RenderInput/templates/SelectLLMModel.tsx
16.33 44:6  Warning: React Hook useEffect has missing dependencies: 'item.value', 'modelList', and 'onChangeModel'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/core/workflow/components/PublishHistoriesSlider.tsx
16.33 57:6  Warning: React Hook useCallback has a missing dependency: 'initData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33 64:5  Warning: React Hook useCallback has missing dependencies: 'initData' and 'onClose'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/support/apikey/Table.tsx
16.33 87:6  Warning: React Hook useEffect has a missing dependency: 'feConfigs?.customApiDomain'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/components/support/wallet/QRCodePayModal.tsx
16.33 39:6  Warning: React Hook useEffect has a missing dependency: 'codeUrl'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/_error.tsx
16.33 26:6  Warning: React Hook useEffect has missing dependencies: 'lastRoute' and 'router'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/account/components/BillTable.tsx
16.33 91:6  Warning: React Hook useEffect has a missing dependency: 'getData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/account/components/UsageTable.tsx
16.33 97:6  Warning: React Hook useEffect has a missing dependency: 'getData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/app/detail/components/SimpleEdit/EditForm.tsx
16.33 155:6  Warning: React Hook useEffect has missing dependencies: 'refresh' and 'watch'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/chat/team.tsx
16.33 165:6  Warning: React Hook useEffect has missing dependencies: 'appId', 'chatId', 'lastChatAppId', 'lastChatId', and 'router'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/dataset/detail/components/CollectionCard/Context.tsx
16.33 119:6  Warning: React Hook useEffect has a missing dependency: 'getData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/dataset/detail/components/CollectionCard/Header.tsx
16.33 55:27  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/dataset/detail/components/DataCard.tsx
16.33 98:24  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
16.33 184:6  Warning: React Hook useMemo has a missing dependency: 'datasetT'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/dataset/detail/components/Import/components/FileSelector.tsx
16.33 153:5  Warning: React Hook useCallback has a missing dependency: 'fileT'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/dataset/detail/components/Import/diffSource/ExternalFile.tsx
16.33 88:6  Warning: React Hook useEffect has missing dependencies: 'reset' and 'sources'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/dataset/detail/components/Import/diffSource/FileCustomText.tsx
16.33 66:6  Warning: React Hook useEffect has missing dependencies: 'reset' and 'sources'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/dataset/detail/components/Import/diffSource/FileLink.tsx
16.33 57:6  Warning: React Hook useEffect has missing dependencies: 'reset' and 'sources'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/dataset/detail/components/Import/diffSource/TableLocal.tsx
16.33 54:6  Warning: React Hook useEffect has a missing dependency: 'setSources'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/login/fastlogin.tsx
16.33 77:6  Warning: React Hook useEffect has missing dependencies: 'authCode', 'callbackUrl', 'code', 'router', and 'token'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/login/index.tsx
16.33 67:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/login/provider.tsx
16.33 101:6  Warning: React Hook useEffect has missing dependencies: 'authCode', 'code', 'error', 'loginStore?.state', 'router', 'state', 't', and 'toast'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/pages/plugin/edit/index.tsx
16.33 61:6  Warning: React Hook useEffect has missing dependencies: 'initData', 'isV2Workflow', 'openConfirm', and 'workflowStringData'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/web/common/hooks/useEditTitle.tsx
16.33 73:6  Warning: React Hook useCallback has missing dependencies: 'toast' and 'valueRule'. Either include them or remove the dependency array. If 'valueRule' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps
16.33 112:5  Warning: React Hook useCallback has a missing dependency: 't'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/web/common/hooks/useSpeech.ts
16.33 164:6  Warning: React Hook useEffect has a missing dependency: 'mediaStream'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
16.33
16.33 ./src/web/common/hooks/useSticky.ts
16.33 19:17  Warning: The ref value 'parentRef.current' will likely have changed by the time this effect cleanup function runs. If this ref points to a node rendered by React, copy 'parentRef.current' to a variable inside the effect, and use that variable in the cleanup function.  react-hooks/exhaustive-deps
16.33
16.33 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
16.48 /app/projects/app:
16.48  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  app@4.8.3 build: `next build`
16.48 Exit status 1
------
Dockerfile:39
--------------------
  37 |
  38 |     ENV NODE_OPTIONS="--max-old-space-size=4096"
  39 | >>> RUN pnpm --filter=app build
  40 |
  41 |     # --------- runner -----------
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm --filter=app build" did not complete successfully: exit code: 1

**Comment by c121914yu** [comment]
docker 问题自己检查是不是合并代码或者网络问题，每次 pr 都会自动 build 测试所以官方代码在 git action 环境中都是可以 build 通过的

**Comment by Essence9999** [comment]
> docker 问题自己检查是不是合并代码或者网络问题，每次 pr 都会自动 build 测试所以官方代码在 git action 环境中都是可以 build 通过的

大佬，有个疑问，下载源码到本地，修改后，直接docker编译不行吗？还得合代码？

**Comment by qianmenfei** [comment]
> [builder 10/10] RUN pnpm --filter=app build:
33.96 Type error: Cannot find module '../../../web/i18n/utils' or its corresponding type declarations.
33.96
33.96 > 1 | import { i18nT } from '../../../web/i18n/utils';
33.96     |                       ^
33.96   2 |
33.96   3 | export type ModelProviderIdType =
33.96   4 |   | 'OpenAI'
34.08 /app/projects/app:
34.08  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  app@4.8.17 build: `next build`
34.08 Exit status 1
------
Dockerfile:44
--------------------
  42 |     ENV NODE_OPTIONS="--max-old-space-size=4096"
  43 |     ENV NEXT_PUBLIC_BASE_URL=$base_url
  44 | >>> RUN pnpm --filter=app build
  45 |
  46 |     # --------- runner -----------
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm --filter=app build" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/lkr9ap82x6k0rphf46bsvlobp

**Comment by erickech** [comment]
请问解决了嘛，我也遇到这个问题
