### ISSUE TITLE
免登陆对话窗口一输入就报错

### ISSUE THREAD

**Issue by Ocean22** [labring/FastGPT#1816]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.4

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**
对话框一输入就报错
![image](https://github.com/labring/FastGPT/assets/45907917/7b9bd225-cd87-4357-a08f-bc78e9f96b97)
![image](https://github.com/labring/FastGPT/assets/45907917/964a0f08-3eb9-4613-9dfa-e6ae60ad7ba8)
![image](https://github.com/labring/FastGPT/assets/45907917/30265bf9-5a67-4fb0-bfdb-8d75a9170767)
![image](https://github.com/labring/FastGPT/assets/45907917/ca1220e1-74ed-449d-9245-19fdd9372810)

**复现步骤**
根据截图即可复现

**预期结果**
修复

**相关截图**

**Comment by c121914yu** [comment]
key 地址不对，自行检查
