### ISSUE TITLE
高级编排-工具调用模块不能调用工具

### ISSUE THREAD

**Issue by Ocean22** [labring/FastGPT#1817]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.4

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**
1、工具调用Http模块发送飞书消息，同样的编排配置，本地私有部署的，单独调试`工具调用`就没问题，整个流程调试和发布应用对话就不行，使用fastgpt.in官网上的就可以
![f4bee981-9d32-4906-b697-5ea4ca95829a](https://github.com/labring/FastGPT/assets/45907917/37a1c9e9-e9f1-4d6a-b562-872a14cf30f6)
![image](https://github.com/labring/FastGPT/assets/45907917/14170886-4561-4551-9902-91b91a69815b)

**复现步骤**
一步步复现

**预期结果**
修复这个问题

**相关截图**

**Comment by sdytzjp** [comment]
我逐步调试也调用不了子模块，工具调用模块直接自己回复了，子模块的描述已经很明确了就是不调用

**Comment by sdytzjp** [comment]
更新，更换了语言模型后，逐步调用可以，但是跟你反映的问题一样，整个流程调试不行，而且ai回复了奇怪的信息，例如，8yjGV2消防演练事项说明”｝。

你有更新@我一下

**Comment by zaoqishibing** [comment]
我也遇到和你一样的问题，请问有解决吗

**Comment by sdytzjp** [comment]
config.json usedInToolCall  toolChoice  functionCall 设置false
