### ISSUE TITLE
英文环境下，等待AI生成回答时显示中文内容

### ISSUE THREAD

**Issue by lientao** [labring/FastGPT#1821]
等待AI回答时，英文界面依然会显示： “知识库搜索”、"AI对话"等中文。期待完成翻译。

<img width="391" alt="let202406212250" src="https://github.com/labring/FastGPT/assets/77399354/01ac53ad-0d92-4d56-81b4-56863ef9f440">

**Comment by xiaoToby** [comment]
你可以在高级编排中更改
![image](https://github.com/labring/FastGPT/assets/40045458/be77f19a-fdcc-453c-8897-0335d851a32f)

**Comment by lientao** [comment]
谢谢，已解决。
