### ISSUE TITLE
免登录链接能否自行设定？

### ISSUE THREAD

**Issue by qiyuanzhang520** [labring/FastGPT#1826]
免登录链接的地址能否自行设定？如fastgpt.com/chat/shareId=16wngsrbtpw2ph18fheuwbg1，ID部分能否自己定义？
在版本更新后，这个ID会发生调整，修改较为麻烦，请问在哪里可以自行设定？

**Comment by c121914yu** [comment]
不支持，要修改就新建一个链接。

**Comment by 1suancaiyu** [comment]
> 免登录链接的地址能否自行设定？如fastgpt.com/chat/shareId=16wngsrbtpw2ph18fheuwbg1，ID部分能否自己定义？ 在版本更新后，这个ID会发生调整，修改较为麻烦，请问在哪里可以自行设定？

请问您现在解决了吗？我现在也遇到了这个问题。
