### ISSUE TITLE
通过工具调用，会先生成回复，然后再进行知识库调用，两次内容还不一样

### ISSUE THREAD

**Issue by masktone** [labring/FastGPT#1831]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**
![工具调用](https://github.com/labring/FastGPT/assets/124564913/d48f87a2-a9f4-4d19-ae20-86cdafa91d8b)

**复现步骤**
使用xinference接入的qwen2模型，前期xinference出现思考过程，已通过升级最新xinference解决了这个问题，但仍出现在工具调用时，先进行问题回答，然后再知识库搜索
**预期结果**

**相关截图**

**Comment by masktone** [comment]
###角色
你是专业的论文编写高手，可以编写长篇论文报告。

###技能
通过调用工具，获得知识素材，然后参照素材进行论文编写。

###工作流程
1.首先理解用户的论文主题。
2.为论文设计提纲框架。
3.调用工具，选择合适的api获得素材。
4.参照素材内容，编写报告，检查报告内容，无误后输出。

###限制
1.用中文进行回复。

**Comment by lijiajun1997** [comment]
你都让他思考了嘛，当然会先回答再调用，你直接让他先调用再思考试试？

**Comment by MZY199603** [comment]
我也想问一下这个相关问题，我使用lmploy部署的qwen2-72B-Instruct，使用的它进行工具调用，没有思考过程，在工具调用时就回复了，作者你是如何解决这个问题的

**Comment by slot181** [comment]
我更加搞不懂了，提示词模式下AI的回复是空的，但在调试里上下文中AI的回复明明是有回复，只能看到一个工具调用……

**Comment by Zhenyi-Wang** [comment]
试下提示词里显式指定是否输出？比如
1.首先理解用户的论文主题，***不要回复***。
...

但我的理解里面，LLM所谓的“思考”，就是靠输出。。例如COT，本质上是增加LLM思考的时间，同时靠着前期输出的思考内容，指导后续文本的生成。
