### ISSUE TITLE
知识库上传8M docx报Timeout

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1832]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
日志好像也没报啥错
![image](https://github.com/labring/FastGPT/assets/66725845/bb701a32-df6e-4473-9343-64ede2503e56)

**复现步骤**
上传一个7.83 MB (8,212,029 字节)的docx文档，一直卡在等待着
![image](https://github.com/labring/FastGPT/assets/66725845/f21bb7c7-6f64-47aa-92be-c4e3ffae71a7)

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/66725845/af20c3e6-ff57-4e89-bd03-ef5182375c9e)

**Comment by c121914yu** [comment]
没遇到，，看看自己服务器负载
