### ISSUE TITLE
本地代码开发，启动后提示Can't resolve 'katex/dist/katex.min.css'

### ISSUE THREAD

**Issue by Jiang-Wan** [labring/FastGPT#1836]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**
pnpm对应的库也是安装完成了的
![问题1](https://github.com/labring/FastGPT/assets/57851281/db4ec105-71b8-4717-af14-e583020e5cf9)
唯一一个问题，就是自动执行postinstall.sh出错，我已经手动执行，并且成功执行
![wenti2](https://github.com/labring/FastGPT/assets/57851281/971f5174-b8d9-449c-9023-d6b4ba45c33b)
但最后运行起来后，提示这个错误
![image](https://github.com/labring/FastGPT/assets/57851281/ca7fb508-5410-4546-96c9-07fd3aac3d88)

node的版本是：
![image](https://github.com/labring/FastGPT/assets/57851281/f578092c-92ca-4188-a729-0c26858aaaa3)
pnpm的版本是：
![image](https://github.com/labring/FastGPT/assets/57851281/e326c87f-c7da-44ea-95ba-2f642564d78f)

是否是还有什么库没安装完毕呢？
**复现步骤**

**预期结果**
能正常启动程序
**相关截图**

**Comment by Jiang-Wan** [comment]
操作系统是Window 10

**Comment by Jiang-Wan** [comment]
在主目录，使用pnpm add katex -D 即可

**Comment by zzz0908** [comment]
@Jiang-Wan  刚踩了这个坑 其实是因为目录中有中文字符导致的 改成英文在重新安装依赖就好了
