### ISSUE TITLE
HTTP模块调用第三方应用报错：self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#1837]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我们在 HTTP模块中调用ansible的api, ansible是自签发证书，我们也在Fastgpt这边部署了ansible的根证书，但是调用的时候报错：
{
"error": {
"message": "self-signed certificate in certificate chain",
"name": "Error",
"method": "post",
"baseURL": "
http://fastgpt-xxxxxx:3000/"
,
"url": "
[https://awx.apps.os.xxxxxx.com/api/v2/job_templates/116/launch/"](https://awx.apps.os.xxxxxxxxx.com/api/v2/job_templates/116/launch/%22)
,
"code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**复现步骤**

**预期结果**
能够顺利调用到自签发证书的第三方应用

**相关截图**
{
"error": {
"message": "self-signed certificate in certificate chain",
"name": "Error",
"method": "post",
"baseURL": "
http://fastgpt-xxxxxx:3000/"
,
"url": "
[https://awx.apps.os.xxxxxx.com/api/v2/job_templates/116/launch/"](https://awx.apps.os.xxxxxxxxx.com/api/v2/job_templates/116/launch/%22)
,
"code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by c121914yu** [comment]
看着是这个地址就是错的

**Comment by ppkitty** [comment]
请问是哪个地址错了呢？fastgpt那个还是第三方应用，能不能给一个正确的例子呢？谢谢

**Comment by c121914yu** [comment]
> 请问是哪个地址错了呢？fastgpt那个还是第三方应用，能不能给一个正确的例子呢？谢谢

请求的接口报错。和fastgpt没关系。

**Comment by ppkitty** [comment]
是请求的接口报错：self-signed certificate in certificate chain，这个错是fastgpt没有部署ansible的自签发证书。问题是我们在Fastgpt部署了ansible的根证书还会报这个错。但在其他的应用中同样的根部署，同样的调用就可以成功。所以想理解下fastgpt调用根证书是怎么调的，是不是我们部署得有问题。

**Comment by c121914yu** [comment]
> 是请求的接口报错：self-signed certificate in certificate chain，这个错是fastgpt没有部署ansible的自签发证书。问题是我们在Fastgpt部署了ansible的根证书还会报这个错。但在其他的应用中同样的根部署，同样的调用就可以成功。所以想理解下fastgpt调用根证书是怎么调的，是不是我们部署得有问题。

没啥特殊操作，就是正常 request

**Comment by cloudtuotuo** [comment]
我这边也复现了，在nginx上部署了AD CS生成的内网证书，代理searxng服务，浏览器访问、curl都可以正常访问https，但在fastgpt里调用时就会报这个错误
应该是fastgpt服务端需要也导入内网证书才行

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/1830
参考
