### ISSUE TITLE
使用chatglm2回答的问题质量很差

### ISSUE THREAD

**Issue by bruceye777** [labring/FastGPT#184]
基于此文档《3分钟在Fastgpt上用上GLM》
https://doc.fastgpt.run/docs/other/ChatGLM2/

不过有报错
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 945, in json
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.

修改了代码
yield "{}".format(chunk.json(exclude_unset=True, ensure_ascii=False))
修改为
yield "{}".format(chunk.json())

然后分别尝试使用了QA拆分和CSV导入两种方式，原始QA数据就是20个问题。

测试下来回答质量很差，可以说完全不着边际
![image](https://github.com/labring/FastGPT/assets/41668200/d23f3d62-8fa1-44cb-ab2b-0e0ecbd26ae7)
![image](https://github.com/labring/FastGPT/assets/41668200/2dea8a9c-e1f8-4286-9fdc-f0c0febbac05)
![image](https://github.com/labring/FastGPT/assets/41668200/c14b6606-35c1-4c07-96f5-47ac8db07226)
![image](https://github.com/labring/FastGPT/assets/41668200/55f2dd1e-182f-4e13-a6ee-9008206ae5db)
完全匹配不到数据集中的内容
![image](https://github.com/labring/FastGPT/assets/41668200/e0d8a194-7a94-46f6-a419-0e38313e048c)
![image](https://github.com/labring/FastGPT/assets/41668200/be1eb550-c74f-4eb2-b81b-76b20bf19b5f)

这是哪里出了问题啊？

**Comment by c121914yu** [comment]
glm是语言模型，和匹配没关系

**Comment by bruceye777** [comment]
那个脚本用的向量模型是m3e-large，我看在huggingface上面下载量排在很前面，那应该用什么模型效果会更好点了？ @c121914yu

**Comment by c121914yu** [comment]
m3e要归一化并且升纬到1536才能用

**Comment by bruceye777** [comment]
我看了原始脚本有升纬到1536看，至于归一化我在encode加入了参数normalize_embeddings=True，不过效果依旧，还是匹配不到文本
![image](https://github.com/labring/FastGPT/assets/41668200/f4d33af7-eba3-42ab-ba69-b2d47ff2013f)

**Comment by azoth07** [comment]
glm自身语义理解问题，感觉相比gpt需要更多prompt去补充

**Comment by winnie1228** [comment]
> 我看了原始脚本有升纬到1536看，至于归一化我在encode加入了参数normalize_embeddings=True，不过效果依旧，还是匹配不到文本 ![image](https://user-images.githubusercontent.com/41668200/261519042-f4d33af7-eba3-42ab-ba69-b2d47ff2013f.png)

请问这个脚本在哪里获取的，方便提供下吗？ 我是想接m3e-base

**Comment by bruceye777** [comment]
就在这个项目里面提供的，你搜下， openai_api.py

**Comment by bruceye777** [comment]
> > 我看了原始脚本有升纬到1536看，至于归一化我在encode加入了参数normalize_embeddings=True，不过效果依旧，还是匹配不到文本 ![image](https://user-images.githubusercontent.com/41668200/261519042-f4d33af7-eba3-42ab-ba69-b2d47ff2013f.png)
> 
> 请问这个脚本在哪里获取的，方便提供下吗？ 我是想接m3e-base

就在这个项目里面提供的，你搜下， openai_api.py

**Comment by yaya929** [comment]
请问解决了吗

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is it solved?

**Comment by yaya929** [comment]
我也是这个问题，请问源码哪里需要修改

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also have the same problem. May I ask where in the source code I need to modify it?

**Comment by lonngxiang** [comment]
我这是m3e向量检索相似度非常小，每次回答都没有引用
![eea9ef692a027c35d2050e46f939098](https://github.com/labring/FastGPT/assets/40717349/3f958f1c-0222-4634-a3fd-cc5b0bb50e07)
