### ISSUE TITLE
当输入框有一些特殊字符时频繁弹框错误提示

### ISSUE THREAD

**Issue by mwnu** [labring/FastGPT#1840]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.4

**问题描述, 日志截图**
像是什么正则表达式错误：
```
[Info] 2024-06-25 07:02:48 Request start /api/core/chat/inputGuide/query 
[Error] 2024-06-25 07:02:48 Api response error: /api/core/chat/inputGuide/query, Invalid regular expression: /一个sql语句是这样的：
```
INSERT INTO github_project(
    d/: Unterminated group 
{
  message: 'Invalid regular expression: /一个sql语句是这样的：\n' +
    '```\n' +
    'INSERT INTO github_project(\n' +
    '    d/: Unterminated group',
  stack: 'SyntaxError: Invalid regular expression: /一个sql语句是这样的：\n' +
    '```\n' +
    'INSERT INTO github_project(\n' +
    '    d/: Unterminated group\n' +
    '    at RegExp (<anonymous>)\n' +
    '    at d (/app/projects/app/.next/server/pages/api/core/chat/inputGuide/query.js:1:9860)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /app/projects/app/.next/server/pages/api/v1/chat/completions.js:1:5672\n' +
    '    at async K (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
    '    at async U.render (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)\n' +
    '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/next-server.js:600:9)\n' +
    '    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/next-server.js:269:37)\n' +
    '    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/base-server.js:816:17)\n' +
    '    at async invokeRender (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/lib/router-server.js:174:21)'
}
[Info] 2024-06-25 07:02:49 Request start /api/core/chat/inputGuide/query 
```
```

**相关截图**

![image](https://github.com/labring/FastGPT/assets/45463732/c79157da-b9f3-4551-a6e1-7d76a2c92a49)

**Comment by c121914yu** [comment]
新版本已经修复了
