### ISSUE TITLE
知识库上传文件后，不能设置chunkSize参数

### ISSUE THREAD

**Issue by 15731807423** [labring/FastGPT#1842]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**
知识库上传文件后，不能设置chunkSize参数，只能通过接口访问设置
![image](https://github.com/labring/FastGPT/assets/45228445/82239467-bb45-407f-8e82-4c6e765c9263)
![image](https://github.com/labring/FastGPT/assets/45228445/8051f839-62fb-44f5-ba1e-3a03db3ebf3a)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
qa 不能设置，取决于模型。

**Comment by 15731807423** [comment]
> qa 不能设置，取决于模型。

什么玩意儿就给我关了，不设置你试试能出来吗，用模型的maxContext乘以0.55，值大于30000预览就报错，出来的结果全是段落，一个问题没有
