### ISSUE TITLE
希望增加多模态模型下的图片/文件输入交互入口和发布应用图片/文件上传的API

### ISSUE THREAD

**Issue by XiangyuTang** [labring/FastGPT#1843]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
期望功能1: 聊天图片上传分析交互
比如类似Dify的这种入口，这个图片上传是一个功能按钮，开启后在聊天窗口即可上传图片

![image](https://github.com/labring/FastGPT/assets/47786354/5c8ea519-25ed-44eb-bad6-031646debfbb)

期望功能2: 聊天文件上传分析交互
如果用户想对文件做分析，比如对一个文件生成摘要的需求，能否在聊天窗口直接上传该文件？

**应用场景**
很多答疑场景用户都会直接甩一张图片过来，然后问这个图上的问题，或者模型需要基于分析图片中的要素回答用户的问题。
文件同理

**Comment by c121914yu** [comment]
重复
