### ISSUE TITLE
4.8.5 未配置商业版链接

### ISSUE THREAD

**Issue by xfghvgnfyjssjgte** [labring/FastGPT#1847]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.5
- [ x] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
升级为4.8.5-alpha 提示 未配置商业版链接
**复现步骤**

**预期结果**

**相关截图**

**Comment by xfghvgnfyjssjgte** [comment]
不影响任何使用，只是在应用界面刚打开时会有这么一个弹出窗口

**Comment by c121914yu** [comment]
正式版修复下
