### ISSUE TITLE
当使用了api调用应用时如果传入了system参数会导致知识库失效

### ISSUE THREAD

**Issue by Mgrsc** [labring/FastGPT#1848]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
V4.8.5

**问题描述, 日志截图**
只要带有system-prompt参数使用api请求应用，知识库失效不会进行知识库搜索
![image](https://github.com/labring/FastGPT/assets/118801216/13888ded-8de5-429c-a13b-33e55429180d)

将system-prompt设置为空，知识库依然不会进行调用搜索
![image](https://github.com/labring/FastGPT/assets/118801216/1562d248-1917-44a6-bfb5-98a832277c4a)

删除system-prompt恢复正常
![image](https://github.com/labring/FastGPT/assets/118801216/6b3d03ac-e88a-4c97-a934-24620572f790)

**复现步骤**
带有系统提示词进行请求

**预期结果**
无论是否带有system-prompt都应该进行知识库的搜索返回

**Comment by c121914yu** [comment]
<img width="1134" alt="image" src="https://github.com/labring/FastGPT/assets/50446880/dc268f61-e781-45d7-a87d-825be2812bcb">
<img width="635" alt="image" src="https://github.com/labring/FastGPT/assets/50446880/a3a3c5ef-d6c4-4bd5-9775-b5e848e8c820">

未发现问题，检查你的中间过程是否有影响

**Comment by c121914yu** [comment]
o 我想我可能知道是什么问题，应该是问题优化导致的，多了 system 后，历史记录截取出现了问题，导致问题优化结果异常，搜不到内容。
