### ISSUE TITLE
问题回复空白！！

### ISSUE THREAD

**Issue by Chenzhexian** [labring/FastGPT#1851]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v5.8.5

**问题描述, 日志截图**
现在是一个应用里，问题分类后调用另一个应用
![image](https://github.com/labring/FastGPT/assets/92191856/8e1ac095-cb3d-4031-b193-ffc728eb0f8f)
然后就会出现回复是空白的情况
![image](https://github.com/labring/FastGPT/assets/92191856/e031e02b-dbf7-4e41-99c2-aaa225258018)
另一个应用具体是这样的
![image](https://github.com/labring/FastGPT/assets/92191856/d8bcaf46-46c4-472c-9251-1597fab536df)
单独使用这个应用是正常的
![image](https://github.com/labring/FastGPT/assets/92191856/9898664e-2320-4c48-b398-0d49ec574388)

**复现步骤**

**预期结果**

**相关截图**
空白回复查看详情
![image](https://github.com/labring/FastGPT/assets/92191856/88f441d7-df81-43c5-a1d0-dcfe34800b7a)
日志好像也没报错
![image](https://github.com/labring/FastGPT/assets/92191856/27f1bced-197c-49e0-bdf1-b140e5a9f261)

**Comment by Chenzhexian** [comment]
docker 部署的，版本4.8.5

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/114d372a-3834-46ad-8fc1-5a376828cac7)
我创建了一个简单的例子，暂时没遇到该问题

**Comment by c121914yu** [comment]
你这个看着像之前有问题的分类连线，试试删除分类，重新加进去在连线。

**Comment by Chenzhexian** [comment]
> 你这个看着像之前有问题的分类连线，试试删除分类，重新加进去在连线。

删了重新建也不行，我这个问题是可以进到那个应用里，也有回复，就是到最后一步返回的是空白，应该回复下面截图的内容的
![image](https://github.com/labring/FastGPT/assets/92191856/e541967e-da35-4411-9743-2e93335174ca)

**Comment by c121914yu** [comment]
> > 你这个看着像之前有问题的分类连线，试试删除分类，重新加进去在连线。
> 
> 删了重新建也不行，我这个问题是可以进到那个应用里，也有回复，就是到最后一步返回的是空白，应该回复下面截图的内容的 ![image](https://private-user-images.githubusercontent.com/92191856/342998782-e541967e-da35-4411-9743-2e93335174ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzMzNDAsIm5iZiI6MTcxOTM3MzA0MCwicGF0aCI6Ii85MjE5MTg1Ni8zNDI5OTg3ODItZTU0MTk2N2UtZGEzNS00NDExLTk3NDMtMmU5MzMzNTE3NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAzMzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZjI5NmU0NDczOTU1ZTE0YTllYjk3NzM3ZThkYWVjZjI1NzViYzNjMTI4MzUxZDg4NGZkNzkyMDhmZDRjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fbbtAq21yUDiiG0v3CNDXteaY9TDooK4k23z4P2wqFk)

你的调用记录里，都没应用调用：
![image](https://github.com/labring/FastGPT/assets/50446880/5d1fa755-0087-4d2e-a8e5-8e71f8fdb9b9)

**Comment by Chenzhexian** [comment]
> > > 你这个看着像之前有问题的分类连线，试试删除分类，重新加进去在连线。
> > 
> > 
> > 删了重新建也不行，我这个问题是可以进到那个应用里，也有回复，就是到最后一步返回的是空白，应该回复下面截图的内容的 ![image](https://private-user-images.githubusercontent.com/92191856/342998782-e541967e-da35-4411-9743-2e93335174ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzMzNDAsIm5iZiI6MTcxOTM3MzA0MCwicGF0aCI6Ii85MjE5MTg1Ni8zNDI5OTg3ODItZTU0MTk2N2UtZGEzNS00NDExLTk3NDMtMmU5MzMzNTE3NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAzMzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZjI5NmU0NDczOTU1ZTE0YTllYjk3NzM3ZThkYWVjZjI1NzViYzNjMTI4MzUxZDg4NGZkNzkyMDhmZDRjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fbbtAq21yUDiiG0v3CNDXteaY9TDooK4k23z4P2wqFk)
> 
> 你的调用记录里，都没应用调用： ![image](https://private-user-images.githubusercontent.com/50446880/342999204-5d1fa755-0087-4d2e-a8e5-8e71f8fdb9b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzM1OTksIm5iZiI6MTcxOTM3MzI5OSwicGF0aCI6Ii81MDQ0Njg4MC8zNDI5OTkyMDQtNWQxZmE3NTUtMDA4Ny00ZDJlLWE4ZTUtOGU3MWY4ZmRiOWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAzNDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NmMxODVjODc3NDEyN2Y0Yzk2OGJjMDQzZmNjOGQxNTQwYjY3ZWUxMDE2N2UxZWRiMTc0OWQxYjBkNDkwMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0wdFT-DFkqlt53aErTFALggbsa8LEP_vvGjmo_wXHLM)

你的意思是说没走到应用里吗？但是问题分类已经定位到这个分类了，为啥没走进去呢

**Comment by c121914yu** [comment]
> > > > 你这个看着像之前有问题的分类连线，试试删除分类，重新加进去在连线。
> > > 
> > > 
> > > 删了重新建也不行，我这个问题是可以进到那个应用里，也有回复，就是到最后一步返回的是空白，应该回复下面截图的内容的 ![image](https://private-user-images.githubusercontent.com/92191856/342998782-e541967e-da35-4411-9743-2e93335174ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzMzNDAsIm5iZiI6MTcxOTM3MzA0MCwicGF0aCI6Ii85MjE5MTg1Ni8zNDI5OTg3ODItZTU0MTk2N2UtZGEzNS00NDExLTk3NDMtMmU5MzMzNTE3NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAzMzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZjI5NmU0NDczOTU1ZTE0YTllYjk3NzM3ZThkYWVjZjI1NzViYzNjMTI4MzUxZDg4NGZkNzkyMDhmZDRjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fbbtAq21yUDiiG0v3CNDXteaY9TDooK4k23z4P2wqFk)
> > 
> > 
> > 你的调用记录里，都没应用调用： ![image](https://private-user-images.githubusercontent.com/50446880/342999204-5d1fa755-0087-4d2e-a8e5-8e71f8fdb9b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzM1OTksIm5iZiI6MTcxOTM3MzI5OSwicGF0aCI6Ii81MDQ0Njg4MC8zNDI5OTkyMDQtNWQxZmE3NTUtMDA4Ny00ZDJlLWE4ZTUtOGU3MWY4ZmRiOWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAzNDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NmMxODVjODc3NDEyN2Y0Yzk2OGJjMDQzZmNjOGQxNTQwYjY3ZWUxMDE2N2UxZWRiMTc0OWQxYjBkNDkwMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0wdFT-DFkqlt53aErTFALggbsa8LEP_vvGjmo_wXHLM)
> 
> 你的意思是说没走到应用里吗？但是问题分类已经定位到这个分类了，为啥没走进去呢

上面提了，新建个问题分类试试，或者debug模式看看

**Comment by i-square** [comment]
这个问题我也遇到了，原因是问题分类没有按预期回复id，分类结果里会显示最后一个类别，但实际上会在这里中断流程，不会继续往下走了。也向 @c121914yu 反馈下，希望能在UI上更直观地显示原因，或许可以加一个分类失败的出口？

你如果能看到调用的LLM的log就知道了，比如正常回复：类型ID："wqre"，导致中断流程的回复："对不起，您的问题无法被分 类到任何给定的类型中。"

**Comment by Chenzhexian** [comment]
> 这个问题我也遇到了，原因是问题分类没有按预期回复id，分类结果里会显示最后一个类别，但实际上会在这里中断流程，不会继续往下走了。也向 @c121914yu 反馈下，希望能在UI上更直观地显示原因，或许可以加一个分类失败的出口？
> 
> 你如果能看到调用的LLM的log就知道了，比如正常回复：类型ID："wqre"，导致中断流程的回复："对不起，您的问题无法被分类到任何给定的类型中。"

没错是这个问题，分类失败了

**Comment by sdytzjp** [comment]
> > 这个问题我也遇到了，原因是问题分类没有按预期回复id，分类结果里会显示最后一个类别，但实际上会在这里中断流程，不会继续往下走了。也向 @c121914yu 反馈下，希望能在UI上更直观地显示原因，或许可以加一个分类失败的出口？
> > 你如果能看到调用的LLM的log就知道了，比如正常回复：类型ID："wqre"，导致中断流程的回复："对不起，您的问题无法被分类到任何给定的类型中。"
> 
> 没错是这个问题，分类失败了

我的问题分类也是总到最后一个分类，这个怎么解决

**Comment by Chenzhexian** [comment]
> > > 这个问题我也遇到了，原因是问题分类没有按预期回复id，分类结果里会显示最后一个类别，但实际上会在这里中断流程，不会继续往下走了。也向 @c121914yu 反馈下，希望能在UI上更直观地显示原因，或许可以加一个分类失败的出口？
> > > 你如果能看到调用的LLM的log就知道了，比如正常回复：类型ID："wqre"，导致中断流程的回复："对不起，您的问题无法被分类到任何给定的类型中。"
> > 
> > 
> > 没错是这个问题，分类失败了
> 
> 我的问题分类也是总到最后一个分类，这个怎么解决

我是这么搞的
提示词加上如果无法确定问题分类都归为其他问题，然后加一个其他问题的分类，配上兜底策略

**Comment by sdytzjp** [comment]
> 并不会，没任何结果，会使用最后一个选项
> 
> <img alt="image" width="768" src="https://private-user-images.githubusercontent.com/50446880/345732618-10793b1e-71fb-4dc8-99fd-c0e8a564b07a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODMxNjgsIm5iZiI6MTcyMDA4Mjg2OCwicGF0aCI6Ii81MDQ0Njg4MC8zNDU3MzI2MTgtMTA3OTNiMWUtNzFmYi00ZGM4LTk5ZmQtYzBlOGE1NjRiMDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA4NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZTc2ZjM3YjAyMmM0YWExYWI5OWJjMzQ0MGFlOGM2ZjBlMDMwMTI4ZTliYzY4MzNiZmFiYzJiYzA4NWZmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7o-Ey1yOqkNBx1qmGaW5O6pfq3gz4P-8NP1LIdatsH8">

是的，不管怎么样都是只选择最后一个

**Comment by i-square** [comment]
> 并不会，没任何结果，会使用最后一个选项
> 
> <img alt="image" width="768" src="https://private-user-images.githubusercontent.com/50446880/345732618-10793b1e-71fb-4dc8-99fd-c0e8a564b07a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODYyMzMsIm5iZiI6MTcyMDA4NTkzMywicGF0aCI6Ii81MDQ0Njg4MC8zNDU3MzI2MTgtMTA3OTNiMWUtNzFmYi00ZGM4LTk5ZmQtYzBlOGE1NjRiMDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOTRkNzFmOTg3MmM3MzJjMDdjYTdlODljYjYwZTI3ZTc5NzgyZGNkYzlkMTUxMGRhNzUxYWE4MDRmODgxMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.roaAu-lqN1vEWaVmb9vdeCSa1x738bUOupFsut7NooY">

那目前的表现来看就是bug了，我特地截了个gif图，我用了个测试api一定不会正确回复，如果使用最后一项的话，应该输出“分类3”，但实际上流程就中断了，输出是空白

![分类停止](https://github.com/labring/FastGPT/assets/5228438/49e7989a-f2ce-4595-bcda-a5f9c5093f57)
