### ISSUE TITLE
使用iPhone手机访问对话页面，聊天窗口中功能按钮样式显示异常

### ISSUE THREAD

**Issue by huangxin995** [labring/FastGPT#1858]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号:  v4.8.4（docker-compose部署）

**问题描述, 日志截图**
使用iPhone手机访问对话页面，聊天窗口中功能按钮样式显示异常，使用Chrome浏览器中的模拟手机窗口样式一切正常。
手机型号：iPhone12 pro
浏览器：Safari、Chrome，显示都是相同的异常

![iPhone12pro真机访问](https://github.com/labring/FastGPT/assets/40195974/56dc85e2-15b8-435b-9add-b1fa3b65bea0)
![Chrome浏览器模拟手机访问](https://github.com/labring/FastGPT/assets/40195974/94c392c6-0739-44f8-abfe-1da81e60c418)

**复现步骤**
使用iPhone访问任一对话页面进行问答交互后均可复现

**预期结果**
修复异常样式，与PC上浏览器访问效果一致

**相关截图**

**Comment by c121914yu** [comment]
换 13 就好了🧐

**Comment by huangxin995** [comment]
> 换 13 就好了🧐

兄弟，刚看到这个回复以为是开玩笑的，拿了13试了下发现真的显示正常，这个可以理解为不是应用的问题，是手机终端的问题吗？

**Comment by c121914yu** [comment]
> > 换 13 就好了🧐
> 
> 兄弟，刚看到这个回复以为是开玩笑的，拿了13试了下发现真的显示正常，这个可以理解为不是应用的问题，是手机终端的问题吗？

😂是这个组件库兼容旧版 ios 有点问题，模拟器模拟不出，又没 12 的手机，就一直没管他了。

**Comment by huangxin995** [comment]
谢谢答复，issue先关了

**Comment by move132** [comment]
```
 <Flex
      {...controlContainerStyle}
      borderRadius={'sm'}
      overflow={'hidden'}
      border={theme.borders.base}
      alignItems={'center'}
      // 最后一个子元素，没有border
      css={css({
        '& > *:last-child, & > *:last-child svg': {
          borderRight: 'none',
          borderRadius: 'md'
        }
      })}
    >
```

加上这行    alignItems={'center'} 可以解决

**Comment by xiafeng111** [comment]
但是为什么Iphone XS的一些型号不仅样式异常，而且还是以英文显示的
