### ISSUE TITLE
本地开发/mongo compass连不上mongo容器

### ISSUE THREAD

**Issue by Madilynalisa** [labring/FastGPT#1859]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**
docker运行成功，知识库问答功能测试正常。
尝试用本地开发，报错
<img width="1178" alt="截屏2024-06-26 15 23 22" src="https://github.com/labring/FastGPT/assets/87683135/cde9981f-5e0c-4d42-b865-f28f7c5ed3e5">

**复现步骤**
利用mongo compass测试连接，但报错

**预期结果**

**相关截图**
<img width="722" alt="截屏2024-06-26 15 25 52" src="https://github.com/labring/FastGPT/assets/87683135/59e5c6e1-70d9-45f4-8fec-0d0f5244d737">
docker中mongo容器日志截图（红框为mongo compass连接测试时返回的日志）：
<img width="1007" alt="截屏2024-06-26 15 26 38" src="https://github.com/labring/FastGPT/assets/87683135/e80532ea-542e-4bd3-961c-5dd676c5b7a7">

**Comment by gaord** [comment]
如果非容器部署mongo开发环境，需要hosts文件加一行：127.0.0.1 mongo。然后使用mongo连接数据库

**Comment by c121914yu** [comment]
数据库问题自行 mongo 社区搜搜学习，

**Comment by Madilynalisa** [comment]
> 数据库问题自行 mongo 社区搜搜学习。 先先确保你的 0.0.0.0 是否可以访问到服务。

您好，后续用navicat进行了测试，localhost，127.0.0.1都能正常连接到mongo容器，但在fastgpt中的.env.local修改地址，还是同样连接不上，困扰很久了，是因为不支持mac m2吗（mongo版本为5.0.18）？

下附.env.local以及dockercompose.yml配置
<img width="1024" alt="截屏2024-07-03 09 28 40" src="https://github.com/labring/FastGPT/assets/87683135/ea81b3c5-3cdc-4157-82eb-36b37455078f">
<img width="1082" alt="截屏2024-07-03 09 29 32" src="https://github.com/labring/FastGPT/assets/87683135/83121d89-9ffb-46fc-84e3-430b6575f571">

**Comment by c121914yu** [comment]
> > 数据库问题自行 mongo 社区搜搜学习。 先先确保你的 0.0.0.0 是否可以访问到服务。
> 
> 您好，后续用navicat进行了测试，localhost，127.0.0.1都能正常连接到mongo容器，但在fastgpt中的.env.local修改地址，还是同样连接不上，困扰很久了，是因为不支持mac m2吗（mongo版本为5.0.18）？
> 
> 下附.env.local以及dockercompose.yml配置
> <img width="1024" alt="截屏2024-07-03 09 28 40" src="https://github.com/labring/FastGPT/assets/87683135/ea81b3c5-3cdc-4157-82eb-36b37455078f">
> <img width="1082" alt="截屏2024-07-03 09 29 32" src="https://github.com/labring/FastGPT/assets/87683135/83121d89-9ffb-46fc-84e3-430b6575f571">
> 
> 

不要用 navicat，他隐藏了很多参数

**Comment by Madilynalisa** [comment]
解决了，不好意思，是自己写的参数问题...
directConnection=true和前面的参数用&连接.....
