### ISSUE TITLE
分享页面，在提问后，ai回答过程中，快速点击新对话按钮，会导致显示内容不正确

### ISSUE THREAD

**Issue by xiaoqiqi001** [labring/FastGPT#1860]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
官方线上版本
- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
左侧对话标题与右侧内容不一致，其实本应该开启新对话。
![企业微信截图_17193898243684](https://github.com/labring/FastGPT/assets/6127557/6cf55338-fbb7-4537-848a-c8c9fa7a5d24)

**复现步骤**
分享页面，保证页面至少有三个新对话，开始提问后，在ai回答的过程中，快速点击开启新对话
**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
忘记关联：
新版禁止了首轮对话过程中，新开对话
