### ISSUE TITLE
v4.6.8之后的版本修改config.json文件后不自动加载，必须重启容器才能生效

### ISSUE THREAD

**Issue by i-square** [labring/FastGPT#1861]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: `v4.8.4-fix`

**问题描述, 日志截图**
之前我使用了v4.6.8版本的本地部署，修改 `config.json` 文件之后过一会儿会自动重新加载，这样可以做到不停服更新配置

但是最近更新到了最新版本 `v4.8.4`，发现无法自动加载配置，修改之后必须restart容器才能生效

请问这是符合预期的变化吗？为什么去掉这个功能呢？

**复现步骤**
`v4.6.8` 版本和 `v4.8.4-fix` 版本修改 `config.json` 文件之后看是否生效

**预期结果**
修改 `config.json` 文件之后不停服即可生效

**相关截图**

**Comment by c121914yu** [comment]
没哪个版本不需要重启

**Comment by i-square** [comment]
> 没哪个版本不需要重启

我翻了翻提交记录，是从 `4.6.9-alpha` 开始去掉了刷新config的定时任务：https://github.com/labring/FastGPT/pull/918/commits/f0fe8fba9c915e27db7a0bc4611677e1e5fe02c7#diff-0a87f3b3657de120dd17f8c74a681455b88097e2f0ca6cb7955d49b34b0f715cL10

这是出于什么原因？

**Comment by c121914yu** [comment]
> > 没哪个版本不需要重启
> 
> 我翻了翻提交记录，是从 `4.6.9-alpha` 开始去掉了刷新config的定时任务 `setUpdateSystemConfigCron`：[f0fe8fb#diff-0a87f3b3657de120dd17f8c74a681455b88097e2f0ca6cb7955d49b34b0f715cL10](https://github.com/labring/FastGPT/commit/f0fe8fba9c915e27db7a0bc4611677e1e5fe02c7#diff-0a87f3b3657de120dd17f8c74a681455b88097e2f0ca6cb7955d49b34b0f715cL10)
> 
> 这是出于什么原因？

o记起来了，因为商业版有后台了，不需要定时刷新了。

**Comment by c121914yu** [comment]
补充一下，这个需求背景是有个 admin 管理端，在上面改了配置后需要同步到 fastgpt，一开始没想到方法，就搞了个定时器。
后面发现可以通过监听数据库方式，于是就删除了。😂所以没考虑过改配置文件等定时器的问题。
