### ISSUE TITLE
m3e接入one-api的问题

### ISSUE THREAD

**Issue by lingaoan2024** [labring/FastGPT#1865]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**
无法正常访问one-api渠道的embedding模型
![image](https://github.com/labring/FastGPT/assets/172566511/d0c607a0-bf12-4816-86ca-f56a706ef855)
![image](https://github.com/labring/FastGPT/assets/172566511/734c6049-d201-4664-861c-a111b06eb73d)
直接请求docker部署的m3e如下图，是可以正常向量化
![image](https://github.com/labring/FastGPT/assets/172566511/4c1d3839-f531-40fb-931e-715b369882e7)
下面是oneapi渠道配置
![image](https://github.com/labring/FastGPT/assets/172566511/58b98bbd-af81-4662-bf6f-20f7c238fdbd)
 下面是测试截图
![image](https://github.com/labring/FastGPT/assets/172566511/b7f3e9d3-967b-46ab-8626-939e814d84ed)
尝试过配置中将url替换为http://host.docker.internal:6008/v1/embeddings
或者类型各种替换尝试，均可以正常报错，但是测试都是404
使用ollama中的chevalblanc/acge_text_embedding:latest也是一样无法找到
----------------------------------------
请各位大神帮忙看看
**复现步骤**
按照官方文档部署m3e:https://doc.fastgpt.in/docs/development/custom-models/m3e/
docker安装脚本如下：
docker run -d --name m3e -p 6008:6008 -e SK-KEY=sk-aaabbbcccdddeeefffggghhhiiijjjkkk registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest
**预期结果**
希望能正常使用embedding
**相关截图**

**Comment by lingaoan2024** [comment]
补充一下：
config.json配置如下：
![image](https://github.com/labring/FastGPT/assets/172566511/67cd2263-80e2-4355-b387-65cbbcadcc5b)
是否可以配置vectorModels像配置reRankModels一样，跳过oneapi？

**Comment by ajiader** [comment]
one api m3e配置截图  估计是url问题

**Comment by Essence9999** [comment]
sudo docker logs m3e
看日志报啥错

**Comment by lingaoan2024** [comment]
> sudo docker logs m3e 看日志报啥错

m3e中没有请求相关的日志，请求还未到模型

**Comment by lingaoan2024** [comment]
> one api m3e配置截图 估计是url问题

url没有问题呢，配置中host.docker.internal是因为one api部署在docker中

**Comment by lingaoan2024** [comment]
在另一台电脑上重新来了一遍，目前已解决，唯一区别就是one-api的令牌配置
昨天配置时，选择了模型范围，今天未选择模型fan范围，已经可以创建索引
![image](https://github.com/labring/FastGPT/assets/172566511/9d740dd3-7c71-499d-8053-05a89640e946)

**Comment by a1258771** [comment]
老哥， 你 使用ollama中的chevalblanc/acge_text_embedding:latest 可以成功吗。 能教下嘛
