### ISSUE TITLE
分享链接对话，显示对话时间

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1867]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
用户对话，能够显示对话时间，便于后期根据时间查看自己的问题
**应用场景**
![image](https://github.com/labring/FastGPT/assets/66725845/c5e731db-89e0-44f0-8846-1f92d238283b)

**相关示例**

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3024
