### ISSUE TITLE
one api使用方式

### ISSUE THREAD

**Issue by av8dtop** [labring/FastGPT#187]
新版的狀況變成不太懂怎麼部屬one api的設定跟對應方式
可否另外做一篇教學
謝謝

**Comment by c121914yu** [comment]
> - OPENAI_BASE_URL=https://api.openai.com/v1
>       - CHAT_API_KEY=sk-xxxx
>       - 要改成 oneapi的網址與令牌對嗎?

要

**Comment by jinghai** [comment]
通过one-api对接文心和星火，貌似Prompt没有生效，请问怎么排查我们发出去的请求？

**Comment by jinghai** [comment]
> 通过one-api对接文心和星火，貌似Prompt没有生效，请问怎么排查我们发出去的请求？

有没有Debug日志可以排查？ @c121914yu

**Comment by imkratos** [comment]
> 通过one-api对接文心和星火，貌似Prompt没有生效，请问怎么排查我们发出去的请求？

这个好像是oneapi那边的问题，我看那边的issue 也有人提了。

**Comment by c121914yu** [comment]
> > 通过one-api对接文心和星火，貌似Prompt没有生效，请问怎么排查我们发出去的请求？
> 
> 有没有Debug日志可以排查？ @c121914yu 

上下文就是传的实际内容。
我用知识库时候它是生效的，不生效的话估计是prompt不适合星火
