### ISSUE TITLE
私有化部署创建数据库报错

### ISSUE THREAD

**Issue by zanderjiang** [labring/FastGPT#1870]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.4

**问题描述, 日志截图**
私有化部署（没有用Docker），在创建新的数据库时会报错TypeError: Cannot read properties of undefined (reading 'model')

<img width="1260" alt="Screen Shot 2024-06-27 at 2 32 01 AM" src="https://github.com/labring/FastGPT/assets/80486189/6d65a303-4c69-428e-8d39-d7d57a3b167c">

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没配置知识库处理模型，看配置文件说明
