### ISSUE TITLE
升级到v4.8.1执行初始化失败，应用及知识库内容丢失

### ISSUE THREAD

**Issue by shadowlkx** [labring/FastGPT#1872]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
从v4.8升级到v4.8.1升级完成后，执行初始化日志

pg connected
init pg successful
default team exist new ObjectId("66739d64aa6db78902e6ea8e")
root user init: { username: 'root', password: '1234' }
[INFO] 2024-06-27 07:30:24 [Vector Queue] Done 
success rename dataset.trainings -> dataset_trainings
dataset_collections 中有数据，无法自动将 dataset.collections 迁移到 dataset_collections，请手动操作
[INFO] 2024-06-27 07:30:24 [QA Queue] Done 
dataset_datas 中有数据，无法自动将 dataset.datas 迁移到 dataset_datas，请手动操作
app_versions 中有数据，无法自动将 app.versions 迁移到 app_versions，请手动操作
success rename buffer.rawtexts -> buffer_rawtexts
success rename team.members -> team_members
success rename team.subscriptions -> team_subscriptions
[INFO] 2024-06-27 07:30:24 Request finish /api/admin/initv481, time: 347ms 

**复现步骤**

**预期结果**

**相关截图**

**Comment by shadowlkx** [comment]
@c121914yu 您好，能帮忙看下未什么初始化无法成功吗

**Comment by c121914yu** [comment]
> @c121914yu 您好，能帮忙看下未什么初始化无法成功吗

没停机升级，目标表有数据了，无法直接重命名旧表。
根据提示，把自动初始化失败的表，手动把内容迁移过去，或者不介意新数据的话，直接把新的表删除，重新初始化。（注意，只需要操作失败的那几个表）

**Comment by shadowlkx** [comment]
@c121914yu 我刚刚连接到mongo手动删除了这几个表，执行初始化就成功了，升级需要先把docker服务都stop吗？

**Comment by c121914yu** [comment]
> @c121914yu 我刚刚连接到mongo手动删除了这几个表，执行初始化就成功了，升级需要先把docker服务都stop吗？

不需要，这个版本最好停机（文档应该有个提示的），因为要迁移表，如果目标表不是空表，会报错的。
