### ISSUE TITLE
undefined 当前分组 default 下对于模型 XXX 无可用渠道 

### ISSUE THREAD

**Issue by kid20210528** [labring/FastGPT#1873]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
创建应用后无法对话，提示：undefined 当前分组 default 下对于模型 通义千问 无可用渠道 

**相关截图**
![1719471242352](https://github.com/labring/FastGPT/assets/84962923/470921f2-bd38-43d7-a3bb-b674643c4702)
![1719471162450](https://github.com/labring/FastGPT/assets/84962923/84d1c66a-7a2e-406c-98ef-19bb77c73487)
![1719471128591](https://github.com/labring/FastGPT/assets/84962923/85afe660-16cb-473b-abd8-fe7aa9ae93b5)
![1719471106571](https://github.com/labring/FastGPT/assets/84962923/4d0c9762-1b5d-4ca0-8a56-396495a7f457)
![1719473939811](https://github.com/labring/FastGPT/assets/84962923/487d557a-10b2-4915-b306-6aa42ef23c39)

**Comment by lijiajun1997** [comment]
api key的问题

**Comment by c121914yu** [comment]
看文档 oneapi 教程
