### ISSUE TITLE
系统插件无法使用

### ISSUE THREAD

**Issue by 13829386012** [labring/FastGPT#1875]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.85

**问题描述, 日志截图**
 我是源码本地部署的，发现在高级编排中的系统插件无法使用，调用时日志报503错误
![文本加工](https://github.com/labring/FastGPT/assets/40138671/ffbe920b-3e07-43a3-a4ba-1160bf2ce4ca)
![文本加工错误](https://github.com/labring/FastGPT/assets/40138671/3261ed89-54bb-46c8-974e-2594bd5ad5e8)
不知道哪里出了问题要如何修复，请求帮助
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/249c39f4-c8d2-4cb6-a34e-244ff8ab9e95)
不太确定，本地没复现出来

**Comment by 13829386012** [comment]
> ![image](https://private-user-images.githubusercontent.com/50446880/343758971-249c39f4-c8d2-4cb6-a34e-244ff8ab9e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODk3NDQsIm5iZiI6MTcxOTQ4OTQ0NCwicGF0aCI6Ii81MDQ0Njg4MC8zNDM3NTg5NzEtMjQ5YzM5ZjQtYzhkMi00Y2I2LWEzNGUtMjQ0ZmY4YWI5ZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDExNTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZGFkMjYyNGJjOTczM2Q0MmQ0MzFiOTE4ZTAzZmI0MGRlNDQ1N2NjZWMyMDEwYjIwNzhlMTM1ZGJhMTg2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mxgcEW-7okTNbwEXVfeAh2An3PN1cofK80xZ2OEc9fA) 不太确定，本地没复现出来

当内部调用api请求系统插件时，会请求本地哪个端口呢，我排除一下端口权限问题

**Comment by c121914yu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/50446880/343758971-249c39f4-c8d2-4cb6-a34e-244ff8ab9e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODk3NDQsIm5iZiI6MTcxOTQ4OTQ0NCwicGF0aCI6Ii81MDQ0Njg4MC8zNDM3NTg5NzEtMjQ5YzM5ZjQtYzhkMi00Y2I2LWEzNGUtMjQ0ZmY4YWI5ZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDExNTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZGFkMjYyNGJjOTczM2Q0MmQ0MzFiOTE4ZTAzZmI0MGRlNDQ1N2NjZWMyMDEwYjIwNzhlMTM1ZGJhMTg2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mxgcEW-7okTNbwEXVfeAh2An3PN1cofK80xZ2OEc9fA) 不太确定，本地没复现出来
> 
> 当内部调用api请求系统插件时，会请求本地哪个端口呢，我排除一下端口权限问题

就是服务运行的端口

**Comment by zkstudio** [comment]
我也出现一样的问题，调试显示json{} 空值

**Comment by c121914yu** [comment]
新版已经不再通过 HTTP 去调用插件，该问题close。
