### ISSUE TITLE
这个能改后端吗 

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#1878]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
能看到后端代码吗 比如我想改这个接口
fastgpt开源版本 /proApi/support/user/account/register/emailAndPhone
找到了proApi 但是里面没有具体的实现逻辑啊 
![image](https://github.com/labring/FastGPT/assets/50564015/76d76d8c-e334-4762-8297-0864b3e677b2)

**复现步骤**

**预期结果**

**相关截图**

**Comment by 704572066** [comment]
这部分接口是商业版闭源的
