### ISSUE TITLE
出现429报错（429 当前分组上游负载已饱和，请稍后再试 (request id: 2024062804540355103293018330914)）

### ISSUE THREAD

**Issue by KWYHDHJ** [labring/FastGPT#1882]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.5

**问题描述, 日志截图**
出现429报错（429 当前分组上游负载已饱和，请稍后再试 (request id: 2024062804540355103293018330914)）

**复现步骤**

**预期结果**

**相关截图**

**Comment by KWYHDHJ** [comment]
然后这个key调用的是在哪里配置的

**Comment by lijiajun1997** [comment]
api key的问题

**Comment by KWYHDHJ** [comment]
哦哦，我换阿里的再试一下吧

**Comment by c121914yu** [comment]
达到模型调用上限了

**Comment by pll8754** [comment]
如何解决
