### ISSUE TITLE
没有ai高级设置

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1887]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [* ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
部署的最新版本，但是没有ai高级配置，只有ai基本配置，导致无法定义引用提示词
**复现步骤**

**预期结果**

**相关截图**
![mmexport1719566338375](https://github.com/labring/FastGPT/assets/174102361/c48daf20-2038-424f-8957-19750ba74760)

**Comment by c121914yu** [comment]
高级编排里
