### ISSUE TITLE
4.8.4工具调用终止和4.7的用法不一致

### ISSUE THREAD

**Issue by romejiang** [labring/FastGPT#1888]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.4

**问题描述, 日志截图**

4.7.1版本《工具调用终止》节点可以被多个《http请求》节点共用。具体看图1

而4.8.4版本必须给每一个《http请求》节点配置一个《工具调用终止》节点。如果共用《工具调用终止》节点，节点将不起效。看图2

**复现步骤**

**预期结果**

希望4.8.4保持原有的使用逻辑，相同的逻辑节点可以复用。

**相关截图**
![截屏2024-06-29 04 17 21](https://github.com/labring/FastGPT/assets/1053325/89b5d5ca-736d-4a70-957f-db16a7596ba2)
![截屏2024-06-29 04 11 26](https://github.com/labring/FastGPT/assets/1053325/7f915342-789c-4bf4-97c9-690ca47aa757)

**Comment by c121914yu** [comment]
不能复用
