### ISSUE TITLE
getaddrinfo ENOTFOUND sandbox

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#1889]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
docker v4.8.5

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
v4.8.5

**问题描述, 日志截图**
<img width="521" alt="Screenshot 2024-06-29 at 08 11 32" src="https://github.com/labring/FastGPT/assets/36452456/99402329-e7c9-426d-ba31-63d2bf60d4be">

<img width="564" alt="Screenshot 2024-06-29 at 08 11 10" src="https://github.com/labring/FastGPT/assets/36452456/635cdf4d-9847-44dc-8b31-00dc81f587d2">

**复现步骤**

**预期结果**

**相关截图**

**Comment by USTCcgg** [comment]
请问该问题是怎么解决的？

**Comment by bincooo** [comment]
> 请问该问题是怎么解决的？

docker 的网络搭桥问题
