### ISSUE TITLE
【建议】增加专门生成式的应用类型，或者可以设置是否需要多轮对话

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#189]
比如有些翻译工具，或简单的生成式场景不需要多轮对话，否则反倒难以控制输出质量，建议像dify一样，可以有专门生成式的应用类型。
或者可以指定是否多轮对话也可以，同时支持上传模板进行批量操作，具体功能可以参考一下dify，谢谢

**Comment by c121914yu** [comment]
你可以选择不要历史记录

**Comment by c121914yu** [comment]
分模式太难用了，直接编排挑选是否需要历史记录就可以了

**Comment by jinghai** [comment]
> 分模式太难用了，直接编排挑选是否需要历史记录就可以了

怎么配置不要历史记录？

**Comment by c121914yu** [comment]
> > 分模式太难用了，直接编排挑选是否需要历史记录就可以了
> 
> 怎么配置不要历史记录？

高级编排里不加入历史记录或者填0就是没有

**Comment by jinghai** [comment]
> > > 分模式太难用了，直接编排挑选是否需要历史记录就可以了
> > 
> > 
> > 怎么配置不要历史记录？
> 
> 高级编排里不加入历史记录或者填0就是没有

太棒了！！

**Comment by jinghai** [comment]
> > > 分模式太难用了，直接编排挑选是否需要历史记录就可以了
> > 
> > 
> > 怎么配置不要历史记录？
> 
> 高级编排里不加入历史记录或者填0就是没有

这个高级模式不错，建议把https://github.com/jinghai/Flowise中的组件也包含进来，就可以使用langchain开发更复杂有趣的应用

**Comment by jinghai** [comment]
> > > 分模式太难用了，直接编排挑选是否需要历史记录就可以了
> > 
> > 
> > 怎么配置不要历史记录？
> 
> 高级编排里不加入历史记录或者填0就是没有

在高级编排里指定了历史记录为0，页面测试也问题，点了保存，但是生成分享链接，外部使用的中无效果，还是带了聊天记录进去。
同时，在后台的“聊天”页面中也没有生效。

**Comment by c121914yu** [comment]
> > > > 分模式太难用了，直接编排挑选是否需要历史记录就可以了
> > > 
> > > 
> > > 怎么配置不要历史记录？
> > 
> > 高级编排里不加入历史记录或者填0就是没有
> 
> 在高级编排里指定了历史记录为0，页面测试也问题，点了保存，但是生成分享链接，外部使用的中无效果，还是带了聊天记录进去。
> 同时，在后台的“聊天”页面中也没有生效。

你点了简易模式的报错吧

**Comment by jinghai** [comment]
> > > > > 分模式太难用了，直接编排挑选是否需要历史记录就可以了
> > > > 
> > > > 
> > > > 怎么配置不要历史记录？
> > > 
> > > 
> > > 高级编排里不加入历史记录或者填0就是没有
> > 
> > 
> > 在高级编排里指定了历史记录为0，页面测试也问题，点了保存，但是生成分享链接，外部使用的中无效果，还是带了聊天记录进去。
> > 同时，在后台的“聊天”页面中也没有生效。
> 
> 你点了简易模式的报错吧

没有点简易模式

**Comment by jinghai** [comment]
点简易模式保存会提醒我覆盖掉高级模式，所以没点

**Comment by c121914yu** [comment]
> > > > > > 分模式太难用了，直接编排挑选是否需要历史记录就可以了
> > > > > 
> > > > > 
> > > > > 怎么配置不要历史记录？
> > > > 
> > > > 
> > > > 高级编排里不加入历史记录或者填0就是没有
> > > 
> > > 
> > > 在高级编排里指定了历史记录为0，页面测试也问题，点了保存，但是生成分享链接，外部使用的中无效果，还是带了聊天记录进去。
> > > 同时，在后台的“聊天”页面中也没有生效。
> > 
> > 你点了简易模式的报错吧
> 
> 没有点简易模式

发现了，0不行，要删掉那个模块
