### ISSUE TITLE
关于知识库和应用的数量限制

### ISSUE THREAD

**Issue by HotelEnglish** [labring/FastGPT#1891]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ x] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
从4.8.1升级到4.8.5后，创建知识库时，提示数量超限。想了解一下是从4.8.5开始对开源版作了限制还是我升级过程中出了问题？
如果确实做了限制，能否明示开源版的具体限制，以便管理知识库和应用。
**复现步骤**

**预期结果**
没有限制最好，如果有限制，应在升级说明里明确说明相应的限制，毕竟是新增的“功能”。
**相关截图**
![image](https://github.com/labring/FastGPT/assets/45430033/51467908-ea25-449d-bcd9-8865024dad5f)

**Comment by HotelEnglish** [comment]
我在问题描述里“你的版本”那选错了，我是用docker部署的，不是部署在sealos公有云上的。

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/blob/main/docSite/content/zh-cn/docs/commercial/intro.md 已更新
