### ISSUE TITLE
高级编排工具调用不生效

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1893]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 
刚安装最新版本
**问题描述, 日志截图**
高级编排的工具调用不生效，调式发现工具调用直接回复了信息，并没有调用相关的模块。根据视频操作不生效，然后将工具调用直接对接自动回复，并编辑了很具体的描述，调试后仍是自行回复，如图。

更新，这可能与大语言模型有关，我更换了模型进行逐步调试就可以，但是整体调试就会出现奇怪的乱码，例如，ai输出：8yjGV2消防事宜注意”｝。这个bug我查了下其他人也反应了。
**复现步骤**

**预期结果**

**相关截图**
![1719743563557](https://github.com/labring/FastGPT/assets/174102361/70b0457c-6000-4c64-bcc0-8a1580056cc7)
![Uploading 1719743814217.jpg…]()
![IMG_20240630_183856](https://github.com/labring/FastGPT/assets/174102361/cf6419f3-94a6-4153-b286-b335b4ba058c)

**Comment by c121914yu** [comment]
检查是否支持函数调用，不支持的就不要设置函数调用模式

**Comment by sdytzjp** [comment]
ok
