### ISSUE TITLE
无法支持图片的markdiown显示

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1894]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 最新版

**问题描述, 日志截图**
知识库里的markdown格式的图片无法显示，但markdwon格式的url可以。如何解决
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没看懂

**Comment by sdytzjp** [comment]
知识库里的手动添加知识，包括markdown格式的图片和markdwon格式的url。调式时，能回复URL但不能回复图片

**Comment by c121914yu** [comment]
> 知识库里的手动添加知识，包括markdown格式的图片和markdwon格式的url。调式时，能回复URL但不能回复图片

<img width="827" alt="image" src="https://github.com/labring/FastGPT/assets/50446880/2f330e73-a91f-4438-aedb-7d9224b1ed11">
自己调整～ 这不返回了么。markdown 图片格式：

```
![]()
```
