### ISSUE TITLE
知识库两个问题求教

### ISSUE THREAD

**Issue by hugefrog** [labring/FastGPT#1896]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ]x  我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x ] 私有部署版本, 具体版本号: 4.7.1

**问题描述, 日志截图**
问题1：建立知识库做了一些测试，把知识库清空删除以后，mongo的数据的占用空间很大（7.9GB）而且并没有减少，这个正常么？
问题2：远程电脑访问fastgpt在知识库中上传文件浏览器老是提示network error上传失败是什么问题啊？
**复现步骤**

**预期结果**

**相关截图**
![微信图片_20240701093810](https://github.com/labring/FastGPT/assets/83398604/8c89d011-e2ae-462a-910b-f4a9d05e9838)

**Comment by c121914yu** [comment]
1. 看数据库配置，是否释放空间。pg 的话，不会释放空间，需要手动释放。
2. 带宽太小，服务器规格问题……

**Comment by hugefrog** [comment]
> 1. 看数据库配置，是否释放空间。pg 的话，不会释放空间，需要手动释放。
> 2. 带宽太小，服务器规格问题……
感谢回复
1.好的，我研究一下数据库配置。
2.部署的机器配置是cpu intel i7-11700f，32G内存，nvdia 3090,win10专业版，采用教程里的docker方式部署。机器在内网，千兆局域网。

**Comment by hugefrog** [comment]
> 1. 看数据库配置，是否释放空间。pg 的话，不会释放空间，需要手动释放。
> 2. 带宽太小，服务器规格问题……

问题2：会不会是docker默认的内存限制太小，上传的文件太大导致的？

**Comment by c121914yu** [comment]
> > 1. 看数据库配置，是否释放空间。pg 的话，不会释放空间，需要手动释放。
> > 2. 带宽太小，服务器规格问题……
> 
> 问题2：会不会是docker默认的内存限制太小，上传的文件太大导致的？

默认一般没有，得看你有没有设置临时存储

**Comment by hugefrog** [comment]
> > > 1. 看数据库配置，是否释放空间。pg 的话，不会释放空间，需要手动释放。
> > > 2. 带宽太小，服务器规格问题……
> > 
> > 
> > 问题2：会不会是docker默认的内存限制太小，上传的文件太大导致的？
> 
> 默认一般没有，得看你有没有设置临时存储
我按教程来构建的docker，也不清楚设置了临时存储没有，更新到了4.8.5，然后把docker的内存限制增大，最近好像没有发现上传时候network error的问题了。
