### ISSUE TITLE
使用工具调用后，猜你想问不生效

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1898]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
最新版本
- [ ] 公有云版本
- [ X] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
使用工具调用后，猜你想问不生效
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
未遇到

**Comment by sdytzjp** [comment]
猜你想问经常不出现，偶尔出现，这个机制是啥

**Comment by c121914yu** [comment]
> 猜你想问经常不出现，偶尔出现，这个机制是啥

模型提示不生效，没按要求返回数组

**Comment by sdytzjp** [comment]
请问这个要怎么提示更好
