### ISSUE TITLE
【问题】温度参数是浮点数，比如ChatGLM是0~1之间的浮点数，我们为什么给设置成整数了？

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#190]

**Comment by c121914yu** [comment]
映射10倍

**Comment by jinghai** [comment]
> 映射10倍

没懂，我设置1，意思是0.1？
与模型配置中的"maxTemperature": 1是什么关系？

**Comment by c121914yu** [comment]
> > 映射10倍
> 
> 没懂，我设置1，意思是0.1？
> 与模型配置中的"maxTemperature": 1是什么关系？

对，模型最大是多少，配置里填多少
