### ISSUE TITLE
请问markdown格式的本地图片怎么上传

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1900]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
最版本
- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 
我要在【指定回复】中带上图片，请问如何插入markdown格式的本地图片，示例语法是![Example Image](/test/example.png)，我想问下路径是服务器的路径还是fastgpt容器内部的路径。我把这个png图片分别复制到服务器路径/root下（对应语句![Example Image](/root/example.png），以及fastgpt容器内部的路径/app下（对应语句![Example Image](/app/example.png），但是都显示不出来
**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
放到 oss 里

**Comment by sdytzjp** [comment]
不好意思，有点菜，oss在哪里

**Comment by sdytzjp** [comment]
> 放到 oss 里

oss在哪里
