### ISSUE TITLE
关于接入jina-rerank重排序模型

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1901]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
1. 关于使用方式：
   https://github.com/labring/FastGPT/issues/1240#issuecomment-2066646335中，作者提到了bge-rerank最低相关度要大于0.85。
在使用jina-rerank重排序模型过程中：
当搜索配置为0.85相关度和混合搜索+结果重排，没有引用内容。如图：
![image](https://github.com/labring/FastGPT/assets/40045458/07d05d56-a3d3-47d5-bd74-da8eeeb8581c)
没有引用内容。查看了jina-rerank的日志，如图：
![image](https://github.com/labring/FastGPT/assets/40045458/4cf97238-af63-400b-b2de-84538ac7aac3)
当搜索配置为0.2相关度和语义搜索+结果重排，有引用内容。如图：
![image](https://github.com/labring/FastGPT/assets/40045458/eb78d69d-642c-4591-82c7-3c9334cb372e)
当搜索配置为0.2相关度和全文检索+结果重排，有引用内容。
所以说，关于最低相关度的值要根据不同的模型去调整？
2. 关于在config.json中配置了多个重排序模型，前端页面上无法选择，并且默认使用config.json中第一个重排序模型

@c121914yu @nongmo677 @lijiajun1997
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
1. 是的
2. 目前只有第一个生效
