### ISSUE TITLE
sandbox是否支持arm版本的？目前在测试的时候，发现arm环境部署的话，调用服务会挂掉

### ISSUE THREAD

**Issue by 125793014** [labring/FastGPT#1902]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: fastgpt:v4.8.5、fastgpt-sandbox:v4.8.3 arm机器

**问题描述, 日志截图**
        error => socket hang up

**复现步骤**
       debug调试模式

**预期结果**

**相关截图**

**Comment by 125793014** [comment]
<img width="471" alt="image" src="https://github.com/labring/FastGPT/assets/75434716/d3a7c716-968f-4422-ba97-614473026cd8">

**Comment by c121914yu** [comment]
github 的镜像支持

**Comment by 125793014** [comment]
github的镜像也试过了 存在同样的问题。

**Comment by 125793014** [comment]
> github 的镜像支持


github的镜像也试过了 存在同样的问题。

**Comment by 125793014** [comment]
> github 的镜像支持


github的镜像也试过了 存在同样的问题。这个问题出现在：debug调试模式，执行工具写的函数代码的时候。

**Comment by 125793014** [comment]
> github 的镜像支持


github的镜像也试过了 存在同样的问题。这个问题出现在：debug调试模式，执行工具写的函数代码的时候。

**Comment by c121914yu** [comment]
可以参考 isolate vm 官方，修改 dockerfile，重新打个包试试
CMD ["node", "--no-node-snapshot", "projects/sandbox/dist/main.js"]

不确定是否有关。

**Comment by 125793014** [comment]
> 可以参考 isolate vm 官方，修改 dockerfile，重新打个包试试 CMD ["node", "--no-node-snapshot", "projects/sandbox/dist/main.js"]
> 
> 不确定是否有关。

按照这个重新打包验证了，问题解决了。

**Comment by c121914yu** [comment]
> > 可以参考 isolate vm 官方，修改 dockerfile，重新打个包试试 CMD ["node", "--no-node-snapshot", "projects/sandbox/dist/main.js"]
> > 不确定是否有关。
> 
> 按照这个重新打包验证了，问题解决了。

ok，我加到 dockerfile 里了
