### ISSUE TITLE
导入配置词乱码，而且无法批量删除

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1903]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
最新版
- [ ] 公有云版本
- [ X] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
通过模板导入中文出现乱码（更改编码格式已经解决，但没有办法批量删除
![image](https://github.com/labring/FastGPT/assets/174102361/335907e0-ae0a-45e2-a0ad-784a2c513658)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没用 utf-8

**Comment by sdytzjp** [comment]
没有办法批量删除，这个考虑优化下吧
