### ISSUE TITLE
Api response error: undefined, Invalid URL

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1904]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
功能都使用正常，但是翻看日志的时候发现了这个报错，虽然现在还没发现它在哪里影响了使用，所以想问问，排查这个报错的思路
报错信息如下：
![image](https://github.com/labring/FastGPT/assets/40045458/e7b1a7c4-cfba-44ed-82c4-1f0d0bdd7045)
@c121914yu @nongmo677 @lijiajun1997
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
商业版的接口，估计是有没隐藏的校验接口，新版是没有了~
