### ISSUE TITLE
知识库无法通过静态链接添加fastgpt官方文档

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1907]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
最新版
- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
知识库，先建文本数据集---网页链接，填入fastgpt的官方文档如下https://doc.fastgpt.in/docs/course/websync/，选择器div[data-prismjs-copy]，无法获取信息，空的。

另外，请问以下两个知识库的功能啥区别
1、知识库，先建文本数据集---网页链接
2、web站点同步

如图
![a1](https://github.com/labring/FastGPT/assets/174102361/c3f2f2d5-c485-4e5d-b588-ca4f47f3127f)
![a2](https://github.com/labring/FastGPT/assets/174102361/1c5b5fc0-0803-4562-9e80-3400b754eccd)
![吖](https://github.com/labring/FastGPT/assets/174102361/ce5b4ffc-943b-4ec4-996a-d2741b7df4c1)

**Comment by c121914yu** [comment]
估计是你选择器写的有问题, 没写任何选择器 ok :
<img width="836" alt="image" src="https://github.com/labring/FastGPT/assets/50446880/4aeed99f-e2c1-40ad-a9e4-64dd0740b7c7">

选择器填写: `.layout-spacing` 也 ok: 

<img width="753" alt="image" src="https://github.com/labring/FastGPT/assets/50446880/89428c51-721f-43fc-8f25-7b281f135482">

**Comment by c121914yu** [comment]
web 站点还会自动爬取网页中子链接。

**Comment by sdytzjp** [comment]
实在不好意思，网络的问题导致的
