### ISSUE TITLE
最新的docker-compose.yml文件有问题

### ISSUE THREAD

**Issue by mpuazxc2** [labring/FastGPT#191]
https://doc.fastgpt.run/docs/develop/deploy/docker
用的是“# 非 host 版本, 不使用本机代理”
这个版本，重新拉去后，数据库链接不上，老版本的“docker-compose.yml”文件正常
-----
还有现在最新发布的是4.0还是4.1了啊，我看有个4.1升级

**Comment by c121914yu** [comment]
4.1,刚修复文档地址了

**Comment by mpuazxc2** [comment]
# 非 host 版本, 不使用本机代理
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.4.2 # docker
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5432:5432
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports: # 生产环境建议不要暴露
      - 27017:27017
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    # image: c121914yu/fast-gpt:latest # docker hub
    image: ghcr.io/labring/fastgpt:latest # 阿里云
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      # root 密码，用户名为: root
      - DEFAULT_ROOT_PSW=1234
      # 中转地址，如果是用官方号，不需要管
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-xxxx
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      # mongo 配置，不需要改
      - MONGODB_URI=mongodb://username:password@mongo:27017/fastgpt
      # pg配置. 不需要改
      - PG_URL=postgresql://username:password@pg:5432/postgres
networks:
  fastgpt:
------
https://doc.fastgpt.run/docs/develop/deploy/docker
也就是“docker-compose.yml”文件有问题
这个真的有问题，重新拉去后，数据库链接不上

**Comment by c121914yu** [comment]
看下配置~mongourl那个补充个authsource

**Comment by mpuazxc2** [comment]
好吧我去看下，我以为拉取最新的docker-compose.yml
就可以不需要改authsource

**Comment by c121914yu** [comment]
> 好吧我去看下，我以为拉取最新的docker-compose.yml 就可以不需要改authsource

早上更新了
