### ISSUE TITLE
知识库无法上传文件

### ISSUE THREAD

**Issue by wanyh2012** [labring/FastGPT#1911]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by wanyh2012** [comment]
![image](https://github.com/labring/FastGPT/assets/25927758/c25355a2-cff6-4b6b-a3b8-0728f9777f1d)

**Comment by wanyh2012** [comment]
curl --location --request POST 'http://172.16.1.85:3000/api/core/dataset/collection/create/localFile' \
--header 'Authorization: Bearer fastgpt-kOoBAKBzyFfwNtlssnEEN6FB24xSghGAEw9qJzC7PYCQnuYg7EHGIknsjUV' \
--form 'file=@"/home/gpt/file/人生.txt"' \
--form 'data="{\"datasetId\":\"667e7b838c9069d1a46c72b1\",\"parentId\":null,\"trainingType\":\"chunk\",\"chunkSize\":512,\"chunkSplitter\":\"\",\"qaPrompt\":\"\",\"metadata\":{}}"'

**Comment by wanyh2012** [comment]
![image](https://github.com/labring/FastGPT/assets/25927758/aa49445f-97bc-4eb9-a77a-c4fd30b0d28b)
使用的是账号生成的apikey，开源版本没有上传功能吗

**Comment by c121914yu** [comment]
填写完 例行检查 再说

**Comment by firstjack** [comment]
请问如何解决的呢？
