### ISSUE TITLE
无法索引知识库

### ISSUE THREAD

**Issue by weirdorr** [labring/FastGPT#1912]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
error => 400 Inference error: Range of input length should be [1, 2048] (request id: 2024070208305054674516722308854)
[Error] 2024-07-02 08:30:50 400 Inference error: Range of input length should be [1, 2048] (request id: 2024070208305054674516722308854) 
[Info] 2024-07-02 08:30:50 [Vector Queue] Start 
[Info] 2024-07-02 08:30:50 [Vector Queue] Start 
Embedding Error eF [Error]: 400 Inference error: Range of input length should be [1, 2048] (request id: 2024070208305063434452547591163)
    at eL.generate (/app/projects/app/.next/server/chunks/76750.js:15:67594)
    at av.makeStatusError (/app/projects/app/.next/server/chunks/76750.js:15:79337)
    at av.makeRequest (/app/projects/app/.next/server/chunks/76750.js:15:80260)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c (/app/projects/app/.next/server/chunks/75612.js:166:1395)
    at async f (/app/projects/app/.next/server/chunks/75612.js:137:15493)
    at async Promise.all (index 0)
    at async u (/app/projects/app/.next/server/chunks/75612.js:314:30962)
    at async /app/projects/app/.next/server/chunks/75612.js:316:3257
    at async o (/app/projects/app/.next/server/chunks/75612.js:134:21731) {
  status: 400,
  headers: {
    'content-length': '200',
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 02 Jul 2024 08:30:50 GMT',
    'x-oneapi-request-id': '2024070208305063434452547591163'
  },
  error: {
    message: 'Inference error: Range of input length should be [1, 2048] (request id: 2024070208305063434452547591163)',
    type: 'upstream_error',
    param: '400',
    code: 'bad_response_status_code'
  },
  code: 'bad_response_status_code',
  param: '400',
  type: 'upstream_error'
}

**Comment by c121914yu** [comment]
模型不是 1536 维度

**Comment by leavegee** [comment]
1536也报错呀~  阿里的text-embedding-v2

**Comment by raozhiyong11** [comment]
@leavegee @c121914yu @weirdorr 请问这个问题怎么解决的？我也遇到一样的问题，而且阿里云后台一直在扣费，是不是索引不成功会一直尝试？

**Comment by weirdorr** [comment]
@raozhiyong11 试试改一下max-token的值

**Comment by raozhiyong11** [comment]
> @raozhiyong11 试试改一下max-token的值

已经改过了，之前默认是3000，现在改成2000了重新启动还是不行，关键是一直重试调用阿里的text-embedding模型
