### ISSUE TITLE
4.8.5版本开始接口不再返回数据库结果 如:/api/core/dataset/collection/create/link

### ISSUE THREAD

**Issue by ZyairYH** [labring/FastGPT#1913]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.5

**问题描述, 日志截图**
接口:/api/core/dataset/collection/create/link
![image](https://github.com/labring/FastGPT/assets/19263658/ac12d219-b170-4f30-b3ff-32b04f3b5dd2)

排查代码发现 目前不再返回数据库结果 这个是为什么呢
![image](https://github.com/labring/FastGPT/assets/19263658/e42db399-ef5f-4324-a226-c61ef8273607)

**复现步骤**
页面或者API调用都不返回collection结果

**预期结果**
返回数据库相关的结果

**相关截图**
![image](https://github.com/labring/FastGPT/assets/19263658/3f64ed3c-b7ba-4114-9731-8631b6f48738)

**Comment by ZyairYH** [comment]
![image](https://github.com/labring/FastGPT/assets/19263658/60cc83d5-fb2f-437f-9085-e46729b3532d)
目前通过修改代码 返回collection结果
不过不确定4.8.5为什么要做这个修改  API和更新日志没有对应描述

**Comment by c121914yu** [comment]
fix: https://github.com/labring/FastGPT/pull/1947
