### ISSUE TITLE
HTTP 请求模块所在服务调用出错，未有输出字段

### ISSUE THREAD

**Issue by chenmonster** [labring/FastGPT#1915]
如下图，当**HTTP 请求**模块的服务挂了，其中它的输出参数 `success` 是布尔类型，默认值是`false`，但是模块调用结束的**判断器**模块始终是`true`，导致进入`True`，能否是`False`，或者要怎样配置呢？

> 当服务是正常，后面的逻辑也是正常的！

![问题.png](https://github.com/labring/FastGPT/assets/34160512/3f4fa02f-18f6-42da-86fd-221e70fd4b96)

**Comment by c121914yu** [comment]
旧版问题自行看源码，新版有成功失败标记
