### ISSUE TITLE
Template在cloud.sealos.top部署不成功

### ISSUE THREAD

**Issue by superlbr** [labring/FastGPT#192]
貌似没有针对cloud.sealos.top做适配

**Comment by c121914yu** [comment]
top用不了gpt

**Comment by superlbr** [comment]
可以走openai代理啊

**Comment by c121914yu** [comment]
试了试，应该是template没更新4.1，需要手动修改环境变量

**Comment by superlbr** [comment]
报错跟gpt无关吧。。
<img width="392" alt="image" src="https://github.com/labring/FastGPT/assets/8142164/3ce55176-9f9c-478e-b28d-ca590f5cfa1e">

**Comment by c121914yu** [comment]
不过top正式发布了么？之前我看都是说测试，，没去关注

**Comment by superlbr** [comment]
上线了，都计费了。。。 https://forum.laf.run/u/carsonyang

**Comment by superlbr** [comment]
Environment 调出来看，都是一样的

**Comment by superlbr** [comment]
top没有 postgresql-14.8.0，只有14.7.2

**Comment by superlbr** [comment]
还是跑不起来，pg/mongo `3 node(s) did not have enough free storage`

**Comment by superlbr** [comment]
跑起来了
