### ISSUE TITLE
语音识别后期是否考虑配置化接入FunASR

### ISSUE THREAD

**Issue by wangyiyong** [labring/FastGPT#1920]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 features
- [x ] 我已确认我已升级到最新版本
- [x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
语音识别测试了不能支持阿里的 [FunASR](https://github.com/modelscope/FunASR/tree/main)  接入，不知后期会不会考虑可以配置化接入FunASR

**应用场景**
语音识别

**Comment by c121914yu** [comment]
可以给 oneapi 提

**Comment by sdytzjp** [comment]
坚决提，oneapi目前好像支持whisper
