### ISSUE TITLE
Milvus版本版本，向量检索bug，语义检索结果的分值一样，搜索结果无法使用

### ISSUE THREAD

**Issue by zijia28** [labring/FastGPT#1923]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ X] 私有部署版本, 具体版本号: V4.8.5

**问题描述, 日志截图**

向量检索时，数据结果分数值一样，搜索结果无法使用，本地部署采用的是bge-m3向量模型，同时测试了官方推荐的m3e-large模型效果是一样的，也存在此问题。

**复现步骤**

**预期结果**

**相关截图**
<img width="1163" alt="image" src="https://github.com/labring/FastGPT/assets/13111096/def0062b-fbd7-453b-a3e3-4aa9173a5d0e">
<img width="1137" alt="image" src="https://github.com/labring/FastGPT/assets/13111096/0fbe0b1a-d619-489c-88f3-1398f9bd3c30">

**Comment by c121914yu** [comment]
未复现，检查下你的向量模型是不是有问题

**Comment by zijia28** [comment]
向量模型已确认没有问题，直接使用官网推荐的m3e-large-api容器自带的向量模型验证的，切换到PG版本就没此问题。Milvus版本有问题。

**Comment by wmqKevin** [comment]
我也遇到同样的问题，用的是智谱的embedding-2

**Comment by Sun-Qiming** [comment]
同问，m3e-large-api输出正常，感觉是milvus哪里不对

**Comment by Sun-Qiming** [comment]
> 同问，m3e-large-api输出正常，感觉是milvus哪里不对

@zijia28 请问你的解决了么

**Comment by Essence9999** [comment]
确实有问题，milvus，语义检索直接为空。

**Comment by USTCcgg** [comment]
同样的问题，希望得到解决

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/2895
