### ISSUE TITLE
关于免登录窗口

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1924]
你好，由于免登录窗口不太安全，会造成token浪费以及非法用户访问。我想做一个登陆页面，并且通过nginx反向代理，只有认证通过后，才可以通过nginx反向代理到免登录窗口的URL，而免登录窗口的URL不对外暴露，只允许nginx访问，请问以上思路是否可以，是否有相关的参考文档

**Comment by c121914yu** [comment]
代码都有，自行开发套一层
