### ISSUE TITLE
本地搭建了docSite,如何在Fastgpt首页左下角的“使用帮助”替换成指定的地址？

### ISSUE THREAD

**Issue by eric20100106** [labring/FastGPT#1926]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我本地使用hugo搭建了fastgpt的docSite,通过localhost:1313可以访问，但如何将此地址配置到Fastgpt系统首页呢？
我尝试在config.json中的feConfigs增加docUrl属性，但重启后并未加载该属性。
**应用场景**
![图片](https://github.com/labring/FastGPT/assets/91023337/c8773929-cbc1-495f-aae8-8c59fd334d20)

**相关示例**

**Comment by xiaoToby** [comment]
改./projects/app/src/pages/api/common/system/getInitData.ts中的docUrl
然后再构建一个项目镜像，参考dev.md

**Comment by eric20100106** [comment]
我系统是部署在docker中的，通过修改配置文件可以实现吗？改哪个地方呢？

**Comment by ptisnoob** [comment]
改完代码，重新打包，docker build。完整命令在文档中应该有:https://doc.fastgpt.in/docs/development/intro/#6-%E9%83%A8%E7%BD%B2%E6%89%93%E5%8C%85

**Comment by c121914yu** [comment]
配置文件中 feConfigs.docUrl  可以

**Comment by ptisnoob** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sdytzjp** [comment]
> 配置文件中 feConfigs.docUrl 可以

请问那个配置文件？config.json没有找到。 4.8.5

**Comment by sdytzjp** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 features
> * [x]  我已确认我已升级到最新版本
> * [x]  我已完整查看过项目 README，已确定现有版本无法满足需求
> * [x]  我理解并愿意跟进此 features，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**
> 
> **功能描述** 我本地使用hugo搭建了fastgpt的docSite,通过localhost:1313可以访问，但如何将此地址配置到Fastgpt系统首页呢？ 我尝试在config.json中的feConfigs增加docUrl属性，但重启后并未加载该属性。 



请问改成了吗，同样的需求

**Comment by ptisnoob** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
