### ISSUE TITLE
dev.md 中的dev

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#1927]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8.5
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/40045458/42957e8e-acbd-4aad-8e56-9322f2ae98ec)
执行图中红框中的命令
会报图中错误：
![image](https://github.com/labring/FastGPT/assets/40045458/4f6be4f4-04f8-4845-bcb8-f09eb6ed103e)

@c121914yu @nongmo677 @lijiajun1997
**复现步骤**

**预期结果**

**相关截图**

**Comment by xiaoToby** [comment]
![image](https://github.com/labring/FastGPT/assets/40045458/a5f8e521-b61c-44dc-a430-d9e383616401)
![image](https://github.com/labring/FastGPT/assets/40045458/1890b1b0-89aa-4c9b-b797-0671a95be18b)
![image](https://github.com/labring/FastGPT/assets/40045458/576d5679-63aa-46fe-966f-bd419abb1d6b)

**Comment by c121914yu** [comment]
数据库连不上，自行检查数据库连接

**Comment by xiaoToby** [comment]
MONGODB_URI=mongodb://username:password@127.0.0.1:27018/fastgpt?authSource=admin&directConnection=true
