### ISSUE TITLE
创建训练订单出错

### ISSUE THREAD

**Issue by dreamfly32** [labring/FastGPT#1928]
版本：v4.8.5
部分代码：
```
api_key='fastgpt-hSp'
headers = {
    "Authorization": f'Bearer {api_key}',
    'Content-Type':'application/json'
}

def create_order():
    url=f'{base_url}/support/wallet/usage/createTrainingUsage'
    body={'name':'test.docx'}
    r=requests.post(url,json=body,headers=headers)
    print(r.text)
```
报错：{"code":501000,"statusText":"unAuthDataset","message":"core.dataset.error.unAuthDataset","data":null}

api_key是对的，其他接口能用，换应用的api_key也是这个提示

**Comment by c121914yu** [comment]
<img width="515" alt="image" src="https://github.com/labring/FastGPT/assets/50446880/d01a09e3-0c58-4bc0-9d6c-1c1da72242c5">

我试了试，没发现问题

**Comment by c121914yu** [comment]
更新下
