### ISSUE TITLE
可否实现登录并获取登录账号信息

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1931]
请问可否实现用户登录功能，并获取到用户信息，然后在对接相关业务系统api时将账号传过去，获取的是用户自己的信息，例如查工资等，

**Comment by c121914yu** [comment]
url 携带 token注入全局变量，并通过 http解析获取用户信息

**Comment by sdytzjp** [comment]
不太明白，有没有案例或者代码参考下
