### ISSUE TITLE
豆包向量模型无法使用

### ISSUE THREAD

**Issue by cl165** [labring/FastGPT#1932]
通过oneapi配置豆包模型
1、豆包的语言模型可以正常使用
2、豆包的向量模型报错

<img width="410" alt="image" src="https://github.com/labring/FastGPT/assets/6203863/b01a6f06-45ef-4db7-9ffe-a30de34aee1d">

<img width="937" alt="image" src="https://github.com/labring/FastGPT/assets/6203863/25fb6d17-9b56-48f3-b639-809e5fad78cb">

**Comment by c121914yu** [comment]
提 oneapi

**Comment by 704572066** [comment]
@cl165 豆包的config.json配置能发一下吗

**Comment by cl165** [comment]
> @cl165 豆包的语言模型config.json配置能发一下吗

<img width="383" alt="image" src="https://github.com/user-attachments/assets/2d195080-b710-404a-af71-ee5fe27e18f1">
