### ISSUE TITLE
问题分类识别为空

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1933]
为什么问题分类无法识别，即便用了提示词也是默认到最后一个分类，config.json里面参数已经改了
 "toolChoice": false,
 "functionCall": false,

![image](https://github.com/labring/FastGPT/assets/174102361/8b65b495-f8ff-4862-b39b-64cfd8e93f40)
![image](https://github.com/labring/FastGPT/assets/174102361/2bec93aa-6866-4030-b041-9b359717e8e1)

**Comment by c121914yu** [comment]
换模型
