### ISSUE TITLE
HTTP请求模块对于 array<object>格式数据没有返回，返回了空

### ISSUE THREAD

**Issue by wingtao** [labring/FastGPT#1934]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![Xnip2024-07-03_20-38-42](https://github.com/labring/FastGPT/assets/17567845/2705b5f2-f7c3-46b2-a10d-e5dc9c7f0646)

**复现步骤**
1. 定义 http 请求response 字段 result 类型为 array<object>,并且http 请求实际返回 array<object>类型
2. 下一个代码执行节点，增加一个变量也定义为 array<object>，并且引用上一个 http 节点的 response result，

**预期结果**
下一个节点可以获取到 http 节点的返回的 result

**相关截图**
![Xnip2024-07-03_20-38-42](https://github.com/labring/FastGPT/assets/17567845/2705b5f2-f7c3-46b2-a10d-e5dc9c7f0646)

** 可能原因 ** 
看代码里数组类的数据都直接返回的空对象，不知道为什么这么做
<img width="1038" alt="Xnip2024-07-03_20-42-49" src="https://github.com/labring/FastGPT/assets/17567845/3a71fcf0-44d9-4cef-9f33-5adddf9d6544">

**Comment by c121914yu** [comment]
自定义输出 result，就只会获取 key=result 的 value 值
