### ISSUE TITLE
http调用接口返回的json如何取值

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1936]
请问http请求获取的json格式，如何处理，如何取某一个、多个值，返回给用户
![image](https://github.com/labring/FastGPT/assets/174102361/153f3b19-731f-4f79-a6a3-94fb337c63ad)
![image](https://github.com/labring/FastGPT/assets/174102361/7a5926da-9b31-408e-bb82-29b7a2131a20)

**Comment by c121914yu** [comment]
字段名： email
