### ISSUE TITLE
文本内容提取 插件 BUG

### ISSUE THREAD

**Issue by cl165** [labring/FastGPT#1939]
文本内容提取工具，
1、使用openai接口时，正常
2、使用其他国内大模型时，无法使用
<img width="1345" alt="image" src="https://github.com/labring/FastGPT/assets/6203863/d973136c-216d-46bf-9c58-8980170e5d0d">
<img width="1320" alt="image" src="https://github.com/labring/FastGPT/assets/6203863/40ce0d12-c5d5-43b7-94fb-1dbd821104a9">

**Comment by c121914yu** [comment]
看文档，把un tool 测试结果发出来再提

**Comment by sdytzjp** [comment]
not tool call 在哪里，没找到？"usedInToolCall": false,"toolChoice": false, "functionCall": false,

**Comment by sdytzjp** [comment]
> 文本内容提取工具， 1、使用openai接口时，正常 2、使用其他国内大模型时，无法使用 <img alt="image" width="1345" src="https://private-user-images.githubusercontent.com/6203863/345679187-d973136c-216d-46bf-9c58-8980170e5d0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTE1MDgsIm5iZiI6MTcyMDE1MTIwOCwicGF0aCI6Ii82MjAzODYzLzM0NTY3OTE4Ny1kOTczMTM2Yy0yMTZkLTQ2YmYtOWM1OC04OTgwMTcwZTVkMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMDM0NjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJjNzdkMzM1ZjliYzllM2MzZTBmYjhmNmM3MmEwZGIzNDNlNThiMzNiZTAyMGEwOTliZGZmMjBiMmM2NGQ3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fLcFnYSaghddqKBCs0rM1TBm8esiRdOALpcwqRZGsF0"> <img alt="image" width="1320" src="https://private-user-images.githubusercontent.com/6203863/345679291-40ce0d12-c5d5-43b7-94fb-1dbd821104a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTE1MDgsIm5iZiI6MTcyMDE1MTIwOCwicGF0aCI6Ii82MjAzODYzLzM0NTY3OTI5MS00MGNlMGQxMi1jNWQ1LTQzYjctOTRmYi0xZGJkODIxMTA0YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMDM0NjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njc0OWFlNWMxZWU4YWU1NTQzY2IwZDkwZjNhMjY4ODU1MTM0ZmQ2MzAzMDA5NWQ3MTA0MzA1YmM3NzIyMWJhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nvMGzeKqlxEc1UWBpcAh_shP4iHHLMp-xKY6hQIbB0k">


请问你有进展没

**Comment by cl165** [comment]
> 看文档，把not tool call 测试结果发出来再提.

<img width="455" alt="image" src="https://github.com/labring/FastGPT/assets/6203863/a06709bc-7147-49a3-82f5-1a803370e347">
所有的模型都是打开的
