### ISSUE TITLE
使用文心 Embedding-V1 成向量错误

### ISSUE THREAD

**Issue by dreamlist** [labring/FastGPT#194]
生成向量错误: error: expected 1536 dimensions, not 384

**Comment by leilichuan** [comment]
ebedding的维度不一样，作者默认openAI的text-embedding-ada-002，维度是1536，其他模型有384、768 1024的
解决方法：到PG向量库中将向量的维度改为对应模型的维度，重启 ALTER TABLE modeldata alter COLUMN vector type vector(384)

**Comment by taurusduan** [comment]
> ebedding的维度不一样，作者默认openAI的text-embedding-ada-002，维度是1536，其他模型有384、768 1024的 解决方法：到PG向量库中将向量的维度改为对应模型的维度，重启 ALTER TABLE modeldata alter COLUMN vector type vector(384)

你好，请教下如何修改纬度，谢谢啊。

**Comment by dreamlist** [comment]
> > ebedding的维度不一样，作者默认openAI的text-embedding-ada-002，维度是1536，其他模型有384、768 1024的 解决方法：到PG向量库中将向量的维度改为对应模型的维度，重启 ALTER TABLE modeldata alter COLUMN vector type vector(384)
> 
> 你好，请教下如何修改纬度，谢谢啊。
找到  mongo.ts 
![image](https://github.com/labring/FastGPT/assets/25025990/3a25225b-494f-4694-99cb-28efc375e1f0)
修改为 vector VECTOR(384) 就行了

**Comment by lifeofbow** [comment]
> > > ebedding的维度不一样，作者默认openAI的text-embedding-ada-002，维度是1536，其他模型有384、768 1024的 解决方法：到PG向量库中将向量的维度改为对应模型的维度，重启 ALTER TABLE modeldata alter COLUMN vector type vector(384)
> > 
> > 
> > 你好，请教下如何修改纬度，谢谢啊。
> > 找到  mongo.ts
> > ![image](https://user-images.githubusercontent.com/25025990/262235633-3a25225b-494f-4694-99cb-28efc375e1f0.png)
> > 修改为 vector VECTOR(384) 就行了

感谢

**Comment by c121914yu** [comment]
好的。目前维度已经做了补0，不同维度也可以使用

**Comment by lifeofbow** [comment]
> 

刚刚更新的吗，我今早拉得好像还不行

**Comment by lifeofbow** [comment]
> 目前维度已经做了补0，不同维度也可以使用

容器更新了吗

**Comment by c121914yu** [comment]
> > 目前维度已经做了补0，不同维度也可以使用
> 
> 容器更新了吗

噢抱歉，，可能得等下。。只改了训练，，忘记改调用的地方

**Comment by lifeofbow** [comment]
> > > 目前维度已经做了补0，不同维度也可以使用
> > 
> > 
> > 容器更新了吗
> 
> 噢抱歉，，可能得等下。。只改了训练，，忘记改调用的地方

好的谢谢

**Comment by c121914yu** [comment]
已支持，参考最新发行版说明：https://github.com/labring/FastGPT/releases/tag/v4.2.1

**Comment by lifeofbow** [comment]
更新后对接还有报错，有大佬知道什么原因吗
QA】任务完成
2023-08-28 11:03:41 生成向量错误: RangeError: Invalid array length
2023-08-28 11:03:41     at unityDimensional (/app/.next/server/chunks/5686.js:3680:24)
2023-08-28 11:03:41     at /app/.next/server/chunks/5686.js:3667:48
2023-08-28 11:03:41     at Array.map (<anonymous>)
2023-08-28 11:03:41     at /app/.next/server/chunks/5686.js:3667:36
2023-08-28 11:03:41     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-28 11:03:41     at async getVector (/app/.next/server/chunks/5686.js:3654:20)
2023-08-28 11:03:41     at async generateVector (/app/.next/server/chunks/5686.js:4329:30)
2023-08-28 11:03:42 【索引】任务完成

**Comment by taurusduan** [comment]
> > > ebedding的维度不一样，作者默认openAI的text-embedding-ada-002，维度是1536，其他模型有384、768 1024的 解决方法：到PG向量库中将向量的维度改为对应模型的维度，重启 ALTER TABLE modeldata alter COLUMN vector type vector(384)
> > 
> > 
> > 你好，请教下如何修改纬度，谢谢啊。
> > 找到  mongo.ts
> > ![image](https://user-images.githubusercontent.com/25025990/262235633-3a25225b-494f-4694-99cb-28efc375e1f0.png)
> > 修改为 vector VECTOR(384) 就行了

好的，非常感谢，我刚才已经适配好了。
