### ISSUE TITLE
HTTP模块请求的URL可以调用变量

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#1940]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
HTTP模块请求的URL可以调用变量

**应用场景**
有时候通过HTTP调用外部成熟应用时，一些成熟应用变量不是通过URL参数带入（如: http://xxxxxxxxxx/?变量/xxx）而是写死的(如: 如: http://xxxxxxxxxx/变量/xxx)。
因为目前的HTTP模块就不能支持这一类的调用，只能再写一层API来调用，不够灵活。

**相关示例**

**Comment by c121914yu** [comment]
没看懂

**Comment by zaite** [comment]
> 没看懂

他的意思应该是需要url路径的自定义组装，把变量引入进去

**Comment by c121914yu** [comment]
忘记 close，好几个版本前就可以了
