### ISSUE TITLE
调用post方法body中获取的json格式总是报错无效

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1941]
如下图，AI可以正常生成Json格式的内容，然后调给http请求中的Body处理，但是总是提示无效的json格式。
如果直接将json写入到body中就没有问题。
![image](https://github.com/labring/FastGPT/assets/174102361/78c12fb4-732e-4d23-983e-e2a7160336b9)
![image](https://github.com/labring/FastGPT/assets/174102361/abf9630c-1d3a-40bc-a5e4-012d4d2ff2a3)
![image](https://github.com/labring/FastGPT/assets/174102361/19055e44-b8ce-4883-b091-8e0926851540)

**Comment by sdytzjp** [comment]
我用AI把代码块```json 和```，这些字符去掉，也在报错，提示无效的json格式，提示json里面有很多类似\n之类的信息

**Comment by c121914yu** [comment]
``` 开头，怎么会是 json～ 自己检查 JSON 字符串是否合法

**Comment by sdytzjp** [comment]
> 

我怀疑是这个http的模块中，body本身的代码转换处理和验证机制有问题。
如果我在body中直接写json就ok，而且可以成功调用接口。
但是如果通过其他模块把json输入到http的body中，就提示json body语法错误，而且也并不调用接口。

这是一个bug吧？应该怎么解决

**Comment by sdytzjp** [comment]
![Uploading mmexport1720101095805.png…]()

**Comment by lijiajun1997** [comment]
有同样的问题
