### ISSUE TITLE
多个页面弹窗错误，对话结束或者导入页面控制台也会报同样错误<!DOCTYPE html><html lang="zh"><head><style data-next-hide-fouc="true">body{display:none}</style>

### ISSUE THREAD

**Issue by Yoki659** [labring/FastGPT#1944]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
进入工作台就会弹窗，对话结束后也会打印该信息，进入团队等页面也均有弹窗
![image](https://github.com/labring/FastGPT/assets/174691137/cc45650c-db48-4511-bffd-6d52f74be7a9)

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/174691137/a1ef0c0e-80db-40b0-8d40-7ac0ae8a778e)
![image](https://github.com/labring/FastGPT/assets/174691137/0cec36f4-a79a-413a-aa27-a435a79189c6)

**Comment by c121914yu** [comment]
估计你是配了商业版地址，但是又没有服务～
