### ISSUE TITLE
【bug急】 工具调用+应用调用后，没有上下文引用

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1945]
最新版，本地部署
工具调用+应用调用后，关于上下文引用存在bug，如下
1、在调试界面，上下文显示正常，如第一张图
2、在立即对话界面，上下文显示正常，如第二张图
3、发布应用时，勾选了返回引用，如第三张图
4、**在免登录窗口，没有出现上下文！！！！！！！！！！，如第四张图**
5、这个被调用的应用，使用免登录窗口时，上下文引用正常显示。

![image](https://github.com/labring/FastGPT/assets/174102361/8d5f4ad2-746a-4ba6-ae24-83da230a6ec0)
![image](https://github.com/labring/FastGPT/assets/174102361/cd208ba1-8d58-4b19-a070-03f6c3d5e357)
![image](https://github.com/labring/FastGPT/assets/174102361/635f7e18-0588-4486-a47c-d5d2bbc1c573)
![image](https://github.com/labring/FastGPT/assets/174102361/dfe37137-0fdc-40aa-8f9e-28176b5408ed)

**Comment by c121914yu** [comment]
分享链接不会提示上下文

**Comment by sdytzjp** [comment]
> 分享链接不会提示上下文

你没明白我的意思吧。免登录窗口有上下文引用的，只是通过通过工具调用和应用调用后没有上下文
