### ISSUE TITLE
回答不完整，好像被限制字数

### ISSUE THREAD

**Issue by zenmic7** [labring/FastGPT#1949]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8.5

**问题描述, 日志截图**
同样的配置，知识库放单个文件测试，能完整问题，索引文件多时，回答问题不完整，只回答一部分就戛然而止，更换索引模型也不能解决问题。
**复现步骤**

**预期结果**

**相关截图**
![STIIITCH_2024_07_04_06_35_47](https://github.com/labring/FastGPT/assets/99777809/3c825bd4-e764-447a-bfb4-f83f28162553)
![IMG_0761](https://github.com/labring/FastGPT/assets/99777809/ca1f647c-26f9-40da-8c8c-fdb347068e74)

**Comment by c121914yu** [comment]
模型max token 上限了，可以考虑把最大上下文设置小点，预留足够的空间给回复。例如：32k 模型，最大上下文设置 28k 即可

**Comment by zenmic7** [comment]
> 模型max token 上限了，可以考虑把最大上下文设置小点，预留足够的空间给回复。例如：32k 模型，最大上下文设置 28k 即可

谢谢，是不是需要我把索引模型的max token设大点，我的聊天模型需要改啥吗？麻烦指点一下，感谢🙏
![Uploading IMG_0762.jpeg…]()

**Comment by SDAIer** [comment]
怎么解决的
