### ISSUE TITLE
【问题】聊天客户端在流式回答过程中点“停止”，没有正确的给后端大模型发停止消息，导致后端模型还在输出

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#195]

**Comment by c121914yu** [comment]
终止是没法终止模型api的，没见哪个厂商提供了终止操作

**Comment by JinCheng666** [comment]
> 终止是没法终止模型api的，没见哪个厂商提供了终止操作

请问在api调用对话接口的应用场景中，如何能实现停止回答的操作？或者在一个问答窗口中，实现并发提问？

一、fastgpt页面，有停止回答功能，调用后能看到，但没有接口说明，不知道该如何使用
curl 'http://10.4.134.11:3020/_next/data/OLRnvyIpwtGgTD4p7MF0h/zh/chat.json?chatId=c91bj6l78lc4&appId=65efb0b8b12a789bea7777f7' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
  -H 'Connection: keep-alive' \
  -H 'Referer: http://10.4.134.11:3020/chat?appId=65efb0b8b12a789bea7777f7' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0' \
  -H 'x-nextjs-data: 1' \
  --insecure

二、在一个问答窗口中，用不同的chatid提问，接口返回的流数据的id均为空，导致无法将流式回答，区分到不同的提问上。
curl --location --request POST 'https://api.fastgpt.in/api/v1/chat/completions' \
--header 'Authorization: Bearer fastgpt-xxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "chatId": "abcd",//在一个问答窗口中，随机生成不同的chatid
    "stream": false,
    "detail": false,

**Comment by c121914yu** [comment]
> > 终止是没法终止模型api的，没见哪个厂商提供了终止操作
> 
> @c121914yu 请问在api调用对话接口的应用场景中，如何能实现停止回答的操作？或者在一个问答窗口中，实现并发提问？
> 
> 一、fastgpt页面，有停止回答功能，调用后能看到，但没有接口说明，不知道该如何使用 curl 'http://10.4.134.11:3020/_next/data/OLRnvyIpwtGgTD4p7MF0h/zh/chat.json?chatId=c91bj6l78lc4&appId=65efb0b8b12a789bea7777f7' -H 'Accept: _/_' -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' -H 'Connection: keep-alive' -H 'Referer: http://10.4.134.11:3020/chat?appId=65efb0b8b12a789bea7777f7' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0' -H 'x-nextjs-data: 1' --insecure ![image](https://private-user-images.githubusercontent.com/48248936/331155307-60c0b7d1-f261-4b60-a8d2-e3cd5f3c708f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTQyMjksIm5iZiI6MTcxNTg1MzkyOSwicGF0aCI6Ii80ODI0ODkzNi8zMzExNTUzMDctNjBjMGI3ZDEtZjI2MS00YjYwLWE4ZDItZTNjZDVmM2M3MDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZmM3MTkwMjMxMjFiMzFiMjBiOWNhNjZkOTlmMmNjZjA4YWY1Y2QyOTg3YjhiZmMyNmUzY2FlMWQ5NmI5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nGpzL0xLelNuA3J0LWbDH9dZCm4R6EHKV9b3oEhDl1s)
> 
> 二、在一个问答窗口中，用不同的chatid提问，接口返回的流数据的id均为空，导致无法将流式回答，区分到不同的提问上。 curl --location --request POST 'https://api.fastgpt.in/api/v1/chat/completions' --header 'Authorization: Bearer fastgpt-xxxxxx' --header 'Content-Type: application/json' --data-raw '{ "chatId": "abcd",//在一个问答窗口中，随机生成不同的chatid "stream": false, "detail": false,
> 
> ![image](https://private-user-images.githubusercontent.com/48248936/331155678-95c8c7c1-f516-4f22-b292-b80ce0fd702a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTQyMjksIm5iZiI6MTcxNTg1MzkyOSwicGF0aCI6Ii80ODI0ODkzNi8zMzExNTU2NzgtOTVjOGM3YzEtZjUxNi00ZjIyLWIyOTItYjgwY2UwZmQ3MDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZGU1YzU2MzIxNjdlYjZiZTE1NzZkZGM2MGM3NjBmZTc1OGIzY2E0NzAyOWZmYWUzNjZjNjZjMWQ2MzEzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8utAXId6vsnDhUtU6IOAQ1ekM2He0T8HrFGN8J84uTs)

abort掉请求即可。后端会自动中断和api的服务。

**Comment by JinCheng666** [comment]
> > > 终止是没法终止模型api的，没见哪个厂商提供了终止操作
> > 
> > 
> > @c121914yu 请问在api调用对话接口的应用场景中，如何能实现停止回答的操作？或者在一个问答窗口中，实现并发提问？
> > 一、fastgpt页面，有停止回答功能，调用后能看到，但没有接口说明，不知道该如何使用 curl 'http://10.4.134.11:3020/_next/data/OLRnvyIpwtGgTD4p7MF0h/zh/chat.json?chatId=c91bj6l78lc4&appId=65efb0b8b12a789bea7777f7' -H 'Accept: _/_' -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' -H 'Connection: keep-alive' -H 'Referer: http://10.4.134.11:3020/chat?appId=65efb0b8b12a789bea7777f7' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0' -H 'x-nextjs-data: 1' --insecure ![image](https://private-user-images.githubusercontent.com/48248936/331155307-60c0b7d1-f261-4b60-a8d2-e3cd5f3c708f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTQyMjksIm5iZiI6MTcxNTg1MzkyOSwicGF0aCI6Ii80ODI0ODkzNi8zMzExNTUzMDctNjBjMGI3ZDEtZjI2MS00YjYwLWE4ZDItZTNjZDVmM2M3MDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZmM3MTkwMjMxMjFiMzFiMjBiOWNhNjZkOTlmMmNjZjA4YWY1Y2QyOTg3YjhiZmMyNmUzY2FlMWQ5NmI5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nGpzL0xLelNuA3J0LWbDH9dZCm4R6EHKV9b3oEhDl1s)
> > 二、在一个问答窗口中，用不同的chatid提问，接口返回的流数据的id均为空，导致无法将流式回答，区分到不同的提问上。 curl --location --request POST 'https://api.fastgpt.in/api/v1/chat/completions' --header 'Authorization: Bearer fastgpt-xxxxxx' --header 'Content-Type: application/json' --data-raw '{ "chatId": "abcd",//在一个问答窗口中，随机生成不同的chatid "stream": false, "detail": false,
> > ![image](https://private-user-images.githubusercontent.com/48248936/331155678-95c8c7c1-f516-4f22-b292-b80ce0fd702a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTQyMjksIm5iZiI6MTcxNTg1MzkyOSwicGF0aCI6Ii80ODI0ODkzNi8zMzExNTU2NzgtOTVjOGM3YzEtZjUxNi00ZjIyLWIyOTItYjgwY2UwZmQ3MDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZGU1YzU2MzIxNjdlYjZiZTE1NzZkZGM2MGM3NjBmZTc1OGIzY2E0NzAyOWZmYWUzNjZjNjZjMWQ2MzEzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8utAXId6vsnDhUtU6IOAQ1ekM2He0T8HrFGN8J84uTs)
> 
> abort掉请求即可。后端会自动中断和api的服务。 同一个窗口chatId都相同，怎么会有不同呢？

感谢大佬，我给前端反馈下。直接abort掉请求
