### ISSUE TITLE
v4.8.6-alpha 对话报错

### ISSUE THREAD

**Issue by Forevery1** [labring/FastGPT#1952]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.6-alpha

**问题描述, 日志截图**
<img width="573" alt="image" src="https://github.com/labring/FastGPT/assets/19872771/8683f8f1-94f4-4a3f-9de8-31517cd6b4e7">

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
未复现，自行检查接口

**Comment by Forevery1** [comment]
> 未复现，自行检查接口。接口问题，自己调通再提，别浪费别人时间。 curl 测试，stream 模式测试结果。

v4.8.5是正常的、我刚更新完。试了下不正常

**Comment by Forevery1** [comment]
> 未复现，自行检查接口。接口问题，自己调通再提，别浪费别人时间。 curl 测试，stream 模式测试结果。

算了、我还是切回v4.8.5吧

**Comment by Forevery1** [comment]
<img width="1367" alt="image" src="https://github.com/labring/FastGPT/assets/19872771/08c49e45-8cab-4b7e-806b-c455a735bc2a">
@c121914yu 这是我看oneapi的日志、下面成功那条是调oneapi的测试按钮输出的。error unmarshalling stream response: invalid character '}' after top-level value是在fastgpt中调对话的

**Comment by c121914yu** [comment]
> <img alt="image" width="1367" src="https://private-user-images.githubusercontent.com/19872771/345812377-08c49e45-8cab-4b7e-806b-c455a735bc2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTI1MjUsIm5iZiI6MTcyMDA5MjIyNSwicGF0aCI6Ii8xOTg3Mjc3MS8zNDU4MTIzNzctMDhjNDllNDUtOGNhYi00YjdlLTgwNmItYzQ1NWE3MzViYzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDExMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YjgxNzEwY2FmNDIwMjIwYmE1MTg5OGY4OWMxZTljOTFkZTNiYzdjYTY3YmZhNzA3MjI0YmExYzQ4ZmQ4MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kel3HOsoAwnkSfPkxD_o1LkgZY2e_G-3rn9rxvatmUE"> @c121914yu 这是我看oneapi的日志、下面成功那条是调oneapi的测试按钮输出的。error unmarshalling stream response: invalid character '}' after top-level value是在fastgpt中调对话的

看着是这个模型流输出是有问题

**Comment by Forevery1** [comment]
> > <img alt="image" width="1367" src="https://private-user-images.githubusercontent.com/19872771/345812377-08c49e45-8cab-4b7e-806b-c455a735bc2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTI1MjUsIm5iZiI6MTcyMDA5MjIyNSwicGF0aCI6Ii8xOTg3Mjc3MS8zNDU4MTIzNzctMDhjNDllNDUtOGNhYi00YjdlLTgwNmItYzQ1NWE3MzViYzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDExMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YjgxNzEwY2FmNDIwMjIwYmE1MTg5OGY4OWMxZTljOTFkZTNiYzdjYTY3YmZhNzA3MjI0YmExYzQ4ZmQ4MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kel3HOsoAwnkSfPkxD_o1LkgZY2e_G-3rn9rxvatmUE"> @c121914yu 这是我看oneapi的日志、下面成功那条是调oneapi的测试按钮输出的。error unmarshalling stream response: invalid character '}' after top-level value是在fastgpt中调对话的
> 
> 看着是这个模型流输出是有问题

好的、我去看看是不是ollama的问题

**Comment by Forevery1** [comment]
感谢大佬、找到问题了。更新fastgpt的时候脚本把oneapi也更新了（v0.6.8）的问题、切换v0.6.7就没有问题了。

**Comment by c121914yu** [comment]
> 感谢大佬、找到问题了。更新fastgpt的时候脚本把oneapi也更新了（v0.6.8）的问题、切换v0.6.7就没有问题了。

好的，记得给他们提下

**Comment by sdytzjp** [comment]
> > 感谢大佬、找到问题了。更新fastgpt的时候脚本把oneapi也更新了（v0.6.8）的问题、切换v0.6.7就没有问题了。
> 
> 好的，记得给他们提下

不能使用oneapiv0.6.8吗

**Comment by Forevery1** [comment]
> > > 感谢大佬、找到问题了。更新fastgpt的时候脚本把oneapi也更新了（v0.6.8）的问题、切换v0.6.7就没有问题了。
> > 
> > 好的，记得给他们提下
> 
> 不能使用oneapiv0.6.8吗

是的，以提bug，不过oneapi那边貌似没有管

**Comment by ChoresS** [comment]
请问，oneapi版本怎么降低

**Comment by sdytzjp** [comment]
docker compose文件把oneapi image改为.7的版本

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 上午10:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] v4.8.6-alpha 对话报错 (Issue #1952)




 
请问，oneapi版本怎么降低

**Comment by sdytzjp** [comment]
0.6.7
