### ISSUE TITLE
【bug急】http请求API接口，提示body语法错误

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1956]
之前提报过问题，没有解决也没有回复就被close了。这个问题很着急，导致无法post接口，麻烦看下是不是bug，如何解决

安装的本地最新版本

如下图，内容提取可以正常生成Json格式的内容，然后调给http请求中的Body处理，但是总是提示【无效的body体】。
如果直接将内容提取的json复制到body中就没有问题。

我觉得是这个http的模块中body本身的代码转换处理机制有问题，导致json格式错误且不调用接口。

下面的日志以及错误信息

![image](https://github.com/labring/FastGPT/assets/174102361/e1580cb6-a100-47ec-8930-c605d58c310b)

![image](https://github.com/labring/FastGPT/assets/174102361/74bcd2fa-d890-4ec0-8cc4-250fa3871a67)

![image](https://github.com/labring/FastGPT/assets/174102361/1863d9de-e060-4427-a821-d1c91d007521)

**Comment by newfish-cmyk** [comment]
可以直接把提取出来的参数填到输入里
```json
{
  "start_time": "{{start_time}}",
  "end_time": "{{end_time}}",
  "room": "{{room}}",
  "date": "{{date}}"
}
```

http 请求模块的输入一般作为变量值使用

如果一定要作为整个body的json的话，可以利用代码运行，传入object类型
<img width="940" alt="image" src="https://github.com/labring/FastGPT/assets/71265218/f1beaebc-bd9a-4c2c-9365-42efbfcf396c">

**Comment by sdytzjp** [comment]
> 可以直接把提取出来的参数填到输入里
> 
> ```json
> {
>   "start_time": "{{start_time}}",
>   "end_time": "{{end_time}}",
>   "room": "{{room}}",
>   "date": "{{date}}"
> }
> ```
> 
> http 请求模块的输入一般作为变量值使用
> 
> 如果一定要作为整个body的json的话，可以利用代码运行，传入object类型 <img alt="image" width="940" src="https://private-user-images.githubusercontent.com/71265218/346030746-f1beaebc-bd9a-4c2c-9365-42efbfcf396c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjcyMjIsIm5iZiI6MTcyMDI2NjkyMiwicGF0aCI6Ii83MTI2NTIxOC8zNDYwMzA3NDYtZjFiZWFlYmMtYmQ5YS00YzJjLTkzNjUtNDJlZmJmY2YzOTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDExNTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYTNiYjM5YmZmZjk2NWMzYTYwYTA2ZDkxNmFmY2E4YTAwMmExY2Q4ZjRiY2JiODgwYTcxNTZiNWZhNDg5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oW3A0G29iIaqxtBZkpmi1RHe2d110RhxLiDF3yfmKkI">

thanks
