### ISSUE TITLE
【bug】使用【工具调用】配合【应用调用】后，上下文【引用】无法显示

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#1957]
本地最新版
之前提过问题，大神可能理解的不太对而closed了，现在重新提交下

高级编排中，使用【工具调用】+【应用调用】后，关于上下文引用存在bug，
高级编排中，使用【问题分类】+【应用调用】后，也是无法出现上下文引用
为了方便编排，提前做了各个应用，然后通过工具调用或者分类分类，进行应用调用。但是因为这两种方式都无法显示“上下文引用”，导致用户提问题时看不到引用的具体信息，而大模型回答的有时候又天马行空，用户没有参考。

希望大神能解决下。
以下时针对无法引用的具体故障描述：

如下
1、在调试界面，上下文显示正常，如第一张图
2、在立即对话界面，上下文显示也正常，如第二张图
3、发布应用时，勾选了返回引用，如第三张图
4、在免登录窗口，却没有出现上下文！！！！！！！！！！，如第四张图
5、但是，这个被调用的应用，使用免登录窗口时，上下文引用也正常显示。
![a1](https://github.com/labring/FastGPT/assets/174102361/15c35dfb-b50a-4cc6-a8e9-af463ff47699)
![a2](https://github.com/labring/FastGPT/assets/174102361/5dcd915b-7200-41d4-8484-f2478d025d98)
![a2](https://github.com/labring/FastGPT/assets/174102361/550b1351-d140-4dd6-bb8d-26446c0efbce)
![a4](https://github.com/labring/FastGPT/assets/174102361/f67a4b55-c54c-4235-8a1b-c60727c0a095)

**Comment by c121914yu** [comment]
分享链接确实不会返回下面几个标签的内容

**Comment by sdytzjp** [comment]
分享链接是可以的显示引用的。只是当使用工具调用或问题分类的时候，无法显示上下文引用，用户看不到引用这个就体验很差了

**Comment by c121914yu** [comment]
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/c2a83d5f-5039-42c6-b0ee-894effb0dfa2">
可以看到引用～

**Comment by sdytzjp** [comment]
你好，你测试的是通过工具加应用的方式吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月7日(周三) 晚上7:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 【bug】使用【工具调用】配合【应用调用】后，上下文【引用】无法显示 (Issue #1957)




 image.png (view on web) 可以看到引用～
