### ISSUE TITLE
文本内容提取为空，userdInToolCall:flase，模型已更换

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1958]
文本内容提取为空，userdInToolCall:flase，模型已更换，仍然无法提取信息

userdInToolCall:flase
toolChoice:flase
functionCall:false

![c1](https://github.com/labring/FastGPT/assets/174102361/4e5163b3-5412-42d4-bc5b-75bf966f5a62)
![c2](https://github.com/labring/FastGPT/assets/174102361/d985eca7-3e3f-4101-b4a6-35c66c30c351)

**Comment by sdytzjp** [comment]
问题解决了，不好意思叨扰了，closed吧

**Comment by ppkitty** [comment]
怎么解决的呢？我也提取不出来

**Comment by sdytzjp** [comment]
换模型



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月12日(周五) 下午3:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [labring/FastGPT] 文本内容提取为空，userdInToolCall:flase，模型已更换 (Issue #1958)




 
怎么解决的呢？我也提取不出来

**Comment by xgl6** [comment]
换的哪个模型

**Comment by jimjigreen** [comment]
我也想知道换的那个模型
