### ISSUE TITLE
one api添加渠道，复制了百度的api key，点击测试，报错get request url failed: invalid baidu apikey

### ISSUE THREAD

**Issue by Wuqunqun** [labring/FastGPT#1959]
![image](https://github.com/labring/FastGPT/assets/34914164/aab8ed55-286f-4094-a75e-6d168c54b6ae)

**Comment by c121914yu** [comment]
错误很明显了，建议翻译一下

**Comment by teanon** [comment]
你的配置的url 是啥呀?
