### ISSUE TITLE
通义千问的config.json怎么配置

### ISSUE THREAD

**Issue by Wuqunqun** [labring/FastGPT#1960]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**相关示例**

**Comment by hellokid200** [comment]
{
    "model": "qwen-max",
    "name": "Qwen-Max",
    "avatar": "/imgs/model/qwen.svg",
    "maxContext": 16000,
    "maxResponse": 4000,
    "quoteMaxToken": 13000,
    "maxTemperature": 1.2,
    "charsPointsPrice": 0,
    "censor": false,
    "vision": false,
    "datasetProcess": true,
    "usedInClassify": true,
    "usedInExtractFields": true,
    "usedInToolCall": true,
    "usedInQueryExtension": true,
    "toolChoice": true,
    "functionCall": false,
    "customCQPrompt": "",
    "customExtractPrompt": "",
    "defaultSystemChatPrompt": "",
    "defaultConfig": {}
  }

**Comment by Wuqunqun** [comment]
> { "model": "qwen-max", "name": "Qwen-Max", "avatar": "/imgs/model/qwen.svg", "maxContext": 16000, "maxResponse": 4000, "quoteMaxToken": 13000, "maxTemperature": 1.2, "charsPointsPrice": 0, "censor": false, "vision": false, "datasetProcess": true, "usedInClassify": true, "usedInExtractFields": true, "usedInToolCall": true, "usedInQueryExtension": true, "toolChoice": true, "functionCall": false, "customCQPrompt": "", "customExtractPrompt": "", "defaultSystemChatPrompt": "", "defaultConfig": {} }

vectorModels怎么配置呢，你发的这个只能配置聊天吧，文档训练的能配置吗，索引模型

**Comment by xiaoToby** [comment]
https://doc.fastgpt.in/docs/development/custom-models/m3e/

**Comment by c121914yu** [comment]
复制，粘贴，修改 model 和 maxtoken 相关即可
