### ISSUE TITLE
数据库索引逻辑问题

### ISSUE THREAD

**Issue by SkyRaker0v0** [labring/FastGPT#1962]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [√] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

感觉现在的数据库索引逻辑反了
在索引完全一致的文本的时候发现全文检索无法命中，反而是语义检索命中了
而在fast上4.8之前是没有这个问题的，期望看看是不是索引逻辑变动

**Comment by c121914yu** [comment]
我去试试
