### ISSUE TITLE
[建议]生成QA时可以指定拆分的文档长度

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#197]

**Comment by c121914yu** [comment]
意义在哪里？

**Comment by jinghai** [comment]
> 意义在哪里？

比如在使用chatglm2-6b-32K模型时，我可以把分段长度设置的更大，同时制定生成更多问题。所以希望在生成QA前可以选择模型、指定长度，指定问题数量。最好还可以完全自己来设置生成QA的prompt

**Comment by jinghai** [comment]
因为不同模型对prompt的理解能力也有不同

**Comment by c121914yu** [comment]
> > 意义在哪里？
> 
> 比如在使用chatglm2-6b-32K模型时，我可以把分段长度设置的更大，同时制定生成更多问题。所以希望在生成QA前可以选择模型、指定长度，指定问题数量。最好还可以完全自己来设置生成QA的prompt

是根据模型最大长度自动匹配的。取45%

**Comment by gaord** [comment]
chatglm2支持prompt中的system消息吗？使用中感觉是被忽略的，而且出来的qa对子质量不高。

**Comment by c121914yu** [comment]
> chatglm2支持prompt中的system消息吗？使用中感觉是被忽略的，而且出来的qa对子质量不高。

glm2本身就不行～不太可能直接用于生产环境。
