### ISSUE TITLE
使用ollama模型进行对话时，提示对话接口报错或返回为空

### ISSUE THREAD

**Issue by rainless01** [labring/FastGPT#1972]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
在接入ollama本地模型进行对话时，出现了<对话接口报错或返回为空>的错误，查找了许多文档但是找不到解决办法

在oneapi中，模型通过了测试，也将模型加入到了令牌当中
![image](https://github.com/labring/FastGPT/assets/174859632/30fd3dc3-c688-476c-8a15-095c4e7432f7)
在最初启动容器的时候oneapi的日志
![image](https://github.com/labring/FastGPT/assets/174859632/c97b8e03-099a-415f-9fb9-00e383113853)
fastgpt的日志
![image](https://github.com/labring/FastGPT/assets/174859632/570e26ba-1a60-442a-ab63-be35913e8237)
以下是我的config的配置内容
![image](https://github.com/labring/FastGPT/assets/174859632/a5a2f576-3517-4d46-ac18-be255fbcf59a)
在进行对话以后，出现了报错，oneapi的日志如下
![image](https://github.com/labring/FastGPT/assets/174859632/32bc5a8c-8bc1-481d-bc8d-ab723da70a3d)
fastgpt日志如下
![image](https://github.com/labring/FastGPT/assets/174859632/2e7fac20-5c47-449a-8503-d3bd0f598e14)
但在ollama上可以正确运行本地模型
现在不知道哪个环节出现了问题，请大佬给出解决方法

**Comment by zhiwei22** [comment]
oneapi日志显示,failed to initialize database. 端口号3306
提示mysql数据库没法连接
可能是因为这个原因吗？

我遇到了相同的问题

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/1952
重复 issue

**Comment by rainless01** [comment]
> oneapi日志显示,failed to initialize database. 端口号3306 提示mysql数据库没法连接 可能是因为这个原因吗？
> 
> 我遇到了相同的问题

换一下oneapi的版本就好了，在docker-compose.yml文件里改一下oneapi的镜像版本，然后docker-compose pull就好了

**Comment by zhiwei22** [comment]
> > oneapi日志显示,failed to initialize database. 端口号3306 提示mysql数据库没法连接 可能是因为这个原因吗？
> > 我遇到了相同的问题
> 
> 换一下oneapi的版本就好了，在docker-compose.yml文件里改一下oneapi的镜像版本，然后docker-compose pull就好了



> #1952 重复 issue

感谢，已解决
