### ISSUE TITLE
chatgpt on webchat无法下载

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1973]
本地4.8.4
docker compose pull无法现在镜像，有没有办法解决
[root@zjpceshi wechat]# docker compose pull
WARN[0000] /root/wechat/docker-compose.yml: `version` is obsolete
[+] Pulling 0/11
 ⠹ chatgpt-on-wechat [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀] Pulling                                                                                                                          6.3s
   ⠧ 76956b537f14 Pulling fs layer                                                                                                                                 2.7s
   ⠧ f75f1b8a4051 Pulling fs layer                                                                                                                                 2.7s
   ⠧ f9adc358e0b8 Pulling fs layer                                                                                                                                 2.7s
   ⠧ f66e101ef41f Waiting                                                                                                                                          2.7s
   ⠧ b913137adf9e Waiting                                                                                                                                          2.7s
   ⠧ 4f4fb700ef54 Waiting                                                                                                                                          2.7s
   ⠧ c158b110a7fc Waiting                                                                                                                                          2.7s
   ⠧ 69748d11102e Waiting                                                                                                                                          2.7s
   ⠧ acc0a2c845c9 Waiting                                                                                                                                          2.7s
   ⠧ 07e330de0452 Waiting                                       

![image](https://github.com/labring/FastGPT/assets/174102361/e557d908-5d5f-4154-805d-81cdb2e5a5da)

![image](https://github.com/labring/FastGPT/assets/174102361/6f0ce468-d21e-45ba-8451-0e780a33b0a9)

**Comment by c121914yu** [comment]
网络问题自己解决
