### ISSUE TITLE
oneapi中多个渠道使用的是哪个渠道

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1974]
本地4 8 4
oneapi中部署了多个手机号申请的文心一言、以及多个账号的同义千问
例如有一个文心一言A，文心一言B两个渠道，分别是用两个手机号去申请的，而这两个渠道里面的模型都一样
因为config.json里面只是写明了模型的名字，没有指定使用oneapi里面那个渠道，所以我想知道对于同一个模型，fastgpt到底调用的是哪个渠道的。
oneapi日志里面也只是显示模型名

我的需求是：
1、比如从百度申请了两个账号，一个是购买的用于生产环境的模型，一个是免费试用的主要来测试的模型，但是模型的名字都一样
2、我希望对于有些fastgpt应用，直接使用购买的大模型去发布，而测试的应用去调用免费试用的模型来测试
以上怎么实现区分
![image](https://github.com/labring/FastGPT/assets/174102361/0a03ec53-c390-4f65-8032-8c50322f0da0)

![image](https://github.com/labring/FastGPT/assets/174102361/917899a0-1b19-45f9-89a6-90dc2af64afd)

**Comment by c121914yu** [comment]
具体可以看 oneapi 代码。
 oneapi 之前是随机的，新版有了优先级，不是完全随机了（同一个优先级情况下，不是完全随机）

**Comment by sdytzjp** [comment]
> 具体可以看 oneapi 代码。 oneapi 之前是随机的，新版有了优先级，不是完全随机了（同一个优先级情况下，不是完全随机） 可以设置免费的优先级更高，并设置一定重试，失败后会自动从所有渠道随机重试。
感谢回复。但达不到我的要求，我希望可以人为选择的，测试的走通义A里面的模型，生产走通以B里面的模型。
