### ISSUE TITLE
强烈建议高级编排取消自动保存

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1976]
本地最新版

强烈建议高级编排取消自动保存，这个自动保存太不好了，原来没问题的编排，尝试着调试些新的功能，结果自动保存了，问题是经过调试整个流程出问题了，导致原来的配置也都被更改了，还没办法回复原来的配置，只能重新再做一遍。

希望有个按键由用户自行决定是否保存。

**Comment by sdytzjp** [comment]
所有提示词的地方，不小心把手动输入改为变量，再改回来后，提示词都没了，还不容易调的

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8.10-alpha
