### ISSUE TITLE
适配fastgpt接入百度开放平台的重排模型  

### ISSUE THREAD

**Issue by xy3xy3** [labring/FastGPT#1977]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 features
- [ x] 我已确认我已升级到最新版本
- [x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

一个价格还可以的在线API

**应用场景**

混合搜索重排

**相关示例**

代码已经实现
# 开通服务

[百度智能云千帆大模型平台 (baidu.com)](https://console.bce.baidu.com/qianfan/chargemanage/list)

在平台搜索bce-reranker开通，价格 **¥0.002元/千tokens**

![image.png](https://blog.skyw.cc/usr/uploads/2024/07/1286042631.png)

# 获取AK,SK

[百度智能云-管理中心 (baidu.com)](https://console.bce.baidu.com/iam/#/iam/accesslist)
创建 Access Key ，复制它和Secret Key

# 本地挂脚本

脚本如下，注意替换自己的AK，SK

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import uvicorn
from fastapi import FastAPI, Security, HTTPException
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel
from typing import Optional, List
import qianfan
from qianfan.resources import Reranker

app = FastAPI()
security = HTTPBearer()
env_bearer_token = 'sk-xxx'

class QADocs(BaseModel):
    query: Optional[str]
    documents: Optional[List[str]]

class Singleton(type):
    def __call__(cls, *args, **kwargs):
        if not hasattr(cls, '_instance'):
            cls._instance = super().__call__(*args, **kwargs)
        return cls._instance

class ReRanker(metaclass=Singleton):
    def __init__(self):
        os.environ["QIANFAN_ACCESS_KEY"] = "你的AK"
        os.environ["QIANFAN_SECRET_KEY"] = "你的SK"
        self.reranker = Reranker(model="bce-reranker-base_v1")

    def compute_score(self, query: str, documents: List[str]):
        if len(documents) > 0:
            result = self.reranker.do(query, documents)
            return result.body['results']
        else:
            return None

class Chat(object):
    def __init__(self):
        self.reranker = ReRanker()

    def fit_query_answer_rerank(self, query_docs: QADocs) -> List:
        if query_docs is None or len(query_docs.documents) == 0:
            return []

        scores = self.reranker.compute_score(query_docs.query, query_docs.documents)

        new_docs = []
        for index, score in enumerate(scores):
            new_docs.append({"index": score['index'], "text": query_docs.documents[score['index']], "score": score['relevance_score']})
        results = [{"index": documents["index"], "relevance_score": documents["score"]} for documents in list(sorted(new_docs, key=lambda x: x["score"], reverse=True))]
        return results

@app.post('/v1/rerank')
async def handle_post_request(docs: QADocs, credentials: HTTPAuthorizationCredentials = Security(security)):
    token = credentials.credentials
    if env_bearer_token is not None and token != env_bearer_token:
        raise HTTPException(status_code=401, detail="Invalid token")
    chat = Chat()
    try:
        results = chat.fit_query_answer_rerank(docs)
        return {"results": results}
    except Exception as e:
        print(f"报错：\n{e}")
        return {"error": "重排出错"}

if __name__ == "__main__":
    token = os.getenv("ACCESS_TOKEN")
    if token is not None:
        env_bearer_token = token
    try:
        uvicorn.run(app, host='0.0.0.0', port=6006)
    except Exception as e:
        print(f"API启动失败！\n报错：\n{e}")
```

# 修改docker配置

docker-composer如下修改

```json
"reRankModels": [
        {
            "model": "bce-reranker-base_v1",
            "name": "检索重排-base",
            "charsPointsPrice": 0,
            "requestUrl": "http://你的服务器ip:6006/v1/rerank",
            "requestAuth": "sk-xx"
        }
    ],
```

https://blog.skyw.cc/archives/312.html

**Comment by c121914yu** [comment]
感觉有点贵。重排一次，基本 50*512 token 以上，相当于 25.6k tokens=5 分

**Comment by xy3xy3** [comment]
> 感觉有点贵。重排一次，基本 50*512 token 以上，相当于 25.6k tokens=0.05 元。 而对应 llm，一般也就花费 0.1 元（3.5 水平的模型）。 0.0002 元/1k token 还差不多。

确实，现在重排模型好像都很贵，刚刚看了一家中转的，价格比百度贵
![image](https://github.com/labring/FastGPT/assets/25221048/f5ed0d2e-bcaf-4495-a913-b5e5eda02a1d)

**Comment by sdytzjp** [comment]
抽空测试下效果

**Comment by sdytzjp** [comment]
> **例行检查**
> 
> * [x ] 我已确认目前没有类似 features
> * [ x] 我已确认我已升级到最新版本
> * [x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
> * [x ] 我理解并愿意跟进此 features，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**
> 
> **功能描述**
> 
> 一个价格还可以的在线API
> 
> **应用场景**
> 
> 混合搜索重排
> 
> **相关示例**
> 
> 代码已经实现
> 
> # 开通服务
> [百度智能云千帆大模型平台 (baidu.com)](https://console.bce.baidu.com/qianfan/chargemanage/list)
> 
> 在平台搜索bce-reranker开通，价格 **¥0.002元/千tokens**
> 
> ![image.png](https://camo.githubusercontent.com/a25a54cda58ed50002c242495e7470a2a4ebd7f524155322c168636ffed9b655/68747470733a2f2f626c6f672e736b79772e63632f7573722f75706c6f6164732f323032342f30372f313238363034323633312e706e67)
> 
> # 获取AK,SK
> [百度智能云-管理中心 (baidu.com)](https://console.bce.baidu.com/iam/#/iam/accesslist) 创建 Access Key ，复制它和Secret Key
> 
> # 本地挂脚本
> 脚本如下，注意替换自己的AK，SK
> 
> ```python
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> import os
> import uvicorn
> from fastapi import FastAPI, Security, HTTPException
> from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
> from pydantic import BaseModel
> from typing import Optional, List
> import qianfan
> from qianfan.resources import Reranker
> 
> app = FastAPI()
> security = HTTPBearer()
> env_bearer_token = 'sk-xxx'
> 
> class QADocs(BaseModel):
>     query: Optional[str]
>     documents: Optional[List[str]]
> 
> class Singleton(type):
>     def __call__(cls, *args, **kwargs):
>         if not hasattr(cls, '_instance'):
>             cls._instance = super().__call__(*args, **kwargs)
>         return cls._instance
> 
> class ReRanker(metaclass=Singleton):
>     def __init__(self):
>         os.environ["QIANFAN_ACCESS_KEY"] = "你的AK"
>         os.environ["QIANFAN_SECRET_KEY"] = "你的SK"
>         self.reranker = Reranker(model="bce-reranker-base_v1")
> 
>     def compute_score(self, query: str, documents: List[str]):
>         if len(documents) > 0:
>             result = self.reranker.do(query, documents)
>             return result.body['results']
>         else:
>             return None
> 
> class Chat(object):
>     def __init__(self):
>         self.reranker = ReRanker()
> 
>     def fit_query_answer_rerank(self, query_docs: QADocs) -> List:
>         if query_docs is None or len(query_docs.documents) == 0:
>             return []
> 
>         scores = self.reranker.compute_score(query_docs.query, query_docs.documents)
> 
>         new_docs = []
>         for index, score in enumerate(scores):
>             new_docs.append({"index": score['index'], "text": query_docs.documents[score['index']], "score": score['relevance_score']})
>         results = [{"index": documents["index"], "relevance_score": documents["score"]} for documents in list(sorted(new_docs, key=lambda x: x["score"], reverse=True))]
>         return results
> 
> @app.post('/v1/rerank')
> async def handle_post_request(docs: QADocs, credentials: HTTPAuthorizationCredentials = Security(security)):
>     token = credentials.credentials
>     if env_bearer_token is not None and token != env_bearer_token:
>         raise HTTPException(status_code=401, detail="Invalid token")
>     chat = Chat()
>     try:
>         results = chat.fit_query_answer_rerank(docs)
>         return {"results": results}
>     except Exception as e:
>         print(f"报错：\n{e}")
>         return {"error": "重排出错"}
> 
> if __name__ == "__main__":
>     token = os.getenv("ACCESS_TOKEN")
>     if token is not None:
>         env_bearer_token = token
>     try:
>         uvicorn.run(app, host='0.0.0.0', port=6006)
>     except Exception as e:
>         print(f"API启动失败！\n报错：\n{e}")
> ```
> 
> # 修改docker配置
> docker-composer如下修改
> 
> ```json
> "reRankModels": [
>         {
>             "model": "bce-reranker-base_v1",
>             "name": "检索重排-base",
>             "charsPointsPrice": 0,
>             "requestUrl": "http://你的服务器ip:6006/v1/rerank",
>             "requestAuth": "sk-xx"
>         }
>     ],
> ```
> 
> https://blog.skyw.cc/archives/312.html


没找到rerank模型
![image](https://github.com/user-attachments/assets/eebb594a-d3e6-4547-a4ed-4914a5487ea1)

**Comment by xy3xy3** [comment]
> > **例行检查**
> > 
> > * [x ] 我已确认目前没有类似 features
> > * [ x] 我已确认我已升级到最新版本
> > * [x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
> > * [x ] 我理解并愿意跟进此 features，协助测试和提供反馈
> > * [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**
> > 
> > **功能描述**
> > 一个价格还可以的在线API
> > **应用场景**
> > 混合搜索重排
> > **相关示例**
> > 代码已经实现
> > # 开通服务
> > [百度智能云千帆大模型平台 （baidu.com）](https://console.bce.baidu.com/qianfan/chargemanage/list)
> > 在平台搜索bce-reranker开通，价格 **¥0.002元/千代币**
> > ![image.png](https://camo.githubusercontent.com/a25a54cda58ed50002c242495e7470a2a4ebd7f524155322c168636ffed9b655/68747470733a2f2f626c6f672e736b79772e63632f7573722f75706c6f6164732f323032342f30372f313238363034323633312e706e67)
> > # 获取AK，SK
> > [百度智能云-管理中心 （baidu.com）](https://console.bce.baidu.com/iam/#/iam/accesslist) 创建 Access Key ，复制它和Secret Key
> > # 本地挂脚本
> > 脚本如下，注意替换自己的AK，SK
> > ```python
> > #!/usr/bin/env python
> > # -*- coding: utf-8 -*-
> > import os
> > import uvicorn
> > from fastapi import FastAPI, Security, HTTPException
> > from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
> > from pydantic import BaseModel
> > from typing import Optional, List
> > import qianfan
> > from qianfan.resources import Reranker
> > 
> > app = FastAPI()
> > security = HTTPBearer()
> > env_bearer_token = 'sk-xxx'
> > 
> > class QADocs(BaseModel):
> >     query: Optional[str]
> >     documents: Optional[List[str]]
> > 
> > class Singleton(type):
> >     def __call__(cls, *args, **kwargs):
> >         if not hasattr(cls, '_instance'):
> >             cls._instance = super().__call__(*args, **kwargs)
> >         return cls._instance
> > 
> > class ReRanker(metaclass=Singleton):
> >     def __init__(self):
> >         os.environ["QIANFAN_ACCESS_KEY"] = "你的AK"
> >         os.environ["QIANFAN_SECRET_KEY"] = "你的SK"
> >         self.reranker = Reranker(model="bce-reranker-base_v1")
> > 
> >     def compute_score(self, query: str, documents: List[str]):
> >         if len(documents) > 0:
> >             result = self.reranker.do(query, documents)
> >             return result.body['results']
> >         else:
> >             return None
> > 
> > class Chat(object):
> >     def __init__(self):
> >         self.reranker = ReRanker()
> > 
> >     def fit_query_answer_rerank(self, query_docs: QADocs) -> List:
> >         if query_docs is None or len(query_docs.documents) == 0:
> >             return []
> > 
> >         scores = self.reranker.compute_score(query_docs.query, query_docs.documents)
> > 
> >         new_docs = []
> >         for index, score in enumerate(scores):
> >             new_docs.append({"index": score['index'], "text": query_docs.documents[score['index']], "score": score['relevance_score']})
> >         results = [{"index": documents["index"], "relevance_score": documents["score"]} for documents in list(sorted(new_docs, key=lambda x: x["score"], reverse=True))]
> >         return results
> > 
> > @app.post('/v1/rerank')
> > async def handle_post_request(docs: QADocs, credentials: HTTPAuthorizationCredentials = Security(security)):
> >     token = credentials.credentials
> >     if env_bearer_token is not None and token != env_bearer_token:
> >         raise HTTPException(status_code=401, detail="Invalid token")
> >     chat = Chat()
> >     try:
> >         results = chat.fit_query_answer_rerank(docs)
> >         return {"results": results}
> >     except Exception as e:
> >         print(f"报错：\n{e}")
> >         return {"error": "重排出错"}
> > 
> > if __name__ == "__main__":
> >     token = os.getenv("ACCESS_TOKEN")
> >     if token is not None:
> >         env_bearer_token = token
> >     try:
> >         uvicorn.run(app, host='0.0.0.0', port=6006)
> >     except Exception as e:
> >         print(f"API启动失败！\n报错：\n{e}")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # 修改docker配置
> > docker-composer如下修改
> > ```json
> > "reRankModels": [
> >         {
> >             "model": "bce-reranker-base_v1",
> >             "name": "检索重排-base",
> >             "charsPointsPrice": 0,
> >             "requestUrl": "http://你的服务器ip:6006/v1/rerank",
> >             "requestAuth": "sk-xx"
> >         }
> >     ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://blog.skyw.cc/archives/312.html
> 
> 没找到rerank模型 ![image](https://private-user-images.githubusercontent.com/174102361/350769626-eebb594a-d3e6-4547-a4ed-4914a5487ea1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Njc4MTMsIm5iZiI6MTcyMTU2NzUxMywicGF0aCI6Ii8xNzQxMDIzNjEvMzUwNzY5NjI2LWVlYmI1OTRhLWQzZTYtNDU0Ny1hNGVkLTQ5MTRhNTQ4N2VhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQxMzExNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGVjZjJhNTVlNTc3NDVmMDhkMTU3Mjg4OGQ2MmExMzVkMGEwMjVlZDgwMTZjZDM4ODI2ZmMzYWYyNmZlZGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nnOpXuMaqgb7ItPI3-Kl8krB9dFANFg8TCpL_vE-1hc)

登录后 在 https://console.bce.baidu.com/qianfan/chargemanage/list ctrl+f搜索

**Comment by sdytzjp** [comment]
没有找到你提的模型，只找到了bce-reranker-base，运行后报错如下


报错：
The provided model `bce-reranker-base` is not in the list of supported models. If this is a recently added model, try using the `endpoint` arguments and create an issue to tell us. Supported models: {'bce-reranker-base_v1'}







JP
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月21日(星期天) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] 适配fastgpt接入百度开放平台的重排模型   (Issue #1977)





   
例行检查
  
[x ] 我已确认目前没有类似 features
 
[ x] 我已确认我已升级到最新版本
 
[x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
 
[x ] 我理解并愿意跟进此 features，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 features 可能会被无视或直接关闭
  
功能描述
 一个价格还可以的在线API
 应用场景
 混合搜索重排
 相关示例
 代码已经实现
 
开通服务
 
百度智能云千帆大模型平台 （baidu.com）
 在平台搜索bce-reranker开通，价格 ¥0.002元/千代币
 
 
获取AK，SK
 
百度智能云-管理中心 （baidu.com） 创建 Access Key ，复制它和Secret Key
 
本地挂脚本
 
脚本如下，注意替换自己的AK，SK
 #!/usr/bin/env python # -*- coding: utf-8 -*- import os import uvicorn from fastapi import FastAPI, Security, HTTPException from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials from pydantic import BaseModel from typing import Optional, List import qianfan from qianfan.resources import Reranker app = FastAPI() security = HTTPBearer() env_bearer_token = 'sk-xxx' class QADocs(BaseModel):     query: Optional[str]     documents: Optional[List[str]] class Singleton(type):     def __call__(cls, *args, **kwargs):         if not hasattr(cls, '_instance'):             cls._instance = super().__call__(*args, **kwargs)         return cls._instance class ReRanker(metaclass=Singleton):     def __init__(self):         os.environ["QIANFAN_ACCESS_KEY"] = "你的AK"         os.environ["QIANFAN_SECRET_KEY"] = "你的SK"         self.reranker = Reranker(model="bce-reranker-base_v1")     def compute_score(self, query: str, documents: List[str]):         if len(documents) &gt; 0:             result = self.reranker.do(query, documents)             return result.body['results']         else:             return None class Chat(object):     def __init__(self):         self.reranker = ReRanker()     def fit_query_answer_rerank(self, query_docs: QADocs) -&gt; List:         if query_docs is None or len(query_docs.documents) == 0:             return []         scores = self.reranker.compute_score(query_docs.query, query_docs.documents)         new_docs = []         for index, score in enumerate(scores):             new_docs.append({"index": score['index'], "text": query_docs.documents[score['index']], "score": score['relevance_score']})         results = [{"index": documents["index"], "relevance_score": documents["score"]} for documents in list(sorted(new_docs, key=lambda x: x["score"], reverse=True))]         return results @app.post('/v1/rerank') async def handle_post_request(docs: QADocs, credentials: HTTPAuthorizationCredentials = Security(security)):     token = credentials.credentials     if env_bearer_token is not None and token != env_bearer_token:         raise HTTPException(status_code=401, detail="Invalid token")     chat = Chat()     try:         results = chat.fit_query_answer_rerank(docs)         return {"results": results}     except Exception as e:         print(f"报错：\n{e}")         return {"error": "重排出错"} if __name__ == "__main__":     token = os.getenv("ACCESS_TOKEN")     if token is not None:         env_bearer_token = token     try:         uvicorn.run(app, host='0.0.0.0', port=6006)     except Exception as e:         print(f"API启动失败！\n报错：\n{e}")
 
修改docker配置
 
docker-composer如下修改
 "reRankModels": [         {             "model": "bce-reranker-base_v1",             "name": "检索重排-base",             "charsPointsPrice": 0,             "requestUrl": "http://你的服务器ip:6006/v1/rerank",             "requestAuth": "sk-xx"         }     ],
 
https://blog.skyw.cc/archives/312.html
  
没找到rerank模型 
  
登录后 在 https://console.bce.baidu.com/qianfan/chargemanage/list ctrl+f搜索

**Comment by sdytzjp** [comment]
是百度返回来的信息，看样模型就是_v1这个名字，改成v1好了，多谢



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月21日(星期天) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] 适配fastgpt接入百度开放平台的重排模型   (Issue #1977)





   
例行检查
  
[x ] 我已确认目前没有类似 features
 
[ x] 我已确认我已升级到最新版本
 
[x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
 
[x ] 我理解并愿意跟进此 features，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 features 可能会被无视或直接关闭
  
功能描述
 一个价格还可以的在线API
 应用场景
 混合搜索重排
 相关示例
 代码已经实现
 
开通服务
 
百度智能云千帆大模型平台 （baidu.com）
 在平台搜索bce-reranker开通，价格 ¥0.002元/千代币
 
 
获取AK，SK
 
百度智能云-管理中心 （baidu.com） 创建 Access Key ，复制它和Secret Key
 
本地挂脚本
 
脚本如下，注意替换自己的AK，SK
 #!/usr/bin/env python # -*- coding: utf-8 -*- import os import uvicorn from fastapi import FastAPI, Security, HTTPException from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials from pydantic import BaseModel from typing import Optional, List import qianfan from qianfan.resources import Reranker app = FastAPI() security = HTTPBearer() env_bearer_token = 'sk-xxx' class QADocs(BaseModel):     query: Optional[str]     documents: Optional[List[str]] class Singleton(type):     def __call__(cls, *args, **kwargs):         if not hasattr(cls, '_instance'):             cls._instance = super().__call__(*args, **kwargs)         return cls._instance class ReRanker(metaclass=Singleton):     def __init__(self):         os.environ["QIANFAN_ACCESS_KEY"] = "你的AK"         os.environ["QIANFAN_SECRET_KEY"] = "你的SK"         self.reranker = Reranker(model="bce-reranker-base_v1")     def compute_score(self, query: str, documents: List[str]):         if len(documents) &gt; 0:             result = self.reranker.do(query, documents)             return result.body['results']         else:             return None class Chat(object):     def __init__(self):         self.reranker = ReRanker()     def fit_query_answer_rerank(self, query_docs: QADocs) -&gt; List:         if query_docs is None or len(query_docs.documents) == 0:             return []         scores = self.reranker.compute_score(query_docs.query, query_docs.documents)         new_docs = []         for index, score in enumerate(scores):             new_docs.append({"index": score['index'], "text": query_docs.documents[score['index']], "score": score['relevance_score']})         results = [{"index": documents["index"], "relevance_score": documents["score"]} for documents in list(sorted(new_docs, key=lambda x: x["score"], reverse=True))]         return results @app.post('/v1/rerank') async def handle_post_request(docs: QADocs, credentials: HTTPAuthorizationCredentials = Security(security)):     token = credentials.credentials     if env_bearer_token is not None and token != env_bearer_token:         raise HTTPException(status_code=401, detail="Invalid token")     chat = Chat()     try:         results = chat.fit_query_answer_rerank(docs)         return {"results": results}     except Exception as e:         print(f"报错：\n{e}")         return {"error": "重排出错"} if __name__ == "__main__":     token = os.getenv("ACCESS_TOKEN")     if token is not None:         env_bearer_token = token     try:         uvicorn.run(app, host='0.0.0.0', port=6006)     except Exception as e:         print(f"API启动失败！\n报错：\n{e}")
 
修改docker配置
 
docker-composer如下修改
 "reRankModels": [         {             "model": "bce-reranker-base_v1",             "name": "检索重排-base",             "charsPointsPrice": 0,             "requestUrl": "http://你的服务器ip:6006/v1/rerank",             "requestAuth": "sk-xx"         }     ],
 
https://blog.skyw.cc/archives/312.html
  
没找到rerank模型 
  
登录后 在 https://console.bce.baidu.com/qianfan/chargemanage/list ctrl+f搜索

**Comment by sdytzjp** [comment]
百度rerank有文档数量限制，知识库分片后很容易超过这个限制，有没有办法把请求按照64个文档拆分成多个请求发送
@xy3xy3

**Comment by humeng126** [comment]
修改发送documents数组的内容，让他只取前64个发送给百度reranker
