### ISSUE TITLE
最大文档字符不超过64？

### ISSUE THREAD

**Issue by martin0359** [labring/FastGPT#1980]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
date	stream	content
2024/07/07 11:47:41	stdout	INFO:     172.17.0.1:38408 - "POST /v1/rerank HTTP/1.1" 200 OK
2024/07/07 11:47:41	stderr	[ERROR][2024-07-07 03:47:41.928] openapi_requestor.py:258 [t:140683129891712]: api request req_id: as-iy3zuhyrdn failed with error code: 336221, err msg: max number of documents is 64, please check https://cloud.baidu.com/doc/WENXINWORKSHOP/s/tlmyncueh
2024/07/07 11:47:41	stdout	api return error, req_id: as-iy3zuhyrdn code: 336221, msg: max number of documents is 64
2024/07/07 11:47:41	stdout	报错：
2024/07/07 11:46:35	stdout	INFO:     172.17.0.1:38356 - "POST /v1/rerank HTTP/1.1" 200 OK
2024/07/07 11:46:35	stdout	api return error, req_id: as-48ug1xzh5h code: 336221, msg: max number of documents is 64
2024/07/07 11:46:35	stdout	报错：
2024/07/07 11:46:35	stderr	[ERROR][2024-07-07 03:46:35.462] openapi_requestor.py:258 [t:140683129891712]: api request req_id: as-48ug1xzh5h failed with error code: 336221, err msg: max number of documents is 64, please check https://cloud.baidu.com/doc/WENXINWORKSHOP/s/tlmyncueh
2024/07/07 11:46:29	stdout	INFO:     172.17.0.1:38342 - "GET / HTTP/1.1" 404 Not Found
2024/07/07 11:46:28	stderr	INFO:     Uvicorn running on http://0.0.0.0:6008/ (Press CTRL+C to quit)
2024/07/07 11:46:28	stderr	INFO:     Application startup complete.
2024/07/07 11:46:28	stderr	INFO:     Waiting for application startup.
2024/07/07 11:46:28	stderr	INFO:     Started server process [1]

**Comment by goodstudy12** [comment]
百度那边只接收64个文档，fastgpt这边默认是发送100个文档的。要不就自己写个脚本中转一下，如果超过64个文档就拆掉，只给百度64个

**Comment by c121914yu** [comment]
考虑自定义脚本里拆分成多次请求

**Comment by sdytzjp** [comment]
rerank碰到同样问题。如何拆成多个请求
