### ISSUE TITLE
docker部署不能灵活添加更多功能

### ISSUE THREAD

**Issue by xdyuvx** [labring/FastGPT#1982]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 features
- [ x] 我已确认我已升级到最新版本
- [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
docker部署项目后，不能修改源码，非常僵硬，扩展能力有限。
想使用http调用拓展功能，发现http调用非常僵硬，不能实现对返回值的灵活处理，也不能定义不同的变量灵活访问http
docker部署的项目所需要的环境安装包有哪些呢，如果可以全部写出的话，直接源码部署fastgpt会更加灵活
**应用场景**
链接知识图谱应用时
**相关示例**

**Comment by c121914yu** [comment]
感觉你不清楚什么叫部署，什么叫开发～建议先了解下概念
