### ISSUE TITLE
自定义TTS模型语音播放时无法试听，对话中需要点击2次才能语音读出

### ISSUE THREAD

**Issue by sipeter** [labring/FastGPT#1984]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

通过api方式接入自定义tts模型时：
1. 试听无法正常使用；
2. 对话中语音播放需要点击两次；

**复现步骤**

我是用gpt sovits 加载的tts模型，通过api方式接入到fastgpt中，当选中模型比如“晓墨”时，第一次点击试听，会生成语音，但并不会播放出声音，之后再点击这个模型，既不会生成语音，也不会播放声音；
选中这个模型为语音播放声音后，在对话中，需要点击2次才能听到声音，第一次生成语音，再次点击才能播放。

对比测试：
1. openai tts-1 的几个声音模型，点击试听，会生成语音，并自动播放出声音；在对话中，点击语音会生成并同时播放出语音；
2. 测试另一个tts项目chatTTS，也是通过api方式接入到fastgpt中，与openai tts-1一样，会按照预期正常播放语音。

**预期结果**

希望能够像openai tts-1和 chatTTS一样，按照预期正常播放语音；
fastgpt中语音播放能够实现生成文字同时自动播放语音，不需要点击播放，或者有没有自动播放的的可选设置？

**相关截图**
![image](https://github.com/labring/FastGPT/assets/8326141/ec5c9f04-2ee8-44ad-84f4-f9bb050b3cad)

**Comment by Goic** [comment]
我也在想方法替换funasr语音模型，docker部署的useSpeech.ts也不知道在哪里，没有相关教程

**Comment by sdytzjp** [comment]
跟进

**Comment by zkstudio** [comment]
同样的问题 
请 @c121914yu 大佬帮忙看看

**Comment by 37llll** [comment]
请问大佬这个问题是如何解决的

**Comment by dooonabe** [comment]
确实，现在还是这样的报错

**Comment by 37llll** [comment]
> 请问大佬这个问题是如何解决的

gptsovits项目里的api2.py输出音频为.wav格式。转码为MP3输出就可以了。不确定是不是fastgpt这边只能接受mp3格式，没看源码。

**Comment by dooonabe** [comment]
> gptsovits项目里的api2.py输出音频为.wav格式。转码为MP3输出就可以了。不确定是不是fastgpt这边只能接受mp3格式，没看源码。

好奇怪，我这改成了mp3格式返回，还是一样的问题
![Image](https://github.com/user-attachments/assets/b21be7a4-903d-4aea-b539-c94af27c4c51)

**Comment by dooonabe** [comment]
> > gptsovits项目里的api2.py输出音频为.wav格式。转码为MP3输出就可以了。不确定是不是fastgpt这边只能接受mp3格式，没看源码。
> 
> 好奇怪，我这改成了mp3格式返回，还是一样的问题 ![Image](https://github.com/user-attachments/assets/b21be7a4-903d-4aea-b539-c94af27c4c51)

感谢大佬，确实是返回音频文件格式的问题，我测试用的文件本身不是mp3格式，只是后缀为mp3😂
