### ISSUE TITLE
问题探讨：分享链接，对话历史记录本地保存，不从数据库加载，是否可行？

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#1985]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
本地对话记录上限30，修改对话记录数，会增大数据库服务器开销；可否对话历史记录本地缓存，不从数据库加载；但这个记录数如何自增呢？例如，下次进入对话，记录数应该是31；这个得本地程序开发吗？还是本项目可以解决？
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
不利于数据运营

**Comment by sdytzjp** [comment]
聊天记录保存在那   可否对接外部数据库

**Comment by c121914yu** [comment]
> 聊天记录保存在那   可否对接外部数据库

不行
