### ISSUE TITLE
创建一个文件集合的提示接口命令提示无效数据集

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1987]
本地4.8.4

{"code":501000,"statusText":"unExistDataset","message":"core.dataset.error.unExistDataset","data":null}

更换了数据集一样的错误

![image](https://github.com/labring/FastGPT/assets/174102361/870cb1bf-3f0b-44c1-965b-7df512025e76)
![image](https://github.com/labring/FastGPT/assets/174102361/a66bc36a-27f1-4a1e-bfa8-ad368b55244c)

**Comment by c121914yu** [comment]
是要知识库 id，不是要集合 id

**Comment by daijunlin** [comment]
> 是要知识库 id，不是要集合 id

我也遇到这个问题,传的就是知识库ID,但是一样提示无效

**Comment by daijunlin** [comment]
问一下,后续有成功不

**Comment by sdytzjp** [comment]
成功了&nbsp; 不知道咋回事&nbsp; 后来就ok了



---原始邮件---
发件人: "Tad ***@***.***&gt;
发送时间: 2024年7月26日(周五) 下午2:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 创建一个文件集合的提示接口命令提示无效数据集 (Issue #1987)




 
问一下,后续有成功不

**Comment by daijunlin** [comment]
> 成功了&nbsp; 不知道咋回事&nbsp; 后来就ok了
> […](#)
> ---原始邮件--- 发件人: "Tad ***@***.***&gt; 发送时间: 2024年7月26日(周五) 下午2:42 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [labring/FastGPT] 创建一个文件集合的提示接口命令提示无效数据集 (Issue #1987) 问一下,后续有成功不 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

辛苦能把去掉apikey和datasetId的请求代码截个图看看不,我对比和我的请求有没有用差异

**Comment by 2662007798** [comment]
注意两点：
1、请求的时候要知识库的id   你需要拿到
2、file上传文件
3、data里面需要是json序列化后的内容，不是字符串的json。

根据这三点检查更正即可对接。
