### ISSUE TITLE
外部系统导入知识库文件

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1988]
本地4.8.4

使用开源版，调用知识库接口，将附件导入fast知识库，提示找不到文件

[root@ceshi fastgpt]# curl --location --request POST 'http://172.22.1.39:18080/api/core/dataset/collection/create/localFile' \
> --header 'Authorization: Bearer fastgpt-v9hRPgVKnyi8y1fAMLd9htnPtmmWl3YQOCMoO1NPKSRKdQ8JnfSq6V7DYi' \
> --form 'file=@"D:\\1\\test1.docx"' \
> --form 'data="{\"datasetId\":\"668b900f25346058ae7227db\",\"parentId\":null,\"trainingType\":\"chunk\",\"chunkSize\":512,\"chunkSplitter\":\"\",\"qaPrompt\":\"\",\"metadata\":{}}"'
**curl: (26) couldn't open file "D:\1\test1.docx"**
[root@ceshi fastgpt]#

**Comment by xy3xy3** [comment]
你在linux上用windows路径？

**Comment by sdytzjp** [comment]
发错了 请看issue2003
