### ISSUE TITLE
知识库问答如何精确问答？当知识库未检索到内容的情况下，不进行AI自行回答用户问题。

### ISSUE THREAD

**Issue by MartinH04** [labring/FastGPT#1991]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√] 我已确认目前没有类似 issue
- [√] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [√] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
关联知识库搜索，并配置了知识库检索模板为”严格问答模板“，但是当检索不到任何内容时，直接调用模型根据用户问题返回用户答案了

**复现步骤**

**预期结果**
询问知识库以外的问题，统统拒绝回复
**相关截图**
![image](https://github.com/labring/FastGPT/assets/54828556/21a9b484-0ef6-451f-a1c2-44b7eae86b85)
![image](https://github.com/labring/FastGPT/assets/54828556/fbe84c5e-cb16-4ba8-88a7-394813a80910)
![image](https://github.com/labring/FastGPT/assets/54828556/968383fa-ea52-4e0c-b7cd-85880ba3c82a)

**Comment by kylewka** [comment]
可以在AI回复与知识库回答之间添加判断条件，引用知识库内容为空时，直接回复指定文本
![image](https://github.com/labring/FastGPT/assets/66908361/bb7cddfe-7e33-4fc8-9793-fc8dc92f7ffe)

**Comment by leadscloud** [comment]
我这遇到相关问题，判断条件也不行，比如我问公司老板是谁，公司介绍知识库是有的，但它不会回答老板是谁，我用deepseek.com问，就会正常回答老板是谁。 如果知识库中没有找到信息，它就回答不知道，这个太不智能了，弄了知识库反而变傻了。

上面这个判断无法处理，因为它也是有相关结果的，只是索引只有公司名字。
