### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by yl3118436** [labring/FastGPT#1992]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x ] 我已确认目前没有类似 issue
- [x  ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x  ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ x ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

代码组件有问题，只要我退出编辑再进来，就会自动给我加上result,data2两个属性，引用的地方也改成result了

![代码组件1](https://github.com/labring/FastGPT/assets/137365713/a96c0bd3-208d-40f3-a892-f95f386b02e0)
![代码组件2](https://github.com/labring/FastGPT/assets/137365713/c3674e4d-abf9-4e27-aca8-bb0e2e8e4eb7)

**Comment by c121914yu** [comment]
嗯，上周有提了，前端显示问题，不影响逻辑，过几天修复。
