### ISSUE TITLE
fastgpt突然就不好用了，oneapi提示访问mysql拒绝

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1994]
![image](https://github.com/labring/FastGPT/assets/174102361/9b7c0c7c-c44f-4815-9ecb-437bad319634)

oneapi   | [error] failed to initialize database, got error dial tcp 192.168.176.5:3306: connect: connection refused

**Comment by c121914yu** [comment]
自己检查数据库问题

**Comment by silenceyese** [comment]
碰到了同样的问题，最后删了oneapi的容器重新创建就好了，感觉是oneapi的bug。

**Comment by sdytzjp** [comment]
不能升级到8



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 上午8:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] fastgpt突然就不好用了，oneapi提示访问mysql拒绝 (Issue #1994)




 
碰到了同样的问题，最后删了oneapi的容器重新创建就好了，感觉是oneapi的bug。
