### ISSUE TITLE
如何让AI做到让用户确认一下信息，根据用户是否确认再判断后续如何操作

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1997]
本地4.8.4

如何让AI做到让用户确认一下信息，根据用户是否确认再判断后续如何操作，比如
出差申请的内容，gpt获取后，让用户确认，如果确认则继续执行后面的步骤，如果用户确认错误，则让用户重新输入完善信息
![image](https://github.com/labring/FastGPT/assets/174102361/0525dd95-6c61-44c5-8b66-0e006f151905)

**Comment by XiangyuTang** [comment]
+1，希望在工作流的过程中加入用户干预的模块，再根据用户的输入去决定工作流下一步的走向

**Comment by dockersky** [comment]
+1

**Comment by soysc** [comment]
+1

**Comment by cloudtuotuo** [comment]
![image](https://github.com/labring/FastGPT/assets/37918843/f3ef79a6-9e64-4907-a249-3d21f343711b)
这么做就可以

**Comment by sdytzjp** [comment]
多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月11日(周四) 上午10:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 如何让AI做到让用户确认一下信息，根据用户是否确认再判断后续如何操作 (Issue #1997)




 
image.png (view on web)
 这么做就可以

**Comment by goactiongo** [comment]
ok

**Comment by cloudtuotuo** [comment]
判断器应该接到【流程开始】，当用户输入信息后先判断
如果接到AI对话后面，肯定每次都要过一遍AI对话

我也是经历过这个过程

**Comment by sdytzjp** [comment]
> 判断器应该接到【流程开始】，当用户输入信息后先判断 如果接到AI对话后面，肯定每次都要过一遍AI对话
> 
> 我也是经历过这个过程

非常感谢
