### ISSUE TITLE
ollama本地大模型突然【全部】报错---对话接口报错或返回为控--max response设置2000

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#1998]
本地ollama部署的大模型都报错，不知道改了config.json里面那个参数导致的，之前好用，改多了就该乱了。
在知识库导入和检索时，用这几个本地模型不报错，但是在AI会话界面就提示以下错误。

通过官网curl测试，更改了key、模型名称如下
curl --location --request POST 'http://172.22.1.39:18080/v1/chat/completions' \
--header 'Authorization: Bearer fastgpt-u5ZgwSMSNndRXgsbGrZQ9tjq4BH76FFBvczMnMsoyL4FvKN9kCOAi42EBp' \
--header 'Content-Type: application/json' \
--data '{
  "model": "ERNIE-Speed-128K",
  "stream": true,
  "temperature": 1,
  "max_tokens": 3000,
  "messages": [
    {
      "role": "user",
      "content": "你是谁"
    }
  ]
}'

但是无论使用本地模型（目前不好用）还是使用外面的模型（目前使用正常），curl出来的信息都一样，如下。

![image](https://github.com/labring/FastGPT/assets/174102361/49020126-d5ba-42fa-a3bb-4ae2dd0e22fa)

下面是config.json里面与这几个大模型有关的配置，请高手帮忙检查下

![image](https://github.com/labring/FastGPT/assets/174102361/e0f2db43-9372-475d-9bcb-42296621a335)

// 已使用 json5 进行解析，会自动去掉注释，无需手动去除
{
  "feConfigs": {
    "lafEnv": "https://laf.dev" // laf环境。 https://laf.run （杭州阿里云） ,或者私有化的laf环境。如果使用 Laf openapi 功能，需要最新版的 laf 。
  },
  "systemEnv": {
    "vectorMaxProcess": 15,
    "qaMaxProcess": 15,
    "pgHNSWEfSearch": 100 // 向量搜索参数。越大，搜索越精确，但是速度越慢。设置为100，有99%+精度。
  },
  "llmModels": [
     {
      "model": "qwen2:0.5b",
      "name": "local-qwen2:0.5b",
      "avatar": "/imgs/model/openai.svg",
      "maxContext": 128000,
      "maxResponse": 2000,
      "quoteMaxToken": 100000,
      "maxTemperature": 1.2,
      "charsPointsPrice": 0,
      "censor": false,
      "vision": false,
      "datasetProcess": true,
      "usedInClassify": false,
      "usedInExtractFields": false,
      "usedInToolCall": false,
      "usedInQueryExtension": false,
      "toolChoice": false,
      "functionCall": false,
      "customCQPrompt": "test31",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig": {}
    },
    {
      "model": "llama3:latest",
      "name": "local-llama3:latest",
      "avatar": "/imgs/model/openai.svg",
      "maxContext": 128000,
      "maxResponse": 2000,
      "quoteMaxToken": 100000,
      "maxTemperature": 1.2,
      "charsPointsPrice": 0,
      "censor": false,
      "vision": false,
      "datasetProcess": true,
      "usedInClassify": false,
      "usedInExtractFields": false,
      "usedInToolCall": false,
      "usedInQueryExtension": false,
      "toolChoice": false,
      "functionCall": false,
      "customCQPrompt": "test31",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig": {}
    },
    {
      "model": "qwen2:latest",
      "name": "local-qwen2:latest",
      "avatar": "/imgs/model/openai.svg",
      "maxContext": 128000,
      "maxResponse": 2000,
      "quoteMaxToken": 100000,
      "maxTemperature": 1.2,
      "charsPointsPrice": 0,
      "censor": false,
      "vision": false,
      "datasetProcess": true,
      "usedInClassify": false,
      "usedInExtractFields": false,
      "usedInToolCall": false,
      "usedInQueryExtension": false,
      "toolChoice": false,
      "functionCall": false,
      "customCQPrompt": "test31",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig": {}
    },

**Comment by y61235** [comment]
同样报这个错误

**Comment by sdytzjp** [comment]
oneapi用0.6.7



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月11日(周四) 晚上8:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [labring/FastGPT] ollama本地大模型突然【全部】报错---对话接口报错或返回为控--max response设置2000 (Issue #1998)




 
同样报这个错误
