### ISSUE TITLE
插件放入文件夹后无法引用

### ISSUE THREAD

**Issue by Felixyang2088** [labring/FastGPT#2000]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [  X  ] 我已确认目前没有类似 issue
- [   X  ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [   X  ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [   X  ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [  X  ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [ X ] 私有部署版本, 具体版本号:  docker 镜像版本： image: ghcr.io/labring/fastgpt:v4.8.5

**问题描述, 日志截图**
<img width="450" alt="image" src="https://github.com/labring/FastGPT/assets/112562274/4dce3acb-ab51-438b-8314-af05e9a5694a">

**复现步骤**
1.插件放入文件夹
2.在工作流中选择插件--团队插件，可以正常看到文件夹。
3.点根目录文件夹。
4.二级目录仍然显示的是根目录文件夹，并未显示正常的插件列表。
**预期结果**
应该显示正常的插件列表
**相关截图**
引用：复现步骤 2 “2.在工作流中选择插件--团队插件，可以正常看到文件夹。”
<img width="554" alt="image" src="https://github.com/labring/FastGPT/assets/112562274/87c16603-0480-4669-86f3-5793e304d20d">

引用：复现步骤 4 “4.二级目录仍然显示的是根目录文件夹，并未显示正常的插件列表。”
<img width="472" alt="image" src="https://github.com/labring/FastGPT/assets/112562274/769d2a13-5c5d-4b28-b375-9df5852f652a">

**Comment by c121914yu** [comment]
见 https://github.com/labring/FastGPT/releases/tag/v4.8.6-alpha
