### ISSUE TITLE
新版本找不到AI高级编排和里面的提示模版

### ISSUE THREAD

**Issue by Cherokeeli** [labring/FastGPT#2002]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.5

**问题描述, 日志截图**
为什么新版本找不到AI高级编排中的提示模版

**复现步骤**
下载最新版本4.8.5，在界面中找不到提示模板
<img width="1716" alt="企业微信截图_ed4a1753-25dc-4ed4-8b21-292cf396821b" src="https://github.com/labring/FastGPT/assets/17857090/6faf6215-6f73-4065-8f44-85569c310fed">

**预期结果**

**相关截图**
![企业微信截图_641865f9-c3c6-468a-903d-982bb991e531](https://github.com/labring/FastGPT/assets/17857090/b8e46491-1675-400d-86b7-9c807e669a83)

**Comment by c121914yu** [comment]
看更新说明

**Comment by c121914yu** [comment]
高级编排就是工作流，简易模式可以转工作流，不能反向。

**Comment by Cherokeeli** [comment]
> 高级编排就是工作流，简易模式可以转工作流，不能反向。

请问提示模板是在哪里呢？

**Comment by c121914yu** [comment]
> > 高级编排就是工作流，简易模式可以转工作流，不能反向。
> 
> 请问提示模板是在哪里呢？

这是啥？
