### ISSUE TITLE
更改oneapi时区

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2004]
fastgtp已经设置了时区，但是其他组件，例如oneapi、pg、mysql、mongo等时区如何更改，更改后是否影响整个环境运行，特别涉及到数据库。

如果不更改，通过docker logs查看容器日志总是差8个小时

![image](https://github.com/labring/FastGPT/assets/174102361/22b40a06-68d1-490d-90a5-e47e86a5ca12)

**Comment by c121914yu** [comment]
日志永远是 utc0
