### ISSUE TITLE
关于word、pdf、pptx导入知识库的图片和表格信息

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2005]
为什么知识库导入带图片的word文件后，在fastgpt数据集中可以看到markdown格式的图片和表格信息
但是同样的word转成PDF导入后，数据集中就没有图片和表格信息
ppt中的图片导入后，也没有图片和表格信息

![image](https://github.com/labring/FastGPT/assets/174102361/7b020b24-8bef-44cb-bb18-d411a641007a)
![image](https://github.com/labring/FastGPT/assets/174102361/6f642de5-7e3b-451d-b76c-e645c282eb50)

**Comment by c121914yu** [comment]
因为 word 是有结构的

**Comment by sdytzjp** [comment]
> 因为 word 是有结构的

pdf和ppt没有结构吗？
另外，在issue上传图片后自动转成markdown，图片显示太大了，这个怎么更改显示大小

**Comment by c121914yu** [comment]
😅pdf 有没有结构。 这种问题咋问得出来的。
改代码可以。

**Comment by ChjxL** [comment]
请问一下，你的也是pdf读到向量知识库没有图片吗
