### ISSUE TITLE
手机端浏览器语音输入提示permission denied，怎么解决，PC端正常

### ISSUE THREAD

**Issue by kevinchi8781** [labring/FastGPT#2007]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=5619337657772254701 skey=@crypt_eb895bcb_c48c27cb98aba208a19951d15fa04004 mmweb_appid=wx_webfilehelper](https://github.com/labring/FastGPT/assets/34735977/59dbaa3e-79fd-410a-beac-9da6832f40e3)

**Comment by sdytzjp** [comment]
请教下pc端如何实现的

**Comment by sdytzjp** [comment]
请教下pc端如何实现的

**Comment by c121914yu** [comment]
允许浏览器使用麦克风
