### ISSUE TITLE
【知识库】文档上传进程与向量索引进程能否独立？？

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#2008]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.5

**问题描述, 日志截图**
当我同时上传几个word文档时，单个文件2m，由于服务器GPU性能，导致索引稍慢，队列中后续上传的文件就会显示超时120000，无法上传，需要手动操作。
有没有方法优化一下？
![image](https://github.com/labring/FastGPT/assets/66725845/c3fe3aee-e3fe-4f98-83b6-fdac513fd443)

![image](https://github.com/labring/FastGPT/assets/66725845/9c2b20d2-a1a9-478f-a4d0-fab84b9eba09)

**复现步骤**

**预期结果**

**相关截图**

**Comment by Essence9999** [comment]
目前能想到的就是，把超时时间延长

**Comment by c121914yu** [comment]
本来就是分开的，上传只是插入索引，只占用cpu和内存。

**Comment by ajiader** [comment]
为什么上传解析多了  回答问题都会卡住
