### ISSUE TITLE
添加embeddings后无法生成知识库

### ISSUE THREAD

**Issue by taurusduan** [labring/FastGPT#201]
我安装fastgpt给出的实例，替换了embeddings：
{
"FeConfig": {
"show_emptyChat": true,
"show_register": false,
"show_appStore": false,
"show_userDetail": false,
"show_git": true,
"systemTitle": "FastGPT",
"authorText": "Made by FastGPT Team.",
"gitLoginKey": ""
},
"SystemParams": {
"gitLoginSecret": "",
"vectorMaxProcess": 15,
"qaMaxProcess": 15,
"pgIvfflatProbe": 20
},
"plugins": {},
"ChatModels": [
{
"model": "gpt-3.5-turbo",
"name": "GPT35-4k",
"contextMaxToken": 4000,
"quoteMaxToken": 2000,
"maxTemperature": 1.2,
"price": 0,
"defaultSystem": ""
},
{
"model": "gpt-3.5-turbo-16k",
"name": "GPT35-16k",
"contextMaxToken": 16000,
"quoteMaxToken": 8000,
"maxTemperature": 1.2,
"price": 0,
"defaultSystem": ""
},
{
"model": "gpt-4",
"name": "GPT4-8k",
"contextMaxToken": 8000,
"quoteMaxToken": 4000,
"maxTemperature": 1.2,
"price": 0,
"defaultSystem": ""
}
],
"QAModels": [
{
"model": "gpt-3.5-turbo-16k",
"name": "GPT35-16k",
"maxToken": 16000,
"price": 0
}
],
"VectorModels": [
{
"model": "embeddings",
"name": "Embedding-2",
"price": 0
}
]
}

**Comment by c121914yu** [comment]
这是什么向量模型？

**Comment by taurusduan** [comment]
> 这是什么工作模型？

开源LLM
https://github.com/josStorer/RWKV-Runner
兼容gpt的模型，接入fastgpt后，可以正常对话。但是使用embeddings生成数据库的时候就卡住了。不知道是不是还要修改知识库这边的配置。谢谢啊。

**Comment by c121914yu** [comment]
要纬度统一

**Comment by taurusduan** [comment]
> 要纬度统一

大哥，请教一下在哪里修改纬度啊，谢谢啊

**Comment by c121914yu** [comment]
已支持自定义向量模型，参考最新发行版说明：https://github.com/labring/FastGPT/releases/tag/v4.2.1
