### ISSUE TITLE
oneapi一直报错

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2010]
![image](https://github.com/labring/FastGPT/assets/174102361/17163281-e557-40cc-ba16-454e2243ece7)

![image](https://github.com/labring/FastGPT/assets/174102361/d0be9160-3796-41ba-ab70-ade7fe1cb8fc)

![image](https://github.com/labring/FastGPT/assets/174102361/46cb8f4c-e2f6-4e72-a60d-63bad703a4b1)

**Comment by xy3xy3** [comment]
显然是连不上mysql，检查一下docker网络配置
