### ISSUE TITLE
Oneapi添加渠道本地大模型，显示Connection Error

### ISSUE THREAD

**Issue by hamiduan** [labring/FastGPT#2013]
系统：Windows11+WSL2+Ubuntu 22.04

大模型：版本Chatglm3-6b-base，WSL2上运行，api_server设置uvicorn.run(app, host='127.0.0.1', port=8000, workers=1), post可访问127.0.0.1:8000，且有响应。
![image](https://github.com/labring/FastGPT/assets/42194631/33d29e38-f48d-4882-81b9-035568b86976)

Fastgpt：Docker运行，端口：9091:3000, - OPENAI_BASE_URL=http://172.20.0.1:3000/v1，- Network:      http://172.21.0.7:3000

Oneapi：Docker运行，端口：3001:3000，- Network:  172.21.0.1， 渠道部署 Base url: 127.0.0.1:8000,报错：
![image](https://github.com/labring/FastGPT/assets/42194631/7f033143-76e4-48a5-9edc-f6f2590921f4)

测试多ip端口皆无效：
![image](https://github.com/labring/FastGPT/assets/42194631/59cafb49-3c44-42da-84ce-5a4393c6c4bd)

Windows和WSL防火墙已down（启动wsl前，.wslconfig 文件已删除）
猜想：docker compose用桥接模式连接FastGPT，要如何将本地模型加入网络中？
求助大佬，感谢！

**Comment by longzhang83** [comment]
使用本机IP， 不要用127.0.0.1
