### ISSUE TITLE
如何更改登陆页面的logo以及"无法登陆点击联系"的URL和文字说明

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2018]
本地4.8.5
如何更改登陆页面的logo以及"无法登陆点击联系"的URL和文字，fastgpt的docker下没有找到
![image](https://github.com/labring/FastGPT/assets/174102361/b3e34f5a-2f92-4cb7-af0b-7c5c329ca85e)
![image](https://github.com/labring/FastGPT/assets/174102361/98315cbd-2cdf-4495-a869-f8731d7fee38)

**Comment by sdytzjp** [comment]
@c121914yu

**Comment by c121914yu** [comment]
改代码
