### ISSUE TITLE
能否在应用页面中增加一个应用搜索功能，支持搜索应用名称？

### ISSUE THREAD

**Issue by caijx168** [labring/FastGPT#2023]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
能否在应用页面中增加一个应用搜索功能，支持搜索应用名称？不然应用创建太多了，不好找
![image](https://github.com/labring/FastGPT/assets/54843188/91d7cf10-b38e-4d4d-8dfb-ef178d3fee72)

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
Done
