### ISSUE TITLE
在快速迭代发展期就从功能性上区分社区版和商业版，其实不太利于项目的发展。

### ISSUE THREAD

**Issue by dimsky** [labring/FastGPT#2028]
个人认为，在快速迭代发展期就从功能性上区分社区版和商业版，其实不太利于项目的发展，很多优质的建议也不会及时更新到社区版，社区也没法参与到这些功能的开发和迭代中去。
商业版暂时只通过云服务的方式或许会是更好的选择。

可能与你们的商业模式有些许冲突，不过看到  dify  的快速发展，相较于  dify  优势越来越小，我觉得  fastgpt  可能需要做些改变。

**Comment by c121914yu** [comment]
不是一个路线，国内不适合做社区，没人买单。

**Comment by leavegee** [comment]
It is recommended to adopt a low-profit, high-volume sales strategy. Early bird users pay 99 RMB per year.
