### ISSUE TITLE
对话上传图片报错getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by HelloEveryonehh** [labring/FastGPT#2029]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.5

**问题描述, 日志截图**
向gpt-4o发送图片，对于我自己部署的fastgpt，是可以读取图片的，但是对于公有云版本，无法读取
![image](https://github.com/user-attachments/assets/487d5ccd-4348-4aef-a74b-416a0b012ab6)
公有云版本
![image](https://github.com/user-attachments/assets/89060dea-0a52-4e06-ac45-b45753cfa013)
公有云版本可以读取openai官方example里面的图片
![image](https://github.com/user-attachments/assets/059b6b5f-6ab2-489a-b0b2-956a40d0c6ba)

**Comment by c121914yu** [comment]
<img width="555" alt="image" src="https://github.com/user-attachments/assets/c38eb80d-0219-4b48-a242-d2458c442dbf">

这个域名 DNS 好像有问题

**Comment by c121914yu** [comment]
你的 DNS 服务器是什么？

**Comment by c121914yu** [comment]
确定是 dns 特例问题，暂时不处理。
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/2b8d8c1a-6d9a-4bc1-9fa9-cc3b1e2756f9">
