### ISSUE TITLE
【功能改善】关于"指定回复" 中 "换行" 功能的小建议

### ISSUE THREAD

**Issue by B3nDan** [labring/FastGPT#203]
已知，指定回复可以换行
1、在指定回复中可以使用\n来换行
<img width="694" alt="Shot 2023-08-21 at 10 22 21@2x" src="https://github.com/labring/FastGPT/assets/129975925/2cff55c9-abc8-4ea5-aaa5-7f48c5e4b39a">
2、也可以直接回车换行
<img width="657" alt="Shot 2023-08-21 at 10 23 48@2x" src="https://github.com/labring/FastGPT/assets/129975925/0eaa6f3b-78da-4833-a892-3522d3902b51">

但是，无法实现 换多行 （即两行文字中间有空行）
1、利用多个\n，无法实现
<img width="708" alt="Shot 2023-08-21 at 10 26 00@2x" src="https://github.com/labring/FastGPT/assets/129975925/db9d3784-7e94-4ba2-8e21-0ef99208074d">
2、直接多个回车，无法实现
<img width="658" alt="Shot 2023-08-21 at 10 26 30@2x" src="https://github.com/labring/FastGPT/assets/129975925/7f9a0a0f-39a0-4319-8567-b4d54dc7c1b7">
3、甚至尝试了使用空格占位，无法实现（可能您用代码剔除了空格吧）
<img width="690" alt="Shot 2023-08-21 at 10 27 09@2x" src="https://github.com/labring/FastGPT/assets/129975925/82fecf2d-b9e9-4ce9-a9ca-408e66010969">

我不知道您是不是故意这么做的
我目前考虑这个功能的原因是，我希望能在两段内容中增加空行，以增强分割感
比如，我可能会在ai回复前增加一个指定回复（提示下方信息由ai生成等等）
个人认为：
如果两段内容紧挨着，可能观感上不太好
中间如果空1行，可以产生更好的分割
例如，图中，在2，3行之间空一行
<img width="1038" alt="Shot 2023-08-21 at 10 37 51@2x" src="https://github.com/labring/FastGPT/assets/129975925/b339000f-26d5-4d1d-8586-8c2767c4b395">

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/365 已经增加

**Comment by B3nDan** [comment]
666
