### ISSUE TITLE
4.8.5 语音输入以及whisper

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2034]
本地4.8.5

本地已经部署了whisper容器，并且在ONEAPI中增加了渠道，渠道测试404是否正常？
本地通过curl测试oneapi对接whisper可以输出，但是渠道测试404错误
![image](https://github.com/user-attachments/assets/7980ce9c-65d6-4d73-a248-4e3c913c69a7)

另外，为什么提示浏览器不支持语音输入，换了好几个了
![image](https://github.com/user-attachments/assets/a09af16b-44d7-426c-954b-aad8540cecd5)

请问发布免登陆页面是否支持语音输入？
如果发布免登陆不支持语音的话，那这个语音是怎么使用的？不用免登陆怎么使用fastgpt？

**Comment by c121914yu** [comment]
换电脑吧~或者换chrome

**Comment by William-715** [comment]
浏览器的问题，用ngnix做个反代，自己配个ssl证书给ngnix就可以了
