### ISSUE TITLE
whisper本地安装启动后，如何设置CPU或GPU模式

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2039]
问题1：
whisper本地安装对接oneapi和fastgpt，运行正常。
根据docker安装的文档，在docke启动运行时可以指定是CPU还是GPU模式运行，请问非docker模式下，如何设置设置CPU或GPU模式。

问题2：
本地安装的whisper，怎么更改ACCESS_TOKEN

问题3：
docker环境下，whisper的ACCESS_TOKEN怎么更改，我在docker环境下使用以下命令更改成12341234不生效，仍然是默认的ACCESS_TOKEN
docker run -itd --name whisper-api -p 3003:3003 -e ACCESS_TOKEN=12341234 --gpus all --restart=always whisper

**Comment by c121914yu** [comment]
非docker模式，代码里写的~
怎么改token，，看你代码怎么配置的呀。
这种问题度娘好了，，你问别人也不懂~

**Comment by xiaoToby** [comment]
![image](https://github.com/user-attachments/assets/bbb867fa-8239-43a5-bf59-d9e1c417d8a3)
![image](https://github.com/user-attachments/assets/740d585c-894d-4f15-81d8-aa14276c2891)
新增一个verify_token function， 然后跑模型时配置好ACCESS_TOKEN这个环境变量
@SDAIer
