### ISSUE TITLE
发现了一段奇怪的代码

### ISSUE THREAD

**Issue by ws02589111** [labring/FastGPT#2043]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
   
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  4.8.6

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/a7118544-9610-46de-a9eb-2c2b6ce39704)

**复现步骤**
代码版本： 090c8808605e67f00aab2f842157f1531e1efd46  
在编译的时候，无意间发现出现了这一行信息，是否预示着，使用的代码库被人植入了恶意代码？
**预期结果**

**相关截图**

**Comment by ws02589111** [comment]
OK，我的误解。
对比了一下， 是core-js作者的赞助地址

**Comment by c121914yu** [comment]
> OK，我的误解。 对比了一下， 是core-js作者的赞助地址

学习了，非常细，我还没注意这个。
