### ISSUE TITLE
简单编排里，工具调用+4O上传图片后检测不到图片

### ISSUE THREAD

**Issue by Dr-xiaoming** [labring/FastGPT#2044]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/7df45310-527e-454f-b7bd-e1aa7ae0216c)

**复现步骤**
简单编排+4O模型，上传图片后问问题
**预期结果**
回复识别到的图片
**相关截图**

**Comment by c121914yu** [comment]
gpt4o 无法同时读图和工具调用

**Comment by Dr-xiaoming** [comment]
> gpt4o 无法同时读图和工具调用
可是我再第一轮对话识别不了图片，但是后面就可以了，发现后面拼接对话历史记录里面是有图片地址的

**Comment by c121914yu** [comment]
> > gpt4o 无法同时读图和工具调用
> > 可是我再第一轮对话识别不了图片，但是后面就可以了，发现后面拼接对话历史记录里面是有图片地址的

有图片地址不等于读图，读图不会体现在历史记录，历史记录只展示文本。

**Comment by Dr-xiaoming** [comment]
> > > gpt4o 无法同时读图和工具调用
> > > 可是我再第一轮对话识别不了图片，但是后面就可以了，发现后面拼接对话历史记录里面是有图片地址的
> 
> 有图片地址不等于读图，读图不会体现在历史记录，历史记录只展示文本。

![image](https://github.com/user-attachments/assets/29f4d596-e05b-4ca5-a4c2-12ba718b7e28)
但是这样对话明显还是读图和工具调用都行，只有第一轮不行

**Comment by c121914yu** [comment]
是的， 我发现了这个问题，后续修复下
