### ISSUE TITLE
【bug】4.8.6 应用的编辑信息不生效

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2052]
4.8.6 应用的编辑信息不生效，如下，该名称和备注信息都不生效

![image](https://github.com/user-attachments/assets/126cc6ee-250f-41c4-a642-3934c3392ee8)

**Comment by c121914yu** [comment]
4.8.6未出现

https://github.com/user-attachments/assets/abf9c1e3-e428-43f6-9f30-201622956252

**Comment by sdytzjp** [comment]
我仍然不可以，请问该怎么解决，改不了名字，导致复制出来一堆copy copy copy 
已经是4.8.6了

**Comment by c121914yu** [comment]
> 我搭建了两台服务器，都是从4.8.4升级到4.8.5、4.8.6,两台的问题一样 请问该怎么解决，改不了名字，导致复制出来一堆copy copy copy 已经是4.8.6了 .
> 
>  22.mp4

不确定，目前都没法复现出来～ 自行 debug 测试吧

**Comment by sdytzjp** [comment]
就是bug
升级到4.8.7解决了
