### ISSUE TITLE
文本内容提取插件无法选择qwen2-instruct-72b模型

### ISSUE THREAD

**Issue by leeyis** [labring/FastGPT#2054]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前存在类似 issue，但是都不能解决我的问题
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**配置文件**
![image](https://github.com/user-attachments/assets/7e0e1ba1-019c-488a-84eb-0b2e6d98dc53)

**复现步骤**
1. 在config.json文件中添加qwen2-instruct-72b的模型
2. 重新创建相关容器
3. 进入高级编排模式
4. 添加“文本内容提取”插件
5. 点击“AI模型”下拉框
**预期结果**
出现第一步配置的qwen2模型，但是可选项中并没有该选项
**相关截图**
![image](https://github.com/user-attachments/assets/a2de25b0-8623-4cea-bdc3-23ef26067378)
在其他插件中可以选到自定义的qwen2模型，说明模型是可用的
![image](https://github.com/user-attachments/assets/0c32fbd3-f50c-4848-a770-a59b25f341bc)

**Comment by lijiajun1997** [comment]
保存完重启了吗

**Comment by leeyis** [comment]
> 保存完重启了吗

我可以确定是重启了，使用的命令`docker compose down && docker compose up -d`

**Comment by leeyis** [comment]
新建一个应用，又可以用选到了，原因不明，可以关闭这个issue了
![image](https://github.com/user-attachments/assets/bb739475-1e7d-4d6d-83b4-ae3b11367735)
