### ISSUE TITLE
FastGPT 使用 Gapier 快速导入Agent工具

### ISSUE THREAD

**Issue by wll0307** [labring/FastGPT#2055]
我导入进行后简易对话的能调用插件但是高级编排不能调用
![6d8e5c6dca8455256092d9640ed94dd](https://github.com/user-attachments/assets/be811d48-5b4c-4b02-9e26-831b26fa3d46)

![473b27ac564a1e6914fbee9514ab8d8](https://github.com/user-attachments/assets/27efc812-105f-4c9a-98b6-9e44383bd867)

**Comment by c121914yu** [comment]
补全信息再提。
以及看 release 修复内容。
