### ISSUE TITLE
分享链接的引用链接，增加可点击，类似bing搜索的引用链接。

### ISSUE THREAD

**Issue by Code-Bai** [labring/FastGPT#2065]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
![image](https://github.com/user-attachments/assets/1bc3c335-1625-4340-8ccc-1697de6be889)

![image](https://github.com/user-attachments/assets/f6a750ac-97eb-4563-a6ce-897134237faf)

**应用场景**
知识库应用场景很难做到100%的正确，用户需要100%确认时，可通过链接跳转进行确认。

**相关示例**

**Comment by c121914yu** [comment]
重复 issue
