### ISSUE TITLE
关于线上功能和私有部署的功能

### ISSUE THREAD

**Issue by weikecloud** [labring/FastGPT#2066]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.6

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/d83730f1-b051-4302-a5f3-9aeac7563bec)
![image](https://github.com/user-attachments/assets/5e5b4908-a49c-48cc-8ce2-51882678a238)

**复现步骤**
点击部署，分享后，功能不一致
**预期结果**
想知道这个身份验证等功能是不是线上才有？
**相关截图**
![image](https://github.com/user-attachments/assets/d00d1f09-ad55-4e6f-95dc-d5c0012fabec)
isPlus是商业版？

**Comment by c121914yu** [comment]
是的
