### ISSUE TITLE
docker 编译出错

### ISSUE THREAD

**Issue by jhfuture** [labring/FastGPT#2068]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.0

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/672cb30d-6f4e-4a13-b475-dd9eb35bf578)
```shell
docker build -f ./projects/app/Dockerfile -t registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:v4.8.0 . --build-arg name=app

**复现步骤**
使用镜像编译或者非镜像。
```shell
docker build -f ./projects/app/Dockerfile -t registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:v4.8.0 . --build-arg name=app

**Comment by leeyis** [comment]
我刚好也遇到这个问题了
![image](https://github.com/user-attachments/assets/f4efe08e-43f9-4f01-b39c-85a8334feb44)

**Comment by jhfuture** [comment]
已解决。
方法如下：
1.检查是否有代码出现问题
2.请将linux系统开启全局梯子

**Comment by c121914yu** [comment]
基本是网络问题，无法安装依赖包
