### ISSUE TITLE
【多轮对话】提问时，上下文的问题补全效果能否拼接到新问题上，便于准确回答新问题

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#2069]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.6

**问题描述, 日志截图**
问：支持3A标准测试吗？
AI：a产品支持标准测试
问：b产品呢
AI：b产品相关介绍等等（没有回答是否支持支持3A标准测试）

知识库搜索阶段，问题优化结果：（很好，符合预期，能正确补全问题）
b产品是否支持支持3A标准测试？
b产品在3A标准测试上表现如何？

联系上下文内容，AI对话时，我的问题是："b产品呢"
从而导致回答不正确。

**预期结果**
联系上下文内容，AI对话时，我的问题能否变成知识库搜索阶段问题优化的结果，真实意图是想问：”b产品是否支持支持3A标准测试“

**Comment by lijiajun1997** [comment]
问题优化工具直接接入

**Comment by sdytzjp** [comment]
问题如何如何接入，如果他的知识库里就是包括了标准测试和产品介绍两部分，问题优化该怎么优化

**Comment by wbext** [comment]
我也是遇到一样的问题，我觉得知识库内部的问题优化结果并不能被ai对话模块接收

**Comment by c121914yu** [comment]
不是有个问题优化模块么😅

**Comment by sdytzjp** [comment]
这个模块怎么用&nbsp; 如果问题分类 后面带着好几个知识库和应用调用，问题优化放在哪，问题优化提示词怎么写



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月24日(周三) 上午9:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 【多轮对话】提问时，上下文的问题补全效果能否拼接到新问题上，便于准确回答新问题 (Issue #2069)




 
不是有个问题优化模块么😅

**Comment by c121914yu** [comment]
> 这个模块怎么用&nbsp; 如果问题分类 后面带着好几个知识库和应用调用，问题优化放在哪，问题优化提示词怎么写
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年7月24日(周三) 上午9:01
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [labring/FastGPT] 【多轮对话】提问时，上下文的问题补全效果能否拼接到新问题上，便于准确回答新问题 (Issue #2069)
> 
> 
> 
> 
>  
> 不是有个问题优化模块么😅
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

知识库里问题优化怎么写就怎么写。输出结果是一个字符串，替换掉知识库里的用户问题。
