### ISSUE TITLE
Docker 编译可能会遗漏 .env.local 文件，需要手动进行补全。

### ISSUE THREAD

**Issue by jhfuture** [labring/FastGPT#2071]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.1
- [ ] 公有云版本
- [* ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
启动容器后，截图如下：
mongodb无法正常连接
![image](https://github.com/user-attachments/assets/c7eed3f6-f386-4016-9de0-cd3cbd053fc3)

**复现步骤**
重新创建容器，并使用 -v 指定数据卷，查看容器的运行文件发现 projects/app 下缺少 .env.local 文件。补全后正常运行。
![image](https://github.com/user-attachments/assets/d5f20923-6c29-4553-8773-fff611f17098)
![image](https://github.com/user-attachments/assets/af35a752-41e7-428c-9451-e064d95ab3cf)

**相关**
Dockerfile编译文件
```shell
# copy packages and one project
COPY pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY ./packages ./packages
COPY ./projects/app/package.json ./projects/app/package.json

**Comment by c121914yu** [comment]
那是本地来发的文件～
