### ISSUE TITLE
如何调用阿里语音模型

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2073]
请问调用阿里语音模型和文本模型方式一样吗？
参照文本模型的方式改了config文件和oneapi配置不生效。

本地whisper效果不好
我想对接阿里语音模型，没有思路，请指点下。
congfig.json怎么改 oneapi怎么设置，需要写python调用吗

fastgpt找不到相关文档

**Comment by c121914yu** [comment]
需要写一个 py 文件对齐接口。由于 oneapi 坑，目前 model 必须叫 whisper-1，这个 pr 修复了 https://github.com/songquanpeng/one-api/pull/1690

**Comment by sdytzjp** [comment]
没看明白。你的意思是config还得用默认的whisper-1？对接其他语音识别模型,那oneapi如何设置？

**Comment by c121914yu** [comment]
> 没看明白。你的意思是config还得用默认的whisper-1？对接其他语音识别模型,那oneapi如何设置？

🥲你先了解下 oneapi 工作原理吧
