### ISSUE TITLE
有添加graphRag的计划吗？

### ISSUE THREAD

**Issue by wangyiyong** [labring/FastGPT#2078]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 features
- [ x] 我已确认我已升级到最新版本
- [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
有没有增加graphRag的计划。
**应用场景**
graphRag加持的知识库，效果提升很大啊。希望有添加graphRag相关功能的计划

**相关示例**

**Comment by longzhang83** [comment]
graphRag 有很大的潜力， 但是目前还是demo阶段， 做很好的落地难度很挺大， 可以是一个探索的方向

**Comment by c121914yu** [comment]
重复 issue，不单独开issue 了。
