### ISSUE TITLE
请求提示API-KEY 不合法，请问大佬是什么原因

### ISSUE THREAD

**Issue by Timoshao** [labring/FastGPT#208]
![3d928ca147d07058996c2e8fecc1f57](https://github.com/labring/FastGPT/assets/108260847/85f108f8-9549-4651-81b4-7fd7bf471428)
![image](https://github.com/labring/FastGPT/assets/108260847/80facfd9-d63e-4353-94cd-c027bbedd294)

自建知识库，聊天的时候偶尔出现api-key不合法，对接的one-api
（贴的两个图片对应内容不一致，但是后台报错都是那样的提示）

**Comment by c121914yu** [comment]
oneapi或者key原因。
oneapi mysql版本目前有个bug，没有及时释放连接，并发高的时候会导致连接数超多，超出限制后也可能出现这个问题。

**Comment by c121914yu** [comment]
或者你是用5元号，一分钟只能3次。可能看oneapi日志

**Comment by Timoshao** [comment]
> 或者你是用5元号，一分钟只能3次。可能看oneapi日志
估计是这个问题 我的oneapi中有部分5元号，
oneapi我没有用mysql
