### ISSUE TITLE
即便定时执行关闭，应用还总是自动执行

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#2083]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
用高级编排做的应用，关闭了定时执行，还是会自动执行。每天HTTP调用都会收到大量的call, 但是明明没有人用。有些出现在半夜3,4点。检查了设置，不管是高级编排还是简单编排，定时执行都是“未开启”状态。
不知道哪里还有设置。

**复现步骤**

**预期结果**
没有人用就应该不会触发。

**相关截图**
![image](https://github.com/user-attachments/assets/7f69b407-4b73-4e18-9945-1d6a1c70120a)

**Comment by c121914yu** [comment]
重复 issue。
之前有提过，你也没给版本号，补充完再提问，

**Comment by ppkitty** [comment]
版本是4.8.2
