### ISSUE TITLE
怎么匿名开放一些api

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#2084]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
私有化部署了一个版本
现在希望可以匿名直接访问一些api 而不必去登录
**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
用api key
