### ISSUE TITLE
应用自动执行

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#2086]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.2

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
用高级编排做的应用，关闭了定时执行，还是会自动执行。每天HTTP调用都会收到大量的call, 但是明明没有人用。有些出现在半夜3,4点。检查了设置，不管是高级编排还是简单编排，定时执行都是“未开启”状态。
不知道哪里还有设置。

**复现步骤**

**预期结果**
没有设置自动执行，不会执行

**相关截图**
![image](https://github.com/user-attachments/assets/a9f7e6ec-2594-4c10-876b-8bcf40d8e301)

**Comment by ppkitty** [comment]
没有查到类似issue呢

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/1772
https://github.com/labring/FastGPT/releases/tag/v4.8.5
