### ISSUE TITLE
通过docker拉取容器失败：missing signature key，更换网路后依然存在

### ISSUE THREAD

**Issue by aiyouwoqudi** [labring/FastGPT#2088]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ]x 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ]x 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/9435e513-b465-4609-a7c5-e3e8f0fc9280)
前置步骤已确认完成

**复现步骤**
1、正常按步骤安装执行docker-compose up -d，无其他动作
**预期结果**
预期可正常安装，但当前未能正常安装
**相关截图**
无

**Comment by aiyouwoqudi** [comment]
所有安装步骤，均按照https://doc.fastgpt.in/docs/development/docker/执行

**Comment by c121914yu** [comment]
环境问题，与项目无关，根据自己服务器环境百度查问题～
