### ISSUE TITLE
关于知识库地点检索、精确匹配以及变量更新

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2089]
探讨一个需求的实现思路，请高手指点下
​用户输入出差信息，通过内容提取功能获取出发地 中转地 目的地的名称并保存到变量中。

现在希望将这些地点信息与知识库的地点信息模糊比对。
​
​如果知识库中只有一条类似信息（例如用户输入的是北京，而知识库里是北京市），则直接更新变量信息为北京市对应的ID
​
​如果知识库中没有类似地点信息，则提示用户更改名称，然后重新检查名称并更新变量值为知识库里内容的ID

如果知识库中匹配了多条类似信息，例如用户输入西安，但知识库里有西安市和西安区，则要求用户明确选择，然后根据用户确认的信息更新变量值为知识库对应地点的ID
​
​

**Comment by c121914yu** [comment]
可以先创2 个数据（例2），看模型能不能判断出来。
