### ISSUE TITLE
知识库取消选择操纵失败

### ISSUE THREAD

**Issue by Dr-xiaoming** [labring/FastGPT#2096]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**
1.首先设置了知识库变量，然后我取消了它，ui显示正常，但是对话就报错，导出配置发现配置里知识库变量里还是有值
**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/3685b248-6284-4398-972a-1bb126c65abc)

**Comment by c121914yu** [comment]
具体版本？目前没发现该问题
