### ISSUE TITLE
全局自定义变量进行变量更新后第二轮对话丢失

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#2099]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.6

**问题描述, 日志截图**

**复现步骤**
1.通过对话形式进行变量更新对name和tel进行赋值，在对话中拼接变量结果正常
2.第二轮对话调用全局变量的变量值无效

**预期结果**
第二轮能够保留变量的赋值
**相关截图**
![image](https://github.com/user-attachments/assets/36d7b32c-4baf-4fca-bc42-a417fdf245e0)
![image](https://github.com/user-attachments/assets/3f24cbdc-f701-4288-8257-eef97bd045c0)
![image](https://github.com/user-attachments/assets/bda647bc-4207-4f10-8a9a-0d90571d85a4)

**Comment by sdytzjp** [comment]
看看咱俩说的是不是一个事情？  #2100
