### ISSUE TITLE
【类型：自定义变量】的全局变量赋值有bug？

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2100]
测试步骤如下：
1、设置全局变量text，变量类型：自定义变量
2、用户输入信息，走判断器else分支，将用户问题存入变量text
3、ai回复：是否确认，确认请输入ok
4、用户输入ok，走判断器if分支，此时变量text为【空值】
5、但是，如果将变量类型设置为【文本】，第4步就可以输出变量值
根据以上测试，如果要满足我们的场景，只能使用【文本类型】的变量，但这种类型下，用户每次打开都会有一个要求输入变量内容的提示框，即便设置非必填，放在那里显示，用户体验也很不好

![image](https://github.com/user-attachments/assets/7b83e61e-83a4-4d07-b561-3ddd1b5c2236)
![image](https://github.com/user-attachments/assets/04d66e76-07ae-441e-abb9-205a94bcd4e1)

![image](https://github.com/user-attachments/assets/1cd37677-91dd-48fd-ba99-abf124e762d9)

**Comment by sdytzjp** [comment]
@c121914yu

**Comment by c121914yu** [comment]
duplicate #2059
