### ISSUE TITLE
问题分类或者工具调用，会话无法连续进行

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2102]
4.8.7
问题分类或者工具调用，配合应用调用的方式，初衷是将复杂的多事物处理的流程进行解耦，单独规划，再整合在一起。

但是使用起来总是无法到达连续对话的目的，例如：

人工：明天从北京出差去上海
ai：好的。（ai此时可以通过问题分类或者工具调用，找到出差的应用程序）
人工：改为后天
ai此时的回复，就可能是另一个问题分类的内容，无法继续上次的对话而继续调用出差的应用

**Comment by xiaoToby** [comment]
记录聊天记录呗

**Comment by sdytzjp** [comment]
已经记录聊天内容了，但是总是在第二轮提问时，进行了错误的分类


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] 问题分类或者工具调用，会话无法连续进行 (Issue #2102)





 
记录聊天记录呗

**Comment by c121914yu** [comment]
怎么编排的，工具怎么描述的
