### ISSUE TITLE
http模块进行本地调用api出现超时

### ISSUE THREAD

**Issue by Love-percation** [labring/FastGPT#2104]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x ] 我已确认目前没有类似 issue
- [x  ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x  ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x ] 私有部署版本, 具体版本号: 4.8.7

**问题描述, 日志截图**
问题一：模仿b站up主，来进行联网查询，在postman和sealos 平台能正常访问api，sealos上已经进行过发布，加上上body后。但是在fastGPT发布后，进行调试，结果异常。
问题二：将百度搜索api换成本地api，出现超时
![image](https://github.com/user-attachments/assets/a9deafbe-8385-4b35-9034-6a2fc636e7fe)

**复现步骤**
问题一：
![K2G~ ZWDTCF53FV4F7ES2HW](https://github.com/user-attachments/assets/1dfccf5e-30f5-4bdc-a7a1-7ef0fcc29111)

![R8ETSCTB$@$229~RSE)Z21C](https://github.com/user-attachments/assets/25304124-a13d-4a0e-99e7-c8ef7f6eb96d)
问题二：
本地api地址，在postman中加上请求参数后，能够正常访问.在fastGPT中出现超时问题。
![image](https://github.com/user-attachments/assets/a5138cf5-e348-48a3-97eb-5c745900f716)
![image](https://github.com/user-attachments/assets/13bebe09-10fd-47e3-8a98-17a7d46dca85)

**预期结果**
期望搜索出结果，调试时，能返回指定回答，如sealos和postman所示。
![image](https://github.com/user-attachments/assets/49bf6800-7823-417c-8e3b-e239e78fa9ae)
![image](https://github.com/user-attachments/assets/021f71c3-874c-4a44-86c3-5b1d0f265ab1)
![image](https://github.com/user-attachments/assets/234fec44-fc24-4a1d-9cdc-0c8313b9ba2a)

**相关截图**

**Comment by Love-percation** [comment]
sealos上的api，使用post和body字段，能够返回和up主相同的结果。
![image](https://github.com/user-attachments/assets/f2e81dfd-d495-474c-90a4-d7c741bec96d)

**Comment by Love-percation** [comment]
![image](https://github.com/user-attachments/assets/d31dd368-3dd6-47cd-a601-5f4e3079a30e)
按照up主的post请求和body写法，在sealos上的谷歌搜索url能够正确返回检索信息。

**Comment by c121914yu** [comment]
那就是你本地网络通信问题了，得自己逐步排查经过的线路。
