### ISSUE TITLE
当前分组 default 下对于模型 gpt-4o-mini 无可用渠道 (request id: 20240720184929126232784JoNA4YYD)

### ISSUE THREAD

**Issue by marcotam1228** [labring/FastGPT#2105]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
你好，我是在線使用的，我輸入中轉api key 出現以下錯誤: 

当前分组 default 下对于模型 gpt-4o-mini 无可用渠道 (request id: 20240720184929126232784JoNA4YYD)

在線使用的  可以改這個default 模型嗎? 謝謝

**Comment by zaite** [comment]
中转还不支持新模型，可以在中转渠道指定一下

**Comment by marcotam1228** [comment]
![螢幕擷取畫面 2024-07-21 145103](https://github.com/user-attachments/assets/0c33cfd7-6293-4722-b027-8084577262e1)
所以說暫時 這個沒辦法解決...謝謝你

**Comment by xy3xy3** [comment]
中转的问题。可以考虑换个中转商家
https://api2.aigcbest.top/register?aff=v85E

**Comment by leeileduo** [comment]
可以通过oneapi容器进行添加需要的大模型。官方文档有介绍
![1111](https://github.com/user-attachments/assets/51aa0f58-4891-42be-984a-adefe6ab99c5)
![222](https://github.com/user-attachments/assets/b11c5208-09fd-408e-b92a-205dba1da41b)
![E36332B5-9AED-4d5f-94C1-46E60AFFBE09](https://github.com/user-attachments/assets/b7ce479e-9ff8-41bf-93dc-28ab7f0742f8)

**Comment by leoyyer** [comment]
![Uploading image.png…]()

**Comment by leoyyer** [comment]
我也遇到同样的问题，添加遇到的时候，验证是通过的，但是实际使用时也是这个错误。

**Comment by fsinbad** [comment]
好像是个误报，可以不管。

**Comment by 1301633938** [comment]
> ![螢幕擷取畫面 2024-07-21 145103](https://github.com/user-attachments/assets/0c33cfd7-6293-4722-b027-8084577262e1) 所以說暫時 這個沒辦法解決...謝謝你

您好，有点问题想问问您

**Comment by zaite** [comment]
> 我也遇到同样的问题，添加渠道的时候，测试是通过。但是实际使用时也是这个错误。 ![1](https://github.com/user-attachments/assets/177c2c23-099e-4c38-83bb-6f16dfb08335) ![2](https://github.com/user-attachments/assets/74f711ae-4a7e-4be6-bb6c-0bae9ab03b38) 我的配置为: "llmModels": [ { "model": "SparkPro", "name": "Spark Pro", "avatar": "/imgs/model/openai.svg", "maxContext": 4000, "maxResponse": 2000, "quoteMaxToken": 4000, "maxTemperature": 1, "charsPointsPrice": 0, "censor": false, "vision": false, "datasetProcess": true, "usedInClassify": true, "defaultSystemChatPrompt": "", "defaultConfig": {} }, { "model": "gpt-4o-mini", "name": "gpt-4o-mini", "avatar": "/imgs/model/openai.svg", "maxContext": 125000, "maxResponse": 16000, "quoteMaxToken": 120000, "maxTemperature": 1.2,

自定义了SparkPro渠道，那该渠道里的模型配置里，加上或者勾上“SparkPro”没有？？

**Comment by 1301633938** [comment]
> 里

怎么联系您，我这个就是不行

**Comment by taibaizhouzi** [comment]
我也遇到类似问题，参照[leoyyer](https://github.com/leoyyer)的方法，解决了。
在oneapi中重定向模型，并调用新名称即可，如图：注意原名模型要保留（蓝色部分）

<img width="1649" height="530" alt="Image" src="https://github.com/user-attachments/assets/5be405e4-8611-49f4-aaaa-983858ebe08d" />
