### ISSUE TITLE
对话开始前必填变量判断需要调整

### ISSUE THREAD

**Issue by bruceye777** [labring/FastGPT#211]
两个必填变量只填了一个，仍然可以通过点击上面的快捷按键链接开始对话
![image](https://github.com/labring/FastGPT/assets/41668200/82ede2b5-8a90-4766-9be9-6051379f39e4)
没有选择区服，TKP是提示词中的内容
![image](https://github.com/labring/FastGPT/assets/41668200/0f917c97-9f58-4bd7-a205-3e52364b3023)

**Comment by c121914yu** [comment]
已修复

**Comment by bruceye777** [comment]
@c121914yu 大佬这个4.3版本要怎么升级啊，我按照那个文档（https://doc.fastgpt.run/docs/installation/upgrading/43/）做，貌似还是一样没有修复啊
curl http://mydomain/api/admin/initv43   -H "rootkey: root_key" 
修改compose文件加入FILE_TOKEN_KEY
执行docker-compose up -d
还需要做什么？

**Comment by c121914yu** [comment]
> @c121914yu 大佬这个4.3版本要怎么升级啊，我按照那个文档（[https://doc.fastgpt.run/docs/installation/upgrading/43/）做，貌似还是一样没有修复啊](https://doc.fastgpt.run/docs/installation/upgrading/43/%EF%BC%89%E5%81%9A%EF%BC%8C%E8%B2%8C%E4%BC%BC%E8%BF%98%E6%98%AF%E4%B8%80%E6%A0%B7%E6%B2%A1%E6%9C%89%E4%BF%AE%E5%A4%8D%E5%95%8A) curl http://mydomain/api/admin/initv43 -H "rootkey: root_key" 修改compose文件加入FILE_TOKEN_KEY 执行docker-compose up -d 还需要做什么？

似乎我这没啥，，选框不填的话点开始是没有反应的。 你可以看看空白对话时候，那个版本好是不是4.3

**Comment by bruceye777** [comment]
@c121914yu "选框不填的话点开始是没有反应的" 这部分是正常的，之前反馈的是“可以通过点击上面的快捷按键开始对话”
空白对话的时候，我没看到哪里有版本号
还有就是我刚刚又再次docker-compose（只包含fastgpt，没有包含pg和mongo），指定了v4.3，发现进去后应用，知识库全部丢失了。。改回latest又恢复正常了
image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:v4.3

**Comment by c121914yu** [comment]
> @c121914yu "选框不填的话点开始是没有反应的" 这部分是正常的，之前反馈的是“可以通过点击上面的快捷按键开始对话” 空白对话的时候，我没看到哪里有版本号 还有就是我刚刚又再次docker-compose（只包含fastgpt，没有包含pg和mongo），指定了v4.3，发现进去后应用，知识库全部丢失了。。改回latest又恢复正常了 image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:v4.3

噢噢，，了解了。。刚改好了，待会发上去。
下面的不懂，，没遇到过，，环境变量连上同一个库就没啥问题。、
