### ISSUE TITLE
页面文本缺失

### ISSUE THREAD

**Issue by ws02589111** [labring/FastGPT#2112]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

发现界面上有大量文本缺失

代码版本: 57ff38e16f2d9567e88c3bc7d0fc1ea81004f6c1
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/7ba8b2b3-360d-4966-a615-c96f920d70a9)
![image](https://github.com/user-attachments/assets/5b9f04b1-bc59-415a-976b-44b80f16d0df)
![image](https://github.com/user-attachments/assets/68bdb926-6ea0-409c-b819-2b204421b712)
![image](https://github.com/user-attachments/assets/69bab473-b930-451c-9ea1-1e261c02b418)

**Comment by c121914yu** [comment]
我这里都正常，检查下是不是你合并代码问题

**Comment by ws02589111** [comment]
我在代码的i18n里面确实没有找到相关内容：
https://github.com/labring/FastGPT/blob/f452554663f77b15162354d18e1d2c1f17f47ba3/packages/web/i18n/zh/common.json

或许是我找错地方了？

**Comment by c121914yu** [comment]
> 我在代码的i18n里面确实没有找到相关内容： https://github.com/labring/FastGPT/blob/f452554663f77b15162354d18e1d2c1f17f47ba3/packages/web/i18n/zh/common.json
> 
> 或许是我找错地方了？

看了下记录还真是，我本地还没拉最新代码，没发现这个问题。我让他回退重新改下。
