### ISSUE TITLE
claude工具调用报错

### ISSUE THREAD

**Issue by Dr-xiaoming** [labring/FastGPT#2123]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/08dd5805-49a1-4ec7-ad6e-7654da7679c0)
![image](https://github.com/user-attachments/assets/f22b1f85-6059-4da0-a7d7-ac6a603f4209)

**复现步骤**
配置文件里直接让claude3.5工具调用会报错，目前配置文件里设置function call为false后可以解决问题，但是这样的输出会很不稳定，看平台上现在好像也是这样处理的，没有别的解决办法嘛？
**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
claude 就没支持函数调用吧
