### ISSUE TITLE
聊天框发送图片报错

### ISSUE THREAD

**Issue by ak-2019** [labring/FastGPT#2127]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.7

**问题描述, 日志截图**
配置了一个智谱多模态模型glm-4v，在聊天界面发送给图片，接口报错了
报错信息：1210 API 调用参数有误，请检查文档。 (request id: 2024072301580059367911215206506)
![1721699293061](https://github.com/user-attachments/assets/badaccc2-5dbb-461d-8a6d-81cd19e4fdb8)
config.json配置
![image](https://github.com/user-attachments/assets/24185eb0-46ba-4540-b070-0d8a47248940)
**复现步骤**
1. oneapi和config.json引入glm-4v模型
2. fastgpt界面搭建agent
3. 配置glm-4v调试
4. 调试报错

**预期结果**
正常响应

**相关截图**

**Comment by ak-2019** [comment]
这是docker的报错日志
![image](https://github.com/user-attachments/assets/f0a84b22-c691-4b9c-9a02-961196291629)

**Comment by c121914yu** [comment]
参数有问题，请检查 oneapi 是否支持

**Comment by sdytzjp** [comment]
请问针对多模态模型的CURL测试命令是下面的请求地址格式吗？另外相关参数在哪里找？

curl --location --request POST 'http://oneapi-IP:PORT/v1/chat/completions' \
--header 'Authorization: Bearer sk-fastgpt' \
--header 'Content-Type: application/json' \
--data '{
  "model": "qwen-vl-v1",
  "max_tokens": 400,
  "messages": [
    {
            "role": "user",
            "content": [
                {"image": "https://q8.itc.cn/c_lfill,w_640,h_426,g_face/images03/20240727/f2b8942be4c74a7b94e55f6b900632aa.jpeg"},
                {"text": "这是什么?"}
            ]
        }
  ]
}'

**Comment by ak-2019** [comment]
换零一模型解决了

**Comment by sdytzjp** [comment]
麻烦明确下具体哪个模型？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月2日(周五) 下午3:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 聊天框发送图片报错 (Issue #2127)




 
换零一模型解决了

**Comment by ak-2019** [comment]
> 麻烦明确下具体哪个模型？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月2日(周五) 下午3:23 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [labring/FastGPT] 聊天框发送图片报错 (Issue #2127) 换零一模型解决了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

yi-vl-plus

**Comment by cmdhh** [comment]
> 换零一模型解决了

能说具体一点吗，我也碰到了这个问题，oneapi的模型类型换成零一？我这么做还是错的
