### ISSUE TITLE
调用 /file/upload 报403权限错误

### ISSUE THREAD

**Issue by lwdnxu** [labring/FastGPT#2128]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
上传文件报错，反复确认key是没错的，这个功能必须是商业版才能用吗？status是200，但是response.json()显示403

**相关截图**
![image](https://github.com/user-attachments/assets/a3485c88-afdc-4b81-8206-575adf967e2e)

**Comment by c121914yu** [comment]
fileupload 不支持 API key。只有文档里声明的接口支持 API key 调用
