### ISSUE TITLE
希望全局变量里面是否可以加一个图片image字段

### ISSUE THREAD

**Issue by HelloEveryonehh** [labring/FastGPT#2129]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在对话框上传图片的时候，希望能得到图片的image-url，可以放在全局变量里面，如果没有上传图片，则为空
**应用场景**
当前我遇到的一个场景是，当我发送对话的时候需要先判断一下用户是否上传了图片，如果用户上传了图片，则应该走第一个分支，如果没有上传图片，则应该走第二个分支。现在的问题是，因为上传图片后，没有一个参数表示图片的url，所以我只能采取AI对话模块，gpt-4o判断是否上传图片，这样有点浪费时间。而且当我调用fastgpt的对话api的时候，在image-url参数里面放入图片url,只有第一个AI对话模型可以读到图片，后面的AI对话模型好像读不到图片内容了。
**相关示例**
目前采取的方案是
![image](https://github.com/user-attachments/assets/da208a82-f4e9-423f-9b46-8dd24b499d43)

**Comment by HelloEveryonehh** [comment]
补充一下，我采取上述工作流的时候，当我的输入同时有文字和图片，会直接报错
![image](https://github.com/user-attachments/assets/ef3a17e1-960c-4a01-beca-a9bd6e16d440)
日志如下
![image](https://github.com/user-attachments/assets/33b2cc11-65bf-4923-be92-25a4e7abf917)

**Comment by c121914yu** [comment]
新版可以拿到图片链接了。
