### ISSUE TITLE
ai输出能不能增加一个功能：如果识别知识库到带有[]的问题，ai输出出来，我们可以点击，发送我们所点击的问题。跟开场白一样

### ISSUE THREAD

**Issue by wbext** [labring/FastGPT#2133]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 features
- [ x] 我已确认我已升级到最新版本
- [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我们往知识库里放问题，先从开场白开始点击大类问题，ai会输出大类问题的分支问题，用户会不断点击发送分支问题，直到引导用户问到自己需要问的问题为止。
<img width="390" alt="1721715248380" src="https://github.com/user-attachments/assets/36bea9f9-d135-48f8-aa4f-007b5c01a049">
**应用场景**
因为用户没有这么多时间引导ai输出自己想要的答案，我们可以预设一些问题让用户点击发送，让用户在最短时间里得到自己想要的答案。而开场白的预设问题覆盖范围不够，可能需要ai输出一些预设问题来细分。
**相关示例**

**Comment by lijiajun1997** [comment]
+1

**Comment by ws02589111** [comment]
![image](https://github.com/user-attachments/assets/a3247a70-6240-40f4-b631-4940ac9b4562)

markdown， 你值得拥有

**Comment by zaite** [comment]
> ![image](https://private-user-images.githubusercontent.com/10301545/351967729-a3247a70-6240-40f4-b631-4940ac9b4562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjIzNDQsIm5iZiI6MTcyMTkyMjA0NCwicGF0aCI6Ii8xMDMwMTU0NS8zNTE5Njc3MjktYTMyNDdhNzAtNjI0MC00MGY0LWI2MzEtNDk0MGFjOWI0NTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE1NDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ODc2YTQxNzIwMmUzNzlmMTQyMDIzOWZkNDE2MjE1MmFmNDdjMDhkODNjZGRkOTViZWExZGFiYzg4ZWMyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ua6pe5LAHzQqzGRUPZAPJ57TWgqY8p7YJ8WRZGFyW-U)
> 
> markdown， 你值得拥有

楼上说的是快捷问题选择，你这个是超链接

**Comment by c121914yu** [comment]
用超链接就可以，url 留空，前端已经做特殊处理了。

**Comment by wbext** [comment]
> 用超链接就可以，url 留空，前端已经做特殊处理了。

具体怎么实现呢？知识库的问题搞成超链接吗？

**Comment by wbext** [comment]
> 用超链接就可以，url 留空，前端已经做特殊处理了。

我将问题转化成markdown超链接，url留空的格式，点击他依然刷新页面
![image](https://github.com/user-attachments/assets/ae81b723-7418-4c6c-8ad8-30e28d01cf0b)

**Comment by c121914yu** [comment]
<img width="497" alt="image" src="https://github.com/user-attachments/assets/576c8808-2a81-439d-a37a-a794da234fc7">

```
[你好]()
```

**Comment by wbext** [comment]
> <img alt="image" width="497" src="https://private-user-images.githubusercontent.com/50446880/353303613-576c8808-2a81-439d-a37a-a794da234fc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTExNTIsIm5iZiI6MTcyMjMxMDg1MiwicGF0aCI6Ii81MDQ0Njg4MC8zNTMzMDM2MTMtNTc2Yzg4MDgtMmE4MS00MzlkLWEzN2EtYTc5NGRhMjM0ZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAzNDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWU2MTVkMDlkODQ5YTFlZjY3OWIwZmM0Y2QyNjYwNjA1YTFjNTI2YjY4MTVkM2ZhMTRkMjZiZjlkYzAwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x-DgQjbz-t1VfBVDkjzavA8glh-H9c_p6K61k8gmkrk">
> ```
> [你好]()
> ```

懂了阿里嘎多
