### ISSUE TITLE
core.chat.Chat API is error or undefined

### ISSUE THREAD

**Issue by xiaohuohu** [labring/FastGPT#2137]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我是使用ollama私有部署，使用curl可以正常的收到回复，但是使用应用示例或者oneapi中的测试，观察到接口不对使用的是"/api/chat"，查看ollama日志
![image](https://github.com/user-attachments/assets/69a9a64f-90dd-4a89-a2d5-9f6521996530)
![1721723274028](https://github.com/user-attachments/assets/4af70893-be8d-41fa-86e2-7805e041797c)

**复现步骤**

**预期结果**
使用正确的调用接口 "/v1/chat/completions"
**相关截图**

**Comment by c121914yu** [comment]
翻之前 issue 或者 oneapi issue 有提

**Comment by xiaohuohu** [comment]
![1721800252515](https://github.com/user-attachments/assets/81d2a356-513f-4b56-b27c-66d35c3d01c2)
解决了  因为使用的ollama部署，所以吧openapi地址换成ollama就也正常运行了
