### ISSUE TITLE
What is the problem with response error 429 426 404

### ISSUE THREAD

**Issue by LauranceDeer** [labring/FastGPT#214]
![WX20230823-111201@2x](https://github.com/labring/FastGPT/assets/131638373/fcf0f793-10fc-45f3-b7c2-2a54060c1b36)
![WX20230823-111216@2x](https://github.com/labring/FastGPT/assets/131638373/4e120fb2-1b51-43a4-bb88-86e22b98bcfe)

**Comment by c121914yu** [comment]
openai key error
