### ISSUE TITLE
core.chat.Chat API is error or undefined & 对话接口报错或返回为空

### ISSUE THREAD

**Issue by phonezhou** [labring/FastGPT#2144]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x ] 私有部署版本, 具体版本号: v4.8.7

**问题描述, 日志截图**

我从4.8.5升级到4.8.7就出现了对话接口报错或返回为空。
<img width="533" alt="image" src="https://github.com/user-attachments/assets/3d995093-cc86-4306-a52e-1e02402d2ad4">

oneapi 测试是正常的

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/f116768e-c26e-4761-81ae-08ecf86afde6">

尝试看FastGPT 的log

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/3400284a-bf8f-43f7-8b68-44dd1da9ed4c">

**复现步骤**

**预期结果**

**相关截图**

**Comment by phonezhou** [comment]
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/c055f8a4-30cf-4b43-8d2b-e2ae89947ba6">

**Comment by phonezhou** [comment]
4.8.5我是用了好一段日子，一直都正常的，就是升级了4.8.7出问题了，求帮助！

**Comment by phonezhou** [comment]
我在fastgpt问问题，然后看oneapi的日志

error unmarshalling stream response: invalid character '}' after top-level value

**Comment by xiaohuohu** [comment]
> 我在fastgpt问问题，然后看oneapi的日志
> 
> error unmarshalling stream response: invalid character '}' after top-level value
解决了吗 我也遇到了，curl测试是正常的有流数据返回

**Comment by xiaohuohu** [comment]
我的问题解决了，我是用的是ollama本地部署，需要把接口换成ollama

**Comment by xiaohuohu** [comment]
![image](https://github.com/user-attachments/assets/2546509a-497b-46e9-8245-1e346f342a01)

**Comment by xiaohuohu** [comment]
![image](https://github.com/user-attachments/assets/1b061a51-d3d6-489d-965c-6b6ae15efeba)  试试自定义模型

**Comment by wananBristl** [comment]
> ![image](https://private-user-images.githubusercontent.com/52985310/351588569-2546509a-497b-46e9-8245-1e346f342a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODk5MDksIm5iZiI6MTcyMTg4OTYwOSwicGF0aCI6Ii81Mjk4NTMxMC8zNTE1ODg1NjktMjU0NjUwOWEtNDk3Yi00NmU5LTgyNDUtMWUzNDZmMzQyYTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA2NDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyN2MyZWRiMzYwMWVjY2NjYjU1MzM0NzExMzM2NzVkY2QwOTRjMmNlMTVkYTIzODExNTc3YmUzYzlhNDhmNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Rrt2yqdvStN8bw-Q3T2KsUyggTZmdVlUktmBV-_lPc)

我也是升级到4.8.7之后被同样的问题困扰了两天，但是按您这样填写的话就相当于没有使用oneapi来做管理了吧

**Comment by c121914yu** [comment]
看之前 issue，不要用 0.6.8 的 oneapi
