### ISSUE TITLE
插件 url导入是不是不支持http?

### ISSUE THREAD

**Issue by sunk926** [labring/FastGPT#2147]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [x] 私有部署版本, 具体版本号: 
 导入的时候直接提示 URL无效,由于接口都是使用apifox这类api工具先测试好了,再生成url的openapi,要是不支持http每次调整都要手动拷贝,挺麻烦的.

**Comment by FinleyGe** [comment]
https://github.com/labring/FastGPT/pull/2159
