### ISSUE TITLE
如何变更QAmodel

### ISSUE THREAD

**Issue by 1715924014** [labring/FastGPT#215]
我在config.json中添加了文心一言模型，现在想用文心一言的模型去做知识库的QA，但是日志显示'当前分组 default 下对于模型 gpt-3.5-turbo-16k 无可用渠道'，这个还需要调哪些参数

**Comment by c121914yu** [comment]
目前还不支持变更

**Comment by kawriwshi33** [comment]
> 目前还不支持变更

也问下，昨天是在yml中直接配的openai，能够做知识库的QA，今天我换成oneapi的接口，也是用的openai的key，但是在做QA的时候，也是出“当前分组 default 下对于模型 gpt-3.5-turbo-16k 无可用渠道'”这个错误

**Comment by Timoshao** [comment]
同样遇到了
![image](https://github.com/labring/FastGPT/assets/108260847/5ca228e8-c028-4b83-8d7d-0325a7fdae66)

**Comment by c121914yu** [comment]
已支持，参考最新发行版说明：https://github.com/labring/FastGPT/releases/tag/v4.2.1

**Comment by c121914yu** [comment]
oneapi需要增加gpt35 16k作为QA模型，5刀用不了，一分钟只能3次，
