### ISSUE TITLE
fastgpt支持root url配置吗，通过子路由访问

### ISSUE THREAD

**Issue by chenhb-zte** [labring/FastGPT#2152]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
支持root url 配置，如使用https://xxxx:3000/fastgpt 格式url访问

**应用场景**
比如同一个域名下有多个网站，使用url子路径形式反向代理到不同的后端服务，比如：
https://domain/xxx    -> https://xxx:3001/xxxx
https://domain/yyy  -> https://yyy:3002/yyyy
https://domain/zzz  ->  https://zzz:3000/fastgpt

目前fastgpt只支持根目录访问， 希望像grafana支持root_url配置

**相关示例**

**Comment by c121914yu** [comment]
不支持
