### ISSUE TITLE
上传图片报错大小 以及 图片识别的问题

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2153]
4.8.7

请问上传图片的大小在哪里控制？默认多大？如何调整这个限制？

另外，为什么图片还有以下问题
1- 上传图片后，如果不输入文字，会提示question is empty
2-无论上传图片还是图片的url，fastgpt都无法识别？这个是不是需要多模态模型
![154d28bde6473f4454615bcfdf698ef](https://github.com/user-attachments/assets/b20a6662-2cd8-4527-9649-72ec189b000c)

![9a45b6ac944d8783377d53e6e1d5c41](https://github.com/user-attachments/assets/e37d142a-597c-494b-bb24-536a570a37c6)
![b15bf040c5d4a8b5a5d88bdae229390](https://github.com/user-attachments/assets/e2861032-a354-416e-ac14-4489d161d6cb)

**Comment by xiaoToby** [comment]
当然是需要多模态模型例如cogvlm

**Comment by c121914yu** [comment]
网关设置得太小了，把你服务器 nginx 或其他网关设置上传大小大点。
