### ISSUE TITLE
知识库支持 RAPTOR 改进算法

### ISSUE THREAD

**Issue by zhanghx0905** [labring/FastGPT#2161]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

目前的召回算法只能从知识库中取得文本片段，这限制了对文档整体的深入了解。RAPTOR 提出了一个创新的做法，在构建知识库时递归地嵌入、聚类和概括文本块。

1. **文本分割**：将检索的文本分割成短文本段，这与传统的检索增强技术类似。
2. **嵌入与聚类**：调用 Embedding 模型获得嵌入向量，通过聚类将文本段分组。分组后，利用语言模型对每一组文本进行概括总结。
3. **循环嵌入与概括**：这些总结过的文本会被重新嵌入，经过嵌入、聚类、总结的循环，直至无法进一步聚类。最终形成了一种结构化的、多层次的树状表示，详细呈现了原始文档的内容。
4. **加入知识库**：在此过程中生成的所有文本块均被加入知识库。搜索的流程与普通的检索方法相同。

这种算法相比 GraphRAG 更为简单，构建成本更低，推理时也不使用任何额外的 Token，速度更快。

**应用场景**

- **文档分析**：提供对长文档的深入理解和分析。
- **知识管理**：构建层次化的知识库以便更有效地管理和检索信息。
- **搜索优化**：通过多层次结构优化搜索结果的相关性和精确度。

**相关示例**

Ragflow的实现 https://github.com/infiniflow/ragflow/blob/main/rag/raptor.py
原论文的中文翻译 https://baoyu.io/translations/ai-paper/2401.18059-raptor-recursive-abstractive-processing-for-tree-organized-retrieval

**Comment by zhanghx0905** [comment]
通过API简单实现了一下，感觉适用范围有限制。

**Comment by TragedyN** [comment]
+1
