### ISSUE TITLE
工具调用后，无法正常查看工具运行详情

### ISSUE THREAD

**Issue by chung1912** [labring/FastGPT#2165]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![a1c44731a40a2f431b41b26b3cdfab0](https://github.com/user-attachments/assets/583eb049-1af6-4a82-a45f-9247fd5363f7)

**复现步骤**
如上所述，工具运行详情只能看个标题，里面的内容看不到
**预期结果**
希望能正常显示
**相关截图**

**Comment by zaite** [comment]
浏览器开无痕模式也是这样吗？

**Comment by chung1912** [comment]
> 浏览器开无痕模式也是这样吗？

是的，无痕模式也一样，换电脑访问也一样

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/2143
这个 pr 有修复
