### ISSUE TITLE
全局变量history默认十条可否调整

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2167]
4.8.7

全局变量，最近聊天记录默认保留10条，这个可否调整

**Comment by Essence9999** [comment]
好像有个history的全局变量，你引用试试

**Comment by sdytzjp** [comment]
这个变量只有10条记录 不够



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月26日(周五) 上午9:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 当前会话聊天记录传递到企业微信客服窗口 (Issue #2167)




 
好像有个history的全局变量，你引用试试
