### ISSUE TITLE
提问，fastgpt报：Slow operation

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#2170]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/660b0d47-0b3d-43e9-b252-c8602e4c7c60)

**复现步骤**
ankane/pgvector:v0.5.0
mongo:5.0.18
fastgpt:4.8.6
one-api:v0.6.6

**Comment by c121914yu** [comment]
升级数据库配置

**Comment by Essence9999** [comment]
> 升级数据库配置，硬件不太行。

昨天根据你之前的相关issue回复，pg升级到0.7.0-pg15，启动fastgpt打开界面很卡、通过分享连接访问fastgpt也很卡，需要一些时间才能加载出来；也尝试了0.7.2-pg16，提示不兼容之类的，就没有升级。

**Comment by Essence9999** [comment]
> 升级数据库配置，硬件不太行。
服务器
cpu i9-11900K @ 3.50GHz 8核
![image](https://github.com/user-attachments/assets/4bec6fd0-dcae-48f8-a943-fd6ffefec4f4)
内存 64G

还不够吗？
是不是应该修改配置文件，给数据库分配内存？

**Comment by c121914yu** [comment]
> > 升级数据库配置，硬件不太行。
> > 服务器
> > cpu i9-11900K @ 3.50GHz 8核
> > ![image](https://private-user-images.githubusercontent.com/66725845/352360684-4bec6fd0-dcae-48f8-a943-fd6ffefec4f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjY1MjcsIm5iZiI6MTcyMTk2NjIyNywicGF0aCI6Ii82NjcyNTg0NS8zNTIzNjA2ODQtNGJlYzZmZDAtZGNhZS00OGY4LWE5NDMtZmQ2ZmZlZmVjNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAzNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzM2JiNWE2MzVlMDY2YmE5OWRjYTNkNWU3MmE3MmQzNDkwMjM2MTdkNGIxODA4YjA1NmEwNmMxZmI3YzM1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1wDuWHqLxDYWCbPUbD_Pp9vCNeQj9s6PJYMlt8QkZs)
> > 内存 64G
> 
> 还不够吗？ 是不是应该修改配置文件，给数据库分配内存？

看这个没用，你又不是裸机部署，你得看你容器分配了多少，还有 IO 交互速度。这块得自己好好研究。

**Comment by Essence9999** [comment]
> > > 升级数据库配置，硬件不太行。
> > > 服务器
> > > cpu i9-11900K @ 3.50GHz 8核
> > > ![image](https://private-user-images.githubusercontent.com/66725845/352360684-4bec6fd0-dcae-48f8-a943-fd6ffefec4f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjY1MjcsIm5iZiI6MTcyMTk2NjIyNywicGF0aCI6Ii82NjcyNTg0NS8zNTIzNjA2ODQtNGJlYzZmZDAtZGNhZS00OGY4LWE5NDMtZmQ2ZmZlZmVjNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAzNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzM2JiNWE2MzVlMDY2YmE5OWRjYTNkNWU3MmE3MmQzNDkwMjM2MTdkNGIxODA4YjA1NmEwNmMxZmI3YzM1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1wDuWHqLxDYWCbPUbD_Pp9vCNeQj9s6PJYMlt8QkZs)
> > > 内存 64G
> > 
> > 
> > 还不够吗？ 是不是应该修改配置文件，给数据库分配内存？
> 
> 看这个没用，你又不是裸机部署，你得看你容器分配了多少，还有 IO 交互速度。这块得自己好好研究。

好的，大佬，我调试看看

**Comment by Essence9999** [comment]
> > > 升级数据库配置，硬件不太行。
> > > 服务器
> > > cpu i9-11900K @ 3.50GHz 8核
> > > ![image](https://private-user-images.githubusercontent.com/66725845/352360684-4bec6fd0-dcae-48f8-a943-fd6ffefec4f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjY1MjcsIm5iZiI6MTcyMTk2NjIyNywicGF0aCI6Ii82NjcyNTg0NS8zNTIzNjA2ODQtNGJlYzZmZDAtZGNhZS00OGY4LWE5NDMtZmQ2ZmZlZmVjNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAzNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzM2JiNWE2MzVlMDY2YmE5OWRjYTNkNWU3MmE3MmQzNDkwMjM2MTdkNGIxODA4YjA1NmEwNmMxZmI3YzM1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1wDuWHqLxDYWCbPUbD_Pp9vCNeQj9s6PJYMlt8QkZs)
> > > 内存 64G
> > 
> > 
> > 还不够吗？ 是不是应该修改配置文件，给数据库分配内存？
> 
> 看这个没用，你又不是裸机部署，你得看你容器分配了多少，还有 IO 交互速度。这块得自己好好研究。
docker stats情况如下：
![image](https://github.com/user-attachments/assets/5ff1c863-c8bc-42cb-b7bd-d6dc1d37ecdc)
看着资源充足啊~
![image](https://github.com/user-attachments/assets/8acf66d1-f35b-420a-8a3c-efd15558e07c)
![image](https://github.com/user-attachments/assets/afc2e15b-881c-416f-a74b-84a64ee8040f)

是我数据库数据录入多了，导致查询耗时？？

**Comment by Essence9999** [comment]
@c121914yu 大佬，有空看下这个方法是否可以优化这类问题
https://github.com/pgvector/pgvector/issues/559#issuecomment-2117399664

**Comment by c121914yu** [comment]
> pgvector/pgvector#559 (comment)

Mongo 问题，看 pg 有啥用，而且和项目本身也没啥关系，取决于你部署。

**Comment by Essence9999** [comment]
> > [pgvector/pgvector#559](https://github.com/pgvector/pgvector/issues/559) (comment)
> 
> Mongo 问题，看 pg 有啥用，而且和项目本身也没啥关系，取决于你部署，检查你自己部署时候是否有足够 IO 交换速度和内存，看数据库负载瓶颈。尤其如果是使用 window 部署的，有很大程度只会用到 10% 的性能。

Ubuntu部署的；我一直以为是pg的问题，升级数据库，还计划转milvus.......
![image](https://github.com/user-attachments/assets/f18d8557-5986-4f3d-95f1-8a369bb59ad7)
