### ISSUE TITLE
阿里Qwen-VL模型，直接报错

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2177]
4.8.7
阿里Qwen-VL模型报错，只是输入文字就报错
config.json 和oneapi配置如下，oneapi渠道测试ok

![image](https://github.com/user-attachments/assets/0c521242-defe-405c-ab03-f674c9c527d5)
![image](https://github.com/user-attachments/assets/4b0329cf-5ee9-46e8-8882-13c9b5a598bc)
![image](https://github.com/user-attachments/assets/4526d52b-00a4-4138-b6f6-4122f79bd5a4)

**Comment by ChjxL** [comment]
请问你的问题解决了吗，我也遇到类似的问题
