### ISSUE TITLE
调用chatglm时，ai会话每次回复内容不全

### ISSUE THREAD

**Issue by swingsun888** [labring/FastGPT#218]
每次回复内容到半路就不输出了，停个几秒钟后就会话结束。

**Comment by c121914yu** [comment]
> 每次回复内容到半路就不输出了，停个几秒钟后就会话结束。
> 

请给出对应模型参数。回复长度，问题长度

**Comment by swingsun888** [comment]
通过其他的webui测试调用这个chatglm的api返回信息正常，chatglm所启用的api为代码目录中提供的文件。

**Comment by kongccc** [comment]
同样的问题 链接chatglm 回复结果丢失后半部分

**Comment by swingsun888** [comment]
大家有解决方法吗

**Comment by kongccc** [comment]
这个问题我也遇到了 调试了很久也没见解决 不知道是什么原因导致的

**Comment by c121914yu** [comment]
响应上限是2分钟。
是正常断开还是报错。
什么规格gpu。

**Comment by swingsun888** [comment]
看了完全响应里面的信息，应该是回复不全，属于正常断卡，NVIDIA T4 gpu

**Comment by aleimu** [comment]
也遇到了,有点奇怪
