### ISSUE TITLE
升级alpha2之后，突然就罢工了，升级之前没有修改过任何配置。

### ISSUE THREAD

**Issue by taurusduan** [labring/FastGPT#2180]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
[V4.8.8-alpha2](https://github.com/labring/FastGPT/releases/tag/v4.8.8-alpha2)
- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/4a202962-278e-4e7a-852f-69e411b46a1c)
4.8.8-alpha1升级alpha2之后，突然就罢工了，升级之前没有修改过任何配置。
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
完善描述再提

**Comment by taurusduan** [comment]
> 完善描述再提

4.8.8-alpha1升级alpha2之后搜索可以调用，但是不会反馈结果。

**Comment by c121914yu** [comment]
> > 完善描述再提
> 
> 4.8.8-alpha1升级alpha2之后搜索可以调用，但是不会反馈结果。

为什么呢？

**Comment by taurusduan** [comment]
> > > 完善描述再提
> > 
> > 
> > 4.8.8-alpha1升级alpha2之后搜索可以调用，但是不会反馈结果。
> 
> 为什么获取不到呢？

这就不知道了，之前alpha1有结果，升级之后就这样了，我看升级文档也没有说要修改什么地方。fastgpt做的后端知识库，dify做的前端工作流，dify上duckduck宫go的搜索没有问题。
![image](https://github.com/user-attachments/assets/57a4978f-04d4-4966-a474-a9530c5f1d56)

**Comment by c121914yu** [comment]
> > > > 完善描述再提
> > > 
> > > 
> > > 4.8.8-alpha1升级alpha2之后搜索可以调用，但是不会反馈结果。
> > 
> > 为什么获取不到呢？
> 
> 这就不知道了，之前alpha1有结果，升级之后就这样了，我看升级文档也没有说要修改什么地方。fastgpt做的后端知识库，dify做的前端工作流，dify上duckduck宫go的搜索没有问题。
> ![image](https://github.com/user-attachments/assets/57a4978f-04d4-4966-a474-a9530c5f1d56)
> 

所以，，日志呢🥲你看过了吗

**Comment by taurusduan** [comment]
> > > > > 完善描述再提
> > > > 
> > > > 
> > > > 4.8.8-alpha1升级alpha2之后搜索可以调用，但是不会反馈结果。
> > > 
> > > 
> > > 为什么获取不到呢？
> > 
> > 
> > 这就不知道了，之前alpha1有结果，升级之后就这样了，我看升级文档也没有说要修改什么地方。fastgpt做的后端知识库，dify做的前端工作流，dify上duckduck宫go的搜索没有问题。
> > ![image](https://private-user-images.githubusercontent.com/30854760/352784068-57a4978f-04d4-4966-a474-a9530c5f1d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDg4OTcsIm5iZiI6MTcyMjMwODU5NywicGF0aCI6Ii8zMDg1NDc2MC8zNTI3ODQwNjgtNTdhNDk3OGYtMDRkNC00OTY2LWE0NzQtYTk1MzBjNWYxZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAzMDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZmQ1MDRmMjgxYzljNDdhYTc2MGRmMzI2ZjY0YzAwMDkyMGM0NTYzMDE4Njk1Nzg0ZTQxNzcyNzE3YTk0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hXL22wst9vIxTNTfe-Xu_5Hf2xT6CGo6DXv9FWcg3Gk)
> 
> 所以，，日志呢🥲你看过了吗

给gpt看过了，没有发现问题，他这个迷惑的就是不是不能请求，更像是请求之后我不想告诉你。我恢复快照了，等正式版了。
