### ISSUE TITLE
指定回复中使用echarts代码，是否支持配合html

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2184]
4.8.7

请问下指定回复里面支持哪些代码

目前使用echarts有些功能不完善，需要配合html和js以及css等实现，可否支持这些代码，或者混合代码

测试了下html不支持

**Comment by c121914yu** [comment]
不支持HTMl，有很多相同 issue 了。

**Comment by sdytzjp** [comment]
不好意思，我用html关键词查看了所有issue没找到类似的问题。青提试下用什么关键字检索，我想知道如何扩展echarts功能，还支持哪些脚本语言
