### ISSUE TITLE
ollama部署向量模型如何添加到one-api

### ISSUE THREAD

**Issue by jingfeiliang** [labring/FastGPT#2200]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
fastgpt通过ollama部署大模型，聊天模型部署成功，请问同事部署向量模型m3e模型如何集成，one-api测试提示错误
**复现步骤**
<img width="806" alt="1722244390306" src="https://github.com/user-attachments/assets/7dccca65-0857-45ab-98ea-6d4c6e9382e6">
<img width="896" alt="1722244449629" src="https://github.com/user-attachments/assets/50b0655c-4091-4584-b5db-5c8587c952eb">

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
选择 ollama 渠道

**Comment by jingfeiliang** [comment]
改成ollama渠道可以了，感谢
