### ISSUE TITLE
阿里funASR如何接入，线上版已经接入

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2201]
线上版已经接入。
请问本地部署fastgpt如何接入阿里FunASR，config.json和oneapi怎么配置

请指导下

**Comment by c121914yu** [comment]
oneapi 直接填 funasr 地址，模型用 whisper-1

**Comment by sdytzjp** [comment]
请问oneapi是这样吗















&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月30日(星期二) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] 阿里funASR如何接入，线上版已经接入 (Issue #2201)





 
oneapi 直接填 funasr 地址，模型用 whisper-1

**Comment by zxwmol** [comment]
@c121914yu 能否有稍微具体一点的接入教程么？
