### ISSUE TITLE
插件详情页面无法返回到上一页

### ISSUE THREAD

**Issue by shilin66** [labring/FastGPT#2202]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.8

**问题描述, 日志截图**
插件详情页面，点击左上角无法返回上一页
**复现步骤**
进入插件详情页面，点击左上角返回
**预期结果**
正常返回上一页
**相关截图**
上方进度条已经拉满，右上角一直转圈
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/506c7793-f234-4ba8-b138-8024bb1a7143">

**Comment by c121914yu** [comment]
部署服务器 卡顿问题，检查网络和 cpu

**Comment by c121914yu** [comment]
Mark下

**Comment by sdytzjp** [comment]
不是网络问题，应该就是bug
抽除了返回其他按键一样，只能刷新页面退出插件
