### ISSUE TITLE
fastgpt新版本不支持openai接口，无法对接飞书、微信等应用

### ISSUE THREAD

**Issue by lijihua2017** [labring/FastGPT#2204]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
curl -X POST https://api.fastgpt.in/api/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer " -d '{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello, how are you?"}],
  "max_tokens": 50,
  "temperature": 0.7
}'
![Uploading WX20240730-113107.png…]()
![Uploading WX20240730-113107.png…]()

**Comment by c121914yu** [comment]
无效 issue

**Comment by lijihua2017** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by lijihua2017** [comment]
@c121914yu  请问一下这个是新版本去掉了openapi接口吗，那之前对接的飞书和微信怎么继续对接呢

**Comment by c121914yu** [comment]
> @c121914yu 请问一下这个是新版本去掉了openapi接口吗，那之前对接的飞书和微信怎么继续对接呢

一直能用，把你问题补全再说～图片都没有

**Comment by lijihua2017** [comment]
![image](https://github.com/user-attachments/assets/0cab3921-68b4-4bf5-89c6-891175052a0c)
这个接口无法访问了，api/openapi/v1接口无法使用了，只能用api/v1接口

**Comment by c121914yu** [comment]
> ![image](https://private-user-images.githubusercontent.com/33613942/353303707-0cab3921-68b4-4bf5-89c6-891175052a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTE0NDUsIm5iZiI6MTcyMjMxMTE0NSwicGF0aCI6Ii8zMzYxMzk0Mi8zNTMzMDM3MDctMGNhYjM5MjEtNjhiNC00YmY1LTg5YzYtODkxMTc1MDUyYTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAzNDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NDIwMGQ0NTEwYjlmY2NkNWQ5NjJkMzFlZjlkN2YxNGVlNDM2MDVmZWRhYWEyMGViY2U4ZTAyMzg0OTY5MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_1JUAufuu2lZcc5TqXQalbZ26n-SLVoUdxM2ScyHG0) 这个接口无法访问了，api/openapi/v1接口无法使用了，只能用api/v1接口，所以没法对接飞书了 @c121914yu

这个1 月就没了，用 v1 不就行了～

**Comment by lijihua2017** [comment]
> > ![image](https://private-user-images.githubusercontent.com/33613942/353303707-0cab3921-68b4-4bf5-89c6-891175052a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTE0NDUsIm5iZiI6MTcyMjMxMTE0NSwicGF0aCI6Ii8zMzYxMzk0Mi8zNTMzMDM3MDctMGNhYjM5MjEtNjhiNC00YmY1LTg5YzYtODkxMTc1MDUyYTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAzNDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NDIwMGQ0NTEwYjlmY2NkNWQ5NjJkMzFlZjlkN2YxNGVlNDM2MDVmZWRhYWEyMGViY2U4ZTAyMzg0OTY5MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_1JUAufuu2lZcc5TqXQalbZ26n-SLVoUdxM2ScyHG0) 这个接口无法访问了，api/openapi/v1接口无法使用了，只能用api/v1接口，所以没法对接飞书了 @c121914yu
> 
> 这个1 月就没了，用 v1 不就行了～

问题是这个v1和openapi/v1应该不兼容吧，不然之前为什么会有openapi/v1，直接换成api/v1根本就用不了

**Comment by c121914yu** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/33613942/353303707-0cab3921-68b4-4bf5-89c6-891175052a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTE0NDUsIm5iZiI6MTcyMjMxMTE0NSwicGF0aCI6Ii8zMzYxMzk0Mi8zNTMzMDM3MDctMGNhYjM5MjEtNjhiNC00YmY1LTg5YzYtODkxMTc1MDUyYTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAzNDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NDIwMGQ0NTEwYjlmY2NkNWQ5NjJkMzFlZjlkN2YxNGVlNDM2MDVmZWRhYWEyMGViY2U4ZTAyMzg0OTY5MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_1JUAufuu2lZcc5TqXQalbZ26n-SLVoUdxM2ScyHG0) 这个接口无法访问了，api/openapi/v1接口无法使用了，只能用api/v1接口，所以没法对接飞书了 @c121914yu
> > 
> > 
> > 这个1 月就没了，用 v1 不就行了～
> 
> 问题是这个v1和openapi/v1应该不兼容吧，不然之前为什么会有openapi/v1，直接换成api/v1 飞书那个对接应用根本就用不了

那就是这个项目有问题～ 为什么删除，因为一模一样了。

**Comment by lijihua2017** [comment]
> > 这个1 月就没了，用 v1 不就行了～

好的，可以用了，已解决，谢谢

**Comment by zanderjiang** [comment]
请问问题是怎么解决的呀，我也是私有化部署的版本，应用完成后想通过openai python sdk的接口去调用应用的api。用了提供的API根和生成的key，调用的时候会给openai.NotFoundError，后面跟了很长一段html。

**Comment by zanderjiang** [comment]
> 请问问题是怎么解决的呀，我也是私有化部署的版本，应用完成后想通过openai python sdk的接口去调用应用的api。用了提供的API根和生成的key，调用的时候会给openai.NotFoundError，后面跟了很长一段html。

已解决，api根后面忘加v1了......
