### ISSUE TITLE
mongo中的数据库fastgpt， 是否可以改名字？

### ISSUE THREAD

**Issue by leavegee** [labring/FastGPT#2205]
**你的版本**
4.8.8-fix

- [x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
我想复用同一个mongo集群，部署2个不同版本的fastgpt， 请问是否可以改数据库名？ 现在是fastgpt，请问如何换个名字？

**Comment by c121914yu** [comment]
修改链接串中的名字即可。
不过不建议这么搞，后续可能会引入多库。一般都是要部署两个数据库～

**Comment by leavegee** [comment]
> 修改链接串中的名字即可。 不过不建议这么搞，后续可能会引入多库。一般都是要部署两个数据库～

修改链接串不行，我才来问题呢。。。

**Comment by leavegee** [comment]
部署两个数据库成本太高了。  mongo数据库的名字能自己定义吗？
