### ISSUE TITLE
应用中问题优化按钮自动打开

### ISSUE THREAD

**Issue by YongQiangLau** [labring/FastGPT#2207]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.7升级4.8.8

**问题描述, 日志截图**
1.我已关闭问题优化且已点击发布按钮，但页面刷新之后会自动打开问题优化且会默认选择配置文件中的第一个模型
2.打开问题优化没有作用
![image](https://github.com/user-attachments/assets/73e45aa8-49d3-47cb-bad8-296176d098df)

**复现步骤**

**预期结果**
1.关闭问题优化之后再次进入或者刷新页面不会自动打开问题优化
2.打开问题优化之后在问答界面展示优化结果
**相关截图**
1.![image](https://github.com/user-attachments/assets/ce49b2b6-6683-4624-96f4-b0796b2900bd)
1.![image](https://github.com/user-attachments/assets/2bf4971b-3a6f-445d-86c5-13e100e6f395)
2.![image](https://github.com/user-attachments/assets/0b50af59-0b87-456d-b1a3-14429f217891)
2.![image](https://github.com/user-attachments/assets/685fb31e-67e3-45ff-a255-ade6718a7a32)

**Comment by wujunyi792** [comment]
同样的问题
