### ISSUE TITLE
搜索测试相关度

### ISSUE THREAD

**Issue by winnie1228** [labring/FastGPT#221]
您好！我本地部署之后在知识库里面做搜索测试，但是结果相似度为276.6083。在线使用版本的搜查结果相似度都是控制再1以内，请问是做了什么调整吗？
![image](https://github.com/labring/FastGPT/assets/78136057/cf57c077-182a-4558-be81-c11dcaec04e2)

**Comment by winnie1228** [comment]
打扰了，已解决。是我自己的embedding模型没有做归一化处理

**Comment by lichao4Java** [comment]
我也一样不是0-1， 怎么做归一化处理啊？

**Comment by boleyn** [comment]
调用模型的时候，给增加一个参数就好了text,normalize_embeddings，embeddings_model.encode(sentences=text,normalize_embeddings=True)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
When calling the model, just add a parameter text,normalize_embeddings, embeddings_model.encode(sentences=text,normalize_embeddings=True)
