### ISSUE TITLE
新对话点赞或者反馈后台看不到，刷新页面再点赞或者反馈才可以看到

### ISSUE THREAD

**Issue by ServiceYun** [labring/FastGPT#2215]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.8

**问题描述, 日志截图**
新对话对AI回复进行点赞或者反馈到后台，在对话日志里看不到，前端刷新页面点赞或者反馈消失，刷新页面之后再点赞或者反馈，在对话日志里面才可以看到

**复现步骤**
对新对话进行点赞或者反馈，在后台看对话日志看不到对应的点赞或者反馈，页面刷新点赞或者反馈消失

**预期结果**
外链新建对话可以进行后台可见的点赞或者反馈

**相关截图**

**Comment by ServiceYun** [comment]
更新复现情况，好像是因为新的对话的dataId和数据库里面的dataId没有对应，刷新页面才会更新对话的dataId和数据库一致，所以导致新对话无法点赞或者反馈

**Comment by ServiceYun** [comment]
问一下这个问题有进展吗

**Comment by c121914yu** [comment]
> 问一下这个问题有进展吗

https://github.com/labring/FastGPT/releases/tag/v4.8.9 这个版本已经修复了，忘记关联这里了，重复了好几个 issue
