### ISSUE TITLE
V4.8.8版本中，编辑插件时，使用HTTP工具，编辑 Params 或者 Body 后 没有保存

### ISSUE THREAD

**Issue by liyukui** [labring/FastGPT#2217]
**相关截图**
![微信图片_20240731090444](https://github.com/user-attachments/assets/20aae6aa-7d5d-4f4f-91f5-aba94b17807a)

**Comment by zhk0603** [comment]
我遇到。 请求参数这块都有问题，数据没有更新

**Comment by c121914yu** [comment]
重复 issue
