### ISSUE TITLE
4.8.8 bug有点多啊

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2220]
4.8.8
插件里测试的，http请求无法增加新的参数
默认只能一个参数，无法增加。非插件也是这样。

临时解决通过curl导入

而且debug信息错误，获取的参数不对,获取的是通过curl导入的测试参数名字，改了参数名字调试仍然去curl导入的参数名字。
![IMG_20240731_112242_edit_215276417810379](https://github.com/user-attachments/assets/dff34304-48a5-41b4-897c-ee3566a3e035)

bug2
也是插件里，第一个http请求可以填入参数和body，第二个http填入参数和body保存不了，切换body和params自动消失

其他bug #2206 
我这小白鼠当的。。。

**Comment by c121914yu** [comment]
重复 issuse

**Comment by sdytzjp** [comment]
> 重复 issuse

解决后下载哪个镜像

**Comment by sdytzjp** [comment]
镜像改为v4.8.8-fix2重新拉取吗
