### ISSUE TITLE
V4.8.1 升级 V4.8.8数据丢失

### ISSUE THREAD

**Issue by infoBrainSys** [labring/FastGPT#2223]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [4.8.8 ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
更新后执行脚本成功，但是仍然没有恢复应用和知识库
![image](https://github.com/user-attachments/assets/db1e1ee0-d3b1-4efc-92f3-fc302e2752d4)
数据都还在
![image](https://github.com/user-attachments/assets/058705d9-254f-41b3-899e-b86bc1be7250)

**复现步骤**
`docker compose pull`
`docker compose down && docker compose up -d`

**Comment by c121914yu** [comment]
自行检查是否遗漏升级，没其他办法。

**Comment by zaite** [comment]
土办法保险点就是，最好一个个版本升级

**Comment by c121914yu** [comment]
> 土办法保险点就是，最好一个个版本升级

是的。官网教程就是要一个个版本升级～不能直接跳。
