### ISSUE TITLE
无法通过3001端口访问oneapi

### ISSUE THREAD

**Issue by wemotech-ai** [labring/FastGPT#2225]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.7

**问题描述, 日志截图**
按照docker-compose的教程部署完成了，也按照教程sleep 10后重新启动oneapi了，oneapi的版本为阿里云的0.6.6。但全部完成之后通过IP:3001的方式无法进入oneapi的页面。
具体表现为：pending很久之后页面显示无法访问 报502

顺带一提：IP:3000的方式进入fastgpt是可以的。但是因为没有配置大模型的API Key 因此无法对话。

**复现步骤**
部署完成后访问IP:3001

**预期结果**
可以正常进入

**相关截图**

**Comment by wemotech-ai** [comment]
我尝试过绑定了域名，但仍然无法进入

**Comment by 704572066** [comment]
> 我尝试过绑定了域名，但仍然无法进入

运行 docker ps 看一下

**Comment by FinleyGe** [comment]
看到你好像是通过外网访问的。请检查一下你的防火墙是否开放了 3001 端口，或者是您的反向代理 Proxy 服务器是否配置了正确的链路。
