### ISSUE TITLE
为什么main分支下的私有化部署没有注册界面呢？

### ISSUE THREAD

**Issue by lwdnxu** [labring/FastGPT#2237]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
为什么main分支下的私有化部署没有注册界面呢？
![image](https://github.com/user-attachments/assets/30a7c1fe-c935-4bd3-8260-6bfb4f242395)

**相关截图**

**Comment by nextwa** [comment]
要打钱才有

**Comment by lwdnxu** [comment]
> 要打钱才有

就是商业版才有吧

**Comment by CloverZhou** [comment]
该爆米了
