### ISSUE TITLE
4.88版本通过api调用知识库查询接口报权限错误，4.87版本正常

### ISSUE THREAD

**Issue by wangmeng3486** [labring/FastGPT#2239]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.88

**问题描述, 日志截图**
<img width="1680" alt="企业微信截图_423382eb-7d29-4b48-96a2-720ff9995ade" src="https://github.com/user-attachments/assets/684e5414-e7bf-4e76-85d7-0101bd16c1fb">

**复现步骤**
升级4.88镜像调用 https://fastgpt.glodon.com/api/core/dataset/list  
{
    "parentId": "667e88d7526e4d42745d8fe8"
}
**预期结果**
返回知识库相信信息
**相关截图**

**Comment by handsome-owner** [comment]
+1
