### ISSUE TITLE
大佬，请问配置文件中的VectorModels支持添加其他模型吗？比如阿里云的通义文本向量text-embedding-v1

### ISSUE THREAD

**Issue by Timoshao** [labring/FastGPT#224]
![image](https://github.com/labring/FastGPT/assets/108260847/ac4a260b-e60f-4005-84f5-b0cc3985afc2)

**Comment by Timoshao** [comment]
看到同类型的问题了，大佬可以忽略

**Comment by c121914yu** [comment]
等待oneapi支持其他商用模型以及自定义向量模型，已提issue

**Comment by Timoshao** [comment]
> 等待oneapi支持其他商用模型以及自定义向量模型，已提issue

oneapi已经更新支持了

**Comment by c121914yu** [comment]
已支持，参考最新发行版说明：https://github.com/labring/FastGPT/releases/tag/v4.2.1

**Comment by Timoshao** [comment]
> 已支持，参考最新发行版说明：https://github.com/labring/FastGPT/releases/tag/v4.2.1

大佬 docker最新镜像有推送吗？
