### ISSUE TITLE
知识库工作流，搜索参数设置和引用提示词设置保存后，过一会再进入编辑时，已保存的配置参数被重置

### ISSUE THREAD

**Issue by kylewka** [labring/FastGPT#2243]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 私有部署版本, 具体版本号: v4.8.8-fix2

**问题描述, 日志截图**
知识库工作流，搜索参数设置和引用提示词设置保存后，过一会再进入编辑时，已保存的配置参数被重置

图1 是9:58编辑保存
图2 是10:15再次打开

![image](https://github.com/user-attachments/assets/126bc4c8-c0c6-4db7-8b39-8740dc79dceb)
![image](https://github.com/user-attachments/assets/e05b6138-966a-4fc2-b89a-842d7bc390f4)

**Comment by kylewka** [comment]
上个版本v4.8.6创建的应用相同操作，配置不丢失

**Comment by kylewka** [comment]
该应用是简易应用转为工作流的，选择了不保留原应用。
删除后重新创建工作流应用就正常了

**Comment by c121914yu** [comment]
同时开了两个标签？
