### ISSUE TITLE
输入问题后，提示：传入的用户问题为空。

### ISSUE THREAD

**Issue by wjhmiss** [labring/FastGPT#2246]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [v] 我已确认目前没有类似 issue
- [v] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [v] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [v] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
我测试了几个版本，V4.8, V4.8.7, V4.8.8-fix2 这三个版本我都出现如下错误。

**问题描述, 日志截图**
报错信息：
![1722579127490](https://github.com/user-attachments/assets/422660dc-198f-4f72-8e10-7af099855b71)

界面信息：
![1722578745174](https://github.com/user-attachments/assets/37525f23-c3b5-4006-a872-b659928f750c)

docker运行信息
![1722579193367](https://github.com/user-attachments/assets/4851f1a0-73e1-4ab3-9aa8-39ad7d1b7ddd)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
是不是因为挂了tool，创建一个简单应用试下

**Comment by c121914yu** [comment]
这截图和版本完全就对不上～

**Comment by wjhmiss** [comment]
发现问题了，@lijiajun1997 就是挂了tool造成的
我测试了几个版本，V4.8, V4.8.7, V4.8.8-fix2 这三个版本

**Comment by sdytzjp** [comment]
基本不用工具也经常碰到这个提示

**Comment by wilson323** [comment]
你们最后怎么解决的我也是这样
