### ISSUE TITLE
oneapi和mysql一直重启

### ISSUE THREAD

**Issue by Dhaizei** [labring/FastGPT#2248]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x  ] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/b57e6a82-b374-4220-9b7f-6cc32cab4d9c)
![image](https://github.com/user-attachments/assets/b08a66df-14f2-43a8-9583-8d1d33e04968)

**复现步骤**
使用的是wsl2+ubuntu，docker桌面版和linux内核。
**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
看 log

**Comment by c121914yu** [comment]
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/ad3b608a-e2fc-49ae-800a-de344584cb14">
