### ISSUE TITLE
【bug】4.8.8-fix2版本私有化版本，插件失效【在线等大佬】模型版本：qwen2:1.5b

### ISSUE THREAD

**Issue by arraycto** [labring/FastGPT#2260]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**模型版本**：qwen2:1.5b

**问题描述, 日志截图**
docker-compose版本部署
**复现步骤**
 无法识别插件和无法获取插件的效果

**预期结果**
![image](https://github.com/user-attachments/assets/99cb265b-9aac-455f-be07-0eef70fb5819)

插件生效，如图
线上版本正常

**相关截图**

私有版本

![image](https://github.com/user-attachments/assets/e78e8faa-f704-45dd-a2a2-53d4d86b2937)

![image](https://github.com/user-attachments/assets/667253eb-d5cc-4e66-8a6c-4f2cbe700c1a)

![image](https://github.com/user-attachments/assets/dd1e1647-7c5a-4531-918a-274e1cdcff9a)

**Comment by c121914yu** [comment]
看日志

**Comment by arraycto** [comment]
怀疑是版本的问题，请大佬指点，日志没看出异常是docker版本的

**Comment by c121914yu** [comment]
重复
