### ISSUE TITLE
开启工具调用中网页内容获取，貌似获取不了？

### ISSUE THREAD

**Issue by lddlww** [labring/FastGPT#2261]
![image](https://github.com/user-attachments/assets/1421499e-1295-4f53-a87c-f5fb0a83c947)

qwen2:7b是用ollama运行，但是fastgpt中开启工具调用获取网页内容，好像不生效

**Comment by zaite** [comment]
试试高级编辑，工具调用插件，，还有一种是问题分类

**Comment by c121914yu** [comment]
检查工具调用是否有报错，以及 toolChoice 字段是否和模型对应上。
