### ISSUE TITLE
Xinference module engine如何选择

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2262]
请问下Xinference module engine如何选择
里面包括llama.cop  Transformers以及vLLM等多个引擎，oneapi或fastgpt支持哪种引擎。

我实在是崩溃了，xinferemce费老劲下载了n个模型，结果只有一个好用，其他所有模型oneapi报错无可用渠道。

请问应该参照什么标准到xinference里下载模型

![mmexport1722771119317](https://github.com/user-attachments/assets/ff7da707-80ae-4c53-b0a8-98d7fb661a98)

**Comment by c121914yu** [comment]
哪种模式不影响接口，没渠道就是 model 没填对而已。
