### ISSUE TITLE
请问怎么在聊天框中上传文件，比如Excel

### ISSUE THREAD

**Issue by ak-2019** [labring/FastGPT#2265]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.7

**问题描述, 日志截图**
请问怎么在聊天框中上传文件，比如Excel，PDF之类的，没找到入口。
config.json中也没有看到相关配置，这个目前是还不支持吗？哪还有什么方法可以折中处理一下吗？
**复现步骤**

**预期结果**

**相关截图**

**Comment by zz620** [comment]
+1

**Comment by Essence9999** [comment]
4.8.9 is coming~
