### ISSUE TITLE
请问分享链接中的【新对话】如何隐藏掉

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2269]
4.8.8

由于启用了单点登陆以及session-ID的控制，如果用户点击分享链接中的【新对话】后session-id变化导致要求用户重新登陆，体验很差。我希望隐藏掉这个按键，如果用户需要发起新对话，只需要重新通过第三方进来即可，不需要再次进行身份验证。

请问呢在哪里隐藏掉这个功能，或者更改为文本提示内容
![image](https://github.com/user-attachments/assets/767a510b-8d4b-43ea-a2d3-a4144dc0d886)

**Comment by goodstudy12** [comment]
加参数&showHistory=0 ？

**Comment by sdytzjp** [comment]
你这个不行，历史会话需要保留，只是不要使用这个按键



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月7日(周三) 上午10:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 请问分享链接中的【新对话】如何隐藏掉 (Issue #2269)




 
加参数&amp;showHistory=0 ？

**Comment by c121914yu** [comment]
特殊需求自行二开

**Comment by sdytzjp** [comment]
我知道需要二开，能不能提示下在哪里处理这个，或者简单点只是隐藏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月7日(周三) 晚上7:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 请问分享链接中的【新对话】如何隐藏掉 (Issue #2269)




 
特殊需求自行二开
