### ISSUE TITLE
使用代码运行时提示错误：getaddrinfo ENOTFOUND fastgpt-ujpimvkv-sandbox.xxx.svc.cluster.local

### ISSUE THREAD

**Issue by swl632** [labring/FastGPT#2272]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: fastgpt:v4.8.8-fix2     部署在sealos上

**问题描述, 日志截图** 执行代码运行时，提示如下
{
  "message": "getaddrinfo ENOTFOUND fastgpt-ujpimvkv-sandbox.xxx.svc.cluster.local",
  "name": "Error",
  "method": "post",
  "code": "ENOTFOUND"
}

**复现步骤**

**预期结果**
执行js内容并返回

**相关截图**
如附件
![屏幕截图 2024-08-06 112837](https://github.com/user-attachments/assets/e83b84c2-cec5-47c8-b079-7ba35a3da6a8)
![屏幕截图 2024-08-06 112905](https://github.com/user-attachments/assets/2926f44b-5bb0-40fa-b078-9a573ced5860)

**Comment by c121914yu** [comment]
沙盒地址没填对

**Comment by swl632** [comment]
这个地址是在什么地方设置的？

**Comment by c121914yu** [comment]
> 这个地址是在什么地方设置的？

沙盒服务的地址

**Comment by swl632** [comment]
晚点找一下，谢谢

**Comment by swl632** [comment]
> > 这个地址是在什么地方设置的？
> 
> 沙盒服务的地址，端口 3000，直接复制 sealos 给的内网地址即可。

非常感谢，解决了，之前配置的地址确实有点问题。

**Comment by caijx168** [comment]
> > > 这个地址是在什么地方设置的？
> > 
> > 
> > 沙盒服务的地址，端口 3000，直接复制 sealos 给的内网地址即可。
> 
> 非常感谢，解决了，之前配置的地址确实有点问题。

请问这个沙盒地址在哪里设置呢？
