### ISSUE TITLE
v4.8.9-test 文档上传后 url不能作为变量输入到doc2x插件

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#2275]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9-test

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/0127bffa-21f0-4f13-ae0b-8a10b99bb128)

**复现步骤**

**预期结果**

**相关截图**

**Comment by Menghuan1918** [comment]
这儿的暂时只能是网址URL

在研究新的文件传输了

**Comment by c121914yu** [comment]
可以先用代码运行手动拼接

**Comment by Menghuan1918** [comment]
https://github.com/labring/FastGPT/pull/2284
已经提了PR啦
