### ISSUE TITLE
配置文件中，模型的参数如何设置

### ISSUE THREAD

**Issue by kid20210528** [labring/FastGPT#2279]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**相关截图**
![微信图片_20240806181011](https://github.com/user-attachments/assets/7fcf002c-9bcd-438e-a7de-eed069193cc8)
这些配置，是根据模型变化的，还是说统一不变的呢？如果是根据模型来变化的，怎么知道设置什么值是比较好的呀？例如我是用的是智谱的glm-4-0520，应该怎么去调整这些参数；或者说这些参数，对于问答的准确性是否有提高作用，怎么调整才能更准确

**Comment by sdytzjp** [comment]
同问

**Comment by c121914yu** [comment]
到模型提供商官网查看
