### ISSUE TITLE
为什么Xinference下载模型，很多都提示报错

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2286]
为什么Xinference下载模型，很多都提示报错
特别是images moduls 和 audio modules，几乎每个都报错

![image](https://github.com/user-attachments/assets/b24b7d0c-4fbd-43e5-9b1b-0f273c8f4ffa)
![image](https://github.com/user-attachments/assets/02faaf29-04c8-44ba-ae51-09152cff94e4)

**Comment by c121914yu** [comment]
去 xf 社区搜搜
