### ISSUE TITLE
Config.json中的大模型配置defaultConfig无效

### ISSUE THREAD

**Issue by Yshayu** [labring/FastGPT#2289]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [ ] 私有部署版本, 具体版本号: 4.8.6
想要开启千问的搜索功能，但是配置在config.json中的defaultConfig默认参数里面没有效果，也不知道哪里可以添加自定义参数？
**相关截图**
 {
      "model": "qwen-turbo",
      "name": "qwen-turbo",
      "avatar": "/imgs/model/qwen.svg",
      "maxContext": 16000,
      "maxResponse": 2000,
      "quoteMaxToken": 13000,
      "maxTemperature": 1.2,
      "charsPointsPrice": 0,
      "censor": false,
      "vision": false,
      "datasetProcess": true,
      "usedInClassify": true,
      "usedInExtractFields": true,
      "usedInToolCall": true,
      "usedInQueryExtension": true,
      "toolChoice": true,
      "functionCall": true,
      "customCQPrompt": "",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig":{
		  "enable_search":true
		  }
    },

**Comment by c121914yu** [comment]
oneapi 不支持自定义参数

**Comment by SDAIer** [comment]
> **例行检查**
> 
> * [ ]  我已确认目前没有类似 issue
> * [ ]  我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
> * [ ]  我使用了自己的 key，并确认我的 key 是可正常使用的
> * [ ]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本**
> 
> * [ ]  私有部署版本, 具体版本号: 4.8.6
>   想要开启千问的搜索功能，但是配置在config.json中的defaultConfig默认参数里面没有效果，也不知道哪里可以添加自定义参数？
>   **相关截图**
>   {
>   "model": "qwen-turbo",
>   "name": "qwen-turbo",
>   "avatar": "/imgs/model/qwen.svg",
>   "maxContext": 16000,
>   "maxResponse": 2000,
>   "quoteMaxToken": 13000,
>   "maxTemperature": 1.2,
>   "charsPointsPrice": 0,
>   "censor": false,
>   "vision": false,
>   "datasetProcess": true,
>   "usedInClassify": true,
>   "usedInExtractFields": true,
>   "usedInToolCall": true,
>   "usedInQueryExtension": true,
>   "toolChoice": true,
>   "functionCall": true,
>   "customCQPrompt": "",
>   "customExtractPrompt": "",
>   "defaultSystemChatPrompt": "",
>   "defaultConfig":{
>   "enable_search":true
>   }
>   },

请问解决了吗,如何在oneapi中增加参数
