### ISSUE TITLE
当我使用langchain-chatchat提供的llm接口时提示没有/v1/embeddings这个接口

### ISSUE THREAD

**Issue by kongccc** [labring/FastGPT#229]
请问一下 我应该如何对接两者

**Comment by c121914yu** [comment]
这是两个不同模型，没有直接关联。

**Comment by franksonet** [comment]
需要自己单独部署，可以参考这里：
https://github.com/bingyuxq/m3e-base_api/blob/master/m3e-base_api.py

**Comment by franksonet** [comment]
对，可以在openai_api.py增加一个embedding的路由
