### ISSUE TITLE
4.8.9-test知识库上传，报Api response error: undefined, 未配置商业版链接: core,dataset,tag,getAllTags

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#2296]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9-test

**问题描述, 日志截图**
正常知识库，上传word文件
![image](https://github.com/user-attachments/assets/7c4bab26-1c6f-491f-b939-5b367ee18828)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
alpha 已经隐藏
