### ISSUE TITLE
知识库应用如何放置HTTP请求的数据

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#2301]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.1

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by heart18z** [comment]
![image](https://github.com/user-attachments/assets/65b8afc5-474f-4a55-8fff-d4d11ea708c1)

**Comment by zaite** [comment]
试试知识库搜索引用合并插件看看

**Comment by heart18z** [comment]
感谢！将接口数据格式改为跟知识库搜索一样的格式即可使用合并插件

**Comment by sdytzjp** [comment]
> 感谢！将接口数据格式改为跟知识库搜索一样的格式即可使用合并插件

请教下，改成什么样的格式。按照下图格式自己拼接吗，这些ID和name怎么写？【】数组里是啥
![image](https://github.com/user-attachments/assets/3a5daa96-4327-4aeb-a1c0-71b665b010a2)

**Comment by c121914yu** [comment]
> > 感谢！将接口数据格式改为跟知识库搜索一样的格式即可使用合并插件
> 
> 请教下，改成什么样的格式。按照下图格式自己拼接吗，这些ID和name怎么写？【】数组里是啥
> ![image](https://github.com/user-attachments/assets/3a5daa96-4327-4aeb-a1c0-71b665b010a2)
> 

写不了，一般不允许这么做，因为这里填了 id，会默认去找数据库的文件。
你直接在 http 里或者通过代码运行，把提示词拼接好，传递给 Ai 即可。

**Comment by sdytzjp** [comment]
多谢大侠回复。
我将http获取的信息传入AI的提示词或者文档引用中，测试应该都可以，只是貌似不能很好的控制ai，例如只允许AI按照http传给他的信息进行回答，好像无法限制他参照他自己的知识来回答问题

**Comment by heart18z** [comment]
![image](https://github.com/user-attachments/assets/c4107ea9-bf3f-4d0f-bf87-16bc96d5125f)
我是通过代码运行模型，将接口里的数据转化为
![image](https://github.com/user-attachments/assets/069045b9-b812-4dad-a29f-237e67248c2a)
并入知识库引用中
