### ISSUE TITLE
代码运行模块总是502

### ISSUE THREAD

**Issue by Toketec** [labring/FastGPT#2302]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.9-alpha
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
<img width="850" alt="image" src="https://github.com/user-attachments/assets/7ab47234-b712-4e82-8943-63efed8003bf">

**复现步骤**
正常添加“代码运行”模块
删除执行内容和出入参
点击调试，执行空代码
502报错
**预期结果**

**相关截图**
<img width="555" alt="image" src="https://github.com/user-attachments/assets/edb2b18c-d1ee-4279-8d4e-6907d8b30a81">

**Comment by c121914yu** [comment]
看日志

**Comment by Toketec** [comment]
> 看日志

日志就这么多呀，已经贴在上面了

**Comment by zaite** [comment]
> **例行检查**
> 
> * [ ]  我已确认目前没有类似 issue
> * [ ]  我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
> * [ ]  我使用了自己的 key，并确认我的 key 是可正常使用的
> * [ ]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本** 4.8.9-alpha
> 
> * [ ]  公有云版本
> * [ ]  私有部署版本, 具体版本号:
> 
> **问题描述, 日志截图** <img alt="image" width="850" src="https://private-user-images.githubusercontent.com/44367138/356181374-7ab47234-b712-4e82-8943-63efed8003bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjY1ODUsIm5iZiI6MTcyMzE2NjI4NSwicGF0aCI6Ii80NDM2NzEzOC8zNTYxODEzNzQtN2FiNDcyMzQtYjcxMi00ZTgyLTg5NDMtNjNlZmVkODAwM2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxMTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDZmY2Y5NTg0NjhmYmYxODk3ZGEzYzZjOTRhNzY4OTM3MThkZTk2OWI3M2Q1ODVjMGNjYzRlM2VkNzJjMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QY_3KIrsjlT0yFu70ZoQQndRm5-sc2VO6zCWvGXd6fY">
> 
> **复现步骤** 正常添加“代码运行”模块 删除执行内容和出入参 点击调试，执行空代码 502报错 **预期结果**
> 
> **相关截图** <img alt="image" width="555" src="https://private-user-images.githubusercontent.com/44367138/356180809-edb2b18c-d1ee-4279-8d4e-6907d8b30a81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjY1ODUsIm5iZiI6MTcyMzE2NjI4NSwicGF0aCI6Ii80NDM2NzEzOC8zNTYxODA4MDktZWRiMmIxOGMtZDFlZS00Mjc5LThkNGUtNjkwN2Q4YjMwYTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxMTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYzkwMWQxNTgxYjczNGM0NmZiYjIyYmE1MDEyZDI2ODBlZDUwNWU5NmViYTU4YWQ4ZDhiNzdmNjRiNDI3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PfU28R5TPzj6qRmtH1Z65jwL3jcwg_tfrJMpuD4Xmwk">

不是，你函数里不return的吗，即使不需要返回结果，你也要返回个空啊

**Comment by c121914yu** [comment]
> 上面

沙盒的日志，代码是跑沙盒里，你要看沙盒服务的日志
