### ISSUE TITLE
500报错 知识库搜索 变量引用报错

### ISSUE THREAD

**Issue by Toketec** [labring/FastGPT#2305]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/e85dd91f-3c2d-4784-bb42-4914b258c01a">

**复现步骤**
1.http请求中，获得符合格式要求的知识库id对象
2.数据样例：如截图所示
3.在知识库搜索时报错

**预期结果**

**相关截图**
<img width="801" alt="image" src="https://github.com/user-attachments/assets/a77fd25f-4f7f-4a4a-a10c-53d2a581c806">
<img width="717" alt="image" src="https://github.com/user-attachments/assets/b442b55d-e347-4d19-afb4-138283e9d2df">

**Comment by c121914yu** [comment]
向量模型配置有问题

**Comment by yanyusanqian** [comment]
我也遇到了这个问题，是在索引时出现的，你解决了吗？
