### ISSUE TITLE
/api/core/dataset/data/update 修改单条数据接口返回500错误

### ISSUE THREAD

**Issue by yoohhwz** [labring/FastGPT#2308]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: fastgpt:4.8.4

**问题描述, 日志截图**
![d719fd2ef317df3edcaaae69ecf788a](https://github.com/user-attachments/assets/46f2b224-d96e-4f5c-bbda-0dc47de87fa5)

**复现步骤**
使用fastgpt4.8.4版本通过应用发布一个对外接口，使用接口操作修改单条知识库数据返回500错误

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/17c84395-fa4f-4863-8bbd-646dbf45139b)

**Comment by c121914yu** [comment]
id不存在

**Comment by sgwsgw** [comment]
好歹标注一下啊？这按照你API文档做的。谁知道你改字段名称了？？？

**Comment by soloctl** [comment]
请问这个问题什么结果了？我 4.8.3 也没能成功弄个更新
