### ISSUE TITLE
指定回复插件 在回复内容前默认会有一个 换行符，是有什么特殊处理吗？

### ISSUE THREAD

**Issue by dimsky** [labring/FastGPT#2309]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
指定回复插件 在回复内容前默认会有一个换行符，在使用 api  调用时，内容前会多一个换行符，与预期不符了，为什么要加这个换行符？
代码位置：
packages/service/core/workflow/dispatchV1/tools/answer.ts       line: 35
```javascript
  return {
    [NodeOutputKeyEnum.answerText]: `\n${formatText}`
  };

```
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
默认指定回复都换行

**Comment by dimsky** [comment]
> 默认指定回复都换行

建议去掉，或者将是否换行交给用户控制，不然在使用 api  调用的时候，返回结果前面多一个换行，需要做特殊处理。

**Comment by c121914yu** [comment]
特殊情况特殊处理，大部分情况需要/不影响，那就兼容大部分情况。

**Comment by dimsky** [comment]
> 特殊情况特殊处理，大部分情况需要/不影响，那就兼容大部分情况。

好的。

**Comment by mengdahuang** [comment]
@dimsky  @c121914yu 抱歉，请教一下。docker 环境的话如果我想修改这部分,应该怎么映射？我尝试进入到fastgpt容器里并没有这个文件。

我就是想实现指定回复默认不加\n

```
  return {
    [NodeOutputKeyEnum.answerText]: `\n${formatText}`
  };
  ```

> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue
> * [x]  我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
> * [x]  我使用了自己的 key，并确认我的 key 是可正常使用的
> * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本**
> 
> * [x]  公有云版本
> * [x]  私有部署版本, 具体版本号:
> 
> **问题描述, 日志截图** 指定回复插件 在回复内容前默认会有一个换行符，在使用 api 调用时，内容前会多一个换行符，与预期不符了，为什么要加这个换行符？ 代码位置： packages/service/core/workflow/dispatchV1/tools/answer.ts line: 35
> 
> ```js
>   return {
>     [NodeOutputKeyEnum.answerText]: `\n${formatText}`
>   };
> ```
> 
> **复现步骤**
> 
> **预期结果**
> 
> **相关截图**

**Comment by mengdahuang** [comment]
> 特殊情况特殊处理，大部分情况需要/不影响，那就兼容大部分情况。

您好，请问我参考本issue修改了 packages/service/core/workflow/dispatchV1/tools/answer.ts line: 35 这部分，把\n移除，然后重新通过actions生成docker镜像，这个换行仍然存在，是还有别的部分代码需要修改吗？

**Comment by dimsky** [comment]
> > 特殊情况特殊处理，大部分情况需要/不影响，那就兼容大部分情况。
> 
> @c121914yu c121914yu 您好，请问我参考本issue修改了 packages/service/core/workflow/dispatchV1/tools/answer.ts line: 35 这部分，把\n移除，然后重新通过actions生成docker镜像，这个换行仍然存在，是还有别的部分代码需要修改吗？

有两个  answer.ts  文件，其中一个文件中有两处添加了换行，可以仔细检查一下代码。
