### ISSUE TITLE
除了配置文件不知道怎么在后台添加新的账号

### ISSUE THREAD

**Issue by jiran214** [labring/FastGPT#231]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
+ [x] 我使用了自己的key，并确认我的 key 是可正常使用的
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
+ [ ] 公有云版本
+ [x] 私有部署版本

**问题描述**
除了配置文件不知道怎么在后台添加新的账号，请问可以简单告诉操作步骤吗，进入哪个容器执行什么命令？

**复现步骤**

**预期结果**

**相关截图**

**Comment by franksonet** [comment]
请问你找到本地部署添加额外的账号的方式了吗？

**Comment by henry-hub** [comment]
打开注册入口可以注册用户

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Open the registration portal to register users

**Comment by lordk911** [comment]
ghcr.io/c121914yu/fastgpt-admin:latest
This isn't open source, is it? A License verification problem occurs @c121914yu

**Comment by ivanberry** [comment]
@jiran214 如何通过配置来新增用户？

**Comment by sdytzjp** [comment]
> 打开注册入口可以注册用户

请问本地部署怎么打开注册入口注册用户？
