### ISSUE TITLE
系统语言改成英文后还有中文地方

### ISSUE THREAD

**Issue by guleng** [labring/FastGPT#2311]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.8

**问题描述, 日志截图**
我在个性化里把系统语言改成英文后页面上还有中文的存在
![image](https://github.com/user-attachments/assets/ec0db070-3749-4a96-bf94-3ed69ac56fc1)
![image](https://github.com/user-attachments/assets/5d131ddf-b425-4a6e-a031-4f6928c6b73b)

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/01c0de66-5573-4ace-97bc-949fb1cc9250)

**Comment by c121914yu** [comment]
翻译问题，请用最新版测试。
这个新版已经翻译了。

**Comment by guleng** [comment]
@c121914yu  我升级到4.8.9-alpha  最新版本后还有地方是有中文的
![image](https://github.com/user-attachments/assets/ac6e6bec-3b1f-47b7-a614-e1748be5bef4)

**Comment by c121914yu** [comment]
> @c121914yu  我升级到4.8.9-alpha  最新版本后还有地方是有中文的
> ![image](https://github.com/user-attachments/assets/ac6e6bec-3b1f-47b7-a614-e1748be5bef4)
> 

可以提 pr，官方没全部翻译。
