### ISSUE TITLE
访问OpenAPI反馈api.fastgpt.in: Name or service not known

### ISSUE THREAD

**Issue by devYren** [labring/FastGPT#2312]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/0a41e2d7-4bb3-41b2-8f88-0e242d248a9c)

**复现步骤**
偶发现象,无法100%复现
**预期结果**
请求正常
**相关截图**
![image](https://github.com/user-attachments/assets/b02cef79-15ac-4b20-966a-c8b69b59d813)

**Comment by c121914yu** [comment]
不稳定就用国内吧
https://fastgpt.cn
