### ISSUE TITLE
通过http获取知识传给AI知识库或文档如何控制引用提示词

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2313]
通过http获取知识传给AI
如果是传给AI作为知识库，发现AI没有引用这部分知识
![image](https://github.com/user-attachments/assets/9f7429ef-d657-475d-abfe-7281a20d8d46)

![image](https://github.com/user-attachments/assets/a3ba13e9-78d7-4398-bc0e-1a7aacaa0a1b)

如果是传给作为文档引用，AI可以参照这部分内容回答，但是没有办法通过引用提示词控制他的回答，例如只可以回答文档相关的问题。

![image](https://github.com/user-attachments/assets/0a9131a2-496e-4709-a429-206e3fedb741)

**Comment by c121914yu** [comment]
鼠标放到知识库引用上，会有数据类型提示。
