### ISSUE TITLE
V4.8.8 标注在对话日志里看不到了

### ISSUE THREAD

**Issue by gufei** [labring/FastGPT#2314]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 私有部署版本, 具体版本号:  V4.8.8

**问题描述, 日志截图**

在对话日志中，原来的版本可以看到标注，现在看不到了，我确定在分享的免登陆窗口中进行了标注

**复现步骤**

**预期结果**

能够出现标注

**相关截图**
![image](https://github.com/user-attachments/assets/24194288-1c91-4c15-a0fc-d51fc7af3b89)

**Comment by newfish-cmyk** [comment]
fixed #2330
