### ISSUE TITLE
4.8.9 对话日志和调试窗口的信息显示不全

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2315]
4.8.9-alpha

以前版本没有发现这种省略显示的情况，现在省略显示很不容易调试和排错
![image](https://github.com/user-attachments/assets/d29905d8-23c1-41be-8ad6-b77d479c4669)

![image](https://github.com/user-attachments/assets/a7c754b5-84ce-49e5-9c43-aa5c3a63fd0a)
![image](https://github.com/user-attachments/assets/84d72bdd-3d1c-488b-8223-ab2dfbd70a74)

![image](https://github.com/user-attachments/assets/2dbded25-20d1-494f-b218-b46734630a7d)

而且经常回复一半就截断了，模型设置的回复上限已经很大了
![image](https://github.com/user-attachments/assets/dde82f89-5903-409f-8cad-490fe61872c4)

**Comment by c121914yu** [comment]
已经调整到20000 字符
