### ISSUE TITLE
是否支持弹出一个免责声明让用户确认

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2317]
4.8.8

是否支持弹出一个免责声明或者提醒之类的功能，让用户【点击确认】后才可以使用。

尝试使用全局变量---下拉单选，来作为一个通知的功能，但是输出框长度、显示效果以及体验效果不太好
![image](https://github.com/user-attachments/assets/dcbea4e8-76c1-4399-b7ec-5d264d94b352)

**Comment by zaite** [comment]
首先你对话机制就没有用户体现的概念，免责确认没有意义，还不知在页面底部做个声明链接（这个你自己完全可以实现），然后变量不是你这么用的

**Comment by sdytzjp** [comment]
不一定是个免责声明，也可能是重要提醒需要确保用户已读。
我知道变量不是这么用的，我只是借助下拉单选变量的必选机制 让用户查看并确认一下。


至于页面底部设置个声明之类的做法技术上没问题，但是用户一般是不会去关注的


所以还是希望有一种方式能做到用户使用之前有个弹窗或确认的一步



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月10日(周六) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 是否支持弹出一个免责声明让用户确认 (Issue #2317)




 
首先你对话机制就没有用户体系的概念，免责确认没有意义，还不知在页面底部做个声明链接（这个你自己完全可以实现），然后变量不是你这么用的

**Comment by zaite** [comment]
> 不一定是个免责声明，也可能是重要提醒需要确保用户已读。 我知道变量不是这么用的，我只是借助下拉单选变量的必选机制 让用户查看并确认一下。 至于页面底部设置个声明之类的做法技术上没问题，但是用户一般是不会去关注的 所以还是希望有一种方式能做到用户使用之前有个弹窗或确认的一步
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月10日(周六) 上午10:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [labring/FastGPT] 是否支持弹出一个免责声明让用户确认 (Issue #2317) 首先你对话机制就没有用户体系的概念，免责确认没有意义，还不知在页面底部做个声明链接（这个你自己完全可以实现），然后变量不是你这么用的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你这种极个别需求还是自己二开下实现吧，或者你通过分享免登录嵌入三方系统，在三方系统上实现
