### ISSUE TITLE
chatgpt-on-wechat v1.7.0适配问题

### ISSUE THREAD

**Issue by monk-after-90s** [labring/FastGPT#2318]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.8

**问题描述, 日志截图**

1. fastgpt中的高级编排应用使用了工具调用，发布了apiKey通过chatgpt-on-wechat v1.7.0绑定微信，在微信里提问触发工具调用的问题比如“今天天气”，chatgpt-on-wechat报错。推测是fastgpt这边在进行工具调用时通过api响应的格式不兼容；
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/3ccfff52-fede-4665-8d6d-476c786d9921">
2. fastgpt中的高级编排应用使用了工具调用且选择的模型是不支持函数调用的时候，比如我用的自建qwen2 72B，发布了apiKey通过chatgpt-on-wechat v1.7.0绑定微信，在微信里提问不触发工具调用的问题比如“你好”，那么得到的回复会以“0: ”开头； 
<img width="492" alt="image" src="https://github.com/user-attachments/assets/cd3aff5f-6c30-4d31-a865-3f95bfe9b335">

 

**复现步骤**

**预期结果**

应用在进行工具调用时的api响应是具有兼容性的；
不支持函数调用的模型在进行工具调用的时候不会回复奇怪的字符“0: ”

**相关截图**

**Comment by c121914yu** [comment]
这不应该让 cow 适配么?

**Comment by c121914yu** [comment]
第二个问题修复：https://github.com/labring/FastGPT/pull/2378

**Comment by monk-after-90s** [comment]
> 第一个问题，应该让 cow 适配，这是 GPT 标准格式。

😀cow有自己的tool calling，估计不会支持外部tool calling

**Comment by Linnnkkk** [comment]
这个问题解决了吗？

**Comment by monk-after-90s** [comment]
用这个代理一下吧，我自己写的
https://github.com/monk-after-90s/fastgptApiProxy

**Comment by Linnnkkk** [comment]
> 用这个代理一下吧，我自己写的 https://github.com/monk-after-90s/fastgptApiProxy @Linnnkkk

多谢大佬，请教一下这个怎么用啊，我是docker环境运行的。

**Comment by monk-after-90s** [comment]
> > 用这个代理一下吧，我自己写的 https://github.com/monk-after-90s/fastgptApiProxy @Linnnkkk
> 
> 多谢大佬，请教一下这个怎么用啊，我是docker环境运行的。

就是用这个项目代理下Fastgpt的api接口，然后将代理接口填入cow

**Comment by Linnnkkk** [comment]
> > > 用这个代理一下吧，我自己写的 https://github.com/monk-after-90s/fastgptApiProxy @Linnnkkk
> > 
> > 
> > 多谢大佬，请教一下这个怎么用啊，我是docker环境运行的。
> 
> 就是用这个项目代理下Fastgpt的api接口，然后将代理接口填入cow

项目代理下Fastgpt的api接我知道，但是cow填的代理地址应该是什么？然后这个项目在cow的容器内部署吗？

**Comment by monk-after-90s** [comment]
> > > > 用这个代理一下吧，我自己写的 https://github.com/monk-after-90s/fastgptApiProxy @Linnnkkk
> > > 
> > > 
> > > 多谢大佬，请教一下这个怎么用啊，我是docker环境运行的。
> > 
> > 
> > 就是用这个项目代理下Fastgpt的api接口，然后将代理接口填入cow
> 
> 项目代理下Fastgpt的api接我知道，但是cow填的代理地址应该是什么？然后这个项目在cow的容器内部署吗？

好问题。那等我把这个代理做成cow的一个插件

**Comment by Linnnkkk** [comment]
> Author



> > > > > 用这个代理一下吧，我自己写的 https://github.com/monk-after-90s/fastgptApiProxy @Linnnkkk
> > > > 
> > > > 
> > > > 多谢大佬，请教一下这个怎么用啊，我是docker环境运行的。
> > > 
> > > 
> > > 就是用这个项目代理下Fastgpt的api接口，然后将代理接口填入cow
> > 
> > 
> > 项目代理下Fastgpt的api接我知道，但是cow填的代理地址应该是什么？然后这个项目在cow的容器内部署吗？
> 
> 好问题。那等我把这个代理做成cow的一个插件

抱歉哈，我对编程不太懂，只会照着教程做。如果大佬你能做成插件那就太好了，直接安装后配置一下，为了这事，我全网找了好几天了，没搞定，可愁死我了，希望大佬能尽快出插件版。
