### ISSUE TITLE
麻烦提供支持tools的模型

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2319]
麻烦提供一个支持tools的模型， 本地开源部署的或者国内公有云第三方在线调用都可，使用了很多模型都不支持tools。

国外在线调用的暂不考虑，翻墙有点麻烦

**Comment by zaite** [comment]
国内大厂的明显基本都支持啊，入文心、通义千问、智谱这些，你仔细看下他们的开发文档

**Comment by c121914yu** [comment]
curl 测试
