### ISSUE TITLE
M3E模型有点问题

### ISSUE THREAD

**Issue by mpuazxc2** [labring/FastGPT#232]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
+ [x] 我使用了自己的key，并确认我的 key 是可正常使用的
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
+ [ ] 公有云版本
+ [x] 私有部署版本

**问题描述**
M3E模型-导入大概5W跳数据就不行了，列队就丢了,列队自动消失了（导入了2遍16W，实际上只能导入5W左右）
Embedding-2导入几十万数据都行，输入比M3E快很多
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
实测，，导入没问题，就是慢。。 你得看看有没有报错日志。

**Comment by lizhuang** [comment]
m3e导入docx有遇到很慢的问题，后台也会报错body400，pdf导入整本书几千个队列都可以导入，就是处理比较慢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
m3e encounters a very slow problem when importing docx, and the background will also report an error body400. PDF can import thousands of queues for the entire book, but the processing is relatively slow.
