### ISSUE TITLE
知识库无法正常导出

### ISSUE THREAD

**Issue by chung1912** [labring/FastGPT#2321]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.9-alpha

**问题描述, 日志截图**
知识库导出，只能导出一个88b的cvs文件，里面的内容如下：
![image](https://github.com/user-attachments/assets/5b360647-02a0-4e53-b6a5-2311404abc76)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
暂时未复现，建议 debug

**Comment by chung1912** [comment]
> 暂时未复现，建议 debug

![image](https://github.com/user-attachments/assets/e6c05fab-b4dd-4628-a70c-ef9e901be578)
debug日志看不出来有什么问题

**Comment by c121914yu** [comment]
> > 暂时未复现，建议 debug
> 
> ![image](https://github.com/user-attachments/assets/e6c05fab-b4dd-4628-a70c-ef9e901be578)
> debug日志看不出来有什么问题

debug 源码，

**Comment by chung1912** [comment]
> > > 暂时未复现，建议 debug
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/38153111/358054642-e6c05fab-b4dd-4628-a70c-ef9e901be578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODM0OTgsIm5iZiI6MTcyMzY4MzE5OCwicGF0aCI6Ii8zODE1MzExMS8zNTgwNTQ2NDItZTZjMDVmYWItYjRkZC00NjI4LWE3MGMtZWY5ZTkwMWJlNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAwNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Y2E0MmNiNTJhMzU4MTRkNDhmNThkMzE1NzMwODYwNDFiZmQ0ZTc0YzI1N2I0NTdjYjk4MmEyY2FkM2I2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pF-bYEoW9hPsq7q7QAk8jQNgxu-zxTkLrprmCgXVLUA)
> > debug日志看不出来有什么问题
> 
> debug 源码，
这个在哪里看？docker部署只会看控制台日志输出

**Comment by c121914yu** [comment]
> > > > 暂时未复现，建议 debug
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/38153111/358054642-e6c05fab-b4dd-4628-a70c-ef9e901be578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODM0OTgsIm5iZiI6MTcyMzY4MzE5OCwicGF0aCI6Ii8zODE1MzExMS8zNTgwNTQ2NDItZTZjMDVmYWItYjRkZC00NjI4LWE3MGMtZWY5ZTkwMWJlNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAwNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Y2E0MmNiNTJhMzU4MTRkNDhmNThkMzE1NzMwODYwNDFiZmQ0ZTc0YzI1N2I0NTdjYjk4MmEyY2FkM2I2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pF-bYEoW9hPsq7q7QAk8jQNgxu-zxTkLrprmCgXVLUA)
> > > debug日志看不出来有什么问题
> > 
> > debug 源码，
> 这个在哪里看？docker部署只会看控制台日志输出
> 

需要开发环境，不是部署后的。

**Comment by chung1912** [comment]
> > > > > 暂时未复现，建议 debug
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/38153111/358054642-e6c05fab-b4dd-4628-a70c-ef9e901be578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODM0OTgsIm5iZiI6MTcyMzY4MzE5OCwicGF0aCI6Ii8zODE1MzExMS8zNTgwNTQ2NDItZTZjMDVmYWItYjRkZC00NjI4LWE3MGMtZWY5ZTkwMWJlNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAwNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Y2E0MmNiNTJhMzU4MTRkNDhmNThkMzE1NzMwODYwNDFiZmQ0ZTc0YzI1N2I0NTdjYjk4MmEyY2FkM2I2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pF-bYEoW9hPsq7q7QAk8jQNgxu-zxTkLrprmCgXVLUA)
> > > > debug日志看不出来有什么问题
> > > 
> > > 
> > > debug 源码，
> > > 这个在哪里看？docker部署只会看控制台日志输出
> 
> 需要开发环境，不是部署后的。

这个真不会弄啊

**Comment by c121914yu** [comment]
升级新版，支持 milvus 导出
