### ISSUE TITLE
如何迁移知识库的部分数据以及对应的向量数据

### ISSUE THREAD

**Issue by bobooboboo** [labring/FastGPT#2327]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.8-fix2

**问题描述, 日志截图**
假设我在A服务器上的FastGPT中有知识库K1、K2、K3，并且都已完成训练，数据向量化完成。向量库用的milvus
1.如果想将指定的知识库Kn（甚至是知识库Kn中的部分数据）以及对应的向量数据迁移到B服务器上的FastGPT中该如何操作。
2.如果A服务器的FastGPT知识库部分数据有修改或者删除该如何同步到B服务器的FastGPT

文档中提供的迁移方案为整体数据迁移，达不到预期效果
并且mongo中dataset_datas -> indexes -> dataId，按照文档的意思为向量的id，但是我通过可视化界面（attu）以及milvus-cli等相关工具捋不清mongo中的数据和向量库中的数据是如何关联的。
**复现步骤**

**预期结果**

**相关截图**

**Comment by zaite** [comment]
迁移好像只能通过导出导入在重新生成向量索引，部分同步这个你可以研究下知识库的api，统一通过第三方接口操作api实现，看看这样可不可行

**Comment by c121914yu** [comment]
dataset_datas 中的 indexes 中的 dataId 和向量库的 id 关联。
