### ISSUE TITLE
通过API训练知识库数据重复

### ISSUE THREAD

**Issue by Yshayu** [labring/FastGPT#2329]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8.6

**问题描述, 日志截图**
通过API批量添加的知识库数据，在创建训练订单的时候没有问题，但是索引后出现重复数据
这是我的API请求参数
![image](https://github.com/user-attachments/assets/d11b8e2d-0396-4feb-ab79-b340040168cd)

**相关截图**

![1](https://github.com/user-attachments/assets/ef3162cf-a5b2-477a-b0c3-bbb36d514195)

![image](https://github.com/user-attachments/assets/6411a665-e796-4788-8a96-81ddacea5c68)
![image](https://github.com/user-attachments/assets/0032b081-596d-4f04-a94b-cf7c63fd70a7)

**Comment by c121914yu** [comment]
QA 模式肯定有重复，模型自动生成，无法确定最终结果。

**Comment by Yshayu** [comment]
好的
