### ISSUE TITLE
ChatGLM2-6B的BUG

### ISSUE THREAD

**Issue by lichao4Java** [labring/FastGPT#233]
使用本地的ChatGLM2-6B模型，通过python openai_api.py 启动。

这是请求到chatglm2的内容， 里面有多层system结构，

![image](https://github.com/labring/FastGPT/assets/13230226/1e502ff2-8dab-425e-8f2d-052e3f07b217)

 但是chatglm2的openai_api.py里面只拼接了第一个system

![image](https://github.com/labring/FastGPT/assets/13230226/705df21e-3415-4312-85b4-8e3081751b88)

所以embedding出来的知识和prompt对chatGLM2-6B不生效，只把第一个system的prompt和用户问题做了拼接。

**Comment by gaord** [comment]
glm2应该不支持system消息的，所以做了拼接。看他的公开文档只支持user和assistant消息。

**Comment by c121914yu** [comment]
@stakeswky
