### ISSUE TITLE
调用链配置过程中，知识库检索引用上限太低只有3000，而普通应用可以支持1万多，功能不一致

### ISSUE THREAD

**Issue by Toketec** [labring/FastGPT#2336]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
<img width="490" alt="image" src="https://github.com/user-attachments/assets/8709549e-6263-4e4a-a7bc-1d7bc01a8375">
<img width="609" alt="image" src="https://github.com/user-attachments/assets/55e62dbd-97b0-481f-99b3-e2f6dcc1ad46">
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/156eb6d9-f774-4117-8447-85953d7cd6fb">

**Comment by c121914yu** [comment]
这个值取决你工作流中，上下文最大的一个模型。

**Comment by masktone** [comment]
> 这个值取决你工作流中，上下文最大的一个模型。

如果将知识库搜索作为插件使用，且不连接LLM时，最大就是3000，希望这个默认数值能够增加

**Comment by c121914yu** [comment]
已增到 16000
