### ISSUE TITLE
无法保存模板&无法联想变量

### ISSUE THREAD

**Issue by AuYuHui** [labring/FastGPT#2338]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9 

**问题描述, 日志截图**
点击保存后，无法保存，输入全局变量，回退后，没有保存
![image](https://github.com/user-attachments/assets/e4bac4a1-44d8-4d71-a9f7-973f85a0d619)
![image](https://github.com/user-attachments/assets/decc4481-f556-4401-a89d-842aa36bed19)
![image](https://github.com/user-attachments/assets/29fc36a1-2b81-4b56-9b89-a4a52866b8c9)

**复现步骤**
点击保存后，无法保存，输入全局变量，回退后，没有保存
无法联想变量， 之前的版本是可以的，
从4.8.3升级到 4.8.9
**预期结果**
可以点击保存

**相关截图**

**Comment by c121914yu** [comment]
没有任何连线的时候，无法保存

**Comment by AuYuHui** [comment]
> 没有任何连线的时候，无法保存

OK, 刚刚连线测试时可以保存的，但是 无法联想变量这个时怎么回事？

**Comment by c121914yu** [comment]
> > 没有任何连线的时候，无法保存
> 
> OK, 刚刚连线测试时可以保存的，但是 无法联想变量这个时怎么回事？

可以看 4.8.8 更新说明，变量已经改版了。

**Comment by c121914yu** [comment]
> > > > 没有任何连线的时候，无法保存
> > > 
> > > 
> > > OK, 刚刚连线测试时可以保存的，但是 无法联想变量这个时怎么回事？
> > 
> > 
> > 可以看 4.8.8 更新说明，变量已经改版了。
> 
> OK, 了解了 placeholder 应该修改一下，提示

好的，应该漏了。
