### ISSUE TITLE
前端输出到一半，显示卡住的问题

### ISSUE THREAD

**Issue by lhplol** [labring/FastGPT#234]
私有部署版本，当我在web聊天页面与fastgpt对话时，gpt输出到一半经常会卡住，但是当我刷新页面，或者切换对话再切回来时，会发现其实gpt回复是完整的，只是前端页面卡住了。可能与知识库有3000条数据，查询太慢，流式输出有时间上限有关？在分享链接页面对话也会卡住，但是刷新没有用。请问应该怎么处理？

**Comment by c121914yu** [comment]
我测试了线上，40万组的知识库，0相似度，取20组，使用gpt35 16k，要求生成3000字三体小说介绍，可以正常使用。
这可能和你的上游和网络有关系，取决你key,网关等是否稳定。

**Comment by lhplol** [comment]
> 

请问可以加入前端容错机制吗？让较慢的回复也能完整显示出来，谢谢

**Comment by kongccc** [comment]
这个问题我也遇到了 调试了很久也没见解决 不知道是什么原因导致的

**Comment by c121914yu** [comment]
> > 
> 
> 请问可以加入前端容错机制吗？让较慢的回复也能完整显示出来，因为gpt是完整生成的，我刷新就好了，感觉这个问题是可以在前端解决的。谢谢

那更加可能是你的网关超时没有设置足够长。

**Comment by lhplol** [comment]
> > > 
> > 
> > 
> > 请问可以加入前端容错机制吗？让较慢的回复也能完整显示出来，因为gpt是完整生成的，我刷新就好了，感觉这个问题是可以在前端解决的。谢谢
> 
> 那更加可能是你的网关超时没有设置足够长。

请问这个参数是在本地修改吗？还是需要中转端配合？如果是本地的话，是哪个路径下的哪个参数呢？感谢

**Comment by lhplol** [comment]
大概是从输入信息--回车，gpt显示第15秒会断掉，不知道是不是这个参数？
路径FastGPT-main\client\public\js\pdf.js
参数const EXECUTION_TIME = 15;
感觉又不像

**Comment by kongccc** [comment]
![image](https://github.com/labring/FastGPT/assets/46598392/d5e0aadf-2752-4884-9dd9-d9014ee426ba)
在此处添加一个gu过滤ping的判断即可

**Comment by lhplol** [comment]
> ![image](https://user-images.githubusercontent.com/46598392/265327369-d5e0aadf-2752-4884-9dd9-d9014ee426ba.png) 在此处添加一个gu过滤ping的判断即可

请问这个在docker容器内怎么改呢？这个文件也不是挂载到容器内的，fastgpt容器里没找到这个文件，find命令也没有权限。谢谢

**Comment by c121914yu** [comment]
现在统一设置成48000，8分钟。。超时的话，基本就是超时了。
glm问题已经解决，可以看最新commit.
