### ISSUE TITLE
基于工具调用的智能体API非流式请求得到非期望的字符串“0: ”

### ISSUE THREAD

**Issue by monk-after-90s** [labring/FastGPT#2340]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.8

**问题描述, 日志截图**

使用fastgpt制作一个智能体，并且其中使用了工具调用，且模型选择的是不支持函数调用的qwen2。发布这个智能体的API，使用Python的openai库进行非流式请求，响应内容会以“0: ”开始。
![image](https://github.com/user-attachments/assets/aa53d780-df1c-40af-a4e3-9539c617ecb4)

**复现步骤**

我使用的代码是
```python
import asyncio

from openai import AsyncOpenAI

client = AsyncOpenAI()


async def main():
    chat_completion = await client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": "Say this is a test",
            }
        ],
        model="Qwen/Qwen2-72B-Instruct-GPTQ-Int4",
    )
    print(chat_completion)


if __name__ == '__main__':
    asyncio.run(main())

```
使用环境变量OPENAI_BASE_URL、OPENAI_API_KEY传入BaseURL和apikey。

**预期结果**

响应结果不是以“0: ”开头，就正常文本。

**相关截图**

**Comment by c121914yu** [comment]
忘记关闭。
4.8.9 解决了。非 stream 模式下，prompt 模式工具调用问题。
