### ISSUE TITLE
插件无效，有图有真相，求教大佬

### ISSUE THREAD

**Issue by arraycto** [labring/FastGPT#2345]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
插件失效，请大佬指点。v4.8.9版本，docker版本。
**问题描述, 日志截图**
![img_v3_02dm_32eb5dc5-5097-4916-9738-9bd5e79c611g](https://github.com/user-attachments/assets/ef08ddad-0795-4314-9cf4-3ec3929bbee8)
**复现步骤**

新建简易应用即可复现。

![img_v3_02dm_0d618c79-ffb2-4276-9d10-ca4820510b2g](https://github.com/user-attachments/assets/c7ba59bf-9874-4a9e-bbb1-2eb90e387463)

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
<img width="1481" alt="image" src="https://github.com/user-attachments/assets/7b8d0419-d554-40b2-8f1d-6dcf44dc75e0">
检查模型配置是否支持 tool，不支持就别设置 tool 模式

**Comment by arraycto** [comment]
采用qwen2:1.5b的模型，配置如下设置了支持，是不是模型本身的原因或者私有化不支持插件的使用？@c121914yu 

配置
`
{
                "model": "qwen2:1.5b",
                "name": "qwen2:1.5b",
                "maxContext": 32000,
                "avatar": "/imgs/model/qwen.svg",
                "maxResponse": 5000,
                "quoteMaxToken": 5000,
                "maxTemperature": 1.2,
                "charsPointsPrice": 0,
                "censor": false,
                "vision": true,
                "datasetProcess": true,
                "usedInClassify": true,
                "usedInExtractFields": true,
                "usedInToolCall": true,
                "usedInQueryExtension": true,
                "toolChoice": true,
                "functionCall": true,
                "customCQPrompt": "",
                "customExtractPrompt": "",
                "defaultSystemChatPrompt": "",
                "defaultConfig": {}
        },
        {
                "model": "glm4:9b",
                "name": "glm4:9b",
                "maxContext": 32000,
                "avatar": "/imgs/model/glm4.svg",
                "maxResponse": 50000,
                "quoteMaxToken": 50000,
                "maxTemperature": 1.2,
                "charsPointsPrice": 0,
                "censor": true,
                "vision": true,
                "datasetProcess": true,
                "usedInClassify": true,
                "usedInExtractFields": true,
                "usedInToolCall": true,
                "usedInQueryExtension": true,
                "toolChoice": true,
                "functionCall": true,
                "customCQPrompt": "",
                "customExtractPrompt": "",
                "defaultSystemChatPrompt": "",
                "defaultConfig": {}
        },

`
