### ISSUE TITLE
上传图片，不带文字就报错

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2346]
使用多模态模型，如果只上传图片，没有输入文字，模型就提示输入为空。这个体验不好，有没有思路解决

**Comment by lijiajun1997** [comment]
加一个判断 问题为空 接入文本加工接到模型里 文本加工里写 请分析图片内容

**Comment by sdytzjp** [comment]
多谢。
图片和文件如何区分。
对于图片，可以用文本拼接——描述图片
对于文件需要用文档解析工具



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 上传图片，不带文字就报错 (Issue #2346)




 
加一个判断 问题为空 接入文本加工接到模型里 文本加工里写 请分析图片内容

**Comment by c121914yu** [comment]
> 多谢。
> 图片和文件如何区分。
> 对于图片，可以用文本拼接——描述图片
> 对于文件需要用文档解析工具
> 而且希望 文件和图片用不同是模型响应
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年8月12日(周一) 晚上9:23
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [labring/FastGPT] 上传图片，不带文字就报错 (Issue #2346)
> 
> 
> 
> 
>  
> 加一个判断 问题为空 接入文本加工接到模型里 文本加工里写 请分析图片内容
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

文件名后缀
