### ISSUE TITLE
4.8.9根据图片 文字 文件来选择不同的模型处理

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2347]
4.8.9可以识别问题中的文件链接
但是无法区分文件和图片

如果希望能够针对图片 文字 文件，由三个不同的模型来响应，该如何处理

**Comment by c121914yu** [comment]
文件后缀

**Comment by sdytzjp** [comment]
编排里哪个模块能识别文件后缀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 上午8:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 4.8.9根据图片 文字 文件来选择不同的模型处理 (Issue #2347)




 
文件后缀

**Comment by sdytzjp** [comment]
> 文件后缀

用if判断文件链接是否包括txt或者jpg不生效，一直走的else
@c121914yu 

![image](https://github.com/user-attachments/assets/f4f3b884-a8a0-4414-9fea-e89b1202e9a5)
