### ISSUE TITLE
复制功能，在model中不生效

### ISSUE THREAD

**Issue by star-devil** [labring/FastGPT#235]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
+ [ ] 我使用了自己的key，并确认我的 key 是可正常使用的
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
+ [ ] 公有云版本
+ [ 4.2.1 ] 私有部署版本

**问题描述**
在非安全域网址下复制APIkey，复制不生效
**复现步骤**
本地服务地址：
![image](https://github.com/labring/FastGPT/assets/46698905/834d9b66-d9d3-4438-80cb-953bdf7a51de)
复制apikey,，提示复制成功，实际没有值被复制
![image](https://github.com/labring/FastGPT/assets/46698905/9e34bc90-4d5d-4e31-8cb4-572ce07196d5)

**预期结果**
在model中能够使用 document.execCommand('copy');这个方法复制
**相关截图**
![image](https://github.com/labring/FastGPT/assets/46698905/959a5896-3b89-4696-8306-39bbf761d14b)

**Comment by c121914yu** [comment]
可能是非ssl，被浏览器禁止了
