### ISSUE TITLE
4.8.9上传图片或文件 多轮对话只认识第一次的附件内容

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2350]
第一次上传图片或文件，可以正常识别

以后再上传新的图片和附件，ai描述的仍然识别的是第一次上传的附件内容

已经更换过不同模型测试

**Comment by lijiajun1997** [comment]
为啥不能新建一个对话呢？

**Comment by sdytzjp** [comment]
不是要新建对话的问题
即便是先建一个对话，也是无法识别第二次以后发送的附件，ai一直描述第一次的附件内容



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 晚上11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 4.8.9上传图片或文件 多轮对话只认识第一次的附件内容 (Issue #2350)




 
为啥不能新建一个对话呢？

**Comment by c121914yu** [comment]
![img_v3_02dn_fc356168-aacc-40d6-9dfc-4e43b56fa06g](https://github.com/user-attachments/assets/bf0935fb-6c65-410b-86e9-f4cbcc3bb63c)
自行检查
