### ISSUE TITLE
4.8.9 长网页源码文本报错

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#2351]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**

**复现步骤**
1.通过get请求获取一个页面代码的信息
2.让LLM加工这些信息
3.LLM无法处理报错
**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/572ab507-a2c6-4e26-9c59-cef8515ec99e)
![image](https://github.com/user-attachments/assets/c238d2cc-a23d-4809-9146-f1b262ff5272)

**Comment by lijiajun1997** [comment]
是不是api返回的报错？

**Comment by c121914yu** [comment]
暂时可以通过关闭图片识别解决
