### ISSUE TITLE
对话接口的flowResponses（节点完整响应）输出不全，缺少调用插件的内部详细步骤的输出

### ISSUE THREAD

**Issue by wangtl** [labring/FastGPT#2361]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

**应用场景**
在调用对话接口时，我需要知道应用详细的执行步骤，以便定位问题，目前各个节点的步骤是有输出的，但是涉及到插件的内部步骤没有，只有插件的最终结果输出，不方便排查插件内容的问题
**相关示例**

**Comment by c121914yu** [comment]
单独测试插件，保证插件运行正确。

**Comment by c121914yu** [comment]
4.8.11 支持嵌套显示。
