### ISSUE TITLE
关闭知识库中文件夹的“启用”并不能关闭文件夹里面的数据集

### ISSUE THREAD

**Issue by chung1912** [labring/FastGPT#2366]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.9

**问题描述,**
关闭知识库中文件夹的“启用”并不能关闭文件夹里面的数据集，里面的数据集还是处于“启用”状态，调用知识库的时候还是会搜索里面的知识

**预期结果**
希望关闭文件夹的“启用”后，该文件夹里面的所有数据集都会关闭“启用”

**Comment by c121914yu** [comment]
已增加
