### ISSUE TITLE
fastgpt工作流当中，在工作流当中使用了行情API接口数据，如何在AI回答流程中，返回AI汇总的回答，和接口的完整响应数据？

### ISSUE THREAD

**Issue by caijx168** [labring/FastGPT#2368]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 
V4.8.7
**问题描述, 日志截图**
fastgpt工作流当中，在工作流当中调用http使用了行情API接口数据，如何在AI回答流程中，返回AI汇总的回答，和接口的完整响应数据？

**复现步骤**

**预期结果**
想要的一个效果就是，AI结合了HTTP请求获取了结果并进行汇总输出的同时，想要 包含一个event或者是什么变量包裹了接口的响应完整数据，前端可以根据这些数据，自己渲染，或者跳转之类的，但是这个数据不算在AI回答里面。原本是想要用指定回复，但是fastAnswer: 指定回复返回给客户端的文本（最终会算作回答），Ai会输出来，但是我想要的是这些数据，只给前端调用，而不做展示
**相关截图**

**Comment by c121914yu** [comment]
二开，增加事件
