### ISSUE TITLE
高级编排界面切换插件选项时报错Cast to ObjectId failed for value "community-duckduckgo" (type string) at path "_id" for model "apps"

### ISSUE THREAD

**Issue by iworklee** [labring/FastGPT#2369]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ √] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
Cast to ObjectId failed for value "community-duckduckgo" (type string) at path "_id" for model "apps"
**复现步骤**
1、打开高级编排
2、选择系统插件，点击duckduckgo服务，此时展示duckduckgo服务列表
3、切换到团队插件，报错Cast to ObjectId failed for value "community-duckduckgo" (type string) at path "_id" for model "apps"
**预期结果**
不报错
**相关截图**
![image](https://github.com/user-attachments/assets/aad1338c-135b-48b0-992c-67e086f32985)

**Comment by c121914yu** [comment]
fix
