### ISSUE TITLE
关于分享链接中提供原文档在线阅读或原文下载功能

### ISSUE THREAD

**Issue by Le-Onde** [labring/FastGPT#2370]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在分享链接中设置引用内容可进行原文档在线阅读或原文下载开关功能，请问大佬近期计划会在4.8.10版本进行更新吗，我看这个功能也挺多人有这个需求的
**应用场景**

**相关示例**
#1951

**Comment by William-715** [comment]
强烈建议增加该功能
