### ISSUE TITLE
上传的文件通过“文档解析“工具无法解析结果

### ISSUE THREAD

**Issue by zkstudio** [labring/FastGPT#2372]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.9

**问题描述, 日志截图**
上传文件启用后，上传txt或者pdf文件通过文档解析后，不能解析具体文本，解析结果为“<Content>Only support .txt, .md, .html, .pdf, .docx, pptx, .csv, .xlsx</Content>”。

**复现步骤**
1. 开启文档上传文件，通过调试发现上传后地址为：
[
"http://x.x.x.x:3000/api/common/file/read?filename=1.txt&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidWNrZXROYW1lIjoiY2hhdCIsInRlYW1JZCI6IjY2NjdmYmQwNTViYWEzZWVkZGQ5ZjQzYyIsInRtYklkIjoiNjY2N2ZiZDA1NWJhYTNlZWRkZDlmNDNlIiwiZmlsZUlkIjoiNjZiYWZhOTM4ODkwOTMwYTQyNjFlNTNmIiwiZXhwIjoxNzI0MTM0Njc1LCJpYXQiOjE3MjM1Mjk4NzV9.1Dxgbjc5I8xOn4W02rzn3V9XPsIeCeTToQ7c691A8OU"
]

2. 通过文档解析，结果为：
File:
<Content>
Only support .txt, .md, .html, .pdf, .docx, pptx, .csv, .xlsx
</Content>

另，将地址换成静态文件地址，如：
[
 "http://x.x.x.x/1.txt"
]
可正常解析。
应该是上传后的文件后续带着token导致误判文件类型导致

**预期结果**
能够正常解析文本

**相关截图**
![image](https://github.com/user-attachments/assets/bf4ffe8c-4ba0-447f-bcec-cb95c9ab45c7)

**Comment by c121914yu** [comment]
未复现～

**Comment by zkstudio** [comment]
日志如下
Warning: Cannot polyfill `DOMMatrix`, rendering may be broken.
Warning: Cannot polyfill `Path2D`, rendering may be broken.
Only support .txt, .md, .html, .pdf, .docx, pptx, .csv, .xlsx
error => Only support .txt, .md, .html, .pdf, .docx, pptx, .csv, .xlsx

**Comment by zkstudio** [comment]
> 未复现～ debug 看看日志

发现是以下代码导致的，去掉前面部分，就访问不了了。
为什么要去掉呢？谢谢！ @c121914yu 

//  Remove the origin(Make intranet requests directly)
        if (requestOrigin && url.startsWith(requestOrigin)) {
          url = url.replace(requestOrigin, '');
        }

**Comment by c121914yu** [comment]
> > 未复现～ debug 看看日志
> 
> 发现是以下代码导致的，去掉前面部分，就访问不了了。 为什么要去掉呢？谢谢！ @c121914yu
> 
> // Remove the origin(Make intranet requests directly) if (requestOrigin && url.startsWith(requestOrigin)) { url = url.replace(requestOrigin, ''); }

因为需要从服务器里的 origin 和客户端不是同一个，直接用 /api/xx文件 路径去请求文件接口，会自动补上服务端的 origin。

**Comment by JTDeve** [comment]
所以这个问题到底怎么解决呢

**Comment by JTDeve** [comment]
> > 未复现～ debug 看看日志
> 
> 发现是以下代码导致的，去掉前面部分，就访问不了了。 为什么要去掉呢？谢谢！ @c121914yu
> 
> // Remove the origin(Make intranet requests directly) if (requestOrigin && url.startsWith(requestOrigin)) { url = url.replace(requestOrigin, ''); }



> **例行检查**
> 
>     * [x]  我已确认目前没有类似 issue
> 
>     * [x]  我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
> 
>     * [x]  我使用了自己的 key，并确认我的 key 是可正常使用的
> 
>     * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> 
>     * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> 
> **你的版本**
> 
>     * [ ]  公有云版本
> 
>     * [x]  私有部署版本, 具体版本号: v4.8.9
> 
> 
> **问题描述, 日志截图** 上传文件启用后，上传txt或者pdf文件通过文档解析后，不能解析具体文本，解析结果为“Only support .txt, .md, .html, .pdf, .docx, pptx, .csv, .xlsx”。
> 
> **复现步骤**
> 
>     1. 开启文档上传文件，通过调试发现上传后地址为：
>        [
>        "http://x.x.x.x:3000/api/common/file/read?filename=1.txt&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidWNrZXROYW1lIjoiY2hhdCIsInRlYW1JZCI6IjY2NjdmYmQwNTViYWEzZWVkZGQ5ZjQzYyIsInRtYklkIjoiNjY2N2ZiZDA1NWJhYTNlZWRkZDlmNDNlIiwiZmlsZUlkIjoiNjZiYWZhOTM4ODkwOTMwYTQyNjFlNTNmIiwiZXhwIjoxNzI0MTM0Njc1LCJpYXQiOjE3MjM1Mjk4NzV9.1Dxgbjc5I8xOn4W02rzn3V9XPsIeCeTToQ7c691A8OU"
>        ]
> 
>     2. 通过文档解析，结果为：
>        File:
> 
> 
> Only support .txt, .md, .html, .pdf, .docx, pptx, .csv, .xlsx
> 
> 另，将地址换成静态文件地址，如： [ "http://x.x.x.x/1.txt" ] 可正常解析。 应该是上传后的文件后续带着token导致误判文件类型导致
> 
> **预期结果** 能够正常解析文本
> 
> **相关截图** ![image](https://private-user-images.githubusercontent.com/7109942/357360703-bf4ffe8c-4ba0-447f-bcec-cb95c9ab45c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMTEyODksIm5iZiI6MTczNzAxMDk4OSwicGF0aCI6Ii83MTA5OTQyLzM1NzM2MDcwMy1iZjRmZmU4Yy00YmEwLTQ0N2YtYmNlYy1jYjk1YzlhYjQ1YzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTZUMDcwMzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTNlYWQ1OWRlZTVhZTdmMGY0NjRhNTIzODgxOGEzMWM1YTk4MWZjNzU3MWJjOTY5YWE5ODhhOWU2YTgzZDIyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nm0dGo8mLCQW5oFU6YrFJfwThUH7_uKEN3BG1ZVMSBI)

请问您解决了吗，我也遇到这个问题

**Comment by SimonSkywalke** [comment]
可能是配置文件出了问题。我的类似问题是docker-compose.yml中的FE_DOMAIN配置失败导致的。将其对应的内容修改成: [http://fastgpt本地访问地址](http://xn--fastgpt-x68la4n760phz5flx1a/) 即可解决(不要以/结尾) @JTDeve @zkstudio @
