### ISSUE TITLE
流程编排中，分支流程可以并行。

### ISSUE THREAD

**Issue by yjzzcao** [labring/FastGPT#2373]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/f0838513-930c-4913-9d63-33a47fd050b8">

我测试发现，在分支流程中依旧是按照特定层级顺序执行。

有没有可能实现并行操作，已实现批任务功能。

比如：

我先生成 10 个子问题：

```
[
"510300的管理人是谁",
"510300的基金经理是谁",
"510300的成立日期是什么时候",
"510300跟踪的指数是什么",
"510300的规模是多少",
"510300跟踪指数的长期年化收益是多少",
"510300跟踪指数的最大回撤是多少",
"510300跟踪指数的当前PE分位值是多少",
"510300跟踪指数的当前PB分位值是多少",
"510300跟踪指数的PE时间序列值是多少",
"510300跟踪指数的PB时间序列值是多少",
"510300近期的资金流入情况如何",
"与510300同类的ETF近期的资金流入情况如何"
]
```

希望并行获取这 10 个问题的答案。依次获取答案效率太慢。

待 10 个答案全部返回后进行答案总结。

**Comment by yjzzcao** [comment]
- 6 这个节点其实是调用当前自己这个应用。
- 我的 2-5 这一条链路，其实就是针对单一问题检索+回答，大概一个问题需要20s 的时间。
- 如果是串行输出，一个 10 个子问题的任务 + 最终的总结，输出时间需要接近 4 分钟。体验不是很好
- 最终效果我想把我所有的子问题清单，同时进行调用，这样就可以控制在 1 分钟内初结果。

有点类似扣子的批处理。

**Comment by lijiajun1997** [comment]
> 123 是并行的，456 也是并行的。

有没与办法实现12345并行生成，但是先后输出，比如先流式输出1，然后1完成后，把2已经生成部分快速输出然后继续流式，或者2全部完成了就一次性快速输出，这样？

**Comment by c121914yu** [comment]
> - 6 这个节点其实是调用当前自己这个应用。
> - 我的 2-5 这一条链路，其实就是针对单一问题检索+回答，大概一个问题需要20s 的时间。
> - 如果是串行输出，一个 10 个子问题的任务 + 最终的总结，输出时间需要接近 4 分钟。体验不是很好
> - 最终效果我想把我所有的子问题清单，同时进行调用，这样就可以控制在 1 分钟内初结果。
> 
> 有点类似扣子的批处理。

我理解下，同时进行 10 个子任务流程这个需求我理解了。
🤔你现在是怎么实现 10 个子问题，串行运行的？

**Comment by c121914yu** [comment]
> > 123 是并行的，456 也是并行的。
> 
> 有没与办法实现12345并行生成，但是先后输出，比如先流式输出1，然后1完成后，把2已经生成部分快速输出然后继续流式，或者2全部完成了就一次性快速输出，这样？

上次忘了，，记下。

**Comment by yjzzcao** [comment]
通过```应用调用```工具，调用自己就可以做到循环。
<img width="549" alt="image" src="https://github.com/user-attachments/assets/d7020903-1bee-4a92-9f04-eff93ef65320">

**Comment by c121914yu** [comment]
4.8.10 已支持完全并行
