### ISSUE TITLE
4.8.9版本更新后初次进入对话标题为“chat:new_chat”，而不是应用标题

### ISSUE THREAD

**Issue by lzh222333** [labring/FastGPT#2377]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/e0528568-6606-4981-abbf-44255685f057)

**复现步骤**

**预期结果**
显示应用标题，而不是等待第一轮对话结束后才更新标题
**相关截图**

**Comment by xiebin2014** [comment]
![image](https://github.com/user-attachments/assets/853d6a1a-1bd7-4b90-a743-f7b27094432a)
知识库这里也有问题，不是稳定复现

**Comment by c121914yu** [comment]
> ![image](https://private-user-images.githubusercontent.com/6446527/358106694-853d6a1a-1bd7-4b90-a743-f7b27094432a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDg4MjUsIm5iZiI6MTcyMzcwODUyNSwicGF0aCI6Ii82NDQ2NTI3LzM1ODEwNjY5NC04NTNkNmExYS0xYmQ3LTRiOTAtYTc0My1mN2IyNzA5NDQzMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMDc1NTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI2MDQ2MzVjOTBmY2JkYWQ3OTNkYTYzYmUxNDYxMWE2NzMyZDBmMzg3NDBiZWM2ZmQ3OGRlYzEzN2ZiZTczZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v0moGQSWmi4GUQup3e_HdHCLb6ONxLmtrqaD2bglirQ) 知识库这里也有问题，不是稳定复现

一起修复了
