### ISSUE TITLE
4.8.9版本IOS移动端语音输入报异常，PC端正常使用。

### ISSUE THREAD

**Issue by jessechan** [labring/FastGPT#2379]
![ppppp_20240814095111](https://github.com/user-attachments/assets/44b6e72a-446b-4f8e-af30-35ea7b326f3f)

在手机微信端或QQ浏览器进入应用免登录分享链接，语音输入报如上异常，语音权限已检查都正常。

**Comment by c121914yu** [comment]
之前有 issue 了，目前IOS 不支持语音输入。

**Comment by leavegee** [comment]
> 之前有 issue 了，目前IOS 不支持语音输入。

啥时候能支持啊？ 要不就把ios操作系统的屏蔽掉呢。
