### ISSUE TITLE
【建议】可以支持多个QAModel，在生成时选择

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#238]
**例行检查**

[//]: # '方框内删除已有的空格，填 x 号'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
不计划了，已经想好，选个最合适的就行了。
