### ISSUE TITLE
为什么不直接使用 OpenAI 的 file 接口

### ISSUE THREAD

**Issue by chengxiaowan** [labring/FastGPT#2380]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x ] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  4.8.9

**问题描述, 日志截图**
在升级到 4.8.9 版本后，我注意到文件解析功能是通过工具调用，由文档解析模块解析全文字符并将其传递给大模型。我想了解为什么不直接使用 OpenAI 的 SDK 提供的 file 接口上传文件，这样做是否有某些技术或安全方面的顾虑？

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
其他模型用不了

**Comment by chengxiaowan** [comment]
> 其他模型用不了

感谢回复!

我理解您选择使用当前方法是为了兼容不同的大模型，特别是那些不支持 file 接口的模型。这确实是一个非常合理的考量。

不过，我注意到市面上有一些大模型是支持 file 接口的，可能在某些情况下（例如文件较大或对文件内容的精确度要求较高时），直接使用这些接口会更加高效。因此，我想建议在未来的版本中，是否可以考虑为那些支持 file 接口的模型增加一个可选项，让用户可以自行选择是使用工具解析还是直接上传文件？

这样既能保持现有的兼容性，又能为有需求的用户提供更多选择。无论如何，我非常感谢您为这个项目所做的工作，期待未来的更新。

**Comment by c121914yu** [comment]
这种考虑单独做插件吧，系统级组件，，以通用为准
