### ISSUE TITLE
隐藏工具调用后的回答上方工具内容

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#2381]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
开启工具调用后，分享出去的链接问答，上方都会带上对应工具的具体内同，希望可以隐藏
隐藏工具调用后的回答上方工具内容
**应用场景**
![image](https://github.com/user-attachments/assets/188a96cf-e946-43de-bf45-4f66e1877565)

**相关示例**

**Comment by bdugsj** [comment]
同求可以隐藏知识库调用的选项

**Comment by Patrickill** [comment]
已经在写了🫡

**Comment by c121914yu** [comment]
4.8.13 已支持
