### ISSUE TITLE
高级编排HTTP请求无法正常传递参数 会携带 undefined  V4.89

### ISSUE THREAD

**Issue by feifeifeichangmeilidejutu12138** [labring/FastGPT#2383]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.89

**问题描述, 日志截图**
高级编排HTTP请求无法正常传递参数
![image](https://github.com/user-attachments/assets/08c38f49-7c4d-4463-8e65-a6a973a903c2)

![image](https://github.com/user-attachments/assets/2f1d01d2-7a57-4a34-ab9a-0bacb13d9353)

**复现步骤**

**预期结果**
http请求可以正常传递参数
**相关截图**
![image](https://github.com/user-attachments/assets/44e2e74c-f115-4552-b871-4ac52a32f191)

**Comment by c121914yu** [comment]
未复现该问题，请提供完整编排

**Comment by Apple1203** [comment]
> 未复现该问题，请提供完整编排

您好，我也遇到了这个问题，用工具调用模块生成SQL，后面接HTTP请求调用数据库，在生成的SQL尾部会自动加入undefined.很奇怪的问题。

![image](https://github.com/user-attachments/assets/5ceb9d93-d3af-48ec-9a00-046c7406d721)

**Comment by haoruilee** [comment]
同样遇到了这个问题

**Comment by c121914yu** [comment]
<img width="1171" alt="image" src="https://github.com/user-attachments/assets/6c7a49c3-aefe-403a-b1ff-672684e4fb6f">
<img width="860" alt="image" src="https://github.com/user-attachments/assets/aca3b7bb-7cdb-4331-9c58-dd75d606de3a">

有可以复现的？试了试最简单的例子，没复现。

**Comment by haoruilee** [comment]
@feifeifeichangmeilidejutu12138 你是使用的Qwen模型么？

**Comment by haoruilee** [comment]
看起来和 #2392 是一样的问题，怀疑是Qwen不能识别这样的配置

**Comment by feifeifeichangmeilidejutu12138** [comment]
> @feifeifeichangmeilidejutu12138 你是使用的Qwen模型么？

是的，我后面改成文档内容提取了

**Comment by feifeifeichangmeilidejutu12138** [comment]
我用同一个模型在官方和开源版上测试了，结果是不一样的[#2392]
