### ISSUE TITLE
markdown组件使用SD文生图API返回base64格式显示不出来

### ISSUE THREAD

**Issue by Kimizhao** [labring/FastGPT#2391]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
使用SD文生图API返回base64格式显示不出来
4.8.5版本是可以的

**复现步骤**

**预期结果**

**相关截图**
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/846ceb21-3b7f-4c84-8b22-4c9d045156dc">

**Comment by 141qq** [comment]
哥，可以分享一下吗，想调用sd 但我不太会

**Comment by c121914yu** [comment]
看了看，是最新版 react markdown 组件不给 base64 直接展示了，下次单独处理下

**Comment by Kimizhao** [comment]
> 看了看，是最新版 react markdown 组件不给 base64 直接展示了，下次单独处理下

可能是base64太大了

**Comment by Kimizhao** [comment]
> 哥，可以分享一下吗，想调用sd 但我不太会

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API

**Comment by c121914yu** [comment]
忘关连，已经支持
