### ISSUE TITLE
当“AI对话”组件前面增加了“知识库搜索”组件后，AI对话的上下文失效

### ISSUE THREAD

**Issue by yf526186881** [labring/FastGPT#2393]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.8

**问题描述, 日志截图**

创建工作流应用，如果单纯只有一个“AI聊天”，组件中设置了上下文，实际聊天使能够结合上下文继续作答的
但是如果在AI聊天前面增加一道“知识库检索”组件，那么AI聊天的上下文就失效了，AI只能根据本轮问题进行作答

补充：
看到其他人有提这个问题，但是回复中说是可能被知识库回复给稀释了，我下面这个图上可以看到，第二个包含了知识库检索的聊天应用，虽然先走了知识库，但是并没有命中，最后还是进入到AI聊天中，之后继续回复“继续”两字，依然发现对话被中断了，没能结合上下文作答；而第一个不包含知识库检索的聊天应用是正常的

**复现步骤**
![image](https://github.com/user-attachments/assets/223421b2-9197-4132-bf57-2a67131c5b8d)
![image](https://github.com/user-attachments/assets/c08dc6f9-c533-4652-be62-b1ce1febeeda)
![image](https://github.com/user-attachments/assets/b74eee34-ea5f-49ca-abfb-1e5839745880)

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
从预览内容中，继续已经不代表继续上一个对话内容了
