### ISSUE TITLE
希望支持 不同应用使用不同key的功能

### ISSUE THREAD

**Issue by luofeng0603** [labring/FastGPT#2395]
目前整个应用都只能使用一个key，能否添加不同应用使用不同key的功能？

**Comment by lijiajun1997** [comment]
不同的应用是不同的key啊 ，你创建多个应用 就可以用不同key实现不同功能啊

**Comment by luofeng0603** [comment]
> 不同的应用是不同的key啊 ，你创建多个应用 就可以用不同key实现不同功能啊

可能我表述有误，我指的是 是oneapi中设置的sk，因为想对不同的应用进行计费，这个时候，希望不同的应用可以设置不同的sk

**Comment by lijiajun1997** [comment]
> > 不同的应用是不同的key啊 ，你创建多个应用 就可以用不同key实现不同功能啊
> 
> 可能我表述有误，我指的是 是oneapi中设置的sk，因为想对不同的应用进行计费，这个时候，希望不同的应用可以设置不同的sk

你可以定义gpt1 gpt2 gpt3的模型名，然后应用1接gpt1 应用2接gpt2. 然后oneapi里记不同的模型名，但是最终转义为gpt，间接实现效果

**Comment by luofeng0603** [comment]
> > > 不同的应用是不同的key啊 ，你创建多个应用 就可以用不同key实现不同功能啊
> > 
> > 
> > 可能我表述有误，我指的是 是oneapi中设置的sk，因为想对不同的应用进行计费，这个时候，希望不同的应用可以设置不同的sk
> 
> 你可以定义gpt1 gpt2 gpt3的模型名，然后应用1接gpt1 应用2接gpt2. 然后oneapi里记不同的模型名，但是最终转义为gpt，间接实现效果

如果一个应用就用一种模型，感觉是可以的，但是一个应用 可能会使用多种模型的，这个感觉 麻烦了点，如果能原生支持就好了

**Comment by sunk926** [comment]
这个应该是商业版的功能吧

**Comment by c121914yu** [comment]
原生支持肯定不可能，fastgpt 本身就有计量了～

**Comment by gaord** [comment]
指导一下fastgpt计量如何使用？不同的用户使用独立计量如何？
