### ISSUE TITLE
登录后 token的有效期是多少啊 怎么修改它

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#2399]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
大佬 登录后 token的有效期是多少啊 怎么修改它啊
**复现步骤**

**预期结果**

**相关截图**

**Comment by luofeng0603** [comment]
后台的token 其实是jwt，可以自己模拟生成的，具体可以看它源码中的jwt的生成规则，用到了配置文件中的 KEY，有效期当然也可以自己指定，生效到2099年也没问题。
