### ISSUE TITLE
使用官网的后台创建的应用，API访问不了，提示"凭证错误"

### ISSUE THREAD

**Issue by luchenwei9266** [labring/FastGPT#240]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
+ [x] 我使用了自己的key，并确认我的 key 是可正常使用的
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
+ [x] 公有云版本
+ [ ] 私有部署版本

**问题描述**
APIKey是新建的，而且已多次新建Key，确认Key和AppID没有问题，然后API还是访问不了，提示"凭证错误"
```
{
    "code": 403,
    "statusText": "unAuthorization",
    "message": "凭证错误",
    "data": null
}
```
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/9455826/d4eee02f-fd09-4104-b901-d47d91f53447)

![image](https://github.com/labring/FastGPT/assets/9455826/4c3990e1-8443-4905-90cb-bb5de09a326c)

![image](https://github.com/labring/FastGPT/assets/9455826/3df7a82e-367f-4a1d-85fc-3102ef4f6e28)

![image](https://github.com/labring/FastGPT/assets/9455826/4ec9ec07-a728-40d9-84fd-a68fd59f8e80)

**Comment by luchenwei9266** [comment]
已解决，可能是梯子和缓存原因导致的。

**Comment by 1234faker** [comment]
> 已解决，可能是梯子和缓存原因导致的。

哥们我也是这错误你是咋解决的啊
