### ISSUE TITLE
求助 安装失败 

### ISSUE THREAD

**Issue by xmmaster** [labring/FastGPT#2400]
error pulling image configuration: download failed after attempts=6: dialing cdn03.quay.io:443 container via direct connection because app settings has no HTTPS proxy: connecting to 104.18.37.147:443: dial tcp 104.18.37.147:443: connectex: No connection could be made because the target machine actively refused it.
=================
 image: quay.io/coreos/etcd:v3.5.5
安装失败，有没有别的地址？请求帮助 感谢！

**Comment by lllwan** [comment]
配置下docker hub代理就好了，参考：https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6
