### ISSUE TITLE
FastGPT-v4.8.9 接入deepseek模型导入数据集一致处于索引中， 后端大量404错误

### ISSUE THREAD

**Issue by lllwan** [labring/FastGPT#2402]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  v4.8.9

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/ac35fd90-fd16-4fee-9526-ad9619666467)

**复现步骤**
![image](https://github.com/user-attachments/assets/24e4edfa-4ed4-4641-a18a-9ee24774f207)
**预期结果**
正常访问

**相关截图**

![image](https://github.com/user-attachments/assets/8d6526e1-8da5-4390-b2a4-db5b59357468)
oneapi日志：
![image](https://github.com/user-attachments/assets/ed42ec7f-731a-47be-b3bd-abdf7ae48492)

**Comment by lijiajun1997** [comment]
deepseek是chat模型 不是embedding模型  你可以用智谱的embedding

**Comment by lllwan** [comment]
明白了，多谢！
