### ISSUE TITLE
是否可以自定义聊天记录？

### ISSUE THREAD

**Issue by lwdnxu** [labring/FastGPT#2403]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
工作流中我想http方法自定义一些聊天记录，这个http的response应该是什么格式的？或者说这个功能是否有实现的方法？
![image](https://github.com/user-attachments/assets/33d421a5-b44a-4e88-82c7-6e0cf935bc16)

**Comment by newfish-cmyk** [comment]
可以构造类似这样的数组，输出参数的数据类型选“历史记录”
```json
[
    {
        "obj": "System",
        "value": [
            {
                "type": "text",
                "text": {
                    "content": systemPrompt
                }
            }
        ]
    },
    {
        "obj": "Human",
        "value": [
            {
                "type": "text",
                "text": {
                    "content": prompt
                }
            }
        ]
    },
    {
        "obj": "AI",
        "value": [
            {
                "type": "text",
                "text": {
                    "content": response
                }
            }
        ]
    }
]
```
