### ISSUE TITLE
是否可以在Chat的API接口处添加一个参数控制是否返回结尾的[DONE]

### ISSUE THREAD

**Issue by alunshqu** [labring/FastGPT#2405]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在Chat的API接口处添加一个参数控制是否返回结尾的[DONE]
**应用场景**
answer类型的响应除了这个[DONE]，都是json格式的，这对于根据event类型来做解析来说是非常不友好的，比如java端，在接收到数据的时候，默认解析为json，这时候会触发异常。
**相关示例**
event: answer
data: [DONE]
-----
JSON 解析失败 D 不是期望的参数

**Comment by c121914yu** [comment]
如果 GPT 去掉的话，这个做法会跟进，如果已经是标准的话，就不考虑特殊处理。
