### ISSUE TITLE
向量模型报错

### ISSUE THREAD

**Issue by xy3xy3** [labring/FastGPT#2416]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
使用模型Embedding-3-large，单一知识库
发生在模型重排前
```
Info] 2024-08-16 12:11:00 [QA Queue] Done
[Info] 2024-08-16 12:11:00 [Vector Queue] Done
The current vector dimension is 3072, and the vector dimension cannot exceed 1536. The first 1536 dimensions are automatically captured
The current vector dimension is 3072, and the vector dimension cannot exceed 1536. The first 1536 dimensions are automatically captured
The current vector dimension is 3072, and the vector dimension cannot exceed 1536. The first 1536 dimensions are automatically captured
The current vector dimension is 3072, and the vector dimension cannot exceed 1536. The first 1536 dimensions are automatically captured
[Error] 2024-08-16 12:11:43 rerank error
```
**复现步骤**
勾选混合搜索，模型重排

**Comment by c121914yu** [comment]
<img width="837" alt="image" src="https://github.com/user-attachments/assets/81e6bdae-9570-406b-93b5-d3c96ad83d11">
没指定维度

**Comment by xy3xy3** [comment]
> <img alt="image" width="837" src="https://private-user-images.githubusercontent.com/50446880/376295748-81e6bdae-9570-406b-93b5-d3c96ad83d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzQyNzIsIm5iZiI6MTczMDMzMzk3MiwicGF0aCI6Ii81MDQ0Njg4MC8zNzYyOTU3NDgtODFlNmJkYWUtOTU3MC00MDZiLTkzYjUtZDNjOTZhZDgzZDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAwMTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMjc5NTFjZTgyN2QyZGMxZGQwMDhmMzlkODljNjc0YTJhYzIwMzVlZmYwYzJkMjBmYmQxYjQyYmNiZDM5ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u8u__DGW9lICvvDpDqhVpzI3ldvvDqC64fY53n888bA"> 没指定维度

根据https://doc.tryfastgpt.ai/docs/development/configuration/#rerank-%E6%8E%A5%E5%85%A5%E7%A7%81%E6%9C%89%E9%83%A8%E7%BD%B2

 `自定义额外参数。例如，如果希望使用 embedding3-large 的话，可以传入 dimensions:1024，来返回1024维度的向量。（目前必须小于1536维度）`
请问现在支持更高维度了吗
