### ISSUE TITLE
数据处理阶段，有部分文档有密码或者无法处理，导致数据处理中断，需要倒回去把有问题的文档删除后才能继续数据处理，是否可以设置跳过有问题的文档，继续数据处理，提高效率？

### ISSUE THREAD

**Issue by William-715** [labring/FastGPT#2418]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

- [ ] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
数据处理阶段，有部分文档有密码或者无法处理，导致数据处理中断，需要倒回去把有问题的文档删除后才能继续数据处理，是否可以设置跳过有问题的文档，继续数据处理，提高效率？

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3118 4.8.13 版本会增加。
