### ISSUE TITLE
【请教】使用deepseek模型好像无法调用插件，不知道是不是配置错了。

### ISSUE THREAD

**Issue by taurusduan** [labring/FastGPT#2420]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
v4.8.9
**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/78d02675-f378-4742-975d-5c05a985078d)

    {
      "model": "deepseek-chat", // 模型名(对应OneAPI中渠道的模型名)
      "name": "deepseek-chat", // 模型别名
      "avatar": "/imgs/model/openai.svg", // 模型的logo
      "maxContext": 125000, // 最大上下文
      "maxResponse": 4000, // 最大回复
      "quoteMaxToken": 120000, // 最大引用内容
      "maxTemperature": 1.2, // 最大温度
      "charsPointsPrice": 0, // n积分/1k token（商业版）
      "censor": false, // 是否开启敏感校验（商业版）
      "vision": true, // 是否支持图片输入
      "datasetProcess": true, // 是否设置为知识库处理模型（QA），务必保证至少有一个为true，否则知识库会报错
      "usedInClassify": true, // 是否用于问题分类（务必保证至少有一个为true）
      "usedInExtractFields": true, // 是否用于内容提取（务必保证至少有一个为true）
      "usedInToolCall": true, // 是否用于工具调用（务必保证至少有一个为true）
      "usedInQueryExtension": true, // 是否用于问题优化（务必保证至少有一个为true）
      "toolChoice": false, // 是否支持工具选择（分类，内容提取，工具调用会用到。目前只有gpt支持）
      "functionCall": false, // 是否支持函数调用（分类，内容提取，工具调用会用到。会优先使用 toolChoice，如果为false，则使用 functionCall，如果仍为 false，则使用提示词模式）
      "customCQPrompt": "", // 自定义文本分类提示词（不支持工具和函数调用的模型
      "customExtractPrompt": "", // 自定义内容提取提示词
      "defaultSystemChatPrompt": "", // 对话默认携带的系统提示词
      "defaultConfig": {} // 请求API时，挟带一些默认配置（比如 GLM4 的 top_p）
    }

![image](https://github.com/user-attachments/assets/812c5d74-2247-499c-8b72-93a32749b776)

如果换成gpt-4o-mini就没有问题，而且我看线上的也是可以调用的。

![image](https://github.com/user-attachments/assets/c6bcd2f4-8106-4fad-9e09-35e1a941049c)

**Comment by Zhenyi-Wang** [comment]
toolChoice改成true试试，他家不久前[更新](https://platform.deepseek.com/api-docs/zh-cn/news/news0725)有支持

**Comment by taurusduan** [comment]
> toolChoice改成true试试，他家不久前[更新](https://platform.deepseek.com/api-docs/zh-cn/news/news0725)有支持

好的，应该是functionCall": true吧

**Comment by Zhenyi-Wang** [comment]
我改的是tool，你可以试试。看文档应该算tool的api

**Comment by taurusduan** [comment]
> 我改的是tool，你可以试试。看文档应该算tool的api

ok

**Comment by taurusduan** [comment]
> deepseek 直接支持 tool 的，而且效果还不错。

ok
