### ISSUE TITLE
为什么<img>标签会被变成md格式？

### ISSUE THREAD

**Issue by B3nDan** [labring/FastGPT#243]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
+ [x] 我使用了自己的key，并确认我的 key 是可正常使用的
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
+ [ ] 公有云版本
+ [x] 私有部署版本

**问题描述**
在知识库内准备的问题中，答案包含一个 "img "标签。
但是在实际ai回复中，这个 "img" 标签，被变成了一个 md格式 的图片
**复现步骤**
如上所述
**预期结果**
正常输出<img>标签的回答，那怕你网页显示不支持<img>标签
**相关截图**
![Shot 2023-09-03 at 21 14 24@2x](https://github.com/labring/FastGPT/assets/129975925/79500821-1ffe-4fba-9a60-6722a020fdb4)
![Shot 2023-09-03 at 21 15 09@2x](https://github.com/labring/FastGPT/assets/129975925/14781a34-02ad-4570-b1ca-b090c558a0ed)

**Comment by c121914yu** [comment]
模型理解问题~
