### ISSUE TITLE
对话列表中显示对话时间

### ISSUE THREAD

**Issue by mn325** [labring/FastGPT#2430]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
希望在对话列表中显示对话时间
![image](https://github.com/user-attachments/assets/b8bfc04e-7cc7-46e9-8fcb-b5a3f7cee630)

**应用场景**

**相关示例**

**Comment by lijiajun1997** [comment]
日志也需要时间

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3024
