### ISSUE TITLE
想要修改高级编排工作流的问答次数上限

### ISSUE THREAD

**Issue by Spylft** [labring/FastGPT#2434]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在高级编排工作流的使用中，设计了一个包含循环的工作流，此时如果循环次数过多，可能会因为运行模块数过多导致最终被提前终止。想要能够对运行模块数上限进行修改。
同时在有循环的时候查看详情选择一个模块时只会显示该模块第一次的输入和输出结果。
**应用场景**
在工作流中使用到循环时就可能会遇到相应的问题
在示例的前两张图中，给出了一个不断对i进行+1操作的循环工作流，可以看到在经历了50次循环后工作流就被强行终止了。
在第三张图中，给出了第二点，即只会显示模块第一次的输入和输出结果的情况，可以看到选择一个模块时会把所有相同模块都选上。
**相关示例**
![QQ截图20240819171844](https://github.com/user-attachments/assets/9e113b7c-f031-46c5-b9b7-e22f1c2b7899)
![QQ截图20240819171606](https://github.com/user-attachments/assets/e2265a1a-3f7a-48db-a826-aefcabfbd276)
![QQ截图20240819171728](https://github.com/user-attachments/assets/d6720b86-e030-4e78-bee3-a7a6e058f771)

**Comment by c121914yu** [comment]
这个需求，会和循环执行模块一起解决。
目前工作流允许最大运行节点为 200

**Comment by c121914yu** [comment]
忘记 close，目前已可以配置
