### ISSUE TITLE
向量查询时返回的值不在0-1之间

### ISSUE THREAD

**Issue by kongccc** [labring/FastGPT#244]
const response: any = await PgClient.query(
      `BEGIN;
        SET LOCAL ivfflat.probes = ${global.systemEnv.pgIvfflatProbe || 10};
        select id,q,a,source,(vector <#> '[${
          vectors[0]
        }]') * -1 AS score from ${PgTrainingTableName} where kb_id='${kbId}' AND user_id='${userId}' order by vector <#> '[${
        vectors[0]
      }]' limit 12;
        COMMIT;`
    );

尝试这段sql查询,发现返回的值是大于1
![image](https://github.com/labring/FastGPT/assets/46598392/264748e3-b4c7-4bc6-824a-ef594b78d1ed)

**Comment by kongccc** [comment]
最终发现好像是作者sql查询有问题?
    const response: any = await PgClient.query(
      `BEGIN;
        SET LOCAL ivfflat.probes = ${global.systemEnv.pgIvfflatProbe || 10};
        select id,q,a,source,(vector <=> '[${
          vectors[0]
        }]') * -1 + 1  AS score from ${PgTrainingTableName} where kb_id='${kbId}' AND user_id='${userId}' order by vector <=> '[${
        vectors[0]
      }]' limit 12;
        COMMIT;`
    );
进行了如上修改之后值就正确了
![image](https://github.com/labring/FastGPT/assets/46598392/4d380655-2268-40ac-aeff-82410ba3536e)

**Comment by c121914yu** [comment]
你没有归一化

**Comment by kongccc** [comment]
我用的是默认的代码 请教一下是哪一部做了这个操作吗

**Comment by c121914yu** [comment]
> 我用的是默认的代码 请教一下是哪一部做了这个操作吗

这是模型层问题。。官方文档给的m3e镜像就没这个问题~

**Comment by kongccc** [comment]
已解决
将open_api.py
# Min-Max normalization
    embeddings = [embedding / np.linalg.norm(embedding) for embedding in embeddings]
这部分修改之后就可以了

**Comment by mxr612** [comment]
虽然但是docker的怎么修啊QwQ

**Comment by mxr612** [comment]
感觉这个函数里面顺便改了应该可以：


function unityDimensional(vector: number[]) {
  if (vector.length > 1536) {
    console.log(
      `The current vector dimension is ${vector.length}, and the vector dimension cannot exceed 1536. The first 1536 dimensions are automatically captured`
    );
    return vector.slice(0, 1536);
  }
  let resultVector = vector;
  const vectorLen = vector.length;

  const zeroVector = new Array(1536 - vectorLen).fill(0);

  return resultVector.concat(zeroVector);
}

**Comment by zha0jf** [comment]
修改 packages/service/core/ai/embedding/index.ts  文件，

在文档最后，增加如下函数：
// Define the normalize_embedding function
export function normalizeEmbedding(vector: number[]): number[] {
  // Calculate L2 norm
  const norm = Math.sqrt(vector.reduce((acc, value) => acc + (value * value), 0));

  // Handle zero norm to avoid division by zero
  if (norm === 0) {
    return vector;
  }

  // Create a new array for the normalized vector
  const normalizedVector = new Array(vector.length).fill(0);
  for (let i = 0; i < vector.length; i++) {
    normalizedVector[i] = vector[i] / norm;
  }

  return normalizedVector;
}

然后，将此文件中的 getVectorsByText函数中的 如下代码，
        const [tokens, vectors] = await Promise.all([
          countPromptTokens(input),
          Promise.all(res.data.map((item) =>unityDimensional(item.embedding)))
        ]);

替换为
        const [tokens, vectors] = await Promise.all([
          countPromptTokens(input),
          Promise.all(res.data.map((item) => {
            // Apply normalization before returning
            return normalizeEmbedding(unityDimensional(item.embedding));
          })),
        ]);
即可。

上述修改的作用是：对于api返回的vectors进行归一化操作，如果api返回的结果已经是归一化过的，则内容不变。
