### ISSUE TITLE
自定义插件中使用process.env读取不到环境变量

### ISSUE THREAD

**Issue by blvyoucan** [labring/FastGPT#2441]
**例行检查**

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  拉的main源码最新

**问题描述, 日志截图**

**复现步骤**

1. 复制packages/plugins/src/template命名为packages/plugins/src/test
2. 在packages/plugins/register.ts的packagePluginList=[...,"test"]末尾添加了test
3. 配置一个工作流调用自定义插件
4. “export TEST_ENV=xxxx”环境变量，同时在.env.local中也配置了环境变量
5. 在packages/plugins/src/test/index.ts中使用process.env.TEST_ENV获取的值为undifiened

**预期结果**

process.env.TEST_ENV的值应该是xxxx

**相关截图**

无

**Comment by c121914yu** [comment]
自定义插件不允许读取环境变量

**Comment by c121914yu** [comment]
也不应该有读环境变量需求

**Comment by blvyoucan** [comment]
> 也不应该有读环境变量需求

能描述下原因吗？我现在写了个插件，用于整合其他几个服务的http接口，这些http接口的地址，我觉得应该是可配置的，比如从环境变量里读取。
