### ISSUE TITLE
请问是否可以支持接入第三方封装的restful API对话接口？

### ISSUE THREAD

**Issue by Btista** [labring/FastGPT#2442]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
 现在相当于是只能填OPENAI格式的api地址和key，我现在有一个封装好的llm对话接口，使用restFul的形式，接口字段都是自定义的，请问怎么接入fastgpt代替它的底层模型添加知识库和编排呢
**应用场景**

**相关示例**

**Comment by Btista** [comment]
小白，感谢楼主解答

**Comment by c121914yu** [comment]
oneapi 接入，自定义模型必须符合 GPT 格式
