### ISSUE TITLE
到底能不能离线

### ISSUE THREAD

**Issue by passwhl** [labring/FastGPT#2443]
获取到docker-compose.yml和config后,docker compose up -d启动成功后
断网，再访问localhost:3000，页面加载不出来，创建应用或知识库一直处于加载中

**Comment by c121914yu** [comment]
没遇到～ 看网络请求，啥加载不出来

**Comment by passwhl** [comment]
> 没遇到～ 看网络请求，啥加载不出来

就部署好之后电脑网断掉  就复现了

**Comment by c121914yu** [comment]
<img width="1541" alt="image" src="https://github.com/user-attachments/assets/d70f142b-f324-47be-9bcf-7a860878d810">
我把 wifi 关了，看着 ok 呢，有没有更多信息？

**Comment by c121914yu** [comment]
发现了是 useQuery 的问题，有些机子没网的话，不会执行。它是判断是否有网络，所以内网情况下是可以，但是没配网络的话是没法请求。

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/2488 这个 pr 做个优化，强制没配置网络情况下也可以发出请求

**Comment by passwhl** [comment]
大部分解决了，知识库的创建还是存在这个不能无连接问题
