### ISSUE TITLE
AI对话 -- 工具调用 -- HTTP请求的流程会导致工具调用输出的结果后自动加入Undefined

### ISSUE THREAD

**Issue by Apple1203** [labring/FastGPT#2444]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.89

**问题描述, 日志截图**

您好，我的设计如下：

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/d195d431-a09d-45dc-9fe5-0766518d29c4">

流程为：模型在 AI对话 中总结知识库，将总结的内容列表返回，输入 工具调用 中构建SQL查询语句，构建的SQL在 http请求 中调用query查询。

在工具调用后可以很好的生成SQL语句，如图所示

<img width="377" alt="截屏2024-08-20 上午11 11 52" src="https://github.com/user-attachments/assets/90ba9179-14d3-4e60-9125-484c40826c30">

但是当调用http请求时，会自动在input的尾部加入‘undefined’，有时候是2-3个‘undefined’，导致查询失败

<img width="373" alt="image" src="https://github.com/user-attachments/assets/08a61912-8c8b-4b29-b447-2bf78af66e71">

感谢您的帮助！

**预期结果**

从工具调用中传递正确的参数给http请求，尾部没有'undefined'

**Comment by c121914yu** [comment]
看看 body 里怎么写的

**Comment by Apple1203** [comment]
> 看看 body 里怎么写的

![image](https://github.com/user-attachments/assets/607b3171-0ecb-44e1-8dc1-02635aa83115)

是这样的

**Comment by c121914yu** [comment]
这看着不是 4.8.9 呢？

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/2383
重复，在旧 issue 讨论
