### ISSUE TITLE
工作流编排中希望支持终止当前对话气泡的功能，后续的输出内容在新的气泡中输出。

### ISSUE THREAD

**Issue by yjzzcao** [labring/FastGPT#2446]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在进行长内容输出时，希望中断当前对话气泡，后续内容在新的对话气泡中输出。

**应用场景**
在深度解析过程中，先输出分析过程，再新的对话气泡中输出总结内容。

**相关示例**

**Comment by lijiajun1997** [comment]
+1 或者两个LLM在两个气泡同时输出

**Comment by c121914yu** [comment]
和对话性质不符，chat 模式就是对称形式，并且部分模型也只支持user 和 ai 对称。
自行增加分割符实现。
