### ISSUE TITLE
中转地址是必须的吗?

### ISSUE THREAD

**Issue by leavegee** [labring/FastGPT#245]
我在部署过程中发现必须配置一个中转地址和key. 
那这样的话 fastGPT 不算是完全私有化部署哇 必须访问外网
还有那些都是付费的服务, 请问是否有免费的或者开源的大模型或者小模型提供支持?
比如百度百川13B 或者 羊驼 或者GLM 等,这样就完全是私有化部署了, 不需要访问外网.
我是新人, 感谢各位大佬的解惑.

**Comment by lhplol** [comment]
部署本档里是可以用本地模型，但是对硬件要求高，而且效果也不如在线模型，性价比比较低，还不如用在线api

**Comment by leavegee** [comment]
> 部署本档里是可以用本地模型，但是对硬件要求高，而且效果也不如在线模型，性价比比较低，还不如用在线api

部署本档里没看到有本地模型呀?都是在线API呀

**Comment by c121914yu** [comment]
可选。
什么模型都行，本地/API，都接oneapi就行，文档里有说明

**Comment by ccly1996** [comment]
> 可选。 什么模型都行，本地/API，都接oneapi就行，文档里有说明

可以不接oneapi吗，不想转一层，就像直接接部署的模型接口
