### ISSUE TITLE
界面问的问题与模型训练问的问题，差距很大，导致微调的模型大打折扣

### ISSUE THREAD

**Issue by panhongfeng** [labring/FastGPT#2450]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ✅] 我已确认目前没有类似 issue
- [✅ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [✅ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ✅] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [✅] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ✅] 私有部署版本, 具体版本号: image: ghcr.io/labring/fastgpt:v4.8.7 # git

**问题描述, 日志截图**
是自己微调的llama3.170B的模型，本地ollama部署的。同样的问题你是谁，ollama启动的窗口回答正确，界面回答就不对，请问这是什么情况
![image](https://github.com/user-attachments/assets/ba7f08e9-bc62-4344-a8dd-a757779dd797)
![image](https://github.com/user-attachments/assets/712eadaa-4cfc-4f9a-b5fe-929479c794af)

**复现步骤**

**预期结果**
期望界面能够和ollama的窗口回答的问题一致
**相关截图**

**Comment by c121914yu** [comment]
提供测试上下文，你图 1 只有 1个问题，图二有一堆问题
