### ISSUE TITLE
版本4.8.9  工具调用 AI模型配置中的 返回AI内容 无法关闭，造成回复内容重复两次

### ISSUE THREAD

**Issue by gufei** [labring/FastGPT#2452]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**

**复现步骤**
工具调用-》http请求-》AI回复
去掉勾选 工具调用中的 返回AI内容，点确认，再打开，仍是勾选状态
由于工具调用和AI回复中都勾选了返回AI内容，这会造成在调试时，返回了两次重复的回复，希望去掉工具调用中的返回AI内容，但去不掉

**预期结果**
希望去掉工具调用中的返回AI内容的勾选

**相关截图**
![image](https://github.com/user-attachments/assets/25c019e4-e089-4485-a52a-81f5acbc2c99)
![image](https://github.com/user-attachments/assets/d5f3a4ff-1c64-4948-8588-87aa63b8566e)

**Comment by c121914yu** [comment]
一直是无法关闭的，UI 没隐藏起来。新版已经隐藏起来了。

**Comment by gufei** [comment]
由于他这里无法关闭，会造成回答重复，这个也不算Bug吗？这个回答 重复的怎么解决？

**Comment by mimo-x** [comment]
同样的困惑，回复过于杂乱直接导致页面不可用
