### ISSUE TITLE
文档给的访问信息是错的

### ISSUE THREAD

**Issue by maxpaynebupt** [labring/FastGPT#2453]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
V4.8.9

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/db74958e-642f-41c3-8a4e-bcfff4fdb991)
文档写的端口是3001，默认密码是123456
实际上的默认端口是3000，默认密码是1234
**复现步骤**
按照文档，使用docker compose安装部署
https://doc.fastgpt.in/docs/development/docker/

**预期结果**
端口与默认密码应该正确
**相关截图**
![image](https://github.com/user-attachments/assets/db74958e-642f-41c3-8a4e-bcfff4fdb991)

**Comment by maxpaynebupt** [comment]
理解错误，3000是web界面。实际情况是3001打不开。

**Comment by maxpaynebupt** [comment]
oneapi反复重启，难道不能离线部署？一定要去访问
https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken

**Comment by maxpaynebupt** [comment]
通过挂载外部证书，以及添加proxy到环境变量给解决了，这个难道每次都要挂着代理跑？

**Comment by c121914yu** [comment]
> oneapi反复重启，难道不能离线部署？一定要去访问 https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken

oneapi 的 README 有说明，离线部署要 volumn 挂载进去

**Comment by c121914yu** [comment]
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/6facd187-f03f-400d-b282-79b71aec7adf">
