### ISSUE TITLE
模型在oneapi测试成功，但是在fastgpt上显示   undefined 当前分组 default 下对于模型 xxxx 无可用渠道 

### ISSUE THREAD

**Issue by cmdhh** [labring/FastGPT#2455]
**例行检查**

- [] 我已确认目前没有类似 issue
- 这个我看了，说要看文档中oneapi教程，我看完了，步骤一样，但没成功
- [✓] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [✓] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [✓] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [✓] 私有部署版本, 具体版本号:  FastGPT V4.8.6

**问题描述, 日志截图**
使用api 在oneapi测试成功，但是在fastgpt上显示   undefined 当前分组 default 下对于模型 xxxx 无可用渠道 
使用本地qwen2模型，可以成功回答

**预期结果**
使用成功

**相关截图**
图一 ：oneapi测试
![捕获11](https://github.com/user-attachments/assets/dba57d0a-5c18-4367-9db0-69f554547733)
图二：fastgpt 使用智谱模型失败，左边是配置文件config.json
![捕获12](https://github.com/user-attachments/assets/137eb2b9-12f2-4c76-9e8f-c34f0854facf)
图三：本地模型回答成功
![捕获13](https://github.com/user-attachments/assets/21bb555c-fdcf-45d7-94f2-9e243eedae65)
图四：日志
![捕获14](https://github.com/user-attachments/assets/6819aef8-ed3d-482c-bc6a-cc609c940e69)
图五：文档中的教程（不知道是不是这个）
![捕获15](https://github.com/user-attachments/assets/cfab3dea-978b-47cf-81c4-bcb6bcaf6998)

**Comment by lijiajun1997** [comment]
你post请求你oneapi试一下  问题再oneapi的配置上 不在fastgpt上

**Comment by lijiajun1997** [comment]
你fastgpt配的是gml-4-0520 oneapi是glm-4-0520， 你找gml的事情，跟我glm有何关系 鲁迅.jpg

**Comment by cmdhh** [comment]
> 你fastgpt配的是gml-4-0520 oneapi是glm-4-0520， 你找gml的事情，跟我glm有何关系 鲁迅.jpg

谢谢谢谢谢谢谢谢谢谢，是我眼瞎了，试了一下，改了名字就好了
