### ISSUE TITLE
工作流循环输出自动停止

### ISSUE THREAD

**Issue by blvyoucan** [labring/FastGPT#2463]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  最新main分支

**问题描述, 日志截图**

**复现步骤**

配置了一个工作流，功能是一个循环用于显示某个任务的进度，大致如下

```mermaid
graph LR;
   S["流程开始"];
   A["判断器"];
   B["http请求-后台某个任务的进度数据"];
   C["指定回复-最终输出"];
   D["指定回复-输出进度信息"];
   S-->A;
   A--"到100%"-->C;
   A--"未到100%"-->B;
   B-->D;
   D--"回到起点判断"-->A;
```

使用该工作流对话时，进度未到达100%就停止了。

**预期结果**

一直循环输出进度，只到进度到达100%

**相关截图**

![Snipaste_2024-08-21_17-01-47](https://github.com/user-attachments/assets/df316f3b-ef2c-475b-a3cf-465db12b34a7)

**Comment by yjzzcao** [comment]
我发现执行的节点上限是 200 个。应该有限制。

**Comment by damahaokaixin** [comment]
<img width="551" alt="image" src="https://github.com/user-attachments/assets/34c88288-310e-4489-8471-c4dcf56a7c88">
对的，遇到了相同的问题，我写了一个循环只能执行到38次。

**Comment by blvyoucan** [comment]
> 我发现执行的节点上限是 200 个。应该有限制。

找了好久，找到一个maxRunTimes参数默认是200。
