### ISSUE TITLE
工作流中关闭某一节点的返回AI内容，使用【指定回复】模块后，流程结束返回的回复会多出一个换行/n

### ISSUE THREAD

**Issue by mengdahuang** [labring/FastGPT#2466]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

当我在工作流中关闭了某一个节点的【返回 AI 内容】后，当流程结束后返回回答时会多一个换行（在接入微信或企业微信时能看到）
如果开启则没有换行。

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/b1f09a36-e4ae-45bf-833c-febb81906714)
![image](https://github.com/user-attachments/assets/66b3ed37-faf4-4512-afa3-a45617a629b9)
![image](https://github.com/user-attachments/assets/6d821b4f-274a-4a85-9271-7e4d890fbe6c)
![image](https://github.com/user-attachments/assets/14d59195-f006-4d1c-b38e-e6b34025a82c)

请问该如何避免多余的换行？谢谢

----

尝试下载V4.8.9源码修改packages/service/core/workflow/dispatchV1/tools/answer.ts代码，把\n删除然后重新生成docker后仍然还是有\n。

请问是还有别的地方需要改吗？

**Comment by mengdahuang** [comment]
https://github.com/labring/FastGPT/issues/2309#issue-2457323012
找到问题了，但我是docker部署的，当我进入fastgpt容器内，发现没有对应路经：`packages/service/core/workflow/dispatchV1/tools/answer.ts`
![image](https://github.com/user-attachments/assets/b58655f3-300c-4a2a-b44d-2cae1231947e)
该如何处理？

**Comment by sdytzjp** [comment]
不能直接在docker改，改源码重现打包镜像

**Comment by mengdahuang** [comment]
> 不能直接在docker改，改源码重现打包镜像

谢谢回复，可以指点一下吗？不太会

**Comment by mengdahuang** [comment]
@c121914yu  您好，请问我参考本issue修改了 packages/service/core/workflow/dispatchV1/tools/answer.ts line: 35 这部分，把\n移除，然后重新通过actions生成docker镜像，这个换行仍然存在，是还有别的部分代码需要修改吗？

谢谢！

**Comment by c121914yu** [comment]
不是 dispatchv1

**Comment by mengdahuang** [comment]
谢谢各位
