### ISSUE TITLE
语义检索值大于1 什么意思？

### ISSUE THREAD

**Issue by anomone** [labring/FastGPT#2467]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/6f1710ec-19f8-48b3-b9c2-3104929a800f)

**复现步骤**

**预期结果**

**相关截图**

**Comment by ShanySky** [comment]
需要先对向量模型接口返回的数据做归一化处理。在fastgpt和向量模型接口之间做一个中间层的web应用程序，在其中实现数据的归一化处理，可以尝试让大模型用python给你实现一版，或者使用你熟悉的编程语言和框架来实现。
