### ISSUE TITLE
分享链接里面的shareId参数，在流程编排里面使用{{shareId}}的方式获取不到，其他自定义的参数都可以。

### ISSUE THREAD

**Issue by longyuit** [labring/FastGPT#2476]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本

Hello，发现一个问题，在分享链接里面的shareId参数，在流程编排里面使用{{shareId}}的方式获取不到，其他自定义的参数都可以。

![image](https://github.com/user-attachments/assets/9a543b8d-c17e-47ca-9965-19eb5eacc624)

或者有什么其他办法能获取到shareId这个参数的值呢。
谢谢！

**Comment by c121914yu** [comment]
shareId 是系统参数，没作为全局变量。

**Comment by longyuit** [comment]
通过其他方式解决了，谢谢。
