### ISSUE TITLE
知识库中的直接分割是使用大语言模型分割的吗还是按照别的什么分割策略？

### ISSUE THREAD

**Issue by HugoSun** [labring/FastGPT#2482]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
想知道知识库中的文件分割的分割策略，如果是使用大语言模型的话，模型的prompt提示词是怎么构造的？如果不是，是按标点符号分割的吗？
**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
直接分割是按字符数和段落分割
问答拆分才是按大模型分割，可以自定义提示词，根据内容的信息结构
