### ISSUE TITLE
公有云版本修改知识库默认权限失败，

### ISSUE THREAD

**Issue by boleyn** [labring/FastGPT#2485]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
最新测试版也有这个问题
- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号:  4.8.10

**问题描述, 日志截图**
知识库配置：从仅协作者访问修改成团队访问刷新后还是恢复原样
![image](https://github.com/user-attachments/assets/c8a2d25c-09fc-4d62-a96c-55618cdf5c8d)
**复现步骤**

**预期结果**
点击保存在刷新应该编程所选
**相关截图**

**Comment by c121914yu** [comment]
提供下知识库 ID？我这里是 ok 的

**Comment by boleyn** [comment]
projects/app/src/pages/api/core/dataset/update.ts  这个地方 修改一下
![image](https://github.com/user-attachments/assets/eaa93095-68bd-4c13-9756-01f27dcb4c05)
我本地新建了几个都有问题，这样修改一下代码就好了

**Comment by c121914yu** [comment]
> projects/app/src/pages/api/core/dataset/update.ts 这个地方 修改一下 ![image](https://private-user-images.githubusercontent.com/24293664/360784681-eaa93095-68bd-4c13-9756-01f27dcb4c05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODYwNDksIm5iZiI6MTcyNDM4NTc0OSwicGF0aCI6Ii8yNDI5MzY2NC8zNjA3ODQ2ODEtZWFhOTMwOTUtNjhiZC00YzEzLTk3NTYtMDFmMjdkY2I0YzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA0MDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMDRkY2NkZmRlMWYxOGZiYzEzZDZmYTFmYTk5ZTRkZjIyNTkyYTMxZjg5OTZhMzY0MWM0ZmY1NDRmNDhjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5MsglW1vpwvUFP2Zf2NHsZGgHcORFLUwYLkoOs53kSs) 我本地新建了几个都有问题，这样修改一下代码就好了

哦，发现了，在 dataset detail 里更新会有问题。在 list 页面 ok。
我修复下。不能直接这么写，这么写会导致无法从子目录移动到根目录了。
