### ISSUE TITLE
有没有知识库批量创建文件集合接口

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2489]
官网只有创建单个文件集合接口

请问有没有批量上传文件的接口

curl --location --request POST 'http://localhost:3000/api/core/dataset/collection/create/localFile' \
--header 'Authorization: Bearer {{authorization}}' \
--form 'file=@"C:\\Users\\user\\Desktop\\fastgpt测试文件\\index.html"' \
--form 'data="{\"datasetId\":\"6593e137231a2be9c5603ba7\",\"parentId\":null,\"trainingType\":\"chunk\",\"chunkSize\":512,\"chunkSplitter\":\"\",\"qaPrompt\":\"\",\"metadata\":{}}"'

**Comment by c121914yu** [comment]
。。循环创建不就好了么
