### ISSUE TITLE
Docker部署（pg+mongodb）+ 源码部署，启动失败

### ISSUE THREAD

**Issue by Tovi163** [labring/FastGPT#2494]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.9
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**

执行命令 pnpm start -p 8002 

> app@4.8.9 start /home/work/fastgpt/FastGPT/projects/app
> next start "-p" "8002"

  ▲ Next.js 14.2.5
  - Local:        http://localhost:8002

 ✓ Starting...
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ✓ Ready in 631ms

通过浏览器访问  host:8002 报错 
Load model====== openapi
Load model====== resource_permission
Load model====== datasets
Load model====== dataset_collections
Load model====== dataset_trainings
Load model====== team_subscriptions
Load model====== apps
Load model====== dataset_datas
Load model====== image
Load model====== dataset.files
Load model====== chat.files
Load model====== buffer_rawtexts
Load model====== dataset_collection_tags
Load model====== systemtimerlocks
Load model====== chat
Load model====== systemConfigs
Load model====== app_system_plugins
Load model====== users
Load model====== team_members
Load model====== teams
Load model====== chatitems
mongo start connect
mongo connected
Error: ENOENT: no such file or directory, open '/app/package.json'
    at Object.openSync (node:fs:596:3)
    at readFileSync (node:fs:464:35)
    at /home/work/fastgpt/FastGPT/projects/app/.next/server/chunks/96960.js:349:23465
    at f (/home/work/fastgpt/FastGPT/projects/app/.next/server/chunks/96960.js:349:23637)
    at /home/work/fastgpt/FastGPT/projects/app/.next/server/chunks/96960.js:351:4441
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async u (/home/work/fastgpt/FastGPT/projects/app/.next/server/pages/api/common/system/getInitData.js:1:2387)
    at async K (/home/work/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/home/work/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/home/work/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/next-server.js:600:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/package.json'
}
[Info] 2024-08-24 18:55:39 Load system plugin successfully: 14
[Error] 2024-08-24 18:55:39 init error
{
  message: "ENOENT: no such file or directory, scandir '/app/data/pluginTemplates'",
  stack: "Error: ENOENT: no such file or directory, scandir '/app/data/pluginTemplates'\n" +
    '    at readdirSync (node:fs:1525:3)\n' +
    '    at /home/work/fastgpt/FastGPT/projects/app/.next/server/chunks/96960.js:349:23772\n' +
    '    at f (/home/work/fastgpt/FastGPT/projects/app/.next/server/chunks/96960.js:349:24031)\n' +
    '    at /home/work/fastgpt/FastGPT/projects/app/.next/server/chunks/96960.js:351:4441\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async u (/home/work/fastgpt/FastGPT/projects/app/.next/server/pages/api/common/system/getInitData.js:1:2387)\n' +
    '    at async K (/home/work/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
    '    at async U.render (/home/work/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)\n' +
    '    at async NextNodeServer.runApi (/home/work/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/next-server.js:600:9)\n' +
    '    at async NextNodeServer.handleCatchallRenderRequest (/home/work/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/next-server.js:269:37)'
}
Load model====== system_logs
 ELIFECYCLE  Command failed with exit code 1.

**复现步骤**

1. 启动服务pnpm start -p 8002，在这里 /home/work/fastgpt/FastGPT/projects/app
2. 浏览器远程访问 ip:8002 

**预期结果**

**相关截图**

<img width="1358" alt="image" src="https://github.com/user-attachments/assets/6e9f8756-4968-421d-b1e7-6eeff2b440b4">

补充信息：

1.  config.json -> config.local.json 仅去除注释
2. .env.local 配置如下

LOG_DEPTH=3
-# 默认用户密码，用户名为 root，每次重启时会自动更新。
DEFAULT_ROOT_PSW=1234
-# 数据库最大连接数
DB_MAX_LINK=5
-# token
TOKEN_KEY=dfdasfdas
-# 文件阅读时的密钥
FILE_TOKEN_KEY=filetokenkey
-# root key, 最高权限
ROOT_KEY=fdafasd
-# openai 基本地址，可用作中转。
OPENAI_BASE_URL=https://api.openai.com/v1
-# oneapi 地址，可以使用 oneapi 来实现多模型接入
-# ONEAPI_URL=https://xxxx.cloud.sealos.io/openai/v1
-# 通用key。可以是 openai 的也可以是 oneapi 的。
-# 此处逻辑：优先走 ONEAPI_URL，如果填写了 ONEAPI_URL，key 也需要是 ONEAPI 的 key
CHAT_API_KEY=sk-xxxx
-# mongo 数据库连接参数，本地开发连接远程数据库时，可能需要增加 directConnection=true 参数，才能连接上。
MONGODB_URI=mongodb://myusername:mypassword@0.0.0.0:27017/fastgpt?authSource=admin&directConnection=true
-# 向量库优先级: pg > milvus
-# PG 向量库连接参数
PG_URL=postgresql://username:password@0.0.0.0:5432/postgres&directConnection=true
-# milvus 向量库连接参数
MILVUS_ADDRESS=https://in03-78bd7f60e6e2a7c.api.gcp-us-west1.zillizcloud.com
MILVUS_TOKEN=133964348b00b4b4e4b51bef680a61350950385c8c64a3ec16b1ab92d3c67dcc4e0370fb9dd15791bcd6dadaf765e98a98735d0d

-# code sandbox url
SANDBOX_URL=http://localhost:3001
-# 商业版地址
PRO_URL=
-# 首页路径
HOME_URL=/

-# 日志等级: debug, info, warn, error
LOG_LEVEL=debug
STORE_LOG_LEVEL=warn

docker的配置

-# 数据库的默认账号和密码仅首次运行时设置有效
-# 如果修改了账号密码，记得改数据库和项目连接参数，别只改一处~
-# 该配置文件只是给快速启动，测试使用。正式使用，记得务必修改账号密码，以及调整合适的知识库参数，共享内存等。
-# 如何无法访问 dockerhub 和 git，可以用阿里云（阿里云没有arm包）

version: '3.3'
services:
  -# db
  pg:
    -# image: pgvector/pgvector:0.7.0-pg15 # docker hub
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.7.0 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5432:5432
    networks:
      - fastgpt
    environment:
      -# 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    -# image: mongo:5.0.18 # dockerhub
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    -# image: mongo:4.4.29 # cpu不支持AVX时候使用
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - fastgpt
    command: mongod --keyFile /data/mongodb.key --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - ./mongo/data:/data/db
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 128 > /data/mongodb.key
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        echo 'const isInited = rs.status().ok === 1
        if(!isInited){
          rs.initiate({
              _id: "rs0",
              members: [
                  { _id: 0, host: "mongo:27017" }
              ]
          })
        }' > /data/initReplicaSet.js
        -# 启动MongoDB服务
        exec docker-entrypoint.sh "$$@" &

        -# 等待MongoDB服务启动
        until mongo -u myusername -p mypassword --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1; do
          echo "Waiting for MongoDB to start..."
          sleep 2
        done

        -# 执行初始化副本集的脚本
        mongo -u myusername -p mypassword --authenticationDatabase admin /data/initReplicaSet.js

        -# 等待docker-entrypoint.sh脚本执行的MongoDB服务进程
        wait $$!

 -# fastgpt
  sandbox:
    container_name: sandbox
    # image: ghcr.io/labring/fastgpt-sandbox:latest # git
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt-sandbox:latest # 阿里云
    networks:
      - fastgpt
    restart: always
  -# oneapi
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mysql:8.0.36 # 阿里云
    # image: mysql:8.0.36
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - fastgpt
    command: --default-authentication-plugin=mysql_native_password
    environment:
     - # 默认root密码，仅首次运行有效
      MYSQL_ROOT_PASSWORD: oneapimmysql
      MYSQL_DATABASE: oneapi
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  fastgpt:`

**Comment by Tovi163** [comment]
补充：

1.  config.json -> config.local.json 仅去除注释
2. .env.local 配置如下

LOG_DEPTH=3
# 默认用户密码，用户名为 root，每次重启时会自动更新。
DEFAULT_ROOT_PSW=1234
# 数据库最大连接数
DB_MAX_LINK=5
# token
TOKEN_KEY=dfdasfdas
# 文件阅读时的密钥
FILE_TOKEN_KEY=filetokenkey
# root key, 最高权限
ROOT_KEY=fdafasd
# openai 基本地址，可用作中转。
OPENAI_BASE_URL=https://api.openai.com/v1
# oneapi 地址，可以使用 oneapi 来实现多模型接入
# ONEAPI_URL=https://xxxx.cloud.sealos.io/openai/v1
# 通用key。可以是 openai 的也可以是 oneapi 的。
# 此处逻辑：优先走 ONEAPI_URL，如果填写了 ONEAPI_URL，key 也需要是 ONEAPI 的 key
CHAT_API_KEY=sk-xxxx
# mongo 数据库连接参数，本地开发连接远程数据库时，可能需要增加 directConnection=true 参数，才能连接上。
MONGODB_URI=mongodb://myusername:mypassword@0.0.0.0:27017/fastgpt?authSource=admin&directConnection=true
# 向量库优先级: pg > milvus
# PG 向量库连接参数
PG_URL=postgresql://username:password@0.0.0.0:5432/postgres&directConnection=true
# milvus 向量库连接参数
MILVUS_ADDRESS=https://in03-78bd7f60e6e2a7c.api.gcp-us-west1.zillizcloud.com
MILVUS_TOKEN=133964348b00b4b4e4b51bef680a61350950385c8c64a3ec16b1ab92d3c67dcc4e0370fb9dd15791bcd6dadaf765e98a98735d0d

# code sandbox url
SANDBOX_URL=http://localhost:3001
# 商业版地址
PRO_URL=
# 首页路径
HOME_URL=/

# 日志等级: debug, info, warn, error
LOG_LEVEL=debug
STORE_LOG_LEVEL=warn

**Comment by Tovi163** [comment]
问题已解决，参考 https://blog.csdn.net/lanyan90/article/details/138182466

**Comment by c121914yu** [comment]
源码部署比较麻烦，dockerfile 里有不少 copy 的脚本，源码部署的话，需要也需要复制过去。
