### ISSUE TITLE
知识库检索出来了不存在的数据

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2495]
4.8.9
知识库检索出来了不存在的数据，但这个数据的确是我的，有可能之前通过接口测试的，但是为什么在知识库中看不到这条数据，而且通过搜索测试提示未知来源，而且点击编辑提示Collection is not exist

![image](https://github.com/user-attachments/assets/ebc2907f-6e80-4d7e-8191-458e3f592fbe)

**Comment by c121914yu** [comment]
看以前更新，有清理脏数据脚本

**Comment by sdytzjp** [comment]
多谢，这个脚本是不是定期自动执行，不需要人工操作




JP
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月12日(星期四) 上午9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [labring/FastGPT] 知识库检索出来了不存在的数据 (Issue #2495)





 
Closed #2495 as completed.

**Comment by c121914yu** [comment]
> 多谢，这个脚本是不是定期自动执行，不需要人工操作
> 
> 
> 
> 
> JP
> ***@***.***
> 
> 
> 
> &nbsp;
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "labring/FastGPT"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年9月12日(星期四) 上午9:44
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [labring/FastGPT] 知识库检索出来了不存在的数据 (Issue #2495)
> 
> 
> 
> 
> 
>  
> Closed #2495 as completed.
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

每小时执行一次。不过只会处理最近几个小时的数据，不是全量扫描，所以如果停机的话就不太准了。
