### ISSUE TITLE
获取知识库数据集合接口无法获取文件夹下面的数据集合

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2500]
4.8.9
通过以下接口命令无法获取文件夹下面数据集，响应数据中能够看到"type": "file" 以及 "type": "folder"
但是folder下面的数据集如何获取出来？

curl --location --request POST 'https://xxxx.com/api/core/dataset/collection/list' \
--header 'Authorization: Bearer fastgpt-v9hRPgVKnyi8y1fAxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "pageNum":1,
    "pageSize": 100,
    "datasetId":"668dfeda8bb4dab68643bac3",
    "parentId": null,
    "searchText":""
}'
响应数据如下

{
    "code": 200,
    "statusText": "",
    "message": "",
    "data": {
        "pageNum": 1,
        "pageSize": 30,
        "data": [
       
            {
                "_id": "66c56784103bebcd8dcf2b7e",
                "parentId": null,
                "tmbId": "667bc3151aad8819f3aced3c",
                "type": "file",
                "name": "盒.xlsx",
                "forbid": false,
                "trainingType": "chunk",
                "tags": [],
                "fileId": "66c5677c103bebcd8dcf2b60",
                "createTime": "2024-08-21T04:05:24.691Z",
                "updateTime": "2024-08-21T04:05:24.691Z",
                "dataAmount": 3,
                "trainingAmount": 0,
                "permission": {
                    "value": 4294967295,
                    "isOwner": true,
                    "hasManagePer": true,
                    "hasWritePer": true,
                    "hasReadPer": true
                }
            },
            {
                "_id": "66b5d12dd2d615e78b7c6b84",
                "parentId": null,
                "tmbId": "667bc3151aad8819f3aced3c",
                "type": "folder",
                "name": "产品修改版",
                "forbid": false,
                "trainingType": "chunk",
                "tags": [],
                "createTime": "2024-08-09T08:19:57.029Z",
                "updateTime": "2024-08-09T08:19:57.029Z",
                "dataAmount": 0,
                "trainingAmount": 2,
                "permission": {
                    "value": 4294967295,
                    "isOwner": true,
                    "hasManagePer": true,
                    "hasWritePer": true,
                    "hasReadPer": true
                }
            },

**Comment by c121914yu** [comment]
parentId

**Comment by sdytzjp** [comment]
请问parentId在哪里获取？parentId和文件夹有什么关系吗？
我的目的是需要将所有"type": "file"的数据集获取出来，包括文件夹下面的数据集。

知识库结构如下：
知识库ID---文件夹1---数据集--数据

以下curl是直接查询的数据ID66cc0ca4f14f6b936892235d，但是没有parentId的信息。
curl --location --request GET 'http://172.16.1.219:18080/api/core/dataset/data/detail?id=66cc0ca4f14f6b936892235d' \
--header 'Authorization: Bearer fastgpt-v9hRPgVKnyi8yxxxx' \

=================

{
    "code": 200,
    "statusText": "",
    "message": "",
    "data": {
        "id": "66cc0ca4f14f6b936892235d",
        "teamId": "667bc3151aad8819f3aced37",
        "q": "22",
        "a": "22",
        "chunkIndex": 0,
        "indexes": [
            {
                "defaultIndex": true,
                "dataId": "73726",
                "text": "22\n22",
                "_id": "66cc0ca4f14f6b936892235e"
            },
            {
                "defaultIndex": false,
                "dataId": "73725",
                "text": "22",
                "_id": "66cc0ca4f14f6b936892235f"
            }
        ],
        "datasetId": "669763c4699c2cc76740fddc",
        "collectionId": "66cc0c9af14f6b9368922312",
        "sourceName": "1.1",
        "isOwner": true,
        "canWrite": true
    }
}
