### ISSUE TITLE
OPENAI token 测试 显示tls 握手超时

### ISSUE THREAD

**Issue by Tovi163** [labring/FastGPT#2505]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
oneapi 启动之后，配置openai 的 token，测试显示超时

<img width="1122" alt="image" src="https://github.com/user-attachments/assets/64f39143-44e1-4b17-b3f8-6a909ee9813c">

**复现步骤**

**预期结果**

**相关截图**

**Comment by heart18z** [comment]
如果是bug，不应该是给oneAPI提吗

**Comment by Tovi163** [comment]
是否可以不使用 oneapi 直接配置 docker-compose.yml 的 OPENAI_BASE_URL 和 CHAT_API_KEY？

**Comment by c121914yu** [comment]
这是你网络和模型提供商连不上
