### ISSUE TITLE
docker部署的fastgpt,usespeed.ts 路径到底在哪？

### ISSUE THREAD

**Issue by phonezhou** [labring/FastGPT#2506]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
docker部署的fastgpt,usespeed.ts 路径到底在哪？

我在接入本地化whisper-asr-webservice语音输入时,在网上的教程都是需要修改use speed.ts的，但我进入docker，没有找到这个文件，听说这个模型不怎么样，想接入本地funasr，请问怎么接入？
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
直接把模型按 whisper 格式封装即可。
改代码要改源码。

**Comment by zhanglf180** [comment]
> 直接把模型按 whisper 格式封装即可。 改代码要改源码。重新打包

请问大佬，打包要怎么操作呀
