### ISSUE TITLE
v4.8.9版本中支持了文件上传对话场景，openAPI请求示例中未看到支持

### ISSUE THREAD

**Issue by JiesenSun** [labring/FastGPT#2508]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8.9

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.9

**问题描述, 日志截图**
v4.8.9版本中支持了文件上传对话场景，openAPI请求示例中未看到支持。

**复现步骤**

**预期结果**
期望openAPI能够支持，谢谢

**相关截图**
![image](https://github.com/user-attachments/assets/66b2df9b-3591-4d67-9e83-b7f227acdd69)

**Comment by c121914yu** [comment]
目前不支持 api

**Comment by JiesenSun** [comment]
> 目前不支持 api

谢谢，是否有计划在下一个版本加进来，有很强的需求😊

**Comment by bobooboboo** [comment]
> > 目前不支持 api
> 
> 谢谢，是否有计划在下一个版本加进来，有很强的需求😊

试了一下把messages.content改成以下格式可以了
![image](https://github.com/user-attachments/assets/f94f0343-3d22-4334-9ae2-ec217ebd36b1)

**Comment by sdytzjp** [comment]
请问有没有测试过图片，为什么有的图片不需要base64，但有的图片提示需要base64.
而且以下base64格式，可以上传成功，但是图片不显示
![image](https://github.com/user-attachments/assets/04396bf5-8fd5-4864-ae89-7d2eb475a5b3)


curl --location --request POST 'https://xxxx/api/v1/chat/completions' \
--header 'Authorization: Bearer fastgpt-sivxEthN40TOddAadKpd1LWanugZlff4nmSXvW' \
--header 'Content-Type: application/json' \
--data '{
    "chatId": "2",
    "stream": false,
    "detail": false,
    "variables": {
        "uid": "asdfadsfasfd2323",
        "name": "张三"
    },
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "name": "1.jpeg",
                    "image_url": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAsSPHFEFE7IGf/2Q=="
                 },
                {
                    "type": "text",
                    "text": "介绍图片"
                }
            ]
        }
    ]
}'

**Comment by c121914yu** [comment]
https://doc.tryfastgpt.ai/docs/development/openapi/chat/
