### ISSUE TITLE
工具调用中子流程添加AI对话后，导致回答混乱

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#2509]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
由于工具调用回答无法细致化提示词，如果用户一个问题，AI选择了两个工具，我并不希望工具调用模块来回答，而是希望AI对话组件来回答，这样方便更好的控制AI的回答结果。

并且在当前的版本中，如果为两个子流程添加AI对话，当同时选择了两个工具后，AI回答会混乱

![image](https://github.com/user-attachments/assets/8f583c78-5454-4a1c-bbb7-2291bfdbcaaf)
![image](https://github.com/user-attachments/assets/1d933bcd-6ef4-4bdc-aff8-6efdb419f74c)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
在AI组件之前做接上工具中止调用，这样信息不会返回给工具调用。但是同时触发两个工具的问题，我目前的思路是，挂一个插件，让AI可以输入多个参数到一次工具调用里，然后这个插件再往下输出信息最后到大模型里
