### ISSUE TITLE
toolChoice和functionCall都是false时，提问文字内容，问答还是会走文档解析功能

### ISSUE THREAD

**Issue by PittYao** [labring/FastGPT#2519]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.9 main分支

**问题描述, 日志截图**
toolChoice和functionCall都是false时，提问文字内容，问答还是会走文档解析功能
<img width="933" alt="image" src="https://github.com/user-attachments/assets/de5e8c35-0b2c-42ab-8af9-a34d49b2e58a">

<img width="732" alt="image" src="https://github.com/user-attachments/assets/6fc4d142-d5bf-44cf-a012-c34c76d30b56">

**复现步骤**
修改config的配置文件
**预期结果**
提问文字内容，不走文档解析节点
**相关截图**

**Comment by c121914yu** [comment]
没 tool 模式，模型理解不行，容易调用文档解析工具。
