### ISSUE TITLE
gpt4在聊天时可能返回空的消息

### ISSUE THREAD

**Issue by HOUTASU** [labring/FastGPT#252]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
gpt4在聊天时可能返回空的消息
**复现步骤**
在快速问问题的时候更容易发生。比如在截图中，在上一个问题没有回答完的情况下，输入新的问题并一直回车(会提示上一个对话还在进行中，没有关系，继续回车)，然后就可能回答为空，并且没有任何报错提示。
具体出问题的位置就是截图2中的代码，取消注释后就会报出错误。
代码位置在： client/src/pages/api/openapi/v1/chat/completions.ts
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/19321784/fbcff9c8-0a65-470d-a9cf-20b6b4cebf78)
![image](https://github.com/labring/FastGPT/assets/19321784/09020dc4-6e53-4f20-a115-ce7751bff204)

**Comment by c121914yu** [comment]
盲猜是上游key挂了，有部分错误 oneapi 没抛出来。
