### ISSUE TITLE
AI对话和 指定回复 混合输出

### ISSUE THREAD

**Issue by lwdnxu** [labring/FastGPT#2520]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8.6
- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
AI对话后续接入指定回复，会造成回复错乱。我看了下好像v4.6.8也有这个issue，是否有解决方法？或者给个方向，我自己来修复
![image](https://github.com/user-attachments/assets/931e518f-d48f-4825-9e25-35471a5a53fb)

**Comment by lwdnxu** [comment]
好像网页版本的fastgpt也有这个问题，我想要的是：指定回复中输出，而不是AI对话中的输出

**Comment by c121914yu** [comment]
没看出来啥问题

**Comment by lwdnxu** [comment]
> 没看出来啥问题

是否可以做到不需要AI对话的结果，只保留指定回复的结果呢？

**Comment by c121914yu** [comment]
> > 没看出来啥问题
> 
> 是否可以做到不需要AI对话的结果，只保留指定回复的结果呢？

那你关掉 AI 对话的输出就好了。

**Comment by lwdnxu** [comment]
okok，很强
