### ISSUE TITLE
文本内容提取希望支持除string类型外其他类型的提取输出结果

### ISSUE THREAD

**Issue by LuckLittleBoy** [labring/FastGPT#2522]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
高级编排中的文本内容提取模块，提取字段配置数据类型为number后，输出中的数据类型依旧是string，希望添加其他类型。
**应用场景**
需要使用文本内容提取模块提取数量等数值类型，以便http调用时传参，对于提取结果为string的输出变量，http模块number参数无法进行变量引用
**相关示例**

**Comment by c121914yu** [comment]
<img width="849" alt="image" src="https://github.com/user-attachments/assets/855f3442-1c98-45eb-8f44-f9e2a13955ed">
不是可以数字么？

**Comment by c121914yu** [comment]
get
