### ISSUE TITLE
在调用知识库应用API时，回答返回的图片地址：https://example.com这个在哪里配置的啊 ？知识库中没有显示这个地址，而在通过api调用的日志中看到有的

### ISSUE THREAD

**Issue by zpcr7** [labring/FastGPT#2523]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/87c7295a-0404-4be9-a55c-6da74dae54a6)

![image](https://github.com/user-attachments/assets/920b8a28-1a21-434a-9285-09296ca07aa6)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
我记得早期版本是可以显示的，现在模型直接补全了url导致bug了，你可以在提示词里加上对于这种格式的url，补全前面域名如"https://fastgpt.in/api/……

**Comment by SDAIer** [comment]
请问怎么解决的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月10日(周日) 下午3:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 在调用知识库应用API时，回答返回的图片地址：https://example.com这个在哪里配置的啊 ？知识库中没有显示这个地址，而在通过api调用的日志中看到有的 (Issue #2523)




 
Closed #2523 as completed.

**Comment by zpcr7** [comment]
![image](https://github.com/user-attachments/assets/d23835c4-5bc0-4d21-8729-669923c2b539)
