### ISSUE TITLE
4.8.9 AI对话计时错误

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#2528]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**

在使用 AI 对话功能时，发现计时统计出现错误。具体表现为插件时间和插件内部的执行时间重复计算，导致总时间统计不准确。

**复现步骤**

1. 启动 AI 对话功能。
2. 进行一次完整的对话交互。
3. 查看计时统计结果。

**预期结果**

希望计时统计能够准确反映对话的实际执行时间，而不是将插件时间和内部执行时间重复计算。

**相关截图**
![image](https://github.com/user-attachments/assets/8cd4fe06-d696-4906-85b3-cb79205a4c3c)

**Comment by c121914yu** [comment]
工具调用反应的是其整个节点运行的时间

**Comment by lijiajun1997** [comment]
> 工具调用反应的是其整个节点运行的时间

但是最后统计成了240秒

**Comment by c121914yu** [comment]
oo

**Comment by heart18z** [comment]
接的sunoAI吗，suno的API不是得异步回调吗

**Comment by lijiajun1997** [comment]
> 接的sunoAI吗，suno的API不是得异步回调吗

https://surl.id/1uHB6XMTE1 这个平台的suno api
