### ISSUE TITLE
后台服务，文档处理编码这些没开源么

### ISSUE THREAD

**Issue by tanyo520** [labring/FastGPT#253]
后台服务，文档处理编码这些没开源么

**Comment by c121914yu** [comment]
在api里

**Comment by Moulcc** [comment]
api里都是接口额，没有后台服务的代码

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The api is full of interfaces, and there is no code for background services.

**Comment by c121914yu** [comment]
> api里都是接口额，没有后台服务的代码

接口不就是后台代码么~

**Comment by Moulcc** [comment]
> > api里都是接口额，没有后台服务的代码
> 
> 接口不就是后台代码么~

我不是很理解 那我请教一个具体的问题哈:

如果putAppById被调，它会发起一个/app/update?appId=xxx 的put请求，那是谁在处理这个put请求呢。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > The api is full of interfaces, and there is no code for background services.
>
> Isn’t the interface just the background code~

I don’t quite understand, so let me ask a specific question:

If putAppById is called, it will initiate a put request with /app/update?appId=xxx, then who is processing this put request.

**Comment by c121914yu** [comment]
> 调

pages/api/app/update 这个接口

**Comment by Moulcc** [comment]
> > 调
> 
> pages/api/app/update 这个接口

Got it, thanks. I checked the wrong directory.
