### ISSUE TITLE
免登陆窗口增加整体查看引用知识的内容

### ISSUE THREAD

**Issue by chung1912** [labring/FastGPT#2531]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
目前对于登录后的“聊天对话”以及”调试”，都可以通过点击“查看详情”--“知识库搜索”来查看引用的所有知识（滚动浏览所有），但是免登陆窗口，只能一个个点进去查看引用的知识，当引用的数量较多的时候，“溯源”十分麻烦，我想查看引用的情况必须一个个点进去看。
**希望“免登陆窗口”增加一个“查看全部引用”的入口，可以直接展示所有引用的内容**

**应用场景**
在对“可信度”要求较高的场景，常常需要核对AI回答的内容到底参考了哪些知识，需要去查看引用的内容“溯源”，能够一次性查看所有引用的好处，是可以通过AI中的某个关键词去引用的内容里面“搜索”，从而快速定位相关知识点。

**相关示例**
通过AI给出的答案，用户通过里面的某个关键词“keyword”，点击“查看全部引用”，然后通过浏览器的ctrl+F搜索，查找出涉及该关键词的原始引用出处

**Comment by Code-Bai** [comment]
+1

**Comment by chonger008** [comment]
+1
