### ISSUE TITLE
知识库不能正确调用向量模型

### ISSUE THREAD

**Issue by Hermit1213** [labring/FastGPT#2534]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: fastgpt:4.8.9, one-api:0.6.4

**问题描述, 日志截图**
fastgpt创建知识库并上传文件后，训练进度条没有动，查看日志报错prompt参数不正确，向量模型没找到
![image](https://github.com/user-attachments/assets/eb2e6a6d-bbd8-48ec-9bf3-79c437f84c4e)
根据文档已经配置向量模型
![image](https://github.com/user-attachments/assets/34b821fc-dfa3-48b8-9e12-34181646bd97)
one-api渠道中也已经配置了向量模型
![image](https://github.com/user-attachments/assets/0a407cc8-2f33-491f-9972-8569219b9244)
目前前端报错
![image](https://github.com/user-attachments/assets/a318ef3e-b03a-4798-b1d5-255594c98d34)
请问这是什么情况，要怎么配置吗？
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
不确定，看着配置对的。不知道智谱有没有这些模型，没用过智谱的 embedding

**Comment by Hermit1213** [comment]
> 不确定，看着配置对的。不知道智谱有没有这些模型，没用过智谱的 embedding

智谱是有向量模型，而且向智谱的api请求可以通过，one-api就不行，不明所以了
![image](https://github.com/user-attachments/assets/c668d5d4-580f-459f-ad69-35bd7bb6b535)

**Comment by c121914yu** [comment]
> > 不确定，看着配置对的。不知道智谱有没有这些模型，没用过智谱的 embedding
> 
> 智谱是有向量模型，而且向智谱的api请求可以通过，one-api就不行，不明所以了 ![image](https://private-user-images.githubusercontent.com/56958327/361640754-c668d5d4-580f-459f-ad69-35bd7bb6b535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTUxNTAsIm5iZiI6MTcyNDc1NDg1MCwicGF0aCI6Ii81Njk1ODMyNy8zNjE2NDA3NTQtYzY2OGQ1ZDQtNTgwZi00NTlmLWFkNjktMzViZDdiYjZiNTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEwMzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMGFhMmM1OTE5YjdjZDMyNTMwNzEzNTE0ZDM3NmYyYjM5ZjIxMzU0NDMzMzA1NzMzZDQ0ZTA2ZTZiNjEzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OY5TJlJxvZzlL_FdQ5NkrXCUY1yPphzcB69UiI62P9g)

我看 oneapi issue，有提无法用智谱的

**Comment by Hermit1213** [comment]
> > > 不确定，看着配置对的。不知道智谱有没有这些模型，没用过智谱的 embedding
> > 
> > 
> > 智谱是有向量模型，而且向智谱的api请求可以通过，one-api就不行，不明所以了 ![image](https://private-user-images.githubusercontent.com/56958327/361640754-c668d5d4-580f-459f-ad69-35bd7bb6b535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTUxNTAsIm5iZiI6MTcyNDc1NDg1MCwicGF0aCI6Ii81Njk1ODMyNy8zNjE2NDA3NTQtYzY2OGQ1ZDQtNTgwZi00NTlmLWFkNjktMzViZDdiYjZiNTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEwMzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMGFhMmM1OTE5YjdjZDMyNTMwNzEzNTE0ZDM3NmYyYjM5ZjIxMzU0NDMzMzA1NzMzZDQ0ZTA2ZTZiNjEzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OY5TJlJxvZzlL_FdQ5NkrXCUY1yPphzcB69UiI62P9g)
> 
> 我看 oneapi issue，有提无法用智谱的

有看到，之前有人提希望能加入智谱的向量模型，之前可以新版本又不行了，应该是之前的适配没有延用下来。。。
