### ISSUE TITLE
新版本one-api报错令牌无权使用模型

### ISSUE THREAD

**Issue by Hermit1213** [labring/FastGPT#2537]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: fastgpt:4.8.9, one-api:0.6.8

**问题描述, 日志截图**
调用智谱模型时报错令牌无权使用模型
![image](https://github.com/user-attachments/assets/2f23a3b7-20c1-40c3-ada0-81251f0f5767)
![image](https://github.com/user-attachments/assets/a6d1ed3a-d75f-407b-b3d3-247e10aaa668)
one-api配置如下
![image](https://github.com/user-attachments/assets/3a7390b8-1e26-45d0-9a0e-accb2ab496e5)
目前解决方法为降one-api版本

**Comment by c121914yu** [comment]
令牌那模型限制设置为空就好了

**Comment by Hermit1213** [comment]
> 令牌那模型限制设置为空就好了

是设置为空的，但还是不能用，有看到其他issue解决办法是降版本
