### ISSUE TITLE
docker里面的mysql、pg、oneapi运行不起来

### ISSUE THREAD

**Issue by fzcccc** [labring/FastGPT#2547]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.9

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/77837344-ffbd-484a-a7b0-2fb9f5e5f222)
我是在win11里面通过wsl2安装ubuntu。docker里面的mysql、pg、oneapi运行不起来
**复现步骤**

**预期结果**

**相关截图**
mysql的报错如下
![image](https://github.com/user-attachments/assets/b39b8149-4f1a-4693-b5c4-9796514e65bc)
pg报错如下
![image](https://github.com/user-attachments/assets/d8b7f82f-4574-4333-a5ca-0cac137dc93d)
oneapi报错如下
![image](https://github.com/user-attachments/assets/6f2f75de-da92-4893-9930-781a06e1d668)

**Comment by yanzengyun** [comment]
权限问题，给容器privage
