### ISSUE TITLE
V4.3知识库导入数据报错

### ISSUE THREAD

**Issue by ChafLee** [labring/FastGPT#255]
column "file_id" does not exist
![image](https://github.com/labring/FastGPT/assets/46702672/75b9b35b-1223-40d8-a79a-6cd98f57ea2a)

**Comment by aleimu** [comment]
我也遇到了,你咋解决的?

**Comment by ChafLee** [comment]
我是升级的旧版本，没改pg库链接，重装了pg就好了

**Comment by aleimu** [comment]
哦哦,重建下数据库,已解决
