### ISSUE TITLE
添加知识库索引后，问答失去AI能力，不能理解上下文。

### ISSUE THREAD

**Issue by WZMMTNH** [labring/FastGPT#2551]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
添加知识库关联后，问答完全失去了理解能力，我问“最近比较好看的电影有哪些”，回答还是挺正常的，列出了最近比较好的电影，但是我接着问“国内的呢”，回答就完全不对，直接在知识库里找的，和电影完全不相关的内容
**复现步骤**

**预期结果**

**相关截图**
![Uploading WechatIMG222.jpg…]()
![Uploading WechatIMG223.jpg…]()
![Uploading WechatIMG224.jpg…]()

**Comment by AAEE86** [comment]
你需要增加一个问题分类

**Comment by WZMMTNH** [comment]
> 你需要增加一个问题分类

增加问题分类是什么意思呢。意思是给知识库里的内容逐个添加问题，问题关联到内容吗

**Comment by AAEE86** [comment]
> > 你需要增加一个问题分类
> 
> 增加问题分类是什么意思呢。意思是给知识库里的内容逐个添加问题，问题关联到内容吗

和知识库无关的内容不调用知识库，比如你知识库是关于公司业务培训的那就和业务无关的直接走另一个LLM

**Comment by WZMMTNH** [comment]
> > > 你需要增加一个问题分类
> > 
> > 
> > 增加问题分类是什么意思呢。意思是给知识库里的内容逐个添加问题，问题关联到内容吗
> 
> 和知识库无关的内容不调用知识库，比如你知识库是关于公司业务培训的那就和业务无关的直接走另一个LLM

好的，谢谢，我去试试。我看到工作流里面有问题分类，具体咋用我看看，谢谢

**Comment by c121914yu** [comment]
没开问题优化
