### ISSUE TITLE
图片渲染失败

### ISSUE THREAD

**Issue by Upcreat** [labring/FastGPT#2566]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x  ] 我已确认目前没有类似 issue
- [ x  ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x  ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x  ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x  ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![局部截取_20240829_103957](https://github.com/user-attachments/assets/2e739618-3f2b-4601-80b3-a403d66a3ecf)

**复现步骤**

**预期结果**
可以找到图片的地址，但是没办法显示出来
**相关截图**

**Comment by CloverZhou** [comment]
+1

**Comment by c121914yu** [comment]
地址呢

**Comment by c121914yu** [comment]
<img width="661" alt="image" src="https://github.com/user-attachments/assets/7f038ec4-4f9c-4e27-afc1-6d7f0865ec12">

**Comment by Upcreat** [comment]
图片地址：“![1.城镇污水处理设施臭气处理技术规程征求意见稿](<https://createup.oss-cn-shenzhen.aliyuncs.com/1.城镇污水处理设施臭气处理技术规程征求意见稿_019199a4-fbc1-762d-8cd4-83e709f7e1ec_40_287397.jpg>)”
测试的：

![局部截取_20240829_113111](https://github.com/user-attachments/assets/4c4303b2-23cf-4722-ac92-d6555423d582)

**Comment by Upcreat** [comment]
[1.城镇污水处理设施臭气处理技术规程征求意见稿](<https://createup.oss-cn-shenzhen.aliyuncs.com/1.城镇污水处理设施臭气处理技术规程征求意见稿_019199a4-fbc1-762d-8cd4-83e709f7e1ec_40_287397.jpg>)
在上面开头加入!,可以看到图片的地址

**Comment by newfish-cmyk** [comment]
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/550f2b8a-0bac-4c53-8534-fa0c672e47ac">
测试着好像没啥问题
