### ISSUE TITLE
打包镜像ERROR [internal] load metadata for docker.io/library/node:20.14.0-alpine   

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2569]
、

![image](https://github.com/user-attachments/assets/7dbcfc6a-393b-47e4-9e0b-0fbf4fb083c1)

**Comment by hechpeng** [comment]
@sdytzjp 怎么解决的

**Comment by sdytzjp** [comment]
网络问题&nbsp; 多试几次



---原始邮件---
发件人: "Providencia ***@***.***&gt;
发送时间: 2024年9月23日(周一) 上午9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 打包镜像ERROR [internal] load metadata for docker.io/library/node:20.14.0-alpine    (Issue #2569)




 
@sdytzjp 怎么解决的
