### ISSUE TITLE
发布时自动填充

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#2574]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
RT
可否在发布时自动填充日期

**应用场景**
<img width="429" alt="Screenshot 2024-08-29 at 18 31 06" src="https://github.com/user-attachments/assets/4fed0566-8a91-4242-af51-d166f6d8154e">

**相关示例**

**Comment by c121914yu** [comment]
忘记关联。已增加
