### ISSUE TITLE
fastgpt的响应格式不符合openai格式，无法接入chatgpt-on-wechat

### ISSUE THREAD

**Issue by Linnnkkk** [labring/FastGPT#2576]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
工作流的输出是一个json，下面的reposeData是一个数组，我看也有很多人反馈这个问题，但是都关闭问题了，但是这个问题没有解决啊
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
不使用工具调用可以。
使用工具调用需要升级 https://github.com/labring/FastGPT/releases/tag/v4.8.10-alpha2 版本

**Comment by sdytzjp** [comment]
chatgpt-on-wechat官网也这么写的
不过即便改了也同样报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月30日(周五) 下午4:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] fastgpt的响应格式不符合openai格式，无法接入chatgpt-on-wechat (Issue #2576)




 
原因找到了，fastgpt的官方文档中，yml格式错了，大家注意下
 Screenshot_20240830_160104.jpg (view on web)

**Comment by sdytzjp** [comment]
重新建一个应用就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月30日(周五) 下午4:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] fastgpt的响应格式不符合openai格式，无法接入chatgpt-on-wechat (Issue #2576)




 
原因找到了，fastgpt的官方文档中，yml格式错了，大家注意下
 Screenshot_20240830_160104.jpg (view on web)
