### ISSUE TITLE
如何在插件中获取token用于调用自带的接口（如创建知识库）

### ISSUE THREAD

**Issue by blvyoucan** [labring/FastGPT#2577]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  4.8

**问题描述, 日志截图**

**复现步骤**

我自定义了一个插件，用于在工作流中创建临时的知识库，但调用/api/core/dataset/create接口时，需要传入token，目前似乎无法获取到

**预期结果**

自定义插件中，获取token，用于调用fastgpt自带的接口

**相关截图**

**Comment by c121914yu** [comment]
可以在 HTTP 请求中，直接用 API key
