### ISSUE TITLE
使用“全文检索”报错:  failed to use text index

### ISSUE THREAD

**Issue by adamwuyu** [labring/FastGPT#2586]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
在“知识库搜索”或“搜索测试”中从语义检索改为全文检索,就会报这个错误:
<img width="747" alt="errorlog" src="https://github.com/user-attachments/assets/14373761-93a1-428a-b633-12cecb890cff">
**复现步骤**
在“知识库搜索”或“搜索测试”中从语义检索改为全文检索
**预期结果**
不报错,能实现全文检索. 万分感谢🙏
**相关截图**
<img width="529" alt="fulltext" src="https://github.com/user-attachments/assets/bf32eb98-0f83-44d1-8d39-5e7947c90d1d">
<img width="558" alt="111111" src="https://github.com/user-attachments/assets/ce7a90ed-c245-430e-8226-893bc6c6bed8">

**Comment by adamwuyu** [comment]
补充信息:
 1. 删除了dataset_datas表的teamId_1_datasetId_1_fullTextToken_text索引;
 2. 新建了新的索引:
 `db.dataset_datas.createIndex({ teamId: 1, datasetId: 1, fullTextToken: "text", q: "text", a: "text" })`
结果:  问题依旧, 求思路🙏🙏🙏🙏🙏🙏

**Comment by c121914yu** [comment]
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/d8bf6dd9-e770-4e25-90f2-4551084dfdba">
这里会有索引自动更新

**Comment by adamwuyu** [comment]
> Collaborator

谢谢，请帮忙看看第3个问题，也就是：有不相关的数据被检索到. 比如全文搜索AAA, 结果没有AAA但包含AAB的数据被搜出来.
