### ISSUE TITLE
使用Dockerfile打包成镜像后端代码修改不生效，前端生效

### ISSUE THREAD

**Issue by taige666** [labring/FastGPT#2587]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
修改了后端代码projects/app/src/pages/api/support/openapi/create.ts中的某个字符串，使用docker build -f ./projects/app/Dockerfile -t fastgpt:i . --build-arg name=app --build-arg proxy=taobao 命令打包项目为镜像文件后run起来发现修改的代码未生效。但是使用make dev name=app在本地直接跑起来就是生效的，不知道原因。而修改projects/app/src/pages/dataset/detail/components/Import/commonProgress/DataProcess.tsx代码打包成镜像后就可以生效。然后当我进入打包后的容器文件中发现projects/app/src/下面居然就两个文件，我不知道合理吗
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/b1ae6fed-038f-486d-a2f7-fedf124f1fb2)

**Comment by c121914yu** [comment]
肯定是代码就没改对，构建产物在.next 文件夹里
