### ISSUE TITLE
全局变量是否能配置默认值默认值

### ISSUE THREAD

**Issue by blvyoucan** [labring/FastGPT#2589]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

配置了全局变量“data”，计划是一个数组，需要传入http插件的body中，配置如下

body:

```json
{
   "data": {{data}}
}
```

首次调用插件时由于全局变量未初始化，会导致调用时的json变为

```
{
  "data": 
}
```

插件会报错message: 'Invalid JSON body: 

**预期结果**

```json
{
  "data":  []
}
```

提供全局变量-自定义变量的默认值配置

**相关截图**

![Snipaste_2024-09-02_10-03-17](https://github.com/user-attachments/assets/527ffc6e-6c1a-4de2-93d6-7fc9913c3ddc)

**Comment by sunk926** [comment]
其实加一个 条件判断> 赋值 就可以了

**Comment by c121914yu** [comment]
排在了 4.8.12

**Comment by c121914yu** [comment]
已合并，忘记关联。
