### ISSUE TITLE
还是希望模块可以折叠,不然功能一旦多了简直是噩梦...

### ISSUE THREAD

**Issue by sunk926** [labring/FastGPT#2591]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
![Quicker_20240902_142147](https://github.com/user-attachments/assets/00b71182-5325-4905-8b3b-7fb816011210)

**应用场景**
模块太多了,就陷入找连接线的状态...
**相关示例**
类似dify模块,能折叠就好,这样布局就能比较整齐

**Comment by c121914yu** [comment]
折叠应该 4.8.12 会有，已经加在规划了
