### ISSUE TITLE
dockerfile 设置了proxy但是安装pnpm很慢

### ISSUE THREAD

**Issue by PittYao** [labring/FastGPT#2593]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
<img width="1480" alt="image" src="https://github.com/user-attachments/assets/402dd089-4ed0-45ec-b10e-231f956c56bc">

**复现步骤**

**预期结果**

**相关截图**

**Comment by blvyoucan** [comment]
改下.npmrc
```npmrc
registry=https://registry.npmmirror.com/
```

**Comment by PittYao** [comment]
> 改下.npmrc
> 
> ```ini-npmrc
> registry=https://registry.npmmirror.com/
> ```
本机上设置的是这个代理。
<img width="582" alt="image" src="https://github.com/user-attachments/assets/a1b93fee-b47c-48aa-a163-26bf96ffc439">


我在dockerfile中设置代理好像也不生效
<img width="980" alt="image" src="https://github.com/user-attachments/assets/8e4e5337-f2a9-4512-8fc4-9538362ce8a1">

**Comment by PittYao** [comment]
> > 改下.npmrc
> > ```
> > registry=https://registry.npmmirror.com/
> > ```
> 
> 本机上设置的是这个代理。 <img alt="image" width="582" src="https://private-user-images.githubusercontent.com/26101917/363616074-a1b93fee-b47c-48aa-a163-26bf96ffc439.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDA0OTEsIm5iZiI6MTcyNTk0MDE5MSwicGF0aCI6Ii8yNjEwMTkxNy8zNjM2MTYwNzQtYTFiOTNmZWUtYjQ3Yy00OGFhLWExNjMtMjZiZjk2ZmZjNDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAzNDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MDcyMDY3YmYxYjRlZTE4Yzk4ODUzZTZiMWMzMDFmYTBjMjRlYjk2MjYwZmE2MjliZDZlMzgzNjgwZjFhOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SqIAtsMuMyuCgAnezrxKQFyY9pTMX5Z2LfFb5YVr5gs">
> 
> 我在dockerfile中设置代理好像也不生效 <img alt="image" width="980" src="https://private-user-images.githubusercontent.com/26101917/363615997-8e4e5337-f2a9-4512-8fc4-9538362ce8a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDA0OTEsIm5iZiI6MTcyNTk0MDE5MSwicGF0aCI6Ii8yNjEwMTkxNy8zNjM2MTU5OTctOGU0ZTUzMzctZjJhOS00NTEyLThmYzQtOTUzODM2MmNlOGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAzNDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNDE2Y2NlNjk0NTZkOTI0NzMyODA1NDRiYjQ2ODExYjQ0YTA3NjE3ODE5NTMzZTEzMGM1NGYwYzYyYWY3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b6R1KpBN5gZePyrw20Hb6zvPDAE5tuPekHvBEtTta4M">

每个阶段都设置就行了
