### ISSUE TITLE
文档解析失败

### ISSUE THREAD

**Issue by AuYuHui** [labring/FastGPT#2595]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/913f74ed-a665-4905-aec1-46adfa263a98)

**复现步骤**
API 调用，解析文档，同一个链接有概率会失败

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
这提示挺明显了呀😂

**Comment by AuYuHui** [comment]
> 这提示挺明显了呀😂

同一链接，可能第二次可以解析出来。
会是是什么原因？
参数不变

**Comment by AuYuHui** [comment]
> 这提示挺明显了呀😂

![image](https://github.com/user-attachments/assets/62aa393e-677f-446a-8c86-1514f1c52113)


文档链接没问题，但是解析不出来。文档结束失败应该 报错不走后面 节点了吧？？

**Comment by c121914yu** [comment]
> > 这提示挺明显了呀😂
> 
> ![image](https://private-user-images.githubusercontent.com/38815121/365083751-6b220b7a-7d4e-44a4-809f-38c4feca718f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDA3OTQsIm5iZiI6MTcyNTgwMDQ5NCwicGF0aCI6Ii8zODgxNTEyMS8zNjUwODM3NTEtNmIyMjBiN2EtN2Q0ZS00NGE0LTgwOWYtMzhjNGZlY2E3MThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDEzMDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNDk5OGEzY2QwMmI1YmM0N2NiNTE2NDYwZDJkZGE0MWE1ZGExYzkzMTY2YWIyYTZmZTg5ZjNjMjgzNTc0ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.foQG14KvFgHq8QTwsnyXnrOGgvksnyOepz6D6B2DXho)
> 
> 文档链接没问题，但是解析不出来。文档结束失败应该 报错不走后面 节点了吧？？

这不都提示你，网络问题了，检查你的网络是不是稳定的～
