### ISSUE TITLE
使用接口【创建一个文件集合】时出现问题，没法正常创建，及不报错也不返回任何东西

### ISSUE THREAD

**Issue by chenxingdbt12345** [labring/FastGPT#2599]
- [ 4.8.9] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
使用接口测试工具时，对创建一个文件集合的接口进行测试发现，没法正常创建，已经确认api密钥和知识库id都正确。
**复现步骤**
request POST 'http://localhost:3000/api/core/dataset/collection/create/localFile' \
--header 'Authorization: Bearer {{authorization}}' \
--form 'file=@"C:\\Users\\user\\Desktop\\fastgpt测试文件\\index.html"' \
--form 'data="{\"datasetId\":\"6593e137231a2be9c5603ba7\",\"parentId\":null,\"trainingType\":\"chunk\",\"chunkSize\":512,\"chunkSplitter\":\"\",\"qaPrompt\":\"\",\"metadata\":{}}"'
**预期结果**
能够正常创建
**相关截图**
![image](https://github.com/user-attachments/assets/1ef0f387-274c-4f68-964c-bfbadc6b0368)
![image](https://github.com/user-attachments/assets/89416859-9e06-4d8b-a2f2-ad49bc9c7c93)

**Comment by c121914yu** [comment]
file 类型就错了

**Comment by chenxingdbt12345** [comment]
> file 类型就错了

我选择了file类型 并且以文件的形式选中
![image](https://github.com/user-attachments/assets/09761fe6-2728-467d-aa73-696717b3a480)
![image](https://github.com/user-attachments/assets/0a88fc4f-179c-42dc-b6ac-eadb7bf4c447)
![image](https://github.com/user-attachments/assets/49718dca-4a92-49e9-8833-5c3abba66cfd)
然后他就报这个错误
可能是我有什么操作失误 但是我现在需要一个请求正常通过的示例

**Comment by c121914yu** [comment]
> > file 类型就错了
> 
> 我选择了file类型 并且以文件的形式选中
> ![image](https://github.com/user-attachments/assets/09761fe6-2728-467d-aa73-696717b3a480)
> ![image](https://github.com/user-attachments/assets/0a88fc4f-179c-42dc-b6ac-eadb7bf4c447)
> ![image](https://github.com/user-attachments/assets/49718dca-4a92-49e9-8833-5c3abba66cfd)
> 然后他就报这个错误
> 可能是我有什么操作失误 但是我现在需要一个请求正常通过的示例

百度下这个错误就知道了

**Comment by chenxingdbt12345** [comment]
ok 解决了 感谢帮助
