### ISSUE TITLE
本地启动服务，新建知识库后，点击知识库详情左下角的全部知识库按钮，服务会一直请求。报错如下。版本分支4.2.2

### ISSUE THREAD

**Issue by OneOfJuly** [labring/FastGPT#260]
{
  message: 'Maximum call stack size exceeded',
  stack: 'RangeError: Maximum call stack size exceeded\n' +
    '    at get (node:internal/bootstrap/node:411:8)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:17:27)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)\n' +
    '    at connectPg (webpack-internal:///(api)/./src/service/pg.ts:33:16)'
}
error: 2023-09-06 10:59:18: Maximum call stack size exceeded

**Comment by c121914yu** [comment]
pg连接问题，大概是环境变量错误或者服务没起来
