### ISSUE TITLE
上传图片后历史记录中没有图片的名字

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2608]
4.8.9
4.8.10-alpha

对话窗口上传文件和图片，获取全局变量history，里面只有文件名字，没有图片名字。
两个版本测试都一样

![mmexport1725361640481](https://github.com/user-attachments/assets/2735e07d-3f8e-442f-a939-6c8760fce4ec)

**Comment by lijiajun1997** [comment]
图片和文件链路不一样，文件是工具解析，图片是通过api请求模型的视觉功能

**Comment by sdytzjp** [comment]
答非所问

**Comment by c121914yu** [comment]
图片设置有就没名字
