### ISSUE TITLE
工具调用仅OpenAI模型可用

### ISSUE THREAD

**Issue by QichangZheng** [labring/FastGPT#2617]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 
- FastGPT: v4.8.9, v4.7.1情况一样
- OneAPI: v0.6.7, v0.6.9-alpha情况一样
- 在Windows和Mac的docker都部署了相同服务，情况一样

**问题描述, 日志截图**
所有模型均通过OneAPI中转，并且可以正常对话，在添加系统工具“获取当前时间“后，仅OpenAI模型能使用此工具。
      "censor": false,
      "vision": true,
      "datasetProcess": true,
      "usedInClassify": true,
      "usedInExtractFields": true,
      "usedInToolCall": true,
      "usedInQueryExtension": true,
      "toolChoice": true,
      "functionCall": true,

使用开源模型（glm4, deepseek-v2, deepseek-llm, qwen2, llama3.1)均无法调用，给不给工具没区别（图1）
Claude3.5模型尝试调用却失败（图2）
Gemini模型直接报错（图3）

**复现步骤**

**预期结果**

**相关截图**
<img width="800" alt="Screenshot 2024-09-04 at 3 46 36 PM" src="https://github.com/user-attachments/assets/9a1ae05e-95e4-437d-9aaa-d19ea1f4f741">
<img width="1041" alt="Screenshot 2024-09-04 at 3 47 37 PM" src="https://github.com/user-attachments/assets/1e2e0f02-f2f1-41df-9260-ffb7f31c0247">
<img width="1034" alt="Screenshot 2024-09-04 at 3 48 21 PM" src="https://github.com/user-attachments/assets/18296bcc-3b94-43ac-88bd-efac97ac57f4">

**Comment by c121914yu** [comment]
你列的几个模型都不知道 tool 模式，需要设置成 false。
国内月之暗面，百川，智谱，阿里均支持 tool 模式。

**Comment by QichangZheng** [comment]
> 你列的几个模型不一定支持 tool 个 function 模式，需要设置成 false。
> claude 肯定是不支持的，开源的几个，看你部署方式，有些支持。
> 具体可以直接 curl 测试是否支持。
> 
> 国内 api 服务， 月之暗面，百川，智谱，阿里，deepseek 均支持 tool 模式。

好的谢谢！所以现在是所有开源模型都不支持工具调用吗？

**Comment by c121914yu** [comment]
> > 你列的几个模型不一定支持 tool 个 function 模式，需要设置成 false。
> > claude 肯定是不支持的，开源的几个，看你部署方式，有些支持。
> > 具体可以直接 curl 测试是否支持。
> > 国内 api 服务， 月之暗面，百川，智谱，阿里，deepseek 均支持 tool 模式。
> 
> 好的谢谢！所以现在是所有开源模型都不支持工具调用吗？

我一般都是用 xinference， 里有有支持的，所以部分开源模型应该也支持，可能只是直接部署的话，没做格式统一。

**Comment by sdytzjp** [comment]
如何通过curl测试是否支持tool



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月5日(周四) 上午10:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 工具调用仅OpenAI模型可用 (Issue #2617)




  
你列的几个模型不一定支持 tool 个 function 模式，需要设置成 false。
 claude 肯定是不支持的，开源的几个，看你部署方式，有些支持。
 具体可以直接 curl 测试是否支持。
 
国内 api 服务， 月之暗面，百川，智谱，阿里，deepseek 均支持 tool 模式。
  
好的谢谢！所以现在是所有开源模型都不支持工具调用吗？
