### ISSUE TITLE
最新版部署，使用分享链接对话，在显示过程中会卡住，显示不完全

### ISSUE THREAD

**Issue by lhplol** [labring/FastGPT#262]
部署方式：docker compose
版本：23年9月6日上午10点的最新版
后台的记录是完整响应了，但是分享链接的前端卡住了，请问是docker镜像没有更新源码最新的commit？还是说“”应用-外部使用-复制分享链接“”这里也要修改一下代码？
谢谢
![无标题](https://github.com/labring/FastGPT/assets/36524051/8ebb1a56-c056-43cb-9d88-cfcec9226242)

**Comment by c121914yu** [comment]
没遇到啥异常~ 可以看看对应日志。

**Comment by lhplol** [comment]
使用one api做流量负载就好了
