### ISSUE TITLE
【求助】接入本地vllm跑的qwen2-7B模型第一句正常回答，第二句就400 no body的问题

### ISSUE THREAD

**Issue by liutianye** [labring/FastGPT#2622]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
通过readme使用docker部署服务，oneapi接入的本地qwen2-7B的模型，oneapi测试成功耗时0.05s，在fastgpt页面创建应用下来选中qwen2-7B后进行测试，在第一句问题时正常回答内容，继续问问题就提示400 no body的报错。vllm的console内只有400的错误code没有具体请求body是什么，求助。
![image](https://github.com/user-attachments/assets/c9a33b2f-2ec9-4c6f-9d94-76ecc5622544)
这是docker的log内容
![image](https://github.com/user-attachments/assets/d845793f-6855-4f50-9cb2-cc5146fafbf8)
**复现步骤**

**预期结果**

**相关截图**

**Comment by liutianye** [comment]
![image](https://github.com/user-attachments/assets/424b18f3-0892-42b8-848d-ac7b2c97b828)

**Comment by c121914yu** [comment]
自行拿日志的 body 来 curl 测试

**Comment by c121914yu** [comment]
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/db1fa878-6380-421c-b3ce-e24c98cf5649">
直接用 oneapi curl 这个数据，或者直接 curl vllm

**Comment by liutianye** [comment]
> 该大了有问题可以理解，改小怎么也会有问题
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月9日(周一) 上午9:02 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [labring/FastGPT] 【求助】接入本地vllm跑的qwen2-7B模型第一句正常回答，第二句就400 no body的问题 (Issue #2622) 自行拿日志里的 body 来 curl 测试 忘了反馈，已经debug完了，是我用vllm起的时候加了max token=2048，所以就报错了，改成了4096了就好了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

不知道呢，我debug把整个参数json扔到postman里去请求发现也是一样报错，然后随手试了一下改4096就可以了...歪打正着。
