### ISSUE TITLE
使用github认证登录fastgpt网站报错。登录fastGPT的网站，点击使用gihub登录，报错啦

### ISSUE THREAD

**Issue by kpchen** [labring/FastGPT#2629]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
登录fastGPT的网站，点击使用gihub登录，报错啦
**复现步骤**
登录fastGPT的网站，点击使用gihub登录，报错啦
**预期结果**

**相关截图**
<img width="631" alt="image" src="https://github.com/user-attachments/assets/8a976133-3775-4c0e-9c3d-ea2bc49fa158">

<img width="1708" alt="image" src="https://github.com/user-attachments/assets/1fc0a5e3-df70-4ddc-8135-5b0cf136eab9">

**Comment by c121914yu** [comment]
fix
