### ISSUE TITLE
AI无法区分历史对话和知识库引用？？

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2635]
4.8.9

先建一个知识库+对话，知识库引用中使用默认提示词

第一个问题是：输出我刚才咨询的问题

正常来说，此时是第一轮对话，AI应该输出之前没有问题。但是AI却输出了针对“输出我刚才咨询的问题”的知识库，从而输出了一堆问题。

如何让AI区分历史对话和知识库引用？提示词怎么写

**Comment by lijiajun1997** [comment]
你的模型能力问题，chatgpt没啥问题

**Comment by sdytzjp** [comment]
我觉得不是模型的问题。

如果没有挂知识库，你问他”我刚才问了哪些问题“，模型是可以输出对话历史记录。
如果挂了知识库，你问他”我刚才问了哪些问题“，模型输出的是知识库中与”我刚才问了哪些问题“这句话向量召回的信息，而不是之前咨询的问题。

请问这个怎么解？

**Comment by c121914yu** [comment]
见 pr 说明
