### ISSUE TITLE
前端界面暴露系统配置数据

### ISSUE THREAD

**Issue by zaite** [labring/FastGPT#2638]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
应用前端分享出去的页面调用的有些接口返回数据会暴露应用一些配置信息或者平台模型配置等敏感内容。能否屏蔽掉一些前端用不到的数据或者配置信息

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
哪些？

**Comment by zaite** [comment]
> 哪些？

api/common/system/getInitData 返回的数据，api/core/chat/outLink/init返回的data->app节点数据

**Comment by c121914yu** [comment]
> > 哪些？
> 
> api/common/system/getInitData 返回的数据，api/core/chat/outLink/init返回的data->app节点数据

没有 app 的数据呢

**Comment by zaite** [comment]
> > > 哪些？
> > 
> > 
> > api/common/system/getInitData 返回的数据，api/core/chat/outLink/init返回的data->app节点数据
> 
> 没有 app 的数据呢。那几个不都是公开的数据么？

![image](https://github.com/user-attachments/assets/2b4c1ca7-2c02-49e4-9a11-4ba8df6b76a6)

**Comment by c121914yu** [comment]
> > > > 哪些？
> > > 
> > > 
> > > api/common/system/getInitData 返回的数据，api/core/chat/outLink/init返回的data->app节点数据
> > 
> > 
> > 没有 app 的数据呢。那几个不都是公开的数据么？
> 
> ![image](https://private-user-images.githubusercontent.com/22079456/365495348-2b4c1ca7-2c02-49e4-9a11-4ba8df6b76a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDk4NTksIm5iZiI6MTcyNTg0OTU1OSwicGF0aCI6Ii8yMjA3OTQ1Ni8zNjU0OTUzNDgtMmI0YzFjYTctMmMwMi00OWU0LTlhMTEtNGJhOGRmNmI3NmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyMzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZTkzM2YzZjY5ZmY3NTRiYWRhNTBlYjE5NzM3MWQzZGM0YTllYzE2MzBkNzA5MjlhMWM2NDA4ZmRiMzY4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vDRIsFC3pUZm8_UrBVOQ8IupRybhrT21CIZPzdx_1hM)

这些页面上都会展示～

**Comment by zaite** [comment]
> api/common/system/getInitData

那这个接口的数据可以隐藏吗，配置信息全出来了

**Comment by c121914yu** [comment]
> > api/common/system/getInitData
> 
> 那这个接口的数据可以隐藏吗，配置信息全出来了

莫得～ 都是前端信息，出来有是问题么～

**Comment by zaite** [comment]
> > > api/common/system/getInitData
> > 
> > 
> > 那这个接口的数据可以隐藏吗，配置信息全出来了
> 
> 莫得～ 都是前端信息，出来有啥问题么～

公司有个项目，要保密这些信息，那只能使用别的三方对话终端不暴露配置的信息了

**Comment by c121914yu** [comment]
没这些数据，页面都没法渲染了。你要是说，里面有啥敏感信息没过滤倒是可以加下～

**Comment by zaite** [comment]
> 没这些数据，页面都没法渲染了。你要是说，里面有啥敏感信息没过滤倒是可以加下～

就是不对外公开使用了那些模型，把模型匿名或者别名可以吗

**Comment by c121914yu** [comment]
> > 没这些数据，页面都没法渲染了。你要是说，里面有啥敏感信息没过滤倒是可以加下～
> 
> 就是不对外公开使用了那些模型，把模型匿名或者别名可以吗

莫得～ 页面展示是别名，但是页面实际选择时候不会选择别名，所以需要原名。你要完全别名，oneapi 加个重定向就可以了。
