### ISSUE TITLE
如何在插件里动态调用"提示词简单应用"?

### ISSUE THREAD

**Issue by timiil** [labring/FastGPT#2648]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

我们创建了若干个带有参数的提示词，以简单应用方式部署； 如何定义一个“插件”或者“工作流”，传入“简单应用名称"or"简单应用id",传入”简单应用参数Json“ ， 从而实现动态调用？ 之前的版本你们给出了动态选择应用，现在最新版本已经废弃，请问如何实现动态？ （我知道可以硬编码调用某个指定的应用"

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
直接像插件一样拖进去

**Comment by timiil** [comment]
动态哦，大哥~~~

**Comment by c121914yu** [comment]
> 直接像插件一样拖进去

之前怎么动态就怎么动态
