### ISSUE TITLE
工具调用，连续调用2次知识库后，查看详情只能看到第一次的调用结果

### ISSUE THREAD

**Issue by Zhenyi-Wang** [labring/FastGPT#2656]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.9

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/da832470-c32f-4846-b6e8-5694c0c398f7)
![image](https://github.com/user-attachments/assets/8fecff5b-493a-4569-b23f-aac994a47f01)

以工具调用形式挂载知识库，调试预览界面，模型如果连续调用2次，在“查看详情里面”只能点开第一次的明细，第二次点不动。

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
升级
