### ISSUE TITLE
工作流中前端展示的输出不可控

### ISSUE THREAD

**Issue by yubuyuabc** [labring/FastGPT#2658]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
工作流中前端展示的输出不可控；1.中间部分组件使用LLM的思考不希望呈现前端，类似coze中只有消息类型的组件才会展示在前端 2..使用指定回复组件，/n并不能有效换行，甚至前端直接呈现了“/n”
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
1. 关闭 ai 回复
2. 斜杆反了

**Comment by yubuyuabc** [comment]
> 1. 关闭 ai 回复
> 2. 斜杆反了
1问题的关闭回复如何操作，官网的工作流中没找到相应配置
2问题和斜杠无关，不展示换行效果
![image](https://github.com/user-attachments/assets/20ad7df0-cc67-4a21-b650-7ee0daabf379)

**Comment by c121914yu** [comment]
> > 1. 关闭 ai 回复
> > 2. 斜杆反了
> 1问题的关闭回复如何操作，官网的工作流中没找到相应配置
> 2问题和斜杠无关，不展示换行效果
> ![image](https://github.com/user-attachments/assets/20ad7df0-cc67-4a21-b650-7ee0daabf379)
> 

噢，备注问题。直接换行就可以了
