### ISSUE TITLE
文档描述错误

### ISSUE THREAD

**Issue by chaofanat** [labring/FastGPT#2666]
[**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

[文档内容有误https://doc.tryfastgpt.ai/docs/course/dataset_engine/](https://doc.tryfastgpt.ai/docs/course/dataset_engine/)
![image](https://github.com/user-attachments/assets/9d26132e-afdf-4a31-9858-16edea1136d8)
红框内是否表达意思反了，从上下文来看，应该是一组数据可能对应多个向量。

**Comment by c121914yu** [comment]
忘记关联，已经纠正，感谢。
