### ISSUE TITLE
4.8.10-fix  IF模块有bug

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2669]
希望尽快处理，对原有流程都有影响。

没找到规律
![image](https://github.com/user-attachments/assets/0afc7e51-e1d0-41a1-8453-25915db48d93)
![image](https://github.com/user-attachments/assets/5c2c27da-b86d-43bd-a260-8a1853f065ea)
![image](https://github.com/user-attachments/assets/01f4b013-1ab4-478e-a685-95465674aacf)
通过对话开场白点击快捷问题[ai版本]，没有匹配到if模块。
收入输入ai版本，有时候可以匹配到if模块，有时候又匹配不多

输入：AI 版本
回复：
 AI 版本更新说明

================
输入：AI 版本
回复：
暂时无法准确回复这个问题。目前的知识。。。

**Comment by c121914yu** [comment]
暂未遇到，提供一下具体编排

**Comment by sdytzjp** [comment]
找到问题了，手动输入“ai版本”没问题，但是通过开场白点击快捷问题、以及复制之前的问题，都会在“ai”和“版本”之间多了一个空格导致的
![image](https://github.com/user-attachments/assets/2e6175c2-9ac2-4173-b061-d06897b6c20a)

![image](https://github.com/user-attachments/assets/71c20b48-db13-4671-b18e-df4ca05e6f1d)
![image](https://github.com/user-attachments/assets/42e0226a-1bc2-4aa3-ada6-09efa6ae1a75)

**Comment by c121914yu** [comment]
中英文中间有空格

**Comment by sdytzjp** [comment]
这就close了？不打算解决了？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月12日(周四) 晚上9:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 4.8.10-fix  IF模块有bug (Issue #2669)




 
Closed #2669 as completed.

**Comment by c121914yu** [comment]
> 这就close了？不打算解决了？
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年9月12日(周四) 晚上9:30
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [labring/FastGPT] 4.8.10-fix  IF模块有bug (Issue #2669)
> 
> 
> 
> 
>  
> Closed #2669 as completed.
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不打算，自行加空格。
