### ISSUE TITLE
免登录窗口 后面两个格式iframe和js模式，语音提示没有权限

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2671]
4.8.10-fix
直接发布页面url可以使用语音功能，如果使用后面两种格式，提示没有权限

![企业微信截图_17260352316864](https://github.com/user-attachments/assets/403f5da4-e2d8-4770-a2f6-9c340f34f058)
![image](https://github.com/user-attachments/assets/d8d023b1-6e68-4b98-aeb5-6643390cd364)

**Comment by c121914yu** [comment]
百度下

**Comment by sdytzjp** [comment]
allow=“microphone”
