### ISSUE TITLE
1210 API 调用参数有误，请检查文档。 (request id: 2024091107451936625419401633009)

### ISSUE THREAD

**Issue by cmdhh** [labring/FastGPT#2673]
**例行检查**

- [ ✓] 我已确认目前没有类似 issue
- [ ✓] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ✓] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ✓] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [✓] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ✓] 私有部署版本, 具体版本号: 
4.8.10
**问题描述, 日志截图**
使用智谱清言glm-4时没问题，使用glm-4v报错，glm-4v是一个能识别图片的大模型。我看见有人提过这样的问题，但是他没解决而是换成别的大模型。我在oneapi的一个issues里面，看见有人说是智谱的接口的问题，不知道是不是https://github.com/songquanpeng/one-api/issues/1778

**预期结果**
成功
**相关截图**
图一：正常没问题
![捕获15](https://github.com/user-attachments/assets/8e7d6d64-15be-4a48-85c0-2691dc3c2745)

图二：使用 glm-4v 报错，右边是日志
![捕获16](https://github.com/user-attachments/assets/bdfe5298-151f-44bf-af54-e2282c1b9e4e)

图三： 报错时oneapi的日志
![捕获17](https://github.com/user-attachments/assets/51910124-3472-49a2-adea-2975101d2be5)

图四： oneapi测试glm-4v是没问题的
![捕获18](https://github.com/user-attachments/assets/2fe337c0-ae80-4011-bbec-35332d2b2bb7)

图五：配置文件（glm-4-plus也能成功）
![捕获19](https://github.com/user-attachments/assets/7548f8ae-e14e-435a-8907-b44d080a474f)

**Comment by xiajinzhi** [comment]
我也遇到了这个问题，请问你解决了吗？

**Comment by junjichan** [comment]
我也遇到了可是我要交作业

**Comment by CaiJianling** [comment]
已找到解决方法：
删除该模型配置文件中的maxResponse字段，删除后即可正常运行。
研究GLM 4V Flash时发现的，查看日志后发现问题原因并解决。

**Comment by xiajinzhi** [comment]
> 已找到解决方法： 删除该模型配置文件中的maxResponse字段，删除后即可正常运行。 研究GLM 4V Flash时发现的，查看日志后发现问题原因并解决。

是config.json吗，删掉也不行呢

**Comment by xiajinzhi** [comment]
> 已找到解决方法： 删除该模型配置文件中的maxResponse字段，删除后即可正常运行。 研究GLM 4V Flash时发现的，查看日志后发现问题原因并解决。

感谢，已经解决了！我试了下把maxResponse改成2000也可以运行
