### ISSUE TITLE
“猜你想问”按钮开启以后，无法生效

### ISSUE THREAD

**Issue by leekuanyew2014** [labring/FastGPT#2678]
![image](https://github.com/user-attachments/assets/2d0ff2ea-e131-4dd2-b345-f2f8ccf5971e)
猜你所问设置后，但是没有生效。

**Comment by c121914yu** [comment]
看日志

**Comment by sdytzjp** [comment]
请问猜你想问的日志在哪里看

**Comment by c121914yu** [comment]
> 请问猜你想问的日志在哪里看

docker logs
