### ISSUE TITLE
本地部署的开源模型怎么添加联网功能

### ISSUE THREAD

**Issue by MusicOfWind** [labring/FastGPT#2679]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
做插件就行 跟模型无关

**Comment by MusicOfWind** [comment]
> 做插件就行 跟模型无关

插件怎么弄，大佬能给个教程或指导一下吗？尝试过dockdockgo，但是部署在本地搜索时报RuntimeError估计网络访问不同。而且应用场景比较严格，注重隐私数据保护

**Comment by sdytzjp** [comment]
使用百度模型 自带百度搜索



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月12日(周四) 下午4:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 本地部署的开源模型怎么添加联网功能 (Issue #2679)




  
做插件就行 跟模型无关
  
插件怎么弄，大佬能给个教程或指导一下吗？尝试过dockdockgo，但是部署在本地搜索时报RuntimeError估计网络访问不同。而且应用场景比较严格，注重隐私数据保护

**Comment by SDAIer** [comment]
qwen-max支持enable_search：ture。fastgpt可以在config.json增加自定义参数，但oneapi目前这个参数好像有问题不生效
https://github.com/songquanpeng/one-api/issues/1857

**Comment by c121914yu** [comment]
本地模型本身不能搜索，需要外挂一个搜索插件。
