### ISSUE TITLE
是否能修改在部署版中导出数据库的时间间隔限制

### ISSUE THREAD

**Issue by PuPuppru** [labring/FastGPT#268]
**例行检查**

- [x ] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在部署版本中由于关闭了用户注册，所以理论上只有一个管理账户（原来的后端接口好像有些变更），导致如果自己一次性要到出多个csv的时候，每次都要等半个多小时。。。。。。。。。。。。是否有修改半个小时间隔的办法，或者创建新用户的方法来规避这个问题？

**Comment by c121914yu** [comment]
4.4已处理。默认为0分钟，
