### ISSUE TITLE
4.8.8-fix2版本无法获代码运行的值

### ISSUE THREAD

**Issue by Xu768212312** [labring/FastGPT#2685]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**4.8.8**

- [ x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/fc34144f-23de-4723-853b-7a399baa154a)
![image](https://github.com/user-attachments/assets/339dcab3-7080-45c3-9a52-7f4636b02c62)

**复现步骤**

**预期结果**

**相关截图**

**Comment by Xu768212312** [comment]
这样的话 输出值如图
![image](https://github.com/user-attachments/assets/38a8b31e-9a0d-451c-816c-abf37b4bdc61)

**Comment by c121914yu** [comment]
这值就是空的呢，多了个 result

**Comment by c121914yu** [comment]
return {AI:222}

**Comment by c121914yu** [comment]
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/469c8a48-4658-4be7-b3fb-77b250032b2c">
那不清楚了，试了试没遇到你的问题

**Comment by CocoDuan2** [comment]
这个问题解决了吗？
我在4.8.10-fix2版本也遇到了这个问题。
<img width="592" alt="image" src="https://github.com/user-attachments/assets/b0ebc21a-82bf-48c9-9bdc-03dbd6bb07c9">
