### ISSUE TITLE
ai对话提示词搜索出现 common:core.module.template.work_start

### ISSUE THREAD

**Issue by lcl-101** [labring/FastGPT#2686]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ✔️] 我已确认目前没有类似 issue
- [ ✔️ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [  ✔️] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [  ✔️] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本 V4.8.10
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
在流程编排中，AI对话中提示词搜搜变量，会出现下面图片中的问题
![image](https://github.com/user-attachments/assets/49648b24-48f0-473d-8211-c41fa818c6a4)

**复现步骤**
流程开始 -> 知识库搜索 -> ai对话 提示词搜索就会复现

**Comment by c121914yu** [comment]
旧的编排，自己修改下对应节点名字。

**Comment by lcl-101** [comment]
> 旧的编排，自己修改下对应节点名字。

怎么修改了

**Comment by c121914yu** [comment]
> > 旧的编排，自己修改下对应节点名字。
> 
> 怎么修改了

升级到最新版，鼠标放上节点，有个改名按键。
