### ISSUE TITLE
用户选择优化

### ISSUE THREAD

**Issue by dreamfly32** [labring/FastGPT#2689]
场景如下图，功能是将AI的回答通过http模块请求服务器生成word文档，问题是如果不选择转文档，是无法继续和AI对话的。

并不是每次对话都需要转文档，所以能不能不强制选择交互，如果用户继续和AI对话，则上次的转文档交互应失效。

或者新增一个组件，叫按钮事件，在AI每次回答后提供一个或多个按钮，例如转word，转pdf等等。

![image](https://github.com/user-attachments/assets/fd0c6367-3aae-4443-aa13-c24e980540f6)

**Comment by lijiajun1997** [comment]
加一个选项叫继续对话啊 然后后面不接任何东西

**Comment by c121914yu** [comment]
没这个计划，流程上不好看。
你可以直接返回一个转文档的接口链接，用户点击后跳转，然后触发转文档即可。
