### ISSUE TITLE
建议加入图片管理

### ISSUE THREAD

**Issue by lhplol** [labring/FastGPT#269]
对于所有输入知识库的文档中的图片，在导入数据库前给出一个markdown格式的本地链接，将图片存入服务器本地的路径下，当用户提问时，根据上下文调出本地的图片返回用户。
目前测试了一下，只能把在线的markdown图片显示出来，本地的似乎很麻烦。谢谢

**Comment by c121914yu** [comment]
mark下。可能会在未来用量管理做完后增加。。

**Comment by lhplol** [comment]
哈哈我自己做出来了，把本地图片映射出去公网，挂给前台回复了

**Comment by xs818818** [comment]
求教怎么实现的，我就不行，每次大语言模型就把我链接忽略了

**Comment by sdytzjp** [comment]
同问
