### ISSUE TITLE
使用nginx代理之后，如何修改静态资源和接口的路径

### ISSUE THREAD

**Issue by fzcccc** [labring/FastGPT#2695]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.10

**问题描述, 日志截图**
我需要使用nginx代理fastgpt，因为fastgpt的静态资源和接口都是使用的相对路径，是当前的域名拼接上相对路径，但是我用nginx代理了之后是有二级路径的，例如nginx的server_name是test，location是
location /fastgpt/ {
proxy_pass fastgpt的ip:3000
},
当我使用test/fastgpt去访问的时候，需要加载fastgpt的静态资源，这时候加载的地址就是test/_next/static/，就提示404找不到资源，实际的路径应该是test/fastgpt/_next/static/，还有api也是test/api，实际应该是test/fastgpt/api。所以想请教各位大佬该怎么修改静态资源和api的路径，在外面加上一层fastgpt。
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
无法修改，需要二级域名。

**Comment by Pumaly** [comment]
这个确实不方便，特别是与其它系统集成的时候。
