### ISSUE TITLE
通过文本分段方式导入pdf时报错

### ISSUE THREAD

**Issue by bruceye777** [labring/FastGPT#270]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
[ERROR]: 2023-09-07 08:04:05: response error: The text contains a special token that is not allowed: <|endofprompt|>
版本是最新版，出现如上错误日志导致无法导入成功，想确认哪些token是 special token，从而规避此种错误
**复现步骤**
导入 《GPT_4，通用人工智能的火花》154页微软GPT研究报告（全中文版）.pdf时出现
**预期结果**
完成导入
**相关截图**
![image](https://github.com/labring/FastGPT/assets/41668200/2f30e643-9fc5-4304-a877-5ac120196b46)

**Comment by c121914yu** [comment]
看着应该是tiktoken错误，新版应该兼容了。可以试试，

**Comment by bruceye777** [comment]
升级到最新版V4.4，导入正常，感谢！
