### ISSUE TITLE
文件对话支持语音输入

### ISSUE THREAD

**Issue by zhanghx0905** [labring/FastGPT#2705]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

支持在聊天框上传文件后，允许用户以语音对话。

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
这两个不冲突吧

**Comment by zhanghx0905** [comment]
> 这两个不冲突吧

按照现在的代码逻辑，上传文档之后会把语音输入按钮隐藏掉

**Comment by c121914yu** [comment]
> > 这两个不冲突吧
> 
> 按照现在的代码逻辑，上传文档之后会把语音输入按钮隐藏掉
> https://github.com/labring/FastGPT/blob/092bb9ab17464b86ce6eca586248b884917d3522/projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx#L520

噢这个意思，提个pr纠正一下好了
