### ISSUE TITLE
使用问题分类，如何支持多轮对话

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2712]
使用问题分类，如何针对同一个主题,支持多轮对话,例如

第一次问题:分析下这个合同
可以通过问题分类找到对应的AI回复

第二次问题:提供下建议
此时,AI无法有效的继续与合同相关的对话

![image](https://github.com/user-attachments/assets/ccf87174-cd10-418f-9148-208daa594a2a)

**Comment by c121914yu** [comment]
加一个全局变量用于记录分类结果，下次进入时候先走判断器，判断全局变量是否有分类结果，有的话直接走分类结果，没有再走分类。

**Comment by mengdahuang** [comment]
@c121914yu 大佬可以展开讲讲，或者帮忙截个图看下吗？没能理解，多谢！

**Comment by sssuperrrr** [comment]
> 加一个全局变量用于记录分类结果，下次进入时候先走判断器，判断全局变量是否有分类结果，有的话直接走分类结果，没有再走分类。

如果全局变量有分类结果，但下一次的输入可能是另一个分类结果（前后两轮对话属于不同分类），这种又该怎么处理呢？也就是在使用问题分类的组件时，怎样判断和区分多轮对话是否属于同一意图
