### ISSUE TITLE
文档解析PDF失败，word可以

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2713]
![image](https://github.com/user-attachments/assets/d8d072d0-cc10-4a42-96e2-ec4d6bd0fcee)
![image](https://github.com/user-attachments/assets/caf13c25-88b4-4f61-9d2b-b990596259d6)

![image](https://github.com/user-attachments/assets/3b776ded-beb2-4b4b-93c3-803a1fa0cf62)

**Comment by c121914yu** [comment]
不支持图片
