### ISSUE TITLE
ios手机不支持语音输入

### ISSUE THREAD

**Issue by nightzjp** [labring/FastGPT#2714]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.10

**问题描述, 日志截图**
工作流配置了语音输入之后，mac通过浏览器语音输入正常，ios手机浏览器语音输入失败；
ios手机生成的音频文件可以正常播放；
ios手机生成的音频文件直接调用openai接口也是无法识别；
当我通过ffmpeg对生成的音频文件转码(ffmpeg -i record.mp3 out.mp3)之后识别正常

**复现步骤**

**预期结果**
后期能不能做ios手机端的适配。

**相关截图**

**Comment by blainehuang1028** [comment]
我也遇到了

**Comment by c121914yu** [comment]
重复 https://github.com/labring/FastGPT/issues/1392
