### ISSUE TITLE
oneapi大量日志该如何处理

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2718]
[SYS] 2024/09/14 - 16:32:25 | batch update started
[SYS] 2024/09/14 - 16:32:25 | batch update finished
[SYS] 2024/09/14 - 16:32:35 | batch update started
[SYS] 2024/09/14 - 16:32:35 | batch update finished
[SYS] 2024/09/14 - 16:32:45 | batch update started
[SYS] 2024/09/14 - 16:32:45 | batch update finished
[SYS] 2024/09/14 - 16:32:55 | batch update started
[SYS] 2024/09/14 - 16:32:55 | batch update finished
[SYS] 2024/09/14 - 16:33:05 | batch update started
[SYS] 2024/09/14 - 16:33:05 | batch update finished
[SYS] 2024/09/14 - 16:33:15 | batch update started
[SYS] 2024/09/14 - 16:33:15 | batch update finished
[SYS] 2024/09/14 - 16:33:25 | batch update started

**Comment by c121914yu** [comment]
oneapi 页面上，设置里，有个清理日志按键，不过日志多了就非常慢，需要手动连 mysql 删除 log 表

**Comment by sdytzjp** [comment]
这种[SYS] 2024/09/14 - 16:33:25 | batch update started日志如何关闭
