### ISSUE TITLE
对话接口如何发送图片或附件

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2720]
官网对话接口中,如何发送图片或者附件?

curl --location --request POST 'https://api.fastgpt.in/api/v1/chat/completions' \
--header 'Authorization: Bearer fastgpt-xxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "chatId": "abcd",
    "stream": false,
    "detail": false,
    "variables": {
        "uid": "asdfadsfasfd2323",
        "name": "张三"
    },
    "messages": [
        {
            "content": "导演是谁",
            "role": "user"
        }
    ]
}'

**Comment by ajiader** [comment]
参考gpt接口

**Comment by SDAIer** [comment]
这都closed

**Comment by c121914yu** [comment]
这不是你自己 close 了么～
