### ISSUE TITLE
会议录音内容总结

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#2727]
目前fastgpt不支持上传音频文件,探讨下如何实现这个功能

单独写一个程序,用户在前端上传音频附件,去调用whisper模型将音频转为文本,然后调用LLM模型,对文本进行归纳总结.
但是页面无法支持流式输出,音频转文本+文本内容总结,需要的时间比较长,用户体验较差

大家有没有好的思路可以提供下

**Comment by PittYao** [comment]
这种耗时任务在对话中怎么做 体验都不会好

**Comment by sdytzjp** [comment]
流式输出效果好一点，但是api接口调用不支持流式输出吧，要等ai全部执行完才能返回结果，这个等待时间有点长



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月18日(周三) 中午11:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 会议录音内容总结 (Issue #2727)




 
这种耗时任务在对话中怎么做 体验都不会好
