### ISSUE TITLE
知识库是否可以在训练中加个停止训练的功能

### ISSUE THREAD

**Issue by ENg-122** [labring/FastGPT#2729]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√] 我已确认目前没有类似 features
- [√] 我已确认我已升级到最新版本
- [√] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [√] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
知识库中的文档在上传后进行训练时，可以终止训练
**应用场景**
本地向量模型调用失败，知识库中的文档会一直在训练中，无法切换别的向量模型
**相关示例**

**Comment by c121914yu** [comment]
删掉文件就可以了
