### ISSUE TITLE
docker compose部署，知识库导入 链接读取没有任何反应

### ISSUE THREAD

**Issue by lonely1215225** [labring/FastGPT#273]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [✅ ] 我已确认目前没有类似 issue
- [✅] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [✅] 我使用了自己的 key，并确认我的 key 是可正常使用的，我使用的是开源模型
- [✅] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [✅] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [✅] 私有部署版本

**问题描述**
docker compose部署，知识库导入 链接读取没有任何反应
**复现步骤**
知识库导入 链接读取没有任何反应
**预期结果**
读取网页内容
**相关截图**
<img width="592" alt="image" src="https://github.com/labring/FastGPT/assets/44398275/7178aaee-93b2-47ed-957c-7de389eec8d6">

**Comment by c121914yu** [comment]
相关日志？
