### ISSUE TITLE
页面或配置文件中能否增加模型的stream自定义配置

### ISSUE THREAD

**Issue by LuckLittleBoy** [labring/FastGPT#2737]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
有的第三方平台可能需要stream=false调用模型，但是现在页面上调用模型默认是true，希望能灵活配置

**应用场景**

**相关示例**

**Comment by lijiajun1997** [comment]
不需要steam直接用http请求就行？

**Comment by c121914yu** [comment]
<img width="608" alt="image" src="https://github.com/user-attachments/assets/46bf1338-40e9-4bb5-9f34-36510b8111e9">
