### ISSUE TITLE
应用发布免密登录是不是有次数控制，为啥我原本用的好好地，现在发布的免密登录地址都变成无效的地址，无法访问

### ISSUE THREAD

**Issue by LRCgtp** [labring/FastGPT#2738]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
![4391d7707a2d9d68437ed03ba30447e](https://github.com/user-attachments/assets/f7287ea5-d32d-4a36-9ad4-d9bf3dce8b88)
![4391d7707a2d9d68437ed03ba30447e](https://github.com/user-attachments/assets/50f0b141-76be-4561-9899-df93d3a9a6c1)

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by LRCgtp** [comment]
请老师尽快帮忙看下这个问题，比较急，谢谢

**Comment by c121914yu** [comment]
编排有 bug，检查自己编排
