### ISSUE TITLE
应用免密登录发布是不是有次数限制，我原来可以用的，现在新发布的地址访问不了，提示无效链接，忙烦老师指导下

### ISSUE THREAD

**Issue by LRCgtp** [labring/FastGPT#2739]
![4391d7707a2d9d68437ed03ba30447e](https://github.com/user-attachments/assets/b639cadc-a54d-4638-b4b9-387c2c0ac335)
![1726644893114](https://github.com/user-attachments/assets/e3749d8a-7b2c-4ba8-9aab-a3c7f26d555f)
![1726645104411](https://github.com/user-attachments/assets/4edad5e2-6ed5-4a0f-9186-5658b7b3ca03)
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by LRCgtp** [comment]
我之前用也还是正常的，昨天开始发布应用通过免密路径访问就访问不了了，服务全部重启了都不行

**Comment by c121914yu** [comment]
没遇到过。这个报错直接是编排就报错了。

**Comment by nightzjp** [comment]
是不是升级之后。编排有些地方没有做调整。
