### ISSUE TITLE
在执行到初始配置时，发现没有相关文件

### ISSUE THREAD

**Issue by Hsdata123** [labring/FastGPT#2740]
![image](https://github.com/user-attachments/assets/45c7b447-1ee5-40d9-a20a-330cab3f5fd6)
没有
![image](https://github.com/user-attachments/assets/b9158d2c-6bbd-4db6-9de6-c6733a82eda1)
这两个文件，请问如何检查并解决

**Comment by c121914yu** [comment]
部署不需要，，
