### ISSUE TITLE
插件新建后无法放入文件夹

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#2741]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
docker v4.8.10
**问题描述, 日志截图**
RT
**复现步骤**

**预期结果**

**相关截图**
<img width="707" alt="Screenshot 2024-09-18 at 23 56 31" src="https://github.com/user-attachments/assets/88b9530e-a57e-474f-a76e-f93e24269b58">

**Comment by bincooo** [comment]
测试了下，似乎是旧版本更新后的文件夹不适配？新建的文件夹正常

**Comment by c121914yu** [comment]
看看数据库里字段有没有异常
