### ISSUE TITLE
fastgpt 知识库的文件处理模型（问题优化）不能修改？

### ISSUE THREAD

**Issue by Qinlilseven** [labring/FastGPT#2751]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x]] 私有部署版本, 具体版本号: V4.8.9

**问题描述, 日志截图**
在支持库倒入文件时候使用的向量模型和应用所使用的模型均来自于在oneapi中配置的百度的模型，
<img width="851" alt="image" src="https://github.com/user-attachments/assets/39d7dbb4-8255-48ef-b453-1ddfbe286e41">
但在对话测试的时候，仍然显现gpt 4o的模型不可使用，发现只有在知识库的文件处理模型仍有相关设置并且没有其他修改选项，请问这里的设置目的是什么以及如何修改？
<img width="558" alt="image" src="https://github.com/user-attachments/assets/fa1d76b8-5cb5-415d-857f-3e92340669a0">

<img width="875" alt="image" src="https://github.com/user-attachments/assets/325775f7-de95-4057-899e-411d27bf8de4">
<img width="526" alt="image" src="https://github.com/user-attachments/assets/9b6a1285-2107-4597-80a3-b17f4d93e240">

**Comment by sdytzjp** [comment]
默认config第一个llm模型，并且知识库检索属性为true
