### ISSUE TITLE
通过docker-compose部署之后给ai发信息报错找不到前端页面

### ISSUE THREAD

**Issue by lovely0216** [labring/FastGPT#2753]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**![image](https://github.com/user-attachments/assets/f088f3f7-363e-406a-b5a3-a0015ca13f27)
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**
![Uploading 微信截图_20240920101619.png…]()

**Comment by DaddySun51** [comment]
是我。我也有这样的情况，暂时不知到咋解决。

**Comment by DaddySun51** [comment]
![9201](https://github.com/user-attachments/assets/1b887ac2-c277-4b22-9bc9-169fe06d9bb8)
![9202](https://github.com/user-attachments/assets/e5ef715c-fd53-451c-bfb3-74c01657a711)
![9203](https://github.com/user-attachments/assets/5fad4520-16a8-444b-b1eb-71575401b42a)
![9204](https://github.com/user-attachments/assets/e3d78022-d6ad-4df8-83ed-b067819ded6d)
![9205](https://github.com/user-attachments/assets/78aa644e-adcb-4576-813a-b5966fe652fc)
![9206](https://github.com/user-attachments/assets/d56f6ee4-cde4-4f69-8ee7-56c8177a437a)
![9207](https://github.com/user-attachments/assets/af4875bc-9c36-46c9-b08d-d9cb6fa4e675)
![9208](https://github.com/user-attachments/assets/7eeeb792-96c2-462c-93d9-b8ded944ca4f)
是这样的

**Comment by DaddySun51** [comment]
https://github.com/labring/FastGPT/issues/1403#issuecomment-2101850634
看看这个。解决了

**Comment by lovely0216** [comment]
> [#1403 (comment)](https://github.com/labring/FastGPT/issues/1403#issuecomment-2101850634) 看看这个。解决了

好的 非常感谢  我的m3e装完之后
![image](https://github.com/user-attachments/assets/590aae12-317c-449f-9eef-39b4906600c2)
这是啥情况
