### ISSUE TITLE
免登录窗口--创建新链接，可否创建短的链接

### ISSUE THREAD

**Issue by leekuanyew2014** [labring/FastGPT#2757]
![image](https://github.com/user-attachments/assets/752916cb-3a3d-4e90-a340-d25961c3f091)
目前zhe这个分享的链接太长了，可否缩短一点？

**Comment by c121914yu** [comment]
id 本来就长，没法短呢

**Comment by leekuanyew2014** [comment]
> id 本来就长，没法短呢

这样的话，分享给别人，感觉上不太好，太长了。

**Comment by c121914yu** [comment]
> > id 本来就长，没法短呢
> 
> 这样的话，分享给别人，感觉上不太好，太长了。

😂会么，太短你不怕别人盗了么

**Comment by leekuanyew2014** [comment]
> > > id 本来就长，没法短呢
> > 
> > 
> > 这样的话，分享给别人，感觉上不太好，太长了。
> 
> 😂会么，太短你不怕别人盗了么

您说的被盗是指？

**Comment by kenith-z** [comment]
要是觉得地址长的话，可以使用短链接生成工具处理一遍

**Comment by c121914yu** [comment]
> > > > id 本来就长，没法短呢
> > > 
> > > 
> > > 这样的话，分享给别人，感觉上不太好，太长了。
> > 
> > 
> > 😂会么，太短你不怕别人盗了么
> 
> 您说的被盗是指？

就是，，比如你链接后只有 3 位，，随便遍历下不就查到你的数据了。
确定有短链需求，可以二次转发下就好了。
