### ISSUE TITLE
输入引导，导入csv文件后乱码

### ISSUE THREAD

**Issue by leekuanyew2014** [labring/FastGPT#2758]
![image](https://github.com/user-attachments/assets/db4f5bc6-da2d-4ff6-bc40-9a956dc9f31c)
输入引导，根据要求导入csv文件，一直是乱码。试过好几次。

**Comment by lijiajun1997** [comment]
csv文件编码不对

**Comment by sdytzjp** [comment]
utf-8

**Comment by leekuanyew2014** [comment]
搞定，感谢两位

**Comment by leekuanyew2014** [comment]
> csv文件编码不对

感谢

**Comment by leekuanyew2014** [comment]
> utf-8

感谢
