### ISSUE TITLE
文本内容提取中文有时会乱码

### ISSUE THREAD

**Issue by nooooom** [labring/FastGPT#2763]
**例行检查**

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.10 fix2

**问题描述, 日志截图**

ollama 部署的 llama3.1-8b-instruct 模型，使用文本内容提取工具时，提取中文有时会出现 Unicode 编码。
![image](https://github.com/user-attachments/assets/9eb66e75-e716-4584-82c1-447268935131)

**Comment by sdytzjp** [comment]
用提示词指定中文试试

**Comment by nooooom** [comment]
> 用提示词指定中文试试

试过了不太行，我看不懂nextjs代码，不知道是不是这个组件间参数传递的BUG，所以想发来让开发看下，如果确定组件没问题，那应该就是模型问题了

**Comment by sdytzjp** [comment]
换个模型吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月21日(周六) 中午1:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 文本内容提取中文有时会乱码 (Issue #2763)




  
用提示词指定中文试试
  
试过了不太行，我看不懂nextjs代码，不知道是不是这个组件间参数传递的BUG，所以想发来让开发看下，如果确定组件没问题，那应该就是模型问题了

**Comment by c121914yu** [comment]
debug 过 ollama？

**Comment by nooooom** [comment]
> debug 过 ollama？

没有，不过我换了qwen2.5模型好像就没问题了，估计是llama3.1中文支持不太好吧，这个issue我关了。

**Comment by sdytzjp** [comment]
可否帮忙用ollama简单测试个场景，如下


使用文档解析+ai对话，上传一个超过3000字的文档，让ai总结，看看ai是否提示找不到文档


如果提示找不到文档，你把文档内容减少到1000左右再试试


多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月21日(周六) 晚上11:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 文本内容提取中文有时会乱码 (Issue #2763)




  
debug 过 ollama？
  
没有，不过我换了qwen2.5模型好像就没问题了，估计是llama3.1中文支持不太好吧，这个issue我关了。

**Comment by sdytzjp** [comment]
可否麻烦用你的ollama简单测试个场景，如下：
使用 文档解析 + AI对话模块
场景一、上传一个1000字左右的文档，让AI总结内容
我测试的效果：可以正常识别并总结。

场景二、上传一个超过3000字的文档，再让AI总结
我测试的效果：AI提示找不到文档（但是debug可以看到已经引用了文档解析的内容）。

详细请看 #2759

**Comment by nooooom** [comment]
> 可否麻烦用你的ollama简单测试个场景，如下：
> 
> 使用 文档解析 + AI对话模块
> 
> 场景一、上传一个1000字左右的文档，让AI总结内容
> 
> 我测试的效果：可以正常识别并总结。
> 
> 
> 
> 场景二、上传一个超过3000字的文档，再让AI总结
> 
> 我测试的效果：AI提示找不到文档（但是debug可以看到已经引用了文档解析的内容）。
> 
> 
> 
> 详细请看 #2759 

周一上班帮你测下
