### ISSUE TITLE
不支持语音流式自动播放

### ISSUE THREAD

**Issue by MouseSun846** [labring/FastGPT#2777]
![image](https://github.com/user-attachments/assets/70849531-9e34-4891-b4a4-535abec9a34f)
v4.7.1 输入后自动语音播放（流式）。
问题回答完毕后，需要手动点击播放才行，没法实现自动播放？

**Comment by c121914yu** [comment]
开启后就可以
<img width="519" alt="image" src="https://github.com/user-attachments/assets/7a4b292c-cf96-4fe0-af44-0f3d492919a3">

**Comment by MouseSun846** [comment]
![image](https://github.com/user-attachments/assets/bc70bfbc-dcbb-46e4-9107-102a08821eca)
为什么我安装的没有

**Comment by MouseSun846** [comment]
> 开启后就可以 <img alt="image" width="519" src="https://private-user-images.githubusercontent.com/50446880/370972549-7a4b292c-cf96-4fe0-af44-0f3d492919a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjg3MjIsIm5iZiI6MTcyNzMyODQyMiwicGF0aCI6Ii81MDQ0Njg4MC8zNzA5NzI1NDktN2E0YjI5MmMtY2Y5Ni00ZmUwLWFmNDQtMGYzZDQ5MjkxOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MjcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNjhkZTY1YTIxYzFhYzUxMjVjZGY5NDk1OTgzNTUxYjc1ZmY2OGI3MGFiNWNhZmM1ZTZkNWRhNjA0NTFlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DEXiIa4DGtIpUmqCwJKY5LGoDO2pswCNVWc34So9ZR4">

为什么我安装的没有 4.8.9 版本没有这个共功能？
![image](https://github.com/user-attachments/assets/edc427b6-82e4-4d68-97f4-c3fbff8bc6fe)

**Comment by c121914yu** [comment]
因为你没开启语音输入

**Comment by MouseSun846** [comment]
> 因为你没开启语音输入

好的，谢谢指导。
