### ISSUE TITLE
fastgpt如果通过信息抽取对问句分析，得到三个关键词，我想要通过知识库，分别对三个关键词语义匹配改写，应该如何实现呢，有点没有思路，在信息抽取模块和知识库间应该如何设计。（之前看dify可以通过迭代模块）

### ISSUE THREAD

**Issue by dingidng** [labring/FastGPT#2778]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

fastgpt如果通过信息抽取对问句分析，得到三个关键词，我想要通过知识库，分别对三个关键词语义匹配改写，应该如何实现呢，有点没有思路，在信息抽取模块和知识库间应该如何设计。（之前看dify可以通过迭代模块）

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
举一个具体例子？没太理解“分别对三个关键词语义匹配改写”

**Comment by c121914yu** [comment]
那你也用迭代实现就可以了
