### ISSUE TITLE
fastgpt调用ollama或者xinference时config.json中的maxContent是否生效？

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#2780]
4.8.10-fx
oneapi 0.6.7

fastgpt调用ollama或者xinference时，config.json中的maxContent都不生效吗？？

## xinference log
![image](https://github.com/user-attachments/assets/df0faf43-c154-4d54-970e-06f9a5ab1900)
![image](https://github.com/user-attachments/assets/1807e18b-589f-4ec4-ba42-e098616a0644)

## ollama log
![image](https://github.com/user-attachments/assets/994ae88a-49aa-4991-9164-a6751e30f12b)
![image](https://github.com/user-attachments/assets/208f85b9-41e0-45c1-8bbe-517a8e2eea4d)

**Comment by sdytzjp** [comment]
@c121914yu

**Comment by c121914yu** [comment]
maxContext 是上下文，maxResponse 是max_tokens，然后你还要看 oneapi 支不支持参数转化

**Comment by SDAIer** [comment]
> maxContext 是上下文，maxResponse 是max_tokens，然后你还要看 oneapi 支不支持参数转化

oneapi那边反馈如下:
这个直接传num_ctx参数就可以了，用0.6.9alpha版本，我加了这个参数进去.docker-compose.yml里image那里制定一下版本，然后怎么传这个参数你得看fastgpt的文档

@c121914yu 请问fastgpt这个参数怎么传
