### ISSUE TITLE
bug：工作流页面，“运行预览”输入框中按Ctrl+Z，撤销的不是文字，而是节点操作

### ISSUE THREAD

**Issue by Zhenyi-Wang** [labring/FastGPT#2787]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.10

**问题描述, 日志截图**
工作流编辑页面中，如果在“运行预览”的输入框中按Ctrl+Z，我的意图是撤销最近的文字编辑，但实际上是撤销了最近的节点操作

**复现步骤**
1. 进入工作流编辑，随便编辑某个节点，比如修改prompt
![image](https://github.com/user-attachments/assets/ce408222-816a-48f2-996d-113129f52aa4)

2. 进入“运行预览”界面，随便输入一些内容，然后按Ctrl+Z
![image](https://github.com/user-attachments/assets/47731a29-7c41-49a9-828b-3ad10d03f109)

3. 可以看到编辑框中的内容没有变化，反而是上一次的节点操作被撤销
![image](https://github.com/user-attachments/assets/b1d72a4b-8fcb-4f67-b519-d679b260bd32)

这样比较违反直觉，希望能够优化下。
感谢！

**预期结果**

**相关截图**

**Comment by Zhenyi-Wang** [comment]
还有Ctrl+C，想复制文字，结果复制了节点的json

**Comment by c121914yu** [comment]
升级最新版

**Comment by Zhenyi-Wang** [comment]
> 升级最新版解决

目前用的是docker的4.8.10-fix2，官网文档4.8.11显示进行中，可以升级的意思？
