### ISSUE TITLE
工具调用-使用讯飞星火的线上模型SparkDesk-v3.5报错：LLM api response empty

### ISSUE THREAD

**Issue by LuckLittleBoy** [labring/FastGPT#2789]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.10-fix

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/48eb3162-a48d-4ca9-8a99-06f7be01863f)
![image](https://github.com/user-attachments/assets/dc634d54-46e1-4d93-a4f7-5d196bbf5f24)
工具调用后LLM针对结果回答时出现异常，one-api版本是v0.6.7，是适配问题吗？
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
星火不支持 tool 模式，需要设置 false
