### ISSUE TITLE
csv上传到表格数据集，部分数据一直在索引中

### ISSUE THREAD

**Issue by arbitraryking** [labring/FastGPT#2790]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: fastgpt:v4.8.9

**问题描述, 日志截图**

![image](https://github.com/user-attachments/assets/a7922be3-2e70-4d73-994c-c69996ea974a)
fastgpt日志：
![image](https://github.com/user-attachments/assets/26fac662-2cd0-48e0-b5bb-1a28627bc041)
one-api日志：
![image](https://github.com/user-attachments/assets/2b769e28-3247-4ce0-ad6f-d64baf7be896)

**复现步骤**
1、在本地测试和部署所使用镜像完全相同，测试时全部csv的内容都正常加载了，唯一差别是测试时知识库设置的文件处理模型是qwenv2-32k，部署时使用智谱glm-4-plus，这会有影响吗？但是oneapi日志中没有关于大模型的请求。
2、我删除了一些一直卡在索引中的csv文件，重新上传，会加载一些数据，但是还是有部分在索引中
**预期结果**

**相关截图**

**Comment by arbitraryking** [comment]
csv已经处理好了的，第一列是用户问题，第二列是答案，用glm-4-plus后最后存储的辅助数据与原来的第二列有差异，甚至部分直接跳过了，用qewn-v2-32k就没有问题，文件处理模型是必用吗？
![image](https://github.com/user-attachments/assets/8ca8c9fc-f0ec-48b6-b655-8a7632ea38b0)
![image](https://github.com/user-attachments/assets/9b5b062a-7947-4e36-90c4-e01e3bdf3643)

**Comment by c121914yu** [comment]
导数据不需要 LLM，只需要  embedding 模型

**Comment by arbitraryking** [comment]
> 导数据不需要 LLM，只需要 embedding 模型

我测试了两次，csv文件分别上传到不同的知识库，只有文件处理模型不一样，一次是正常的，另一次加载到知识库里的内容被修改了，不是我原始csv里的数据。导数据不需要 LLM，那这里选择的大模型是做什么的呢。

![image](https://github.com/user-attachments/assets/50fce773-428b-480a-91cb-01f68b60a1d7)

**Comment by c121914yu** [comment]
> csv已经处理好了的，第一列是用户问题，第二列是答案，用glm-4-plus后最后存储的辅助数据与原来的第二列有差异，甚至部分直接跳过了，用qewn-v2-32k就没有问题，文件处理模型是必用吗？

QA
