### ISSUE TITLE
对话日志查看详情，希望加入某条消息的具体时间

### ISSUE THREAD

**Issue by Zhenyi-Wang** [labring/FastGPT#2795]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
版本 v4.8.10-fix2
目前对话日志似乎只有会话才显示时间，里面的对话不显示，时间跨度长一些的话不方便追溯。能否逐条显示？或者至少在查看详情里能看到。

**应用场景**

**相关示例**
![image](https://github.com/user-attachments/assets/a0133704-9f3c-4bdf-897e-1a65053fd145)

**Comment by ws02589111** [comment]
+1

**Comment by ws02589111** [comment]
Any update？

**Comment by ws02589111** [comment]
Any update？

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3024
