### ISSUE TITLE
知识库搜索测试报错user [3446] quota [-20847155]preConsumedQuota [743]is not enough，但oneapi有余额

### ISSUE THREAD

**Issue by syusama** [labring/FastGPT#2796]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.9

**问题描述, 日志截图**
知识库搜索测试报错user [3446] quota [-20847155]preConsumedQuota [743]is not enough，但oneapi有余额
![微信图片_20240926090818](https://github.com/user-attachments/assets/bf204b11-5d89-4136-80b1-870c6755298b)
对话接口正常

oneapi的余额和令牌限制都没有问题：
![微信图片_20240926104917](https://github.com/user-attachments/assets/75bd1843-5a63-43f4-9c9f-661e58a126fc)
![微信图片_20240926104922](https://github.com/user-attachments/assets/9ff6a5e4-8081-4af8-b8a3-dcb8b121cf86)

**复现步骤**
打开知识库，进行搜索测试，出现报错

**预期结果**
正常搜索知识库

**相关截图**

**Comment by c121914yu** [comment]
到 oneapi 找找或提下，目前没遇到过
