### ISSUE TITLE
工具调用LLM api response empty

### ISSUE THREAD

**Issue by xinyang920** [labring/FastGPT#2805]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: fastgpt=v4.8.8-fix2,xinference=0.15.1,qwen2.5-32b.
llmmodels配置：
{
      "model": "xlab-32b-awq",
      "name": "xlab-32b-awq",
      "maxContext": 32000,
      "avatar": "/imgs/model/xlab_chat_v1.svg",
      "maxResponse": 5000,
      "quoteMaxToken": 13000,
      "maxTemperature": 1.2,
      "charsPointsPrice": 0.1,
      "censor": false,
      "vision": false,
      "datasetProcess": true,
      "usedInClassify": true,
      "usedInExtractFields": true,
      "usedInToolCall": true,
      "usedInQueryExtension": true,
      "toolChoice": true,
      "functionCall": true,
      "customCQPrompt": "",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig": {}
    }

**问题描述, 日志截图**
使用工具调用时，报错“LLM api response empty”。查看日志xinference正常（有截图）
ps: 在另一套环境中也发现这个问题，但是属于偶尔报错(大部分时间正常)。版本是fastgpt=v4.8.8-fix2,xinference=0.13.0,qwen1.5-72b.

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/cb3801f1-37d4-41db-a552-f328090be9d8)
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/8c3cd659-a889-42c6-98e5-d5b756eb2ad8">

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/2290b4c7-611f-4f96-a2f8-0c8c0064e457">

**Comment by xinyang920** [comment]
又尝试了transformer启动模型qwen2.5-32b，工具调用不连接工具时正常回复；连接工具后报错，xinference无输入日志。
![image](https://github.com/user-attachments/assets/0461d891-1273-4f7b-8089-26d901b1e0b7)
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/087d5e27-4cf7-43ca-8fec-7124fb20d734">
![image](https://github.com/user-attachments/assets/45750ee3-15a2-4af0-91e4-0cc184d862c3)
<img width="1223" alt="image" src="https://github.com/user-attachments/assets/145e1b44-2626-4646-9b7d-4ceef3c0e5dd">

**Comment by c121914yu** [comment]
curl 测试后，仍无法找到问题再 open
