### ISSUE TITLE
请问如何跳过登录页访问？ 

### ISSUE THREAD

**Issue by soundmemories** [labring/FastGPT#2807]
目前部署在服务器上可以通过http://192.168.137.68:3000访问登录页，

目前想把服务嵌入到现有服务，想访问http://192.168.137.68:3000时加上用户名和密码，这样直接跳转到使用界面，请问这个要加什么参数，还是改什么配置呢？

先感谢各位大佬解答了！

**Comment by c121914yu** [comment]
无解，只能免登录

**Comment by soundmemories** [comment]
> 无解，只能免登录对话。或者自行二开，定义自动登录规则。

谢谢，请问如何设置免登录对话呢？

**Comment by Zhenyi-Wang** [comment]
> > 无解，只能免登录对话。或者自行二开，定义自动登录规则。
> 
> 谢谢，请问如何设置免登录对话呢？

![image](https://github.com/user-attachments/assets/e9e8b940-4c9e-4f19-8fdd-755409a8108a)
应用配置顶部有个发布渠道的标签，在里面配置
