### ISSUE TITLE
重排模型显示调用成功了为什么页面还是显示false

### ISSUE THREAD

**Issue by gongjl123** [labring/FastGPT#2820]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8.10

**问题描述, 日志截图**
重排模型显示调用成功了为什么页面还是显示false
![img_v3_02f4_cc28fad8-5d3e-481b-b506-78e9ea1009dg](https://github.com/user-attachments/assets/e73b6c95-b837-4182-9c13-b09e6053ea77)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
看 fastgpt 日志，会提示是否成功
