### ISSUE TITLE
bug：简易应用的“图像上传”关不掉

### ISSUE THREAD

**Issue by Zhenyi-Wang** [labring/FastGPT#2821]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.10-fix2

**问题描述, 日志截图**

1. 简易应用，设置中关闭了“图像上传”
![image](https://github.com/user-attachments/assets/3ecc4d47-e174-4615-b418-c1e7a3027cf7)

2. 不管是web还是api对话，依然会从用户问题中提取图片（我故意填了错的地址，所以报错）
![image](https://github.com/user-attachments/assets/df2e0e2e-9212-43fd-ac52-37731b05f0e2)
![image](https://github.com/user-attachments/assets/4fdc6bf6-5236-494b-82f8-50fbe18d0773)
![image](https://github.com/user-attachments/assets/3d5a1d3e-017b-409c-8ca2-777fe11d331c)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
这里只是关闭上传，不会关闭 AI 对话取图

**Comment by Zhenyi-Wang** [comment]
对话取图能关不？我碰到的场景是web抓取的知识库带有失效图片，被附加到用户的问题中，导致报错。用户一脸懵。。

**Comment by c121914yu** [comment]
> 对话取图能关不？我碰到的场景是web抓取的知识库带有失效图片，被附加到用户的问题中，导致报错。用户一脸懵。。

工作流里可以。
新版加了限制，超过 4 个图或者 1000 字符就不取

**Comment by Zhenyi-Wang** [comment]
最好还是加个开关吧，感觉普通用户挺难注意到的。而且也费token

**Comment by c121914yu** [comment]
> 最好还是加个开关吧，感觉普通用户挺难注意到的。而且也费token

一般不会传一个用不了的图吧

**Comment by Zhenyi-Wang** [comment]
网页的知识库还是有可能的。。

1. 图片链接失效，就是我前面提到的场景。
2. 也有可能是图片格式不支持。比如svg，能访问但Azure不能解析。
![image](https://github.com/user-attachments/assets/e0029706-156a-44a6-9678-38b375bb5893)

**Comment by c121914yu** [comment]
没事，抓取网页一般都会超出 1000 字符了

**Comment by Zhenyi-Wang** [comment]
也有道理。。期待新版
