### ISSUE TITLE
【SaaS用户】发起会话后，聊天框右上角会出现更多按钮，可以发起新会话或导出markdown，这个更多按钮可以关闭吗

### ISSUE THREAD

**Issue by lientao** [labring/FastGPT#2823]
<img width="371" alt="SCR-20240927-nnym" src="https://github.com/user-attachments/assets/09d4f757-47bd-4146-a26e-cd8ff0a29592">

**Comment by lijiajun1997** [comment]
得改代码

**Comment by lientao** [comment]
> 得改代码

谢谢，看来SaaS用户是不行了。

**Comment by c121914yu** [comment]
关不掉
