### ISSUE TITLE
【急！】v4.8.3版本数据量超过5万条时，导出的数据缺失

### ISSUE THREAD

**Issue by Jonathanfdy** [labring/FastGPT#2825]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8.3
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
现在用的是v4.8.3版本，比较稳定，但近期发现，数据量目前在6万条左右（按照导出的csv行数），但只能导出5万条，后面的数据都无法导出和备份。这个后来才发现，如果早些发现我们可以增加新的知识库，但现在没有任何办法导出和备份数据了，问题很严重，请问在不升级版本的情况下如何解决？

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
二开代码，或者直接从数据库导出
