### ISSUE TITLE
关于对接chatgpt-on-wechat微信聊天窗口如何显示图片问题

### ISSUE THREAD

**Issue by silencezhang7** [labring/FastGPT#2826]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.11

**问题描述, 日志截图**
fastgpt对接chatgpt-on-wechat时，怎么把知识库检索出来的图片在微信上面直接显示呢，目前直接在fastgpt上面使用markdown格式能正常显示，但是对接chatgpt-on-wechat时却直接显示了!{图片}(https://xxxxxxx)，请问有什么思路吗
微信截图：
![11dbd7a4-6b8a-4bab-bf7f-96b897a7ee45](https://github.com/user-attachments/assets/8f1c7e5c-04d9-4340-b319-ccf610dada41)
fastgpt截图：
![image](https://github.com/user-attachments/assets/b95c5354-6446-4bc6-b650-e1fb5f6c7755)

**相关截图**

**Comment by c121914yu** [comment]
需要二开 cow，捕获图片，并发送图片

**Comment by silencezhang7** [comment]
> 需要二开 cow，捕获图片，并发送图片，发图片是有单独操作的，不确定 cow 是否支持。

感谢，已经对其进行二开
