### ISSUE TITLE
调用为集合批量添加数据接口后，实际添加的内容与接口参数中提交的内容不符

### ISSUE THREAD

**Issue by 17iu** [labring/FastGPT#2831]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.6 

**问题描述, 日志截图**
1. 调用接口：/api/core/dataset/data/pushData
2. 输入数据：{"collectionId":"66f76fe9baa538ef28decba7","trainingMode":"qa","data":[{"q":"可以免费用？","a":"可以免费用的"}]}
3. 输出数据：{"code":200,"statusText":"","message":"","data":{"insertLen":1,"overToken":[],"repeat":[],"error":[]}}
4. 实际被添加的内容与输入内容不符，看上去是相关的，但内容似乎是由AI产生的：
![image](https://github.com/user-attachments/assets/2cf17c61-ea69-4a56-8c20-a3f7ea2d8d39)
5. 测试添加了很多其他question和answer，有的时候1组qa会对应同时增加多组知识库qa到数据库，如调用接口时输入qa为：
{"collectionId":"66f76fe9baa538ef28decba7","trainingMode":"qa","data":[{"q":"有没有优惠","a":"没有优惠，请尽快下手"}]}
但实际被添加到集合中的内容如下：
![image](https://github.com/user-attachments/assets/f93ed032-53d8-413e-a942-0aeb6a1c25d9)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
你这是 QA 模式，是让模型自己总结生成。

**Comment by 17iu** [comment]
明白了，谢谢！
