### ISSUE TITLE
创建一个文件集合报404

### ISSUE THREAD

**Issue by sgwsgw** [labring/FastGPT#2837]
- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
**版本是：V4.7**
![c83ad7a83643a9bcfad71273f84b33d](https://github.com/user-attachments/assets/7f8077c8-6a0c-423e-abc2-c97b2961d24e)
![3bd9922e569c2fec3b1fd3e4b0283ae](https://github.com/user-attachments/assets/b1212839-82de-479d-9cb6-f8ecb20fd72d)

**Comment by c121914yu** [comment]
升级
