### ISSUE TITLE
只有AI回复节点，却一直显示多轮对话

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#2839]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/f232bfab-076e-401f-8e17-259b10b50f55)

只有AI回复节点，却一直显示多轮对话，导致回复混乱
**复现步骤**

**预期结果**

**相关截图**

**Comment by heart18z** [comment]
版本4.8.10

**Comment by c121914yu** [comment]
看详情就知道了
