### ISSUE TITLE
应用无法选择知识库

### ISSUE THREAD

**Issue by Ink-Osier** [labring/FastGPT#284]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√] 我已确认目前没有类似 issue
- [√] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [√] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√] 私有部署版本

**问题描述**
最新版无法在应用里选择知识库，单击后对应知识库选项会消失，但是无法选中

**复现步骤**
1. 创建知识库
2. 创建应用
3. 选择知识库

**预期结果**
能顺利选中知识库

**相关截图**

**Comment by c121914yu** [comment]
看看升级文档

**Comment by bruceye777** [comment]
需要发送一个POST请求，每次升级版本之前都要看看升级文档有什么额外操作
https://doc.fastgpt.run/docs/installation/upgrading/44/
升级好之后可以正常选择知识库，上面是已关联知识库，下面是未关联知识库
![image](https://github.com/labring/FastGPT/assets/41668200/95faac06-b66b-40b1-bb1b-deb7eb0d9b0c)

**Comment by Ink-Osier** [comment]
@c121914yu  @bruceye777 好的好的 谢谢两位大佬！
