### ISSUE TITLE
chat API如何实现流式输出（stream：true）

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#2852]
通过API调用fastgpt应用，如果stream:false，运行ok，前端页面可以正常一次性输出结果。

希望前端页面实现流式输出的效果
将stream:true
后端程序日志已经收到了流式输出的信息，但最终还是报错。
data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":"准备"},"index":0,"finish_reason":null}]}

data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":"启动"},"index":0,"finish_reason":null}]}

data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":""},"index":0,"finish_reason":null}]}

data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":"\n"},"index":0,"finish_reason":null}]}

data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":""},"index":0,"finish_reason":null}]}

data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{},"index":0,"finish_reason":"stop"}]}

data: [DONE]

ERROR:__main__:Error processing chat service response: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:172.16.1.219 - - [03/Oct/2024 11:25:17] "POST /upload HTTP/1.0" 500 -

**Comment by MugCode** [comment]
所以是什么解决的？

**Comment by MusicOfWind** [comment]
> 通过API调用fastgpt应用，如果stream:false，运行ok，前端页面可以正常一次性输出结果。
> 
> 希望前端页面实现流式输出的效果 将stream:true 后端程序日志已经收到了流式输出的信息，但最终还是报错。 data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":"准备"},"index":0,"finish_reason":null}]}
> 
> data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":"启动"},"index":0,"finish_reason":null}]}
> 
> data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":""},"index":0,"finish_reason":null}]}
> 
> data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":"\n"},"index":0,"finish_reason":null}]}
> 
> data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"role":"assistant","content":""},"index":0,"finish_reason":null}]}
> 
> data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{},"index":0,"finish_reason":"stop"}]}
> 
> data: [DONE]
> 
> ERROR:**main**:Error processing chat service response: Expecting value: line 1 column 1 (char 0) INFO:werkzeug:172.16.1.219 - - [03/Oct/2024 11:25:17] "POST /upload HTTP/1.0" 500 -

能说一下怎么实现流式输出吗
