### ISSUE TITLE
镜像image fastgpt/fastgpt-sandbox:latest无法拉取

### ISSUE THREAD

**Issue by wenyaodong777** [labring/FastGPT#2855]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.9
- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
[root@reexuan-front-07service fastgpt]# docker-compose up -d
Pulling pg (registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.7.0)...
Trying to pull repository registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector ... 
v0.7.0: Pulling from registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector
b0a0cf830b12: Pull complete
b311dac095c3: Pull complete
36163cea98c3: Pull complete
fe401a45083b: Pull complete
b4f63e66f657: Pull complete
9a8245430c33: Pull complete
74c893d239e5: Pull complete
789ed9a95b21: Pull complete
5b691e4e12b4: Pull complete
e502d5360f88: Pull complete
0292671f3c2d: Pull complete
5247a27db111: Pull complete
b3a42a5269c3: Pull complete
5fc19b802589: Pull complete
973f95d4f335: Pull complete
694339e21380: Pull complete
Digest: sha256:27df42f0d0be8d5623ff1aea5fea7134e175af1cdef62d9df00b322a3c85edc9
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.7.0
Pulling mongo (registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18)...
Trying to pull repository registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo ... 
5.0.18: Pulling from registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo
99803d4b97f3: Pull complete
6653ceb22977: Pull complete
e067c5774dde: Pull complete
3f2512535c9b: Pull complete
95823dd64119: Pull complete
806644aafaf1: Pull complete
b6eb4ecca0a2: Pull complete
a85fb80d261c: Pull complete
b8e25023b418: Pull complete
Digest: sha256:2b7e5f3ddc4f4707cdf72bd55e50a0dbd34b5832e5e97d9fdf5adc19abebf068
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18
Pulling sandbox (registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt-sandbox:latest)...
Trying to pull repository registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt-sandbox ... 
Pulling repository registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt-sandbox
ERROR: Error: image fastgpt/fastgpt-sandbox:latest not found
**复现步骤**
拉取config.json
拉取curl -o docker-compose.yml https://raw.githubusercontent.com/labring/FastGPT/main/files/docker/docker-compose-pgvector.yml
执行docker-compose up -d
**预期结果**
镜像拉取成功
**相关截图**
件日志

**Comment by c121914yu** [comment]
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/82eb0218-f349-4b54-bb8f-5be4c40a5339">
未复现噢

**Comment by c121914yu** [comment]
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/7e419312-c76e-44d4-bfed-f5e201ffd1d8">
