### ISSUE TITLE
版本显示有问题

### ISSUE THREAD

**Issue by dreamfly32** [labring/FastGPT#2857]
版本：v4.8.11-alpha2，
问题：页面显示版本号为4.8.10，（我确信显示有问题，因为我回退到4.8.9显示是正确的），不过这应该不影响代码运行模块里的strToBase64吧，怎么说此函数没定义？

我的场景是，将AI回复内容转文档，由于[2689](https://github.com/labring/FastGPT/issues/2689) 不支持，所以想出此办法。
另外能不能支持zlib 库，用于压缩字符串。
估计不会支持吧，太小众了😂

![image](https://github.com/user-attachments/assets/e048d5de-82b3-42be-b9f3-2d44b0af38a3)
![image](https://github.com/user-attachments/assets/41f7ee35-d4dc-4547-811b-bac9184d9274)
![image](https://github.com/user-attachments/assets/6a9623ff-3d4e-4e3f-ab75-5b084bbbff85)

**Comment by c121914yu** [comment]
alpha 版本不更新版本号

**Comment by c121914yu** [comment]
strToBase64 是 4.8.11 的，你没升级 sandbox

**Comment by c121914yu** [comment]
压缩字符串可以，但是不能压缩文件～ 没地方存
