### ISSUE TITLE
内容提取组件无法提取参数

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#2859]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.10

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/9b0dde77-43a8-444a-90c0-68987522f553)
![image](https://github.com/user-attachments/assets/3a08ce9f-ddbf-46c6-a37f-020b971e6f34)
同样的模型情况下，本地部署的版本无法进行内容提取
是我config配置文件不对吗
    {
      "model": "qwen-turbo", 
      "name": "qwen-turbo", 
      "avatar": "/imgs/model/qwen.svg", 
      "maxContext": 8000,
      "maxResponse": 4000,
      "quoteMaxToken": 4000, 
      "maxTemperature": 1.2, 
      "charsPointsPrice": 0, 
      "censor": false, 
      "vision": false,
      "datasetProcess": true, 
      "usedInClassify": true, 
      "usedInExtractFields": true,
      "usedInToolCall": true,
      "usedInQueryExtension": true, 
      "toolChoice": true,
      "functionCall": true, 
      "customCQPrompt": "", 
      "customExtractPrompt": "", 
      "defaultSystemChatPrompt": "", 
      "defaultConfig":{}  
    },
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
https://doc.tryfastgpt.ai/docs/development/faq/#%E5%85%B6%E4%BB%96%E6%A8%A1%E5%9E%8B%E6%B2%A1%E6%B3%95%E8%BF%9B%E8%A1%8C%E9%97%AE%E9%A2%98%E5%88%86%E7%B1%BB%E5%86%85%E5%AE%B9%E6%8F%90%E5%8F%96 看文档
