### ISSUE TITLE
nginx代理后文档解析报404

### ISSUE THREAD

**Issue by 305607610** [labring/FastGPT#2867]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.10-fix2

**问题描述, 日志截图**
nginx代理后调用 /api/v1/chat/completions 接口上传文件文档解析时 报404错误
请求信息如下
![image](https://github.com/user-attachments/assets/1bb43d49-ec96-4a4b-b575-e6f38de17b6f)

不使用nginx代理 文档解析是正常的

![image](https://github.com/user-attachments/assets/10240523-d421-4ec7-b088-247d5aea8559)
![image](https://github.com/user-attachments/assets/34a5b71e-eb31-4f9a-acce-9d3551d50066)

nginx配置如下
http://10.18.31.135:13000/ 是fastgpt的部署地址
![image](https://github.com/user-attachments/assets/fc85b995-d608-4b3c-9fc5-23354daa73d9)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
不支持 2 级路由

**Comment by rocymp** [comment]
最新版本依然存在该问题。

**Comment by rocymp** [comment]
找到问题了。文件读取代码做了相对路径判断和截断。

**Comment by Axingx** [comment]
> 找到问题了。文件读取代码做了相对路径判断和截断。

所以是怎么解决的最终？我现在也遇到了这个问题
