### ISSUE TITLE
接入rerank模型知识库检索调用重排时报错 object of type 'NoneType' has no len() INFO:    172.17.0.1:36218 - "POST /v1/rerank HTTP/1.1" 200 OK

### ISSUE THREAD

**Issue by MusicOfWind** [labring/FastGPT#2881]
fastgpt 版本：v4.6.7
rerank 版本：官网的 docker 镜像 registry.cn-hangzhou.aliyunccs.com/fastgpt/bge-rerank-base:v0.1
linux 使用 curl 测试能正常得到结果：
curl -X 'POST' \
  'http://192.168.50.63:6006/v1/rerank' \
  -H 'Authorization: Bearer sk-aaaabbbcccdddeeeefffggghhhiiijjjkkkk' \
  -H 'Content-Type: application/json' \
  --data '{
	  "query": "who are you",
	  "documents": ["I want to go to sleep",
	  "I am Bob",
	  "Today is Friday"]
  }'
config.json 该部分配置：
"reRankModels": [
        {
            "model": "bge-reranker-base",
            "name": "reranker", 
            "charsPointsPrice": 0,
            "requestUrl": "http://192.168.50.63:6006/v1/rerank",
            "requestAuth": "sk-aaaabbbcccdddeeeefffggghhhiiijjjkkkk"
        }
    ]
知识库使用重排时前端都显示正常，但是查看 rerank 容器 log 有报错：
object of type 'NoneType' has no len() 
INFO: 172.17.0.1:36218 - "POST /v1/rerank HTTP/1.1" 200 OK

**Comment by c121914yu** [comment]
v4.6.7 无法使用registry.cn-hangzhou.aliyunccs.com/fastgpt/bge-rerank-base 镜像，可以翻下文档变更记录，有个个人的镜像。ruanshaotong/xxx 好像
