### ISSUE TITLE
内容提取组件-提取数组格式报错

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#2883]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
内容提取组件-提取数组格式报错
![image](https://github.com/user-attachments/assets/94cfbd7f-53f0-4a7c-a158-5dc031298dbb)
![image](https://github.com/user-attachments/assets/98105a7b-577f-40ac-a911-9f2173b063c6)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
得检查这个模型支不支持数组类型
