### ISSUE TITLE
调用API上传csv文件类型的模板 不会拆分 问答？

### ISSUE THREAD

**Issue by sgwsgw** [labring/FastGPT#2884]
![image](https://github.com/user-attachments/assets/58dcb43e-a614-4f61-8871-e7c0c73e0627)
![image](https://github.com/user-attachments/assets/ed9e8040-7c63-4fbe-bdd3-6f254ecaf5cc)
![image](https://github.com/user-attachments/assets/a1425186-b94a-4365-bd83-5517eceb95b0)
![image](https://github.com/user-attachments/assets/92a976ea-2021-4bfd-9940-9219837e1e1a)
如图，同样的模板文件，通过1直接用后台上传 就能够准确的直接拆分。而通过API上传的 直接拆分 就有问题，这是为什么？？文件都是同一个文件。

**Comment by c121914yu** [comment]
这个接口是拆文件的呀

**Comment by zhouxihong1** [comment]
这个接口是对应UI上传的文本类型数据，表格类型的数据好像没有openAPI提供，我的做法是，抓包之后自己实现一个，涉及到两个接口，/api/common/file/upload和/api/core/dataset/collection/create/csvTable

**Comment by c121914yu** [comment]
> 这个接口是对应UI上传的文本类型数据，表格类型的数据好像没有openAPI提供，我的做法是，抓包之后自己实现一个，涉及到两个接口，/api/common/file/upload和/api/core/dataset/collection/create/csvTable

table 的话，可以通过 pushData 传。

**Comment by sgwsgw** [comment]
> 这个接口是拆文件的呀，只有问答拆分和直接分段两种格式。

我的意思就是 我调用API 设置 问答拆分的格式，但是它并没有根据问答 格式 来拆分啊。用的文件 就是你们提供的模板文件
