### ISSUE TITLE
文本数据集-网页链接导入飞书文档，没有对飞书文档正确切片

### ISSUE THREAD

**Issue by hsx1612727380** [labring/FastGPT#2889]
**master分支独立部署**

**预期结果**
飞书文档中文字信息都是没有，应该根据具体的文档内容获取数据，只获取了<iframe >

**相关截图**
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by hsx1612727380** [comment]
上面的截图发现上传看不到，重新上传下
![image](https://github.com/user-attachments/assets/182f72a3-372c-4bf7-b8a6-fdeb3f36d4fa)
![image](https://github.com/user-attachments/assets/228b84ff-4b1f-4847-a6da-4cc37bc914e4)

**Comment by c121914yu** [comment]
飞书文档不是静态网页，不支持获取
