### ISSUE TITLE
用户选择组件希望可以进行输入阻塞

### ISSUE THREAD

**Issue by heart18z** [labring/FastGPT#2894]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/6434524e-9621-46d8-930d-b43ab0ffd26a)
如果开启了用户选择组件，但是用户没有选择继续提问会导致在输出为空，
调整逻辑应该是可以手动设定 强制用户是否需要选择
1. 如果用户不需要强制选择，则聊天框可正常对话
2. 如果用户需要强制选择，则聊天框没有发送按钮
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
4.8.11 BUG，修复下：https://github.com/labring/FastGPT/commit/99d7b339dd3ac7f8f273a5698ac015643ed47d19
