### ISSUE TITLE
工具调用子应用，关于回复显隐的疑问？

### ISSUE THREAD

**Issue by Zhenyi-Wang** [labring/FastGPT#2901]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.11-fix

**问题描述, 日志截图**

新版的应用可以作为工具挂载，个人认为非常好，但在使用中有一些疑问。

测试的配置很简单，如下
主应用：
![image](https://github.com/user-attachments/assets/809130f4-b180-4b1f-b000-5e26b53683da)

子应用
![image](https://github.com/user-attachments/assets/d9336d15-9cf7-4ffa-8cb5-e20d140c34e5)

关于子应用的“返回AI内容”和“禁用流输出”功能：

---
### 情景1：关闭 “返回AI内容”
![image](https://github.com/user-attachments/assets/b6893806-9356-4888-9e85-7e5146d7f570)

在这种情况下，无论是否开启“禁用流输出”，主应用都无法接收到任何反馈。

不太了解使用场景。。

---
### 情景2：打开“返回AI内容”，关闭 “禁用流输出”
这时，在调试界面和免登陆窗口中，显示的逻辑不一致：
![image](https://github.com/user-attachments/assets/10a95023-0331-4da9-afe2-61bd8eb60304)

开发人员可能会误以为，用户能够看到子应用的回复。
但实际上用户只能短暂看到回复，然后内容就突然消失了。

我还试了API的流式响应，发现answer似乎没有区分是否来源于工具调用，只是在过程中有一个toolResponse。是要手动匹配string来区别吗？
![image](https://github.com/user-attachments/assets/57ad9d08-f156-4a6e-9295-337833001768)

这种情况有些奇怪，似乎没有充分考虑。

---
### 情况3：打开“返回AI内容”，打开 “禁用流输出”
这时，子应用的表现比较像一个普通的插件，默默执行，默默返回响应，然后主应用来回复。没有任何问题。

---
### 使用“工具调用终止”的场景
![image](https://github.com/user-attachments/assets/5f4c5aa9-38c7-478d-8b6a-2abe1812ed14)

有时候，我希望让子应用回复，主应用只作为调度。
特别是子应用回复比较长的时候，用户不需要等很久，我也可以节省一些token。
但是由于 情景2 提到的问题，回复最终会被隐藏，变成空白。
![image](https://github.com/user-attachments/assets/42aa8c26-11b2-401d-891a-8cbf9995cc3f)

不知新版是否会对这些问题进行调整？

感谢大佬们辛勤投入，为你们点赞！

**复现步骤**

**预期结果**

**相关截图**

**Comment by Zhenyi-Wang** [comment]
对了，使用“工具调用终止”，AI回复为空，好像还会导致这个问题 https://github.com/labring/FastGPT/issues/2899

**Comment by c121914yu** [comment]
应该是应用调用时候，结果存储问题，新版我做了些调整，测试下这个问题。

**Comment by c121914yu** [comment]
在嵌套子应用调用中，工具调用会取子应用输出的内容作为工具结果（也就是，单独运行子应用时，对话框可以看到的内容）
情景 1： 不一定是 AI 对话，可能是指定回复之类的。
情景 2：修复了下，如下图
工具终止：也是同一个 PR 解决

<img width="736" alt="image" src="https://github.com/user-attachments/assets/3f29361e-16a1-41ae-bb11-92b6336d2c6f">
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/d269b1c8-5991-4f27-853d-7ed8f76acead">

**Comment by c121914yu** [comment]
可以使用这个 pr 的镜像测试：ghcr.io/labring/fastgpt-pr:2903
