### ISSUE TITLE
打包报错，has no exported member 'AiChatQuotePrompt'

### ISSUE THREAD

**Issue by 2277419213** [labring/FastGPT#2902]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.11
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.11-fix

**问题描述, 日志截图**
打包报错
```
./src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx:31:3
44.76 Type error: Module '"@fastgpt/global/core/workflow/template/system/aiChat"' has no exported member 'AiChatQuotePrompt'.
44.76
44.76   29 | import type { AiChatQuoteRoleType } from '@fastgpt/global/core/workflow/template/system/aiChat/type';
44.76   30 | import {
44.76 > 31 |   AiChatQuotePrompt,
44.76      |   ^
44.76   32 |   AiChatQuoteRole,
44.76   33 |   AiChatQuoteTemplate
44.76   34 | } from '@fastgpt/global/core/workflow/template/system/aiChat';
44.87 /app/projects/app:
44.87  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  app@4.8.11.1 build: `next build`
```
**复现步骤**
执行docker build
**预期结果**
不报错
**相关截图**
![image](https://github.com/user-attachments/assets/0c8de20e-d0a5-4315-aea3-9454ee9861fa)

**Comment by c121914yu** [comment]
未遇到，检查是不是和丢了代码

**Comment by 2277419213** [comment]
> 未遇到，检查是不是和丢了代码

已检查，代码没有合并漏，直接打包完整的4.8.11也会出现这种情况，还有大佬，4.8.11版本更改了权限架构，新增了group，这个哪里可以权限关系不

**Comment by c121914yu** [comment]
> > 未遇到，检查是不是和丢了代码
> 
> 已检查，代码没有合并漏，直接打包完整的4.8.11也会出现这种情况，还有大佬，4.8.11版本更改了权限架构，新增了group，这个哪里可以权限关系不

那不应该，那为啥 github action 能打包～ 肯定是你环境有问题。
开源版没有权限控制。
