### ISSUE TITLE
docker-compose镜像拉取失败，镜像源不存在

### ISSUE THREAD

**Issue by Aloee1** [labring/FastGPT#2904]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
使用官方文档的docker-compose拉取镜像，都提示镜像源不存在。网络连接没问题，vpn开了和关了都试了。
![image](https://github.com/user-attachments/assets/7f08a422-e199-4705-b296-7b71a7569bbf)

![Uploading image.png…]()

**复现步骤**

**预期结果**

**相关截图**

**Comment by Aloee1** [comment]
![image](https://github.com/user-attachments/assets/fc7956c5-140c-4c4f-bfef-cb032e4701d6)

**Comment by Aloee1** [comment]
求助各位佬

**Comment by c121914yu** [comment]
latest 肯定不存在，这是备份镜像，只有文档里的一个，其他版本自行官方找
