### ISSUE TITLE
SyntaxError: Unexpected token is not valid JSON

### ISSUE THREAD

**Issue by letacada** [labring/FastGPT#2912]
![07a61d1d43f91b05c4f36c7828c0036](https://github.com/user-attachments/assets/64031cdc-acd6-409a-bd6e-bcb32af62e78)
有人遇到相同的问题吗？ 求解答

**Comment by c121914yu** [comment]
模型返回的 JSON 不对，换个好点的模型

**Comment by c121914yu** [comment]
还有吧 issue 基础信息补全再发问题。
