### ISSUE TITLE
QA对类型知识库，能否设置只检索问题，不检索答案。

### ISSUE THREAD

**Issue by glimmer1998** [labring/FastGPT#2917]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.2

**问题描述, 日志截图**
上传QA对类型的csv和文本类型的文件共同作为知识库，在检索时，发现QA中已有的问题的向量相似度匹配度比较低。

推测原因：QA对形式的数据集会将Q和A内容共同作为检索内容，但是在提问时，往往单独输入Q，所以匹配会降低。

单独添加问题为自定义索引可以解决这个问题，但比较麻烦。请问有没有其他方法，或者设置只检索问题，不检索答案？

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
使用更新版本，会自动添加索引。（具体是多少忘了
<img width="1093" alt="image" src="https://github.com/user-attachments/assets/ae28811d-6bb9-440d-9ced-370d74a9a251">

**Comment by ChiuHsin** [comment]
是的，最好可以有个选项，要不要把答案进行索引
