### ISSUE TITLE
http模块无法提取

### ISSUE THREAD

**Issue by he-bowen** [labring/FastGPT#2920]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.11

**问题描述, 日志截图**
http无法提取
![image](https://github.com/user-attachments/assets/b83591c6-5461-4ac5-a34e-544b469ce893)
![image](https://github.com/user-attachments/assets/2e683c16-b567-4554-ad8e-21af70f2595b)

**复现步骤**
http提取数组内容所有节点

**预期结果**
期望可以修复

**相关截图**

**Comment by c121914yu** [comment]
没这个语法，写代码解决

**Comment by SDAIer** [comment]
这个可否使用新版本的循环插件处理

**Comment by he-bowen** [comment]
> 写代码解决

写代码太考验JS能力，期望HTTP模块能够完全实现类APIFOX的格式，通过 代码模块 期望可以增加 Python代码运行能力

**Comment by ans1988dog** [comment]
要是支持python运行真就好了

**Comment by ans1988dog** [comment]
要是支持python那可太方便了

**Comment by SDAIer** [comment]
在外面写py，用http调用也不麻烦。
就算是支持py，也是轻量化的，很多模块无法导入



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月15日(周二) 下午5:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] http模块无法提取 (Issue #2920)




 
要是支持python那可太方便了
