### ISSUE TITLE
工作流-知识库搜索模块-无法显示变量引用选择的具体选项

### ISSUE THREAD

**Issue by hope-dreaming** [labring/FastGPT#2924]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√ ] 我已确认目前没有类似 issue
- [√ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [√ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ √] 私有部署版本, 具体版本号: 
阿里云主镜象
**问题描述, 日志截图**
工作流-知识库搜索模块-无法显示变量引用选择的具体选项

**复现步骤**
1. 添加知识库搜索模块，选择变量引用
![屏幕截图 2024-10-15 145336](https://github.com/user-attachments/assets/a5be4563-0a4f-43b3-befc-c9714ef05274)

**预期结果**
![屏幕截图 2024-10-15 145242](https://github.com/user-attachments/assets/6f131fb4-767e-48c6-946e-0d8e43b2f2d0)

**相关截图**

**Comment by hope-dreaming** [comment]
那请问在工作流中怎么拼接数组使得知识库搜索模块可以根据id选择到知识库啊

**Comment by hope-dreaming** [comment]
> 知识库不推荐引用模式，除非特殊情况，自己代码拼接数组 [{datasetId:'xxx'}]

拼接的变量仍然不能被知识库的变量引用模块检测到

**Comment by c121914yu** [comment]
> > 知识库不推荐引用模式，除非特殊情况，自己代码拼接数组 [{datasetId:'xxx'}]
> 
> 拼接的变量仍然不能被知识库的变量引用模块检测到

<img width="980" alt="image" src="https://github.com/user-attachments/assets/0483c2bf-f7ec-4d4b-8656-6b2bd5599048">
这不就可以了

**Comment by hope-dreaming** [comment]
> > > 知识库不推荐引用模式，除非特殊情况，自己代码拼接数组 [{datasetId:'xxx'}]
> > 
> > 
> > 拼接的变量仍然不能被知识库的变量引用模块检测到
> 
> <img alt="image" width="980" src="https://private-user-images.githubusercontent.com/50446880/377034731-0483c2bf-f7ec-4d4b-8656-6b2bd5599048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzk4NjgsIm5iZiI6MTcyOTA3OTU2OCwicGF0aCI6Ii81MDQ0Njg4MC8zNzcwMzQ3MzEtMDQ4M2MyYmYtZjdlYy00ZDRiLTg2NTYtNmIyYmQ1NTk5MDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExNTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZGU4OWY3NzVkMmI0ZWNiN2JiYmU3MGYwMDEyMTQ3ZjkzYTczMjAxYWJiNTdhNGViZjk0NDU1OTUzN2MwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nmJpoxqwWICpWHAg1tHJI9u0kyjM9lojNsFNZdYMT8A"> 这不就可以了

非常感谢

**Comment by ayellowhuang** [comment]
> 知识库不推荐引用模式，除非特殊情况，自己代码拼接数组 [{datasetId:'xxx'}]

牛逼了我的哥，感谢！
