### ISSUE TITLE
fastgpt调用ollama的qwen2.5:3b提示失败，oneapi测试正常，工作流调试也正常

### ISSUE THREAD

**Issue by yixiuquan** [labring/FastGPT#2929]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
FastGpt V4.8.11，oneapi 0.6.8。ubuntu docker 安装的ollama，ollama运行的qwen2.5:3b。
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
fastgpt调用ollama的qwen2.5:3b提示失败，而oneapi测试正常，工作流调试也正常
**复现步骤**
1、oneapi中添加qwen2.5:3b的渠道
2、fastgpt中config.local.json中增加qwen2.5:3b的模型配置
3、创建应用、工作流并使用qwen2.5:3b
4、应用测试聊天报错LLM model response empty
5、工作流调试一步步走，可以正常走通
**预期结果**
都应该调用走通
**相关截图**
工作流调用成功：
![image](https://github.com/user-attachments/assets/e9f7e1d9-e4bd-4118-8a81-7174587b67c5)
![image](https://github.com/user-attachments/assets/e9c539da-99c0-4152-a718-6c7d7639a349)
oneapi调用成功：
![image](https://github.com/user-attachments/assets/8d009ed5-8601-4865-8711-502c23bac018)
fastgpt config.local.json截图：
![image](https://github.com/user-attachments/assets/1cb66687-45ac-418c-96f6-551de1ae16b1)
fastgpt调用失败截图：
![image](https://github.com/user-attachments/assets/c9b49f09-9f39-4b57-b6d9-0fbed32266a1)
fastgpt调用失败时oneapi截图：
![image](https://github.com/user-attachments/assets/9c88550e-e89b-48ae-a1aa-94bbfd7dad89)
fastgpt调用ollama报错后台日志：
![image](https://github.com/user-attachments/assets/2bebac7c-a4d7-4170-bebe-51739437a746)
工作流调试调用成功fastgpt后台日志：
![image](https://github.com/user-attachments/assets/16f34a51-1f19-4181-93a1-7d4af8feca9b)
工作流调试调用成功oneapi日志：
![1729045311067](https://github.com/user-attachments/assets/bec54be1-f639-4b88-bdd5-02d538eefbbb)
工作流调试调用成功
![image](https://github.com/user-attachments/assets/eff78551-af0b-4515-bfeb-72364cb3948b)

**Comment by c121914yu** [comment]
文档里教程的测试结果呢？

**Comment by c121914yu** [comment]
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/b714edea-cc88-44a7-a80f-cc42ecee7816">
先根据文具测试完

**Comment by LuckLittleBoy** [comment]
ollama 工具调用不支持 stream流式调用，而且qwen2.5模型本身也有点问题。https://github.com/QwenLM/Qwen2.5/issues/1012
