### ISSUE TITLE
4.8.11版本，BI图表插件，无法选择代码运行节点返回的变量

### ISSUE THREAD

**Issue by yahoolcj** [labring/FastGPT#2938]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [4.8.11 ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
使用插件 ：BI图表功能，连接到代码运行节点后，无法选择代码运行节点返回的变量
![ae67df9e6746944403f1eb327ea4abe](https://github.com/user-attachments/assets/bfba1ce0-c28b-4cc7-a2c4-64f8cdf4d28f)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
这不是数据类型都不一样
