### ISSUE TITLE
rerank排序问题

### ISSUE THREAD

**Issue by chobitsX** [labring/FastGPT#2940]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8

**问题描
![20241016-171221](https://github.com/user-attachments/assets/b75ccd68-a7d2-4719-8508-8b7998e474ed)
述, 日志截图**

**复现步骤**
使用rerank结果重排即可
**预期结果**
下面的综合排名应该排在上面那个前面才对
**相关截图**

**Comment by c121914yu** [comment]
未发现改问题，升级到最新版进行测试。

**Comment by chobitsX** [comment]
> 未发现该问题，有可以复现的例子？ 4.8 版本太旧了，升级到最新版进行测试，旧版本只能自行 debug。

目前最新版本就是4.8.11吧，我上面第三位版本号忘记打了而已呢，你们那边没办法复现rerank比较高但综合排序很低的问题么

**Comment by c121914yu** [comment]
> > 未发现该问题，有可以复现的例子？ 4.8 版本太旧了，升级到最新版进行测试，旧版本只能自行 debug。
> 
> 目前最新版本就是4.8.11吧，我上面第三位版本号忘记打了而已呢，你们那边没办法复现rerank比较高但综合排序很低的问题么

rerank 排前，但是综合低是正常的。但是第二个图中，排名 73 不太对的问题，我还没复现。

**Comment by chobitsX** [comment]
> > > 未发现该问题，有可以复现的例子？ 4.8 版本太旧了，升级到最新版进行测试，旧版本只能自行 debug。
> > 
> > 
> > 目前最新版本就是4.8.11吧，我上面第三位版本号忘记打了而已呢，你们那边没办法复现rerank比较高但综合排序很低的问题么
> 
> rerank 排前，但是综合低是正常的。但是第二个图中，排名 73 不太对的问题，我还没复现。

有办法可以使用rerank排名为主么，比如我就是想用rerank得排名来作为最终的排序

**Comment by c121914yu** [comment]
> > > 未发现该问题，有可以复现的例子？ 4.8 版本太旧了，升级到最新版进行测试，旧版本只能自行 debug。
> > 
> > 
> > 目前最新版本就是4.8.11吧，我上面第三位版本号忘记打了而已呢，你们那边没办法复现rerank比较高但综合排序很低的问题么
> 
> rerank 排前，但是综合低是正常的。但是第二个图中，排名 73 不太对的问题，我还没复现。

改代码逻辑
