### ISSUE TITLE
向量模型页面上不展示全部模型类型

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#2941]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
config.json 定义向量模型的相关截图：
![image](https://github.com/user-attachments/assets/1e68d4bc-fb11-4c59-8b7a-9b287007f188)
前端页面展示向量模型：
![image](https://github.com/user-attachments/assets/172d7971-80d2-4ff5-8ae4-4bde32fb108c)
问题：
只显示了moka-m3e-large，没有显示text2vec-embedding-model
**复现步骤**

**预期结果**

**相关截图**

**Comment by xiaoToby** [comment]
@c121914yu

**Comment by c121914yu** [comment]
没重启，自个按文档检查配置文件加载
