### ISSUE TITLE
长文本输入后，最大响应 tokens自动默认为200，导致回复被截断

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#2942]
4.8.11-fix

AI+文档解析，AI配置中设置回复上限1950。
![image](https://github.com/user-attachments/assets/9013f12f-500a-41e7-841f-f46c0e8331dd)

### 问题1、如果输入的文件内容较少，AI回复正常。
通过以下oneapi log发现，promptTokens=5122, completionTokens=421，AI正常完成回复信息。

```shell
[INFO] 2024/10/16 - 13:16:34 | 202410161316242480038804280722 | record consume log: userId=1, channelId=23, promptTokens=5122, completionTokens=421, modelName=glm4:9b, tokenName=Initial Root Token, quota=166290, content=模型倍率 30.00，分组倍率 1.00，补全倍率 1.00
```

![image](https://github.com/user-attachments/assets/292b2b11-a87b-4f41-a8fb-fbe5f9ba1923)

### 问题2、如果输入的文件内容较多，AI只回复200tokens （更换了本地模型和阿里在线模型问题一样，oneapi   completionTokens以及AI查看详情--最大响应 tokens都是200）
通过以下oneapi log发现，promptTokens=52919, completionTokens=200（每次都是200），AI不能完整回复。

```sh
[INFO] 2024/10/16 - 13:10:18 | 2024101613080342515017285425314 | record consume log: userId=1, channelId=23, promptTokens=52919, completionTokens=200, modelName=glm4:9b, tokenName=Initial Root Token, quota=1593570, content=模型倍率 30.00，分组倍率 1.00，补全倍率 1.00
```
![image](https://github.com/user-attachments/assets/76da0540-9b67-4d54-a93a-878d5e0394d7)

**Comment by c121914yu** [comment]
那不就意味着，你得换一个更大点模型了么？已经 oversize 了

**Comment by SDAIer** [comment]
多谢回复。模型的大小没有问题。
我用本地模型可以支持128k上下文，而我输入的只有59k上下文。
另外，我也用了阿里在线qwen72b模型，上下文不到6k，也是同样的问题，最大响应 tokens:自动变为200
![image](https://github.com/user-attachments/assets/75083774-5e08-4886-b169-a823452a1acc)

**Comment by c121914yu** [comment]
<img width="942" alt="image" src="https://github.com/user-attachments/assets/b53afb19-9064-428f-9506-ea9ef8545cb8">
那就是你自个配置有问题了

**Comment by SDAIer** [comment]
你好。请问“128k 模型不配 128k 上下文”----这句话什么意思？

关于你上面提到的公式我的确有点懵，跟我之前理解的不一样。

请教下，如果按照以下设置
1、流程中，AI配置--回复上限：1950
2、模型最大支持上下文128k（已经通过num_ctx参数传递给ollama，查看ollama日志已经生效）

如果此时输入的上下文大小是59k左右（就是提示词+文档解析的内容），如果让模型详细总结，模型是否应该可以正常回复大于200个token。为什么此时自动变为200了？

![image](https://github.com/user-attachments/assets/ae7e8ecd-3ed9-4e56-90cc-77754e6223c3)

我用本地模型和在线模型都是同样的问题。
请问，这个问题我该如何排错

**Comment by SDAIer** [comment]
我发现问题了，config.json中maxContext配置的有点小导致的。

另外，请教下，我上面描述中，
oneapi log：completionTokens=200 以及AI-查看详情--最大响应tokens200
这个200是怎么来的？是模型返回的吗？还是fastgpt通过模型识别oversize 后自动设置为200？
