### ISSUE TITLE
通过调用猜你想问api返回403

### ISSUE THREAD

**Issue by JOEWJ** [labring/FastGPT#2949]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.9

**问题描述, 日志截图**
调用猜你想问api返回403：
![image](https://github.com/user-attachments/assets/cb5ba854-a5c9-4219-a686-453bb1e4a254)

**复现步骤**
应用已打开猜你想问且已发布
![image](https://github.com/user-attachments/assets/4a71c6e3-9092-458d-876e-56d124cc49f1)
![image](https://github.com/user-attachments/assets/c736ad36-aeec-41bb-bf6c-d6baa9bba99b)
postman的Headers已填写且反复核对过
![image](https://github.com/user-attachments/assets/191f9258-9aeb-4b38-9cfe-ae0a01cb0794)

**预期结果**

**相关截图**

**Comment by gith-u-b** [comment]
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/fb35d9cb-fc38-4370-aa6d-bbe80fed8f17">

**Comment by newfish-cmyk** [comment]
4.8.12以后版本才支持

**Comment by gith-u-b** [comment]
> 4.8.12以后版本才支持

这次4.8.12版本会支持吗？
