### ISSUE TITLE
跑着跑着报错了

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#2954]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7
- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
截图是两个bug
bug1
{
  message: '502  (request id: 20241018023925328530613TR96mAeq)',
  stack: 'Error: 502  (request id: 20241018023925328530613TR96mAeq)\n' +
    '    at eI.generate (/app/projects/app/.next/server/chunks/28687.js:25:70210)\n' +
    '    at af.makeStatusError (/app/projects/app/.next/server/chunks/28687.js:25:81687)\n' +
    '    at af.makeRequest (/app/projects/app/.next/server/chunks/28687.js:25:82610)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Object.A [as chatNode] (/app/projects/app/.next/server/chunks/47671.js:129:1115)\n' +
    '    at async N (/app/projects/app/.next/server/chunks/47671.js:130:2771)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async P (/app/projects/app/.next/server/chunks/47671.js:130:4100)\n' +
    '    at async /app/projects/app/.next/server/pages/api/v1/chat/completions.js:1:4234'
}

bug2
update apiKey totalPoints error l [MongoNetworkError]: connection 459597 to ip地址:27017 closed
    at S.onClose (/app/projects/app/.next/server/chunks/29066.js:6:127541)
    at Socket.<anonymous> (/app/projects/app/.next/server/chunks/29066.js:6:126714)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:323:12) {
  [Symbol(errorLabels)]: Set(0) {}
}
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/a3894ef0-fcb2-42f5-a3a4-e96d72a26dc3)
![image](https://github.com/user-attachments/assets/48cde53c-d8cf-49d6-9e7a-60d7fde1a6a7)

**Comment by c121914yu** [comment]
oneapi 报错，自己检查
