### ISSUE TITLE
本地部署时，新建应用时页面出现Application error: a client-side exception has occurred (see the browser console for more information).错误

### ISSUE THREAD

**Issue by lgvt369** [labring/FastGPT#2959]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.11

**问题描述, 日志截图**
打开页面时出现了如下报错
Application error: a client-side exception has occurred (see the browser console for more information)

**复现步骤**
工作台-新建-工作流-创建空白工作流
**预期结果**
正常显示页面
**相关截图**
![image](https://github.com/user-attachments/assets/f2d3642b-4bff-45e8-bc50-01d34050cbff)

**Comment by silencezhang7** [comment]
好像确实

**Comment by bg9cxn** [comment]
我这边测试应该是浏览器版本太老的问题。我也是私有化部署，内网不能上互联网，用Chrome 96.0版本会出现问题，改用Chrome 109.0或者Firefox115版本就没问题了。
一般内网不能上互联网的话，浏览器版本都会比较老...

**Comment by lgvt369** [comment]
> 我这边测试应该是浏览器版本太老的问题。我也是私有化部署，内网不能上互联网，用Chrome 96.0版本会出现问题，改用Chrome 109.0或者Firefox115版本就没问题了。 一般内网不能上互联网的话，浏览器版本都会比较老...

这个问题作者已经在最新版本中修复了

**Comment by bg9cxn** [comment]
> > 我这边测试应该是浏览器版本太老的问题。我也是私有化部署，内网不能上互联网，用Chrome 96.0版本会出现问题，改用Chrome 109.0或者Firefox115版本就没问题了。 一般内网不能上互联网的话，浏览器版本都会比较老...
> 
> 我的这个问题作者已经在最新版本中修复了

我也看到作者的修复问题的回复了，但是我把docker镜像换到目前最新的4.8.12了，用老版本浏览器还是有问题，新版本浏览器在4.8.11和4.8.12都没问题。
你那边有更新代码吗？更新后问题还会复现吗？

**Comment by Crescentz** [comment]
相同的问题又出现了

**Comment by Crescentz** [comment]
> 我这边测试应该是浏览器版本太老的问题。我也是私有化部署，内网不能上互联网，用Chrome 96.0版本会出现问题，改用Chrome 109.0或者Firefox115版本就没问题了。 一般内网不能上互联网的话，浏览器版本都会比较老...


可以做伸手党吗
