### ISSUE TITLE
请教下：更换知识库，寻找下一条训练数据有没有可能产生冲突

### ISSUE THREAD

**Issue by ENg-122** [labring/FastGPT#2960]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√] 我已确认目前没有类似 issue
- [√] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [√] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
  // Find next rebuilding data to insert training queue
  await mongoSessionRun(async (session) => {
    // get new mongoData insert to training
    const newRebuildingData = await MongoDatasetData.findOneAndUpdate(
      {
        teamId: mongoData.teamId,
        datasetId: mongoData.datasetId,
        rebuilding: true
      },
      {
        $unset: {
          rebuilding: null
        },
        updateTime: new Date()
      },
      { session }
    ).select({
      _id: 1,
      collectionId: 1
    });

    if (newRebuildingData) {
      await MongoDatasetTraining.create(
        [
          {
            teamId: mongoData.teamId,
            tmbId: trainingData.tmbId,
            datasetId: mongoData.datasetId,
            collectionId: newRebuildingData.collectionId,
            billId: trainingData.billId,
            mode: TrainingModeEnum.chunk,
            model: trainingData.model,
            q: '1',
            dataId: newRebuildingData._id
          }
        ],
        { session }
      );
    }
  });
如果vectorMaxProcess是15，这里的newRebuildingData有没有可能被多个线程同时findOneAndUpdate同一条数据啊？
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
不会，mongo 中，这个属于原子操作

**Comment by ENg-122** [comment]
好嘞 感谢
