### ISSUE TITLE
配置GptGod的key时报错

### ISSUE THREAD

**Issue by gyh333** [labring/FastGPT#2962]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x ] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ x ] 公有云版本: https://tryfastgpt.ai/
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
【账号】-【个人信息】处的OpenAI / OpenAPI账号，配置GptGod的key时报错，如下图：
![4a56c64b2b554597eeb70070ce11287](https://github.com/user-attachments/assets/00225fa2-abad-4218-ba42-d2a9b30c7d5e)
![0e7b34b3b65d4d4e29400ad191a8b7f](https://github.com/user-attachments/assets/4e719e6a-0166-48b4-ae4f-4022c4b5e841)
![7e432d88d6e1d02281adfb53fcd3ab1](https://github.com/user-attachments/assets/e063ef2e-0c45-471e-8a9e-a07ee82843aa)

**复现步骤**

**预期结果**

**相关截图**
在dify里面没问题
![b998277372e0ca8ae4e9d018c055b62](https://github.com/user-attachments/assets/ee9f10fb-f9b0-42f2-9b57-f7a1c028436c)
![b0881fc145d89d6281619d4055733f4](https://github.com/user-attachments/assets/0061c2e1-d547-44ac-8f53-c99ce0c4097c)

**Comment by c121914yu** [comment]
key 没返回任何内容，自行检查渠道是否正常。

**Comment by gyh333** [comment]
> key 没返回任何内容，自行检查渠道是否完全符合 openai，包括 stream 和非 stream 模式。

![image](https://github.com/user-attachments/assets/6b1f4a43-ee09-4c09-9a45-7ebda59b9c26)
这个地方肯定是有bug的，我在模型里面勾选了gpt-4o-mini才能成功添加，不信你们自己试一下！再说，gptgod没有用过吗？
