### ISSUE TITLE
嵌套有其他工作流的工作流，日志显示异常

### ISSUE THREAD

**Issue by cloudtuotuo** [labring/FastGPT#2966]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.11-fox

**问题描述, 日志截图**
当该工作流中调用了其他工作流时，在日志显示界面，生成结果并未直接显示：
![image](https://github.com/user-attachments/assets/403d5c58-cf85-45db-b306-c253011dabf9)

**预期结果**
应在日志中显示输出结果：
![image](https://github.com/user-attachments/assets/8d2a8c83-7288-4db2-a87f-d14eaf0bd9b1)

**Comment by c121914yu** [comment]
前面有重复 issue，翻下。

**Comment by cloudtuotuo** [comment]
可以确保使用的是最新模式的嵌套工作流，并且开启了流响应
被嵌套的工作流中有多个AI对话节点，中间部分是不返回内容的，只有最后一个返回

在使用API调用这个大工作流时，返回是正常的，只有日志这里有异常

![image](https://github.com/user-attachments/assets/76099e00-18f6-42cd-90f2-8649ce1f1506)

**Comment by cloudtuotuo** [comment]
再次补充，不知何故，在没有调整该工作流的情况下，API也只返回空数据了；在【应用配置】-【运行】下，可以看到输出结果

**Comment by c121914yu** [comment]
> 再次补充，不知何故，在没有调整该工作流的情况下，API也只返回空数据了；在【应用配置】-【运行】下，可以看到正常的输出结果
> 
> 将嵌套的应用改为了【插件】，同样的问题
> 
> ![image](https://github.com/user-attachments/assets/a34b13c0-ade5-4c96-aafa-b708252ead51)
> 
> 

API 非 stream 调用？是的话，可以看看更新日志里的修复

**Comment by cloudtuotuo** [comment]
刚刚更新了4.8.12-fix，bug已修复，感谢
