### ISSUE TITLE
节点默认支持 类似 Http节点 的 “输出字段提取”

### ISSUE THREAD

**Issue by zhk0603** [labring/FastGPT#2975]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 features
- [x ] 我已确认我已升级到最新版本
- [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
所有节点能不能增加类似Http节点 的自定义输出，因为在很多时候，不管是自己写的插件，还是用别人的，这些插件的输出结果流转到下一个环节的时候，我都会增加“代码运行”的节点进行处理，可能是提取其中的一个参数，然后再输出，这样就很麻烦

**应用场景**

**相关示例**

**Comment by zhk0603** [comment]
我看最近是支持JSONPath来提取字段了

**Comment by c121914yu** [comment]
肯定不行啊，自己的插件又没自定义输出，提取啥？不都把输出都放出来了。

**Comment by zhk0603** [comment]
> 肯定不行啊，自己的插件又没自定义输出，提取啥？不都把输出都放出来了。

自定义插件有输出，比如输出一个对象：{prop1: 1, prop2: 2, arr: []}。
假设下一个工作流我需要把 arr 作为参数传进去。我就得添加一个中间的节点“代码运行”，把 arr 参数抽出来，才能丢给下一个节点。这种场景经常遇到。所以我觉得灵活一点，就是如果能支持像http节点那样，能自定义再次自定义输出字段，就比较灵活。

**Comment by c121914yu** [comment]
> > 肯定不行啊，自己的插件又没自定义输出，提取啥？不都把输出都放出来了。
> 
> 自定义插件有输出，比如输出一个对象：{prop1: 1, prop2: 2, arr: []}。 假设下一个工作流我需要把 arr 作为参数传进去。我就得添加一个中间的节点“代码运行”，把 arr 参数抽出来，才能丢给下一个节点。这种场景经常遇到。所以我觉得灵活一点，就是如果能支持像http节点那样，能自定义再次自定义输出字段，就比较灵活。

那你插件为啥不直接输出中间的～

**Comment by zhk0603** [comment]
> > > 肯定不行啊，自己的插件又没自定义输出，提取啥？不都把输出都放出来了。
> > 
> > 
> > 自定义插件有输出，比如输出一个对象：{prop1: 1, prop2: 2, arr: []}。 假设下一个工作流我需要把 arr 作为参数传进去。我就得添加一个中间的节点“代码运行”，把 arr 参数抽出来，才能丢给下一个节点。这种场景经常遇到。所以我觉得灵活一点，就是如果能支持像http节点那样，能自定义再次自定义输出字段，就比较灵活。
> 
> 那你插件为啥不直接输出中间的～

我知道呀，自己的插件还好说能自己改。别人的就没法搞，而且，即使是自己写插件复用的多了。这个地方要用提取a字段，另一个地方要提取b字段，甚至是内层里面的某些字段，我总不能遇到一个场景不用就回去改插件吧，这种不是很灵活。
所以大佬您看看我说的可行不

**Comment by c121914yu** [comment]
> > > > 肯定不行啊，自己的插件又没自定义输出，提取啥？不都把输出都放出来了。
> > > 
> > > 
> > > 自定义插件有输出，比如输出一个对象：{prop1: 1, prop2: 2, arr: []}。 假设下一个工作流我需要把 arr 作为参数传进去。我就得添加一个中间的节点“代码运行”，把 arr 参数抽出来，才能丢给下一个节点。这种场景经常遇到。所以我觉得灵活一点，就是如果能支持像http节点那样，能自定义再次自定义输出字段，就比较灵活。
> > 
> > 
> > 那你插件为啥不直接输出中间的～
> 
> 我知道呀，自己的插件还好说能自己改。别人的就没法搞，而且，即使是自己写插件复用的多了。这个地方要用提取a字段，另一个地方要提取b字段，甚至是内层里面的某些字段，我总不能遇到一个场景不用就回去改插件吧，这种不是很灵活。 所以大佬您看看我说的可行不

不是很需要，我感觉写个代码比自定义提取好用多了。
