### ISSUE TITLE
工作流节点编辑区域，键盘点击Backspace键，提示节点不允许删除

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#2980]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 4.8.11-fix

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/5ea9c0ad-ca99-422d-9215-c22c72ff86d4)

**复现步骤**
在参数编辑区域，键盘Backspace键删除文本，提示”节点不允许删除“
**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
选中了不可删的节点吧

**Comment by Essence9999** [comment]
> 选中了不可删的节点吧

只是节点中得参数值写错了，我把错误内容通过Backspace和回车键，进行删除，就会出现这种情况

**Comment by c121914yu** [comment]
> Backspace

没看懂
