### ISSUE TITLE
Qwen2.5 相关模型回复异常

### ISSUE THREAD

**Issue by rlyohh** [labring/FastGPT#2983]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
fastgpt：4.8.11-fix
ollama：0.3.13
oneapi：0.6.8

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
qwen2:7b、qwen2:1.5b、qwen2.5:7b、qwen2.5:3b、qwen2.5:1.5b
![image](https://github.com/user-attachments/assets/9bbcf88d-454c-4f30-a970-b5b2fe9d1fbf)
![image](https://github.com/user-attachments/assets/5474e3fc-cfb6-43d8-a001-2c1df7152cbe)
![image](https://github.com/user-attachments/assets/bf6474dc-8d94-4ef6-97cd-b3e28c1a97b4)

gemma2:9b
![image](https://github.com/user-attachments/assets/93141074-19ed-4285-a774-939ccd81c8ee)

命令行运行截图
![image](https://github.com/user-attachments/assets/b0c7047d-1ac0-407f-97fa-1a7c5d71120e)

**复现步骤**

**预期结果**
通义千问相关模型回复正常

**相关截图**

**Comment by c121914yu** [comment]
不应该提给千问么

**Comment by NerdyNomadPixelPilgrim** [comment]
FastGPT版本4.8.10的时候是正常的，近期升级了之后发现了异常

**Comment by c121914yu** [comment]
> FastGPT版本4.8.10的时候是正常的，近期升级了之后发现了异常

那你自己 debug 看看提示啥的好了，也看不出啥问题

**Comment by yixiuquan** [comment]
把oneapi 换成0.6.7 就好了
据说是oneapi 0.6.8这个版本不支持ollama 的stream导致的

**Comment by rlyohh** [comment]
非常感谢两位 @c121914yu @yixiuquan 
问题已经解决，降低 one-api 的版本到 v0.6.7 之后即可。
