### ISSUE TITLE
界面中英文切换，鼠标刷新一下，界面语言就变成浏览器的默认语言

### ISSUE THREAD

**Issue by Essence9999** [labring/FastGPT#2984]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.11-fix

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/bcf3d04c-63ab-4a33-ab86-e88ddb4fd661)
鼠标右键，刷新就变成中文了
![image](https://github.com/user-attachments/assets/dcf43b5e-7b4b-4536-99b3-16b6353563ca)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
https://github.com/user-attachments/assets/253deb7a-a4d2-44c0-a9c3-e3b67bc21771

没复现呢？
