### ISSUE TITLE
知识库上百个文档向量化速度慢

### ISSUE THREAD

**Issue by TTlovelearing** [labring/FastGPT#2986]
[](url)**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
在建立知识库的时候,需要上传几百个文档小说文件,使用m3e模型进行向量化,cpu和gpu使用率低,之前测试过可能会占用十几个小时来进行向量化,可以如何优化速度?
**复现步骤**

**预期结果**

**相关截图**
<img width="1564" alt="截屏2024-10-25 10 54 03" src="https://github.com/user-attachments/assets/5e60fff5-9e8a-42e1-8291-b14d03fdaa07">

**Comment by c121914yu** [comment]
提高线程数量（改配置文件）
提高数据库性能（裸机装数据库，或者用 etcd）

**Comment by TTlovelearing** [comment]
> 提高线程数量（改配置文件） 提高数据库性能（裸机装数据库，或者用 etcd）

配置文件是 config.json中的这两项吗?
<img width="949" alt="截屏2024-10-25 19 25 28" src="https://github.com/user-attachments/assets/c425b7ef-e5d0-4bdd-83dc-be7eaa301e4e">

**Comment by SDAIer** [comment]
同问
