### ISSUE TITLE
Dockerfile部署失败

### ISSUE THREAD

**Issue by HSoft-Wyt** [labring/FastGPT#2991]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.11:fix

**问题描述, 日志截图**
使用Dockerfile部署出现一堆问题,少包这个问题就不说了,我自己慢慢解决了
结果登录的时候提示.next包又缺失不少文件
我在本地搭建了一套,发现没有这几个文件照样跑的好好的
完全排查不出来问题所在了
而且这个Dockerfile槽点太多了,每次升级都要重新部署,然后又要手动修改,还要解决一堆bug
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/a526ff78-a918-48c3-9423-903de3577227)
![image](https://github.com/user-attachments/assets/4c80e3cd-6492-4802-95e1-ba0c0eceeeeb)

**Comment by c121914yu** [comment]
没搞懂你干啥，dockerfile 和你本地文件有啥关系

**Comment by HSoft-Wyt** [comment]
> 没搞懂你干啥，dockerfile 和你本地文件有啥关系，不是 docker build 就完事了

docker build完事儿了,但是登录报错,提示我少文件,我在本地搭了一套,发现本地也没有,但是跑的好好的

**Comment by HSoft-Wyt** [comment]
> 没搞懂你干啥，dockerfile 和你本地文件有啥关系，不是 docker build 就完事了

而且4.8.2版本没有这个问题,我看了一下schema.proto文件,是zilliz包里面的文件,文件位置也在zilliz包的路径下,怎么会在,next路径下呢?

**Comment by HSoft-Wyt** [comment]
> 没搞懂你干啥，dockerfile 和你本地文件有啥关系，不是 docker build 就完事了

我的意思是,我本地缺少这些文件,没有问题没有报错,但在云平台部署,就会出现图中缺少文件的问题

**Comment by HSoft-Wyt** [comment]
> 没搞懂你干啥，dockerfile 和你本地文件有啥关系，不是 docker build 就完事了

我的意思是,我本地缺少这些文件,没有问题没有报错,但在云平台部署,就会出现图中缺少文件的问题

**Comment by HSoft-Wyt** [comment]
> 没搞懂你干啥，dockerfile 和你本地文件有啥关系，不是 docker build 就完事了

而且我如果不手动修改Dockerfile,在build的过程中是会报错的,zilliz包和titoken包都是缺失的
