### ISSUE TITLE
v4.8.11通用知识库子目录文件无法通过对话附件链接或者其他链接访问，提示“未能加载 PDF 文档”

### ISSUE THREAD

**Issue by kevin50ster** [labring/FastGPT#2997]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: v4.8.11

**问题描述, 日志截图**

**复现步骤**
- 通用知识库，新建两层子目录，上传文件到第三层目录后，查看原始内容，提示“未能加载PDF文档”
- 通过对话时使用知识库，关联出的pdf文件，无法访问。
- 根目录下文件可正常访问

**预期结果**
希望知识库子目录文件能正确访问到

**相关截图**
<img width="812" alt="image" src="https://github.com/user-attachments/assets/97d58cf3-2ed0-4705-98d9-339907d288d3">

<img width="1309" alt="截屏2024-10-27 下午9 23 57" src="https://github.com/user-attachments/assets/d087dd20-88ec-4b02-871d-91b281147a9c">

**Comment by c121914yu** [comment]
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/a9fe26cc-5538-47e7-a922-2fea626ed4c7">
试了试，未发现该问题，可以检查下数据库里是否能找到该文件。

**Comment by kevin50ster** [comment]
@c121914yu 感谢您的回复，我再查一下原因~

**Comment by ans1988dog** [comment]
请问下这问题解决了吗？我现在遇到的现象是通过手动上传的没问题，可以打开源文档；但是通过接口上传的文档，然后打开源文档就显示“未能加载PDF文档。”，但是通过对比元数据，
手动上传的和接口上传的数据一摸一样，搞不懂了，这是为啥？

**Comment by ans1988dog** [comment]
> <img alt="image" width="1218" src="https://private-user-images.githubusercontent.com/50446880/380504051-a9fe26cc-5538-47e7-a922-2fea626ed4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTEyMTUsIm5iZiI6MTczMjg1MDkxNSwicGF0aCI6Ii81MDQ0Njg4MC8zODA1MDQwNTEtYTlmZTI2Y2MtNTUzOC00N2U3LWE5MjItMmZlYTYyNmVkNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAzMjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MjZhOWNiNGViZTYyZGYwNGJlOTU3MjMxOTQ0MTk0NzFjYmE0NDBkYzI4ZTc2MDViYzljZTQyZTUwMGZjZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GW2MS52GdnLVuX-p_27aBrl6QMxSTLwD7vN0MtsZH2g"> 试了试，未发现该问题，可以检查下数据库里是否能找到该文件。

麻烦看下这个异常呢。我现在遇到的现象是通过手动上传的没问题，可以打开源文档；但是通过接口上传的文档，然后打开源文档就显示“未能加载PDF文档。”，但是通过对比元数据，
手动上传的和接口上传的数据一摸一样，搞不懂了，这是为啥？
