### ISSUE TITLE
国产浏览器兼容问题

### ISSUE THREAD

**Issue by ifkd111** [labring/FastGPT#3000]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√ ] 我已确认目前没有类似 issue
- [ √] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ √] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√] 私有部署版本, 具体版本号: 4.8.10

**问题描述, 日志截图**
单位电脑只能使用红莲华浏览器，或者google45左右版本，打不开分享链接。
**复现步骤**

**预期结果**
希望能兼容低版本google或者红莲花浏览器。
**相关截图**

**Comment by rainyoung** [comment]
我们也遇到这个问题，4.8.6之前的旧版本都没问题，之后的新版本都不好使了，打不开~~~~~

**Comment by c121914yu** [comment]
可以发下控制台错误？或者自己 debug 看看是哪个依赖出了问题

**Comment by rainyoung** [comment]
![1730255166876](https://github.com/user-attachments/assets/c22a1ba7-18bc-4d12-85ec-46b216f4672d)

**Comment by duskcouple** [comment]
我的是这种报错，换了100版本以上的chrome就不报错了。进工作流设计界面就会报错，然后退出界面。不进入工作流设计界面都没问题，简单应用的界面也可以进入，不报错。
![微信图片_20241030101057](https://github.com/user-attachments/assets/d79382f9-60c6-4bb6-84da-2276e6596794)

**Comment by c121914yu** [comment]
> 我的是这种报错，换了100版本以上的chrome就不报错了。进工作流设计界面就会报错，然后退出界面。不进入工作流设计界面都没问题，简单应用的界面也可以进入，不报错。 ![微信图片_20241030101057](https://private-user-images.githubusercontent.com/26564245/381369898-d79382f9-60c6-4bb6-84da-2276e6596794.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTczOTksIm5iZiI6MTczMDI1NzA5OSwicGF0aCI6Ii8yNjU2NDI0NS8zODEzNjk4OTgtZDc5MzgyZjktNjBjNi00YmI2LTg0ZGEtMjI3NmU2NTk2Nzk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDI4MGNlMjE1OGY4MTA2NDI2OWY4ZmRjYzMxZGY1MGRmY2RkNGEzNzljODVhODNlYmRiYTJhYWU3MTExZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zFNNO9zaMlwdE1jHWPHZzata-akYfCcPXw3VqQWhF_k)

看起来是不支持 findLast 的 api

**Comment by duskcouple** [comment]
> > 我的是这种报错，换了100版本以上的chrome就不报错了。进工作流设计界面就会报错，然后退出界面。不进入工作流设计界面都没问题，简单应用的界面也可以进入，不报错。 ![微信图片_20241030101057](https://private-user-images.githubusercontent.com/26564245/381369898-d79382f9-60c6-4bb6-84da-2276e6596794.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTczOTksIm5iZiI6MTczMDI1NzA5OSwicGF0aCI6Ii8yNjU2NDI0NS8zODEzNjk4OTgtZDc5MzgyZjktNjBjNi00YmI2LTg0ZGEtMjI3NmU2NTk2Nzk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDI4MGNlMjE1OGY4MTA2NDI2OWY4ZmRjYzMxZGY1MGRmY2RkNGEzNzljODVhODNlYmRiYTJhYWU3MTExZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zFNNO9zaMlwdE1jHWPHZzata-akYfCcPXw3VqQWhF_k)
> 
> 看起来是不支持 findLast 的 api

是的，我们是买了商业版的本地化内部网私有部署，不连接互联网，内部的计算机，包括浏览器版本都是不太高的版本，也有国产化的环境，国产化也是浏览器版本不会太高。所以如果采用了不想下兼容的某些技术，可能会无法使用。

PS：建议开发技术选型的时候考虑一下咱们现在的整体大环境和趋势，兼顾下兼容性，毕竟现在所有政府、国企等国产化生态是大势所趋，还是强制性的。

**Comment by rainyoung** [comment]
> > > 我的是这种报错，换了100版本以上的chrome就不报错了。进工作流设计界面就会报错，然后退出界面。不进入工作流设计界面都没问题，简单应用的界面也可以进入，不报错。 ![微信图片_20241030101057](https://private-user-images.githubusercontent.com/26564245/381369898-d79382f9-60c6-4bb6-84da-2276e6596794.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTczOTksIm5iZiI6MTczMDI1NzA5OSwicGF0aCI6Ii8yNjU2NDI0NS8zODEzNjk4OTgtZDc5MzgyZjktNjBjNi00YmI2LTg0ZGEtMjI3NmU2NTk2Nzk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDI4MGNlMjE1OGY4MTA2NDI2OWY4ZmRjYzMxZGY1MGRmY2RkNGEzNzljODVhODNlYmRiYTJhYWU3MTExZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zFNNO9zaMlwdE1jHWPHZzata-akYfCcPXw3VqQWhF_k)
> > 
> > 
> > 看起来是不支持 findLast 的 api
> 
> 是的，我们是买了商业版的本地化内部网私有部署，不连接互联网，内部的计算机，包括浏览器版本都是不太高的版本，也有国产化的环境，国产化也是浏览器版本不会太高。所以如果采用了不想下兼容的某些技术，可能会无法使用。
> 
> PS：建议开发技术选型的时候考虑一下咱们现在的整体大环境和趋势，兼顾下兼容性，毕竟现在所有政府、国企等国产化生态是大势所趋，还是强制性的。

你们怎么处理的？？？重新编译吗？？

**Comment by 18212343994** [comment]
用谷歌80版本浏览器，在简易应用开启文件上传，往对话框上传文件并发送时，也会报错并返回工作台，这个问题能否也修复一下呢。
![Uploading 1731472002334.jpg…]()

**Comment by 18212343994** [comment]
用谷歌80版本浏览器，在V4.8.13版本简易应用开启文件上传，往对话框上传文件并发送时，也会报错并返回工作台，这个问题能否也修复一下呢。
![1731472002334](https://github.com/user-attachments/assets/96bc3220-6ef2-41d9-993e-db73390b2142)

**Comment by c121914yu** [comment]
> 用谷歌80版本浏览器，在V4.8.13版本简易应用开启文件上传，往对话框上传文件并发送时，也会报错并返回工作台，这个问题能否也修复一下呢。 ![1731472002334](https://private-user-images.githubusercontent.com/65266522/385585973-96bc3220-6ef2-41d9-993e-db73390b2142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzMyMjEsIm5iZiI6MTczMTQ3MjkyMSwicGF0aCI6Ii82NTI2NjUyMi8zODU1ODU5NzMtOTZiYzMyMjAtNmVmMi00MWQ5LTk5M2UtZGI3MzM5MGIyMTQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA0NDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMjY2ZjhkZjYzZDJmNDUyMGQ3NTk5NmFlNTc3NTI5NmJlNzNlYTBkYTg5Y2U4NGJmMmY1MmM4ODk0MTQyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.glqR4JtGb-1wkuqlpJ3fUabu_RkDfR7yxPWrgqNwynw)

https://github.com/labring/FastGPT/pull/3147 这里处理
