### ISSUE TITLE
mongo版本换为4.4.29，依旧报错 Waiting for MongoDB to start

### ISSUE THREAD

**Issue by 305607610** [labring/FastGPT#3001]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.11-fix

**问题描述, 日志截图**
根据文档mongo版本换为 4.4.29 依旧报错 Waiting for MongoDB to start
![image](https://github.com/user-attachments/assets/52175c4f-def4-4a75-ac0d-a546b19eaf16)
![image](https://github.com/user-attachments/assets/777400df-ea54-405c-99b6-7db662e11f4d)
![image](https://github.com/user-attachments/assets/06cf41f7-1ed8-4f48-9523-45bdaf6e81b6)

**复现步骤**

**预期结果**

**相关截图**

**Comment by WHUEugene** [comment]
怎么解决的啊
