### ISSUE TITLE
4.7版本问题

### ISSUE THREAD

**Issue by lxb0425** [labring/FastGPT#3003]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7

**问题描述, 日志截图**
vllm部署的qwen2-vl-72B-instruct   oneapi配置的自定义渠道 指向vllm部署后的api
我现在用的4.7版本 一直是大语言模型 ，现在准备切换模型，想支持图片和视频输入 请问下当时的4.7支持吗 我在配置界面上没有找到开启图片的开关
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/a0d94a77-346f-41a0-ac06-21fe7ff35eac)

**Comment by c121914yu** [comment]
没有的话就是不支持。可以翻下更新记录，忘了啥时候的功能了。
