### ISSUE TITLE
Embedding API is not responding

### ISSUE THREAD

**Issue by sndhmg** [labring/FastGPT#3008]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: ghcr.io/labring/fastgpt:v4.8.11

**问题描述, 日志截图**
创建了一个知识库，并在一个应用中关联该知识库，测试对话可以正常返回，并正常关联知识库，但是在免登陆窗口报错Embedding API is not responding
![image](https://github.com/user-attachments/assets/941a67cd-a1e6-4b31-a12d-035df3496ce0)
使用api方式访问/api/v1/chat/completions，也报同样的错
![image](https://github.com/user-attachments/assets/1cda8942-5940-4426-8610-81df90e95552)
![image](https://github.com/user-attachments/assets/d5a0f28c-814e-4910-b91d-fb471b06d8b5)
![image](https://github.com/user-attachments/assets/922a4a84-4ed1-46c5-b95a-449ef3d2c11f)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
和他提示一样，模型错误

**Comment by sndhmg** [comment]
已经找到原因，循环代理导致的

**Comment by daguda** [comment]
> 已经找到原因，循环代理导致的

循环代理是什么？
