### ISSUE TITLE
对话框输出文字很慢

### ISSUE THREAD

**Issue by kid20210528** [labring/FastGPT#3019]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ √] 私有部署版本, 具体版本号: 4.8.11

**问题描述, 日志截图**

AI对话完之后，对话框中输出文字有时快有时慢，这个具体跟哪些东西挂钩啊？

**Comment by tt-a1i** [comment]
这个通常与你的api key对应的服务端数据返回速度有关, 也可以打开F12浏览器调试工具,录制对应请求的Timing对比你对话中的文字生成速度来确定问题所在

**Comment by kid20210528** [comment]
> 这个通常与你的api key对应的服务端数据返回速度有关, 也可以打开F12浏览器调试工具,录制对应请求的Timing对比你对话中的文字生成速度来确定问题所在

好的    谢谢
