### ISSUE TITLE
对话框输入中文加数字时，会自动在文字和数字之间增加空格，导致部分场景无法正确进入下个流

### ISSUE THREAD

**Issue by E218PQ** [labring/FastGPT#3025]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8.11
- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
对话框输入中文加数字时，会自动在文字和数字之间增加空格，导致部分场景无法正确进入下个流

**复现步骤**
输入框输入中文+数字，发送后即可看到中文和数字之间就已经被增加空格。
**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/8f45d26c-48c2-4a7e-b26e-ea5e675340ba)

**Comment by c121914yu** [comment]
只是 ui 展示，实际数据无空格，有问题肯定是你工作流编排有问题，

**Comment by SDAIer** [comment]
if判断也得需要增加空格

**Comment by E218PQ** [comment]
> 只是 ui 展示，实际数据无空格，有问题肯定是你工作流编排有问题，

就是实际HTTP请求传出的数据中加了空格了，才报错的。

**Comment by c121914yu** [comment]
> > 只是 ui 展示，实际数据无空格，有问题肯定是你工作流编排有问题，
> 
> 就是实际HTTP请求传出的数据中加了空格了，才报错的。

没发现，测试了下，发送过去的是没空格的
