### ISSUE TITLE
在引用数据库时，生成的SQL无法给到数据源配置插件，因为AI生成的对话自带标点以及其他文字，因此无法实现连接数据库并且查找相关数据。

### ISSUE THREAD

**Issue by Cynthia-ly** [labring/FastGPT#3039]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/eb346094-97ca-4ac2-adaa-21669ee762b5)

![image](https://github.com/user-attachments/assets/18a187ba-9d6a-4d79-bdcf-bd28d7926e0c)

**复现步骤**

**预期结果**

**相关截图**

**Comment by heart18z** [comment]
肯定走内容提前出sql，再变量传递给数据库

**Comment by silencezhang7** [comment]
走个内容提取，把sql提出来

**Comment by RipperTs** [comment]
使用专业的NLSQL的模型，比如sqlcode
