### ISSUE TITLE
tempture

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#3045]
config.json设置tempture最大1.2，但是在工作流中AI的tempture范围是1-10？是否正常

**Comment by i-square** [comment]
FastGPT工作流里的temperature与其说是一个值，不如说是一个比例，实质上它会除以10再跟你config.json里设置的maxTemperature相乘作为真正的temperature值，见代码：[packages/service/core/ai/utils.ts#L42](https://github.com/labring/FastGPT/blob/main/packages/service/core/ai/utils.ts#L42)

举例来说，比如你设置的最大是1.2，那么工作流里你设置5，那么实际发送到模型那边的值是 1.2*(5/10)=0.6

但是好像模块里缺少这个参数的说明，即使说明了可能也有人不理解，不知道为什么当初要这么设计而不是直接使用配置文件里的maxTemperature 做范围

**Comment by c121914yu** [comment]
> FastGPT工作流里的temperature与其说是一个值，不如说是一个比例，实质上它会除以10再跟你config.json里设置的maxTemperature相乘作为真正的temperature值，见代码：[packages/service/core/ai/utils.ts#L42](https://github.com/labring/FastGPT/blob/main/packages/service/core/ai/utils.ts#L42)
> 
> 
> 
> 举例来说，比如你设置的最大是1.2，那么工作流里你设置5，那么实际发送到模型那边的值是 1.2*(5/10)=0.6
> 
> 
> 
> 但是好像模块里缺少这个参数的说明，即使说明了可能也有人不理解，不知道为什么当初要这么设计而不是直接使用配置文件里的maxTemperature 做范围

你从使用角度就好理解了，如果用户换一个模型，发现温度的范围就变了，会很奇怪。而且有的模型是 0-1，有的是 0-2，但是 gpt 一般 1.5 以上都会乱码不可用，所以一般最大设置个 1.3 这样。
如果一个滑动块最大是 1.3，会很丑。

**Comment by SDAIer** [comment]
多谢



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 1, 2024 19:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [labring/FastGPT] tempture (Issue #3045)




 
FastGPT工作流里的temperature与其说是一个值，不如说是一个比例，实质上它会除以10再跟你config.json里设置的maxTemperature相乘作为真正的temperature值，见代码：packages/service/core/ai/utils.ts#L42
 
举例来说，比如你设置的最大是1.2，那么工作流里你设置5，那么实际发送到模型那边的值是 1.2*(5/10)=0.6
 
但是好像模块里缺少这个参数的说明，即使说明了可能也有人不理解，不知道为什么当初要这么设计而不是直接使用配置文件里的maxTemperature 做范围
