### ISSUE TITLE
插件使用报错

### ISSUE THREAD

**Issue by buibiui** [labring/FastGPT#3050]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by buibiui** [comment]
![屏幕截图 2024-11-01 111251](https://github.com/user-attachments/assets/3495b182-5959-418f-a59a-8ca22c1e2c60)
使用插件时，进行ai对话报错，请问是什么原因

**Comment by cloudtuotuo** [comment]
模型API问题，用oneapi中转一下

**Comment by buibiui** [comment]
已经用oneapi中转了

**Comment by AYueBlog** [comment]
遇到相同的问题了，解决了吗？

**Comment by c121914yu** [comment]
看文档 https://doc.tryfastgpt.ai/docs/development/faq/#%E6%8A%A5%E9%94%99---%E6%A8%A1%E5%9E%8B%E5%93%8D%E5%BA%94%E4%B8%BA%E7%A9%BA
