### ISSUE TITLE
版本更新后指定回复模块输出Markdown格式链接功能异常

### ISSUE THREAD

**Issue by Dcklin** [labring/FastGPT#3056]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [✔] 我已确认目前没有类似 issue
- [✔] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [✔] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [✔] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [✔] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 私有部署版本, 具体版本号: 
V4.8.12-fix

**问题描述, 日志截图**

旧版本正常，更新最新版本后使用指定回复模块输出以下链接：
[示例文件1](http://192.168.0.1:10000/file.xlsx)
[示例文件2](http://192.168.0.1:10000/我的file.xlsx)

示例文件1正常，示例文件2格式异常

**复现步骤**

**预期结果**

**相关截图**

**Comment by Dcklin** [comment]
测试发现文件名中带有中文的输出都有问题

**Comment by c121914yu** [comment]
无效 issue，重新提交

**Comment by c121914yu** [comment]
> 测试发现文件名中带有中文的输出都有问题

中文链接加个编码

**Comment by c121914yu** [comment]
链接打不开

**Comment by Dcklin** [comment]
> > 测试发现文件名中带有中文的输出都有问题
> 
> 中文链接加个编码

测试的链接是：http://192.168.0.1:10000/我的file.xlsx
旧版本的时候不用加编码也能用，现在测试带中文的链接加上URL编码无法正常跳转
