### ISSUE TITLE
把compose单个应用独立出来

### ISSUE THREAD

**Issue by AlanWang2333** [labring/FastGPT#3057]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

可不可以把，compose里面的应用独立出来，因为我已经有一个MySQL数据库了，oneapi用的onehub，不想再增加额外的docker应用了

**Comment by mingtian886** [comment]
这个不是bug，你自己删除掉one api相关的就行了，我就没有部署one api

**Comment by c121914yu** [comment]
手动去掉即可
