### ISSUE TITLE
dockerfile npm i not work correctly in Mainland China

### ISSUE THREAD

**Issue by Robin021** [labring/FastGPT#3064]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.8.12-beta

**问题描述, 日志截图**
when i try to build the docker image , in step npm i , it always timeout, whatever  with the arg proxy or not:

`252.7  WARN  GET https://registry.npmjs.org/openapi-types/-/openapi-types-12.1.3.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
252.7  WARN  GET https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.0.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
252.7  WARN  GET https://registry.npmjs.org/@types/lodash/-/lodash-4.17.7.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
253.2  WARN  GET https://registry.npmjs.org/@types/js-yaml/-/js-yaml-4.0.9.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
254.6 Progress: resolved 123, reused 0, downloaded 124, added 0
255.6 Progress: resolved 124, reused 0, downloaded 124, added 0
314.2 Progress: resolved 124, reused 0, downloaded 125, added 0
315.2 Progress: resolved 127, reused 0, downloaded 127, added 0
316.2 Progress: resolved 129, reused 0, downloaded 129, added 0
373.3 /app/packages/global:
373.3  ERR_SOCKET_TIMEOUT  request to https://registry.npmjs.org/openai/-/openai-4.61.0.tgz failed, reason: Socket timeout
373.3
373.3 This error happened while installing a direct dependency of /app/packages/global
373.3
373.3 FetchError: request to https://registry.npmjs.org/openai/-/openai-4.61.0.tgz failed, reason: Socket timeout
373.3     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:68852:18)
373.3     at ClientRequest.emit (node:events:519:28)
373.3     at TLSSocket.socketErrorListener (node:_http_client:500:9)
373.3     at TLSSocket.emit (node:events:531:35)
373.3     at emitErrorNT (node:internal/streams/destroy:169:8)
373.3     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
373.3     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
------
Dockerfile:19
--------------------
  17 |     RUN [ -f pnpm-lock.yaml ] || (echo "Lockfile not found." && exit 1)
  18 |
  19 | >>> RUN pnpm i
  20 |
  21 |     # --------- builder -----------
--------------------`

**复现步骤**

**预期结果**
can we change the Dockerfile under projects/app/ in line  19 with below directly:
`RUN pnpm i -i --registry https://registry.npmmirror.com `
**相关截图**

**Comment by c121914yu** [comment]
已调整
