### ISSUE TITLE
数据不同步

### ISSUE THREAD

**Issue by sher-niubility** [labring/FastGPT#3068]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ √] 我已确认目前没有类似 issue
- [√ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [√ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
两端同时修改同一个app的配置，刷新后数据不同步
看请求接口是已经修改完成了的，但页面上展示就是数据对不上
**复现步骤**
1. 使用账号a修改应用a的对话开场白 ，同时账号b也在应用a的配置页面
2. 当账号a提交并发布后，账号b进行页面刷新的动作，但数据并没有更新
**预期结果**

**相关截图**

**Comment by sher-niubility** [comment]
看了下代码，是因为新加的快照 数据是存在本地的，它每次加载是优先读本地的快照

**Comment by c121914yu** [comment]
本地有编辑记录会优先本地，切换应用或手动退出会重置记录。可以直接点历史记录获取云端数据
