### ISSUE TITLE
ChatGLM2-6B模型在知识库问答中不起作用，回答错误。

### ISSUE THREAD

**Issue by cocomany** [labring/FastGPT#308]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
ChatGLM2-6B模型对手到FastGPT直接对话正常，但在知识库问答中不起作用， system message好像没起作用。

**复现步骤**

**预期结果**

**相关截图**
<img width="450" alt="242903f62d144bd49aeb47fcd0786dc" src="https://github.com/labring/FastGPT/assets/124849750/1931013f-acd1-41a4-832c-e6844485b7bb">

**Comment by luozb** [comment]
我也碰到同样的问题

**Comment by cocomany** [comment]
原因是做知识库问答时，System Role出现了两条，这在ChatGLM2-6B就不理解第二个system content了。 
 我已提交了PR.

**Comment by c121914yu** [comment]
4.4.3已做了非system模型兼容。可以再试试
