### ISSUE TITLE
能不能像Kimi一样文件拖入或粘贴即上传？体验好太多了

### ISSUE THREAD

**Issue by ddup001** [labring/FastGPT#3090]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ √ ] 我已确认目前没有类似 features
- [ √ ] 我已确认我已升级到最新版本
- [ √ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ √ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [ x  ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
如题，能不能像Kimi一样文件拖入或粘贴即上传？
现在上传一个文件得点击上传按钮，再选择文件，再上传，流程好长啊，用了KImi这种粘贴和拖入的功能之后，就感觉这种多步骤的上传体验感差了好多。
能不能优化？
**应用场景**
1、图片粘贴即输入让AI解读；
2、文件拖入即上传
**相关示例**
同上

**Comment by c121914yu** [comment]
不是，，有粘贴么～

**Comment by ddup001** [comment]
> 不是，，有粘贴么～

fastgpt里有？我刚又试了下，怎么不行呢？版本4.8.12

**Comment by c121914yu** [comment]
> > 不是，，有粘贴么～
> 
> fastgpt里有？我刚又试了下，怎么不行呢？版本4.8.12

我的就行～

**Comment by c121914yu** [comment]
> > 不是，，有粘贴么～
> 
> fastgpt里有？我刚又试了下，怎么不行呢？版本4.8.12

你是，聚焦输入框了么

**Comment by ddup001** [comment]
> > > 不是，，有粘贴么～
> > 
> > 
> > fastgpt里有？我刚又试了下，怎么不行呢？版本4.8.12
> 
> 你是，聚焦输入框了么，再输入框里，打字状态，粘贴文件，是 ok 的。

感谢感谢，打字状态粘贴图片，还真可以

**Comment by ddup001** [comment]
> > > > 不是，，有粘贴么～
> > > 
> > > 
> > > fastgpt里有？我刚又试了下，怎么不行呢？版本4.8.12
> > 
> > 
> > 你是，聚焦输入框了么，再输入框里，打字状态，粘贴文件，是 ok 的。
> 
> 感谢感谢，打字状态粘贴图片，还真可以

现在就剩下文件拖入了，有办法吗？

**Comment by c121914yu** [comment]
> > > > > 不是，，有粘贴么～
> > > > 
> > > > 
> > > > fastgpt里有？我刚又试了下，怎么不行呢？版本4.8.12
> > > 
> > > 
> > > 你是，聚焦输入框了么，再输入框里，打字状态，粘贴文件，是 ok 的。
> > 
> > 
> > 感谢感谢，打字状态粘贴图片，还真可以
> 
> 现在就剩下文件拖入了，有办法吗？

嗯，有时间加下

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3104 这里现简单加下吧，还没做释放提示，直接拖到输入框就可以了
