### ISSUE TITLE
打开 /chat/share 页面时，网页title不正确

### ISSUE THREAD

**Issue by wxlzmt** [labring/FastGPT#3094]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.11.fix

**问题描述, 日志截图**
使用免登录窗口打开工作流应用页面 `/chat/share?shareId=xxx` 时，网页的`title`属性固定为`FastGPT` (即应用名称不生效)，
然后继续在网页内进行 【新建对话】 或 【切换历史会话】 操作时，网页title更新正常了(变成了应用的名字)。

**复现步骤**
打开页面 `/chat/share?shareId=略` ， 观察浏览器tab页名称变化。

**预期结果**
第一次打开 `/chat/share` 页面时，网页标题立即更新为应用的名字，而不是默认值 `FastGPT` 

**相关截图**

**Comment by Xujinhe** [comment]
当前版本依然会出现这个问题，我猜测是标题异步加载的问题，禁掉这个接口URL就不会，不知道是不是设计如此？
![wechat_2024-12-04_155728_916](https://github.com/user-attachments/assets/ba795cdc-5035-4789-ada4-a7d82c8a907a)
@c121914yu

**Comment by sudy1** [comment]
在4.9.0版本任然会出随机现这个BUG，为什么还是没有修复？

**Comment by Xujinhe** [comment]
> 在4.9.0版本任然会出随机现这个BUG，为什么还是没有修复？

据我了解这不是bug，可能是故意的

**Comment by sudy1** [comment]
@c121914yu 彻底解决下这个BUG
