### ISSUE TITLE
图表插件功能无法使用

### ISSUE THREAD

**Issue by leekoko** [labring/FastGPT#3099]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: V4.8.11

**问题描述, 日志截图**
工作流拖拽图表，数据输入之后返回为空

<img width="1219" alt="截屏2024-11-08 16 06 46" src="https://github.com/user-attachments/assets/c7300fb8-f9a8-409f-ae4b-7f40ef936165">

**复现步骤**
工作流拖拽图表，
示例数据如下
    return {
        data1: "['周一', '周二', '周三', '周四', '周五', '周六', '周日']",
        data2: "[23, 35, 28, 42, 31, 25, 37]"
    }

去掉中括号 [ 、 ] 也不行

**预期结果**
能够使用图表功能，看起来就很炫酷！！！

**相关截图**

**Comment by leekoko** [comment]
运行结果截图如下
<img width="869" alt="image" src="https://github.com/user-attachments/assets/0411369c-1679-46ac-bdbd-88b7bfdc92fa">

**Comment by c121914yu** [comment]
data2 没对，需要 array<string>

**Comment by leekoko** [comment]
> data2 没对，需要 array string 格式，而不是 array number

尝试过了
{
  "data1": "['周一', '周二', '周三', '周四', '周五', '周六', '周日']",
  "data2": "['23', '35', '28', '42', '31', '25', '37']"
}
也不行

{
  "data1": "'周一', '周二', '周三', '周四', '周五', '周六', '周日'",
  "data2": "'23', '35', '28', '42', '31', '25', '37'"
}
不行

{
  "data1": "周一, 周二, 周三, 周四, 周五, 周六, 周日",
  "data2": "23, 35, 28, 42, 31, 25, 37"
}
不行

**Comment by SDAIer** [comment]
到底咋样行

**Comment by c121914yu** [comment]
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/a6fbb373-a41f-41d0-aff6-a1272525ce18">

**Comment by c121914yu** [comment]
代码里序列化是 JSON.stringify(["1","2","3"])
