### ISSUE TITLE
无法使用o1-mini和o1-preview模型

### ISSUE THREAD

**Issue by sandycs-protoss** [labring/FastGPT#3105]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [x] 私有部署版本, 具体版本号: V4.8.11

**问题描述, 日志截图**
OPENAI的o1-mini和o1-preview无法使用。报错：
错误提示：
unsupported_value Unsupported value: 'messages[0].role' does not support 'system' with this model. (request id: 202411090747202598506059931226)
我使用ONEAPI是没有问题的
因为o1-mini和o1-preview都不支持role里有system这个角色
怎么办呢？

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/f0ba9277-41ac-4a7d-86c0-f3ab1c6ee64b)
![image](https://github.com/user-attachments/assets/7d65a258-4a91-472d-b3a2-6ccd7e0875d4)

**Comment by sandycs-protoss** [comment]
附上config.json
[config.json](https://github.com/user-attachments/files/17686939/config.json)

**Comment by c121914yu** [comment]
1. 不能加提示
2. 不能文件上传
3. 不能知识库

不然都会有 system 提示词

**Comment by sandycs-protoss** [comment]
> 1. 不能加提示
> 2. 不能文件上传
> 3. 不能知识库
> 
> 不然都会有 system 提示词

![image](https://github.com/user-attachments/assets/6f6321cb-d3aa-4dda-8d26-bcd2ba46a73a)
我没有加任何参数，但是system提示仍然存在

**Comment by bdugsj** [comment]
一样存在该问题 版本4.8.11

**Comment by ZunbaRan** [comment]
> 1. 不能加提示
> 2. 不能文件上传
> 3. 不能知识库
> 
> 不然都会有 system 提示词

![image](https://github.com/user-attachments/assets/50ef25c0-fa4b-4d3b-ab42-7f2078256ceb)
我这里有同样的问题，没有携带任何系统提示词，不应该把问题改为closed

**Comment by c121914yu** [comment]
> > 1. 不能加提示
> > 2. 不能文件上传
> > 3. 不能知识库
> > 
> > 不然都会有 system 提示词
> 
> ![image](https://github.com/user-attachments/assets/50ef25c0-fa4b-4d3b-ab42-7f2078256ceb)
> 我这里有同样的问题，没有携带任何系统提示词，不应该把问题改为closed

因为都不关注下 release，都写的很清楚了:  https://github.com/labring/FastGPT/releases/tag/v4.8.11-fix😅

**Comment by ZunbaRan** [comment]
> > > 1. 不能加提示
> > > 2. 不能文件上传
> > > 3. 不能知识库
> > > 
> > > 不然都会有 system 提示词
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/30222123/397997621-50ef25c0-fa4b-4d3b-ab42-7f2078256ceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjQwOTYsIm5iZiI6MTczNTEyMzc5NiwicGF0aCI6Ii8zMDIyMjEyMy8zOTc5OTc2MjEtNTBlZjI1YzAtZmE0Yi00ZDNiLWFiNDItN2YyMDc4MjU2Y2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDEwNDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NWE2YzAxY2FjNDRkZDlkNWZmYTIyYjhlMDU4YWU5NzJiOTQ3MTgyOTRmMTJjY2U0OWNhZDk3NDFkYzk3MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GPikSGmmX2Z4sUwMN14FU7Zij1LImtCN__0_Ff8b7Ps)
> > 我这里有同样的问题，没有携带任何系统提示词，不应该把问题改为closed
> 
> 因为都不关注下 release，都写的很清楚了: https://github.com/labring/FastGPT/releases/tag/v4.8.11-fix 😅所以为啥让填版本号，不就让你关注下更新记录自己翻翻有没有问题。

接受批评，不好意思确实没有看更新版本，因为我直接用 docker-compsoe 部署的，感谢解答
