### ISSUE TITLE
基础功能：表单输入，在进行api调用时，无法显示表单输入的信息

### ISSUE THREAD

**Issue by zpcr7** [labring/FastGPT#3110]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
1.进行工作流的编排时，引入了表单
![image](https://github.com/user-attachments/assets/0fc4e8e2-7c7f-44ab-8387-28c229041bd0)
2.表单内容如下
![image](https://github.com/user-attachments/assets/416d27fa-feb3-47ad-85ed-cb4fb9545ddf)
3.通过自测的时候，表单内容正常提示
![image](https://github.com/user-attachments/assets/6c57c748-188f-4b4f-ab29-90b3faf62c01)
4.通过api访问
![image](https://github.com/user-attachments/assets/048befa4-523e-41f0-9e4d-4d85553315ee)
5.表单内容无法回显
![image](https://github.com/user-attachments/assets/abc7b2ed-d98f-4702-9c82-1234581518a5)
6.然后又在服务器上测试
![image](https://github.com/user-attachments/assets/ddb28056-5fee-4cc2-9b82-bad45b1b0bc8)
7.还是无法提示表单的内容
![image](https://github.com/user-attachments/assets/1eda1504-03d3-4da5-99ff-542d8781c03b)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没传 detail=true
