### ISSUE TITLE
对话接口无错误反馈

### ISSUE THREAD

**Issue by sun-timer** [labring/FastGPT#3114]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.11

**问题描述, 日志截图**
输入任意请求内容返回均为200，未提示问题；appId需要到哪里获取，现有api接口没有相应的输出
![image](https://github.com/user-attachments/assets/528ed163-451c-4db8-a0cf-6b2eb2a7871e)

**复现步骤**
通过api获取某个应用的历史记录

**预期结果**
![image](https://github.com/user-attachments/assets/92affba6-adf4-4857-9ea3-abc752931c89)

**相关截图**

**Comment by VViiepan** [comment]
appId就是你生成的应用的id，可以通过F12查看init接口，它的返回里面就有appId参数，我也有个问题请教，你的请求里cookie有加吗

**Comment by sun-timer** [comment]
> appId就是你生成的应用的id，可以通过F12查看init接口，它的返回里面就有appId参数，我也有个问题请教，你的请求里cookie有加吗

需要添加cookie吗？我没有加

**Comment by VViiepan** [comment]
> > appId就是你生成的应用的id，可以通过F12查看init接口，它的返回里面就有appId参数，我也有个问题请教，你的请求里cookie有加吗
> 
> 需要添加cookie吗？我没有加

我不加cookie报403：
{
    "code": 403,
    "statusText": "unAuthorization",
    "message": "common:code_error.error_message.403",
    "data": null
}

**Comment by c121914yu** [comment]
目前可以从 url 上获取
