### ISSUE TITLE
求教大佬! 通过API接口的方法重构对话页面

### ISSUE THREAD

**Issue by VViiepan** [labring/FastGPT#3116]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√ ] 私有部署版本, 具体版本号:V4.8.9 

**问题描述, 日志截图**
求教各位大佬，我现在正在按照https://doc.tryfastgpt.ai/docs/development/openapi/chat/
中的API形式重构对话页面（前端重新写，在API接口前再包一层控制访问权限），但是在这个过程中遇到了以下一些问题，所有接口我都已经添加了--header 'Authorization: Bearer {{apikey}}'参数，：
1.在进入对话页面时，会调用getHistories接口对吧，其中body有两个参数，一个appId应该从哪里取（还是说可以拿到应用id后写死），另一个source参数-对话源是什么意思，从哪里取？
2.我在调用getHistories接口时，如果不加cookie参数，会报403：
请求：{
    "appId": "66d80d9771b0c64b5cee9c20",
    "offset": 0,
    "pageSize": 20,
    "source": "api"
}
返回：{
    "code": 403,
    "statusText": "unAuthorization",
    "message": "common:code_error.error_message.403",
    "data": null
}
这是不是意味着api接口都是通过cookie去区分用户权限的，如果是的话，是不是得所有用户都需要有一个账号密码，登陆后才能取到cookie，才能实现上述区分用户的功能？
3.在初次进入对话页面时，会自动调用init初始化对话接口，这个接口也有两个参数，appId和chatId，appId和上面一样是写死？然后chatId在新建对话时是由前端随机生成的吗
**复现步骤**

**预期结果**

**相关截图**
<img width="585" alt="17313751238004" src="https://github.com/user-attachments/assets/a69dd16a-df1e-43c4-b0e9-1fcf80dda147">

**Comment by 2277419213** [comment]
路过顺手解答一下问题，不代表官方
1、getHistories是获取应用的历史记录，appId则是这个应用的唯一标识，这个appId可以从工作台里面，点进应用，查看地址栏，可以看到地址栏有个appId，这个就是你要的appId，另外source参数是来源标识，在对话的时候存进去chats的一个字段。
分别对应以下标识，官方没有注释是来源于什么渠道，不过可以看个大概，用api对话的，就是api标识。
test = 'test',
online = 'online',
share = 'share',
api = 'api',
team = 'team',
feishu = 'feishu',
official_account = 'official_account',
wecom = 'wecom'
2、你的调用方式没有错，是符合文档中https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95，描述的使用方式，不过根据官方的源码看来，源码本身就没有设计该功能，不知道是不是在商业版源码中，projects\app\src\pages\api\core\chat\getHistories.ts，不过有需要的话，可以自己二开一下，这个难度不是很大。
3、这个问题中的appId同上第一所示，这里看到的appId和工作台里面点进去看到appId一致，你也可以取这里的值，chatId是对话的唯一标识，标识这个应用的唯一一个对话，这个是没有规律的，同一个id表示同一个对话，可以自己生成，官方对话中确实是前端随机生成的

**Comment by VViiepan** [comment]
> 路过顺手解答一下问题，不代表官方 1、getHistories是获取应用的历史记录，appId则是这个应用的唯一标识，这个appId可以从工作台里面，点进应用，查看地址栏，可以看到地址栏有个appId，这个就是你要的appId，另外source参数是来源标识，在对话的时候存进去chats的一个字段。 分别对应以下标识，官方没有注释是来源于什么渠道，不过可以看个大概，用api对话的，就是api标识。 test = 'test', online = 'online', share = 'share', api = 'api', team = 'team', feishu = 'feishu', official_account = 'official_account', wecom = 'wecom' 2、你的调用方式没有错，是符合文档中[https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95，描述的使用方式，不过根据官方的源码看来，源码本身就没有设计该功能，不知道是不是在商业版源码中，projects\app\src\pages\api\core\chat\getHistories.ts，不过有需要的话，可以自己二开一下，这个难度不是很大。](https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95%EF%BC%8C%E6%8F%8F%E8%BF%B0%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%A0%B9%E6%8D%AE%E5%AE%98%E6%96%B9%E7%9A%84%E6%BA%90%E7%A0%81%E7%9C%8B%E6%9D%A5%EF%BC%8C%E6%BA%90%E7%A0%81%E6%9C%AC%E8%BA%AB%E5%B0%B1%E6%B2%A1%E6%9C%89%E8%AE%BE%E8%AE%A1%E8%AF%A5%E5%8A%9F%E8%83%BD%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%B8%8D%E6%98%AF%E5%9C%A8%E5%95%86%E4%B8%9A%E7%89%88%E6%BA%90%E7%A0%81%E4%B8%AD%EF%BC%8Cprojects%5Capp%5Csrc%5Cpages%5Capi%5Ccore%5Cchat%5CgetHistories.ts%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%9C%89%E9%9C%80%E8%A6%81%E7%9A%84%E8%AF%9D%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%B7%B1%E4%BA%8C%E5%BC%80%E4%B8%80%E4%B8%8B%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%9A%BE%E5%BA%A6%E4%B8%8D%E6%98%AF%E5%BE%88%E5%A4%A7%E3%80%82) 3、这个问题中的appId同上第一所示，这里看到的appId和工作台里面点进去看到appId一致，你也可以取这里的值，chatId是对话的唯一标识，标识这个应用的唯一一个对话，这个是没有规律的，同一个id表示同一个对话，可以自己生成，官方对话中确实是前端随机生成的

感谢大佬解答！我正在试图往用户表里加账号，看看能不能在开源版实现多账户数据隔离

**Comment by 2277419213** [comment]
> 路过顺手解答一下问题，不代表官方 1、getHistories是获取应用的历史记录，appId则是这个应用的唯一标识，这个appId可以从工作台里面，点进应用，查看地址栏，可以看到地址栏有个appId，这个就是你要的appId，另外source参数是来源标识，在对话的时候存进去chats的一个字段。 分别对应以下标识，官方没有注释是来源于什么渠道，不过可以看个大概，用api对话的，就是api标识。 test = 'test', online = 'online', share = 'share', api = 'api', team = 'team', feishu = 'feishu', official_account = 'official_account', wecom = 'wecom' 2、你的调用方式没有错，是符合文档中[https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95，描述的使用方式，不过根据官方的源码看来，源码本身就没有设计该功能，不知道是不是在商业版源码中，projects\app\src\pages\api\core\chat\getHistories.ts，不过有需要的话，可以自己二开一下，这个难度不是很大。](https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95%EF%BC%8C%E6%8F%8F%E8%BF%B0%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%A0%B9%E6%8D%AE%E5%AE%98%E6%96%B9%E7%9A%84%E6%BA%90%E7%A0%81%E7%9C%8B%E6%9D%A5%EF%BC%8C%E6%BA%90%E7%A0%81%E6%9C%AC%E8%BA%AB%E5%B0%B1%E6%B2%A1%E6%9C%89%E8%AE%BE%E8%AE%A1%E8%AF%A5%E5%8A%9F%E8%83%BD%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%B8%8D%E6%98%AF%E5%9C%A8%E5%95%86%E4%B8%9A%E7%89%88%E6%BA%90%E7%A0%81%E4%B8%AD%EF%BC%8Cprojects%5Capp%5Csrc%5Cpages%5Capi%5Ccore%5Cchat%5CgetHistories.ts%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%9C%89%E9%9C%80%E8%A6%81%E7%9A%84%E8%AF%9D%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%B7%B1%E4%BA%8C%E5%BC%80%E4%B8%80%E4%B8%8B%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%9A%BE%E5%BA%A6%E4%B8%8D%E6%98%AF%E5%BE%88%E5%A4%A7%E3%80%82) 3、这个问题中的appId同上第一所示，这里看到的appId和工作台里面点进去看到appId一致，你也可以取这里的值，chatId是对话的唯一标识，标识这个应用的唯一一个对话，这个是没有规律的，同一个id表示同一个对话，可以自己生成，官方对话中确实是前端随机生成的

@c121914yu 大佬看看2这个需求，确认一下这个方法是不是开源也可以具备，可以的话我就提pr了

**Comment by c121914yu** [comment]
> > 路过顺手解答一下问题，不代表官方 1、getHistories是获取应用的历史记录，appId则是这个应用的唯一标识，这个appId可以从工作台里面，点进应用，查看地址栏，可以看到地址栏有个appId，这个就是你要的appId，另外source参数是来源标识，在对话的时候存进去chats的一个字段。 分别对应以下标识，官方没有注释是来源于什么渠道，不过可以看个大概，用api对话的，就是api标识。 test = 'test', online = 'online', share = 'share', api = 'api', team = 'team', feishu = 'feishu', official_account = 'official_account', wecom = 'wecom' 2、你的调用方式没有错，是符合文档中[https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95，描述的使用方式，不过根据官方的源码看来，源码本身就没有设计该功能，不知道是不是在商业版源码中，projects\app\src\pages\api\core\chat\getHistories.ts，不过有需要的话，可以自己二开一下，这个难度不是很大。](https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95%EF%BC%8C%E6%8F%8F%E8%BF%B0%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%A0%B9%E6%8D%AE%E5%AE%98%E6%96%B9%E7%9A%84%E6%BA%90%E7%A0%81%E7%9C%8B%E6%9D%A5%EF%BC%8C%E6%BA%90%E7%A0%81%E6%9C%AC%E8%BA%AB%E5%B0%B1%E6%B2%A1%E6%9C%89%E8%AE%BE%E8%AE%A1%E8%AF%A5%E5%8A%9F%E8%83%BD%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%B8%8D%E6%98%AF%E5%9C%A8%E5%95%86%E4%B8%9A%E7%89%88%E6%BA%90%E7%A0%81%E4%B8%AD%EF%BC%8Cprojects%5Capp%5Csrc%5Cpages%5Capi%5Ccore%5Cchat%5CgetHistories.ts%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%9C%89%E9%9C%80%E8%A6%81%E7%9A%84%E8%AF%9D%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%B7%B1%E4%BA%8C%E5%BC%80%E4%B8%80%E4%B8%8B%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%9A%BE%E5%BA%A6%E4%B8%8D%E6%98%AF%E5%BE%88%E5%A4%A7%E3%80%82) 3、这个问题中的appId同上第一所示，这里看到的appId和工作台里面点进去看到appId一致，你也可以取这里的值，chatId是对话的唯一标识，标识这个应用的唯一一个对话，这个是没有规律的，同一个id表示同一个对话，可以自己生成，官方对话中确实是前端随机生成的
> 
> @c121914yu 大佬看看2这个需求，确认一下这个方法是不是开源也可以具备，可以的话我就提pr了

应该不行，鉴权时候，会鉴用户有没有对于 app read 权限的。理论上，你只能在顶层再套一层权限（也就是，你需要自己维护一套 chatId）

**Comment by 2277419213** [comment]
> > > 路过顺手解答一下问题，不代表官方 1、getHistories是获取应用的历史记录，appId则是这个应用的唯一标识，这个appId可以从工作台里面，点进应用，查看地址栏，可以看到地址栏有个appId，这个就是你要的appId，另外source参数是来源标识，在对话的时候存进去chats的一个字段。 分别对应以下标识，官方没有注释是来源于什么渠道，不过可以看个大概，用api对话的，就是api标识。 test = 'test', online = 'online', share = 'share', api = 'api', team = 'team', feishu = 'feishu', official_account = 'official_account', wecom = 'wecom' 2、你的调用方式没有错，是符合文档中[https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95，描述的使用方式，不过根据官方的源码看来，源码本身就没有设计该功能，不知道是不是在商业版源码中，projects\app\src\pages\api\core\chat\getHistories.ts，不过有需要的话，可以自己二开一下，这个难度不是很大。](https://doc.tryfastgpt.ai/docs/development/openapi/chat/#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95%EF%BC%8C%E6%8F%8F%E8%BF%B0%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%A0%B9%E6%8D%AE%E5%AE%98%E6%96%B9%E7%9A%84%E6%BA%90%E7%A0%81%E7%9C%8B%E6%9D%A5%EF%BC%8C%E6%BA%90%E7%A0%81%E6%9C%AC%E8%BA%AB%E5%B0%B1%E6%B2%A1%E6%9C%89%E8%AE%BE%E8%AE%A1%E8%AF%A5%E5%8A%9F%E8%83%BD%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%B8%8D%E6%98%AF%E5%9C%A8%E5%95%86%E4%B8%9A%E7%89%88%E6%BA%90%E7%A0%81%E4%B8%AD%EF%BC%8Cprojects%5Capp%5Csrc%5Cpages%5Capi%5Ccore%5Cchat%5CgetHistories.ts%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%9C%89%E9%9C%80%E8%A6%81%E7%9A%84%E8%AF%9D%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%B7%B1%E4%BA%8C%E5%BC%80%E4%B8%80%E4%B8%8B%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%9A%BE%E5%BA%A6%E4%B8%8D%E6%98%AF%E5%BE%88%E5%A4%A7%E3%80%82) 3、这个问题中的appId同上第一所示，这里看到的appId和工作台里面点进去看到appId一致，你也可以取这里的值，chatId是对话的唯一标识，标识这个应用的唯一一个对话，这个是没有规律的，同一个id表示同一个对话，可以自己生成，官方对话中确实是前端随机生成的
> > 
> > 
> > @c121914yu 大佬看看2这个需求，确认一下这个方法是不是开源也可以具备，可以的话我就提pr了
> 
> 应该不行，鉴权时候，会鉴用户有没有对于 app read 权限的。理论上，你只能在顶层再套一层权限（也就是，你需要自己维护一套 chatId）。也可以根据分享页面的 outlinkUId 来设置多用户，自己维护一套 uid，当outlinkUId来用。

![image](https://github.com/user-attachments/assets/9a6cb194-fbfc-4bd9-b698-4a6f8d31477a)
现在是没有文档的这个方法，用apikey的方式会返回403
![image](https://github.com/user-attachments/assets/9df223f3-bce1-43a6-8c8a-7bd60a55520c)
源码补充一个authApiKey的认证方式就可以了

**Comment by VViiepan** [comment]
给遇到同问题的同学：最后选择了自己维护一套outlinkuid的方式做的
