### ISSUE TITLE
插件创建传参数问题

### ISSUE THREAD

**Issue by nianshengmei** [labring/FastGPT#3119]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 私有部署版本, 具体版本号: v4.8.13-alpha

**问题描述, 日志截图**
我试图创建一个较为复杂的图表，但是参数传递出现了问题
<img width="1683" alt="image" src="https://github.com/user-attachments/assets/883e5fd8-6169-4ed6-8d6f-1321a87ac971">

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/af9785eb-358d-46e2-8c25-69cb1fa8ab8b">

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
麻烦提供下完整的图，看不出你是干了啥

**Comment by nianshengmei** [comment]
我创建了一个插件<img width="1811" alt="image" src="https://github.com/user-attachments/assets/70309bca-c8f2-4378-bd36-dea0fed6a8d4">
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/49385602-2c6d-4bf1-91f3-89dfffb741c2">
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/979cf859-f098-4f93-8e71-72789f8bc7c1">

**Comment by nianshengmei** [comment]
> 麻烦提供下完整的图，看不出你是干了啥

如上
