### ISSUE TITLE
官方镜像，执行pnpm i报错，提示

### ISSUE THREAD

**Issue by dignfei** [labring/FastGPT#3125]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
ghcr.io/labring/fastgpt:v4.8.11 镜像

**问题描述, 日志截图**
<img width="937" alt="image" src="https://github.com/user-attachments/assets/2bc9f39f-cf50-4259-a4f7-1159b35c3650">

**复现步骤**
将最新的代码4.8.13-dev拷贝到/app目录下，执行：
npm config set registry https://registry.npmmirror.com
apk add --no-cache libc6-compat && npm install -g pnpm@9.4.0
pnpm i

出现报错，这个chakra-cli不知道是什么，试验了多个包都无法找到这个chakra-cli

**预期结果**
正常编译

**相关截图**

**Comment by c121914yu** [comment]
没看懂你操作了啥，一下 4.8.11，一下 4.8.13。
还是拷贝了啥内容？开发应该是直接 clone
