### ISSUE TITLE
知识库无法精确匹配到需要的信息

### ISSUE THREAD

**Issue by lp380490944** [labring/FastGPT#313]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
知识库相关的内容无法精确的检索到，例如有一本书里讲大黄花鱼的营养成分的，原文中明明有，但是每次引用的几个都不是的，常规的检索是可以检索到的
**复现步骤**
可能是我的知识库文本有点多
**预期结果**
能够精确匹配到需要检索的信息
**相关截图**
<img width="1139" alt="image" src="https://github.com/labring/FastGPT/assets/13585771/2951fecc-0e3e-42b3-8039-00d55f0f7942">
<img width="1113" alt="image" src="https://github.com/labring/FastGPT/assets/13585771/56fe9536-bda2-4658-9b87-afd19406aa46">

**Comment by lp380490944** [comment]
> 直接分段是这样的，内容多杂效果不咋滴。

有啥好的建议不？现在这个情况根本没有办法在生产环境使用

**Comment by c121914yu** [comment]
> > 直接分段是这样的，内容多杂效果不咋滴。
> 
> 有啥好的建议不？现在这个情况根本没有办法在生产环境使用

QA拆分，更小的颗粒，手动优化。

**Comment by c121914yu** [comment]
这种数据，我觉得更适合你本地做好分段，然后导入。因为他们是有一定结构化的。
