### ISSUE TITLE
请教如何在高级编排中结合大模型语义理解使用图形插件画出折线图。

### ISSUE THREAD

**Issue by LRCgtp** [labring/FastGPT#3139]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**
问题举例：某省电信1~6主营收入分别120万元、300万元、450万元、500万元、560万元、650万元，请结合以上信息给出1~6月电信主营收入分布情况，用折线图表示。
**相关截图**

**Comment by newfish-cmyk** [comment]
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/dc9ba009-ad05-4c93-a085-e81a2cd78404">
试试这样行不行

**Comment by LRCgtp** [comment]
我试了清华质谱glm4模型，不行，模型工具输出数据如下，请老师指点一下，如果清华质谱模型不支持，请问下国内哪些模型支持。
![Uploading 1731473814105.jpg…]()

**Comment by c121914yu** [comment]
智谱、qwen、deepseek、moonshot的 openai 格式都支持工具调用。（oneapi 不能选千问，智谱渠道，需要用 openai 渠道，然后代理填写对应厂商的地址）
