### ISSUE TITLE
最新的代码是不是有bug，运行之前编排的工作流会报错，新建的就不会有问题

### ISSUE THREAD

**Issue by silencezhang7** [labring/FastGPT#3154]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
编排时，发送消息会报错，只存在之前编排的应用中，新建的就没有问题：
![image](https://github.com/user-attachments/assets/54462353-937a-4312-9721-2608e40c4375)

**Comment by c121914yu** [comment]
看了下几个工作流，目前还没遇到，再看看

**Comment by duskcouple** [comment]
好像全局变量都挂了，用/引用全局变量的值都是空的，引用不到，目前在HTTP请求的插件中是这种情况。没有删除应用重建，嫌麻烦，等着看别人是不是也如此，都这样，那就不是个体问题了

**Comment by c121914yu** [comment]
<img width="962" alt="image" src="https://github.com/user-attachments/assets/2069009c-5cdd-4c77-bb0c-0633be20699f">
看着还行

**Comment by heart18z** [comment]
> <img alt="image" width="962" src="https://private-user-images.githubusercontent.com/50446880/386071079-2069009c-5cdd-4c77-bb0c-0633be20699f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjYxODEsIm5iZiI6MTczMTU2NTg4MSwicGF0aCI6Ii81MDQ0Njg4MC8zODYwNzEwNzktMjA2OTAwOWMtNWNkZC00Yzc3LWJiMGMtMDYzM2JlMjA2OTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA2MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzFmNTYzYzkxMTE3MzllZDU5YWEwYTQxMWE0M2JlNjRkNjI5YTIyNGQ3ODA2NmFjMGVhNGJiMTdlNjczNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DSYNl9BArK7TSZ4dtMt3FHuwwwwdgpocS25SerrHZr0"> 看着还行

是新版本的全局状态的变量名和描述有出入，我也遇到了。
![image](https://github.com/user-attachments/assets/3cfbc552-5b12-48c7-a335-c4c7215f85f8)
![image](https://github.com/user-attachments/assets/da6cf2b6-b699-46f0-bc7f-86ee2436382f)

**Comment by c121914yu** [comment]
> > <img alt="image" width="962" src="https://private-user-images.githubusercontent.com/50446880/386071079-2069009c-5cdd-4c77-bb0c-0633be20699f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjYxODEsIm5iZiI6MTczMTU2NTg4MSwicGF0aCI6Ii81MDQ0Njg4MC8zODYwNzEwNzktMjA2OTAwOWMtNWNkZC00Yzc3LWJiMGMtMDYzM2JlMjA2OTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA2MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzFmNTYzYzkxMTE3MzllZDU5YWEwYTQxMWE0M2JlNjRkNjI5YTIyNGQ3ODA2NmFjMGVhNGJiMTdlNjczNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DSYNl9BArK7TSZ4dtMt3FHuwwwwdgpocS25SerrHZr0"> 看着还行
> 
> 是新版本的全局状态的变量名和描述有出入，我也遇到了。 ![image](https://private-user-images.githubusercontent.com/106878712/386072450-3cfbc552-5b12-48c7-a335-c4c7215f85f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjY0OTUsIm5iZiI6MTczMTU2NjE5NSwicGF0aCI6Ii8xMDY4Nzg3MTIvMzg2MDcyNDUwLTNjZmJjNTUyLTViMTItNDhjNy1hMzM1LWM0YzcyMTVmODVmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNjM2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDhiYzA1MjFkZmI0MTUzNDllNzNlOTQ2MGJhMjYzNTNjODMwN2JiZmZkODVjZmZhOWU2YzIyZmI5Zjk1NzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mZqxBBQMxQ0jSx9wr7GGqHu66nlgO20ypznwU_h6VFg) ![image](https://private-user-images.githubusercontent.com/106878712/386072497-da6cf2b6-b699-46f0-bc7f-86ee2436382f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjY0OTUsIm5iZiI6MTczMTU2NjE5NSwicGF0aCI6Ii8xMDY4Nzg3MTIvMzg2MDcyNDk3LWRhNmNmMmI2LWI2OTktNDZmMC1iYzdmLTg2ZWUyNDM2MzgyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNjM2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWYzZTkxZmVmYTBhMjJhZmFmMDM1YzVlMzcxMTBjMjZkM2QyMWY5YzkxMGZmNGQ3MmY5MTRhMjRhZWZlYjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MXQPlegmDLaMLPtD-2QGjLL5PqXKCdIU9H5Sp5BVusI)

你保存下就一样了

**Comment by duskcouple** [comment]
更新下全局变量试试，我是默认赋值的或者必填第一次对话就需要输入的没问题，这个全局变量的值OK，
如果工作流中有更新了这个全局变量，更新的变量的值只会在本轮对话中有效，第二次再次输入问题进行对话，你会发现这个更新后的全局变量的值没了

**Comment by duskcouple** [comment]
我工作流中有个对某个全局变量判空 IF ELSE的处理，第一次更新全局变量后，再次对话发现流程总是走为空那条，后来用指定回复测试了下，全局变量更新没有成功，后续再对话还是为空

**Comment by c121914yu** [comment]
> 我工作流中有个对某个全局变量判空 IF ELSE的处理，第一次更新全局变量后，再次对话发现流程总是走为空那条，后来用指定回复测试了下，全局变量更新没有成功，后续再对话还是为空

我试试。倒是发现了，全局变量，会导致发问题时候，校验错误，导致无法发出。

**Comment by c121914yu** [comment]
> 我工作流中有个对某个全局变量判空 IF ELSE的处理，第一次更新全局变量后，再次对话发现流程总是走为空那条，后来用指定回复测试了下，全局变量更新没有成功，后续再对话还是为空

https://github.com/labring/FastGPT/pull/3156 发现了～ 是更新变量的问题，这里修复下，待会儿发布个 fix
