### ISSUE TITLE
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 3f562f77-83f6-44ba-aa2f-748fff4127a0::mvjnnilqvlmw868bzsgwffgg7: "/projects/app/data": not found

### ISSUE THREAD

**Issue by chenkai89** [labring/FastGPT#3165]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.13

**问题描述, 日志截图**
![图片](https://github.com/user-attachments/assets/a04575d5-701c-4b33-acea-65d2098dc2cb)

**复现步骤**
docker build -t fastgpt2 ./projects/app/

**预期结果**
构建成功

**相关截图**

**Comment by c121914yu** [comment]
命令就不对，看 dev.md
