### ISSUE TITLE
最新代码分享链接AI回复的时候好像看不到执行过程，是代码改了吗

### ISSUE THREAD

**Issue by silencezhang7** [labring/FastGPT#3171]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

最新代码分享链接AI回复的时候好像看不到执行过程了，以前记得有AI回复等过程描述
![image](https://github.com/user-attachments/assets/341eb8a7-441b-4f6e-90d6-e357cd725b66)

**Comment by c121914yu** [comment]
要打开开关

**Comment by SDAIer** [comment]
打开哪个开关
