### ISSUE TITLE
目前新版本是不能直接调ollama的识别图片的api接口么？

### ISSUE THREAD

**Issue by Forevery1** [labring/FastGPT#3172]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![Screenshot_2024-11-16-09-40-51-386_com.microsoft.rdc.androidx.jpg](https://github.com/user-attachments/assets/915e5ca0-1d18-43d1-aec5-62e9cede3912)

**复现步骤**
调用ollama的minicpm-v模型，上传图片提问

**预期结果**
之前在4.8.12版本的时候是正常的，更新到4.8.13后就报错了

**相关截图**

**Comment by c121914yu** [comment]
可以参考升级文档增加资源 domain 环境变量。
或者加个环境变量 MULTIPLE_DATA_TO_BASE64=true。之前测试没删这个变量，一定要设置 true 才能转 base64 发送。

**Comment by Forevery1** [comment]
> 可以参考升级文档增加资源 domain 环境变量。
> 或者加个环境变量 MULTIPLE_DATA_TO_BASE64=true。之前测试没删这个变量，一定要设置 true 才能转 base64 发送。

已解决，非常感谢
