### ISSUE TITLE
新增知识库报错

### ISSUE THREAD

**Issue by hermitriver** [labring/FastGPT#3182]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.13-fix

**问题描述, 日志截图**
无法正常进入创建通用知识库页面

**复现步骤**
1. 访问管理后台
2. 左侧导航栏点击“知识库”
3. 点击“新建 -》通用知识库”
4. 页面黑屏仅显示出错信息“Application error: a client-side exception has occurred (see the browser console for more information).”，1-2秒后浏览器自动回退到访问知识库之前的页面，fastgpt容器内此时没信息输出

**预期结果**
正常进入新建知识库页面

**相关截图**
浏览器日志报错截图：
![image](https://github.com/user-attachments/assets/5037e32f-04cd-4354-bb50-83c1b2597d23)

**Comment by c121914yu** [comment]
<img width="933" alt="image" src="https://github.com/user-attachments/assets/3efc1646-72ed-4331-b243-bf5d52c5259b">
你把模型都设置 false 了

**Comment by hermitriver** [comment]
你们模板缺省datasetProcess设的是false，但是网上已经有人反馈过这个问题，所以之前就已经改成true了，但是知识库仍然报错

**Comment by c121914yu** [comment]
> 你们模板缺省datasetProcess设的是false，但是网上已经有人反馈过这个问题，所以之前就已经改成true了，但是知识库仍然报错

截图的就是模板😂哪里缺了。

**Comment by role11** [comment]
我也遇到了，这个咋搞的？改了半天config文件成功报这个错了：
TypeError: Cannot read properties of undefined (reading 'provider')
    at list-49257c16e810a353.js:1:21467
    at Array.map (<anonymous>)
    at N (list-49257c16e810a353.js:1:21408)
    at ad (framework-61d8b7214f67f72f.js:9:58402)
    at ud (framework-61d8b7214f67f72f.js:9:72732)
    at i (framework-61d8b7214f67f72f.js:9:120264)
    at oO (framework-61d8b7214f67f72f.js:9:99020)
    at framework-61d8b7214f67f72f.js:9:98887
    at oF (framework-61d8b7214f67f72f.js:9:98894)
    at ox (framework-61d8b7214f67f72f.js:9:95646)
