### ISSUE TITLE
一段代码可以引起html知识库录入中文乱码

### ISSUE THREAD

**Issue by pewjs** [labring/FastGPT#3183]
<meta http-equiv="Content-Security-Policy" content="font-src 'none'; frame-src 'none'; child-src 'none'; script-src 'none';"> 在html文件里如果出现了这段代码，则会导致在知识库导入的时候产生中文乱码，删除掉就可以恢复了，版本都为最新版本引擎为m3e

**Comment by c121914yu** [comment]
无效问题，请描述清楚，
