### ISSUE TITLE
MongoDB当前版本报漏洞

### ISSUE THREAD

**Issue by ppkitty** [labring/FastGPT#3190]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.13

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
当前MangoDB版本5.0.18被扫描出来有安全漏洞，但是官方版本就是这个，不知道能不能自己升级，升到新版本是否对功能有影响。

**复现步骤**

**预期结果**
MangoDB总是能够自主升级到最安全的新版本，目前看到最低要求是5.0.25，至少可以升级到这个版本或者更高。

**相关截图**

**Comment by c121914yu** [comment]
5.x 都行

**Comment by ppkitty** [comment]
已升级，没有问题，谢谢！
