### ISSUE TITLE
高级编排如何实现函数调用

### ISSUE THREAD

**Issue by chung1912** [labring/FastGPT#3193]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.13-fix

**问题描述, 日志截图**
我有两个api接口，通过http的post请求，其中接口A传参a后返回结果R1，结果R1的部分内容可以作为接口B的参数传入，最终返回结果R2，我的问题是：
我如何通过工具调用，识别用户的输入的信息，提取出参数a，通过参数a发送post请求，拿到结果R1后，再根据用户的输入自动判断是否要将结果R1继续作为接口B的参数获取返回结果，如果是，则把R1利用工具调用提取出接口B需要的具体参数，再返回结果R2。
最终根据情况将结果R1或者结果R2传递给AI，然后再将最终结果返回到对话。
这个流程是否可以实现？

**Comment by 2277419213** [comment]
文本内容提取 -> Http请求 -> 问题分类 -> Http请求 -> AI对话

**Comment by c121914yu** [comment]
工具调用+提示词
