### ISSUE TITLE
能否支持知识库来源手动输入？

### ISSUE THREAD

**Issue by phoben** [labring/FastGPT#320]
需求内容：在手动录入问答对时，可否将来源设为编辑框，可以自定义来源。
需求场景：为了数据库质量，我们可能采用手动录入的方式，将网址内容转录到知识库中，此时来源字段不应该是固定的”手动录入“，应该仍然是来源网址。
![image](https://github.com/labring/FastGPT/assets/55103351/12d052eb-f9aa-44a7-a6f6-9b35e1b3fd41)

**Comment by leekoko** [comment]
类似建议：在“直接分段”之后，可以配合 “手动输入” 自己补充问答上去

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Similar suggestion: After "direct segmentation", you can use "manual input" to add your own Q&A

**Comment by c121914yu** [comment]
4.5.1 采用集合概念后，去除了source
