### ISSUE TITLE
AI对话中回答要求如何修改

### ISSUE THREAD

**Issue by dreamfly32** [labring/FastGPT#3202]
![image](https://github.com/user-attachments/assets/45db37de-83c5-4c94-bf7a-41740950eb46)
![image](https://github.com/user-attachments/assets/8b079522-4521-4c03-b7b9-3b557371ce5f)

如图，上面要求markdown输出，导致公众号输出带一些*
我试了提示词设置不要markdown输出，无用。

**Comment by c121914yu** [comment]
修改高级编排里，知识库引用提示词，
