### ISSUE TITLE
插件无法正常发布

### ISSUE THREAD

**Issue by chung1912** [labring/FastGPT#3211]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.13-fix

**问题描述, 日志截图**
插件无法正常保存和发布，当选择“”保存“或者”“保存并发布”后，不能变更为保存，还是显示未保存，退出时弹出警告

**预期结果**
希望可以正常保存并发布插件

**相关截图**
![image](https://github.com/user-attachments/assets/b56ed29d-af4b-4c17-aaf2-ec0de782c537)

**Comment by c121914yu** [comment]
编排发下？没法复现。还有就是，有没有保存记录？

**Comment by c121914yu** [comment]
编排发下？我尝试删除系统配置，也还是会提示已保存。需要排查下，是哪里匹配不一致。 那个是否保存，不会影响是否真正保存了。

**Comment by chung1912** [comment]
> 编排发下？我尝试删除系统配置，也还是会提示已保存。需要排查下，是哪里匹配不一致。 那个是否保存，不会影响是否真正保存了。

复现不了，现在删除系统配置也能正常保存了
