### ISSUE TITLE
加入自定义全局变量无法发送消息

### ISSUE THREAD

**Issue by zxinglove** [labring/FastGPT#3215]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.13

**问题描述, 日志截图**

**复现步骤**
![1](https://github.com/user-attachments/assets/d4c6b9c3-4ffa-4d82-92dc-f1ec06a8d61c)
![2](https://github.com/user-attachments/assets/c269c9fb-47ad-4c5f-8f49-459654d41532)
取消自定义全局变量后，可以正常发送消息
**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
看 4.8.13-fix 说明
