### ISSUE TITLE
v4.8.13：悬停在某条知识库的QA上，知识库ID会挡住问题，有没有考虑将知识库ID显示在别的地方呢？

### ISSUE THREAD

**Issue by wbext** [labring/FastGPT#3225]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.13

**问题描述, 日志截图**
![知识库](https://github.com/user-attachments/assets/cd42001b-9bf8-4147-988a-9ebf3670d83b)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没有。不悬停就行了。
