### ISSUE TITLE
如何接入本地的baichuan2-13b-chat模型

### ISSUE THREAD

**Issue by Mr-IT007** [labring/FastGPT#323]
请问如何接入本地的baichuan2-13b-chat模型

**Comment by c121914yu** [comment]
和glm一样，自己部署个服务。

**Comment by c121914yu** [comment]
https://doc.fastgpt.run/docs/custom-models/chatglm2/

**Comment by daxiaraoming** [comment]
[接入 ChatGLM2-6B](https://github.com/labring/FastGPT/blob/3d7178d06f26153c565168ad8b972e2c2e31d69a/docSite/content/docs/custom-models/chatglm2.md?plain=1#L100-L117)
这里没理解，是ChatModels配置chatglm2，并且VectorModels配置M3E吗？必须使用M3E吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[Access to ChatGLM2-6B](https://github.com/labring/FastGPT/blob/3d7178d06f26153c565168ad8b972e2c2e31d69a/docSite/content/docs/custom-models/chatglm2.md?plain=1#L100-L117)
I don't understand here. Is ChatModels configured with chatglm2, and VectorModels configured with M3E? Do I have to use M3E?
