### ISSUE TITLE
快速本地开发运行时停在ready打印

### ISSUE THREAD

**Issue by sun-timer** [labring/FastGPT#3230]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: fastgpt: v4.8.1

**问题描述, 日志截图**
在执行快速本地开发时打印停止在ready，没有后续打印，不知道是不是卡住了
![image](https://github.com/user-attachments/assets/842a4601-4e9f-41b0-9b37-44c05b4a019b)

**复现步骤**

**预期结果**
是否有办法打印出运行日志，看看问题在哪
**相关截图**

**Comment by c121914yu** [comment]
🤔这不就成功了么，然后你访问页面就好了呢
