### ISSUE TITLE
127.0.0.1:40476/health\

### ISSUE THREAD

**Issue by ximilijiao** [labring/FastGPT#3241]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.14
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
在使用ollama嵌入模型时，发现embedding这个接口可用，但是FastGpt会调用127.0.0.1:40476/health\这个端口，这个端口ollama并没有出现，请问该如何修改
FastGPT截图
![image](https://github.com/user-attachments/assets/b747936e-c1e9-4de9-9cd8-9fac4054b513)

ollama服务端截图
![image](https://github.com/user-attachments/assets/d97db4c2-c889-46bc-bbb3-8b90c15b584a)
![image](https://github.com/user-attachments/assets/8866905b-7e97-4284-8c0e-ce6286754bd6)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
oneapi 没选择 ollma 渠道导致 404
