### ISSUE TITLE
上传文件报错 EACCES: permission denied, open '/tmp/aIQs6kGiQMUG.docx'

### ISSUE THREAD

**Issue by 305607610** [labring/FastGPT#3242]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.11-fix

**问题描述, 日志截图**
系统：centos7
docker compose 部署，上传文件报错， EACCES: permission denied, open '/tmp/aIQs6kGiQMUG.docx' ，请问是什么情况
截图如下
![image](https://github.com/user-attachments/assets/d617b939-8871-4347-a1ea-e81940b62735)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
看下是不是限制了 docker 权限

**Comment by BANGzys** [comment]
请问最终是怎么解决的呢
