### ISSUE TITLE
HTTP请求节点中JSON中使用系统变量不生效

### ISSUE THREAD

**Issue by xhzkp** [labring/FastGPT#3243]
遇到一个问题, 我在HTTP请求节点的JSON中使用了系统变量, 如下所示, 但是执行后都没生效: 
演示如下:
![BUG2](https://github.com/user-attachments/assets/29f9a3f1-edcf-423b-bc35-3c61c532a208)

``
{
  "sessionId": "{{chatId}}",
  "chatInput": "{{userChatInput}}"
}
```

**Comment by c121914yu** [comment]
1. 4.8.13  chatId 在调试中不存在
2. 没有 userChatInput 这个变量
