### ISSUE TITLE
工作流中判断器后加入ai对话，打印Cannot read properties of null(reading 'q')

### ISSUE THREAD

**Issue by sun-timer** [labring/FastGPT#3252]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.11

**问题描述, 日志截图，配置文件等**
在一个工作流中添加知识库搜索，输出连接一个判断器，之后添加了两个ai对话，希望没有在知识库中检索到时通过另一个ai模型进行联网搜索，但是执行过程中输出：
![image](https://github.com/user-attachments/assets/cdbf7505-e273-4a8a-8562-d131829703f5)
![image](https://github.com/user-attachments/assets/38775f53-04a8-4c78-a0c2-af72e597ba21)

**复现步骤**
![image](https://github.com/user-attachments/assets/12b43d81-ffaa-4e24-9652-99b0313e2fae)

**预期结果**

**相关截图**
如果知识库中检索成功则可以正常返回
![image](https://github.com/user-attachments/assets/7b54947f-6388-482d-809e-9aead15e5833)

**Comment by 305607610** [comment]
+1  我加了http组件  频繁报这个错

**Comment by c121914yu** [comment]
用最新版本测试该问题，之前已经有过类似 issue 了

**Comment by sun-timer** [comment]
> 用最新版本测试该问题，之前已经有过类似 issue 了。

哦哦谢谢了，问题已经解决，知识库调用那里必须要填内容才不会报错

**Comment by 578691200** [comment]
> > 用最新版本测试该问题，之前已经有过类似 issue 了。
> 
> 哦哦谢谢了，问题已经解决，知识库调用那里必须要填内容才不会报错

可以说下具体怎么解决吗？我也遇到这个问题了

**Comment by andh5351** [comment]
AI对话组件的知识库调用选择后，再清空内容也会遇到这种问题。
将Work Flow导出成Json，就会发现多出了一行脏配置："value": [null,null]
我使用的是v4.14.6版本。
解决方法1：选择正确的知识库调用返回结果
解决方法2：如果是误操作，那么只能删除AI对话组件，再用新组件就不会有脏配置信息了（或者导出json文件，手动删除，再导入也可）
