### ISSUE TITLE
工具调用HTTP请求 需要多轮搜索时显示结果异常

### ISSUE THREAD

**Issue by revjie0310** [labring/FastGPT#3253]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.13

**问题描述, 日志截图，配置文件等**
输入问题：
根据以下名单，请帮我搜索出每个通用名对应销量较高的 3 个商品名及厂家名称。输出格式为：序号 通用名 商品名 厂家名称。请每个药品通用名分别进行搜索整理。以下是名单：

1 、阿苯达唑胶囊；
2 、阿苯达唑颗粒；
-------------------------------------
输入问题后，调用了两次搜索请求，但是返回的结果不正确，对话框里的参数显示正确，但是查看详情里的参数是一致的，不知道具体什么原因

对话框截图如下：
![image](https://github.com/user-attachments/assets/a2dd5ec9-28a7-4359-bfcb-be9a947686dd)
查看详情截图如下：
![image](https://github.com/user-attachments/assets/d9ed6e2d-8dd5-483d-979d-9ce56482cc73)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没看懂哪里错了

**Comment by revjie0310** [comment]
![image](https://github.com/user-attachments/assets/777ae96c-c87d-4b37-b509-2e84e61356b3)
实际工具调用里的，两次搜索请求参数都一致，导致结果返回的信息都一致
但是对话框里的参数显示是不一样的

**Comment by c121914yu** [comment]
对话框中参数不也一致么？试了试没发现啥问题，感觉是你接口有问题

**Comment by CocoDuan2** [comment]
我和你遇到相同的问题,
我通过这样处理解决了
https://github.com/labring/FastGPT/pull/3372

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3502 暂时改成工具串行执行，而不是并行。
