### ISSUE TITLE
AI如何使用非流式输出

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#3255]
有些场景不需要ai直接输出内容，而是希望将第一个ai的回复输出给后面的节点进行处理，然后再回答问题。

但是由于ai是流式输出，全部输出完以后，后面的节点才能开始处理，这就导致用户一直在等待，体验较差。

有没有办法让ai不要流式输出，而是一次性快速输出信息让后面来处理，从而减少用户等待时间

测试过kimi 通义千问以及本地模型，使用提示词都无法控制

**Comment by duskcouple** [comment]
其实应该在类似AI对话的这类涉及到AI大模型交互的插件节点增加个配置开关来控制openai  api 的stream参数的true/false。openai的api格式stream参数可配置，说明是有必要的。一个复杂智能体应用中应用AI的节点大多不需要流式输出，因为流程中需要一次性获得完整输出来驱动下一步工作流程，流式输出只是在对话交互体验上感觉好。现在目前AI大模型应用都在搞智能体工作流编排，很多时候AI节点是用来在整体流程中完成某个功能任务，流式输出反而不适配这种需求。

**Comment by 2277419213** [comment]
![image](https://github.com/user-attachments/assets/4500e94b-7d6c-4d43-b613-15b96dddc81f)
![image](https://github.com/user-attachments/assets/7bc5c658-702d-46ff-8824-22df53932ce0)
![image](https://github.com/user-attachments/assets/fd2be5ef-2382-4027-81e6-7dfb8ae5e899)
![image](https://github.com/user-attachments/assets/0accc129-d44a-45a9-b0bf-15c4e8c57adb)
这里可能有一个假想误区，AI的流式输出和非流式输出的时间一致性应该是差不多的，本地模型取决于GPU的算力，外网大模型取决于网络速度，这里测试了本地化大模型和公网的GLM大模型，同样的内容，均是流式输出快一点点，你也可以用postman测试一下

**Comment by SDAIer** [comment]
> 其实应该在类似AI对话的这类涉及到AI大模型交互的插件节点增加个配置开关来控制openai api 的stream参数的true/false。openai的api格式stream参数可配置，说明是有必要的。一个复杂智能体应用中应用AI的节点大多不需要流式输出，因为流程中需要一次性获得完整输出来驱动下一步工作流程，流式输出只是在对话交互体验上感觉好。现在目前AI大模型应用都在搞智能体工作流编排，很多时候AI节点是用来在整体流程中完成某个功能任务，流式输出反而不适配这种需求。

你说的很对，的确需要

**Comment by SDAIer** [comment]
@2277419213 分析的对，也许的确是假象误区，等高手确认下

**Comment by c121914yu** [comment]
时间肯定是一样的
