### ISSUE TITLE
输入长文本内容后，AI回复的内容不是我想要的

### ISSUE THREAD

**Issue by sandy518-sandy** [labring/FastGPT#3259]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图，配置文件等**
想做一个AI打分工具，输入短文本后，可以按照打分规则返回打分的分数，但是输入长文本后，无法回复分数，而开始发散回答了，请问是我的配置出现问题了吗？还是应该继续在prompt中完善
**复现步骤**

**预期结果**

**相关截图**
![1](https://github.com/user-attachments/assets/2eb1a85c-34cc-4158-92b5-0d7070614fa2)
这个是长文本的
![2-1](https://github.com/user-attachments/assets/cf4dc93e-945c-47dc-aa90-6f2bdc8d07c5)
![2-2](https://github.com/user-attachments/assets/958ba20c-5744-4a16-b369-88078657a5be)
这个是可以出现评分的短文本的
![Uploading 3-1.png…]()

**Comment by sandy518-sandy** [comment]
烦请各位老师帮忙看一下

**Comment by c121914yu** [comment]
完善 prompt，换模型。。7b 模型，就别想用来做任务了，基本只能回答～
