### ISSUE TITLE
猜你想问，v4.8.14版本返回的结果默认是英文

### ISSUE THREAD

**Issue by yajsite** [labring/FastGPT#3261]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: v4.8.14

**问题描述, 日志截图，配置文件等**
通过测试验证v4.8.13和v4.8.14版本，发现猜你想问的结果会变成英文。通过抓取的参数发现调用/api/core/ai/agent/createQuestionGuide接口时，提交给模型接口的最后的一个对象content是英文的Prompt，应该是这个原因导致的
`{'messages': [ {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': 'You are an AI assistant tasked with predicting the user\'s next question based on the conversation history. Your goal is to generate 3 potential questions that will guide the user to continue the conversation. When generating these questions, adhere to the following rules:\n\n1. Use the same language as the user\'s last question in the conversation history.\n2. Keep each question under 20 characters in length.\n3. Return the questions in JSON format: ["question1", "question2", "question3"].\n\nAnalyze the conversation history provided to you and use it as context to generate relevant and engaging follow-up questions. Your predictions should be logical extensions of the current topic or related areas that the user might be interested in exploring further.\n\nRemember to maintain consistency in tone and style with the existing conversation while providing diverse options for the user to choose from. Your goal is to keep the conversation flowing naturally and help the user delve deeper into the subject matter or explore related topics.'}], 'model': 'xxxxx', 'max_tokens': 200, 'temperature': 0.1}`
**复现步骤**
如截图中直接提问就会返回
**预期结果**
返回对应语言的猜你想问内容
**相关截图**
![image](https://github.com/user-attachments/assets/d8733e51-be1c-4e56-92de-0fe200b9b177)

**Comment by c121914yu** [comment]
换个模型

**Comment by c121914yu** [comment]
<img width="844" alt="image" src="https://github.com/user-attachments/assets/4a01a306-3d34-42da-826d-cd96a17ffe85">
 prompt 对 gpt 挺稳的

**Comment by yajsite** [comment]
@c121914yu 应该不是模型的问题，我用的豆包pro模型，之前在fastgpt老版本没出现猜你想问变英文的情况。看了下代码，可能是这一块逻辑引起，在最后加了一段固定的Prompt。
![image](https://github.com/user-attachments/assets/feee9549-645f-4cc8-9e63-48e12d0ee072)

**Comment by SDAIer** [comment]
以前的版本的确是没这个问题，好像从4.8.11以后就这样了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月28日(周四) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 猜你想问，v4.8.14版本返回的结果默认是英文 (Issue #3261)




 
@c121914yu 应该不是模型的问题，我用的豆包pro模型，之前在fastgpt老版本没出现猜你想问变英文的情况。看了下代码，可能是这一块逻辑引起，在最后加了一段固定的Prompt。
 image.png (view on web)

**Comment by c121914yu** [comment]
> @c121914yu 应该不是模型的问题，我用的豆包pro模型，之前在fastgpt老版本没出现猜你想问变英文的情况。看了下代码，可能是这一块逻辑引起，在最后加了一段固定的Prompt。 ![image](https://private-user-images.githubusercontent.com/14304483/390668916-feee9549-645f-4cc8-9e63-48e12d0ee072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODA5MTgsIm5iZiI6MTczMjc4MDYxOCwicGF0aCI6Ii8xNDMwNDQ4My8zOTA2Njg5MTYtZmVlZTk1NDktNjQ1Zi00Y2M4LTllNjMtNDhlMTJkMGVlMDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA3NTY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0Y2E5Zjg3NzM1YzQzZWQxOTM0NTVjZTA4OWU4ZmQ0ZWNhMjc3N2M1YjNjNDE0M2IyYzk3NWNlNTIyYjNiMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ykbjNI4t44QMwAXLAulH3XsBS7AHAz0FFVQYSNpPWAQ)

那可能这个提示词不适合豆包了。

**Comment by SDAIer** [comment]
你加的prompt放在问题里吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月28日(周四) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 猜你想问，v4.8.14版本返回的结果默认是英文 (Issue #3261)




 
@c121914yu 应该不是模型的问题，我用的豆包pro模型，之前在fastgpt老版本没出现猜你想问变英文的情况。看了下代码，可能是这一块逻辑引起，在最后加了一段固定的Prompt。
 image.png (view on web)

**Comment by yajsite** [comment]
4.8.16版本猜你想问的自定义提示词功能，已经解决了这个问题
