### ISSUE TITLE
oneapi报错read: connection reset by peer

### ISSUE THREAD

**Issue by lgy1027** [labring/FastGPT#3266]
现在部署registry.cn-hangzhou.aliyuncs.com/fastgpt/one-api:v0.6.6 # 阿里云一直重启，报错如下：
![image](https://github.com/user-attachments/assets/437183d2-cc44-45ee-95c5-3da09b5eeb29)

**Comment by Upcreat** [comment]
我也遇到了，使用默认的没什么问题

**Comment by c121914yu** [comment]
网络不行，拉不到token 文件，参考 oneapi github 说明，手动下载配置文件
