### ISSUE TITLE
ACCESS_TOKEN在哪找？

### ISSUE THREAD

**Issue by zhizhuaa** [labring/FastGPT#3273]
![image](https://github.com/user-attachments/assets/f9d77748-cf0f-46b5-b424-964c864811b5)

**Comment by 357656763** [comment]
+1

**Comment by c121914yu** [comment]
。。这不是让你自己填写的么

**Comment by 357656763** [comment]
填什么😫
，我写的mytoken。但是没用

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月29日(周五) 下午5:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] ACCESS_TOKEN在哪找？ (Issue #3273)




 
。。这不是让你自己填写的么
