### ISSUE TITLE
通用知识库通过接口上传PDF文件，点击“查看原始内容”，报错提示“未能加载 PDF 文档。” 

### ISSUE THREAD

**Issue by ans1988dog** [labring/FastGPT#3274]
例行检查

[ √] 我已确认目前没有类似 issue
[ √] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
[ √] 我使用了自己的 key，并确认我的 key 是可正常使用的
[ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
你的版本

 公有云版本
[ √] 私有部署版本, 具体版本号: v4.8.10

**问题描述, 日志截图，配置文件等**
通过接口上传知识库PDF文件，查看原始内容时报错未能加载PDF文档
![image](https://github.com/user-attachments/assets/8ab64d6b-a6e1-43f4-a842-18bc57f5debe)
![image](https://github.com/user-attachments/assets/a914680b-934e-4725-b29f-b45d903d52dd)

**但是通过手动上传的操作，却可以正常查看原始内容！！！**

**复现步骤**
1、手动新建知识库；
2、通过调用接口上传pdf文件；
**/api/core/dataset/collection/create/localFile**
3、上传成功后，点击查看原始内容，报错“未能加载PDF文档。”
**预期结果**
点击“查看原始内容”按钮，可以查看pdf源文件
**相关截图**

**Comment by c121914yu** [comment]
4.8.13 和 4.8.14 未复现，请用最新版测试后重新反馈。以及可以检查数据库中是否存在该文件。
