### ISSUE TITLE
通过“免登陆窗口”分享出去的智能体，别人无法点踩提交反馈，提示无权限

### ISSUE THREAD

**Issue by kid20210528** [labring/FastGPT#3279]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.14

**问题描述, 日志截图，配置文件等**
通过“免登陆窗口”分享出去的智能体，别人无法点踩提交反馈，提示无权限

**复现步骤**

**预期结果**

**相关截图**
![1732884347034](https://github.com/user-attachments/assets/78c8fa6e-eb49-43de-a6fe-8fe442ec2edd)

![1732884229791](https://github.com/user-attachments/assets/a39208bf-1bfe-4131-92ee-21b417fce44f)

**Comment by SDAIer** [comment]
而且对话日志里也看不到点赞或评论信息、而且好评和差评的图标也不显示
