### ISSUE TITLE
奇怪的问题

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#3283]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图，配置文件等**

有没有人遇到我这样的问题？
我的电脑配置不算好，以往是能正常使用这个项目的，最近回坑之后一进入流程编排页面就崩溃。
我怀疑我的电脑是不是老化了，还去dify那里试了试。。。
gpu貌似占用率很高
请看：

**复现步骤**

https://github.com/user-attachments/assets/ad77dee9-4d4c-4bd6-8d68-090b06332931

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
F12 看看，估计是应用太老，有空字段没兼容导致的。

**Comment by bincooo** [comment]
是你们的官网上的
<img width="1950" alt="Screenshot 2024-12-01 at 23 07 03" src="https://github.com/user-attachments/assets/28f95e67-da22-49c5-89e9-61b306680b2c">

**Comment by c121914yu** [comment]
> 是你们的官网上的
> <img width="1950" alt="Screenshot 2024-12-01 at 23 07 03" src="https://github.com/user-attachments/assets/28f95e67-da22-49c5-89e9-61b306680b2c">
> 

可以看看，是不是开了翻译

**Comment by c121914yu** [comment]
> 另外在safari上能进去，但是有很明显的卡顿
> 
> [视频](https://www.hostize.com/zh/edit/by12HHcZ09upknw0km4D2)

无法打开该视频，麻烦直接github 上传。

**Comment by bincooo** [comment]
https://github.com/user-attachments/assets/794fcb32-b92f-4417-9112-9306dca58102

**Comment by c121914yu** [comment]
> 
> https://github.com/user-attachments/assets/794fcb32-b92f-4417-9112-9306dca58102
> 

这是啥配置的电脑，是不是有啥特殊配置，之前有用户是那种win7 的老机器， 节点不是很多的话，还是很流畅的。😂

**Comment by c121914yu** [comment]
> 3.7 GHz 6-Core Intel Core i7 + AMD 580

感觉可能是gpu 不太行，但是因为有 GPU，浏览器还是选择了gpu 加速渲染。

**Comment by bincooo** [comment]
感觉是我驱动的问题，这电脑用好几年了。
笔记本上能用，就这样吧
