### ISSUE TITLE
升级到4.8.14之后cosyvioce无法使用了，ios的whisper问题解决了

### ISSUE THREAD

**Issue by William-715** [labring/FastGPT#3286]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图，配置文件等**
升级到4.8.14之后cosyvioce无法使用了    
**复现步骤**
每次都会浮现
**预期结果**
无法针对ai回复的文本进行语音播放。
**相关截图**
![image](https://github.com/user-attachments/assets/eed6f808-c8d9-4479-b81c-69dea1528ce3)

**Comment by heart18z** [comment]
文本转语音不是用的openAI的TTS，自己可以配置为阿里的cosyvioce吗

**Comment by William-715** [comment]
> 文本转语音不是用的openAI的TTS，自己可以配置为阿里的cosyvioce吗

可以的

**Comment by heart18z** [comment]
4.8.14如果切换为openAI的TTS，语言合成是否生效

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3303

**Comment by SDAIer** [comment]
> > 文本转语音不是用的openAI的TTS，自己可以配置为阿里的cosyvioce吗
> 
> 可以的


请教下fastgpt如何设置tts，不用浏览器默认的语音

**Comment by gengpeip** [comment]
> > > 文本转语音不是用的openAI的TTS，自己可以配置为阿里的cosyvioce吗
> > 
> > 
> > 可以的
> 
> 请教下fastgpt如何设置tts，不用浏览器默认的语音
请问您的问题解决了吗，fastgpt要怎么接入cosyvoice呢~
