### ISSUE TITLE
原始文件保存目录

### ISSUE THREAD

**Issue by peanutpaste** [labring/FastGPT#3287]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [4.8.14 ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图，配置文件等**
我想下载之前上传到fastgpt处理过的文件的对应的原始文件，但是我没找到在哪里目录下。
请问我应该到哪里找到这些对应的原始文件
![image](https://github.com/user-attachments/assets/43f97327-fa6e-4650-bbed-be330a946f63)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
mongodb 里，需要用脚本去下载。
