### ISSUE TITLE
版本升级后原先工作流中的Number变量在HTTP模块上引用不到

### ISSUE THREAD

**Issue by LuckLittleBoy** [labring/FastGPT#3297]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.14

**问题描述, 日志截图，配置文件等**
fastgpt版本从v4.8.12升级到v4.8.14后，原先工作流中的Number变量在HTTP模块上引用不到！

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/ff1cafc2-08fb-41ff-b2d9-5ab802476d65)

**Comment by LuckLittleBoy** [comment]
必须要把HTTP插件里Number变量删了重新创建才可以，创建新的HTTP插件都不行 : )

**Comment by c121914yu** [comment]
没看懂图片啥意思，不都有么

**Comment by LuckLittleBoy** [comment]
> 没看懂图片啥意思，不都有么

![image](https://github.com/user-attachments/assets/d76e80ee-f5ed-4b62-95fb-da178278c880)
![image](https://github.com/user-attachments/assets/a4771213-a483-4fc4-8c2b-1ccfa4dbd425)
点击出不来变量选择

**Comment by LuckLittleBoy** [comment]
> 没看懂图片啥意思，不都有么
控制台有报错
![image](https://github.com/user-attachments/assets/d5ea5fec-567a-4aa4-8078-abe1cbf3de4f)
