### ISSUE TITLE
向量库中使用emb向量模型索引 出现语义索引匹配值超过0-1区间 最多可达1万多

### ISSUE THREAD

**Issue by 2662007798** [labring/FastGPT#3298]
有没有人遇到过的？

**Comment by Huojunning** [comment]
我也遇到了
![Uploading 1733280855053.png…]()

**Comment by Huojunning** [comment]
![1733280855053](https://github.com/user-attachments/assets/f3ecc0ef-8b25-4011-8753-fa1a4316467a)
我也遇到了

**Comment by 2662007798** [comment]
更换阿里的模型 删掉数据重新导入




阿生
***@***.***

**Comment by c121914yu** [comment]
模型没归一化

**Comment by 2662007798** [comment]
> 模型没归一化

国内模型都试过了 都不行

**Comment by 2662007798** [comment]
修改 packages/service/core/ai/embedding/index.ts 文件，

在文档最后，增加如下函数：
// Define the normalize_embedding function
export function normalizeEmbedding(vector: number[]): number[] {
// Calculate L2 norm
const norm = Math.sqrt(vector.reduce((acc, value) => acc + (value * value), 0));

// Handle zero norm to avoid division by zero
if (norm === 0) {
return vector;
}

// Create a new array for the normalized vector
const normalizedVector = new Array(vector.length).fill(0);
for (let i = 0; i < vector.length; i++) {
normalizedVector[i] = vector[i] / norm;
}

return normalizedVector;
}

然后，将此文件中的 getVectorsByText函数中的 如下代码，
const [tokens, vectors] = await Promise.all([
countPromptTokens(input),
Promise.all(res.data.map((item) =>unityDimensional(item.embedding)))
]);

替换为
const [tokens, vectors] = await Promise.all([
countPromptTokens(input),
Promise.all(res.data.map((item) => {
// Apply normalization before returning
return normalizeEmbedding(unityDimensional(item.embedding));
})),
]);
即可。

上述修改的作用是：对于api返回的vectors进行归一化操作，如果api返回的结果已经是归一化过的，则内容不变。

**Comment by SDAIer** [comment]
这个除了实现数值方面的归一化以外，对模型实际向量检索的效果有变化吗

**Comment by lcl-101** [comment]
![image](https://github.com/user-attachments/assets/2c16269e-2f33-4fcd-be47-e1369bf68854)
你好，我按照你的方法修改了，分数动几千多变声100以内容，但还是没有归一

**Comment by SDAIer** [comment]
只是少了一个数量级&nbsp; 1000多变为100多&nbsp; ，100多变为10多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月21日(周六) 上午10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 向量库中使用emb向量模型索引 出现语义索引匹配值超过0-1区间 最多可达1万多(#已解决) (Issue #3298)




 
image.png (view on web)
 你好，我按照你的方法修改了，分数动几千多变声100以内容，但还是没有归一

**Comment by lcl-101** [comment]
![image](https://github.com/user-attachments/assets/df315bba-cc01-4820-9fb4-4b62c87cec55)
正确p配置到的结果在0到1之前，但是其他的结果还是比1大

**Comment by SDAIer** [comment]
你这只是个别现象，大部分只是缩小了量级，并没有归一



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月21日(周六) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/FastGPT] 向量库中使用emb向量模型索引 出现语义索引匹配值超过0-1区间 最多可达1万多(#已解决) (Issue #3298)




 
image.png (view on web)
 正确p配置到的结果在0到1之前，但是其他的结果还是比1大
