### ISSUE TITLE
点击保存之后,还是显示未保存

### ISSUE THREAD

**Issue by 2468262712** [labring/FastGPT#3305]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ X] 我已确认目前没有类似 issue
- [ X] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ X] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [X ] 我理解并愿意跟进此 issue，协助测试和提供反馈

- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X ] 私有部署版本, 具体版本号: 4.8.14-fix

**问题描述, 日志截图，配置文件等**

**复现步骤**
工作台中的简易应用,点击保存之后,还是显示未保存
**预期结果**
应该显示已保存
**相关截图**
![image](https://github.com/user-attachments/assets/450b8825-b1cc-4e88-a9f2-27d397965314)

**Comment by newfish-cmyk** [comment]
#3293 Fixed
