### ISSUE TITLE
代码运行识别不出全局变量

### ISSUE THREAD

**Issue by hope-dreaming** [labring/FastGPT#3308]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√ ] 我已确认目前没有类似 issue
- [ √] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ √] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ √] 私有部署版本, 具体版本号: 
4.8.14
**问题描述, 日志截图，配置文件等**
工作流中运行代码运行节点时函数接收不到全局变量的输入
**复现步骤**
![image](https://github.com/user-attachments/assets/190fa116-aeb5-4bcc-a3a7-e4135231cf42)
![image](https://github.com/user-attachments/assets/a2be6eaa-e045-4313-b061-6a3c17bb287c)

**相关截图**

**Comment by hope-dreaming** [comment]
只有全局变量的值不能被代码运行引用，流程开始的用户问题就可以被成功引用

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3315 只有 debug 模式会这样，这个 pr 修复
