### ISSUE TITLE
上传图片不能识别

### ISSUE THREAD

**Issue by pingyuan2016** [labring/FastGPT#3321]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: V4.8.14-fix

**问题描述, 日志截图，配置文件等**
使用的是PgVector版本，上传图片无法显示，后台地址显示Upload file success training_loss.png, cost 16ms

**复现步骤**
mkdir fastgpt
cd fastgpt
curl -O https://raw.githubusercontent.com/labring/FastGPT/main/projects/app/data/config.json
pgvector 版本(测试推荐，简单快捷)
curl -o docker-compose.yml https://raw.githubusercontent.com/labring/FastGPT/main/files/docker/docker-compose-pgvector.yml
docker-compose up -d

shi使用默认的gpt-4o配置文件，文本问答没有问题，上传图片识别不了
![image](https://github.com/user-attachments/assets/3ec7b848-f4fd-4fdb-b29c-01f04afd46d4)

![image](https://github.com/user-attachments/assets/7ae2b3a8-1fb9-4278-a0c4-b944408591dc)

**预期结果**
可以出现图片识别
![2b679cbf9aa37354ee2cc835cba9f99](https://github.com/user-attachments/assets/965daab0-80d1-4d47-aa8e-0295ff4f3f9e)

**相关截图**

**Comment by monk-after-90s** [comment]
同样

**Comment by aidfsoft** [comment]
重装就好了，切记fastpgt 模型config配置先不用改
