### ISSUE TITLE
chat:LLM_model_response_empty

### ISSUE THREAD

**Issue by zhizhuaa** [labring/FastGPT#3340]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.14

工作流中一步步调试是可以正确运行的，整体运行时就报 chat:LLM_model_response_empty
整体测试流程如下：
![image](https://github.com/user-attachments/assets/43c3355b-c205-436f-bd11-a7d4658d1f02)
一步步调试如下：
![image](https://github.com/user-attachments/assets/6c85bad4-b3e8-441f-b7f4-1b6916774063)
![image](https://github.com/user-attachments/assets/e423dc58-2378-4dad-b0ba-c01011237628)
![image](https://github.com/user-attachments/assets/46fc3061-36b4-4401-a9c7-fd3e5741f130)
整体测试运行如下：
![image](https://github.com/user-attachments/assets/a8eba6f0-8fb3-4c0c-ab27-aed40ffe3058)
请问你们发布的版本没有稳定的版本吗？体验感十分不好，简单的功能都不停的报错

**Comment by c121914yu** [comment]
看文档怎么调试
