### ISSUE TITLE
会话没结束

### ISSUE THREAD

**Issue by hellowJuly** [labring/FastGPT#3342]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图，配置文件等**
解决了长文本对话问题之后，上传进行分析，输出的内容不全就结束了
**复现步骤**

**预期结果**

**相关截图**
<img width="601" alt="image" src="https://github.com/user-attachments/assets/b890647c-bc32-4944-bae7-93691d77d8f9">

**Comment by c121914yu** [comment]
1. 换更大点模型
2. 准确设置 max_tokens
