### ISSUE TITLE
“代码运行”节点，使用.replace方法时，在节点调试时可以运行，但是流程调试会报错。

### ISSUE THREAD

**Issue by shikaiwei1** [labring/FastGPT#3343]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号:  V4.8.14 (SANDBOX使用v4.8.14)

**问题描述, 日志截图，配置文件等**
[流程简单测试.json](https://github.com/user-attachments/files/18052807/default.json)
流程文件导出如上。
“代码运行节点”节点，如果节点使用流程调试（页面右上角运行，或从“流程开始”点击“调试”），那么会报错：inputString.replace is not a function
![image](https://github.com/user-attachments/assets/a5872ae8-61cc-4b0a-868c-88114f8cf724)
如果仅仅在“代码运行”节点上点击“调试”，则可以正常运行
![image](https://github.com/user-attachments/assets/d389a3ec-54a9-45de-8cd0-e4cd7260d298)

**复现步骤**
1. 在fastgpt新建流程，并导入上述文件
2. 点击“运行”（或“流程开始”点击“调试”），输入一段文本，如“啊啊啊，aa,b,存储，d”
3. 运行，则能复现报错；
4. 在节点右上角点击“调试”，并输入与上次一样的文本。能正常输出结果。正确结果应当是：
```
{
  "strArray": [
    "啊啊啊",
    "aa",
    "b",
    "存储",
    "d"
  ]
}
```
**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
js 中 array 没有 replace 方法

**Comment by c121914yu** [comment]
如果仅仅在“代码运行”节点上点击“调试”，则可以正常运行： 因为强制给一个 array 数据赋值字符串。
