### ISSUE TITLE
4.8.15-alpha 问题反馈

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#3344]
## 1 原有流程编辑时提示未配置商业版
![image](https://github.com/user-attachments/assets/b87941f7-658b-4c1c-b5e0-bc5243b65d13)

## 工具箱为空
![image](https://github.com/user-attachments/assets/beb548e3-6898-4cd1-83bd-9e432c86a57d)

## 啥叫：自定义系统级文件解析服务Demo

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3339 这里有个 pr 已经修复
