### ISSUE TITLE
按照部署步骤操作,测试one api超时不通,是不是缺少其他文档?

### ISSUE THREAD

**Issue by bian1721** [labring/FastGPT#3348]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
:v4.8.14
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 
官网推荐  ghcr.io/labring/fastgpt:v4.8.14
**问题描述, 日志截图，配置文件等**
![image](https://github.com/user-attachments/assets/a743b287-a0b4-4227-a1d8-7b4dc93e3561)
请问大佬这是什么原因?

**Comment by bian1721** [comment]
其他的正常启动,但是点渠道测试不通

**Comment by c121914yu** [comment]
这是你服务器和这个模型地址网络不同
