### ISSUE TITLE
文本内容提供无法提取字段

### ISSUE THREAD

**Issue by su-god** [labring/FastGPT#3359]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.14-fix

**问题描述, 日志截图，配置文件等**
文本内容提供功能不能正常使用，模型使用qwen2:72b及gpt4o均无法提取想要的字段。

**复现步骤**
文本内容提供功能，输入想要提取的信息，但是提取的内容却是{}
**预期结果**
应该提取出想要的字段
**相关截图**
![image](https://github.com/user-attachments/assets/a0a22d85-d1b1-45ab-b180-4ab5a283d3de)
![image](https://github.com/user-attachments/assets/eaca3aca-eabc-4584-aa25-8450c99bad79)
![image](https://github.com/user-attachments/assets/7531f900-e2ad-4818-9338-8bbddbba4aff)

**Comment by SDAIer** [comment]
qwen-max提取下看看

**Comment by su-god** [comment]
> qwen-max提取下看看

![image](https://github.com/user-attachments/assets/db96a47e-0ec6-42b2-84f8-413fc36aacfe)
还是不行

**Comment by c121914yu** [comment]
错误的配置工具调用模式或者 oneapi 渠道没选 openai 类型。
 日志会提示：Your model may not support tool_call

**Comment by su-god** [comment]
> 错误的配置工具调用模式或者 oneapi 渠道没选 openai 类型。 日志会提示：Your model may not support tool_call

确实有这个报错，我要去审查什么配置呢
![image](https://github.com/user-attachments/assets/c8206ad3-df6f-472a-bb2e-17fe2c4f475e)

![image](https://github.com/user-attachments/assets/1c0c65d9-9930-49f3-bd84-712c7d58c876)

**Comment by c121914yu** [comment]
> > 错误的配置工具调用模式或者 oneapi 渠道没选 openai 类型。 日志会提示：Your model may not support tool_call
> 
> 确实有这个报错，我要去审查什么配置呢
> ![image](https://github.com/user-attachments/assets/c8206ad3-df6f-472a-bb2e-17fe2c4f475e)
> 
> ![image](https://github.com/user-attachments/assets/1c0c65d9-9930-49f3-bd84-712c7d58c876)
> 

千问这个渠道不支持tool 模式，要用openai 渠道。
