### ISSUE TITLE
relation "modeldata" does not exist

### ISSUE THREAD

**Issue by clcc2019** [labring/FastGPT#336]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ X] 私有部署版本

**问题描述**
私有化部署创建知识库报错
relation "modeldata" does not exist

**复现步骤**

**预期结果**

**相关截图**
<img width="1509" alt="image" src="https://github.com/labring/FastGPT/assets/46099295/515ebf75-1922-453a-8648-a6765c5bfc51">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.run/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [X] Private deployment version

**Problem Description**
Error when creating knowledge base during privatized deployment
relation "modeldata" does not exist

**Steps to reproduce**

**expected outcome**

**Related screenshots**
<img width="1509" alt="image" src="https://github.com/labring/FastGPT/assets/46099295/515ebf75-1922-453a-8648-a6765c5bfc51">

**Comment by RiverBird2000** [comment]
same bug，how to figure it out
