### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by clcc2019** [labring/FastGPT#337]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ X] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ X] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
<img width="1435" alt="image" src="https://github.com/labring/FastGPT/assets/46099295/d81b1014-60ac-40eb-8585-f525d5142ea9">
<img width="1511" alt="image" src="https://github.com/labring/FastGPT/assets/46099295/b769a247-f6d3-44e0-866a-73f5c4c792f4">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hello, I also encountered this problem, how did I solve it?
