### ISSUE TITLE
Cannot read properties of undefined (reading 'functionCall')

### ISSUE THREAD

**Issue by chenhaoqiang** [labring/FastGPT#338]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
创建了应用以及知识库，并使用高级编排进行编排，使用的是OneAPI转发的Azure OpenAI接口（GPT-35-turbo和GPT-35-turbo-16k API版本=2023-07-01-preview），聊天时报错：Cannot read properties of undefined (reading 'functionCall')  最后面有截图。

使用postman调用OneAPI接口，传入了functions参数，能正确返回函数调用命中结果。
![image](https://github.com/labring/FastGPT/assets/20062034/9247cad9-9fa4-4654-872b-484932e02ed8)

**复现步骤**
- 部署OneAPI，配置渠道和令牌
![image](https://github.com/labring/FastGPT/assets/20062034/5ac76409-88b1-4373-b1b6-0e2fb99bfc71)

- Docker-Compose部署FastGPT，创建config.json，修改docker-compose.yml，设置相关OneAPI参数以及config.json的volumes
- 打开FastGPT页面，登录后创建【问题分类+知识库】的应用
- 创建知识库，导入知识
- 在应用使用高级编排，配置知识库以及GPT-35-turbo模型
- 聊天窗口发送“你好”

**预期结果**
正确返回内容

**相关截图**
页面报错截图：
![image](https://github.com/labring/FastGPT/assets/20062034/5347b99f-90e6-415a-bd5e-e0fa5b85106f)

docker日志截图：
![image](https://github.com/labring/FastGPT/assets/20062034/e419af15-cf08-4332-aae8-920af9034ae7)

**Comment by chenhaoqiang** [comment]
fastgpt version: 4.4.4
![image](https://github.com/labring/FastGPT/assets/20062034/5cc6a7f2-468f-4a82-ba09-c45c582526d4)

**Comment by c121914yu** [comment]
需要调整下配置文件，或者升级到最新版。
4.4.4 后指定了 functioncall 模型，有个版本初始值没有赋上，4.4.5 已修复。

**Comment by chenhaoqiang** [comment]
> 需要调整下配置文件，或者升级到最新版。
> 
> 4.4.4 后指定了 functioncall 模型，有个版本初始值没有赋上，4.4.5 已修复。

感谢回复！我晚上刚把这个解决了，把配置文件从源码里拷贝了一份，重启了下docker-compose就好了，很神奇！源码我下了，本地跑也是没问题的。有空我研究下源码学习学习，希望这个项目越来越好！！！
