### ISSUE TITLE
语音播报是否会考虑支持自定义微软的接口

### ISSUE THREAD

**Issue by JeazW** [labring/FastGPT#340]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
配置微软接口后，语音播报支持微软的音色，再好点儿支持下拉选择播音员，再好点儿支持下载音频。微软接口免费额度很高，根本用不完。
**应用场景**
语音播报，文字转语音，语音产品
**相关示例**
https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/get-started-text-to-speech?tabs=windows%2Cterminal&pivots=programming-language-csharp

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
After configuring the Microsoft interface, the voice broadcast supports Microsoft's timbres, better yet supports drop-down selection of announcers, and better still supports downloading audio. The free quota of Microsoft interface is very high and cannot be used up at all.
**Application Scenario**
Voice broadcast, text-to-speech, voice products
**Related Examples**
https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/get-started-text-to-speech?tabs=windows%2Cterminal&pivots=programming-language-csharp@@=== =Whether voice broadcasting will consider supporting customized Microsoft interfaces

**Comment by c121914yu** [comment]
非开源的内容不太考虑直接接入。如果有合适的模型可以考虑。后面可能会考虑加一个 url，统一输入输出，有需要的可以自己部署一个接口去接入。
