### ISSUE TITLE
安卓app嵌入后使用语音输入提示Permission denied

### ISSUE THREAD

**Issue by LuckLittleBoy** [labring/FastGPT#3418]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.12

**问题描述, 日志截图，配置文件等**
通过免登录窗口创建链接，已使用域名https，浏览器和小程序使用语音输入没有问题，但是在自己开发的安卓app上通过webview嵌入后，语音输入提示Permission denied，有没有大神知道这个应该怎么整

![微信图片_20241217175657](https://github.com/user-attachments/assets/550fb200-3920-4daf-b046-15097447dc92)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
跨域问题
iframe 中的内容可能来自不同的域，而浏览器出于安全原因限制了跨域访问。这意味着，您无法直接从父页面访问或控制 iframe 中的内容，包括请求麦克风权限。

**Comment by SDAIer** [comment]
<iframe allow="microphone *; camera *;" v-if="showIframe" :src="iframeSrc" frameborder="0" style="width: 100%; height: 100%;"></iframe>

**Comment by LuckLittleBoy** [comment]
> <iframe allow="microphone *; camera *;" v-if="showIframe" :src="iframeSrc" frameborder="0" style="width: 100%; height: 100%;"></iframe>

我们是通过webview加载的，试了下将iframe放在一个html文件中加载，但是又出现了could not start audio source问题呢
![306c5090023e6355dab74c0bf87d41c](https://github.com/user-attachments/assets/a2a2283b-bb02-41bb-af38-93015313f63a)

**Comment by LuckLittleBoy** [comment]
解决了，谢谢大家的意见
