### ISSUE TITLE
新加入的模型openapi 测试404

### ISSUE THREAD

**Issue by to8toandy** [labring/FastGPT#3419]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.7

**问题描述, 日志截图，配置文件等**
docker 私有化部署；config.json新增大模型配置后，openapi测试报404，无任何报错信息
![image](https://github.com/user-attachments/assets/a61b10b2-f487-46bd-8542-7ef6d62697a8)
fastGpt应用报错：
![image](https://github.com/user-attachments/assets/12e19639-87c7-45fd-8244-01eb3f936da4)

![image](https://github.com/user-attachments/assets/e91b4032-bc63-4135-97a5-be48d9b2d168)

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
啥模型 这是你模型配置问题 要么oneapi没设置对 要么模型端有问题

**Comment by lijiajun1997** [comment]
你在oneapi里没ping通啊  要么请求的格式不兼容

**Comment by lijiajun1997** [comment]
自定义渠道是针对openai格式的

**Comment by to8toandy** [comment]
嗯是的，自定义渠道不行，更新了最新版本就有豆包渠道了；感谢🙏
