### ISSUE TITLE
分享链接的标题显示bug

### ISSUE THREAD

**Issue by ajiader** [labring/FastGPT#3428]
pc浏览器访问分享页面， 网页表示显示FASTGPT 刷新就变成分享的标题，   一会刷新标题就又变成FASTGPT
希望显示成分享的设置的标题 
![image](https://github.com/user-attachments/assets/b74d1353-d393-4126-8f7f-938e691d6396)

**Comment by c121914yu** [comment]
根据 issue 模板完成再提，这个问题已经修复过了，不知道你是啥版本。

**Comment by ajiader** [comment]
![image](https://github.com/user-attachments/assets/1917e382-0b1e-4881-8021-831127c5e94b)
docker镜像:registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:v4.8.15-fix2

**Comment by ajiader** [comment]
ctrl+f5  更容易复现

**Comment by kid20210528** [comment]
同样遇到，4.8.16版本
