### ISSUE TITLE
Can it support the Chatgpt key provided by Microsoft Azure?

### ISSUE THREAD

**Issue by hffei** [labring/FastGPT#343]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
类似chatgpt on wechat那个项目那样，支持openai的key，也支持微软Azure key
**应用场景**
这样部署的时候，服务器就不需要VPN连接openAi了。目前微软的Key是可以直接访问的
**相关示例**
https://github.com/zhayujie/chatgpt-on-wechat

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
Similar to the chatgpt on wechat project, it supports openai key and Microsoft Azure key.
**Application Scenario**
When deployed in this way, the server does not need a VPN to connect to openAi. Currently Microsoft Key can be accessed directly
**Related Examples**
https://github.com/zhayujie/chatgpt-on-wechat

**Comment by c121914yu** [comment]
文档里有说明。
oneapi支持任意key

**Comment by c121914yu** [comment]
https://doc.fastgpt.run/docs/installation/one-api/ 参考文档

**Comment by hffei** [comment]
谢谢，已经接入成功。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thank you, the connection has been successful.
