### ISSUE TITLE
IF插件增加分支插入功能或者跟随位置变化调整后续关联节点

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#3435]
目前的IF插件无法插入分支，只能在最后增加

但是拖动分支的前后位置时会导致与后续节点出现错误，只是关联了分支的位置，并没有随着分支的上下位置变更而跟随变化

请优化下

**Comment by c121914yu** [comment]
同时调整出线，会导致连线交叉，重新手动连一个线好了。
