### ISSUE TITLE
硅基流的视觉模型遇到图片内容都会报错

### ISSUE THREAD

**Issue by flyhunterl** [labring/FastGPT#3441]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: 4.8.15

**问题描述, 日志截图，配置文件等**
使用硅基流的视觉模型接受图片都会有一下报错信息 我尝试的模型：deepseek-ai/deepseek-vl2   Pro/Qwen/Qwen2-VL-7B-Instruct 其他来源的模型没有此类问题，同样的api地址在其他应用上发送图片没有问题
400 Provider API error: Image url should be a valid url or should like data:image/TYPE;base64,YOUR-BASE64-CONTENT (request id: 20241220101431275102011n91L8wIi)
**复现步骤**

**预期结果**

**相关截图**

**Comment by flyhunterl** [comment]
> 正常接入了 deepseek-ai/deepseek-vl2 没遇到这个问题，看看日志里请求体。 <img alt="image" width="1443" src="https://private-user-images.githubusercontent.com/50446880/397805588-4eeac488-fb9d-4015-bdb8-f71268b9d460.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDI3NTIsIm5iZiI6MTczNDc0MjQ1MiwicGF0aCI6Ii81MDQ0Njg4MC8zOTc4MDU1ODgtNGVlYWM0ODgtZmI5ZC00MDE1LWJkYjgtZjcxMjY4YjlkNDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAwNTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwOGVmZGU4OGU1YmU1NzFlMDZhMGY2ODU5YzFhOTA1YWZhNWYwOGEzZDNlZDgxZTdlNmM2YmUyZGU5NzE5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OyGDtJlIIQ2PFRNpXWpN67qqKRMkmYV0xVWbmrNKUGo">

好的，谢谢您回复，我再去检查下日志和config

**Comment by flyhunterl** [comment]
> 正常接入了 deepseek-ai/deepseek-vl2 没遇到这个问题，看看日志里请求体。 <img alt="image" width="1443" src="https://private-user-images.githubusercontent.com/50446880/397805588-4eeac488-fb9d-4015-bdb8-f71268b9d460.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDM5NzksIm5iZiI6MTczNDc0MzY3OSwicGF0aCI6Ii81MDQ0Njg4MC8zOTc4MDU1ODgtNGVlYWM0ODgtZmI5ZC00MDE1LWJkYjgtZjcxMjY4YjlkNDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAxMTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwN2QwM2YxNzQ4YTRiNGYxNTE2ZGE1MGUwNWQ4YzI4NDFmYmZjZTVlYmY2MWMzZDQzMjk0ZjJiYWJhZWZjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lU8JTTn-GQifeGmY4MkHIMLatooejfL1R-Uo1aELN5Y">

……我又去检查了下配置文件，发现compose文件的domin配置前面多了一个空格…………去掉后就正常了……奇了怪了  为什么其他场景其他模型没这个问题……所以我一开始没怀疑到配置文件…………

**Comment by c121914yu** [comment]
> > 正常接入了 deepseek-ai/deepseek-vl2 没遇到这个问题，看看日志里请求体。 <img alt="image" width="1443" src="https://private-user-images.githubusercontent.com/50446880/397805588-4eeac488-fb9d-4015-bdb8-f71268b9d460.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDM5NzksIm5iZiI6MTczNDc0MzY3OSwicGF0aCI6Ii81MDQ0Njg4MC8zOTc4MDU1ODgtNGVlYWM0ODgtZmI5ZC00MDE1LWJkYjgtZjcxMjY4YjlkNDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAxMTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwN2QwM2YxNzQ4YTRiNGYxNTE2ZGE1MGUwNWQ4YzI4NDFmYmZjZTVlYmY2MWMzZDQzMjk0ZjJiYWJhZWZjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lU8JTTn-GQifeGmY4MkHIMLatooejfL1R-Uo1aELN5Y">
> 
> ……我又去检查了下配置文件，发现compose文件的domin配置前面多了一个空格…………去掉后就正常了……奇了怪了  为什么其他场景其他模型没这个问题……所以我一开始没怀疑到配置文件…………

只有传文件用到这个变量
