### ISSUE TITLE
Hope to be able to intervene in user issues

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#345]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
希望可以在用户的问题进行二次干预，比如用户输入“你好” , 可以干预成 “你好 (使用中文回复)”，所以可否在用户问题这栏添加文本输入框和变量？

<img width="794" alt="截屏2023-09-24 19 32 11" src="https://github.com/labring/FastGPT/assets/36452456/f0be0320-24ad-424a-939d-3fbde6854db9">

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
I hope that secondary intervention can be carried out in the user's question. For example, if the user inputs "Hello", it can be intervened into "Hello (reply in Chinese)", so can I add a text input box and variables to the user's question column?
<img width="883" alt="Screenshot 2023-09-24 19 25 30" src="https://github.com/labring/FastGPT/assets/36452456/902add5e-99ea-421d-865e-e018e608358c">

**Application Scenario**

**Related Examples**

**Comment by bincooo** [comment]
额。我补充一下哈，在没有命中知识库的时候，无法干预

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Forehead. Let me add that it is impossible to intervene when the knowledge base is not hit.

**Comment by c121914yu** [comment]
http模块不就行么

**Comment by bincooo** [comment]
> http模块不就行么

额，为了在末尾加点约束提示词，专门做个http请求服务，不太妥吧

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Isn’t the http module just fine?

Well, in order to add some constraint prompt words at the end, it is not appropriate to make a special http request service.

**Comment by c121914yu** [comment]
> > http模块不就行么
> 
> 额，为了在末尾加点约束提示词，专门做个http请求服务，不太妥吧。而且对非开发者来说不太有好

用laf云函数就好了，简单方便。
你是末尾加，他是开头加，待会有个中间加，可视化会变得很复杂。

**Comment by bincooo** [comment]
哦，好吧。我去看一下laf

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Oh fine. I'll go check it out laf
