### ISSUE TITLE
知识库同步自网页，建议可以添加自己的爬虫pai，自己爬。开源版

### ISSUE THREAD

**Issue by better319** [labring/FastGPT#3455]
知识库同步自网页，建议可以添加自己的爬虫pai，自己爬。开源版
建议类似dify，开发知识库爬虫部分需求。
![image](https://github.com/user-attachments/assets/56e1b7ad-1d5a-4fee-8356-9f6040abd69f)
可以参考  Firecrawl或者Jina Reader

https://www.firecrawl.dev/account
https://jina.ai/reader/

**Comment by c121914yu** [comment]
目前已支持 api 知识库，可以对接自己的爬虫文档库。

**Comment by better319** [comment]
> 目前已支持 api 知识库，可以对接自己的爬虫文档库。其余类型知识库暂未计划开放。

方便给个具体的api知识库的例子吗？或者说推荐个网址或服务。
