### ISSUE TITLE
知识库文档删除报错

### ISSUE THREAD

**Issue by 503612012** [labring/FastGPT#3460]
##### 知识库文档删除报错
> 这里应该是`datasetId`而非`datasetIds`吧？
> 删除dataset.datas的数据量小的时候，没有问题，数据量大的时候，就会报错，不明白是怎么回事。

![001](https://github.com/user-attachments/assets/e6f72458-7e8f-47c3-bff8-ce85b6593eb4)

**Comment by 503612012** [comment]
执行到这一行的时候，总是报`WriteConflict error: this operation conflicted wit…try your operation or multi-document transaction.`错误，而且是如果数据量小的话，不报错，数据量大的话(删除18810条数据)，就会报错。

**Comment by 503612012** [comment]
这是调用api/core/dataset/collection/delete接口的时候返回的异常信息：
![image](https://github.com/user-attachments/assets/2ceaa36d-0260-425f-bf3b-941d8469d588)

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3453/commits/cfafc4be45cdda438cd47c911b09238cdc29740a 这个 commit 有了点优化，取消删除知识库时候，关联删除 data 时候的事务(根据官方说明，超过 1000 条数据删除时候，最好不要用事务），所以删除 data 时候，不加入事务的选项了。会在 4.8.17 版本优化，可以升级 4.8.17-alpha 测试
