### ISSUE TITLE
希望支持Minio等S3协议文件库

### ISSUE THREAD

**Issue by xieyos** [labring/FastGPT#3463]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
API文件库功能非常棒，但是现有文件系统一般为S3协议的分布式存储系统，希望能支持S3协议

**应用场景**
API文件库

**相关示例**
直接填写S3存储桶相关参数，自行遍历所有存储桶中所有对象

**Comment by c121914yu** [comment]
s3 也不太统一，可以自己写个 serverless 来兼容，不做封装了。

**Comment by c121914yu** [comment]
s3 也不太统一，可以自己写个 serverless 来兼容，不做封装了。
😂或者看看有没有社区大佬提下，已经做的挺标准的拓展了
