### ISSUE TITLE
About the problem that the use of the "Problem Classification" module may fail and report errors

### ISSUE THREAD

**Issue by MartialBE** [labring/FastGPT#347]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
使用 `问题分类` 时，客户输入的消息可能并不是一个问题（比如：你好、哈哈哈 这些语句）或者分类不够完善时，导致GPT将不会调用函数，从而报错`SyntaxError: Unexpected end of JSON input`。
**复现步骤**
比如设置一个`问题分类` 如下：
<img width="293" alt="iShot_2023-09-25_11 53 09" src="https://github.com/labring/FastGPT/assets/42402987/39430701-9076-48f1-a00f-a5c38d9bffbf">

用户输入 `-。-`， 这种无意义文字或者其他（很容易触发这个问题），可以看到下面日志中的 打印的 `response.data.choices?.[0]?.message?.function_call?.arguments` 为`undefined`。
<img width="1057" alt="iShot_2023-09-25_11 55 32" src="https://github.com/labring/FastGPT/assets/42402987/0bc1b79e-877a-4df1-b1bb-8b162b444abd">

**预期结果**
这个报错是不应该产生的。
应该对这个报错进行处理，以下是我的一些方法：
1. `问题分类` 模块增加一个 `默认输出`， 如果判读GPT没有使用函数调用则走`默认输出`的流程
2. 如果不增加`默认输出`这个类型的话， 需要增加一个 `system prompt`，指定它必须调用函数，例如：`你是一个函数调用机器人，你接下来必须调用agent_user_question函数，禁止直接回复。`

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
When using `problem classification`, the message entered by the customer may not be a question (for example: hello, hahaha, etc.) or the classification is not complete enough, causing GPT to not call the function, thus reporting the error `SyntaxError: Unexpected end of JSON input`.
**Steps to reproduce**
For example, set a `problem classification` as follows:
<img width="293" alt="iShot_2023-09-25_11 53 09" src="https://github.com/labring/FastGPT/assets/42402987/39430701-9076-48f1-a00f-a5c38d9bffbf">

User input `-. -`, this kind of meaningless text or other (which can easily trigger this problem), you can see that the `response.data.choices?.[0]?.message?.function_call?.arguments` printed in the log below is` undefined`.
<img width="1057" alt="iShot_2023-09-25_11 55 32" src="https://github.com/labring/FastGPT/assets/42402987/0bc1b79e-877a-4df1-b1bb-8b162b444abd">

**expected outcome**
This error should not occur.
This error should be handled. Here are some of my methods:
1. The `Problem Classification` module adds a `Default Output`. If no function call is used to interpret GPT, the process of `Default Output` will be followed.
2. If you do not add the `default output` type, you need to add a `system prompt`, specifying that it must call a function, for example: `You are a function-calling robot, you must call the agent_user_question function next, and direct replies are prohibited. `

**Related screenshots**

**Comment by c121914yu** [comment]
我尝试了几个无意义的内容，发现 functioncall 指定函数时是一定会生成对象的，我不确定你用了什么模型。

**Comment by c121914yu** [comment]
我会增加一个错误检测，默认走最后一个。

**Comment by MartialBE** [comment]
> 我尝试了几个无意义的内容，发现 functioncall 指定函数时是一定会生成对象的，我不确定你用了什么模型。

我是用的是gpt-3.5-0613 模型。
我这边使用复现概率超高，基本处于不能用的状态。😂😂

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> I tried a few meaningless things and found that functioncall will definitely generate an object when specifying a function. I'm not sure what model you used.

I am using the gpt-3.5-0613 model.
The probability of recurrence is extremely high in my case, and it is basically in a state of being unusable. 😂😂

**Comment by c121914yu** [comment]
新版已解决，默认走最后一个。
