### ISSUE TITLE
豆包模型在工具调用里用不了

### ISSUE THREAD

**Issue by linqinguang** [labring/FastGPT#3489]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.15

**问题描述, 日志截图，配置文件等**
豆包模型具备Tool Call能力，但是在工具调用里却用不了Tool Call。通过curl看了下豆包模型和其他正常的模型的区别是豆包在触发tool_calls时，messages.content中会有选择工具的原因，而其他模型的content都是空字符串。例如
```Json
{
    "index": 0,
    "message": {
        "role": "assistant",
        "content": "当前提供了1个工具，分别是[\"b9NctXLecxTp\"]，需求为查天气，需要先查询当前时间的天齐，此处应调用b9NctXLecxTp。",
        "tool_calls": [
            {
                "index": 0,
                "id": "b9NctXLecxTp:0",
                "type": "function",
                "function": {
                    "name": "b9NctXLecxTp",
                    "arguments": "{\n  \"now_time\": \"2024-02-29 23:59:59 Wednesday\"\n}"
                }
            }
        ]
    },
    "finish_reason": "tool_calls"
}
```

而在代码packages\service\core\workflow\dispatch\agent\runTool\toolChoice.ts的572行，if判断中的条件是responseChoice?.content，而非responseChoice?.tool_calls或part.choices?.[0]?.finish_reason==="tool_calls"，导致豆包返回tool_calls但工具按照正常assistant回复处理。

虽然原因找到了，但是写不来ts，只好厚颜无耻当个伸手党了

**Comment by c121914yu** [comment]
好的，我们去试试。

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/3493 已处理，把 else if 去掉，改成并列 if 即可。
不过实测，豆包工具调用不是很好用。
