### ISSUE TITLE
data for page 。。。 exceeds the threshold

### ISSUE THREAD

**Issue by SDAIer** [labring/FastGPT#3490]
4.8.16

Warning: **data for page "/dataset/detail"** (path "/dataset/detail?datasetId=6770058fa7ceasd52f12&collectionId=67700217ceae0b7122f35&currentTab=dataCard") is 175 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data

Warning: **data for page "/" is 150 kB** which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data

**Comment by c121914yu** [comment]
翻译文件较大，后续优化，没啥影响

**Comment by tunglinwood** [comment]
> 翻译文件较大，后续优化，没啥影响

请问这个跟翻译有啥关系？这个不就是文件上传有个上限在吗？
