### ISSUE TITLE
Connect to the openapi interface exposed by text-generation-webui. When updating the openAI account, the interface reports an error 500.

### ISSUE THREAD

**Issue by bryant-rh** [labring/FastGPT#350]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
docker 部署 
registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest

- [ ] 公有云版本
- [ ] 私有部署版本
docker 部署 
registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest

**问题描述**
1.text-generation-webui 对接了chinese-alpaca-2-7b-hf 模型，并测试正常
![image](https://github.com/labring/FastGPT/assets/43403977/6689b283-b1aa-4c20-b21d-b0b8925a6ff5)

2. 通过text-generation-webui  暴露OpenaAPi 接口，接入fastgpt
![image](https://github.com/labring/FastGPT/assets/43403977/f9588751-24cc-4fea-b7a3-237ce7848889)

3. fastgpt 接口报错500
![image](https://github.com/labring/FastGPT/assets/43403977/2ed66fba-d825-4671-a49b-901ffc3afe5f)

日志报错如下：
<img width="1397" alt="image" src="https://github.com/labring/FastGPT/assets/43403977/6ad0a4b3-22bd-4b42-924b-d7a49ef30260">

4. 查看text-generation-webui 返回接口正常
<img width="905" alt="image" src="https://github.com/labring/FastGPT/assets/43403977/0db4df36-715f-4ee9-b4e1-d10cb1b5ef38">

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
截图里 content 是为空字符串。应该与这个有关。程序里用了隐式转换，空字符不会通过校验。

**Comment by bryant-rh** [comment]
> 截图里 content 是为空字符串。应该与这个有关。程序里用了隐式转换，空字符不会通过校验。

但是我用curl 测试，返回正常
<img width="1385" alt="image" src="https://github.com/labring/FastGPT/assets/43403977/34eb7ffa-2f1a-4993-8de1-0f2ec21c6412">

**Comment by c121914yu** [comment]
> > 截图里 content 是为空字符串。应该与这个有关。程序里用了隐式转换，空字符不会通过校验。
> 
> 但是我用curl 测试，返回正常 <img alt="image" width="1385" src="https://user-images.githubusercontent.com/43403977/270523233-34eb7ffa-2f1a-4993-8de1-0f2ec21c6412.png">

参数没一样。maxTokens=1

**Comment by c121914yu** [comment]
新版改成undefined判断，空字符串也可以通过。
