### ISSUE TITLE
Import data>Direct segmentation>Link reading, when the paragraph length is 1000 or above, the data set has no data

### ISSUE THREAD

**Issue by leekoko** [labring/FastGPT#353]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
导入数据>直接分段>链接读取，段落长度1000及以上时，数据集没有数据;
当我使用默认的500长度，导入的数据在数据集中会显示。
日志无明显报错。

**复现步骤**
导入数据>直接分段>链接读取，段落长度填写1000及以上，导入之后不会出现数据集

**预期结果**
导入之后要有数据集

**相关截图**
<img width="1217" alt="image" src="https://github.com/labring/FastGPT/assets/23375386/b2fe3231-b125-4212-bea2-bae55ae99955">
<img width="977" alt="image" src="https://github.com/labring/FastGPT/assets/23375386/13a7dcfc-cad4-4e52-bb55-cd0af56cf1b1">
<img width="1332" alt="image" src="https://github.com/labring/FastGPT/assets/23375386/040a9df7-127c-46b9-a0e5-5f7fc14699a6">
<img width="616" alt="image" src="https://github.com/labring/FastGPT/assets/23375386/ee76fb82-f5f8-4ce0-b68a-04a85366a401">
<img width="1342" alt="image" src="https://github.com/labring/FastGPT/assets/23375386/af69f542-01e5-4e76-94f6-918777a8c030">

**Comment by leekoko** [comment]
虽然导入在数据集中没有显示，但是“搜索测试”是成功的；可是引用到应用上就无法实现搜索

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Although the import is not displayed in the data set, the "search test" is successful; however, the search cannot be implemented when it is referenced in the application.

**Comment by c121914yu** [comment]
4.4.5已修复。重新预览 fileId 不为空导致。
