### ISSUE TITLE
Advanced orchestration-module to simplify the development process

### ISSUE THREAD

**Issue by atmgla** [labring/FastGPT#356]
话说fastgpt的高级编排可玩性很强，但现在编排的模块还是比较局限，如果能将模块的代码插件化，然后给个新增模块的教程引导更多的社区开发者来共同开发就好了。

比如zhayujie/chatgpt-on-wechat项目就是将插件开发流程公布，然后吸引了许多人来开发新的插件功能。

我也想新增一些模块，比如：
1. 【支持编排赋值的变量模块】，现在限定词被废，所以有时候通过http模块返回的数据，无法引导AI对话模块去解析数据来回复用户。有了这个模块的话，就可以将http模块的返回结果赋值给变量模块，然后在AI对话的系统提示词引用变量来引导AI
2. 【判断模块】，同样的也是对http模块返回的数据进行判断，或者对变量模块的数据进行判断，从而走不一样的分支，重点是还不用耗费token
3. ...

fastgpt的可能性很高，如果有更多的社区开发者加入，应该能有很多有创意的玩法

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It is said that fastgpt's advanced orchestration is very playable, but the current orchestration modules are still relatively limited. It would be great if the module code could be plug-inized, and then a tutorial on adding new modules could be provided to guide more community developers to jointly develop it. .

For example, the zhayujie/chatgpt-on-wechat project published the plug-in development process and attracted many people to develop new plug-in functions.

I also want to add some new modules, such as:
1. [Variable module that supports arrangement assignment], now the qualifier is abolished, so sometimes the data returned through the http module cannot guide the AI ​​dialogue module to parse the data to reply to the user. With this module, you can assign the return result of the http module to the variable module, and then quote the variable in the system prompt of the AI ​​dialogue to guide the AI.
2. [Judgment Module], it also judges the data returned by the http module, or the data of the variable module, so as to take different branches. The key point is that there is no need to waste tokens.
3. ...

The possibility of fastgpt is very high. If more community developers join, there should be many creative ways to play

**Comment by c121914yu** [comment]
等待二次封装功能上线。

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.6.5-alpha
或许这个会满足你的需求
