### ISSUE TITLE
Add possible problem display

### ISSUE THREAD

**Issue by aleimu** [labring/FastGPT#360]
[//]: # '方框内填 x 表示打钩'

- [✔️] 我已确认目前没有类似 features
- [✔️] 我已确认我已升级到最新版本
- [✔️] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [✔️] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
知识库问答里加一个模块用来展示查询到的问答对,在大模型回答完后再在下方展示一下向量匹配得到的top3的问题部分,如果点击这些可能的问题,就会直接展示问题对应的答案部分,这样的话,避免再查询大模型,也降低了幻觉
**应用场景**

**相关示例**
https://[medisearch.io](https://medisearch.io/zh)/zh

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[//]: # 'Fill x in the box to indicate tick'

- [✔️] I have confirmed that there are currently no similar features
- [✔️] I have confirmed that I have upgraded to the latest version
- [✔️] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [✔️] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
A module is added to the knowledge base question and answer to display the queried question and answer pairs. After the large model has finished answering, the top 3 question parts obtained by vector matching are displayed below. If you click on these possible questions, the answers corresponding to the questions will be directly displayed. Partially, in this case, it avoids querying large models and reduces hallucinations.
**Application Scenario**

**Related Examples**
https://[medisearch.io](https://medisearch.io/zh)/zh

**Comment by c121914yu** [comment]
Good Feature

**Comment by c121914yu** [comment]
我们在定制客服编排流程时实现了这个功能，大致思路是维护一个问答知识库与一个文档知识库，每次对话时先对问答知识库进行检索，去0.93相关性以上的内容进行输出。所以这并不需要新增任何功能块实现，目前就可以。 你可能只需要一个HTTP模块对搜索到的数据进行处理。

**Comment by c121914yu** [comment]
未来有机会这个功能会做成插件引入，而不是新的模块或改造知识库搜索模块。
