### ISSUE TITLE
Can fastgpt determine the user's intention and call the corresponding data source?

### ISSUE THREAD

**Issue by keehub** [labring/FastGPT#362]
比如智能音箱，问他天气由气象服务提供数据，要他控制电器有家电程序提供服务

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
For example, if you ask a smart speaker about the weather, the weather service will provide data, and if you want it to control electrical appliances, a home appliance program will provide services.

**Comment by c121914yu** [comment]
可以参考实验室预约例子，提取对应的action
