### ISSUE TITLE
[Update Doc] Pls Update Doc on connecting local deployed LLM port to docker container

### ISSUE THREAD

**Issue by yhyu13** [labring/FastGPT#363]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

I found it lack of tutorial on working with locally deployed LLMs with FastGPT. 

But since I succeeded, I will share my experience. It would be great if you can add this to read me

Let me describe my setup:

1, A remote Ubuntu server is running an openai like api (made by textgen-webui with openai extension) which listens on server port 5051, this port is then forwarded to my local windows machine. So I think post to 127.0.0.1:5051.

2, On my local windows machine, I run the docker engine with wsl2 backend. I then started the docker containers as described here https://doc.fastgpt.run/docs/installation/docker/

Only with a little change to the base url

```
- OPENAI_BASE_URL=http://host.docker.internal:5051/v1
```

The `host.docker.internal` magic host address is made by docker for containers to get access to host machine, you don't need to expose or do any port mapping, no need to config windows LAN firewall setting. it just works.  Reference to answers here on this trick https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container

**应用场景**

Local/Remote deployed LLM available on host port, docker container using host port

**相关示例**

**Comment by c121914yu** [comment]
Thank you for your suggestion, fastgpt can access local model, by oneapi reference: https://doc.fastgpt.run/docs/custom-models/chatglm2/.

However, it should be noted that other docker containers need to form a network with the original Docker-Compose, or use the container ip as you say.
