### ISSUE TITLE
winston-mongodb: error initialising logger MongoError: Authentication failed.

### ISSUE THREAD

**Issue by wwwzhouhui** [labring/FastGPT#367]
version: '3.3'

services:

  pg:
    image: ankane/pgvector:v0.4.2 
    container_name: pg
    restart: always 
    ports:  
      - 5432:5432
    networks:
      - fastgpt
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=abc@123
      - POSTGRES_DB=postgres
    volumes:
      - D:\code\pgvector\pg\data:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0.18
    container_name: mongo 
    restart: always
    ports:   
      - 27017:27017
    networks:
      - fastgpt
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=abc@123
    volumes:
      - D:\code\mongo\data:/data/db

  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      - DEFAULT_ROOT_PSW=1234
      - OPENAI_BASE_URL=https://api.chatanywhere.com.cn
      - CHAT_API_KEY=
      - DB_MAX_LINK=5  
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      - MONGODB_URI=mongodb://username:password@mongo:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      - PG_URL=postgresql://username:password@pg:5432/postgres
    volumes:
      - D:\code\mongo\fastgpt\config.json:/app/data/config.json

networks:
  fastgpt:

fastgpt 登录的时候和mongo建立数据库连接有权限问题，感觉docker-compose.yml mongo 配置有问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
version: '3.3'

services:

  pg:
    image: ankane/pgvector:v0.4.2 
    container_name: pg
    restart: always 
    ports:  
      - 5432:5432
    networks:
      - fastgpt
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=abc@123
      - POSTGRES_DB=postgres
    volumes:
      - D:\code\pgvector\pg\data:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0.18
    container_name: mongo 
    restart: always
    ports:   
      - 27017:27017
    networks:
      - fastgpt
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=abc@123
    volumes:
      - D:\code\mongo\data:/data/db

  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      - DEFAULT_ROOT_PSW=1234
      - OPENAI_BASE_URL=https://api.chatanywhere.com.cn
      - CHAT_API_KEY=
      - DB_MAX_LINK=5  
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      - MONGODB_URI=mongodb://username:password@mongo:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      - PG_URL=postgresql://username:password@pg:5432/postgres
    volumes:
      - D:\code\mongo\fastgpt\config.json:/app/data/config.json

networks:
  fastgpt:


fastgpt 登录的时候和mongo建立数据库连接有权限问题，感觉docker-compose.yml mongo 配置有问题

**Comment by c121914yu** [comment]
1. 你改了数据库默认账号和密码，但是不改连接参数里的账号密码
2. 不推荐账号密码有特殊符号，容易出错

**Comment by wwwzhouhui** [comment]
是密码的问题  @ 的问题
