### ISSUE TITLE
Upload csv file prompts error.

### ISSUE THREAD

**Issue by WangJing1900** [labring/FastGPT#379]
<html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx</center> </body> </html>      
文件是1万多条新闻文章，是不是文件太大的原因？

**Comment by c121914yu** [comment]
超出网关限制大小

**Comment by erickech** [comment]
请问如何解决？
