### ISSUE TITLE
Supports more open source offline private LLM models and embedding models, and provides docker images

### ISSUE THREAD

**Issue by yinggoga** [labring/FastGPT#387]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
支持更多开源离线私有LLM模型和embedding模型，并提供docker镜像
类似https://github.com/chatchat-space/Langchain-Chatchat

**应用场景**

**相关示例**
https://github.com/chatchat-space/Langchain-Chatchat

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
Supports more open source offline private LLM models and embedding models, and provides docker images
Similar to https://github.com/chatchat-space/Langchain-Chatchat

**Application Scenario**

**Related Examples**
https://github.com/chatchat-space/Langchain-Chatchat

**Comment by c121914yu** [comment]
这个应该给oneapi提issue，FastGPT 不单独做模型集成
