### ISSUE TITLE
Docker image postgres data permission problem under windows

### ISSUE THREAD

**Issue by ycgkwyc** [labring/FastGPT#389]
**例行检查**
Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... 2023-10-11T05:27:00.751155400Z The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
2023-10-11 05:26:40.022 UTC [83] FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions
2023-10-11 05:26:40.022 UTC [83] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
2023-10-11 05:26:47.448 UTC [84] FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions
2023-10-11 05:26:47.448 UTC [84] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
2023-10-11 05:27:01.298 UTC [84] FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions
2023-10-11 05:27:01.298 UTC [84] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by ycgkwyc** [comment]
# 非 host 版本, 不使用本机代理
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.4.2 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5444:5444
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - PODATA=/home
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    command: sh -c "chmod 0750 /var/lib/postgresql/data && exec docker-entrypoint.sh postgres"
  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports: # 生产环境建议不要暴露
      - 27017:27017
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      # root 密码，用户名为: root
      - DEFAULT_ROOT_PSW=1234
      # 中转地址，如果是用官方号，不需要管
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-xxx
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      # mongo 配置，不需要改. 如果连不上，可能需要去掉 ?authSource=admin
      - MONGODB_URI=mongodb://username:password@mongo:27017/fastgpt?authSource=admin
      # pg配置. 不需要改
      - PG_URL=postgresql://username:password@pg:5444/postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fastgpt:
# host 版本, 不推荐。
# version: '3.3'
# services:
#   pg:
#   image: ankane/pgvector:v0.4.2 # dockerhub
#   # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # 阿里云
#   container_name: pg
#   restart: always
#   ports: # 生产环境建议不要暴露
#       - 5444:5444
#   environment:
#       # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
#       - POSTGRES_USER=username
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=postgres
#   volumes:
#       - ./pg/data:/var/lib/postgresql/data
#   mongo:
#   image: mongo:5.0.18
#   # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
#   container_name: mongo
#   restart: always
#   ports: # 生产环境建议不要暴露
#       - 27017:27017
#   environment:
#       # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
#       - MONGO_INITDB_ROOT_USERNAME=username
#       - MONGO_INITDB_ROOT_PASSWORD=password
#   volumes:
#       - ./mongo/data:/data/db
#       - ./mongo/logs:/var/log/mongodb
#   fastgpt:
#   # image: ghcr.io/labring/fastgpt:latest # github
#   image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
#   network_mode: host
#   restart: always
#   container_name: fastgpt
#   environment:
#       # root 密码，用户名为: root
#       - DEFAULT_ROOT_PSW=1234
#       # 中转地址，如果是用官方号，不需要管
#       - OPENAI_BASE_URL=https://api.openai.com/v1
#       - CHAT_API_KEY=sk-xxxx
#       - DB_MAX_LINK=5 # database max link
#       # token加密凭证（随便填，作为登录凭证）
#       - TOKEN_KEY=any
#       # root key, 最高权限，可以内部接口互相调用
#       - ROOT_KEY=root_key
#       # mongo 配置，不需要改
#       - MONGODB_URI=mongodb://username:password@0.0.0.0:27017/fastgpt?authSource=admin
#       # pg配置. 不需要改
#       - PG_URL=postgresql://username:password@0.0.0.0:5444/postgres

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
# Non-host version, does not use native proxy
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.4.2 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # Alibaba Cloud
    container_name:pg
    restart: always
    ports: # It is recommended not to expose in production environment
      - 5444:5444
    networks:
      -fastgpt
    environment:
      # The configuration here only takes effect on the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      -PODATA=/home
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    command: sh -c "chmod 0750 /var/lib/postgresql/data && exec docker-entrypoint.sh postgres"
  mongo:
    image:mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # Alibaba Cloud
    container_name: mongo
    restart: always
    ports: # It is recommended not to expose in production environment
      - 27017:27017
    networks:
      -fastgpt
    environment:
      # The configuration here only takes effect on the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # Alibaba Cloud
    ports:
      - 3000:3000
    networks:
      -fastgpt
    depends_on:
      -mongo
      - pg
    restart: always
    environment:
      # root password, user name: root
      - DEFAULT_ROOT_PSW=1234
      # Transit address, if you use an official account, you don’t need to worry about it.
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-xxx
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      # Mongo configuration, no need to change. If you can't connect, you may need to remove ?authSource=admin
      - MONGODB_URI=mongodb://username:password@mongo:27017/fastgpt?authSource=admin
      # pg configuration. No need to change
      - PG_URL=postgresql://username:password@pg:5444/postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fastgpt:
# host version, not recommended.
# version: '3.3'
# services:
#pg:
# image: ankane/pgvector:v0.4.2 # dockerhub
# # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # Alibaba Cloud
# container_name: pg
# restart: always
# ports: # It is recommended not to expose the production environment
# - 5444:5444
# environment:
# # The configuration here only takes effect for the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
# - POSTGRES_USER=username
# - POSTGRES_PASSWORD=password
# - POSTGRES_DB=postgres
# volumes:
# - ./pg/data:/var/lib/postgresql/data
#mongo:
# image: mongo:5.0.18
# # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # Alibaba Cloud
# container_name: mongo
# restart: always
# ports: # It is recommended not to expose the production environment
# - 27017:27017
# environment:
# # The configuration here only takes effect for the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
# - MONGO_INITDB_ROOT_USERNAME=username
# - MONGO_INITDB_ROOT_PASSWORD=password
# volumes:
# - ./mongo/data:/data/db
# - ./mongo/logs:/var/log/mongodb
#fastgpt:
# # image: ghcr.io/labring/fastgpt:latest # github
# image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # Alibaba Cloud
# network_mode: host
# restart: always
# container_name: fastgpt
# environment:
# # root password, user name: root
# - DEFAULT_ROOT_PSW=1234
# # Transit address, if you use an official account, you don’t need to worry about it.
# - OPENAI_BASE_URL=https://api.openai.com/v1
# - CHAT_API_KEY=sk-xxxx
# - DB_MAX_LINK=5 # database max link
# # Token encryption credentials (fill in whatever you want, as login credentials)
# - TOKEN_KEY=any
# # root key, the highest authority, can call each other through internal interfaces
# - ROOT_KEY=root_key
# # mongo configuration, no need to change
# - MONGODB_URI=mongodb://username:password@0.0.0.0:27017/fastgpt?authSource=admin
# # pg configuration. No need to change
# - PG_URL=postgresql://username:password@0.0.0.0:5444/postgres

**Comment by ycgkwyc** [comment]
fixit 不能放在同一个 data目录下
修改：
volumes:
      - ./pg/data:/var/lib/postgresql/pgdata

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
fixit cannot be placed in the same data directory
Revise:
volumes:
      - ./pg/data:/var/lib/postgresql/pgdata

**Comment by yhyu13** [comment]
第一次启动确实需要删一下pg data这个目录，然后我本地就好了

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
When you start it for the first time, you really need to delete the pg data directory, and then I can do it locally.

**Comment by ihacker2018** [comment]
> 第一次启动确实需要删一下pg data这个目录，然后我本地就好了

为啥我删除了也不行

**Comment by ihacker2018** [comment]
> fixit 不能放在同一个 data目录下 修改： volumes: - ./pg/data:/var/lib/postgresql/pgdata

你是怎么处理的，我把data改了个名也不行
