### ISSUE TITLE
The chat API cannot be called through the API-Key in the application

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#396]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**
curl --location --request POST 'http://192.168.56.107:6019/api/chat/completions' \
--header 'Authorization: Bearer fastgpt-DcamPUEXl1joShWWtoKFKPa6' \
--header 'Content-Type: application/json' \
--data-raw '{
    "chatId":"111",
    "stream":false,
    "detail": false,
    "variables": {
        "cTime": "2022/2/2 22:22"
    },
    "messages": [
        {
            "content": "导演是谁",
            "role": "user"
        }
    ]
}'

![image](https://github.com/labring/FastGPT/assets/5433705/983a068b-5192-463d-8b0a-73d1b9a439b5)
![image](https://github.com/labring/FastGPT/assets/5433705/af395635-d47a-4468-9cca-afe6b736f8e0)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**
curl --location --request POST 'http://192.168.56.107:6019/api/chat/completions' \
--header 'Authorization: Bearer fastgpt-DcamPUEXl1joShWWtoKFKPa6' \
--header 'Content-Type: application/json' \
--data-raw '{
    "chatId":"111",
    "stream":false,
    "detail": false,
    "variables": {
        "cTime": "2022/2/2 22:22"
    },
    "messages": [
        {
            "content": "Who is the director",
            "role": "user"
        }
    ]
}'

![image](https://github.com/labring/FastGPT/assets/5433705/983a068b-5192-463d-8b0a-73d1b9a439b5)
![image](https://github.com/labring/FastGPT/assets/5433705/af395635-d47a-4468-9cca-afe6b736f8e0)

**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
地址没对，注意看文档

**Comment by jinghai** [comment]
> 地址没对，注意看文档

就是看文档上的地址，我调用我定义的app，正确地址是什么，可以直接告诉我吗

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> The address is incorrect, please read the documentation carefully.

Just look at the address in the document. I call the app I defined. What is the correct address? Can you tell me directly?

**Comment by c121914yu** [comment]
> > 地址没对，注意看文档
> 
> 就是看文档上的地址，我调用我定义的app，正确地址是什么，可以直接告诉我吗

文档上的例子都有v1，你这路径明显少了
