### ISSUE TITLE
Is it possible to use xinference as the AI ​​dialogue source to achieve local multi-model access?

### ISSUE THREAD

**Issue by Minamiyama** [labring/FastGPT#399]

**Comment by c121914yu** [comment]
可以给oneapi 提feature，只要他们兼容了接口即可。

**Comment by qinxuye** [comment]
@Minamiyama Do you have interest to submit a PR to add xinference support for FastGPT?

**Comment by Minamiyama** [comment]
> @Minamiyama Do you have interest to submit a PR to add xinference support for FastGPT?

yes, I'd like to ;-p

**Comment by c121914yu** [comment]
翻一遍PR翻到这个。
感谢xinference支持，这周我们补一个接入文档。

**Comment by c121914yu** [comment]
> @c121914yu Could you help attach the detailed integration document?

https://doc.fastai.site/docs/development/custom-models/xinference/
