### ISSUE TITLE
The commercial version plug-in is loading...

### ISSUE THREAD

**Issue by xudaye2001** [labring/FastGPT#400]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
正常部署, 创建了应用, 使用md加载了测试文档.  使用外链分享.  打开后报错.

**复现步骤**

**预期结果**
![41697368886_ pic](https://github.com/labring/FastGPT/assets/46616201/28266918-b209-4836-9c0e-65bebe775e05)

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**
Deployed normally, created the application, and used md to load the test document. Use external links to share. An error was reported after opening.

**Steps to reproduce**

**expected outcome**
![41697368886_ pic](https://github.com/labring/FastGPT/assets/46616201/28266918-b209-4836-9c0e-65bebe775e05)


**Related screenshots**

**Comment by c121914yu** [comment]
4.5已经修复
