### ISSUE TITLE
After the revision, the return information of the "HTTP module" of advanced arrangement cannot be directly sent to the "specified reply" module.

### ISSUE THREAD

**Issue by wm-network** [labring/FastGPT#402]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
发现最近高级编排功能是不是迭代了，之前的保存貌似回滚了，重新设置了后发现一个问题，HTTP 模块返回的数据直接传递给 指定回复的【回复内容】，会无效被视为空，最终对话里显示的还是固定的内容。已验证HTTP模块数据返回是正确的。

**复现步骤**
如图 直接返回 关联 回复的内容， 直接返回的字段类型调整过也一样的，已在服务端验证这个返回的数据是非空的。
**预期结果**
【回复的内容】应该被【直接返回】字段覆盖。
**相关截图**
![image](https://github.com/labring/FastGPT/assets/130726200/a3a8cbac-f6b9-43ad-9619-be36a488ac7b)

![image](https://github.com/labring/FastGPT/assets/130726200/bfa9d79d-55c2-415d-bfe7-3d1c123f58ee)

**Comment by wm-network** [comment]
发现把触发器的连接断掉就可以了，那没问题了，可以关闭哈

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I found that just disconnecting the trigger is enough. That’s no problem. You can close it.
