### ISSUE TITLE
Consult me ​​about packaging issues encountered when upgrading to the new version 4.5.

### ISSUE THREAD

**Issue by taurusduan** [labring/FastGPT#406]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
docker打包时遇到问题
使用https://doc.fastgpt.run/docs/development/intro/的指令
docker build -t dockername/fastgpt --build-arg name=app .

root@debian11:/mnt/FastGPT-4.5# docker build -t dockername/fastgpt --build-arg name=app .
[+] Building 17.8s (11/27)                                                           docker:default
 => [internal] load build definition from Dockerfile                                           0.0s
 => => transferring dockerfile: 2.23kB                                                         0.0s
 => [internal] load .dockerignore                                                              0.0s
 => => transferring context: 139B                                                              0.0s
 => [internal] load metadata for docker.io/library/node:current-alpine                         1.9s
 => CACHED [builder 1/9] FROM docker.io/library/node:current-alpine@sha256:a369136b6f7640f85a  0.0s
 => [internal] load build context                                                              0.8s
 => => transferring context: 12.94MB                                                           0.7s
 => CACHED [builder 2/9] WORKDIR /app                                                          0.0s
 => CACHED [runner  3/10] RUN addgroup --system --gid 1001 nodejs                              0.0s
 => CACHED [runner  4/10] RUN adduser --system --uid 1001 nextjs                               0.0s
 => ERROR [deps 2/7] RUN apk add --no-cache libc6-compat --repository=http://dl-cdn.alpineli  15.9s
 => ERROR [runner  5/10] RUN apk add --no-cache curl ca-certificates --repository=http://dl-  15.9s
 => CACHED [builder 3/9] COPY package.json pnpm-workspace.yaml ./                              0.0s
------                                                                                              
 > [deps 2/7] RUN apk add --no-cache libc6-compat --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main && npm install -g pnpm:                                                                   
0.740 fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz                   
5.742 WARNING: fetching http://dl-cdn.alpinelinux.org/alpine/edge/main: temporary error (try again later)                                                                                               
5.742 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz                 
10.75 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz            
10.75 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)                                                                                             
15.75 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: temporary error (try again later)                                                                                        
15.75 ERROR: unable to select packages:
15.75   libc6-compat (no such package):
15.75     required by: world[libc6-compat]
------
------
 > [runner  5/10] RUN apk add --no-cache curl ca-certificates --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main &&     update-ca-certificates:
0.763 fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
5.771 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
5.771 WARNING: fetching http://dl-cdn.alpinelinux.org/alpine/edge/main: temporary error (try again later)
10.78 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)
10.78 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
15.79 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: temporary error (try again later)
15.79 ERROR: unable to select packages:
15.79   ca-certificates (no such package):
15.79     required by: world[ca-certificates]
15.79   curl (no such package):
15.79     required by: world[curl]
------
Dockerfile:46
--------------------
  45 |     # Use edge repository for curl and ca-certificates
  46 | >>> RUN apk add --no-cache curl ca-certificates --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main && \
  47 | >>>     update-ca-certificates
  48 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache curl ca-certificates --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main &&     update-ca-certificates" did not complete successfully: exit code: 2
root@debian11:/mnt/FastGPT-4.5# 

debian11桌面环境，网络正常
![image](https://github.com/labring/FastGPT/assets/30854760/1fceb9f5-d748-4936-aa75-e5f3812efb7c)

谢谢啊。

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
docker打包默认不走代理，需自行指定端口
