### ISSUE TITLE
When using the official website API, it prompts "Certificate error"

### ISSUE THREAD

**Issue by QichangZheng** [labring/FastGPT#410]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ X] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ X] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ X] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ X] 公有云版本
- [ ] 私有部署版本

**问题描述**
类似：https://github.com/labring/FastGPT/issues/240
改变VPN无法解决，在Colab运行结果也是这样，用的是应用的api。

**复现步骤**
```
import requests

url = "https://fastgpt.run/api/v1/chat/completions"
apikey = 'fastgpt-cOG8hD36jdF3cZVr7hZDdvd9ajYX'
# url = 'http://localhost:3000/api'
# url = 'https://fastgpt.run/api'

headers = {
    "Authorization": apikey,
    "Content-Type": "application/json"
}

data = {
    "chatId": "222",
    "stream": False,
    "detail": False,
    "variables": {
        "cTime": "2022/2/2 22:22"
    },
    "messages": [
        {
            "content": "导演是谁?",
            "role": "user"
        }
    ]
}

response = requests.post(url, headers=headers, json=data)

print(response.text)
```
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/82627111/c089d68e-d0e9-4bb0-aca0-cbf20303094b)
![image](https://github.com/labring/FastGPT/assets/82627111/ad97cc6b-020b-40fb-bc25-79c09c133bf4)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [
- [X] I used my own key and confirmed that my key can be used normally
- [X] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [X] Public cloud version
- [ ] private deployment version

**Problem Description**
Similar: https://github.com/labring/FastGPT/issues/240
Changing the VPN cannot solve the problem, and the result is the same when running in Colab, using the application's API.

**Steps to reproduce**
import requests

url = "https://fastgpt.run/api/v1/chat/completions"
apikey = 'fastgpt-cOG8hD36jdF3cZVr7hZDdvd9ajYX'
# url = 'http://localhost:3000/api'
# url = 'https://fastgpt.run/api'

headers = {
    "Authorization": apikey,
    "Content-Type": "application/json"
}

data = {
    "chatId": "222",
    "stream": False,
    "detail": False,
    "variables": {
        "cTime": "2022/2/2 22:22"
    },
    "messages": [
        {
            "content": "Who is the director?",
            "role": "user"
        }
    ]
}

response = requests.post(url, headers=headers, json=data)

print(response.text)

**expected outcome**

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/82627111/c089d68e-d0e9-4bb0-aca0-cbf20303094b)

**Comment by c121914yu** [comment]
.run 域名需要挂梯子，证书问题应该是没有了，之前挂了1小时
