### ISSUE TITLE
chatgpt-on-wechat Report an error based on the documentation!

### ISSUE THREAD

**Issue by lonely1215225** [labring/FastGPT#411]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
Bad Gateway: Invalid response object from API: '{"code":500,"statusText":"","message":"Post \\"http://region-9.autodl.pro:20943/v1/chat/completions?retry=0\\": dial tcp 36.139.225.141:20943: connect: connection refused (request id: 20231019102645818281101NboUowrd)","data":null}' (HTTP response code was 500)
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [x] Public cloud version
- [ ] private deployment version

**Problem Description**
Bad Gateway: Invalid response object from API: '{"code":500,"statusText":"","message":"Post \\"http://region-9.autodl.pro:20943/v1/chat /completions?retry=0\\": dial tcp 36.139.225.141:20943: connect: connection refused (request id: 20231019102645818281101NboUowrd)","data":null}' (HTTP response code was 500)
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
地址少了个 /api？
