### ISSUE TITLE
Why can’t I access domestic addresses? I need to bypass the wall.

### ISSUE THREAD

**Issue by lishuailingcqupt** [labring/FastGPT#413]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.run/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**

**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by YaoSiQian** [comment]
More clearly:
The domain <https://fastgpt.run> was banned by [GFW](https://en.wikipedia.org/wiki/Great_Firewall)
If you try to ping this domain in China, you'll probably get a random IP in global.

[![Ping from multiple locations in China](https://github.com/labring/FastGPT/assets/29835749/bd4c83e6-4d43-4650-b766-d16013928fb0 "Ping from multiple locations in China")](https://ping.chinaz.com/fastgpt.run)

**Comment by c121914yu** [comment]
.run域名国内已无法直接访问，国内临时可以用 https://ai.fastgpt.in 替代
