### ISSUE TITLE
There is no available channel for model text-embedding-ada-002 under the current group default.

### ISSUE THREAD

**Issue by NeoTwh** [labring/FastGPT#414]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
 导入数据后出现，控制台出现当前分组 default 下对于模型 text-embedding-ada-002 无可用渠道 
**复现步骤**
私有化部署之后，接入one-api 的平台使用 微软云的 openai 模型
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/32731816/9e4e9766-ece0-46c9-a00e-af9ea039a020)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x ] I have confirmed that there is currently no similar issue
- [x ] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x ] private deployment version

**Problem Description**
 Appears after importing data. The console shows that there are no available channels for the model text-embedding-ada-002 under the current group default.
**Steps to reproduce**
After privatization deployment, the platform that accesses one-api uses the openai model of Microsoft Cloud
**expected outcome**

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/32731816/9e4e9766-ece0-46c9-a00e-af9ea039a020)

**Comment by c121914yu** [comment]
oneapi配置不对，参考文档添加相关模型。
