### ISSUE TITLE
V4.5 docker build error,  Error: resolve-url-loader: CSS error

### ISSUE THREAD

**Issue by xjune123** [labring/FastGPT#415]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
    下载最新V4.5代码后，构建镜像直接报错
**复现步骤**
    执行构建镜像
`docker build -t dockername/fastgpt --build-arg name=app .
`
**预期结果**
  预期能构建镜像成功，但是实际在多次构建，都卡在RUN pnpm --filter=app run build 这个命令，报错信息如下
`#0 69.42 Error: resolve-url-loader: CSS error
#0 69.42   PostCSS received undefined instead of CSS string
#0 69.42   at new Input (/app/node_modules/.pnpm/registry.npmmirror.com+postcss@8.4.14/node_modules/postcss/lib/input.js:24:13)
#0 69.42     at encodeError (/app/node_modules/.pnpm/registry.npmmirror.com+next@13.5.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js:85:16)
#0 69.42     at onFailure (/app/node_modules/.pnpm/registry.npmmirror.com+next@13.5.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js:71:18)
#0 69.42     at processTicksAndRejections (node:internal/process/task_queues:95:5)
#0 69.42     at runNextTicks (node:internal/process/task_queues:64:3)
#0 69.42     at process.processImmediate (node:internal/timers:449:9)

`
**相关截图**
<img width="1498" alt="image" src="https://github.com/labring/FastGPT/assets/21253844/273387ab-b47f-45bf-8073-8e4047a35614">

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/417

新版 dockerfile 指定了node版本，已解决。
