### ISSUE TITLE
我自己写的第三方接口，使用的是标准的openai接收和返回结构，在oneapi中测试没有问题，但在与fastgpt通讯中一直返回为空，不知道我写的json格式是否有问题还其他什么原因

### ISSUE THREAD

**Issue by dazhizun** [labring/FastGPT#420]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
我自己写的第三方接口，使用的是标准的openai接收和返回结构，在oneapi中测试没有问题，但在与fastgpt通讯中一直返回为空，不知道我写的json格式是否有问题还其他什么原因

接收结构用的是：
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'

返回结构用的是：
{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "model": "gpt-3.5-turbo-0613",
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}

**预期结果**
fastgpt有返回结果，可否给出fastgpt要求的返回json格式

**相关截图**
这是我自己写的接口POST测试图
![微信截图_20231023135321](https://github.com/songquanpeng/one-api/assets/3522824/6278f883-fb54-4f81-af14-530deebbc10b)

这是POST自己搭建的ONEAPI渠道测试图
![微信截图_20231023135431](https://github.com/songquanpeng/one-api/assets/3522824/5cb59498-e3f8-4710-a8ce-a919fc41e238)

这是渠道测试成功截图
![微信截图_20231023135549](https://github.com/songquanpeng/one-api/assets/3522824/07a63f6e-b263-4e85-90ca-7f946917e05f)

![微信截图_20231023135620](https://github.com/songquanpeng/one-api/assets/3522824/d7dcef37-4d90-4d10-8c9c-a135bc9b1ae6)

这是fastgpt返回消息为空截图
![微信截图_20231023135704](https://github.com/songquanpeng/one-api/assets/3522824/d46d4c4b-c830-4ca4-a255-561cdbaffdb1)

经测试其他的接口没有问题，但是我写的也是按照标准的openai接口写出来的
![微信截图_20231023140850](https://github.com/songquanpeng/one-api/assets/3522824/8ae2c8de-3c35-4bd7-85d0-1eaf8439bd46)

**Comment by dazhizun** [comment]
测试过了，还是没有解决，不调用oneapi，直接调用我自己写的接口也不行，是否可以给个标准的头协议，POST和返回JSON的格式哇，我自己写一个调用模块

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I've tested it, but it's still not solved. It doesn't work if I don't call oneapi, or directly call the interface I wrote myself. Can you give me a standard header protocol, POST and return JSON format? I'll write a calling module myself.

**Comment by c121914yu** [comment]
oneapi测试只是非stream的测试，说明你是stream模式有问题，用curl测测就懂了。

**Comment by dazhizun** [comment]
您的意思是要写一个stream模式就可以了吗

**Comment by c121914yu** [comment]
> 您的意思是要写一个stream模式就可以了吗

两个模式都要写

**Comment by dazhizun** [comment]
![微信截图_20231024010056](https://github.com/labring/FastGPT/assets/3522824/16def959-d531-4502-88b6-86fc606fd04d)
都按流类型输出了，杂还是不行呢

**Comment by dazhizun** [comment]
fix: run app stream=false response
我看您修复了关闭流，在哪里设置呢，实在抓狂了~~

**Comment by dazhizun** [comment]
已搞定，感谢感谢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Done, thank you
