### ISSUE TITLE
api and gpt error return formats are not consistent

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#422]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.5.0
- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
这是FastGPT返回错误：
```
{"code":500,"statusText":"","message":"当前分组 default 下对于模型 M3E 无可用渠道 (request id: 2023102316560920779259FmI5pN9a)","data":null}
```
这是chatgpt返回错误：
```
{
"error":{
"message": "Incorrect API key provided: xxx-*********************************************43ca. You can find your API key at https://platform.openai.com/account/api-keys.",
"type": "invalid_request_error",
"param": null,
"code": "invalid_api_key"
}
}
```
可否改为gpt的错误响应格式？
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**
v4.5.0
- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
This is the error returned by FastGPT:
```
{"code":500,"statusText":"","message":"There is no available channel for model M3E under the current group default (request id: 2023102316560920779259FmI5pN9a)","data":null}
```
This is the error returned by chatgpt:
```
{
"error":{
"message": "Incorrect API key provided: xxx-************************************** *******43ca. You can find your API key at https://platform.openai.com/account/api-keys.",
"type": "invalid_request_error",
"param": null,
"code": "invalid_api_key"
}
}
```
Can I change it to the error response format of gpt?
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
不会统一格式。
