### ISSUE TITLE
docker deployment, modified port, started normally, inaccessible

### ISSUE THREAD

**Issue by lilinrestart** [labring/FastGPT#426]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ √] 我已确认目前没有类似 issue
- [√ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [√ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
最新版
- [ ] 公有云版本
- [√] 私有部署版本

**问题描述**
docker部署，修改了端口，正常启动，使用ip+端口7031，无法访问
**复现步骤**
按照文档所示进行部署，仅修改了端口
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/140720825/44441f9c-f9cf-4031-848d-b7151b37d3bb)

![image](https://github.com/labring/FastGPT/assets/140720825/bc9daa42-eeb1-48d6-9c05-cac14afe50c4)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [√] I have confirmed that there is currently no similar issue
- [√ ] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.run/docs/intro/)
- [√ ] I used my own key and confirmed that my key can be used normally
- [√ ] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [√] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**
new
- [ ] Public cloud version
- [√] Private deployment version

**Problem Description**
Docker deployment, modified port, started normally, used ip + port 7031, inaccessible
**Steps to reproduce**
Deployed as shown in the documentation, only modified the port
**expected outcome**

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/140720825/44441f9c-f9cf-4031-848d-b7151b37d3bb)

![image](https://github.com/labring/FastGPT/assets/140720825/bc9daa42-eeb1-48d6-9c05-cac14afe50c4)

**Comment by c121914yu** [comment]
并没有理解你的意图，在 docker 中，这个配置只是一个本机与容器端口的映射，容器实际还是运行 3000，而本地则为 7031。如需 ip:7031 访问，确保防火墙之类的开放即可。

**Comment by xinggonglie** [comment]
怎么修改容器的端口，我想改成4000:4000这种，需要改代码吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
How to modify the port of the container? I want to change it to 4000:4000. Do I need to change the code?

**Comment by Grewizard11** [comment]
> 怎么修改容器的端口，我想改成4000:4000这种，需要改代码吗？

改成4000:3000就可以，3000是容器的端口，4000是本机的映射端口

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> How to modify the port of the container? I want to change it to 4000:4000. Do I need to change the code?

Just change it to 4000:3000. 3000 is the port of the container and 4000 is the mapped port of the local machine.
