### ISSUE TITLE
After the upgrade was completed on 10.24, the knowledge base was lost

### ISSUE THREAD

**Issue by hbytw** [labring/FastGPT#428]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [// ] 我已确认目前没有类似 issue
- [// ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ //] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [// ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ 4.5.1] 公有云版本
- [ //] 私有部署版本

**问题描述**
使用 docker-compose pull   docker-compose up -d 两条命令更新后，知识库全部丢失。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/43083918/d308af52-4423-47c5-b5c9-7964ae5fc59b)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [// ] I have confirmed that there is currently no similar issue
- [// ] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [ //] I used my own key and confirmed that my key can be used normally
- [// ] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [4.5.1] Public cloud version
- [ //] Private deployment version

**Problem Description**
After updating the two commands using docker-compose pull docker-compose up -d, the knowledge base was completely lost.
**Steps to reproduce**

**expected outcome**

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/43083918/d308af52-4423-47c5-b5c9-7964ae5fc59b)

**Comment by c121914yu** [comment]
你确定你看文档了？

**Comment by hbytw** [comment]
没仔细看，我以为直接升级就行了，大意了，还能恢复吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Without looking carefully, I thought that just upgrading would be enough. If I was careless, can I still restore it?

**Comment by hbytw** [comment]
怎么能找回数据啊？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
How can I retrieve the data?

**Comment by c121914yu** [comment]
> 没仔细看，我以为直接升级就行了，大意了，还能恢复吗？

执行初始化就好了

**Comment by hbytw** [comment]
感谢，初始化成功。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks, initialization successful.
