### ISSUE TITLE
Local docker deployment, new data set file upload failed

### ISSUE THREAD

**Issue by lilinrestart** [labring/FastGPT#429]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√ ] 我已确认目前没有类似 issue
- [√ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [√ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√ ] 私有部署版本

**问题描述**

**复现步骤**
本地部署docker，上传文件
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/140720825/47e8049a-83b0-406a-8fe8-f119769391c1)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [√ ] I have confirmed that there is currently no similar issue
- [√ ] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.run/docs/intro/)
- [√ ] I used my own key and confirmed that my key can be used normally
- [√] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [√] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [√ ] Private deployment version

**Problem Description**

**Steps to reproduce**
Deploy docker locally and upload files
**expected outcome**

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/140720825/47e8049a-83b0-406a-8fe8-f119769391c1)

**Comment by lilinrestart** [comment]
文件大小只有几兆

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The file size is only a few megabytes

**Comment by c121914yu** [comment]
代码限制是500M，超出是网关没有允许传输更大的内容。应调整 nginx 或者 ingress 之类的。
