### ISSUE TITLE
Connection trigger problem

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#430]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
version: 4.5.1

我配置了多个用户消息card，但是只有一个能触发AI回应

如下图：
1号card能正常触发，2号连线后无法触发
日志也只新增一行
```
[INFO]: 2023-10-24 18:56:35: finish completions: {"source":"fastgpt","userId":"6538048befc3f128eb14c48c","price":0}
```
**复现步骤**

**预期结果**

**相关截图**
<img width="1422" alt="Screenshot 2023-10-25 at 02 51 42" src="https://github.com/labring/FastGPT/assets/36452456/8c79c45d-9ddc-4b97-8636-0e618d512ed1">

**Comment by c121914yu** [comment]
因为是等价的，多个只是为了好看，功能上没有差异。

**Comment by bincooo** [comment]
谢回。

那为什么无法触发AI对话的卡片？问题分类可以确定是分类2，但是没有继续执行

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thank you.

So why can't the card trigger the AI ​​dialogue? The problem classification can be determined to be category 2, but the execution is not continued.

**Comment by c121914yu** [comment]
> 谢回。
> 
> 那为什么无法触发AI对话的卡片？问题分类可以确定是分类2，但是没有继续执行

因为AI对话还连接了引用内容，而引用内容需要1的知识库搜索，这意味着这个编排是矛盾的。

**Comment by bincooo** [comment]
哦，也就是说要两个连线的条件都触发才能继续执行？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Oh, that means that both connection conditions must be triggered before execution can continue?
