### ISSUE TITLE
Help: PDF upload is restricted, how to change the size limit

### ISSUE THREAD

**Issue by nickboyabc** [labring/FastGPT#431]
![](https://s2.loli.net/2023/10/25/Ri3SwGMTEjA54f6.png)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![](https://s2.loli.net/2023/10/25/Ri3SwGMTEjA54f6.png)

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/429
同
