### ISSUE TITLE
使用oneapi集成星火模型embedding报错

### ISSUE THREAD

**Issue by lyzheng01** [labring/FastGPT#433]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
Fast GPT V4.5.0
私有部署版本

**问题描述**
使用oneapi集成星火模型的时候发现没有星火的向量模型使用，ChatModels对话正常显示，但是知识库录入和检索就报错，报错信息如下：
[INFO] 2023/10/25 - 19:34:09 | 20231025193409668521031oYo34JQD | user 1 has enough quota 99998615, trusted and no need to pre-consume 
[SYS] 2023/10/25 - 19:34:09 | error reading stream response: websocket: close 1000 (normal): close this ws conn 

2023/10/25 19:34:09 [Recovery] 2023/10/25 - 19:34:09 panic recovered:
runtime error: index out of range [0] with length 0
/usr/local/go/src/runtime/panic.go:114 (0x438b9b)
/build/controller/relay-xunfei.go:234 (0xc7faf0)
/build/controller/relay-text.go:587 (0xc7af4f)
/build/controller/relay.go:196 (0xc824b9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x91c52a)
/build/middleware/distributor.go:96 (0xc9c079)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x91c52a)
/build/middleware/auth.go:123 (0xc9ba13)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x91c52a)
/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 (0xc9ccbc)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x92837d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x92834c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x91c52a)
/build/middleware/request-id.go:16 (0xc9d0d5)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x9291d9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x9291c7)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x92743a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x9270cd)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x926bfc)
/usr/local/go/src/net/http/server.go:2938 (0x6d4bcd)
/usr/local/go/src/net/http/server.go:2009 (0x6d0ab3)
/usr/local/go/src/runtime/asm_amd64.s:1650 (0x46d1e0)

**复现步骤**

**预期结果**

**相关截图**

![image](https://github.com/labring/FastGPT/assets/143930490/2f9f1f95-1b87-49b6-9d74-156132a85c08)

**Comment by c121914yu** [comment]
runtime error: index out of range [0] with length 0 说明数组是空的，应自行检查该接口
