### ISSUE TITLE
When the knowledge base result is empty, the http module or the specified reply module cannot be triggered.

### ISSUE THREAD

**Issue by fan1jun** [labring/FastGPT#436]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本：4.4.7

**问题描述**
知识库结果为空时，无法触发http模块或指定回复模块
**复现步骤**
[
  {
    "moduleId": "userChatInput",
    "name": "用户问题(对话入口)",
    "flowType": "questionInput",
    "position": {
      "x": 349.3289224321007,
      "y": 1607.8116807043698
    },
    "inputs": [
      {
        "key": "userChatInput",
        "type": "systemInput",
        "label": "用户问题",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "userChatInput",
        "label": "用户问题",
        "type": "source",
        "valueType": "string",
        "targets": [
          {
            "moduleId": "ilht4i",
            "key": "userChatInput"
          },
          {
            "moduleId": "y58gru",
            "key": "userChatInput"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "5fk9ru",
    "name": "HTTP模块",
    "flowType": "httpRequest",
    "showStatus": true,
    "position": {
      "x": 1569.5823010662725,
      "y": 594.8219956078507
    },
    "inputs": [
      {
        "key": "switch",
        "type": "target",
        "label": "触发器",
        "valueType": "any",
        "connected": true
      },
      {
        "key": "url",
        "value": "https://xxx.io/search",
        "type": "input",
        "label": "请求地址",
        "description": "请求目标地址",
        "placeholder": "https://api.fastgpt.run/getInventory",
        "required": true,
        "connected": true
      },
      {
        "valueType": "string",
        "type": "target",
        "label": "搜索词",
        "edit": true,
        "key": "searchKey",
        "required": true,
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "finish",
        "label": "模块调用结束",
        "description": "模块调用结束时触发",
        "valueType": "boolean",
        "type": "source",
        "targets": [
          {
            "moduleId": "0g9nm2",
            "key": "switch"
          }
        ]
      },
      {
        "label": "搜索词",
        "valueType": "string",
        "type": "source",
        "edit": true,
        "targets": [],
        "key": "searchKey"
      },
      {
        "label": "搜索结果",
        "valueType": "string",
        "type": "source",
        "edit": true,
        "targets": [
          {
            "moduleId": "0g9nm2",
            "key": "systemPrompt"
          }
        ],
        "key": "SResults"
      }
    ]
  },
  {
    "moduleId": "ilht4i",
    "name": "知识库搜索",
    "flowType": "kbSearchNode",
    "showStatus": true,
    "position": {
      "x": 816.0906157560987,
      "y": 575.0392803587324
    },
    "inputs": [
      {
        "key": "switch",
        "type": "target",
        "label": "触发器",
        "valueType": "any",
        "connected": false
      },
      {
        "key": "kbList",
        "type": "selectDataset",
        "label": "关联的知识库",
        "value": [
          {
            "kbId": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "vectorModel": {
              "model": "text-embedding-ada-002",
              "name": "Embedding-2",
              "price": 0,
              "defaultToken": 500,
              "maxToken": 3000
            }
          },
          {
            "kbId": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "vectorModel": {
              "model": "text-embedding-ada-002",
              "name": "Embedding-2",
              "price": 0,
              "defaultToken": 500,
              "maxToken": 3000
            }
          }
        ],
        "list": [],
        "required": true,
        "connected": true
      },
      {
        "key": "similarity",
        "type": "slider",
        "label": "相似度",
        "value": 0.62,
        "min": 0,
        "max": 1,
        "step": 0.01,
        "markList": [
          {
            "label": "100",
            "value": 100
          },
          {
            "label": "1",
            "value": 1
          }
        ],
        "connected": true
      },
      {
        "key": "limit",
        "type": "slider",
        "label": "单次搜索上限",
        "description": "最多取 n 条记录作为本次问题引用",
        "value": 5,
        "min": 1,
        "max": 20,
        "step": 1,
        "markList": [
          {
            "label": "1",
            "value": 1
          },
          {
            "label": "20",
            "value": 20
          }
        ],
        "connected": true
      },
      {
        "key": "userChatInput",
        "type": "target",
        "label": "用户问题",
        "required": true,
        "valueType": "string",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "finish",
        "label": "模块调用结束",
        "description": "模块调用结束时触发",
        "valueType": "boolean",
        "type": "source",
        "targets": []
      },
      {
        "key": "isEmpty",
        "label": "搜索结果为空",
        "type": "source",
        "valueType": "boolean",
        "targets": [
          {
            "moduleId": "5fk9ru",
            "key": "switch"
          }
        ]
      },
      {
        "key": "unEmpty",
        "label": "搜索结果不为空",
        "type": "source",
        "valueType": "boolean",
        "targets": [
          {
            "moduleId": "y58gru",
            "key": "switch"
          }
        ]
      },
      {
        "key": "quoteQA",
        "label": "引用内容",
        "description": "始终返回数组，如果希望搜索结果为空时执行额外操作，需要用到上面的两个输入以及目标模块的触发器",
        "type": "source",
        "valueType": "kb_quote",
        "targets": [
          {
            "moduleId": "y58gru",
            "key": "quoteQA"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "ezio5s",
    "name": "用户问题(对话入口)",
    "flowType": "questionInput",
    "position": {
      "x": 1254.2276193305545,
      "y": 532.3509146108194
    },
    "inputs": [
      {
        "key": "userChatInput",
        "type": "systemInput",
        "label": "用户问题",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "userChatInput",
        "label": "用户问题",
        "type": "source",
        "valueType": "string",
        "targets": [
          {
            "moduleId": "5fk9ru",
            "key": "searchKey"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "0g9nm2",
    "name": "AI 对话",
    "flowType": "chatNode",
    "showStatus": true,
    "position": {
      "x": 2494.1855269831726,
      "y": 697.9825468830436
    },
    "inputs": [
      {
        "key": "switch",
        "type": "target",
        "label": "触发器",
        "valueType": "any",
        "connected": true
      },
      {
        "key": "model",
        "type": "selectChatModel",
        "label": "对话模型",
        "value": "gpt-3.5-turbo",
        "list": [],
        "required": true,
        "connected": true
      },
      {
        "key": "temperature",
        "type": "slider",
        "label": "温度",
        "value": 2,
        "min": 0,
        "max": 10,
        "step": 1,
        "markList": [
          {
            "label": "严谨",
            "value": 0
          },
          {
            "label": "发散",
            "value": 10
          }
        ],
        "connected": true
      },
      {
        "key": "maxToken",
        "type": "maxToken",
        "label": "回复上限",
        "value": 2000,
        "min": 100,
        "max": 4000,
        "step": 50,
        "markList": [
          {
            "label": "100",
            "value": 100
          },
          {
            "label": "4000",
            "value": 4000
          }
        ],
        "connected": true
      },
      {
        "key": "systemPrompt",
        "type": "textarea",
        "label": "系统提示词",
        "max": 300,
        "valueType": "string",
        "description": "模型固定的引导词，通过调整该内容，可以引导模型聊天方向。该内容会被固定在上下文的开头。可使用变量，例如 {{language}}",
        "placeholder": "模型固定的引导词，通过调整该内容，可以引导模型聊天方向。该内容会被固定在上下文的开头。可使用变量，例如 {{language}}",
        "value": "",
        "connected": true
      },
      {
        "key": "quoteTemplate",
        "type": "hidden",
        "label": "引用内容模板",
        "valueType": "string",
        "value": "",
        "connected": true
      },
      {
        "key": "quotePrompt",
        "type": "hidden",
        "label": "引用内容提示词",
        "valueType": "string",
        "value": "",
        "connected": true
      },
      {
        "key": "quoteQA",
        "type": "quoteList",
        "label": "引用内容",
        "description": "对象数组格式，结构：\n [{q:'问题',a:'回答'}]",
        "valueType": "kb_quote",
        "connected": false
      },
      {
        "key": "history",
        "type": "target",
        "label": "聊天记录",
        "valueType": "chat_history",
        "connected": true
      },
      {
        "key": "userChatInput",
        "type": "target",
        "label": "用户问题",
        "required": true,
        "valueType": "string",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "finish",
        "label": "模块调用结束",
        "description": "模块调用结束时触发",
        "valueType": "boolean",
        "type": "source",
        "targets": []
      },
      {
        "key": "history",
        "label": "新的上下文",
        "description": "将本次回复内容拼接上历史记录，作为新的上下文返回",
        "valueType": "chat_history",
        "type": "source",
        "targets": []
      },
      {
        "key": "answerText",
        "label": "模型回复",
        "description": "将在 stream 回复完毕后触发",
        "valueType": "string",
        "type": "source",
        "targets": []
      }
    ]
  },
  {
    "moduleId": "ttaqlj",
    "name": "聊天记录",
    "flowType": "historyNode",
    "position": {
      "x": 2042.8773179478444,
      "y": 1223.7490126279038
    },
    "inputs": [
      {
        "key": "maxContext",
        "type": "numberInput",
        "label": "最长记录数",
        "value": 6,
        "min": 0,
        "max": 50,
        "connected": true
      },
      {
        "key": "history",
        "type": "hidden",
        "label": "聊天记录",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "history",
        "label": "聊天记录",
        "valueType": "chat_history",
        "type": "source",
        "targets": [
          {
            "moduleId": "0g9nm2",
            "key": "history"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "mpdf5a",
    "name": "用户问题(对话入口)",
    "flowType": "questionInput",
    "position": {
      "x": 2070.2293306166525,
      "y": 1545.894939616084
    },
    "inputs": [
      {
        "key": "userChatInput",
        "type": "systemInput",
        "label": "用户问题",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "userChatInput",
        "label": "用户问题",
        "type": "source",
        "valueType": "string",
        "targets": [
          {
            "moduleId": "0g9nm2",
            "key": "userChatInput"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "fwwrpi",
    "name": "聊天记录",
    "flowType": "historyNode",
    "position": {
      "x": 332.108687626388,
      "y": 1234.8883860718956
    },
    "inputs": [
      {
        "key": "maxContext",
        "type": "numberInput",
        "label": "最长记录数",
        "value": 6,
        "min": 0,
        "max": 50,
        "connected": true
      },
      {
        "key": "history",
        "type": "hidden",
        "label": "聊天记录",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "history",
        "label": "聊天记录",
        "valueType": "chat_history",
        "type": "source",
        "targets": [
          {
            "moduleId": "y58gru",
            "key": "history"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "y58gru",
    "name": "AI 对话",
    "flowType": "chatNode",
    "showStatus": true,
    "position": {
      "x": 1401.5232949374868,
      "y": 1328.7953862503282
    },
    "inputs": [
      {
        "key": "switch",
        "type": "target",
        "label": "触发器",
        "valueType": "any",
        "connected": true
      },
      {
        "key": "model",
        "type": "selectChatModel",
        "label": "对话模型",
        "value": "gpt-3.5-turbo",
        "list": [],
        "required": true,
        "connected": true
      },
      {
        "key": "temperature",
        "type": "slider",
        "label": "温度",
        "value": 2,
        "min": 0,
        "max": 10,
        "step": 1,
        "markList": [
          {
            "label": "严谨",
            "value": 0
          },
          {
            "label": "发散",
            "value": 10
          }
        ],
        "connected": true
      },
      {
        "key": "maxToken",
        "type": "maxToken",
        "label": "回复上限",
        "value": 2000,
        "min": 100,
        "max": 4000,
        "step": 50,
        "markList": [
          {
            "label": "100",
            "value": 100
          },
          {
            "label": "4000",
            "value": 4000
          }
        ],
        "connected": true
      },
      {
        "key": "systemPrompt",
        "type": "textarea",
        "label": "系统提示词",
        "max": 300,
        "valueType": "string",
        "description": "模型固定的引导词，通过调整该内容，可以引导模型聊天方向。该内容会被固定在上下文的开头。可使用变量，例如 {{language}}",
        "placeholder": "模型固定的引导词，通过调整该内容，可以引导模型聊天方向。该内容会被固定在上下文的开头。可使用变量，例如 {{language}}",
        "value": "",
        "connected": true
      },
      {
        "key": "quoteTemplate",
        "type": "hidden",
        "label": "引用内容模板",
        "valueType": "string",
        "value": "",
        "connected": true
      },
      {
        "key": "quotePrompt",
        "type": "hidden",
        "label": "引用内容提示词",
        "valueType": "string",
        "value": "",
        "connected": true
      },
      {
        "key": "quoteQA",
        "type": "quoteList",
        "label": "引用内容",
        "description": "对象数组格式，结构：\n [{q:'问题',a:'回答'}]",
        "valueType": "kb_quote",
        "connected": true
      },
      {
        "key": "history",
        "type": "target",
        "label": "聊天记录",
        "valueType": "chat_history",
        "connected": true
      },
      {
        "key": "userChatInput",
        "type": "target",
        "label": "用户问题",
        "required": true,
        "valueType": "string",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "finish",
        "label": "模块调用结束",
        "description": "模块调用结束时触发",
        "valueType": "boolean",
        "type": "source",
        "targets": []
      },
      {
        "key": "history",
        "label": "新的上下文",
        "description": "将本次回复内容拼接上历史记录，作为新的上下文返回",
        "valueType": "chat_history",
        "type": "source",
        "targets": []
      },
      {
        "key": "answerText",
        "label": "模型回复",
        "description": "将在 stream 回复完毕后触发",
        "valueType": "string",
        "type": "source",
        "targets": []
      }
    ]
  }
]
**预期结果**
按照流程，结果为空则触发相应模块

**相关截图**
![image](https://github.com/labring/FastGPT/assets/129055843/d2f66c21-0da6-41ae-8185-f55d51ba4536)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version: 4.4.7

**Problem Description**
When the knowledge base result is empty, the http module or the specified reply module cannot be triggered.
**Steps to reproduce**
[
  {
    "moduleId": "userChatInput",
    "name": "User question (dialogue entry)",
    "flowType": "questionInput",
    "position": {
      "x": 349.3289224321007,
      "y": 1607.8116807043698
    },
    "inputs": [
      {
        "key": "userChatInput",
        "type": "systemInput",
        "label": "User Question",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "userChatInput",
        "label": "User Question",
        "type": "source",
        "valueType": "string",
        "targets": [
          {
            "moduleId": "ilht4i",
            "key": "userChatInput"
          },
          {
            "moduleId": "y58gru",
            "key": "userChatInput"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "5fk9ru",
    "name": "HTTP module",
    "flowType": "httpRequest",
    "showStatus": true,
    "position": {
      "x": 1569.5823010662725,
      "y": 594.8219956078507
    },
    "inputs": [
      {
        "key": "switch",
        "type": "target",
        "label": "trigger",
        "valueType": "any",
        "connected": true
      },
      {
        "key": "url",
        "value": "https://xxx.io/search",
        "type": "input",
        "label": "Request address",
        "description": "Request target address",
        "placeholder": "https://api.fastgpt.run/getInventory",
        "required": true,
        "connected": true
      },
      {
        "valueType": "string",
        "type": "target",
        "label": "search term",
        "edit": true,
        "key": "searchKey",
        "required": true,
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "finish",
        "label": "Module call ends",
        "description": "Triggered when the module call ends",
        "valueType": "boolean",
        "type": "source",
        "targets": [
          {
            "moduleId": "0g9nm2",
            "key": "switch"
          }
        ]
      },
      {
        "label": "search term",
        "valueType": "string",
        "type": "source",
        "edit": true,
        "targets": [],
        "key": "searchKey"
      },
      {
        "label": "Search results",
        "valueType": "string",
        "type": "source",
        "edit": true,
        "targets": [
          {
            "moduleId": "0g9nm2",
            "key": "systemPrompt"
          }
        ],
        "key": "SResults"
      }
    ]
  },
  {
    "moduleId": "ilht4i",
    "name": "Knowledge Base Search",
    "flowType": "kbSearchNode",
    "showStatus": true,
    "position": {
      "x": 816.0906157560987,
      "y": 575.0392803587324
    },
    "inputs": [
      {
        "key": "switch",
        "type": "target",
        "label": "trigger",
        "valueType": "any",
        "connected": false
      },
      {
        "key": "kbList",
        "type": "selectDataset",
        "label": "Associated knowledge base",
        "value": [
          {
            "kbId": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "vectorModel": {
              "model": "text-embedding-ada-002",
              "name": "Embedding-2",
              "price": 0,
              "defaultToken": 500,
              "maxToken": 3000
            }
          },
          {
            "kbId": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "vectorModel": {
              "model": "text-embedding-ada-002",
              "name": "Embedding-2",
              "price": 0,
              "defaultToken": 500,
              "maxToken": 3000
            }
          }
        ],
        "list": [],
        "required": true,
        "connected": true
      },
      {
        "key": "similarity",
        "type": "slider",
        "label": "similarity",
        "value": 0.62,
        "min": 0,
        "max": 1,
        "step": 0.01,
        "markList": [
          {
            "label": "100",
            "value": 100
          },
          {
            "label": "1",
            "value": 1
          }
        ],
        "connected": true
      },
      {
        "key": "limit",
        "type": "slider",
        "label": "Single search limit",
        "description": "Take up to n records as references for this question",
        "value": 5,
        "min": 1,
        "max": 20,
        "step": 1,
        "markList": [
          {
            "label": "1",
            "value": 1
          },
          {
            "label": "20",
            "value": 20
          }
        ],
        "connected": true
      },
      {
        "key": "userChatInput",
        "type": "target",
        "label": "User Question",
        "required": true,
        "valueType": "string",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "finish",
        "label": "Module call ends",
        "description": "Triggered when the module call ends",
        "valueType": "boolean",
        "type": "source",
        "targets": []
      },
      {
        "key": "isEmpty",
        "label": "Search results are empty",
        "type": "source",
        "valueType": "boolean",
        "targets": [
          {
            "moduleId": "5fk9ru",
            "key": "switch"
          }
        ]
      },
      {
        "key": "unEmpty",
        "label": "Search results are not empty",
        "type": "source",
        "valueType": "boolean",
        "targets": [
          {
            "moduleId": "y58gru",
            "key": "switch"
          }
        ]
      },
      {
        "key": "quoteQA",
        "label": "Quoted content",
        "description": "Always return an array. If you want to perform additional operations when the search result is empty, you need to use the above two inputs and the trigger of the target module",
        "type": "source",
        "valueType": "kb_quote",
        "targets": [
          {
            "moduleId": "y58gru",
            "key": "quoteQA"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "ezio5s",
    "name": "User question (dialogue entry)",
    "flowType": "questionInput",
    "position": {
      "x": 1254.2276193305545,
      "y": 532.3509146108194
    },
    "inputs": [
      {
        "key": "userChatInput",
        "type": "systemInput",
        "label": "User Question",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "userChatInput",
        "label": "User Question",
        "type": "source",
        "valueType": "string",
        "targets": [
          {
            "moduleId": "5fk9ru",
            "key": "searchKey"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "0g9nm2",
    "name": "AI dialogue",
    "flowType": "chatNode",
    "showStatus": true,
    "position": {
      "x": 2494.1855269831726,
      "y": 697.9825468830436
    },
    "inputs": [
      {
        "key": "switch",
        "type": "target",
        "label": "trigger",
        "valueType": "any",
        "connected": true
      },
      {
        "key": "model",
        "type": "selectChatModel",
        "label": "dialogue model",
        "value": "gpt-3.5-turbo",
        "list": [],
        "required": true,
        "connected": true
      },
      {
        "key": "temperature",
        "type": "slider",
        "label": "temperature",
        "value": 2,
        "min": 0,
        "max": 10,
        "step": 1,
        "markList": [
          {
            "label": "rigorous",
            "value": 0
          },
          {
            "label": "divergent",
            "value": 10
          }
        ],
        "connected": true
      },
      {
        "key": "maxToken",
        "type": "maxToken",
        "label": "Reply limit",
        "value": 2000,
        "min": 100,
        "max": 4000,
        "step": 50,
        "markList": [
          {
            "label": "100",
            "value": 100
          },
          {
            "label": "4000",
            "value": 4000
          }
        ],
        "connected": true
      },
      {
        "key": "systemPrompt",
        "type": "textarea",
        "label": "System prompt word",
        "max": 300,
        "valueType": "string",
        "description": "The guide word fixed by the model. By adjusting the content, you can guide the model chat direction. The content will be fixed at the beginning of the context. Variables can be used, such as {{language}}",
        "placeholder": "The guide word fixed by the model. By adjusting the content, you can guide the model chat direction. The content will be fixed at the beginning of the context. Variables can be used, such as {{language}}",
        "value": "",
        "connected": true
      },
      {
        "key": "quoteTemplate",
        "type": "hidden",
        "label": "Quote content template",
        "valueType": "string",
        "value": "",
        "connected": true
      },
      {
        "key": "quotePrompt",
        "type": "hidden",
        "label": "Quote content prompt words",
        "valueType": "string",
        "value": "",
        "connected": true
      },
      {
        "key": "quoteQA",
        "type": "quoteList",
        "label": "Quoted content",
        "description": "Object array format, structure:\n [{q:'question',a:'answer'}]",
        "valueType": "kb_quote",
        "connected": false
      },
      {
        "key": "history",
        "type": "target",
        "label": "Chat history",
        "valueType": "chat_history",
        "connected": true
      },
      {
        "key": "userChatInput",
        "type": "target",
        "label": "User Question",
        "required": true,
        "valueType": "string",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "finish",
        "label": "Module call ends",
        "description": "Triggered when the module call ends",
        "valueType": "boolean",
        "type": "source",
        "targets": []
      },
      {
        "key": "history",
        "label": "New context",
        "description": "Splice the content of this reply with the historical record and return it as a new context",
        "valueType": "chat_history",
        "type": "source",
        "targets": []
      },
      {
        "key": "answerText",
        "label": "Model reply",
        "description": "Will be triggered after the stream has finished replying",
        "valueType": "string",
        "type": "source",
        "targets": []
      }
    ]
  },
  {
    "moduleId": "ttaqlj",
    "name": "Chat history",
    "flowType": "historyNode",
    "position": {
      "x": 2042.8773179478444,
      "y": 1223.7490126279038
    },
    "inputs": [
      {
        "key": "maxContext",
        "type": "numberInput",
        "label": "Longest number of records",
        "value": 6,
        "min": 0,
        "max": 50,
        "connected": true
      },
      {
        "key": "history",
        "type": "hidden",
        "label": "Chat history",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "history",
        "label": "Chat history",
        "valueType": "chat_history",
        "type": "source",
        "targets": [
          {
            "moduleId": "0g9nm2",
            "key": "history"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "mpdf5a",
    "name": "User question (dialogue entry)",
    "flowType": "questionInput",
    "position": {
      "x": 2070.2293306166525,
      "y": 1545.894939616084
    },
    "inputs": [
      {
        "key": "userChatInput",
        "type": "systemInput",
        "label": "User Question",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "userChatInput",
        "label": "User Question",
        "type": "source",
        "valueType": "string",
        "targets": [
          {
            "moduleId": "0g9nm2",
            "key": "userChatInput"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "fwwrpi",
    "name": "Chat history",
    "flowType": "historyNode",
    "position": {
      "x": 332.108687626388,
      "y": 1234.8883860718956
    },
    "inputs": [
      {
        "key": "maxContext",
        "type": "numberInput",
        "label": "Longest number of records",
        "value": 6,
        "min": 0,
        "max": 50,
        "connected": true
      },
      {
        "key": "history",
        "type": "hidden",
        "label": "Chat history",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "history",
        "label": "Chat history",
        "valueType": "chat_history",
        "type": "source",
        "targets": [
          {
            "moduleId": "y58gru",
            "key": "history"
          }
        ]
      }
    ]
  },
  {
    "moduleId": "y58gru",
    "name": "AI dialogue",
    "flowType": "chatNode",
    "showStatus": true,
    "position": {
      "x": 1401.5232949374868,
      "y": 1328.7953862503282
    },
    "inputs": [
      {
        "key": "switch",
        "type": "target",
        "label": "trigger",
        "valueType": "any",
        "connected": true
      },
      {
        "key": "model",
        "type": "selectChatModel",
        "label": "dialogue model",
        "value": "gpt-3.5-turbo",
        "list": [],
        "required": true,
        "connected": true
      },
      {
        "key": "temperature",
        "type": "slider",
        "label": "temperature",
        "value": 2,
        "min": 0,
        "max": 10,
        "step": 1,
        "markList": [
          {
            "label": "rigorous",
            "value": 0
          },
          {
            "label": "divergent",
            "value": 10
          }
        ],
        "connected": true
      },
      {
        "key": "maxToken",
        "type": "maxToken",
        "label": "Reply limit",
        "value": 2000,
        "min": 100,
        "max": 4000,
        "step": 50,
        "markList": [
          {
            "label": "100",
            "value": 100
          },
          {
            "label": "4000",
            "value": 4000
          }
        ],
        "connected": true
      },
      {
        "key": "systemPrompt",
        "type": "textarea",
        "label": "System prompt word",
        "max": 300,
        "valueType": "string",
        "description": "The guide word fixed by the model. By adjusting the content, you can guide the model chat direction. The content will be fixed at the beginning of the context. Variables can be used, such as {{language}}",
        "placeholder": "The guide word fixed by the model. By adjusting the content, you can guide the model chat direction. The content will be fixed at the beginning of the context. Variables can be used, such as {{language}}",
        "value": "",
        "connected": true
      },
      {
        "key": "quoteTemplate",
        "type": "hidden",
        "label": "Quote content template",
        "valueType": "string",
        "value": "",
        "connected": true
      },
      {
        "key": "quotePrompt",
        "type": "hidden",
        "label": "Quote content prompt words",
        "valueType": "string",
        "value": "",
        "connected": true
      },
      {
        "key": "quoteQA",
        "type": "quoteList",
        "label": "Quoted content",
        "description": "Object array format, structure:\n [{q:'question',a:'answer'}]",
        "valueType": "kb_quote",
        "connected": true
      },
      {
        "key": "history",
        "type": "target",
        "label": "Chat history",
        "valueType": "chat_history",
        "connected": true
      },
      {
        "key": "userChatInput",
        "type": "target",
        "label": "User Question",
        "required": true,
        "valueType": "string",
        "connected": true
      }
    ],
    "outputs": [
      {
        "key": "finish",
        "label": "Module call ends",
        "description": "Triggered when the module call ends",
        "valueType": "boolean",
        "type": "source",
        "targets": []
      },
      {
        "key": "history",
        "label": "New context",
        "description": "Splice the content of this reply with the historical record and return it as a new context",
        "valueType": "chat_history",
        "type": "source",
        "targets": []
      },
      {
        "key": "answerText",
        "label": "Model reply",
        "description": "Will be triggered after the stream has finished replying",
        "valueType": "string",
        "type": "source",
        "targets": []
      }
    ]
  }
]
**expected outcome**
According to the process, if the result is empty, the corresponding module will be triggered.

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/129055843/d2f66c21-0da6-41ae-8185-f55d51ba4536)

**Comment by c121914yu** [comment]
As can be seen from the figure, the knowledge base search has given 2 results, so the branch will not go empty

**Comment by waveboy800** [comment]
This problem is back in version 4.5.2.

**Comment by c121914yu** [comment]
The judgment that the knowledge base is empty is not a semantic judgment, but a recall judgment, and once the data is recalled, the result will not be empty.
