### ISSUE TITLE
when upgrading to v4.5.1 the collectionId may be empty string  

### ISSUE THREAD

**Issue by HJrookie** [labring/FastGPT#443]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**

尝试根据文档升级到 4.5.1 版本时,控制台报错,如下所示  
<img width="911" alt="image" src="https://github.com/labring/FastGPT/assets/27692261/1fff49a3-a6f3-4fd3-9eab-abeb41a6f79d">

定位到相关代码如下

<img width="561" alt="image" src="https://github.com/labring/FastGPT/assets/27692261/e270de35-574e-4ed5-a116-38a0b4d38286">

[具体文件以及对应行](https://github.com/labring/FastGPT/blob/v4.5.1/projects/app/src/pages/api/admin/initv451.ts#L233)

在这一行中,会取 collectionId 作为_id,去 mongo 中查询是否有相应文件, 但是发现当collectionId 为空字符串时, 就会出现 上面控制台中的错误

**复现步骤**
本地代码版本为 v4.5.1, 启动项目,并且 curl 发送请求,即可在控制台看到相关报错  

**预期结果**
预期结果为 可以升级成功,无错误
**相关截图**
见上面的问题描述

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**

When trying to upgrade to version 4.5.1 according to the documentation, the console reports an error as shown below
<img width="911" alt="image" src="https://github.com/labring/FastGPT/assets/27692261/1fff49a3-a6f3-4fd3-9eab-abeb41a6f79d">

Locate the relevant code as follows

<img width="561" alt="image" src="https://github.com/labring/FastGPT/assets/27692261/e270de35-574e-4ed5-a116-38a0b4d38286">


[Specific files and corresponding lines](https://github.com/labring/FastGPT/blob/v4.5.1/projects/app/src/pages/api/admin/initv451.ts#L233)

In this line, collectionId will be used as _id to query whether there is a corresponding file in mongo. However, when the collectionId is an empty string, the error in the console above will appear.

**Steps to reproduce**
The local code version is v4.5.1, start the project, and send a request with curl, you can see the relevant error report in the console

**expected outcome**
The expected result is that the upgrade can be successful without errors.
**Related screenshots**
See problem description above

**Comment by HJrookie** [comment]
因为跨版本升级,所以才出现了这个问题. 按文档一步一步升级不会遇到这个问题  
解决办法就是, 重新 clone 一份代码,添加 `config.local.json` 以及 `.env.local`文件,然后切换代码版本,逐步升级.

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This problem occurs because of cross-version upgrades. You will not encounter this problem if you upgrade step by step according to the documentation.
The solution is to clone the code again, add the `config.local.json` and `.env.local` files, then switch the code version and gradually upgrade.

**Comment by shiliu2023** [comment]
docker部署的升级也有这个问题，如何解决呢？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The upgrade of docker deployment also has this problem. How to solve it?

**Comment by c121914yu** [comment]
跨版本问题，没有执行 4.4.7升级 直接升级了4.5.1。 由于4.5.1字段变化，无法逆向执行4.4.7，需手动阅读4.4.7的升级脚本，并把对应的sql修改成新的字段；或手动将4.5.1修改的字段还原。
