### ISSUE TITLE
Unrecognized request argument supplied: functions (request id: 20231030161628621356161t38p4aKp)

### ISSUE THREAD

**Issue by an-bad-apple** [labring/FastGPT#444]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [✔️ ] 我已确认目前没有类似 issue
- [✔️ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [ ✔️] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ✔️] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ✔️] 私有部署版本

**问题描述**
我使用的 one api 去分发 azure gpt 
目前已经调试 简单对话的 ，但是在调试“问题分类+知识库类型”的时候报错了。
confit.json 配置如下
<img width="400" alt="image" src="https://github.com/labring/FastGPT/assets/26055389/9de44440-853a-4c12-ab55-3550608adc43">
![image](https://github.com/labring/FastGPT/assets/26055389/249f8c88-eb46-4379-9594-a5eabfc0a9b1)
![image](https://github.com/labring/FastGPT/assets/26055389/62d21058-fae9-4a8f-b727-334201097050)

在使用 “问题分类+知识库类型” 回复报错
![Uploading image.png…]()

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [✔️ ] I have confirmed that there is currently no similar issue
- [✔️ ] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.run/docs/intro/)
- [✔️] I used my own key and confirmed that my key can be used normally
- [✔️] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [✔️] Private deployment version

**Problem Description**
I use one api to distribute azure gpt
Currently, simple dialogue has been debugged, but an error was reported when debugging "problem classification + knowledge base type".
confit.json configuration is as follows
<img width="400" alt="image" src="https://github.com/labring/FastGPT/assets/26055389/9de44440-853a-4c12-ab55-3550608adc43">
![image](https://github.com/labring/FastGPT/assets/26055389/249f8c88-eb46-4379-9594-a5eabfc0a9b1)
![image](https://github.com/labring/FastGPT/assets/26055389/62d21058-fae9-4a8f-b727-334201097050)


Reply to an error using "Problem Classification + Knowledge Base Type"
![image](https://github.com/labring/FastGPT/assets/26055389/eac429fa-542f-41b2-84cc-e9ce9485b99c)





**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by an-bad-apple** [comment]
![image](https://github.com/labring/FastGPT/assets/26055389/843e4c75-7338-4ca0-93a4-cd26977e619d)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![image](https://github.com/labring/FastGPT/assets/26055389/843e4c75-7338-4ca0-93a4-cd26977e619d)
