### ISSUE TITLE
When using azure openai, the "reservation laboratory" demo in the operation manual will trigger the content review mechanism.

### ISSUE THREAD

**Issue by an-bad-apple** [labring/FastGPT#446]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ✔️] 我已确认目前没有类似 features
- [ ✔️] 我已确认我已升级到最新版本
- [ ✔️] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ✔️] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我在提问，”预约明天上午10点的会议室“ ，触发了azure的内容审查，然后我找到源码，加了一段模板后，可以避免触发内容审查，希望这里能支持一个自定义提示词模板功能，来规避azure的拦截
在文件projects/app/src/service/moduleDispatch/agent/extract.ts
<img width="619" alt="image" src="https://github.com/labring/FastGPT/assets/26055389/539de192-b52e-49ed-b9ed-397ca47bb873">

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [✔️] I have confirmed that there are currently no similar features
- [✔️] I have confirmed that I have upgraded to the latest version
- [✔️] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [✔️] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
I was asking a question, "Reserve a conference room at 10 a.m. tomorrow", which triggered Azure's content review. Then I found the source code and added a template to avoid triggering content review. I hope it can support a custom prompt word template function. , to circumvent Azure's interception
In the file projects/app/src/service/moduleDispatch/agent/extract.ts
<img width="619" alt="image" src="https://github.com/labring/FastGPT/assets/26055389/539de192-b52e-49ed-b9ed-397ca47bb873">







**Application Scenario**

**Related Examples**

**Comment by c121914yu** [comment]
代码里不允许有特意绕过检测的行为，如果有特殊需要可自行通过http重组输入。
