### ISSUE TITLE
When initializing 451, the log keeps reporting this error. docker version.

### ISSUE THREAD

**Issue by shiliu2023** [labring/FastGPT#449]
Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer

**Comment by HJrookie** [comment]
你得按步骤一步一步升级

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
You have to upgrade step by step

**Comment by HJrookie** [comment]
先看你现在的数据库在哪个版本
然后按文档 一步一步升级
你这个问题的原因在于  collection_id有的是空字符串

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
First check which version your current database is in
Then follow the document to upgrade step by step
The reason for your problem is that collection_id contains empty strings.

**Comment by c121914yu** [comment]
> 先看你现在的数据库在哪个版本
> 然后按文档 一步一步升级
> 你这个问题的原因在于  collection_id有的是空字符串

是的，因为没有执行4.4.7的初始化，4.4.7初始化会重置这个字段。
