### ISSUE TITLE
chat history api

### ISSUE THREAD

**Issue by angular-moon** [labring/FastGPT#450]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
希望增加对话历史记录 API

**应用场景**
通过 API 使用应用时, 希望能够获取到用户和AI的对话历史记录 

**相关示例**
定制UI 或 和其他及时沟通系统整合时需要获取历史聊天记录

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there are currently no similar features
- [ ] I have confirmed that I have upgraded to the latest version
- [ ] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [ ] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
Want to add conversation history API

**Application Scenario**
When using the application through the API, you hope to obtain the conversation history between the user and the AI.

**Related Examples**
When customizing the UI or integrating with other timely communication systems, you need to obtain historical chat records.

**Comment by dq7532183** [comment]
还有在对话日志那,加上导出功能,这也是一个需求

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
There is also a need to add an export function to the conversation log.

**Comment by sdytzjp** [comment]
我也需要聊天记录api

**Comment by c121914yu** [comment]
4.8.12
