### ISSUE TITLE
The model `ERNIE-Bot` does not exist, what is the reason?

### ISSUE THREAD

**Issue by shiliu2023** [labring/FastGPT#451]
已经配置上了，但是还是提示不存在。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It has been configured, but it still says it does not exist.

**Comment by my6777637** [comment]
我也遇到这个问题了，最后解决了吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also encountered this problem, was it finally solved?

**Comment by my6777637** [comment]
> 我也遇到这个问题了，最后解决了吗？

解决了，要改ubaserl和重启容器

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> I also encountered this problem, was it finally solved?

Solved, you need to change ubaserl and restart the container
