### ISSUE TITLE
error: column "collection_id" does not exist

### ISSUE THREAD

**Issue by Nothingness-Void** [labring/FastGPT#452]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.run/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在创建知识库的文件时会有报错 ：“error: column "collection_id" does not exist”
docker-compose logs 的报错为 

```
`fastgpt    | init pg error error: access method "hnsw" does not exist
fastgpt    |     at /app/node_modules/.pnpm/registry.npmmirror.com+pg-pool@3.6.1_pg@8.11.3/node_modules/pg-pool/index.js:45:11
fastgpt    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
fastgpt    |     at async d (/app/projects/app/.next/server/chunks/296.js:82:659) {
fastgpt    |   length: 94,
fastgpt    |   severity: 'ERROR',
fastgpt    |   code: '42704',
fastgpt    |   detail: undefined,
fastgpt    |   hint: undefined,
fastgpt    |   position: undefined,
fastgpt    |   internalPosition: undefined,
fastgpt    |   internalQuery: undefined,
fastgpt    |   where: undefined,
fastgpt    |   schema: undefined,
fastgpt    |   table: undefined,
fastgpt    |   column: undefined,
fastgpt    |   dataType: undefined,
fastgpt    |   constraint: undefined,
fastgpt    |   file: 'indexcmds.c',
fastgpt    |   line: '831',
fastgpt    |   routine: 'DefineIndex'
fastgpt    | }
fastgpt    | {
fastgpt    |   stack: 'error: column "collection_id" does not exist\n' +
fastgpt    |     '    at /app/node_modules/.pnpm/registry.npmmirror.com+pg-pool@3.6.1_pg@8.11.3/node_modules/pg-pool/index.js:45:11\n' +
fastgpt    |     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
fastgpt    |     '    at async R (/app/projects/app/.next/server/chunks/296.js:67:1090)\n' +
fastgpt    |     '    at async m (/app/projects/app/.next/server/pages/api/core/dataset/collection/list.js:1:2970)'
fastgpt    | }
fastgpt    | [ERROR]: 2023-11-03 13:23:11: response error: column "collection_id" does not exist`
```

**复现步骤**
打开fast-gpt 创建知识库 弹出报错
**预期结果**
正常创建知识库
**相关截图**
![image](https://github.com/labring/FastGPT/assets/55913486/0d43270e-5127-4568-bf18-1f313b7d14f4)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README and [project documentation](https://doc.fastgpt.run/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
There will be an error when creating a file in the knowledge base: "error: column "collection_id" does not exist"
The error reported by docker-compose logs is

``fastgpt | init pg error error: access method "hnsw" does not exist
fastgpt | at /app/node_modules/.pnpm/registry.npmmirror.com+pg-pool@3.6.1_pg@8.11.3/node_modules/pg-pool/index.js:45:11
fastgpt | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
fastgpt | at async d (/app/projects/app/.next/server/chunks/296.js:82:659) {
fastgpt | length: 94,
fastgpt | severity: 'ERROR',
fastgpt | code: '42704',
fastgpt | detail: undefined,
fastgpt | hint: undefined,
fastgpt | position: undefined,
fastgpt | internalPosition: undefined,
fastgpt | internalQuery: undefined,
fastgpt | where: undefined,
fastgpt | schema: undefined,
fastgpt | table: undefined,
fastgpt | column: undefined,
fastgpt | dataType: undefined,
fastgpt | constraint: undefined,
fastgpt | file: 'indexcmds.c',
fastgpt | line: '831',
fastgpt | routine: 'DefineIndex'
fastgpt | }
fastgpt | {
fastgpt | stack: 'error: column "collection_id" does not exist\n' +
fastgpt | ' at /app/node_modules/.pnpm/registry.npmmirror.com+pg-pool@3.6.1_pg@8.11.3/node_modules/pg-pool/index.js:45:11\n' +
fastgpt | ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
fastgpt | ' at async R (/app/projects/app/.next/server/chunks/296.js:67:1090)\n' +
fastgpt | ' at async m (/app/projects/app/.next/server/pages/api/core/dataset/collection/list.js:1:2970)'
fastgpt | }
fastgpt | [ERROR]: 2023-11-03 13:23:11: response error: column "collection_id" does not exist``

**Steps to reproduce**
Open fast-gpt and create a knowledge base. An error message will pop up.
**expected outcome**
Create a knowledge base normally
**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/55913486/0d43270e-5127-4568-bf18-1f313b7d14f4)

**Comment by HJrookie** [comment]
看下版本更新文档...

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Check out the version update documentation...
