### ISSUE TITLE
[Feature Request] Availability on selection of models in QA Knowledge Injection

### ISSUE THREAD

**Issue by sebastian0619** [labring/FastGPT#453]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

Add a UI compatibility of a selection box of model selection on QA data injection page. So after the configuration with config.json. Users may, on their will, to decide the quality of these bunches of Q&A should be like, by selecting the more capable models.

**应用场景**

For now, the models selection for QA data injection is to some extent optional but not so user friendly as it requires the edits in _config.json_. For some knowledge, I may deem it easy, so like gpt-3.5 or simply chatglm2 or 3 could do the job. But some knowledge requires more capability of understanding and reasoning, thus gpt-3.5 may not competent for the job, it thereby requires a process of "turn down container - edit config - restart container - data injection - stop container - edit config-restart container" ---- whole lot of things to do.

Kindly arrange to make it possible, thanks!

**相关示例**

**Comment by c121914yu** [comment]
Thanks to your suggestion, we support repository selection of different file preprocessing models in version 4.6, which means QA split can dynamically select models.
