### ISSUE TITLE
[Suggestion] The knowledge base can add Excel export function, especially for generating FAQ

### ISSUE THREAD

**Issue by jinghai** [labring/FastGPT#458]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
知识库可以增加Excel导出功能，由其是对于生成FAQ
**应用场景**
生成FAQ后可能需要专家来确认是否正确
**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there are currently no similar features
- [ ] I have confirmed that I have upgraded to the latest version
- [ ] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [ ] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
The knowledge base can add Excel export function, which is useful for generating FAQs.
**Application Scenario**
After generating the FAQ, experts may be needed to confirm whether it is correct.
**Related Examples**

**Comment by c121914yu** [comment]
知识库卡片页可以导出
