### ISSUE TITLE
[ERROR]: 2023-11-09 06:18:11: response error: Cast to ObjectId failed for value "" (type string) at path "_id" for model "dataset.collections"

### ISSUE THREAD

**Issue by yuanhaishan** [labring/FastGPT#461]
**你的版本**

- [ ] 私有部署版本 4.5.2

**问题描述**
对话:  需要板材吗
回答: 
![image](https://github.com/labring/FastGPT/assets/53658688/84d15c8c-42da-4461-9a9e-74547882b393)

**预期结果**
正常返回输出

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**your version**

- [ ] Private deployment version 4.5.2

**Problem Description**
Dialogue: Do you need plates?
answer: 
![image](https://github.com/labring/FastGPT/assets/53658688/84d15c8c-42da-4461-9a9e-74547882b393)



**expected outcome**
Normal return output

**Comment by yuanhaishan** [comment]
那怎么解决呀 我输入其他中文是可以的 比如你好
![image](https://github.com/labring/FastGPT/assets/53658688/46ad155d-d541-4339-b6c3-51afdceb3b22)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
How to solve it? I can input other Chinese characters, such as hello
![image](https://github.com/labring/FastGPT/assets/53658688/46ad155d-d541-4339-b6c3-51afdceb3b22)

**Comment by c121914yu** [comment]
看着像升级没初始化

**Comment by c121914yu** [comment]
还有问题的话再open
