### ISSUE TITLE
When generating QA, fill in the file topic, but it is not actually used.

### ISSUE THREAD

**Issue by qsimu** [labring/FastGPT#464]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
- [4.5.2 ] 私有部署版本

**问题描述**
生成QA时, 填写文件主题, 实际未被使用
**复现步骤**
添加打印日志
<img width="699" alt="b2d5ec7b24949677a69017aafbd3baf" src="https://github.com/labring/FastGPT/assets/42400779/bc659da1-daee-46ea-9026-f805b31bc169">

<img width="791" alt="fbda228e803536dad0f834bde9e0102" src="https://github.com/labring/FastGPT/assets/42400779/11eba963-6645-4266-9103-327dfcf1b247">

<img width="1384" alt="d61663d029a09643b5f6accdb5d1f0d" src="https://github.com/labring/FastGPT/assets/42400779/9a77a79c-d156-4aa4-ad79-1fc31b1db1a5">

<img width="674" alt="e7e8403421f6196187d0eef21331fa0" src="https://github.com/labring/FastGPT/assets/42400779/d8151935-dae8-44bc-b5a7-000a6ba09216">

**预期结果**
预期结果是, 
我会给你一段文本，它们的主题是 校园卡，学习它们，并整理学习成果，要求为：\n' +
      '1. 提出最多 25 个问题。\n' +
      '4. 按格式返回多个问题和答案:\n' +
      'A1: 答案。\n' +
      '我的文本：..

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**
- [4.5.2] Private deployment version

**Problem Description**
When generating QA, fill in the file subject, but it is not actually used.
**Steps to reproduce**
Add print log
<img width="699" alt="b2d5ec7b24949677a69017aafbd3baf" src="https://github.com/labring/FastGPT/assets/42400779/bc659da1-daee-46ea-9026-f805b31bc169">

<img width="791" alt="fbda228e803536dad0f834bde9e0102" src="https://github.com/labring/FastGPT/assets/42400779/11eba963-6645-4266-9103-327dfcf1b247">

<img width="1384" alt="d61663d029a09643b5f6accdb5d1f0d" src="https://github.com/labring/FastGPT/assets/42400779/9a77a79c-d156-4aa4-ad79-1fc31b1db1a5">

<img width="674" alt="e7e8403421f6196187d0eef21331fa0" src="https://github.com/labring/FastGPT/assets/42400779/d8151935-dae8-44bc-b5a7-000a6ba09216">

**expected outcome**
The expected result is,
I will give you a text, their theme is campus card, study them, and organize the learning results, the requirements are: \n' +
      '1. Ask up to 25 questions. \n' +
      '4. Return multiple questions and answers according to format:\n' +
      'A1: Answer. \n' +
      'My text: ..

**Related screenshots**

**Comment by c121914yu** [comment]
忘记关联了，4.6已修复，
