### ISSUE TITLE
本地启动报错 ==> ReferenceError: window is not defined

### ISSUE THREAD

**Issue by zoupengfeiagent** [labring/FastGPT#465]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**
启动后访问就报错：
ReferenceError: window is not defined
**复现步骤**
启动后访问就报错
**预期结果**

**相关截图**
<img width="1099" alt="image" src="https://github.com/labring/FastGPT/assets/149367880/24d40ba8-5f1a-404f-97c1-23f471e04e90">
<img width="998" alt="image" src="https://github.com/labring/FastGPT/assets/149367880/789a7a90-f1ad-4fb4-bf28-d859868ec191">

**Comment by Yanshang1991** [comment]
把本地nodejs版本改成18，应该就没有问题了。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Change the local nodejs version to 18 and there should be no problem.
