### ISSUE TITLE
Using Alibaba Tongyi’s text-embedding-v1 model, the test matching degree exceeds 1,

### ISSUE THREAD

**Issue by angular-moon** [labring/FastGPT#469]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本
![image](https://github.com/labring/FastGPT/assets/7876335/1fa3c939-0e92-4166-a830-ad68f446e4a3)

**问题描述**
使用 阿里通义的 text-embedding-v1 模型进行搜索测试:
![image](https://github.com/labring/FastGPT/assets/7876335/ca9112ca-f4dc-4a61-b8e2-82ba8c7f1a18)

**复现步骤**

**预期结果**
匹配度应该在 0-1 之间
**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version
![image](https://github.com/labring/FastGPT/assets/7876335/1fa3c939-0e92-4166-a830-ad68f446e4a3)


**Problem Description**
Use Alibaba Tongyi’s text-embedding-v1 model for search testing:
![image](https://github.com/labring/FastGPT/assets/7876335/ca9112ca-f4dc-4a61-b8e2-82ba8c7f1a18)

**Steps to reproduce**

**expected outcome**
Matching should be between 0-1
**Related screenshots**

**Comment by c121914yu** [comment]
向量没有归一化

**Comment by waveboy800** [comment]
> 向量没有归一化

如何归一化？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
>Vectors are not normalized

How to normalize?
