### ISSUE TITLE
[BUG] 纠正回复Failed

### ISSUE THREAD

**Issue by 52cs** [labring/FastGPT#470]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
纠正回复Failed

**复现步骤**
https://vimeo.com/884369537

**预期结果**
纠正回复should success

**相关截图**
https://vimeo.com/884369537

Proposal:
Instead of [creating new knowledge record](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/dataset/detail/components/InputDataModal.tsx#L91) when 纠正回复everytime, we could query the most similar record, if its similar score is larger than a threshold, let's edit it instead of creating a new one.

https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/dataset/detail/components/InputDataModal.tsx#L91

**Comment by c121914yu** [comment]
这是你的操作不正确，你的标注是加入一条新的数据，而不是修改原来的数据，并且未清空上下文中。

**Comment by 52cs** [comment]
1. This is no way to 修改原来的数据 from 纠正回复/Mark.
    When you click 纠正回复/Mark in the first time, you will be guided to 加入一条新的数据.
    When you click 纠正回复/Mark after the first time, you will be guided to modify the data you just added, instead of the original data.
    
        
    https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/dataset/detail/components/InputDataModal.tsx#L370-L372
    ```
                 onClick={handleSubmit(defaultValue.id ? onUpdateData : sureImportData)}
              >
                {defaultValue.id ? '确认变更' : '确认导入'}
    ```
    https://github.com/labring/FastGPT/blob/main/projects/app/src/components/ChatBox/SelectMarkCollection.tsx#L169
    ```
                id: adminMarkData.dataId,
    ```
    https://github.com/labring/FastGPT/blob/main/projects/app/src/components/ChatBox/index.tsx#L664-L679
    ```
                                if (item.adminFeedback) {
                                  setAdminMarkData({
                                    chatItemId: item.dataId,
                                    datasetId: item.adminFeedback.datasetId,
                                    collectionId: item.adminFeedback.collectionId,
                                    dataId: item.adminFeedback.dataId,
                                    q: item.adminFeedback.q || chatHistory[index - 1]?.value || '',
                                    a: item.adminFeedback.a
                                  });
                                } else {
                                  setAdminMarkData({
                                    chatItemId: item.dataId,
                                    q: chatHistory[index - 1]?.value || '',
                                    a: item.value
                                  });
                                }
    ```

2. So, by following your advice, I clicked 纠正回复/Mark and added a new correct data. Then I clear the history(It is best not to do this in the future). And the following is the result. It is still not reliable.
![Screenshot from 2023-11-16 19-38-21](https://github.com/labring/FastGPT/assets/96275757/627ec5f9-8ee1-4580-bd96-df580333c8a6)


As you can see, with the same question, it gives me two different answers. While, the first is my wanted.
