### ISSUE TITLE
In conversation mode: Send any message and report an error Chat API is error or undefined, normal in debug preview state

### ISSUE THREAD

**Issue by goodtpg** [labring/FastGPT#472]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本 ： docker部署 4.6 对接one-api；模型使用百度文心一言

**问题描述**
对话模式下：发送任何消息报错 Chat API is error or undefined ，调试预览状态下正常
**相关截图**

调试预览正常：
![调试预览](https://github.com/labring/FastGPT/assets/19973313/69900c5c-190a-4279-b8f5-39904f8ba563)

沟通对话报错
![对话模式](https://github.com/labring/FastGPT/assets/19973313/18dc9fc5-9af1-4662-8749-141f28d5003f)

FastGtp日志
![fastgtp日志](https://github.com/labring/FastGPT/assets/19973313/f7300d1e-5797-4c29-828e-713261ca5469)

one-api日志截图
![oneapi截图](https://github.com/labring/FastGPT/assets/19973313/bc30b1e1-f11c-4cf0-a3c8-bf69b252610c)

**Comment by c121914yu** [comment]
v4.6似乎没遇到这个问题，之前版本我没注意，可以试试。

**Comment by eyangs** [comment]
我是v4.6也出现相同问题，连接本地模型出错

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I have the same problem with v4.6, and there is an error when connecting to the local model.
