### ISSUE TITLE
[BUG] Same question, different reply

### ISSUE THREAD

**Issue by 52cs** [labring/FastGPT#483]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
Same question, different reply
**复现步骤**
Enter the following link and ask the following question twice.
FastGPT Link:
https://fastgpt.run/chat/share?shareId=xpizlgnp3m6l62t9kyxtnupc&chatId=83owyc2o0wkp
Question:
"FastGPT 的相关项目有哪些？"
**预期结果**
Same question, Same reply.
**相关截图**
![Screenshot from 2023-11-16 19-54-18](https://github.com/labring/FastGPT/assets/96275757/4f794e26-7b22-4826-8109-e42211650bfa)

Related discussion:
https://github.com/labring/FastGPT/issues/470#issuecomment-1814279179

**Comment by c121914yu** [comment]
无效测试，不同上下文

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/d30123ee-f65e-4923-8259-dfa7c06ce9a9)
从你的测试链接中并没有发现异常
