### ISSUE TITLE
How to connect the model of the problem classification module to the local model and use it

### ISSUE THREAD

**Issue by Mr-IT007** [labring/FastGPT#487]
我在config.json文件中把分类模型改成本地部署的百川模型后，使用问题分类模块没有效果

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
After I changed the classification model in the config.json file to the locally deployed Baichuan model, using the problem classification module has no effect

**Comment by c121914yu** [comment]
不支持funtioncall的模型，要设置为false
