### ISSUE TITLE
After upgrading to V4.6.1-alpha version, the chat prompt column "data_id" does not exist

### ISSUE THREAD

**Issue by hbytw** [labring/FastGPT#491]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [xx] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
升级后出现了column "data_id" does not exist
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/43083918/1027968b-8e7a-4848-a5f8-e762125c41c6)
错误日志
get init config error, set default Error: ENOENT: no such file or directory, open '/app/data/config.json'
    at Object.openSync (node:fs:601:3)
    at readFileSync (node:fs:469:35)
    at Y (/app/projects/app/.next/server/chunks/4854.js:12:913)
    at beforeHook (/app/projects/app/.next/server/chunks/2382.js:79:3429)
    at i (/app/projects/app/.next/server/chunks/2382.js:2:1536)
    at y (/app/projects/app/.next/server/chunks/2382.js:79:3373)
    at /app/projects/app/.next/server/chunks/1282.js:1:1475
    at /app/projects/app/.next/server/chunks/1509.js:1:444
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/data/config.json'
}
mongo start connect
mongo connected
【index】Task done
pg connected
default team exist new ObjectId("64fe7883169bdcf566688984")
root user init: { username: 'root', password: 'ytw3921379' }
init pg error error: access method "hnsw" does not exist
    at /app/projects/app/.next/server/chunks/936.js:3:438592
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (/app/projects/app/.next/server/chunks/2382.js:2:3172) {
  length: 94,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'indexcmds.c',
  line: '831',
  routine: 'DefineIndex'
}
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)'
}
[ERROR]: 2023-11-18 09:35:45: sse error: column "data_id" does not exist
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async q (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2464)'
}
[ERROR]: 2023-11-18 09:36:08: sse error: column "data_id" does not exist
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async q (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2464)'
}
[ERROR]: 2023-11-18 09:36:17: sse error: column "data_id" does not exist
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async q (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2464)'
}
[ERROR]: 2023-11-18 09:36:25: sse error: column "data_id" does not exist
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async q (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2464)'
}
[ERROR]: 2023-11-18 09:36:35: sse error: column "data_id" does not exist
{
  stack: 'Error: 503 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20231118173704586138773d4KrW5T4)\n' +
    '    at APIError.generate (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/error.mjs:60:20)\n' +
    '    at OpenAI.makeStatusError (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:244:25)\n' +
    '    at OpenAI.makeRequest (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:283:30)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async m (/app/projects/app/.next/server/chunks/8484.js:44:369)\n' +
    '    at async Object.h [as classifyQuestion] (/app/projects/app/.next/server/chunks/8484.js:39:678)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 2)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async /app/projects/app/.next/server/chunks/1282.js:1:2661'
}
[ERROR]: 2023-11-18 09:37:04: sse error: 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20231118173704586138773d4KrW5T4)
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async /app/projects/app/.next/server/pages/api/core/dataset/searchTest.js:1:2203'
}
[ERROR]: 2023-11-18 09:38:01: response error: column "data_id" does not exist
error: column "data_id" does not exist
    at /app/projects/app/.next/server/chunks/936.js:3:438592
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m (/app/projects/app/.next/server/pages/api/admin/initv46-fix.js:1:2534)
    at async q (/app/projects/app/.next/server/pages/api/admin/initv46-fix.js:1:2433) {
  length: 174,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "modeldata.dataset_id".',
  position: '11',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3656',
  routine: 'errorMissingColumn'
}
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async m (/app/projects/app/.next/server/pages/api/admin/initv46-fix.js:1:2534)\n' +
    '    at async q (/app/projects/app/.next/server/pages/api/admin/initv46-fix.js:1:2433)'
}
[ERROR]: 2023-11-18 09:40:40: response error: column "data_id" does not exist
{
  stack: 'Error: 503 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20231118174100544291493Kvwf22Hn)\n' +
    '    at APIError.generate (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/error.mjs:60:20)\n' +
    '    at OpenAI.makeStatusError (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:244:25)\n' +
    '    at OpenAI.makeRequest (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:283:30)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async m (/app/projects/app/.next/server/chunks/8484.js:44:369)\n' +
    '    at async Object.h [as classifyQuestion] (/app/projects/app/.next/server/chunks/8484.js:39:678)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 2)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async /app/projects/app/.next/server/chunks/1282.js:1:2661'
}
[ERROR]: 2023-11-18 09:41:00: sse error: 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20231118174100544291493Kvwf22Hn)
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async /app/projects/app/.next/server/chunks/1282.js:1:2661'
}
[ERROR]: 2023-11-18 09:41:13: sse error: column "data_id" does not exist
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async /app/projects/app/.next/server/chunks/1282.js:1:2661'
}
[ERROR]: 2023-11-18 09:41:24: sse error: column "data_id" does not exist
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async /app/projects/app/.next/server/chunks/1282.js:1:2661'
}
[ERROR]: 2023-11-18 09:44:53: sse error: column "data_id" does not exist
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async /app/projects/app/.next/server/chunks/1282.js:1:2661'
}
[ERROR]: 2023-11-18 09:45:06: sse error: column "data_id" does not exist
{
  stack: 'error: column "data_id" does not exist\n' +
    '    at /app/projects/app/.next/server/chunks/936.js:3:438592\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async f (/app/projects/app/.next/server/chunks/2382.js:74:2993)\n' +
    '    at async Object.u [as datasetSearchNode] (/app/projects/app/.next/server/chunks/8484.js:50:2870)\n' +
    '    at async O (/app/projects/app/.next/server/chunks/8484.js:50:5066)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:6134)\n' +
    '    at async q (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2464)'
}
[ERROR]: 2023-11-18 09:59:36: sse error: column "data_id" does not exist

**Comment by zhukunpenglinyutong** [comment]
遇到相同问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Encountered the same problem

**Comment by c121914yu** [comment]
看文档

**Comment by c121914yu** [comment]
https://doc.fastgpt.in/docs/installation/upgrading/46/
每个升级都有可能要初始化，请关注文档。

**Comment by hbytw** [comment]
初始化后问题解决，4.6每次更新都需要初始化吗？

**Comment by wxttt** [comment]
> 初始化后问题解决，4.6每次更新都需要初始化吗？

hi 老哥 遇到相同的问题，请问你这边解决了么？

**Comment by hbytw** [comment]
按说明初始化一下即可。





苑天伟
***@***.***







                       
原始邮件
                       
                     

发件人："wxttt"< ***@***.*** &gt;;

发件时间：2024/1/16 12:34

收件人："labring/FastGPT"< ***@***.*** &gt;;

抄送人："hbytw"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [labring/FastGPT] After upgrading to V4.6.1-alpha version, thechat prompt column "data_id" does not exist (Issue #491)




  
初始化后问题解决，4.6每次更新都需要初始化吗？
  
hi 老哥 遇到相同的问题，请问你这边解决了么？
