### ISSUE TITLE
sse error: Connection error.

### ISSUE THREAD

**Issue by panliang5020** [labring/FastGPT#499]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.6.1
- [ ] 公有云版本
- [  x ] 私有部署版本

**问题描述**
        对话调用报错

**复现步骤**
         服务部署成功,测试与gpt-3.5对话是 出现错误,connecttion error 

**预期结果**
       正常交流
**相关截图**
![image](https://github.com/labring/FastGPT/assets/51695693/8299c892-d6cd-42fd-be62-034ffe8d99d3)
![image](https://github.com/labring/FastGPT/assets/51695693/1aad6148-2c2f-4527-bb43-6fa838984d59)

**Comment by panliang5020** [comment]
配置文件:
# 非 host 版本, 不使用本机代理
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5432:5432
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports: # 生产环境建议不要暴露
      - 27017:27017
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
    ports:
      - 5008:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      # root 密码，用户名为: root
      - DEFAULT_ROOT_PSW=1234
      # 中转地址，如果是用官方号，不需要管
      - OPENAI_BASE_URL=https://rndzchmkguom.cloud.sealos.io/openai/v1
      #- OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-****************************************************
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      # mongo 配置，不需要改. 如果连不上，可能需要去掉 ?authSource=admin
      - MONGODB_URI=mongodb://username:password@mongo:27017/fastgpt?authSource=admin
      - PG_URL=postgresql://username:password@pg:5432/postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fastgpt:

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Configuration file:
# Non-host version, does not use native proxy
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # Alibaba Cloud
    container_name:pg
    restart: always
    ports: # It is recommended not to expose in production environment
      - 5432:5432
    networks:
      -fastgpt
    environment:
      # The configuration here only takes effect on the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image:mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # Alibaba Cloud
    container_name: mongo
    restart: always
    ports: # It is recommended not to expose in production environment
      - 27017:27017
    networks:
      -fastgpt
    environment:
      # The configuration here only takes effect on the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # Alibaba Cloud
    ports:
      - 5008:3000
    networks:
      -fastgpt
    depends_on:
      -mongo
      -pg
    restart: always
    environment:
      # root password, username: root
      - DEFAULT_ROOT_PSW=1234
      # Transit address, if you use an official account, you don’t need to worry about it.
      - OPENAI_BASE_URL=https://rndzchmkguom.cloud.sealos.io/openai/v1
      #- OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-************************************************ *******
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      # Mongo configuration, no need to change. If you can't connect, you may need to remove ?authSource=admin
      - MONGODB_URI=mongodb://username:password@mongo:27017/fastgpt?authSource=admin
      - PG_URL=postgresql://username:password@pg:5432/postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fastgpt:

**Comment by c121914yu** [comment]
上游错误，自行处理上游问题，测试结果以curl stream模式成功为准

**Comment by c121914yu** [comment]
长时间未响应，暂时关闭。

**Comment by willwilling** [comment]
你的问题解决了吗？ 怎么解决的？

**Comment by willwilling** [comment]
> 上游错误，自行处理上游问题，测试结果以curl stream模式成功为准

请问下这个是怎么看出来是上游问题的
这个curl stream又是啥意思？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Upstream errors, handle upstream problems by yourself, the test results are subject to the success of curl stream mode

Please tell me how you can tell this is an upstream problem.
What does this curl stream mean?
