### ISSUE TITLE
问题分类模块的functioncall有对应的解析函数模板吗，类似qwen openai_api.py文件中的parse_messages函数

### ISSUE THREAD

**Issue by Mr-IT007** [labring/FastGPT#502]
**相关截图**
![parse](https://github.com/labring/FastGPT/assets/39551480/f0b4d8a1-1f9e-495c-8b85-2c66ff422b11)

**Comment by c121914yu** [comment]
projects/app/src/service/moduleDispatch/agent/classifyQuestion.ts
