### ISSUE TITLE
Private cloud deployment Create knowledge base Prompt modeldata does not exist

### ISSUE THREAD

**Issue by 157677678** [labring/FastGPT#503]
私有云部署 最新版

 创建知识库 提示 modeldata 不存在
![image](https://github.com/labring/FastGPT/assets/67778969/046cc8ff-1f66-4970-9717-959b75697143)
公网的没有这个问题 公网的有什么新变化吗？

**Comment by c121914yu** [comment]
数据库启动失败或者版本不对，看开头的日志会有提示

**Comment by AlexBenjarmin** [comment]
请问解决了吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Has it been resolved?

**Comment by 157677678** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> Has it been resolved?

重装了 好像又行了 不过有其他的问题了…… 我再查查吧
