### ISSUE TITLE
In a chat conversation, the information response is interrupted, but the log shows a complete response.

### ISSUE THREAD

**Issue by jiangheng88** [labring/FastGPT#504]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
In a chat conversation, the information response is interrupted, but the log shows a complete response.

**复现步骤**

**预期结果**
希望不要出现中断情况
**相关截图**
![6150b9c0cd8d65597308a8120def8dc](https://github.com/labring/FastGPT/assets/31200936/97cf5bc7-1ce4-47f7-b51e-a71e04acfcc7)

**Comment by Pnut-GGG** [comment]
不是网关的问题，应该是前端的问题，http stream流的内容是完整的，调整页面窗口大小（由桌面端改为移动端，重新加载js，计算布局后）显示正常。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It's not a gateway problem, it should be a front-end problem. The content of the http stream is complete, and the page window size is adjusted (from desktop to mobile, js is reloaded, and the layout is calculated) and the display is normal.

**Comment by c121914yu** [comment]
> 不是网关的问题，应该是前端的问题，http stream流的内容是完整的，调整页面窗口大小（由桌面端改为移动端，重新加载js，计算布局后）显示正常。

前端与服务器之间也有网关。不是只有服务器与api接口有。

**Comment by c121914yu** [comment]
近期似乎没有发现该问题，暂时关闭，后续继续关注网络问题。
