### ISSUE TITLE
dataset export failed

### ISSUE THREAD

**Issue by ws02589111** [labring/FastGPT#505]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

docker with v4.6.1 image 
bump from v4.6

**问题描述**
export dataset failed

**复现步骤**
export any dataset 
**预期结果**
download csv success
**相关截图**
![image](https://github.com/labring/FastGPT/assets/10301545/7f674b66-7a12-4277-98f0-05850313f38f)

logs from docker 
![image](https://github.com/labring/FastGPT/assets/10301545/24f1f06a-62f6-41fa-bdd8-9c8da3a5f3e7)

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/f8e05e70-4758-4af7-8778-3a6f60736445)
引用GPT回答
