### ISSUE TITLE
Is it possible to access third-party elasticsearch library or database?

### ISSUE THREAD

**Issue by shenmadouyaowen** [labring/FastGPT#507]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 features
- [x ] 我已确认我已升级到最新版本
- [x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
使用其他工具构建了elasticsearch，是否可以加一个第三方向量库对接？
**应用场景**
可以对接其他的向量库或者数据库
**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x ] I have confirmed that I have upgraded to the latest version
- [x ] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
If you use other tools to build elasticsearch, can you add a third-party vector library to connect it?
**Application Scenario**
Can be connected to other vector libraries or databases
**Related Examples**

**Comment by c121914yu** [comment]
http模块可以对接外部数据

**Comment by shenmadouyaowen** [comment]
> http模块可以对接外部数据

有对接实列么？

**Comment by c121914yu** [comment]
> > http模块可以对接外部数据
> 
> 有对接实列么？

https://doc.fastgpt.in/docs/workflow/examples/lab_appointment/

**Comment by shenmadouyaowen** [comment]
> > > http模块可以对接外部数据
> > 
> > 
> > 有对接实列么？
> 
> https://doc.fastgpt.in/docs/workflow/examples/lab_appointment/

Thank you

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > The http module can connect to external data
>>
>>
> > Is there any docking example?
>
> https://doc.fastgpt.in/docs/workflow/examples/lab_appointment/

Thank you
