### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by he-bowen** [labring/FastGPT#512]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
1.应用和聊天界面增加分类功能。或者可以增加自定义分组分类功能
2.应用中心增加回收站功能
3.应用免登陆分享增加关闭 聊天记录

**应用场景**
1. 分组细致，整体效果不凌乱
2. 避免误删除导致编排丢失
3. 多个终端访问可保护用户隐私

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
1. Add classification functions to application and chat interfaces. Or you can add custom grouping and classification functions
2. Add recycle bin function to the application center
3. The application can share without login and close the chat history.

**Application Scenario**
1. The grouping is meticulous and the overall effect is not messy.
2. Avoid accidental deletion leading to loss of arrangement
3. Multiple terminal access protects user privacy

**Related Examples**

**Comment by c121914yu** [comment]
聊天分类和回收短期不会考虑。
应用分类在p2计划中
应用免登陆分享增加关闭聊天记录这个并不是很理解，因为历史记录是存本地的，仅分享人与使用的人会看到。

**Comment by he-bowen** [comment]
> 聊天分类和回收短期不会考虑。 应用分类在p2计划中 应用免登陆分享增加关闭聊天记录这个并不是很理解，因为历史记录是存本地的，仅分享人与使用的人会看到。

好的，感谢您的回复。

应用免登陆分享增加关闭聊天记录主要为：一个分享链接给到多个用户使用，多个用户之间可以看到相互的聊天记录。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Chat classification and recycling will not be considered in the short term. The application classification is in the p2 plan. The application does not need to be logged in to share, add and turn off chat records. This is not very understandable, because the history records are saved locally and only the people who share them and the people who use them can see them.

OK, thanks for your reply.

The application's login-free sharing adds the ability to turn off chat records mainly for the following reasons: one shared link can be used by multiple users, and multiple users can see each other's chat records.
