### ISSUE TITLE
构建知识库出错： column “data_id” of relation "modeldata"  does not exist

### ISSUE THREAD

**Issue by eyangs** [labring/FastGPT#513]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ √] 我已确认目前没有类似 issue
- [ √] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ √] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本** V4.6.1

- [ ] 公有云版本
- [√ ] 私有部署版本

**问题描述**
构建知识库出现错误
**复现步骤**

**预期结果**

**相关截图**
系统界面
![image](https://github.com/labring/FastGPT/assets/644198/cb851b10-e16d-4983-805a-0955c0eb251e)

日志：
![image](https://github.com/labring/FastGPT/assets/644198/093db27e-df89-4ac5-8753-e1428328a993)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [√] I have confirmed that there is currently no similar issue
- [√] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [√] I used my own key and confirmed that my key can be used normally
- [√] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [√] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**Your version** V4.6.1

- [ ] Public cloud version
- [√ ] Private deployment version

**Problem Description**
An error occurred while building the knowledge base
**Steps to reproduce**

**expected outcome**

**Related screenshots**
system interface
![image](https://github.com/labring/FastGPT/assets/644198/cb851b10-e16d-4983-805a-0955c0eb251e)

log:
![image](https://github.com/labring/FastGPT/assets/644198/093db27e-df89-4ac5-8753-e1428328a993)

**Comment by Mr-IT007** [comment]
遇到相同问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Encountered the same problem

**Comment by Mr-IT007** [comment]
> **例行检查**
> 
> * [ √] 我已确认目前没有类似 issue
> * [ √] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
> * [ √] 我使用了自己的 key，并确认我的 key 是可正常使用的
> * [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
> * [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本** V4.6.1
> 
> * [ ]  公有云版本
> * [√ ] 私有部署版本
> 
> **问题描述** 构建知识库出现错误 **复现步骤**
> 
> **预期结果**
> 
> **相关截图** 系统界面 ![image](https://user-images.githubusercontent.com/644198/285374796-cb851b10-e16d-4983-805a-0955c0eb251e.png)
> 
> 日志： ![image](https://user-images.githubusercontent.com/644198/285374646-093db27e-df89-4ac5-8753-e1428328a993.png)

数据库有问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> **Routine inspection**
>
> * [√] I have confirmed that there is currently no similar issue
> * [√] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.in/docs/intro/)
> * [√] I used my own key and confirmed that my key can be used normally
> * [√] I understand and am willing to follow up on this issue, assist in testing and provide feedback
> * [√] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**
>
> **your version** V4.6.1
>
> * [ ] Public cloud version
> * [√ ] Private deployment version
>
> **Problem Description** An error occurred while building the knowledge base **Reproduction Steps**
>
> **Expected results**
>
> **Related screenshots** System interface ![image](https://user-images.githubusercontent.com/644198/285374796-cb851b10-e16d-4983-805a-0955c0eb251e.png)
>
> Log: ![image](https://user-images.githubusercontent.com/644198/285374646-093db27e-df89-4ac5-8753-e1428328a993.png)

There is a problem with the database

**Comment by c121914yu** [comment]
升级未初始化，参考升级文档。

**Comment by liuhuapiaoyuan** [comment]
按照文档初始化了 还是不行啊

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I initialized it according to the documentation, but it still doesn’t work.
