### ISSUE TITLE
Unable to specify content reply after content extraction

### ISSUE THREAD

**Issue by vary** [labring/FastGPT#514]
**例行检查**

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [x] 私有部署版本

**问题描述**
新建一个应用，把用户问题提取内容，无法把提取后的内容传递给指定回复，如图，指定回复为空，但是已经提取到内容
**复现步骤**
新建一个应用，把用户问题提取内容然后再指向指定回复
**预期结果**
能够改变指定回复的内容
**相关截图**
<img width="1501" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/0fd03426-bcd8-4bbe-afd9-34e86ec6bb44">
<img width="1151" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/db65105d-a669-49cc-b379-60fe2a0f0313">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

- [x] I have confirmed that there is currently no similar issue
- [
- [ ] I used my own key and confirmed that my key can be used normally.
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [x] Public cloud version
- [ ] private deployment version

**Problem Description**
Create a new application to extract content from user questions. The extracted content cannot be passed to the specified reply, as shown in the figure. The specified reply is empty, but the content has been extracted.
**Steps to reproduce**
Create a new application, extract the content of user questions and then point to the specified reply.
**expected outcome**
Ability to change the content of a specified reply
**Related screenshots**
<img width="1501" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/0fd03426-bcd8-4bbe-afd9-34e86ec6bb44">
<img width="1151" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/db65105d-a669-49cc-b379-60fe2a0f0313">

**Comment by c121914yu** [comment]
这个版本的执行机制会有从上往下的顺序，如果把完全提取接入到触发器，提取模块会先输出字段完全提取打到触发器里，从而让指定回复输出空内容。下面的提取结果再输出时候，runtime已经结束，不会再输出任何内容。 
可以等4.6.2-alpha版本试试，或者只连接完整提取结果

**Comment by vary** [comment]
感谢，不连接触发器确实可以了

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks, it works without connecting the trigger
