### ISSUE TITLE
[Question] Is there any chance to introduce ChatGLM3 model? Or it's possible to talk to the modle now?

### ISSUE THREAD

**Issue by haroldrandom** [labring/FastGPT#520]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [ ] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [ ] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**

**Application Scenario**

**Related Examples**

**Comment by uestcsongtaoli** [comment]
ChaGLM3可以私有化部署。
当前的项目如果结合OneAPI，将OneAPI当做模型的注册中心，只需要将你的模型部署成兼容OpenAI API兼容的接口，理论上可以接入任意模型。

ChaGLM3 can be privately deployed. 
If the current project integrates with OneAPI, using OneAPI as the model registry, you only need to deploy your model as an interface compatible with the OpenAI API. In theory, this allows integration with any model.
