### ISSUE TITLE
The maximum chat record and parameter length can be customized

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#522]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
你好，可否将最大聊天记录的50条自定义到config，这样可根据用户需求调配。
参数的输入长度也是。
固定50和100感觉太短了，许多AI也陆续支持更长的上下文
<img width="320" alt="Screenshot 2023-11-28 at 07 17 05" src="https://github.com/labring/FastGPT/assets/36452456/32aea31d-c1e5-4175-8d2b-86390180d683">
<img width="806" alt="Screenshot 2023-11-28 at 07 17 17" src="https://github.com/labring/FastGPT/assets/36452456/8b84251f-8858-4cd2-b2fa-21d52dc589bb">

**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
考虑这个数值的主要原因是数据库的负担，例如，用户仅选择了一个4k的模型，但是用了100条历史记录，实际上每次只会用到10来条，而对数据库的负担则是成倍的。
并且在按量计费中，99%用户并不会选择超过20条的历史记录。
4.6.2中，我们临时增加了这个值到了100。
