### ISSUE TITLE
Connect ECONNREFUSED 172.19.0.2:15432 appears when deleting the knowledge base

### ISSUE THREAD

**Issue by ChanLicher** [labring/FastGPT#527]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
我使用的是 docker 本地部署，删除知识库的时候出现 connect ECONNREFUSED 172.19.0.2:15432
**复现步骤**

**预期结果**

**相关截图**
![Quicker_20231129_092834](https://github.com/labring/FastGPT/assets/55681496/c6c638cc-dc90-47a3-8dad-bc8a23c5dd4b)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
I am using docker for local deployment. When deleting the knowledge base, connect ECONNREFUSED 172.19.0.2:15432 appears.
**Steps to reproduce**

**expected outcome**

**Related screenshots**
![Quicker_20231129_092834](https://github.com/labring/FastGPT/assets/55681496/c6c638cc-dc90-47a3-8dad-bc8a23c5dd4b)

**Comment by c121914yu** [comment]
数据库没连上
