### ISSUE TITLE
调用会话接口时 出现 Cast to Number failed for value "NaN" (type number) at path "usage"错误

### ISSUE THREAD

**Issue by xiaofei5246092** [labring/FastGPT#528]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**
调用会话接口，调用可以完成，但后台会出现类型错误
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/30060308/44654f95-af24-4cb4-b1fe-cc9d44c8cb3d)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Call the session interface, the call can be completed, but a type error will occur in the background
**Steps to reproduce**

**expected outcome**

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/30060308/44654f95-af24-4cb4-b1fe-cc9d44c8cb3d)
