### ISSUE TITLE
APPID changed?

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#530]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
RT
docs上找不到相关信息，只在源码中找到一个从`req.body`处获取的逻辑

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
RT
I couldn't find relevant information in the docs. I only found a logic obtained from `req.body` in the source code.

**Steps to reproduce**

**expected outcome**

**Related screenshots**
Has the API input method of

**Comment by bincooo** [comment]
哦，好想又行了

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Oh, I really want to do it again
