### ISSUE TITLE
Knowledge base export problem

### ISSUE THREAD

**Issue by zutomayo11** [labring/FastGPT#535]
**知识库导出问题**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**导出知识库显示{"code":403statusText:"unAuthorization"message:"凭证错误"data:null}**

**复现步骤**

**预期结果**

**相关截图**
![WeChate35f256e612c618d1aeece3addbce89f](https://github.com/labring/FastGPT/assets/127024045/8ec08910-0127-4da5-8fe6-92e89b18e03f)

**Comment by xsfhacg** [comment]
我也是，界面上显示导出失败，无法下载，请联系你的组织，日志也报凭证错误

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Me too. The interface shows that the export failed and cannot be downloaded. Please contact your organization. The log also reports a credential error.

**Comment by c121914yu** [comment]
ip模式部署的不支持导出，需要有ssl证书

**Comment by xsfhacg** [comment]
我是在官网https://fastgpt.run/上导出的，导出失败
![QQ截图20231219133649](https://github.com/labring/FastGPT/assets/41864243/470456d8-e1c2-4d1b-adaa-77427dcf8999)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I exported it on the official website https://fastgpt.run/, but the export failed.
![QQ screenshot 20231219133649](https://github.com/labring/FastGPT/assets/41864243/470456d8-e1c2-4d1b-adaa-77427dcf8999)

**Comment by c121914yu** [comment]
> 我是在官网[https://fastgpt.run/上导出的，导出失败](https://fastgpt.run/%E4%B8%8A%E5%AF%BC%E5%87%BA%E7%9A%84%EF%BC%8C%E5%AF%BC%E5%87%BA%E5%A4%B1%E8%B4%A5) ![QQ截图20231219133649](https://private-user-images.githubusercontent.com/41864243/291486027-470456d8-e1c2-4d1b-adaa-77427dcf8999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjQ4MjIsIm5iZiI6MTcwMjk2NDUyMiwicGF0aCI6Ii80MTg2NDI0My8yOTE0ODYwMjctNDcwNDU2ZDgtZTFjMi00ZDFiLWFkYWEtNzc0MjdkY2Y4OTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA1NDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MTI1MzUxNjhkYmEzNmE0OTE5OTE4ZTc3MWRjYTM0NDJhYzFjMjgwNWQ4ZDAxZDVjZDY4ZDNlNDI0MmZiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7BHey9EyuslWNbK-2lDb6D_3rXOHddtBs7YoIVgodjw)

是否可以提供更多信息，用户名或具体的知识库 id。
在 50 组测试数据里没法复现这个问题，可能则与浏览器环境有关。

**Comment by xsfhacg** [comment]
id：657955dbe2a57ff2b8c91889

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
So: 657,955 Dubai, 1889

**Comment by c121914yu** [comment]
> id：657955dbe2a57ff2b8c91889

![image](https://github.com/labring/FastGPT/assets/50446880/b33698ea-d16e-409e-994d-42d9547a8bb7)

我这边是可以导出的，估计就是浏览器环境问题，可能某些原因导致你的环境不支持cookie传输。

**Comment by xsfhacg** [comment]
Browser is edge，

> > id：657955dbe2a57ff2b8c91889
> 
> ![image](https://private-user-images.githubusercontent.com/50446880/291494390-b33698ea-d16e-409e-994d-42d9547a8bb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjcyNDgsIm5iZiI6MTcwMjk2Njk0OCwicGF0aCI6Ii81MDQ0Njg4MC8yOTE0OTQzOTAtYjMzNjk4ZWEtZDE2ZS00MDllLTk5NGQtNDJkOTU0N2E4YmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA2MjIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOWQ1NzY1ZTIxYjcwMzE2OWFjOGFjODQ2MDcyZDY1MjBmZjNmNGM5NDVjYzk4N2E3NWIzZmM3NTU2MzAwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DlI2UDPcRi6yE98C4JjrMaw6DAveqXQ0uxDYh0gnsWk)
> 
> 我这边是可以导出的，估计就是浏览器环境问题，可能某些原因导致你的环境不支持cookie传输。

好的多谢，我20分钟后去换个浏览器试下

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Browser is edge,

> > id: 657955dbe2a57ff2b8c91889
>
> ![image](https://private-user-images.githubusercontent.com/50446880/291494390-b33698ea-d16e-409e-994d-42d9547a8bb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ naXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjcyNDgsIm5iZiI6MTcwMjk2Njk0OCwicGF0aCI6Ii81MDQ0Njg4MC8yOTE0 OTQzOTAtYjMzNjk4ZWEtZDE2ZS00MDllLTk5NGQtNDJkOTU0N2E4YmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJ GMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA2MjIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOWQ1NzY1ZTIx YjcwMzE2OWFjOGFjODQ2MDcyZDY1MjBmZjNmNGM5NDVjYzk4N2E3NWIzZmM3NTU2MzAwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0. DlI2UDPcRi6yE98C4JjrMaw6DAveqXQ0uxDYh0gnsWk)
>
> I can export it here. It is probably a browser environment problem. There may be some reasons why your environment does not support cookie transmission.

Okay, thank you. I'll try another browser in 20 minutes.

**Comment by xsfhacg** [comment]
之前是edge浏览器，现在我换了谷歌浏览器试了下也不行，是不是我账号的问题（账号：git-xsfhacg）
![QQ截图20231219150546](https://github.com/labring/FastGPT/assets/41864243/d97e786c-8606-458e-92bd-b75444e7e54b)

**Comment by xsfhacg** [comment]
大佬麻烦帮我再看下，qq浏览器、edge、google都试了无法导出，github账号和邮箱账号也分别试了都不行
![Uploading QQ截图20231221094359.png…]()

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Sir, please help me take another look. I have tried QQ browser, edge, and google and it cannot be exported. I have also tried the github account and the email account separately and it still doesn't work.
![Uploading QQ screenshot 20231221094359.png…]()

**Comment by Samge0** [comment]
same problem

**Comment by fishgotfamous** [comment]
same problem

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
same problem

**Comment by c121914yu** [comment]
目前看来只要是 https，并且浏览器允许 cookie，都可以导出。

**Comment by stephenlzc** [comment]
我已经注册好了SSL,但是用https访问不了，请问我需要修改哪里啊？

> 目前看来只要是 https，并且浏览器允许 cookie，都可以导出。
