### ISSUE TITLE
When importing a docx file in version 4.6.2, if it contains a background image, the import will not report an error and keep spinning.

### ISSUE THREAD

**Issue by TheChalice** [labring/FastGPT#536]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
在4.6.2版本中导入docx文件如果里面包含背景图，导入不报错一直转圈
**复现步骤**
点击知识库，导入文件，导入test.docx,显示解析中一直解析，把docx的背景图删除后导入正常
**预期结果**
希望可以正常报错，谢谢
**相关截图**
[test.docx](https://github.com/labring/FastGPT/files/13521401/test.docx)

**Comment by leoterry-ulrica** [comment]
@c121914yu 这个问题出现的频率很高，希望能够解决。

**Comment by c121914yu** [comment]
是否有相关测试文件，我的测试文件中并不会出现这个问题。

**Comment by c121914yu** [comment]
> 是否有相关测试文件，我的测试文件中并不会出现这个问题。

ye 看到测试文件了
