### ISSUE TITLE
Knowledge base performs OCR recognition on image documents

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#538]
现在只要上传的文档里面有图片，则在知识库端上传文档的时候会一直处于【解析中...】，希望可以增加OCR识别。
![b4291a8fe43914d0649794f8c2578f9](https://github.com/labring/FastGPT/assets/18339429/47364eb3-fed4-4219-8dd7-fc971dfc1e9e)

**Comment by c121914yu** [comment]
ocr估计还要很长时间，这个读取问题已经修复 https://github.com/labring/FastGPT/compare/main...c121914yu:FastGPT:main
