### ISSUE TITLE
The keywords extracted by the text extraction module are garbled, causing the input and output of the http module to be garbled.

### ISSUE THREAD

**Issue by haojing8312** [labring/FastGPT#540]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
v4.6.2，通过sealos一键部署。
参考高级编排中实现谷歌联网搜索，在测试时发现文本提取的内容是乱码https://doc.fastgpt.run/docs/workflow/examples/google_search/

**复现步骤**
参考高级编码-编排示例-联网GPT，导入编排配置，保存进行测试对话，查看完整响应
**预期结果**
searchKey中应该是“呼和浩特天气”
**相关截图**
![image](https://github.com/labring/FastGPT/assets/39109151/1bc92b86-a2b9-4d40-bfc4-0cbdea29a341)
![image](https://github.com/labring/FastGPT/assets/39109151/659ab222-73e7-422d-b3eb-e891624741b4)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
v4.6.2, one-click deployment through sealos.
Refer to the implementation of Google Internet search in Advanced Orchestration. During the test, it was found that the text extracted was garbled https://doc.fastgpt.run/docs/workflow/examples/google_search/

**Steps to reproduce**
Refer to Advanced Coding - Arrangement Examples - Networked GPT, import the orchestration configuration, save the test session, and view the complete response.
**expected outcome**
The searchKey should be "Hohhot weather"
**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/39109151/1bc92b86-a2b9-4d40-bfc4-0cbdea29a341)
![image](https://github.com/labring/FastGPT/assets/39109151/659ab222-73e7-422d-b3eb-e891624741b4)

**Comment by haojing8312** [comment]
已解决，将文本提取模型从turbo-1106修改为trubo即可，建议官方修改config.json中默认模型

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![image](https://github.com/labring/FastGPT/assets/39109151/28832757-5c74-468e-b4b6-daa0b2de75f9)
