### ISSUE TITLE
Are there any plans to support other vector repositories, such as faiss, milvus?

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#544]
是否有计划支持其它向量存储库，如：faiss、milvus？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Are there any plans to support other vector repositories such as faiss, milvus?

**Comment by c121914yu** [comment]
> > milvus 有考虑，但是优先级不高，并没有太大的需求。
> 
> 请问一下你们基于pg vector存储向量，是基于哪些优势考虑呢？

成本，性能，稳定性与易用性。

**Comment by c121914yu** [comment]
已支持，忘记关联
