### ISSUE TITLE
Advanced orchestration is expected to support python code calls

### ISSUE THREAD

**Issue by yinggoga** [labring/FastGPT#552]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
高级编排期望支持python代码调用

**应用场景**
高级编排期望支持python代码调用，这样相比于http调用更加灵活

**相关示例**
微软的prompt flow已支持python代码调用
https://learn.microsoft.com/zh-cn/azure/machine-learning/prompt-flow/tools-reference/python-tool?view=azureml-api-2
![image](https://github.com/labring/FastGPT/assets/27919234/7142ed5e-400f-4a73-af78-09458d043292)<br>
![image](https://github.com/labring/FastGPT/assets/27919234/2e4274ac-27be-411b-af04-025ffb699eb7)

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8.2 js sandbox
