### ISSUE TITLE
Vector model similarity problem

### ISSUE THREAD

**Issue by HDlonger** [labring/FastGPT#560]
请问为什么我使用m3e模型进行知识库搜索测试，得到的结果相似度高达500多，正常应该在1以下，而且并没有按相似排序
![image](https://github.com/labring/FastGPT/assets/93592432/61db500b-0e77-4371-92ec-c0e8e5890b39)

**Comment by c121914yu** [comment]
未归一化，模型问题。去对应模型社区找解决方案

**Comment by HDlonger** [comment]
归一化可以解决相似性排序乱的问题吗，明明一样的问题，匹配到的答案相似度排序排在后面

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Can normalization solve the problem of chaotic similarity ranking? It is obviously the same question, but the matched answers are ranked lower in similarity ranking.
