### ISSUE TITLE
Failed to embed the web page into the halo blog system and call it

### ISSUE THREAD

**Issue by LiberatorHg** [labring/FastGPT#561]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
网页嵌入到halo博客系统中调用失败，直接在halo博客系统后台全局head里注入代码

**复现步骤**
在halo博客系统后台全局head里注入代码
![image](https://github.com/labring/FastGPT/assets/52238701/8d47e4cc-6e1b-4cb4-95c7-21415abf9e04)

**预期结果**
试过隔壁dify的嵌入就完美支持，但是论知识库还是本项目好用，希望有什么办法可以嵌入进halo博客系统

**相关截图**
![image](https://github.com/labring/FastGPT/assets/52238701/cdf133d2-8ab1-4083-89fa-e0704a083e35)
![image](https://github.com/labring/FastGPT/assets/52238701/f6cd5689-43c8-434c-8d7e-e0d146981eca)

**Comment by LiberatorHg** [comment]
并且国内这个js是timeout
![image](https://github.com/labring/FastGPT/assets/52238701/14e3649a-10da-48de-817f-d9a45945688d)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
And the domestic js is timeout
![image](https://github.com/labring/FastGPT/assets/52238701/14e3649a-10da-48de-817f-d9a45945688d)

**Comment by c121914yu** [comment]
这是网络问题吧，run域名只能国外或者梯子用，可以用in域名

**Comment by c121914yu** [comment]
长时间未响应，暂时关闭。请测试新版，还有问题请重新打开。
