### ISSUE TITLE
Can text content extraction support switching models?

### ISSUE THREAD

**Issue by chenhaoqiang** [labring/FastGPT#562]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
文本内容提取可以支持切换模型吗？目前问题分类是支持切换分类模型的，文本内容提取我看了源码是取的配置文件里的ExtractModels配置的第一个模型，需要切换的时候，需要改配置文件，然后重启fastgpt，不太方便，希望后续支持下此功能，感谢作者！
![image](https://github.com/labring/FastGPT/assets/20062034/ef1aedbe-0518-4b68-be05-6464ad172d0e)

**应用场景**
模型整套切换的场景，比如切换ChatGPT到ChatGLM模型，每次需要改配置文件，然后重启fastgpt，不太方便

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
Can text content extraction support switching models? Currently, problem classification supports switching classification models. When I looked at the source code for text content extraction, I took the first model configured by ExtractModels in the configuration file. When you need to switch, you need to change the configuration file and then restart fastgpt, which is not convenient. I hope this feature will be supported in the future, thank you to the author!
![image](https://github.com/labring/FastGPT/assets/20062034/ef1aedbe-0518-4b68-be05-6464ad172d0e)

**Application Scenario**
In the scenario of complete model switching, such as switching from ChatGPT to ChatGLM model, you need to change the configuration file every time and then restart fastgpt, which is inconvenient.

**Related Examples**

**Comment by c121914yu** [comment]
会在下个大版本中实现。

**Comment by chenhaoqiang** [comment]
> 会在下个大版本中实现。

谢谢大佬！😁

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Will be implemented in the next major version.

Thank you, boss! 😁

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/620 已经支持
