### ISSUE TITLE
Can the number of one-time file uploads be increased in the knowledge base? Too few now

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#563]
知识库中可否增加一次性文件个数的上传？现在太少了

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Can the number of files uploaded at one time be increased in the knowledge base? There are too few now
