### ISSUE TITLE
After publishing a local large model using one api, the option of the model cannot be seen on the model configuration page.

### ISSUE THREAD

**Issue by wufxgtihub123** [labring/FastGPT#565]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√ ] 我已确认目前没有类似 issue
- [ √] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [√ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ √] 私有部署版本

**问题描述**
我在启动本地chatglm3模型opean api服务后，并利用one api代理出去，且在config.json中添加了该模型配置，并docker restart  容器id重启了fastgpt，但是我在web页面选择模型时，并没有看到chatglm3的选项，我昨天按照此方式改还没有任务问题，而且当我把config.sjon中的有关chatgpt的配置都删除掉，只留了chatglm3的模型描述时，我在web页面依然能看到gpt相关的选项，
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/74227869/9f5905df-4a4e-49e6-9ffc-d8da8c4cc75a)
![image](https://github.com/labring/FastGPT/assets/74227869/3a83da40-481b-4a11-b511-cc0e57481c9a)
![image](https://github.com/labring/FastGPT/assets/74227869/da99bca0-7791-4dfc-9142-49306acfefde)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [√ ] I have confirmed that there is currently no similar issue
- [√] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [√ ] I used my own key and confirmed that my key can be used normally
- [√] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [√] Private deployment version

**Problem Description**
After I started the local chatglm3 model oean api service, I used one api to proxy out, added the model configuration in config.json, and restarted fastgpt with docker restart container id, but when I selected the model on the web page, there was no I saw the chatglm3 option. I changed it this way yesterday and there was no task problem. Moreover, when I deleted all the chatgpt configurations in config.sjon and left only the chatglm3 model description, I could still see it on the web page. To gpt related options,
**Steps to reproduce**

**expected outcome**

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/74227869/9f5905df-4a4e-49e6-9ffc-d8da8c4cc75a)
![image](https://github.com/labring/FastGPT/assets/74227869/3a83da40-481b-4a11-b511-cc0e57481c9a)
![image](https://github.com/labring/FastGPT/assets/74227869/da99bca0-7791-4dfc-9142-49306acfefde)

**Comment by c121914yu** [comment]
https://doc.fastgpt.in/docs/development/docker/#%E5%A6%82%E4%BD%95%E6%A3%80%E6%9F%A5%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%98%AF%E5%90%A6%E6%8C%82%E8%BD%BD
参考文档进行排查，90%是配置文件格式错，9%是没权限
