### ISSUE TITLE
The [Introduction] content of the knowledge base cannot be saved.

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#566]
知识库的【介绍】内容保存不了，没有抛出异常，界面上提示更新成功。
退出刷新后，再进去里面的内容为空。
![1701853729140](https://github.com/labring/FastGPT/assets/18339429/2d82bcc7-1095-43fa-895c-da4da14d3b55)

![image](https://github.com/labring/FastGPT/assets/18339429/2f806eb7-c45e-44cb-9c9f-59ffe2f64207)

![1701854064457](https://github.com/labring/FastGPT/assets/18339429/5cc05c3e-abf3-4381-b0a2-8c326a9f9540)

![1701854075135](https://github.com/labring/FastGPT/assets/18339429/bea22dd6-d9bb-4148-ad5d-9f438726bfb6)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The [Introduction] content of the knowledge base cannot be saved, no exception is thrown, and the interface prompts that the update is successful.
After exiting the refresh, the content inside will be empty.
![1701853729140](https://github.com/labring/FastGPT/assets/18339429/2d82bcc7-1095-43fa-895c-da4da14d3b55)

**Comment by leoterry-ulrica** [comment]
projects/app/src/pages/api/core/dataset/update.ts里面的逻辑缺失知识库简介属性的保存。
