### ISSUE TITLE
api/core interface unAuthorization

### ISSUE THREAD

**Issue by dq7532183** [labring/FastGPT#567]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
1. api/core/chat/item/delete  删除聊天记录接口,使用应用的apikey或全局通用的 key或rootkey,都不能请求,错误403 unAuthorization
2. api/core/chat/feedback/userUpdate  反馈建议接口,不使用任何token,能请求
3. api/core/ai/agent/createQuestionGuide  下一步引导接口,使用root_key能请求,但是用应用的apikey不能请求,错误403 unAuthorization
官网的rootkey暴露了

**预期结果**
使用应用的apikey可以请求 api/core/chat 下的接口,
使用通用的apikey可以请求非应用的所有接口

**相关截图**
![51ffcb3d3c07950f9480c222e5d2034](https://github.com/labring/FastGPT/assets/22310176/8c557c39-ebac-4516-b55d-ad23447f8d24)
![f2edbe742ac4e18338770becac634ed](https://github.com/labring/FastGPT/assets/22310176/6c45d94f-a103-4ac2-a145-211113a9e382)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x ] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
1. api/core/chat/item/delete interface for deleting chat records, using the application’s apikey or global key or rootkey, cannot be requested, error 403 unAuthorization
2. api/core/chat/feedback/userUpdate feedback suggestion interface, does not use any token, can request
3. api/core/ai/agent/createQuestionGuide The next step is to guide the interface. It can be requested using root_key, but it cannot be requested using the application's apikey. Error 403 unAuthorization
The rootkey of the official website was exposed


**expected outcome**
Use the application's apikey to request the interface under api/core/chat.
Use a common apikey to request all interfaces of non-applications

**Related screenshots**
![51ffcb3d3c07950f9480c222e5d2034](https://github.com/labring/FastGPT/assets/22310176/8c557c39-ebac-4516-b55d-ad23447f8d24)
![51ffcb3d3c07950f9480c222e5d2034](https://github.com/labring/FastGPT/assets/22310176/c3130a8e-d0a0-46a9-9cd7-13b017acfddc)

**Comment by Halecoder** [comment]
> 非常感谢! 我们立即修复这个问题。 关于apikey无法调用接口，目前并不计划所有接口允许apikey调用，仅支持部分。

我也有这样问题，无法导出csv，报错
```
{
    "code": 403,
    "statusText": "unAuthorization",
    "message": "凭证错误",
    "data": null
}
```

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Thank you very much! We will fix this immediately. Regarding the interface that apikey cannot call, there are currently no plans to allow apikey to call all interfaces, only some are supported.

I also have this problem, I can't export csv and get an error
```
{
    "code": 403,
    "statusText": "unAuthorization",
    "message": "Certificate error",
    "data": null
}
```

**Comment by c121914yu** [comment]
> > 非常感谢! 我们立即修复这个问题。 关于apikey无法调用接口，目前并不计划所有接口允许apikey调用，仅支持部分。
> 
> 我也有这样问题，无法导出csv，报错
> ```
> {
>     "code": 403,
>     "statusText": "unAuthorization",
>     "message": "凭证错误",
>     "data": null
> }
> ```

看着像浏览器不支持cookie，可以尝试换谷歌浏览器。
