### ISSUE TITLE
When the shared application is accessed, the browser title should display the logo set by the application. Now the default is the system logo.

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#573]
分享出去的应用访问时候浏览器title应该显示应用已设置的logo，现在默认都是系统logo，没有变化。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
When accessing a shared application, the browser title should display the logo that has been set by the application. Now the default is the system logo and there is no change.

**Comment by c121914yu** [comment]
我不确定是什么版本，但近期没有变动这个title。测试线上环境，确实是应用名。使用新版还有问题的重新open
