### ISSUE TITLE
Unrecognized request argument supplied: functions

### ISSUE THREAD

**Issue by dockersky** [labring/FastGPT#574]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ✅] 私有部署版本

**问题描述**
使用Azure openAI(gpt-3.5-turbo-16k)， 在文本内容提取时，会报：Unrecognized request argument supplied: functions 错误。

**复现步骤**
高级编排，增加文本抽取的模块。
**预期结果**
正常能够抽取到相关内容。
**相关截图**
config.json 配置如下:

{
      "FeConfig": {
        "show_emptyChat": false,
        "show_register": false,
        "show_appStore": false,
        "show_userDetail": true,
        "show_git": false,
        "systemTitle": "AI",
        "authorText": "Made by devops Team.",
        "gitLoginKey": ""
      },
      "SystemParams": {
        "gitLoginSecret": "",
        "vectorMaxProcess": 15,
        "qaMaxProcess": 15,
        "pgIvfflatProbe": 20
      },
      "plugins": {},
      "ChatModels": [
        {
          "model": "gpt-3.5-turbo",
          "name": "GPT35-4k",
          "contextMaxToken": 4000,
          "quoteMaxToken": 2000,
          "maxTemperature": 1.2,
          "price": 0,
          "defaultSystem": ""
        },
        {
          "model": "gpt-3.5-turbo-16k",
          "name": "GPT35-16k",
          "contextMaxToken": 16000,
          "quoteMaxToken": 8000,
          "maxTemperature": 1.2,
          "price": 0,
          "defaultSystem": ""
        },
        {
          "model": "gpt-4",
          "name": "GPT4-8k",
          "contextMaxToken": 8000,
          "quoteMaxToken": 4000,
          "maxTemperature": 1.2,
          "price": 0,
          "defaultSystem": ""
        },
        {
          "model": "gpt-4-32k",
          "name": "GPT-4-32k",
          "contextMaxToken": 32000,
          "quoteMaxToken": 200000,
          "maxTemperature": 1.2,
          "price": 0,
          "defaultSystem": ""
        }
      ],
      "QAModels": [
        {
          "model": "gpt-3.5-turbo-16k",
          "name": "GPT35-16k",
          "maxToken": 16000,
          "price": 0
        }
      ],
      "VectorModels": [
        {
          "model": "text-embedding-ada-002",
          "name": "Embedding-2",
          "price": 0
        }
      ]
    }

**Comment by c121914yu** [comment]
az需要安装新07版本以上的才支持functipncall
