### ISSUE TITLE
It is recommended that config.json can provide visual configuration in the system

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#577]
建议config.json在系统中可以提供可视化配置，避免人工配置容易出错。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It is recommended that config.json can provide visual configuration in the system.

**Comment by c121914yu** [comment]
未来可能会有，但未再规划中。
