### ISSUE TITLE
knowledge base‘s intro cannot be updated

### ISSUE THREAD

**Issue by WyHy** [labring/FastGPT#579]
I am using the 4.6.3 version based on docker-compose, and I found that the introduction of the knowledge base cannot be updated, and the intro field is configured on the config page of the knowledge base, and the update is successful after clicking Save, but the introduction display is still empty after returning to the list page。

![image](https://github.com/labring/FastGPT/assets/13045015/1de63339-2f93-4584-ac8e-24fbcff05d9d)
![image](https://github.com/labring/FastGPT/assets/13045015/06ae8ce9-cdce-4c6a-b974-7b00c7ac00aa)

**Comment by c121914yu** [comment]
4.6.4 already fix.
