### ISSUE TITLE
When using vllm to simulate gpt, a 400 error is reported

### ISSUE THREAD

**Issue by lostmaniac** [labring/FastGPT#580]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
使用vllm进行模拟gpt时候，caddy进行路由，
caddy路由如下

```
:80 {
	reverse_proxy /v1/embeddings http://127.0.0.1:8000 {
    	rewrite /v1/embeddings
	}
	reverse_proxy /v1/chat/completions http://127.0.0.1:8001 {
		  	rewrite /v1/completions
	}
}
```

caddy日志
{"upstream": "127.0.0.1:8001", "duration": 0.001995308, "request": {"remote_ip": "172.21.0.4", "remote_port": "35298", "client_ip": "172.21.0.4", "proto": "HTTP/1.1", "method": "POST", "host": "10.88.7.50", "uri": "/v1/completions", "headers": {"X-Forwarded-Proto": ["http"], "X-Stainless-Lang": ["js"], "X-Stainless-Package-Version": ["4.16.1"], "Authorization": [], "X-Stainless-Os": ["Linux"], "Accept": ["application/json, text/plain, */*"], "User-Agent": ["OpenAI/JS 4.16.1"], "Accept-Encoding": ["gzip,deflate"], "Content-Length": ["7428"], "X-Stainless-Runtime": ["node"], "X-Forwarded-Host": ["10.88.7.50"], "X-Stainless-Runtime-Version": ["v18.15.0"], "X-Stainless-Arch": ["x64"], "X-Forwarded-For": ["172.21.0.4"], "Content-Type": ["application/json"]}}, "headers": {"Date": ["Thu, 07 Dec 2023 14:37:58 GMT"], "Server": ["uvicorn"], "Content-Length": ["172"], "Content-Type": ["application/json"]}, "status": 400}

vllm启动命令：

python -m vllm.entrypoints.openai.api_server --host=127.0.0.1 --port=8001 --model=chatglm3-6b-32k --trust-remote-code  --tokenizer-mode=auto --served-model-name=chatglm3"

**复现步骤**

发送任意聊天，会导致空请求一次/v1/chat/completions
然后vllm就会报错400，后续请求就没办法发送了

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
When using vllm to simulate gpt, caddy performs routing.
The caddy route is as follows

```
:80 {
reverse_proxy /v1/embeddings http://127.0.0.1:8000 {
    rewrite /v1/embeddings
}
reverse_proxy /v1/chat/completions http://127.0.0.1:8001 {
rewrite /v1/completions
}
}
```

caddy log
{"upstream": "127.0.0.1:8001", "duration": 0.001995308, "request": {"remote_ip": "172.21.0.4", "remote_port": "35298", "client_ip": "172.21.0.4 ", "proto": "HTTP/1.1", "method": "POST", "host": "10.88.7.50", "uri": "/v1/completions", "headers": {"X-Forwarded -Proto": ["http"], "X-Stainless-Lang": ["js"], "X-Stainless-Package-Version": ["4.16.1"], "Authorization": [], " X-Stainless-Os": ["Linux"], "Accept": ["application/json, text/plain, */*"], "User-Agent": ["OpenAI/JS 4.16.1"], "Accept-Encoding": ["gzip,deflate"], "Content-Length": ["7428"], "X-Stainless-Runtime": ["node"], "X-Forwarded-Host": [" 10.88.7.50"], "X-Stainless-Runtime-Version": ["v18.15.0"], "X-Stainless-Arch": ["x64"], "X-Forwarded-For": ["172.21. 0.4"], "Content-Type": ["application/json"]}}, "headers": {"Date": ["Thu, 07 Dec 2023 14:37:58 GMT"], "Server": [ "uvicorn"], "Content-Length": ["172"], "Content-Type": ["application/json"]}, "status": 400}

vllm startup command:

python -m vllm.entrypoints.openai.api_server --host=127.0.0.1 --port=8001 --model=chatglm3-6b-32k --trust-remote-code --tokenizer-mode=auto --served-model -name=chatglm3"


**Steps to reproduce**

Sending any chat will result in an empty request for /v1/chat/completions
Then vllm will report an error 400, and subsequent requests cannot be sent.

**expected outcome**



**Related screenshots**
