### ISSUE TITLE
The vector model does not call the configuration in the configuration file

### ISSUE THREAD

**Issue by 20082010** [labring/FastGPT#586]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在配置中已经更换了VectorModels，但依旧还是请求的text-embedding-ada-002
**复现步骤**

**预期结果**
需要更具配置的模型选择正确的
**相关截图**
![image](https://github.com/labring/FastGPT/assets/3966324/c1ae941d-bfd2-431c-a287-362ae3fb46b1)
![image](https://github.com/labring/FastGPT/assets/3966324/2099eb8e-ac00-4641-8f9e-dffda6335701)

**Comment by c121914yu** [comment]
需要提供更详细信息。例如:
是否读取到模型。
是否创建千问向量的知识库。

已创建的知识库无法变更向量。
