### ISSUE TITLE
The answer is inaccurate and cannot be matched in the knowledge base.

### ISSUE THREAD

**Issue by HDlonger** [labring/FastGPT#587]
模型：chatglm3+m3e-base
知识库匹配相似性差距大，匹配不到知识库原有的知识，这是怎么回事，原脚本的升纬到1536也做了
![Uploading 5ecfba599d6d7a56bb4fb2aeec0c6d6.png…]()

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Model: chatglm3+m3e-base
There is a big similarity gap in the knowledge base matching, and the original knowledge in the knowledge base cannot be matched. What is going on? The original script has been upgraded to 1536.
![Uploading 5ecfba599d6d7a56bb4fb2aeec0c6d6.png…]()

**Comment by HDlonger** [comment]
![bd3fc54d62ac1f595d1f95ada64f361](https://github.com/labring/FastGPT/assets/93592432/918ebcab-2117-4b19-bd04-718f0a6b6e4a)
![de9fdfdd4a542fc2759b7d2bf2f8c68](https://github.com/labring/FastGPT/assets/93592432/64a3a2b8-efb5-46fb-a14d-8164c770832d)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![bd3fc54d62ac1f595d1f95ada64f361](https://github.com/labring/FastGPT/assets/93592432/918ebcab-2117-4b19-bd04-718f0a6b6e4a)
![de9fdfdd4a542fc2759b7d2bf2f8c68](https://github.com/labring/FastGPT/assets/93592432/64a3a2b8-efb5-46fb-a14d-8164c770832d)

**Comment by HDlonger** [comment]
请问这是什么模型的原因，语言模型还是向量模型？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
May I ask what model is causing this, a language model or a vector model?

**Comment by c121914yu** [comment]
需要先归一化，这个问题有好多次issue了，可以翻翻。

**Comment by lonngxiang** [comment]
@c121914yu 这边相似度刚好相反，很小导致对话回答内容都没有引用信息，这是什么问题呢？
![eea9ef692a027c35d2050e46f939098](https://github.com/labring/FastGPT/assets/40717349/364dbf96-a2be-45c8-8e62-63d49bc88df0)
