### ISSUE TITLE
Full response tokens are 0

### ISSUE THREAD

**Issue by nightzjp** [labring/FastGPT#593]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
1. 当使用openai官方代理或自己的代理可正常使用；
2. 当使用aiproxy.io的代理的前提下，如果使用问题分类，默认会走最底部的一个分支
**复现步骤**

**预期结果**

**相关截图**
<img width="937" alt="image" src="https://github.com/labring/FastGPT/assets/73635091/2cede4b1-8927-4288-af5c-b53a0c4d1e42">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
1. It can be used normally when using openai official agent or your own agent;
2. When using aiproxy.io's proxy, if you use issue classification, the bottom branch will be taken by default.
**Steps to reproduce**

**expected outcome**

**Related screenshots**
<img width="937" alt="image" src="https://github.com/labring/FastGPT/assets/73635091/2cede4b1-8927-4288-af5c-b53a0c4d1e42">

**Comment by c121914yu** [comment]
私有部署报错问题请提供相关位置的日志。

**Comment by c121914yu** [comment]
长时间未响应，暂时关闭。
