### ISSUE TITLE
There will be a lot of errors when importing documents for QA splitting

### ISSUE THREAD

**Issue by lostmaniac** [labring/FastGPT#598]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
导入文档进行QA拆分时候会有大量报错
**复现步骤**
fastgpt    | Embedding Error e$ [Error]: Request timed out.
fastgpt    |     at tx.makeRequest (/app/projects/app/.next/server/chunks/5092.js:23:79559)
fastgpt    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
fastgpt    |     at async b (/app/projects/app/.next/server/chunks/9847.js:81:4178)
fastgpt    |     at async Y (/app/projects/app/.next/server/chunks/9847.js:83:1514)
fastgpt    |     at async Promise.all (index 0)
fastgpt    |     at async R (/app/projects/app/.next/server/chunks/9847.js:82:161)
fastgpt    |     at async h (/app/projects/app/.next/server/chunks/9847.js:93:2538) {
fastgpt    |   status: undefined,
fastgpt    |   headers: undefined,
fastgpt    |   error: undefined,
fastgpt    |   code: undefined,
fastgpt    |   param: undefined,
fastgpt    |   type: undefined
fastgpt    | }

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
网络超时，key问题。

**Comment by lostmaniac** [comment]
用的是我本地的模型，不是openai的模型

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I am using my local model, not OpenAI’s model.
