### ISSUE TITLE
知识库上传文档报错“e.replaceAll is not a function”

### ISSUE THREAD

**Issue by LuisToday** [labring/FastGPT#601]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ X] 我已确认目前没有类似 issue
- [ X] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ X] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ X] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [X ] 公有云版本
- [ ] 私有部署版本

**问题描述**
知识库上传文档报错“e.replaceAll is not a function”
**复现步骤**
登陆——知识库——新建/导入——文件导入——选择文件——选择文件——打开——报错
**预期结果**
上传成功，开始训练
**相关截图**
![bug](https://github.com/labring/FastGPT/assets/152672070/177f09e7-13bf-466d-a2ac-f517d6f599e9)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [X] I have confirmed that there is currently no similar issue
- [
- [X] I used my own key and confirmed that my key can be used normally
- [X] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [X ] Public cloud version
- [ ] private deployment version

**Problem Description**
Error "e.replaceAll is not a function" reported when uploading documents to the knowledge base
**Steps to reproduce**
Login-Knowledge Base-New/Import-File Import-Select File-Select File-Open-Error Report
**expected outcome**
Upload successfully, start training
**Related screenshots**
![bug](https://github.com/labring/FastGPT/assets/152672070/177f09e7-13bf-466d-a2ac-f517d6f599e9)

**Comment by c121914yu** [comment]
可以提供原文档测试一下么？

**Comment by LuisToday** [comment]
可能是我机子的问题，我换了一台电脑，这个问题就没有再出现过。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It may be a problem with my machine. I changed my computer and this problem has not occurred again.
