### ISSUE TITLE
bug feedback users.findOne

### ISSUE THREAD

**Issue by shiliu2023** [labring/FastGPT#605]
Operation `users.findOne()` buffering timed out after 10000ms

升级之后登录提示这个 怎么搞？

**Comment by c121914yu** [comment]
数据库问题，按部署文档自己排查

**Comment by MusicOfWind** [comment]
> Operation `users.findOne()` buffering timed out after 10000ms
> 
> 升级之后登录提示这个 怎么搞？

大哥，你怎么解决的
