### ISSUE TITLE
FastGPT v4.6.4 The classification results of problem classification are all the last option

### ISSUE THREAD

**Issue by ixqkedp** [labring/FastGPT#613]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
FastGPT v4.6.4 问题分类的分类结果都是最后一个选项

**复现步骤**
1. 使用问题分类，来分类输入内容是“中文”或“英文”，不管输入中文或英文，都会比判定成英文 
   (分类1：中文、分类2：英文)
2. 使用内建的问题分类范类测试，输入“你好”，被判定为“其它问题”
   (分类1：打招呼,问候等问题、分类2：关于xxx问题、分类3：商务问题、分类4：其它问题)
3. 本地模型使用text-generation-webui载入yentinglin/Taiwan-LLaMa-v1.0模型

**预期结果**
  输入「中文字」会被分类在中文问题，输入「英文字」会被分类在英文讯息

**相关截图**
![01](https://github.com/labring/FastGPT/assets/53467418/c6e8b799-5e60-462d-876c-7e6cfd2382ce)
![02](https://github.com/labring/FastGPT/assets/53467418/5e560333-552b-46ca-a385-6c5d16c74c1f)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
The classification results of problem classification are all the last option

**Steps to reproduce**
1. Use question classification to classify the input content as "Chinese" or "English". Regardless of whether the input content is Chinese or English, it will be judged as English.
   (Category 1: Chinese, Category 2: English)
2. Use the built-in question classification category test, enter "Hello", and it will be judged as "other questions"
   (Category 1: Saying hello, greetings and other questions, Category 2: Questions about xxx, Category 3: Business issues, Category 4: Other issues)

**expected outcome**
  Entering "Chinese characters" will be classified into Chinese questions, entering "English characters" will be classified into English messages

**Related screenshots**
![01](https://github.com/labring/FastGPT/assets/53467418/c6e8b799-5e60-462d-876c-7e6cfd2382ce)
![02](https://github.com/labring/FastGPT/assets/53467418/5e560333-552b-46ca-a385-6c5d16c74c1f)

**Comment by c121914yu** [comment]
模型问题，看错误日志

**Comment by ixqkedp** [comment]
log顯示如下：
{
  type: 'object',
  properties: {
    type: {
      type: 'string',
      description: "问题类型。下面是几种可选的问题类型: 中文問題，返回：'wqre'；英文問題，返回：'sdfa'",
      enum: [Array]
    }
  },
  required: [ 'type' ]
}
{
  role: 'assistant',
  content: '\n' +
    'class Solution(object):\n' +
    '    def classify(self, content):\n' +
    "        if content == '中文':\n" +
    "            return '中文'\n" +
    "        elif content == '英文':\n" +
    "            return '英文'\n" +
    '        else:\n' +
    "            raise Exception('Unknown language')"
}
Your model may not support toll_call SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at y (/app/projects/app/.next/server/chunks/7050.js:75:554)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.g [as classifyQuestion] (/app/projects/app/.next/server/chunks/7050.js:70:841)
    at async M (/app/projects/app/.next/server/chunks/7050.js:90:5284)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async b (/app/projects/app/.next/server/chunks/7050.js:90:6369)
    at async l (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2554)
[INFO] 2023-12-20 03:24:00 finish completions: {"source":"fastgpt","teamId":"657be1f5a9dcff4fdb7fb675","tmbId":"657be1f5a9dcff4fdb7fb679","price":0}

**Comment by c121914yu** [comment]
关闭重复问题
