### ISSUE TITLE
FastGPT v4.6.4 Text content extraction cannot extract the target field

### ISSUE THREAD

**Issue by ixqkedp** [labring/FastGPT#614]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
FastGPT v4.6.4 文本内容提取无法提取目标字段

**复现步骤**
 1. 使用实验室预约的范例测试文本内容提取输入文本中的姓名、时间、实验室名，但都提取空值
 2. 本地模型使用text-generation-webui载入yentinglin/Taiwan-LLaMa-v1.0模型

**预期结果**
 预期可以正确提取出姓名、时间、实验室名，并透过http模块传送给pytho api

**相关截图**
![03](https://github.com/labring/FastGPT/assets/53467418/181a1074-9697-448f-b459-b64d7d7c2d84)
![04](https://github.com/labring/FastGPT/assets/53467418/40af95b9-6761-4a3f-a511-f5d51a4639ff)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Text content extraction cannot extract the target field

**Steps to reproduce**
 1. Use the sample test text content of the laboratory appointment to extract the name, time, and laboratory name in the input text, but all of them extract null values.
 2. The local model uses text-generation-webui to load the yentinglin/Taiwan-LLaMa-v1.0 model

**expected outcome**
 It is expected that the name, time, and laboratory name can be correctly extracted and sent to the python api through the http module.

**Related screenshots**
![03](https://github.com/labring/FastGPT/assets/53467418/181a1074-9697-448f-b459-b64d7d7c2d84)
![04](https://github.com/labring/FastGPT/assets/53467418/40af95b9-6761-4a3f-a511-f5d51a4639ff)

**Comment by leoterry-ulrica** [comment]
我也遇到同样的问题。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also encountered the same problem.

**Comment by c121914yu** [comment]
没看懂，提取不了不是模型问题么儿

**Comment by ixqkedp** [comment]
log顯示如下：
{
  type: 'object',
  properties: {
    type: {
      type: 'string',
      description: "问题类型。下面是几种可选的问题类型: 实验室问题，返回：'fasw'；新增、取消、查询、修改预约实验室，返回：'fqsw'",
      enum: [Array]
    }
  },
  required: [ 'type' ]
}
{ role: 'assistant', content: '您好，请告诉我您想要预约的时间段和日期。我会为您查看并回復。' }
Your model may not support toll_call SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at y (/app/projects/app/.next/server/chunks/7050.js:75:554)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.g [as classifyQuestion] (/app/projects/app/.next/server/chunks/7050.js:70:841)
    at async M (/app/projects/app/.next/server/chunks/7050.js:90:5284)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async b (/app/projects/app/.next/server/chunks/7050.js:90:6369)
    at async l (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2554)
[INFO] 2023-12-20 03:08:28 finish completions: {"source":"fastgpt","teamId":"657be1f5a9dcff4fdb7fb675","tmbId":"657be1f5a9dcff4fdb7fb679","price":0}

python api接收到的json如下：
{'appointment': '{}', 'action': '{}', 'variables': {'cTime': '2023-12-20 11:07:12'}}

**Comment by ixqkedp** [comment]
请问哪些模型有技援提取？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Which models have technical assistance extracted?

**Comment by c121914yu** [comment]
> 您的模型可能不支持 toll_call SyntaxError: Unexpected end of JSON input

只有GPT支持tool。其他模型只有prompt模式

**Comment by SnakeHacker** [comment]
If it is not a gpt-3.5 model, setting the `toolChoice` field in the `config.local.json` to false for the model configuration will suffice.
