### ISSUE TITLE
FastGPT v4.6.4 文本内容提取-function calling失效

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#615]
更新版本到4.6.4后，发下系统模块中的【文本内容提取】对function  calling失效了，以下是请求和输出信息。
![1702747784372](https://github.com/labring/FastGPT/assets/18339429/eac7560a-b824-47d4-816b-ff4d7d205b10)

```
2023-12-17 01:15:23.355 | DEBUG    | __main__:create_chat_completion:144 - ==== request ====
{'messages': [ChatMessage(role='user', content='<任务描述>\n你是一个天气查询助手。根据用户问题，提取出城市。注意不是简单的文本提取，而是上下文理解后的提取。如果用户问题中不包含城市则不提取。\\n如果内容不存在，返回空字符串。\n\n- 如果字段为空，你返回空字符串。\n- 不要换行。\n- 结合历史记录和文本进行提取。\n</任务描述>\n\n<文本>\n广州今天天气如何\n</文本>', name=None, function_call=None)], 'temperature': 0.0, 'top_p': 0.8, 'max_tokens': 1024, 'echo': False, 'stream': False, 'repetition_penalty': 1.1, 'functions': None}
2023-12-17 01:15:23.579 | DEBUG    | __main__:create_chat_completion:225 - ==== message ====
```

**Comment by leoterry-ulrica** [comment]
@c121914yu 麻烦帮忙排查一下原因，已经卡主好几天了。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@c121914yu Please help me find out the cause. It has been stuck for several days.

**Comment by c121914yu** [comment]
function call已经被弃用，改成tool choice了

**Comment by ccly1996** [comment]
请问内容提取模块能调用本地部署的模型吗

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Can the content extraction module call locally deployed models?
