### ISSUE TITLE
Request support for Zhipu AI

### ISSUE THREAD

**Issue by assassinliujie** [labring/FastGPT#616]
chatglm成本稍微低一点，如果能支持使用chatglm就好了

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The cost of chatglm is slightly lower. It would be great if it could support the use of chatglm

**Comment by leoterry-ulrica** [comment]
已支持了的。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Already supported.
