### ISSUE TITLE
The content of the knowledge base is segmented and the code analysis in the document is performed.

### ISSUE THREAD

**Issue by Halecoder** [labring/FastGPT#617]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
上传相关md文本内容进行分段时，fastgpt对js代码进行执行，导致导入失败
**复现步骤**

下面是相关代码的文档，可以导入进行测试

https://www.123pan.com/s/Mrw9-nZkl.html

下面是两个js代码片段，可以放入md文档进行上传测试：

第一个：
上传含有本代码片段的文档，会在浏览器执行弹出窗口

```js
var name = "<img src=x onerror=alert(1)>";
el.innerHTML = name;
```

第二个：
上传含有本代码片段的文档，会出现网络错误

```html
<base href="http://www.example.com/page.html">
```

**相关截图**
[![tan1.jpg](https://www.freeimg.cn/i/2023/12/17/657ea155d96dc.jpg)](https://www.freeimg.cn/i/2023/12/17/657ea155d96dc.jpg)

[![network error.jpg](https://www.freeimg.cn/i/2023/12/17/657ea1578218b.jpg)](https://www.freeimg.cn/i/2023/12/17/657ea1578218b.jpg)

**Comment by c121914yu** [comment]
忘记关联了，之前取消了html解析，只解析纯文本。新版本应该没这个问题了。
