### ISSUE TITLE
 response error: Operation `users.findOne()` buffering timed out after 10000ms: {"stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.eval (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+mongoose@7.6.3/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)"}

### ISSUE THREAD

**Issue by xjinlina77** [labring/FastGPT#618]
[ERROR] 2023-12-17 15:54:00 response error: Operation `users.findOne()` buffering timed out after 10000ms: {"stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.eval (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+mongoose@7.6.3/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)"}
[ERROR] 2023-12-17 15:54:00 response error: Operation `users.findOne()` buffering timed out after 10000ms: {"stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.eval (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+mongoose@7.6.3/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)"}
error-> mongo connect error MongooseServerSelectionError: connect ECONNREFUSED 0.0.0.0:27017
    at _handleConnectionErrors (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+mongoose@7.6.3/node_modules/mongoose/lib/connection.js:805:11)
    at NativeConnection.openUri (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+mongoose@7.6.3/node_modules/mongoose/lib/connection.js:780:11)
    at async connectMongo (webpack-internal:///(api)/../../packages/service/common/mongo/init.ts:18:9)
    at async handler (webpack-internal:///(api)/./src/pages/api/user/account/loginByPassword.ts:22:9) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { '0.0.0.0:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
[ERROR] 2023-12-17 15:55:46 response error: Operation `users.findOne()` buffering timed out after 10000ms: {"stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.eval (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+mongoose@7.6.3/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)"}

**Comment by xjinlina77** [comment]
![1702799945453](https://github.com/labring/FastGPT/assets/151553788/9c9f18c4-885e-42a3-969a-25433358c551)

**Comment by c121914yu** [comment]
数据库没起来，或者连接参数问题

**Comment by katfionn** [comment]
> 数据库没起来，或者连接参数问题

我用最新的版本的，数据库方面什么都没改，默认配置的，，也出现了同样的提示，大佬最后是怎么处理好的
