### ISSUE TITLE
Please tell me why FastGPT/files/models/Baichuan2 /openai_api.py needs to be expanded to 1536

### ISSUE THREAD

**Issue by ikuntrue199** [labring/FastGPT#623]
请教一下，FastGPT/files/models/Baichuan2 /openai_api.py 中，嵌入向量的维度为什么要拓展到1536

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Please tell me why the dimension of the embedding vector is expanded to 1536 in FastGPT/files/models/Baichuan2/openai_api.py

**Comment by c121914yu** [comment]
因为向量存储需要指定维度

**Comment by ikuntrue199** [comment]
只有FastGPT  有这个要求吗  还是说其他的embedding入库都要为1536

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Does only FastGPT have this requirement? Or does it mean that all other embeddings must be 1536?

**Comment by c121914yu** [comment]
> 只有FastGPT 有这个要求吗 还是说其他的embedding入库都要为1536

openai的接口就是1536，目前应该都没有比它高维度的模型，基本是756和1024.
