### ISSUE TITLE
How to make the knowledge base answer more accurate

### ISSUE THREAD

**Issue by HDlonger** [labring/FastGPT#626]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
如何能让知识库回答的更准确，其实已经在知识库中匹配到该问题的答案了，可是还是不回答，总不能只能提问同知识库预设的一模一样的问题吧
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/93592432/0b705a0f-d096-4a6f-a8bc-ddfc9d1dfbd1)
![image](https://github.com/labring/FastGPT/assets/93592432/3a403c67-832c-4b98-8f1b-50e9c7a90f5b)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
How to make the knowledge base answer more accurately? In fact, the answer to the question has been matched in the knowledge base, but it still does not answer. You can't just ask the same question as the one preset in the knowledge base.
**Steps to reproduce**

**expected outcome**

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/93592432/30cabb34-fec7-4238-8f00-b89851119137)
![image](https://github.com/labring/FastGPT/assets/93592432/642dd3cd-0f28-4a9b-aeea-37a7cd5a18e5)

**Comment by c121914yu** [comment]
与提示词结构和引用结构有关，可以调整这两个参数，从而实现模型回答的精度与范度

**Comment by c121914yu** [comment]
> 与提示词结构和引用结构有关，可以调整这两个参数，从而实现模型回答的精度与范度

具体内容应该去学习RAG提示词。
