### ISSUE TITLE
"Classification" does not work properly

### ISSUE THREAD

**Issue by leezhuuu** [labring/FastGPT#629]
![WeChat7f2ac8509fd6392f5cc9ecd6f00e14d4](https://github.com/labring/FastGPT/assets/69389053/9d776d64-6933-4242-89ed-ebf5fd8d1f8e)

请问这是怎么回事，是用的是自己部署的docker，api是用的是中转的openai的api，测试api正确，
“分类”不能正常起作用，每次测试发现它只回复分类项目中最后一条类别，
请看一下这是哪里的问题，谢谢

**Comment by leezhuuu** [comment]
![WeChatc208a970b3a708c7ed9be2eccfc71944](https://github.com/labring/FastGPT/assets/69389053/9b5f29d1-f739-423b-bf72-c18372a35c86)

日志是这样的

**Comment by leezhuuu** [comment]
![WeChat5276a31ff398350a2e981e287702bd31](https://github.com/labring/FastGPT/assets/69389053/8f5412af-d322-4069-ac27-457994343b5a)


应该是这里的格式不正确，请问应该如何修改呢？

**Comment by c121914yu** [comment]
需要返回json格式才能分类。
1. 设置了function call=true，默认会走 openai 最新的 toolChoices 接口。
2. 没设置function call=true，走提示词模式。模型必须返回 JSON 格式的答案才能被识别。

**Comment by leezhuuu** [comment]
好的，已解决，谢谢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
OK, solved, thank you

**Comment by swingsun888** [comment]
> 好的，已解决，谢谢
请问怎么解决的，我也遇到类似的问题
