### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by zxwmol** [labring/FastGPT#630]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
采用fastgpt对接one-api，均采用docker部署，报错：Connection error。
fastgpt完整日志：ERROR] 2023-12-20 08:09:58 sse error: Connection error.: {"stack":"Error: Connection error.\n    at tx.makeRequest (/app/projects/app/.next/server/chunks/5092.js:23:79572)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.k [as chatNode] (/app/projects/app/.next/server/chunks/7050.js:90:1025)\n    at async M (/app/projects/app/.next/server/chunks/7050.js:90:5284)\n    at async Promise.all (index 0)\n    at async Promise.all (index 0)\n    at async b (/app/projects/app/.next/server/chunks/7050.js:90:6369)\n    at async /app/projects/app/.next/server/chunks/1282.js:1:3122"}
one-api无报错
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/38974244/a6cfad6a-eb63-4953-9247-9dddffde943d)
![image](https://github.com/labring/FastGPT/assets/38974244/1996e322-0c6c-4130-864b-c6c3fd9cd580)
![image](https://github.com/labring/FastGPT/assets/38974244/f04c21bd-f77a-41ea-acdc-172a9fa9895a)
![image](https://github.com/labring/FastGPT/assets/38974244/610ef373-dc68-4086-89bd-c9a56e932909)

**Comment by c121914yu** [comment]
不能localhost，要用桥接模式。

**Comment by c121914yu** [comment]
> Connection

补补docker网络方式。

**Comment by YueXingZe** [comment]
您好，请问问题解决了吗

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hello, has the problem been solved?

**Comment by zxwmol** [comment]
已解决，需要使用节点IP，不能用127

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Solved, node IP needs to be used, 127 cannot be used

**Comment by xiaoping1993** [comment]
请问怎么看这个“节点ip”啊，我也遇到这个问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Please tell me how to check this "node IP". I also encountered this problem.

**Comment by WestCraneLi** [comment]
please check your ip of  container in docker
for example:
* docker ps # find your container id
* docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <id of container or name of contaienr>
* use the ip

**Comment by weifengzyl** [comment]
看这个https://blog.csdn.net/zylwoaini/article/details/136618101
