### ISSUE TITLE
After connecting to chat-on-webchat, the webchat tool and dell-3 drawing cannot be used.

### ISSUE THREAD

**Issue by linrb685** [labring/FastGPT#632]
绘图：[INFO][2023-12-20 11:51:56][wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
画图出现问题，请休息一下再问我吧), 

tool：During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/plugins/tool/tool.py", line 104, in on_handle_context
    _reply = self.app.ask(query, user_session)
  File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/victorinox.py", line 116, in ask
    return self.ask(query, chat_history, retry_num + 1)
  File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/victorinox.py", line 118, in ask
    raise TimeoutError("超过重试次数")
TimeoutError: 超过重试次数
[ERROR][2023-12-20 11:45:27][tool.py:109] - 超过重试次数
[INFO][2023-12-20 11:45:27][chat_gpt_bot.py:49] - [CHATGPT] query=请你随机用一种聊天风格，提醒用户：这个问题tool插件暂时无法处理
[INFO][2023-12-20 11:45:34][wechat_channel.py:191] - [WX] sendMsg=Reply(type=TEXT, content=@away
哎呀，看来您问的这个问题关于泉州今日天气，我的工具箱里暂时还没有这个功能呢。不过，您可以快速查一下最新的天气预报，用手机上的天气App或者直接在网上搜索一下，应该能找到您需要的信息。如果有其他问题或者需要帮助的地方，我随时在这儿哦！),

**Comment by c121914yu** [comment]
fastgpt不支持绘图。要接入的话，自己找一个oneapi去接fastgpt再接入cow
