### ISSUE TITLE
File upload failed

### ISSUE THREAD

**Issue by linrb685** [labring/FastGPT#633]
我上传一个8M的pdf文件，提示最多只支持10个文件。是pdf太大内容太多的问题吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I uploaded an 8M pdf file and it was prompted that only a maximum of 10 files are supported. Is it a problem that the pdf is too large and contains too much content?

**Comment by c121914yu** [comment]
数量10个是限制选择10个文件。
大小，我这上传100M都可以，前提是网关开了这么大。
有没有截图或录屏。

**Comment by linrb685** [comment]
是我上传的pdf不标准

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The pdf I uploaded is not standard.

**Comment by c121914yu** [comment]
> 是我上传的pdf不标准

ok
