### ISSUE TITLE
PDF not text file

### ISSUE THREAD

**Issue by yaoyaoio** [labring/FastGPT#634]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [✓] 我已确认目前没有类似 issue
- [✓] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [✓] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [✓] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [✓] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ 4.6.4] 公有云版本
- [ ] 私有部署版本

**问题描述**
I am in the dataset -> create/import -> file import. If I upload a PDF in image format, such as a scanned copy, it will not be successfully parsed. But the front end did not prompt. 
So I looked at the relevant code. In the [readPdfContent](https://github.com/labring/FastGPT/blob/main/projects/app/src/pages/dataset/detail/components/Import/FileSelect.tsx#L174C34-L174C34) function, the returned text is empty. The [readPDFPage](https://github.com/labring/FastGPT/blob/main/projects/app/src/web/common/file/utils.ts#L46C13-L46C24) inside readPdfContent did not handle the case where tokenizedText is empty. If it is a PDF in image format, the [getTextContent](https://github.com/labring/FastGPT/blob/41115a96c005c29a68d4a4fc321f88d6f7a01aa1/projects/app/src/web/common/file/utils.ts#L48C44-L48C44)() function returns empty. So I think either judge whether the test is empty and prompt at the outermost layer, or handle it in readPDFPage.

**复现步骤**
You could reproduce this issue by uploading a non-text PDF.

**预期结果**
![CleanShot 2023-12-20 at 22 38 08@2x](https://github.com/labring/FastGPT/assets/14813534/b8982ba2-0d67-410c-8740-74e1df3abd95)

**相关截图**

**Comment by c121914yu** [comment]
4.6.7 对提示做个新的优化。
