### ISSUE TITLE
Why is the http module in the docker I deployed not the latest? Where should I go to find the latest version?

### ISSUE THREAD

**Issue by leezhuuu** [labring/FastGPT#635]
![Screenshot_2023-12-21-00-42-07-206_com android chrome-edit](https://github.com/labring/FastGPT/assets/69389053/c3f55c48-9fad-43e6-bae5-43066c25832f)
为什么我部署的docker中的http模块不是最新的呢？应该去哪里寻找最新的版本呢

**Comment by c121914yu** [comment]
看镜像仓库
