### ISSUE TITLE
Custom Embedding API not working properly

### ISSUE THREAD

**Issue by zhangmjcn** [labring/FastGPT#637]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
通过FastGPT调用来自OneAPI转发的私有Embedding服务时，出现错误，不能获得vector以编制文档索引。经测试，OneAPI的embedding通过curl调用正常。

**复现步骤**
1.OneAPI中添加“自定义渠道”，将http设置为本地的Embedding服务
2.修改 data/config.json, 添加一个新的VectorModel记录:
  {
          "model":"local-embedding", # 注：名称与OneAPI中的名称对应， 我用的是一个token 1024位的向量
          "name": "Embedding-local",
          "price": 0,
          "defaultToken":450,
          "maxToken":5000
     }
3. FastGPT中新建知识库，索引模型选择：Embedding-local
4. 在新的知识库中导入一个pdf文件， 创建成功然后编制索引过程中，报错。

**预期结果**
应正常编制索引。

**相关截图**
![1](https://github.com/labring/FastGPT/assets/25670023/6327ec82-bef2-4b46-bc98-303bab681018)
![2](https://github.com/labring/FastGPT/assets/25670023/cbacd3e9-4bbb-48fb-bc2d-cd2ad75efa68)
![3](https://github.com/labring/FastGPT/assets/25670023/195ea027-072e-4f9b-a316-c8ca3ea6127e)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
When calling the private Embedding service forwarded from OneAPI via FastGPT, an error occurred and the vector could not be obtained for document indexing. After testing, OneAPI's embedding is called normally through curl.

**Steps to reproduce**
1. Add "custom channel" to OneAPI and set http as the local Embedding service
2. Modify data/config.json and add a new VectorModel record:
  {
          "model":"local-embedding", # Note: The name corresponds to the name in OneAPI. I use a token 1024-bit vector.
          "name": "Embedding-local",
          "price": 0,
          "defaultToken":450,
          "maxToken":5000
     }
3. Create a new knowledge base in FastGPT and select the index model: Embedding-local
4. Import a pdf file into the new knowledge base. The creation is successful and then an error is reported during the indexing process.

**expected outcome**
Indexing should occur normally.

**Related screenshots**
![1](https://github.com/labring/FastGPT/assets/25670023/6327ec82-bef2-4b46-bc98-303bab681018)
![2](https://github.com/labring/FastGPT/assets/25670023/cbacd3e9-4bbb-48fb-bc2d-cd2ad75efa68)
![3](https://github.com/labring/FastGPT/assets/25670023/195ea027-072e-4f9b-a316-c8ca3ea6127e)

**Comment by c121914yu** [comment]
向量维度不对吧。

**Comment by zhangmjcn** [comment]
> 向量维度不对吧。

本地embedding的API向量维度返回的是1024。 比较理想的状况是，在FastGPT中可以支持维度为1024的向量，目前试了一下没调通，认为系统应该不支持1024维度的向量

随后，我将返回的向量以添加0的方式扩充模拟1536（提示中要求1536），但是扩充后，仍显示出错，记得返回的信息显示成向量维度为3071， 不是1536。于是就卡在这里了。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> The vector dimensions are wrong, right?

The API vector dimension of local embedding returns 1024. The ideal situation is that FastGPT can support vectors with a dimension of 1024. Currently, I have tried it but it failed to work. I think the system should not support vectors with a dimension of 1024.

Then, I expanded the returned vector by adding 0 to simulate 1536 (the prompt required 1536), but after the expansion, an error was still displayed. Remember that the returned information showed that the vector dimension was 3071, not 1536. So I'm stuck here.

**Comment by zhangmjcn** [comment]
已解决，传入给oneAPI的本地embedding格式没对应上，对应好就正常了。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Solved. The local embedding format passed to oneAPI does not correspond. Once the mapping is done, it will be normal.

**Comment by CaoYunzhou** [comment]
https://github.com/CaoYunzhou/cf-embedding
顺带写的，可以免费用

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
https://github.com/CaoYunzhou/cf-embedding
Written by the way, you can use it for free
