### ISSUE TITLE
An error occurs when using the gpt-4-vision-preview model

### ISSUE THREAD

**Issue by syusama** [labring/FastGPT#639]
**问题描述**
An error occurs when using the gpt-4-vision-preview model

**复现步骤**

**预期结果**

**相关截图**
bind_request_body_failed json: cannot unmarshal array into Go struct field Message.messages.content of type string (request id: 20231221170013440826620UJmYbqu8)
![微信截图_20231221170338](https://github.com/labring/FastGPT/assets/16223129/05e2654b-9037-4ad0-bb86-02d318c4bf64)

**Comment by c121914yu** [comment]
看着像上游key报错了

**Comment by syusama** [comment]
上游的One-Api版本过低，还不支持gpt-4-vision-preview，升级一下One-Api就好了
