### ISSUE TITLE
connect EPERM

### ISSUE THREAD

**Issue by joeshi1** [labring/FastGPT#640]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
网页版

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
在任何输入框输入文字均得到connect EPERM 提示。

**复现步骤**
在任何输入框输入任何文字。

**预期结果**
connect EPERM

**相关截图**

<img width="322" alt="2023 12 22" src="https://github.com/labring/FastGPT/assets/80762055/3fc698e1-7fea-4242-acca-6dbb0b5d3b70">

**Comment by zengold** [comment]
我也有这个问题，eperm链接错误，请问是否连接的库有问题，同为web版本

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also have this problem. The eperm link is wrong. Is there a problem with the connected library? They are both web versions.

**Comment by c121914yu** [comment]
数据库出现了问题，正在修复~

**Comment by c121914yu** [comment]
已修复
