### ISSUE TITLE
Questions about initialization

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [labring/FastGPT#650]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
是不是使用docker-compose部署，也需要自己支持初始化脚本
如果是要执行的话，是不是要执行所有版本的初始化命令，并且要按照顺序执行？
如果是这么麻烦的话，为什么不用一个脚本自动化从头执行到尾，我们现在是不是还要通过查看代码才能知道哪些脚本能执行
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Do you use docker-compose to deploy? You also need to support the initialization script yourself.
If it is to be executed, should all versions of the initialization commands be executed in order?
If it is so troublesome, why not use a script to automate the execution from start to finish? Do we still have to look at the code to know which scripts can be executed?
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
都需要执行。
因为官方不会跨版本升级，所以不会有自动升级脚本。
不用看代码，看版本号就行。

**Comment by c121914yu** [comment]
https://doc.fastgpt.in/docs/development/upgrading/intro/ 升级说明
