### ISSUE TITLE
[Question completion] function, always answer directly

### ISSUE THREAD

**Issue by wm-network** [labring/FastGPT#651]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
【问题补全】功能，已经在提示词中再次强调不许直接回答了， 偶尔还是会回答，而且有时候返回一半信息，后面一半会在后面流程的ai对话功能里输出出来。
目前用的是fast4k。
请问有什么办法改善这个问题吗。

**复现步骤**
会话中的第一句没问题，一般都是第二句开始容易出现。

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [x] Public cloud version
- [ ] private deployment version

**Problem Description**
The [Question Completion] function has once again emphasized that direct answers are not allowed in the prompt words. Occasionally, answers will still be given, and sometimes half of the information will be returned, and the latter half will be output in the AI ​​dialogue function in the subsequent process.
Currently using fast4k.
Is there any way to improve this problem?

**Steps to reproduce**
The first sentence in a conversation is fine, but it usually comes more easily from the second sentence.

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
用plus模型试试
