### ISSUE TITLE
fasgpt 外部使用，不会转发functions或者tools的，同意接口也不会返回functions_call或者tolls_call

### ISSUE THREAD

**Issue by YC04-23** [labring/FastGPT#658]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 features
- [ x] 我已确认我已升级到最新版本
- [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我也同样碰到这个问题，使用的chatglm和fastgpt，我发现通过fastgpt转发的api接口不会将functions，或tools转发到chatglm里面，在request里面，没有这两个参数
同样的我尝试过阅读过文档，文档里面里面有介绍支持openai标准的functions_call,只需要将配置模型的toolChoice改为true，我同意的也设置了

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
I also encountered this problem. I used chatglm and fastgpt. I found that the api interface forwarded through fastgpt would not forward functions or tools to chatglm. In the request, there are no these two parameters.
I have also tried reading the documentation. The documentation introduces functions_call that supports the openai standard. You only need to change the toolChoice of the configuration model to true. I agree with it and set it.

**Comment by c121914yu** [comment]
没法复现，测试过程，问题分类与提取模块的tools已经成功发送。请提供更多数据。

**Comment by mushan0x0** [comment]
<img width="485" alt="image" src="https://github.com/labring/FastGPT/assets/29084441/ea976c30-bb17-4099-b3c1-6b7a76c7a115">

将应用通过apikey的方式放到别的工具里确实不会触发函数调用，感觉是从入口到末尾之间函数调用参数丢失了

<img width="1330" alt="image" src="https://github.com/labring/FastGPT/assets/29084441/70b43e5c-0c25-4cb3-b225-0d06286397a3">

**Comment by c121914yu** [comment]
> <img width="485" alt="image" src="https://github.com/labring/FastGPT/assets/29084441/ea976c30-bb17-4099-b3c1-6b7a76c7a115">
> 
> 将应用通过apikey的方式放到别的工具里确实不会触发函数调用，感觉是从入口到末尾之间函数调用参数丢失了 @c121914yu 
> 
> <img width="1330" alt="image" src="https://github.com/labring/FastGPT/assets/29084441/70b43e5c-0c25-4cb3-b225-0d06286397a3">
> 

如果你指的是吧 fastgpt 当做接口中转，那肯定是没有用的
