### ISSUE TITLE
AI reply, there is no typewriter effect on the front end

### ISSUE THREAD

**Issue by qingzhp** [labring/FastGPT#663]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.6.4

- [ ] 公有云版本
- [ √] 私有部署版本

**问题描述**
AI回复没有打字机一个一个字输出的效果，而是一下子全部显示（没有流式效果）。在群里问了人，确认了key没问题，网站也没挂CDN

**复现步骤**
每次对话都是这样

**预期结果**
恢复打字机效果（恢复流式效果）

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**
4.6.4

- [ ] Public cloud version
- [√] Private deployment version

**Problem Description**
The AI ​​reply does not have the effect of a typewriter outputting words one by one, but displays them all at once (no streaming effect). I asked people in the group and confirmed that there is no problem with the key and the website is not linked to CDN.

**Steps to reproduce**
Every conversation is like this

**expected outcome**
Restore typewriter effect (restore streaming effect)

**Related screenshots**

**Comment by c121914yu** [comment]
并没有办法复现，也没看到其他人有这个问题，大概率是你的网关之类配置不好。

**Comment by qingzhp** [comment]
解决了，nginx配置的问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Solved, nginx configuration problem
