### ISSUE TITLE
Use one API to access other models, but when operating the fastgpt conversation, it always shows that the network cannot be connected.

### ISSUE THREAD

**Issue by littlemousehao** [labring/FastGPT#664]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**
通过one API来接入其他模型，修改配置文件为 OPENAI_BASE_URL=http://localhost:13000/v1，也加入了令牌，，但是操作fastgpt对话的时候，一直显示网络无法连接。
**复现步骤**
[ERROR] 2023-12-27 23:43:12 sse error: Connection error.: {"stack":"Error: Connection error.\n    at tx.makeRequest (/app/projects/app/.next/server/chunks/6031.js:23:79572)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.k [as chatNode] (/app/projects/app/.next/server/chunks/303.js:92:1025)\n    at async Q (/app/projects/app/.next/server/chunks/303.js:92:5714)\n    at async Promise.all (index 0)\n    at async Promise.all (index 0)\n    at async T (/app/projects/app/.next/server/chunks/303.js:92:6569)\n    at async l (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2557)"}，这是运行日志，不知道是哪里的问题。
**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
在容器里，localhost是指向自身，并不会指向本地。如果你通过docker部署，应该是用容器IP或同网络的容器名来进行连接（可参数数据库连接）
