### ISSUE TITLE
465 version of the container reported an error that the config could not be read and permission was denied.

### ISSUE THREAD

**Issue by CityOx** [labring/FastGPT#665]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在问题出现前，使用威联通nas部署compose版的463版本，今天按照文档进行升级，采取步骤（升464→初始化（post响应代码200、容器无报错，系统网页进入正常）→更新config文件→升级465），此时465版的容器内报错无法读取config，权限被拒绝。

我尝试了：
1.给容器特权。仍然报错。
2.修改物理环境下config文件的读写权限给任何人，仍然报错后修改其所有者为999，还是一样报错。
3.修改compose中fastgpt版本464，回退到464版本，没改变其他设置。正常了。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Before the problem occurred, I used QNAP nas to deploy the 463 version of the compose version. Today I upgraded according to the documentation and took the steps (upgrade to 464 → initialization (post response code 200, no error in the container, and the system webpage entered normally) → update the config file → upgrade 465), at this time, an error is reported in the container of version 465 that the config cannot be read and permission is denied.

I tried:
1. Give the container privileges. Still getting error.
2. Modify the read and write permissions of the config file in the physical environment to anyone, and the error is still reported. After modifying its owner to 999, the error is still reported.
3. Modify fastgpt version 464 in compose and roll back to version 464 without changing other settings. Normal.

**Comment by CityOx** [comment]
问题解决了,不是fastgpt的锅.
是因为我手欠开启了威联通的"高级文件权限"功能,导致容器获取不到挂载文件.
如果你也遇到该问题,把这个功能关掉就ok.

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The problem is solved, it's not fastgpt's fault.
It's because I didn't turn on QNAP's "Advanced File Permissions" function, so the container couldn't get the mounted file.
If you also encounter this problem, turn off this function and it will be ok.
