### ISSUE TITLE
Failed to execute 'setItem' on 'Storage'

### ISSUE THREAD

**Issue by erweixin** [labring/FastGPT#666]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**

The zustand/middleware persist utilizes local storage to cache store data. In some scenarios, it may encounter limitations imposed by the browser's local storage capacity. Have you considered using [localforage](https://github.com/localForage/localForage) to address this issue? I can submit a pull request if needed.

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
This is a very good proposal and, if nothing else, should be able to be packaged directly into zustand middleware for use
