### ISSUE TITLE
Storage data time problem

### ISSUE THREAD

**Issue by winnie1228** [labring/FastGPT#667]
存储数据库的时间统一少8小时，请问有简便的方法调整吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The time to store the database is uniformly reduced by 8 hours. Is there an easy way to adjust it?

**Comment by c121914yu** [comment]
没必要改，linux时间本来就比北京少8小时，要改的话直接改镜像时区。容易造成定时任务错误。
