### ISSUE TITLE
Hello, I want to access fastgt normally on http://localhost:3000/test. Can this requirement be realized?

### ISSUE THREAD

**Issue by TheChalice** [labring/FastGPT#668]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
您好，我想在http://localhost:3000/test上正常访问fastgt，请问这个需求可以实现吗，我在next.config.js里加了 basePath: '/test',但这样就会让api全部404，请问您这边有什么好的解决方案吗
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
Hello, I want to access fastgt normally on http://localhost:3000/test. Can this requirement be achieved? I added basePath: '/test' to next.config.js, but this will make the api all 404, do you have any good solutions here?
**Application Scenario**

**Related Examples**

**Comment by c121914yu** [comment]
这个可以考虑 nginx 重定向。

**Comment by TheChalice** [comment]
请问是类似于这样写吗
server {
    listen 8888;

    server_name 10.1.251.131;


    location /test/ {
        rewrite ^/test/(.*)$ /$1 break;
        proxy

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is it written like this?
server {
    listen 8888;

    server_name 10.1.251.131;


    location /test/ {
        rewrite ^/test/(.*)$ /$1 break;
        proxy

**Comment by TheChalice** [comment]
请问可以这样写吗

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Could you please write it like this?

**Comment by TheChalice** [comment]
[nginx.conf.txt](https://github.com/labring/FastGPT/files/13806584/nginx.conf.txt)

**Comment by c121914yu** [comment]
> [nginx.conf.txt](https://github.com/labring/FastGPT/files/13806584/nginx.conf.txt)

估计不太行，在接口中使用的都是 / 的相对域名地址。

**Comment by c121914yu** [comment]
> > [nginx.conf.txt](https://github.com/labring/FastGPT/files/13806584/nginx.conf.txt)
> 
> 估计不太行，在接口中使用的都是 / 的相对域名地址。

我只设置过，拦截 /api，转向其他地方。
