### ISSUE TITLE
Load init config error TypeError: Cannot read properties of undefined (reading 'pluginBaseUrl')

### ISSUE THREAD

**Issue by shanjijian** [labring/FastGPT#671]
**例行检查**

- [yes ] 我已确认目前没有类似 issue
- [yes] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [yes ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [yes ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [yes] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [yes ] 私有部署版本: 3.3

**问题描述**
使用OrbStack模拟的Ubuntux64系统中，修改mongo版本为：4.4.26后，启动搭建，查看日志会报错：无法找到：pluginBaseUrl。
**复现步骤**
使用OrbStack模拟的Ubuntux64系统中，修改mongo版本为：4.4.26后，启动搭建，查看日志：
Load init config error TypeError: Cannot read properties of undefined (reading 'pluginBaseUrl')
    at h (/app/projects/app/.next/server/chunks/63697.js:1:4219)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async y (/app/projects/app/.next/server/chunks/63697.js:1:2674)
    at async f (/app/projects/app/.next/server/chunks/63697.js:1:1772)

**预期结果**
报错后页面可以正常启动，但是登录点击等操作会报错：Network Error。
**相关截图**
<img width="844" alt="image" src="https://github.com/labring/FastGPT/assets/42663412/fa4be84f-fb31-4b2e-9cac-9df0f7b6875e">

**Comment by cat-undertale** [comment]
我是今天更新拉取后也出现这个问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also had this problem after updating today.

**Comment by ymg2007** [comment]
我这边今天在sealos上部署了很多次都是这个报错，请问一下这个报错如何解决

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I deployed on sealos many times today and got this error. Could you please tell me how to solve this error?

**Comment by c121914yu** [comment]
改成最新配置文件就行

**Comment by c121914yu** [comment]
https://doc.fastgpt.in/docs/development/configuration/#466-alpha-%E7%89%88%E6%9C%AC%E5%AE%8C%E6%95%B4%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0 参考
