### ISSUE TITLE
After deploying docker compose using WSL2 UBUNTU22.4 and docker destop, I cannot log in as the root user. When observing in docker destop, I find that the image fastgpt keeps restarting indefinitely.

### ISSUE THREAD

**Issue by 871052165** [labring/FastGPT#674]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
使用WSL2 UBUNTU22.4和 docker destop部署docker compose后，无法使用root用户登录，在 docker destop中观察，发现镜像fastgpt一直在无限重启
**复现步骤**
按照docker compose步骤进行后，可以正常通过网页访问主页，但是无法进行登录，其他页面也无法点击，在docker destop中观察，可看到镜像一直在不断重启。
**预期结果**
可正常使用
**相关截图**
![微信截图_20231231122256](https://github.com/labring/FastGPT/assets/50550790/26ced678-9efb-4223-b7bf-c010803214cc)
![image](https://github.com/labring/FastGPT/assets/50550790/0610ad5c-7d2e-4b18-a37a-818a48cc850c)
![image](https://github.com/labring/FastGPT/assets/50550790/3ae5ffea-638a-4409-a7e3-f635fb02c3bd)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
After deploying docker compose using WSL2 UBUNTU22.4 and docker destop, I cannot log in as the root user. When observing in docker destop, I find that the image fastgpt keeps restarting indefinitely.
**Steps to reproduce**
After following the docker compose steps, you can access the homepage through the web page normally, but you cannot log in, and other pages cannot be clicked. Observing in docker destop, you can see that the image is constantly restarting.
**expected outcome**
Can be used normally
**Related screenshots**
![WeChat screenshot_20231231122256](https://github.com/labring/FastGPT/assets/50550790/26ced678-9efb-4223-b7bf-c010803214cc)
![image](https://github.com/labring/FastGPT/assets/50550790/0610ad5c-7d2e-4b18-a37a-818a48cc850c)
![image](https://github.com/labring/FastGPT/assets/50550790/3ae5ffea-638a-4409-a7e3-f635fb02c3bd)

**Comment by gitcitt1** [comment]
Linux Mint，本地docker-compose部署发生同样问题，部署后端口无法正常访问，并频繁拒绝链接，查看日志后发现不断重启

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Linux Mint, the same problem occurs in local docker-compose deployment. After deployment, the port cannot be accessed normally, and connections are frequently rejected. After checking the log, it is found that it keeps restarting.

**Comment by c121914yu** [comment]
重启前的日志看看，大概率是配置文件版本和镜像版本不对。

**Comment by gitcitt1** [comment]
非常感谢，确实是本地配置文件版本的落后，根据项目中的 https://github.com/labring/FastGPT/blob/main/projects/app/data/config.json 给出的config.json文件内容更新了本地配置文件之后成功部署了，没有重启问题出现，正常使用😘

**Comment by turing-bird** [comment]
> 显然，确实本地配置文件版本落后，根据目录中的https://github.com/labring/FastGPT/blob/main/projects/app/data/config.json给出的config.json文件内容更新了本地配置文件之后成功部署了，没有重启问题出现，正常使用😘

It’s been so long and it’s still wrong~~~~
