### ISSUE TITLE
Login-free external links are embedded in corporate WeChat, and users cannot provide feedback.

### ISSUE THREAD

**Issue by qingzhp** [labring/FastGPT#678]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
外链用户点击反馈，显示无权限；点赞功能正常

**复现步骤**
1.打开fastgpt外链
2.点击反馈，提示报错

**预期结果**
外链使用反馈功能正常

**相关截图**
![image](https://github.com/labring/FastGPT/assets/7796066/32d74460-fd3f-4de4-934d-ca2a653cfdcd)
![image](https://github.com/labring/FastGPT/assets/7796066/3a7434b3-4dfd-4524-9ff8-3f343242f1c3)
![image](https://github.com/labring/FastGPT/assets/7796066/ed15d108-581f-49e4-9fc8-d0fd7e077f29)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**

**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/685
这个pr中修复了
