### ISSUE TITLE
External usage of FastGPT application—API access 504 Gateway Time-out

### ISSUE THREAD

**Issue by ZhiyuXu0124** [labring/FastGPT#681]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在使用FastGPT应用外部使用途径的API访问时，我的一个应用整体运行时间较长大约50s左右，通过API请求会返回:
```html
<html>

<head>
    <title>504 Gateway Time-out</title>
</head>

<body>
    <center>
        <h1>504 Gateway Time-out</h1>
    </center>
    <hr>
    <center>nginx</center>
</body>

</html>
```
但使用服务后台都是正常的，请求可以在应用的对话日志中看到。我切换至其他耗时10秒左右的应用时，均可以正常访问。
是否可以开放nginx超时相关的配置？

**复现步骤**
通过API POST请求一个耗时过长（超过1分钟）的应用即可

**预期结果**
可以开放nginx超时相关的配置
或者API调用不限制响应时间

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
When using API access from outside the FastGPT application, the overall running time of one of my applications is about 50 seconds, and the API request will return:
```html
<html>

<head>
    <title>504 Gateway Time-out</title>
</head>

<body>
    <center>
        <h1>504 Gateway Time-out</h1>
    </center>
    <hr>
    <center>nginx</center>
</body>

</html>
```
However, it is normal to use the service background, and the request can be seen in the application's conversation log. When I switch to other applications that take about 10 seconds, I can access them normally.
Is it possible to open nginx timeout related configuration?

**Steps to reproduce**
Just request an application that takes too long (more than 1 minute) through API POST

**expected outcome**
```html
<html>

<head>
    <title>504 Gateway Time-out</title>
</head>

<body>
    <center>
        <h1>504 Gateway Time-out</h1>
    </center>
    <hr>
    <center>nginx</center>
</body>

</html>
```

**Related screenshots**

**Comment by c121914yu** [comment]
响应时长是客户端配置的，，和fastgpt没有关系。。

**Comment by mengdahuang** [comment]
我也遇到同样的问题
