### ISSUE TITLE
gpt chat error report

### ISSUE THREAD

**Issue by wgyuuu** [labring/FastGPT#683]
Could not parse message into JSON: {"id":"chatcmpl-8cmdvebyMOfuH5UCDgpkWlZeus0XD","object":"chat.completion.chunk","created":1704254139,"model":"gpt-35-turbo","choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}
{"id":"chatcmpl-8cmdvebyMOfuH5UCDgpkWlZeus0XD","object":"chat.completion.chunk","created":1704254139,"model":"gpt-35-turbo","choices":[{"index":0,"delta":{"content":"你"},"finish_reason":null}]}
From chunk: [
  'data: {"id":"chatcmpl-8cmdvebyMOfuH5UCDgpkWlZeus0XD","object":"chat.completion.chunk","created":1704254139,"model":"gpt-35-turbo","choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}',
  'data: {"id":"chatcmpl-8cmdvebyMOfuH5UCDgpkWlZeus0XD","object":"chat.completion.chunk","created":1704254139,"model":"gpt-35-turbo","choices":[{"index":0,"delta":{"content":"你"},"finish_reason":null}]}'
]
[ERROR] 2024-01-03 03:55:39 sse error: Unexpected token { in JSON at position 212: {"stack":"SyntaxError: Unexpected token { in JSON at position 212\n    at JSON.parse (<anonymous>)\n    at eK.r [as iterator] (/app/projects/app/.next/server/chunks/66031.js:23:69327)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async x (/app/projects/app/.next/server/chunks/20303.js:92:2273)\n    at async /app/projects/app/.next/server/chunks/20303.js:92:1302\n    at async Object.k [as chatNode] (/app/projects/app/.next/server/chunks/20303.js:92:1265)\n    at async Q (/app/projects/app/.next/server/chunks/20303.js:92:5761)\n    at async Promise.all (index 0)\n    at async Promise.all (index 0)\n    at async T (/app/projects/app/.next/server/chunks/20303.js:92:6616)\n    at async /app/projects/app/.next/server/pages/api/v1/chat/completions.js:1:7460"}

**Comment by wgyuuu** [comment]
我是docker部署的，页面上能显示出内容，但是报错了。  日志如上
![image](https://github.com/labring/FastGPT/assets/9672924/31dbacce-8276-436a-a38c-f4be06c5a80c)

**Comment by c121914yu** [comment]
看着是gpt接口响应问题，返回的格式有bug。检查自己的渠道~
