### ISSUE TITLE
how to enable voice input？

### ISSUE THREAD

**Issue by WyHy** [labring/FastGPT#687]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.6.4

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
无法使用语言输入功能，点击按钮没有任何反应，只出现了“语音输入”这样一个小tips
我从4.6一直升级到4.6.4，其他功能正常，包括gpt4v的文件上传功能，但是就是这个语音输入到现在都没搞明白如何使用
我用的是chrome浏览器，切换到safari也是一样，点击没有反应，我说的反应指的是可以向微信或者chatgpt客户端那样出现音频变化可以接受讲话内容

**复现步骤**

**预期结果**
语音功能正常使用

**相关截图**
![07](https://github.com/labring/FastGPT/assets/13045015/c88feed6-5cd4-4d2a-9995-13260952edf8)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**
v4.6.4

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
The language input function cannot be used. There is no response when clicking the button. Only a small tip like "voice input" appears.
I have upgraded from 4.6 to 4.6.4. Other functions are normal, including the file upload function of gpt4v, but I still don’t understand how to use this voice input.
I am using the Chrome browser, and it is the same when switching to Safari. There is no response when clicking. The response I am talking about means that the audio changes like WeChat or chatgpt clients and the speech content can be accepted.

**Steps to reproduce**

**expected outcome**
Voice function works normally

**Related screenshots**
![07](https://github.com/labring/FastGPT/assets/13045015/c88feed6-5cd4-4d2a-9995-13260952edf8)

**Comment by c121914yu** [comment]
可能系统不支持吧，后面再关注下~ 我这点了有特效的：
![image](https://github.com/labring/FastGPT/assets/50446880/c07183bd-0723-420a-94b5-ca51cd7330b4)

**Comment by WyHy** [comment]
> 可能系统不支持吧，后面再关注下~ 我这点了有特效的： ![image](https://private-user-images.githubusercontent.com/50446880/294084561-c07183bd-0723-420a-94b5-ca51cd7330b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDQ5NTIsIm5iZiI6MTcwNDM0NDY1MiwicGF0aCI6Ii81MDQ0Njg4MC8yOTQwODQ1NjEtYzA3MTgzYmQtMDcyMy00MjBhLTk0YjUtY2E1MWNkNzMzMGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA1MDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzdiODhjYTE0YTY2OTAyM2M4MzViZjYzMDUwNWY0NDhkZWUwOWQxZWVlOTBjZjM0NjlmOWRmNWMyMWE0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4nEBezDMguMcdKmKEgO8FnqLVum7RZmlaLFFRKLbwQ)

服务是在Centos上基于docker-compose部署的，
使用的话我是 MacOS Ventura 13.1，Chrome 是 120.0.6099.129版本，换成别的windows的电脑，也是相同的问题，点击没啥反应，是我部署的有问题吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Maybe the system does not support it, please pay attention later~ I clicked this and it has special effects: ![image](https://private-user-images.githubusercontent.com/50446880/294084561-c07183bd-0723-420a-94b5 -ca51cd7330b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..p4nEBezDMguMcdKmKEgO8FnqLVum7RZmlaLFFRKLbwQ)

The service is deployed based on docker-compose on Centos.
I am using MacOS Ventura 13.1, and Chrome is version 120.0.6099.129. When I switch to another Windows computer, the same problem occurs. There is no response when clicking. Is there something wrong with my deployment?

**Comment by leoterry-ulrica** [comment]
需要是https协议，或者修改浏览器安全设置。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It needs to be https protocol or modify the browser security settings.

**Comment by WyHy** [comment]
> 需要是https协议，或者修改浏览器安全设置。

哇，解决了，确实是浏览器安全限制的原因，感谢感谢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Need to use https protocol, or modify browser security settings.

Wow, it’s solved. It’s indeed due to browser security restrictions. Thank you.

**Comment by deerleo** [comment]
<img width="405" alt="image" src="https://github.com/labring/FastGPT/assets/1190377/c1bde6f4-65af-4bba-a47d-84fb61e331ef">

你这个加了文件上传功能吗？

**Comment by 03tommysad** [comment]
> > 需要是https协议，或者修改浏览器安全设置。
> 
> 哇，解决了，确实是浏览器安全限制的原因，感谢感谢

这个浏览器要怎么修改呀，呜呜不太会

**Comment by nightzjp** [comment]
> > > 需要是https协议，或者修改浏览器安全设置。
> > 
> > 
> > 哇，解决了，确实是浏览器安全限制的原因，感谢感谢
> 
> 这个浏览器要怎么修改呀，呜呜不太会

当前页面，浏览器输入栏左侧有”不安全“提示，点进去之后选”网站设置“，”不安全内容“。

**Comment by ifkd111** [comment]
> 需要是https协议，或者修改浏览器安全设置。

怎么做？大佬求教学

**Comment by ifkd111** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue
> * [x]  我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
> * [x]  我使用了自己的 key，并确认我的 key 是可正常使用的
> * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本** v4.6.4
> 
> * [ ]  公有云版本
> * [x]  私有部署版本
> 
> **问题描述** 无法使用语言输入功能，点击按钮没有任何反应，只出现了“语音输入”这样一个小tips 我从4.6一直升级到4.6.4，其他功能正常，包括gpt4v的文件上传功能，但是就是这个语音输入到现在都没搞明白如何使用 我用的是chrome浏览器，切换到safari也是一样，点击没有反应，我说的反应指的是可以向微信或者chatgpt客户端那样出现音频变化可以接受讲话内容
> 
> **复现步骤**
> 
> **预期结果** 语音功能正常使用
> 
> **相关截图** ![07](https://private-user-images.githubusercontent.com/13045015/293919388-c88feed6-5cd4-4d2a-9995-13260952edf8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE5MjQsIm5iZiI6MTcxNjQ1MTYyNCwicGF0aCI6Ii8xMzA0NTAxNS8yOTM5MTkzODgtYzg4ZmVlZDYtNWNkNC00ZDJhLTk5OTUtMTMyNjA5NTJlZGY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA4MDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YTMwMzI3Y2U4ODA3OTkwNzdmYzEzMDZjOGIxZTViZTgzNjFhYWEzMGIwM2ViOTVkMGNkN2IzNmU3ZGRkOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ERnl2xYCWStvN1jT9t353oo7SEJO9XCh5n3mD0eTrrY)

请问gpt4v上传文件功能怎么实现？我模型用千问l可以吗

**Comment by wsy2510741927** [comment]
> > > > 修改需要是https协议，或者浏览器安全设置。
> > > 
> > > 
> > > 哇，解决了，确实是浏览器安全限制的原因，谢谢谢谢
> > 
> > 
> > 浏览这个器要怎么修改呀，呜呜不太会
> 
> 当前页面，浏览器输入栏左侧有“不安全”提示，点进去之后选择“网站设置”，“不安全内容”。

![Image](https://github.com/user-attachments/assets/51716580-101f-4503-85df-3a58ea61a906)  浏览器上确实显示是禁止，但是不能选择允许是为什么  ？
