### ISSUE TITLE
Semantic retrieval and advanced orchestration test search structures display differently

### ISSUE THREAD

**Issue by dadastory** [labring/FastGPT#691]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**
在知识库中进行搜索测试，测试结果勉强准确，但是在实际应用中的高级编排中进行测试发现，对话实际搜索出来的引用和知识库中的完全不同，不清楚是不是语义搜索的bug
**复现步骤**

**预期结果**
知识库中的搜索测试应当与实际对话中的知识库引用结果一致
**相关截图**
![image](https://github.com/labring/FastGPT/assets/84147842/13583057-c912-44c9-9e51-03becda2d9e4)
![image](https://github.com/labring/FastGPT/assets/84147842/79151cc3-7444-45a8-8d15-a47df50ef273)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x ] I have confirmed that there is currently no similar issue
- [
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
A search test was conducted in the knowledge base, and the test results were barely accurate. However, when tested in advanced orchestration in actual applications, it was found that the references actually searched for in the conversation were completely different from those in the knowledge base. It was not clear whether it was a semantic search bug.
**Steps to reproduce**

**expected outcome**
Search tests in the knowledge base should match knowledge base citations in actual conversations
**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/84147842/13583057-c912-44c9-9e51-03becda2d9e4)
![image](https://github.com/labring/FastGPT/assets/84147842/79151cc3-7444-45a8-8d15-a47df50ef273)

**Comment by c121914yu** [comment]
看有没有包含就行，不用看顺序

**Comment by dadastory** [comment]
> 看有没有包含就行，不用看顺序

没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Just check to see if it is included, no need to look at the order.

It is not included. The actual chat citations are not even as good as those in the knowledge base search test. It feels a bit wrong.

**Comment by dadastory** [comment]
补充一下是从latest版本更新到最新的v4.6.6-alpha  请问这块搜索内容是否最近有啥更改吗？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I would like to add that it is updated from the latest version to the latest v4.6.6-alpha. Is there any recent change in this search content?

**Comment by c121914yu** [comment]
> > 看有没有包含就行，不用看顺序
> 
> 没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴

没有。你看看是不是用了文本补全

**Comment by dadastory** [comment]
我个人有个想法不知道可不可以行，就是将QA问题放到ES中，然后将搜索结果的索引喂给GPT进行相似度排序，这种方式我觉得可能比目前语义排序的准确而且稍微好点

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I personally have an idea, I don’t know if it is feasible, which is to put the QA questions into ES, and then feed the index of the search results to GPT for similarity sorting. I think this method may be more accurate and slightly better than the current semantic sorting.

**Comment by dadastory** [comment]
> > > 看有没有包含就行，不用看顺序
> > 
> > 
> > 没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴
> 
> 没有。你看看是不是用了文本补全

没有用到，而且我的组件里面貌似也没有聊天记录的组件

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > Just check whether it is included, not the order.
>>
>>
> > It is not included. The actual chat citations are not even as good as those in the knowledge base search test. It feels a bit wrong.
>
>No. Check to see if text completion is used

Not used, and it seems that there is no chat record component in my component.

**Comment by c121914yu** [comment]
> > > > 看有没有包含就行，不用看顺序
> > > 
> > > 
> > > 没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴
> > 
> > 
> > 没有。你看看是不是用了文本补全
> 
> 没有用到，而且我的组件里面貌似也没有聊天记录的组件

不需要了。有测试数据集么

**Comment by dadastory** [comment]
> > > 看有没有包含就行，不用看顺序
> > 
> > 
> > 没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴
> 
> 没有。你看看是不是用了文本补全
请问是否是问题分类组件影响的呢？
![image](https://github.com/labring/FastGPT/assets/84147842/2b4d2ecd-b9b2-430a-b501-efe0cba4ef91)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > Just check whether it is included, not the order.
>>
>>
> > It is not included. The actual chat citations are not even as good as those in the knowledge base search test. It feels a bit wrong.
>
>No. Check to see if text completion is used
Is it affected by the problem classification component?
![image](https://github.com/labring/FastGPT/assets/84147842/2b4d2ecd-b9b2-430a-b501-efe0cba4ef91)

**Comment by c121914yu** [comment]
> > > > 看有没有包含就行，不用看顺序
> > > 
> > > 
> > > 没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴
> > 
> > 
> > 没有。你看看是不是用了文本补全
> > 请问是否是问题分类组件影响的呢？
> > ![image](https://private-user-images.githubusercontent.com/84147842/294218178-2b4d2ecd-b9b2-430a-b501-efe0cba4ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODEyMjUsIm5iZiI6MTcwNDM4MDkyNSwicGF0aCI6Ii84NDE0Nzg0Mi8yOTQyMTgxNzgtMmI0ZDJlY2QtYjliMi00MzBhLWI1MDEtZWZlMGNiYTRlZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWFlMzc0YTUzMGQyMDcyNDc4YjUyZDRhZTBhMDQxNTBmNGY2NjEyOGYwZTg4NGQxMWE4MGRiZGYzYzI3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Dc5kVTxchjhJnKnPrVm34yheowED-zDoGdW5IoGxd8)

这明显不对，为什么要把分类连接过去么？这不变成搜分类的内容了么

**Comment by dadastory** [comment]
> > > > > 看有没有包含就行，不用看顺序
> > > > 
> > > > 
> > > > 没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴
> > > 
> > > 
> > > 没有。你看看是不是用了文本补全
> > > 请问是否是问题分类组件影响的呢？
> > > ![image](https://private-user-images.githubusercontent.com/84147842/294218178-2b4d2ecd-b9b2-430a-b501-efe0cba4ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODEyMjUsIm5iZiI6MTcwNDM4MDkyNSwicGF0aCI6Ii84NDE0Nzg0Mi8yOTQyMTgxNzgtMmI0ZDJlY2QtYjliMi00MzBhLWI1MDEtZWZlMGNiYTRlZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWFlMzc0YTUzMGQyMDcyNDc4YjUyZDRhZTBhMDQxNTBmNGY2NjEyOGYwZTg4NGQxMWE4MGRiZGYzYzI3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Dc5kVTxchjhJnKnPrVm34yheowED-zDoGdW5IoGxd8)
> 
> 这明显不对，为什么要把分类连接过去么？这不变成搜分类的内容了么

原来是这样，我理解了，这么晚了还麻烦你，非常感谢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > > > Just check whether it is included, not the order.
> > > >
> > > >
> > > > It is not included. The actual chat citations are not even as good as those in the knowledge base search test. It feels a bit wrong.
>>>
>>>
> > > No. Check to see if text completion is used
> > > Is it affected by the problem classification component?
> > > ![image](https://private-user-images.githubusercontent.com/84147842/294218178-2b4d2ecd-b9b2-430a-b501-efe0cba4ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ naXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODEyMjUsIm5iZiI6MTcwNDM4MDkyNSwicGF0aCI6Ii84NDE0Nzg0Mi8yOTQyMT gxNzgtMmI0ZDJlY2QtYjliMi00MzBhLWI1MDEtZWZlMGNiYTRlZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJ TJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWFlMzc0YTUz MGQyMDcyNDc4YjUyZDRhZTBhMDQxNTBmNGY2NjEyOGYwZTg4NGQxMWE4MGRiZGYzYzI3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Dc5k VTxchjhJnKnPrVm34yheowED-zDoGdW5IoGxd8)
>
> This is obviously wrong. Why should the categories be connected? Doesn’t this become the content of the search category?

So that’s it, I understand, I’m still bothering you so late, thank you very much

**Comment by c121914yu** [comment]
> > > > > > 看有没有包含就行，不用看顺序
> > > > > 
> > > > > 
> > > > > 没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴
> > > > 
> > > > 
> > > > 没有。你看看是不是用了文本补全
> > > > 请问是否是问题分类组件影响的呢？
> > > > ![image](https://private-user-images.githubusercontent.com/84147842/294218178-2b4d2ecd-b9b2-430a-b501-efe0cba4ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODEyMjUsIm5iZiI6MTcwNDM4MDkyNSwicGF0aCI6Ii84NDE0Nzg0Mi8yOTQyMTgxNzgtMmI0ZDJlY2QtYjliMi00MzBhLWI1MDEtZWZlMGNiYTRlZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWFlMzc0YTUzMGQyMDcyNDc4YjUyZDRhZTBhMDQxNTBmNGY2NjEyOGYwZTg4NGQxMWE4MGRiZGYzYzI3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Dc5kVTxchjhJnKnPrVm34yheowED-zDoGdW5IoGxd8)
> > 
> > 
> > 这明显不对，为什么要把分类连接过去么？这不变成搜分类的内容了么
> 
> 原来是这样，我理解了，这么晚了还麻烦你，非常感谢

完整响应里的知识库搜索，可以看到实际传入的搜索词。

**Comment by dadastory** [comment]
> > > > > > > 看有没有包含就行，不用看顺序
> > > > > > 
> > > > > > 
> > > > > > 没有包含，实际聊天的引用甚至不如知识库搜索测试里面的，感觉有点牛头不对马嘴
> > > > > 
> > > > > 
> > > > > 没有。你看看是不是用了文本补全
> > > > > 请问是否是问题分类组件影响的呢？
> > > > > ![image](https://private-user-images.githubusercontent.com/84147842/294218178-2b4d2ecd-b9b2-430a-b501-efe0cba4ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODEyMjUsIm5iZiI6MTcwNDM4MDkyNSwicGF0aCI6Ii84NDE0Nzg0Mi8yOTQyMTgxNzgtMmI0ZDJlY2QtYjliMi00MzBhLWI1MDEtZWZlMGNiYTRlZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWFlMzc0YTUzMGQyMDcyNDc4YjUyZDRhZTBhMDQxNTBmNGY2NjEyOGYwZTg4NGQxMWE4MGRiZGYzYzI3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Dc5kVTxchjhJnKnPrVm34yheowED-zDoGdW5IoGxd8)
> > > 
> > > 
> > > 这明显不对，为什么要把分类连接过去么？这不变成搜分类的内容了么
> > 
> > 
> > 原来是这样，我理解了，这么晚了还麻烦你，非常感谢
> 
> 完整响应里的知识库搜索，可以看到实际传入的搜索词。

好的，我理解错了，请问后续语义搜索可以支持用ES吗？我个人是做java开发的，不清楚能不能贡献一份力

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > > > > > Just check whether it is included, not the order.
> > > > > >
> > > > > >
> > > > > > It is not included. The actual chat citations are not even as good as those in the knowledge base search test. It feels a bit wrong.
> > > > >
> > > > >
> > > > > No. Check to see if text completion is used
> > > > > Is it affected by the problem classification component?
> > > > > ![image](https://private-user-images.githubusercontent.com/84147842/294218178-2b4d2ecd-b9b2-430a-b501-efe0cba4ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiO iJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODEyMjUsIm5iZiI6MTcwNDM4MDkyNSwicGF0aCI6Ii84NDE0Nzg0Mi8yOTQ yMTgxNzgtMmI0ZDJlY2QtYjliMi00MzBhLWI1MDEtZWZlMGNiYTRlZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFp BJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWFlMzc0Y TUzMGQyMDcyNDc4YjUyZDRhZTBhMDQxNTBmNGY2NjEyOGYwZTg4NGQxMWE4MGRiZGYzYzI3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Dc 5kVTxchjhJnKnPrVm34yheowED-zDoGdW5IoGxd8)
>>>
>>>
> > > This is obviously wrong. Why should the categories be connected? Doesn’t this become the content of the search category?
>>
>>
> > So that’s it, I understand, I’m bothering you so late, thank you very much
>
> Knowledge base search in the complete response, you can see the actual incoming search terms.

Okay, I misunderstood. Can ES be supported for subsequent semantic searches? I personally do Java development, I don’t know if I can contribute.

**Comment by dadastory** [comment]
已经解决，错误理解输入参数含义。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Solved, misunderstanding the meaning of input parameters.
