### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ygxiuming** [labring/FastGPT#706]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x ] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x ] 私有部署版本

**问题描述**
使用docker部署，与chatglm3接入，但是在启动容器登陆后，一切正常，但是当我把网络断掉，在局域网运行时，发现所有的功能都无法运行，例如：创建应用，创建知识库等等，都将卡在创建的页面。当网络重新连接时，一切功能又恢复如初，我想在局域网中运行。

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ x ] I have confirmed that there is currently no similar issue
- [ x ] I have reviewed the project README in full, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ x ] I used my own key and confirmed that my key can be used normally
- [ x ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ x ] private deployment version

**Problem Description**
Use docker to deploy and connect to chatglm3, but after starting the container and logging in, everything is normal. However, when I disconnect the network and run it on the LAN, I find that all functions cannot run, such as creating applications, creating knowledge bases, etc. , will all be stuck on the created page. When the network reconnects, everything functions as before and I want to run it on the LAN.

**Steps to reproduce**


**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
不太确定你的具体细节。我这边可以纯内网运行。
