### ISSUE TITLE
There is a problem with the new version of m3e and it gets stuck when building the knowledge base.

### ISSUE THREAD

**Issue by xs818818** [labring/FastGPT#707]
老版本没问题，但是更新后，m3e容器接口报422错误

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
There is no problem with the old version, but after the update, the m3e container interface reports a 422 error

**Comment by xs818818** [comment]
4.6.5没问题，4.6.6开始不行

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
No problem with 4.6.5, but not working with 4.6.6

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/693
