### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sunlin-xiaonai** [labring/FastGPT#714]
本地部署录入数据和查询时候，一直出现 RangeError: Maximum call stack size exceeded 错误。pg 链接不稳定
![image](https://github.com/labring/FastGPT/assets/129371884/b8a21605-74a0-4332-9000-4ff6393f2c46)

**Comment by yaoyaoio** [comment]
我昨天也遇到这个问题了。我这边是因为env里的PG配置不正确。没有成功连接上PG。也没有成功打印console.log('init pg successful');所以你可以看看是否和我的问题一样。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also encountered this problem yesterday. On my side, it's because the PG configuration in env is incorrect. Failed to connect to PG. It also failed to print console.log('init pg successful'); so you can see if it is the same problem as mine.

**Comment by c121914yu** [comment]
和不稳定没关系，完全就是没成功连接上。

**Comment by c121914yu** [comment]
检查对应的数据库有没有成功运行，以及连接参数是否正确。
