### ISSUE TITLE
In external link mode, when the user clicks the feedback button to submit feedback content, it prompts that there is no permission.

### ISSUE THREAD

**Issue by aaronuu** [labring/FastGPT#718]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 私有部署版本

**问题描述**
外链模式下，用户点击反馈按钮，提示无权限

**复现步骤**
外链模式下，用户点击反馈按钮，提示无权限

**预期结果**
成功提交反馈内容

**相关截图**
<img width="411" alt="image" src="https://github.com/labring/FastGPT/assets/3114397/62dd8679-b93f-4b4b-a9de-3abd17eb2752">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [x] Private deployment version

**Problem Description**
In the external link mode, when the user clicks the feedback button, it prompts that there is no permission.

**Steps to reproduce**
In the external link mode, when the user clicks the feedback button, it prompts that there is no permission.

**expected outcome**
Feedback submitted successfully

**Related screenshots**
<img width="411" alt="image" src="https://github.com/labring/FastGPT/assets/3114397/62dd8679-b93f-4b4b-a9de-3abd17eb2752">

**Comment by aaronuu** [comment]
最新版本v4.6.6

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The latest version v4.6.6

**Comment by c121914yu** [comment]
4.6.6正式版已经解决了呢，之前已经提过了。

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/f1788851-9335-4564-bffb-4d2326f89205)
