### ISSUE TITLE
After upgrading to 4.6.6, the locally deployed embedding reports error 422

### ISSUE THREAD

**Issue by USTC-Wentao-Yang** [labring/FastGPT#721]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**

**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by USTC-Wentao-Yang** [comment]
本地部署的embedding 在数据入库的时候报错 422

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Locally deployed embedding reports error 422 when data is entered into the database.

**Comment by c121914yu** [comment]
正式版已经修复了这个问题，不知道你是什么版本。

**Comment by c121914yu** [comment]
> 正式版已经修复了这个问题，不知道你是什么版本。

https://github.com/labring/FastGPT/pull/693

**Comment by WilliamYWT** [comment]
> > 正式版已经修复了这个问题，不知道你是什么版本。
> 
> #693

最新的main，对话的时候使用embedding没有问题，但是数据库插入数据报错422

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > This problem has been fixed in the official version. I don’t know which version you have.
>
> #693

The latest main, there is no problem using embedding during dialogue, but the database inserts data and reports error 422

**Comment by c121914yu** [comment]
> embedding

目前没法复现这个问题~ 看社区很多已经正常用着了。希望有更多日志
