### ISSUE TITLE
Knowledge Base There is no response when creating a new folder, and an error occurs when adding a new knowledge base.

### ISSUE THREAD

**Issue by albert045** [labring/FastGPT#732]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
V4.6.6
- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
升级V4.6.6后删除了原有知识库，新创建文件夹没反应，新加入知识库时报错。

**复现步骤**
点击知识库，点击新建，点击文件夹，输入1，点击确认。无响应。
点击知识库，点击新建，点击知识库，报错见最后截图。

**预期结果**
正常执行

**相关截图**
![image](https://github.com/labring/FastGPT/assets/11400951/194a0594-90fe-47c0-9817-f156777bedbe)
知识库位置
![image](https://github.com/labring/FastGPT/assets/11400951/378df85c-3101-4bd3-acbc-bd93eb9d8af2)
新建文件夹错误截图
![image](https://github.com/labring/FastGPT/assets/11400951/53d769cb-32c1-40bf-82c5-d1c3c925f54b)
新建知识库错误截图

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**
V4.6.6
- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
After upgrading to V4.6.6, the original knowledge base was deleted, the newly created folder did not respond, and an error occurred when adding a new knowledge base.

**Steps to reproduce**
Click Knowledge Base, click New, click Folder, enter 1, and click Confirm. No response.
Click Knowledge Base, click New, click Knowledge Base, see the last screenshot for error reporting.

**expected outcome**
Normal execution

**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/11400951/194a0594-90fe-47c0-9817-f156777bedbe)
Knowledge base location
![image](https://github.com/labring/FastGPT/assets/11400951/378df85c-3101-4bd3-acbc-bd93eb9d8af2)
New folder error screenshot
![image](https://github.com/labring/FastGPT/assets/11400951/53d769cb-32c1-40bf-82c5-d1c3c925f54b)
Screenshot of the error in creating a new knowledge base

**Comment by c121914yu** [comment]
配置文件问题，自个检查配置文件是否加载
