### ISSUE TITLE
How to use the remake rerank model

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [labring/FastGPT#734]
我在fastGPT的config.json中成功配置了对应的参数，但是在创建应用完成后，reRank模型对应的docker日志中没有任何显示，如何解决
使用了one api作为chatglm3(本地部署)与m3e(docker容器)的代理接口，reRank是本地192.168.7.104的docker部署
![image](https://github.com/labring/FastGPT/assets/87591236/9c75c5c9-3108-436e-9696-fc96a514fed0)
![image](https://github.com/labring/FastGPT/assets/87591236/9a1c56d1-b355-473c-a912-58ae3f90af20)
![image](https://github.com/labring/FastGPT/assets/87591236/574eef7b-a90d-4972-bb0a-fe6dbd8cf60a)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I successfully configured the corresponding parameters in fastGPT's config.json, but after creating the application, nothing is displayed in the docker log corresponding to the reRank model. How to solve this problem?
One api is used as the proxy interface for chatglm3 (local deployment) and m3e (docker container), reRank is the local docker deployment of 192.168.7.104
![image](https://github.com/labring/FastGPT/assets/87591236/9c75c5c9-3108-436e-9696-fc96a514fed0)
![image](https://github.com/labring/FastGPT/assets/87591236/9a1c56d1-b355-473c-a912-58ae3f90af20)
![image](https://github.com/labring/FastGPT/assets/87591236/574eef7b-a90d-4972-bb0a-fe6dbd8cf60a)

**Comment by c121914yu** [comment]
和创建知识库没关系~ 这是检索时候才用的。
