### ISSUE TITLE
Version 4.6.6 Knowledge Base Q&A, the first answer is that the ChatGLM3 model is called normally, and the second answer is that the model is not called according to the configuration (openai is called). I want to know the reason?

### ISSUE THREAD

**Issue by surfboy2000** [labring/FastGPT#736]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**V4.6.6

- [ ] 公有云版本
- [ ] 私有部署版本 私有

**问题描述**
4.6.6版知识库问答，第一次回答正常调用ChatGLM3模型，第二次回答未按配置调用模型（调用了openai），想知道是什么原因？
点击保存并预览，重复循环问题现象
**复现步骤**

**预期结果**
回答正常调用ChatGLM3模型
**相关截图**
![1](https://github.com/labring/FastGPT/assets/52144375/d37ddd65-94cd-4c63-b97b-fb3a80994de5)
![2](https://github.com/labring/FastGPT/assets/52144375/d2aee7e8-d6f7-4eaf-927c-44975bc5458d)
![3](https://github.com/labring/FastGPT/assets/52144375/f9485c84-50d1-4e69-98c5-9391d274cfb0)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**V4.6.6

- [ ] Public cloud version
- [ ] private deployment version private

**Problem Description**
In the knowledge base Q&A version 4.6.6, the first answer is that the ChatGLM3 model is called normally, and the second answer is that the model is not called according to the configuration (openai is called). I want to know the reason?
Click Save and Preview to repeat the loop problem phenomenon
**Steps to reproduce**

**expected outcome**
Answer Normal call to ChatGLM3 model
**Related screenshots**
![1](https://github.com/labring/FastGPT/assets/52144375/d37ddd65-94cd-4c63-b97b-fb3a80994de5)
![2](https://github.com/labring/FastGPT/assets/52144375/d2aee7e8-d6f7-4eaf-927c-44975bc5458d)
![3](https://github.com/labring/FastGPT/assets/52144375/f9485c84-50d1-4e69-98c5-9391d274cfb0)

**Comment by surfboy2000** [comment]
单独新建一个基于chatglm3的AI对话，没有问题。该问题出在知识库的应用中

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
There is no problem in creating a new AI conversation based on chatglm3. The problem lies in the application of knowledge base

**Comment by swingsun888** [comment]
我也是遇到同样的问题，第2此对话就报接口错误，如何解决！

**Comment by dabaoshu** [comment]
同样是这个问题版本debugger到代码是把输入的文本在这个执行步骤发生了替换成为了""
![image](https://github.com/labring/FastGPT/assets/56434860/93abe56a-c9d2-46ac-9a79-d2281bc20295)

**Comment by c121914yu** [comment]
没有修改索引模型为glm3，检查一遍配置文件就会看到gpt模型了。
