### ISSUE TITLE
Can the debugging preview in advanced orchestration stop or continue directly from a certain module? Starting from the beginning every time is a bit cumbersome for a large number of modules.

### ISSUE THREAD

**Issue by xinggonglie** [labring/FastGPT#737]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
就相当于在某一个模块的地方有一个“重新发送”的按钮，可以把prompt重新发送一遍，然后就按照新修改的模块运行
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
It is equivalent to having a "resend" button in a certain module. You can resend the prompt and then run it according to the newly modified module.
**Application Scenario**

**Related Examples**

**Comment by c121914yu** [comment]
debug模式是有计划Q2实现。
不过你说的修改模块后还能保留之前的数据，这点后续会评估下。

**Comment by c121914yu** [comment]
忘记关联，4.8已经有了
