### ISSUE TITLE
After all concurrency is set to 1, the 5 dollar number still reports 429

### ISSUE THREAD

**Issue by Adsryen** [labring/FastGPT#739]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ √ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ √] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [  √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [  √] 私有部署版本

**问题描述**

并发全部设为1后，5刀号仍然报429，oneapi面板日志，FastGPT已经成功调用了模型，知识库成功有70+的索引，在等待就绪后，知识库的集合仍然为0，这个是否能从根源解决问题，key的使用上还有很大的提升

可接受时间慢点，也不接受时间也等了，也就绪了，然而没有出现数据

是否可以多等待5刀号的成功调用呢

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [√] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [√] I used my own key and confirmed that my key can be used normally
- [√] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [√] Private deployment version

**Problem Description**

After the concurrency is all set to 1, the number 5 still reports 429. In the oneapi panel log, FastGPT has successfully called the model, and the knowledge base successfully has 70+ indexes. After waiting for it to be ready, the collection of the knowledge base is still 0. Is this possible? Solve the problem from the root, and there is still a big improvement in the use of keys.

It is acceptable for the time to be slower, but it is not acceptable for the time to wait and it is ready, but no data appears.


Can we wait longer for the successful call of the 5 dollar number?


**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
没有意愿去做限流控制，限流基本不可用，没啥意义。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
If the 5-dollar account is available, there is no need to limit the flow. In fact, the 5-dollar ordinary account model is fully supported. The main reason is that the account speed is slightly slower and is lost by the fast program 429.

So this can be completely controlled on the program side, instead of forcing you to change to a better and faster account.

**Comment by c121914yu** [comment]
> 如果5刀号可用的话，就没有限流的必要了，其实5刀普通账号的模型是完全支持的，主要就是账号的速率稍微慢了，就被fast程序429丢掉了
> 
> 所以完全这个可以在程序这边控制，而不是非得强制性去更换更好更快的账号

对使用者来说，5 刀等于不可用。所以没必要支持。
