### ISSUE TITLE
http module rectification

### ISSUE THREAD

**Issue by MS-zh** [labring/FastGPT#744]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
1. http模块无法接收IMG格式的返回信息
2. http模块反馈信息必须用字段接收，无法定义多字段用一个出参口
3. http模块出差字段为json时，例如示例数据中取key为data时，出参为json对象，无法被其他模块的入参接收到。建议加一个传入非字符串会自动转换为字符串的中转模块，类似指定回复模块。
  示例数据 {  "message": "message", 
      "data": {    "name": "name",    
      "age": 10 }}
**应用场景**
多功能助手，数据库读写...
**相关示例**
全能助手示例

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
1. The http module cannot receive return information in IMG format.
2. HTTP module feedback information must be received using fields. Multiple fields cannot be defined using one output port.
3. When the outgoing field of the http module is json, for example, when the key is data in the example data, the outgoing parameter is a json object and cannot be received by the input parameters of other modules. It is recommended to add a transit module that will automatically convert non-string input into a string, similar to the designated reply module.
  Sample data { "message": "message",
      "data": { "name": "name",
      "age": 10 }}
**Application Scenario**
Multifunctional assistant, database reading and writing...
**Related Examples**
Almighty Assistant Example
