### ISSUE TITLE
In the question and answer dialogue after upgrading from 4.6.4 to 4.6.6, the second prompt was "undefined There is no available channel for the module to gpt-3.5turbo-1106 under the current group default"

### ISSUE THREAD

**Issue by buctllx** [labring/FastGPT#747]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 私有部署版本  V4.6.6

**问题描述**
你好，我从V4.6.4升级到 V4.6.6版本后，新建了一个应用或者打开已有的应用，选择one-api接入自己本地的大模型chatglm，然后在“调试预览”中对话，第一次提问正常回复，但是在第二次提问的时候却提示找不到模型 gpt-3.5-turbo-1106 的提示，如下图：
![image](https://github.com/labring/FastGPT/assets/12623648/edbb53fc-c4e9-4e43-8d42-de035313e672)

**复现步骤**
前提条件：使用 docker-compose 安装 v4.6.4 并确保正常试用，并通过 OneAPI 渠道接入 ChatGLM 大模型在 FastGPT 中使用 ChatGLM 大模型。

1. 进入 fastgpt 目录
2. docker-compose down
3. docker pull fastgpt
4. 更新配置文件 config.json 和 docker-compose.yml 文件 到 V4.6.6 版本
5. docker-compose up -d

启动 V4.6.6 版本的 config.json 和  docker-compose.yml  信息如下：
 config.json
```{
  "systemEnv": {
    "openapiPrefix": "fastgpt",
    "vectorMaxProcess": 15,
    "qaMaxProcess": 15,
    "pgHNSWEfSearch": 100
  },
  "chatModels": [
    {
      "model": "gpt-3.5-turbo",
      "name": "GPT35",
      "inputPrice": 0,
      "outputPrice": 0,
      "maxContext": 4000,
      "maxResponse": 4000,
      "quoteMaxToken": 2000,
      "maxTemperature": 1.2,
      "censor": false,
      "vision": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "gpt-3.5-turbo-16k",
      "name": "GPT35-16k",
      "maxContext": 16000,
      "maxResponse": 16000,
      "inputPrice": 0,
      "outputPrice": 0,
      "quoteMaxToken": 8000,
      "maxTemperature": 1.2,
      "censor": false,
      "vision": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "gpt-4",
      "name": "GPT4-8k",
      "maxContext": 8000,
      "maxResponse": 8000,
      "inputPrice": 0,
      "outputPrice": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1.2,
      "censor": false,
      "vision": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "gpt-4-vision-preview",
      "name": "GPT4-Vision",
      "maxContext": 128000,
      "maxResponse": 4000,
      "inputPrice": 0,
      "outputPrice": 0,
      "quoteMaxToken": 100000,
      "maxTemperature": 1.2,
      "censor": false,
      "vision": true,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "chatglm_turbo",
      "name": "chatglm_turbo",
      "maxContext": 8000,
      "maxResponse": 4000,
      "price": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1,
      "censor": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "chatglm_pro",
      "name": "chatglm_pro",
      "maxContext": 8000,
      "maxResponse": 4000,
      "price": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1,
      "censor": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "qwen-turbo",
      "name": "qwen-turbo",
      "maxContext": 8000,
      "maxResponse": 4000,
      "price": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1,
      "censor": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "qwen-max",
      "name": "qwen-max",
      "maxContext": 8000,
      "maxResponse": 4000,
      "price": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1,
      "censor": false,
      "defaultSystemChatPrompt": ""
    }
  ],
  "qaModels": [
    {
      "model": "gpt-3.5-turbo-16k",
      "name": "GPT35-16k",
      "maxContext": 16000,
      "maxResponse": 16000,
      "inputPrice": 0,
      "outputPrice": 0
    }
  ],
  "cqModels": [
    {
      "model": "gpt-3.5-turbo",
      "name": "GPT35",
      "maxContext": 4000,
      "maxResponse": 4000,
      "inputPrice": 0,
      "outputPrice": 0,
      "toolChoice": true,
      "functionPrompt": ""
    },
    {
      "model": "gpt-4",
      "name": "GPT4-8k",
      "maxContext": 8000,
      "maxResponse": 8000,
      "inputPrice": 0,
      "outputPrice": 0,
      "toolChoice": true,
      "functionPrompt": ""
    }
  ],
  "extractModels": [
    {
      "model": "chatglm_turbo",
      "name": "chatglm_turbo",
      "maxContext": 16000,
      "maxResponse": 4000,
      "inputPrice": 0,
      "outputPrice": 0,
      "toolChoice": true,
      "functionPrompt": ""
    }
  ],
  "qgModels": [
    {
      "model": "gpt-3.5-turbo-1106",
      "name": "GPT35-1106",
      "maxContext": 1600,
      "maxResponse": 4000,
      "inputPrice": 0,
      "outputPrice": 0
    }
  ],
  "vectorModels": [
    {
      "model": "text-embedding-ada-002",
      "name": "Embedding-2",
      "inputPrice": 0,
      "outputPrice": 0,
      "defaultToken": 700,
      "maxToken": 3000,
      "weight": 100
    },
    {
      "model": "bge-zh",
      "name": "bge-zh",
      "price": 0.2,
      "defaultToken": 700,
      "maxToken": 3000
    }
  ],
  "reRankModels": [],
  "audioSpeechModels": [
    {
      "model": "tts-1",
      "name": "OpenAI TTS1",
      "inputPrice": 0,
      "outputPrice": 0,
      "voices": [
        { "label": "Alloy", "value": "alloy", "bufferId": "openai-Alloy" },
        { "label": "Echo", "value": "echo", "bufferId": "openai-Echo" },
        { "label": "Fable", "value": "fable", "bufferId": "openai-Fable" },
        { "label": "Onyx", "value": "onyx", "bufferId": "openai-Onyx" },
        { "label": "Nova", "value": "nova", "bufferId": "openai-Nova" },
        { "label": "Shimmer", "value": "shimmer", "bufferId": "openai-Shimmer" }
      ]
    }
  ],
  "whisperModel": {
    "model": "whisper-1",
    "name": "Whisper1",
    "inputPrice": 0,
    "outputPrice": 0
  }
}```

docker-compose.yml 
```# 非 host 版本, 不使用本机代理
# (不懂 Docker 的，只需要关心 OPENAI_BASE_URL 和 CHAT_API_KEY 即可！)
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5432:5432
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports: # 生产环境建议不要暴露
      - 27017:27017
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
    ports:
      - 3003:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      # root 密码，用户名为: root
      - DEFAULT_ROOT_PSW=1234
      # 中转地址，如果是用官方号，不需要管。务必加 /v1
      - OPENAI_BASE_URL=http://192.168.11.11:3000/v1
      - CHAT_API_KEY=sk-oV12232323121222222222222222
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      # mongo 配置，不需要改. 如果连不上，可能需要去掉 ?authSource=admin
      - MONGODB_URI=mongodb://username:password@mongo:27017/fastgpt?authSource=admin
      # pg配置. 不需要改
      - PG_URL=postgresql://username:password@pg:5432/postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fastgpt:
# host 版本, 不推荐。
# version: '3.3'
# services:
#   pg:
#   image: ankane/pgvector:v0.5.0 # dockerhub
#   # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # 阿里云
#   container_name: pg
#   restart: always
#   ports: # 生产环境建议不要暴露
#       - 5432:5432
#   environment:
#       # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
#       - POSTGRES_USER=username
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=postgres
#   volumes:
#       - ./pg/data:/var/lib/postgresql/data
#   mongo:
#   image: mongo:5.0.18
#   # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
#   container_name: mongo
#   restart: always
#   ports: # 生产环境建议不要暴露
#       - 27017:27017
#   environment:
#       # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
#       - MONGO_INITDB_ROOT_USERNAME=username
#       - MONGO_INITDB_ROOT_PASSWORD=password
#   volumes:
#       - ./mongo/data:/data/db
#       - ./mongo/logs:/var/log/mongodb
#   fastgpt:
#   # image: ghcr.io/labring/fastgpt:latest # github
#   image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
#   network_mode: host
#   restart: always
#   container_name: fastgpt
#   environment:
#       # root 密码，用户名为: root
#       - DEFAULT_ROOT_PSW=1234
#       # 中转地址，如果是用官方号，不需要管
#       - OPENAI_BASE_URL=https://api.openai.com/v1
#       - CHAT_API_KEY=sk-xxxx
#       - DB_MAX_LINK=5 # database max link
#       # token加密凭证（随便填，作为登录凭证）
#       - TOKEN_KEY=any
#       # root key, 最高权限，可以内部接口互相调用
#       - ROOT_KEY=root_key
#       # mongo 配置，不需要改
#       - MONGODB_URI=mongodb://username:password@0.0.0.0:27017/fastgpt?authSource=admin
#       # pg配置. 不需要改
#       - PG_URL=postgresql://username:password@0.0.0.0:5432/postgres
```

然后进入系统，新建或者进入老应用，在“调试预览”中对话，第一次提问正常回复，但是在第二次提问的时候却提示找不到模型 gpt-3.5-turbo-1106 的提示。

**预期结果**
正常回复，不报错。

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Private deployment version V4.6.6

**Problem Description**
Hello, after I upgraded from V4.6.4 to V4.6.6, I created a new application or opened an existing application, selected one-api to connect to my local large model chatglm, and then dialogued in "Debug Preview", Chapter The first question was answered normally, but when the second question was asked, it was prompted that the model gpt-3.5-turbo-1106 could not be found, as shown below:
![image](https://github.com/labring/FastGPT/assets/12623648/edbb53fc-c4e9-4e43-8d42-de035313e672)


**Steps to reproduce**
Prerequisite: Use docker-compose to install v4.6.4 and ensure normal trial, and access the ChatGLM large model through the OneAPI channel to use the ChatGLM large model in FastGPT.

1. Enter the fastgpt directory
2. docker-compose down
3. docker pull fastgpt
4. Update the configuration file config.json and docker-compose.yml file to version V4.6.6
5. docker-compose up -d

The information of config.json and docker-compose.yml that starts the V4.6.6 version is as follows:
 config.json
`{
  "systemEnv": {
    "openapiPrefix": "fastgpt",
    "vectorMaxProcess": 15,
    "qaMaxProcess": 15,
    "pgHNSWEfSearch": 100
  },
  "chatModels": [
    {
      "model": "gpt-3.5-turbo",
      "name": "GPT35",
      "inputPrice": 0,
      "outputPrice": 0,
      "maxContext": 4000,
      "maxResponse": 4000,
      "quoteMaxToken": 2000,
      "maxTemperature": 1.2,
      "censor": false,
      "vision": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "gpt-3.5-turbo-16k",
      "name": "GPT35-16k",
      "maxContext": 16000,
      "maxResponse": 16000,
      "inputPrice": 0,
      "outputPrice": 0,
      "quoteMaxToken": 8000,
      "maxTemperature": 1.2,
      "censor": false,
      "vision": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "gpt-4",
      "name": "GPT4-8k",
      "maxContext": 8000,
      "maxResponse": 8000,
      "inputPrice": 0,
      "outputPrice": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1.2,
      "censor": false,
      "vision": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "gpt-4-vision-preview",
      "name": "GPT4-Vision",
      "maxContext": 128000,
      "maxResponse": 4000,
      "inputPrice": 0,
      "outputPrice": 0,
      "quoteMaxToken": 100000,
      "maxTemperature": 1.2,
      "censor": false,
      "vision": true,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "chatglm_turbo",
      "name": "chatglm_turbo",
      "maxContext": 8000,
      "maxResponse": 4000,
      "price": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1,
      "censor": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "chatglm_pro",
      "name": "chatglm_pro",
      "maxContext": 8000,
      "maxResponse": 4000,
      "price": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1,
      "censor": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "qwen-turbo",
      "name": "qwen-turbo",
      "maxContext": 8000,
      "maxResponse": 4000,
      "price": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1,
      "censor": false,
      "defaultSystemChatPrompt": ""
    },
    {
      "model": "qwen-max",
      "name": "qwen-max",
      "maxContext": 8000,
      "maxResponse": 4000,
      "price": 0,
      "quoteMaxToken": 4000,
      "maxTemperature": 1,
      "censor": false,
      "defaultSystemChatPrompt": ""
    }
  ],
  "qaModels": [
    {
      "model": "gpt-3.5-turbo-16k",
      "name": "GPT35-16k",
      "maxContext": 16000,
      "maxResponse": 16000,
      "inputPrice": 0,
      "outputPrice": 0
    }
  ],
  "cqModels": [
    {
      "model": "gpt-3.5-turbo",
      "name": "GPT35",
      "maxContext": 4000,
      "maxResponse": 4000,
      "inputPrice": 0,
      "outputPrice": 0,
      "toolChoice": true,
      "functionPrompt": ""
    },
    {
      "model": "gpt-4",
      "name": "GPT4-8k",
      "maxContext": 8000,
      "maxResponse": 8000,
      "inputPrice": 0,
      "outputPrice": 0,
      "toolChoice": true,
      "functionPrompt": ""
    }
  ],
  "extractModels": [
    {
      "model": "chatglm_turbo",
      "name": "chatglm_turbo",
      "maxContext": 16000,
      "maxResponse": 4000,
      "inputPrice": 0,
      "outputPrice": 0,
      "toolChoice": true,
      "functionPrompt": ""
    }
  ],
  "qgModels": [
    {
      "model": "gpt-3.5-turbo-1106",
      "name": "GPT35-1106",
      "maxContext": 1600,
      "maxResponse": 4000,
      "inputPrice": 0,
      "outputPrice": 0
    }
  ],
  "vectorModels": [
    {
      "model": "text-embedding-ada-002",
      "name": "Embedding-2",
      "inputPrice": 0,
      "outputPrice": 0,
      "defaultToken": 700,
      "maxToken": 3000,
      "weight": 100
    },
    {
      "model": "bge-zh",
      "name": "bge-zh",
      "price": 0.2,
      "defaultToken": 700,
      "maxToken": 3000
    }
  ],
  "reRankModels": [],
  "audioSpeechModels": [
    {
      "model": "tts-1",
      "name": "OpenAI TTS1",
      "inputPrice": 0,
      "outputPrice": 0,
      "voices": [
        { "label": "Alloy", "value": "alloy", "bufferId": "openai-Alloy" },
        { "label": "Echo", "value": "echo", "bufferId": "openai-Echo" },
        { "label": "Fable", "value": "fable", "bufferId": "openai-Fable" },
        { "label": "Onyx", "value": "onyx", "bufferId": "openai-Onyx" },
        { "label": "Nova", "value": "nova", "bufferId": "openai-Nova" },
        { "label": "Shimmer", "value": "shimmer", "bufferId": "openai-Shimmer" }
      ]
    }
  ],
  "whisperModel": {
    "model": "whisper-1",
    "name": "Whisper1",
    "inputPrice": 0,
    "outputPrice": 0
  }
}`

docker-compose.yml
`# Non-host version, does not use native proxy
# (If you don’t know Docker, you only need to care about OPENAI_BASE_URL and CHAT_API_KEY!)
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # Alibaba Cloud
    container_name: pg
    restart: always
    ports: # It is recommended not to expose in production environment
      - 5432:5432
    networks:
      -fastgpt
    environment:
      # The configuration here only takes effect on the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image:mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # Alibaba Cloud
    container_name: mongo
    restart: always
    ports: # It is recommended not to expose in production environment
      - 27017:27017
    networks:
      -fastgpt
    environment:
      # The configuration here only takes effect on the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # Alibaba Cloud
    ports:
      - 3003:3000
    networks:
      -fastgpt
    depends_on:
      -mongo
      -pg
    restart: always
    environment:
      # root password, username: root
      - DEFAULT_ROOT_PSW=1234
      # Forwarding address, if you use an official account, you don’t need to worry about it. Be sure to add /v1
      - OPENAI_BASE_URL=http://192.168.11.11:3000/v1
      - CHAT_API_KEY=sk-oV12232323121222222222222222
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      # Mongo configuration, no need to change. If you can't connect, you may need to remove ?authSource=admin
      - MONGODB_URI=mongodb://username:password@mongo:27017/fastgpt?authSource=admin
      # pg configuration. No need to change
      - PG_URL=postgresql://username:password@pg:5432/postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fastgpt:
# host version, not recommended.
# version: '3.3'
# services:
#pg:
# image: ankane/pgvector:v0.5.0 # dockerhub
# # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # Alibaba Cloud
# container_name: pg
# restart: always
# ports: # It is recommended not to expose the production environment
# - 5432:5432
# environment:
# # The configuration here only takes effect for the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
# - POSTGRES_USER=username
# - POSTGRES_PASSWORD=password
# - POSTGRES_DB=postgres
# volumes:
# - ./pg/data:/var/lib/postgresql/data
#mongo:
# image: mongo:5.0.18
# # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # Alibaba Cloud
# container_name: mongo
# restart: always
# ports: # It is recommended not to expose the production environment
# - 27017:27017
# environment:
# # The configuration here only takes effect for the first run. After modification, restarting the image will not take effect. It is necessary to delete the persistent data and then restart to have an effect.
# - MONGO_INITDB_ROOT_USERNAME=username
# - MONGO_INITDB_ROOT_PASSWORD=password
# volumes:
# - ./mongo/data:/data/db
# - ./mongo/logs:/var/log/mongodb
#fastgpt:
# # image: ghcr.io/labring/fastgpt:latest # github
# image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # Alibaba Cloud
# network_mode: host
# restart: always
# container_name: fastgpt
# environment:
# # root password, username: root
# - DEFAULT_ROOT_PSW=1234
# # Forwarding address, if you use an official account, you don’t need to worry about it.
# - OPENAI_BASE_URL=https://api.openai.com/v1
# - CHAT_API_KEY=sk-xxxx
# - DB_MAX_LINK=5 # database max link
# # Token encryption credentials (fill in whatever you want, as login credentials)
# - TOKEN_KEY=any
# # root key, the highest authority, can call each other through internal interfaces
# - ROOT_KEY=root_key
# # mongo configuration, no need to change
# - MONGODB_URI=mongodb://username:password@0.0.0.0:27017/fastgpt?authSource=admin
# # pg configuration. No need to change
# - PG_URL=postgresql://username:password@0.0.0.0:5432/postgres`


Then enter the system, create a new application or enter an old application, and talk in the "Debug Preview". The first time I ask a question, I get a normal reply, but when I ask the second question, I get a prompt that the model gpt-3.5-turbo-1106 cannot be found.

**expected outcome**
Reply normally and no error will be reported.

**Related screenshots**

**Comment by surfboy2000** [comment]
我也遇到同样的问题，大佬给的答复是：没有修改所有模型为glm3，检查一遍配置文件就看到gpt模型了。详见#736

我后来，把 extractModels 模型只保留了 chatglm3 ，把 chatgpt3.5删掉。问题解决了。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also encountered the same problem. The answer given by the boss was: All models were not modified to glm3. After checking the configuration file, I saw the gpt model. See #736 for details

I later kept only chatglm3 in the extractModels model and deleted chatgpt3.5. The problem is solved.

**Comment by c121914yu** [comment]
配置文件没改全，所有的模型都需要改完。
