### ISSUE TITLE
Create the knowledge base locally, and the prompt is always indexing.

### ISSUE THREAD

**Issue by wangjiangnan9098** [labring/FastGPT#751]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
利用docker compose 部署本地fastgpt，创建知识库导入本地文件后，提示一直在索引中。仅仅有3组索引，文件类型为doc，大小为600k

**复现步骤**

本地部署，重复导入文件，依旧提示一直在索引中

**预期结果**

**相关截图**
<img width="1159" alt="截屏2024-01-19 17 17 23" src="https://github.com/labring/FastGPT/assets/8630390/411892ef-c755-4f55-89f9-a22405e8f433">

**Comment by c121914yu** [comment]
key 不行，这个 issue 和文档都提有了。
