### ISSUE TITLE
When setting OpenAI/OneAPI account, and providing the APIKey and BaseURL, the TIME OUT notice always prompts. I have test the Key and URL in my local environment

### ISSUE THREAD

**Issue by WSDzju** [labring/FastGPT#753]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

<img width="632" alt="屏幕截图 2024-01-19 194656" src="https://github.com/labring/FastGPT/assets/147698475/098f83e3-ebf4-404f-a48f-66335e2d6790">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**

**Steps to reproduce**

**expected outcome**

**Related screenshots**

<img width="632" alt="Screenshot 2024-01-19 194656" src="https://github.com/labring/FastGPT/assets/147698475/098f83e3-ebf4-404f-a48f-66335e2d6790">

**Comment by c121914yu** [comment]
无效地址。

**Comment by WSDzju** [comment]
> 连接不到的地址。

这个地址是可以使用 OneAPI代理的？有API key 和BaseUrl？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Unreachable address.

Can this address use OneAPI proxy? Do you have an API key and BaseUrl?

**Comment by c121914yu** [comment]
> > 连接不到的地址。
> 
> 这个地址是可以使用 OneAPI代理的？有API key 和BaseUrl？

可以的，但是必须要公有云的服务器可以访问到。当然，基本公网能访问的都可以。
