### ISSUE TITLE
[Suggestion] Can historical records be carried when searching in the knowledge base?

### ISSUE THREAD

**Issue by Lavanille777** [labring/FastGPT#755]
尤其是用户提问的历史记录
使用问题补全或者内容提取虽然也可以达成目的，但是效果不稳定还耗时。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Especially the history of user questions
Although using question completion or content extraction can also achieve the goal, the effect is unstable and time-consuming.

**Comment by c121914yu** [comment]
多用几次，就知道用历史记录搜没啥用😂最后还是得让模型过滤。
