### ISSUE TITLE
After Zhipu updates the GLM-4 model, TOP_P cannot be 1. I hope it can be modified as a model configuration parameter.

### ISSUE THREAD

**Issue by kuziTony** [labring/FastGPT#760]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
智谱更新GLM-4后更新了新的参数，
![image](https://github.com/labring/FastGPT/assets/125565288/8867a491-613c-4335-988e-ccc03b49aa07)
在聊天的代码中查询
![image](https://github.com/labring/FastGPT/assets/125565288/6f5a5934-49c5-4c86-9280-d5c4053e5c34)
top_p写死了为1 导致在使用GLM-4模型的时候一定会报top_p是非法参数  期待修改
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**
After Zhipu updated GLM-4, it updated new parameters.
![image](https://github.com/labring/FastGPT/assets/125565288/8867a491-613c-4335-988e-ccc03b49aa07)
Query in the chat code
![image](https://github.com/labring/FastGPT/assets/125565288/6f5a5934-49c5-4c86-9280-d5c4053e5c34)
top_p is hard-coded to 1. As a result, when using the GLM-4 model, it will be reported that top_p is an illegal parameter. Looking forward to modifying it.
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by 0000sir** [comment]
How to fix this temporary before the team release  the official patch? Thank you

**Comment by tyrantGXY** [comment]
我也是发现了这个问题，有什么办法临时能解决下呢？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also discovered this problem, is there any temporary solution?

**Comment by LinyuJupiter** [comment]
You can use the following methods to temporarily solve the problem.
https://github.com/LinyuJupiter/FastGPT-zhipu-api

**Comment by qy8502** [comment]
同样的问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
same question

**Comment by 0000sir** [comment]
Found this will be fixed in #804
Wait for new image 🤣👍

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.6.8-alpha 已修复
