### ISSUE TITLE
I hope to increase the configurable return length of vector search in advanced arrangement.

### ISSUE THREAD

**Issue by Dy-yun** [labring/FastGPT#762]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
希望增加高级编排里向量搜索返回长度可配置。
**应用场景**

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there are currently no similar features
- [x] I have confirmed that I have upgraded to the latest version
- [x] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [x] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**
Hope to increase the configurable return length of vector search in advanced orchestration.
**Application Scenario**

**Related Examples**

**Comment by c121914yu** [comment]
具体指的是什么

**Comment by Dy-yun** [comment]
> 具体指的是什么

知识库搜索的引用上上限，简单模式、高级编排和搜索测试可配置的大小都是不一致的，在配置文件中也没找到可以修改的字段。

**Comment by c121914yu** [comment]
> > 具体指的是什么
> 
> 知识库搜索的引用上上限，简单模式、高级编排和搜索测试可配置的大小都是不一致的，在配置文件中也没找到可以修改的字段。

上限取决模型。测试没有模型限制，所以固定了一个值。

**Comment by Dy-yun** [comment]
> > > 具体指的是什么
> > 
> > 
> > 知识库搜索的引用上上限，简单模式、高级编排和搜索测试可配置的大小都是不一致的，在配置文件中也没找到可以修改的字段。
> 
> 上限取决模型。测试没有模型限制，所以固定了一个值。

模型设置maxToken智能影响到他上传的上限，但是无法影响他引用的上限，比如喔maxtoken设置了3w，引入和测试的上限都会改为3w，但是简单配置上的引用上限是8k，高级编排里引用是3k，这两个引用值没有变动。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > What does it refer to specifically?
>>
>>
> > The upper limit of references for knowledge base search, the configurable sizes of simple mode, advanced orchestration and search test are all inconsistent, and no fields that can be modified were found in the configuration file.
>
> The upper limit depends on the model. The test has no model constraints, so a value is fixed.

The model setting maxToken intelligently affects the upper limit of his upload, but cannot affect the upper limit of his references. For example, if maxtoken is set to 30,000, the upper limit of introduction and testing will be changed to 30,000, but the upper limit of references in simple configuration is 8k, and in advanced orchestration, the upper limit is 8k. It is 3k, and these two reference values ​​have not changed.

**Comment by c121914yu** [comment]
> > > > 具体指的是什么
> > > 
> > > 
> > > 知识库搜索的引用上上限，简单模式、高级编排和搜索测试可配置的大小都是不一致的，在配置文件中也没找到可以修改的字段。
> > 
> > 
> > 上限取决模型。测试没有模型限制，所以固定了一个值。
> 
> 模型设置maxToken只能影响到他上传和测试的上限，但是无法影响他引用的上限，比如我maxtoken设置了3w，引入和测试的上限都会改为3w，但是简单配置上的引用上限是8k，高级编排里引用是3k，这两个引用上限没有变动。

模型引用上限由quoteMaxToken决定
