### ISSUE TITLE
Flickers and jitters when streaming output images

### ISSUE THREAD

**Issue by buctllx** [labring/FastGPT#770]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
fastgpt 在回到问题的时候，如果回答的文本中有图片，并且在图片后面还有文字，那么在流式输出的时候 图片位置会变空白，并不断闪烁抖动。

**复现步骤**
1. 准备一个带有图片连接的问题和答案，并且在图片后面还有文本；
2. 提问这个问题，并在 图片连接输出完毕后就能发现这闪烁抖动问题；

**预期结果**
图片在流式输出的过程中一直显示不会闪烁抖动。

**相关截图**
![picture-rock](https://github.com/labring/FastGPT/assets/12623648/ab2e16d2-277e-4652-ae24-38f5074d6ba5)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
When fastgpt returns to the question, if there is a picture in the text of the answer and there is text behind the picture, then the picture position will become blank during the streaming output and continue to flicker and jitter.

**Steps to reproduce**
1. Prepare a question and answer with a picture link and text behind the picture;
2. Ask this question, and you will be able to find the flickering and jittering problem after the picture is connected and output;

**expected outcome**
The picture will always be displayed without flickering during the streaming output process.

**Related screenshots**
![picture-rock](https://github.com/labring/FastGPT/assets/12623648/ab2e16d2-277e-4652-ae24-38f5074d6ba5)

**Comment by c121914yu** [comment]
4.6.7已经修复这个问题

**Comment by buctllx** [comment]
> 4.6.7已经修复这个问题

感谢~~

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> 4.6.7 has fixed this problem

Thanks~~

**Comment by jackieZhouQQ** [comment]
@buctllx 返回图片是怎么做的，提示词和文件的qa格式有要求吗
