### ISSUE TITLE
The knowledge base openapi interface will prompt a credential error when using a common key

### ISSUE THREAD

**Issue by yufeng97** [labring/FastGPT#771]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
版本v4.6.7
接口 /api/core/dataset/data/list
使用通用key (fastgpt-xxxxx)会提示403凭证错误，改用网页平台获取的Token字段可以请求成功
```json
{
    "code": 403,
    "statusText": "unAuthorization",
    "message": "凭证错误",
    "data": null
}
```
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Version v4.6.7
Interface /api/core/dataset/data/list
Using the general key (fastgpt-xxxxx) will prompt 403 credential error. If you use the Token field obtained from the web platform, the request can be successful.
```json
{
    "code": 403,
    "statusText": "unAuthorization",
    "message": "Certificate error",
    "data": null
}
```
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
无法复现
![image](https://github.com/labring/FastGPT/assets/50446880/010c87bb-4760-4845-a310-0b793e651e17)

**Comment by yufeng97** [comment]
你的authorization是什么？我用的是在账户api密钥生成的key
![image](https://github.com/labring/FastGPT/assets/47183963/081c7782-a791-4f68-ac0a-10eab8ad349d)

**Comment by yufeng97** [comment]
不好意思是我的问题，我拉取镜像缓存了还是v4.6.6，并不是最新版，更新到v4.6.7没有这个问题，感谢您的回复。建议阿里云的镜像添加不同版本的tag

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Sorry, this is my problem. The image cache I pulled is still v4.6.6, which is not the latest version. I updated to v4.6.7 and there is no such problem. Thank you for your reply. It is recommended to add different versions of tags to Alibaba Cloud images.
