### ISSUE TITLE
null value in column "tmb_id" of relation "modeldata" violates not-null constraint

### ISSUE THREAD

**Issue by blackkeai** [labring/FastGPT#772]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
创建自己的支持库，上床文档之后执行索引的时候后台报错。

error => null value in column "tmb_id" of relation "modeldata" violates not-null constraint

**复现步骤**

**预期结果**

**相关截图**
<img width="1192" alt="image" src="https://github.com/labring/FastGPT/assets/7159046/ae4a9f18-ba93-47ad-8ee4-fcd37cc49bea">

**Comment by blackkeai** [comment]
最新版本数据库字段变化，重新初始化数据库就好了。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
If the fields in the latest version of the database change, just reinitialize the database.

**Comment by kitaev-chen** [comment]
> 最新版本数据库字段变化，重新初始化数据库就好了。

是应该删除 mongo 还是 pg 下的 data？

**Comment by smilence86** [comment]
同问，应该怎么操作，上个版本还创建了数据，能保留吗

**Comment by kingszhe9664** [comment]
我重新拉了最新镜像 然后重新执行  rs.initiate({
  _id: "rs0",
  members: [
    { _id: 0, host: "mongo:27017" }
  ]
})    还是没有用

依然在处理索引的时候   提示 null value in column "tmb_id" of relation "modeldata" violates not-null constraint
（chat中转是正常的）

**Comment by HotelEnglish** [comment]
遇到了同样的问题，使用应用对话可以正常使用，但是导入知识库出现错误提示，已经初始化部分集合并初始化了API 4.6.7。反复安装了无数次了，无解，求助。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Encountered the same problem. It can be used normally using the application dialog, but an error message appears when importing the knowledge base. Some collections have been initialized and API 4.6.7 has been initialized. I have installed it countless times and can't find a solution. Please help.

**Comment by tohsaka888** [comment]
首先down docker container：
```shell
docker-compose down
```
再删除`pg/data`：
```shell
sudo rm -rf pg
```
最后`docker-compose`重启容器即可
