### ISSUE TITLE
The minimum correlation does not take effect

### ISSUE THREAD

**Issue by buctllx** [labring/FastGPT#776]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本  V4.6.6

**问题描述**
应用配置里面设置“知识库-搜索参数” 最低相关度=0.4，
然后在调试预览中提问一个与知识库无关的问题，结果没有按照“空搜索回复”，原因是：发现有检索到知识库的相关上下文，但是发现返回的知识库引用内容的“相关性”数值都很低，明显低于设定的“最低相关度=0.4”。
按照文档中说明，语义检索的时候会考虑“最低相关度”，在我设置了“最低相关度=0.4”的情况下，是不是不应该返回检索到的“相关性”数值低于 0.4 的知识库引用？
![image](https://github.com/labring/FastGPT/assets/12623648/5b9dd100-135a-4d27-af8f-913baa477902)
![image](https://github.com/labring/FastGPT/assets/12623648/f3b7fe34-9785-415d-b3d2-71696030c5d2)

**复现步骤**
1. 应用配置里面设置“知识库-搜索参数” 最低相关度=0.4， 语义检索，“空搜索回复” ;
2. 保存设置后在调试预览中提问一个与知识库无关的问题，结果没有按照“空搜索回复”，返回的引用信息明显低于设定的“最低相关度=0.4”

**预期结果**
不返回 低于设定的“最低相关度=0.4” 的引用内容；
回答使用“空搜索回复” 中设置的内容；

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version V4.6.6

**Problem Description**
In the application configuration, set the "Knowledge Base-Search Parameters" minimum relevance = 0.4,
Then I asked a question unrelated to the knowledge base in the debugging preview. The result did not follow the "empty search reply". The reason is: it was found that the relevant context of the knowledge base was retrieved, but the "relevance" value of the returned knowledge base reference content was found. All are very low, significantly lower than the set "minimum correlation = 0.4".
According to the description in the document, the "minimum relevance" will be considered during semantic retrieval. If I set "minimum relevance = 0.4", should I not return the retrieved knowledge with a "relevance" value lower than 0.4? Library reference?
![image](https://github.com/labring/FastGPT/assets/12623648/5b9dd100-135a-4d27-af8f-913baa477902)
![image](https://github.com/labring/FastGPT/assets/12623648/f3b7fe34-9785-415d-b3d2-71696030c5d2)


**Steps to reproduce**
1. Set "Knowledge Base-Search Parameters" in the application configuration, minimum relevance = 0.4, semantic retrieval, "empty search reply";
2. After saving the settings, I asked a question unrelated to the knowledge base in the debugging preview. The result was that the "empty search reply" was not followed, and the reference information returned was significantly lower than the set "minimum relevance = 0.4"

**expected outcome**
Do not return reference content that is lower than the set "minimum relevance = 0.4";
Answers use the content set in "Empty Search Reply";


**Related screenshots**

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/46d40823-f5e2-49cb-80fc-f704b5a9ff88)
无法复现，请确保你点了保存

**Comment by buctllx** [comment]
> ![image](https://private-user-images.githubusercontent.com/50446880/299200516-46d40823-f5e2-49cb-80fc-f704b5a9ff88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzgxNTIsIm5iZiI6MTcwNjA3Nzg1MiwicGF0aCI6Ii81MDQ0Njg4MC8yOTkyMDA1MTYtNDZkNDA4MjMtZjVlMi00OWNiLTgwZmMtZjcwNGI1YTlmZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Y2E0ZDMwMGUyODE3YWM2ZDkyOTYzMWIxNTExNWM1ZmQ4YzJjZmZiYTg3ODE3OTVjY2Y0NGUyNmE1MmJhZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01oJOWrbp4FLBdgET80f3ZERzi-aDsXTAsshjbnidsY) 无法复现，请确保你点了保存

确认已保存，我又试了一遍，下面截图是我“调试预览”界面的测试信息；
![image](https://github.com/labring/FastGPT/assets/12623648/6f76b0ea-89b0-4343-89f2-6f38564f2bc5)
![image](https://github.com/labring/FastGPT/assets/12623648/d236be9b-a19a-47f1-ae7f-fdcc91de0e65)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> ![image](https://private-user-images.githubusercontent.com/50446880/299200516-46d40823-f5e2-49cb-80fc-f704b5a9ff88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..01oJOWr bp4FLBdgET80f3ZERzi-aDsXTAsshjbnidsY) cannot be reproduced, please Make sure you click Save

After confirming that it was saved, I tried again. The screenshot below is the test information of my "Debug Preview" interface;
![image](https://github.com/labring/FastGPT/assets/12623648/6f76b0ea-89b0-4343-89f2-6f38564f2bc5)
![image](https://github.com/labring/FastGPT/assets/12623648/d236be9b-a19a-47f1-ae7f-fdcc91de0e65)

**Comment by c121914yu** [comment]
看着搜索模式并不是语义检索？

**Comment by buctllx** [comment]
> 看着搜索模式并不是语义检索？

我勾选了“结果重排”，试验多次后发现一个规律：勾选了“结果重排”就会出现这个问题，不勾选就正常；
是 reRankModel 不支持，还是我reRankModels 的配置有问题？reRankModels 配置见下面截图
![image](https://github.com/labring/FastGPT/assets/12623648/bef860d2-9e85-48a8-87bb-a2a39b206919)
![image](https://github.com/labring/FastGPT/assets/12623648/8aa07045-55a1-450d-a6fd-187540390f48)

**Comment by c121914yu** [comment]
> > 看着搜索模式并不是语义检索？
> 
> 我勾选了“结果重排”，试验多次后发现一个规律：勾选了“结果重排”就会出现这个问题，不勾选就正常； 是 reRankModel 不支持，还是我reRankModels 的配置有问题？reRankModels 配置见下面截图 ![image](https://private-user-images.githubusercontent.com/12623648/299212994-bef860d2-9e85-48a8-87bb-a2a39b206919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODYwNzQsIm5iZiI6MTcwNjA4NTc3NCwicGF0aCI6Ii8xMjYyMzY0OC8yOTkyMTI5OTQtYmVmODYwZDItOWU4NS00OGE4LTg3YmItYTJhMzliMjA2OTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA4NDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMDYzM2JiZGVkODZkM2QyYTNmZGQyYmVmY2M0MTg1OGRhNzVmNWJmYjAzNmRkOWQ3M2RhOWNmMWM0MDk5YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZGQh10lNEbXeuv78rje5K4mCI5_ozuAtc9YUJ32Gojk) ![image](https://private-user-images.githubusercontent.com/12623648/299213785-8aa07045-55a1-450d-a6fd-187540390f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODYwNzQsIm5iZiI6MTcwNjA4NTc3NCwicGF0aCI6Ii8xMjYyMzY0OC8yOTkyMTM3ODUtOGFhMDcwNDUtNTVhMS00NTBkLWE2ZmQtMTg3NTQwMzkwZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA4NDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDFmNzJiNzkxZjc4YWJjYzZkNTFlMTRjNjI2ODc2YTgyMTYwMTkxYjhlZGJkMTEwYjI2YjkxYmE3YjExN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R_bdeiBt1xyj1JtgVcdsik1w0JJOwi6PconZlAP1nhU)

理论上勾不勾选也不影响搜索模式，混合检索/全文检索如果没有rerank的话，那么肯定不会过滤。

**Comment by c121914yu** [comment]
可以看看是不是rerank没生效，生效的话会有日志： Rerank Time: xxx

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/10e2defb-5b30-4225-9874-edb8172267fc)
这块过滤逻辑有一点小小缺陷，如果勾选了 Rerank，但是 Rerank 模型运行失败，也会认为做了“相关度”过滤。因此，如果过滤无效，很有可能是rerank模型报错了。日志里也会有对应的报错提示。

**Comment by buctllx** [comment]
> ![image](https://private-user-images.githubusercontent.com/50446880/299251226-10e2defb-5b30-4225-9874-edb8172267fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODc4NDcsIm5iZiI6MTcwNjA4NzU0NywicGF0aCI6Ii81MDQ0Njg4MC8yOTkyNTEyMjYtMTBlMmRlZmItNWIzMC00MjI1LTk4NzQtZWRiODE3MjI2N2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwN2Y3ZjQwMTRmMWY5MzZhZDVkZWVmZTkwYjgzNDY0NmZkNjE2ZWI3OThlOGU2MjQxNmFlNjU0YzU1ZmIzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TYLclHOI6i9vFmDyZWj438DnOYj5Upr8RVJlgijQrNU) 这块过滤逻辑有一点小小缺陷，如果勾选了 Rerank，但是 Rerank 模型运行失败，也会认为做了“相关度”过滤。因此，如果过滤无效，很有可能是rerank模型报错了。日志里也会有对应的报错提示。

确实，我 curl 测试了一下 rerank api 确实报错了，正好触发了这个缺陷；歪个楼问个关于 rerank model 配置的问题：
我按照官方文档，在同一台服务器配置 bge-reranker-base 模型，直接 curl 是 ok 的，但是接入 one-api 后 curl 就报错了，

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> ![image](https://private-user-images.githubusercontent.com/50446880/299251226-10e2defb-5b30-4225-9874-edb8172267fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..TYLclHOI6i9 vFmDyZWj438DnOYj5Upr8RVJlgijQrNU) This filtering logic is a bit small A small flaw, if Rerank is checked but the Rerank model fails to run, it will be considered that "relevance" filtering has been performed. Therefore, if the filtering is invalid, it is likely that the rerank model reported an error. There will also be corresponding error messages in the log.

Indeed, I curl tested the rerank api and it did report an error, which happened to trigger this defect; I would like to ask a question about the rerank model configuration:
I followed the official documentation and configured the bge-reranker-base model on the same server. Direct curl was ok, but after connecting to one-api, curl reported an error.

**Comment by c121914yu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/50446880/299251226-10e2defb-5b30-4225-9874-edb8172267fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODc4NDcsIm5iZiI6MTcwNjA4NzU0NywicGF0aCI6Ii81MDQ0Njg4MC8yOTkyNTEyMjYtMTBlMmRlZmItNWIzMC00MjI1LTk4NzQtZWRiODE3MjI2N2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwN2Y3ZjQwMTRmMWY5MzZhZDVkZWVmZTkwYjgzNDY0NmZkNjE2ZWI3OThlOGU2MjQxNmFlNjU0YzU1ZmIzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TYLclHOI6i9vFmDyZWj438DnOYj5Upr8RVJlgijQrNU) 这块过滤逻辑有一点小小缺陷，如果勾选了 Rerank，但是 Rerank 模型运行失败，也会认为做了“相关度”过滤。因此，如果过滤无效，很有可能是rerank模型报错了。日志里也会有对应的报错提示。
> 
> 确实，我 curl 测试了一下 rerank api 确实报错了，正好触发了这个缺陷；歪个楼问个关于 rerank model 配置的问题： 我按照官方文档，在同一台服务器配置 bge-reranker-base 模型，直接 curl 是 ok 的，但是接入 one-api 后 curl 就报错了，不知道配置哪里出问题了，可否给个 成功样例 的 reRankModels 配置参考一下 ![image](https://private-user-images.githubusercontent.com/12623648/299259421-4313cef2-01a7-4cd3-96c3-2a571273a726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODg0MDIsIm5iZiI6MTcwNjA4ODEwMiwicGF0aCI6Ii8xMjYyMzY0OC8yOTkyNTk0MjEtNDMxM2NlZjItMDFhNy00Y2QzLTk2YzMtMmE1NzEyNzNhNzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MjE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZmJjMmYxMjM3ZWYzNjQ1MzZjODZhNGU4MGExNjkzMGM1NDhjMWExOTRkZGY1ODhmMzMwOTIwZTA5MGJjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRZ1KXlG5tdKgtWAK1k-qUFgg3iVe_RssPG5v5SMYyU)

这个不是标准模型，oneapi不支持。。直接填可用的地址就可以

**Comment by buctllx** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/50446880/299251226-10e2defb-5b30-4225-9874-edb8172267fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODc4NDcsIm5iZiI6MTcwNjA4NzU0NywicGF0aCI6Ii81MDQ0Njg4MC8yOTkyNTEyMjYtMTBlMmRlZmItNWIzMC00MjI1LTk4NzQtZWRiODE3MjI2N2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwN2Y3ZjQwMTRmMWY5MzZhZDVkZWVmZTkwYjgzNDY0NmZkNjE2ZWI3OThlOGU2MjQxNmFlNjU0YzU1ZmIzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TYLclHOI6i9vFmDyZWj438DnOYj5Upr8RVJlgijQrNU) 这块过滤逻辑有一点小小缺陷，如果勾选了 Rerank，但是 Rerank 模型运行失败，也会认为做了“相关度”过滤。因此，如果过滤无效，很有可能是rerank模型报错了。日志里也会有对应的报错提示。
> > 
> > 
> > 确实，我 curl 测试了一下 rerank api 确实报错了，正好触发了这个缺陷；歪个楼问个关于 rerank model 配置的问题： 我按照官方文档，在同一台服务器配置 bge-reranker-base 模型，直接 curl 是 ok 的，但是接入 one-api 后 curl 就报错了，不知道配置哪里出问题了，可否给个 成功样例 的 reRankModels 配置参考一下 ![image](https://private-user-images.githubusercontent.com/12623648/299259421-4313cef2-01a7-4cd3-96c3-2a571273a726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODg0MDIsIm5iZiI6MTcwNjA4ODEwMiwicGF0aCI6Ii8xMjYyMzY0OC8yOTkyNTk0MjEtNDMxM2NlZjItMDFhNy00Y2QzLTk2YzMtMmE1NzEyNzNhNzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MjE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZmJjMmYxMjM3ZWYzNjQ1MzZjODZhNGU4MGExNjkzMGM1NDhjMWExOTRkZGY1ODhmMzMwOTIwZTA5MGJjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRZ1KXlG5tdKgtWAK1k-qUFgg3iVe_RssPG5v5SMYyU)
> 
> 这个不是标准模型，oneapi不支持。。直接填可用的地址就可以

根据上面curl成功的截图，我直接配置 reRankModels 如下就可以了吗？
"reRankModels": [
        {
            "model": "bge-reranker-base",
            "name": "bge-reranker-base",
            "inputPrice": 0,
            "requestUrl": "http://10.80.253.10:6006/api/v1/rerank",
            "requestAuth": "sk-bge-reranker-base"
        }
    ]

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > ![image](https://private-user-images.githubusercontent.com/50446880/299251226-10e2defb-5b30-4225-9874-edb8172267fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..TYLclHOI6 i9vFmDyZWj438DnOYj5Upr8RVJlgijQrNU) This filtering logic has A small flaw is that if Rerank is checked but the Rerank model fails to run, it will be considered that "relevance" filtering has been performed. Therefore, if the filtering is invalid, it is likely that the rerank model reported an error. There will also be corresponding error messages in the log.
>>
>>
> > Indeed, I curl tested the rerank api and it indeed reported an error, which happened to trigger this defect; Wai Ge Lou asked a question about the rerank model configuration: I followed the official documentation and configured the bge-reranker-base model on the same server. Direct curl is ok, but after connecting to one-api, curl reports an error. I don’t know where the problem is in the configuration. Can you give me a successful example of reRankModels configuration for reference? [image](https://private-user- images.githubusercontent.com/12623648/299259421-4313cef2-01a7-4cd3-96c3-2a571273a726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..rRZ1KXlG5tdKgtWAK1k-qU Fgg3iVe_RssPG5v5SMYyU)
>
> This is not a standard model and is not supported by oneapi. . Just fill in the available address directly

According to the above screenshot of successful curl, can I directly configure reRankModels as follows?
"reRankModels": [
        {
            "model": "bge-reranker-base",
            "name": "bge-reranker-base",
            "inputPrice": 0,
            "requestUrl": "http://10.80.253.10:6006/api/v1/rerank",
            "requestAuth": "sk-bge-reranker-base"
        }
    ]

**Comment by buctllx** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/50446880/299251226-10e2defb-5b30-4225-9874-edb8172267fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODc4NDcsIm5iZiI6MTcwNjA4NzU0NywicGF0aCI6Ii81MDQ0Njg4MC8yOTkyNTEyMjYtMTBlMmRlZmItNWIzMC00MjI1LTk4NzQtZWRiODE3MjI2N2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwN2Y3ZjQwMTRmMWY5MzZhZDVkZWVmZTkwYjgzNDY0NmZkNjE2ZWI3OThlOGU2MjQxNmFlNjU0YzU1ZmIzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TYLclHOI6i9vFmDyZWj438DnOYj5Upr8RVJlgijQrNU) 这块过滤逻辑有一点小小缺陷，如果勾选了 Rerank，但是 Rerank 模型运行失败，也会认为做了“相关度”过滤。因此，如果过滤无效，很有可能是rerank模型报错了。日志里也会有对应的报错提示。
> > 
> > 
> > 确实，我 curl 测试了一下 rerank api 确实报错了，正好触发了这个缺陷；歪个楼问个关于 rerank model 配置的问题： 我按照官方文档，在同一台服务器配置 bge-reranker-base 模型，直接 curl 是 ok 的，但是接入 one-api 后 curl 就报错了，不知道配置哪里出问题了，可否给个 成功样例 的 reRankModels 配置参考一下 ![image](https://private-user-images.githubusercontent.com/12623648/299259421-4313cef2-01a7-4cd3-96c3-2a571273a726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODg0MDIsIm5iZiI6MTcwNjA4ODEwMiwicGF0aCI6Ii8xMjYyMzY0OC8yOTkyNTk0MjEtNDMxM2NlZjItMDFhNy00Y2QzLTk2YzMtMmE1NzEyNzNhNzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MjE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZmJjMmYxMjM3ZWYzNjQ1MzZjODZhNGU4MGExNjkzMGM1NDhjMWExOTRkZGY1ODhmMzMwOTIwZTA5MGJjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRZ1KXlG5tdKgtWAK1k-qUFgg3iVe_RssPG5v5SMYyU)
> 
> 这个不是标准模型，oneapi不支持。。直接填可用的地址就可以

我修改配置后试了一下，看日志 rerank 是超时（curl测试没问题），结果还是没有过滤掉小于 最低相关度 的引用数据。
![image](https://github.com/labring/FastGPT/assets/12623648/1ad74512-fc19-4743-abb4-3c0363d44421)
![image](https://github.com/labring/FastGPT/assets/12623648/e84410b4-a316-4fb2-a639-5d8000a47630)
![image](https://github.com/labring/FastGPT/assets/12623648/8bd860ba-d2a2-45fa-a570-18b5959ef872)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > ![image](https://private-user-images.githubusercontent.com/50446880/299251226-10e2defb-5b30-4225-9874-edb8172267fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..TYLclHOI6 i9vFmDyZWj438DnOYj5Upr8RVJlgijQrNU) This filtering logic has A small flaw is that if Rerank is checked but the Rerank model fails to run, it will be considered that "relevance" filtering has been performed. Therefore, if the filtering is invalid, it is likely that the rerank model reported an error. There will also be corresponding error messages in the log.
>>
>>
> > Indeed, I curl tested the rerank api and it did report an error, which happened to trigger this defect; I would like to ask a question about the rerank model configuration: I followed the official documentation and configured the bge-reranker-base model on the same server. Direct curl is ok, but after connecting to one-api, curl reports an error. I don’t know where the problem is in the configuration. Can you give me a successful example of reRankModels configuration for reference? [image](https://private-user- images.githubusercontent.com/12623648/299259421-4313cef2-01a7-4cd3-96c3-2a571273a726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..rRZ1KXlG5tdKgtWAK1k-qU Fgg3iVe_RssPG5v5SMYyU)
>
> This is not a standard model and is not supported by oneapi. . Just fill in the available address directly

I tried it after modifying the configuration and found that the rerank timeout in the log (curl test was no problem), but the result was that the reference data smaller than the minimum correlation was still not filtered out.
![image](https://github.com/labring/FastGPT/assets/12623648/1ad74512-fc19-4743-abb4-3c0363d44421)
![image](https://github.com/labring/FastGPT/assets/12623648/e84410b4-a316-4fb2-a639-5d8000a47630)
![image](https://github.com/labring/FastGPT/assets/12623648/8bd860ba-d2a2-45fa-a570-18b5959ef872)

**Comment by buctllx** [comment]
更新一下状态：

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Update the status:

**Comment by c121914yu** [comment]
> 更新一下状态：
> 
> 1. 在设置有 rerank model 且 rerank 访问错误的时候会导致“最低相关度”功能失效；
> 2. 至于我自己 rerank 超时的问题，是因为没有开放端口访问，建议在说明文档中加一下；
4.6.8做了优化，返回的rerank状态会以实际调用为准。
