### ISSUE TITLE
V4.6.7 The output of the dialogue interface has been changed to the output of paragraphs, and the reading experience has declined.

### ISSUE THREAD

**Issue by zaite** [labring/FastGPT#777]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
V4.6.7对话界面的流式输出改成了一段话一段话的输出，阅读体验感下降了，能不能优化一下，对比下还是老版本的输出方式好用，对阅读友好
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
The streaming output of the dialogue interface in V4.6.7 has been changed to the output of paragraphs. The reading experience has declined. Can it be optimized? In comparison, the output method of the old version is still easy to use and friendly to reading.
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by zaite** [comment]
而且在回复速度上明显感觉慢了很多（应该是这种新的输出方式造成了）

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
And the reply speed obviously feels much slower (probably caused by this new output method)

**Comment by zaite** [comment]
申请关闭，已经查到是接口的问题，而非fastgpt的bug

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The application is closed. It has been found that it is an interface problem and not a fastgpt bug.

**Comment by c121914yu** [comment]
> V4.6.7对话界面的流式输出改成了一段话一段话的输出，阅读体验感下降了，能不能优化一下，对比下还是老版本的输出方式好用，对阅读友好

底部可以自行 close

**Comment by wbext** [comment]
> 而且在回复速度上明显感觉慢了很多（应该是这种新的输出方式造成了）

哥我也觉得4.6.7v版本以后回复速度比以前慢，不知道是不是跟你一样的问题，我可以联系你吗？我的邮箱是1215922548@qq.com，或者可以留下你的联系方式
