### ISSUE TITLE
V4.6.7 "Debug Preview" interface "Regenerate" button of the conversation record, the conversation record will be deleted

### ISSUE THREAD

**Issue by buctllx** [labring/FastGPT#780]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本 V4.6.7 

**问题描述**
点击“调试预览”界面的 “重新生成”按钮，对话记录会被删除。
![image](https://github.com/labring/FastGPT/assets/12623648/aeaf6571-003c-4a7f-b007-b82a5f115e69)

**复现步骤**
1. 在“调试预览”界面先随便问一个问题llm回答；
2. 回答完成后点击上一步提问中的 “重新生成”按钮，改对话会被删除并没有重新生成；

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version V4.6.7

**Problem Description**
Click the "Regenerate" button on the "Debug Preview" interface, and the conversation record will be deleted.
![image](https://github.com/labring/FastGPT/assets/12623648/aeaf6571-003c-4a7f-b007-b82a5f115e69)

**Steps to reproduce**
1. In the "Debug Preview" interface, ask a question and llm answer it;
2. After completing the answer, click the "Regenerate" button in the previous question. The conversation will be deleted and not regenerated;

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This problem exists not only in debugging preview, but also in all chat interfaces. It needs to be fixed urgently.

**Comment by c121914yu** [comment]
昨天已经修复了，用的不多，留着下个版本一起提

**Comment by zhanghx0905** [comment]
> 昨天已经修复了，用的不多，留着下个版本一起提

能不能给个临时解决的patch，非常感谢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> It was fixed yesterday and is not used much. It will be mentioned in the next version.

Can you give me a temporary fix patch? Thank you very much.

**Comment by c121914yu** [comment]
> > 昨天已经修复了，用的不多，留着下个版本一起提
> 
> 能不能给个临时解决的patch，非常感谢

嗯，已经提了，正在打 action
