### ISSUE TITLE
Knowledge graph integration

### ISSUE THREAD

**Issue by deerleo** [labring/FastGPT#788]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

引入知识图谱，实现更复杂的关系查询。

**应用场景**

向量检索并不能满足所有场景，比如：提取出来 合同金额 > 10w 的所有文档

**相关示例**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there are currently no similar features
- [ ] I have confirmed that I have upgraded to the latest version
- [ ] I have fully reviewed the project README and determined that the existing version cannot meet the needs.
- [ ] I understand and am willing to follow up on this feature, assist with testing and provide feedback
- [x] I understand and agree with the above content, and understand that project maintainers have limited energy. **Features that do not follow the rules may be ignored or closed directly**

**Function description**

Introduce knowledge graph to achieve more complex relationship queries.

**Application Scenario**

Vector retrieval cannot satisfy all scenarios, for example: extract all documents with contract amount > 100,000

**Related Examples**

**Comment by c121914yu** [comment]
This feature is not planned for the open source version
