### ISSUE TITLE
the model selection list in the application settings has become empty

### ISSUE THREAD

**Issue by nickboyabc** [labring/FastGPT#790]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
After upgrading to 4.6.7 with pull, the model selection list in the application settings has become empty, how to restore it?
通过pull一键升级到4.6.7后，应用设置的 模型选择列表变空表了，如何恢复呢
![1](https://github.com/labring/FastGPT/assets/120318135/1f2d0562-d92b-4ef5-913b-e725010beeba)

**复现步骤**

**预期结果**

**相关截图**

**Comment by excitedstate** [comment]
v4.6.7: 将config.json中的llmModels改成chatModels, 可以临时解决这一问题，副作用未知....

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
v4.6.7: Change llmModels in config.json to chatModels, which can temporarily solve this problem. The side effects are unknown....

**Comment by c121914yu** [comment]
如楼上说的，检查配置文件。
