### ISSUE TITLE
connectToDatabase loop calling problem

### ISSUE THREAD

**Issue by uestcsongtaoli** [labring/FastGPT#792]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [] 公有云版本
- [x] 私有部署版本

**问题描述**
projects/app/src/service/mongo.ts的 connectToDatabase 函数调用了 connectMongo，而 connectMongo 中的 afterHook 钩子又调用了 getInitConfig。然后，getInitConfig 函数中又调用了 connectToDatabase。
这里的循环调用没弄明白。
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [] Public cloud version
- [x] Private deployment version

**Problem Description**
The connectToDatabase function of projects/app/src/service/mongo.ts calls connectMongo, and the afterHook hook in connectMongo calls getInitConfig. Then, connectToDatabase is called in the getInitConfig function.
I don't understand the loop call here.
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
注意看if

**Comment by c121914yu** [comment]
> 注意看if

connectMongo只会调用一次，初始化后就不会再调用了。
