### ISSUE TITLE
How to add Baidu Wenxin’s Embedding-V1 model to VectorModels:

### ISSUE THREAD

**Issue by austincityu** [labring/FastGPT#793]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**
在config.json总添加了百度的Embedding-V1,但是并不能生效。
  "vectorModels": [
    {
      "model": "Embedding-V1",
      "name": "文心向量模型",
      "inputPrice": 0,
      "outputPrice": 0,
      "defaultToken": 700,
      "maxToken": 3000,
      "weight": 100
    },
    {
      "model": "text-embedding-ada-002",
      "name": "Embedding-2",
      "inputPrice": 0,
      "outputPrice": 0,
      "defaultToken": 700,
      "maxToken": 3000,
      "weight": 100
    }

报错如下：
Embedding Error Embedding API 404
Embedding API 404
error => Embedding API 404
[ERROR] 2024-01-26 08:05:00 Embedding API 404 
{ message: undefined, stack: undefined }
【index】Task done

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
oneapi 里添加，和其他模型方法一致。
