### ISSUE TITLE
I made a small ChatGPT application in WeChat. After connecting fastGPT and api key, after specifying the chatId, I can only successfully send the conversation once, and an error will be reported the second time.

### ISSUE THREAD

**Issue by guoxin2235** [labring/FastGPT#796]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
   V4.6.7

- [x] 公有云版本
- [ ] 私有部署版本

**问题描述**
API对话时，ChatId冲突。
不管是在fastGPT线上版还是在外部使用API对话时，chatId都存在冲突，只能成功发送二次对话，第三次就报错。

**复现步骤**
在微信中做了一个ChatGPT小应用，接入了fastGPT和api key后，在指定chatId后，只能成功发送二次对话，第三次就报错。

**预期结果**
可以使用同一个chatId实现上下文连续对话，如果不使用chatId，则无法实现上下文问答的的关联

**相关截图**
![QQ图片20240129205548](https://github.com/labring/FastGPT/assets/157015592/6c966a10-8fd7-43c3-a7df-1a15d39ead2d)

![报错日志](https://github.com/labring/FastGPT/assets/157015592/be3ece1a-8964-4f98-9750-9e7acd3ffb7a)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [x] Public cloud version
- [ ] private deployment version

**Problem Description**
I made a small ChatGPT application in WeChat. After connecting fastGPT and api key, after specifying the chatId, I can only successfully send the conversation once, and an error will be reported the second time.

**Steps to reproduce**
I made a small ChatGPT application in WeChat. After connecting fastGPT and api key, after specifying the chatId, I can only successfully send the conversation once, and an error will be reported the second time.

**expected outcome**
You can use the same chatId to achieve contextual continuous dialogue. If you do not use chatId, you cannot achieve contextual Q&A correlation.
**Related screenshots**
![Error log](https://github.com/labring/FastGPT/assets/157015592/be3ece1a-8964-4f98-9750-9e7acd3ffb7a)

**Comment by c121914yu** [comment]
感觉是你编排问题？这边20上下文都可以。

**Comment by guoxin2235** [comment]
![QQ图片20240201000907](https://github.com/labring/FastGPT/assets/157015592/3c51c6b1-1ff6-42e3-9715-281917e8b9ed)
编排图

**Comment by guoxin2235** [comment]
> 方便发下编排？
我使用了oneapi转发的gemini pro的api，是否跟这个有关？
![QQ图片20240201000907](https://github.com/labring/FastGPT/assets/157015592/a399979e-452c-44ed-9f38-c1df7bb8ae0d)

**Comment by c121914yu** [comment]
你把历史记录改成偶数 试试
