### ISSUE TITLE
sse.ts handles chunks errors

### ISSUE THREAD

**Issue by ningpengtao-coder** [labring/FastGPT#798]
sse.ts的parseStreamChunk方法未考虑chunk不完整的情况，导致不完整的chunk被丢弃（上半部分）。不完整的chunk（下半部分）会导致后续的chunk无法解析json。最终导致仅显示部分内容。

请考虑使用更加健壮的库处理sse（ https://github.com/Azure/fetch-event-source.git ）。

```typescript
export class SSEParseData {
  storeReadData = '';
  storeEventName = '';

  parse(item: { event: string; data: string }) {
    if (item.data === '[DONE]') return { eventName: item.event, data: item.data };

    if (item.event) {
      this.storeEventName = item.event;
    }

    try {
      // 1.不完整的chunk + 完整的chunk
      const formatData = this.storeReadData + item.data;
	  
      // 2.解析错误
      const parseData = JSON.parse(formatData);
      const eventName = this.storeEventName;

      this.storeReadData = '';
      this.storeEventName = '';

      return {
        eventName,
        data: parseData
      };
    } catch (error) {
      if (typeof item.data === 'string' && !item.data.startsWith(': ping')) {
	    //3.不完整的chunk + 完整的chunk 1...n
        this.storeReadData += item.data;
      } else {
        this.storeReadData = '';
      }
    }
	// 4.后续chunk永远是空对象
    return {};
  }
}
```

**Comment by c121914yu** [comment]
catch里不是处理了么

**Comment by ningpengtao-coder** [comment]
@c121914yu 会一直走这个条件“typeof item.data === 'string' && !item.data.startsWith(': ping')”，一直拼接“this.storeReadData += item.data;“

**Comment by ningpengtao-coder** [comment]
@c121914yu catch仅考虑了排除ping开头的情况。我遇到的情况是chunk不完整的情况。
完整chunk：
event: answer
data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"content":"电影"},"index":0,"finish_reason":null}]}
不完整chunk（上半）：
event: an
不完整chunk（下半）：
swer
data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"content":"电影"},"index":0,"finish_reason":null}]}

**Comment by c121914yu** [comment]
> @c121914yu catch仅考虑了排除ping开头的情况。我遇到的情况是chunk不完整的情况。
> 完整chunk：
> event: answer
> data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"content":"电影"},"index":0,"finish_reason":null}]}
> 不完整chunk（上半）：
> event: an
> 不完整chunk（下半）：
> swer
> data: {"id":"","object":"","created":0,"model":"","choices":[{"delta":{"content":"电影"},"index":0,"finish_reason":null}]}

对的呀。不是 ping 开头就拼接

**Comment by ningpengtao-coder** [comment]
@c121914yu 我更新了一下问题，麻烦你看一下。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@c121914yu I updated the question, please take a look.

**Comment by c121914yu** [comment]
> @c121914yu 我更新了一下问题，麻烦你看一下。

了解了，是指丢包的情况？

**Comment by ningpengtao-coder** [comment]
> > @c121914yu 我更新了一下问题，麻烦你看一下。
> 
> 了解了，是指丢包的情况？

不存在丢包问题，是一个chunk被分成两个部分并且上半部分没有放到storeReadData导致的问题。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > @c121914yu I updated the question, please take a look.
>
> Understood, does it mean packet loss?

There is no packet loss problem. It is a problem caused by a chunk being divided into two parts and the upper part not being placed in storeReadData.

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/804/commits/eb5d5edafe5df40d8c2ae1eb33bc58b4d5fe1c75 这个commit优化了。微软的包很久没更新了，使用了chatNextWeb相同的包。
https://github.com/labring/FastGPT/pull/804
