### ISSUE TITLE
sealos api request 404 after deploying fastgpt

### ISSUE THREAD

**Issue by 17607683785** [labring/FastGPT#801]
我使用了sealos部署了fastgpt，但是我在请求api的时候发生了404的错误，下面是我的请求参数：
curl --location --request POST 'https://pcmrmqnr.cloud.sealos.io/api' \
--header 'Authorization: Bearer openapi-M2FRqgUUeM59Pq9pZ2Y1BA8booNC5wErZ' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: pcmrmqnr.cloud.sealos.io' \
--header 'Connection: keep-alive' \
--data-raw '{
    "chatId": "111",
    "stream": false,
    "detail": false,
    "messages": [
        {
            "content": "导演是谁",
            "role": "user"
        }
    ]
}'
<img width="1013" alt="Snipaste_2024-01-30_00-51-13" src="https://github.com/labring/FastGPT/assets/107823857/a329daae-50d6-4b8f-9e5f-83d029db898c">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I used sealos to deploy fastgpt, but a 404 error occurred when I requested the api. The following are my request parameters:
curl --location --request POST 'https://pcmrmqnr.cloud.sealos.io/api' \
--header 'Authorization: Bearer openapi-M2FRqgUUeM59Pq9pZ2Y1BA8booNC5wErZ' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: pcmrmqnr.cloud.sealos.io' \
--header 'Connection: keep-alive' \
--data-raw '{
    "chatId": "111",
    "stream": false,
    "detail": false,
    "messages": [
        {
            "content": "Who is the director",
            "role": "user"
        }
    ]
}'
<img width="1013" alt="Snipaste_2024-01-30_00-51-13" src="https://github.com/labring/FastGPT/assets/107823857/a329daae-50d6-4b8f-9e5f-83d029db898c">

**Comment by c121914yu** [comment]
地址不对，看文档的自己。
