### ISSUE TITLE
During private deployment, the data set is always being indexed and cannot be ready.

### ISSUE THREAD

**Issue by Grewizard11** [labring/FastGPT#802]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**
![1](https://github.com/labring/FastGPT/assets/140785752/83d7166b-afb9-4528-9322-d888dd380e05)
如图所示，私有化部署后，建立知识库。但是知识库的数据集上传成功后，一直处于索引状态，没有ready，想知道是什么原因。困扰好几天了

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
![1](https://github.com/labring/FastGPT/assets/140785752/83d7166b-afb9-4528-9322-d888dd380e05)
As shown in the figure, after privatization deployment, a knowledge base is established. However, after the data set of the knowledge base is successfully uploaded, it is always in the index state and is not ready. I want to know the reason. Been troubled for several days

**Comment by c121914yu** [comment]
emm，看日志了么

**Comment by c121914yu** [comment]
90%是key不行，

**Comment by shengxiagit** [comment]
遇到了同样的问题，同时发现在one-api中是一直在循环请求embedding模型

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I encountered the same problem and found that the embedding model was constantly being requested in a loop in one-api.

**Comment by shengxiagit** [comment]
> 遇到了同样的问题，同时发现在one-api中是一直在循环请求embedding模型



> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> I encountered the same problem and found that the embedding model was constantly being requested in a loop in one-api.

![Uploading iShot_2024-02-02_10.34.23.png…]()

**Comment by Grewizard11** [comment]
> 90%是key不行，

解决了，的确是key不行。openai送的那5刀，有每分钟处理数据的次数限制

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> 90% of them are keys.

Solved, it is indeed the key that is not working. The $5 provided by openai has a limit on the number of times data can be processed per minute.
