### ISSUE TITLE
Openai api, connection error

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#803]
![image](https://github.com/labring/FastGPT/assets/40045458/f4e00747-897a-49ae-9a1d-966e94ff87d0)
![image](https://github.com/labring/FastGPT/assets/40045458/d99e8c87-96d6-403d-9b7d-f120bd1e3f91)
![image](https://github.com/labring/FastGPT/assets/40045458/73b3b251-169d-427c-9890-34d07f8ae0a1)
![image](https://github.com/labring/FastGPT/assets/40045458/4bc1e12c-9130-449b-92d1-c6976924945f)
![image](https://github.com/labring/FastGPT/assets/40045458/0e4fe5c0-17f5-4fb5-8cbb-f7ce9c8cd76f)
![image](https://github.com/labring/FastGPT/assets/40045458/310aa28c-b594-48ef-b683-8b85c62c7745)
![image](https://github.com/labring/FastGPT/assets/40045458/28574a0c-c44a-4a23-9099-e4b6cda271f4)
![image](https://github.com/labring/FastGPT/assets/40045458/de664b87-4249-4761-ab23-e12900b30e78)

如图，一直都是connection error,求助，是哪一块出了问题

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![image](https://github.com/labring/FastGPT/assets/40045458/f4e00747-897a-49ae-9a1d-966e94ff87d0)
![image](https://github.com/labring/FastGPT/assets/40045458/d99e8c87-96d6-403d-9b7d-f120bd1e3f91)
![image](https://github.com/labring/FastGPT/assets/40045458/73b3b251-169d-427c-9890-34d07f8ae0a1)
![image](https://github.com/labring/FastGPT/assets/40045458/4bc1e12c-9130-449b-92d1-c6976924945f)
![image](https://github.com/labring/FastGPT/assets/40045458/0e4fe5c0-17f5-4fb5-8cbb-f7ce9c8cd76f)
![image](https://github.com/labring/FastGPT/assets/40045458/310aa28c-b594-48ef-b683-8b85c62c7745)
![image](https://github.com/labring/FastGPT/assets/40045458/28574a0c-c44a-4a23-9099-e4b6cda271f4)
![image](https://github.com/labring/FastGPT/assets/40045458/de664b87-4249-4761-ab23-e12900b30e78)


As shown in the picture, it always shows connection error. Please help, which part is the problem?

**Comment by xiaoToby** [comment]
难道是要因为调用openai-gpt，需要收费？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there a charge for calling openai-gpt?

**Comment by c121914yu** [comment]
> 难道是要因为调用openai-gpt，需要收费？

怎么可能不收费

**Comment by c121914yu** [comment]
不过，大概率是网没连上，sealosIO最近被墙了不少，有些地区没法连接。可以看看OneAPI有没有请求日志。

**Comment by weifengzyl** [comment]
如何解决的呢????

**Comment by xiaoToby** [comment]
> 如何解决的呢????

可以不调用国外的这些模型，可以去申请chatglm2的api-key，或者本地部署chatglm2，自定义sk-key,也能用上
