### ISSUE TITLE
ai回复乱码问题，开始回复会显示乱码，回复完毕，刷新页面后又显示正常

### ISSUE THREAD

**Issue by boleyn** [labring/FastGPT#808]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
ai回复的内容出现乱码
**复现步骤**
问ai问题
**预期结果**
编码正常的内容
**相关截图**
<img width="480" alt="image" src="https://github.com/labring/FastGPT/assets/24293664/e9faae2e-2c4d-46fd-9546-522a595c7fc4">
![img_v3_027k_6a426263-cd2d-44b1-8ec4-0d56bdd485ag](https://github.com/labring/FastGPT/assets/24293664/fb1dc766-93b6-4291-ab61-7da7a990cc06)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**

**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by boleyn** [comment]
操作失误

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Operation error

**Comment by boleyn** [comment]
重新编辑

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
re-edit

**Comment by boleyn** [comment]
![img_v3_027k_6a426263-cd2d-44b1-8ec4-0d56bdd485ag](https://github.com/labring/FastGPT/assets/24293664/1a7a0e53-6d09-4d07-a645-5ec6f49a362f)

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/804
可以看看这个pr是不是解决了
