### ISSUE TITLE
How to dynamically select a knowledge base, or operate through API.

### ISSUE THREAD

**Issue by zhoufn** [labring/FastGPT#809]
**例行检查**

**你的版本**

**问题描述**
有多个知识库，怎么让用户动态的选择呢？

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

**your version**

**Problem Description**
There are multiple knowledge bases, how can users make dynamic choices?

**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by lijiajun1997** [comment]
考虑让用户用关键词+判断工具+加知识库组合？

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Consider allowing users to use a combination of keywords + judgment tools + knowledge base?

**Comment by c121914yu** [comment]
目前不直接支持该功能

**Comment by lijiajun1997** [comment]
<img width="552" alt="1997a01c622dbeb16065a8682fff13f" src="https://github.com/labring/FastGPT/assets/156336589/aae9003c-896d-4f09-9f48-3546951d012d">
