### ISSUE TITLE
部分系统不兼容，导致页面崩溃。如果可以，请联系作者，反馈下具体操作和页面。 大部分是 苹果 的 safari 浏览器导致，可以尝试更换 chrome 浏览器。

### ISSUE THREAD

**Issue by CodingNowPls** [labring/FastGPT#815]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
部分系统不兼容，导致页面崩溃。如果可以，请联系作者，反馈下具体操作和页面。 大部分是 苹果 的 safari 浏览器导致，可以尝试更换 chrome 浏览器。
**复现步骤**
使用docker-compose部署的
**预期结果**
增加知识库的时候，点击添加就报错了
**相关截图**
![image](https://github.com/labring/FastGPT/assets/22097022/acad10c0-7fea-43a4-b5cb-32b4d86c53e8)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [√ ] I have confirmed that there is currently no similar issue
- [√ ] I have fully reviewed the project README and [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [√] I used my own key and confirmed that my key can be used normally
- [√ ] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [√ ] Private deployment version

**Problem Description**
Some systems are incompatible, causing the page to crash. If possible, please contact the author and provide feedback on the specific operations and pages. Most of them are caused by Apple's Safari browser. You can try to change the Chrome browser.
**Steps to reproduce**
Deployed using docker-compose
**expected outcome**
When adding a knowledge base, I get an error when I click Add.
**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/22097022/acad10c0-7fea-43a4-b5cb-32b4d86c53e8)

**Comment by c121914yu** [comment]
配置文件错误

**Comment by CodingNowPls** [comment]
> 配置文件错误

不知道哪里错了，能给个提示么

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Configuration file error

I don’t know where I went wrong. Can you give me a hint?

**Comment by c121914yu** [comment]
> > 配置文件错误
> 
> 不知道哪里错了，能给个提示么

日志会提示

**Comment by CodingNowPls** [comment]
> > > 配置文件错误
> > 
> > 
> > 不知道哪里错了，能给个提示么
> 
> 日志会提示

我就按照文档改了登录密码跟api-key 还有一个启动端口，其他都没有改，日志没看到有什么报错的信息

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > Configuration file error
>>
>>
> > I don’t know what’s wrong. Can you give me a hint?
>
> The log will prompt

I changed the login password, api-key, and startup port according to the documentation, but nothing else was changed. I didn’t see any error messages in the logs.

**Comment by excitedstate** [comment]
同样的问题。日志指向了/app/projects/app/.next/server/pages/api/core/dataset/create.js:1:2130位置
<img width="756" alt="image" src="https://github.com/labring/FastGPT/assets/44634316/50992ef4-2608-416f-bd55-4044e324a295">
这个位置访问了global.qaModels[0].model
<img width="253" alt="image" src="https://github.com/labring/FastGPT/assets/44634316/b10409bc-33c8-48a3-8f1c-1bd549b15299">
我没有在配置文件中找到这一项，我猜测我需要在config.json中添加一个叫qaModels的array；
<img width="896" alt="image" src="https://github.com/labring/FastGPT/assets/44634316/c9223428-7264-43d2-8f60-aa977e190305">
我不会写这个array，所以就把chatModels复制了一份过来😂。现在不出现这个问题了。
<img width="521" alt="image" src="https://github.com/labring/FastGPT/assets/44634316/46ed7433-a066-4e69-8fe7-1ca5d4edeabf">
副作用未知。请问有大佬知道在哪里找config.json的schema吗？求求了~~

**Comment by CodingNowPls** [comment]
> 同样的问题。日志指向了/app/projects/app/.next/server/pages/api/core/dataset/create.js:1:2130位置 <img alt="image" width="756" src="https://private-user-images.githubusercontent.com/44634316/301736536-50992ef4-2608-416f-bd55-4044e324a295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTMyMjAsIm5iZiI6MTcwNjg1MjkyMCwicGF0aCI6Ii80NDYzNDMxNi8zMDE3MzY1MzYtNTA5OTJlZjQtMjYwOC00MTZmLWJkNTUtNDA0NGUzMjRhMjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA1NDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyM2ZlNWM2MWUwMTRjNjZlMzMwMzUzNDA3ZDNhYzdlNjUzMzAzMTYzNDAxYTY1OGEwZjVjOWI3YmJkOWRkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._wFjEFjXKoG6XQ8oq_bhI6fMwWgP3M23i6Fd0I23uNs"> 这个位置访问了global.qaModels[0].model <img alt="image" width="253" src="https://private-user-images.githubusercontent.com/44634316/301736764-b10409bc-33c8-48a3-8f1c-1bd549b15299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTMyMjAsIm5iZiI6MTcwNjg1MjkyMCwicGF0aCI6Ii80NDYzNDMxNi8zMDE3MzY3NjQtYjEwNDA5YmMtMzNjOC00OGEzLThmMWMtMWJkNTQ5YjE1Mjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA1NDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YTVjMmFjYjRjMTc1OTk4OTYzYTQ2YThjZjkzOGNlODVjNTViMTUwNWE3NTYzZGU5MjBkOTQ5N2I1MDM5OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yFSynst6v8zUIskRMqRY888d7oaJxrNprRdzjTKfjpY"> 我没有在配置文件中找到这一项，我猜测我需要在config.json中添加一个叫qaModels的array； <img alt="image" width="896" src="https://private-user-images.githubusercontent.com/44634316/301737228-c9223428-7264-43d2-8f60-aa977e190305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTMyMjAsIm5iZiI6MTcwNjg1MjkyMCwicGF0aCI6Ii80NDYzNDMxNi8zMDE3MzcyMjgtYzkyMjM0MjgtNzI2NC00M2QyLThmNjAtYWE5NzdlMTkwMzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA1NDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YzE5MTg5NDk1ZmZkN2FjY2RiMzhjOTE1YjcxMGE2MzhlYmEyYjI0NDQxYWY3ODUxNzJiZmRjODEwZDBkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gGdyJdixANlGuja7dXqF56BJX7fk_LDQChDvJ6Qz5hY"> 我不会写这个array，所以就把chatModels复制了一份过来😂。现在不出现这个问题了。 <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/44634316/301738399-46ed7433-a066-4e69-8fe7-1ca5d4edeabf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTMyMjAsIm5iZiI6MTcwNjg1MjkyMCwicGF0aCI6Ii80NDYzNDMxNi8zMDE3MzgzOTktNDZlZDc0MzMtYTA2Ni00ZTY5LThmZTctMWNhNWQ0ZWRlYWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA1NDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYTJhNDc0YTQ4MzE2NjcwOTdiMjMxZTcyZTBlYTM4OTNmNDUwMDRlMjYxZTdmNjgxNjlmOWM1Mjg5NDY0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.444SLk7lH096_uIeid5brAE0VHUkNU7ZRPedOM_ajaA"> 副作用未知。请问有大佬知道在哪里找config.json的schema吗？求求了~~

我加了群在问，等我弄好了给你说

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
>Same problem. The log points to the location /app/projects/app/.next/server/pages/api/core/dataset/create.js:1:2130<img alt="image" width="756" src="https:// private-user-images.githubusercontent.com/44634316/301736536-50992ef4-2608-416f-bd55-4044e324a295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.._wFjEFjXKoG6XQ8oq_ bhI6fMwWgP3M23i6Fd0I23uNs"> This location accessed global.qaModels[0].model <img alt= "image" width="253" src="https://private-user-images.githubusercontent.com/44634316/301736764-b10409bc-33c8-48a3-8f1c-1bd549b15299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9. .yFSynst6v8zUIskRMqRY888d7oaJxrNprRdzjTKfjpY">i This item was not found in the configuration file. I guess I need to add an array called qaModels to config.json; <img alt="image" width="896" src="https://private-user-images .githubusercontent.com/44634316/301737228-c9223428-7264-43d2-8f60-aa977e190305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..gGdyJdixANlGuja7dXqF56BJX 7fk_LDQChDvJ6Qz5hY"> I can’t write this array, so I copied chatModels 😂. This problem no longer occurs. <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/44634316/301738399-46ed7433-a066-4e69-8fe7-1ca5d4edeabf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9. . 444SLk7lH096_uIeid5brAE0VHUkNU7ZRPedOM_ajaA"> Side effects unknown. Does anyone know where to find the schema of config.json? Please~~

I joined the group and am asking, I will let you know when I have it done.

**Comment by 1wingedangel** [comment]
docker-compose 部署的版本好像是4.6.7，要用以前的配置文件

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The version deployed by docker-compose seems to be 4.6.7, so you need to use the previous configuration file.

**Comment by CodingNowPls** [comment]
> docker-compose 部署的版本好像是4.6.7，要用以前的配置文件

麻烦问一下以前的配置文件在哪下载

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> The deployed version of docker-compose seems to be 4.6.7, so you need to use the previous configuration file.

Could you please tell me where to download the previous configuration files?

**Comment by 1wingedangel** [comment]
> > docker-compose 部署的版本好像是4.6.7，要用以前的配置文件
> 
> 麻烦问一下以前的配置文件在哪下载

看文档里有

https://doc.fastgpt.in/docs/development/configuration/

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > The deployed version of docker-compose seems to be 4.6.7, so you need to use the previous configuration file.
>
> Could you please tell me where to download the previous configuration files?

See it in the documentation

https://doc.fastgpt.in/docs/development/configuration/

**Comment by CodingNowPls** [comment]
> > > docker-compose 部署的版本好像是4.6.7，要用以前的配置文件
> > 
> > 
> > 麻烦问一下以前的配置文件在哪下载
> 
> 看文档里有
> 
> https://doc.fastgpt.in/docs/development/configuration/

谢谢

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > The deployed version of docker-compose seems to be 4.6.7, so you need to use the previous configuration file.
>>
>>
> > Could you please tell me where to download the previous configuration files?
>
> See the documentation
>
> https://doc.fastgpt.in/docs/development/configuration/

Thanks

**Comment by CodingNowPls** [comment]
> > > docker-compose 部署的版本好像是4.6.7，要用以前的配置文件
> > 
> > 
> > 麻烦问一下以前的配置文件在哪下载
> 
> 看文档里有
> 
> https://doc.fastgpt.in/docs/development/configuration/

看到了，确实是4.6.7，地址在这里  https://github.com/labring/FastGPT/pkgs/container/fastgpt，我打算pull最新的镜像，然后部署试试

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > The deployed version of docker-compose seems to be 4.6.7, so you need to use the previous configuration file.
>>
>>
> > Could you please tell me where to download the previous configuration files?
>
> See the documentation
>
> https://doc.fastgpt.in/docs/development/configuration/

I saw it, it is indeed 4.6.7. The address is here https://github.com/labring/FastGPT/pkgs/container/fastgpt. I plan to pull the latest image and then try to deploy it.

**Comment by CodingNowPls** [comment]
配置文件换成 docker-compose  的镜像地址换成：ghcr.io/labring/fastgpt:v4.6.8-alpha  然后用最新的配置就好了

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Change the configuration file to docker-compose and the image address to: ghcr.io/labring/fastgpt:v4.6.8-alpha and then use the latest configuration.

**Comment by huluohu** [comment]
## 环境
- 镜像：v4.6.8-alpha
- 配置：使用最新的4.6.8版本的配置
- 客户端：macOS版Edge 121.0.2277.83
## 问题
创建知识库时，页面会提示下面的错误，并自动跳转到知识库主页；创建文件夹正常。

![image](https://github.com/labring/FastGPT/assets/7138642/e65b1b27-33c0-487c-944f-3d8bd9f6631a)

**Comment by CodingNowPls** [comment]
> ## 环境
> * 镜像：v4.6.8-alpha
> * 配置：使用最新的4.6.8版本的配置
> * 客户端：macOS版Edge 121.0.2277.83
> 
> ## 问题
> 创建知识库时，页面会提示下面的错误，并自动跳转到知识库主页；创建文件夹正常。 ![image](https://private-user-images.githubusercontent.com/7138642/301808822-d156a20a-be7d-488b-9b10-dd8ea9945e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4Njk4NDEsIm5iZiI6MTcwNjg2OTU0MSwicGF0aCI6Ii83MTM4NjQyLzMwMTgwODgyMi1kMTU2YTIwYS1iZTdkLTQ4OGItOWIxMC1kZDhlYTk5NDVlOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTAyNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQzODk5MWU0ZjdiOTNkMzc2NmZiN2U3YTFjZGQ4ZGI3ZDYxYzFhYjZhZGE5ODE0ODAwNmU5NmExYTI1MDA4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F1eBd5a-OLahT41d4sQlnXUg0qW9utthte6JwrtgA10)
> 
> 补充：尝试了纯净安装的Chrome，也不能创建知识库，与Edge现象一样。

你把docker-compose 中改成fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:v4.6.8-alpha # git  
然后再用最新的配置文件试试

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> ## Environment
> * Mirror: v4.6.8-alpha
> * Configuration: Use the latest 4.6.8 version configuration
> * Client: macOS version Edge 121.0.2277.83
>
> ## Question
> When creating a knowledge base, the page will prompt the following error and automatically jump to the knowledge base homepage; creating a folder is normal. ![image](https://private-user-images.githubusercontent.com/7138642/301808822-d156a20a-be7d-488b-9b10-dd8ea9945e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRo dWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4Njk4NDEsIm5iZiI6MTcwNjg2OTU0MSwicGF0aCI6Ii83MTM4NjQyLzMwMTgwOD gyMi1kMTU2YTIwYS1iZTdkLTQ4OGItOWIxMC1kZDhlYTk5NDVlOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0Wk ElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTAyNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQzODk5MWU 0ZjdiOTNkMzc2NmZiN2U3YTFjZGQ4ZGI3ZDYxYzFhYjZhZGE5ODE0ODAwNmU5NmExYTI1MDA4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ .F1eBd5a-OLahT41d4sQlnXUg0qW9utthte6JwrtgA10)
>
> Supplement: I tried a pure installation of Chrome, but the knowledge base cannot be created, which is the same as Edge.

You change docker-compose to fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:v4.6.8-alpha # git
Then try again with the latest configuration file

**Comment by huluohu** [comment]
> > ## 环境
> > 
> > * 镜像：v4.6.8-alpha
> > * 配置：使用最新的4.6.8版本的配置
> > * 客户端：macOS版Edge 121.0.2277.83
> > 
> > ## 问题
> > 创建知识库时，页面会提示下面的错误，并自动跳转到知识库主页；创建文件夹正常。 ![image](https://private-user-images.githubusercontent.com/7138642/301808822-d156a20a-be7d-488b-9b10-dd8ea9945e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4Njk4NDEsIm5iZiI6MTcwNjg2OTU0MSwicGF0aCI6Ii83MTM4NjQyLzMwMTgwODgyMi1kMTU2YTIwYS1iZTdkLTQ4OGItOWIxMC1kZDhlYTk5NDVlOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTAyNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQzODk5MWU0ZjdiOTNkMzc2NmZiN2U3YTFjZGQ4ZGI3ZDYxYzFhYjZhZGE5ODE0ODAwNmU5NmExYTI1MDA4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F1eBd5a-OLahT41d4sQlnXUg0qW9utthte6JwrtgA10)
> > 补充：尝试了纯净安装的Chrome，也不能创建知识库，与Edge现象一样。
> 
> 你把docker-compose 中改成fastgpt: container_name: fastgpt image: ghcr.io/labring/fastgpt:v4.6.8-alpha # git 然后再用最新的配置文件试试

感谢回复。目前使用的镜像就是ghcr.io/labring/fastgpt:v4.6.8-alpha，配置文件也是最新4.6.8的，依然报不兼容错误。

> Compose.yml

<img width="757" alt="image" src="https://github.com/labring/FastGPT/assets/7138642/524d202f-4940-44ce-b8b1-cc93e154ce5c">

> config.json
<img width="794" alt="image" src="https://github.com/labring/FastGPT/assets/7138642/c26d26ee-80f7-4f65-a1d0-065c2666b188">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > ## Environment
>>
> > * Mirror: v4.6.8-alpha
> > * Configuration: Use the latest 4.6.8 version configuration
> > * Client: macOS version Edge 121.0.2277.83
>>
> > ## Question
> > When creating a knowledge base, the page will prompt the following error and automatically jump to the knowledge base homepage; the folder creation is normal. ![image](https://private-user-images.githubusercontent.com/7138642/301808822-d156a20a-be7d-488b-9b10-dd8ea9945e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRo dWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4Njk4NDEsIm5iZiI6MTcwNjg2OTU0MSwicGF0aCI6Ii83MTM4NjQyLzMwMTgwOD gyMi1kMTU2YTIwYS1iZTdkLTQ4OGItOWIxMC1kZDhlYTk5NDVlOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0Wk ElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTAyNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQzODk5MWU 0ZjdiOTNkMzc2NmZiN2U3YTFjZGQ4ZGI3ZDYxYzFhYjZhZGE5ODE0ODAwNmU5NmExYTI1MDA4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ .F1eBd5a-OLahT41d4sQlnXUg0qW9utthte6JwrtgA10)
> > Supplement: I tried a pure installation of Chrome, but the knowledge base cannot be created, which is the same as Edge.
>
> Change docker-compose to fastgpt: container_name: fastgpt image: ghcr.io/labring/fastgpt:v4.6.8-alpha # git and then try with the latest configuration file

Thanks Reply. The image currently used is ghcr.io/labring/fastgpt:v4.6.8-alpha, and the configuration file is also the latest 4.6.8, but the incompatibility error is still reported.

>Compose.yml

<img width="757" alt="image" src="https://github.com/labring/FastGPT/assets/7138642/524d202f-4940-44ce-b8b1-cc93e154ce5c">

> config.json
<img width="794" alt="image" src="https://github.com/labring/FastGPT/assets/7138642/c26d26ee-80f7-4f65-a1d0-065c2666b188">

**Comment by huluohu** [comment]
找到原因了，是因为datasetProcess全部都设置为false了，没找到可以作为知识库模型的模型。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I found the reason. It was because all datasetProcess settings were set to false, and no model that could be used as a knowledge base model was found.
