### ISSUE TITLE
User questions and knowledge base data cannot be input to AI

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#817]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本 4.6.8

**问题描述**
在知识库模式下经常会出现问题和知识库无法输入给AI，导致AI根据prompt进行胡乱回答。在限制知识库输出少于2000的时候不会出现。使用的GPT是GPT 3.5 turbo-16k。
**复现步骤**
1.设置知识库输出数据为4000.
2.提出一个问题。
3.AI没有根据数据库的答案进行回答，也没有检测到问题胡乱回答。
**预期结果**
正常回答问题。
**相关截图**
![image](https://github.com/labring/FastGPT/assets/156336589/bc9f2bea-498a-4b40-921e-c0acb23c0a94)
![image](https://github.com/labring/FastGPT/assets/156336589/a477ae36-7e87-4b4d-b2bf-534f1805bcf8)
![image](https://github.com/labring/FastGPT/assets/156336589/12b72924-6b70-4810-b12f-291bda66d195)
![image](https://github.com/labring/FastGPT/assets/156336589/d5fd68c4-aa66-4262-b717-7a6125fe9f04)

**Comment by lijiajun1997** [comment]
![image](https://github.com/labring/FastGPT/assets/156336589/b2160ce3-2e08-4d69-80e4-ab70a387c1c5)
正常对话如果超过2-3k也会无法传递给AI？ 之前版本没有遇到这个问题

**Comment by suwubee** [comment]
试下把知识库的为空和不为空逻辑分开来输出，看知识库是否有获取到，尤其设置了最低相关度。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Try outputting the empty and non-empty logic of the knowledge base separately to see if the knowledge base has been obtained, especially if the minimum correlation is set.

**Comment by lijiajun1997** [comment]
> 试下把知识库的为空和不为空逻辑分开来输出，看知识库是否有获取到，尤其设置了最低相关度。

看图3 知识库是有获取到信息的 怀疑是AI那里觉得字数超了  但不管是什么模型 超过3000字AI就无法正常工作

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Try to output the empty and non-empty logic of the knowledge base separately to see if the knowledge base has been obtained, especially if the minimum correlation is set.

Look at Figure 3. The knowledge base has acquired information. I suspect that the AI ​​thinks the number of words is too high. But no matter what model it is, the AI ​​cannot work properly if it exceeds 3,000 words.
