### ISSUE TITLE
Can you introduce how to use input parameters and input parameter types in plug-in development?

### ISSUE THREAD

**Issue by huluohu** [labring/FastGPT#818]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
使用插件功能开发一个搜索插件，但是对入参的类型不是太理解，wiki中也没看到相关的说明
**复现步骤**
1、添加入参，我想选择用户问题，不知该选择哪种类型，主要是“外部数据”这个不知道具体是指什么

**预期结果**

**相关截图**
<img width="889" alt="image" src="https://github.com/labring/FastGPT/assets/7138642/d1f3bf9a-ddc5-49f4-9c27-9138b1af0bc4">

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
Use the plug-in function to develop a search plug-in, but I don’t quite understand the types of input parameters, and I don’t see any relevant instructions in the wiki.
**Steps to reproduce**
1. Add input parameters. I want to select user questions. I don’t know which type to choose. The main thing is “external data”. I don’t know what it specifically refers to.

**expected outcome**

**Related screenshots**
<img width="889" alt="image" src="https://github.com/labring/FastGPT/assets/7138642/d1f3bf9a-ddc5-49f4-9c27-9138b1af0bc4">

**Comment by c121914yu** [comment]
外部数据: 模块外部传入的数据。(ui 上表现出，是一个输入连线)
其他类型都是有 ui 渲染的，输入框之类的，

**Comment by huluohu** [comment]
> 外部数据: 模块外部传入的数据。(ui 上表现出，是一个输入连线) 其他类型都是有 ui 渲染的，输入框之类的，

谢谢解答。

我测试了下，对话会卡在插件那个节点，一直不继续。

1、下面是应用的编排
![image](https://github.com/labring/FastGPT/assets/7138642/eacede60-edaf-4612-a2ec-8aecdffd320b)

2、下面是插件
![image](https://github.com/labring/FastGPT/assets/7138642/e1a314d5-b5d1-4c50-a2de-12f89727861d)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> External data: Data passed in from outside the module. (Appeared on UI, it is an input connection) Other types are rendered by UI, such as input boxes and the like.

Thanks for the answer.

I tested it, and the conversation would get stuck at the plug-in node and never continue.

1. The following is the arrangement of the application
![image](https://github.com/labring/FastGPT/assets/7138642/eacede60-edaf-4612-a2ec-8aecdffd320b)

2. The following is the plug-in
![image](https://github.com/labring/FastGPT/assets/7138642/e1a314d5-b5d1-4c50-a2de-12f89727861d)

**Comment by c121914yu** [comment]
> > 外部数据: 模块外部传入的数据。(ui 上表现出，是一个输入连线) 其他类型都是有 ui 渲染的，输入框之类的，
> 
> 谢谢解答。
> 
> 我测试了下，对话会卡在插件那个节点，一直不继续。
> 
> 1、下面是应用的编排 ![image](https://private-user-images.githubusercontent.com/7138642/302080088-eacede60-edaf-4612-a2ec-8aecdffd320b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjY2NDksIm5iZiI6MTcwNzAyNjM0OSwicGF0aCI6Ii83MTM4NjQyLzMwMjA4MDA4OC1lYWNlZGU2MC1lZGFmLTQ2MTItYTJlYy04YWVjZGZmZDMyMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMDU1OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk0Zjc5MDQ4NGFiZjgyNDUxNmQ4MjkyOGRlZjkxZDkyYmQwZWY1YzU1ODE0OTdjMDg5NzIxNzA2YmM1YjIwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2n18oc3s52-WNtNXMLky1BjUa77sV1PX1GW4PgHflEw)
> 
> 2、下面是插件 ![image](https://private-user-images.githubusercontent.com/7138642/302080175-e1a314d5-b5d1-4c50-a2de-12f89727861d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjY2NDksIm5iZiI6MTcwNzAyNjM0OSwicGF0aCI6Ii83MTM4NjQyLzMwMjA4MDE3NS1lMWEzMTRkNS1iNWQxLTRjNTAtYTJkZS0xMmY4OTcyNzg2MWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMDU1OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZkNjc5MDA2YzA5ZTdjYzc2OTU5ZmJlNTNiYmQ1YWM0OTZkMmJhNTNhNGQwYTg3NGM2YzJjNTU3MzE4MWQxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1AFDfOGnXvcEmE1G1Jx7Rn85Pccv_qUwNv_qy4YZqpE)

因为接口一直没返回。

**Comment by huluohu** [comment]
我把http调用直接去掉了，插件的输入和输出直接连接，外部应用添加这个插件后，会话还是会卡在这个插件节点。
似乎跟http调用无关，在后台看不到太详细的日志，有点抓瞎啦😂

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I directly removed the http call, and the input and output of the plug-in are directly connected. After the external application adds this plug-in, the session will still be stuck at this plug-in node.
It seems to have nothing to do with http calls. I can’t see too detailed logs in the background, which is a bit confusing😂

**Comment by c121914yu** [comment]
使用插件并没发现这个问题，暂时搁置。

**Comment by c121914yu** [comment]
先close，后续还有问题重新open
