### ISSUE TITLE
stawky/chatglm2-m3e:latest

### ISSUE THREAD

**Issue by CodingNowPls** [labring/FastGPT#824]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
stawky/chatglm2-m3e:latest  这个怎么启动，现在我下载下来使用docker run 启动不了，我去镜像哪里查了，没有任何说明，
https://hub.docker.com/r/stawky/chatglm2-m3e
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
stawky/chatglm2-m3e:latest How to start this? Now I download it and use docker run to start it but it cannot be started.
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
就是 docker run 就可以了

**Comment by c121914yu** [comment]
docker run 再 6006 端口即可。

**Comment by beiliwzl** [comment]
> docker run 再 6006 端口即可。

你好 我运行后提升 found no nvidia driver on your system，请问遇到过吗，镜像需要另外安装NVIDIA驱动吗？谢谢

**Comment by jayli517** [comment]
> > docker run 再 6006 端口即可。
> 
> 你好 我运行后提升 found no nvidia driver on your system，请问遇到过吗，镜像需要另外安装NVIDIA驱动吗？谢谢

系统安装的时候，就得装好nvidia驱动，docker和nvidia docker，nvcc等环境，这个是docker里面调用gpu
