### ISSUE TITLE
Files in the knowledge base cannot be deleted

### ISSUE THREAD

**Issue by zzlyzq** [labring/FastGPT#825]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.6.8

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
安装完成后，使用GPT相关llm使用正常。在调测glm期间，遇到上传的文件无法删除。

**复现步骤**
不清楚。

**预期结果**
不清楚。

**相关截图**
![截图_选择区域_20240204103914](https://github.com/labring/FastGPT/assets/1989900/fb1c2720-f987-4260-addf-db3ff419ba50)
![截图_选择区域_20240204103923](https://github.com/labring/FastGPT/assets/1989900/467bad8d-1049-4894-b208-42164bcb1072)
![截图_选择区域_20240204103930](https://github.com/labring/FastGPT/assets/1989900/6abef774-1762-465e-a1b2-c03b82124096)

**Comment by lijiajun1997** [comment]
初始化mongo副本集了吗

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Have you initialized the mongo replica set?

**Comment by zzlyzq** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> Have you initialized the mongo replica set?

No, I used the version below 4.6.8 before. 
I have checked the doc that with the version 4.6.8, it should use replset.
But, if I do this, my data will lost or exist?
