### ISSUE TITLE
How to set the model used in the next step of guidance

### ISSUE THREAD

**Issue by huluohu** [labring/FastGPT#827]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
如题，下一步指引目前智能开关，目前似乎跟AI聊天模块共用一个模型，是否支持单独设置其使用的模型，谢谢。
**复现步骤**

**预期结果**
可以针对下一步指引独立设置模型
**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
As the title states, the next step is to guide the current smart switch. It seems to share a model with the AI ​​chat module. Does it support setting the model it uses separately? Thank you.
**Steps to reproduce**

**expected outcome**
Models can be set up independently for next step guidance
**Related screenshots**

**Comment by c121914yu** [comment]
目前不支持，直接选 llmmodels 第一个。

**Comment by c121914yu** [comment]
短期不计划，不希望用户做选择。
