### ISSUE TITLE
fastgpt's /api/v1/chat/completions interface instability problem

### ISSUE THREAD

**Issue by leekoko** [labring/FastGPT#828]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**

/api/v1/chat/completions接口进行调用，5次差不多有1次失败
key验证过没有那么高的失败率

下面是fastgpt的报错日志

**复现步骤**
直接api调用

**预期结果**
api调用稳定返回结果

**相关截图**

<img width="977" alt="截屏2024-02-05 10 36 51" src="https://github.com/labring/FastGPT/assets/23375386/ea08df85-02f2-444d-bc4d-d6165fe29f69">
<img width="983" alt="截屏2024-02-05 10 37 02" src="https://github.com/labring/FastGPT/assets/23375386/8273276a-778b-4846-94a4-5cff70de3203">
<img width="972" alt="截屏2024-02-05 10 37 14" src="https://github.com/labring/FastGPT/assets/23375386/e8770db9-59ed-43bc-a631-541363b59492">
<img width="971" alt="截屏2024-02-05 10 37 34" src="https://github.com/labring/FastGPT/assets/23375386/90f1de3c-c10c-4a62-8a1c-c490a6f54bdc">

**Comment by c121914yu** [comment]
目前没遇到过

**Comment by c121914yu** [comment]
看你提供的日志，均是 oneapi 返回额报错。

**Comment by leekoko** [comment]
> 目前没遇到过

401、429的报错是fastgpt发出的么，这个错误码什么含义

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Never encountered it so far

Are the 401 and 429 errors issued by fastgpt? What does this error code mean?

**Comment by c121914yu** [comment]
> > 目前没遇到过
> 
> 401、429的报错是fastgpt发出的么，这个错误码什么含义

鉴权失败。key 上限

**Comment by YTaoger** [comment]
@leekoko 你好，401的问题你有再遇到过吗？

**Comment by leekoko** [comment]
> @leekoko 你好，401的问题你有再遇到过吗？

应该还是在的，因为我是离线版本。最近也没有做升级

**Comment by YTaoger** [comment]
> > @leekoko 你好，401的问题你有再遇到过吗？
> 
> 应该还是在的，因为我是离线版本。最近也没有做升级

那你这边最后还有使用fastgpt对接openai的接口吗？
