### ISSUE TITLE
reranker reranking response time is very long

### ISSUE THREAD

**Issue by swingsun888** [labring/FastGPT#829]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√] 私有部署版本

**问题描述**
发现勾选重排选项后，响应时间都在35秒以上，不勾选运行时间5s，正常吗？
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
没 gpu？

**Comment by swingsun888** [comment]
发现gpu没启用，已解决！

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Found that the gpu was not enabled, solved!

**Comment by leoterry-ulrica** [comment]
> 没 gpu？

CPU是不是不行的？
