### ISSUE TITLE
According to the official deployment tutorial, mongo cannot be started. The previous version was normal.

### ISSUE THREAD

**Issue by 871052165** [labring/FastGPT#830]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [  x] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [  x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x ] 私有部署版本

**问题描述**
按照最新的docker 部署教程走，无法正常部署
**复现步骤**
 
![image](https://github.com/labring/FastGPT/assets/50550790/ebb2f0df-ade8-4250-9609-a1550a0b5ef1)

**预期结果**
之前的版本没有此问题，可以正常启动mongo
**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is currently no similar issue
- [ x ] I have reviewed the project README in full, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ x ] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ x ] private deployment version

**Problem Description**
Following the latest docker deployment tutorial, it cannot be deployed normally.
**Steps to reproduce**
 
![image](https://github.com/labring/FastGPT/assets/50550790/ebb2f0df-ade8-4250-9609-a1550a0b5ef1)

**expected outcome**
The previous version did not have this problem and mongo could be started normally.
**Related screenshots**

**Comment by C-Dragon8** [comment]
我遇到了同样的问题。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I encountered the same problem.

**Comment by c121914yu** [comment]
重复了 https://github.com/labring/FastGPT/issues/823
