### ISSUE TITLE
[BUG] Latest version V4 .6.8-alpha, quoteMaxToken configuration does not take effect

### ISSUE THREAD

**Issue by liuchao0807** [labring/FastGPT#833]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
最新版本V4.6.8-alpha， quoteMaxToken配置不生效，如图所示，gpt-4-turbo的最大引用配置为100000，但是界面里能选择的最大引用还是只有3000

**复现步骤**
V4.6.8-alpha必现

**预期结果**
界面里能选择的最大引用数与配置文件中相同

**相关截图**
![屏幕截图 2024-02-05 235010](https://github.com/labring/FastGPT/assets/22492920/55c2e0b9-85d9-4b88-89e9-892d430a49af)
![屏幕截图 2024-02-05 234902](https://github.com/labring/FastGPT/assets/22492920/faf40ed8-26eb-4ad9-8b57-cf7c4a21869c)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x] I have confirmed that there is no similar issue currently
- [x] I have fully reviewed the project README, as well as [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist in testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x] Private deployment version

**Problem Description**
In the latest version V4.6.8-alpha, the quoteMaxToken configuration does not take effect. As shown in the figure, the maximum quote configuration of gpt-4-turbo is 100000, but the maximum quote that can be selected in the interface is still only 3000.

**Steps to reproduce**
V4.6.8-alpha must appear

**expected outcome**
The maximum number of references that can be selected in the interface is the same as in the configuration file

**Related screenshots**
![Screenshot 2024-02-05 235010](https://github.com/labring/FastGPT/assets/22492920/55c2e0b9-85d9-4b88-89e9-892d430a49af)
![Screenshot 2024-02-05 234902](https://github.com/labring/FastGPT/assets/22492920/faf40ed8-26eb-4ad9-8b57-cf7c4a21869c)

**Comment by c121914yu** [comment]
应该是修复了，最新镜像没法复现了。可能某次提交合并了。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This problem still exists. I still have this problem with the latest image. The quotation limit is 3000, and there is no way to follow the change in the value of quoteMaxToken.

**Comment by lijiajun1997** [comment]
4.6.8正式版已经修复
