### ISSUE TITLE
Problems using glm4 model

### ISSUE THREAD

**Issue by swingsun888** [labring/FastGPT#835]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**
发现调用glm4模型，通过共享api调用后返回的信息到微信，不会自动换行，输出都是/n/n，感觉返回信息格式不能识别，换成chatglm3模型，就正常。
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [ ] I have confirmed that there is currently no similar issue
- [ ] I have fully reviewed the project README, as well as [Project Documentation](https://doc.fastgpt.in/docs/intro/)
- [ ] I used my own key and confirmed that my key can be used normally.
- [ ] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [ ] private deployment version

**Problem Description**
I found that when calling the glm4 model, the information returned to WeChat after calling the shared api does not automatically wrap, and the output is all /n/n. I feel that the format of the returned information cannot be recognized. If I change it to the chatglm3 model, it will be normal.
**Steps to reproduce**

**expected outcome**

**Related screenshots**

**Comment by c121914yu** [comment]
> 通过chatgpt-on-wechat调用api时，使用的模型是glm4，出现无法识别换行/n/n，更换成chatglm3正常。

换行应该是\n吧，如果输出 /n，是模型问题了。3可以，4不行，说明是模型输出有问题。
