### ISSUE TITLE
The actual user is not registered when logging in

### ISSUE THREAD

**Issue by XM233333333** [labring/FastGPT#836]
当我配置好下面的时候，运行docker服务，然后尝试启动fastgpt，登陆的时候说我未注册。
<img width="576" alt="image" src="https://github.com/labring/FastGPT/assets/117915911/60e8ee15-4303-4602-b4ac-7edf65865daa">

下面是我运行的服务和配置：

<img width="868" alt="image" src="https://github.com/labring/FastGPT/assets/117915911/88699e69-33ae-4d53-ad23-82524547206f">
<img width="968" alt="image" src="https://github.com/labring/FastGPT/assets/117915911/da9c46ba-d507-457a-b1a1-e39b0cd02d8e">
<img width="883" alt="image" src="https://github.com/labring/FastGPT/assets/117915911/01300148-2143-44c7-a0b4-54af4bf024d5">
请大佬帮我看看，谢谢！

**Comment by netist123** [comment]
met same problem.

**Comment by LixvYang** [comment]
I'm having the same problem, any progress on this bug?

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/823
相同问题

**Comment by 1956792943** [comment]
> met same problem.
> 
> but when I added "command: mongod --keyFile /data/mongodb.key --replSet rs0", the mongo can not be running(keep in started).

对。将mongodb.key注释掉，可以起来了，但是也出现用户未注册问题，咋办？

**Comment by XM233333333** [comment]
目前还不知道怎么解决

**Comment by qingxi008** [comment]
我也是遇到 同样的问题。也是不开启Mongo的副本，然后登陆提示用户未注册

**Comment by ZDF64** [comment]
![image](https://github.com/labring/FastGPT/assets/15723054/0fdba4b7-1032-4c50-a8eb-2bc619aa7b60)

我这里副本应该是起来了，但是还是显示用户未注册
![image](https://github.com/labring/FastGPT/assets/15723054/ca1d49fa-23a8-484d-855e-b94e04676f2b)

**Comment by c121914yu** [comment]
> ![image](https://private-user-images.githubusercontent.com/15723054/316413596-0fdba4b7-1032-4c50-a8eb-2bc619aa7b60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTA4NjUsIm5iZiI6MTcxMTM1MDU2NSwicGF0aCI6Ii8xNTcyMzA1NC8zMTY0MTM1OTYtMGZkYmE0YjctMTAzMi00YzUwLWE4ZWItMmJjNjE5YWE3YjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOWViZGE3YzkyNWNiY2Y0Y2Y1YzRhZTgwNDE2NmQ3OTcwYTFiMzY0YTRiNzNmMjY2YTMzYjhlMDY1N2JkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VbgEfgcOXADCRXzGcQq1_Pf9BTTKvQjvDlsZzvVj1yg)
> 
> 我这里副本应该是起来了，但是还是显示用户未注册 ![image](https://private-user-images.githubusercontent.com/15723054/316414074-ced78b42-50f2-45a5-9f73-7debcc45bd6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTA4NjUsIm5iZiI6MTcxMTM1MDU2NSwicGF0aCI6Ii8xNTcyMzA1NC8zMTY0MTQwNzQtY2VkNzhiNDItNTBmMi00NWE1LTlmNzMtN2RlYmNjNDViZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMjU0MGY1ZTBmNzliZjQ3YjYyYTA0ZjY1OTBhZDlmMWM1MDM3ZDAxOGExZTI5ZjExYjA2NTdmZDMzYzdlYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QuMqQ9zsEAzfKYc45t7GPUC55ZbJYwtaNMG6a83We98)

再点一次就好了

**Comment by ZDF64** [comment]
> > ![image](https://private-user-images.githubusercontent.com/15723054/316413596-0fdba4b7-1032-4c50-a8eb-2bc619aa7b60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTA4NjUsIm5iZiI6MTcxMTM1MDU2NSwicGF0aCI6Ii8xNTcyMzA1NC8zMTY0MTM1OTYtMGZkYmE0YjctMTAzMi00YzUwLWE4ZWItMmJjNjE5YWE3YjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOWViZGE3YzkyNWNiY2Y0Y2Y1YzRhZTgwNDE2NmQ3OTcwYTFiMzY0YTRiNzNmMjY2YTMzYjhlMDY1N2JkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VbgEfgcOXADCRXzGcQq1_Pf9BTTKvQjvDlsZzvVj1yg)
> > 我这里副本应该是起来了，但是还是显示用户未注册 ![image](https://private-user-images.githubusercontent.com/15723054/316414074-ced78b42-50f2-45a5-9f73-7debcc45bd6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTA4NjUsIm5iZiI6MTcxMTM1MDU2NSwicGF0aCI6Ii8xNTcyMzA1NC8zMTY0MTQwNzQtY2VkNzhiNDItNTBmMi00NWE1LTlmNzMtN2RlYmNjNDViZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMjU0MGY1ZTBmNzliZjQ3YjYyYTA0ZjY1OTBhZDlmMWM1MDM3ZDAxOGExZTI5ZjExYjA2NTdmZDMzYzdlYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QuMqQ9zsEAzfKYc45t7GPUC55ZbJYwtaNMG6a83We98)
> 
> 再点一次就好了

卧槽，太神秘了，确实解决了
不过我这边有点不同，我这里再点几次都是用户未注册，但是我把密码改错，点击后提示密码不对，再改回来就进来了
