### ISSUE TITLE
4.6.8 cannot log in after startup, and the front and back ends report errors.

### ISSUE THREAD

**Issue by 229250919** [labring/FastGPT#838]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**4.6.8**

- [x] 私有部署版本

**问题描述**
启动项目后无法登录，前后端报错
![image](https://github.com/labring/FastGPT/assets/83050744/b45b7510-4d27-4d52-aaed-5ccd93f036b4)
![image](https://github.com/labring/FastGPT/assets/83050744/8902cbdf-5439-4201-9fea-62be06f032a9)

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
配置文件错误
