### ISSUE TITLE
There is a problem with resubmitting the config file provided in the official tutorial, which will cause the database to fail to start.

### ISSUE THREAD

**Issue by taurusduan** [labring/FastGPT#846]
**你的版本**
4.6.8
- [ ] 公有云版本
- [ x] 私有部署版本

![image](https://github.com/labring/FastGPT/assets/30854760/afa29ac0-ed24-4ea2-ba42-239b9cd47fc4)
下载的config文件会导致数据库100%无法启动。

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/823 问题重复，数据库部署问题可谷歌解决
