### ISSUE TITLE
sse error: core.chat.Chat API is error or undefined

### ISSUE THREAD

**Issue by zhoulvjun** [labring/FastGPT#847]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
使用最新版本4.6.8的FastGPT，在ChatNextWeb中直接设置部署的api地址和key，可以正常使用；但如果是在one-api中建立FastGPT的渠道/自定义渠道，则会在FastGPT端报以下错误：

[ERROR] 2024-02-13 13:57:59 sse error: core.chat.Chat API is error or undefined
{
  message: 'core.chat.Chat API is error or undefined',
  stack: undefined
}
**复现步骤**
以前在issues中也见过类似情况，感觉这次又出现了。以前的回复是：

已修复，由于 openai sdk4.x 与 oneapi 的 headers 没有完全相同。
https://github.com/labring/FastGPT/pull/421
_Originally posted by @c121914yu in https://github.com/labring/FastGPT/issues/397#issuecomment-1774548346_
**预期结果**
能够在one-api中正常调用
**相关截图**

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/0d28a798-e91c-4d12-a5f9-dfb7d0500498)
![image](https://github.com/labring/FastGPT/assets/50446880/54aea3b0-652c-4440-9b1e-7e511d8fcea2)
![image](https://github.com/labring/FastGPT/assets/50446880/fbc2eb1c-6688-4149-92c1-c315ee3a2a3c)

我这边是正常的。

**Comment by zhoulvjun** [comment]
谢谢您的回复！我发现是所用的ChatNextWeb版本有问题（还不清楚具体问题出在哪，但换其它版本可以正常调用One-API中的FastGPT），并不是FastGPT或One-API的问题。被ChatNextWeb能直接用FastGPT的api误导了，以为它也能正常调用One-API中的FastGPT。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
thank you for your reply! I found that there was a problem with the ChatNextWeb version I was using (it’s not clear where the problem lies, but FastGPT in One-API can be called normally with other versions), and it was not a problem with FastGPT or One-API. I was misled by ChatNextWeb's API that can directly use FastGPT, thinking that it can also call FastGPT in One-API normally.
