### ISSUE TITLE
关于多轮AI聊天的打印

### ISSUE THREAD

**Issue by epochaudio** [labring/FastGPT#850]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ *] 我已确认目前没有类似 features
- [ *] 我已确认我已升级到最新版本
- [ *] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ *] 我理解并愿意跟进此 features，协助测试和提供反馈
- [*] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

![Xnip2024-02-15_15-17-02](https://github.com/labring/FastGPT/assets/60331828/a3ba8e7f-cc52-4ba6-8dd9-9047608c89c0)

![Xnip2024-02-15_15-17-56](https://github.com/labring/FastGPT/assets/60331828/8be1875f-9daa-4466-a62f-29994e9dd472)
多轮AI聊天的结果，建议分开打印，或者仅仅显示最后一个AI的结果。
现在都挤在一起的！

**Comment by c121914yu** [comment]
这个应该半年没更新了，看使用率不到 1%，暂时不打算更新。

**Comment by c121914yu** [comment]
打印内容本来就可以自己调整。打不打印也可以调整。
