### ISSUE TITLE
Gemini模型400错误

### ISSUE THREAD

**Issue by flyinsz** [labring/FastGPT#854]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [×] 私有部署版本

**问题描述**
对话选择Gemini模型发生400错误
![screenshot-1708065987615](https://github.com/labring/FastGPT/assets/27534375/0cff97f6-fc56-4d2d-825c-80b4073b03c7)

**复现步骤**

config.json已经配置好Gemini模型参数如下：
    {
      "model": "gemini-pro",
      "name": "gemini",
      "maxContext": 128000,
      "maxResponse": 4000,
      "quoteMaxToken": 100000,
      "maxTemperature": 1.2,
      "inputPrice": 0,
      "outputPrice": 0,
      "censor": false,
      "vision": false,
      "datasetProcess": false,
      "toolChoice": false,
      "functionCall": false,
      "customCQPrompt": "",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig": {}
    }
oneapi也已接入了Gemini并已测试成功；
AI对话模块选择Gemini，有几次测试成功，之后就一直400错误，重新注册了Google账号获取了新的API Key后问题依旧。

**预期结果**

**相关截图**
![screenshot-1708065987615](https://github.com/labring/FastGPT/assets/27534375/0cff97f6-fc56-4d2d-825c-80b4073b03c7)

**Comment by lcl2257970753** [comment]
你好麻烦问一下你是如何接入oneapi的

**Comment by huluohu** [comment]
这个是gemini报区域限制了，建议把oneapi部署到**干净的**墙外主机上（我用的rn偶尔也报区域限制，怀疑就是机器ip被谷歌拉黑了）

**Comment by duskcouple** [comment]
应该不是代理区域限制问题，我这里也是gemini报错，我用node写了个中转gemini的接口，oneapi中设置代理地址进行中转，但是fastgpt好像不识别oneapi返回的东西，中转的后端都已经看到了返回的输出了。
![搜狗截图20240328214527](https://github.com/labring/FastGPT/assets/26564245/f8674d21-1a32-4108-a31b-66f5e2eee0bc)
![CM3Q5VT32DYAT (US8@{Z)Q](https://github.com/labring/FastGPT/assets/26564245/4c644ceb-bb2d-48ed-a3a8-20b86b103216)
