### ISSUE TITLE
Transaction numbers are only allowed on a replica set member or mongos 

### ISSUE THREAD

**Issue by swingsun888** [labring/FastGPT#857]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**  
更新到新版本4.6.8
- [ ] 公有云版本
- [√] 私有部署版本

**问题描述**
知识库通过URL导入的时候，报以下错误“Transaction numbers are only allowed on a replica set member or mongos ”，导入文档正常。
**复现步骤**

**预期结果**

**相关截图**

**Comment by swingsun888** [comment]
已解决，是MongoDB初始化问题。

**Comment by xunmenglt** [comment]
请问是如何解决的？
