### ISSUE TITLE
用户登陆的token是永不过期的么

### ISSUE THREAD

**Issue by union-cmd** [labring/FastGPT#860]
我想调用一些api的接口，访问这些api的接口需要用到token，想问一下它这个token是永不过期的么，还是有存活时间的。
<img width="767" alt="image" src="https://github.com/labring/FastGPT/assets/61687719/fe018e38-6a59-4692-9b40-fde95ea757c2">

**Comment by c121914yu** [comment]
token 怎么可能不过期😅设置的是 7 天过期

**Comment by union-cmd** [comment]
请问这个怎么设置永久呢

**Comment by c121914yu** [comment]
你给的这个分享链接鉴权，不是 fastgpt 的 token，是你系统传递过来的参数。

**Comment by union-cmd** [comment]
就是我访问接口它是需要校验token的，我想要将token设置为永久可以么
<img width="506" alt="image" src="https://github.com/labring/FastGPT/assets/61687719/c24fe29f-39e6-497a-ada6-4410a72add35">

**Comment by c121914yu** [comment]
> 就是我访问接口它是需要校验token的，我想要将token设置为永久可以么
> <img width="506" alt="image" src="https://github.com/labring/FastGPT/assets/61687719/c24fe29f-39e6-497a-ada6-4410a72add35">
> 

不可能不过期，没法设置

**Comment by union-cmd** [comment]
好的 谢谢
