### ISSUE TITLE
知识库检索或者上传时偶尔会意外卡死崩溃，并且容器无法重启

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#863]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.8.6
- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在导入知识或者使用知识库检索过程中，有时候会出错导致容器卡死。并且容器中无法重启应用，容器也无法重启，需要重启电脑解决。详见截图报错。
操作系统win10, docker版本v25.0.2，电脑配置AMD R9 5950X+64G内存+SSD

**复现步骤**
1.操作应用进行知识库检索提问或者大量上传知识。
2.提问卡在知识库搜索，然后应用卡死。
3.应用在docker中无法重启。
4.docker重启会卡在启动界面。
5.重启电脑恢复正常。
详见截图

**预期结果**
不确定是代码的bug还是docker在windows上的兼容性问题
**相关截图**
![J)3DLO2)UYOEZ0FIF{1$F3A](https://github.com/labring/FastGPT/assets/156336589/23fcd386-164f-4747-9113-2c4bb66ef40f)
![X7 2 `G2FX M8ZI)A2SD1(T](https://github.com/labring/FastGPT/assets/156336589/3c5362f4-12df-484f-9ab1-567309ebfb82)
![B}%L09SBJ0_LEYL0WNRM_F4](https://github.com/labring/FastGPT/assets/156336589/e5af866e-5a41-47a2-968f-f37a449e757b)
![7DOERE_V7C5}2CVX 4_LDFG](https://github.com/labring/FastGPT/assets/156336589/56ca198b-4b41-4019-a094-e908e410e155)
![$7@ZX$OJS`G98XLWVA36R2S](https://github.com/labring/FastGPT/assets/156336589/c9c6d4c2-ba8a-41d1-ac5b-a6222bdd7a9d)
![H(HB_XXLLFHRF87{ZQN9$VK](https://github.com/labring/FastGPT/assets/156336589/a8f23941-28f4-4f68-a2dd-ee2cf1e74f8f)

**Comment by c121914yu** [comment]
暂时没遇到，2400w组向量，8c32g mongo, 16c64g PG，负载都正常。

**Comment by lijiajun1997** [comment]
应该是WSL的问题
