### ISSUE TITLE
升级V4.6.8后，“最低相关度”设置不见了

### ISSUE THREAD

**Issue by buctllx** [labring/FastGPT#864]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
从4.6.7升级到4.6.8后，原来“应用”-”知识库搜索“参数中的“最低相关度”设置找不到了。
![image](https://github.com/labring/FastGPT/assets/12623648/fa6253b2-3ac0-4b6c-970c-843607b5c64d)

**复现步骤**

**预期结果**
我看了一下官方在线版本是有的，截图如下：
![企业微信截图_1708312858409](https://github.com/labring/FastGPT/assets/12623648/e2d973de-e64c-4e98-9ec5-03bb43df7026)

**相关截图**

**Comment by c121914yu** [comment]
语义检索或者加了重排才有相关度过滤。单纯全文检索或者混合检索没有最低相关度
