### ISSUE TITLE
新版本指定回复模块会在AI对话的内容尚未显示完毕后就进行输出，导致输出混合

### ISSUE THREAD

**Issue by lzh222333** [labring/FastGPT#868]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.6.8
- [x] 公有云版本
- [x] 私有部署版本

**问题描述**
4.6.8更新后，指定回复模块的内容会跟AI对话的内容混在一起
**复现步骤**
配置已按最小可复现配置进行了精简，如图所示
**预期结果**
结果应为先输出完AI对话内容才输出“以上内容来自AI”
**相关截图**
![image](https://github.com/labring/FastGPT/assets/10153117/b7fdc78f-a13e-4b33-aa9b-809c29b97a39)

**Comment by c121914yu** [comment]
下个版本修复

**Comment by lijiajun1997** [comment]
用AI调用介绍做触发器试试？

**Comment by naimehao** [comment]
是的，跟着官方文档做这个固定开头和结尾内容的测试，遇到了一样的问题

**Comment by swingsun888** [comment]
我也遇到指定回复内容混乱情况。

**Comment by lwdnxu** [comment]
现在问题还没解决吗？版本是4.8.6
