### ISSUE TITLE
调用对话接口报错Key is error. You need to use the app key rather than the account key.

### ISSUE THREAD

**Issue by Brotherxu6** [labring/FastGPT#869]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.6.7 
- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
调用对话接口报错Key is error. You need to use the app key rather than the account key.
**复现步骤**
`import requests

url = "http://XXXXXXX:3000/api/v1/chat/completions"  # 替换为目标URL
data = {
    "model": "gpt-4-turbo-preview",
    "chatId": "2",
    "messages": [
        {
            "role": "user",
            "content": "你叫什么"
        },
    ]
}
headers = {
    "Authorization": "Bearer fastgpt-MR6gEYaQY1a9n7O2742K7m890vTN0KYFNOI"
}
response = requests.post(url, json=data, headers=headers, timeout=600)
print(response.text)
json_data = response.json()

print(json_data["choices"][0]["message"]["content"])`
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/80322476/5c9aea5d-5829-458b-a459-e7e99bc846e3)
![image](https://github.com/labring/FastGPT/assets/80322476/fd2a8f30-4df1-41e4-83e1-ee79e83ef61f)

**Comment by apas008** [comment]
我也报这个错误

**Comment by LuckyGJX** [comment]
我也是，请问怎么解决的呀
