### ISSUE TITLE
請求增加 Chatgpt  JSON mode 模式

### ISSUE THREAD

**Issue by WuKaiYi** [labring/FastGPT#871]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 features
- [x ] 我已确认我已升级到最新版本
- [x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

根據openai 的說明 已經有JSON mode 模式可以使用,具體鏈接是:https://platform.openai.com/docs/guides/text-generation/json-mode
可以在AI 對話節點加入一個開關是否使用JSON 模式

**Comment by c121914yu** [comment]
可以用内容提取模块替代

**Comment by WuKaiYi** [comment]
我的理解是 在對chatgpt 的api發送請求的時候就加入  "response_format": { "type": "json_object" },

**Comment by c121914yu** [comment]
> 我的理解是 在對chatgpt 的api發送請求的時候就加入  "response_format": { "type": "json_object" },

内容提取也可以输出 json，没有区别。

**Comment by zanderjiang** [comment]
现在OpenAI出了strict的模式，内容提取模块可以实现对json schema的严格输出吗

**Comment by gaord** [comment]
使用内容提取还要再次调用模型。无疑会增加成本和使用体验。

**Comment by c121914yu** [comment]
> 使用内容提取还要再次调用模型。无疑会增加成本和使用体验。

为啥要再次，不是一次么

**Comment by gaord** [comment]
一段文本是模型输出的，对这段文本的内容提取还要调用一次模型，不是吗？

**Comment by c121914yu** [comment]
> 一段文本是模型输出的，对这段文本的内容提取还要调用一次模型，不是吗？

你自己想的吧～ 内容提取直接就是提字段了，压根就不走生成。

**Comment by gaord** [comment]
![image](https://github.com/user-attachments/assets/99e06b52-843e-4575-b95d-15a6ffc05467)
不是这个内容提取？需要配置模型？

**Comment by c121914yu** [comment]
> ![image](https://private-user-images.githubusercontent.com/9567937/380116352-99e06b52-843e-4575-b95d-15a6ffc05467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTE5NTYsIm5iZiI6MTcyOTg1MTY1NiwicGF0aCI6Ii85NTY3OTM3LzM4MDExNjM1Mi05OWUwNmI1Mi04NDNlLTQ1NzUtYjk1ZC0xNWE2ZmZjMDU0NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMTAyMDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTdhYjkzZmFmYmVjNDE4NWQzZmYyNTFjYTRlZWJiMDVjOTM3ZjU5OTFjNmU2Njk1MjU0ZTExMTdmODBlNzI0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FrQ0_5ZwhHVPFPE_M5ReEhORxKbIZ6-FieCKdABLZiE) 不是这个内容提取？需要配置模型？

配模型，为啥就一定要调用 2 次？

**Comment by gaord** [comment]
![](https://cdn.jsdelivr.net/gh/yangchuansheng/fastgpt-imgs@main/imgs/extract1.png)
文档里没说明这个必填的需要提取的文本是做什么用的？既然从聊天输出提取内容，文档在这个方面不是特别明了。

**Comment by opinratera** [comment]
确实，我现在的做法是不用模型问答，直接用http请求到oneapi，传入json_mode的配置
