### ISSUE TITLE
知识库+对话引导在创建时必须要先选择模型并保存，否则就会报错

### ISSUE THREAD

**Issue by naimehao** [labring/FastGPT#872]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
错误：
![Xnip2024-02-21_09-30-34](https://github.com/labring/FastGPT/assets/50571342/1da19210-bdb7-4a71-821e-de99ee82b2cf)

正常：
![Xnip2024-02-21_09-31-40](https://github.com/labring/FastGPT/assets/50571342/73a96e88-5124-46e8-a1e6-ec3aa8ed685b)

**Comment by shuaizai88** [comment]
把gpt3补全那个去掉就好了，但是可能会影响效果。
![image](https://github.com/labring/FastGPT/assets/32242038/fb4f77eb-12b6-477c-a1c5-0f7f30bf2d3b)

**Comment by c121914yu** [comment]
应该是你哪里缺少模型。我这里按你的操作测试，是ok的。
