### ISSUE TITLE
免登录窗口中清除所有记录异常

### ISSUE THREAD

**Issue by Tianhen1741** [labring/FastGPT#873]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本 （V4.6.8）

**问题描述**
发布应用-免登录窗口，里面在用的时候清除所有记录不好用，清除后刷新浏览器又回来了；
登录进去的聊天中清除所有记录倒是好用的
其中在这两个地方进行单个对话的删除，再刷新是不会再显示了，只有免登录发布的全部删除异常
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/32192816/87983f5b-9863-4bb7-b435-629abeb11757)

**Comment by c121914yu** [comment]
下个版本修复
