### ISSUE TITLE
问题分类模块

### ISSUE THREAD

**Issue by lcl2257970753** [labring/FastGPT#874]
问题分类模块不管输入什么内容，都是最后一个问题

**Comment by c121914yu** [comment]
日志会有报错。模型配置不对，不支持工具调用，又没用提示词模式

**Comment by xhlj2023** [comment]
> 日志会有报错。模型配置不对，不支持工具调用，又没用提示词模式

我也发现这个问题了，分类器基本都是给到最后一个分类，不论提问的内容是什么，提示词写了也没用
提示词怎么写？分类的准确？有没有模板参考一下？
