### ISSUE TITLE
当config.json中没有gpt-3.5-turbo-16k时在UI点击创建知识库会报错

### ISSUE THREAD

**Issue by fictionking** [labring/FastGPT#875]
原因是创建知识库时"文件处理模型"会用代码中默认的“gpt-3.5-turbo-16k”,而4.6.8 新配置文件config.json没有这处的配置。

**Comment by fictionking** [comment]
4.6.8 新配置文件config.json中将需要用于知识库文件处理的模型的"datasetProcess"设为true,

**Comment by c121914yu** [comment]
> 4.6.8 新配置文件config.json中将需要用于知识库文件处理的模型的"datasetProcess"设为true,

至少一个为 true
