### ISSUE TITLE
知识库搜索模块问题补全建议

### ISSUE THREAD

**Issue by huluohu** [labring/FastGPT#876]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
新版的知识库搜索模块很好用，但是有个小问题建议优化下，就是补全后的“用户问题”没有同步到输出侧，仅用在了知识库搜索这一步，即模块输出中的“用户问题”没有变更为补全后的结果。

建议：是否能否在模块输出中的“用户问题”中同步补全后的结果。

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/7138642/e9f9d6dc-2061-4b1f-93a5-11f46198ebe0)

**Comment by c121914yu** [comment]
没意义，还会影响模型

**Comment by huluohu** [comment]
好的，谢谢啦。
