### ISSUE TITLE
请求知识库创建api 403

### ISSUE THREAD

**Issue by shuaizai88** [labring/FastGPT#878]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X ] 私有部署版本

**问题描述**
通过 账号-api秘钥创建的key，再调用接口的时候报403
**复现步骤**

**预期结果**

**相关截图**
![9c1e1a837acfdb08ee8cfe7bf6e44ed](https://github.com/labring/FastGPT/assets/32242038/589d4083-932a-4092-b2c2-97bb50f6ccc6)

![2f48f614bf359f58914c1dc4489e732](https://github.com/labring/FastGPT/assets/32242038/2aed3715-4059-4b78-9c4a-79843378ea92)

**Comment by c121914yu** [comment]
4.6.7这个接口才能api访问。
