### ISSUE TITLE
知识库导出失败

### ISSUE THREAD

**Issue by gytai** [labring/FastGPT#879]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
选择知识库进行导出
**复现步骤**
1. 选中知识库 进行导出
2. 显示导出错误
**预期结果**
导出成功
**相关截图**
![image](https://github.com/labring/FastGPT/assets/8663682/8a840459-f787-4dcd-a732-456f6fdb869e)

**Comment by gytai** [comment]
关联 https://github.com/labring/FastGPT/issues/535

**Comment by a491004300** [comment]
![image](https://github.com/labring/FastGPT/assets/47101077/49bc2def-1fc0-466c-9e99-e6bc3830faef)
一样的问题  导出失败.

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/535
重复了，没用 ssl。
