### ISSUE TITLE
ios如何请求api接口

### ISSUE THREAD

**Issue by wc2411888** [labring/FastGPT#880]
我的ios使用了什么方式都无法正确调用api接口，请问有参考代码吗?用postman可以访问，但iOS不知道怎么去流式请求

**Comment by wc2411888** [comment]
#import <Foundation/Foundation.h>

dispatch_semaphore_t sema = dispatch_semaphore_create(0);

NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"http://wecom-ai-test.integrity.com.cn:5002/api/v1/chat/completions"]
  cachePolicy:NSURLRequestUseProtocolCachePolicy
  timeoutInterval:10.0];
NSDictionary *headers = @{
  @"Authorization": @"Bearer fastgpt-uBkXh1vs5zqZYRtWh3Ulh8VKkZ86cpknNN",
  @"Content-Type": @"application/json"
};

[request setAllHTTPHeaderFields:headers];
NSData *postData = [[NSData alloc] initWithData:[@"{\r\n    \"chatId\": \"abcd\",\r\n    \"stream\": true,\r\n    \"detail\": false,\r\n    \"variables\": {\r\n        \"uid\": \"asdfadsfasfd2323\",\r\n        \"name\": \"张三\"\r\n    },\r\n    \"messages\": [\r\n        {\r\n            \"content\": \"你是什么大模型\",\r\n            \"role\": \"user\"\r\n        }\r\n    ]\r\n}" dataUsingEncoding:NSUTF8StringEncoding]];
[request setHTTPBody:postData];

[request setHTTPMethod:@"POST"];

NSURLSession *session = [NSURLSession sharedSession];
NSURLSessionDataTask *dataTask = [session dataTaskWithRequest:request
completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
  if (error) {
    NSLog(@"%@", error);
    dispatch_semaphore_signal(sema);
  } else {
    NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *) response;
    NSError *parseError = nil;
    NSDictionary *responseDictionary = [NSJSONSerialization JSONObjectWithData:data options:0 error:&parseError];
    NSLog(@"%@",responseDictionary);
    dispatch_semaphore_signal(sema);
  }
}];
[dataTask resume];
dispatch_semaphore_wait(sema, DISPATCH_TIME_FOREVER);

**Comment by wc2411888** [comment]
#import <Foundation/Foundation.h>

dispatch_semaphore_t sema = dispatch_semaphore_create(0);

NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"http://wecom-ai-test.integrity.com.cn:5002/api/v1/chat/completions"]
  cachePolicy:NSURLRequestUseProtocolCachePolicy
  timeoutInterval:10.0];
NSDictionary *headers = @{
  @"Authorization": @"Bearer fastgpt-xx",
  @"Content-Type": @"application/json"
};

[request setAllHTTPHeaderFields:headers];
NSData *postData = [[NSData alloc] initWithData:[@"{\r\n    \"chatId\": \"abcd\",\r\n    \"stream\": true,\r\n    \"detail\": false,\r\n    \"variables\": {\r\n        \"uid\": \"asdfadsfasfd2323\",\r\n        \"name\": \"张三\"\r\n    },\r\n    \"messages\": [\r\n        {\r\n            \"content\": \"你是什么大模型\",\r\n            \"role\": \"user\"\r\n        }\r\n    ]\r\n}" dataUsingEncoding:NSUTF8StringEncoding]];
[request setHTTPBody:postData];

[request setHTTPMethod:@"POST"];

NSURLSession *session = [NSURLSession sharedSession];
NSURLSessionDataTask *dataTask = [session dataTaskWithRequest:request
completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
  if (error) {
    NSLog(@"%@", error);
    dispatch_semaphore_signal(sema);
  } else {
    NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *) response;
    NSError *parseError = nil;
    NSDictionary *responseDictionary = [NSJSONSerialization JSONObjectWithData:data options:0 error:&parseError];
    NSLog(@"%@",responseDictionary);
    dispatch_semaphore_signal(sema);
  }
}];
[dataTask resume];
dispatch_semaphore_wait(sema, DISPATCH_TIME_FOREVER);

**Comment by wc2411888** [comment]
stream 设置为false可以请求到结果 ，stream 设置为true就会失败

**Comment by c121914yu** [comment]
没开发过IOS，蹲一手~
