### ISSUE TITLE
新建应用，配置chatglm3 模型，并关联知识库，发送第二个问题时候会默认调用 gpt-3.5-turbo-1106 模型而不是 chatglm3

### ISSUE THREAD

**Issue by beyondalbert** [labring/FastGPT#882]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
新建应用，配置chatglm3 模型，并关联知识库，发送第二个问题时候会默认调用 gpt-3.5-turbo-1106 模型而不是 chatglm3
**复现步骤**
1、新建应用，配置chatglm3 模型，并关联知识库
2、发送第一个问题给机器人，回答没有问题；
3、再发送第二个问题给机器人，提示：
undefined 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20240222051155844508117UYKSVlFv)
4、更加准确的说法应该是，我每新建一个对话，这个对话的第一个问题是没问题的，第二个问题就是出现上面的错误提示了

当前本地环境说明：
1、自己部署了one api ,fastgpt 的ai模型都是 对接的one API
2、one api 上我把gpt-3.5 的渠道删除了，没有删除前，直接提示我这个openai 的key是被封了（确实是被封了）
3、本地fastgpt是直接拉的github代码，版本是4.6.7，直接通过 pnpm dev 跑起来的服务

本地环境初步尝试：
1、直接把配置文件中chatModels中的gpt-3.5-turbo和gpt-3.5-turbo-16k删除后，重启服务也不行
2、我在应用中把关联的知识库删除后，这个问题就没有了
 
**预期结果**

**相关截图**

**Comment by beyondalbert** [comment]
完整的错误日志如下：

[ERROR] 2024-02-22 13:38:15 sse error: undefined 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20240222053815409680420X5EhVP2P) 
{
  message: '503 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20240222053815409680420X5EhVP2P)',
  stack: 'Error: 503 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20240222053815409680420X5EhVP2P)\n' +
    '    at APIError.generate (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+openai@4.23.0_encoding@0.1.13/node_modules/openai/error.mjs:78:20)\n' +
    '    at OpenAI.makeStatusError (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+openai@4.23.0_encoding@0.1.13/node_modules/openai/core.mjs:279:65)\n' +
    '    at OpenAI.makeRequest (webpack-internal:///(api)/../../node_modules/.pnpm/registry.npmmirror.com+openai@4.23.0_encoding@0.1.13/node_modules/openai/core.mjs:318:30)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Object.dispatchCFR [as cfr] (webpack-internal:///(api)/./src/service/moduleDispatch/tools/cfr.ts:42:20)\n' +
    '    at async moduleRun (webpack-internal:///(api)/./src/service/moduleDispatch/index.ts:181:29)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async dispatchModules (webpack-internal:///(api)/./src/service/moduleDispatch/index.ts:217:5)\n' +
    '    at async handler (webpack-internal:///(api)/./src/pages/api/v1/chat/completions.ts:177:74)'
}

**Comment by c121914yu** [comment]
没修改完所有模型。

**Comment by beyondalbert** [comment]
> 没修改完所有模型。 没有gpt模型就不要留在配置文件里。 第二次对话调用了问题补全。

意思是 问题补全调用了chatgpt模型么？
还有，这个没有修改完所有模型 具体是指？麻烦能说的具体点么，谢谢

**Comment by Ka-ga** [comment]
同问

**Comment by c121914yu** [comment]
> > 没修改完所有模型。 没有gpt模型就不要留在配置文件里。 第二次对话调用了问题补全。
> 
> 意思是 问题补全调用了chatgpt模型么？
> 还有，这个没有修改完所有模型 具体是指？麻烦能说的具体点么，谢谢

内容补全也选模型

**Comment by teacherlin** [comment]
我在选择本地部署的llama3也出现类似的报错：undefined 当前分组 default 下对于模型 llama3 无可用渠道 (request id: 2024050314513692688319697840805)

**Comment by Rsslosc** [comment]
config.json
add
` 
 "QAModels": [
	{
           "model": "llama3",
	   "name": "llama3",
	   "maxContext": 4000,
           "maxResponse": 4000,
	   "price": 0
	}
  ],

model and name use yours
`

**Comment by benshan123** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue[x]  我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)[x]  我使用了自己的 key，并确认我的 key 是可正常使用的[x]  我理解并愿意跟进此 issue，协助测试和提供反馈[x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **你的版本**
> 
> * [ ]  公有云版本[x]  私有部署版本
> 
> **问题描述** 新建应用，配置chatglm3 模型，并关联知识库，发送第二个问题时候会默认调用 gpt-3.5-turbo-1106 模型而不是 chatglm3 **复现步骤** 1、新建应用，配置chatglm3 模型，并关联知识库 2、发送第一个问题给机器人，回答没有问题； 3、再发送第二个问题给机器人，提示： undefined 当前分组 default 下对于模型 gpt-3.5-turbo-1106 无可用渠道 (request id: 20240222051155844508117UYKSVlFv) 4、更加准确的说法应该是，我每新建一个对话，这个对话的第一个问题是没问题的，第二个问题就是出现上面的错误提示了
> 
> 当前本地环境说明： 1、自己部署了one api ,fastgpt 的ai模型都是 对接的one API 2、one api 上我把gpt-3.5 的渠道删除了，没有删除前，直接提示我这个openai 的key是被封了（确实是被封了） 3、本地fastgpt是直接拉的github代码，版本是4.6.7，直接通过 pnpm dev 跑起来的服务
> 
> 本地环境初步尝试： 1、直接把配置文件中chatModels中的gpt-3.5-turbo和gpt-3.5-turbo-16k删除后，重启服务也不行 2、我在应用中把关联的知识库删除后，这个问题就没有了
> 
> **预期结果**
> 
> **相关截图**

您好  我也遇到了这个问题，想问下你解决了吗？
