### ISSUE TITLE
希望在高级编排中的http模块能提取到免登录窗口url用户自定义的参数

### ISSUE THREAD

**Issue by shixud** [labring/FastGPT#887]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
1.免登录窗口地址:http://test.com/chat/share?shareId=aaa&chatId=bbb&userId=10086&key=aaa ,其中自定义的参数为userId和key, 希望在高级编排中的http模块，通过{{userId}} 和 {{key}} 能提取到url中的params信息。
2.在高级编排中的"用户引导"模块中，设置全局变量时，字段类型可以新增一个类型为URL参数。开始对话时，不需要用户填写，直接读取url中的params来对应字段key.
**应用场景**
在嵌入内部系统时，增加自定义参数来标记当前用户信息，使用http模块时提取用户信息，传递到api接口。
**相关示例**

**Comment by c121914yu** [comment]
这个已经规划了，一两个版本会实现。

**Comment by c121914yu** [comment]
Done
