### ISSUE TITLE
指定回复内容的bug

### ISSUE THREAD

**Issue by jingyaogong** [labring/FastGPT#888]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ✓] 我已确认目前没有类似 issue
- [ ✓] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ✓] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [✓ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
v4.6.8
- [× ] 公有云版本
- [ ✓] 私有部署版本

**问题描述**
高级编排，查找数据库不存在的问题时，触发自定义指定回复内容时
经常性出现
```
v.extensionQueries?.join is not a function
```

此外4.6.8-alpha自定义回复的内容可以流式输出，4.6.8-alpha以外的所有版本，自定义回复内容秒输出，没有任何停顿。体验不佳。

**复现步骤**
如上
**预期结果**
无
**相关截图**
![Screenshot_20240224_235531_com quark browser](https://github.com/labring/FastGPT/assets/62287848/03cdca04-eb06-4bf5-bc20-382aa23a1a7f)

**Comment by c121914yu** [comment]
没遇到哎，怎么出现的，配置文件对不对，看着是问题补全报错了，问题补全对不对？

**Comment by jingyaogong** [comment]
> 没遇到哎，怎么出现的，配置文件对不对，看着是问题补全报错了，问题补全对不对？

![Screenshot_20240225_105617_com quark browser](https://github.com/labring/FastGPT/assets/62287848/3cbc6bb3-5f4b-4087-9239-d94185f10ea8)
没有问题补全模块唉，当发第一个消息且数据库无匹配的时候就会报错
当非第一个消息时候不会报错

**Comment by jingyaogong** [comment]
> 没遇到哎，怎么出现的，配置文件对不对，看着是问题补全报错了，问题补全对不对？

且4.6.6没遇到，4.6.8才遇到这个问题

**Comment by jingyaogong** [comment]
> > 没遇到哎，怎么出现的，配置文件对不对，看着是问题补全报错了，问题补全对不对？
> 
> ![Screenshot_20240225_105617_com quark browser](https://private-user-images.githubusercontent.com/62287848/307572532-3cbc6bb3-5f4b-4087-9239-d94185f10ea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDQ5NzIsIm5iZiI6MTcwODg0NDY3MiwicGF0aCI6Ii82MjI4Nzg0OC8zMDc1NzI1MzItM2NiYzZiYjMtNWY0Yi00MDg3LTkyMzktZDk0MTg1ZjEwZWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA3MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmM2JhZmQ5ZGU2N2NhMTU2YzU0MTQ4OTE1ZTliOWQwNGQxZWE4ODhhNjFkODAzNmU3YmE5MzZhOWEwNTgxYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CrOxVodsTd4OlsRa_9l4JdbuyIN9GvpD8CNyJ4XKf54) 没有问题补全模块唉，当发第一个消息且数据库无匹配的时候就会报错 当非第一个消息时候不会报错

**Comment by jingyaogong** [comment]
再实验一下，好像真的是打开了问题补全才出现

**Comment by jingyaogong** [comment]
> 没遇到哎，怎么出现的，配置文件对不对，看着是问题补全报错了，问题补全对不对？

好像确实是问题补全的问题。
那指定回复时，于正常回答一样的流式输出如何配置，一股脑冒出来指定回复的内容感觉体验有点问题诶。

**Comment by c121914yu** [comment]
> > 没遇到哎，怎么出现的，配置文件对不对，看着是问题补全报错了，问题补全对不对？
> 
> 好像确实是问题补全的问题。
> 那指定回复时，于正常回答一样的流式输出如何配置，一股脑冒出来指定回复的内容感觉体验有点问题诶。

看着是补全时候传入了空指针，可以发下你的编排？

**Comment by c121914yu** [comment]
> > 没遇到哎，怎么出现的，配置文件对不对，看着是问题补全报错了，问题补全对不对？
> 
> 好像确实是问题补全的问题。
> 那指定回复时，于正常回答一样的流式输出如何配置，一股脑冒出来指定回复的内容感觉体验有点问题诶。

指定回复设计确实是一次性回复。
