### ISSUE TITLE
知识库检索，向量分数异常

### ISSUE THREAD

**Issue by Selivia** [labring/FastGPT#892]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
我在测试知识库检索的时候，发现语义检索出来的分值是162，而你这边说明相似度分支范围应该在0-1之间，我没看懂，现在ai基于知识库回答，不管问什么都会命中知识库，这应该不是这样的。我本地化部署了chatGLM3+m3e模型
**预期结果**
知识库检索分值应该在0-1之间
**相关截图**
<img width="841" alt="iShot_2024-02-26_14 31 09" src="https://github.com/labring/FastGPT/assets/17275076/e4f8da6b-9089-4c5f-82cb-e3b6d45e8062">
<img width="650" alt="iShot_2024-02-26_14 35 38" src="https://github.com/labring/FastGPT/assets/17275076/f881cd3c-72f5-4bb8-98c8-9de39888e19b">

**Comment by c121914yu** [comment]
向量没有归一化。

**Comment by Selivia** [comment]
问下如何向量归一化，官网上没有找到对应的配置

**Comment by lonngxiang** [comment]
我这是m3e向量检索相似度非常小，刚好相反，导致每次回答都没有引用

![eea9ef692a027c35d2050e46f939098](https://github.com/labring/FastGPT/assets/40717349/c86c107b-0852-4b29-8137-9e307b79f027)

**Comment by dreamsnail** [comment]
有解决吗

**Comment by 13829386012** [comment]
@Selivia 请问有解决吗

**Comment by Selivia** [comment]
@13829386012 后面替换成他们官方的m3e，分数显示就正常了，
镜像名: stawky/m3e-large-api:latest
国内镜像：registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest

> @Selivia 请问有解决吗

**Comment by chenmonster** [comment]
> @13829386012 后面替换成他们官方的m3e，分数显示就正常了， 镜像名: stawky/m3e-large-api:latest 国内镜像：registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest
> 
> > @Selivia 请问有解决吗

确实用官方的就没问题，我用 `nomic-embed-text:v1.5`  `milkey/m3e:large-f16` `milkey/gte:large-zh-f16` 模型做语义检索都是超过1了
