### ISSUE TITLE
知识库访问报错

### ISSUE THREAD

**Issue by yibohub** [labring/FastGPT#893]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√ ] 私有部署版本

**问题描述**
新建知识库，开启新对话，报错：Cannot read properties of null (reading 'id')
**复现步骤**
新建知识库，导入文本数据集，问答拆分。将新知识库加入应用后报错。这个错误不是每次都出项，我已经碰到过两次。
**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/161293070/6321fc4f-2d4a-4e80-be8f-0a9e52ea3b75)

**Comment by c121914yu** [comment]
看着是有空指针

**Comment by weiyiming1** [comment]
![Screenshot from 2024-02-27 16-59-30](https://github.com/labring/FastGPT/assets/40327819/4f08ba77-c10a-4e7f-a811-f6f6036da3ea)
知识库的搜索测试，也遇到同样问题

**Comment by lx3689589** [comment]
同样的操作遇到这个报错，请问解决了么
