### ISSUE TITLE
问题分类选择本地chatglm3模型后，提示还是gpt的模型

### ISSUE THREAD

**Issue by raynordlk** [labring/FastGPT#896]
使用高级编排问题分类选择本地chatglm3模型后，提示还是gpt3的在线LLM模型

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本** 
fast gpt 4.6.8 私有部署版本

**问题描述**
1. 使用高级编排功能的问题分类
2. 选择模型为本地部署的chatglm3模型（非高级编排下可以正常使用，没有部署问题）
3. 在高级编排模式下，调试预览输入ai对话信息后，报错信息为：“gpt-3.5无可用渠道”
**复现步骤**

**预期结果**
问题分类能正常使用，并调用http模块接口

**相关截图**
![微信图片_20240227104426](https://github.com/labring/FastGPT/assets/7829338/33835be0-a684-477c-b3d3-41d9c5badaea)

**Comment by c121914yu** [comment]
有没改完的地方。补全、对话、分类……而且没有这个模型，为什么要配置进去？

**Comment by Lands-1203** [comment]
请问问题分类 能自动分配成功吗？或者说问题分类是怎么实现的？ 我输入一个问题自动给我归类吗？
