### ISSUE TITLE
star过了10000就开始变相涨价收割韭菜？

### ISSUE THREAD

**Issue by qnmlgbd250** [labring/FastGPT#897]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
老板是要给我们团队发工资是吧，非常欢迎。一个月也不到6位数，不是很多。有你的支持，免费都可以。

**Comment by yangchuansheng** [comment]
你问错地方了吧，这里是开源版本，哪来的收费，如果你问的是线上的 FastGPT，那也不应该在这里问啊
