### ISSUE TITLE
希望关键词能加链接，可点击，直接对话

### ISSUE THREAD

**Issue by loveyxh** [labring/FastGPT#904]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
1. 希望文本中含有的关键词能加上链接，用户可以点击关键词直接对话。
2. 效果通用户引导模块中，关键词链接可以点击一样。

![image](https://github.com/labring/FastGPT/assets/9854836/38b1743d-14be-46ef-be89-28e22f59a92f)

**应用场景**
1 。调用HTTP 模块，输出的文本，文本中含有关键词

**相关示例**

**Comment by c121914yu** [comment]
可以通过 [需要点击的文本]() 来实现。FastGPT markdown已经内置了，如果超链接 href 为空，会触发发送问题功能。
