### ISSUE TITLE
配置文件修改vectorModels.maxToken后,知识库检索测试界面生效,在APP中引用知识库时无效

### ISSUE THREAD

**Issue by yykui2022** [labring/FastGPT#905]
版本:4.6.6

我们的模型支持32k的token, 知识库的分块希望能足够大以保留足够多的信息,
设置vectorModels.maxToken=32000后, 在知识库检索测试页面确实引用上限是32000. 但是在app页面插入的知识库模块,里面还是3000.

**Comment by c121914yu** [comment]
你的向量模型支持32k？我还没见过32k的向量模型
