### ISSUE TITLE
我用智能微秘书对接fastGPT（fastGPT对接one-api），在微信中收到的内容出现\n\n，发现对oneapi做了二次转义

### ISSUE THREAD

**Issue by shyouhui** [labring/FastGPT#907]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**
`我用智能微秘书(wechat.aibotk.com)对接fastGPT（fastGPT对接one-api），在微信中收到的内容出现\n\n，做了二次转义。这个哪位知道怎么改哈？`

**相关截图**

![image](https://github.com/labring/FastGPT/assets/157334984/04b7f4ec-ea0d-4e6f-b6d5-70ab1b54c585)
测试one-api，收到的内容是正常的，但经过fastGPT转接后，回车符被二次转义。
![image](https://github.com/labring/FastGPT/assets/157334984/21c454c1-865b-469c-9b3b-34d1c1490fc1)

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/d9a22374-8ae8-41c5-9dcd-85e5c9972903)
怪了，我这边没有出现这个，，

**Comment by shyouhui** [comment]
> ![image](https://private-user-images.githubusercontent.com/50446880/309140874-d9a22374-8ae8-41c5-9dcd-85e5c9972903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NzE2NzAsIm5iZiI6MTcwOTQ3MTM3MCwicGF0aCI6Ii81MDQ0Njg4MC8zMDkxNDA4NzQtZDlhMjIzNzQtOGFlOC00MWM1LTlkY2QtODVlNWM5OTcyOTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDEzMDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNGE4N2VjYjhhYTA0NTkwNmEyNWE4MjRlYTBiMjRmYmEwZWU3NzczZWE2MzhkMzVmNTc3ZWU3MzJlMDdlZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1Bj5LzjIS41jeeUeC6RvKyYf9ouKA7HkXY7k6Gnwds8) 怪了，我这边没有出现这个，，

你fastGPT接的是one-api吗？

**Comment by c121914yu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/50446880/309140874-d9a22374-8ae8-41c5-9dcd-85e5c9972903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NzE2NzAsIm5iZiI6MTcwOTQ3MTM3MCwicGF0aCI6Ii81MDQ0Njg4MC8zMDkxNDA4NzQtZDlhMjIzNzQtOGFlOC00MWM1LTlkY2QtODVlNWM5OTcyOTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDEzMDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNGE4N2VjYjhhYTA0NTkwNmEyNWE4MjRlYTBiMjRmYmEwZWU3NzczZWE2MzhkMzVmNTc3ZWU3MzJlMDdlZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1Bj5LzjIS41jeeUeC6RvKyYf9ouKA7HkXY7k6Gnwds8) 怪了，我这边没有出现这个，，
> 
> 你fastGPT接的是one-api吗？

是的，但是我没接微秘书。本地测试了下。不过本地版本是4.6.9 alpha了，后面再观察下 ~

**Comment by swingsun888** [comment]
我是用chatgpt-on-wechat对接也是这种情况，最后没办法把chatgpt-on-wechat的代码加了个转义就好了。

**Comment by c121914yu** [comment]
看 oneapi 上评论 0.6.1 已经解决了。0.6 有问题，
