### ISSUE TITLE
希望通过API实现对知识库的增删改查

### ISSUE THREAD

**Issue by MasterYFeng** [labring/FastGPT#91]
例如：
获取所有知识库的名称和id；
获取知识库中数据数量和状态；
修改知识库的名称；
新增和删除知识库。

**Comment by JieShenAI** [comment]
我也想要这样的功能。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I also want such functionality.
