### ISSUE TITLE
本地源代码+docker数据库部署，经验分享，希望文档更改进一下

### ISSUE THREAD

**Issue by qqqzhch** [labring/FastGPT#910]
环境 win+wsl 2 +docker
在 win上把docker和wsl 2 安装
开始按照https://doc.fastgpt.in/docs/development/intro/ 进行部署

在部署数据库的时候，发现部署完后，localhot:3000已经可以开始访问了
https://doc.fastgpt.in/docs/development/docker/
原来部署数据库的文档里面偷偷的也包含了app的docker
这个时候我们的想法就是使用docker 里面的数据库 和本地跑next.js源代码

## 注意事项1 
rs.initiate({
  _id: "rs0",
  members: [
    { _id: 0, host: "mongo:27017" }
  ]
})
如果需要从源代码访问docker里面mongo 需要改为
rs.initiate({
  _id: "rs0",
  members: [
    { _id: 0, host: "0.0.0.0:27017" }
  ]
})
## 注意事项2 mongo的链接字符串
 mongo 数据库连接参数
MONGODB_URI=mongodb://myname:mypassword@0.0.0.0:27017/fastgpt?authSource=admin
## 注意事项3 PG 数据库连接参数
PG 数据库连接参数
PG_URL=postgresql://username:password@0.0.0.0:5432/postgres

**Comment by koulas** [comment]
我想问下，如果是部署在公有云服务器的，那ip地址不是写0.0.0.0吧，要改成什么呢？

**Comment by ringwraith** [comment]
同样的需求，但我是改成了本机的ip地址

**Comment by c121914yu** [comment]
是按部署来写的文档，不是开发。部署环境通常不会允许外网访问数据库。需要本地开发的话把网络容器名改成可访问ip即可。
