### ISSUE TITLE
max token 有的时候为负数

### ISSUE THREAD

**Issue by shuaizai88** [labring/FastGPT#911]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ V] 私有部署版本

**问题描述**
用的m3e+qwen1.5 14b 配置如下，token都是1024
![23856c2acf1b6142267b2c539e3c77c](https://github.com/labring/FastGPT/assets/32242038/93d5e521-4de5-4f74-b84f-22debbd74029)
给m3e 添加了一些知识，搜索测试正常
![image](https://github.com/labring/FastGPT/assets/32242038/569fbac6-a858-4b5d-8bf4-51d9ff1c7609)
使用机器人问问题的时候，m3e 的参数正常，但是给qwen1.5 发送请求的时候max_token给了一个负数
![be1e44fea5fa170726438c5e5788b39](https://github.com/labring/FastGPT/assets/32242038/e140cbe7-4767-4e6d-9bd1-8ccf8c7c4495)
导致报错
**复现步骤**

**预期结果**
正常传max token
**相关截图**

**Comment by c121914yu** [comment]
1. 引用 token 必须小于最大 token，至少少 2 个块的长度，避免引用内容太长。
2.你这模型只有 1024 长度，，用不了知识库
