### ISSUE TITLE
API对话接口中全局变量variables参数中uid怎么

### ISSUE THREAD

**Issue by Selivia** [labring/FastGPT#913]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
我在高级编排中添加了一个全局变量，变量名为testv,变量key为input
请问如何在api中去传递这个变量，我看了官方文档只写了一个uid和name，这两个参数具体怎么传？
uid:testv和uid:input我都试了一遍，都失败了，求助
**复现步骤**

**预期结果**

**相关截图**
<img width="348" alt="image" src="https://github.com/labring/FastGPT/assets/17275076/0c73e629-ab37-4701-a852-77060885d25e">
<img width="701" alt="image" src="https://github.com/labring/FastGPT/assets/17275076/5b2bda12-9c88-41d3-a850-4efad33d9f96">

**Comment by c121914yu** [comment]
啊这，，key 要对应 json 的 key 呀。。

**Comment by c121914yu** [comment]
你就直接
input: 你的内容
