### ISSUE TITLE
Qwen-VL模型调用失败

### ISSUE THREAD

**Issue by warlockedward** [labring/FastGPT#914]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ X ] 私有部署版本

**问题描述**
使用Qwen-VL模型，通过one-api做代理接入到FastGPT中，在进行大模型对话的时候总是出现错误

**复现步骤**

**预期结果**

**相关截图**
<img width="1578" alt="image" src="https://github.com/labring/FastGPT/assets/18415055/7d6e4ee4-84f4-4f9a-86e6-06895045185c">
<img width="1744" alt="image" src="https://github.com/labring/FastGPT/assets/18415055/299938c1-868f-4cfa-aa3c-aba971f97ed7">

**Comment by c121914yu** [comment]
没研究过，先测测能oneapi能不能用吧。oneapi不行，fastgpt也不行。

**Comment by c121914yu** [comment]
> > 没研究过，先测测能oneapi能不能用吧。oneapi不行，fastgpt也不行。
> 
> oneapi调用是没有问题，一到fastgpt就不行。不过我测试了开源的CogVLM却又可以，我怀疑是封装格式的问题

log 看看接口入参。

**Comment by stevensy123** [comment]
> > > 没研究过，先测测能oneapi能不能用吧。oneapi不行，fastgpt也不行。
> > 
> > 
> > oneapi调用是没有问题，一到fastgpt就不行。不过我测试了开源的CogVLM却又可以，我怀疑是封装格式的问题
> 
> log 看看接口入参。

同样的问题，oneapi可以测试，但是fastgpt出现bad_response_status_code bad response status code 422 (request id: 2024042812101495473201255555802)

**Comment by stevensy123** [comment]
> > 没研究过，先测测能oneapi能不能用吧。oneapi不行，fastgpt也不行。
> 
> oneapi调用是没有问题，一到fastgpt就不行。不过我测试了开源的CogVLM却又可以，我怀疑是封装格式的问题

解决了吗，朋友

**Comment by swallowMuzi** [comment]
> > > 没研究过，先测测能oneapi能不能用吧。oneapi不行，fastgpt也不行。
> > 
> > 
> > oneapi调用是没有问题，一到fastgpt就不行。不过我测试了开源的CogVLM却又可以，我怀疑是封装格式的问题
> 
> 解决了吗，朋友
请问下你解决了吗，我现在也想接qwen_vl

**Comment by xavi713** [comment]
通过one-api的吗？入参，请求地址都要更新
