### ISSUE TITLE
insufficient_user_quota user quota is not enough

### ISSUE THREAD

**Issue by Hapluckyy** [labring/FastGPT#916]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**
长时间调用后，出现
```
insufficient_user_quota user quota is not enough
```
报错
请问要修改哪个文件，更改root用户默认的api调用额度？
是否可以实现在管理页面中对多用户进行实时修改？

**相关截图**
![image](https://github.com/labring/FastGPT/assets/82488352/e189d204-f29c-4e17-8b4a-25c871ddf39f)
![image](https://github.com/labring/FastGPT/assets/82488352/6d78efa5-ed4d-48d7-8a2d-e8e1c586e9fc)

**Comment by Hapluckyy** [comment]
如果在部署模型时，没有对模型的调用花销进行设置，都是0元，为什么还会有这个报错呢？请教一下如何进行多账户的api金额管理问题，谢谢
![image](https://github.com/labring/FastGPT/assets/82488352/da3b0639-361b-40a2-aab2-462b06e5e0cc)

**Comment by c121914yu** [comment]
文档 faq 里有
