### ISSUE TITLE
可否增加一个人工客服入口

### ISSUE THREAD

**Issue by wbext** [labring/FastGPT#919]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
目前这个训练机器人的平台只提供聊天机器人的api供客户访问，但聊天机器人的能力毕竟有限，只能分担部分压力。有很多问题需要人工客服亲自解决，如果能在与机器人聊天界面内置一个转人工客服的入口更好了。
**复现步骤**

**预期结果**

**相关截图**
![e3cb82564c7a37caf45cca6b5fb51f8](https://github.com/labring/FastGPT/assets/134917942/1d0426d4-b098-4e00-a4b0-67504ced9504)

**Comment by c121914yu** [comment]
可以通过超链接实现跳转
