### ISSUE TITLE
超过200W的知识库数据量检索缓慢

### ISSUE THREAD

**Issue by bysx111** [labring/FastGPT#920]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
超过200W数据的知识库检索，单次需要2-3分钟，这个有没好的优化方法？大神指导一下
**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
看pgvector和pg的参数文档，自己调整参数或索引。
