### ISSUE TITLE
希望http文本加工等模块的 字段编辑 增加 默认值设置

### ISSUE THREAD

**Issue by 0-StarRing-0** [labring/FastGPT#922]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
http、文本加工等模块的字段编辑功能，增加一个默认值设置  
当http返回结果中没有该字段，或者文本加工里字段输入为空时，用默认值代替

**应用场景**
http返回结果不确定，可能有字段不存在时，让编排可以顺利运行

**相关示例**
- <img width="408" alt="d53a685cad75341efd89eed89d0dff6" src="https://github.com/labring/FastGPT/assets/38901803/cea6a136-b4d3-4a88-a379-f4037f561aba">
- 上图中，data.records[1] 字段不存在，导致下游无法运行，最终输出为空
- <img width="354" alt="9b665ae593e47d504600dccd8aa176a" src="https://github.com/labring/FastGPT/assets/38901803/e02cd068-5891-41e6-bbf5-4d6e23f113b3">
- 如果把 data.records[1]  的连接去掉，下游可以运行，但 {{records1}} 因为没有默认值，直接输出了变量名
- 添加默认值功能，应可解决上述问题

**Comment by c121914yu** [comment]
看错了，这个没解决。。只是提取模块加了默认值。
