### ISSUE TITLE
问题分类模块

### ISSUE THREAD

**Issue by lcl2257970753** [labring/FastGPT#923]
**例行检查**
问题分类模块分不了类，本地搭建一直分到最后一个问题，不知道是什么原因
[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by lcl2257970753** [comment]
有没有人解决或者遇到过

**Comment by c121914yu** [comment]
日志会有错误提示，文档 faq 也有说明。你用的不是 gpt，但是又用工具模式。

**Comment by xhlj2023** [comment]
> 日志会有错误提示，文档 faq 也有说明。你用的不是 gpt，但是又用工具模式。

请问错误提示的日志去哪里看？

**Comment by Stefankeep** [comment]
我这边 使用 chatGLM3 没有 报错 但是 仍然 只会分类到 第一个里面去

```json
 {
      "model": "GLM3",
      "name": "智谱清言",
      "avatar": "/imgs/model/qwen.svg",
      "maxContext": 32000,
      "maxResponse": 4000,
      "quoteMaxToken": 13000,
      "maxTemperature": 1.2,
      "charsPointsPrice": 0,
      "censor": false,
      "vision": false,
      "datasetProcess": true,
      "usedInClassify": true,
      "usedInExtractFields": true,
      "usedInToolCall": false,
      "usedInQueryExtension": true,
      "toolChoice": true,
      "functionCall": false,
      "customCQPrompt": "",
      "customExtractPrompt": "",
      "defaultSystemChatPrompt": "",
      "defaultConfig":{}
    }
```
