### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by ws02589111** [labring/FastGPT#924]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X] 私有部署版本

**问题描述**
更新了最新的代码后，登陆界面无限loading，浏览器控制台和服务均无报错
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/10301545/ad9cd9a1-ba95-4c82-a829-540bbbb7d50e)

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/921 fix
