### ISSUE TITLE
聊天记录的总数量不正确

### ISSUE THREAD

**Issue by ws02589111** [labring/FastGPT#925]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ X] 私有部署版本

**问题描述**
聊天窗口的顶部，显示了对话历史记录的数量，记录数量超过30条后，就固定显示为30条
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/10301545/00dae920-5972-49e7-b6db-22a4952cf9ee)

**Comment by c121914yu** [comment]
默认设置30条上限
