### ISSUE TITLE
如何替換掉url後面的 chat/completion ??

### ISSUE THREAD

**Issue by Eddy-Powers** [labring/FastGPT#926]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
用oneAPI接入gemma，當在fastgpt對話後，送出時在網址後面會多加 caht/completion，但因為gemma在網址後面是 api/chat
導致錯誤。請問如何解決??

**复现步骤**

**预期结果**

**相关截图**
![1709595026257](https://github.com/labring/FastGPT/assets/34379571/6b3e6d93-f5c8-47d3-821d-fd683c4bd91f)
![Uploading 1709594932284.png…]()

**Comment by c121914yu** [comment]
自己改 gemma 的接口，适配 gpt 格式。
