### ISSUE TITLE
Why is it so expensive to deploy only one application, fastgpt?

### ISSUE THREAD

**Issue by 17607683785** [labring/FastGPT#927]
### What is the problem this feature will solve?

<img width="211" alt="Snipaste_2024-02-02_17-43-03" src="https://github.com/labring/sealos/assets/107823857/a45b51cd-366a-4958-bce7-5b805cf81709">

**Comment by c121914yu** [comment]
> ### What alternatives have you considered?

ok

**Comment by c121914yu** [comment]
> 我可能知道了，是因为卸载应用的时候，对应的数据库没有删除导致的

ok
