### ISSUE TITLE
通过知识库进行问答出现SyntaxError

### ISSUE THREAD

**Issue by xiaoToby** [labring/FastGPT#929]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如图所示：
![image](https://github.com/labring/FastGPT/assets/40045458/7c10c55e-2887-4612-9247-a686ad775aa0)
该怎么去定位出问题的文档

**Comment by c121914yu** [comment]
看报错日志

**Comment by xiaoToby** [comment]
> 看报错日志

是要到fastgpt容器内看报错日志吗，上面的截图我是docker logs看到的

**Comment by xiaoToby** [comment]
很困惑的是token 作 ,我没有地方用到了 “作” 这个中文

**Comment by c121914yu** [comment]
json解析报错。大概率是你用了分类、提取或者补全啥的，模型没有返回json格式。

**Comment by xiaoToby** [comment]
文件处理模型：chatglm2-16bit
索引模型： text2vec-large-chinese
重排模型：rerank

是用错了哪个模型吗

**Comment by c121914yu** [comment]
> 文件处理模型：chatglm2-16bit 索引模型： text2vec-large-chinese 重排模型：rerank
> 
> 是用错了哪个模型吗

glm2没有tool模式。

**Comment by xiaoToby** [comment]
那文件处理模型可以用[chinese-llama-alpaca-2] 模型吗
该怎么判断模型是否有tool模式，之前都没有意识到这方面问题
@c121914yu

**Comment by DAQ121** [comment]
我也想知道，哪些模型有tool模式
