### ISSUE TITLE
本地部署，使用chatglm3-6b的权重，第二轮对话会报错

### ISSUE THREAD

**Issue by 13874360430** [labring/FastGPT#930]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X] 我已确认目前没有类似 issue
- [X] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [X] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [X] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X ] 私有部署版本

**问题描述**
在服务器上本地部署，使用chatglm2-6b的权重模型，可以正常使用fastgpt。但是用chatglm3-6b的权重模型，在fastgpt上只进行了一轮对话，接着第二次再问问题，就显示“对话接口报错或返回为空”
**复现步骤**
1、启动chatglm3-6b的 openai_api.py
2、docker 部署 one api，分别连接chatglm3-6b 和 fastgpt
3、修改config.json的语言模型为oneapi中的chatglm3-6b
4、在fastgpt中选择chatglm-6b语言模型
5、进行过两轮对话，在第二轮对话的时候会报错

**预期结果**
使用chatglm-6b的模型，可以进行多轮对话

**相关截图**
![微信截图_20240304214155](https://github.com/labring/FastGPT/assets/45893805/17350053-d32e-4f04-a56b-c433550e5f88)
![微信截图_20240305140945](https://github.com/labring/FastGPT/assets/45893805/9bc8f197-cffe-47fa-9cfc-2ca7a0b8007d)
![微信截图_20240305141013](https://github.com/labring/FastGPT/assets/45893805/f0f85b8b-ed1f-4b43-8d66-804edac5cae6)
![微信截图_20240305141013](https://github.com/labring/FastGPT/assets/45893805/b47407ba-78e3-4778-98f4-7d9a60088297)

**Comment by c121914yu** [comment]
debug 看看参数

**Comment by nongmo677** [comment]
官方提供的chatglm3格式化类似于OpenAI的API是api_server.py，直接套用chatglm2的会存在风险，`/v1/chat/completions`的代码都不一样了
