### ISSUE TITLE
本地部署的m3e-large-api不可用

### ISSUE THREAD

**Issue by Adsryen** [labring/FastGPT#931]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ √] 我已确认目前没有类似 issue
- [√ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ √] 私有部署版本

**问题描述**
正常部署了stawky/m3e-large-api:latest的镜像，
正常部署了one-api的镜像，

并且通过以下两种方式测试，都返回了向量
curl  http://192.168.3.253:3000/v1/embeddings     oneapi的key
curl  http://192.168.3.253:6008/v1/embeddings     环境变量的key

在config写的：
{
            "model": "m3e",
            "name": "M3E（测试）",
            "price": 0.1,
            "defaultToken": 500,
            "maxToken": 1800
        }

然后在one-api写的base url是（都试了）：
http://192.168.3.253:6008
http://192.168.3.253:6008/v1/embeddings

然后fastgpt的docker logs还是报embeddings api 404
这是为何？

**Comment by c121914yu** [comment]
你 m3e 地址就不对，少了个/aoi

**Comment by JadeLuo** [comment]
curl --location --request POST 'http://192.168.3.253:6008/v1/embeddings' \
--header 'Authorization: Bearer sk-aaabbbcccdddeeefffggghhhiiijjjkkk' \
--header 'Content-Type: application/json' \
--data'{
    "model": "m3e",
    "input": [
        "laf是什么"
    ]
}'

**Comment by JadeLuo** [comment]
先有确定m3e服务正常

**Comment by JadeLuo** [comment]
curl --location --request POST 'http://192.168.3.253:3000/v1/embeddings' \
--header 'Authorization: Bearer sk-5EKTqC5wNJJ5QixKA863A29931784f05BbFf98B67c2f14Bd' \
--header 'Content-Type: application/json' \
--data-raw '{
    "model": "m3e",
    "input": [
        "laf是什么"
    ]
}'

**Comment by JadeLuo** [comment]
再测试通过one-api去调用 用3000端口调时注意换成one-api的密钥

**Comment by Mr-IT007** [comment]
> 再测试通过one-api去调用 用3000端口调时注意换成one-api的密钥

密钥问题是报401吧，404应该不是密钥问题

**Comment by Mr-IT007** [comment]
遇到相同问题

**Comment by a576378368** [comment]
我也遇到同样问题，docker 安装fastGpt config.json会挂载不成功，导致本地大语言模型和向量词模型配置不了。后来通过本地开发，更改.env.配置和config.json，然后构建镜像，后面将镜像发布到阿里云，然后再通过Docker Compose 部署就能够看到m3e和本地大语言模型选项了。另外直接使用one-api测试m3e，会返回404那个是正常的，m3e不是聊天模型，测试调用chat会失败。

**Comment by c121914yu** [comment]
> 我也遇到同样问题，docker 安装fastGpt config.json会挂载不成功，导致本地大语言模型和向量词模型配置不了。后来通过本地开发，更改.env.配置和config.json，然后构建镜像，后面将镜像发布到阿里云，然后再通过Docker Compose 部署就能够看到m3e和本地大语言模型选项了。另外直接使用one-api测试m3e，会返回404那个是正常的，m3e不是聊天模型，测试调用chat会失败。

配置文件没写对

**Comment by xangelwing** [comment]
> curl --location --request POST 'http://192.168.3.253:6008/v1/embeddings' --header 'Authorization: Bearer sk-aaabbbcccdddeeefffggghhhiiijjjkkk' --header 'Content-Type: application/json' --data'{ "model": "m3e", "input": [ "laf是什么" ] }'

遇到类似404问题，按这个方式调通了。

**Comment by mingmars** [comment]
终结：这是registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest 模型不支持GPU的问题。直接去拉国外的镜像就好
stawky/m3e-large-api:latest  用这个就可以使用gpu

**Comment by mingmars** [comment]
终结：这是registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest 模型不支持GPU的问题。直接去拉国外的镜像就好
stawky/m3e-large-api:latest  用这个就可以使用gpu
