### ISSUE TITLE
v.4.6.8无法添加知识库

### ISSUE THREAD

**Issue by zhouping988** [labring/FastGPT#932]
v.4.6.8无法添加知识库 报如下错误：换ie 谷歌、火狐都不行，部分系统不兼容，导致页面崩溃。如果可以，请联系作者，反情下具体操作和页面。大部分是 苹果 的 saian 浏览器导致，可以尝试更换 chromne 浏览器，或者是因为开了中文翻泽导致，请检查并关闭中文翻译。

![7da050b644453063f8af4ce329f646c](https://github.com/labring/FastGPT/assets/53424753/e0412d32-c1a3-41b4-bbe2-b32a92da490a)

**Comment by tom6q6** [comment]
我也有同样问题，你解决了吗

**Comment by zhouping988** [comment]
> 我也有同样问题，你解决了吗

没有，换到4.6.7的docker镜像也是有同样的问题

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/875
重复。配置文件不对。f12 控制台会有空指针错误提示
