### ISSUE TITLE
更新到v4.6.8后AI回答时间变长了

### ISSUE THREAD

**Issue by wbext** [labring/FastGPT#935]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**

**复现步骤**

**预期结果**

**相关截图**

**Comment by wbext** [comment]
知识库检索时间花了130多秒，其他模块正常且使用模型都是3.5-16k。问题补全所用模型用回3.5-16k后知识库检索时间回归到3秒左右，但是有时候还会出现检索知识库超100秒的情况。

**Comment by c121914yu** [comment]
和模型没啥关系，数据库性能不够~

**Comment by c121914yu** [comment]
https://github.com/pgvector/pgvector 自己学习pg相关参数进行调整。尤其是hnsw索引和内存交换。
