### ISSUE TITLE
ollama api

### ISSUE THREAD

**Issue by kinbod** [labring/FastGPT#938]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

**应用场景**
可以支持ollama吗

**相关示例**

**Comment by taurusduan** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 features
> * [x]  我已确认我已升级到最新版本
> * [x]  我已完整查看过项目 README，已确定现有版本无法满足需求
> * [x]  我理解并愿意跟进此 features，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**
> 
> **功能描述**
> 
> **应用场景** 可以支持ollama吗
> 
> **相关示例**

早就支持了，你自己可以部署看看，但是我这边测试下来配合数据库速度很慢，感觉性价比不高。

**Comment by kinbod** [comment]
> > **例行检查**
> > 
> > * [x]   我已确认目前没有类似 features
> > * [x]   我已确认我已升级到最新版本
> > * [x]   我已完整查看过项目 README，已确定现有版本无法满足需求
> > * [x]   我理解并愿意跟进此 features，协助测试和提供反馈
> > * [x]   我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**
> > 
> > **功能描述**
> > **应用场景** 可以支持ollama吗
> > **相关示例**
> 
> 早就支持了，你自己可以部署看看，但是我这边测试下来配合数据库速度很慢，感觉性价比不高。

我是说在里面怎么配置呢？？？没有找到配置ollama的地方

**Comment by c121914yu** [comment]
oneapi支持，和fastgpt没关系
