### ISSUE TITLE
支持直接通过 Iframe 执行 Javascript 代码的模块

### ISSUE THREAD

**Issue by sheng-di** [labring/FastGPT#939]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
目前只有 HTTP 调用方式，还有一些其他的简单的功能。可以考虑直接新建一个 iframe 作为 Javascript 的执行环境，这样就可以在不使用服务器的情况下，处理更多复杂的场景。
**应用场景**
模块：Javascript 模块（浏览器 Iframe）
**相关示例**

**Comment by c121914yu** [comment]
app是跑在服务器的，没有iframe~
可以考虑用serverless服务，不需要部署。。后面会直接把laf融合进去。

**Comment by sheng-di** [comment]
原来如此。。
也许可以通过 vm2 单独执行某个 Script，一个精简的子模块；集成 laf 也挺好，工作量可能大一些。

**Comment by c121914yu** [comment]
> 一些

单独做一个 Runtime 缺点挺多：
1. 语法提示不全。不像laf已经有完整的web编辑器。
2. 无法导第三方包。
3. 需要注意内存泄露。

集成的主要工作是需要给定义一套类似 openapi 的协议，可以直接捕获 laf 的代码结构，生成一个类似HTTP模块的出入参数。

**Comment by sheng-di** [comment]
> > 一些
> 
> 单独做一个 Runtime 缺点挺多：
> 
> 1. 语法提示不全。不像laf已经有完整的web编辑器。
> 2. 无法导第三方包。
> 3. 需要注意内存泄露。
> 
> 集成的主要工作是需要给定义一套类似 openapi 的规则，可以直接捕获 laf 的代码结构，生成一个类似HTTP模块的出入参数。

思路挺好的。
