### ISSUE TITLE
希望能够通过http外挂的方式支持私有的模型

### ISSUE THREAD

**Issue by cdredfox** [labring/FastGPT#94]
希望能够通过http外挂的方式支持私有的模型

1. 能够外挂向量模型，如text2vec这样的模型 
2. 能够外挂文本模型，如chatGLM-6B这样的模型

**Comment by azoth07** [comment]
支持+1

**Comment by c121914yu** [comment]
理论上，你可以写套接口，格式与 openai 对齐就可以了。这样就能直接修改 baseurl 去访问。
v4 会支持外挂，但是接口格式也要求与 openai 相同
