### ISSUE TITLE
V4.6.8 知识库搜索测试报错：Cannot read properties of null (reading '_id')

### ISSUE THREAD

**Issue by jiulititi** [labring/FastGPT#940]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√ ] 我已确认目前没有类似 issue
- [√ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [√ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [√ ] 私有部署版本

**问题描述**
知识库的搜索测试中点击测试报错：Cannot read properties of null (reading '_id')
**复现步骤**
新建手工录入知识库，输入一条问答，你是谁/我是XXX，然后在搜索测试中输入，你是谁，点击测试
**预期结果**
可正常测试使用知识库
**相关截图**
![image](https://github.com/labring/FastGPT/assets/49226420/55140da9-f9a4-4918-a9ee-2b109cf4e298)

**Comment by c121914yu** [comment]
4.6.9已解决。可以执行4.6.9的初始化脚本进行数据清洗。
有过训练中删除数据的操作，导致有数据无集合。
