### ISSUE TITLE
能否将第三方的使用功能嵌入到fastgpt？

### ISSUE THREAD

**Issue by wbext** [labring/FastGPT#941]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
我想问问fastgpt是否允许将第三方的使用功能(比如udesk的人工客服功能)嵌入到fastgpt，如果可以是在哪个文件上嵌入？超链接跳转页面对用户体验不是很好。
**应用场景**
![e3cb82564c7a37caf45cca6b5fb51f8](https://github.com/labring/FastGPT/assets/134917942/d2c16058-9a7a-4e2b-9d21-231d5df1871b)

**相关示例**
我目前使用的是udesk的客服机器人，在聊天界面有人工客服的小窗口，点进去能直接在同一个界面转人工不用链接跳转界面。

**Comment by c121914yu** [comment]
不想跳转可以自己二开。
