### ISSUE TITLE
无法获取文本内容提取结果

### ISSUE THREAD

**Issue by MoonBottle** [labring/FastGPT#942]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本 4.6.8 版本

**问题描述**
不能正确获取到想提取的目标字段
![image](https://github.com/labring/FastGPT/assets/12904505/99122cf7-d077-4bb0-9ea3-eb8699c19b2b)
提取结果为空
![image](https://github.com/labring/FastGPT/assets/12904505/d62119ea-d7e5-4005-9843-1fa6b987702b)

**复现步骤**
见问题描述

**预期结果**
能正确获取到提取结果

**相关截图**
见问题描述

**Comment by c121914yu** [comment]
看文档FAQ，不是tool模型关掉tool模式。

**Comment by yangkl-ui** [comment]
> 看文档FAQ，不是tool模型关掉tool模式。
toolChoice和functionCall都关了，customExtractPrompt自定义提示词也配了，还是提取不到任何东西

**Comment by yangkl-ui** [comment]
> 看文档FAQ，不是tool模型关掉tool模式。

toolChoice和functionCall都关了，customExtractPrompt自定义提示词也配了，还是提取不到任何东西
