### ISSUE TITLE
配置了正确的OpenAI key，但是fastgpt一直返回401

### ISSUE THREAD

**Issue by YTaoger** [labring/FastGPT#943]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本(在docker上部署的)

**问题描述**
在docker-compose.yml中正确配置了`OPENAI_BASE_URL` 以及 `CHAT_API_KEY` 
/api/v1/chat/completions接口调用，fastgpt控制台会报401的error，前端页面会提示`account_deactivated The OpenAI account associated with this API key has been deactivated. If you are the developer for this OpenAI app, please check your email for more information. If you are seeing this error while using another app or site, please reach out to them for more help.` 
<img width="620" alt="image" src="https://github.com/labring/FastGPT/assets/35984856/fec30e94-08ea-480d-8fe4-02aaa1fd6c9b">

**复现步骤**
聊天窗口，随便发一条消息，就会提示关于Openai Key的报错信息

**预期结果**
能够正常使用对接openai

**相关截图**
在curl中测试OpenAI key 是没有问题的，可以得到正确的响应
<img width="865" alt="image" src="https://github.com/labring/FastGPT/assets/35984856/2ae23093-6c1a-4eec-873d-0c1c0d6f88ff">
在fastgpt中，就会报401
<img width="1259" alt="image" src="https://github.com/labring/FastGPT/assets/35984856/4b540f39-aeaa-439d-8048-b603e314da1a">

**Comment by c121914yu** [comment]
中文翻译下就知道了

**Comment by YTaoger** [comment]
> 中文翻译下就知道了

我想表达的是，我的openai key是没有任何问题的，但是在fastgpt中就提示与此API密钥关联的OpenAI帐户被停用了，控制台日志也显示的是401，但是我通过curl测试了openai官方的接口，确认key是没有任何问题的

**Comment by c121914yu** [comment]
> > 中文翻译下就知道了
> 
> 我想表达的是，我的openai key是没有任何问题的，但是在fastgpt中就提示与此API密钥关联的OpenAI帐户被停用了，控制台日志也显示的是401，但是我通过curl测试了openai官方的接口，确认key是没有任何问题的

你说你没问题，人家说你有问题~ 那不是有问题

**Comment by YTaoger** [comment]
> > > 中文翻译下就知道了
> > 
> > 
> > 我想表达的是，我的openai key是没有任何问题的，但是在fastgpt中就提示与此API密钥关联的OpenAI帐户被停用了，控制台日志也显示的是401，但是我通过curl测试了openai官方的接口，确认key是没有任何问题的
> 
> 你说你没问题，人家说你有问题~ 那不是有问题

那为什么我通过curl的方式，直接对接api.openai.com，就可以正常使用，但是在fastgpt中，就会被提示账号被停用了，对这一块还是有点疑问

**Comment by c121914yu** [comment]
> **复现步骤** 聊天窗口，随便发一条消息，就会提示关于Openai Key的报错信息
> 
> **预期结果** 能够正常使用对接openai
> 
> **相关截图**

那不就只有一种可能，你填错key了~

**Comment by YTaoger** [comment]
> > **复现步骤** 聊天窗口，随便发一条消息，就会提示关于Openai Key的报错信息
> > **预期结果** 能够正常使用对接openai
> > **相关截图**
> 
> 那不就只有一种可能，你填错key了~

key是实打实的没填错，我对照过很多次了，就是感觉很离谱，所以才提的issues

**Comment by c121914yu** [comment]
> > > **复现步骤** 聊天窗口，随便发一条消息，就会提示关于Openai Key的报错信息
> > > **预期结果** 能够正常使用对接openai
> > > **相关截图**
> > 
> > 
> > 那不就只有一种可能，你填错key了~
> 
> key是实打实的没填错，我对照过很多次了，就是感觉很离谱，所以才提的issues

截图看看容器里的env

**Comment by YTaoger** [comment]
> > > > **复现步骤** 聊天窗口，随便发一条消息，就会提示关于Openai Key的报错信息
> > > > **预期结果** 能够正常使用对接openai
> > > > **相关截图**
> > > 
> > > 
> > > 那不就只有一种可能，你填错key了~
> > 
> > 
> > key是实打实的没填错，我对照过很多次了，就是感觉很离谱，所以才提的issues
> 
> 截图看看容器里的env

这个key都是我重新生成的一个key，反复测试过，就是在fastgpt中就会报401，openai官方的接口就是正常的可用的
<img width="862" alt="image" src="https://github.com/labring/FastGPT/assets/35984856/d8d58a0e-58dd-4b1e-bffe-6d94db9d538a">

**Comment by c121914yu** [comment]
> > > > > **复现步骤** 聊天窗口，随便发一条消息，就会提示关于Openai Key的报错信息
> > > > > **预期结果** 能够正常使用对接openai
> > > > > **相关截图**
> > > > 
> > > > 
> > > > 那不就只有一种可能，你填错key了~
> > > 
> > > 
> > > key是实打实的没填错，我对照过很多次了，就是感觉很离谱，所以才提的issues
> > 
> > 
> > 截图看看容器里的env
> 
> 这个key都是我重新生成的一个key，反复测试过，就是在fastgpt中就会报401，openai官方的接口就是正常的可用的 <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/35984856/310724372-d8d58a0e-58dd-4b1e-bffe-6d94db9d538a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Nzg0MDEsIm5iZiI6MTcwOTc3ODEwMSwicGF0aCI6Ii8zNTk4NDg1Ni8zMTA3MjQzNzItZDhkNThhMGUtNThkZC00YjFlLWJmZmUtNmQ5NGRiOWQ1MzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAyMjE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMGQ2OTdlMjJkNWNkODNlOGZkYzhhZGFkMTZmNjcwNDFlOGZhYWUwN2MzYTEwMzA1OWI1N2ExYzg4NDAzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h9Edq4fbvX0TyQdGsDJUDb4Bj2EO2F7XHObWD__Szdw">

我指的是容器里，不是配置文件。。可能你都没重启~

**Comment by YTaoger** [comment]
> > > > > > **复现步骤** 聊天窗口，随便发一条消息，就会提示关于Openai Key的报错信息
> > > > > > **预期结果** 能够正常使用对接openai
> > > > > > **相关截图**
> > > > > 
> > > > > 
> > > > > 那不就只有一种可能，你填错key了~
> > > > 
> > > > 
> > > > key是实打实的没填错，我对照过很多次了，就是感觉很离谱，所以才提的issues
> > > 
> > > 
> > > 截图看看容器里的env
> > 
> > 
> > 这个key都是我重新生成的一个key，反复测试过，就是在fastgpt中就会报401，openai官方的接口就是正常的可用的 <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/35984856/310724372-d8d58a0e-58dd-4b1e-bffe-6d94db9d538a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Nzg0MDEsIm5iZiI6MTcwOTc3ODEwMSwicGF0aCI6Ii8zNTk4NDg1Ni8zMTA3MjQzNzItZDhkNThhMGUtNThkZC00YjFlLWJmZmUtNmQ5NGRiOWQ1MzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAyMjE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMGQ2OTdlMjJkNWNkODNlOGZkYzhhZGFkMTZmNjcwNDFlOGZhYWUwN2MzYTEwMzA1OWI1N2ExYzg4NDAzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h9Edq4fbvX0TyQdGsDJUDb4Bj2EO2F7XHObWD__Szdw">
> 
> 我指的是容器里，不是配置文件。。可能你都没重启~

哦哦，懂了，Thank you !

**Comment by YTaoger** [comment]
这个问题我解决了，最终的原因还是因为容器中的环境变量没有替换，是我自己对docker不太熟悉导致的😥，最后感谢 @c121914yu
