### ISSUE TITLE
版本升级之后原来的知识库都没了

### ISSUE THREAD

**Issue by bruceye777** [labring/FastGPT#944]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
升级到4.6.8之后，知识库和应用全部没了，查看fastgpt容器日志，报错：
essage: 'column "team_id" does not exist'
这要如何解决？

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
升级看升级文档说明~ 不看文档就别先乱升级~

**Comment by bruceye777** [comment]
> 升级看升级文档说明~ 不看文档就别先乱升级~

我看了升级文档，没有关于team的升级脚本，还有就是我跨越了多个版本，每个初始化脚本都要执行一次？

**Comment by c121914yu** [comment]
> > 升级看升级文档说明~ 不看文档就别先乱升级~
> 
> 我看了升级文档，没有关于team的升级脚本，还有就是我跨越了多个版本，每个初始化脚本都要执行一次？

文档不是写的很清楚了么~一个个升~
