### ISSUE TITLE
使用应用的key接入chatgpt-on-wechat后，从微信中得到的答案和应用中直接获取的答案区别太大

### ISSUE THREAD

**Issue by JerryMoon** [labring/FastGPT#945]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.6.8

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
使用知识库+gpt3.5，应用中直接对话、分享的免登录链接的对话答案都在预期内。
使用该应用的key接入chatgpt-on-wechat后，从微信中得到的答案和应用中直接获取的答案区别非常大。
1、请问一下，微信中请求过来的接口会走知识库搜索吗
2、怎么才能在对话历史中看到从微信中请求和响应的数据，方便看问题出在哪里

**复现步骤**
1、使用该应用的key接入chatgpt-on-wechat
2、在微信中提问

**预期结果**
应用中和微信中得到的答案区别不大

**相关截图**

**Comment by c121914yu** [comment]
挺大的吧，你得看cow是怎么获取历史记录的。

**Comment by Grewizard11** [comment]
我也遇到过，后来尝试调整了一下chatgpt-on-wechat里面的temperature参数，效果好了点。
我也挺好奇这两个问题
“1、请问一下，微信中请求过来的接口会走知识库搜索吗
2、怎么才能在对话历史中看到从微信中请求和响应的数据，方便看问题出在哪里”

**Comment by c121914yu** [comment]
> 我也遇到过，后来尝试调整了一下chatgpt-on-wechat里面的temperature参数，效果好了点。
> 我也挺好奇这两个问题
> “1、请问一下，微信中请求过来的接口会走知识库搜索吗
> 2、怎么才能在对话历史中看到从微信中请求和响应的数据，方便看问题出在哪里”

外部调整任何模型参数都没用。
加 chatid 的请求，fastgpt 才会记录。如果是不传，则直接以传入的完整记录为上下文。

**Comment by huluohu** [comment]
> > 我也遇到过，后来尝试调整了一下chatgpt-on-wechat里面的temperature参数，效果好了点。
> > 我也挺好奇这两个问题
> > “1、请问一下，微信中请求过来的接口会走知识库搜索吗
> > 2、怎么才能在对话历史中看到从微信中请求和响应的数据，方便看问题出在哪里”
> 
> 外部调整任何模型参数都没用。外部调用只不过是触发 fastgpt 应用，不会传递任何参数。 加 chatid 的请求，fastgpt 才会记录。如果是不传，则直接以传入的完整记录为上下文。

这个问题我之前也想过，主要是cow不支持传递参数😹

**Comment by justdavid-y** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/issues/2031

**Comment by huluohu** [comment]
> 可以参考这个配置[zhayujie/chatgpt-on-wechat#2031](https://github.com/zhayujie/chatgpt-on-wechat/issues/2031)

参考个得儿啊，两边都不愿意适配。
