### ISSUE TITLE
通过API 调用知识库接口  创建一个链接集合

### ISSUE THREAD

**Issue by zhangshuo687686** [labring/FastGPT#946]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
  问一下，通过API 调用知识库接口  “创建一个链接集合”，链接地址内容是TXT格式的自动分段，链接地址内容是PDF、Word等格式的就不能自动分段。这块参数有差异吗，还是只支持TXT的。多谢！

**复现步骤**
接口请求格式参考的接口文档，
参数
```json
{
    "trainingType": "chunk",
    "chunkSize": 512,
    "link": "https://zhixiaologo.oss-cn-hzfinance.aliyuncs.com/2024/3/26051709519553612.pdf",
    "datasetId": "65e67f4366288d2529b5da1a",
    "metadata": {
        "webPageSelector": ".docs-content"
    },
    "qaPrompt": "",
    "chunkSplitter": ""
}
```
**预期结果**
希望通过API 调用知识库接口  “创建一个链接集合” 能够自动对支持的格式文件都进行分段
**相关截图**
上传文件列表如下
![1](https://github.com/labring/FastGPT/assets/49425161/e1b54913-f502-46a9-9146-4d405c100ef0)

上传的pdf格式的文件没有自动分段，如下图
![2](https://github.com/labring/FastGPT/assets/49425161/49cab424-e352-4395-8d18-047cae2fd466)

上传的txt格式的文件没有自动分段，如下图
![3](https://github.com/labring/FastGPT/assets/49425161/29844f0c-1100-4b34-82ec-df297aca981f)

**Comment by c121914yu** [comment]
pdf没法直接链接读取

**Comment by zhangshuo687686** [comment]
在知识库页面手动的添加数据集，系统会自动分段，这个操作有相应的api接口吗

**Comment by zhangshuo687686** [comment]
@c121914yu
