### ISSUE TITLE
每次提问都会回答两遍？

### ISSUE THREAD

**Issue by xhlj2023** [labring/FastGPT#948]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
问题分类+知识库模式，提问后，所有问题都是回答两遍，这是bug还是设置问题？求教
**复现步骤**
问题分类+知识库模式，随便设置一个分类器，将 配置文件中   "toolChoice": false,
    "functionCall": false,都设置为false确保不会默认选择最后一个分类。
然后回答问题就会变成回答两遍
**预期结果**

**相关截图**
![12](https://github.com/labring/FastGPT/assets/153268230/806483ac-64bd-45f3-b6d3-b39c70a9fca4)
![18](https://github.com/labring/FastGPT/assets/153268230/da2eb980-dd64-4628-90a1-ea5b7087835a)

**Comment by c121914yu** [comment]
编排不对
