### ISSUE TITLE
知识库测试报错404

### ISSUE THREAD

**Issue by lixingxing1231** [labring/FastGPT#951]
docker本地部署wan完成后测试报错

**Comment by lixingxing1231** [comment]
![(ALONB75OW1HX38L6V@ZVG2](https://github.com/labring/FastGPT/assets/22806545/9b019597-73d5-44a5-8345-f1a389cf0934)

**Comment by c121914yu** [comment]
向量模型路径错误

**Comment by lixingxing1231** [comment]
> 向量模型路径错误

是的，我也发现了，因为我用的是通义千问的模型，没有text-embedding-ada-002模型

**Comment by Cordy27** [comment]
我在使用过程中即使不使用text-embedding-ada-002也会因为地址中没有此模型报错，请问如何解决
