### ISSUE TITLE
本地部署后发布应用遇到的问题

### ISSUE THREAD

**Issue by inrelif** [labring/FastGPT#954]
本地部署fastgpt，新建了自己的对话应用，使用发布应用功能，“免登录窗口”给的访问网址是：http://localhost:3020/chat/share?shareId=16wngsrbtpw2ph18fheuwbg1
这个网址只有本机可以访问，别的电脑并不能访问。

请问如何让本地创建的应用其他人可以访问

**Comment by lijiajun1997** [comment]
要么你有公网IP，要么做内网穿透，可以试试花生壳

**Comment by c121914yu** [comment]
> 本地部署fastgpt，新建了自己的对话应用，使用发布应用功能，“免登录窗口”给的访问网址是：http://localhost:3020/chat/share?shareId=16wngsrbtpw2ph18fheuwbg1
> 这个网址只有本机可以访问，别的电脑并不能访问。
> 
> 请问如何让本地创建的应用其他人可以访问

肯定得公网 ip
