### ISSUE TITLE
4.6.9 知识库增强模式没有任何知识导入

### ISSUE THREAD

**Issue by lijiajun1997** [labring/FastGPT#959]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本 4.6.9

**问题描述**
用知识库增强模式导入知识后没有任何效果，oneapi那边也没有收到任何QA请求，数据库里看到trainingdata在排队
**复现步骤**
1.导入文件
2.选择增强模式导入

**预期结果**
正常产生导入结果
**相关截图**
![image](https://github.com/labring/FastGPT/assets/156336589/60ff7cbd-3692-450e-a6f8-705ca80ee524)
![image](https://github.com/labring/FastGPT/assets/156336589/780a0cc6-3cb4-4213-bf3b-25f59af67748)
![image](https://github.com/labring/FastGPT/assets/156336589/3c7314cb-20e2-4e66-9b69-b19b1aee3087)

**Comment by c121914yu** [comment]
开源版不支持

**Comment by lijiajun1997** [comment]
> 开源版不支持

谢谢
