### ISSUE TITLE
本地部署fastgpt,使用rerank模型报错

### ISSUE THREAD

**Issue by HelloEveryonehh** [labring/FastGPT#961]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在知识库搜索测试的时候，选择了混合搜索+结果重排，但是docker logs fastgpt报错
```
【index】Task done
【QA】Task Done
rerank error: { message: 'invalid request: list of documents must not be empty' }
```
**复现步骤**
1.config.json配置cohere的api和api_key
2.知识库搜索测试，选择混合搜索+结果重排
3.搜索
**预期结果**
能正常使用cohere重排模型
**相关截图**
![image](https://github.com/labring/FastGPT/assets/110333012/91190832-7f1c-4656-ba2d-708fce4698a9)
![image](https://github.com/labring/FastGPT/assets/110333012/445c8cd4-10a1-4e74-a40e-ba84cb6fc9f1)

**Comment by HelloEveryonehh** [comment]
我原本以为是我的cohere的model写错了，但是，当我更改以后还是报错，报错内容和上面一致
![image](https://github.com/labring/FastGPT/assets/110333012/2720c9ca-d1e2-420d-8732-8a5a48521edf)

**Comment by zhanghx0905** [comment]
fastgpt没有对cohere的rerank api做特别对接，需要自己到rerank.ts里重写一个api调用函数

**Comment by HelloEveryonehh** [comment]
> fastgpt没有对cohere的rerank api做特别对接，需要自己到rerank.ts里重写一个api调用函数
请教一下是不是不只是单纯的改一个api调用函数呀，对于cohere的返回值result的处理那部分需要修改吗，以及对于这个document应该怎么传入呢？

**Comment by leoterry-ulrica** [comment]
> > fastgpt没有对cohere的rerank api做特别对接，需要自己到rerank.ts里重写一个api调用函数
> 
> 请教一下是不是不只是单纯的改一个api调用函数呀，对于cohere的返回值result的处理那部分需要修改吗，以及对于这个document应该怎么传入呢？

fastgpt不兼容cohere的rerank api接口

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/pull/1053 这个pr后会把格式对齐cohere，本地模型需要升级rerank镜像。
