### ISSUE TITLE
在知识库进行问答时，提问“你好”，fastgpt 返回异常。通过对话api接口调用，不通的chaId 有的能成功，有的不能成功

### ISSUE THREAD

**Issue by zhangshuo687686** [labring/FastGPT#964]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在知识库进行问答时，提问“你好”，fastgpt 返回异常。通过对话api接口调用，不通的chaId 有的能成功，有的不能成功

**复现步骤**

**预期结果**

**相关截图**

第一次请求参数：

{
    "chatId": "65e17726a816262fbba1b824",
    "appId": "65e67f8d66288d2529b5da44",
    "stream": true,
    "detail": false,
    "messages": [
        {
            "content": "你好",
            "role": "user"
        }
    ]
}

第一次请求返回结果：

2024-03-11T01:00:38.027504971Z [ERROR] 2024-03-11 01:00:38 sse error: core.chat.Chat API is error or undefined 
2024-03-11T01:00:38.027596951Z {
2024-03-11T01:00:38.027637660Z   message: 'core.chat.Chat API is error or undefined',
2024-03-11T01:00:38.027642530Z   stack: undefined
2024-03-11T01:00:38.027646680Z }

第二次请求参数 ：

{
    "chatId": "abcd",
    "appId": "65e67f8d66288d2529b5da44",
    "stream": true,
    "detail": false,
    "messages": [
        {
            "content": "你好",
            "role": "user"
        }
    ]
}

第二次请求返回结果 ： 数据正常返回

**Comment by c121914yu** [comment]
key问题

**Comment by zhangshuo687686** [comment]
使用的是同一个key，发送的两次请求

**Comment by c121914yu** [comment]
> 使用的是同一个key，发送的两次请求

所以说是你key问题呢

**Comment by zhangshuo687686** [comment]
如果是一个新对话，输入你好，就会报错。如果之前有几轮对话了，输入你好就会报 错
[ERROR]  sse error: core.chat.Chat API is error or undefined 
       message: 'core.chat.Chat API is error or undefined',
      stack: undefined

**Comment by zhangshuo687686** [comment]
是key的问题

**Comment by zhangshuo687686** [comment]
是key的问题

**Comment by Gopherlinzy** [comment]
你好，我也有同样的问题，fastgpt镜像是最新，但是输入英文是可以正常对话，输入中文就会报错：[ERROR] 2024-03-17 03:46:09 sse error: core.chat.Chat API is error or undefined
2024-03-17 11:46:09 fastgpt  | {
2024-03-17 11:46:09 fastgpt  |   message: 'core.chat.Chat API is error or undefined',
2024-03-17 11:46:09 fastgpt  |   stack: undefined
2024-03-17 11:46:09 fastgpt  | }
