### ISSUE TITLE
有没有可能针对知识库可以显式地自定义提示词？

### ISSUE THREAD

**Issue by zhoulvjun** [labring/FastGPT#965]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ x ] 我已确认目前没有类似 features
- [ x ] 我已确认我已升级到最新版本
- [ x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ x ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
针对QA生成、问题分类、问题补全/优化这些源代码中配套有提示词的诸多功能，希望能够为用户提供前端修改界面，以便根据不同知识库以及在其基础上衍生的应用做相应的提示词调整。
**应用场景**
目前的提示词是直接写在源代码中，修改和调试比较麻烦；而且，不同知识库中的知识在学科性质和材料多寡程度上各异，需要设置不同的提示词来生成、分类或补全问题，以达到更适用的程度。为了测试最终使用者的用户体验，在应用级别也会有必要进行问题补全、猜你想问等这些功能的提示词调整，比如生成不同提示词版本的应用来看最终使用者会对哪个版本提示词支持的应用更满意。
**相关示例**

**Comment by c121914yu** [comment]
会的。适当时候会设计合适的交互。
