### ISSUE TITLE
希望 HTTP 模块请求地址支持变量。

### ISSUE THREAD

**Issue by zhanghx0905** [labring/FastGPT#972]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**

希望 HTTP 模块 请求路径支持配置变量。

**相关示例**

如图所示，希望增强 HTTP 模块的自定义配置范围，能够在 HTTP 请求地址中配置变量

![企业微信截图_17101386621052](https://github.com/labring/FastGPT/assets/50790281/3f9f52bf-175e-444d-82ad-f86869b5e16c)

**Comment by zhanghx0905** [comment]
经过再次测试fastgpt已经具有此功能了

**Comment by zhaobingxu19** [comment]
![image](https://github.com/labring/FastGPT/assets/82586081/40f2d4a8-25b1-4063-8289-8f1f4d8a3598)

**Comment by zhaobingxu19** [comment]
貌似只用全局变量可以，外部参数传入不行

**Comment by zhaobingxu19** [comment]
> 经过再次测试fastgpt已经具备此功能了

请问具体怎么实现了？
我在具体使用中发现只有全局变量可以，外部参数输入的识别不出来

**Comment by monk-after-90s** [comment]
> 经过再次测试fastgpt已经具有此功能了

怎么用
