### ISSUE TITLE
免登录窗口分享设置页面，设置开关，管理员可控制引用的文件是否支持下载

### ISSUE THREAD

**Issue by JinCheng666** [labring/FastGPT#974]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
在免登录窗口分享设置页面，目前已有"是否返回引用"的功能，希望能在"是否返回引用"打开的情况下，再加载一个开关按钮"下载"，控制引用的文件是否支持下载。

**应用场景**
针对知识库的检索，尤其是重点知识，用户通常需要下载源文件，做进一步的阅读或验证。如果有这个功能，对用户会很方便。

**相关示例**
![image](https://github.com/labring/FastGPT/assets/48248936/cdabf685-fd20-4570-bb06-b802d80dc114)

**Comment by c121914yu** [comment]
后续产品设计考虑下

**Comment by RexWzh** [comment]
@JinCheng666 请问这个页面是怎么进入的，root 账号登进来没有显示这些：

<img width="943" alt="image" src="https://github.com/labring/FastGPT/assets/62223937/cbad35e8-3b4a-484f-957b-a91839b1867f">

**Comment by zhapi1780** [comment]
希望后续版本升级考虑这个功能

**Comment by William-715** [comment]
支持增加该功能
