### ISSUE TITLE
HTTP请求模块更新到V4.6.9之后，参数值填全局变量或外部传入变量无效

### ISSUE THREAD

**Issue by zhaobingxu19** [labring/FastGPT#975]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
HTTP请求模块更新到V4.6.9之后，参数值填全局变量或外部传入变量无效
**复现步骤**
![Snipaste_2024-03-11_18-00-28](https://github.com/labring/FastGPT/assets/82586081/c3cf53bb-bb1e-4563-a313-2dacc5b10032)

**预期结果**

**相关截图**

**Comment by Lands-1203** [comment]
@c121914yu 请问是否可以支持 获取分享链接上的自定义参数
