### ISSUE TITLE
[ BUG ] 判断器是不是有问题？

### ISSUE THREAD

**Issue by W4ddl3** [labring/FastGPT#979]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
![Shot 2024-03-12 at 14 36 08@2x](https://github.com/labring/FastGPT/assets/141616559/b2c99717-4481-408d-9a61-4b2fcc7a9c11)
![Shot 2024-03-12 at 14 36 34@2x](https://github.com/labring/FastGPT/assets/141616559/c9b58805-92dd-4980-9b2d-2452772915f1)

**复现步骤**
按照文档来写的
https://doc.fastai.site/docs/workflow/modules/tfswitch/

**预期结果**
输出 false

**相关截图**

**Comment by c121914yu** [comment]
多打了空格？

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/35f5e961-1ae9-440b-8356-31bd76102aea)
看着似乎没问题

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.

**Comment by lonycn** [comment]
我 的也是反的。。
