### ISSUE TITLE
新建知识库提示失败

### ISSUE THREAD

**Issue by smartbeck** [labring/FastGPT#981]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
新建知识库时（本地部署方式），页面提示如下：
部分系统不兼容，导致页面崩溃。如果可以，请联系作者，反馈下具体操作和页面。 大部分是 苹果 的 safari 浏览器导致，可以尝试更换 chrome 浏览器。或者是因为开了中文翻译导致，请检查并关闭中文翻译。
**复现步骤**
系统：
 centos7 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

docker版本：
 Version:           25.0.4
 API version:       1.44
 Go version:        go1.21.8
 Git commit:        1a576c5
 Built:             Wed Mar  6 16:33:16 2024
 OS/Arch:           linux/amd64
 Context:           default

docker compose版本：
Docker Compose version v2.24.7

chrome版本：
Chrome 已是最新版本
版本 122.0.6261.112（正式版本） （64 位）

**预期结果**

**相关截图**

**Comment by cloudtuotuo** [comment]
Pls check config.json.

**Comment by smartbeck** [comment]
> Pls check config.json.

rearrange docker-compose.yml、config.json ，and problem gone，ths！

**Comment by smartbeck** [comment]
problem gone

**Comment by xavi713** [comment]
how did you solve this issue @smartbeck

**Comment by xavi713** [comment]
use the suggest config.json fixed the issue.
