### ISSUE TITLE
4.6.9 知识库搜索配置界面bug

### ISSUE THREAD

**Issue by cloudtuotuo** [labring/FastGPT#982]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.6.9

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
在【知识库搜索配置】模块，【结果重排】勾选无效；【搜索过滤】中的【最低相关度】被隐藏

**复现步骤**
- 打开之前已配置的workflow，【知识库搜索】模块显示的搜索参数中，模式为【混合检索】、【最低相关度】0.4、【结果重排】打勾
- 点击配置后，【结果重排】未勾选，【搜索过滤】中的【最低相关度】被隐藏
- 勾选【结果重排】，点击【完成】
- 搜索参数显示同第一步
- 点击配置后，第二步问题复现

- 在配置时，选择【语义检索】+【结果重排】并保存后
- 再次进入配置界面，【结果重排】未勾选，但【搜索过滤】中的【最低相关度】显示出来了

**相关截图**
![issue](https://github.com/labring/FastGPT/assets/37918843/938d78bc-ea5f-46fc-bcce-a056abbcf4d2)

**Comment by c121914yu** [comment]
如果是新的模块呢？

**Comment by cloudtuotuo** [comment]
新的模块也这样

**Comment by leoterry-ulrica** [comment]
遇到同样的问题！！

**Comment by leoterry-ulrica** [comment]
> 如果是新的模块呢？

遇到同样的问题，确实存在。

**Comment by c121914yu** [comment]
> 新的模块也这样

ok 我关注下

**Comment by c121914yu** [comment]
UI问题，不影响实际使用，4.7正式版修复。
