### ISSUE TITLE
如何限制只能回答知识库中的问题，无关问题不准回答

### ISSUE THREAD

**Issue by uu-xixi** [labring/FastGPT#988]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ √] 我已确认目前没有类似 issue
- [ √] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ]√ 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ]√ 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ √] 私有部署版本

**问题描述**
请问一下，如何限制只能回答知识库中的相关问题，无关问题不准进行回答。 我找不到在哪里限制，我看后台记录有用户问了很多无关问题，把这个当成了ChatGpt来用o(╥﹏╥)o
**复现步骤**

**预期结果**

**相关截图**

**Comment by wbext** [comment]
我想到的办法是可以在ai对话那块的提示词里告诉ai不要回答xx无关的问题

**Comment by Jonathanfdy** [comment]
这个可以通过prompt进行限制。ai是否听话，一方面取决于你prompt的技巧，另一方面也取决于调用大模型的能力（版本）

**Comment by c121914yu** [comment]
不太可能 100%，只能无限修改提示或者看模型能力。再者就是再用一个模型检查输出结果。
