### ISSUE TITLE
使用docker部署的fastgpt服务无法使用服务器代理

### ISSUE THREAD

**Issue by AidenPerce** [labring/FastGPT#989]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [√ ] 我已确认目前没有类似 issue
- [√ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [√ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [√ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
 私有部署版本
v4.7-alpha
docker-compose版本：v2.24.6
docker版本：25.0.3

**问题描述**
使用容器部署成功后，进行问答测试，长时间无响应,日志出现异常；
环境使用了http_proxy和https_proxy代理；
fastgpt应用请求期间抓包代理端口发现没有请求， 容器内使用curl命令请求api.openai.com可以正常响应并且代理端口抓包可以抓取到；

**复现步骤**

**预期结果**
设置linux系统代理，理论上应用请求也应该会走代理才对

**相关截图**
<img width="400" alt="6233368eeb3421bf6dda1b3814ff003" src="https://github.com/labring/FastGPT/assets/129489986/701b6168-8017-40c6-92ae-f30715118969">

**Comment by c121914yu** [comment]
需要给fastgpt加环境变量：
AXIOS_PROXY_HOST=127.0.0.1
AXIOS_PROXY_PORT=7890

**Comment by c121914yu** [comment]
> 需要给fastgpt加环境变量： AXIOS_PROXY_HOST=127.0.0.1 AXIOS_PROXY_PORT=7890

**Comment by cuisws** [comment]
我也是这样，在本地是可以的，linux访问openai也是可以的，但是fastgpt不行，这两个环境变量具体加在哪里啊？请问楼主好了吗？

**Comment by AidenPerce** [comment]
> 我也是这样，在本地是可以的，linux访问openai也是可以的，但是fastgpt不行，这两个环境变量具体加在哪里啊？请问楼主好了吗？

没能解决， 后来没有在容器内用代理了， 你可以试试上边大佬提供的环境变量添加上试一下，可能因为语言原因使用的环境白能量不同

**Comment by joshzhong66** [comment]
直接加在config.json文件的fastgfpt镜像下就可以
