### ISSUE TITLE
Using the gpt-4-0125-preview model as a file processing model causes the file to remain in the index

### ISSUE THREAD

**Issue by LinhanXu3928** [labring/FastGPT#991]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本

**问题描述**
Using the gpt-4-0125-preview model as a file processing model causes the file to remain in the index
**复现步骤**
Set gpt-4 turbo by modifying the datasetProcess field to true of config.json, and then select the file processing model as gpt-4 turbo on the webpage. Import the PDF dataset, split it using Enhanced processing, and  the file keep displayed in the index. Viewing logs keeps refreshing information
[INFO] 2024-03-14 03:51:00 [QA Queue] Done 
[INFO] 2024-03-14 03:51:00 [Vector Queue] Done 
[INFO] 2024-03-14 03:52:00 [QA Queue] Done 
[INFO] 2024-03-14 03:52:00 [Vector Queue] Done 

**预期结果**

**相关截图**
![image](https://github.com/labring/FastGPT/assets/86815251/23adf834-2f2b-47b5-b0e6-a27b435ef9eb)
![image](https://github.com/labring/FastGPT/assets/86815251/e387f6a2-932e-47a4-b6c4-14d538305f0a)

**Comment by c121914yu** [comment]
无法复现

**Comment by LinhanXu3928** [comment]
> 无法复现
后来在讨论群里有群友跟我遇到了一样的问题，然后发现是只要使用知识库的增强处理（实验）就会出现这个问题，跟选择的模型无关。（本地部署）
![image](https://github.com/labring/FastGPT/assets/86815251/d76f6e83-8e99-4d7a-b083-b3ba1b5e863f)

**Comment by c121914yu** [comment]
增强处理商业版才有

**Comment by LinhanXu3928** [comment]
> 增强处理商业版才有

哦哦好的，建议增加一个提示，不然本地部署用户会以为是bug

**Comment by LinhanXu3928** [comment]
> 增强处理商业版才有

哦哦好的，建议增加一个提示，不然本地部署用户会以为是bug

**Comment by c121914yu** [comment]
> > 增强处理商业版才有
> 
> 哦哦好的，建议增加一个提示，不然本地部署用户会以为是bug

嗯，4.6.9忘记隐藏了。4.7解决了。
