### ISSUE TITLE
当使用Gemini-Pro模型进行聊天时会卡住的情况

### ISSUE THREAD

**Issue by huluohu** [labring/FastGPT#993]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
升级到v4.7后，当将LLM切换为gemini-pro时，聊天界面只会输出2～3行就会卡住不动，会持续1分多种没有任何输出。

**复现步骤**
1. fastgpt版本为v4.7
1. 将LLM切换为gemini-pro
2. 将最大回复设置为2000
3. promt中明确要求输出不低于1000字
4. 已单独用NextChat等客户端测试过oneapi，没有出现卡住的情况
5. 已在fastgpt中切换成其他模型测试，未出现卡住的情况

**预期结果**
1、能够完整回复

**相关截图**
![image](https://github.com/labring/FastGPT/assets/7138642/6e81a139-fe6d-478a-9089-0bc3f3b13045)

**Comment by lninghaha** [comment]
同样的情况，我这边是4.6.9，我另一个服务器是4.6.8，本来以为是升级的问题，但是换会旧版的服务器，发现也是这个情况。不知道是不是谷歌那边有了调整。

**Comment by huluohu** [comment]
我单独用NextChat连oneapi，gemini是正常的。

**Comment by huluohu** [comment]
今天恢复了，原因不明😂

**Comment by c121914yu** [comment]
> 今天恢复了，原因不明😂

看来是api问题了
