### ISSUE TITLE
4.6.8版本，应用中的配置->更多设置中，引用内容模板中的{{score}}变量无效，其他变量正常。

### ISSUE THREAD

**Issue by Jonathanfdy** [labring/FastGPT#996]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本

**问题描述**
4.6.8版本，应用中的配置->更多设置中，引用内容模板中的{{score}}变量无效，其他变量正常。
**复现步骤**

**预期结果**

**相关截图**

**Comment by Jonathanfdy** [comment]
这个排序功能是在让ai识别几个知识库内容时，选择最佳的结果是很有参考价值的。

**Comment by c121914yu** [comment]
已经取消了这个变量。由于有了混合检索和重排，这个得分已经不是单一的了。
让模型参考这个得分意义不大，模型本身就具有判断了，根据index也ok了。

**Comment by qurikuduo** [comment]
> 已经取消了这个变量。由于有了混合检索和重排，这个得分已经不是单一的了。 让模型参考这个得分意义不大，模型本身就具有判断了，根据index也ok了。

请问4.6.7中也取消这个变量了吗？index是怎么定义值的，有没有资料可以学习的，多谢。
