### ISSUE TITLE
本地部署无法登录root 1234

### ISSUE THREAD

**Issue by zcs110** [labring/FastGPT#997]
(http://localhost:3000/login?lastRoute=%2Fapp%2Flist)
默认账户和密码无法登陆
root 1234
Operation `users.findOne()` buffering timed out after 10000ms

**Comment by zcs110** [comment]
![Uploading 微信图片_20240314195930.png…]()

**Comment by zcs110** [comment]
![20240314195930](https://github.com/labring/FastGPT/assets/12912027/136c38f5-d55b-4f39-a9b9-00fc54aeeb9c)
MongoDB是通的

**Comment by zcs110** [comment]
怎么测试 通不通

**Comment by zcs110** [comment]
![Uploading docker20240315091530.png…]()
我看docker已经启动了啊。
新手小白

**Comment by c121914yu** [comment]
timed out就是不通

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/issues/823 相似问题。

**Comment by belugaming** [comment]
> (http://localhost:3000/login?lastRoute=%2Fapp%2Flist) 默认账户和密码无法登陆 root 1234 Operation `users.findOne()` buffering timed out after 10000ms

解决了没有？

**Comment by holywings0727** [comment]
同问 有人解答吗
